### ISSUE TITLE
telemetry API: tagOverrides not adding custom label but new metric instead

### ISSUE THREAD

**Issue by uykusuz** [istio/istio#45775]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Good day!

I'm trying to apply the example from [classifying metrics](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/). That works as expected: there's a label `request_operation` for e.g. `istio_requests_total`.

But now I want to have a custom new label. Taken the following resource from the example:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-tags
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_operation:
              value: istio_operationId
      providers:
        - name: prometheus
```

I change the line `request_operation` to `my_new_request_operation`. 

I expect there's a label `my_new_request_operation` for `istio_requests_total`.
But actually there's no new label in the metric `istio_requests_total` but a new metric `my_new_request_operation__istio_requests_total`.

Is that expected? If so, how would I add a custom label to the existing metric?

Thanks in advance!

### Version

```Text
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (64 proxies)

$ kubectl version --short
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
