### ISSUE TITLE
Metrics  source_app labels is unknown

### ISSUE THREAD

**Issue by devevarde** [istio/istio#45782]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Most of the metrics reported with source_app=unknown

### Version

```Text
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (22 proxies)


Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.14

Helm version
v3.8.0
```

### Additional Information

In all namespaces were I enabled the istio-inject the pods annotated with 

**prometheus.io/path: /stats/prometheus
prometheus.io/port: 15020
prometheus.io/scrape: true**

Other Services have their own Service monitor like the below but when I enable istio-inject on these services namespace I see the annotations replaced with the above with 15020 port and /stats/prometheus

 **prometheus.io/path: /metrics
 prometheus.io/port: “8084”
prometheus.io/scrape: “true”**

![image](https://github.com/istio/istio/assets/52662766/557ec2b7-5df1-4cf0-b7e2-3d745032257a)

More info / I have this following configurations 
```Yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-sidecars
  namespace: istio-system
  annotations:
    helm.sh/hook-weight: "2"
spec:
  selector:
    matchLabels:
      {{- range $k, $v := .Values.serviceMonitor.sidecars.labelSelector }}
        {{ $k }}: {{ $v | quote }}
      {{- end }}
  namespaceSelector:
    any: true
  endpoints:
    - targetPort: http-envoy-prom
      path: /stats/prometheus
      interval: {{ .Values.serviceMonitor.sidecars.interval | quote }}
```
The values.yaml 
```Yaml
sidecars:
    interval: 10s
    labelSelector:
      security.istio.io/tlsMode: istio
```
I add the following scrapping role as well

```Yaml
 - honor_labels: true
      job_name: kubernetes-pods-envoy-sidecar
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: drop
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
        replacement: '[$2]:$1'
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        target_label: __address__
      - action: replace
        regex: (\d+);((([0-9]+?)(\.|$)){4})
        replacement: $2:$1
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: drop
        regex: Pending|Succeeded|Failed|Completed
        source_labels:
        - __meta_kubernetes_pod_phase
```
But Still partially work Partially works !!!

![image](https://github.com/istio/istio/assets/52662766/feeab314-15af-4d7e-96e5-64805e6b8cb5)
![image](https://github.com/istio/istio/assets/52662766/aae3576d-0d6b-42b2-8c8c-7d2789453253)

![image](https://github.com/istio/istio/assets/52662766/9667eebf-e37c-4132-bb60-84a2c12da1a2)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [X] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
