### ISSUE TITLE
RequestAuthentication : outputClaimToHeaders - JWT with Polish letter claim cause strange char in header

### ISSUE THREAD

**Issue by BobakMariusz** [istio/istio#45793]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

RequestAuthentication:

```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: blah
  namespace: blah
spec:
  jwtRules:
  - issuer: https://blah/blah
    jwksUri: https://blah/blah
    outputClaimToHeaders:
    - header: x-user-name
      claim: name
```

JWT:

{
....
  "name": "Marek Ogarek-Mikołaj",
...
}

Cause:
In x-user-name header I have: Marek Ogarek-MikoÅaj  but expected: Marek Ogarek-Mikołaj
 
Is there any workaround or maybe some additional info need to be send to be properly decoded ?? 

Thanks in advance!

### Version

```Text
===============istioctl===================
istioctl version
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (12 proxies)


===============kubectl====================
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3+rke2r1", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-17T20:37:48Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3+rke2r1", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-17T20:37:48Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
