### ISSUE TITLE
Sidecar resource which has workload selector is not work

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#45806]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Some sidecar resource which has a workload selector is not work.
For example: 
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  creationTimestamp: "2023-07-04T06:41:54Z"
  generation: 1
  name: my-service
  namespace: default
  ownerReferences:
  - apiVersion: microservice.slime.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ServiceFence
    name: my-service
    uid: a292ef20-5cc5-49bd-a829-8ac7dd845530
  resourceVersion: "669691508"
  uid: 974d992f-9506-4ad7-8814-4d5f0f4dd494
spec:
  egress:
  - hosts:
    - '*/other-service.default.svc.cluster.local'
    - istio-system/*
    - mesh-operator/*
  workloadSelector:
    labels:
      component: my-service
```
Then do
```
istioctl  pc cluster my-service-xxxx
```
Some clusters is not on sidecar's egress hosts.
On our k8s clusters has two versions of istiod. One is 1.11.5 another is 1.16.5. The issue only happens on my-service when injected with version 1.16.5

### Version

```Text
$ istioctl version
client version: 1.17.3
istiod version: 1.11-dev
istiod version: 1.11-dev
istiod version: 1.16.5
istiod version: 1.16.5
data plane version: 1.11-dev (232 proxies), 1.16.5 (194 proxies), 65536.65536.65536 (2 proxies), 999.0.0 (1 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
> Some clusters is not on sidecar's egress hosts.

This is not descriptive enough to understand, can you provide more info

**Comment by Patrick0308** [comment]
```
istioctl  pc cluster my-service-xxxx
SERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                        9080      -          inbound       ORIGINAL_DST
BlackHoleCluster                                        -         -          -             STATIC
InboundPassthroughClusterIpv4                           -         -          -             ORIGINAL_DST
PassthroughCluster                                      -         -          -             ORIGINAL_DST
agent                                                   -         -          -             STATIC
global-sidecar.mesh-operator.svc.cluster.local          80        -          outbound      EDS
global-sidecar.mesh-operator.svc.cluster.local          8080      -          outbound      EDS
global-sidecar.mesh-operator.svc.cluster.local          9080      -          outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local      80        -          outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local      443       -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local     80        -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local     443       -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local     15021     -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local     15443     -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local     31400     -          outbound      EDS
istiod.istio-system.svc.cluster.local                   443       -          outbound      EDS
istiod.istio-system.svc.cluster.local                   15010     -          outbound      EDS
istiod.istio-system.svc.cluster.local                   15012     -          outbound      EDS
istiod.istio-system.svc.cluster.local                   15014     -          outbound      EDS
lazyload.mesh-operator.svc.cluster.local                80        -          outbound      EDS
lazyload.mesh-operator.svc.cluster.local                8081      -          outbound      EDS
lazyload.mesh-operator.svc.cluster.local                8082      -          outbound      EDS
lazyload.mesh-operator.svc.cluster.local                16010     -          outbound      EDS
other-service.default.svc.cluster.local                 8080     -           outbound      EDS
other-service-a.default.svc.cluster.local               8080     -           outbound      EDS
prometheus_stats                                        -         -          -             STATIC
sds-grpc                                                -         -          -             STATIC
xds-grpc                                                -         -          -             STATIC
zipkin                                                  -         -          -             STRICT_DNS
```

other-service-a.default.svc.cluster.local  should not exist cause the sidecar does not define this egress hosts.

I can't reproduce this issue on a simple 1.16.5  demo.

**Comment by howardjohn** [comment]
one thing to look into is if you have multiple sidecars selecting the same workload perhaps

**Comment by Patrick0308** [comment]
```
kubectl get sidecar -ndefault -o jsonpath='{.items[*].spec.workloadSelector.labels}' | jq
```
@howardjohn I use this command to ensure there aren't multiple sidecars selecting the same workload.

**Comment by Patrick0308** [comment]
In my cluster, It will be create a MESH_INTERNAL serviceentries when pod is created. So the pod ip is exported to both SVC and serviceentries.
I reproduce this issue on 1.16.5 demo.
I have a internal service entries, and sidecar
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ratings
spec:
  hosts:
  - ratings.test.service.entries
  endpoints:
  - address: 172.17.0.8 ## this is ratings pod's ip
  ports:
  - number: 9080
    name: http
    protocol: tcp
  location: MESH_INTERNAL
  resolution: STATIC
--- 
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: ratings
  namespace: default
spec:
  egress:
  - hosts:
    - istio-system/*
  workloadSelector:
    labels:
      app: ratings
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings
    service: ratings
  name: ratings
  namespace: default
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: ratings
  sessionAffinity: None
  type: ClusterIP
```
The ratings sidecar is ineffective on 1.16.5. I think the sidecar should be work, because there are not multi sidecar resources to select same workload. @howardjohn Any thoughts on it?
