### ISSUE TITLE
Egress Gateway not working with HTTPS

### ISSUE THREAD

**Issue by ChrisJBurns** [istio/istio#45854]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Am running the following code and when I try to exec onto a pod (with a sidecar) within the infra namespace and run `curl -sSL -o /dev/null -D - https://edition.cnn.com/politics`, I get `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to edition.cnn.com:443` . Am following https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic

The http traffic worked fine. But the https does not.
Here's my yamls
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
  namespace: istio-system
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-gateway
  namespace: istio-system
spec:
  selector:
    istio: egress-gateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
  namespace: infra
spec:
  host: istio-egress-gateway.istio-system
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: infra
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - istio-system/egress-gateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egress-gateway.istio-system
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      - istio-system/egress-gateway
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
```

Istio version: 1.18

Is worth mentioning, it works when I add the `ServiceEntry` on it's own. But I get the curl error above when adding the `Gateway`, `DestinationRule` and `VirtualService`. Also the result of `istioctl pc routes $(kubectl get pods -l istio=egress-gateway -o jsonpath='{.items[0].metadata.name}' -n istio-system).istio-system -o json` is just

```json
[
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/healthz/ready"
                        },
                        "route": {
                            "cluster": "agent"
                        }
                    }
                ]
            }
        ]
    }
]
```

### Version

```Text
$ istioctl version
client version: 1.12.2
control plane version: 1.18.0
data plane version: 1.18.0 (50 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.14-eks-c12679a", GitCommit:"05d192f0de17608d98e17761ad3cffa9a6407f2f", GitTreeState:"clean", BuildDate:"2023-05-22T23:41:27Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

## HTTP
The following are the http YAML's that work perfectly fine, it's just the https that doesn't work.
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
  namespace: istio-system
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-gateway
  namespace: istio-system
spec:
  selector:
    istio: egress-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
  namespace: infra
spec:
  host: istio-egress-gateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: infra
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-system/egress-gateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egress-gateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-system/egress-gateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 80
      weight: 100
```

Although I still can't see anything in the routes config when I run `istioctl pc routes $(kubectl get pods -l istio=egress-gateway -o jsonpath='{.items[0].metadata.name}' -n istio-system).istio-system`

```json
[
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/healthz/ready"
                        },
                        "route": {
                            "cluster": "agent"
                        }
                    }
                ]
            }
        ]
    }
]
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by nshankar13** [comment]
I ran through the HTTPS demo about two weeks back and it worked as expected for me. Did you delete the HTTP demo ServiceEntry, VirtualService, and DestinationRule before running through the HTTPS steps?

**Comment by ChrisJBurns** [comment]
I deleted the HTTP resources. We can't think of any. If I exec onto the `istio-proxy` itself and do the CURL request, there are no problems. It just seems to be that the routing or something isn't going right. When I make the request for the app container, I see a log in the `istio-proxy` sidecar saying `NC Upstream cluster not found `. There are no logs in the Egress Gateway pod at all

**Comment by ChrisJBurns** [comment]
@nshankar13  Did you use the Helm Chart to install the Egress Gateway also? Am wondering if there's something that the `istioctl` or operator does that the Helm Chart doesn't that I need to factor in

**Comment by ChrisJBurns** [comment]
I'll try the VirtualService change, but is worth mentioning that I also walked through the Sleep example in the default namespace and I ran into the same problems I'm getting now.

**Comment by nshankar13** [comment]
Ahh I see. I used istioctl, but back when I used Helm to install ingress and ran through the ingress demos, I noticed that the selector label for the gateway is different between istioctl vs Helm - not sure if that's the case for egress. 

If it is, I would try updating the selector label in the Gateway object and see if that helps.

**Comment by nshankar13** [comment]
You may also find this helpful: https://github.com/istio/istio/issues/43826.

**Comment by ChrisJBurns** [comment]
It links to https://istio.io/latest/docs/setup/additional-setup/gateway/ which has an entry saying that the namespace that the gateway is deployed in must have istio injection enabled or there will be pod start failures. I've deployed my gateway into the `istio-system` namespace which hasn't got istio injection enabled and pods seem to start fine.

**Comment by nshankar13** [comment]
I meant the actual label for `istio:` on the Pod/Deployment - `ex: istio: egressgateway`. 

For context, I added this PR for the ingress demos: https://github.com/istio/istio.io/pull/12486

**Comment by ChrisJBurns** [comment]
oh, yes, i noticed that from the ingress gateway stuff I did back a couple of months ago. The gateway is `istio: egress-gateway`, which is used in all of my code samples above

**Comment by ChrisJBurns** [comment]
@nshankar13  Got this to work in the end. In all honesty, I cannot actually figure out what caused it to work. I deployed the egress gateway in it's own namespace just to see if it worked. But it still didn't seem to work. I've played and poked around with the resources and deleting some service entries that were left in some old namespaces and after enough poking around I got it to work.

The following is the manifest that worked, as you can probably tell, apart from the naming of `egress-gateway` to `egressgateway` and some namespace changes, nothing really is different. It's quite bizzare given the ingress gateway works without issue and we've specifically named it `ingress-gateway` and not `ingressgateway`. Either way, it seems there's still some under the hood stuff that Istio may do that discriminates against custom names. Because of this, we've renamed all out gateways to follow the `ingressgateway` and `egressgateway` convention.


```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cnn
  namespace: istio-egress
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: egressgateway
  namespace: istio-egress
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
  namespace: istio-egress
spec:
  host: istio-egressgateway.istio-egress.svc.cluster.local
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: istio-egress
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - istio-egress/egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-egress.svc.cluster.local
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      - istio-egress/egressgateway
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
```

Appreciate the help in debugging this bud! (y)
