### ISSUE TITLE
Adding affinity to ingress gateway k8s spec in manifest generates unwanted yaml

### ISSUE THREAD

**Issue by andysworkshop** [istio/istio#45853]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Add the following to the install (istioctl install method) manifest `spec.components.ingressGateways[name=mygateway]` block:

```yaml
k8s:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: topology.kubernetes.io/zone
            labelSelector:
              matchExpression:
                - key: istio
                  operator: In
                  values:
                    - ingressgateway
 ```

Now run a dry-run install and inspect the `Deployment` for the gateway and note the following unwanted elements:

```yaml
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: null
      requiredDuringSchedulingIgnoredDuringExecution: null
```

Note that the `k8s.affinity` section for pilot in the manifest works fine. Only the gateways generate this unwanted yaml.

### Version

```Text
client version: 1.17.3
control plane version: 1.17.3
data plane version 1.16.1 (X proxies), 1.17.3 (Y proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
