### ISSUE TITLE
custom metric source address

### ISSUE THREAD

**Issue by milank78git** [istio/istio#45888]
Hi,

I want add custom metric source.address. I have configuration 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: x-forward-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 1
```
and istio configuration add     
```
accessLogFormat: |
        {
            "accl": {
                "start_time": "%START_TIME%",
                "method": "%REQ(:METHOD)%",
                "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                "response_code": "%RESPONSE_CODE%",
                "bytes_received": "%BYTES_RECEIVED%",
                "bytes_sent": "%BYTES_SENT%",
                "duration": "%DURATION%",
                "up_svc_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
                "user_agent": "%REQ(USER-AGENT)%",
                "authority": "%REQ(:AUTHORITY)%",
                "forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
                "request_protocol": "%REQ(X-REQUEST-PROTOCOL)%",
                "access_control_allow_origin": "%REQ(ACCESS-CONTROL-ALLOW-ORIGIN)%",
                "scheme": "%REQ(:SCHEME)%",
                "resp_access_control_allow_origin": "%RESP(Access-Control-Allow-Origin)%"
            }
        }
```
In log view forwarded_for source_Ip
But if add this configuration for metrics  
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: namespace-metrics
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_COUNT
      tagOverrides:
        destination_port:
          value: "string(destination.port)"
        request_host:
          value: "request.host"
        source_address:
          value: "request.x-forwarded-for"
```
Returns no value for source_address
Please help
