### ISSUE TITLE
Configured extensionProvider for tracing activates default zipkin tracer additionally

### ISSUE THREAD

**Issue by a-thaler** [istio/istio#45890]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm using the new extensionProvider mechanism for tracing and it is working fine. However, while debugging the network traffic on my nodes I realized that DNS lookups are done for the default zipkin configuration (using zipkin.istio-system). That default endpoint does not exist in my setup and the constant failing lookups are causing additional stress on coreDNS.

To isolate the problem I started to reproduce it by first installing Istio 1.18.0 on an empty cluster with the default profile using the istioctl. I deployed a workload having an istio sidecar and triggered an endpoint. Then I analyzed the traffic using tcpdump and wireshark.

I installed istio with this command:
`/istio-1.18.0/bin/istioctl install -f istio.yaml`

I started with this istio.yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing: {}
```
That worked as expected, no zipkin lookups are recorded

Then I added an extensionProvider like that (having no telemetry API resource applied):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing: {}
    extensionProviders:
      - name: mytraces
        opencensus:
          service: "myCustomProvider.myNamespace.svc.cluster.local"
          port: 55678
```
Having istio re-installed and my workload restarted, **I suddenly can find DNS lookups for `zipkin.istio-system`**. Lookups for the custom provider cannot be found as expected as there is no defaultProvider configured nor a telemetry resource applied.

Configuring the custom provider as default is not improving the situation:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing: {}
    extensionProviders:
      - name: mytraces
        opencensus:
          service: "myCustomProvider.myNamespace.svc.cluster.local"
          port: 55678
    defaultProviders:
      tracing:
      - mytraces
```
Still the additional zipkin.istio-system lookups can be found but now also the expected custom provider lookups.

### Version

```Text
$ ./istio-1.18.0/bin/istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (2 proxies)

$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.5
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
can you share the output of running `istioctl pc c <target_pod_name>`

**Comment by a-thaler** [comment]
I used the first configuration from the description without active defaultProviders, only extensionProviders.
```bash
$ ./istio-1.18.0/bin/istioctl pc c sample-metrics-6d888896c5-6r25r
SERVICE FQDN                                                    PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                                8080      -          inbound       ORIGINAL_DST     
BlackHoleCluster                                                -         -          -             STATIC           
InboundPassthroughClusterIpv4                                   -         -          -             ORIGINAL_DST     
PassthroughCluster                                              -         -          -             ORIGINAL_DST     
agent                                                           -         -          -             STATIC           
apiserver-proxy.kube-system.svc.cluster.local                   16910     -          outbound      ORIGINAL_DST     
blackbox-exporter.kube-system.svc.cluster.local                 9115      -          outbound      EDS              
calico-felix-monitoring.kube-system.svc.cluster.local           9091      -          outbound      EDS              
calico-typha-monitoring.kube-system.svc.cluster.local           9093      -          outbound      EDS              
calico-typha.kube-system.svc.cluster.local                      5473      -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local             80        -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local             443       -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local             15021     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                           443       -          outbound      EDS              
istiod.istio-system.svc.cluster.local                           15010     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                           15012     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                           15014     -          outbound      EDS              
kube-dns-upstream.kube-system.svc.cluster.local                 53        -          outbound      EDS              
kube-dns.kube-system.svc.cluster.local                          53        -          outbound      EDS              
kube-dns.kube-system.svc.cluster.local                          9153      -          outbound      EDS              
kube-proxy.kube-system.svc.cluster.local                        10249     -          outbound      ORIGINAL_DST     
kubernetes.default.svc.cluster.local                            443       -          outbound      EDS              
metrics-server.kube-system.svc.cluster.local                    443       -          outbound      EDS              
network-problem-detector-host.kube-system.svc.cluster.local     8080      -          outbound      EDS              
network-problem-detector-pod.kube-system.svc.cluster.local      8080      -          outbound      EDS              
node-exporter.kube-system.svc.cluster.local                     16909     -          outbound      ORIGINAL_DST     
prometheus_stats                                                -         -          -             STATIC           
sample-metrics2.icke.svc.cluster.local                          8080      -          outbound      EDS              
sds-grpc                                                        -         -          -             STATIC           
xds-grpc                                                        -         -          -             STATIC           
zipkin                                                          -         -          -             STRICT_DNS
```

**Comment by a-thaler** [comment]
The pod is deployed in namespace ìcke`. In the pcap fie you can find these DNS lookups having the source IP of the pod:

````
7581	69.958925	100.64.1.4	100.104.0.10	DNS	85	Standard query 0xa4a7 A zipkin.istio-system
7568	69.941972	100.64.1.4	100.104.0.10	DNS	112	Standard query 0xf925 A zipkin.istio-system.eu-west-1.compute.internal
7564	69.941584	100.64.1.4	100.104.0.10	DNS	99	Standard query 0x1585 A zipkin.istio-system.cluster.local
7560	69.941165	100.64.1.4	100.104.0.10	DNS	103	Standard query 0x8959 A zipkin.istio-system.svc.cluster.local
7555	69.940451	100.64.1.4	100.104.0.10	DNS	108	Standard query 0xb9fa A zipkin.istio-system.icke.svc.cluster.local
4738	39.937313	100.64.1.4	100.104.0.10	DNS	85	Standard query 0x0438 A zipkin.istio-system
4719	39.934103	100.64.1.4	100.104.0.10	DNS	112	Standard query 0x3573 A zipkin.istio-system.eu-west-1.compute.internal
4715	39.933722	100.64.1.4	100.104.0.10	DNS	99	Standard query 0x7193 A zipkin.istio-system.cluster.local
4711	39.933284	100.64.1.4	100.104.0.10	DNS	103	Standard query 0xdafe A zipkin.istio-system.svc.cluster.local
4706	39.932543	100.64.1.4	100.104.0.10	DNS	108	Standard query 0x8d08 A zipkin.istio-system.icke.svc.cluster.local
1044	9.929295	100.64.1.4	100.104.0.10	DNS	85	Standard query 0x18be A zipkin.istio-system
1031	9.926135	100.64.1.4	100.104.0.10	DNS	112	Standard query 0xd27b A zipkin.istio-system.eu-west-1.compute.internal
1027	9.925756	100.64.1.4	100.104.0.10	DNS	99	Standard query 0x7d8d A zipkin.istio-system.cluster.local
1023	9.925319	100.64.1.4	100.104.0.10	DNS	103	Standard query 0xafef A zipkin.istio-system.svc.cluster.local
1018	9.924543	100.64.1.4	100.104.0.10	DNS	108	Standard query 0x82fe A zipkin.istio-system.icke.svc.cluster.local
```

**Comment by zirain** [comment]
this looks like a regression/bug

**Comment by zirain** [comment]
I try with istioctl with defferent version:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing: {}
```

will always generate a static cluster name `zipkin`, you should try work with following:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        tracer: none
```
