### ISSUE TITLE
failed to create manager for existing fields: failed to convert new object (istio-system/istio-platformgateway; apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="istio-proxy"].ports: duplicate entries for key [containerPort=8080,protocol="TCP"

### ISSUE THREAD

**Issue by andrew-clark-cc** [istio/istio#45922]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Tried to deploy another istio-ingress gateway called istio-platformgateway
below ports:
```
          ports:
            - port: 80
              targetPort: 8080
              name: http
              protocol: TCP
            - port: 8080
              targetPort: 8080
              name: http-alternative
              protocol: TCP
```

This was fine on 1.13.8 but becomes an issue with 1.15.7 istio.

The main ingress and egress gateways are using the new 1.15.7 but the istio-platformgateway is still on 1.13.8 due to the error.

### Version

```Text
istioctl version
client version: 1.15.7
istiod version: 1.13.8
istiod version: 1.13.8
istiod version: 1.13.8
istiod version: 1.13.8
istiod version: 1.13.8
istiod version: 1.15.7
istiod version: 1.15.7
istiod version: 1.15.7
istiod version: 1.15.7
istiod version: 1.15.7
data plane version: 1.13.8 (647 proxies), 1.15.7 (10 proxies)
```

### Additional Information

Any ideas on why this has been introduced as nothing is on the release notes as far as I can tell?

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
