### ISSUE TITLE
404 - via_upstream error when calling ingress gateway

### ISSUE THREAD

**Issue by 0xfourzerofour** [istio/istio#45931]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have configured Istio on an EKS cluster where the ingress gateway is talking to an NLB. I am able to see the request received in the logs for the specific pod that it needs to call.

The service is called using virtual service configuration however the response from the service back to the caller is not returned.

I get a 404 - via_upstream error.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.mediaAsset.name }}
  namespace: {{ .Values.mediaAsset.namespace }}
spec:
  gateways:
    - {{ .Values.mediaAsset.gateway.name }}
  hosts:
    - "*"
  http:
  - name: mas-grpc
    match:
    - uri:
        prefix: /mas_grpc
    route:
    - destination:
        host: {{ .Values.mediaAsset.host }}
        port:
          number: {{ .Values.mediaAsset.service.grpcPort }}
  - name: mas-http
    match:
    - uri:
        prefix: /mas
    route:
    - destination:
        host: {{ .Values.mediaAsset.host }}
        port:
          number: {{ .Values.mediaAsset.service.httpPort }}
```

```
resource "kubernetes_manifest" "shared_gateway" {
  manifest = {
    "apiVersion" = "networking.istio.io/v1alpha3"
    "kind"       = "Gateway"
    "metadata" = {
      "name"      = "shared-gateway-${var.env}"
      "namespace" = "istio-ingress"
    }
    "spec" = {
      "selector" = {
        "istio" = "ingressgateway"
      }
      "servers" = [
        {
          "port": {
            "number" = 80,
            "name" = "http"
            "protocol" = "HTTP"
          }
          "hosts" = ["*"]
        }
      ]
        
    }
  }

  depends_on = [helm_release.istio_ingress]
}



```

### Version

```Text
client version: 1.17.3
control plane version: 1.18.0
data plane version: 1.18.0 (2 proxies)

Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.2-eks-c12679a
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
