### ISSUE TITLE
Weighted TLS route doesn't work together with http tunnel subset

### ISSUE THREAD

**Issue by wenpincui** [istio/istio#45947]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a VirtualService which routes percentage of traffic to a service called `proxy-gateway.route-management.svc.cluster.local`, this service's destination rule specifies a subset where HTTP tunnel is enabled. When testing, if the traffic routed to this service, it will always fail. From client side's log we can see:

`curl: (35) OpenSSL/3.1.0: error:0A00010B:SSL routines::wrong version number`

From the service side, it says:

`[2023-07-11T03:27:34.236Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 10.184.37.202:443 10.184.18.96:45542 - -`

VirtualService Definition:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ip.me-mesh
  namespace: foo
spec:
  exportTo:
  - foo
  gateways:
  - mesh
  hosts:
  - ip.me
  tls:
  - match:
    - port: 443
      sniHosts:
      - ip.me
    route:
    - destination:
        host: proxy-gateway.route-management.svc.cluster.local
        port:
          number: 443
        subset: ip.me
      weight: 60
    - destination:
        host: istio-egressgateway.egress-gateway.svc.cluster.local
        port:
          number: 443
      weight: 40
```

However, if I disable the weighted routing and route all traffic to the service, it works. Now the VirtualService looks like:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ip.me-mesh
  namespace: foo
spec:
  exportTo:
  - foo
  gateways:
  - mesh
  hosts:
  - ip.me
  tls:
  - match:
    - port: 443
      sniHosts:
      - ip.me
    route:
    - destination:
        host: proxy-gateway.route-management.svc.cluster.local
        port:
          number: 443
        subset: ip.me
```

Checked the generated listener config of envoy, when it works, the listener config looks like:
```
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        cluster: outbound|443|ip.me|proxy-gateway.route-management.svc.cluster.local
        statPrefix: outbound|443|ip.me|proxy-gateway.route-management.svc.cluster.local
        tunnelingConfig:
          hostname: ip.me:443
```
When weighted routing is enabled, the config looks like:
```
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        statPrefix: ip.me-mesh.route-management
        weightedClusters:
          clusters:
          - name: outbound|443|ip.me|proxy-gateway.route-management.svc.cluster.local
            weight: 60
          - name: outbound|443||istio-egressgateway.egress-gateway.svc.cluster.local
            weight: 40
```

As we can see, the `tunnelingConfig` is missing. 

### Version

```Text
❯ istioctl version
client version: 1.14.1
istiod version: 1.15.0
istiod version: 1.15.0
istiod version: 1.17.1
istiod version: 1.17.1
data plane version: 1.15.0 (2682 proxies), 1.17.1 (63 proxies)

❯ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.8
Kustomize Version: v4.5.7
Server Version: v1.25.6
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
