### ISSUE TITLE
TLS mode MUTUAL not working for protocol TLS 

### ISSUE THREAD

**Issue by lakshmisivareddy** [istio/istio#46004]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team ,
i am routing HTTPS, TLS traffic through istio , i am trying to add TLS mode MUTUAL 
for Protocol: HTTPS TLS mode MUTUAL is working 
but Protocol: TLS , TLS mode MUTUAL is not  working 

i am using istio version 
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (3 proxies)

when i am using  TLS mode: PASSTHROUGH on port 8883 and  protocol TLS , traffic is routing 
please find istio ingress netstat output 

```
$ netstat -nlt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:15004         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8089            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8089            0.0.0.0:*               LISTEN     
tcp6       0      0 :::15020                :::*                    LISTEN  
```

please  find my Gateway configuration 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: deli-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 8089
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 8883
        name: mqtt
        protocol: TLS
      tls:
        mode: PASSTHROUGH
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: httpbin-credential
      hosts:
        - "*"
```
but when i am doing TLS mode: MUTUAL 
i observed istio ingress not showing  listing 8883, traffic is not going though 

```
$ netstat -nlt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:15004         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8089            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8089            0.0.0.0:*               LISTEN     
tcp6       0      0 :::15020                :::*                    LISTEN     
```
$ %                                                                          

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: deli-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 8089
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 8883
        name: mqtt
        protocol: TLS
      tls:
        mode: MUTUAL
        credentialName: httpbin-credential
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: httpbin-credential
      hosts:
        - "*"
```

can u someone please help with how to enable TLS mode MUTUAL  for protocol TLS 

### Version

```Text
l0c0gvk@m-l4mn7q22fh bin % ./istioctl version 
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (3 proxies)

l0c0gvk@m-l4mn7q22fh bin % kubectl version 
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

can u someone please help with how to enable TLS mode MUTUAL  for protocol TLS 

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by lakshmisivareddy** [comment]
i am seeing error in istio pod : gateway omitting listener "0.0.0.0_8883" due to: must have more than 0 chains in listener "0.0.0.0_8883"

**Comment by hzxuzhonghu** [comment]
Do you have validating webhook enbaled, when you create `deli-ingress-gateway` you should encounter an error, because mutual tls mode requires server cert/private key set

**Comment by lakshmisivareddy** [comment]
@hzxuzhonghu Thanks for the response 
yes i have valid webhook  , i created a kubernetes secret httpbin-credential which has the cert, keys
i have a scenario clients communicates over TLS and HTTPS based i want to do SSL termination at istio ingress and based on the SNI route the traffic to appropriate service 
with protocol : HTTPS everything is working with TLS MUTUAL ,
but when i tried the same thing with protocol TLS , it's not working

**Comment by lakshmisivareddy** [comment]
@hzxuzhonghu 
with TLS : PASSTHROUGH
l0c0gvk@m-l4mn7q22fh bin % ./istioctl proxy-config listeners istio-ingressgateway-5f9cfcdd74-wrgrp.istio-system
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8089  ALL   Route: http.8089
0.0.0.0 8443  ALL   Route: https.443.https.deli-ingress-gateway.istio-system
0.0.0.0 8883  ALL   Cluster: outbound|8883||store1-mqtt1-service.default.svc.cluster.local
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*

with TLS : MUTUAL
l0c0gvk@m-l4mn7q22fh bin % ./istioctl proxy-config listeners istio-ingressgateway-5f9cfcdd74-wrgrp.istio-system
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8089  ALL   Route: http.8089
0.0.0.0 8443  ALL   Route: https.443.https.deli-ingress-gateway.istio-system
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*

with TLS : MUTUAL i am not seeing 8883 getting listed in listeners

**Comment by hzxuzhonghu** [comment]
Do you have virtualService bound to  the gateway

**Comment by hzxuzhonghu** [comment]
BTW. you can enable debug log level on istiod and check the logs

**Comment by lakshmisivareddy** [comment]
Hi @hzxuzhonghu thanks for the response 
Please find my Gateway, VirtualService
i found this log : gateway omitting listener "0.0.0.0_8883" due to: must have more than 0 chains in listener "0.0.0.0_8883"
after changing TLS mode to MUTUAL but it is working fine if the TLS mode PASSTHROUGH
can u please help me here 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: deli-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 8089
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 8883
        name: mqtt-broker
        protocol: TLS
      tls:
        #credentialName: httpbin-credential
        mode: MUTUAL
        #mode: PASSTHROUGH
        #mode: ISTIO_MUTUAL
        serverCertificate: /etc/istio/mqtt-ingress-cers/connected-deli-istio-ingress.pem
        privateKey: /etc/istio/mqtt-ingress-cers/connected-deli-istio-ingress.key
        caCertificates: /etc/istio/mqtt-cers-ca-certs/root_CA_cert_filename.pem
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: httpbin-credential
      hosts:
        - "*"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: deli-ingress-vs
  namespace: istio-system
spec:
  gateways:
    - deli-ingress-gateway
  hosts:
    - "*"


  tls:
    - match:
        - port: 8883
          sniHosts:
            - "*"
      route:
        - destination:
            host: store1-mqtt1-service.default.svc.cluster.local
            port:
              number: 8883
  #   - match:
  #       - port: 8883
  #         sniHosts:
  #           - "store2.com"
  #     route:
  #       - destination:
  #           host: mqtt2-service.default.svc.cluster.local
  #           port:
  #             number: 8883
  http:
    - match:
        - uri:
             prefix: "/store1/weatherForecast"
      rewrite:
            uri: "/WeatherForecast"
      route:
        - destination:
            host: store1-app-service.default.svc.cluster.local
            port:
              number: 8089
```

**Comment by hzxuzhonghu** [comment]
Thanks for the details. I will try to reproduce, maybe you can run `istioctl analyze` as well

**Comment by lakshmisivareddy** [comment]
Hi @hzxuzhonghu 
please find istioctl analyze  output 

l0c0gvk@m-l4mn7q22fh bin % ./istioctl analyze                                                                  
Warning [IST0103] (Pod default/virt-launcher-aziot-edge-kubevirt01-linux-xbb98) The pod default/virt-launcher-aziot-edge-kubevirt01-linux-xbb98 is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod default/virt-launcher-aziot-edge-kubevirt02-linux-dl4l4) The pod default/virt-launcher-aziot-edge-kubevirt02-linux-dl4l4 is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod default/virt-launcher-aziot-edge-kubevirt03-linux-fc84r) The pod default/virt-launcher-aziot-edge-kubevirt03-linux-fc84r is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod default/virt-launcher-aziot-edge-kubevirt04-linux-nmzmh) The pod default/virt-launcher-aziot-edge-kubevirt04-linux-nmzmh is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod default/virt-launcher-aziot-edge-kubevirt05-linux-p87vf) The pod default/virt-launcher-aziot-edge-kubevirt05-linux-p87vf is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod default/virt-launcher-aziot-edge-kubevirt06-linux-rvx26) The pod default/virt-launcher-aziot-edge-kubevirt06-linux-rvx26 is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Info [IST0118] (Service default/aziot-edge-kubevirt-2-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service default/aziot-edge-kubevirt01-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service default/aziot-edge-kubevirt02-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service default/aziot-edge-kubevirt03-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service default/aziot-edge-kubevirt04-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service default/aziot-edge-kubevirt05-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service default/aziot-edge-kubevirt06-vm-ssh-service) Port name ssh (port: 22, targetPort: 22) doesn't follow the naming convention of Istio port.
Info [IST0135] (Pod default/virt-launcher-aziot-edge-kubevirt-2-linux-6s2dm) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.

**Comment by hzxuzhonghu** [comment]
Figurred out: you could not set tls match for 8089. Please set tcp match

```
	// An ordered list of route rule for non-terminated TLS & HTTPS
	// traffic. Routing is typically performed using the SNI value presented
	// by the ClientHello message. TLS routes will be applied to platform
	// service ports named 'https-*', 'tls-*', unterminated gateway ports using
	// HTTPS/TLS protocols (i.e. with "passthrough" TLS mode) and service
	// entry ports using HTTPS/TLS protocols.  The first rule matching an
	// incoming request is used.  NOTE: Traffic 'https-*' or 'tls-*' ports
	// without associated virtual service will be treated as opaque TCP
	// traffic.
	Tls []*TLSRoute `protobuf:"bytes,5,rep,name=tls,proto3" json:"tls,omitempty"`
```

**Comment by lakshmisivareddy** [comment]
Hi @hzxuzhonghu 
i tried disabling  8089 
but still the same 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: deli-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    # - port:
    #     number: 8089
    #     name: http
    #     protocol: HTTP
    #   hosts:
    #     - "*"
    - port:
        number: 8883
        name: mqtt-broker
        protocol: TLS
      tls:
        credentialName: httpbin-credential
        mode: MUTUAL
        #mode: PASSTHROUGH
        #mode: ISTIO_MUTUAL
        #serverCertificate: /etc/istio/mqtt-ingress-cers/connected-deli-istio-ingress.pem
        #privateKey: /etc/istio/mqtt-ingress-cers/connected-deli-istio-ingress.key
        #caCertificates: /etc/istio/mqtt-cers-ca-certs/root_CA_cert_filename.pem
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: httpbin-credential
      hosts:
        - "*"
```

**Comment by hzxuzhonghu** [comment]
Sorry i meant 8883, you should add a tcp match for it

**Comment by lakshmisivareddy** [comment]
Hi @hzxuzhonghu 
i tried this it didn't worked  can u check once 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: deli-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 8089
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 8883
        name: mqtt-tcp-broker
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 8883
        name: mqtt-broker
        protocol: TLS
      tls:
        #credentialName: httpbin-credential
        mode: MUTUAL
        #mode: PASSTHROUGH
        #mode: ISTIO_MUTUAL
        serverCertificate: /etc/istio/mqtt-ingress-cers/connected-deli-istio-ingress.pem
        privateKey: /etc/istio/mqtt-ingress-cers/connected-deli-istio-ingress.key
        caCertificates: /etc/istio/mqtt-cers-ca-certs/root_CA_cert_filename.pem
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: httpbin-credential
      hosts:
        - "*"
```
