### ISSUE TITLE
Authorization Policy: Not respecting "if not set any is allowed"

### ISSUE THREAD

**Issue by asuperpower** [istio/istio#46056]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In authorization policy, for each rule, it does not respect the "if not set, any is allowed" always in the following examples.

The examples: 

I have a default deny all policy in istio-system. I add this policy, which works without 'to' being specified until I add namespaces.

1. Simple from allowing all
```
rules
- from:
  - {}
```
Result: Traffic is allowed to flow

2. From allowing all namespaces
```
rules:
- from:
  - source:
      namespaces:
        - "*"
```
Result: Traffic gets blocked by RBAC with egress gateway showing: `rbac_access_denied_matched_policy[none]`

3. From allowing all namespaces, to allowing all
```
rules:
- to:
  - {}
- from:
  - source:
      namespaces:
        - "*"
```
Result: Traffic is allowed to flow

2. should function the same as 1. but it requires adding to, meaning that it does not respect the rules "if not set, any is allowed". In this case, as I started simple, it was an easy fix but I imagine that this could cause some headaches in other, more complicated scenarios.

Full chart for info:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-egress-gateway
  namespace: istio-gateway
spec:
  selector:
    matchLabels:
      istio: egress-gateway
  action: ALLOW
  rules:
  - to:
    - {}
  - from:
    - source:
        namespaces:
          - "*"
```

### Version

```Text
$ istioctl version
client version: 1.17.3
control plane version: 1.17.2
data plane version: 1.17.2 (24 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.26.3
$ helm version --short
v3.12.0+gc9f554d
```

### Additional Information

$ istioctl bug-report

Target cluster context: (removed)

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-07-18 12:15:29.268402 +0100 BST

Cluster endpoint: (removed)
CLI version:
version.BuildInfo{Version:"1.17.3", GitRevision:"61a081630d1bcc705e22b674e7f2fab7be3f16df-dirty", GolangVersion:"go1.20.4", BuildStatus:"Clean", GitTag:"1.17.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision stable:
&version.MeshInfo{
    {
        Component: "istiod",
        Info:      version.BuildInfo{Version:"1.17.2", GitRevision:"3e857775086a061d12ee445f32a0b35ea17c8488", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision stable: Versions {1.17.2}

Fetching proxy logs for the following containers:
(Removed)

Fetching Istio control plane information from cluster.
The following fetches are still running: 
  PodExec istio-system/istiod-stable-794db44687-tlnd6/discovery:pilot-discovery request GET debug/push_status

Running istio analyze on all namespaces and report as below:
Analysis Report:
(Removed)

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [x] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
