### ISSUE TITLE
Same services but with different ports in multicluster case will be only choosen to use the first service's ports.

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#46105]
In the multi-cluster case, given that we have the foo service with different ports defined in the different clusters, CDS will only push the first service with it's port but ignore the port of the service residing in the other cluster.
```
# the first cluster
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: test
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: foo
---
# the second cluster
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: test
spec:
  ports:
    - port: 8090
      protocol: TCP
  selector:
    app: foo
```

I found that we only care about cluster vip merging but ignore the ports merging. Is that we expect, or a bug? 
-  If it is we expect, do we have metrics or something else to warn users who do these things in their production env.
-  If it is a bug, should we fix now?
