### ISSUE TITLE
Is there a way to only retain istio_requests_total metrics and drop all the metrics?

### ISSUE THREAD

**Issue by jyothi-balla** [istio/istio#46205]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We get a lot of metrics from stats/prometheus endpoint, is there a way to reduce the amount of metrics from source as envoy gives us a lot of metrics and have only `istio_requests_total`.
I see there is a way by providing inclusion_list for envoy configuration, Can someone help how to configure this?
We have used helm to setup istio

### Version

```Text
using istio 1.17
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
you can try https://istio.io/latest/docs/tasks/observability/telemetry/

**Comment by jyothi-balla** [comment]
> you can try https://istio.io/latest/docs/tasks/observability/telemetry/

```
metrics:
    - providers:
         - name: prometheus
      overrides:
        - disabled: true
          match:
            mode: CLIENT
            metric: REQUEST_COUNT
```

should use something like this to disable all the metrics ? is there a way to keep only one metrics called istio_requests_total ? instead of having the list grow to exclude all the metrics that is not required?
