### ISSUE TITLE
Probe rewrite broken for custom `host`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46215]
Example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: gcr.io/istio-testing/app:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          initialDelaySeconds: 1
          httpGet:
            host: httpbin.org
            path: /get
            port: 80
```

NOTE: `host` is NOT the same as setting `headers[host]=httpbin.org`. In the above example, kubelet will actually do `curl httpbin.org/get` -- it does not go to the pod at all!

When we rewrite this, we get

```
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: httpbin.org
        path: /app-health/echo/readyz
        port: 15020
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```

This is broken. We send to httpbin.org:15020/app-health/echo/readyz which is obviously wrong.

IMO this is a terrible pattern, and I don't think anyone actually does it (note we have never gotten a bug report about it!). However, we should probably handle it better.

IMO we don't need to handle it actually. The whole point of the rewrite is to bypass mtls. But in this case, its going to httpbin - we can just let kubelet send it there as is. So I would propose when `host` is set, we skip rewriting the probe.

Edge case: in theory, they can make a DNS address that resolves to the pod IP (or even put the pod ip in there directly -- if they somehow guess it), at which point we would want a rewrite. These seems exceedingly unlikely and dumb though, so I don't mind that being broken.

cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Yes, this is a corner case we never handled well. As to why there was no bug reported, I believe that this httpGet.host is not commonly used. Even doubt if this is a bad API design

**Comment by howardjohn** [comment]
yeah definitely should not be used

**Comment by AlexGS74** [comment]
I see exactly this behavior without Host override:

```        
livenessProbe:
  httpGet:
    path: /healthz
    port: 8888
  initialDelaySeconds: 3
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /ready
    port: 8888
  initialDelaySeconds: 3
  periodSeconds: 30
``` 

Causes Istio 1.18.0 to poll healthchecks on port 15020.

![image](https://github.com/istio/istio/assets/8890708/c600be64-4c50-41d5-bd36-8d0335a049ac)

While 
```
ISTIO_KUBE_APP_PROBERS:        {"/app-health/api-sidecar/livez":{"httpGet":{"path":"/healthz","port":8888,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/api-sidecar/readyz":{"httpGet":{"path":"/ready","port":8888,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/redacted/livez":{"httpGet":{"path":"/healthz","port":8889,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/redacted/readyz":{"httpGet":{"path":"/ready","port":8889,"scheme":"HTTP"},"timeoutSeconds":1}}

Liveness:       http-get http://:15020/app-health/redacted/livez delay=3s timeout=1s period=30s #success=1 #failure=3                                                                   
Readiness:      http-get http://:15020/app-health/redacted/readyz delay=3s timeout=1s period=30s #success=1 #failure=3
```

The healthchecks on port 15020 succeed because we made them so.
