### ISSUE TITLE
istio add new tag by http request headers but in fact sometimes the value is wrong

### ISSUE THREAD

**Issue by iluoy** [istio/istio#46237]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I try to add new tags on `istio_requests_total` metric by customizing HTTP request headers, but sometimes the metrics are wrong

add new HTTP requests header `x-original-path` by envoy lua filter in case losing the origin request path after rewriting

```
              local function get_raw_path(path)
                  local raw_path = path
                  local p = path:find('?')
                  if p then
                     raw_path = path:sub(1, p - 1)
                  end
                  return raw_path
              end

              function envoy_on_request(request_handle)
                  local request_path = request_handle:headers():get(":path")
                  if not request_path then
                      request_handle:logWarn(":path Http Header Not Found!")
                      return
                  end
                  local raw_request_path = get_raw_path(request_path)
                  request_handle:headers():add("x-original-path", raw_request_path)
                  request_handle:logInfo("origin path is " .. raw_request_path)
```

add new tag  `request_path` by `x-original-path` http requests headers 

```
...
  meshConfig:
    defaultConfig:
      extraStatTags:
        - request_path
...

    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          configOverride:
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    request_path: string(request.headers["x-original-path"])
...
```

but some metric is wrong, sometimes it records the `request_path` is `/test1-service/actuator/health`, but the `destination_service_name` is `test-service`

VirtualService
```
  kind: VirtualService
  metadata:
    name: virtualservice-test
  spec:
    gateways:
    - istio-system/test-gateway
    hosts:
    - xxx
    http:
    - headers:
        request:
          set:
            X-Forwarded-Proto: https
      match:
      - uri:
          prefix: /test1-service/
      rewrite:
        uri: /
      route:
      - destination:
          host: test1-service.default.svc.cluster.local
          port:
            number: 8080
    - headers:
        request:
          set:
            X-Forwarded-Proto: https
      match:
      - uri:
          prefix: /test-service/
      rewrite:
        uri: /
      route:
      - destination:
          host: test-service.default.svc.cluster.local
          port:
            number: 8080
```

```
istio_requests_total{reporter="source",source_workload="istio-ingressgateway-1-17-1",source_canonical_service="istio-ingressgateway-1-17-1",source_canonical_revision="1-17-1",source_workload_namespace="istio-system",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-1-17-1-service-account",source_app="istio-gateway",source_version="",source_cluster="Kubernetes",destination_workload="test-service,destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/test-service",destination_app="unknown",destination_version="unknown",destination_service="test-service.default.svc.cluster.local",destination_canonical_service="test-service",destination_canonical_revision="latest",destination_service_name="test-service",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",response_code="200",grpc_response_status="",response_flags="-",connection_security_policy="unknown",istio_host="xxx",request_path="/test1-service/actuator/health"} 1

```
customizing

### Version

```Text
➜  ~ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (26 proxies)
```

### Additional Information

1. Most of merics with right value
2. There are no DestinationRule for test1-service and test2-service
3. some metric with unknown `request_path`

```

istio_requests_total{reporter="source",source_workload="istio-ingressgateway-1-17-1",source_canonical_service="istio-ingressgateway-1-17-1",source_canonical_revision="1-17-1",source_workload_namespace="istio-system",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-1-17-1-service-account",source_app="istio-gateway",source_version="",source_cluster="Kubernetes",destination_workload="test-service",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/test-service",destination_app="unknown",destination_version="unknown",destination_service="test-service.defaultsvc.cluster.local",destination_canonical_service="test-service",destination_canonical_revision="latest",destination_service_name="test-service",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",response_code="200",grpc_response_status="",response_flags="-",connection_security_policy="unknown",istio_host="xxx",request_url_path="unknown"} 1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
