### ISSUE TITLE
Destination fallbacks.

### ISSUE THREAD

**Issue by Ferdudas97** [istio/istio#46240]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
When there are no endpoints for cluster defined as a route destination, then traffic should be routed to one of defined fallbacks. Currently in this situation we will receive UH (unhealthy upstream). The fallback destination should be configurable for each destination defined in VirtualService.

#### How can it work?
Control plane receives information about desired destinations and fallbacks for routes.
During creation of route, if the desired destination/cluster does not have any endpoint, then the control plane tries to replace it with the first destination from the fallback list which has any endpoint/instance.

##### Example usage - internal canary

When some services will have canary instances and the base request will have X-Canary header then service mesh will redirect traffic to the canary instance, if there is no canary instance then we should use fallback (non canary instance). 

* services are responsible for header propagation
<img width="759" alt="image" src="https://github.com/istio/istio/assets/26126241/067e6d45-880e-45dd-ad62-1881c2956863">

#### Possible api

```
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
 name: foo
 namespace: xys-namespace
spec:
 hosts:
   - foo
 http:
   - name: "internal-canary"
     match:
       - headers:
           x-canary:
             exact: "1"
     route:
       - destination:
           host: foo
           subset: canary
         fallback:
           - destination:
               host: foo
               subset: fallback-subset
           - destination:
               host: foo
               subset: global
   - name: "global"
     route:
       - destination:
           host: foo
           subset: global
```

#### Performance considerations
We think there will not be any performance degradation on data-plane level, because for envoys this feature will be transparent, in any case they will receive only one cluster and all logic related with choosing the correct one will be implemented on the control plane side during building config for envoys.. There is only one thing that can affect the performance data-plane - Changing cluster for route will trigger sending changed routes to the envoy (RDS).

We cannot predict the possible impact on the control-plane, but probably the control-plane will have to do more complex logic during configuration creation and the number of pushes to data-planes can be a little more frequent.

**Describe alternatives you've considered**

[Envoy native loadbalancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) - is based on subsets, each endpoint has its own metadata and envoy implements logic responsible for selecting the correct subset and fallbacks - but Istio doesn’t support this envoy feature even by using EnvoyFilter.

There was a [proposition of implementing](https://docs.google.com/document/d/1qvd2nnvsTBQdRrSCwTs6zX1S0e2wh37uI49uqBhtdRw/edit?pli=1&resourcekey=0-rlhqTrOa7s2baqF3i8_S1A) this feature and this proposition was rejected but we're providing more general use-cases for this feature and presenting current lack of fallbacks

##### Example envoy config

Subset configuration for cluster
```
{
  "lb_subset_config": {
    "fallback_policy": "DEFAULT_SUBSET",
    "default_subset": {
      "lb_regular": true
    },
    "subset_selectors": [
      {
        "keys": [
          "canary"
        ]
      }
    ],
    "list_as_any": true
  }
}
```

Endpoint configuration for not canary instance

```
{
  "endpoint": {
    "address": {
      "socket_address": {
        "address": "xxx.xxx.xxx.xxx",
        "port_value": 31000
      }
    },
    "health_check_config": {}
  },
  "health_status": "HEALTHY",
  "metadata": {
    "filter_metadata": {
      "envoy.lb": {
        "lb_regular": true,
      }
    }
  }
}
```

Endpoint configuration for  canary instance

```
{
  "endpoint": {
    "address": {
      "socket_address": {
        "address": "xxx.xxx.xxx.xxx",
        "port_value": 31000
      }
    },
    "health_check_config": {}
  },
  "health_status": "HEALTHY",
  "metadata": {
    "filter_metadata": {
      "envoy.lb": {
        "canary": "1",
        "lb_regular": true
      }
    }
  }
}
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
We (Allegro) are in the process of analyzing Istio as a replacement for our in-house [control plane](https://github.com/allegro/envoy-control). We highly rely on envoy subsets and fallbacking features and lack of these fallbacks is a blocker for migration to Istio. This functionality is used to implement sticky/internal canary routing and routing for dev environments when we have many virtual dev environments and each virtual environment contains only a subset of the required services.

**Comment by hzxuzhonghu** [comment]
Yes, have seen this req many times. @howardjohn we can discuss it in this week's meeting

**Comment by fatedier** [comment]
> How can it work?
Control plane receives information about desired destinations and fallbacks for routes.
During creation of route, if the desired destination/cluster does not have any endpoint, then the control plane tries to replace it with the first destination from the fallback list which has any endpoint/instance.

We have the same requirements, but it seems that the solutions here do not completely solve our problem. Replacing routing in control plane will have a window period, and it is unavoidable to have request errors during this window period.

Actually, we can achieve this capability through a custom controller, watching endpoints, and modifying the virtual service. But we need a fallback feature without any request errors.

**Comment by Ferdudas97** [comment]
@hzxuzhonghu, do you mean the 'Istio WG Meeting' that takes place on this Wednesday?

**Comment by hzxuzhonghu** [comment]
Yes

**Comment by Ferdudas97** [comment]
@hzxuzhonghu what about it? This issue haven't been discussed on yesterday meeting.

**Comment by hzxuzhonghu** [comment]
I didnot attend the community meeting as the time is not friendly to me. But you can add this agenda to next meeting

**Comment by zengyuxing007** [comment]
Envoy supports the [ClusterSpecifierPlugin](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-cluster-specifier-plugin) externsion point.  Using it, we can customize the target cluster for the final routing.

**Comment by zengyuxing007** [comment]
Related issue: https://github.com/istio/istio/issues/39445

Another solution： Using the latest feature of Envoy Proxy: [subset loadbalancer](https://github.com/envoyproxy/envoy/commit/39b25c0bec2a9a6c3e8e776ca0effd742d68d82f), to implement it.

**Comment by Ferdudas97** [comment]
Hey, if I correctly understand, [ClusterSpecifierPlugin](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-cluster-specifier-plugin) only allows choosing a cluster name based on request headers. However, there is no information available regarding which clusters are available or how many endpoints they have.

The second solution, subset load balancing, is from our perspective, the best approach because we have used it previously in our in-house control plane. Do you have plans to implement subset load balancing in the near future?

**Comment by hzxuzhonghu** [comment]
@zengyuxing007 @Ferdudas97 After looking at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets

I am not sure how envoy works based on the config

```
---
name: cluster-name
type: EDS
eds_cluster_config:
  eds_config:
    path: '.../eds.conf'
connect_timeout:
  seconds: 10
lb_policy: LEAST_REQUEST
lb_subset_config:
  fallback_policy: DEFAULT_SUBSET
  default_subset:
    stage: prod
  subset_selectors:
  - keys:
    - v
    - stage
  - keys:
    - stage
    fallback_policy: NO_FALLBACK
```

**Comment by PanOS1** [comment]
Guys we need this!!!!

**Comment by gawarz** [comment]
@hzxuzhonghu 

[envoy subsets](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) can be configured at cluster level.
You need read [header_to_metadata_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_to_metadata_filter) to understand [envoy subsets](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets)

As I understand in order to use this feature for dynamic fallback we need to specify metadata for each instance (LbEndpoint) in cluster. For example:
```yaml
metadata:
  filter_metadata:
    envoy.lb:
      version: '1.0'
      stage: 'canary'
```


Next step is setup header_to_metadata in order to map headers to request metadata 
```yaml
http_filters:
- name: envoy.filters.http.header_to_metadata
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
  request_rules:
  - header: x-canary
      on_header_present:
        metadata_namespace: envoy.lb
        key: stage
        value: "canary"
        type: STRING	  
    remove: false
```


And now you can configure subsets for cluster

```yaml
name: cluster-name
type: EDS
eds_cluster_config:
  eds_config:
    path: '.../eds.conf'
connect_timeout:
  seconds: 10
lb_policy: LEAST_REQUEST
lb_subset_config:
  fallback_policy: DEFAULT_SUBSET
  default_subset:
    stage: prod
  subset_selectors:
  - keys:
    - stage
```

Thanks to that requests with header x-canary will be proxied to canary endpoints in cluster-name and if we turn off all canary instances requests will flow to default endpoints

**Comment by tuhao1020** [comment]
need this too

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by AleksanderBrzozowski** [comment]
We are also interested in this feature. Our use case is that we run workloads in many regions, for example eu-west-1 and us-east-1. What we want to do is to be able to failover to a second region in case of a failure in primary region.

We currently have two separate meshes between these two regions, thus it is impossible to get this out of the box. What we tried to do is to use `ingress gateway` in a second region to route request to the workload in second region.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin-failover
  namespace: my-ns
spec:
  exportTo:
    - my-ns
  hosts:
    - httpbin-failover.org
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: httpbin.second-region.com
      locality: us-east-1
    - address: httpbin
      locality: eu-west-1
```

there is also a need to rewrite authority, see below

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-failover
  namespace: my-ns
spec:
  exportTo:
    - my-ns
  hosts:
    - httpbin-failover.org
  http:
    - rewrite:
        authority: httpbin.second-region.com
      route:
        - destination:
            host: httpbin-failover.org
      timeout: 1s
```

This actually works, but has a few limitations:
- we can't use mTLS inside the cluster, and https outside (?)
- we have to rewrite authority

**Comment by Karanraj06** [comment]
Interested in this feature. We have two AKS clusters in East US and West US. Currently, for intra-cluster service communication, requests are routed outside the cluster to our DNS server, ensuring resiliency by redirecting traffic to the other cluster if a service is down.

We plan to migrate to Istio and use local DNS resolution but are concerned about losing this resiliency. Are there any open-source alternatives or solutions within Istio that can help us maintain this failover mechanism, ensuring traffic is routed to the second cluster if the destination service in the first cluster is unavailable?

Thank you for any insights!

**Comment by keithmattix** [comment]
I'm curious if we can augment the existing subsets in DR to have this functionality

**Comment by hzxuzhonghu** [comment]
If there is only an abstract service name for the two regions,  we can set  DestinationRule `FailoverPriority` to do fail over automatically

**Comment by keithmattix** [comment]
It sounds like the ask is to failover to a different `Service`/envoy cluster; IIUC, failover priority just sorts endpoints within a single cluster

**Comment by hzxuzhonghu** [comment]
Yes, that is what i am asking. I mean we can workaround that by define a SE them, and prioritize them even by workload labels

**Comment by AleksanderBrzozowski** [comment]
> Yes, that is what i am asking. I mean we can workaround that by define a SE them, and prioritize them even by workload labels

What about different transport layer? I mean, what if there is a requirement to use mTLS for calls inside the cluster, and HTTPS for calls outside of the cluster? This doesn't seem to be possible know.

**Comment by AleksanderBrzozowski** [comment]
> Maybe transport socket match can support it, i didnot try that

@hzxuzhonghu Could you provide more details how this can be done? 🙏

**Comment by yshch** [comment]
> We are also interested in this feature. Our use case is that we run workloads in many regions, for example eu-west-1 and us-east-1. What we want to do is to be able to failover to a second region in case of a failure in primary region.

I'm also trying to do something similar. The biggest issue for me was also inability to configure different upstream TLS settings for different endpoints. Envoy subsets alone do not solve this problem. The only mechanisms that do this cleanly, as far as i can tell, are transport socket matches and aggregated clusters.

Using transport socket match with stock Istio does not seem to be possible, because there is no way, as far as i can tell, to easily modify endpoint metadata. EnvoyFilter can't be used to patch endpoints also.

Using EnvoyFilters to create aggregated cluster and then attach this cluster to a route does seem to work though.

I think from a user perspective i would like to see something similar to this suggestion in Gateway API: https://github.com/kubernetes-sigs/gateway-api/issues/1802, https://github.com/kubernetes-sigs/gateway-api/discussions/2304. It's just very easy to understand and also covers multiple use cases.

```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: example-httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: example-gateway
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: example-svc
          port: 80
          priority: 0
        - group: networking.istio.io
          kind: Hostname
          name: example.com
          port: 443
          priority: 1
```

**Comment by yshch** [comment]
Here's an example of a hacky workaround using EnvoyFilter. In this example we failover from local pods serving HTTP to external HTTPS endpoint provided with ServiceEntry. This is way too ugly and really requires automation for any real world use though.

Example Service matching local workload pods:
```
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: default
spec:
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: httpbin
    app.kubernetes.io/name: httpbin
  type: ClusterIP
```

Example ServiceEntry to be used as a fallback. You can also use another Service or whatever. Here i use DestinationRule to setup TLS mode and to pass correct SNI:
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-se
  namespace: default
spec:
  endpoints:
    - address: yourdomain-external.io
      locality: r/z/s
  hosts:
    - example-se.default.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
      targetPort: 443
  resolution: DNS

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: example-se
  namespace: default
spec:
  host: example-se.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: yourdomain-external.io
```

HTTPRoute serving traffic to example Service. You could also just use VirtualService.
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-httproute
  namespace: default
spec:
  hostnames:
    - yourdomain.io
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: example
      namespace: istio-gateways
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: example-svc
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```

Lastly two EnvoyFilter object. First is used to created aggregated cluster from Service and ServiceEntry Istio managed clusters. Second attaches this aggregated cluster to the route.
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: example-agg-cluster
  namespace: istio-gateways
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value:
          name: example_agg_cluster
          connect_timeout: 1s
          lb_policy: CLUSTER_PROVIDED
          cluster_type:
            name: envoy.clusters.aggregate
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.clusters.aggregate.v3.ClusterConfig
              clusters:
                - outbound|80||example-svc.default.svc.cluster.local
                - outbound|443||example-se.default.svc.cluster.local
  priority: 50
  workloadSelector:
    labels:
      istio: ingressgateway

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: example-agg-cluster-route
  namespace: istio-gateways
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "yourdomain.io:443"
      patch:
        operation: MERGE
        value:
          route:
            cluster: example_agg_cluster
  priority: 100
  workloadSelector:
    labels:
      istio: ingressgateway
```
