### ISSUE TITLE
Sidecar configuration

### ISSUE THREAD

**Issue by veronikaBu** [istio/istio#46262]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

Add the capability to the Sidecar object to sort spec.egress.hosts based on namespace patterns (not exact names).
Currently, the Sidecar object allows users to define egress rules using specific namespace names. However, in scenarios where there is a need to define egress rules for multiple namespaces that follow a certain pattern (e.g., namespaces with a specific label or naming convention), there is no straightforward way to achieve this. Or possibility bind to specific hosts in network.  
example:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
  - hosts:
    -  "*name*/*"
```
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
  - hosts:
    bind: 10.0.0.0/17
  - hosts:
    bind: 10.64.0.0/17
```
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
