### ISSUE TITLE
Istioctl analyze incorrectly reporting IST0101

### ISSUE THREAD

**Issue by nberkley-gp** [istio/istio#46269]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

`istioctl analyze` incorrectly reports IST0101 errors for VSs pointing at SEs defined in another namespace but not exported to `*`.

For example the following will reproduce an error saying that httpbin.org was not found:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: ns-1
spec:
  exportTo:
  - .
  - ns-2
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-vs
  namespace: ns-1
spec:
  exportTo:
  - ns-2
  hosts:
  - httpbin.org
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
```

### Version

```Text
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.5
```

### Additional Information

The issue is because we're not respecting exportTo for any value other than `*` in `InitServiceEntryHostMap`. I'm still waiting on my employer to get a CLA set up and will file a PR to fix once it's set up if nobody gets there first.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
