### ISSUE TITLE
Active healthcheck via envoy filter stopped working after 1.18

### ISSUE THREAD

**Issue by Noksa** [istio/istio#46277]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The following manifest works with istio 1.16 and 1.17:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: debug-delete-me
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: web-mgmt.kazoo5-frankfurt.svc.cluster.local
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        health_checks:
        - always_log_health_check_failures: true
          event_log_path: /dev/stdout
          healthy_threshold: 1
          http_health_check:
            host: web-mgmt.kazoo5-frankfurt.svc.cluster.local
            path: /
          interval: 5s
          no_traffic_interval: 5s
          timeout: 5s
          unhealthy_threshold: 1
  workloadSelector:
    labels:
      kazooService: kazoo-apps
```

After upgrading to 1.18 istio-proxy container can't be ready due to the following error:
```
2023-08-02T08:56:24.499466Z    info    Readiness succeeded in 5.596842514s
2023-08-02T08:56:24.499848Z    info    Envoy proxy is ready
2023-08-02T08:58:59.260905Z    warning    envoy config external/envoy/source/common/config/grpc_subscription_impl.cc:128    gRPC config for type.googleapis.com/envoy.config.cluster.v3.Cluster rejected: Error adding/updating cluster(s) outbound|80||web-mgmt.kazoo5-frankfurt.svc.cluster.local: Didn't find a registered implementation for name: 'envoy.health_checkers.http'    thread=23
```

### Version

```Text
❯ ~ istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (21 proxies)

❯ ~ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.26.4

```
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
