### ISSUE TITLE
istioctl install without cluster-admin ClusterRole

### ISSUE THREAD

**Issue by westwind-sc** [istio/istio#46309]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Current we install Istio via `istioctl install`. we created a cluster role as below for `istioctl install`. It is part of the cluster-admin ClusterRole. Those are too widely rules. 
Could we provide a doc list all the required rules? And then update them each release, or update it with pull request that required new apiGroups/resources/verbs.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioctl-install
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
