### ISSUE TITLE
Unable to use Filesystem HTTP Cache EnvoyFilter

### ISSUE THREAD

**Issue by Stono** [istio/istio#46327]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm wondering if `envoy.extensions.http.cache.file_system_http_cache.v3.FileSystemHttpCacheConfig` is missing or miss configured in some way in the istio build.

I've successfully got a cache filter working with Simple (in memory):

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cache-filter
spec:
  workloadSelector:
    labels:
      app: istio-test-app-1
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: "envoy.filters.http.cache"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig"
```

But when I attempt to use https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/cache/file_system_http_cache/v3/file_system_http_cache.proto#extension-envoy-extensions-http-cache-file-system-http-cache:

```
              "@type": "type.googleapis.com/envoy.extensions.http.cache.file_system_http_cache.v3.FileSystemHttpCacheConfig"
              cache_path: /var/lib/istio/data
              manager_config:
                thread_pool:
                  thread_count: 1
```

I get `{"level":"warning","time":"2023-08-04T18:57:59.618266Z","scope":"envoy config","msg":"gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Didn't find a registered implementation for type: 'envoy.extensions.http.cache.file_system_http_cache.v3.FileSystemHttpCacheConfig'\n","caller":"external/envoy/source/common/config/grpc_subscription_impl.cc:128","thread":28}` in the envoy logs.

### Version

```Text
Istio: `1.17.5`
Kubernetes `v1.26.5`
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
