### ISSUE TITLE
Support Configuring OpenTelemetryTracingProvider to send traces to Daemonset Collector

### ISSUE THREAD

**Issue by ben-childs-docusign** [istio/istio#46398]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

We have deployed our opentelemetry collectors as daemonsets within our kubernetes cluster listening on hostport: 4317 and most of our applications send traces to that collector by using the `status.hostIP` provided by the kubernetes downward api to route metrics, logs and traces to the collector on the local host. This daemonset collector is configured to augment telemetry with useful resource attributes such as the k8s.node.name based on the node it is running on.

Istio configuration seems to only support a kubernetes service as a destination for trace requests this means we would have to deploy a separate collector as a service and we would lose the ability to augment the telemetry based on node level attributes.

**Describe alternatives you've considered**

Deploying the open telemetry collector as a service is a possible workaround but is not ideal as node level attributes cannot be added to the event stream.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ben-childs-docusign** [comment]
This may be supported by:
https://github.com/istio/istio/pull/28043

We will test and confirm

**Comment by zirain** [comment]
Providers do not support $(HOST_IP). If you’re running collector in agent mode, you can use [service internal traffic policy](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/#using-service-internal-traffic-policy), and set InternalTrafficPolicy to Local for better performance.

Can you give a try with above?

**Comment by ben-childs-docusign** [comment]
Thanks for the pointer @zirain , I'll try it and let you know if it works.

**Comment by ben-childs-docusign** [comment]
The following config is working for me:
I had to add this config to turn on sampling for the new telemetry api
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  # no selector specified, applies to all workloads
  tracing:
  - randomSamplingPercentage: 100.00
  - providers:
    - name: "opentelemetry"
```

And then configure the provider in meshconfig:
```
meshConfig:
  defaultProviders:
    tracing:
      - "opentelemetry"
  extensionProviders:
    - name: opentelemetry
      opentelemetry:
        service: [OTELDAEMONSET].[NAMESPACE].svc.cluster.local
        port: 4317
```

I was scratching my head for a bit until I figured out that the randomSamplingPercentage is a new config that did not get picked up from the previous meshConfig settIng:
```
meshConfig:
  defaultConfig:
    tracing:
      sampling: 100
```
