### ISSUE TITLE
Not able to include X-B3-TRACEID when using default envoy provider combined with opentelemetry extensionProvider

### ISSUE THREAD

**Issue by srodenhuis** [istio/istio#46414]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I created a setup using OTel Collector (Operator) and Grafana Tempo. Istio operator is configured with the opentelemetry extensionProvider and I use the default envoy provider with a customized accessLogFormat to add the X-B3-TRACEID to the logs. When I enable the opentelemetry extension using the Telemetry resource, the traceID is `null` but traces are coming in.
I also tried using the envoyFileAccessLog extensionProvider next to the opentelemetry extensionProvider, but same outcome.

Meshconfig:
```
meshConfig:
   accessLogFile: /dev/stdout
   accessLogFormat: |
     [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(X-B3-TRACEID)%
   enableTracing: true
    enableAutoMtls: true
    defaultProviders:
      tracing:
      - otel-tracing
    enableEnvoyAccessLogService: true
    enableTracing: true
    extensionProviders:
    - opentelemetry:
        port: 4317
        service: otel-collector-collector.otel.svc.cluster.local
      name: otel-tracing
```
Telemetry:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: otel-tracing
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
```

Is this expected behaviour, a bug, or am I missing something here?
The OTel Collector and Propagation work as expected and I can see the full trace (Gateway, Ingress, apps).

My goal is to enable devs to see a traceID in de logs (Loki) and from there see the trace in Tempo, but then I need the istio-proxy sidecar to log the traceID.

Thanks in advance!

### Version

```Text
Istio Operator 1.17.4
```

### Additional Information

Current output:
```
[2023-08-09T11:21:08.305Z] "GET /resources/css/petclinic.css HTTP/1.1" 200 - via_upstream - "-" 0 207840 3 2 "77.167.77.239,10.224.0.188" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "960f453b-b793-9d3a-a7f2-ff0dda28a022" "petclinic.team-test.20.93.226.67.nip.io" "10.224.0.45:8080" inbound|8080|| 127.0.0.6:34447 10.224.0.45:8080 10.224.0.188:0 outbound_.80_._.petclinic.team-test.svc.cluster.local default traceID=-
```

Expected output:
```
[2023-08-09T11:24:33.710Z] "GET /resources/images/favicon.png HTTP/1.1" 200 - via_upstream - "-" 0 528 4 3 "77.167.77.239,10.224.0.172" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "f50ce106-6afa-47f1-9b19-0b6b15e5f287" "petclinic.team-test.x.x.x.x.nip.io" "10.224.0.253:8080" inbound|8080|| 127.0.0.6:49925 10.224.0.253:8080 10.224.0.172:0 outbound_.80_._.petclinic.team-test.svc.cluster.local default traceID=5241c603452f8a7951bfdf1bae0a185f 
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
