### ISSUE TITLE
GRPC Authorization not working

### ISSUE THREAD

**Issue by syamrag** [istio/istio#46413]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a grpc service deployed on test-service namespace and I have created the below AuthorizationPolicy. When I try to access the service  grpc service from "dev-app1" namespace I am getting "CANCELLED: Call cancelled" error on node js app.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-test-service-from-dev-app1
  namespace: test-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/dev-app1/sa/deployment-runner"]

    - source:
        namespaces: ["dev-app1"]

    to:
    - operation:
        methods: ["POST"]
```

If I remove the methods field it's working. The below config works but I want to add methods and path filter for the policy

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-test-service-from-dev-app1
  namespace: test-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/dev-app1/sa/deployment-runner"]

    - source:
        namespaces: ["dev-app1"]
```

### Version

```Text
client version: 1.17.0
control plane version: 1.17.0
data plane version: 1.17.0 (24 proxies)

kubectl version

Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
