### ISSUE TITLE
ServerReflectionInfo method requires to be on AuthorizationPolicy for gRPC on Ambient

### ISSUE THREAD

**Issue by knabben** [istio/istio#46428]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Adding an AuthorizationPolicy for the waypoint only for the method of my app is not enough to have it passing, looking the logs waypoint try to hit the ServerReflectionInfo first and gets blocked, it's required to make the app method work, add the reflection method in the ACL as well.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authz
  namespace: default
spec:
  selector:
    matchLabels:
      gateway.istio.io/managed: istio.io-mesh-controller
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/default/sa/grpca
      to:
      - operation:
          methods:
          - POST
          paths: ["/grpcbin.GRPCBin/DummyServerStream", "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"]
```

If on propose it should  at least be documented, otherwise marking as a bug

### Version

```Text
istio 1.18.1
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
