### ISSUE TITLE
Failed to use portName in EnvoyFilter.RouteConfigurationMatch

### ISSUE THREAD

**Issue by blaisewang** [istio/istio#46459]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi all,

I deployed the BookInfo application in the `bookinfo` namespace and created the associated BookInfo Gateway following this guide https://istio.io/latest/docs/examples/bookinfo/

Command I used

```bash
kubectl create ns bookinfo
kubectl label namespace bookinfo istio-injection=enabled
kubectl apply -n bookinfo -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -n bookinfo -f samples/bookinfo/networking/bookinfo-gateway.yaml
```

So far so good, all functions worked as expected. Then, I tried to create an EnvoyFilter only applies to the `bookinfo-gateway` with the following yaml

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bookinfo-gateway-metadata
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 80
        portName: "http" # L11 of https://raw.githubusercontent.com/istio/istio/release-1.16/samples/bookinfo/networking/bookinfo-gateway.yaml
    patch:
      operation: MERGE
      value:
        metadata:
          filter_metadata:
            envoy.filters.http.lua:
              foo: "bar"
```

I searched the `foo` value from the generated proxy config via `istioctl proxy-config route -n istio-system istio-ingressgateway-566c5fc9cd-vmtks -o yaml | grep foo` but found nothing.

I also tried to add a `routeConfiguration.gateway` with following yaml

```yaml
...
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 80
        portName: "http"
        gateway: "bookinfo/bookinfo-gateway"
    patch:
...
```

But didn't work either. The only way to have the `foo` value in the generated proxy configuration is to keep only the `portNumber` value in the `routeConfiguration`, like

```yaml
...
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 80
    patch:
...
```

Any kind of help is greatly appreciated.

### Version

```Text
$ istioctl version
client version: 1.16.7
control plane version: 1.16.7
data plane version: 1.16.7 (8 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.6
Kustomize Version: v4.5.4
Server Version: v1.24.6-aliyun.1
```

### Additional Information

Target cluster context: 297960165566421595-ccc069e51d05640d2bef0572291e7c085

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-08-10 20:50:20.918276858 +0800 CST

Cluster endpoint: https://172.16.131.152:6443
CLI version:
version.BuildInfo{Version:"1.16.7", GitRevision:"00136097767eec680da8749837a8d79adf110b1a", GolangVersion:"go1.19.11", BuildStatus:"Clean", GitTag:"1.16.7"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.7", GitRevision:"00136097767eec680da8749837a8d79adf110b1a", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.7"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.16.7}

Fetching proxy logs for the following containers:

bookinfo/details-v1/details-v1-7d4d9d5fcb-r94kv/details
bookinfo/details-v1/details-v1-7d4d9d5fcb-r94kv/istio-proxy
bookinfo/productpage-v1/productpage-v1-66756cddfd-45qvh/istio-proxy
bookinfo/productpage-v1/productpage-v1-66756cddfd-45qvh/productpage
bookinfo/ratings-v1/ratings-v1-85cc46b6d4-2wzh2/istio-proxy
bookinfo/ratings-v1/ratings-v1-85cc46b6d4-2wzh2/ratings
bookinfo/reviews-v1/reviews-v1-777df99c6d-pkpmn/istio-proxy
bookinfo/reviews-v1/reviews-v1-777df99c6d-pkpmn/reviews
bookinfo/reviews-v2/reviews-v2-cdd8fb88b-ldsj6/istio-proxy
bookinfo/reviews-v2/reviews-v2-cdd8fb88b-ldsj6/reviews
bookinfo/reviews-v3/reviews-v3-58b6479b-rmmq7/istio-proxy
bookinfo/reviews-v3/reviews-v3-58b6479b-rmmq7/reviews
istio-system/istio-egressgateway/istio-egressgateway-6796d654d8-s2bd4/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-566c5fc9cd-vmtks/istio-proxy
istio-system/istiod/istiod-549db5fd75-zxqxx/discovery
istio-system/kiali/kiali-64df7bf7cc-ctgl4/kiali

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /root/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
