### ISSUE TITLE
Ambient: consider more granular enablement for ztunnel and waypoints

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46488]
Currently, ztunnel redirection is enabled on a per-pod basis and waypoints on a per-SA basis.

A user may want to be more granular. For example, they may already use TLS on a certain port in their application and not want Istio for that port.

We should look into adding more granular enablement options

**Comment by bleggett** [comment]
Related (port exclusions, etc): https://github.com/istio/istio/issues/43700

Configurable port capture exclusion is already something we support, and will probably have to support in ambient.

It's unclear if we need much beyond that at this point.

**Comment by howardjohn** [comment]
Notably, port exclusions in istio today break auto-mtls. And ambient is basically auto-mtls amplified.

**Comment by howardjohn** [comment]
Spent some time putting together a e2e example of Costin's idea (or my version of it, anyhow).

I used Istio GW and ztunnel. Both could be swapped out. For example, could use network policy and GKE managed LB.

```
go run ./istioctl/cmd/istioctl install -y -d manifests/ --set profile=ambient --set meshConfig.accessLogFile=/dev/stdout --set meshConfig.defaultHttpRetryPolicy.attempts=0

kubectl create ns server
k label ns server istio.io/dataplane-mode=ambient istio-injection- --overwrite
kubectl apply -f ~/kube/apps/echo-versions.yaml -n server

kubectl create ns client
k label ns client istio.io/dataplane-mode=ambient istio-injection- --overwrite
kubectl apply -f ~/kube/shell/shell.yaml -n client


kubectl exec -n client deployment/shell -- curl -s echo-versions.server # We can connect directly

kubectl apply -f tests/integration/pilot/testdata/gateway-api-crd.yaml
cat <<EOF | kubectl apply -f - -n server
# Gateway doesn't handle having redirection enabled for it...
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: disable-hbone
  namespace: server
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: gateway
  environmentVariables:
    ISTIO_META_ENABLE_HBONE: "false"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: server
  annotations:
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo
  namespace: server
spec:
  hostnames: [echo.mesh.howardjohn.net]
  parentRefs:
  - name: gateway
  rules:
  - backendRefs:
    - name: echo-v1
      port: 80
      weight: 1
    - name: echo-v2
      port: 80
      weight: 2
EOF

# Setup DNS and external DNS
gcloud dns managed-zones create "howardjohn-net" --dns-name "howardjohn.net." \
  --description "Automatically managed zone by kubernetes.io/external-dns"

gcloud iam service-accounts create external-dns --project howardjohn-istio
gcloud projects add-iam-policy-binding howardjohn-istio \
    --member "serviceAccount:external-dns@howardjohn-istio.iam.gserviceaccount.com" \
    --role roles/dns.admin
gcloud iam service-accounts add-iam-policy-binding external-dns@howardjohn-istio.iam.gserviceaccount.com \
  --role roles/dns.admin
gcloud iam service-accounts add-iam-policy-binding external-dns@howardjohn-istio.iam.gserviceaccount.com \
  --role "roles/iam.workloadIdentityUser" \
  --member "serviceAccount:howardjohn-istio.svc.id.goog[external-dns/external-dns]"

cat <<EOF | kubectl apply -f - -n external-dns
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@howardjohn-istio.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways","httproutes","grpcroutes","tlsroutes","tcproutes","udproutes"] 
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  labels:
    app.kubernetes.io/name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns  
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.13.5
          args:
            - --source=gateway-httproute
            - --source=gateway-grpcroute
            - --source=gateway-tlsroute
            - --source=gateway-tcproute
            - --source=gateway-udproute
            - --domain-filter=howardjohn.net # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
            - --provider=google
            - --log-format=json # google cloud logs parses severity of the "text" log format incorrectly
            - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
            - --registry=txt
            - --txt-owner-id=my-identifier
EOF
# Workaround external DNS bug
kubectl -n istio-system set image deployment istiod discovery=gcr.io/howardjohn-istio/pilot:1692638696 # For writing IP instead of hostname

# Send requests through "waypoint"
kubectl exec -n client deployment/shell -- curl -s curl echo.mesh.howardjohn.net/{0..100} | grep Hostname= | sort | uniq -c
 # still works
kubectl exec -n client deployment/shell -- curl -s echo-versions.server

# Block traffic on port 80 unless its from gateway
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: echo-enforce-waypoint
spec:
  selector:
    matchLabels:
      app: echo-versions
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/server/sa/gateway-istio"]
  - to:
    - operation:
        notPorts: ["80"]
```
