### ISSUE TITLE
Is there an easier way to log request and response body that using Lua filters?

### ISSUE THREAD

**Issue by matined** [istio/istio#46503]
**Describe the feature request**

I'd like to easily log full request and response bodies, especially a json data passed to the pod and returned by it and access it using prometheus or save it to the database.

**Describe alternatives you've considered**

I see that it should be possible using Lua filter. Is there a better method?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
wasmplugin?

**Comment by hzxuzhonghu** [comment]
wasm is more conplexter.  For request body you can use traffic mirror

**Comment by ramaraochavali** [comment]
you can use https://www.envoyproxy.io/docs/envoy/v1.27.0/api-v3/extensions/filters/http/tap/v3/tap.proto to dump the request/response

**Comment by matined** [comment]
@ramaraochavali  
> you can use https://www.envoyproxy.io/docs/envoy/v1.27.0/api-v3/extensions/filters/http/tap/v3/tap.proto to dump the request/response

I really like the idea, but it doesn't work for me :// Could I kindly ask you to verify if I use it correctly?

1. I enabled Access Logs using `istioctl install -y --set meshConfig.accessLogFile=/dev/stdout` for installation

2. I applied an EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-logging
  namespace: my-namespace
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: envoy.filters.http.tap
    patch:
      operation: INSERT_AFTER
      value:
        name: envoy.filters.http.tap
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.tap.v3.Tap
          common_config:
            static_config:
              match_config:
                any_match: true
              output_config:
                sinks:
                  - format: JSON_BODY_AS_BYTES
                    streaming_admin: {}
```

3. I create a pod in ns `my-namespace`, curl it and expect to see the body of the request using `kubectl logs ...` command.

Thank you in advance ;))

**Comment by zengyuxing007** [comment]
It is only allowed to specify the streaming admin output sink if the tap is being configured from the POST /tap admin endpoint.

If you use static configuration, you can configure it like this.


```yaml
  name: envoy.transport_sockets.tap
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.transport_sockets.tap.v3.Tap
    common_config:
      static_config:
        match_config:
          any_match: true
        output_config:
          sinks:
            - format: PROTO_BINARY
              file_per_tap:
                path_prefix: /some/tap/path
```
