### ISSUE TITLE
Telemetry objects used to disable Access Logging throw IST0157

### ISSUE THREAD

**Issue by diranged** [istio/istio#46510]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The current documentation for how to disable access logging (https://istio.io/latest/docs/reference/config/telemetry/) ([defined here](https://github.com/istio/istio.io/blob/d1090e0407285e5d5ce8a962233679107deefc50/content/en/docs/reference/config/telemetry/index.html#L169-L180)) is invalid. The creation of a `Telemetry` object without any providers throws the `IST0157` error.

<img width="939" alt="image" src="https://github.com/istio/istio/assets/768067/27e564d5-188a-4abc-9766-035357926c50">

Here's an example resource and the error that's reported:

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable
spec:
  accessLogging:
  - disabled: true
status:
  observedGeneration: "1"
  validationMessages:
  - documentationUrl: https://istio.io/v1.17/docs/reference/config/analysis/ist0157/
    level: WARNING
    type:
      code: IST0157
```

The reality is you need to create the resource like this:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable
spec:
  accessLogging:
    - disabled: true
      providers:
        - name: envoy
```

I think this is just a documentation bug...

### Version

```Text
$ istioctl version
client version: 1.17.3
istiod version: 1.16.7
istiod version: 1.16.7
istiod version: 1.17.5
istiod version: 1.17.5
pilot version: 1.16.0
pilot version: 1.16.0
data plane version: 1.16.0 (30 proxies), 1.16.7 (212 proxies)
```
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
