### ISSUE TITLE
Header based routing not working with grpc

### ISSUE THREAD

**Issue by VinithKrishnan** [istio/istio#46541]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Tried routing grpc requests using header based routing but istio fails to route the requests according to the rules specified in the Virtual Service spec.

Client code that attaches header using grpc metadata:
```
func main() {
        flag.Parse()
          // Set up a connection to the server.
	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewGreeterClient(conn)
	// Contact the server and print out its response.
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	
	// add header to request as grpc metadata
	value := "world" 
	ctx = metadata.AppendToOutgoingContext(ctx, "hello", value)
	
	
	r, err := c.SayHello(ctx, &pb.HelloRequest{Name: *name})
	if err != nil {
		log.Fatalf("could not greet: %v", err)
	}
	log.Printf("Greeting: %s", r.GetMessage())
}
```

Gateway :
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grpc-service-gateway
  namespace: istio-system
spec:
  selector:
    istio: seldongateway
  servers:
  - hosts:
    - '*'
    port:
      name: grpc
      number: 80
      protocol: GRPC
```

Virtual Service:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello
  namespace: kratos-team
spec:
  gateways:
  - istio-system/grpc-service-gateway
  hosts:
  - '*'
  http:
  - match:
    - headers:
        hello:
          exact: world
    route:
    - destination:
        host: grpc-service.kratos-team.svc.cluster.local
        port:
          number: 50051
  - route:
    - destination:
        host: hello-service.kratos-team.svc.cluster.local
        port:
          number: 50051
```

Logs of ingressgateway pod when request is made with value "world" for key "hello":
```
[2023-08-15T17:12:07.859Z] "POST /helloworld.Greeter/SayHello HTTP/2" 200 - via_upstream - "-" 12 18 8 8 "192.168.113.244" "grpc-go/1.57.0" "27d43656-44d2-98e7-a0b8-a00232045e09" "grpc-inference.kratos.nvidia.com:80" "192.168.28.212:50051" outbound|50051||grpc-service.kratos-team.svc.cluster.local 192.168.50.78:49278 192.168.50.78:8080 192.168.113.244:29499 - -
```

Logs of ingressgateway pod when request is made with value "earth" for key "hello":
```
[2023-08-15T17:12:47.014Z] "POST /helloworld.Greeter/SayHello HTTP/2" 200 - via_upstream - "-" 12 18 1 1 "192.168.51.120" "grpc-go/1.57.0" "c4386e5c-8d09-9f9b-adcd-af9779d7799a" "grpc-inference.kratos.nvidia.com:80" "192.168.28.212:50051" outbound|50051||grpc-service.kratos-team.svc.cluster.local 192.168.50.78:49278 192.168.50.78:8080 192.168.51.120:57698 - -
```

As observed above when a request is sent with the value "earth" for key/header "hello", the response is  being routed to `
grpc-service.kratos-team.svc.cluster.local`  instead of `hello-service.kratos-team.svc.cluster.local`, which is not what the Virtual Service is configured to do.

   

  

### Version

```Text
client version: 1.16.1
control plane version: 1.16.0
data plane version: 1.11.4 (1 proxies), 1.16.0 (109 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
