### ISSUE TITLE
LEAST_REQUEST Loadbalancer and warmupDurationSecs not working stable

### ISSUE THREAD

**Issue by NiroDeveloper** [istio/istio#46554]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In some cases the load balancer is not working as expected.
In my application newly spawned replicas are slower in the first few minutes.

I would assume that this replica would then receive fewer requests than the rest, but in some cases istio does simple round robin load balancing.
Example (Requests per Second separated by Pod):
![image](https://github.com/istio/istio/assets/23154768/b8bcabad-196e-42c6-b0e3-dafe0bc838b7)
Here you can see an example of a load test, where no configuration was changed during the runtime.
At the first scale up all pods were blocked because of a new slow pod.
At the second scale up the load balancer did it quite well.
=> Istio does not function stably?

Istio traffic policy:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: delivery-load-balancing
spec:
  host: delivery-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
      warmupDurationSecs: 60s
```

### Version

```Text
root@bootstrap:~# istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.17.2 (10 proxies), 1.18.0 (179 proxies)

root@bootstrap:~# kubectl version --short
Client Version: v1.20.7
Server Version: v1.25.11

root@bootstrap:~# helm version --short
v3.2.4+g0ad800e
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
