### ISSUE TITLE
Port level mTLS mode not rejecting out-of-mesh traffic

### ISSUE THREAD

**Issue by ymesika** [istio/istio#46570]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In a setup where you have a helloworld service running in a `test` namespace with the ambient label I applied the following PeerAuthentication to that namespace:
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: helloworld-strict
  namespace: test
spec:
  mtls:
    mode: PERMISSIVE
  portLevelMtls:
    "5000":
      mode: STRICT
  selector:
    matchLabels:
      app: helloworld
```
I then tries to call the helloworld service from another namespace that is out of the mesh (not labeled).
Currently requests hits the service and response received.
I tested it with sidecars and it rejects the traffic on that port with the same config.

@keithmattix Is this supposed to be supported?

### Version

```Text
Current master.
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
