### ISSUE TITLE
Support customization for Kubernetes Gateway API automated deployments

### ISSUE THREAD

**Issue by svrakitin** [istio/istio#46594]
**Describe the feature request**

I am looking for a way to configure `nodeSelector`, `tolerations` and `affinity` for automatic `Gateway` deployments in the multi-tenant Kubernetes cluster.

[Documentation](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment) references [Custom templates](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental) section, which introduces `inject.istio.io/templates` annotation to provide custom patches on top of the default `sidecar` and `gateway` templates. This doesn't really work after https://github.com/istio/istio/pull/43369 got merged.

As I understand the actual `kube-gateway` template is hardcoded for `gateway.networking.k8s.io/v1beta1/Gateway` here in https://github.com/istio/istio/blob/d400ed59d02763bd6323a942f9b8bf9a6693b646/pilot/pkg/config/kube/gateway/deploymentcontroller.go#L135 and the only way to customize default template is to copy it from [kube-gateway.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml), add patches on top and supply a patched template via Helm values. This is complicated to maintain and probably not safe to keep between version upgrades.

I see following options:
* Supporting `inject.istio.io/templates` or new annotation on `GatewayClass`, so `Gateway` inherits a common template. 
* Extend `ProxyConfig` to support extra pod fields like tolerations and affinity.

For example
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: istio-custom
  annotations:
    inject.istio.io/templates: custom
spec:
  controllerName: istio.io/gateway-controller
```

or

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: my-gateway-affinity
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: my-gateway
  nodeSelector: {}
  affinity: {}
  tolerations: []
```

I can also contribute, but I see there is some active refactoring happening atm.

**Describe alternatives you've considered**

Providing complete custom template.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by PavelPikat** [comment]
Can this be reopened please?
I wanted to try the new Ambient Mesh on multi-arch AKS cluster and got immeteatly blocked because my Waypoint is being scheduled on Windows nodes, and without nodeSelector, I'm not sure how I can tell the scheduler to only target Linux node pools.

I wish there were some annotations and config hooks to set this in the Gateway

**Comment by danielloader** [comment]
Likewise this bit me instantly when trying to use tolerations to tolerate my core managed node group on EKS and not just provision karpenter provisioned nodes just for the sake of deployment of the gateway pods. 

I'd like to utilise the under utilised but mandatory managed node group for this functionality but I keep a taint on it to prevent client workloads going on it those nodes.

Likewise I'd like to add `spreadTopologyConstraints` to the deployment to get AZ aware deployments for higher resiliency and or nodeAntiAffinity to keep gateways spread out over nodes in a pool too.

**Comment by svrakitin** [comment]
Definitely needs a reopen, I would like to stop patching the `kube-gateway.yaml`. :)

**Comment by hzxuzhonghu** [comment]
cc @howardjohn

**Comment by keithmattix** [comment]
> Can this be reopened please? I wanted to try the new Ambient Mesh on multi-arch AKS cluster and got immediately blocked because my Waypoint is being scheduled on Windows nodes, and without nodeSelector, I'm not sure how I can tell the scheduler to only target Linux node pools.
> 
> I wish there were some annotations and config hooks to set this in the Gateway

You can technically modify the sidecar-injector configmap and change the kube-gateway template to add a custom nodeSelctor, but I agree it's less than ideal. There are changes necessary in the upstream Gateway API to make this really smooth....if you have control over all of the things you're deploying to your windows nodes, you can add a taint to them so that the waypoints never get scheduled there

**Comment by zirain** [comment]
https://github.com/istio/istio/issues/48000#issuecomment-2136081267

**Comment by nicole-lihui** [comment]
the similar requirement：
https://github.com/istio/istio/issues/48000

**Comment by dro-sh** [comment]
Any updates there?

**Comment by dro-sh** [comment]
I want to set different affinity and toleration for two gateways. So edit `kube-gateway` template does not suit me. Also I am using ambient mode. And custom pod injection also does not work: I set annotation at gateway `inject.istio.io/templates`, but injection does not happen. Only way I that I see now is copy `kube-gateway` Deployment and set manually values or create chart for that.

**Comment by roivaz** [comment]
Hi folks, I'm using Istio's (v1.21) implementation of Gateway API and want to set affinity so pods get scheduled across different failure domains to improve availability. I tried to use `inject.istio.io/templates` as the documentation suggests but this doesn't seem to be working (https://istio.io/v1.21/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental). I don't like the option of editing the `kube-gateway` template as I could end up with a broken configuration in a future Istio upgrade. 
I'm thinking of adding a mutating webhook to inject this configuration in the gateway pods using something like kyverno, but it really would be nice to have some way to configure it. The ability to configure tolerations, resources, affinity, etc, it's very important in a production Gateway.

**Comment by twoTimesAgnew** [comment]
Hello,  
We're using istio `1.22.3` with kubernetes gateway API and are trying to run a full `arm64` cluster in GKE. However, GKE auto-taints all the nodes with `kubernetes.io/arch=arm64:NoSchedule` so we would need to set a toleration on the auto-created Gateway resource from istio. Using `inject.istio.io/templates` does not seem to work on the Gateway resource.

**Comment by nirvanagit** [comment]
@howardjohn @keithmattix - what is your recommendation on this? This is a blocking feature for us to move to using k8s gateway API. Appreciate your input.

**Comment by keithmattix** [comment]
I'm looking at a couple of options to make this easier, either with parametersRef in Gateway API or something else. This would be targeting Istio 1.25

**Comment by keithmattix** [comment]
Actually @nirvanagit, will [manually deploying](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment) your Gateway work for you? If so, please let me know so we can address any gaps

**Comment by nirvanagit** [comment]
@keithmattix - manually deploying definitely works. Thanks for pointing to the document.

Could we extend the Gateway API using custom extensions to provide that field in the Gateway spec itself? 

While manually deploying works, I was wondering as we enhance IstioD as a Gateway controller, manually managing the resources could diverge from the standard, and make it hard to come back.

**Comment by BeyondEvil** [comment]
Sorry, I don't really understand how to deploy it manually to solve this @keithmattix 🫣

**Comment by mikemorris** [comment]
[celebrate]     Mike Morris reacted to your message:
________________________________

**Comment by mikemorris** [comment]
[0]     Mike Morris reacted to your message:
________________________________

**Comment by zakariais** [comment]
hi
any news on when this will be supported?
nodeSelector is really imp for us

**Comment by kamalmarhubi** [comment]
@keithmattix out of curiosity, what are the pros / cons of that vs parametersRef with a config CRD as [you mentioned](https://github.com/istio/istio/issues/46594#issuecomment-2442397197) previously?

(My guess: you lose an amount of type safety but possibly don't have to deal with mirroring the ever-expanding PodSpec. Though I suppose you can get the latter by defining the pod part inside a `x-kubernetes-preserve-unknown-fields` object?)

**Comment by keithmattix** [comment]
@kamalmarhubi This would be via parametersRef :) The reference would be to the aforementioned configmap; you're exactly right about mirroring the PodSpec. Not creating a new CRD helps cut down on complexity

**Comment by therealmitchconnors** [comment]
For reference, [this](https://gateway-api.sigs.k8s.io/reference/spec/#:~:text=ParametersRef%20is%20a%20reference%20to,not%20require%20any%20additional%20configuration.) is the Gateway API field we could use to accomplish this.

**Comment by mikemorris** [comment]
^ is the field on GatewayClass, https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.LocalParametersReference is the similar field we would use for per-Gateway configuration extensibility.

**Comment by dgn** [comment]
I like this idea. One suggestion I have is to add an option to enable/disable the customization at the GatewayClass level. That way, security-conscious admins can disable it for sensitive GatewayClasses.

A nice-to-have would be to also have the same option at the GatewayClass level (possibly through [ParametersRef](https://gateway-api.sigs.k8s.io/reference/spec/#:~:text=ParametersRef%20is%20a%20reference%20to,not%20require%20any%20additional%20configuration.)). That would allow admins to adjust the kind of Gateways that are deployed, and by disabling the Gateway-level customization enforce these settings.

**Comment by keithmattix** [comment]
Yeah I think istiod setting makes the most sense to me

**Comment by howardjohn** [comment]
> What do you mean by 'own the resource'? Can't everyone create a GatewayClass with the correct controllerName and istiod will reconcile it?

Strictly speaking they can. But its a bit wonky...

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: istio
spec:
  controllerName: istio.io/gateway-controller
  description: The default Istio GatewayClass
```

is the config. It doesn't make sense for a user to be writing the description for it. Right now that is the main thing (aside from any dual-ownership object being weird, since we will create it if they don't) but there are constantly proposals upstream to add more cruft.

**Comment by howardjohn** [comment]
@vincedevendra Istio 1.25 is coming out in ~days, this is targettng 1.26

**Comment by howardjohn** [comment]
I've put together an initial implementation of this: https://github.com/istio/istio/pull/55283. Please take a look and let me know if you have any feedback

**Comment by jearangoo** [comment]
i am using gke version 1.32.2-gke.1297002 and istio version 1.26.1 with this configuration, setting the infrastructure block as it is specified in https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: egress
  namespace: istio-system
  annotations:
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: egress-gateway-options
      namespace: istio-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: egress-gateway-options
  namespace: istio-system
data:
  deployment: |
    spec:
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: istio
          tolerations:
            - effect: NoSchedule
              key: app/istio-reserved
              operator: Exists


```
it applies but when the gateway is inspected via kubectl describe it has the api version `gateway.networking.k8s.io/v1` and does not have the infrastructure block with deploymet nodeSelector or tolerations, the generated deployment does not have the nodeSelector or tolerations either
am i doing something wrong? thanks.

**Comment by howardjohn** [comment]
see https://blog.howardjohn.info/posts/crd-versioning/ for why it's v1

**Comment by macrokernel** [comment]
I can confirm a similar issue as described by @jearangoo with Istio 1.26.8:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-gateway-options
  namespace: istio-qa
data:
  deployment: |
    spec:
      template:
        spec:
          nodeSelector:
            launch-role/infra: "true"
          tolerations:                        # <-- there is an issue with this part
            - effect: NoSchedule
              key: istio.io/rev=istio-qa
              operator: Exists
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: site-gateway
  namespace: istio-qa
  annotations:
    cert-manager.io/issuer: qa-site-letsencrypt
  labels:
    istio.io/rev: istio-qa
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: site-gateway-options
  listeners:
  ...
```

```shell
$ kubectl -n istio-qa describe deployments.apps site-gateway-istio |grep -E 'Node|Tolerations'
  Node-Selectors:  <none>
  Tolerations:     <none>
```

However, the Infrastracture block is present in the gateway description:

```shell
$ kubectl -n istio-qa describe gtw site-gateway |grep -A4 Infra
  Infrastructure:
    Parameters Ref:
      Group:  
      Kind:   ConfigMap
      Name:   site-gateway-options
```

I tried with these API versions:
- apiVersion: gateway.networking.k8s.io/v1beta1
- apiVersion: gateway.networking.k8s.io/v1

UPDATE: 
It is working fine with no tolerations specified. I don't actually need tolerations, just copied it from the above example. Suspecting there is a syntax error in the tolerations spec.

**Comment by sridhargaddam** [comment]
> It is working fine with no tolerations specified. I don't actually need tolerations, just copied it from the above example.  Suspecting there is a syntax error in the tolerations spec.
> ```
> tolerations:                        # <-- there is an issue with this part
>            - effect: NoSchedule
>              key: istio.io/rev=istio-qa
>              operator: Exists
> ```

The `key` field in your sample YAML includes both the key and the value (`istio.io/rev=istio-qa`), which is not valid syntax for K8s tolerations.

You can use `Exists` with just the `key` 
```
  tolerations:
    - effect: NoSchedule
      key: istio.io/rev
      operator: Exists
```
or you can use `Equal` with separate `key` and `value` fields.

```
  tolerations:
    - effect: NoSchedule
      key: istio.io/rev
      operator: Equal
      value: istio-qa
```
