### ISSUE TITLE
Authorization policy not working

### ISSUE THREAD

**Issue by nischay30** [istio/istio#46591]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a below AuthorizationPolicy, which is working with ipBlocks, but now with namespaces or principals, which is very wierd.

This is TLS traffic not HTTPS

Snippet of working policy
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-traffic
  namespace: egress
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks: ["IP of egress gateway Pod"]
    to:
    - operation:
        ports: ['443']
  selector:
    matchLabels:
      istio: egress
```

Snippet of policy which didn't work
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-traffic
  namespace: egress
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespace: ["List of all namespaces"]
    to:
    - operation:
        ports: ['443']
  selector:
    matchLabels:
      istio: egress
```

### Version

```Text
istioctl version:

client version: 1.15.1
control plane version: 1.15.1

kubectl version:
Client Version: v1.23.3
Server Version: v1.24.16
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
