### ISSUE TITLE
Istioctl Analyze not consistently respecting Exports for ServiceEntry used by VirtualService

### ISSUE THREAD

**Issue by Sodman** [istio/istio#46597]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have noticed that when running `istioctl analyze -A` it erroneously reports that my host cannot be found. My basic setup is:
- A ServiceEntry in workspace foo, which is exported to ns bar
- A VirtualService in namespace bar, which is not exported exported to any other namespace.
- The VS routes traffic to the host of the SE.

When I run `istioctl analyze -A` I get the error:
```
$ istioctl Analyze -A
Error [IST0101] (VirtualService bar/foo-route) Referenced host not found: "foobar.staging.mesh"
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/v1.17/docs/reference/config/analysis for more information about causes and resolutions.
```

These are the two resources needed to reproduce this:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-virtualdestination
  namespace: foo
spec:
  hosts:
  - foobar.staging.mesh
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: https
    protocol: HTTP
    targetPort: 80
  resolution: DNS
  exportTo:
    - "bar"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-route
  namespace: bar
spec:
  hosts:
  - foo.foo.svc.cluster.local
  http:
  - name: "foo-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: foobar.staging.mesh
        port:
          number: 80
```

What's interesting is that if I change the SE to export to all `"*"` instead of explicitly to the VS NS `"bar"`, then analyze has no issues:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-virtualdestination
  namespace: foo
spec:
  hosts:
  - foobar.staging.mesh
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: https
    protocol: HTTP
    targetPort: 80
  resolution: DNS
  exportTo:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-route
  namespace: bar
spec:
  hosts:
  - foo.foo.svc.cluster.local
  http:
  - name: "foo-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: foobar.staging.mesh
        port:
          number: 80
```

```
$ istioctl analyze -A
✔ No validation issues found when analyzing all namespaces.
```

Also interesting is that if the VirtualService is exported to the ServiceEntry's namespace, then this also makes analyze happy:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-virtualdestination
  namespace: foo
spec:
  hosts:
  - foobar.staging.mesh
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: https
    protocol: HTTP
    targetPort: 80
  resolution: DNS
  exportTo:
    - "bar"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-route
  namespace: bar
spec:
  exportTo:
  - "foo"
  hosts:
  - foo.foo.svc.cluster.local
  http:
  - name: "foo-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: foobar.staging.mesh
        port:
          number: 80
```

```
$ istioctl analyze -A         

✔ No validation issues found when analyzing all namespaces.
```

### Version

```Text
Istio 1.17.2
```

### Additional Information

Other than the VirtualService and ServiceEntry described above, my environment is a fresh kind cluster with a vanilla `istioctl install -y` run on it, with two namespaces `foo` and `bar`, both of which are injected and each ns running a sample httpbin pod.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
