### ISSUE TITLE
istio-cni does not setup IPv6 redirects when dual-stack is enabled

### ISSUE THREAD

**Issue by adams-shaun** [istio/istio#46625]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When installing istio with istio-cni in dual-stack mode, it seems IPv6 IP tables rules are not being setup correctly.

Steps to repro:

Use helm to install base, cni, istiod on the latest 1.18.2.  Applied the following overrides to enable experimental dual-stack.

```
pilot:
  env:
    ISTIO_DUAL_STACK: "true"

meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_DUAL_STACK: "true"
```

Apply auto-injection label, sleep and dual-stack service as below:

```
kubectl label --overwrite namespace default istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/sleep/sleep.yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simpleserver
---
apiVersion: v1
kind: Service
metadata:
  name: simpleserver
  labels:
    app: simpleserver
    service: simpleserver
spec:
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
  - IPv6
  - IPv4
  ports:
  - name: http
    port: 8090
  selector:
    app: simpleserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleserver
      version: v1
  template:
    metadata:
      labels:
        app: simpleserver
        version: v1
    spec:
      serviceAccountName: simpleserver
      containers:
      - image: quay.io/aspenmesh/simpleserver:dual-stack
        imagePullPolicy: IfNotPresent
        name: simpleserver
        ports:
        - containerPort: 8090
EOF
```

Run curl commands from sleep pod:
```
~ $ curl -4 simpleserver:8090/get
X-Envoy-Attempt-Count: 2
X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/default/sa/simpleserver;Hash=5c757eeb3651e93f7c175ce926849408a7c84f5f63f85fcf78c7fd9c1eecc628;Subject="";URI=spiffe://cluster.local/ns/default/sa/sleep
X-B3-Traceid: cc9e8d4f5549c9c1cad147a708f8e2b7
Accept: */*
X-Forwarded-Proto: http
X-Request-Id: 3f5d845b-c674-44b9-a4c1-97d232226262
User-Agent: curl/8.2.1
X-B3-Spanid: 2c81e3fe71a08c87
X-B3-Parentspanid: cad147a708f8e2b7
X-B3-Sampled: 0
remote addr: 127.0.0.6:35621
host addr: simpleserver:8090
ipv4 handler
~ $ curl -6 simpleserver:8090/get
User-Agent: curl/8.2.1
Accept: */*
remote addr: [fd00:10:244:1::5]:45296
host addr: simpleserver:8090
ipv6 handler
```

Also view the daemonset UDS logs:

```
2023-08-21T18:07:33.822908Z	info	cni	============= Start iptables configuration for sleep-69cfb4968f-r8kj2 =============
2023-08-21T18:07:33.822943Z	info	cni	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=
2023-08-21T18:07:33.822951Z	info	cni	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020,15021,15090
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=15020
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
NETWORK_NAMESPACE=/var/run/netns/cni-3b1a0a84-a6ef-4287-b022-8169330de0c0
CNI_MODE=true
HOST_NSENTER_EXEC=false
EXCLUDE_INTERFACES=
2023-08-21T18:07:33.822960Z	info	cni	Running iptables-restore with the following input:
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2023-08-21T18:07:33.822966Z	info	cni	Running command: iptables-restore --noflush
2023-08-21T18:07:33.822972Z	info	cni	Running ip6tables-restore with the following input:
2023-08-21T18:07:33.822990Z	info	cni	Running command: ip6tables-restore --noflush
2023-08-21T18:07:33.822996Z	info	cni	Running command: iptables-save
2023-08-21T18:07:33.823002Z	info	cni	Command output: 
# Generated by iptables-save v1.8.7 on Mon Aug 21 18:07:33 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon Aug 21 18:07:33 2023
2023-08-21T18:07:33.823008Z	info	cni	============= End iptables configuration for sleep-69cfb4968f-r8kj2 =============
```

Observations:

- simpleserver echoes the request received. For the IPv6 request, it is missing Envoy headers.  The sidecars have been bypassed.
- No ip6tables output in the CNI configuration.  ENABLE_INBOUND_IPV6 is set to false.

Analysis:
The code responsible for determining whether to add ipv6 rules is not aware of environment variables in pilot or injected pods:
https://github.com/istio/istio/blob/master/tools/istio-iptables/pkg/cmd/root.go#L219

This logic functions when using istio-init because the associated environment variable has been injected into the pod.

### Version

```Text
➜  istio-1.18.2 bin/istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (5 proxies)
➜  istio-1.18.2 kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.7
Kustomize Version: v4.5.7
Server Version: v1.24.9
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
➜  istio-1.18.2 helm version --short
v3.11.1+g293b50c
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
