### ISSUE TITLE
Invalid proxy listener config for dual-stack services (1.19)

### ISSUE THREAD

**Issue by adams-shaun** [istio/istio#46633]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I noticed this installing sample workloads in a dual-stack environment on latest 1.19

Setup:

```
#! /bin/bash

VALUES=values.yaml
CWD=$(pwd)
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# install istio
kubectl create ns istio-system
helm install -n istio-system istio-base $CWD/manifests/charts/base

helm install istio-cni $CWD/manifests/charts/istio-cni -n kube-system --set components.cni.enabled=true -f $SCRIPT_DIR/$VALUES
helm install -n istio-system istiod $CWD/manifests/charts/istio-control/istio-discovery -f $SCRIPT_DIR/$VALUES

# install workloads
kubectl create namespace dual-stack
kubectl create namespace ipv4
kubectl create namespace ipv6

kubectl label --overwrite namespace default istio-injection=enabled
kubectl label --overwrite namespace dual-stack istio-injection=enabled
kubectl label --overwrite namespace ipv4 istio-injection=enabled
kubectl label --overwrite namespace ipv6 istio-injection=enabled

kubectl apply --namespace dual-stack -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/tcp-echo/tcp-echo-dual-stack.yaml
kubectl apply --namespace ipv4 -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/tcp-echo/tcp-echo-ipv4.yaml
```

values file:
```
istio_cni:
  enabled: true
sidecarInjectorWebhook:
  injectedAnnotations:
    k8s.v1.cni.cncf.io/networks: istio-cni

pilot:
  env:
    ISTIO_DUAL_STACK: "true"

meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    proxyMetadata:
      ISTIO_AGENT_DUAL_STACK: "true"

global:
  hub: localhost:5000
  tag: istio-testing
  proxy:
    logLevel: info

cni:
# Configuration file to insert istio-cni plugin configuration
# by default this will be the first file found in the cni-conf-dir
# Example
# cniConfFileName: 10-calico.conflist
  logLevel: debug
  # CNI bin and conf dir override settings
  # defaults:
  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d
  cniConfFileName: ""

  excludeNamespaces:
    - istio-system

  # Custom annotations on pod level, if you need them
  podAnnotations: {}

  # If this value is set a RoleBinding will be created
  # in the same namespace as the istio-cni DaemonSet is created.
  # This can be used to bind a preexisting ClusterRole to the istio/cni ServiceAccount
  # e.g. if you use PodSecurityPolicies
  psp_cluster_role: ""

  # Deploy the config files as plugin chain (value "true") or as standalone files in the conf dir (value "false")?
  # Some k8s flavors (e.g. OpenShift) do not support the chain approach, set to false if this is the case
  chained: true

  repair:
    enabled: true
    hub: ""
    tag: ""

    labelPods: true
    deletePods: true

    initContainerName: "istio-validation"

    brokenPodLabelKey: "cni.istio.io/uninitialized"
    brokenPodLabelValue: "true"

  # Experimental taint controller for further race condition mitigation
  taint:
    enabled: false
```

We can see the sidecars never come online due to invalid config, istiod logs:
```
2023-08-22T03:34:14.645293Z    warn    ads    ADS:LDS: ACK ERROR tcp-echo-5dd5786b4f-jbcbx.ipv4-1 Internal:Error adding/updating listener(s) fd00:10:96::320f_90
00: error adding listener: 'fd00:10:96::320f_9000' has duplicate address '[fd00:10:96::320f]:9000,10.96.77.38:9000' as existing listener                        
10.96.241.142_9001: error adding listener: '10.96.241.142_9001' has duplicate address '10.96.241.142:9001,10.96.77.38:9001' as existing listener    
```

Analysis:

- There seems to be an error in the generation code: https://github.com/istio/istio/blob/release-1.19/pilot/pkg/networking/core/v1alpha3/listener.go#L454.  The `listenerOpts.extraBind` is not getting reset between loop iterations.  Reinstantiating the struct per service & port resolved the issue locally. 
- This seems to be resolved on main with the refactor from https://github.com/istio/istio/pull/46227

### Version

```Text
HEAD of release-1.19
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
