### ISSUE TITLE
meshConfig.defaultConfig.sampling is ignored

### ISSUE THREAD

**Issue by gigi206** [istio/istio#46653]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I deploy istio with the following helm parameters:
```yaml
meshConfig:
  enableTracing: true
  defaultConfig:
    sampling: 100.0
    tracing:
      zipkin:
        address: jaeger-collector.jaeger.svc.cluster.local:9411
```

I deploy the bookinfo application:
```bash
kubectl get pod -n bookinfo 
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-5886bc6dd6-l7hq2       2/2     Running   0          16h
productpage-v1-7d478866fd-vk585   2/2     Running   0          16h
ratings-v1-85895fb646-splmq       2/2     Running   0          16h
reviews-v1-7f8d4d8dfd-knz7t       2/2     Running   0          16h
reviews-v2-7ccf74557d-kpgbb       2/2     Running   0          16h
reviews-v3-cc5889b98-f5ws7        2/2     Running   0          16h
```

But we can see that the ramdom sampling is empty despite of the fact that I have set `meshConfig.defaultConfig.sampling` to `100.00` :
```
istioctl pc l productpage-v1-7d478866fd-vk585 -n bookinfo -oyaml | grep randomSampling | head -5
          randomSampling: {}
          randomSampling: {}
          randomSampling: {}
          randomSampling: {}
          randomSampling: {}

```

I need to declare it with Telemetry resource for it works:
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - randomSamplingPercentage: 100
```

```
istioctl pc l productpage-v1-7d478866fd-vk585 -n bookinfo -oyaml | grep randomSampling -A1 | head -14
          randomSampling:
            value: 100
--
          randomSampling:
            value: 100
--
          randomSampling:
            value: 100
--
          randomSampling:
            value: 100
--
          randomSampling:
            value: 100
```

### Version

```Text
istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (11 proxies)


```bash
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.6+rke2r1
Kustomize Version: v4.5.7
Server Version: v1.26.6+rke2r1
```
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
cc @zirain

**Comment by zirain** [comment]
> It looks like `sampling` should be under `tracing` field.

I would say it's same, see https://github.com/istio/istio/blob/130b6c319c9658ae214530e9b1d4cff2861a0e72/pilot/pkg/networking/core/v1alpha3/tracing.go#L123

**Comment by zirain** [comment]
I perfer to respect `defaultConfig.tracing.sampling` then there's no Telemetry API resource.

WDYT? cc @howardjohn @lei-tang

**Comment by gigi206** [comment]
Sorry, there is a mistake in my config, but it seems does not work too with this `meshConfig.defaultConfig.tracing.sampling`:
```yaml
meshConfig:
  enableTracing: true
  defaultConfig:
    tracing:
      sampling: 100.0
      zipkin:
        address: jaeger-collector.jaeger.svc.cluster.local:9411
```
