### ISSUE TITLE
Istio fails resolving wild-card IngressGateway with SSL Termination

### ISSUE THREAD

**Issue by schroedt** [istio/istio#46655]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have an issue equal to [#28849](https://github.com/istio/istio/issues/28849). When **not stating `*` as host**, I get an SSL error and connection does not work. If I add an `*`, traffic works fine.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: application-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.example.de'
        - '*.example2.de'
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*.example.de'
        - '*.example2.de'
        - '*'                                                               << Mandatory setting for being working
      port:
        number: 15002
        name: https-applications
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: istio-ingressgateway-certs
    - hosts:
        - '*.tls.example.de'
        - '*.tls.example2.de'
      port:
        number: 10443
        name: tls-passthrough
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
```

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: "2020-12-23T14:33:08Z"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: istio-controlplane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.7.5
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  clusterIP: 10.97.81.180
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 32656
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 32215
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31398
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp-istiod
    nodePort: 30917
    port: 15012
    protocol: TCP
    targetPort: 15012
  - name: tls
    nodePort: 31523
    port: 15443
    protocol: TCP
    targetPort: 15443
  - name: https-applications                                          <<< Here for termination
    nodePort: 30000
    port: 15002
    protocol: TCP
    targetPort: 15002
  - name: tls-passthrough                                            <<< Here for passthroug
     nodePort: 10443
     port: 10443
     targetPort: 8443
     protocol: TCP
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
```

SSL is via cert-manager, which sets certificate for wildcard:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ****
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: ****
    solvers:
      - dns01:
          cloudflare:
            apiKeySecretRef:
              key: api-key
              name: ***
            email: ****
        selector:
          dnsNames:
            - example.de
            - '*.example.de'
```

The Service is addressed via a `VirtualService`:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vs
  namespace: app
spec:
  hosts:
  - app.example.de
  gateways:
  - istio-system/application-gw
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 8080
        host: app-svc.app.svc.cluster.local
```

### Version

```Text
./istioctl version
client version: 1.17.5
control plane version: 1.17.5
data plane version: 1.17.1 (64 proxies), 1.17.5 (1 proxies)

./istioctl version --short
client version: 1.17.5
control plane version: 1.17.5
data plane version: 1.17.1 (64 proxies), 1.17.5 (1 proxies)
```

### Additional Information

When upgrading from Istio 1.17.5 to Istio 1.18.0/1/2 the same SSL error occurs, even when setting '*' as host.

Please note that I replaced the domain with example.de and example2.de and removed mail-addresses etc.

Connection is:
Browser > Nginx Proxy_Pass > K8s Nodeport > Ingressgateway > Gateway > K8s Workload

**NGinx Logs**
When `*` is configured as host:
```
192.168.191.7 - - [23/Aug/2023:09:16:13 +0000] "GET /K8s/APP-Istio/blob/master/iac/application-gateway.yaml HTTP/2.0" 502 552 "https://app.example.de/K8s/APP-Istio/tree/master/iac" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54"
```

When `*` is removed as host (only `*.example.de`)
```
2023/08/23 09:16:13 [error] 44#44: *32062 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 192.168.191.7, server: example.de, request: "GET /favicon.ico HTTP/2.0", upstream: "https://<node>:<port>/favicon.ico", host: "app.example.de", referrer: "https://app.example.de/K8s/APP-Istio/blob/master/iac/application-gateway.yaml"
192.168.191.7 - - [23/Aug/2023:09:16:13 +0000] "GET /favicon.ico HTTP/2.0" 502 552 "https://app.example.de/K8s/APP-Istio/blob/master/iac/application-gateway.yaml" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54"
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [x] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
