### ISSUE TITLE
First-class support for attaching VirtualServices to Gateway API Gateways

### ISSUE THREAD

**Issue by frankbu** [istio/istio#46662]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Istio is encouraging users to start using Gateway API (k8s Gateway and xxxRoute) instead of the traditional Istio resources (Istio Gateway and VirtualServce) for traffic management wherever possible. This is fine until an Istio feature that is not currently (or may never be) supported in Gateway API is needed. The recommendation is to then use Istio config in that case (at least for now), but it seems that with few exceptions this amounts to an all or nothing proposition.

It is currently possible to attach a VirtualService to a k8s Gateway in cases where a k8s HTTPRoute is missing a needed feature e.g., fault injection. However, to do that, the VirtualService needs to reference the internal underlying Istio Gateway by name:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-headers
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - example-gateway-istio-autogenerated-k8s-gateway-default
  http:
  - match:
    - uri:
        exact: /headers
    fault:
      abort:
        percentage:
          value: 50
        httpStatus: 500
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

This works but is not currently recommended because it relies on details of the internal implementation.

Should we add a first class API for attaching VirtualService to K8s Gateways and document it as a way to configure feature gaps when using Gateway API? For example:

```
  gateways:
  - gateway.networking.k8s.io/example-gateway
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
@keithmattix @costinm for opinions as well

**Comment by frankbu** [comment]
Another maybe crazy idea would be to allow users to annotate an HTTPRoute with extra stuff that should be patched into the generated VirtualService, something like this:

```
kubectl apply -n sample-ingress -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin-headers
  annotations:
    istio.io/gateway-extension: '.spec.http[0].fault={"abort":{"percentage":{"value":50},"httpStatus":500}}'
spec:
  parentRefs:
  - name: example-gateway
  hostnames: ["httpbin.example.com"]
  rules:
  - matches:
    - path:
        type: Exact
        value: /headers
    backendRefs:
    - name: httpbin
      port: 8000
EOF
```

**Comment by keithmattix** [comment]
I honestly didn't know this was a possibility today. From where I stand, it feels like VirtualService is here to stay for the foreseeable future until the Istio project fully embraces Gateway API's policy attachment semantics. If that's the case, I think creating a more user-friendly API makes a lot of sense.  I'm more persuaded by the gateway binding flow rather than annotating HTTPRoute; the latter is all but guaranteed to churn as upstream Gateway API evolves

**Comment by costinm** [comment]
Agreed, no annotations. 

We can create new clean CRDs or adopt CRDs from others, I think it's best to leave VirtualServi ce alone and for users who want stability.

It's not only the attachment - but also the mixing of layers and subtle differences.

IMO at some point it may be worth a clean implementation of gateway API without translation...

**Comment by frankbu** [comment]
> It's not only the attachment - but also the mixing of layers and subtle differences.

@costinm I'm not sure I understand what you're saying. Are you saying that we should not encourage VS attachment to k8s GW, because of potential subtle issues? Problem is users are already getting burned by missing features when they start using Gateway API, as we encourage them to, so I think we need to do something to help with this.

The process to add new features to Gateway API itself is about as slooooowwww as I've ever seen. I've been working on a simple HTTPRoute timeouts GEP since May ... it's close but still not finalized 😞

**Comment by frankbu** [comment]
Some previous discussion on this topic: https://github.com/istio/api/pull/2770#issuecomment-1536667356

Problem is that track 2 `Start to document when and how to use Istio config together with Gateway API config` turns out to be very little can be done to complement k8s config using Istio config (it's mostly all or nothing, as I mentioned above) without depending on the internal implementation details.

Also given the slow progress on track 1, it seem that this problem will persist for a long time (several years at least).

**Comment by howardjohn** [comment]
Some additional concerns:

1. Does this make VirtualService a Route type? Assuming it needs to be represented in Gateway status and supported in spec allowedRoutes
2. 
3. How on earth does conflict resolution work here? What happens when multiple VirtualServices attach to the same GW? What about combining VirtualService + HTTPRoute? What about policy/other things that we expect to work consistently with Routes?

**Comment by frankbu** [comment]
> Does this make VirtualService a Route type? Assuming it needs to be represented in Gateway status and supported in spec allowedRoutes

Yes, I think it should. Proposal: restrict allowedRoutes to only accept VS with exactly one route, others will be rejected. That way, a VS route will account for 1 attachedRoute in the status, just like the k8s routes.

Re: conflict resolution, I think that one should be able to mix and match with k8s routes. Conflicts would work like they do for mutliple VSs in Istio today. We could add that all Istio extension VSs are considered lower priority than the k8s routes, if there are conflicts.

**Comment by keithmattix** [comment]
As a first step to gather user feedback, can we advertise this capability more broadly and maybe even support the alias syntax from the description?

**Comment by frankbu** [comment]
@keithmattix I've been working on some examples but we don't want to publicize the current hacky way of doing it, so I think the first step is to at least get some agreement on a cleaner way to try. I like the idea of making VS just be another kind of Route type 😃

**Comment by frankbu** [comment]
Here's my first attempt at a proposal to get started:

**Proposal:**

1. Extend syntax of `gateways:` field in a `VirtualService` to allow an optional gateway group:

```
"[gateway-group:][namespace/]gateway-name" | "mesh"

gateway-group can be "gateway.networking.k8s.io" or "networking.istio.io" (default)

Examples:

"gateway.networking.k8s.io:default/example-gateway"
"gateway.networking.k8s.io:example-gateway"
"networking.istio.io:default/example-gateway"
"networking.istio.io:example-gateway"
"default/example-gateway"
"example-gateway"
"mesh"
```

2. A `VirtualSevice` can only be attached to a K8s Gateway if the Gateway has explicitly included `VirtualService` in `allowedRoutes.kinds`

3. The `VirtualService` must include exactly 1 route in its spec or it will be rejected

4. If accepted, the VirtualService will account for 1 increment in the corresponding listeners `attachedRoutes` status field

Here's an example of a Gateway with 2 attached routes (i.e., an `HTTPRoute` and a `VirtualService` extension)

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "*.example.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: HTTPRoute
      - kind: VirtualService
        group: "networking.istio.io/v1beta1"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin-get
spec:
  parentRefs:
  - name: example-gateway
  hostnames: ["httpbin.example.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /get
    backendRefs:
    - name: httpbin
      port: 8000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-headers
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - "gateway.networking.k8s.io:example-gateway"
  http:
  - match:
    - uri:
        exact: /headers
    fault:
      abort:
        percentage:
          value: 50
        httpStatus: 500
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```
