### ISSUE TITLE
meshConfig settings do not always get propagated to gateways

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#46686]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using the following install yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
  meshConfig:
    defaultConfig:
      gatewayTopology:
        forwardClientCertDetails: APPEND_FORWARD
        numTrustedProxies: 1
```

I get different values for the 8443 listener of the ingress gateway depending on the namespace that it was installed into.

After installing Istio using istioctl and the following yaml

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpbin-credential # must be the same as secret
    hosts:
    - httpbin.example.com
 ```
I then installed the gateway to an empty httpbin namespace

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty # Do not install CRDs or the control plane
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: httpbin
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
```

Looking at the 8443 listener it showed

```json
                            "streamIdleTimeout": "0s",
                            "useRemoteAddress": true,
                            "forwardClientCertDetails": "SANITIZE_SET",
                            "setCurrentClientCertDetails": {
                                "subject": true,
```

When repeating this for the `istio-system` namespace by installing the gateway to it

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty # Do not install CRDs or the control plane
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
```

I get the following

```json
                            "streamIdleTimeout": "0s",
                            "useRemoteAddress": true,
                            "xffNumTrustedHops": 1,
                            "forwardClientCertDetails": "APPEND_FORWARD",
                            "setCurrentClientCertDetails": {
                                "subject": true,
```

I expected all gateways deployed to get the meshConfig that I deployed and not only the ones in the `istio-system` namespace.

I tested this from 1.14.6 as well and the same pattern exists.

### Version

```Text
$ kubectl version                                                                                                                                                                                                                      Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.11
WARNING: version difference between client (1.28) and server (1.25) exceeds the supported minor version skew of +/-1

$ istioctl version
client version: 1.18.2
control plane version: 1.18.0
data plane version: 1.18.0 (2 proxies)
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
