### ISSUE TITLE
Inconsistency between `istioctl install` and `istioctl install -f`

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio#46714]
Currently, when installing Istio without any overlays, an `installed-state` IOP resource is saved into the cluster. However, when specifying an overlaid IOP using `-f` like the following:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
spec:
  profile: minimal
  hub: hanxiaop
  tag: 1.20
  values:
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: "true"
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        sampling: 100.0

```

The `installed-state` IOP resource is not saved due to a bug that causes it to be unnamespaced when applied. 

I think now is a good time to remove the entire `installed-state` thing from istioctl and fix all other commands, rather than fixing this specific inconsistency.
