### ISSUE TITLE
Strange behavior with outlier ejection and locality load balancing

### ISSUE THREAD

**Issue by panchr** [istio/istio#46724]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am investigating behavior into how Envoy outlier ejection works, specifically as configured through Istio. We observed some inconsistent behavior between testing setups and I wanted to get some clarity on that. This seems either like a bug in how Istio configures Envoy or Envoy itself, which is why I am asking here.
 
Here is our client and server setup:
* 1 client pod, in AZ us-east-1a
* 3 server pods. Each pod is in a different AZ.
  * The server pod in AZ us-east-1a is not reachable over the network—I blocked traffic to it using `iptables` on the Kubernetes node that it runs on (using `sudo nsenter --net=<server pod net namespace> iptables -A INPUT -p tcp -s <client pod IP> -j DROP`). In other words, all TCP packets to it are dropped.
* We have locality load-balancing enabled, so the client pod should solely reach the server pod in the same AZ—again, this is the server pod that is dropping all packets using `iptables`.
* The application code will cancel its request in 5 seconds if it does not receive a response (by closing the TCP connection). When this happens, the proxy logs a Downstream Connection Termination (DC).

In all _other_ testing cases (but not this one), we noticed that with a proxy TCP connection timeout of 5 seconds (see the DestinationRule below) and the application timeout of 5 seconds, outlier ejection is never triggered. This made reasonable sense to us, as it seems that Envoy’s outlier ejection code is not even called for Downstream Connection Termination, even if the TCP connection that the proxy makes to the server pod fails later on (e.g. after the DC). We also tested this with a TCP timeout of 10 seconds, so much greater than the application timeout, and found the same behavior.

For example, we set up a test with 3 server pods per AZ (9 total), and 1 of the server pods in us-east-1a was dropping all traffic with `iptables`. That server pod was never ejected, and the client proxy continued to log timeouts whenever it hit that pod.

I also tested it with 1 server pod per AZ (so 3 pods total), with locality load-balancing disabled, and one of the server pods dropping all traffic with `iptables`. That server pod was never ejected, and the client proxy continued to log timeouts whenever it hit that pod.

With both of those cases, reducing the proxy’s TCP timeout, through the DestinationRule, to be 1 second (e.g. lower than the application timeout), allowed outlier ejection to be triggered.

What is strange about this test case (1 pod per AZ + locality load-balancing _enabled)_ is that after an indeterminate number of TCP connection failures to the server pod, that pod gets ejected for exactly 30 seconds. This is weird because:

* We don’t expect outlier ejection to even occur, based on the other testing I mentioned above.
* When outlier ejection does occur, I would expect it to occur after 3 TCP timeouts to the server pod. We’ve observed it reach 30+ timeouts before the ejection is triggered.
* There are a flood of requests immediately after outlier ejection to the other two pods in the other AZs. This could be application behavior, I’m not certain on it.
* When outlier ejection occurs repeatedly for the same pod, I would expect the duration of the ejection to increase—the first ejection is 30 seconds, the next 60, 90, and then so forth up until 300 seconds.
* We don’t observe any cluster panics; here are the metrics from /stats for this cluster:

```
cluster.outbound|4879||server.server.svc.mesh.lb_healthy_panic: 0
cluster.outbound|4879||server.server.svc.mesh.lb_local_cluster_not_ok: 0
cluster.outbound|4879||server.server.svc.mesh.outlier_detection.ejections_detected_consecutive_5xx: 1
cluster.outbound|4879||server.server.svc.mesh.outlier_detection.ejections_consecutive_5xx: 1
cluster.outbound|4879||server.server.svc.mesh.outlier_detection.ejections_enforced_total: 1
cluster.outbound|4879||server.server.svc.mesh.outlier_detection.ejections_total: 1
```

In this graph, blue lines are the successes and purple lines are TCP timeouts (Envoy response flag 0x4000).
![image](https://github.com/istio/istio/assets/6776539/30ccd857-f1bf-4a02-8f61-9e42c4d745c9)

Here is the server’s DestinationRule:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: server
  namespace: server
spec:
  host: server.server.svc.mesh
  trafficPolicy:
    portLevelSettings:
    - connectionPool:
        http:
          h2UpgradePolicy: DO_NOT_UPGRADE
          http1MaxPendingRequests: 8192
          idleTimeout: 3600s
          maxRetries: 81920
        tcp:
          connectTimeout: 5s
          maxConnections: 8192
      loadBalancer:
        localityLbSetting:
          enabled: true
        simple: ROUND_ROBIN
      outlierDetection:
        baseEjectionTime: 30s
        consecutive5xxErrors: 3
        consecutiveGatewayErrors: 0
        interval: 30s
        maxEjectionPercent: 10
        minHealthPercent: 50
      port:
        number: 4879
      tls:
        mode: ISTIO_MUTUAL
```

### Version

```Text
$ istioctl version
client version: 1.15.5
control plane version: 1.15
data plane version: 1-15-5-patch1 (<...> proxies)

$ kubectl version --short
Client Version: v1.22.15
Server Version: v1.25.8-patch3
WARNING: version difference between client (1.22) and server (1.25) exceeds the supported minor version skew of +/-1
```
```


### Additional Information

_No response_
