### ISSUE TITLE
VirtualService validation fails to detect missing destination cluster

### ISSUE THREAD

**Issue by chlunde** [istio/istio#46722]
### Bug Description

We ran into another issue with VirtualService validation.

The following invalid VirtualService is approved by the webhook validation:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: crash
spec:
  http:
  - corsPolicy:
      allowCredentials: false
      allowHeaders:
      - Cookie
      - X-CSRFToken
      allowMethods:
      - GET
      - DELETE
      allowOrigins:
      - regex: https://.*(bar|foo).example.com
    name: cors-policy
```

But rejected by envoy/XDS push:

```
gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[10]: embedded message failed validation | caused by VirtualHostValidationError.Routes[1]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by RouteActionValidationError.WeightedClusters: embedded message failed validation | caused by WeightedClusterValidationError.Clusters: value must contain at least 1 item(s)):
```

The consequence was that any new VirtualServices after this was created, was not applied.

This is similar to https://github.com/istio/istio/issues/44424

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.18.2
data plane version: 1.17.2 (10 proxies), 1.18.2 (781 proxies)
```

### Additional Information

Workaround: alert on `sum(increase(pilot_total_xds_rejects{app="istiod", namespace="istio-system"}[15m]))>3`

I notice the metric `pilot_xds_rds_reject` comes into existence with value 1, but it does not drop to 0 when the issue is resolved.
