### ISSUE TITLE
error handling /istio-validator-istio-system, retrying (retry count: N): webhook is not ready, retry controller=validation

### ISSUE THREAD

**Issue by apryiomka** [istio/istio#46746]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The sidecar fails to inject with the following error:

> Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": dial tcp 10.0.27.245:15017: i/o timeout

istod reports the following error:
> error handling /istio-validator-istio-system, retrying (retry count: N): webhook is not ready, retry controller=validation

### Version

```Text
istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (10 proxies)
```

### Additional Information

I saw suggestion to hotfix the deployment with `hostNetwork: true`, but it didn't help. We are running in k8s 1.27 in AWS EKS. This is the installation operator manifest:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      extraStatTags:
        - request_host
        - request_operation
        - request_method
  components:
    pilot:
      k8s:
        imagePullPolicy: IfNotPresent
        hpaSpec:
            maxReplicas: 3
            minReplicas: 3
        affinity: 
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: dedicated
                      operator: In
                      values:
                        - infra
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: topology.kubernetes.io/zone
        tolerations:
          - operator: Exists
```
