### ISSUE TITLE
Issue with gateway post upgrade from 1.15.3 to 1.18.1 -- seeking on what changed

### ISSUE THREAD

**Issue by saiharshitachava** [istio/istio#46776]
HI Team,

We recently upgraded istio from 1.15.3 to 1.18.1 along with EKS 1.23 to 1.25 upgrade

The istio gateway config pointing to two virtual services worked perfectly before the upgrade. This broke after the upgrade giving a route not found error
We noticed there was no route for http in the gateway and added it and things started working..
Im trying to understand how it was working before as it was for sure working all these days on 1.15.3 what change in istio exactly triggered this?

Below is the updated gateway yaml but prior upgrade it worked without the http configs

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sample-gw
  namespace: sample
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - sample.abc.com
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - sample.abc.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sample-gw-secret
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
```
