### ISSUE TITLE
Kubernetes Ingress: controller fails to update IP addresses in items.status.loadBalancer if controller service is not deployed in istio-system namespace

### ISSUE THREAD

**Issue by jtv8** [istio/istio#46791]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Replication

1. Follow these steps from https://istio.io/latest/docs/setup/install/helm/:

    ```
    kubectl create namespace istio-system
    helm install istio-base istio/base -n istio-system --set defaultRevision=default
    helm install istiod istio/istiod -n istio-system --wait
    ```

2. Create an ingress gateway as follows.

    **NOTE: The tutorial at https://istio.io/latest/docs/setup/install/helm/ is misleading here - it tells you to install the gateway with the release name `istio-ingress` but this does not match the default value of MeshConfig.ingressService, which is `istio-ingressgateway`.**
    ```
    kubectl create namespace istio-ingress
    helm install istio-ingressgateway istio/gateway -n istio-ingress --wait
    ```

3. Enable sidecar injection and deploy the `httpbin` sample:

    ```
    kubectl label namespace default istio-injection=enabled
    kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/httpbin/httpbin.yaml
    ```

4. Create the sample Ingress from https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/:

    ```
    kubectl apply -f - <<EOF
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.class: istio
      name: ingress
    spec:
      rules:
      - host: httpbin.example.com
        http:
          paths:
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 8000
    EOF
    ```

5. Running `kubectl get ingress ingress -o yaml` will show:
    ```
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    [...]
    status:
      loadBalancer: {}
    ```

Repeating the above steps but deploying the ingress controller to the `istio-system` namespace causes `status.loadBalancer` to be populated correctly:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
[...]
  loadBalancer:
    ingress:
    - ip: 12.34.56.78
```

### Likely cause 

There is no configuration option for setting the ingress controller namespace in `MeshConfig`. It appears only to be configurable via an environment variable here:

https://github.com/istio/istio/blob/d43fc6ccf177479bb9d0466837863800e41b97c5/pilot/pkg/config/kube/ingress/controller.go#L93

and defaults to the value here:

https://github.com/istio/istio/blob/329543c63c34ea9b8e27ec9c914330b16661bf35/pkg/config/constants/constants.go#L71

The Pilot `StatusSyncer` then uses this namespace to attempt to retrieve the service object from the APIServer here:

https://github.com/istio/istio/blob/d43fc6ccf177479bb9d0466837863800e41b97c5/pilot/pkg/config/kube/ingress/status.go#L118

If it fails to find the service at the namespace it is expecting, it fails silently without logging this as an error.

### Workarounds and fixes

In the short term, I suggest updating the docs at https://istio.io/latest/docs/setup/install/helm/ and https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/ to include the following working example of how to set up the ingress gateway controller via Helm:

```
helm install istio-ingressgateway istio/gateway -n istio-system --wait
```

In the longer term, I would suggest either:

1. adding a global mesh configuration value `MeshConfig.ingressNamespace`, or
2. updating `StatusSyncer` to search all namespaces for a service that matches `MeshConfig.ingressService` or `MeshConfig.ingressSelector`.

### Version

```Text
$ istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (2 proxies)
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.3
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor 
version skew of +/-1
$ helm version --short
v3.10.3
```
