### ISSUE TITLE
SSL handshake fails after upgrading from 1.17.5 to 1.18.2

### ISSUE THREAD

**Issue by schroedt** [istio/istio#46794]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Configuration as in [#46655](https://github.com/istio/istio/issues/46655).

When upgrading istioctrl via HELM operator from 1.17.5 to 1.18.2, SSL handshakes fail, **e.g.**:

```
023/08/31 18:20:03 [error] 44#44: *59 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 192.168.2.64, server: example.de, request: "GET /d/vu8e0VWZk/istio-performance-dashboard?orgId=1&refresh=10s HTTP/2.0", upstream: "https://192.168.190.115:30000/d/vu8e0VWZk/istio-performance-dashboard?orgId=1&refresh=10s", host: "app.example.de"
```

Any idea what changed between Istio 1.17.5 and 1.18.2, breaking SSL?

**Configs**

### Istio-Ingressgateway
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: "2020-12-23T14:33:08Z"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: istio-controlplane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.7.5
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  clusterIP: 10.97.81.180
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 32656
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 32215
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31398
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp-istiod
    nodePort: 30917
    port: 15012
    protocol: TCP
    targetPort: 15012
  - name: tls
    nodePort: 31523
    port: 15443
    protocol: TCP
    targetPort: 15443
  - name: https-applications                                          <<< Taking this route
    nodePort: 30000
    port: 15002
    protocol: TCP
    targetPort: 15002
  - name: tls-passthrough
     nodePort: 10443
     port: 10443
     targetPort: 8443
     protocol: TCP
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
```

### Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: application-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.example.de'                            
        - '*.example2.de'
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*.example.de'                              << Taking this route
        - '*.example2.de'
      port:
        number: 15002
        name: https-applications
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: istio-ingressgateway-certs
    - hosts:
        - '*.tls.example.de'
        - '*.tls.example2.de'
      port:
        number: 10443
        name: tls-passthrough
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
```
### Virtual Service
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vs
  namespace: app
spec:
  hosts:
  - app.example.de
  gateways:
  - istio-system/application-gw
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 8080
        host: app-svc.app.svc.cluster.local
```

### Version

```Text
https://hub.docker.com/r/istio/istioctl

istio/istioctl:1.17.5 (works) and istio/istioctl:1.18.2 (breaks)
```

### Additional Information

Routing
1. `Public Internet Browser` to `myFritz-DYNDNS`**:443**
2. `myFritz`**:443** to `192.168.190.64`**:443** (Nginx Proxy_Pass)
3. `192.168.64`**:443** to `192.168.190.100`**:30000** (K8s Nodeport of istio-ingressgateway)
4. `192.168.190.100`**:30000** to `Istio Gateway`**:15002** (application-gw)
5. Istio `VirtualService` to `app-svc.app.svc.cluster.local`**:8080**
6. `app-svc.app.svc.cluster.local`**:8080** to `pod/app`**:8080**
