### ISSUE TITLE
Identical stat config using Telemetry API versus EnvoyFilter causes 10x config size

### ISSUE THREAD

**Issue by CathalC2011** [istio/istio#46858]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello, we recently migrated from configuring stats via EnvoyFilters to Telemetry v2, using the first-class Telemetry resources.

We discovered that identical config (applied to all metrics) resulted in 10x more config with Telemetry than it did using EnvoyFilters.

Take a simple Telemetry resource:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: netshoot
  namespace: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        destination_service:
          value: "CATHAL_TEST_1"
```

Port-forward to any workload on 15000, and inspect a dynamic listener. It results in
```
"configuration": {
"@type": "type.googleapis.com/google.protobuf.StringValue",
"value": "{\"metrics\":[{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"request_messages_total\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"response_messages_total\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"requests_total\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"request_duration_milliseconds\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"request_bytes\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"response_bytes\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"tcp_connections_closed_total\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"tcp_connections_opened_total\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"tcp_received_bytes_total\"},{\"dimensions\":{\"destination_service\":\"CATHAL_TEST_1\"},\"name\":\"tcp_sent_bytes_total\"}]}"
}
```

Versus using an EnvoyFilter which does the exact same thing;
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter-1.15
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.15.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "metrics": [
                      {
                        "dimensions": {
                          "destination_service": "CATHAL_TEST_1"
                        }
                      }
                    ]
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
```

Yet only produces the following config:
```
"configuration": {
"@type": "type.googleapis.com/google.protobuf.StringValue",
"value": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\",\n  \"metrics\": [\n    {\n      \"dimensions\": {\n        \"destination_service\": \"CATHAL_TEST_1\"\n      }\n    }\n  ]\n}\n"
}
```

Both appear to work identically, but the Telemetry approach repeats the config 10 times (I am guessing for each of the 10 Istio traffic metrics, but that's a guess). 

This causes significant additional memory overhead in proxies with a large number of listeners. It also results in significantly increased pressure on Istiod, which has to calculate, store, compress, and distribute that config across the data plane. 

Naturally the impact here is greater in larger clusters.

### Version

```Text
istioctl version                             
client version: 1.15.3
control plane version: 1.17.5
data plane version: 1.17.5 (2 proxies)
```

```
kc version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.24.15
```
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
Thanks for reporting this, it's somehting we should improved.

**Comment by chitvlc** [comment]
Hello,
Same happened when switching from Telemetry V2 to Telemetry API and dropping labels aka `tags` on istio 1.18.2
Istio will generate `tags_to_remove` per metric name:
```
  "name": "istio.stats",
  "typed_config": {
    "@type": "type.googleapis.com/stats.PluginConfig",
    "metrics": [
      {
        "name": "request_messages_total",
        "tags_to_remove": [
          "destination_app",
          "destination_canonical_revision",
          "destination_canonical_service",
          "destination_cluster",
          "destination_principal",
          "destination_service",
          "destination_service_name",
          "destination_service_namespace",
          "destination_version",
          "destination_workload_namespace",
          "grpc_response_status",
          "source_app",
          "source_canonical_revision",
          "source_canonical_service",
          "source_cluster",
          "source_principal",
          "source_version",
          "source_workload_namespace"
        ]
      },
      {
        "name": "response_messages_total",
        "tags_to_remove": [
          "destination_app",
          "destination_canonical_revision",
          "destination_canonical_service",
          "destination_cluster",
          "destination_principal",
          "destination_service",
          "destination_service_name",
          "destination_service_namespace",
          "destination_version",
          "destination_workload_namespace",
          "grpc_response_status",
          "source_app",
          "source_canonical_revision",
          "source_canonical_service",
          "source_cluster",
          "source_principal",
          "source_version",
          "source_workload_namespace"
        ]
      },
``` 
In case of using Telemetry V2 name is missing and only one block of `tags_to_remove` present in configuration for all metrics.
```
 {
    "name": "istio.stats",
    "typed_config": {
      "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
      "type_url": "type.googleapis.com/stats.PluginConfig",
      "value": {
        "metrics": [
          {
            "tags_to_remove": [
              "destination_canonical_service",
              "destination_principal",
              "destination_version",
              "destination_app",
              "destination_cluster",
              "destination_service",
              "destination_service_name",
              "destination_service_namespace",
              "destination_canonical_revision",
              "destination_workload_namespace",
              "source_cluster",
              "source_app",
              "source_version",
              "source_principal",
              "source_workload_namespace",
              "source_canonical_service",
              "source_canonical_revision"
            ]
          }
        ]
      }
    }
  },
``` 
Example config to drop labels using telemetry api:
```
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: ALL_METRICS
            mode: CLIENT_AND_SERVER
          tagOverrides:
            source_app:
              operation: REMOVE
            source_cluster:
              operation: REMOVE
            source_version:
              operation: REMOVE
            source_principal:
              operation: REMOVE
            source_workload_namespace:
              operation: REMOVE
            source_canonical_service:
              operation: REMOVE
            source_canonical_revision:
              operation: REMOVE
            destination_app:
              operation: REMOVE
            destination_cluster:
              operation: REMOVE
            destination_version:
              operation: REMOVE
            destination_principal:
              operation: REMOVE
            destination_service:
              operation: REMOVE
            destination_workload_namespace:
              operation: REMOVE
            destination_canonical_service:
              operation: REMOVE
            destination_canonical_revision:
              operation: REMOVE
            destination_service_name:
              operation: REMOVE
            destination_service_namespace:
              operation: REMOVE
            grpc_response_status:
              operation: REMOVE
```
