### ISSUE TITLE
grpc per method metrics are absent

### ISSUE THREAD

**Issue by smaftoul** [istio/istio#46933]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We want to see grpc per method metrics produced by the envoy grpc_stats filter.
We have been able to produce stats directly with envoy with this configuration:
```
node:
  cluster: service_greeter
  id: test-id

admin:
  #access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9000


static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 8081 }
    filter_chains:
    - filters:     
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager      
          stat_prefix: ingress_grpc
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: 
                  prefix: "/"
                route:
                  cluster: service_grpc
          http_filters:
          - name: envoy.filters.http.grpc_stats
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
              stats_for_all_methods: true
              enable_upstream_stats: true                            
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router        

  clusters:
  - name: service_grpc
    type: static
    connect_timeout: 5s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: service_grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 50052
    common_lb_config:
      healthy_panic_threshold:
        value: 50.0   
```
and a GRPC service  running on `127.0.0.1:50052` , after some grpc request were received, we do see some `envoy_cluster_grpc_ServiceMethod_...` metrics emitted by envoy.

Now we start with a brand new minikube and an up to date istioctl, istio install with either default or preview profile, we just apply a single filter so we have grpc enabled for all methods where grpc_stats filter is enabled, but we don't see the metrics in the envoy dashboard.
We do see in the config dump of the istio proxy that grpc_stats filters are enabled and that `stats_for_all_methods` is changed from false to true, but no new metrics appears.

```
❯ minikube start --driver docker
[...]
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

❯ istioctl install --set profile=preview
This will install the Istio 1.19.0 "preview" profile (with components: Istio core, Istiod, and Ingress gateways) into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                                                                                                                                                                                                             Made this installation the default for injection and validation.

❯ cat filter.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: grpc-stats
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.grpc_stats
      patch:
          operation: MERGE
          value:
            name: envoy.filters.http.grpc_stats
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
              stats_for_all_methods: true
              enable_upstream_stats: true

❯ kubectl apply -f  filter.yaml
envoyfilter.networking.istio.io/grpc-stats created

❯ kubectl run server --port 50051 --image=grpc/java-example-hostname  -l 'sidecar.istio.io/inject=true'
pod/server created

❯ kubectl run -ti go --image=golang  -l 'sidecar.istio.io/inject=true'
If you don't see a command prompt, try pressing enter.
root@go:/go# go install github.com/vadimi/grpc-client-cli/cmd/grpc-client-cli@latest
[...]
root@go:/go# grpc-client-cli 10.244.0.5:50051 # got the IP of the pod by doing manually kubectl get pods elsewhere
? Choose a service: helloworld.Greeter
? Choose a method: SayHello
Message json (type ? to see defaults): {}
{
  "message": "Hello , from server"
}
^C
root@go:/go#
exit
Session ended, resume using 'kubectl attach go -c go -i -t' command when the pod is running

❯ istioctl dashboard envoy server
```

Then we go to either stats or prometheus/stats tab, and no per method grpc metrics there, but given we enabled stats_for_all_methods on all grpc_stats filter instances, and the filter is there, and istio.stats is also there , called after the grpc_stats, we suppose the stats are supposed to be here.

### Version

```Text
$ istioctl version
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (3 proxies)

$ kubectl version --short
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.3
```


### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/12578310/bug-report.tar.gz)
[config_dump.json.gz of server's envoy including istio.stats and grpc_stats filter with stats_for_all_methods enabled](https://github.com/istio/istio/files/12578437/config_dump.json.gz)
