### ISSUE TITLE
Deleting the service that Custom AuthorizationPolicy depends on results in all requests to the gateway being denied

### ISSUE THREAD

**Issue by fatedier** [istio/istio#46951]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Refer to the steps in [External Authorization](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/), but select istio-gateway pods.

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: CUSTOM
  provider:
    name: sample-ext-authz-grpc
  rules:
  - to:
    - operation:
        hosts: ["example.com"]
```

```
  extensionProviders:
  - name: "sample-ext-authz-grpc"
    envoyExtAuthzGrpc:
      service: "ext-authz.foo.svc.cluster.local"
      port: "9000"
  - name: "sample-ext-authz-http"
    envoyExtAuthzHttp:
      service: "ext-authz.foo.svc.cluster.local"
      port: "8000"
      includeRequestHeadersInCheck: ["x-ext-authz"]
```

When I delete the service `ext-authz.foo`, not only `example.com`'s requests is 403, but all gateway requests return 403.

I expect it will only affect requests to `example.com`, not all requests.

### Version

```Text
istio 1.19.0
```
