### ISSUE TITLE
Gateway API's GRPCRoute support

### ISSUE THREAD

**Issue by matiza5** [istio/istio#46976]
Hello,

I see, that PR https://github.com/istio/istio/pull/46336 has been merged on 7th August.
5th of September Istio 1.19 has been released, but I cannot see code from this PR in that release. Will it be included in any patch release soon? Or do we have to wait for 1.20... ? I'm really waiting for that feature for past few months. Any info would be appreciated.

Regards,
Armin

**Comment by zirain** [comment]
@howardjohn looks like merged after branch cut?

**Comment by howardjohn** [comment]
Yes it will be in 1.20. gRPC route is not really critical, you can do everything with HTTPRoute that you can with grpc route

**Comment by matiza5** [comment]
@howardjohn do you mean, that I can pass GRPC traffic over HTTPRoute and handle i.e. routing by GRPC method with HTTPRoute?

**Comment by howardjohn** [comment]
Yes, GRPC is a type of HTTP. grpc route is just to make it more ergonomic

**Comment by zirain** [comment]
feel free to reopen.

**Comment by matiza5** [comment]
-- Reopening

Hi again.

We now have isito 1.20 with GRPCRoute support. But it seems it does not work.
I have installed Gateway-API CRDs in latest v1.0.0 and Istio 1.20.0.
This is my gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
    networking.gke.io/load-balancer-type: Internal
  name: gateway-private
  namespace: istio-ingress
spec:
  addresses:
  - type: IPAddress
    value: 10.x.x.x
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.labs.internal.example.com'
    name: labs-internal-example-com-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: labs-internal-example-com-tls
      mode: Terminate
status:
  addresses:
  - type: IPAddress
    value: 10.x.x.x
  conditions:
  - lastTransitionTime: "2023-11-27T09:31:42Z"
    message: Resource accepted
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2023-11-27T09:32:51Z"
    message: Resource programmed, assigned to service(s) gateway-private-istio.istio-ingress.svc.cluster.local:443
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
  listeners:
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2023-11-27T09:31:42Z"
      message: No errors found
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2023-11-27T09:31:42Z"
      message: No errors found
      observedGeneration: 1
      reason: NoConflicts
      status: "False"
      type: Conflicted
    - lastTransitionTime: "2023-11-27T09:31:42Z"
      message: No errors found
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2023-11-27T09:31:42Z"
      message: No errors found
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    name: labs-internal-example-com-https
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
```

and my `GRPCRoute`:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpc-hostname-service
  namespace: default
spec:
  hostnames:
  - grpc-test.labs.internal.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-private
    namespace: istio-ingress
    sectionName: labs-internal-example-com-https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: grpc-hostname-service
      port: 50051
      weight: 1

```
As you can see, there is `attachedRoutes: 0` in `Gateway` and no `status:` section in `GRPCRoute` (this is full listing). When I'm changing `GRCPRoute` to `HTTPRoute` and `v1alpha2` to `v1beta1` to "convert" it - after applying everything works perfectly - meaning all the `parentRefs` are correct. Maybe I'm missing something... ? I have `PILOT_ENABLE_ALPHA_GATEWAY_API: true` ENV set for istio discovery, dunno if it's required, but it is there.

In istio discovery logs I can see only this, nothing more regarding my `GRPCRoute`:
```
2023-11-26T20:46:01.665390Z	info	ads	Push debounce stable[18] 1 for config GRPCRoute/default/grpc-hostname-service: 100.287201ms since last change, 100.287038ms since last push, full=true
```

Additionaly - I have tested proposal for using HTTPRoute instead of GRPCRoute. This are the results:
```bash
$ grpcurl -proto hostname_service.proto grpc-test.labs.internal.example.com:443 hostname.HostnameService/EchoHostname
ERROR:
  Code: Unavailable
  Message: upstream connect error or disconnect/reset before headers. reset reason: protocol error

```
It works, when I'm trying the same from inside of a cluster:
```bash
$ grpcurl -plaintext -proto proto.proto grpc-hostname-service:50051 hostname.HostnameService/EchoHostname                           
{
  "hostname": "grpc-hostname-service-775ddbdfcd-sdvsw"
}

```

Could you please help me somehow? I'm stuck here and I need to deliver working solution for exposing GRPC traffic on L7. I don't want to abandon Istio, but support for exposing GRPC over L7 with TLS is essential for me.

Thanks!

**Comment by matiza5** [comment]
Update (SOLVED):

I found out that I was missing one thing: `name: grpc` on the kubernetes service. With named port everything starts working... I found it by accident. I looked through Istio docs and I couldn't find any info about it.
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-hostname-service
spec:
  selector:
    app: grpc-hostname-service
  ports:
    - name: grpc  # <------------ THIS LINE
      protocol: TCP
      port: 50051
      targetPort: 50051
```
