### ISSUE TITLE
Cannot configure ingress-gateway to route to external service (using K8S Gateway API)

### ISSUE THREAD

**Issue by paul-bormans** [istio/istio#46986]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When we expose a service using an HTTPRoute / Gateway (obviously using istio ingress-gateway as the ingress-controller) we get a TLS error when accessing:

```
[2023-09-13T11:03:10.367Z] "GET / HTTP/2" 503 UF,URX upstream_reset_before_response_started{connection_failure,TLS_error:_268435703:SSL_routines:
OPENSSL_internal:WRONG_VERSION_NUMBER} - "TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER" 0 213 117 - "10.10.0.88" 
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" 
"d880995c-fdb5-4820-b6ea-9599996d0b90" "prometheus.my-domain.com" "10.101.6.145:9090" 
outbound|9090||prometheus-k8s.monitoring.svc.cluster.local - 10.101.14.113:8443 10.10.0.88:52916 prometheus.my-domain.com monitoring.prometheus.0
```

This error can be reproduced by spinning a curl pod (next to the ingress-gateway) and issue a request.
Since the svc is not running inside the mesh this kind of makes sense since istio is handling the traffic and connection fails on the handshake. On the curl pod this can easily be solved in two ways:
1 - traffic.sidecar.istio.io/excludeOutboundPorts: "9090"
2 - with a ServiceEntry:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: prometheus-egress
  namespace: istio-ingress
spec:
  hosts:
  - prometheus-k8s.monitoring.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 9090
    protocol: HTTP
  resolution: DNS
```
Both solutions have proven to work for the curl pod and obviously the ServiceEntry is the preferred solution.
That solution however does not work for the ingress-gateway; it keeps raising the same SSL error.
Also when inspecting the pc (istioctl-1.17.5 pc all <podname>) there doesn't seem to be a difference in routing configuration with or without the ServiceEntry (while there are differences for the curl pod pc).

A note on the external service; this pod (prometheus) does have a sidecar but it's configured to not handle any traffic (this is to have access to istio crt's to scrape metric target both in and outside the mesh).

Notice we found a guide (https://istio.io/latest/blog/2019/proxy/) but that is using VirtualService while those are generated when using K8S Gateway API.

Our questions:
- What is the expected impact to the proxy-config when setting ServiceEntry?
- How can we inspect the generated virtual-service?
- And offcourse: where is the mistake, how to fix?

### Version

```Text
(base) ➜  dpng istioctl-1.17.5 version
client version: 1.17.5
istiod version: 1.17.5
istiod version: 1.17.5
istiod version: 1.17.5
istiod version: 1.18.2
istiod version: 1.18.2
istiod version: 1.18.2
data plane version: 1.17.5 (135 proxies), 1.18.2 (6 proxies)
(base) ➜  dpng kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3-gke.1700
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/12606494/bug-report.tar.gz)

**Comment by paul-bormans** [comment]
I just found that the error can be solved by:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus-outbound
  namespace: istio-ingress
spec:
  host: prometheus-k8s.monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```
Obviously HTTP outbound isn't really the way to go but at least i git rid of the SSL error :-).
