### ISSUE TITLE
Envoyfilter filterChain sni not working

### ISSUE THREAD

**Issue by jgournet** [istio/istio#47004]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Following the suggestions from https://github.com/istio/istio/issues/10543, I tried this EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: web-customize-authz-response
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          sni: test.mydomain.com
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          local_reply_config:
            mappers:
            - filter:
                status_code_filter:
                  comparison:
                    op: EQ
                    value:
                      default_value: 503
                      runtime_key: placeholder
              status_code: 503
              body:
                inline_string: customized_authz_deny_response
              body_format_override:
                text_format: "<h1>%LOCAL_REPLY_BODY% %RESPONSE_CODE% %REQ(:path)%</h1>"
                content_type: "text/html; charset=UTF-8"
```

*issue:*
- when we remove "sni: test.mydomain.com" and set deployment to 0, it works fine: we get the desired output instead of "no healthy upstream".
- when we use that "sni: test.mydomain.com": we get "no healthy upstream".

We have checked that "test.mydomain.com" is indeed the "authority" received in istio logs.

### Version

```Text
istio version: 1.18.2


kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.4-eks-2d98532
```
```


### Additional Information

(not attaching too much information yet, as this "sounds" fairly easy to reproduce - I will attach more if it turns out we're the only ones affected)
