### ISSUE TITLE
Dual-stack: Envoy readiness probes are not reachable on both v4 and v6 endpoints

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#47013]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

DS IPv4-first clusters: http request to IPV6_POD_IP:15021/healthz/ready of istio-proxy fails
DS IPv6-first clusters: http request to IPV4_POD_IP:15021/healthz/ready of istio-proxy fails

Here are steps to reproduce:

1. Obtain a DS cluster using Kind (the default Ip-family is not important for the verification). I used a DS Kind cluster with IPv4 as default.
2. Deploy Istio SM with DS enabled.

```
istioctl install --set profile=demo -f DS_operator.yaml
DS_operator.yaml is as follows:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
   components:
      pilot:
         k8s:
            env:
               - name: ISTIO_DUAL_STACK
                 value: "true"
   meshConfig:
      defaultConfig:
         proxyMetadata:
            ISTIO_DUAL_STACK: "true"
```

3. Deploy sleep by using kubectl apply -f https://github.com/istio/istio/blob/master/samples/sleep/sleep.yaml -n istio-system

Obtain the two pod ips of ingress gw
```
kubectl get pods $ingress_gw_pod -n istio-system -o yaml
Example:
  podIP: 10.244.0.13
  podIPs:
  - ip: 10.244.0.13
  - ip: fd00:10:244::d
 ```

4. Contact the healthz readiness endpoints of the ingress gw.The request using the pod ip matching the default family of your cluster will work, the other will fail.

```
kubectl exec $sleep_pod -n istio-system -it -- curl ingressgw_pod_ip_ipv4:15021/healthz/ready -v
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Fri, 17 Mar 2023 13:18:05 GMT
< content-length: 0
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host 10.244.0.13 left intact
kubectl exec $sleep_pod -n istio-system -it -- curl [ingressgw_pod_ip_ipv6]:15021/healthz/ready -v
*   Trying fd00:10:244::d:15021...
* TCP_NODELAY set
* connect to fd00:10:244::d port 15021 failed: Connection refused
* Failed to connect to fd00:10:244::d port 15021: Connection refused
* Closing connection 0
curl: (7) Failed to connect to fd00:10:244::d port 15021: Connection refused
command terminated with exit code 7
```

### Version

```Text
$ istioctl version
client version: 1.20-alpha.f7393dd36802a2c40b4efe60895213de87badbf7
control plane version: 1.20-alpha.b52a510c0d5a8f9e5b54f8f8bb0db2f679f11c18
data plane version: 1.20-alpha.b4b2fb49082f8416cffa40f723e2293ffbdad050 (5 proxies), 1.20-alpha.b52a510c0d5a8f9e5b54f8f8bb0db2f679f11c18 (1 proxies)
```
