### ISSUE TITLE
Unable to create Wasm HTTP filter

### ISSUE THREAD

**Issue by apryiomka** [istio/istio#47042]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Following he configuration from here: https://cloudnative.to/istio.io/docs/tasks/observability/metrics/customize-metrics/ and here: https://cloudnative.to/istio.io/docs/tasks/observability/metrics/classify-metrics/ to add extra dimensions to our istio metrics that include: host, request method (GET, POST, PUT, ...) and request path.

I am getting the error trying to apply the fileter on the sidecar:

```
2023-09-19T20:31:24.139960Z	error	envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:109	Wasm VM failed Failed to load NullVM plugin	thread=20
2023-09-19T20:31:24.140013Z	error	envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:109	Wasm VM failed Failed to load Wasm code	thread=20
2023-09-19T20:31:24.140020Z	critical	envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:474	Plugin configured to fail closed failed to load	thread=20
2023-09-19T20:31:24.140619Z	warning	envoy config external/envoy/source/common/config/grpc_subscription_impl.cc:128	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to create Wasm HTTP filter
```

the sidecar never loads or succeeds and remains in not ready state indefinitely until the filter is deleted:

```
2023-09-19T20:32:05.558648Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2023-09-19T20:32:07.557763Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```

Similar error can be seen in the `istiod`:

```
2023-09-19T20:30:59.255345Z	warn	ads	ADS:LDS: ACK ERROR ezpass-64d4c7f6f8-98bxj.ezpass-5285 Internal:Error adding/updating listener(s) virtualInbound: Unable to create Wasm HTTP filter
```

Some other errors from the 

### Version

```Text
istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (10 proxies)
```

### Additional Information

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      extraStatTags:
        - request_host
        - request_operation
        - request_method
  components:
    pilot:
      k8s:
        strategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        imagePullPolicy: IfNotPresent
        hpaSpec:
            maxReplicas: 3
            minReplicas: 2
        affinity: 
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: dedicated
                      operator: In
                      values:
                        - infra
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: topology.kubernetes.io/zone
        tolerations:
          - operator: Exists
    ingressGateways:
      - name: istio-ingressgateway
        label:
          app: istio-ingressgateway
          istio: ingressgateway
        enabled: true
        k8s:
          imagePullPolicy: IfNotPresent
          hpaSpec:
            maxReplicas: 1000
            minReplicas: 10
          podDisruptionBudget:
            minAvailable: 5
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: tls
                port: 15443
                protocol: TCP
                targetPort: 15443
  values: # https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_operation: clean_path
                    request_host: request.host
                    request_method: request.method
            gateway:
              disable_host_header_fallback: true
              metrics:
                - name: requests_total
                  dimensions:
                    request_operation: clean_path
                    request_host: request.host
                    request_method: request.method
```
applying envoy filter breaks the sidecar
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: attributegen-filter
spec:
  workloadSelector:
    labels:
      app: ezpass
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        proxy:
          proxyVersion: '1\.18.*'
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "istio.stats"
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.attributegen
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            value:
              config:
                configuration:
                  "@type": type.googleapis.com/google.protobuf.StringValue
                  value: |
                    {
                      "attributes": [
                        {
                          "output_attribute": "clean_path",
                          "match": [
                            {
                              "value": "root",
                              "condition": "request.url_path == '/'"
                            },
                            {
                              "value": "/healthz",
                              "condition": "request.url_path == '/healthz'"
                            }
                          ]
                        }
                      ]
                    }
                vm_config:
                  runtime: envoy.wasm.runtime.null
                  code:
                    local: { inline_string: "envoy.wasm.attributegen" }
```
