### ISSUE TITLE
Istiod is in CrashBackLoop after setting global logLevel in Helm Chart

### ISSUE THREAD

**Issue by teimyBr** [istio/istio#47069]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When setting this: 

This Settings i have added to the istio values.
```
global:
  logging:
    level: "default:warning"
  proxy: 
    logLevel: warning
    componentLogLevel: "misc:error"
```

The Istiod is in CrashBackLoop with this log

`Error: invalid output level 'default:warning'2023-09-21T13:39:43.292185Z    error    invalid output level 'default:warning'`

https://artifacthub.io/packages/helm/istio-official/istiod?modal=values This settings i found here

### Version

```Text
istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (628 proxies)
```
