### ISSUE TITLE
Istio VM http2 connection ALPN: server did not agree on a protocol.

### ISSUE THREAD

**Issue by xyphanajay** [istio/istio#47064]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am running Istio VM as router for handling edge requests as reverse proxy. I am using envoyfilter for configurating http listeners. I am configuring `codec_type: AUTO` with https TLS certs. When I am making curl call with `--http2` flag, envoy is ending up with `http1.1` connection only.

Sample curl call
```
$ curl https://abc.net/abc/info --resolve abc.net:443:10.xx.xx.43 -vl --http2
* processing: https://abc.net/abc/info
* Added abc.net:443:10.xx.xx.43 to DNS cache
* Hostname abc.net was found in DNS cache
*   Trying 10.xx.xx.43:443...
* Connected to abc.net (10.xx.xx.43) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.abc.net
*  start date: Apr 10 00:00:00 2023 GMT
*  expire date: May  2 23:59:59 2024 GMT
*  subjectAltName: host "abc.net" matched cert's "*.abc.net"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /xyz/info HTTP/1.1
> Host: abc.net
> User-Agent: curl/8.2.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< content-type: application/json;charset=utf-8
< date: Thu, 21 Sep 2023 11:50:14 GMT
< x-envoy-upstream-service-time: 0
< vary: Accept-Encoding
< server: envoy
< transfer-encoding: chunked
<
* Connection #0 to host abc.net left intact
```

Envoyfilter listener:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: listener-https
  namespace: envoy
  labels:
    app: envoy
spec:
  workloadSelector:
    labels:
      app: envoy
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: "https_listener"
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 80
        filter_chains:
        - filters:
          - name: "envoy.filters.network.http_connection_manager"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              codec_type: AUTO
              stat_prefix: ingress
              use_remote_address: true
              normalize_path: true
              merge_slashes: true
              path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
              common_http_protocol_options:
                idle_timeout: 300s
                headers_with_underscores_action: REJECT_REQUEST
              http2_protocol_options:
                max_concurrent_streams: 100
                initial_stream_window_size: 65536
                initial_connection_window_size: 1048576
              stream_idle_timeout: 300s
              request_timeout: 300s
              generate_request_id: false # enable with tracing
              ## access log config
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/var/log/istio/envoy-http-2xx.log"
              route_config:
                name: cluster_route
                request_headers_to_add:
                  - header:
                      key: X-Client-IP
                      value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                  - header: 
                      key: X-Proxy
                      value: "envoy"
                  - header: 
                      key: X-Request-Start
                      value: "%START_TIME(%s.%3f)%"
                virtual_hosts:
                - name: "local_hosts"
                  domains: 
                    - abc.net
                  routes:
                  - match:
                      prefix: "/abc/"
                    route:
                      cluster: "outbound|8080|common|common.abc.svc.cluster.local"
                      timeout: 0.4s
                      max_stream_duration:
                        max_stream_duration: 0s
                  - match:
                      prefix: "/"
                    direct_response:
                      status: 204
              http_filters:
              - name: envoy.filters.http.decompressor
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
                  decompressor_library:
                    name: envoy.compression.gzip.decompressor
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip
                  request_direction_config:
                    common_config:
                      enabled:
                        default_value: true
                        runtime_key: request_decompressor_enabled
              - name: envoy.filters.http.compressor
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                  request_direction_config:
                    common_config:
                      enabled:
                        default_value: false
                        runtime_key: request_compressor_enabled
                  compressor_library:
                    name: for_response
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                      memory_level: 3
                      window_bits: 10
                      compression_level: BEST_COMPRESSION
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
                  default_source_code:
                    inline_string: |
                      function envoy_on_request(request_handle)
                        -- some lua logic
              local_reply_config:
                mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: GE
                        value:
                          default_value: 300
                          runtime_key: "non_2xx_status_code"
                  status_code: 204
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain: { filename: "/etc/certs/abc.net.crt" }
                    private_key: { filename: "/etc/certs/abc.net.key" }
```

### Version

```Text
$ istioctl version
client version: 1.13.1
control plane version: 1.16.1
data plane version: 1.16.1 (265 proxies)

$ kubectl version --short
Client Version: v1.24.16
Kustomize Version: v4.5.4
Server Version: v1.24.14-gke.1200

$ envoy --version
envoy  version: 3c27a1b0cf381ca854ccc3a2034e88c206928da2/1.26.4-dev/Clean/RELEASE/BoringSSL
```

### Additional Information

I am trying to get http2 requests on envoy from downstream. Downstream supports http2 connections but somehow with envoy it is ending up with http1.1 connection.

**Comment by hzxuzhonghu** [comment]
You should set AlpnProtocols within the envoyfilter 

```
              common_tls_context:
                alpn_protocols: ["h2", "http/1.1"]
                tls_certificates:
                  - certificate_chain: { filename: "/etc/certs/abc.net.crt" }
                    private_key: { filename: "/etc/certs/abc.net.key" }
```
