### ISSUE TITLE
grpc server/client with custom TLS not working with mTLS strict mode

### ISSUE THREAD

**Issue by janekmichalik** [istio/istio#47078]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have Istio mTLS STRICT mode enabled on my cluster (at global level). I also have two grpc pods, one server, one client. The client must use python authzed client to talk to grpc server, it means that it requires custom TLS configuration (self-signed in my case) during client init. In this case I the client is not able to communicate with the grpc server due to:

```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.43.208.154:50051: Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.43.208.154:50051: Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {grpc_status:14, created_time:"2023-09-21T21:54:52.536158426+00:00"}"
```

**is this supported at all?**

I have also tried to disable mTLS for the grpc server, so I can use this custom TLS and skip istio mTLS

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: custom-tls
  namespace: prod
spec:
  host: spice-db.prod.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
  workloadSelector:
    matchLabels:
      app: spicedb
```

but the same result with destination rule. I have also tried other destination rules with SIMPLE mode, same result. I was also trying with peer authentication (DISABLE, PERMISSIVE) but got socket closed or wrong version number errors.

As far as I understand Istio mTLS, I should be able to configure STRICT mode for case, when two pods are communicating via custom TLS, right?

### Version

```Text
root@<hidden>:~# istioctl version
client version: 1.18.1
control plane version: 1.18.1
data plane version: 1.18.1 (44 proxies)

root@<hidden>:~# kubectl version --short
Client Version: v1.25.11+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.11+k3s1
```
