### ISSUE TITLE
Cannot connect to external services on port 443 if a service names it something different from https

### ISSUE THREAD

**Issue by hflobao** [istio/istio#47088]
I've faced this situation both in istio 1.13.2 (k8s 1.23) and 1.18.0 (k8s 1.27).

If someone creates an service with port 443 and name it other than https, like the example below, any pod with sidecar injected cannot connect to external URLs on this port.

```
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: grpc    <<------------
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: ClusterIP
```

With this configuration in place on the cluster, the following behavior can be seen:

- Connection to external services on port 443 get error 404. It seems that the envoy in the sidecar tries to find the name locally in the cluster:
```
[root@my-deploy-c4c969f94-b6pqz ~]# curl -kv https://github.com
* Uses proxy env variable https_proxy == 'http://proxy.sig.umbrella.com:443'
*   Trying 146.112.50.46:443...
* Connected to proxy.sig.umbrella.com (146.112.50.46) port 443 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to github.com:443
> CONNECT github.com:443 HTTP/1.1
> Host: github.com:443
> User-Agent: curl/7.76.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 404 Not Found        <<------------------
< date: Fri, 22 Sep 2023 19:33:23 GMT
< server: envoy                 <<------------------
< connection: close
< content-length: 0
<
* Received HTTP code 404 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 404 from proxy after CONNECT
```

- The output from istioctl proxy-config listener shows an routing entry for the 0.0.0.0:443
```
ADDRESS         PORT  MATCH                                       DESTINATION
172.20.0.10     53    ALL                                         Cluster: outbound|53||kube-dns.kube-system.svc.cluster.local
0.0.0.0         80    Trans: raw_buffer; App: http/1.1,h2c        Route: 80
0.0.0.0         80    ALL                                         PassthroughCluster
172.20.161.184  80    Trans: raw_buffer; App: http/1.1,h2c        Route: grafana.observability.svc.cluster.local:80
172.20.161.184  80    ALL                                         Cluster: outbound|80||grafana.observability.svc.cluster.local
172.20.241.10   80    ALL                                         Cluster: outbound|80||kubecost-grafana.kubecost.svc.cluster.local
0.0.0.0         443   Trans: raw_buffer; App: http/1.1,h2c        Route: 443    <<-----------------
0.0.0.0         443   ALL                                         PassthroughCluster
```

Right after renaming the port to https in the service, the routing entry in the listener output is gone and the pods resume access to the external services.

My questions are: 
- Is this by design? Or an issue to be fixed...
- Why it happens?

Thanks a lot!
