### ISSUE TITLE
Security Design Flaw: ServiceEntry and request hijacking

### ISSUE THREAD

**Issue by kdorosh** [istio/istio#47106]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Opening this github issue to track the request hijacking flaw outlined in this [design doc](https://docs.google.com/document/d/1uDWoWxHyMCE4oUc-nTJPfVoQyikZP-UMp-_BrAA-PQE)

Shortest repro:

```yaml
# apply this config to ns2, then we can break pre-existing traffic in ns1
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se1
  namespace: ns2
spec:
  addresses:
  - 240.240.1.1
  hosts:
  - google.com
  ports:
  - name: http
    number: 80
    protocol: HTTP
  workloadSelector:
    labels:
      app: helloworld
```

Can hijack traffic to google.com in other namespaces beyond workloads in ns1.

Fix is to change service resolution behavior, but in a backwards compatible way. The suggestion is solution 2 in the originally linked design doc. I opened an [istio/api PR](https://github.com/istio/api/pull/2935) for TOC to look at

### Version

```Text
latest istio, e.g. https://github.com/solo-io/istio/tree/c40184f1a1cf10413a61f56e555e2def29605c00
```
