### ISSUE TITLE
matchSubjectAltNames in UpstreamTlsContext is being rendered with default service SA in multicluster setup

### ISSUE THREAD

**Issue by apolovov** [istio/istio#47130]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

* There is sofisticated setup of four clusters combined in a multicluster mesh (baremetal setup):
  * `foo-a`
  * `foo-b`
  * `bar-a`
  * `bar-b`
* There is a HTTP-service `myapp.myns.svc` in clusters `bar-a` and `bar-b` with ServiceAccount `myapp`. (And numbers of similar services). Clients are in `foo-a` and `foo-b` clusters.
* Every cluster has four ingressgateways. Recently, we had to eliminate a single ingressgateway of cluster `bar-a`, so we excluded the gateway from `meshNetworks` config of other clusters. (We use istio-operator and IstioOperator resources to deploy istiod).
* After excluding the gateway, we faced lots of TLS errors from `myapp` clients (`upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`).
* During investigation, we found that envoy cluster config of `myapp` on client side was rendered incorrectly. Here is the diff before/after:
```
           combinedValidationContext:
             defaultValidationContext:
               matchSubjectAltNames:
-              - exact: spiffe://cluster.local/ns/myns/sa/myapp
+              - exact: spiffe://cluster.local/ns/myns/sa/default
             validationContextSdsSecretConfig:
               name: ROOTCA
               sdsConfig:
```
* After `myapp` was rollout-restarted, everything was fixed.
* The issue happened again after including the ingressgateway to the list of gateways.

Unfortunately, we can't reproduce the issue on stage clusters, and obtaining permission to debug the problem in production is nearly impossible :(.

### Version

```Text
# ./istioctl version
client version: 1.19.0
control plane version: 1.16.2
data plane version: 1.16.2 (XXX proxies)
# kubectl version --short
Client Version: v1.23.17
Server Version: v1.23.17
```
