### ISSUE TITLE
Waypoint/zTunnel L4 Authz Policy Edge Case

### ISSUE THREAD

**Issue by ymesika** [istio/istio#47137]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Today when a waypoint exists the ztunnel does not enforce authz policies.
However, the authz policies with/without waypoint have different selectors:

L4 authz policy without a waypoint:

```yaml
selector:
    matchLabels:
      app: helloworld
```

L4/L7 authz policy with a waypoint:

```yaml
selector:
    matchLabels:
      istio.io/gateway-name: helloworld
```

This difference in the selector raises problematic edge cases where user has a L4 authz policy (without a waypoint) and deploys a waypoint. In this case the existing authz policy isn't enforced by the waypoint.

### Version

```Text
1.19.0
```
