### ISSUE TITLE
Multiple headers in VirtualService http match create wrong envoy config

### ISSUE THREAD

**Issue by florianmutter** [istio/istio#47148]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Creating a virtual service with this rule:

```yaml
spec:
  gateways:
  - staging/default-gateway
  hosts:
  - example.com
  http:
  - delegate:
      name: service-b
      namespace: default
    match:
    - headers:
        cookie:
          regex: ^.*remotedev=flo.*$
    - headers:
        remotedev:
          exact: flo
```

Creates an envoy config that looks like this:

```json
       {
        "name": "example.com:443",
        "domains": [
         "example.com"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true,
           "headers": [
            {
             "name": "cookie",
             "string_match": {
              "safe_regex": {
               "regex": "^.*remotedev=flo.*$"
              }
             }
            },
            {
             "name": "remotedev",
             "string_match": {
              "exact": "flo"
             }
            }
           ]
          },
          "route": {
           "cluster": "outbound|8088||service-b.default.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/instore/virtual-service/servicepoint-ui"
            }
           }
          },
          "decorator": {
           "operation": "service-b.default.svc.cluster.local:8088/*"
          },
          "name": "remotedev-flo"
         },
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true,
           "headers": [
            {
             "name": "cookie",
             "string_match": {
              "safe_regex": {
               "regex": "^.*remotedev=flo.*$"
              }
             }
            },
            {
             "name": "remotedev",
             "string_match": {
              "exact": "flo"
             }
            }
           ]
          },
          "route": {
           "cluster": "outbound|8088||service-b.default.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/instore/virtual-service/servicepoint-ui"
            }
           }
          },
          "decorator": {
           "operation": "service-b.default.svc.cluster.local:8088/*"
          },
          "name": "remotedev-flo"
         },
```

So we end up with two identical rules that require both headers.

### Version

```Text
$ istioctl version
client version: 1.19.0
istiod version: 1.19.0
data plane version: 1.19.0 (6 proxies)
$ kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.7-gke.500
```

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by ramaraochavali** [comment]
Can you please share the delegate VS also?

**Comment by florianmutter** [comment]
Here is the yaml of the VS that we delegate to:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-b
  namespace: default
spec:
  http:
  - match:
    - uri:
        prefix: /
    retries:
      attempts: 0
    route:
    - destination:
        host: service-b
        port:
          number: 8088

```
