### ISSUE TITLE
Too strict validation of CUSTOM policy?

### ISSUE THREAD

**Issue by chlunde** [istio/istio#47157]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi, we had a cluster running without webhook validation, and a CUSTOM AuthorizationPolicy was created:

```yaml
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: custom
spec:
  action: CUSTOM
  provider:
    name: custom
  rules:
    - from:
        - source:
            namespaces:
              - istio-system
            principals:
              - cluster.local/ns/istio-system/sa/...
```

This worked fine (only ingress traffic was required to pass this check).

However, when we fixed the webhook, the policy was rejected:

```
admission webhook "validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:
        * invalid policy custom.ns: From.Namespaces is currently not supported with CUSTOM action
        * invalid policy custom.ns: From.Principals is currently not supported with CUSTOM action
```

https://github.com/istio/istio/blob/b2ce487107adac695163d2fa577b2994c59a9ebf/pkg/config/validation/validation.go#L2007-L2023

Is the validation too strict, this works as expected? It looks like the validation has not been changed since the initial commit by @yangminzhu

### Version

```Text
1.18.3
```
