### ISSUE TITLE
Add possibility of adding condition when CUSTOM auth policy has been used

### ISSUE THREAD

**Issue by chlunde** [istio/istio#47219]
**Describe the feature request**
When using a CUSTOM authorization policy in a setup with a default empty AuthorizationPolicy (i.e. deny all by default), you must also crease an identical ALLOW policy. If there are any conditions, like `methods` or `hosts`, they must be duplicated.

This introduces a possible security issue if the CUSTOM policy is changed to be narrower than the ALLOW policy.

If an CUSTOM policy could leave an "audit trail" on the request, an ALLOW policy could use this instead of attempting to duplicate the policy conditions of the CUSTOM policy. For example, if it is possible to set [conditions](https://istio.io/latest/docs/reference/config/security/conditions/) in an http filter, we could introduce `request.ext_authz` as an array of all ext authz modules that have been applied.

**Describe alternatives you've considered**

* a CUSTOM_ALLOW policy or additional attributes to customize the behavior, like bypassing other authorization policies when set. I think this would complicate the flow further and be less flexible.
* Setting an HTTP header in the external provider, and checking it in the next authoritzation policy. This is not Out Of Band, and is more vulnerable to security issues.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### Example of current situation:

```yaml
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "productpage-viewer"
  namespace: default
spec:
  selector:
    matchLabels:
      app: productpage
  action: CUSTOM
  provider:
    name: authz-module-1
  rules:
  - to:
    - operation:
        hosts: ["ext-hostname.example.com"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "productpage-viewer"
  namespace: default
spec:
  selector:
    matchLabels:
      app: productpage
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts: ["ext-hostname.example.com"]
```

### Proposed solution:

```yaml
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "productpage-viewer"
  namespace: default
spec:
  selector:
    matchLabels:
      app: productpage
  action: CUSTOM
  provider:
    name: authz-module-1
  rules:
  - to:
    - operation:
        hosts: ["ext-hostname.example.com"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "productpage-viewer"
  namespace: default
spec:
  action: ALLOW
  rules:
  - when:
    - key: request.ext_authz
      values: ["authz-module-1"] # Only true when allowed by the CUSTOM provider authz-module-1
```
