### ISSUE TITLE
Does Istio have a plan to support service name in HTTP URL path or header?

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#4722]
As I understand it, currently Istio take the "host" part of the http request as the service name and use it to find the destination service. For example, in the Bookinfo example, the service name "details" is extracted from the host part of request "http://details:9080/...".

While I understand this is a logical approach for Istio because of its tight relationship with kubernetes, there're also other ways to locate the service name in Microservice practices. Service name may also be part of URL path or even an HTTP header. For example, a request may be sent to a URL like http://IP:Port/api/details/v1/{resource_id}, in which the service name "details" should be extracted from URL path.

Will Istio plan to support service name in HTTP URL path or header? Or maybe it's already supported somewhere I don't noticed?

**Comment by linsun** [comment]
don't think this is supported or we have near term plan to support this cc @andraxylia @rshriram @louiscryan @frankbu

**Comment by frankbu** [comment]
You can do it with v1alpha3 rules: https://istio.io/docs/reference/config/istio.networking.v1alpha3.html

For example:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo-rule
spec:
  hosts:
  - bookinfo.com
  http:
  - match:
      uri:
        prefix: /reviews/
    route:
    - destination:
        name: reviews
  - match:
      uri:
        prefix: /ratings/
    route:
    - destination:
        name: ratings
```
