### ISSUE TITLE
Simple Wasmplugin failed loading in waypoint

### ISSUE THREAD

**Issue by linsun** [istio/istio#47227]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a very simple wasm image and it works fine with sidecar.

When I use it on waypoint:

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: hello
  namespace: default
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: httpbin
  pluginName: add_header
  imagePullPolicy: Always
  url: oci://webassemblyhub.io/linsun/helloworld:latest
```

The waypoint failed to validate the `TypedExtensionConfig` with the following in the log:

```
2023-10-06T19:01:58.987901Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:128	gRPC config for type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig rejected: Proto constraint validation failed (WasmValidationError.Config: embedded message failed validation | caused by PluginConfigValidationError.VmConfig: embedded message failed validation | caused by VmConfigValidationError.Code: embedded message failed validation | caused by AsyncDataSourceValidationError.Remote: embedded message failed validation | caused by RemoteDataSourceValidationError.Sha256: value length must be at least 1 characters): config {
  name: "default.hello"
  root_id: "add_header"
  vm_config {
    runtime: "envoy.wasm.runtime.v8"
    code {
      remote {
        http_uri {
          uri: "oci://webassemblyhub.io/linsun/helloworld:latest"
          cluster: "_"
          timeout {
            seconds: 30
          }
        }
      }
    }
    environment_variables {
      key_values {
        key: "ISTIO_META_WASM_IMAGE_PULL_POLICY"
        value: "Always"
      }
      key_values {
        key: "ISTIO_META_WASM_PLUGIN_RESOURCE_VERSION"
        value: "11088"
      }
    }
  }
  configuration {
  }
}
	thread=21
```

### Version

```Text
1.19.1
```

**Comment by linsun** [comment]
Confirmed this is indeed caused by ecds config not able to work with delta response. I got wasm oci image downloaded fine after disable delta per @kyessenov 's suggestion in https://github.com/istio/istio/blob/359678f4bc7be37143dd9b1b726e950d1a6be99d/pkg/bootstrap/config.go#L94

**Comment by hanxiaop** [comment]
This exists not only in waypoints but also sidecars using delta xDS with ECDS. I think this is related to upstream Envoy after correcting the forward logic in https://github.com/istio/istio/pull/47302. I've also sent an issue to track https://github.com/envoyproxy/envoy/issues/30379.

**Comment by hanxiaop** [comment]
Still exist

**Comment by hanxiaop** [comment]
@howardjohn Just tested https://github.com/envoyproxy/envoy/issues/30379 again. The new behavior observed is that the init configuration dump information is no longer shown. However, proxies that enable Delta XDS, such as waypoint or sidecars with `ISTIO_DELTA_XDS: "true"`, still cannot be ready. I'm not sure if this is now an issue on the Envoy side, so I raise it here for investigation.

To reproduce, enable delta XDS for the sidecar or use a waypoint, and add a WasmPlugin resource as follows:

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: hello
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  pluginName: hello
  imagePullPolicy: Always
  url: <wasm-address>
```

Then, redeploy the pod. The proxy will not be ready, with an ECDS config like:

```
{
  "@type": "type.googleapis.com/envoy.admin.v3.EcdsConfigDump",
  "ecds_filters": [
  {
    "ecds_filter": {
      "@type": "type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig",
      "name": "extenstions.istio.io/wasmplugin/default.hello"
    },
  "last_updated": "2024-02-08T07:01:16.286Z"
  }
  ]
},
```
