### ISSUE TITLE
CorsPolicy not working if matched by headers

### ISSUE THREAD

**Issue by caibirdme** [istio/istio#47236]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In the VS conf, if I match a request by uri, the corsPolicy works and the related headers are added to the response header. But if I match the request by headers, then non cors related headers are added to the response header.
Here's the config:

When match by uri, it works:
```yaml
spec:
  http:
    - match:
        - uri:
            prefix: /hello/
      route:
        - destination:
            host: hello.test.svc.cluster.local
            port:
              number: 8080
      corsPolicy:
        allowMethods:
          - POST
          - GET
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - '*'
        maxAge: 24h
        allowOrigins:
          - regex: .*
```
The response contains the cors header:
```
< date: Sat, 07 Oct 2023 09:46:24 GMT
< content-type: application/json
< content-length: 178
< x-content-type-options: nosniff
< x-envoy-upstream-service-time: 161
< access-control-allow-origin: https://example.com
< server: istio-envoy
```

While matched by headers, it doesn't work:
```yaml
spec:
  http:
    - match:
        - headers:
            x-i-wantto-go:
              exact: hello.test.svc.cluster.local
      route:
        - destination:
            host: hello.test.svc.cluster.local
            port:
              number: 8080
      corsPolicy:
        allowMethods:
          - POST
          - GET
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - '*'
        maxAge: 24h
        allowOrigins:
          - regex: .*
```
No access-control-xxx header in response

### Version

```Text
istio version: 1.16.5
k8s version: 1.24
```
