### ISSUE TITLE
unable connect the external atlas mongodb

### ISSUE THREAD

**Issue by storehubdeploy** [istio/istio#47234]
`###` Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

istio-proxy cannot connect to the atlas cloud mongodb cluster
when i inject the istio，the apps  connet to mongo failled
the config mongodb cluster address is testcluster.ibxvq.mongodb.net
the service entry setting 

     

```
      apiVersion: networking.istio.io/v1alpha3
      kind: ServiceEntry
      metadata:
        name: external-svc-mongocluster
        namespace: test17
      spec:
        hosts:
        - testcluster.ibxvq.mongodb.net
        addresses:
        ports:
        - number: 27017
          name: mongodb
          protocol: TCP
        location: MESH_EXTERNAL
        resolution: NONE
```

but the log  shows
<img width="1412" alt="image" src="https://github.com/istio/istio/assets/31533566/a2bdf455-501d-40e7-8922-b4b639119c06">

### Version

```Text
istio version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.14.3 (4 proxies), 1.18.2 (70 proxies)

k8s version
Client Version: v1.20.4-eks-6b7464
Server Version: v1.25.12-eks-2d98532
```
