### ISSUE TITLE
Adding apparmor annotation for istio-init breaks istio gateway

### ISSUE THREAD

**Issue by aittam** [istio/istio#47272]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

I am trying to add the AppArmor annotations to my istio sidecar containers and I see that I can do it by using `sidecarInjectorWebhook.injectedAnnotations` in [here](https://github.com/istio/istio/blob/3e857775086a061d12ee445f32a0b35ea17c8488/manifests/charts/istio-control/istio-discovery/values.yaml#L92) 

and hence I added the following:

```
          "container.apparmor.security.beta.kubernetes.io/istio-proxy": "runtime/default",
          "container.apparmor.security.beta.kubernetes.io/istio-init": "runtime/default"
```
and all worked fine in general until I wanted to install the [istio-gateway](https://github.com/istio/istio/tree/master/manifests/charts/gateway) helm chart. The creation of the gateway pods fails with:

`Error creating: Pod "my-gateway-56c9495bd-84rhw" is invalid: metadata.annotations[container.apparmor.security.beta.kubernetes.io/istio-init]: Invalid value: "istio-init": container not found`

because on the gateway there is no such container injected. 

If I remove the annotation for the `istio-init` container then everything works and the gateway pods spin up successfully. 

I am currently running version 1.17.2 and, we are planning to upgrade soon, it's just not possible right now. Although, I looked at the changes in the helm chart and, at first sight, it doesn't seem to have changed much in that particular aspect.

Is this a supported scenario? 

### Version

```Text
client version: 1.18.2
control plane version: 1.17.2
data plane version: 1.17.2 (42 proxies)

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.6
```

**Comment by howardjohn** [comment]
The gateway doesn't have an istio-init container. Just remove the annotation

**Comment by aittam** [comment]
@howardjohn I guess my question was, how? since adding it to `sidecarInjectorWebhook.injectedAnnotations` will add it to the gateway pod as well. While not adding the annotation there means I won't have it set in all the other pods?

**Comment by howardjohn** [comment]
Ah sorry, missed that part. https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection I suppose... otherwise the field you are setting is global to all injection

**Comment by aittam** [comment]
I read that part but I wasn't sure how to leverage that for the gateway pod. I do install the gateway helm chart with something like:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gateway
    releaseName: my-gateway
    namespace: istio-system
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.17.2
    includeCRDs: true
    valuesInline:
      name: my-gateway
      labels:
        app: my-gateway
        istio: my-gateway
      replicaCount: 2
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80
      imagePullPolicy: Always
      service:
        type: LoadBalancer
        ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 443
      podAnnotations:
        container.apparmor.security.beta.kubernetes.io/istio-proxy: "runtime/default"
```

Which does create the Deployment manifest like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-gateway
    app.kubernetes.io/version: 1.17.2
    helm.sh/chart: gateway-1.17.2
    istio: my-gateway
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: my-gateway
      istio: my-gateway
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        app: my-gateway
        istio: my-gateway
        sidecar.istio.io/inject: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spire-gateway
            topologyKey: kubernetes.io/hostname
      containers:
      - env: null
        image: auto
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      serviceAccountName: my-gateway
```

So, If I understand correctly, I am already overriding some template configurations but that doesn't apply to annotations the way I want, which makes sense to me.

Is removing

`"container.apparmor.security.beta.kubernetes.io/istio-init": "runtime/default"` 

from `sidecarInjectorWebhook.injectedAnnotations` and manually adding it to my other workloads manifests the only way?
