### ISSUE TITLE
envoyExtAuthzHttp doesnt respect VirtualService Destination after successful authentication

### ISSUE THREAD

**Issue by teceP** [istio/istio#47301]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I activate the AuthorizationPolicy in combination with the oauth2-proxy extensionProvider, I get asked to login when accessing those 3 example URLS:
          - test-istio.example.de
          - test-jaeger.example.de
          - test-prometheus.example.de

After successfull authorization, I expect to get redirected to the Application e.g. jaeger WEB UI.
But all requests are forwarded to the OAuth2-Proxy instance, even if the user is authenticated.

The Browser says "404 page not found" and I can see in OAuth2-Proxy Log, that the requests are forwarded to OAuth2-Proxy Pod:

```
127.0.0.6 - 65fc466c-67bd-4eeb-a188-4b1561dc22a3 - m.teklic@example.de [2023/10/11 02:53:10] test-jaeger.example.de GET - "/jaeger/search" HTTP/1.1 "" 404 19 0.001
```

Which configuration am I forgetting here?

### Version

```Text
client version: 1.17.6
control plane version: 1.19.1
data plane version: 1.17.6 (21 proxies), 1.19.0 (18 proxies), 1.19.1 (13 proxies)

Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.4
```

### Additional Information

Mesh Config:
```yaml
    extensionProviders:
    - envoyExtAuthzHttp:
        headersToDownstreamOnDeny:
        - content-type
        - set-cookie
        headersToUpstreamOnAllow:
        - authorization
        - cookie
        includeAdditionalHeadersInCheck:
          X-Auth-Request-Redirect: '%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%'
        includeHeadersInCheck:
        - authorization
        - cookie
        port: 80
        service: iam-oauth2-proxy.iam.svc.cluster.local
      name: oauth2-proxy
```
AuthorizationPolicy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        hosts:
          - test-istio.example.de
          - test-jaeger.example.de
          - test-prometheus.example.de
```
VirtualServices
```
---
# Source: istio/charts/ingresses/templates/tpl.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-istio
  namespace: istio-system
spec:
  hosts:
  - test-istio.example.de
  gateways:
  - test-ingressgateway
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
---
# Source: istio/charts/ingresses/templates/tpl.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-jaeger
  namespace: istio-system
spec:
  hosts:
  - test-jaeger.example.de
  gateways:
  - test-ingressgateway
  http:
  - route:
    - destination:
        host: tracing.istio-system.svc.cluster.local
        port:
          number: 80
---
# Source: istio/charts/ingresses/templates/tpl.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-prometheus
  namespace: istio-system
spec:
  hosts:
  - test-prometheus.example.de
  gateways:
  - test-ingressgateway
  http:
  - route:
    - destination:
        host: monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local
        port:
          number: 9090
```
