### ISSUE TITLE
[Istio 1.18.2] Istio SDS fails to read -cacert secrets

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#47315]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Steps to reproduce:
1. Install Istio 1.18.2 into a cluster
2. Follow setup from https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ to create httpbin secret named httpbin-certs instead of httpbin-credential
3. Configure MUTUAL tls on a host in the Gateway Resource
```
    - hosts:
      - httpbin.com
      port:
        name: https-metrics-receiver
        number: 443
        protocol: HTTPS
      tls:
        credentialName: httpbin-certs
        mode: MUTUAL
```
4. Add httpbin-certs-cacerts with cacert key
```
apiVersion: v1
data:
  cacert: <some cert>
kind: Secret
metadata:
  name: httpbin-certs-cacert
  namespace: istio-system
type: Opaque
```
5. Check istiod logs:
```
2023-10-11T22:58:33.056497Z	warn	ads	failed to fetch ca certificate for kubernetes://httbin-certs-cacert: found secret, but didn't have expected keys cacert or ca.crt; found: tls.crt, tls.key
```
6. Check gateway secrets istioctl pc s istio-ingressgateway-<pod-suffix>
```
RESOURCE NAME                                      TYPE           STATUS      VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE
kubernetes://httpbin-certs-cacert                      WARMING     false
```

Expected Behavior: 
1. Istiod reads cacert correctly at step 5.

### Version

```Text
istio 1.18.2
```
