### ISSUE TITLE
gateway-api: using ReferenceGrant to allowTCPRoute cross-namespace references does not take effect. 

### ISSUE THREAD

**Issue by believening** [istio/istio#47341]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Using ReferenceGrant to allow TCPRoute cross-namespace references does not take effect. However, it can be made effective by configuring a ReferenceGrant from HTTPRoute .

### Version

```Text
$ istioctl version
client version: 1.19-dev
control plane version: 1.19.0
data plane version: 1.19.0 (5 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

### Additional Information

**Reproduction**：

1. Deploy "tcp-echo" as a backend service in namespace `ns1`.

    ```yaml
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: tcp-echo
      namespace: ns1
      labels:
        app: tcp-echo
        service: tcp-echo
    spec:
      ports:
      - name: tcp
        port: 9000
      - name: tcp-other
        port: 9001
      # Port 9002 is omitted intentionally for testing the pass through filter chain.
      selector:
        app: tcp-echo
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tcp-echo
      namespace: ns1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: tcp-echo
          version: v1
      template:
        metadata:
          labels:
            app: tcp-echo
            version: v1
            sidecar.istio.io/inject: "true"
        spec:
          containers:
          - name: tcp-echo
            image: docker.io/istio/tcp-echo-server:1.2
            imagePullPolicy: IfNotPresent
            args: [ "9000,9001,9002", "hello" ]
            ports:
            - containerPort: 9000
            - containerPort: 9001
    ```

2. Create `Gateway` and `TCPRoute` in namespace `ns2` that references "tcp-echo".

    ```yaml
    ---
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    metadata:
      name: tcp-echo-gateway
      namespace: ns2 
    spec:
      gatewayClassName: istio
      listeners:
      - name: tcp-31400
        protocol: TCP
        port: 31400
        allowedRoutes:
          kinds:
          - kind: TCPRoute
    ---
    apiVersion: gateway.networking.k8s.io/v1alpha2
    kind: TCPRoute
    metadata:
      name: tcp-echo
      namespace: ns2 
    spec:
      parentRefs:
      - name: tcp-echo-gateway
        sectionName: tcp-31400
      rules:
      - backendRefs:
        - name: tcp-echo
          namespace: ns1
          port: 9000
    ```
    Currently, the status of `TCPRoute` is `false` since there is no `ReferenceGrant`.

3. Creating a `ReferenceGrant` in `ns1` for the `TCPRoute` in `ns2` does not work.
    ```yaml
    ---
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    metadata:
      name: allow-tcproute-in-ns2
      namespace: ns1
    spec:
      from:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
        namespace: ns2 
      to:
      - group: ""
        kind: Service
    ```

4. But creating a ReferenceGrant in ns1 for the HTTPRoute in ns2 works.
    ```yaml
    ---
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    metadata:
      name: allow-httproute-in-ns2
      namespace: ns1
    spec:
      from:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        namespace: ns2 
      to:
      - group: ""
        kind: Service
    ```
