### ISSUE TITLE
Incorrect values in NDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#47340]
Pilot nds looks good, but agent has weird values:

```yaml
vm.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
vm.echo.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
vm.echo.svc.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
vm.echo.svc.cluster.local:
  ips:
  - fd00:10:96::f006
  namespace: echo
  registry: Kubernetes
  shortname: vm
vm.echo.svc.cluster.local.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
```

You can see the FQDN is duplicated

```yaml
istio-egressgateway.istio-system.:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system..:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc.:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc..:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc.cluster.local:
  ips:
  - fd00:10:96::47f3
  namespace: istio-system
  registry: Kubernetes
  shortname: istio-egressgateway
istio-egressgateway.istio-system.svc.cluster.local.:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc.cluster.local..:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
```

double `..` seems broken
