### ISSUE TITLE
Routing with public domain names does not work

### ISSUE THREAD

**Issue by sando38** [istio/istio#47357]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**Preamble**:
Got most of the input from my colleague @PaoloC68, so he may have more infos.
We deployed istio with Helm. Helm chart version is `1.19.1`, we have deployed the charts `base`, `istiod` and `gateway`.

**Setup**:
We need to route traffic from one pod to another to authenticate. The authentication address is a publicly resolvable domain name "auth.example.info". However, our container logs show, that we cannot connect to the respective pod. We tried many different configurations without any luck.

**Issue Encountered**
I am unable to establish a TLS connection to an external service that is part of the same Kubernetes cluster. The issue occurs only when I try to connect from a Pod within the cluster to the external service via its public DNS. This results in a TLS handshake error. The issue doesn't manifest when connecting from outside the cluster.

**Expectation**
I expect to be able to establish a TLS connection to the service both from within and outside the cluster seamlessly, without encountering a TLS handshake error.

**Steps Taken**
- Validated the certificates and they are not the issue.
- Tried direct queries using `openssl` and `curl` commands, which also failed.
- Checked Istio's `ServiceEntry` and `Gateway` configurations to ensure they are set up correctly.
  - `ServiceEntry` with both `MESH_EXTERNAL` and `MESH_INTERNAL` ([like described here](https://discuss.istio.io/t/best-way-to-to-route-public-service-dns-internally/9390/5))
- Used `istioctl analyze` and found no significant issues.
- Attempted to bypass Istio's sidecar for outbound traffic using the annotation `traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0"` but to no avail.
- DNS lookup using `nslookup` works fine; it's just the actual connection that fails.

**Logs & Error Messages**
I get a `Connection reset by peer` error when I try to connect.

```
OpenSSL SSL_connect: Connection reset by peer in connection to auth.example.info:443
```

### Version

```Text
$ istioctl version
no ready Istio pods in "istio-system"
1.19.1

$ istioctl version -i istio
client version: 1.19.1
control plane version: 1.19.1
data plane version: 1.19.1 (18 proxies)

$ kubectl version --short
Client Version: v1.26.3
Server Version: v1.27.4
```

### Additional Information

[istio_config_dump.txt](https://github.com/istio/istio/files/12899774/istio_config_dump.txt)
[bug-report.tar.gz](https://github.com/istio/istio/files/12900182/bug-report.tar.gz)

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authentik-virtual-service
  namespace: istio
spec:
  hosts:
    - "auth.example.info"
    - "auth.example.net"
    - "auth.example.com"
  gateways:
  - wildcardgateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: authentik.authentik.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: svc-redirect-auth
  namespace: istio
spec:
  endpoints:
   - address: "xxx.xxx.xxx.xxx" # The Ingress Gateway LB
   - address: "xxx.xxx.xxx.xxx" # The Ingress Gateway LB
  hosts:
    - auth.example.com
    - auth.example.info
    - auth.example.net
  location: MESH_INTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
#  workloadSelector:
#    labels:
#      app: authentik
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: svc-redirect-backend
  namespace: istio
spec:
  endpoints:
   - address: "xxx.xxx.xxx.xxx" # The Ingress Gateway LB
   - address: "xxx.xxx.xxx.xxx" # The Ingress Gateway LB
  hosts:
    - backend.example.com
    - backend.example.info
    - backend.example.net
  location: MESH_INTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
#  workloadSelector:
#    labels:
#      app: django
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: wildcardgateway
  namespace: istio
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "example.info"
    - "example.net"
    - "example.com"
    - "*.example.info"
    - "*.example.net"
    - "*.example.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "example.info"
    - "example.net"
    - "example.com"
    - "*.example.info"
    - "*.example.net"
    - "*.example.com"
    tls:
      mode: SIMPLE
      credentialName: wildcard-example-tls
---
apiVersion: v1
kind: Service
metadata:
  name: additional-gateway
  namespace: istio
spec:
  type: LoadBalancer
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: gateway
    istio: gateway
```
