### ISSUE TITLE
New version of istio do not honour portNumber in EnvoyFilter

### ISSUE THREAD

**Issue by anilv4** [istio/istio#47362]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**Background & Issue**

- We are upgrading our istio from 1.6 to 1.14.
- Our application needs all outbound tcp connections to destination port 1528 to remain intact for 24 hours even if the connection go idle.
- Destination is a DB hosted outside of K8S cluster.
- As istio-proxy's idle_timeout is 60mins, we used the following envoy filter to modify the default timeout.

```
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.tcp_proxy       
        portNumber: 1528
    patch:
      operation: MERGE
      value:
        name: envoy.tcp_proxy            
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy   
          idle_timeout: 86400s 
```

- When we use the same configuration updated for Istio 1.14, isto-proxy do not honour the idle time_output. 

```
# cat istio-timeout.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: idle-timeout
  namespace: goserver
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
        portNumber: 1528
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 86400s
```

**Reproducer Steps:**

1. Start the following pod.

```
# cat goserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-deployment
  namespace: goserver
spec:
  replicas: 1 # Set the desired number of replicas (pods)
  selector:
    matchLabels:
      app: goserver # The label used to select pods for this deployment
  template:
    metadata:
      labels:
        app: goserver # The label applied to pods created from this template
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: goserver
          image: quay.io/deployments/goserver:v15-f38 # The container image from quay.io
          ports:
            - containerPort: 8080 # The port your application listens on
```
2. Apply the following envoyfilter.

```
# cat istio-timeout.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: idle-timeout
  namespace: goserver
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
        portNumber: 1528
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 10s 
```

3. On a remote system, say, for example, bastion. Start a nc server & tcpdump to observe the traffic.

```
 # date; time nc -lk 1528 -i 24h (nc server IP is 192.168.122.1)

# tcpdump -i any -nn port 1528 (second terminal)
```
 
4. Take rsh of the goserver pod

`# kubectl rsh goserver-xxx`

5. Start the nc client connection.

`# nc 192.168.122.1 1528 -i24h`

6. Observe the tcpdump, wait for 10 seconds, envoy won't disconnect the idle connection even after 10 seconds.

7. Exit the rsh session.

**8. Update the envoyfilter and remove the **portNumber** idle_timeout works. (WORKAROUND FOR NOW)**

9. Start the nc client connection again.

`# nc 192.168.122.1 1528 -i24h`

 10. This time you can see FIN from the envoy exactly after 10 seconds.
 

```
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on virbr0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
20:18:01.001182 IP 192.168.122.254.35128 > 192.168.122.1.1528: Flags [S], seq 3128801540, win 28200, options [mss 1410,sackOK,TS val 3295896774 ecr 0,nop,wscale 7], length 0
20:18:01.001229 IP 192.168.122.1.1528 > 192.168.122.254.35128: Flags [S.], seq 1542184685, ack 3128801541, win 65160, options [mss 1460,sackOK,TS val 2689455727 ecr 3295896774,nop,wscale 7], length 0
20:18:01.001520 IP 192.168.122.254.35128 > 192.168.122.1.1528: Flags [.], ack 1, win 221, options [nop,nop,TS val 3295896774 ecr 2689455727], length 0

20:18:11.001480 IP 192.168.122.254.35128 > 192.168.122.1.1528: Flags [F.], seq 1, ack 1, win 221, options [nop,nop,TS val 3295906774 ecr 2689455727], length 0
20:18:11.001545 IP 192.168.122.1.1528 > 192.168.122.254.35128: Flags [F.], seq 1, ack 2, win 510, options [nop,nop,TS val 2689465727 ecr 3295906774], length 0
20:18:11.001665 IP 192.168.122.254.35128 > 192.168.122.1.1528: Flags [.], ack 2, win 221, options [nop,nop,TS val 3295906774 ecr 2689465727], length 0
```

### Version

```Text
# istioctl version
client version: 1.19.0
control plane version: OSSM_2.3.7-1
data plane version: 1.14.5 (3 proxies)

# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.11+1485cc9
```
