### ISSUE TITLE
503 error when connecting with service from wasm plugin

### ISSUE THREAD

**Issue by janekmichalik** [istio/istio#47372]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have k8s cluster with istio mTLS `STRICT` mode enabled. I also have wasm plugin integrated with istio ingress gateway. 
The wasm plugin needs access to k8s service to get some data, but its seems that with `STRICT` mode the communication is terminated. 

It seems that wasm plugin is running within envoy process that is why it is not able to handle mTLS, right? How can I handle such case to preserve `STRICT` mode?

logs from istio ingress gateway:
```
2023-10-13T20:49:08.653912Z     error   envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1154 wasm log istio-system.<wasm-plugin>: Context ID: 4. Unknown issue occurred. Response status code: 503, body: "upstream connect error or disconnect/reset before headers. reset reason: connection termination"  thread=50
```

logs from Istio-proxy sidecar (of k8s service that wasm plugin is trying to reach)
```
2023-10-13T20:57:31.907732Z     debug   envoy main external/envoy/source/server/server.cc:263   flushing stats  thread=21
[2023-10-13T20:57:31.650Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.42.0.147:5555 10.42.0.154:36420 - -
```

### Version

istioctl version:
```
client version: 1.19.1
control plane version: 1.19.1
data plane version: 1.19.1
```

**Comment by janekmichalik** [comment]
> @janekmichalik assuming no errors when istio mTLS is not set to `STRICT`? Is your PeerAuthentication policy defined at the workload level for your ingress gateway?
> https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#enable-mutual-tls-per-workload

@GregHanson no error when `PERMISSIVE` mode set. My `PeerAuthentication` is set globally for the entire mesh:
https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/#lock-down-mutual-tls-for-the-entire-mesh

**Comment by janekmichalik** [comment]
**more context**

I am using below `envoyFilter` to configure cluster which is used by dispatched request in wasm plugin to get data from `target-service`

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-upstream-target-service
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value: # Cluster specification
          name: outbound_account_service
          type: LOGICAL_DNS
          connect_timeout: 5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: outbound_account_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "target-service.default.svc.cluster.local"
                          protocol: TCP
                          port_value: 5555
```

**Comment by janekmichalik** [comment]
**more context**

I am using below `envoyFilter` to configure cluster which is used by dispatched request in wasm plugin to get data from `target-service`

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-upstream-target-service
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value: # Cluster specification
          name: outbound_target_service
          type: LOGICAL_DNS
          connect_timeout: 5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: outbound_target_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "target-service.default.svc.cluster.local"
                          protocol: TCP
                          port_value: 5555
```

**Comment by GregHanson** [comment]
`STRICT` places restrictions on inbound connections to sidecar enabled pods, making sure those inbound requests are using mutual tls.  Assuming `target-service` is running with a sidecar?  If I understand your setup correctly, your wasm client is missing the config to tell it to use mutual tls when talking to `target-service`?  Which make sense because those tls settings are stored at the cluster level (usually in transport socket matches).  You could inspect other cluster objects `istioctl pc cluster <pod_name>.<pod_ns> --fqdn XXXXX -ojson` of another pod in the mesh and copy the missing fields over to your EnvoyFilter

I think to most closely resemble your scenario, I would try this:
 - deploy sleep pod with sidecar
 - deploy a ServiceEntry and DestinationRule for a dummy external service like httpbin with a dns endpoint defined:
 ```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin.org
  subsets:
  - name: httpbin
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: httpbin.org # use correct SNI here
EOF
```
 - check the json configuration of the httpbin cluster for the sleep pod and copy relative settings to your EnvoyFilter
 ```
istioctl pc cluster deploy/sleep --fqdn httpbin.org -ojson
```
