### ISSUE TITLE
holdApplicationUntilProxyStarts does not work with lifecycle parameters

### ISSUE THREAD

**Issue by AlfredoFausto** [istio/istio#47373]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using holdApplicationUntilProxyStarts this should add a postStart hook in the deployment manifest:

```
      proxy:
        lifecycle:
          postStart:
            exec:
              command:
              - pilot-agent
              - wait
```
But if this is combined with a lifecycle parameters this will effectively override the holdApplicationUntilProxyStarts postStart hook.

Example:

```
   proxy:
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sleep
                - '45'
```

Whenever is put in the lifecycle values, will override any other lifecycle hook. The problem is on the injection template which the control flow is not right:
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L216C20-L216C20
```
 {{- if .Values.global.proxy.lifecycle }}
    lifecycle:
      {{ toYaml .Values.global.proxy.lifecycle | indent 6 }}
  {{- else if $holdProxy }}
    lifecycle:
      postStart:
        exec:
          command:
          - pilot-agent
          - wait
  {{- end }}
```

This is a problem since not both lifecycle hooks can be configured but instead only the ones in the lifecycle values will be present in the pod injection.

### Version

```Text
istioctl version                        
client version: 1.19.1
control plane version: 1.19.1
data plane version: 1.19.1 (2 proxies
---
kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.2
```
