### ISSUE TITLE
In dual-stack mode, when ServiceEntires use TLS and multiple hosts only IPv4 listeners are created

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#47406]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This is seen in Istio 1.18.2 and fixed on master/1.20.

1. Install Istio on a dual-stack cluster in dual-stack mode
2. Apply the following yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - api.dropboxapi.com
  - www.googleapis.com
  - api.facebook.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```
3. Inspect the listeners
```bash
0.0.0.0       443   ALL                                                                                           Non-HTTP/Non-TCP
0.0.0.0       443   SNI: www.googleapis.com                                                                       Cluster: outbound|443||www.googleapis.com
0.0.0.0       443   SNI: api.facebook.com                                                                         Cluster: outbound|443||api.facebook.com
0.0.0.0       443   SNI: api.dropboxapi.com                                                                       Cluster: outbound|443||api.dropboxapi.com
10.96.0.1     443   ALL                                                                                           Cluster: outbound|443||kubernetes.default.svc.cluster.local
10.96.105.209 443   ALL                                                                                           Cluster: outbound|443||istiod.istio-system.svc.cluster.local
```

vs the same for master

```bash
0.0.0.0,::    443   ALL                                                                                           Non-HTTP/Non-TCP
0.0.0.0,::    443   SNI: www.googleapis.com                                                                       Cluster: outbound|443||www.googleapis.com
0.0.0.0,::    443   SNI: api.facebook.com                                                                         Cluster: outbound|443||api.facebook.com
0.0.0.0,::    443   SNI: api.dropboxapi.com                                                                       Cluster: outbound|443||api.dropboxapi.com
```

### Version

```Text
Istio 1.18.2
```
