### ISSUE TITLE
Bad Request This combination of host and port requires TLS.

### ISSUE THREAD

**Issue by AB-1712** [istio/istio#47404]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have service with port 443 and target port 8099. I have gateway and virtual service configured.
Because of TLS termination happening at gateway, not able to access the service. please provide a solution. 

this is my gateway service:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: servicegateway
  namespace: random
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: XXX
    hosts:
    - '*'
```

this is my VS file:
```
kind: VirtualService
metadata:
  name: vs
  namespace: random
spec:
  hosts:
  - '*'
  gateways:
  - servicegateway
  http:
  - match:
    - uri:
        prefix: /abc
    route:
    - destination:
        host: service1
        port:
          number: 80 
  - match:
    - uri:
        prefix: /cde
    route:
    - destination:
        host: service2
        port:
          number: 443
```

please suggest a solution where I can fix this issue. 

### Version

```Text
Client Version: v1.24.2
Kustomize Version: v4.5.4
```
