### ISSUE TITLE
Destination rules only apply to inbound

### ISSUE THREAD

**Issue by flexwang** [istio/istio#47416]
We have a single client replica, multiple server replica setup. If I set up a destination rule, seems that it will affect both client side and server side:

1. The client side won't be able to make more than 2 requests at the same time;
2. The server side replica won't be able to handle more than 2 requests at the same time;

Is it possible to config that we only want the server side rejection?

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: http-max-requests
spec:
  host: ...
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 2
```
