### ISSUE TITLE
Deployment object for ingress-gateway has 'spec.selector' too wide

### ISSUE THREAD

**Issue by eraac** [istio/istio#47425]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've two ingress gateway (one for an internal load balancer, one for an external), which obviously have different scaling/lifecycle/... 

But it seems the `spec.selector` inside the deployment object isn't specific enough and select pods from the both gateways. Which cause scaling issue for the HPA (which has as target the deployment object)

<details>
  <summary>deployment</summary>
 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-gateway-glb
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
```

</details>

<details>
  <summary>operator</summary>
  
```yaml
    ingressGateways:
    - name: ingress-gateway-glb
      namespace: istio-ingress
      enabled: true
      k8s:
        priorityClassName: critical

        resources:
          requests:
            cpu: 500m
            memory: 128Mi

        hpaSpec:
          minReplicas: 3
          maxReplicas: 50
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60

        podDisruptionBudget:
          maxUnavailable: 1
          selector:
            matchLabels:
              service.istio.io/canonical-name: ingress-gateway-glb

        tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "istio"
          effect: "NoSchedule"

        serviceAnnotations:
          cloud.google.com/neg: '{"exposed_ports": {"8443": {}}}'
          cloud.google.com/app-protocols: '{"https": "HTTPS"}'

        service:
          type: ClusterIP
          selector:
            service.istio.io/canonical-name: ingress-gateway-glb
          ports:
          - name: https
            port: 8443
            protocol: TCP
            targetPort: 8443

        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: ingress-gateway-glb
          patches:
          - path: spec.template.metadata.labels.app\.kubernetes\.io/name
            value: ingress-gateway-glb
```

</details>

The problem now, it's I can't set `gatewayspec.label` inside the operator configuration, because `spec.selector` is immutable

### Version

```Text
$ istioctl version
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.0 (16 proxies), 1.19.1 (4 proxies), 1.19.3 (32 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.13", GitCommit:"5244794d27b4cc68290bc496b00e248857ac8b47", GitTreeState:"clean", BuildDate:"2023-08-24T00:01:27Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.10-gke.2700", GitCommit:"df2448d7739c44e41ee999b9065ce506cab86344", GitTreeState:"clean", BuildDate:"2023-06-22T09:25:37Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

In fact, I've also the issue for the PDB and the Service, which I've update in my configuration the selector for both, but IMO the operator should take care of this
