### ISSUE TITLE
istio gatway-api - when creating gateway (GatewayApi) a deployment being created with injected suffix

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#47429]
Hi, I created a gateway (gateway-api) with the following config:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external-gateway
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: tls-secret
        namespace: istio-ingress
```

This gateway creates a deployment with the name: `external-gateway-istio`
I want the deployment name to be the same as the gateway name `external-gateway`, is there a config or annotation to remove the istio suffix?

I didn't find anything about this.
I want the same name because it will help me templating it with helm

Thanks
