### ISSUE TITLE
Add Dynatrace tracing extension

### ISSUE THREAD

**Issue by joaopgrassi** [istio/istio#47453]
**Describe the feature request**

Dynatrace is transitioning to use the OpenTelemetry tracer in Envoy to collect spans from Envoy. The reason for this is: our integration with Envoy today rely on the OpenTracing tracer, [which is deprecated and will be removed soon](https://github.com/envoyproxy/envoy/pull/28987).

Dynatrace supports ingesting OpenTelemetry Protocol data (OTLP) **only over HTTP**. As a prerequisite for this transition, I worked on getting a HTTP exporter in Envoy. The HTTP exporter is [merged and will be part of Envoy version 1.28 ](https://github.com/envoyproxy/envoy/pull/29207). So now, Dynatrace customers can send Envoy spans to Dynatrace via HTTP. 

The majority of our customers though uses Envoy "via" Istio. As part of this transition we would be glad if we could introduce a Dynatrace Tracing Extension to Istio. 

Our proposal is to Introduce a new tracing extension that "wraps" and uses the OpenTelemetry tracer under the hood. The reason for going this route is to make the configuration easier for our customers. For example, to send spans to Dynatrace they need to configure the correct URL and Authorization API token as a header, which can be error prone and cumbersone. With our extension, we can hide all this complexity from our customers and let them focus on the minimal parts (their SaaS URL + access token). 

There is already precedence in Istio for such approach, with the [Lightstep extension wrapping the OTel tracer](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/tracing.go#L397).

Additionally, we are also working on extra extensions on Envoy's OpenTelemetry tracer to be able to configure [Resource Detectors](https://github.com/envoyproxy/envoy/pull/29547) and a [Sampler](https://github.com/envoyproxy/envoy/pull/30259). These are concepts that exist in OpenTelemetry and further allow for proper enrichment/correlation of data + allowing them to better configure the volume of data exported, which is crucial for cost management.

With our Dynatrace extension in Istio, we can then also configure for our customers the Dynatrace resource detector + Sampler. If we would rely purely on the OTel extension in Istio, our customers would have to configure all of this themselves, which is not optimal.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Opening this official issue as discussed on Slack with [Jianpeng He](https://github.com/zirain).

**Comment by howardjohn** [comment]
The thing I am a bit worried about is otel has a vast ecosystem. 100s of integrations. We probably don't want to end up with 100 light wrappers around otel in Istio APIs. 

Lightstep I would consider an exception; it has been around in Istio for 5+ years, before any of the OpenX projects - and it is deprecated in favor of configuring Otel directly.

One thing that may help would be to show the configuration a user would have to do today to use Dynatrace with Istio, and perhaps with the proposed solution?

**Comment by joaopgrassi** [comment]
@howardjohn I totally understand the concerns. 

Unfortunately, our experience is that even with documentation, we get many support requests from customers and most of the time it's just misconfiguration. For example, users need to provide the URL and authentication token as an HTTP header and those causes a lot of confusion for some reason. They also misconfigure the protocol, for ex use `gRPC` or use `HTTP` but providing the `gPRC` default collector port instead. You can see some examples of the above [here](https://github.com/open-telemetry/opentelemetry-js/issues/4166), [here](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1743) and [here](https://github.com/open-telemetry/opentelemetry-js/issues/4120).

I fear that if we go this route, users would then just start opening issues here, confusing such errors as bugs with the extension/tracer, just like we see either as Dynatrace support requests or in the wild in the OTel repos. 

And this is just the exporter, as I said in the original OP, we are also working on other features in the OTel tracer in Envoy, that allows configuring resource detectors and a customer Sampler, so the configuration will "add up". 

Here's an estimated Istio mesh configuration when all of the above components are merged:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        # 1 for HTTP and a MESH_EXTERNAL back-end this would need to be most likely 443
        # can easily be misconfigured with the collector gRPC port (default for most cases..)
        port: 4317
        # 2 misconfigured the URL
        service: {your-environment-id}.live.dynatrace.com
        # New concept we don't have today in Istio
        protocol: otlp_http
        headers:
        # 3 misconfigured header format for the API token
            Authorization: "Api-Token token"
        resource_detectors:
            - dynatrace:
            - environment
            - ...
        # 4 redundant configuration we can derive from the service host
        sampler:
            - dynatrace
              sampler_config_url: {your-environment-id}.live.dynatrace.com/sampler/...
              more..
```

1. They very often misconfigure the port. All sorts of weird combination, like in the linked JS issues I posted above

2. They need to use the full URL `https://{your-environment-id}.live.dynatrace.com/api/v2/otlp/v1/traces`, but in most OTel SDKs, the path is appended automatically by the exporter, so I can already see they not providing `v1/traces` for ex, or something else. We see this today quite often.

3. Same thing - common misconfiguration area, even so with a bunch of documentation in the Dynatrace support pages. 

4. Redundant as we can derive most of this configuration from the others above

Compared to what it would look like with our own extension in Istio:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: dynatrace
      dynatrace:
        service: {your-environment-id}.live.dynatrace.com
        apiToken: dt0c01.abc
```
 
This way, most can be skipped as we know which config is the best for the customer - which resource detector, which sampling strategy, how to specify the auth token, what is the full OTLP receiver path and etc.


> 100s of integrations. We probably don't want to end up with 100 light wrappers around otel in Istio APIs.

For tracing at least, I think it would be the major vendors, which are only a handful. Also, I believe the "maintenance burden" would not be different if Dynatrace had a proprietary tracer in Envoy, like AWS, Datadog or Zipkin. If we went that route, we would still need to add an Extension Provider here in Istio APIs, right? So I don't see much difference but maybe I'm wrong.

All in all, I understand your concerns but I think wrapping the OTel tracer with some "syntatic sugar" to make configuration easier is beneficial for everybody. Reduces bugs/issues reported in Istio, in our support channels and less frustrations for Istio users.
