### ISSUE TITLE
File path based Gateway TLS setting is not working when using SPIRE as workload identity issuer.

### ISSUE THREAD

**Issue by cb-troydai** [istio/istio#47481]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

*Hypothesis*

When SPIRE is configured to provide workload identity it replaces the default sds-cluster. However for ingress gateway, the source of the TLS certs is also moved to sds-cluster. The default SDS client, when SPIRE workload api socket is not mount, understand the specific resource name `file-cert:<key>~<cert>`. However, once it is replaced by SPIRE, the above resource name is passed onto the `spire-agent`, which is not able to resolve it.

This breaks the file based TLS SIMPLE mode configuration when SPIRE is the workload identity issuer.

*Context*
I set up my mesh to use SPIRE issuing workload identity. Traffic between proxies, including ingress gateway, are mTLS based on SPIRE issued identity. Workload socket are mounted from spire-agent through CSI.

*Error case*
I'm trying to set up SIMPLE mode TLS at the ingress gateway. Following is the Gateway resource:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: mesh-config
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 8080
        protocol: HTTP
    - hosts:
        - "romeo.example.net"
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /run/secrets/gateway-tls/tls.key
        serverCertificate: /run/secrets/gateway-tls/tls.cert
```

Running this configuration, I fail to curl over TLS. (I replaced the host name in logs below to avoid expose internal details)

_The gateway open up at 8443, but my NLB maps 443 to 8443._

```
❯ curl -k https://romeo.example.net/httpbin/hostname
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to romeo.example.net:443
```

```
❯ openssl s_client -connect romeo.example.net:443
CONNECTED(00000006)
00D329DB01000000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:304:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 345 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

```
❯ istioctl proxy-config secret istio-ingressgateway-6bd97dcb68-22rc5.istio-system
RESOURCE NAME                                                                    TYPE           STATUS      VALID CERT     SERIAL NUMBER                                NOT AFTER                NOT BEFORE
file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key                    WARMING     false
...

```

In ingress gateway log stream, I saw
```
2023-10-20T02:30:35.254103Z     warning envoy config external/envoy/source/common/config/grpc_stream.h:153      StreamSecrets gRPC config stream to sds-grpc closed: 3, workload is not authorized for the requested identities ["file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key"]      thread=18
```

It seems to me that the proxy attempted to fetch identity from spire-agent for unknown reason.

I dump the config on ingress gateway, the TLS config doesn't seem to be right

```
            "tls_certificate_sds_secret_configs": [
             {
              "name": "file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key",
              "sds_config": {
               "api_config_source": {
                "api_type": "GRPC",
                "grpc_services": [
                 {
                  "envoy_grpc": {
                   "cluster_name": "sds-grpc"
                  }
                 }
                ],
                "set_node_on_first_message_only": true,
                "transport_api_version": "V3"
               },
               "resource_api_version": "V3"
              }
             }
            ]
```

*Alternative*

Using the same cert and key, I place them in Kubernetes secret, the TLS works correctly.
```
      tls:
        mode: SIMPLE
        credentialName: romeo
```

That indicate the keys and cert are correct.

*Restriction*

I don't wish to use Kubernetes secret to store the key and cert as it is not safe. My design is to use a sidecar mount in memory medium with the gateway and rotate the cert and key in memory.

### Version

```Text
❯ istioctl version
client version: 1.19.0
control plane version: 1.18.2
data plane version: 1.18.2 (6 proxies)
```

**Comment by cb-troydai** [comment]
What is weird to me is that the TLS context created even for file is a SDS API config
https://github.com/istio/istio/blob/master/pilot/pkg/security/model/authentication.go#L243

**Comment by cb-troydai** [comment]
Trace back to the removal of TlsCertificate in this PR https://github.com/istio/istio/pull/25786/files

What's the supported approach to use file based cert and key directly without secret?

**Comment by hzxuzhonghu** [comment]
@ramaraochavali

**Comment by cb-troydai** [comment]
Folks, any update?

**Comment by cb-troydai** [comment]
I also understand this change has been made two years ago. And I believe the scenario I demand this broken since. I suspect rarely have users use SPIFFE/SPIRE integration while *not* using Kubernetes secret for Gateway's TLS credential. Thus you don't see a report.

The theory of this bug is simple. Now all the cert fetching is done through an SDS cluster. The default implementation of that cluster (the built in one when I do not mount spire-agent to the workload uds volume) under that the resource name `file-cert://<key-path>~<cert-path>`, which is parsed from the Gateway resource. Thus when SPIRE is NOT integrated the scenario works fine.

However, once a spire-agent's workload api socket is mount, the SDS cluster points to the spire-agent. The spire-agent do NOT understand that [`file-cert://`](https://github.com/istio/istio/blob/e07d9025a701e45d11c024e38f4edd816b175116/pkg/security/security.go#L551) resource name, hence it refused to issue the identity thus fail this scenario.

**Comment by ramaraochavali** [comment]
Is there a way to identify SPIRE-AGENT is enabled?

**Comment by cb-troydai** [comment]
Yes, I mount the spire-agent, I can see the cert through the x-forward-cert header. The whole point of this is that I need the mTLS backed by SPIFFE/SPIRE.

**Comment by cb-troydai** [comment]
This error is returned by spire-agent (I list it in the description of this issue)
```
2023-10-20T02:30:35.254103Z     warning envoy config external/envoy/source/common/config/grpc_stream.h:153      StreamSecrets gRPC config stream to sds-grpc closed: 3, workload is not authorized for the requested identities ["file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key"]      thread=18
```

**Comment by cb-troydai** [comment]
Pod description of ingress-gateway
```
Volumes:
  workload-socket:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            csi.spiffe.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:  <none>
```

Headers seen by application in the mesh also indicate the certs are issued by the SPIRE.

Logs in gateway
```
2023-10-17T01:24:26.572261Z     info    Workload SDS socket found. Istio SDS Server won't be started
```

**Comment by ramaraochavali** [comment]
My question - how do we identify when SPIRE is enabled? Where do you configure this?

**Comment by ramaraochavali** [comment]
is this by setting `spiffe.io/spire-managed-identity: true`  as described [here](https://github.com/istio/istio/blob/65d15b6b616ac969f2a354a990599fd908ba3b28/samples/security/spire/README.md?plain=1)

**Comment by cb-troydai** [comment]
No. Above annotation has nothing to do whether the ingress gateway use SPIRE identity. It is about using spire managed control to register identity for ingress gateway. We do not use it, we manually register an identity. This annotation is omitable.

For istio-proxy to work with spire-agent, the only thing you need is to mount the spire-agent's workload api socket path to the workload-socket. The istio-proxy do not need to be explicitly configured to use spire, it *always* use the SDS mount at `/run/secrets/workload-spiffe-uds`. Thus just need to replace that folder with the volume from spire-agent daemon set.

Here's the gateway istio proxy's mutation:
```
    gateway-spire: |
      spec:
        containers:
        - name: istio-proxy
          volumeMounts:
          - name: workload-socket
            mountPath: /run/secrets/workload-spiffe-uds
            readOnly: true
        volumes:
          - name: workload-socket
            csi:
              driver: "csi.spiffe.io"
              readOnly: true
        initContainers:
        - name: wait-for-spire-socket
          image: busybox:1.28
          volumeMounts:
            - name: workload-socket
              mountPath: /run/secrets/workload-spiffe-uds
              readOnly: true
          env:
            - name: CHECK_FILE
              value: /run/secrets/workload-spiffe-uds/socket
          command:
            - sh
            - "-c"
            - |-
              echo "$(date -Iseconds)" Waiting for: $${CHECK_FILE}
              while [[ ! -e $${CHECK_FILE} && ! -L $${CHECK_FILE} ]] ; do
                echo "$(date -Iseconds)" File does not exist: $${CHECK_FILE}
                sleep 15
              done
              ls -l $${CHECK_FILE}
```
