### ISSUE TITLE
Istio is configured with two vss. How to manage their priorities? the traffic of the first discovery is forwarded to the route with the rule prefix: /.

### ISSUE THREAD

**Issue by dorseysen** [istio/istio#47514]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I configure two vss. That is, 
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-gw-https-vs
  namespace: dorsey
spec:
  gateways:
    - istio-system/xxx-https
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /xxx/health
      route:
        - destination:
            host: podname0.namespace.svc.cluster.local
            port:
              number: 10000
            subset: v1
    - delegate:
        name: xx-vs
        namespace: xx-namespace
      match:
        - uri:
            prefix: /
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-gw-https-vs-1
  namespace: dorsey1
spec:
  gateways:
    - istio-system/xxx-https
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /dorsey
      route:
        - destination:
            host: podname1.namespace1.svc.cluster.local
            port:
              number: 10000
            subset: v1
```
the traffic of the first discovery is forwarded to the route with the rule prefix: /.，I expected traffic /dorsey to go to podname1, but it went to podname0.

I strongly want to know the direct route preference of two different vss (the configuration is the same in other places, only the match is different).

### Version

```Text
istio-1.8.6
```
