### ISSUE TITLE
DestinationPolicy circuitBreaker rules not applied to sidecar "in.<port>" cluster

### ISSUE THREAD

**Issue by prune998** [istio/istio#4751]
# Description
I'm using a DestinationPolicy rule to increase the number of connexions from my client to my server, behind an `istio-ingress`.

client -- grpc + tls --> istio-ingress (port 443) -- grpc --> useredge pod (port 1081)
```
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: useredged-circuit-breaker
  namespace: dev
spec:
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 10
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpMaxPendingRequests: 1000
      httpMaxRequests: 100000
      httpMaxRequestsPerConnection: 10000
      maxConnections: 100000
      sleepWindow: 30s
  destination:
    name: useredged
```

Looking at the `istio-ingress` `cluster` metrics, I see it is configured as : 
```
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_connections::100000
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_pending_requests::1000
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_requests::100000
out.useredged.dev.svc.cluster.local|grpc::default_priority::max_retries::3
```

This is working fine and I can go up to 10k+ client connexions, which result to around 8 TCP connexions to the `useredge`, multiplexing my 10k+ streams.

## adding Istio Sidecar
When adding the sidecar to the `useredge` pod (using auto-inject annotation), the local Istio config does not take care of the `DestinationPolicy`, leading to a configuration of : 
```
in.1081::default_priority::max_connections::1024
in.1081::default_priority::max_pending_requests::1024
in.1081::default_priority::max_requests::1024
in.1081::default_priority::max_retries::3
```

In this situation, is seems the local Istio Sidecar is limitting the number of requests the pod can handle.

# Version
Istio 0.7.0 + auto_inject on GKE 1.9.6
