### ISSUE TITLE
Listener misconfiguration can lead to ingress not being able to start

### ISSUE THREAD

**Issue by tehlers320** [istio/istio#47511]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Setting gateways + virtualservice in a certain way involving TCP listeners can cause the ingress to not start. 

```
2023-10-22T17:10:58.577375Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:128	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: error adding listener '0.0.0.0:8443': filter chain '' has the same matching rules defined as ''
```

Add a config like this (it needs two similarly configured apps because the bug is when you bind two gateways to the same tcp listener port)

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: break-lds-dev-2
  namespace: break-lds
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - break-lds2-dev.some.us-west-4.madeup.domain
    - break-lds2-devsome.madeup.domain
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: break-lds
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
  - hosts:
    - tcp-break-lds2-dev.some.us-west-4.madeup.domain
    - tcp-break-lds2-devsome.madeup.domain
    port:
      name: tcp
      number: 443
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: break-lds-dev-3
  namespace: break-lds
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - break-lds3-dev.some.us-west-4.madeup.domain
    - break-lds3-devsome.madeup.domain
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: break-lds
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
  - hosts:
    - tcp-break-lds3-dev.some.us-west-4.madeup.domain
    - tcp-break-lds3-devsome.madeup.domain
    port:
      name: tcp
      number: 443
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: break-lds-dev-2
  namespace: break-lds
spec:
  gateways:
  - break-lds-dev-2
  - break-lds-dev-3
  - mesh
  hosts:
  - break-lds2-dev.some.us-west-4.madeup.domain
  - tcp-break-lds2-dev.some.us-west-4.madeup.domain
  - break-lds2-dev.break-lds.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: break-lds-dev-2
        port:
          number: 8081
  tcp:
  - route:
    - destination:
        host: break-lds-dev-2
        port:
          number: 6565
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: break-lds-dev-3
  namespace: break-lds
spec:
  gateways:
  - break-lds-dev-3
  hosts:
  - break-lds3-dev.some.us-west-4.madeup.domain
  - tcp-break-lds3-dev.some.us-west-4.madeup.domain
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: break-lds-dev-3
        port:
          number: 8081
  tcp:
  - route:
    - destination:
        host: break-lds-dev-3
        port:
          number: 6565
```

After this your ingress can no longer start. 

### Version

```Text
client version: 1.19.3
control plane version: 1.19.1
data plane version: 1.19.1 (64 proxies)
```

### Additional Information

This bug may have impacted older versions or its just simply user error. 

in 1.18 or 19 

```
cannot patch "break-lds" with kind Gateway: admission webhook "rev.validation.istio.io" denied the request: configuration is invalid: server cannot have TLS settings for non HTTPS/TLS ports
```

because our prior config would be the same expect the gateway would have a tls block on the TCP section  
```
    tls:
      credentialName: break-lds
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

Im not sure if this was related or this in fact saved us from letting bad config parse before.
