### ISSUE TITLE
gateway api: migration to http route not working as expected

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#47520]
Hi,

I am trying to migrate from virtual service to http route, 
I will try to describe the flow of my application, my route to my application is `app.example.com`
I am hosting my app on aws cloudfront, when accessing the app on any route except `/api` the user is forwarded to s3 and gets the static files, when the route prefix is `/api` the user is forwarded to aws ALB and then to istio with httproute.

diagram:
```
app.example.com -> cloudfront -> s3 -> static files
(not working anymore)
app.example.com/api/somerequest -> cloudfront -> alb -> gateway (gateway api) -> httproute -> backend service
(worked in past)
app.example.com/api/somerequest -> cloudfront -> alb -> gateway (istio gateway) -> virtualservice -> backend service
```

My problem is that the backend service can't get the request from the http route and I can't figure out why.
Everything is working fine with istio virtual service, but not with httproute and gateway api.
(if I expose another service that does not go from cloudfront like `admin.example.com` it works well).

istio config (works):
```
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: external-gateway
  namespace: istio-ingress
spec:
  servers:
    - port:
        number: 443
        protocol: HTTPS
        name: https
      hosts:
        - '*'
      tls:
        mode: SIMPLE
        credentialName: tls-secret
  selector:
    istio: ingressgateway

---

kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: backend-service
  namespace: example
  labels:
    app: backend-service
spec:
  hosts:
    - app.example.com
  gateways:
    - istio-ingress/external-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: backend-service
            port:
              number: 80
```

gateway api config (not working)
```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: external-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: tls-secret
            namespace: istio-ingress
      allowedRoutes:
        namespaces:
          from: All

---

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: backend-service
  namespace: example
  labels:
    app: backend-service
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-ingress
      name: external-gateway
  hostnames:
    - app.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ''
          kind: Service
          name: backend-service
          port: 80
          weight: 1
```

Why gateway api does not get that the request that passed from cloudfront is `app.exmaple.com` and pass the request to the backend service?

Another question:
I have seen that istio creates autogenerated virtual service on each httproute, if I want to migrate to gateway api, should I still create a virtual service for the `mesh` gateway? (or to specify internal service dns on the virtual service hosts?)

**Comment by howardjohn** [comment]
Hey, we are going to need a bit more info here. Can you check the status of the HTTPRoute and Gateway? it will expose any errors.

What is "not working"? Are there logs or error codes, etc?

See https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by Rez0k** [comment]
> Can you check the status of the HTTPRoute and Gateway

Gateway with status:
```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: external-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: tls-secret
            namespace: istio-ingress
      allowedRoutes:
        namespaces:
          from: All
status:
  addresses:
    - type: Hostname
      value: external-gateway-istio.istio-ingress.svc.cluster.local
  conditions:
    - type: Accepted
      status: 'True'
      observedGeneration: 5
      lastTransitionTime: '2023-10-17T14:47:19Z'
      reason: Accepted
      message: Resource accepted
    - type: Programmed
      status: 'True'
      observedGeneration: 5
      lastTransitionTime: '2023-10-17T14:47:22Z'
      reason: Programmed
      message: >-
        Resource programmed, assigned to service(s)
        external-gateway-istio.istio-ingress.svc.cluster.local:443
  listeners:
    - name: https
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
      attachedRoutes: 5
      conditions:
        - type: Accepted
          status: 'True'
          observedGeneration: 5
          lastTransitionTime: '2023-10-17T14:47:19Z'
          reason: Accepted
          message: No errors found
        - type: Conflicted
          status: 'False'
          observedGeneration: 5
          lastTransitionTime: '2023-10-17T14:47:19Z'
          reason: NoConflicts
          message: No errors found
        - type: Programmed
          status: 'True'
          observedGeneration: 5
          lastTransitionTime: '2023-10-17T14:47:19Z'
          reason: Programmed
          message: No errors found
        - type: ResolvedRefs
          status: 'True'
          observedGeneration: 5
          lastTransitionTime: '2023-10-17T14:47:19Z'
          reason: ResolvedRefs
          message: No errors found
```

HTTPRoute with status
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: backend-service
  namespace: example
  labels:
    app: backend-service
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-ingress
      name: external-gateway
  hostnames:
    - app.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ''
          kind: Service
          name: backend-service
          port: 80
          weight: 1
status:
  parents:
    - parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        namespace: istio-ingress
        name: external-gateway
      controllerName: istio.io/gateway-controller
      conditions:
        - type: Accepted
          status: 'True'
          observedGeneration: 11
          lastTransitionTime: '2023-10-22T12:28:14Z'
          reason: Accepted
          message: Route was valid
        - type: ResolvedRefs
          status: 'True'
          observedGeneration: 11
          lastTransitionTime: '2023-10-22T12:28:14Z'
          reason: ResolvedRefs
          message: All references resolved
```

I opened kiali and saw that istio created autogenerated virtual service:
```
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: backend-service-0-istio-autogenerated-k8s-gateway
  namespace: example
  annotations:
    internal.istio.io/parents: HTTPRoute/backend-service.example
    internal.istio.io/route-semantics: gateway
spec:
  hosts:
    - app.example.com
  gateways:
    - istio-ingress/external-gateway-istio-autogenerated-k8s-gateway-https
  http:
    - name: example.backend-service.0
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: backend-service.example.svc.cluster.local
            port:
              number: 80
status: {}
```

> What is "not working"? Are there logs or error codes, etc?
No error logs at istiod / the gateway pod (in istio-ingress namespace)

`app.exmaple.com` serves the frontend (via S3) and the backend (by the prefix `/api`) 
the flow is:
```
app.example.com -> cloudfront -> s3 -> static files
app.example.com/api/somerequest -> cloudfront -> aws alb -> gateway (gateway api) -> httproute -> backend service
```

No requests with the `/api` prefix  reaching the backend service and I can't figure out why.
as I mentioned above, it works with istio (no gateway api):
```
app.example.com/api/somerequest -> cloudfront -> alb -> gateway (istio gateway) -> virtualservice -> backend service
```

I changed istio config to gateway api config and now backend service not getting any requests.

Why the HTTPRoute can't see that the traffic (with `/api` prefix) should be forwarded to the backend service?

<b>Note</b>: if I am using HTTPRoute on pods without the cloudfront network hop everything is working fine with gateway api, for example:
```
app2.example.com -> aws alb -> gateway (gateway api) -> httproute -> service2
```

Does the gateway api can't read (and forward) some headers coming from cloudfront?
I know it's probably wrong but it seems like HTTPROUTE not reading the HOST HEADER coming from cloudfront, and then can't forward the traffic to the backend service.
