### ISSUE TITLE
Egress logs break when enabling filtering with new Telemetry API

### ISSUE THREAD

**Issue by jbilliau-rcd** [istio/istio#47533]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are on Istio 1.17.8 and trying to filter out healthcheck logs from AWS Route53 healthchecks. According to the docs, I've setup a new `Telemetry` object using the below YAML:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-defaults
  namespace: istio-config
spec:
  accessLogging:
  - filter:
      expression: '!(request.useragent.startsWith("Amazon-Route53-Health-Check-Service"))'
    match:
      mode: CLIENT
    providers:
      - name: envoy
```

And it does work....however, egress logs break for some reason. I get the below log when doing a `curl https://www.google.com` from my Istio-injected pod:

[2023-10-23T21:14:44.179Z] "- - -" 0 - "-" 883 24293 139 - "-" "-" "-" "-" "142.250.190.36:443" outbound|443||www.google.com 172.18.36.204:41698 240.240.100.242:443 172.18.36.204:38594 - - -

Once I apply that `Telemetry` object, this stops working. I've tried it without the `match.mode` block as well, same results. 

Using docs here - https://istio.io/latest/docs/reference/config/telemetry/#WorkloadMode

### Version

```Text
istioctl version
client version: 1.19.3
istiod version: 1.17.8
istiod version: 1.17.8
istiod version: 1.17.8

kubectl version --short
Client Version: v1.25.12
Kustomize Version: v4.5.7
Server Version: v1.25.12-eks-2d98532
```

**Comment by zirain** [comment]
can you share the config dump? before vs after?

**Comment by howardjohn** [comment]
Is `istio-config` configured as the rootNamespace or where the workload runs? By default it isn't, so it may not be applying at all

**Comment by zirain** [comment]
I can reproduce this, configuration looks good.

```
- name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - filter:
            extensionFilter:
              name: envoy.access_loggers.extension_filters.cel
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.access_loggers.filters.cel.v3.ExpressionFilter
                expression: '!(request.useragent.startsWith("Amazon-Route53-Health-Check-Service"))'
          name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        cluster: PassthroughCluster
        statPrefix: PassthroughCluster
```
