### ISSUE TITLE
Trying to add label and value to existing metric, instead it prefixes metric name with the label. 

### ISSUE THREAD

**Issue by BenCoughlan15** [istio/istio#47580]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

hey! 

I have a Telemetry config like this: 

```
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: istio-requests-total-business-mode
  namespace: development
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  metrics:
  - overrides:
    - match:
        metric: REQUEST_COUNT
      tagOverrides:
        business_app_mode:
          value: "string(request.headers['business-app-mode'])"
    providers:
    - name: prometheus
---
```

essentially I'd like to take the outcome of the request header, and append it to the metric as a label, this would allow me to filter out the "test" metrics from the "live" metrics, based off the header value. 

Instead, what's happening, is it suffixes my metric name as follows:

business_app_mode___unknown___**istio_requests_total**
business_app_mode___test___**istio_requests_total**
business_app_mode___live___**istio_requests_total**

Is there something glaringly obvious that I'm missing? 

i.e., 
I'm looking for: 
istio_requests_total{connection_security_policy="unknown", container="istio-proxy", destination_app="unknown", **business_app_mode="test"**, ...etc}

not:
business_app_mode___test___istio_requests_total{connection_security_policy="unknown", container="istio-proxy", destination_app="unknown"... etc}

I've scoured the documentation, and can't find anything, am I being really silly? 

### Version

```Text
> istioctl version
client version: 1.19.3
control plane version: 1.15.4
data plane version: 1.15.4 (17 proxies)
> kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.14-gke.2700
```

### Additional Information

> istioctl bug-report

Target cluster context: dev-au

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-10-25 17:12:46.191322 +0100 BST
