### ISSUE TITLE
Istio 1.19.x and envoy.filters.http.ext_proc send unexpected headers

### ISSUE THREAD

**Issue by Toand** [istio/istio#47583]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When client sends a request to the gRPC pod (istio-proxy + gRPC container) with the regular header, the istio-proxy uses EnvoyFilter to send the request to the gRPC container.

See the following in the gRPC container debug logs:
```
time="2023-10-24T08:07:44Z" level=error msg="[key:\":authority\"  3:\"abc.xyz\" key:\":path\"  3:\"/\" key:\":method\"  3:\"GET\" key:\":scheme\"  3:\"https\" key:\"content-length\"  3:\"0\" key:\"x-forwarded-proto\"  3:\"https\" key:\"x-forwarded-for\"  3:\"x.y.z.x,y.z.y.y,z.z.z.z\"]"
time="2023-10-24T08:07:55Z" level=error msg=" Token invalid: string: Failed to split a string "
time="2023-10-24T08:07:55Z" level=error msg="getAccessToken got err=string: Failed to split a string "
time="2023-10-24T08:07:55Z" level=error msg="Call http request got error: invalid_grant. StatusCode: 400"
```
Excepted: 
```
time="2023-10-24T08:07:44Z" level=error msg="[key:\":authority\"  value:\"abc.xyz\" key:\":path\"  value:\"/\" key:\":method\"  value:\"GET\" key:\":scheme\"  value:\"https\" key:\"content-length\"  value:\"0\" key:\"x-forwarded-proto\"  value:\"https\" key:\"x-forwarded-for\"  value:\"x.y.z.x,y.z.y.y,z.z.z.z\"]"
```
Header name/value pair:
https://github.com/envoyproxy/go-control-plane/blob/v0.11.0/envoy/config/core/v3/base.pb.go#L1091

````
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-extproc-filter
spec:
  workloadSelector:
    labels:
      app: grpc
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_proc
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
          failure_mode_allow: false
          processing_mode:
            request_header_mode: "DEFAULT"
            response_header_mode: "SKIP"
          grpc_service:
            envoy_grpc:
              cluster_name: grpc-processor-cluster
          message_timeout: 2s
  - applyTo: CLUSTER
    patch:
      operation: ADD
      value:
        http2_protocol_options: {}
        name: grpc-processor-cluster
        type: STATIC
        load_assignment:
          cluster_name: grpc-token-processor-cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 18080
        health_checks:
        - timeout: 1s
          interval: 5s
          unhealthy_threshold: 1
          healthy_threshold: 3
          grpc_health_check:
            service_name: "envoy.service.ext_proc.v3.ExternalProcessor"
````

### Version

```Text
istio: 1.19.1
EKS: 1.28
```

### Additional Information

There were no issues discovered in Istio 1.17.x or 1.18.5.
