### ISSUE TITLE
Documentation for Ingress Gateway deployment doesn't require Role for native k8s Gateways

### ISSUE THREAD

**Issue by terabyte128** [istio/istio#47599]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've followed the instructions for manually [deploying a Gateway](https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway), using modified Kubernetes YAML instructions and adding a listener on port 443 for HTTPS. 

Note that the deployed YAML intentionally **does not include** a Role allowing the pod to access any secrets.

```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: cluster-ingress
spec:
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: cluster-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  template:
    metadata:
      annotations:
        # Select the gateway injection template (rather than the default sidecar template)
        inject.istio.io/templates: gateway
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways can select this workload
        istio: ingressgateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with "istio.io/rev: revision-name"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: istio-proxy
        image: istio/proxyv2:test
        imagePullPolicy: Never
```

I've also deployed a native k8s Gateway that references an existing, valid certificate:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: cluster-ingress
spec:
  gatewayClassName: istio
  addresses:
  - value: istio-ingressgateway.cluster-ingress.svc.cluster.local
    type: Hostname
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: gateway-tls
```

And I find that this configuration works properly, despite the lack of anything granting the Ingress Gateway pod access to the TLS secret. 

I have also tried this with an Istio Gateway resource (rather than a k8s native one) and found that it _does not_ work without the proper role (as I would expect).

From looking through logs, it seems like the certificate for the native Gateway is being retrieved by the `istiod` pod, while the certificate for the Istio Gateway is retrieved by the Ingress Gateway pod. 

So I have a couple questions:
* Is this expected behavior?
* If the permissions are not required for native k8s Gateways, should it be noted in the documentation?

### Version

```Text
$ istioctl version
client version: 1.19.3
control plane version: 1.19-dev
data plane version: 1.19-dev (1 proxies)
$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.27.4
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/13174677/bug-report.tar.gz)
