### ISSUE TITLE
securityContext is not applied when runAsRoot is set to true

### ISSUE THREAD

**Issue by calikonur** [istio/istio#47603]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

When deploying Istio GW using the runAsRoot=true , no securityContext is applied at all. Is there any reason to keep whole securityContext block out of the container? What are the parameters in the securityContext that can be set even though we want Istio GW to run with "runAsRoot=true" option?

### Version

```Text
client version: 1.17.2
control plane version: 1.18-dev
data plane version: 1.18.3 (3 proxies)
```

**Comment by calikonur** [comment]
I use the customized version of Gateway's Helm Chart and take the securityContext out of the {{- if not .Values.runAsRoot }}{{- end}} block in the container level.
So it became 
```
containers:
    - name: istio-proxy
  ...
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
```
instead of 
```
containers:
    - name: istio-proxy
  ...
      {{- if not .Values.runAsRoot }}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
     {{- end }}
```

Then I have created a values file that will modify the ServiceMesh Gateway target ports to the ports below 1024 and added one more port 88 just to test it:
```
gateways:
  istio-ingressgateway:
    name: istio-ingressgateway
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    ports:
    ## You can add custom gateway ports in user values overrides, but it must include those ports since helm replaces.
    # Note that AWS ELB will by default perform health checks on the first port
    # on this list. Setting this to the health check port will ensure that health
    # checks always work. https://github.com/istio/istio/issues/12503
    - port: 15021
      targetPort: 15021
      name: status-port
      protocol: TCP
    - port: 80
      targetPort: 80
      name: http2
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
   - port: 88
      targetPort: 88
      name: http
      protocol: TCP
```

After that, I deployed istio with "runAsRoot=true" , run an httpbin service inside mesh and applied following Gateway and VirtualService resources
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpbin-credential # must be the same as secret
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: httpbin
```
When I send curl request to the ingress gateway I can get reply.
So applying securityContext did not change any functionality when running GW with "runAsRoot=true" mode, although I was expecting it the gateway either crash or does not send the traffic. Because now gateway binds envoy process to the port 443, which is below 1024.
So my question is that this has been resolved in some envoy (or istio?) changes at some point? Or is it possible that it is an environment problem?
