### ISSUE TITLE
istioctl cannot pass parameters as tolerations

### ISSUE THREAD

**Issue by iop45636** [istio/istio#47638]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi All,

Is there any way to edit the istio's tolerations via istioctl? since no more information about how to pass the tolerations for istio.

and actually, i need to pass the toleration parameters when i install the istio by istioctl and the parameters as below:
```
tolerations:
- key: usage
  effect: NoSchedule 
  operator: Equal
  value: system
```

### Version

```Text
istioctl v1.14.6
kubernetes v1.24.8
```

### Additional Information

the environment required the toleration for workload deployment

**Comment by hanxiaop** [comment]
Have you tried this?
```
spec:
  components:
    pilot:
      k8s:
        tolerations:
        - ...
```
