### ISSUE TITLE
CA Certs broken, never recover

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#47650]
Situation:
Istiod from master installed. It worked ok.

~80 minutes later, mutating webhook configmap was updated. At this point, injection broke. The Webhook config shows the wrong cert, and is constantly patched to the wrong cert:

```
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUs3aEkveGN6WVhhV3hiZHgwQWpLbGN3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16RXdNekF4T1RVeE5UaGFGdzB6TXpFdwpNamN4T1RVeE5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFY4VlhGZWN4RnY0TW1nVnhubk1HYWxicHpVaXM1d0tmVGNsMTAKbGxtUHpOSDlSV1h1Y0xHc1pOdTBIUExhQ0Nzd2M2d1NsbWQvcTMwcFNVOXcxVGFjbERVUWxZTEYwR2Q3aWNSYgpEcjZtcG9ncjJXaDJNMmJDRFBsTFZWUk1keXZRMm5qSkEwK2V5VDlhV0lyS2JBMnpEb0xFb3pMWGJUbWd2d1RKClkyYzNFbjZBY0tKcFBLTkI2Y1BkeXMyWXBJekticU9jMnBOSFNmOUdCc0lvSWJ5WERZdmdVQWRKK1J1Skp0b3MKUUVSOGFaZHJSWm1RQzJWUWVhcmdmeEZPL0V2dExSdjdiT0pXVklEQzNLVXVMc3ZYajAwaWJBN2N3RXZLMHdDcgpYeFFtVzJUOGR2RHhGelZHOEEwSWdrd0UrOHlid2hUUEpLZEZFR3dGQzlGVGYwdkhBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFzUDFJR0lwU3UKT1pjUnN2SlVmZ2p4My81d2xEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFRc0RkT2NLSlpuQkNZQWdKdmhLdgpKWnRWZWVYMFJYcXF4Y1VUMlN4ek5YNzhNUExmVjdFeHM1aWk5dXBrTXAwNFR6SVFQZUNBUkViR3B3TWJVcVkwCm8xR2gxSjNQQUpVSjczbUdnamhnYVIyS0tUcHIyRi9nSHFTVjJVWlJyZWV4OXY0ZkNoR3VLTHQzS3VtcmxON0oKR0EyNVVVMU9oWE1DU01jYTZNNnlsYjlOTFZ4dGpVaStsTnpPbXYzaUZNRnNORXdXcjdTa2ZxSlNrVFl6bkRyVgpkQkZZQTVQa09XcGI3NGVBajI4QzlENXFxM1U3T2lzczhzMzFBVFh6TWlXL0x6RW0xeHdvd0hJUk5CeWQvV2xCCnloQVAzVlFOei9hcXZjbG9SYnJEWEdLSTFjRnVQeC9MQnI3eDZmMHRnSmFxd0h2SWJhQ1ZCUmFFeG12STkvZCsKL1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
```

This same cert is the `root-cert.pem` from cacerts:

```
apiVersion: v1
data:
  ca-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUs3aEkveGN6WVhhV3hiZHgwQWpLbGN3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16RXdNekF4T1RVeE5UaGFGdzB6TXpFdwpNamN4T1RVeE5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFY4VlhGZWN4RnY0TW1nVnhubk1HYWxicHpVaXM1d0tmVGNsMTAKbGxtUHpOSDlSV1h1Y0xHc1pOdTBIUExhQ0Nzd2M2d1NsbWQvcTMwcFNVOXcxVGFjbERVUWxZTEYwR2Q3aWNSYgpEcjZtcG9ncjJXaDJNMmJDRFBsTFZWUk1keXZRMm5qSkEwK2V5VDlhV0lyS2JBMnpEb0xFb3pMWGJUbWd2d1RKClkyYzNFbjZBY0tKcFBLTkI2Y1BkeXMyWXBJekticU9jMnBOSFNmOUdCc0lvSWJ5WERZdmdVQWRKK1J1Skp0b3MKUUVSOGFaZHJSWm1RQzJWUWVhcmdmeEZPL0V2dExSdjdiT0pXVklEQzNLVXVMc3ZYajAwaWJBN2N3RXZLMHdDcgpYeFFtVzJUOGR2RHhGelZHOEEwSWdrd0UrOHlid2hUUEpLZEZFR3dGQzlGVGYwdkhBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFzUDFJR0lwU3UKT1pjUnN2SlVmZ2p4My81d2xEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFRc0RkT2NLSlpuQkNZQWdKdmhLdgpKWnRWZWVYMFJYcXF4Y1VUMlN4ek5YNzhNUExmVjdFeHM1aWk5dXBrTXAwNFR6SVFQZUNBUkViR3B3TWJVcVkwCm8xR2gxSjNQQUpVSjczbUdnamhnYVIyS0tUcHIyRi9nSHFTVjJVWlJyZWV4OXY0ZkNoR3VLTHQzS3VtcmxON0oKR0EyNVVVMU9oWE1DU01jYTZNNnlsYjlOTFZ4dGpVaStsTnpPbXYzaUZNRnNORXdXcjdTa2ZxSlNrVFl6bkRyVgpkQkZZQTVQa09XcGI3NGVBajI4QzlENXFxM1U3T2lzczhzMzFBVFh6TWlXL0x6RW0xeHdvd0hJUk5CeWQvV2xCCnloQVAzVlFOei9hcXZjbG9SYnJEWEdLSTFjRnVQeC9MQnI3eDZmMHRnSmFxd0h2SWJhQ1ZCUmFFeG12STkvZCsKL1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ca-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMWZGVnhYbk1SYitESm9GY1o1ekJtcFc2YzFJck9jQ24wM0pkZEpaWmo4elIvVVZsCjduQ3hyR1RidEJ6eTJnZ3JNSE9zRXBabmY2dDlLVWxQY05VMm5KUTFFSldDeGRCbmU0bkVXdzYrcHFhSUs5bG8KZGpObXdnejVTMVZVVEhjcjBOcDR5UU5QbnNrL1dsaUt5bXdOc3c2Q3hLTXkxMjA1b0w4RXlXTm5OeEorZ0hDaQphVHlqUWVuRDNjck5tS1NNeW02am5OcVRSMG4vUmdiQ0tDRzhsdzJMNEZBSFNma2JpU2JhTEVCRWZHbVhhMFdaCmtBdGxVSG1xNEg4UlR2eEw3UzBiKzJ6aVZsU0F3dHlsTGk3TDE0OU5JbXdPM01CTHl0TUFxMThVSmx0ay9IYncKOFJjMVJ2QU5DSUpNQlB2TW04SVV6eVNuUlJCc0JRdlJVMzlMeHdJREFRQUJBb0lCQVFDTStwVWNwaUFYcmhXTQpZQjQySUxQclc5TWJmd0FBOUpVaTN1LzZqY0RDNDZOVWxGQ1JDUzNyZmlMUTAycXNoa2wvaWhuUHZkREI3bzF4CmtWK0o2Tll0NC9QNzA2bnpGRnU4cXBIN3R3R202NEk3OHUzRlJpWG1wWW41UEdkcVkvVTVrVjJhaUZZRk9uUkcKNHFYQ3NlVnRJcGpGWHcxM3JBQVhqd2htZE54bEN0UFRhMkhraDJzYmxnN2NYY1U5cXExYzVnNjFDVUhHSUFxdgo3Q0Z1Y3gzczhQMENDM2V2N05aZzFiazRoR24vTGI3WUQ5UFNiMHF1NzRhbnM1NXBwWnZPZkNZQ1hZc2tyQkdyCjh6SlRPWjdlOGg1YmUzeWJjTzBjOElJSk1ZMVFnWUpEVi83NFV5VnRpQmw1NzZta21HUElwRU0wZ2ZMSnZqL3MKOXZYbTRla0JBb0dCQU53dGtBTzZvbEwyTkQ5RVNJRlZhZjZKMUVHOWk1bkFFOTNFeGp3YTNNQkhOOU8zRVlTeQpwVmNGbDRtbHZkMVg4bjdzL2VSbGY4REw2ODVzWUtKMWhsNWNZaUhxVVJldG9JZGF5bWphcjhtNzJ0ZHo5VUg0CnB3anlXU3cwOENhOStFUStGRm01azlLZkxCUkpvd0RpOE9ENXM2M295YWp1Rm1MTm05K3RacnlIQW9HQkFQakEKRXJQUE5jU0Y0OC9TVGswWWlXLzJyS1Ixa1ZtV0w3QThYWmorYVRucDUvRWZJT0pqZzhVQWZwa0NmSTRVTm13NApKbEtldjVaeG1IeDhmODJhd1huSVJ4MW4xZXJHV05CVGtVMm9IRXdTa2ZhNG94M005WWxnUE5tdVQ4ZUtVeitpCmM1b01aNzFHdDdUM1pMaFBmMGdtRkx2YWFQQ2k2d3BmQjdFU1lBYkJBb0dCQU0wc2pDcGRiY3hmYjdxUkYvdWwKcTVzdHR5VDN5N0lmd3FPRExiTnUyTTA0MEhZeS8xa24zRmxtZFpzb1h2QjNkeHIrSDI0SmcyNFcyUXZJQkpqLwphWkpmQm5kU1VmVDlzRHpSeHhMRXp0RHZoSFFIczhHaFE0NWJ2K3NvL2Ewc2s4Q01GUXl6bVdQSlBoczlyMjh4CkM0U3FTOXpBczhMKzhzOXBpRnA4ek9MYkFvR0FRMjZlSTB4YXdRbWl0aVhHd0RPVW5sdDZkYUxCWWszS1k3WVoKa1czMlRKTFNJNVZTcnN4WFhrSkNEMnlUSTFqclgrN2d4S2p3T3ZKVWFmcStFcGlQTmxwS25QZ1hEMnZ4aTVmNwozZGRpeEdTTVdSdTRiRTJ4aWlvaWxNZ2lMRytkSGJVR0xZNkxXTTRnNHRmbDMrajlFaXZ3bHZRZ1dvdHZ1QUlHCjdjT1RjSUVDZ1lBVVllbk9Nc3lYdncyZndxS0lVK3JXS1R1cURTMnhoM0dteldON1dBci9xVnRuNkRWdFprYTQKa0FXbStPWjVDVGhXZkI4THk2eUR0UUYxcUhZMEF4eStsQ3EveHZvSlFVN3Z1Sm51Tmp4T2lxNXo2SXRTNzFBRwpZS2RidmR0ZVorbllONnJpeEFialZEZ3d1NWIzRXplczFETjFBaUVnRkJ5cU5vREtwN25ianc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  cert-chain.pem: ""
  istio-generated: ""
  key.pem: ""
  root-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUs3aEkveGN6WVhhV3hiZHgwQWpLbGN3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16RXdNekF4T1RVeE5UaGFGdzB6TXpFdwpNamN4T1RVeE5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFY4VlhGZWN4RnY0TW1nVnhubk1HYWxicHpVaXM1d0tmVGNsMTAKbGxtUHpOSDlSV1h1Y0xHc1pOdTBIUExhQ0Nzd2M2d1NsbWQvcTMwcFNVOXcxVGFjbERVUWxZTEYwR2Q3aWNSYgpEcjZtcG9ncjJXaDJNMmJDRFBsTFZWUk1keXZRMm5qSkEwK2V5VDlhV0lyS2JBMnpEb0xFb3pMWGJUbWd2d1RKClkyYzNFbjZBY0tKcFBLTkI2Y1BkeXMyWXBJekticU9jMnBOSFNmOUdCc0lvSWJ5WERZdmdVQWRKK1J1Skp0b3MKUUVSOGFaZHJSWm1RQzJWUWVhcmdmeEZPL0V2dExSdjdiT0pXVklEQzNLVXVMc3ZYajAwaWJBN2N3RXZLMHdDcgpYeFFtVzJUOGR2RHhGelZHOEEwSWdrd0UrOHlid2hUUEpLZEZFR3dGQzlGVGYwdkhBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFzUDFJR0lwU3UKT1pjUnN2SlVmZ2p4My81d2xEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFRc0RkT2NLSlpuQkNZQWdKdmhLdgpKWnRWZWVYMFJYcXF4Y1VUMlN4ek5YNzhNUExmVjdFeHM1aWk5dXBrTXAwNFR6SVFQZUNBUkViR3B3TWJVcVkwCm8xR2gxSjNQQUpVSjczbUdnamhnYVIyS0tUcHIyRi9nSHFTVjJVWlJyZWV4OXY0ZkNoR3VLTHQzS3VtcmxON0oKR0EyNVVVMU9oWE1DU01jYTZNNnlsYjlOTFZ4dGpVaStsTnpPbXYzaUZNRnNORXdXcjdTa2ZxSlNrVFl6bkRyVgpkQkZZQTVQa09XcGI3NGVBajI4QzlENXFxM1U3T2lzczhzMzFBVFh6TWlXL0x6RW0xeHdvd0hJUk5CeWQvV2xCCnloQVAzVlFOei9hcXZjbG9SYnJEWEdLSTFjRnVQeC9MQnI3eDZmMHRnSmFxd0h2SWJhQ1ZCUmFFeG12STkvZCsKL1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
kind: Secret
metadata:
  name: cacerts
  namespace: istio-system
type: istio.io/ca-root
---
apiVersion: v1
data:
  ca-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRY2FkVFpneUQyckMwZTlJQ1o5eFExekFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1UQXpNREl4TURnMU5Gb1hEVE16TVRBeQpOekl4TURnMU5Gb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNNlJLaUVtdCtPNGZBU1luSkFvbjVYRGt6SWNLWk56RUV6TEZRb0YKN3cwMXJSV3IwVDYzbmk1VGtsaFM5RHF3eWh0ZUZQOC9kd0lOSGZ4cE1taFlGTHBITzg2b1Jpd200WVoxeVNmSgp2dG5ScFJNczRHdWQvQVUrZFlsWFB3YURrVFhTa3F0eDVkd0tqTGZGSzJ1VEpHaUlwY0FMZUxhMndMUUZxT3N2Ck9mU2JiMVZ5b2NGZEIvbG4wNVJCNjZpdU5zaU5TOGdaSXBDY1JYMzdmN1VRMW1IUXRsWUtGeDdKTGwvcXFKV1AKbTBIM25FRHYyV3BwbHByRG9YZUdNME1MT2NVWnhSanpmSThoeU53SGlGMSt3cWpnREtGc1ZaVzlaSTJ1eG5IMwpvaTM3Q1VNaFBBc3VSdnZTMzhrTmdLNUU2bHhNak50c0wvZjY5ekt4OVRLa3NvTUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGRTMvcjh3R2R0QlgKSVJXYmFaa2V1L3BPdUM5VU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzJ4clAvVUMrSm5OMnpSTUxzNnpOUQo5R0p5R0pVVXc5L2NuTnU2STlCOU1zQSs0TDJEVHVZRnN2MThUcm5zS3dNL2JJdEJMajkycmxXckk3N2NFSEJPCm0vTG5oVUFxR2FGN0wrVGNWT1piVEx2ZHg5aW1DNmxNM2dSaFdmUHBBMUJXcFY5QXhiMXZub252NTFsSXNkQ2UKOHE2RVRvYUxHREZTeWg1cmhwSHdFVW9RNldNMWRNbWpCRXhHcHpXQlVVMnozVC8zczA4aVJvOEE5TGwxRWVPZwpxWVBPbXZWWld2YlJoMjdjUFdPdjdQbnorVUx1VHN3MUtRbGxPd0U5N3FPL1ZsRldFNGNMbW5BV3JKTXdGOXVBCmE5eUdlTFdwSnJLb3J5OWNncmJYUlBDM2g2KytqRm1JUjJoWVJBQ3ZidVZUWDkvTmxJWEJXWm1oRE0rYzVnR0QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  ca-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBenBFcUlTYTM0N2g4QkppY2tDaWZsY09UTWh3cGszTVFUTXNWQ2dYdkRUV3RGYXZSClByZWVMbE9TV0ZMME9yREtHMTRVL3o5M0FnMGQvR2t5YUZnVXVrYzd6cWhHTENiaGhuWEpKOG0rMmRHbEV5emcKYTUzOEJUNTFpVmMvQm9PUk5kS1NxM0hsM0FxTXQ4VXJhNU1rYUlpbHdBdDR0cmJBdEFXbzZ5ODU5SnR2VlhLaAp3VjBIK1dmVGxFSHJxSzQyeUkxTHlCa2lrSnhGZmZ0L3RSRFdZZEMyVmdvWEhza3VYK3FvbFkrYlFmZWNRTy9aCmFtbVdtc09oZDRZelF3czV4Um5GR1BOOGp5SEkzQWVJWFg3Q3FPQU1vV3hWbGIxa2phN0djZmVpTGZzSlF5RTgKQ3k1Rys5TGZ5UTJBcmtUcVhFeU0yMnd2OS9yM01ySDFNcVN5Z3dJREFRQUJBb0lCQVFERTVOR0hiK1J3QnZVUApYSGcvWUxsY2cyTFdyTWxrWnBUdTNkUmNEWFBpMzNydjRTbzk0Yi9BNEovcDJJZzdPVEFzRGUxdHJ3eTh3OHdGClFEQndEU1VVdWJsa0xqbFU5R3FiUThKTlRwdS8rM2loWW5FM293c0o1Sk1jS2pGRkFEdDFWaFcvblgwLzFENTEKSEZkYTNwSWhvYjU3NDNOWWxiSHc1a1F3aUg5eGl0Q1psSzlFaEVPVTdTd1JydVAzL3Z3VTNwYXJ2WCswUzdqQwp3VExJTGZNNXZkZXN3ZkVPakdMYW9LSjMyWjhGVXE2SlFDaGRRdFBmU2dObFN3Vk40a0dhY2I0aUpISUNuRmFFCk0zVHFsblZtSkJhTlNmcTBydkxkek9ZQ0J2Zm5KdUlsNkFlQkZrZTdVVE93QXFKSHNGaXYwbGppZVNNL1VqUGQKQkFOK1RQWkJBb0dCQU9mTjNzdzhXT2lKOU14cXBwSzlsYmt1YzJ2YTltODVTeEwvUDVSVnlYWkdQSUJQU3pKNwpGdS91YW1FbEJ5Mjl6ZjlsKzIxSnc1QmpSSEhSQlhxVVN5d3M2MDlLM3pmM0JtUEQvZW82OEhHMDZ1OEhud1Q0ClkyKzhHcFptUWhCci9KMkNpbXd6eGdPK2RHWFY4THFHRDIxd3ErMnEvZ1l0V1ZGbmJEeldrZ2NwQW9HQkFPUWcKN0V6aVV0S0FQNW5ZcWxzaXlQQWkza1liWUxjYW5sWGtlVDdKbEpvNFU2c2JSMW8wSTk3SUNlT0NjdzZHMDlrcAp4bFkwZ01hd0JibFJDaFE2L1NxQi9TWkZBd1hFR0RYTXROa2JQMXFub045TjFtVjBjaEpGMFhySWRySldVVEo1Cld2RHFyV3MyMTA4THVXa09IaTBydFpHRHVtbmlSNXVKSFBkeHluM0xBb0dBY3Z2M0liNXBwK2dPNjN1WDUwQnQKemE4U0NCVlVtdldEblFmS2hRMU00d09TTFYrb0FJRjRia29Jc09tS054Rm81dUN5cUpLbmxLNzVHN0JBbEg2TgpEM3UwdWQ5OC9Lam5uWU55SjhkVzBFQ2JMVGpOazh5V25xMWpUdW1vcWJhM1YzYVNyWHU5Sk14THR0dzZEbnhECm1Oa0VIOS9ySkN0SW5BMitiaXROd29rQ2dZQUJSd25ydUV5OGJ3bHNKQ0Y0Rnk3RzRYc2JLMllVUUdyb2tqbjMKbHd0ay9iSENRSW5hd0hYKzltSFB5MWczbVp1d0dLTEtzc3FSMGtTRjhDVTlUY05ETEswdFBLK3lwWkY1STZkVAptK3B6NklKbkhibDRvZmxOanVTSWFuejNyTElSdFVwRUZSeFpnRm9lVUROK21oeWpKaDZETFJpckpTQS9oN29JCnpMTlVsd0tCZ1FEWHJPekRYQ1hzZzJBMmNZM0RxNTFvYWJQNFZocG9EbWEzM3A0QWF1RUNEZDlWcVdpUjF4QngKM0pDYXZSWEtzZ1YzeWRLUnhaNGJONWJ4bVN4K3ZqRlAycXB6MTNJWm1VUHBaQmRCdFduZE1jcVUvSDFEcVdZMwo3VkVVMzlYdXhWOGdtdTdUbHJpMkJJWFQwZ3V4VERiRXp6VSs5MXdNUVpFbGZxYVorKzFNRWc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  cert-chain.pem: ""
  istio-generated: ""
  key.pem: ""
  root-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRY2FkVFpneUQyckMwZTlJQ1o5eFExekFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1UQXpNREl4TURnMU5Gb1hEVE16TVRBeQpOekl4TURnMU5Gb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNNlJLaUVtdCtPNGZBU1luSkFvbjVYRGt6SWNLWk56RUV6TEZRb0YKN3cwMXJSV3IwVDYzbmk1VGtsaFM5RHF3eWh0ZUZQOC9kd0lOSGZ4cE1taFlGTHBITzg2b1Jpd200WVoxeVNmSgp2dG5ScFJNczRHdWQvQVUrZFlsWFB3YURrVFhTa3F0eDVkd0tqTGZGSzJ1VEpHaUlwY0FMZUxhMndMUUZxT3N2Ck9mU2JiMVZ5b2NGZEIvbG4wNVJCNjZpdU5zaU5TOGdaSXBDY1JYMzdmN1VRMW1IUXRsWUtGeDdKTGwvcXFKV1AKbTBIM25FRHYyV3BwbHByRG9YZUdNME1MT2NVWnhSanpmSThoeU53SGlGMSt3cWpnREtGc1ZaVzlaSTJ1eG5IMwpvaTM3Q1VNaFBBc3VSdnZTMzhrTmdLNUU2bHhNak50c0wvZjY5ekt4OVRLa3NvTUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGRTMvcjh3R2R0QlgKSVJXYmFaa2V1L3BPdUM5VU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzJ4clAvVUMrSm5OMnpSTUxzNnpOUQo5R0p5R0pVVXc5L2NuTnU2STlCOU1zQSs0TDJEVHVZRnN2MThUcm5zS3dNL2JJdEJMajkycmxXckk3N2NFSEJPCm0vTG5oVUFxR2FGN0wrVGNWT1piVEx2ZHg5aW1DNmxNM2dSaFdmUHBBMUJXcFY5QXhiMXZub252NTFsSXNkQ2UKOHE2RVRvYUxHREZTeWg1cmhwSHdFVW9RNldNMWRNbWpCRXhHcHpXQlVVMnozVC8zczA4aVJvOEE5TGwxRWVPZwpxWVBPbXZWWld2YlJoMjdjUFdPdjdQbnorVUx1VHN3MUtRbGxPd0U5N3FPL1ZsRldFNGNMbW5BV3JKTXdGOXVBCmE5eUdlTFdwSnJLb3J5OWNncmJYUlBDM2g2KytqRm1JUjJoWVJBQ3ZidVZUWDkvTmxJWEJXWm1oRE0rYzVnR0QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
kind: Secret
metadata:
  name: istio-ca-secret
  namespace: istio-system
type: istio.io/ca-root
```

The Istiod logs show 2 root certs though:

```
2023-10-30T21:15:51.871112Z     info    creating CA and initializing public key
2023-10-30T21:15:51.871133Z     info    Using istiod file format for signing ca files
2023-10-30T21:15:51.871157Z     info    cacerts secret found is IstioGenerated, use it as the CA certificate
2023-10-30T21:15:51.871164Z     info    Use self-signed certificate as the CA certificate
2023-10-30T21:15:51.876431Z     info    pkica   Load signing key and cert from existing secret istio-system/istio-ca-secret
2023-10-30T21:15:51.877553Z     info    pkica   Set secret name for self-signed CA cert rotator to istio-ca-secret
2023-10-30T21:15:51.877573Z     info    pkica   Using existing public key: -----BEGIN CERTIFICATE-----
MIIC/DCCAeSgAwIBAgIQcadTZgyD2rC0e9ICZ9xQ1zANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIzMTAzMDIxMDg1NFoXDTMzMTAy
NzIxMDg1NFowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAM6RKiEmt+O4fASYnJAon5XDkzIcKZNzEEzLFQoF
7w01rRWr0T63ni5TklhS9DqwyhteFP8/dwINHfxpMmhYFLpHO86oRiwm4YZ1ySfJ
vtnRpRMs4Gud/AU+dYlXPwaDkTXSkqtx5dwKjLfFK2uTJGiIpcALeLa2wLQFqOsv
OfSbb1VyocFdB/ln05RB66iuNsiNS8gZIpCcRX37f7UQ1mHQtlYKFx7JLl/qqJWP
m0H3nEDv2WpplprDoXeGM0MLOcUZxRjzfI8hyNwHiF1+wqjgDKFsVZW9ZI2uxnH3
oi37CUMhPAsuRvvS38kNgK5E6lxMjNtsL/f69zKx9TKksoMCAwEAAaNCMEAwDgYD
VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFE3/r8wGdtBX
IRWbaZkeu/pOuC9UMA0GCSqGSIb3DQEBCwUAA4IBAQC2xrP/UC+JnN2zRMLs6zNQ
9GJyGJUUw9/cnNu6I9B9MsA+4L2DTuYFsv18TrnsKwM/bItBLj92rlWrI77cEHBO
m/LnhUAqGaF7L+TcVOZbTLvdx9imC6lM3gRhWfPpA1BWpV9Axb1vnonv51lIsdCe
8q6EToaLGDFSyh5rhpHwEUoQ6WM1dMmjBExGpzWBUU2z3T/3s08iRo8A9Ll1EeOg
qYPOmvVZWvbRh27cPWOv7Pnz+ULuTsw1KQllOwE97qO/VlFWE4cLmnAWrJMwF9uA
a9yGeLWpJrKory9cgrbXRPC3h6++jFmIR2hYRACvbuVTX9/NlIXBWZmhDM+c5gGD
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIC/TCCAeWgAwIBAgIRAK7hI/xczYXaWxbdx0AjKlcwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMzEwMzAxOTUxNThaFw0zMzEw
MjcxOTUxNThaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDV8VXFecxFv4MmgVxnnMGalbpzUis5wKfTcl10
llmPzNH9RWXucLGsZNu0HPLaCCswc6wSlmd/q30pSU9w1TaclDUQlYLF0Gd7icRb
Dr6mpogr2Wh2M2bCDPlLVVRMdyvQ2njJA0+eyT9aWIrKbA2zDoLEozLXbTmgvwTJ
Y2c3En6AcKJpPKNB6cPdys2YpIzKbqOc2pNHSf9GBsIoIbyXDYvgUAdJ+RuJJtos
QER8aZdrRZmQC2VQeargfxFO/EvtLRv7bOJWVIDC3KUuLsvXj00ibA7cwEvK0wCr
XxQmW2T8dvDxFzVG8A0IgkwE+8ybwhTPJKdFEGwFC9FTf0vHAgMBAAGjQjBAMA4G
A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQsP1IGIpSu
OZcRsvJUfgjx3/5wlDANBgkqhkiG9w0BAQsFAAOCAQEAQsDdOcKJZnBCYAgJvhKv
JZtVeeX0RXqqxcUT2SxzNX78MPLfV7Exs5ii9upkMp04TzIQPeCAREbGpwMbUqY0
o1Gh1J3PAJUJ73mGgjhgaR2KKTpr2F/gHqSV2UZRreex9v4fChGuKLt3KumrlN7J
GA25UU1OhXMCSMca6M6ylb9NLVxtjUi+lNzOmv3iFMFsNEwWr7SkfqJSkTYznDrV
dBFYA5PkOWpb74eAj28C9D5qq3U7Oiss8s31ATXzMiW/LzEm1xwowHIRNByd/WlB
yhAP3VQNz/aqvcloRbrDXGKI1cFuPx/LBr7x6f0tgJaqwHvIbaCVBRaExmvI9/d+
/Q==
-----END CERTIFICATE-----
```

cacerts and istio-ca-secret are differing!

From logs, I see pilot-discovery wrote istio-ca-secret at 2023-10-30T21:08:54Z, but cacerts at 2023-10-30T19:51:58Z.

At 2023-10-30T21:08:54Z I patched Istiod to imagePullPolicy=Always, since I thought maybe it was an old cached `:latest` image causing issues. This was *after* the issues started!

The old instance at 19:51 started up logging just the following cert:

```
-----BEGIN CERTIFICATE-----
MIIC/TCCAeWgAwIBAgIRAK7hI/xczYXaWxbdx0AjKlcwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMzEwMzAxOTUxNThaFw0zMzEw
MjcxOTUxNThaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDV8VXFecxFv4MmgVxnnMGalbpzUis5wKfTcl10
llmPzNH9RWXucLGsZNu0HPLaCCswc6wSlmd/q30pSU9w1TaclDUQlYLF0Gd7icRb
Dr6mpogr2Wh2M2bCDPlLVVRMdyvQ2njJA0+eyT9aWIrKbA2zDoLEozLXbTmgvwTJ
Y2c3En6AcKJpPKNB6cPdys2YpIzKbqOc2pNHSf9GBsIoIbyXDYvgUAdJ+RuJJtos
QER8aZdrRZmQC2VQeargfxFO/EvtLRv7bOJWVIDC3KUuLsvXj00ibA7cwEvK0wCr
XxQmW2T8dvDxFzVG8A0IgkwE+8ybwhTPJKdFEGwFC9FTf0vHAgMBAAGjQjBAMA4G
A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQsP1IGIpSu
OZcRsvJUfgjx3/5wlDANBgkqhkiG9w0BAQsFAAOCAQEAQsDdOcKJZnBCYAgJvhKv
JZtVeeX0RXqqxcUT2SxzNX78MPLfV7Exs5ii9upkMp04TzIQPeCAREbGpwMbUqY0
o1Gh1J3PAJUJ73mGgjhgaR2KKTpr2F/gHqSV2UZRreex9v4fChGuKLt3KumrlN7J
GA25UU1OhXMCSMca6M6ylb9NLVxtjUi+lNzOmv3iFMFsNEwWr7SkfqJSkTYznDrV
dBFYA5PkOWpb74eAj28C9D5qq3U7Oiss8s31ATXzMiW/LzEm1xwowHIRNByd/WlB
yhAP3VQNz/aqvcloRbrDXGKI1cFuPx/LBr7x6f0tgJaqwHvIbaCVBRaExmvI9/d+
/Q==
-----END CERTIFICATE-----
```

and 'CASecret istio-ca-secret not found, will create one called cacerts'

---

Overall it seems like I ran old version, then new version. These generated two distinct self-signed certs and merged them together in a broken manner.

Note this is going from master -> master, so its plausible this is an invalid upgrade and not something a real user can hit

@jaellio
