### ISSUE TITLE
Header-based routing in VirtualService is not functioning correctly when using Istio in proxyless mode.

### ISSUE THREAD

**Issue by Song-yu** [istio/istio#47693]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When attempting to call `xds://grpc-example.defalut.svc.cluster.local:7777`, I encountered an error related to the `x-canary` header matcher in my VirtualService configuration. The error suggests that the header matcher exact: "true" is unrecognized.

Error Message:
 > UnaryEcho: _,  rpc error: code = Unavailable desc = name resolver error: received route is invalid: route match:{prefix:"/" case_sensitive:{value:true} headers:{name:"x-canary" string_match:{exact:"true"}}} route:{cluster:"outbound|7777|canary|grpc-example.default.svc.cluster.local" timeout:{} retry_policy:{retry_on:"connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes" num_retries:{value:2} retry_host_predicate:{name:"envoy.retry_host_predicates.previous_hosts" typed_config:{type_url:"type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"}} host_selection_retry_max_attempts:5 retriable_status_codes:503} max_stream_duration:{max_stream_duration:{}}} metadata:{filter_metadata:{key:"istio" value:{fields:{key:"config" value:{string_value:"/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/grpc-example-vsvc"}}}}} decorator:{operation:"grpc-example.default.svc.cluster.local:7777/*"} has an unrecognized header matcher: &{StringMatch:exact:"true"}
 
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grpc-example-vsvc
  namespace: default
spec:
  hosts:
    - grpc-example.default.svc.cluster.local
  http:
    - match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: grpc-example.default.svc.cluster.local
            subset: canary
    - match:
        - sourceLabels:
            role: canary
      route:
        - destination:
            subset: canary
            host: grpc-example.default.svc.cluster.local
    - name: primary
      route:
        - destination:
            host: grpc-example.default.svc.cluster.local
            subset: stable
          weight: 100
        - destination:
            host: grpc-example.default.svc.cluster.local
            subset: canary
          weight: 0
```

### Version

```Text
$ istioctl version
client version: 1.18.2
control plane version: 1.19.3
data plane version: 1.19.3 (28 proxies)
$ kubectl version --short
Client Version: v1.23.14
Server Version: v1.27.3-gke.100
```
