### ISSUE TITLE
Timeout for external service e.g. `ServiceEntry`

### ISSUE THREAD

**Issue by Hronom** [istio/istio#47713]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have next config [inspired by this](https://github.com/istio/istio/issues/16915#issuecomment-529210672):
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-yevhentienkaiev-app-reqres.in
  namespace: yevhentienkaiev-app
spec:
  hosts:
    - reqres.in
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: https
  resolution: DNS
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-yevhentienkaiev-app-reqres.in
  namespace: yevhentienkaiev-app
spec:
  hosts:
    - reqres.in
  http:
    - route:
        - destination:
            host: reqres.in
          weight: 100
      timeout: 10s
```

Doing this from the pod (30 means delay `30 sec`):
```
curl --location 'https://reqres.in/api/users?delay=30'
```
Expectation to get timeout after `10s`, but not getting it, what I'm doing wrong?

### Version

```Text
Istio `1.18.2`
```
