### ISSUE TITLE
MongoDB in Kubernetes Fails to Run as Root Use

### ISSUE THREAD

**Issue by qodirovshohijahon** [istio/istio#47719]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**I've encountered an issue when trying to deploy a MongoDB instance within a Kubernetes cluster where MongoDB fails to run as the root user, and I'm seeking assistance in resolving this.**

Environment Details:

Kubernetes Cluster Version: v1.25.6 (AKS)
MongoDB Image: docker.io/vbergbauer/examples-bookinfo-mongodb:1.16.4
Kubernetes Deployment Configuration: 

When attempting to deploy MongoDB within our Kubernetes cluster, the deployment is failing the main reason is permission I enabled istio_cni in istio control plane istio requires to deploy as root user but mongodb only (not other deployment) can not deploy as root user.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-v1
  namespace: bookinfo
  labels:
    app: mongodb-v1
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-v1
      version: v1
  template:
    metadata:
      labels:
        app: mongodb-v1
        version: v1
    spec:
      serviceAccountName: mongodb-database
      securityContext:
        seccompProfile:
          type: RuntimeDefault        
      containers:
      - name: mongodb-v1 
        image: docker.io/vbergbauer/examples-bookinfo-mongodb:1.16.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data-db
          mountPath: /data/db
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true 
      volumes:
      - name: data-db
        persistentVolumeClaim:
          claimName: bookinfo-mongodb
```
