### ISSUE TITLE
gateway-api: unable to create gateway - failed to assign to all requested addresses: address pending for hostname

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#47750]
Hi,

I am using istio with gateway-api.
I have one gateway that works great with HTTPRoute.
I am using aws and I need to create Network load balancer to forward traffic on port 25, so I am trying to create another gateway with NLB annotations.
But I am facing an error on the tcp-gateway creation: `Assigned to service(s) tcp-gateway-istio.istio-ingress.svc.cluster.local:25,
      but failed to assign to all requested addresses: address pending for hostname
      "tcp-gateway-istio.istio-ingress.svc.cluster.local"'`
Relevent yamls:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: istio
spec:
  controllerName: istio.io/gateway-controller
  description: The default Istio GatewayClass
status:
  conditions:
    - lastTransitionTime: '2023-10-17T11:56:38Z'
      message: Handled by Istio controller
      observedGeneration: 1
      reason: Accepted
      status: 'True'
      type: Accepted
```

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: xxxx
    service.beta.kubernetes.io/aws-load-balancer-subnets: xxx
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: xxxx
    service.beta.kubernetes.io/aws-load-balancer-type: xxxx
    service.beta.kubernetes.io/load-balancer-source-ranges: xxx
  name: tcp-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp
    port: 25
    protocol: TCP
status:
  conditions:
  - lastTransitionTime: "2023-11-06T12:13:47Z"
    message: Resource accepted
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2023-11-06T12:13:47Z"
    message: 'Assigned to service(s) tcp-gateway-istio.istio-ingress.svc.cluster.local:2525,
      but failed to assign to all requested addresses: address pending for hostname
      "tcp-gateway-istio.istio-ingress.svc.cluster.local"'
    observedGeneration: 1
    reason: Invalid
    status: "False"
    type: Programmed
  listeners:
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2023-11-06T12:13:47Z"
      message: No errors found
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2023-11-06T12:13:47Z"
      message: No errors found
      observedGeneration: 1
      reason: NoConflicts
      status: "False"
      type: Conflicted
    - lastTransitionTime: "2023-11-06T12:13:47Z"
      message: No errors found
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2023-11-06T12:13:47Z"
      message: No errors found
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    name: tcp
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: TCPRoute
```

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcpserver
  namespace: example
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: tcp-gateway
      namespace: istio-ingress
      sectionName: tcp
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: tcp-service
          port: 25
          weight: 1
```

I followed istio guide here: https://raw.githubusercontent.com/istio/istio/release-1.19/samples/tcp-echo/gateway-api/tcp-echo-all-v1.yaml
 I can't understand why the gateway is set to PROGRAMED=False and throwing: Assigned to service(s) tcp-gateway-istio.istio-ingress.svc.cluster.local:2525,
      but failed to assign to all requested addresses: address pending for hostname
      "tcp-gateway-istio.istio-ingress.svc.cluster.local"'
      
I checked and the `tcp-gateway-istio.istio-ingress.svc.cluster.local` does exist.
The NLB is successfully created on aws as well.

Any ideas?

**Comment by Rez0k** [comment]
.

**Comment by Rez0k** [comment]
?

**Comment by jbmolle** [comment]
Hi,
I have the same problem.
When I create the gateway "gateway-prod" and apply it with kubectl, I get a deployment gateway-prod-istio but I don't get any service created.
I'm working inside istio-ingress namespace, I have installed Istio with minimal profile and I'm using Cilium as CNI.
Thanks for your help!
JB

**Comment by jbmolle** [comment]
Ok I solved my problem.
I added a listener with name example.com
According to here https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.SectionName this is a valid name. But it doesn't work in Istio and the service isn't created. When I changed the name to example-com everything works.

**Comment by keithmattix** [comment]
@Rez0k does the Service corresponding to the gateway have an External IP address assigned?

**Comment by keithmattix** [comment]
@jbmolle can you post the relevant YAML files so we can see what's being deployed? Redact any sensitive information of course

**Comment by Rez0k** [comment]
> @Rez0k does the Service corresponding to the gateway have an External IP address assigned?

After upgrade to istio version 1.20.0 the programmed value is now set to True
Then I encounter another problem and this fixed it:
```
istiod:
  pilot:
    env:
      PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
```

Now everyhing works as expected
