### ISSUE TITLE
[Gateway API] HTTPRoute PathPrefix matcher not generating routes for paths other than "/"

### ISSUE THREAD

**Issue by olafurflygenring** [istio/istio#47761]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm seeing weird behaviour while converting istio ingress configuration declared via the istio Gateway/Virtualservices toGateway API.

Everything seems to translate nicely to the new Gateway/HTTPRoute resources, except I'm  having trouble with PathPrefix matchers in HTTPRoutes.

The problem is that routes are not generated correctly/don't work if I match against other things than "/"

Take this HTTPRoute for example (some information is `<redacted>` because it's irrelevant and/or sensitive)

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: <redacted>-ingress
spec:
  hostnames:
  {{- range .Values.global.fqdnsInternal }}
  - {{ . }}
  {{- end }}
  parentRefs:
    - name: <redacted>-gateway-internal
      namespace: istio-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /com.<redacted>.<redacted>
      backendRefs:
        - name: <redacted>-service
          namespace: {{ .Release.Namespace }}
          port: <redacted>
```

Listing the routes of gateway-internal pod via `istioctl proxy-config route` gives us these routes:

```
NAME        VHOST NAME                DOMAINS                MATCH        VIRTUAL SERVICE
http.80     <fqdnsInternal[0]>:80    <fqdnsInternal[0]>                   <redacted>-0-istio-autogenerated-k8s-gateway.<redacted>
http.80     <fqdnsInternal[1]>:80    <fqdnsInternal[1]>                   <redacted>-4-istio-autogenerated-k8s-gateway.<redacted>
```

And trying to access the service via ingress results in this access being record on the ingress pod:

```
"POST /com.<redacted>.<redacted>/<service> HTTP/2" 200 NR route_not_found - "-" 0 0 0 - "<redacted>" "grpcurl/v1.8.7 grpc-go/1.48.0" "2cbff782-7251-4914-b6a5-0fcfbfc2ea12" "fqdnsInternal[1]" "-" - - <redacted> - -
```

Changing the value of the PathPrefix matcher to a "/" like so:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: <redacted>-ingress
spec:
  hostnames:
  {{- range .Values.global.fqdnsInternal }}
  - {{ . }}
  {{- end }}
  parentRefs:
    - name: <redacted>-gateway-internal
      namespace: istio-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: <redacted>-service
          namespace: {{ .Release.Namespace }}
          port: <redacted>
```

gives me this `istioctl proxy-config route`:

```
NAME        VHOST NAME                DOMAINS                        MATCH        VIRTUAL SERVICE
http.80     <fqdnsInternal[0]>:80     <fqdnsInternal[0]>             /*           <redacted>-0-istio-autogenerated-k8s-gateway.<redacted>
http.80     <fqdnsInternal[1]>:80     <fqdnsInternal[1]>             /*           <redacted>-4-istio-autogenerated-k8s-gateway.<redacted>
```

Accessing the service now (and making sure that no other HTTPRoute is active on the Ingress gateway) gives this access log line:

```
"POST /com.<redacted>.<redacted>/<service> HTTP/2" 200 - via_upstream - "-" 5 383 41 40 "<redacted>" "grpcurl/v1.8.7 grpc-go/1.48.0" "8e3a7e8e-0ac8-4ad8-8625-10861f1b7fe1" "fqdnsInternal[1]" "<redacted>" outbound|<redacted>||<redacted>.svc.cluster.local <redacted> <redacted> <redacted> - <redacted>-ingress.0
```

I'm not quite sure what's going on here, and at a glance it looks like there's a bug when converting the HTTPRoute PathPrefix  to VirtualService definitions:

### Version

```Text
client version: 1.19.0
control plane version: 1.19.3
data plane version: 1.19.3 (77 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7-eks-4f4795d

Helm: v3.12.3+g3a31588
```
