### ISSUE TITLE
Allow setting the name of the `tls_certificate_sds_secret_configs` in DestinationRule

### ISSUE THREAD

**Issue by grameshtwilio** [istio/istio#47781]
**Describe the feature request**
When using Spire as the secret provider, workloads can receive multiple identities from Spire. I'd like to configure the correct certificates for the different upstreams that I'd wish to connect to. This should be used when the mTLS mode is `ISTIO_MUTUAL`. 

Setting something like 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: non-default-upstream
spec:
  host: upstream.dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      certificateSdsSecretConfigName: "spiffe://example.org/custom/identity"
```
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by DingGGu** [comment]
Do you want to try like this implementations? https://github.com/istio/istio/issues/41666

I too am experiencing a similar problem. When two clusters with Spire Federation installed had different CAs, an attempt was made to implement mTLS communication using the Ingress Gateway and Destination Rule, but it failed.

```
# Run in sidecar injected-pod
curl http://b.example.org
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED%
```


```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: b
spec:
  hosts:
  - b.example.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: b
spec:
  host: b.example.org
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
