### ISSUE TITLE
Istio Virtual Service is unable to append value to already available request header with HeaderOptions

### ISSUE THREAD

**Issue by malisettikalyan** [istio/istio#47785]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team, I am using request header add options provided by Istio Virtual service.
https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations

- Ideally, when a request is received by istio Virtual Service, It should be able append some additional headers based on the configuration detail.

But, I am facing an issue where, 
- If the headers with key "baggage" is already present, then istio is unable to append the value to the already existing headers.

- If the headers with key "baggage" is not present, then istio is able to add the value to already existing headers.

Eg : Before receiving the request, If in headers, **baggage = flow_name=canarytest.canary-app1--other,req_zone_name=test-zone.**

When istio virtual service receives the request, it should append "x-canary=true" in already present baggage header. Now, it should be something like below
 **baggage** =flow_name=canarytest.canary-app1--other,req_zone_name=test-zone, **x-canary=true**
 
 But, Istio virtual service is unable to modify. 
 
 - Not only baggage headers, I am facing this issue for other headers(with different name) as well.
 
 In the official documentation, it was mentioned that, 
 

add | map<string, string> | Append the given values to the headers specified by keys (will create a comma-separated list of values)
-- | -- | --

 header options "add" supports this. **But, it is not working.**
 
 **Note :** I am not facing issue with traffic routing, I am only facing issue with request headers add feature.

**Need this help on urgent basis.**

Please refer to below sample virtual service.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: canary-app2
  namespace: canarytest
spec:
  exportTo:
  - .
  hosts:
  - canary-app2
  http:
  - match:
    - headers:
        baggage:
          regex: .*x-canary=true.*
    route:
    - destination:
        host: canary-app2
        subset: canary
  - name: primary
    route:
    - destination:
        host: canary-app2
        subset: stable
      weight: 100
    - destination:
        host: canary-app2
        subset: canary
      headers:
        request:
          add:
            baggage: x-canary=true
```

### Version

```Text
control plane - 1.18.2-distroless
istio-operator - 1.18.2-distroless
```

### Additional Information

Istio virtual service header options is unable to append value to a already existing key in headers.

https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations

**Comment by malisettikalyan** [comment]
> ### Is this the right place to submit this?
> * [x]  This is not a security vulnerability or a crashing bug
> * [x]  This is not a question about how to use Istio
> 
> ### Bug Description
> Hi Team, I am using request header add options provided by Istio Virtual service. https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations
> 
> * Ideally, when a request is received by istio Virtual Service, It should be able append some additional headers based on the configuration detail.
> 
> But, I am facing an issue where,
> 
> * If the headers with key "baggage" is already present, then istio is unable to append the value to the already existing headers.
> * If the headers with key "baggage" is not present, then istio is able to add the value to already existing headers.
> 
> Eg : Before receiving the request, If in headers, **baggage = flow_name=canarytest.canary-app1--other,req_zone_name=test-zone.**
> 
> When istio virtual service receives the request, it should append "x-canary=true" in already present baggage header. Now, it should be something like below **baggage** =flow_name=canarytest.canary-app1--other,req_zone_name=test-zone, **x-canary=true**
> 
> But, Istio virtual service is unable to modify.
> 
> * Not only baggage headers, I am facing this issue for other headers(with different name) as well.
> 
> In the official documentation, it was mentioned that,
> 
> add	map<string, string>	Append the given values to the headers specified by keys (will create a comma-separated list of values)
> header options "add" supports this. **But, it is not working.**
> 
> **Note :** I am not facing issue with traffic routing, I am only facing issue with request headers add feature.
> 
> **Need this help on urgent basis.**
> 
> Please refer to below sample virtual service.
> 
> `apiVersion: networking.istio.io/v1beta1 kind: VirtualService name: canary-app2 namespace: canarytest spec: exportTo:
> 
> * .
>   hosts:
> * canary-app2
>   http:
> * match:
>   
>   * headers:
>     baggage:
>     regex: ._x-canary=true._
>     route:
>   * destination:
>     host: canary-app2
>     subset: canary
> * name: primary
>   route:
>   
>   * destination:
>     host: canary-app2
>     subset: stable
>     weight: 100
>   * destination:
>     host: canary-app2
>     subset: canary
>     headers:
>     request:
>     add:
>     baggage: x-canary=true
>     `
> 
> ### Version
> ```
> control plane - 1.18.2-distroless
> istio-operator - 1.18.2-distroless
> ```
> 
> ### Additional Information
> Istio virtual service header options is unable to append value to a already existing key in headers.
> 
> https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations

@hanxiaop @istio-policy-bot @istio-testing @whitneygriffith @howardjohn Can you please help her

**Comment by zirain** [comment]
maybe you can try with WasmPlugin?

**Comment by hanxiaop** [comment]
Not sure if I understand it correctly, but I think if you have a request with a header like `baggage: somevalue`, you will get `baggate: somevalue,x-canary=true` in this situation.

**Comment by malisettikalyan** [comment]
Yeah @hanxiaop That's my requirement. But, Istio Virtual is unable to append values to already existing header. Need help in here

**Comment by hanxiaop** [comment]
@malisettikalyan I just tried, and this VS worked for me:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  hosts:
  - httpbin
  http:
  - headers:
      request:
        add:
          testheader: x-test=true
    route:
    - destination:
        host: httpbin
        subset: v1
```
when I did:
```
 k exec deploy/sleep -- curl httpbin:8000/headers -H "testheader: appendthis"
...
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin:8000", 
    "Testheader": "appendthis,x-test=true", 
...
```
Can you double check if your vs is correct?

**Comment by malisettikalyan** [comment]
My Virtual service is working fine with traffic routing and other scenarios. Can you please refer my below VS and try a test run ? Meanwhile, will check from my end as well.

I am using the Headers request add inside the route.  I have referred istio documentation(https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers)

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: canary-app2
  namespace: canarytest
spec:
  exportTo:
  - .
  hosts:
  - canary-app2
  http:
  - match:
    - headers:
        baggage:
          regex: .*x-canary=true.*
    route:
    - destination:
        host: canary-app2
        subset: canary
  - name: primary
    route:
    - destination:
        host: canary-app2
        subset: stable
      weight: 100
    - destination:
        host: canary-app2
        subset: canary
      headers:
        request:
          add:
            baggage: x-canary=true
```

**Comment by hanxiaop** [comment]
> @hanxiaop My Virtual service is working fine with traffic routing and other scenarios. Can you please refer my below VS and try a test run ? Meanwhile, will check from my end as well.
> 
> I am using the **Headers request add inside the route configuration**. I have referred istio documentation(https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers)
> 
> ```
> apiVersion: networking.istio.io/v1beta1
> kind: VirtualService
>   name: canary-app2
>   namespace: canarytest
> spec:
>   exportTo:
>   - .
>   hosts:
>   - canary-app2
>   http:
>   - match:
>     - headers:
>         baggage:
>           regex: .*x-canary=true.*
>     route:
>     - destination:
>         host: canary-app2
>         subset: canary
>   - name: primary
>     route:
>     - destination:
>         host: canary-app2
>         subset: stable
>       weight: 100
>     - destination:
>         host: canary-app2
>         subset: canary
>       headers:
>         request:
>           add:
>             baggage: x-canary=true
> ```

So since `stable` receives 100% traffic, the header modification for `canary` should not take effect?

**Comment by malisettikalyan** [comment]
No @hanxiaop I have tried with argo rollouts where the weight gets updated dynamically. You can move the 

headers:
        request:
          add:
            baggage: x-canary=true
            
to stable subset for your testing.

Like below

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: canary-app2
  namespace: canarytest
spec:
  exportTo:
  - .
  hosts:
  - canary-app2
  http:
  - match:
    - headers:
        baggage:
          regex: .*x-canary=true.*
    route:
    - destination:
        host: canary-app2
        subset: canary
  - name: primary
    route:
    - destination:
        host: canary-app2
        subset: stable
      weight: 100
      headers:
        request:
          add:
            baggage: x-canary=true
    - destination:
        host: canary-app2
        subset: canary
```

Note : I have tried the config referred by you 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: canary-app2
  namespace: canarytest
spec:
  exportTo:
  - .
  hosts:
  - canary-app2
  http:
  - headers:
      request:
        add:
          testheader: x-test=true
    route:
    - destination:
        host: canary-app2
        subset: stable
```

I tried below curl

curl --location 'http://canary-app2:8080/status' \
--header 'testheader: name=pavan'

It only resulted testheader: name=pavan 

![image](https://github.com/istio/istio/assets/131119956/9343500d-7fb1-432d-98da-a742636d539b)


When I tried below curl

curl --location 'http://canary-app2:8080/status' 

It resulted testheader: x-test=true

![image](https://github.com/istio/istio/assets/131119956/0775b2aa-3ada-40fd-8309-b3b664697fe0)

**Comment by malisettikalyan** [comment]
@hanxiaop Thanks for your response. I was able to check on this issue.

Now, the response i have received is 

baggage: somevalue
baggage: x-canary=true

I am receiving duplicate headers in my application. Is it expected ? Any way we can solve it ? By appending the headers ?

I am expecting a result like below
baggate: somevalue,x-canary=true

**Comment by hanxiaop** [comment]
> baggage: somevalue
> baggage: x-canary=true

I don't think this is expected. Maybe @howardjohn can help; however I think some of the folks are at KubeCon and will be back after that.

**Comment by howardjohn** [comment]
In HTTP it's valid to have both forms. And actually IIRC it's valid for `baggage` specifically as well. But would want to double check, I think proxies are supposed to do a certain way and I forget which it is.

**Comment by malisettikalyan** [comment]
@hanxiaop @howardjohn For my requirement, I am expecting below value

baggage: somevalue,x-canary=true

if my service receives multiple headers of same key, it is only letting one of them pass through during context propagation

can you please help in achieving my requirement

**Comment by hzxuzhonghu** [comment]
@malisettikalyan I am not sure how did it even work (add the x-canary=true) with

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: canary-app2
  namespace: canarytest
spec:
  exportTo:
  - .
  hosts:
  - canary-app2
  http:
  - match:
    - headers:
        baggage:
          regex: .*x-canary=true.*
    route:
    - destination:
        host: canary-app2
        subset: canary
  - name: primary
    route:
    - destination:
        host: canary-app2
        subset: stable
      weight: 100
    - destination:
        host: canary-app2
        subset: canary
      headers:
        request:
          add:
            baggage: x-canary=true
```

As @hanxiaop said, not request will go to this subset.


I tested manually with a route headers

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
   name: canary-app2
spec:
  hosts:
  - httpbin
  http:
  - name: primary
    route:
    - destination:
        host: httpbin
      headers:
        request:
          add:
            baggage: x-canary=true
```

The result is completely as expected:

```
 curl -H "Baggage: name=xuzhonghu" http://httpbin:8000/headers
{
  "headers": {
    "Accept": "*/*", 
    "Baggage": "name=xuzhonghu,x-canary=true", 
    "Host": "httpbin:8000", 
    "User-Agent": "curl/8.4.0", 
    "X-B3-Parentspanid": "b843ef2ad659fbf0", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "57ea9d417b6ee3cd", 
    "X-B3-Traceid": "529a8a36a6c0702bb843ef2ad659fbf0", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/default/sa/httpbin;Hash=625b6fd32a33ef457dc5fa824d28d8c960159f04b3b8f0c9511f4d4e649527d4;Subject=\"\";URI=spiffe://cluster.local/ns/default/sa/sleep"
  }
}

```
