### ISSUE TITLE
Unable to set upstream header `Authorization` in CUSTOM `AuthorizationPolicy`

### ISSUE THREAD

**Issue by harveyjing** [istio/istio#47797]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I setup Istio, Oauth2-proxy to secure my app. After I hit the protected endpoint, the auth flow works good and session cookie is set as normal. But in my backend service(httpbin), there is no `Authorization` header. I print log in Istio cidecar and found `Authorization` **RESPONSE** header in Oauth2-proxy cidecar but **NOT** in **REQUEST** headers in backend service `httpbin`. 
```
accessLogFormat: "[%START_TIME%] %REQ(:METHOD)%
        %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL% %RESPONSE_CODE%
        %REQ(AUTHORIZATION)% %REQ(x-auth-request-email)% %RESP(AUTHORIZATION)% %RESP(x-auth-request-email)%"
kubectl logs -l app=istio-ingressgateway -c istio-proxy -n istio-system
[2023-11-07T14:14:38.297Z] GET /get HTTP/1.1 200 - xxx@gmail.com - -
kubectl logs -l app=oauth2-proxy -c istio-proxy -n oauth2-proxy
[2023-11-07T14:14:38.298Z] GET /get HTTP/1.1 200 - - Bearer veryloooogtoken xxx@gmail.com
kubectl logs -l app=httpbin -c istio-proxy -n sololude
[2023-11-07T14:14:38.304Z] GET /get HTTP/1.1 200 - xxx@gmail.com - -
```
This is my mesh config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogFormat: "[%START_TIME%] %REQ(:METHOD)%
        %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL% %RESPONSE_CODE%
        %REQ(AUTHORIZATION)% %REQ(x-auth-request-email)% %RESP(AUTHORIZATION)% %RESP(x-auth-request-email)%"
    extensionProviders:
      - name: oauth2-proxy
        envoyExtAuthzHttp:
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
          port: 4180
          # headers sent to the oauth2-proxy in the check request.
          includeRequestHeadersInCheck:
            - authorization
            - cookie
          # headers sent to backend application when request is allowed.
          headersToUpstreamOnAllow:
            - authorization
            - path
            - x-auth-request-user
            - x-auth-request-email
            - x-auth-request-access-token
          # headers sent back to the client when request is denied.
          headersToDownstreamOnDeny:
            - content-type
            - set-cookie
          # headers sent back to the client when request is allowed.
          headersToDownstreamOnAllow:
            - content-type
            - set-cookie
          includeAdditionalHeadersInCheck:
            "X-Auth-Request-Redirect": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
```
Auth policy:
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: https://account.sololude.com
      jwksUri: https://account.sololude.com/oauth2/jwks
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - demo.test
            paths:
              - /api/user
              - /get
              - /headers
```
Oauth2-proxy config:
```
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
stringData:
  OAUTH2_PROXY_CLIENT_ID: client_id
  OAUTH2_PROXY_CLIENT_SECRET: client_secret
  # OAUTH2_PROXY_REDIRECT_URL: http://demo.test:3000/api/auth/callback
  OAUTH2_PROXY_REDIRECT_URL: http://demo.test/oauth2/callback
  # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#generating-a-cookie-secret
  OAUTH2_PROXY_COOKIE_SECRET: YJCuPn0MyZFTAHvUnwYMhSSsgupY2BhEwvAW5_aBayA=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          args:
            - --http-address=0.0.0.0:4180
            - --provider=oidc
            - --oidc-issuer-url=https://account.sololude.com
            - --email-domain=*
            - --cookie-refresh=1h
            - --cookie-secure=false
            - --set-xauthrequest
            - --pass-access-token
            - --set-authorization-header
            - --upstream=static://200
            - --reverse-proxy
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_CLIENT_SECRET
            - name: OAUTH2_PROXY_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_REDIRECT_URL
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_COOKIE_SECRET
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1000Mi
          ports:
            - containerPort: 4180
              protocol: TCP
          readinessProbe:
            periodSeconds: 3
            httpGet:
              path: /ping
              port: 4180
```
Ingress gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sololude-gw-http
  namespace: sololude
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
  namespace: sololude
spec:
  hosts:
    - "*"
  gateways:
    - sololude-gw-http
  http:
    - name: "oauth2-proxy-route"
      match:
        - uri:
            prefix: "/oauth2"
      route:
        - destination:
            host: oauth2-proxy.oauth2-proxy.svc.cluster.local
            port:
              number: 4180
    - name: "default-route"
      route:
        - destination:
            host: httpbin
            port:
              number: 8000
```

### Istio Version
```
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.3 (3 proxies)
```

### Version

```Text
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.3 (3 proxies)
```
```


### Additional Information

_No response_

**Comment by harveyjing** [comment]
And the authenticated protected endpoint `/get` response using `httpbin` backend service:
<img width="1143" alt="image" src="https://github.com/istio/istio/assets/68357448/7547f970-70af-41d2-9bbb-bd3b16d11d21">

**Comment by harveyjing** [comment]
After days Envoy source code research, I dump my ingress Envory filter chains config. Can anyone can help me examine this?
```
- accessLog:
  - filter:
      responseFlagFilter:
        flags:
        - NR
    name: envoy.access_loggers.file
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      logFormat:
        textFormatSource:
          inlineString: |
            [%START_TIME%] %REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL% %RESPONSE_CODE% %REQ(AUTHORIZATION)% %REQ(x-auth-request-email)% %RESP(AUTHORIZATION)% %RESP(x-auth-request-email)%
      path: /dev/stdout
  address:
    socketAddress:
      address: 0.0.0.0
      portValue: 8080
  continueOnListenerFiltersTimeout: true
  filterChains:
  - filters:
    - name: istio_authn
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/io.istio.network.authn.Config
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] %REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL% %RESPONSE_CODE% %REQ(AUTHORIZATION)% %REQ(x-auth-request-email)% %RESP(AUTHORIZATION)% %RESP(x-auth-request-email)%
            path: /dev/stdout
        forwardClientCertDetails: SANITIZE_SET
        httpFilters:
        - name: istio.metadata_exchange
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/io.istio.http.peer_metadata.Config
            value:
              upstream_discovery:
              - istio_headers: {}
              - workload_discovery: {}
              upstream_propagation:
              - istio_headers: {}
        - name: envoy.filters.http.rbac
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
            shadowRules:
              action: DENY
              policies:
                istio-ext-authz-ns[istio-system]-policy[istio-ingressgateway]-rule[0]:
                  permissions:
                  - andRules:
                      rules:
                      - orRules:
                          rules:
                          - header:
                              name: :authority
                              stringMatch:
                                exact: demo.test
                                ignoreCase: true
                      - orRules:
                          rules:
                          - urlPath:
                              path:
                                exact: /api/user
                          - urlPath:
                              path:
                                exact: /get
                          - urlPath:
                              path:
                                exact: /headers
                  principals:
                  - andIds:
                      ids:
                      - any: true
            shadowRulesStatPrefix: istio_ext_authz_
        - name: envoy.filters.http.ext_authz
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            allowedHeaders:
              patterns:
              - exact: authorization
                ignoreCase: true
              - exact: cookie
                ignoreCase: true
            filterEnabledMetadata:
              filter: envoy.filters.http.rbac
              path:
              - key: istio_ext_authz_shadow_effective_policy_id
              value:
                stringMatch:
                  prefix: istio-ext-authz
            httpService:
              authorizationResponse:
                allowedClientHeaders:
                  patterns:
                  - exact: content-type
                    ignoreCase: true
                  - exact: set-cookie
                    ignoreCase: true
                allowedClientHeadersOnSuccess:
                  patterns:
                  - exact: content-type
                    ignoreCase: true
                  - exact: set-cookie
                    ignoreCase: true
                allowedUpstreamHeaders:
                  patterns:
                  - exact: authorization
                    ignoreCase: true
                  - exact: path
                    ignoreCase: true
                  - ignoreCase: true
                    prefix: x-auth-request
              serverUri:
                cluster: outbound|4180||oauth2-proxy.oauth2-proxy.svc.cluster.local
                timeout: 600s
                uri: http://oauth2-proxy.oauth2-proxy.svc.cluster.local
            transportApiVersion: V3
        - name: envoy.filters.http.jwt_authn
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
            bypassCorsPreflight: true
            providers:
              origins-0:
                issuer: https://account.sololude.com
                localJwks:
                  inlineString: '{"keys":[{"kty":"RSA","e":"AQAB","kid":"b39070b9-14e7-4619-9acf-43c672854077","n":"wCcfvXe09biXr7rGaMt48bCfJTu_RMcdRlCePKAX902u6dyVqfU92Xefy60vEOY4Z6IZE2C_8KFa-mn8HpHcyCXD2gubdBbG0iEq9bgtUh9uXTWc1EzKbmyxDMagt40VL2C4uAfWrhBYOVVLrV4xw2JeQRuHY5ruoclGF8ZEW9qyzjQ64urHcpZOgRDlWI2SGj1H3seLCQX6dm_GIGGPbjFXQZxlBOQsMvYUBHOUUXHTguw8R7nA63vXWLN25S196jt9gt3iKSI8CXiVlgyz-NVgux8AUrrINo5KUxsMunFCRBBa45XS04BR5mjMc3Y5qbOXFq5-ChlGZU_dGWzOOQ"}]}'
                payloadInMetadata: https://account.sololude.com
            rules:
            - match:
                prefix: /
              requires:
                requiresAny:
                  requirements:
                  - providerName: origins-0
                  - allowMissing: {}
        - name: istio_authn
          typedConfig:
            '@type': type.googleapis.com/istio.envoy.config.filter.http.authn.v2alpha1.FilterConfig
            policy:
              originIsOptional: true
              origins:
              - jwt:
                  issuer: https://account.sololude.com
              principalBinding: USE_ORIGIN
            skipValidateTrustDomain: true
        - name: envoy.filters.http.grpc_stats
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
            emitFilterState: true
            statsForAllMethods: false
        - name: istio.alpn
          typedConfig:
            '@type': type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig
            alpnOverride:
            - alpnOverride:
              - istio-http/1.0
              - istio
              - http/1.0
            - alpnOverride:
              - istio-http/1.1
              - istio
              - http/1.1
              upstreamProtocol: HTTP11
            - alpnOverride:
              - istio-h2
              - istio
              - h2
              upstreamProtocol: HTTP2
        - name: envoy.filters.http.fault
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
        - name: envoy.filters.http.cors
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
        - name: istio.stats
          typedConfig:
            '@type': type.googleapis.com/stats.PluginConfig
            disableHostHeaderFallback: true
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        httpProtocolOptions: {}
        normalizePath: true
        pathWithEscapedSlashesAction: KEEP_UNCHANGED
        rds:
          configSource:
            ads: {}
            initialFetchTimeout: 0s
            resourceApiVersion: V3
          routeConfigName: http.8080
        requestIdExtension:
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
            useRequestIdForTraceSampling: true
        serverName: istio-envoy
        setCurrentClientCertDetails:
          cert: true
          dns: true
          subject: true
          uri: true
        statPrefix: outbound_0.0.0.0_8080
        streamIdleTimeout: 0s
        tracing:
          clientSampling:
            value: 100
          customTags:
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_effective_policy_id
            tag: istio.authorization.dry_run.allow_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_engine_result
            tag: istio.authorization.dry_run.allow_policy.result
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_effective_policy_id
            tag: istio.authorization.dry_run.deny_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_engine_result
            tag: istio.authorization.dry_run.deny_policy.result
          - literal:
              value: latest
            tag: istio.canonical_revision
          - literal:
              value: istio-ingressgateway
            tag: istio.canonical_service
          - literal:
              value: cluster.local
            tag: istio.mesh_id
          - literal:
              value: istio-system
            tag: istio.namespace
          overallSampling:
            value: 100
          randomSampling:
            value: 1
        upgradeConfigs:
        - upgradeType: websocket
        useRemoteAddress: true
  name: 0.0.0.0_8080
  trafficDirection: OUTBOUND
```
