### ISSUE TITLE
virtual services and service entry for wildcard service

### ISSUE THREAD

**Issue by rahul6941** [istio/istio#47820]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are trying setup egress gateway for api domain . We setup below configuration but traffic is not routing from pod to istio egress 
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentry-for-onpremises-internal-api
spec:
  hosts:
  - "*.internal-domain.com"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destinationrule-egress-for-onpremises-internal-api
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:internal
  - name: internal
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: api.internal-domain.com
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-onpremises-internal-api
spec:
  host: "*.internal-domain.com"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
----
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-direct-onpremises-internal-api
spec:
  hosts:
  - "*.internal-domain.com"
  gateways:
  - gateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
	  sni_hosts:
            - "*.internal-domain.com"
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: internal
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - gateway
      port: 80
	  sni_hosts:
            - api.internal-domain.com
    route:
    - destination:
        host: api.internal-domain.com
        port:
          number: 443
      weight: 100
---
```

### Version

```Text
istioctl version : 1.19.3
kubectl version --short :v1.25.7-eks-a59e1f0
```
