### ISSUE TITLE
No registered implementation for gRPC field extraction filter

### ISSUE THREAD

**Issue by schurmann** [istio/istio#47836]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm interested in using the new gRPC field extraction filter in envoy and to my understanding it should be available in envoy 1.27 which Istio 1.19 is using. When applying the filter to a sidecar I see an error. I even tried to use Istio 1.20.0-rc.0 to see if that would help. When using an image from envoy I can configure it successfully.

```text
warning    envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound
: Didn't find a registered implementation for 'grpc_field_extraction' with type URL: 'envoy.extensions.filters.http.grpc_field_extraction.v3.GrpcFieldExtractionConfig'
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "grpc-sample.name" . }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_field_extraction
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_field_extraction.v3.GrpcFieldExtractionConfig
            descriptor_set:
              filename: /lib/greeter.pb
            extractions_by_method:
              com.acme.Greeter.SayHello:
                request_field_extractions:
                  name:
```

### Version

```Text
$ istioctl version
client version: 1.19.3
control plane version: 1.20.0-rc.0
data plane version: 1.20.0-rc.0 (3 proxies)
$ kubectl version --short
Client Version: v1.24.16
Kustomize Version: v4.5.4
Server Version: v1.24.16+k3s1
$ helm version --short
v3.13.2+g2a2fb3b
```
