### ISSUE TITLE
Virtual Service with a dynamic host using regex capture

### ISSUE THREAD

**Issue by allen-bmf** [istio/istio#47846]
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtual-service
spec:
  hosts:
    - my-service.example.com
  http:
    - match:
        - uri:
            regex: "^/api/([a-z]+)/.*"
      rewrite:
        uri: /
      route:
        - destination:
            host: my-service-$1
            port:
              number: 80
```
Is dynamic routing using regex possible? If not, are there any plans?
