### ISSUE TITLE
VirtualService uriRegexRewrite not working

### ISSUE THREAD

**Issue by moanass** [istio/istio#47871]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtual-service
spec:
  hosts:
    - my-service.example.com
  http:
    - match:
        - uri:
            regex: "^/([a-zA-Z0-9_-]+)/aaa/bbb(/.*)$"
      rewrite:
        uriRegexRewrite:
          match: "^/([a-zA-Z0-9_-]+)/aaa/bbb(/.*)$"
          rewrite: \2
      route:
        - destination:
            host: my-service
            port:
              number: 80
```

Failed to save resource: admission webhook "validation.istio.io" denied the request: configuration is invalid: rewrite must specify at least one of URI, UriRegexRewrite, or authority. Only one of URI or UriRegexRewrite may be specified

An error occurs even though only one of URI, UriRegexRewrite, or authority is set.
I'm trying to load the second capture group with rewrite

### Version

```Text
1.19.4
```
