### ISSUE TITLE
Gateway Api: Route HTTPS Redirect

### ISSUE THREAD

**Issue by jbmolle** [istio/istio#47881]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,
I've installed Istio 1.20.0 with minimal profile and I've deployed a Gateway API gateway.
I've deployed the httpbin sample deployment.
I've created a HTTPRoute like the following:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-http-route
  namespace: test
spec:
  parentRefs:
  - name: gateway-prod
    namespace: istio-ingress
  hostnames:
  - test.com
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
  - backendRefs:
    - name: httpbin
      namespace: test
      port: 8000
```
The problem is that the RequestRedirect filter takes precedence over the backendRef both in HTTP and HTTPS.
So if I run `curl -HHost:test.com http://gateway_ip/get` I get a 301 Redirect to https://test.com/get and if I run `curl -HHost:test.com https://gateway_ip/get` I also get a 301 Redirect so I can't reach httpbin backend.
If I remove the filters part in both HTTP and HTTPS, I can reach the httpbin backend.

The filter should be ignored in HTTPS. Is there a way to apply the redirect filter only when scheme is http?

### Version

```Text
client version: 1.20.0
istiod version: 1.20.0
data plane version: 1.20.0 (2 proxies)

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

**Comment by keithmattix** [comment]
To achieve your goal, you need 2 different listeners on your ` Gateway` and 2 different HTTPRoutes.
1. Define 2 listeners on your `Gateway`: one for http (usually to port 80) and one for https (usually port 443)
2. Remove the second rule in your `HTTPRoute`. Add a `sectionName` to the parentRef of the remaining route; it should look like this when you're done:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-test-http-route
  namespace: test
spec:
  parentRefs:
  - name: gateway-prod
    namespace: istio-ingress
    sectionName: http
  hostnames:
  - test.com
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
```

This will ensure only http requests get redirected

3. Create another `HTTPRoute` whose `parentRef` has a sectionName of `https` and goes directly to the backend like so:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-https-route
  namespace: test
spec:
  parentRefs:
  - name: gateway-prod
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - test.com
  rules:
  - backendRefs:
    - name: httpbin
      namespace: test
      port: 8000
```

That should get you where you want to go
