### ISSUE TITLE
SNI TLS Routing for Postgres Services

### ISSUE THREAD

**Issue by Garett-MacGowan** [istio/istio#47895]
### Describe the feature request

**_The Setup_**

I've got a GKE cluster with Istio & CloudNativePG deployed. I have two CloudNativePG `Cluster` resources deployed, serving the standard `r`, `rw`, and `ro` services.

**_Goal_**

I would like to be able to expose the two postgres `rw` services over two separate subdomains using the same port (`5432`). Connecting to the postgres services using something like `db1.data.mysite.com` and `db2.data.mysite.com` and port `5432` would be ideal.

**_Problem_**

I know that TCP alone cannot handle this. I went down the path of using TLS passthrough and SNI routing, but I can't get it working. Any guidance would be appreciated.

As I understand it, the proxy needs to support postgres SNI specifically, but I'm not sure if it does in this case.

The error message below indicates a missing filter chain. I'm not sure how to interpret this. Does this mean that I need to configure something like the [following](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter#config-network-filters-postgres-proxy)? It looks to me like this is for tracking stats.

**_SNI Attempt_**

Here's one of the configurations i've tried so far:

> Note that there would be another VirtualService for db2 in another namespace.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db1
spec:
  gateways:
    - istio-system/istio-ingress-gateway
  hosts:
    - db1.data.mysite.com
  tls:
    - match:
        - sniHosts:
            - db1.data.mysite.com
      route:
        - destination:
            host: db1-rw.namespace.svc.cluster.local
            port:
              number: 5432
```

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: istio-system
  name: istio-ingress-gateway
  labels:
    app: ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 5432
        name: tls-postgres
        protocol: TLS
      tls:
        mode: PASSTHROUGH
      hosts:
        - "*"
```

My istio-ingressgateway exposes the 5432 TCP port
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
    - port: 5432
      name: tls-postgres
      protocol: TCP
      targetPort: 5432
```

_**Errors**_

> psycopg2

connection to server at "db1.data.mysite.com", (my-loadbalancer-ip), port 5432 failed: server closed the connection unexpectedly

> Ingress Gateway Pod Logs

` "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.48.5.72:5432 10.0.0.62:53309 - -`

### Affected product area (please put an X in all that apply)

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### Affected features (please put an X in all that apply)

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

### Alternative Solution

The alternative here is to use pure TCP. The downside of this is UX, since I would have to use a new port for every database instance within the mesh. Also security.
