### ISSUE TITLE
GRPC Proxyless support for EnvoyFilters

### ISSUE THREAD

**Issue by anuragagarwal561994** [istio/istio#47927]
**Describe the feature request**
Istio grpc-proxyless feature to have support for EnvoyFilter

Currently there has been limited development for grpc-proxyless feature in istio but it is one of the most performant features of istio which we are using in our production setup and empowers our infra.

Istio is helping us empower our control planes while grpc is effectively handling load balancing for our setup. GRPC XDS is developing at a rapid pace and adding new features with every release. These features are supported via the Envoy XDS API, but not necessarily directly related to istio configurations.

Istio provides support for using EnvoyFilters to pass any custom configuration to envoy if something is not readily supported by istio in the current phase.

Keeping both things in mind, it would be great if the EnvoyFilter support is extended to GRPC Xds use-cases as an experimental approach, which will allow both the grpc-proxyless and istio development to be on differnet tracks yet being supportive of each other.

As an example, we wanted to try out [outlier detection](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md), but the algorithms supported by grpc-xds have currently an alternative in istio, hence a suggestion on one of the threads was to instead use [EnvoyFilter](https://github.com/grpc/grpc-java/issues/10656).

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[X] GRPC Proxyless

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
I made some changes on my local setup in the istio source code to make this working and I would to contribute for this feature.

Mainly the changes involved were exposing the cluster patcher from `clutser.go` so it can be accessed in `cds.go`
Since this will be my first contribution to istio, it would be great if the community can help me better design the code to follow the code development guidelines properly.

**Comment by hzxuzhonghu** [comment]
>As an example, we wanted to try out [outlier detection](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md), but the algorithms supported by grpc-xds have currently an alternative in istio, hence a suggestion on one of the threads was to instead use https://github.com/grpc/grpc-java/issues/10656.

Not sure how do you patch as the [outlier detection](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md) type is not same with envoy's

**Comment by anuragagarwal561994** [comment]
The types are same with enovy, if you are confused with https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md#lb-policy-config

This is an internal representation which is created after grpc-xds has parsed the enovy configuration and is not provided by the XDS API and that is okay.

If you see this

https://github.com/grpc/grpc-java/blob/0987dc401ca55885b99e98a857705396ab47828e/xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java#L299

It is taking Envoy form of config and then translating it to internal object which is then used 

https://github.com/grpc/grpc-java/blob/0987dc401ca55885b99e98a857705396ab47828e/util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java

https://github.com/grpc/grpc-java/blob/0987dc401ca55885b99e98a857705396ab47828e/xds/src/main/java/io/grpc/xds/XdsClusterResource.java#L219

I think these are enough to be able to navigate the code.

GRPC proxyless uses only what envoy supports, just adds its own sugar over it. So it doesn't have much things different in terms of the API, hence the above patching will work. I have locally tested it as well, or may be let me know if I got something wrong in understanding the question.

**Comment by hzxuzhonghu** [comment]
Do you have an example on outlier? I am asking because i am wondering whether it can be make it in tree

**Comment by anuragagarwal561994** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: outlier-on-percentage
  namespace: istio-poc
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: grpc-server.istio-poc.svc.cluster.local
    patch:
      operation: MERGE
      value:
        outlier_detection:
          failure_percentage_threshold: 100
          enforcing_failure_percentage: 100
          failure_percentage_minimum_hosts: 0
          failure_percentage_request_volume: 2
  workloadSelector:
    labels:
      app: grpc-client
```

If I understand correctly you need the `EnvoyFilter` configuration for the same right, this when I tested with the changes in the linked MR, was propogating to the grpc client.

How the client handles these outliers remains to be tested, but my main goal here was first to let the client understand the config and assuming the client will handle the rest.
