### ISSUE TITLE
Disable JWT Authentication for all paths except one path

### ISSUE THREAD

**Issue by justinyjsong** [istio/istio#47948]
So I have a tricky situation where I want to enable JWT Authentication to a single API endpoint (ex: /temporary-path) and allow other endpoint to not use JWT policy check (using custom check)

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: test-jwt
spec:
  jwtRules:
  # Rule to check JWT be issued by GCP SA
  - issuer: "https://accounts.google.com"
 ---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        notPaths: ["/temporary-path"]
  - from:
    - source:
       requestPrincipals: ["https://accounts.google.com/*"]
  - to:
    - operation:
       methods: ["POST"]
       paths: ["/temporary-path"]
  # omitted 'when' but let's assume custom condition applies here.
```

I thought the above 1st rule will allow execution of any API except `/temporary-path`to use non-JWT and 2nd policy will enable JWT check on `temporary-path`, but it seems like JWT is still required for non `temporary-path`.
