### ISSUE TITLE
remoteIpBlocks doesn't work correctly behind Gateways with different numTrustedProxies

### ISSUE THREAD

**Issue by mikebryant** [istio/istio#47947]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have two different Gateways (one public, one behind Google IAP) with `numTrustedProxies: 1` and `numTrustedProxies: 2` respectively.

We want to be able to use AuthorizationPolicies with `remoteIpBlocks`, and have that respect the original client IP, whichever gateway it came in.

The `x-envoy-external-address` is being set correctly, we can see it in the backend apps - but it doesn't appear to be being used by the AuthorizationPolicy rules.

### Version

```Text
~ istioctl version
seems to hang? We're on 1.19.3

~ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.12
Kustomize Version: v4.5.7
Server Version: v1.25.15-eks-4f4795d
```

### Additional Information

We've worked around this with the following EnvoyFilter

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-internal-remote-ip-handling
  annotations:
    description: |-
      This filter is designed to overwrite the X-Forwarded-For Header on the upstream request
      This will enable the correct use of remoteIpBlocks on things behind the mesh
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: istio-gateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:headers():replace("X-Forwarded-For", request_handle:headers():get("X-Envoy-External-Address"))
            end
```

**Comment by hzxuzhonghu** [comment]
Envoy will use xff header to authorize rather than X-Envoy-External-Address. Looks expected

**Comment by mikebryant** [comment]
The docs state:
> Optional. A list of IP blocks, populated from X-Forwarded-For header or proxy protocol. To make use of this field, you must configure the numTrustedProxies field of the gatewayTopology under the meshConfig when you install Istio or using an annotation on the ingress gateway. See the documentation here: [Configuring Gateway Network Topology](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/). Single IP (e.g. “203.0.113.4”) and CIDR (e.g. “203.0.113.0/24”) are supported. This is the same as the remote.ip attribute.

We have configured `numTrustedProxies` correctly for both of our Gateways, using the annotation on the ingress gateway method. We can't use the meshConfig method because `numTrustedProxies` isn't consistent across our different Gateway architectures. (And in the debug/log output, and by inspection of `X-Envoy-External-Address`, we can see this is working correctly for the gateway, just not the backend services behind them). So by the docs as they're currently written, this should work. I see it as either a bug in the code, or a bug in the docs.

I'd also be fairly happy to use a condition on `request.headers[X-Envoy-External-Address]` - but that condition doesn't appear to support CIDR matching, so it's not suitable either

**Comment by hzxuzhonghu** [comment]
Does X-Forwarded-For set right? The authz works by inspecting the IP from XFF, if no XFF provided, it cannot work

**Comment by mikebryant** [comment]
When it reaches the Gateway, the `X-Forwarded-For` header is correct, and for the respective gateways has the right number of entries for numTrustedProxies. AuthorizationPolicies associated with the Gateways seem to work correctly

When the request reaches a backend service in the mesh, the `X-Forwarded-For` doesn't appear to have been changed, so a single backend service may get inconsistent lengths as the requests come in from different Gateways with different numbers of proxies in front. The backend services in the mesh do receive a correct `X-Envoy-External-Address` - so the `numTrustedProxies` configuration on the relevant gateway has been correctly applied.

I think ideally `remoteIpBlocks` should use the `X-Envoy-External-Address` set by the trusted istio gateway at the edge. This behaviour would match the intent from the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-external-address) - things inside the mesh should use this, because the route a request comes in from the outside may not have a consistent X-Forwarded-For header length when you have multiple different types of Gateway

**Comment by hzxuzhonghu** [comment]
>When the request reaches a backend service in the mesh, the X-Forwarded-For doesn't appear to have been changed,

So you want to apply authorize policy in the backend service?

**Comment by mikebryant** [comment]
Yes, exactly. This is an AuthorizationPolicy one of our dev teams owns, they want to limit access to requests that originally came from the GitHub IP range (for incoming webhooks).

**Comment by hzxuzhonghu** [comment]
If you want to authorize the direct source address, actually the gateway address. You can use source.IpBlocks, rather than the RemoteIPblocks

**Comment by aleveille** [comment]
Additionnally, what should we understand from this:

```
	fromMatches := []*security.Match{}
	for _, from := range rule.From {
		op := from.Source
		if action == security.Action_ALLOW && anyNonEmpty(op.RemoteIpBlocks, op.NotRemoteIpBlocks, op.RequestPrincipals, op.NotRequestPrincipals) {
			// L7 policies never match for ALLOW
			// For DENY they will always match, so it is more restrictive
			return nil
		}
		match := &security.Match{
			SourceIps:     stringToIP(op.IpBlocks),
			NotSourceIps:  stringToIP(op.NotIpBlocks),
			Namespaces:    stringToMatch(op.Namespaces),
			NotNamespaces: stringToMatch(op.NotNamespaces),
			Principals:    stringToMatch(op.Principals),
			NotPrincipals: stringToMatch(op.NotPrincipals),
		}
		fromMatches = append(fromMatches, match)
	
```
https://github.com/istio/istio/blob/f231e954baa054d092000a64c1fbd07c6e208d14/pilot/pkg/serviceregistry/kube/controller/authorization.go#L826-L830

**Comment by jamisonblanchard** [comment]
We are experiencing this issue as well. This has to be a bug. Irrespective of the `numTrustedProxies` setting, the local trusted IP from the proxy (a load balancer in our case) doesn't use the correct IP. This is in directly conflict with the documentation quoted above.

**Comment by macrokernel** [comment]
I am having the same issue as [fabio-s-franco](https://github.com/fabio-s-franco). Istio version: 1.23.2. Please reopen the issue.

**Comment by jgournet** [comment]
I can't be sure it's to solve this issue that we added this horrible fix a long time ago, but sharing it, in case that helps:
(see the description)
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-internal-remote-ip-handling-new
  namespace: istio-system
  annotations:
    description: |-
      This filter is designed to overwrite the X-Forwarded-For Header on the upstream request
      This will enable the correct use of remoteIpBlocks on things behind the mesh
spec:
  workloadSelector:
    labels:
      istio: bgl-ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:headers():replace("X-Forwarded-For", request_handle:headers():get("X-Envoy-External-Address"))
            end
```
