### ISSUE TITLE
Can not use regex to reduce cardinality of istio metrics which caused istio side car crash

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#47940]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Dear Experts,
I am using istio as my kubernetes service mesh. And I want to use metrics such as istio_requests_total as my SLI. I need to add a customized label "request_url_path" into those metrics, whose value is set to the real request url(request.url).

However, after I apply those customization at my metrics, during my load tests, istio-proxy sidecar keeps crashing because of OOMKilled.

After investigation, I think it was cause by the dynamic part inside the request.url(such as some GUID, or random numbers), for example:` /api/v1/jobs/27ee8e1c8bcedd1becerqfe`

I want to remove those dynamic parts inside the url and only apply those static part, below is my test code for applying a customized metrics with telemetry v2.  It checks whether the url path include "login", or "logout", or "api/user", if yes, use "login", or "logout", or "api/user" as the label's value, otherwise, use "unknown" as the label's value.

However, below configuration doesn't work.

It seems the `find`  function(for Common Expression Language regex) is not defined in istio. 

Could you provide some suggestions on how can I solve my problem? Thanks a lot!!

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: add-tags
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: REQUEST_COUNT
          tagOverrides:
            request_url_path:
              value: request.url_path.matches('^/(login|logout|api/user).*$')?request.url_path.find('/(login|logout|/api/user)'):"unknown"
```

### Version

```Text
istioctl version:
client version: 1.19.3
control plane version: 1.15.7
data plane version: 1.15.7 (149 proxies)

kubectl version --short：
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.6
```

**Comment by suxiaoxiaomm** [comment]
We ended up with using lua envoyfilter to remove the Guid part inside the request path and add this as a http request header.
Then add this extra header as a istio metrics dimension.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-add-uri-headers-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              -- Log information about the request
              local x = "%x"
              local t = { x:rep(8), x:rep(4), x:rep(4), x:rep(4), x:rep(12) }
              local pattern_guid = table.concat(t, '%-')
              local pattern_uri = '([^%?]+).*'
              local uripath = string.match(request_handle:headers():get(":path"),pattern_uri)
              local strippedpath = string.gsub(uripath,pattern_guid,'{GUID}')
              request_handle:logInfo("Path: "..strippedpath)
              request_handle:headers():add("request_path_header", strippedpath)
            end
```

**Comment by zirain** [comment]
I think that's the right direction, another suggestion is try https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

**Comment by suxiaoxiaomm** [comment]
> I think that's the right direction, another suggestion is try https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

Thank you for the suggestion.
It seems Lua is more flexible than CEL when using Regex. I perhaps will use Lua filter.

**Comment by zirain** [comment]
so does WASM, which may have better performance.

**Comment by rooque** [comment]
I'm in a similar situation... but did't manage to get it right like you @suxiaoxiaomm .

So I want to eliminate some id's values from URLs from metrics; I have urls like this: /api/v1/provisioning/{id} and /v1/{vendor}/msisdn/{msisdn}

First I tried to do like this:

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_DURATION
          tagOverrides:
            request_host:
              value: 'has(request.host) ? request.host : ''unknown'''
            request_method:
              value: 'has(request.method) ? request.method : ''unknown'''
            request_path:
              value: 'request.path.matches('.*/[0-9]') ? request.path.substring(0, request.path.lastIndexOf('/')) : request.path'
      providers:
        - name: prometheus
```

but I discovered that envoy does not support substring and lastIndexOf; (while k8s support it)

then I tried to use AttrubuteGen like this:
the logic:  if it matches, the attribute "exa_customPath" is genereted, and I want to use that as the request_method dimision; if not matches use request.url_path



```yaml

apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: istio-attributegen-filter
  namespace: istio-system
spec:
  url: https://storage.googleapis.com/istio-build/proxy/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    debug: true
    attributes:
    - output_attribute: "exa_customPath"
      match:
        # - value: "no" // HERE I TRIED WITH A DEFAULT VALUE TOO
        #   condition: ""
        - value: "/api/v1/provisioning/{id}"
          condition: "request.url_path.matches('^/api/v1/provisioning/[[:digit:]]*$')"
        - value: "/v1/{vendor}/msisdn/{msisdn}"
          condition: "request.url_path.matches('^/v1/.*/msisdn/[[:digit:]]*$')"
        
```

with Telemetry like this:

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_DURATION
          tagOverrides:
            request_host:
              value: 'has(request.host) ? request.host : ''unknown'''
            request_method:
              value: 'has(request.method) ? request.method : ''unknown'''
            request_path:
              # value: >- # HERE I TRIED DIFFERENT WAY, NONE WORKED :(
              #   has(request.url_path) ? (exa_customPath.contains("/") ? exa_customPath : request.url_path) : "unknown"
              #   has(request.url_path) ? (exa_customPath != 'no' ? exa_customPath : request.url_path) : "unknown"
              value: 'exa_customPath.contains("/") ? exa_customPath : request.url_path'
      providers:
        - name: prometheus
```

but my metrics are showing up like this:

```
istio_request_duration_milliseconds_count{app="cs-authentication", connection_security_policy="mutual_tls", destination_app="cs-authentication", destination_canonical_revision="v1", destination_canonical_service="cs-authentication", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/authentication/sa/default", destination_service="cs-authentication.authentication.svc.cluster.local", destination_service_name="cs-authentication", destination_service_namespace="authentication", destination_version="v1", destination_workload="cs-authentication", destination_workload_namespace="authentication", instance="10.74.1.147:15020", job="kubernetes-pods", namespace="authentication", pod="cs-authentication-6f88b9bb5b-kvrzm", pod_template_hash="6f88b9bb5b", reporter="destination", request_host="cs-authentication-homol.whitelabel.com.br", request_method="GET", request_path="unknown", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="cs-authentication", service_istio_io_canonical_revision="v1", source_app="istio-ingressgateway", source_canonical_revision="latest", source_canonical_service="istio-ingressgateway", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway", source_version="unknown", source_workload="istio-ingressgateway", source_workload_namespace="istio-system", version="v1"}
```

all with request_path="unknown" 

is this a bug?

**Comment by zirain** [comment]
can you try this with latest version?

**Comment by rooque** [comment]
> can you try this with latest version?

Unfortunately, I am currently unable to set up an environment with the latest version of istio to try to reproduce this behavior.

But I used the same workaround @suxiaoxiaomm used.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-numbers-from-path
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request)
              local path = request:headers():get(":path")
              if path then
                local new_path = path:gsub("[?&][^?&]+=[^?&]+", "")
                local final_path = new_path:gsub("%d%d+", "{id}")
                request:headers():replace("striped_path", final_path)
              end
            end
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request)
              local path = request:headers():get(":path")
              if path then
                local new_path = path:gsub("[?&][^?&]+=[^?&]+", "")
                local final_path = new_path:gsub("%d%d+", "{id}")
                request:headers():replace("striped_path", final_path)
              end
            end
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request)
              local path = request:headers():get(":path")
              if path then
                local new_path = path:gsub("[?&][^?&]+=[^?&]+", "")
                local final_path = new_path:gsub("%d%d+", "{id}")
                request:headers():replace("striped_path", final_path)
              end
            end
            
```

then

```json
"metrics": [
                      {
                        "name": "request_duration_milliseconds",
                        "dimensions": {
                          "request_host": "has(request.host) ? request.host : 'unknown'",
                          "request_method": "has(request.method) ? request.method : 'unknown'",
                          "request_path": "request.headers['striped_path']"
                        }
                      }
                    ]
```
