### ISSUE TITLE
Overwrite Issue in IstioOperator for Resources with Identical Names Across Namespaces

### ISSUE THREAD

**Issue by Freezind** [istio/istio#47991]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

#### Overview:
In Istio's `IstioOperator` configuration, defining multiple ingress gateways with the same name across different namespaces (`ns0` and `ns1`) results in an overwrite issue. This bug, encountered when using the `istioctl manifest generate` command, leads to an incomplete deployment as only the gateway in the last listed namespace is recognized.

#### Example Configuration:
The following configuration aims to deploy two Istio ingress gateways with the same name in `ns0` and `ns1`:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-setup
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: ns0
        enabled: true
        k8s:
          service:
            type: LoadBalancer
      - name: istio-ingressgateway
        namespace: ns1
        enabled: true
        k8s:
          service:
            type: LoadBalancer
```
#### Steps to Reproduce:
1.Create an IstioOperator YAML file with the above configuration.
2.Run `istioctl manifest generate -f istioOperator.yaml` to generate Kubernetes manifests.
3.Review the generated manifest.

#### Actual Behavior:
The generated manifest, detailed below, only includes the ingress gateway for `ns1`, omitting the configuration for `ns0`. This behavior suggests that the second ingress gateway configuration overwrites the first. The complete manifest is available [here](https://gist.github.com/Freezind/aa9699ba00cfe77d3b18482c38b29358#file-manifest-yaml).
```yaml
    ingressGateways:
    - enabled: true
      k8s:
        service:
          type: LoadBalancer
      name: istio-ingressgateway
      namespace: ns1
```

#### Expected Behavior:
The expected outcome is for the generated manifest to include separate ingress gateway entries for both `ns0` and `ns1`, as shown below:
```yaml
ingressGateways:
- enabled: true
  k8s:
    service:
      type: LoadBalancer
  name: istio-ingressgateway
  namespace: ns0
- enabled: true
  k8s:
    service:
      type: LoadBalancer
  name: istio-ingressgateway
  namespace: ns1
```

### Version

```Text
$ istioctl version                                                 
client version: 1.18.0
control plane version: 1.18.5
data plane version: 1.18.5 (39 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.7-eks-4f4795d
```
