### ISSUE TITLE
Native HTTP Metadata Exchange filter not propagting headers to sidecar from Egress Gateway

### ISSUE THREAD

**Issue by psinghal20** [istio/istio#47999]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

With the new Native Metadata exchange filter, Gateways are always configured to discover and propagate headers upstream. In the case of an Egress Gateway, we have a sidecar accessing an external service through the Egress gateway. The sidecar and Egress gateway can be configured to communicate over `ISTIO_MTLS`.

The expectation is that the metadata would be discovered and propagated to the downstream sidecar from the Egress gateway. Due to the missing `downstream_discovery` and `downstream_propagation` in Gateway, the metadata headers are never sent to the downstream sidecar. 

To verify the above behaviour, I added a test in the existing telemetry integration tests: https://github.com/psinghal20/istio/blob/http-egress-gateway-mx/tests/integration/telemetry/common/stats.go#L189-L263.
This test is similar to the existing `TestStatsGatewayServerTCPFilter`. The test fails because the `destination_app` label is `unknown` instead of the `istio-egressgateway` value. 

To further confirm my suspicion of the Metadata exchange filter, I tried installing an Envoy filter applied on the Egress Gateway to configure the `downstream_discovery` and `downstream_propagation` using `istio_headers`. 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: mx-filter-test
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: istio.metadata_exchange
      patch:
        operation: MERGE
        value:
          name: istio.metadata_exchange
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/io.istio.http.peer_metadata.Config
            value:
              upstream_discovery:
              - istio_headers: {}
              upstream_propagation:
              - istio_headers: {}
              downstream_discovery:
              - istio_headers: {}
              downstream_propagation:
              - istio_headers: {}

```

The above filter passed the added test successfully and the `destination_app` label in metric samples populated correctly to `istio-egressgateway`.

This confirmed that the new metadata filter configuration for gateways by Istiod is incorrect and should also have the downstream configuration. 

The configuration of the HTTP Metadata filter is based on the listener class here: https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L383. I propose that configuration for Gateway Listener class should also consider the TLS mode. If the TLS configuration is `ISTIO_MUTUAL`, we can safely propagate the metadata headers to downstream peers.

### Version

```Text
$ istioctl version                      
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)
```
