### ISSUE TITLE
Memory leak in Sidecar, istio 1.19 and 1.20

### ISSUE THREAD

**Issue by Stono** [istio/istio#48023]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Creating a ticket for https://istio.slack.com/archives/C05C7FULQAG/p1700759075429959?thread_ts=1700065931.240079&cid=C05C7FULQAG on slack to discuss what looks like a memory leak in the sidecar since we upgraded to 1.19.

![image](https://github.com/istio/istio/assets/1486729/de9754dd-09a4-400f-b9a4-de8d4b758611)

It only really appears on our highest throughput services.

I've pinged @howardjohn a pprof.

This appears to be in 1.20 too, although we only have 1.20 in our preprod environment so much lower volume.  

### Version

```Text
1.19.4
```

**Comment by Stono** [comment]
FWIW I'm also unable to create heapdump, I get: "Heap profile is not implemented in current build" from `istio-proxy` when hitting http://127.0.0.1:15000/heap_dump.

**Comment by kyessenov** [comment]
Is there some specific telemetry API applied to the workload? It might help to narrow down the cause.

**Comment by kyessenov** [comment]
If you can share telemetry config (or config_dump) for the affected service, and describe the traffic briefly, I can try to replicate the leak locally. There might be some combination of "tag overrides" that causes a leak, but it's difficult to pin point it.

**Comment by Stono** [comment]
Hey everyone.  Sorry for the delay, been swamped.  Will try and get as much debug info as possible over tomorrow.

I think we will be fishing though and it will be hard to pinpoint without a heap dump and that isn't possible on the istio build I use (just the oss version on GitHub), that only permits profiling allocations over a time window and can't really leave that running for days.  The growth is most prominent on a very high throughput service over the course of a few days.

**Comment by hanxiaop** [comment]
> If you can share telemetry config (or config_dump) for the affected service, and describe the traffic briefly, I can try to replicate the leak locally. There might be some combination of "tag overrides" that causes a leak, but it's difficult to pin point it.

I'm using 1.19.3. The current behavior I've observed is: when I apply the same telemetry configuration to both an HTTP service and a TCP service, the HTTP traffic does not have any memory leak. However, for the TCP service, when I have 100 clients, 1000 tps, and a 10KB response body, the Envoy memory usage slowly increases from 60Mi to 260Mi over several hours.

**Comment by hanxiaop** [comment]
Tried 1.17.8, with the same traffic and TCP still had the leak.

<img width="1369" alt="image" src="https://github.com/istio/istio/assets/20888172/e40dc951-f526-45f7-bf84-621c5763c530">

**Comment by zirain** [comment]
@kyessenov anything related to the native stats filter?

**Comment by owais** [comment]
This is quite similar to what we were experiencing. Now that I think about it, most services that saw the leak were also TCP (kafka, thrift, etc). 

Details in case it helps narrow down the issue: https://github.com/istio/istio/issues/48028#issuecomment-1850751671

**Comment by kyessenov** [comment]
@hanxiaop Are these different clients or the same client opening connections, e.g. with respect to peer labels?

**Comment by kyessenov** [comment]
Also, @hanxiaop do you change any label values when you see the leak? Or is it the default config?

**Comment by ldemailly** [comment]
You can maybe repro using fortio's tcp echo port?

**Comment by hanxiaop** [comment]
> @hanxiaop Are these different clients or the same client opening connections, e.g. with respect to peer labels?

@kyessenov There is only one client, with multiple tcp connections.

**Comment by hanxiaop** [comment]
> Also, @hanxiaop do you change any label values when you see the leak? Or is it the default config?

I do have some other configs:

```
meshConfig:
  defaultConfig:
    extraStatTags:
      - destination_mesh_id
      - source_mesh_id
values:
  telemetry:
    v2:
      prometheus:
        configOverride:
          inboundSidecar:
            disable_host_header_fallback: true
            metrics:
              - dimensions:
                  destination_mesh_id: "node.metadata['MESH_ID']"
                  source_mesh_id: "downstream_peer.mesh_id"
                  destination_cluster: "node.metadata['CLUSTER_ID']"
                  source_cluster: "downstream_peer.cluster_id"
          outboundSidecar:
            metrics:
              - dimensions:
                  destination_cluster: "upstream_peer.cluster_id"
                  destination_mesh_id: "upstream_peer.mesh_id"
                  source_cluster: "node.metadata['CLUSTER_ID']"
                  source_mesh_id: "node.metadata['MESH_ID']"
          gateway:
            disable_host_header_fallback: true
            metrics:
              - dimensions:
                  destination_mesh_id: "node.metadata['MESH_ID']"
                  source_mesh_id: "downstream_peer.mesh_id"
                  destination_cluster: "node.metadata['CLUSTER_ID']"
                  source_cluster: "downstream_peer.cluster_id"
```
