### ISSUE TITLE
portLevelMtls for multiple ports not working as expected

### ISSUE THREAD

**Issue by rahtr** [istio/istio#48036]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have a string mTLS policy for the mesh which includes all the namespaces. For some of our pods(ports), we want to set a `PERMISSIVE` mode which can be achieved by setting up `portLevelMtls` in `PeerAuthentication` . This works fine when be have multiple ports defined in the `portLevelMtls` map  in `PeerAuthentication` object but if we have multiple `PeerAuthentication` objects the listeners for plain text are not created. For example this PA would create the non-tls listeners for both ports `8000` and `9000`:

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app: test-exporter
  name: test-exporter
  namespace: dev
spec:
  mtls:
    mode: UNSET
  portLevelMtls:
    "9000":
      mode: PERMISSIVE
    "8000":
      mode: PERMISSIVE                       
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio

```

but if I apply two PA's 

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app: test-exporter-1
  name: test-exporter-1
  namespace: dev
spec:
  mtls:
    mode: UNSET
  portLevelMtls:
    "9000":
      mode: PERMISSIVE                       
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio

```

and 

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app: test-exporter-2
  name: test-exporter-2
  namespace: dev
spec:
  mtls:
    mode: UNSET
  portLevelMtls:
    "8000":
      mode: PERMISSIVE                       
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio

```
the non-tls listeners are created only for the lower port that is `8000`.

### Version

```Text
istioctl version


client version: 1.19.0
control plane version: 1.19.3
data plane version: 1.19.3 (470 proxies)
```

kubectl version

```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.10-eks-4f4795d
```
```


### Additional Information

_No response_
