### ISSUE TITLE
update AuthorizationPolicy will make websocket connection close

### ISSUE THREAD

**Issue by Lewisyixin** [istio/istio#48077]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

1. install istiod、istio-base and istio-ingress by helm
2. create virtualservice (and serviceentry)
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    desc: test
  name: external-lyx-ws-test
  namespace: istio-ingress
spec:
  gateways:
  - lyx-gw
  hosts:
  - lyx-ws-test-qa.test.com
  http:
  - match:
    - uri:
        prefix: /
    retries: {}
    route:
    - destination:
        host: external-lyx-ws-test.192.168.20.226.8765.tcloud
        port:
          number: 8765
      weight: 10000
    timeout: 10.001s
```
this vs connect to a simple ws server by python code
```
import asyncio
import websockets

async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)

start_server = websockets.serve(echo, "0.0.0.0", 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
3.  create AP cr  (and  auth server also, auth server default allows all request)
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: lyx-test
  namespace: istio-ingress
spec:
  action: CUSTOM
  provider:
    name: lyx-auth-test
  rules:
  - to:
    - operation:
        hosts:
        - lyx-ws-test-qa.weizhipin.com
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        paths:
        - /*
        - /l2e*
  selector:
    matchLabels:
      app: istio-ingress
```
4.  connect to ws server by js code below
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WebSocket Client</title>
</head>
<body>
    <h1>WebSocket Client</h1>
    <div id="output"></div>

    <script>
        const outputDiv = document.getElementById('output');
        const socket = new WebSocket('ws://lyx-ws-test-qa.weizhipin.com'); 

        socket.addEventListener('open', (event) => {
            outputDiv.innerHTML += '<p>WebSocket Connection Opened</p>';
           

            socket.send('Hello, WebSocket Server!');
        });

        socket.addEventListener('message', (event) => {
            outputDiv.innerHTML += `<p>Server says: ${event.data}</p>`;
        });

        socket.addEventListener('close', (event) => {
            outputDiv.innerHTML += '<p>WebSocket Connection Closed</p>';
        });
    </script>
</body>
</html>
```
5. update AuthorizationPolicy config ( such as  change path from '/l2e*' to '/l2f*') and after some time(It is generally within one minute, but the specific number of seconds is not fixed.) the ws connect will close
<img width="429" alt="image" src="https://github.com/istio/istio/assets/17898688/b363e37f-a26a-4875-9f77-7e0ebadb9727">

### Version

```Text
helm version: version.BuildInfo{Version:"v3.12.0-rc.1"
istio/istio-ingress version: 1.20.0
kubelet version: v1.24.0
```
