### ISSUE TITLE
Some tcp telemetry is missing

### ISSUE THREAD

**Issue by josunect** [istio/istio#48097]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In a namespace with `istio-injection=enabled` label, the telnet traffic was reported as tcp traffic. This is an example: 

`istio_tcp_received_bytes_total{reporter="destination",destination_workload_namespace="sidecars"}`

`istio_tcp_received_bytes_total{app="tcpserver", connection_security_policy="mutual_tls", destination_app="tcpserver", destination_canonical_revision="latest", destination_canonical_service="tcpserver", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/sidecars/sa/default", destination_service="tcpserver.sidecars.svc.cluster.local", destination_service_name="tcpserver", destination_service_namespace="sidecars", destination_workload="tcpserver", destination_workload_namespace="sidecars", instance="10.244.2.5:15020", job="kubernetes-pods", namespace="sidecars", pod="tcpserver-5b9fc45b55-rksf8", pod_template_hash="5b9fc45b55", reporter="destination", request_protocol="tcp", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="tcpserver", service_istio_io_canonical_revision="latest", source_app="debugbox", source_canonical_revision="latest", source_canonical_service="debugbox", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/sidecars/sa/default", source_version="unknown", source_workload="debugbox", source_workload_namespace="sidecars"}`

`istio_tcp_received_bytes_total{reporter="source",destination_workload_namespace="sidecars"}`

`istio_tcp_received_bytes_total{app="debugbox", connection_security_policy="unknown", destination_app="tcpserver", destination_canonical_revision="latest", destination_canonical_service="tcpserver", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/sidecars/sa/default", destination_service="tcpserver.sidecars.svc.cluster.local", destination_service_name="tcpserver", destination_service_namespace="sidecars", destination_version="unknown", destination_workload="tcpserver", destination_workload_namespace="sidecars", instance="10.244.1.6:15020", job="kubernetes-pods", namespace="sidecars", pod="debugbox-7fcd54b996-p6qgz", pod_template_hash="7fcd54b996", reporter="source", request_protocol="tcp", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="debugbox", service_istio_io_canonical_revision="latest", source_app="debugbox", source_canonical_revision="latest", source_canonical_service="debugbox", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/sidecars/sa/default", source_workload="debugbox", source_workload_namespace="sidecars"}`

In istio 1.20 with Ambient profile this query returns empty results. 
![image](https://github.com/istio/istio/assets/49480155/2e396149-7b88-4336-b89f-3cc493fb178c)

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (8 proxies)

Client Version: v1.27.0
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

### Additional Information

How to reproduce it: 

(Tested in kind cluster with istio 1.20 and ambient profile)

```
kubectl create ns ambient
kubectl create ns sidecars

# Label namespace
kubectl label namespace sidecars istio-injection=enabled
kubectl label namespace ambient istio.io/dataplane-mode=ambient

# Create apps
kubectl apply -f ~/dev/deployments/traffic.yaml -n ambient
kubectl apply -f ~/dev/deployments/traffic.yaml -n sidecars

# Install telnet
kubectl exec $(kubectl get pod -l app=debugbox -n ambient -o jsonpath={.items..metadata.name}) -c debugbox -n ambient -- apt install telnet -y
kubectl exec $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- apt install telnet -y

# http traffic
kubectl exec $(kubectl get pod -l app=debugbox -n ambient -o jsonpath={.items..metadata.name}) -c debugbox -n ambient -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"

kubectl exec $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"

# tcp traffic
kubectl exec -it $(kubectl get pod -l app=debugbox -n ambient -o jsonpath={.items..metadata.name}) -c debugbox -n ambient -- telnet tcpserver 9000
kubectl exec -it $(kubectl get pod -l app=debugbox -n sidecars -o jsonpath={.items..metadata.name}) -c debugbox -n sidecars -- telnet tcpserver 9000
```

Traffic.yaml: 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpserver
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugbox
---
apiVersion: v1
kind: Service
metadata:
  name: debugbox
  labels:
    app: debugbox
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: debugbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugbox
  template:
    metadata:
      labels:
        app: debugbox
    spec:
      containers:
      - name: debugbox
        image: markeijsermans/debug
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver
  labels:
    app: tcpserver
spec:
  ports:
  - port: 9000
    name: tcp
  selector:
    app: tcpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpserver
  template:
    metadata:
      labels:
        app: tcpserver
    spec:
      containers:
      - name: tcpserver
        image: istio/tcp-echo-server:1.1
        imagePullPolicy: IfNotPresent
        args: [ "9000", "hello" ]
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcpserver
```
