### ISSUE TITLE
Add support for async_fetch in remote_jwks in Request Authentication 

### ISSUE THREAD

**Issue by anirudhsaligram** [istio/istio#48108]
**Describe the feature request**

Support for `remote_jwks` was added part of [this](https://github.com/istio/istio/issues/28742) enhancement request and is under the `PILOT_JWT_ENABLE_REMOTE_JWKS` feature flag. It would be nice to support the envoy proxy's [async_fetch](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwksasyncfetch) directly in Istio without the need to configure this setting explicitly part of the envoy filter. What do you all think?

**Describe alternatives you've considered**

While trying to get the envoy filter to MERGE only the `async_fetch` setting, I ran into issues where the MERGE operation is replacing the entire provider configuration instead of just adding the `async_fetch` config block to the `remote_jwks` config. The workaround for me was to include the entire `remote_jwks` config block once again part of the envoy filter which seemed unnecessary to me. Either this or I am doing the MERGE wrong.. in which case, it would be nice to know how to fix this..

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Here are my configs for anyone who is interested (configure destination rule & service entry as needed):

OS: Debian GNU/Linux
Istio Version: 1.18.2 (same issues in other later versions as well)

1) Set the `PILOT_JWT_ENABLE_REMOTE_JWKS` env

2) Request Authentication config 
```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: release-name-jwt-ra
  annotations:
    RoleType: foo
  labels:
    app.kubernetes.io/name: release-name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: release-name
  jwtRules:
    - issuer: "https://x.y.z.com"
      jwksUri: "https://x.y.z.com/auth/v1/jwks"
      forwardOriginalToken: true
```

3) Generated Envoy config
```js
             {
              "name": "envoy.filters.http.jwt_authn",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication",
               "providers": {
                "origins-0": {
                 "issuer": "https://x.y.z.com",
                 "remote_jwks": {
                  "http_uri": {
                   "uri": "https://x.y.z.com/oauth2/v0/jwks",
                   "cluster": "outbound|443||x.y.z.com",
                   "timeout": "5s"
                  },
                  "cache_duration": "300s"
                 },
                 "forward": true,
                 "payload_in_metadata": "https://x.y.x.com"
                }
               },
               "rules": [
                {
                 "match": {
                  "prefix": "/"
                 },
                 "requires": {
                  "requires_any": {
                   "requirements": [
                    {
                     "provider_name": "origins-0"
                    },
                    {
                     "allow_missing": {}
                    }
                   ]
                  }
                 }
                }
               ],
               "bypass_cors_preflight": true
              }
             }
```

4) Add Envoy Filter to `MERGE` `async_fetch` config:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: release-name-jwt-ef
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: release-name
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.jwt_authn"
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.http.jwt_authn"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication"
            providers:
              origins-0: # Assuming that there is only one provider
                remote_jwks:
                  async_fetch:
                    fast_listener: true
```

5) Expected Output: `async_fetch` config added along with existing `remote_jwks` config.
```js
             {
              "name": "envoy.filters.http.jwt_authn",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication",
               "providers": {
                "origins-0": {
                 "issuer": "https://x.y.z.com",
                 "remote_jwks": {
                  "http_uri": {
                   "uri": "https://x.y.z.com/oauth2/v0/jwks",
                   "cluster": "outbound|443||x.y.z.com",
                   "timeout": "5s"
                  },
                  "async_fetch": {
                    "fast_listener": true
                  },
                  "cache_duration": "300s"
                 },
                 "forward": true,
                 "payload_in_metadata": "https://x.y.x.com"
                }
               },
               "rules": [
                {
                 "match": {
                  "prefix": "/"
                 },
                 "requires": {
                  "requires_any": {
                   "requirements": [
                    {
                     "provider_name": "origins-0"
                    },
                    {
                     "allow_missing": {}
                    }
                   ]
                  }
                 }
                }
               ],
               "bypass_cors_preflight": true
              }
             }
```

6) Actual Output: Notice how the entire provider config is replaced
```js
             {
              "name": "envoy.filters.http.jwt_authn",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication",
               "providers": {
                "origins-0": {
                 "remote_jwks": {
                  "async_fetch": {
                   "fast_listener": true
                  }
                 }
                }
               },
               "rules": [
                {
                 "match": {
                  "prefix": "/"
                 },
                 "requires": {
                  "requires_any": {
                   "requirements": [
                    {
                     "provider_name": "origins-0"
                    },
                    {
                     "allow_missing": {}
                    }
                   ]
                  }
                 }
                }
               ],
               "bypass_cors_preflight": true
              }
             }
```
