### ISSUE TITLE
Upgrade with spec.values.telemetry.enabled = false will not delete EnvoyFilter stats-filter-xxx

### ISSUE THREAD

**Issue by j2gg0s** [istio/istio#48126]
First time, I install with default profile.
Istio add EnvoyFilter `stats-filter-xxx` for me.

Second time, I upgrade with default profile and set values.telemetry.enabled to false.
EnvoyFilter `stats-filter-xxx` has not be deleted.

Do I have to delete it manually? Why is this?

**Affected product area (please put an X in all that apply)**
[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by zirain** [comment]
how did you install your istio? istioctl or helm?
what's the version you're using?

**Comment by j2gg0s** [comment]
I thought this was intentional, so I didn’t provide the relevant scene

```
istioctl version
client version: 1.20.0
control plane version: 1.20.0
```

Install with telemetry.enabled = true
```
istioctl --context cn-shanghai install -r 1-20-0 -f control/test.yaml --set values.telemetry.enabled=true -y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete

k --context cn-shanghai get -n istio-system envoyfilters stats-filter-1.20-1-20-0
NAME                       AGE
stats-filter-1.20-1-20-0   30s

istioctl --context cn-shanghai install -r 1-20-0 -f control/test.yaml --set values.telemetry.enabled=false -y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete

k --context cn-shanghai get -n istio-system envoyfilters stats-filter-1.20-1-20-0
NAME                       AGE
stats-filter-1.20-1-20-0   114s
```

@zirain cc

**Comment by zirain** [comment]
can you kindly share the value of control/test.yaml? by default, istio will not install envoyfilter(use Telemetry API instead) by default in v1.20.

**Comment by j2gg0s** [comment]
after remove some gateways

```yaml
---
# Source: istio-control/templates/istio.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example
  namespace: istio-system
spec:
  revision: 1-20-0
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 4
          minReplicas: 2
        env:
        - name: "PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS"
          value: "true"
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    
    - namespace: ingress-istio
      name: internal-default
      enabled: true
      label:
        app: internal-default
      k8s:
        nodeSelector:
          echo.tech/dev: enabled
        serviceAnnotations:
          networking.istio.io/exportTo: "."
          service.beta.kubernetes.io/alibaba-cloud-loadbalancer-protocol-port: "http:80,https:443"
          service.beta.kubernetes.io/alibaba-cloud-loadbalancer-forward-port: "80:443"
          service.beta.kubernetes.io/alibaba-cloud-loadbalancer-xforwardedfor-proto: "on"
        podAnnotations:
          proxy.istio.io/config: |-
            proxyStatsMatcher:
              inclusionSuffixes:
              - cx_active
              - cx_destory
              - cx_http1_total
              - cx_http2_total
              - rq_total
              - rq_pending_total
              - rq_pending_active
            concurrency: 4
        resources:
          requests:
            cpu: "0.1"
            memory: 500Mi
          limits:
            cpu: "2"
            memory:  2Gi
        service:
          externalTrafficPolicy: Local
          ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 30081
          - name: http-as-ssl
            protocol: TCP
            port: 443
            targetPort: 8080
            nodePort: 30082
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: internal-default
          patches:
          - path: "spec.template.spec.containers[0].ports[0]"
          - path: "spec.template.metadata.labels"
            value: |
              log.echo.tech/ingress: enabled
              echo.tech/authn: enabled
  meshConfig:
    accessLogEncoding: JSON
    enableTracing: true
    protocolDetectionTimeout: 0.3s
    defaultConfig:
      extraStatTags:
      - method
      - authority
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin:
          address: jaeger-collector.monitor.svc.cluster.local:9411
      gatewayTopology:
        numTrustedProxies: 1
    discoverySelectors:
      - matchLabels:
          istio-discovery: enabled
    defaultProviders:
      tracing:
        - zipkin-collector
    extensionProviders:
    - name: zipkin-collector
      zipkin:
        service: jaeger-collector.monitor.svc.cluster.local
        port: 9411
  values:
    global:
      meshID: test
      network: cn-shanghai
      multiCluster:
        clusterName: cn-shanghai
      logAsJson: true
      logging:
        level: all:debug
      proxy:
        image: xxx.cn-shanghai.cr.aliyuncs.com/well-known/istio-proxyv2:1.20.0
        logLevel: info
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
      proxy_init:
        image: xxx.cn-shanghai.cr.aliyuncs.com/well-known/istio-proxyv2:1.20.0
    telemetry:
      enabled: false
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
```
