### ISSUE TITLE
how to proxy domain as nginx proxy_pass

### ISSUE THREAD

**Issue by yulinor** [istio/istio#48124]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
as tittle
**Describe alternatives you've considered**

Trigger a button at browser address a to request the interface of domain name b. nginx, which is responsible for processing the request of domain name b, will request the request to domain name c through proxy_pass, because the environment networks of a and c cannot be connected and can only pass through the environment of b. So if it is implemented through pure istio (I want to discard nginx), and the browser address cannot be changed to c or b.
I tried svc externalname pointing to domain name c, and host in vs specifying domain name b. In fact, an error 503 no cluster found was reported. Later, the serviceentry that uses DNS to resolve domain names will report the same error; or it will be 404 uh, but the upstream_cluster becomes "|443||domain c". The operation here is confusing, but both results are confirmed to have existed. In the end, I had to add workloadentryselecotr to serviceentry, and add workloadentry to specify the nginx address that resolves to the c domain name before it can be resolved. But IP may change, so dns is needed (cluster b can resolve domain name address c).
So, how can we directly proxy traffic to the c domain name like nginx's proxy_pass? The simpler, the better!

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Please post the Gateway VS and Dr you applied, and make it more clearly what domain you access

**Comment by yulinor** [comment]
hah，The configuration file has been changed in a confusing way, and the previous corresponding version cannot be found.
So I expect to initiate a request test3 at test-core.domain.com. domain.com/checkProtocol, reaches cluster b, and the istio of cluster b sends its proxy to cluster c as test.domain.com/checkProtocol.
test-core  is domain a ，test3 is domain b ，test is domain c。

Now my adjusted results are as follows：
VS test3 to test
```yaml
spec:
  gateways:
  - myapps
  hosts:
  - test3.domain.com
  http:
  - corsPolicy:
      allowCredentials: true
      allowMethods:
      - GET
      - POST
      - PUT
      - OPTIONS
      - DELETE
      - PATCH
      allowOrigins:
      - exact: https://test.domain.com
    match:
    - uri:
        prefix: /checkProtocol
    name: go-check-test3
    route:
    - destination:
        host: test.domain.com
        port:
          number: 443
```

serviceentry
```yaml
spec:
  endpoints:
  - address: test.domain.com
    ports:
      https: 443
  hosts:
  - test.domain.com
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: tcp
  - name: https
    number: 443
    protocol: tcp
  resolution: DNS
```

destinationrule
```yaml
spec:
  host: test.domain.com
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 10
      tcp:
        connectTimeout: 5s
        maxConnections: 100
        tcpKeepalive:
          interval: 75s
          time: 7200s
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

According to the above configuration, currently istio can find that upstream_cluster is outbound|443||test.domain, but the feedback flag is UF, URX, and the error is "upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure".


Since it is a test environment, it is actually a cluster, just a simulation test. And I hope to remove nginx, so the network information of the current environment is as follows:
A dns-node load resolves domain names in the entire environment, and an openresty is deployed to directly forward the traffic of ports 80 and 443 through istio.stream to the nodeport of svc of istio-ingressgateway, and perform tls secret verification through istio-Gateway. Turn on httpsredirect.

**Comment by yulinor** [comment]
So, I expect to use openresty to simulate becoming aliyun-slb.In fact, I want to deploy a cluster, and I also hope to use slb and also do tcp forwarding istio port. No need for slb to accept https certificate.

**Comment by yulinor** [comment]
> Please post the Gateway VS and Dr you applied, and make it more clearly what domain you access

please help me///

**Comment by blowfishpro** [comment]
I've managed to get this working.  It requires a fair bit of config (you're close though).  I suspect this use case of entering the cluster via a gateway and then immediately leaving is an unusual one as far as Istio is concerned.  You basically have to do 4 things to ensure the upstream connection/request is configured correctly:

1. Set up DNS resolution in the `ServiceEntry`
2. Set up the SNI value to connect with in the `DestinationRule`
3. Set up the domain name to verify on the returned certificate (`subjectAltNames`), either in the `ServiceEntry` or `DestinationRule`
4. Set the host header/authority to be the target domain, in the `VirtualService`

Here's an abbreviated config:
`VirtualService`:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  gateways: [ingress]
  hosts: [downstream.example.com]
  http:
  - match:
      uri:
        prefix: /example
    rewrite:
      authority: upstream.example.com # this sets the host/authority header, otherwise it stays as downstream.example.com
    route:
    - destination:
        host: this.can.be.anything.as.long.as.it.is.consistent.and.unique
        port:
          number: 443
```
`ServiceEntry`:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
spec:
  hosts: [this.can.be.anything.as.long.as.it.is.consistent.and.unique]
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTP2 # probably depends on what the upstream supports
  resolution: DNS
  endpoints:
  - address: upstream.example.com # this is what DNS gets resolved against
```
`DestinationRule`:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
spec:
  host: this.can.be.anything.as.long.as.it.is.consistent.and.unique
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        caCertificates: /etc/ssl/certs/ca-certificates.crt # if not set, verification won't occur
        sni: upstream.example.com # this sets the SNI value on the TLS handshake
        subjectAltNames: [www.qa.appfolio.com] # this verifies that the certificate matches
```
