### ISSUE TITLE
"failed to list *v1alpha1.IstioOperator: json: cannot unmarshal number into Go struct field IstioOperator.items.spec of type string" when parsing IstioOperator CRD

### ISSUE THREAD

**Issue by joelcomp1** [istio/istio#48153]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

the Istio Operator container just constantly ouptuts: 

2023-12-04T12:33:56.322810Z	info	klog	k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: failed to list *v1alpha1.IstioOperator: json: cannot unmarshal number into Go struct field IstioOperator.items.spec of type string
2023-12-04T12:33:56.323125Z	error	klog	k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.IstioOperator: failed to list *v1alpha1.IstioOperator: json: cannot unmarshal number into Go struct field IstioOperator.items.spec of type string

then eventually it crashes with a reflector stack exception and repeats:

[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 226 [running]:
	>  runtime/debug.Stack()
	>  	runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Error(0xc00076ca00, {0x33fec20, 0xc00019b0e0}, {0x2eccd69, 0x20}, {0x0, 0x0, 0x0})
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/log/deleg.go:139 +0x5d
	>  github.com/go-logr/logr.Logger.Error({{0x344a228?, 0xc00076ca00?}, 0x44654b?}, {0x33fec20, 0xc00019b0e0}, {0x2eccd69, 0x20}, {0x0, 0x0, 0x0})
	>  	github.com/go-logr/logr@v1.2.4/logr.go:299 +0xda
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1({0x34441c8?, 0xc000884730?}, 0xc000c8c1e0, {0x3428478, 0xc000c82f00})
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:203 +0x172
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2(0xc000c8c1e0, {0x34441c8?, 0xc000884730}, 0xc000f84020)
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:208 +0x40c
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0xc000c8c1e0, {0x34441c8, 0xc000884730})
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:234 +0x159
	>  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0xc00003ce00)
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/manager/runnable_group.go:223 +0xc8
	>  created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile in goroutine 225
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/manager/runnable_group.go:207 +0x19d
2023-12-04T12:32:40.592665Z	fatal	Manager exited non-zero: failed to wait for istiocontrolplane-controller caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.IstioOperator
Lo

### Version

```Text
Istio Operator: 1.19.4
Istio: 1.19.4
```

### Additional Information

The below CRD is what I am trying to apply, I have spent several hours trying to figure out what is wrong but I can't manage to get any additional debug to figure out what is wrong with my CRD from my helm chart:

```
spec:
  components:
    cni:
      enabled: true
      k8s:
        affinity: {}
        overlays:
          - apiVersion: apps/v1
            kind: DaemonSet
            name: istio-cni-node
            patches:
              - path: >-
                  spec.template.spec.containers.[name:install-cni].securityContext.privileged
                value: true
      namespace: kube-system
    egressGateways:
      - enabled: false
        k8s:
          affinity: {}
          resources: {}
          service:
            type: LoadBalancer
        label:
          app: istio-egressgateway
          istio: egressgateway
        name: istio-egressgateway
        namespace: istio-system
    ingressGateways:
      - enabled: false
        k8s:
          affinity: {}
          nodeSelector: {}
          podAnnotations: {}
          resources: {}
          service:
            type: LoadBalancer
          serviceAnnotations: {}
          tolerations: []
        label:
          app: istio-ingressgateway
          istio: ingressgateway
        name: istio-ingressgateway
        namespace: istio-system
      - enabled: true
        k8s:
          service:
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: mongodb
                port: 27017
                protocol: TCP
                targetPort: 27017
              - name: vcluster
                port: 9443
                protocol: TCP
                targetPort: 9443
            type: LoadBalancer
        label:
          app: public-ingressgateway
          istio: ingressgateway
        name: public-ingressgateway
        namespace: istio-system
    pilot:
      k8s:
        affinity: {}
        env:
          - name: ENABLE_LEGACY_FSGROUP_INJECTION
            value: 'false'
        hpaSpec:
          maxReplicas: 3
          metrics:
            - resource:
                name: cpu
                target:
                  averageUtilization: 60
                  type: Utilization
              type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
        replicaCount: 1
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
        strategy: {}
  hub: registry1.dso.mil/ironbank/opensource/istio
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogFormat: >
      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
      %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS%
      %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
      %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
      %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%"
      "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%"
      "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS%
      %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS%
      %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)%
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 100
      zipkinAddress: jaeger-collector.jaeger.svc:9411
    enableTracing: true
    extensionProviders:
      - envoyExtAuthzGrpc:
          port: '10003'
          service: authservice.authservice.svc.cluster.local
        name: authservice
    meshMTLS:
      minProtocolVersion: TLSV1_2
  profile: default
  tag: 1.19.4
  values:
    cni:
      ambient:
        enabled: false
      chained: false
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      excludeNamespaces:
        - istio-system
        - kube-system
      hub: harbor.bcubed.local/b3/ironbank/opensource/istio
      image: install-cni
      logLevel: info
      repair:
        enabled: false
      tag: 1.19.4
    defaultRevision: default
    global:
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - private-registry
      proxy:
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      proxy_init:
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      tracer:
        zipkin:
          address: jaeger-collector.jaeger.svc:9411
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: false
      jwksResolverExtraRootCA: |
        -----BEGIN CERTIFICATE-----
        MIIBeTCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
        cnZlci1jYUAxNjU5MDkyMDUxMB4XDTIyMDcyOTEwNTQxMVoXDTMyMDcyNjEwNTQx
        MVowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTY1OTA5MjA1MTBZMBMGByqG
        SM49AgEGCCqGSM49AwEHA0IABHTlkUuRsSExprPuQFGs8VlknDwMYff7PuydJGtF
        NEntQi2Vb6keWhsYLbNzEz6XhRT7jLl3M3sdb3zAsgIWNQ+jQjBAMA4GA1UdDwEB
        /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSGdJXgi7AHg7jYEy6H
        B6Vzub2NiDAKBggqhkjOPQQDAgNIADBFAiEAuVvRTUrs7iw9Fr4+qPy5D4K+gtiM
        YIJ1DT2gpvW9UgYCIEyyiUhRHGIkXPQw7mvf3zJGPZt+VCjEHi2mB8sWZBux
        -----END CERTIFICATE-----
      traceSampling: 100
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
      rewriteAppHTTPProbe: true
```

**Comment by PapashaEnot** [comment]
@joelcomp1, hello! It looks like problem is in **_resources_** section in **_components.pilot_** block.

You should change 1 -> '1'.

Example:
```yaml
spec:
  ...
  components:
    pilot:
      k8s:
        ...
        resources:
          limits:
            cpu: 1 # <- change here to '1'
            memory: 2Gi
          requests:
            cpu: 1 # <- change here to '1'
            memory: 2Gi
    ....
  ```
