### ISSUE TITLE
az failover not working as expected

### ISSUE THREAD

**Issue by xhdnoah** [istio/istio#48197]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
### Bug Description

My cluster have two AZ: `j, k`, each of them deploys an identical application pod and same istio gateway, what i expected is the traffic only send to the primary zone for example `j` in normal times, but failover to the secondary zone `k` when the outlier detection happens. What i have tried is setting the localityLbSetting.distribute to make sure zone `k` gets no traffic:
```yaml
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        distribute:
        - from: '*'
          to: 
            xxx/xxx-j/*: 100
    outlierDetection:
      consecutive5xxErrors: 300
      interval: 10s
      baseEjectionTime: 1m
```
In this case the traffic does go only to the `j` zone however the failover is still not working since the envoy clusters only register the pod in zone `j`; and the gateway in secondary zone is required in our scenario.
My question is: is there any other way i can do to implement this task? thanks for any help

### Version

```Text
$ istioctl version
client version: 1.18.2
control plane version: 1.15.2
data plane version: 1.15.2 (371 proxies)
$ kubectl version
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.24.6-aliyun.1
```
