### ISSUE TITLE
ingress-gateway: latency increase on scaling events

### ISSUE THREAD

**Issue by eraac** [istio/istio#48208]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

On scale up or down events [1], some previous pods have increase in latency [2] and cpu/memory usage. In the best scenario this is limited to few milliseconds, but on the worst case latency is up to 10s and load balancer report failure [3].

My only hypothesis is the xDS pushes which seems high for just one more pod, but I've no idea if this is normal or not.

<details>
  <summary>latency / cpu / memory metrics</summary>
<img width="894" alt="image" src="https://github.com/istio/istio/assets/5497623/e12dffb2-a57f-4d5b-ae7f-c329c287fac4">
</details>

<details>
  <summary>xDS pushes metrics</summary>
<img width="894" alt="image" src="https://github.com/istio/istio/assets/5497623/f3a4973c-18d8-468d-9efe-1d7fb97768ba">
</details>

---
[1]: triggered manually or via an HPA
[2]: reported by the metrics: istio_request_duration_milliseconds_bucket
[3]: `failed_to_connect_to_backend`

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.19.0 (4 proxies), 1.19.3 (19 proxies), 1.20.0 (26 proxies)
$ kubectl version --short
Client Version: v1.25.13
Kustomize Version: v4.5.7
Server Version: v1.25.10-gke.2700
```

### Additional Information

<details>
  <summary>istioctl operator.yaml</summary>
  
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal

  meshConfig:
    # same as default, without the X-FORWARDED-FOR header (we can't store client IPs)
    accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"

  values:
    global:
      multiCluster:
        clusterName: "xxxxx"

    pilot:
      autoscaleEnabled: true

    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true

  components:
    pilot:
      enabled: true

      k8s:
        priorityClassName: critical

        podDisruptionBudget:
          maxUnavailable: 1

        hpaSpec:
          minReplicas: 2
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60

        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi

        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            # try to spread per zone
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: istiod

            requiredDuringSchedulingIgnoredDuringExecution:
            # not on the same node
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: istiod

        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:
          - path: spec.template.metadata.labels.app\.kubernetes\.io/name
            value: istiod

    ingressGateways:

    # global

    - name: ingress-gateway-global
      namespace: istio-ingress
      enabled: true
      label:
        app.kubernetes.io/name: ingress-gateway-global

      k8s:
        priorityClassName: critical

        resources:
          requests:
            cpu: 1000m
            memory: 512Mi

        hpaSpec:
          minReplicas: 3
          maxReplicas: 50
          behavior:
            scaleDown:
              stabilizationWindowSeconds: 600
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60

        podDisruptionBudget:
          maxUnavailable: 1

        tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "istio"
          effect: "NoSchedule"

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "cloud.google.com/gke-nodepool"
                  operator: "In"
                  values:
                  - "istio-02"

        serviceAnnotations:
          cloud.google.com/neg: '{"exposed_ports": {"8443": {}}, "ingress": true}'
          cloud.google.com/app-protocols: '{"https": "HTTPS"}'

        podAnnotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 60s

        service:
          type: ClusterIP
          ports:
          - name: https
            port: 8443
            protocol: TCP
            targetPort: 8443

        strategy:
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 10%

        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: ingress-gateway-global
          patches:

            # set a startupProbe (failed startup check doesn't generate error logs on kubelet)
          - path: spec.template.spec.containers.[name:istio-proxy].startupProbe
            value:
              initialDelaySeconds: 1
              failureThreshold: 30
              httpGet:
                path: "/healthz/ready"
                port: 15021
                scheme: HTTP

            # unset the value
          - path: spec.template.spec.containers.[name:istio-proxy].resources.limits.cpu

            # increase the termination grace periods, must be higher than 'terminationDrainDuration' and preStop hook duration
            # 3 minutes 30 secondes
          - path: spec.template.spec.terminationGracePeriodSeconds
            value: 210

            # delay the SIGTERM signal, to ensure NEG is update before
          - path: spec.template.spec.containers.[name:istio-proxy].lifecycle.preStop.exec.command
            value: ["/bin/sh", "-c", "sleep 120s"]
```

</details>

We have a GKE cluster, with a dedicated node pool for the istio-ingress, and the global load balancer connect to the ingress-gateway via [NEG](https://cloud.google.com/load-balancing/docs/negs).

I can probably share more, but I don't know what can be relevant or not
