### ISSUE TITLE
Envoy proxy memory burst/out of memory if telemetry grpc server is slow for both trace and access logs

### ISSUE THREAD

**Issue by liwanxue** [istio/istio#48217]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Using `[Telemetry API](https://istio.io/latest/docs/tasks/observability/telemetry/#using-the-api)` or `[MeshConfig ExtensionProvider](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider)` to configure them to sending trace/access log to a grpc server. 

It will translate to envoy_grpc
```yaml
             "provider": {
              "name": "envoy.tracers.opentelemetry",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "outbound|5000||xxx.nsxxx",
                 "authority": "xxx.nsxxx"
                }
               },
               "service_name": "istio-ingressgateway.istio-system"
              }
             }
```

Will there isn't per-stream limitation for envoy_grpc connection, but it has this in google_grpc https://github.com/envoyproxy/envoy/pull/11072 

According to my experiment, when there are backpressure from telementry grpc server, the memory of envoyproxy will increase to 15GB if using MeshConfig ExtensionProvider to enable it. But using google grpc client with envoyfilter, the memory increase could be limited to 330MB.

Suggestion: expose option to use google_grpc instead of envoy_grpc as grpc client. 

### Version

```Text
istio: 1.17
kubectl: v1.23.6-90+ffb9be09b02b47
```

### Additional Information

A working envoyfilter using google_grpc for access log grpc server would like this 
```yaml
              name: envoy.access_loggers.http_grpc
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
                additional_request_headers_to_log:
                  - abc
                additional_response_headers_to_log:
                  - x-envoy-upstream-service-time
                common_config:
                  log_name: http_envoy_accesslog
                  buffer_size_bytes: 1048576 #1MB, default 16k
                  grpc_service:
                    google_grpc:
                      stat_prefix: als_access_log_grpc
                      target_uri: als.ns:5000
                      per_stream_buffer_limit_bytes: 5242880 # 5MB, default 1MB
                      channel_args:
                        args:
                          grpc.lb_policy_name:
                            string_value: round_robin
                  filter_state_objects_to_log:
                    - wasm.upstream_peer
                    - wasm.upstream_peer_id
                    - wasm.downstream_peer
                    - wasm.downstream_peer_id
                  transport_api_version: V3

```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
Right now, olny `stackdriver` use `GoogleGrpc`, I know little about this, maybe @kyessenov can share more.

**Comment by kyessenov** [comment]
I think you could achieve the same thing with protocol_options in envoy_grpc. The telemetry is dropped when the stream reaches the high watermark, which is controlled by the flow control buffer sizes. I think you want to set `initial_stream_window_size` to 5MB from the default 256MB.

**Comment by zirain** [comment]
> I think you could achieve the same thing with protocol_options in envoy_grpc. The telemetry is dropped when the stream reaches the high watermark, which is controlled by the flow control buffer sizes. I think you want to set `initial_stream_window_size` to 5MB from the default 256MB.

for accesslogs, it's an arrary, IIRC, it's hard to merge with EnvoyFilter? if so, should we provide API for it? or we should change the default value, 256MB seems too large.

**Comment by kyessenov** [comment]
This is a setting in the upstream cluster actually. It's an old problem that flow control buffers are too large by default in Istio.

**Comment by zirain** [comment]
So it's https://github.com/envoyproxy/go-control-plane/blob/b4fd0ad8d58a9bf8cb7d455883b07b565c0d6dfd/envoy/api/v2/core/protocol.pb.go#L428 ?

**Comment by liwanxue** [comment]
@kyessenov @zirain  thanks for your suggestions,  any example configuration I can have a try?

**Comment by zirain** [comment]
try something like:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: merge-cluster
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        name: outbound|8000||httpbin.default.svc.cluster.local
    patch:
      operation: MERGE
      value:
        name: "outbound|8000||httpbin.default.svc.cluster.local"
        http2_protocol_options: 
          initial_stream_window_size: 5242880
```
