### ISSUE TITLE
Envoy filter doesn't applies patches in proper order

### ISSUE THREAD

**Issue by Ferdudas97** [istio/istio#48238]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I create a envoy filter with two patches, which each one modifies timeouts in route - first without matcher should be applied to each route (there is no match criteria) and the second only to specified routes. According to documentation - `Patches within a patch set are processed in the order that they appear in the configPatches list.` - but only this without matchers is applied.

## Example envoy filter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bar
  namespace: default
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        route:
          idle_timeout: 9.000000s
          timeout: 3.000000s
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: foo.appengine:80
    patch:
      operation: MERGE
      value:
        route:
          idle_timeout: 100.000000s
          timeout: 200.000000s
  workloadSelector:
    labels:
      app: bar

```

### Version

```Text
kubectl version
Client Version: v1.28.2
Server Version: v1.23.12
istioctl version
control plane version: 1.17.1
data plane version: 1.17.1
```

**Comment by j2gg0s** [comment]
Can you check your vhost.name by `istioctl proxy-config route {pod}.{namespace} | grep foo.appengine`

**Comment by Ferdudas97** [comment]
```
80                                                             foo.appengine:80                                               foo.appengine                                         /*                     foo.namespace-default
80                                                             foo.appengine:80                                               foo.appengine                                         /*                     foo.namespace-default
80                                                             foo.appengine:80                                               foo.appengine                                         /*                     foo.namespace-default
```

**Comment by Ferdudas97** [comment]
when i apply 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bar
  namespace: default
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: foo.appengine:80
    patch:
      operation: MERGE
      value:
        route:
          idle_timeout: 100.000000s
          timeout: 200.000000s
  workloadSelector:
    labels:
      app: bar
```
it correctly configures a timeouts for this vhost
