### ISSUE TITLE
Multiple JWT tokens on same domain

### ISSUE THREAD

**Issue by holotrack** [istio/istio#48244]
We configured extensionProvider to handler our JWT istio connections to our clusters. We confiured requestauthentication like that:

```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  annotations:

  generation: 33
  labels:
    argocd.argoproj.io/instance: ephemeral-devops
  name: oauth-api-jwt
  namespace: devops
  resourceVersion: "376506068"
  uid: 3295810c-31c6-4600-8a4f-2712a4d3cfa5
spec:
  jwtRules:
  - issuer: https://zitadel.example.com
    jwksUri: https://zitadel.example.com/oauth/v2/keys
  selector:
    matchLabels:
      app: api
```

After applying this configuration everything what is using our zitadel oauth2 solution is working but we have too moblie clients whose are sending its own bearrer token in Authentication header and we started getting such error on mobile endpoints:

```Jwt issuer is not configured```

After adding additional issuer:

```

- issuer: mobileissuer
```

We have such error:
```
Jwt verification fails
```

Is there posibility to exclude this mobile issuer from veryfication/checking? It will be done on app level.  How should such config with multiple JWT tokens looks like? We excluded mobile endpoint but istio still want to veryfy token on this mobile endpoint:

```apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    argocd.argoproj.io/instance: ephemeral-devops
  name: oauth-api-jwt
  namespace: devops
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        notPaths:
        - /horizon*
        - /telescope*
        paths:
        - /*
  - to:
    - operation:
        paths:
        - /horizon*
        - /telescope*
    when:
    - key: request.auth.claims[groups]
      values:
      - group1
      - group2
  selector:
    matchLabels:
      app: api
```
Any ideas how to handle such config?

**Comment by wulianglongrd** [comment]
It seems that the problem is caused by the same request header? (Both use `Authentication`)
If this is the reason, you can use `fromHeaders`, see https://istio.io/latest/docs/reference/config/security/jwt/#JWTHeader

**Comment by husnialhamdani** [comment]
You can do like this for multiple `jwtRules`:

```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: sample-requestauth
  namespace: some-namespace
spec:
  jwtRules:
  - issuer: https://issuer-1
    jwksUri: https://issuer-1/some-path
  - issuer: https://issuer-2
    jwksUri: https://issuer-2/some-path
  selector:
    matchLabels:
      app: some-label
```
