### ISSUE TITLE
Prometheis

### ISSUE THREAD

**Issue by NetanelK** [istio/istio#48263]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have a deployment with Istio sidecar and ServiceMonitor configured. With the following environment variable:
```YAML
PROXY_CONFIG: |
{
  "tracing": {
    "zipkin": {
      "address": "jaeger-operator-jaeger-collector.monitoring.svc.cluster.local:9411"
    }
  },
  "proxyMetadata": {
    "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"
  },
  "extraStatTags": [
    "request_operation"
  ],
  "gatewayTopology": {
    "numTrustedProxies": 2
  },
  "terminationDrainDuration": "15s",
  "proxyStatsMatcher": {
    "inclusionRegexps": [
      ".*downstream_cx_active"
    ]
  }
}
```

When we try to restart the deployment it gets stuck with terminating state while istio-proxy produce the following log:
```
2023-12-10T13:59:07.027187Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2023-12-10T13:59:07.924816Z	info	There are still 1 active connections
```

When inspecting conntrack table we saw that the active connection src matches prometheus server ip, when we added `traffic.sidecar.istio.io/excludeInboundPorts` with the metrics port no issue occurred, but this solution doesn't fit all of our workloads.

We do like to keep EXIT_ON_ZERO_ACTIVE_CONNECTIONS instead of waiting for drain period.
We tried to filter based on user agent header, but it doesn't work well.

How can we fix that behavior?

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.18.1
data plane version: 1.18.1 (29 proxies)

$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.15-eks-4f4795d
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
