### ISSUE TITLE
Change `custom-gateway` labels

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48295]
In tests/integration/pilot/gw_topology_test.go the test suites will deploy custom-gateway has same labels with istio ingressgateway.
```
kind: Service
metadata:
  name: custom-gateway
  labels:
    istio: ingressgateway
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    istio: ingressgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-gateway
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  template:
```

And then set up a gateway, it also applies to the default istio ingress gateway. It is unexpected, so we should change the labels to be different.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio:  "ingressgateway" 
  servers:
  - port:
```
