### ISSUE TITLE
Judgment on whether the retry strategy is effective

### ISSUE THREAD

**Issue by lgy1027** [istio/istio#48296]
I am now verifying whether the retry policy is effective. The current configuration is as follows. When I access istio-proxy, there is only one access log. This does not seem to be effective. Do I need any additional operations in this area?

NAME                       READY   STATUS    RESTARTS   AGE
httpbin-5479d46d89-xjfgx   2/2     Running   0          6h59m

![image](https://github.com/istio/istio/assets/38779388/8c2cc681-9351-4903-898b-72ca5126bce6)

kubectl run -i --rm --restart=Never dummy --image=dockerqa/curl:ubuntu-trusty --command -- curl --silent --head httpbin:8000/status/503

istio-proxy logs

![image](https://github.com/istio/istio/assets/38779388/225530f7-95b2-4e9b-97b1-5bc59d56a6d2)
If you want to test whether the retry is effective, is there any good way? I am using version 1.19.3

**Comment by zirain** [comment]
IIRC, there's a header(`X-Envoy-Attempt-Count`), or you can add `%REQ(X-ENVOY-ATTEMPT-COUNT)%` in accesslog.

**Comment by lgy1027** [comment]
> X-Envoy-Attempt-Count

Hello, can you tell me how to set it up? I couldn't find the relevant help documentation.

**Comment by zirain** [comment]
a demo iop configuration like following:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ambient
  namespace: istio-system
spec:
  profile: ambient
  meshConfig:
    accessLogFormat: "[%START_TIME%] [%REQ(X-ENVOY-ATTEMPT-COUNT)%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %REQUEST_TX_DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% 
```
