### ISSUE TITLE
egress not working in Istio 1.20

### ISSUE THREAD

**Issue by djannot** [istio/istio#48300]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The same configuration is working with Istio 1.19.3.

I've created a ServiceEntry with the following spec:

```
spec:
  exportTo:
  - bookinfo-backends
  - bookinfo-frontends
  - httpbin
  - istio-gateways
  hosts:
  - httpbin.org
  ports:
  - name: https
    number: 443
    protocol: HTTPS
    targetPort: 443
  - name: https-egress
    number: 80
    protocol: HTTP
  resolution: DNS
```

I have a VirtualService with this spec:

```
spec:
  exportTo:
  - bookinfo-backends
  - bookinfo-frontends
  - httpbin
  - istio-gateways
  gateways:
  - virtualgateway-egress-gw-istio--7ed6ddc6cc0426b3eed55330f42f16e
  - mesh
  hosts:
  - httpbin.org
  http:
  - match:
    - authority:
        exact: httpbin.org
      gateways:
      - virtualgateway-egress-gw-istio--7ed6ddc6cc0426b3eed55330f42f16e
      port: 8443
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway-1-20.istio-gateways.svc.cluster.local
        port:
          number: 443
        subset: httpbin-bookinfo-frontends-cluster1
```

And I have a DestinationRule with this spec:

```
spec:
  exportTo:
  - bookinfo-backends
  - bookinfo-frontends
  - httpbin
  - istio-gateways
  host: istio-egressgateway-1-20.istio-gateways.svc.cluster.local
  subsets:
  - name: httpbin-bookinfo-frontends-cluster1
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: httpbin.org
```

So, the subset is correctly defined, but there's no Envoy cluster created for it in my Pod running in the bookinfo-frontends namespace, only

```
outbound|443||istio-egressgateway-1-20.istio-gateways.svc.cluster.local::default_priority::max_connections::4294967295
outbound|443||istio-egressgateway-1-20.istio-gateways.svc.cluster.local::default_priority::max_pending_requests::4294967295
...
outbound|80||istio-egressgateway-1-20.istio-gateways.svc.cluster.local::default_priority::max_connections::4294967295
outbound|80||istio-egressgateway-1-20.istio-gateways.svc.cluster.local::default_priority::max_pending_requests::4294967295
...
```

So when I try to send a request to http://httpbin.org/get, I get a 503 error with a NC flag

### Version

```Text
istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (12 proxies)

kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```

**Comment by minuyim** [comment]
https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1917
It seems that this line causes the bug.

**Comment by howardjohn** [comment]
@minuyim nice find! interested in submitting a PR?

**Comment by minuyim** [comment]
@kimmikimmi has found the cause and is creating PR.

**Comment by GregHanson** [comment]
reproduce steps:

setup
```
istioctl install --set profile=demo
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/sleep/sleep.yaml

kubectl create ns foo
kubectl label namespace foo istio-injection=enabled
kubectl apply -f samples/sleep/sleep.yaml -n foo
```
modified egress gateway with TLS origination from the docs to include 
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  exportTo:
  - foo
  - default
  - istio-system
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: https-egress
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https-port-for-tls-origination
      protocol: HTTPS
    hosts:
    - httpbin.org
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-httpbin
spec:
  exportTo:
  - foo
  - default
  - istio-system
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: my-subset
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: httpbin.org
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-httpbin-through-egress-gateway
spec:
  exportTo:
  - foo
  - default
  - istio-system
  hosts:
  - httpbin.org
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: my-subset
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-httpbin
spec:
  exportTo:
  - foo
  - default
  - istio-system
  host: httpbin.org
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
EOF
```

default ns works:
```
k exec -it deploy/sleep  -- curl -i httpbin.org/get
istioctl pc cluster deploy/sleep --fqdn istio-egressgateway.istio-system.svc.cluster.local
SERVICE FQDN                                           PORT     SUBSET        DIRECTION     TYPE     DESTINATION RULE
istio-egressgateway.istio-system.svc.cluster.local     80       -             outbound      EDS      egressgateway-for-httpbin.default
istio-egressgateway.istio-system.svc.cluster.local     443      -             outbound      EDS      egressgateway-for-httpbin.default
istio-egressgateway.istio-system.svc.cluster.local     80       my-subset     outbound      EDS      egressgateway-for-httpbin.default
istio-egressgateway.istio-system.svc.cluster.local     443      my-subset     outbound      EDS      egressgateway-for-httpbin.default
```
foo fails despite being an exported ns
```
k exec -it deploy/sleep -n foo -- curl -i httpbin.org/get
HTTP/1.1 503 Service Unavailable

istioctl pc cluster deploy/sleep -n foo --fqdn istio-egressgateway.istio-system.svc.cluster.local
SERVICE FQDN                                           PORT     SUBSET     DIRECTION     TYPE     DESTINATION RULE
istio-egressgateway.istio-system.svc.cluster.local     80       -          outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local     443      -          outbound      EDS
```
