### ISSUE TITLE
Sidecar injector precedence should be given to pod labels

### ISSUE THREAD

**Issue by kanurag94** [istio/istio#48316]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**Problem**
Having a revision label on namespace currently overrides revision label given at pod. This is not the expectation when we think about granular control.
This is problematic while doing granular canary upgrades and migration. Migrating a whole namespace is always not ideal. The expected precedence is not documented currently so I believe this issue to be an _ask._

For example:
Namespace `ns1` has a label `istio.io/rev=1-19` and within `ns` there is a `details` deployment which has label `istio.io/rev=1-17`. In this case the revision of namespace `ns1` is always used.

This is due to current MutatingWebhookConfiguration which says something like

```
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - 1-19
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
      
and

  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - "1-19"
```

**Suggestion**

Ideally this could have been something like (subjected to feedback):
```
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - 1-19
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: DoesNotExist
      
and

  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - 1-19
```

**Question**

If this is done deliberately, I wish to understand why and probably:
1. Why does the namespace label and pod label be need to be considered mutually exclusive?
2. What is the impact of `ENHANCED_RESOURCE_SCOPING` if pod labels can be honoured in precedence of namespace labels?

Ps. I believe this is not for security purpose as someone can always add `sidecar.istio.io/inject: false` to override adding proxy even today.

**Expecation**
Pod labels should be able to overwrite namespace label revision. I can draft a PR if this is accepted as a valid requirement.

### Version

```Text
client version: 1.17.2
istiod version: 1.17.2
pilot version: 1.19.3-9d7a73d4d6
istiod version: 1.19.3-9d7a73d4d6
istiod version: 1.19.3-9d7a73d4d6
data plane version: 1.17.2 (6 proxies), 1.19.3-9d7a73d4d6 (21 proxies)

Client Version: v1.27.1
Server Version: v1.25.2
```
