### ISSUE TITLE
Sidecar injector precedence should be given to pod labels

### ISSUE THREAD

**Issue by kanurag94** [istio/istio#48317]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Having a revision label on namespace currently overrides revision label given at pod. This is not the expectation when we think about granular control.
This is problematic while doing granular canary upgrades and migration. Migrating a whole namespace is always not ideal. The expected precedence is not documented currently so I believe this issue to be an _ask._

For example:
Namespace `ns1` has a label `istio.io/rev=1-19` and within `ns` there is a `details` deployment which has label `istio.io/rev=1-17`. In this case the revision of namespace `ns1` is always used.

This is due to current MutatingWebhookConfiguration which says something like

```
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - 1-19
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
      
and

  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - "1-19"
```

**Suggestion**

Ideally this could have been something like (subjected to feedback):
```
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - 1-19
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: DoesNotExist
      
and

  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - 1-19
```

**Describe alternatives you've considered**
Pod labels should be able to overwrite namespace label revision. Currently edited the MutatingWebhook manually.

**Question**

If this is done deliberately, I wish to understand why and probably:
1. Why does the namespace label and pod label be need to be considered mutually exclusive?
2. What is the impact of `ENHANCED_RESOURCE_SCOPING` if pod labels can be honoured in precedence of namespace labels?

Ps. I believe this is not for security purpose as someone can always add `sidecar.istio.io/inject: false` to override adding proxy even today.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
I can draft a PR if this is accepted as a valid requirement.
