### ISSUE TITLE
http/1.1 protocol error: headers count exceeds limit

### ISSUE THREAD

**Issue by allen-bmf** [istio/istio#48356]
istio ver : 1.19.4

```
2023-12-14T08:44:56.591559Z	debug	envoy client external/envoy/source/common/http/codec_client.cc:170	[Tags: "ConnectionId":"502"] Error dispatching received data: http/1.1 protocol error: headers count exceeds limit	thread=23
```
I want to increase http header count and http header size
The problem is that it is not possible with envoyfilter.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-header-count-size-control
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        common_http_protocol_options:
          max_headers_count: 200 # default is 100
        max_request_headers_kb: 96 # 96 KiB is the maxumum allowed, default is 60 KiB.
  - applyTo: NETWORK_FILTER
    match:      
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          common_http_protocol_options:
            max_headers_count: 200 # default is 100
          max_request_headers_kb: 96 # 96 KiB is the maxumum allowed, default is 60 KiB.
```

not working this enovy filter
