### ISSUE TITLE
Can we have `loadBalancerClass` added to Operator API ServiceSpec so we can use it with `istioctl` installation?

### ISSUE THREAD

**Issue by karanrn** [istio/istio#48360]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Kubernetes already supports `spec.loadBalancerClass` in the service spec. It will be good to have the same in the gateway through `istioctl` using a custom profile which is an IstioOperator CR. Using this we can offload the external Load Balancer (LB) reconciliation to respective controllers.

This becomes convenient when hosting the K8s cluster on a cloud provider like AWS and using the respective LB controllers which are controlled through service annotations.

Reference for AWS LB controller - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/#configuration

We are using `istioctl` to generate our manifests with configuration from a custom profile
```
istioctl manifest generate -f istio-custom-profile -o .
```

**Describe alternatives you've considered**
We have to manually add `spec.loadBalancerClass` to the generated manifest of the ingress gateway service. It becomes an extra step to add it every time we generate the manifests.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Related issue - https://github.com/istio/istio/issues/39079

**Comment by karanrn** [comment]
I can work on this if it makes sense to add it

**Comment by hanxiaop** [comment]
The `gateways` charts rendered in istioctl are deprecated, see https://github.com/istio/istio/tree/master/manifests/charts/gateway#legacy-gateway-helm-charts.

**Comment by hanxiaop** [comment]
I think in this case, k8s `Overlays` field in the gateway component should work?

**Comment by karanrn** [comment]
Thank you @hanxiaop I will try this out

**Comment by karanrn** [comment]
@hanxiaop I am actually using k8s overlays
```
ingressGateways:
- name: istio-ingressgateway
  enabled: true
  k8s:
    replicaCount: 2
    service:
      ports:
        - name: status-port
          nodePort: 31002
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          nodePort: 31001
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          nodePort: 31000
          port: 443
          protocol: TCP
          targetPort: 8443
        - name: tcp
          nodePort: 31003
          port: 31400
          targetPort: 31400
        # This is the port where sni routing happens
        - name: tls
          nodePort: 31004
          port: 15443
          targetPort: 15443
      loadBalancerSourceRanges:
        - "x.x.x.x/32"
      loadBalancerClass: "service.k8s.aws/nlb"
 ```


And I am getting an unmarshalling error - `Error: error unmarshaling JSON: while decoding JSON: unknown field "loadBalancerClass" in istio.operator.v1alpha1.ServiceSpec`
