### ISSUE TITLE
TLS-Origination from workload not working, but HTTPS calls works from sidecar

### ISSUE THREAD

**Issue by esn89** [istio/istio#48424]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have sidecar mounted certs and keys, and from within the istio-proxy sidecar, my HTTPS calls using the certs at the mount point work:

`kubectl exec -it pod -c istio-proxy -- bash`

`cd /etc/certs/secrets`

`curl https://endpoint.com/foo/bar/1 --key key.key --cert cert.crt --cacert cacert`

And from there, I was confident that I can rule out any cert/key issue and networking issue because my curl returns 200 and I am happy.

However, when I begin to make HTTP calls from within my main workload pod:

`kubectl exec -it pod -c istio-proxy -- bash`

I expect it to hit the same endpoint without any issues with TLS enabled via envoy sidecar and with those same keys/certs I have provided.  However, I get this error:
 
 ```
 curl --request GET --url http://endpoint.com/foo/bar/1
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

**Details of my set up:**

How my certs are mounted:

Deployment.yaml:

```json
        sidecar.istio.io/userVolumeMount: |
          [
            {
              "name": "my-set-of-certs-keys",
              "mountPath": "/etc/certs/secrets",
              "readOnly": true
            }
          ]
```

`VirtualService`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: qs-cn
spec:
  exportTo:
  - .
  hosts:
  - endpoint.com
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: endpoint.com
        port:
          number: 443
        subset: cdl-mtls
 ```
 
 `DestinationRule`:
 
 ```yaml
 apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: qs-cn
spec:
  exportTo:
  - .
  host: endpoint.com
  subsets:
  - name: cdl-mtls
    trafficPolicy:
      tls:
        caCertificates: /etc/certs/services/cacert.pem
        clientCertificate: /etc/certs/services/client.crt
        mode: MUTUAL
        privateKey: /etc/certs/services/client.key
        sni: endpoint.com
 ```
 
 `VirtualService`:
 
 ```yaml
 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: qs-cn
spec:
  exportTo:
  - .
  hosts:
  - endpoint.com
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: endpoint.com
        port:
          number: 443
        subset: cdl-mtls
```

### Version

```Text
client version: 1.15.7
control plane version: 1.15.7
data plane version: 1.15.7 (11 proxies)

Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.11-eks-8cb36c9

v3.12.3+g3a31588
```

**Comment by GregHanson** [comment]
1.15 is EOL, are you able to reproduce with latest istio?

Is `endpoint.com` a local istio-injected service or an external service, do you have a ServiceEntry defined?  I would check envoy proxy logs to try and get a better idea of the actual error:

```
istioctl pc log <client_pod_name>.<client_pod_ns> --level <debug|trace>
# perform the failed request a few times
# reset the envoy logs pack to normal - trace logs generate a lot
istioctl pc log <client_pod_name>.<client_pod_ns> --reset
```

**Comment by esn89** [comment]
Hi @GregHanson, let me try to upgrade the istio.

endpoint.com is an external service, outside of our cluster.  We have a ServiceEntry for that:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: qs-cn
spec:
  exportTo:
  - .
  hosts:
  - endpoint.com
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 443
    protocol: HTTPS
  resolution: DNS
```

**Comment by GregHanson** [comment]
do you have a `port: 80` defined in your SE?  I think you want your ServiceEntry more in line with the TLS origination examples we have in the [docs](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#configuring-access-to-an-external-service):
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: qs-cn
spec:
  exportTo:
  - .
  hosts:
  - endpoint.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
```
otherwise the client `curl --request GET --url http://endpoint.com/foo/bar/1` sidecar won't have a port 80 listener with hostname matching for `endpoint.com`
