### ISSUE TITLE
forwardClientCertDetails not work in app envoy sidecar

### ISSUE THREAD

**Issue by wuzhuoquan** [istio/istio#48506]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I set ```forwardClientCertDetails: APPEND_FORWARD``` in the meshConfig like this
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
        forwardClientCertDetails: APPEND_FORWARD
```

And then I intall istio with this IstioOperator yaml, and check the istio configmap to make sure the value of ```forwardClientCertDetails``` has been change to APPEND_FORWARD
```
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      gatewayTopology:
        forwardClientCertDetails: APPEND_FORWARD
        numTrustedProxies: 2
```

Set the mtls mode in ```STRICT```

And then I deploy 3 test apps in the namespace ```istio-test``` with label ```istio-injection: enabled```.
All the 3 apps is the same except deployment name and svc
| deployment | service |
| ---|---|
|   test-app-1  |  test-app-1  |
|   test-app-2  |  test-app-2  |
|   test-app-3  |  test-app-3  |

The apps has 2 api interface
- /headers  :   return the headers received from the client to the client
- /proxy      :   proxy the request to the URL that specified by the header ```x-proxy-url```

The code is below
```
@bp.route("/headers", methods=["get"])
def return_headers():
    headers = ""
    for k, v in request.headers:
        headers = headers + "%s: %s\n" % (k, v)
    print(headers)
    return headers

@app.route("/proxy", methods=["get", "post"])
def proxy():
    url = request.headers.get("x-proxy-url")
    if url is None:
        return "x-proxy-url must in headers to specifice which url to proxy", 404
    logger.info(url)
    headers = dict(request.headers)
    headers.pop('Host')
    logger.info(headers)
    response = requests.request(request.method, url=url, headers=headers)
    return Response(response.content, content_type=response.headers['Content-Type'], status=response.status_code)
```

After that, I make a request in test-app-1 pod
```
curl http://test-app-2:8080/proxy -H "x-proxy-url: http://test-app-3:8080/headers"
```
That means ```test-app-2``` will send the request to ```test-app-3``` with All the headers from ```test-app-1```, of course include ```X-Forwarded-Client-Cert```

the headers of ```test-app-2``` received
```
{
    "User-Agent": "curl/7.68.0",
    "Accept": "*/*",
    "X-Proxy-Url": "http://test-app-3:8080/headers",
    "X-Forwarded-Proto": "http",
    "X-Request-Id": "1800d423-9bce-9c10-8cfb-eb8883bc6800",
    "X-Envoy-Attempt-Count": "1",
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/istio-test/sa/test-app-2;Hash=51e50ed9092af68c8a511cc0e2b78c6a6eb985904a52c6987b39ebf5cd4c2487;Subject=\"\";URI=spiffe://cluster.local/ns/istio-test/sa/test-app-1",
    "X-B3-Traceid": "7ade8e3a928ca337109d10b31534bb50",
    "X-B3-Spanid": "b3206bf3ef9791f9",
    "X-B3-Parentspanid": "109d10b31534bb50",
    "X-B3-Sampled": "1"
}
```

And the headers returnd from ```test-app-3```，notice that the header ```X-Forwarded-Client-Cert``` is overwrite, not append.
```
Host: test-app-3:8080
User-Agent: curl/7.68.0
Accept-Encoding: gzip, deflate
Accept: */*
X-Proxy-Url: http://test-app-3:8080/headers
X-Forwarded-Proto: http
X-Request-Id: 1800d423-9bce-9c10-8cfb-eb8883bc6800
X-Envoy-Attempt-Count: 1
X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/istio-test/sa/test-app-3;Hash=c769008ab48ddd6acac46874f85135b2d80f0f47d7861783ef960161156122e0;Subject="";URI=spiffe://cluster.local/ns/istio-test/sa/test-app-2
X-B3-Traceid: 7ade8e3a928ca337109d10b31534bb50
X-B3-Spanid: 3950dbd82de4895c
X-B3-Parentspanid: d3b972b4856bc5f9
X-B3-Sampled: 1
```

### Version

```Text
wuzq@wuzhuoqanmbp211 ~ % istioctl version
client version: unknown
control plane version: 1.19.3
data plane version: 1.19.3 (10 proxies), unknown (4 proxies)


Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.26.3-aliyun.1
```
