### ISSUE TITLE
EnvoyFilter ext_authz googlegrpc disable routing for specific paths

### ISSUE THREAD

**Issue by amankumarcs** [istio/istio#48507]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Describe the feature request

I want to avoid routing requests to OPA authz sidecar for kubernetes healthcheck requests.
example if path is "/health/check" then bypass

How can we implement it in Istio?

Here is our EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      ct-enforcement: enabled
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            transport_api_version: V3
            status_on_error:
              code: ServiceUnavailable
            grpc_service:
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz"
```

### Version

```Text
client version: 1.15.2
control plane version: 1.20.1
data plane version: 1.20.0 (1 proxies), 1.20.1 (6 proxies), 1.14.3 (1 proxies), 1.18.2 (6 proxies)


#kubectl version --short
Client Version: v1.19.0
Server Version: v1.24.16
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
