### ISSUE TITLE
HTTPRouteMatchRequest method validation error

### ISSUE THREAD

**Issue by zirain** [istio/istio#48529]
apply following configuration will receive error message:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: method-prefix
spec:
  hosts:
    - "httpbin"
  http:
    - match:
        - method:
            prefix: ""
      route:
        - destination:
            host: httpbin.default.svc.cluster.local
```

error message:
```console
2023-12-24T07:05:01.702424Z	warn	ads	ADS:RDS: ACK ERROR sleep-7656cf8794-9ns8b.default-3 Internal:Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Match: embedded message failed validation | caused by RouteMatchValidationError.Headers[0]: embedded message failed validation | caused by HeaderMatcherValidationError.StringMatch: embedded message failed validation | caused by StringMatcherValidationError.Prefix: value length must be at least 1 characters): name: "80"
virtual_hosts {
  name: "httpbin.default.svc.cluster.local:80"
  domains: "httpbin.default.svc.cluster.local"
  routes {
    match {
      prefix: "/"
      case_sensitive {
        value: true
      }
      headers {
        name: ":method"
        string_match {
          prefix: ""
        }
      }
    }
    route {
      cluster: "outbound|80||httpbin.default.svc.cluster.local"
      timeout {
      }
      retry_policy {
        retry_on: "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes"
        num_retries {
          value: 2
        }
        retry_host_predicate {
          name: "envoy.retry_host_predicates.previous_hosts"
          typed_config {
            [type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate] {
            }
          }
        }
        host_selection_retry_max_attempts: 5
        retriable_status_codes: 503
      }
      max_grpc_timeout {
      }
    }
    metadata {
      filter_metadata {
        key: "istio"
        value {
          fields {
            key: "config"
            value {
              string_value: "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/method-prefix"
            }
          }
        }
      }
    }
    decorator {
      operation: "httpbin.default.svc.cluster.local:80/*"
    }
  }
  include_request_attempt_count: true
}
```
