### ISSUE TITLE
Uri, scheme, method, authority are not ignored in HTTPMatchRequest header keys

### ISSUE THREAD

**Issue by qts0312** [istio/istio#48555]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello, in Istio official documentation, it says that the keys uri, scheme, method and authority will be ignored in HTTPMatchRequest headers to avoid conflicts. https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

However, in my practice, these keys are not ignored. Here is my configuration:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - '*.bookinfo.com'
  http:
  - match:
    - uri:
        prefix: /productpage
      method:
        exact: GET
      headers:
        method:
          exact: GET
    route:
    - destination:
        host: productpage.default.svc.cluster.local
```

I tried `curl -H"Host:www.bookinfo.com" http://1.1.1.1:10090/productpage -vv`, but it failed. Only using `curl -H"Host:www.bookinfo.com" -H"method:GET" http://1.1.1.1:10090/productpage -vv`, packet can reach the target pod. 

The same thing happens in uri, scheme and authority, which is not consistent with the official documentation.

### Version

```Text
$ istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1
$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

### Additional Information

This configuration doesn't cause warn in `kubectl logs -l app=istiod -n istio-system --tail=300`
