### ISSUE TITLE
Header operations are not correctly merged in virtual service delegation

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#48604]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I use header operation in a delegated virtual service, the operations do not take effect before delegating the traffic to  delegated virtual service. The [document](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute) depicts that delegation will merge rules both virtual services, but it does not.

In this example, I cannot `curl -H"Host:www.bookinfo.com" http://1.1.1.1:10090/productpage -vv` because virtual service `bookinfo` does not add label `hello` before delegation to virtual service `productpage`. The desired behavior should be a successful visit at `productpage.default.svc.cluster.local`.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - www.bookinfo.com
  http:
  - delegate:
      name: productpage
      namespace: default
    headers:
      request:
        add:
          label: hello
    match:
    - uri:
        prefix: /productpage
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  http:
  - match:
    - headers:
        label:
          exact: hello
    route:
    - destination:
        host: productpage.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se
spec:
  hosts:
  - www.bookinfo.com
  ports:
  - name: http
    number: 10090
    protocol: HTTP
  resolution: DNS
```

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (4 proxies)
$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```
