### ISSUE TITLE
`choose_first: true` of Compressor is not applied with EnvoyFilter

### ISSUE THREAD

**Issue by noahingh** [istio/istio#48620]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The `choose_first` [field](https://www.envoyproxy.io/docs/envoy/latest%20/api-v3/extensions/filters/http/compressor/v3/compressor.proto) is not applied to the compressor filter in EnvoyFilter. When I checked the listener of istio-proxy with `istioctl`, the `choose_first` field was not found. I post the EnvoyFilter and the result of `istioctl` below. 

<details>
<summary>EnvoyFilter</summary>

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-compression
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            compressor_library:
              name: text_optimized
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.compression.brotli.compressor.v3.Brotli
                quality: 11
            choose_first: true
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            compressor_library:
              name: text_optimized
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                compression_level: BEST_COMPRESSION
                memory_level: 9
            remove_accept_encoding_header: true
```
</details>

<details>
<summary>Istioctl pc listener</summary>

```shell
istioctl pc listener istio-ingressgateway-nlb-5bcbf879d8-rrh96.istio-system -o json | more
```
```json
                                {
                                    "name": "envoy.filters.http.compressor",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compres
sor",
                                        "compressorLibrary": {
                                            "name": "text_optimized",
                                            "typedConfig": {
                                                "@type": "type.googleapis.com/envoy.extensions.compression.brotli.compressor.v3.Brotli",
                                                "quality": 11
                                            }
                                        }
                                    }
                                }
```

</details>

### Version

```Text
$istioctl version 
client version: 1.16.7
control plane version: 1.16.7
data plane version: 1.16.7 (227 proxies)

$kubectl version
Client Version: v1.24.16
Kustomize Version: v4.5.4
Server Version: v1.25.16-eks-8cb36c9
```

### Additional Information

The version of an envoy of Istio-proxy is `1.24.10-dev`, and the [document](https://www.envoyproxy.io/docs/envoy/v1.24.10/api-v3/extensions/filters/http/compressor/v3/compressor.proto) of the same version describes the `choose_first`.
