### ISSUE TITLE
Inconsistent proxy configuration when ServiceEntry resolution is changed

### ISSUE THREAD

**Issue by Kyslik** [istio/istio#48653]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Example SE:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example
  namespace: example
spec:
  addresses:
  - 1.1.1.1
  exportTo:
  - .
  hosts:
  - example.external
  ports:
  - name: tcp-20000
    number: 20000
    protocol: tcp
```

This produces following cluster:

```json
"cluster": {
  "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
  "name": "outbound|20000||example.external",
  "type": "ORIGINAL_DST",
  "connect_timeout": "10s",
  "lb_policy": "CLUSTER_PROVIDED",
"last_updated": "2024-01-04T19:18:43.819Z"
```

Amend above SE and add `resolution: DNS`. Which produces following cluster:

```json
"cluster": {
    "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    "name": "outbound|20000||example.external",
    "type": "STRICT_DNS",
    "connect_timeout": "10s",
    "lb_policy": "LEAST_REQUEST",
"last_updated": "2024-01-04T19:24:35.274Z"
```

Amend above SE and update `resolution` to `NONE`. Which produces following cluster:

```json
"cluster": {
    "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    "name": "outbound|20000||example.external",
    "type": "STRICT_DNS",
    "connect_timeout": "10s",
    "lb_policy": "LEAST_REQUEST",
"last_updated": "2024-01-04T19:24:35.274Z"
```

> Note that there is no change; not even in the `last_updated` timestamp.

Now remove SE altogether and create one with `resolution: NONE`. Which produces following cluster:

```json
"cluster": {
    "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    "name": "outbound|20000||example.external",
    "type": "ORIGINAL_DST",
    "connect_timeout": "10s",
    "lb_policy": "CLUSTER_PROVIDED",
"last_updated": "2024-01-04T19:33:09.186Z"
```

### Version

```Text
istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1 (4 proxies)

kubernetes
Server Version: v1.25

This was also observed on Istio 1.18.
```

### Additional Information

n/a
