### ISSUE TITLE
spec.components.ingressGateways.namespace in IstioOperator API is not getting honored.

### ISSUE THREAD

**Issue by bhaskar-reddy** [istio/istio#48695]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

what you tried:
Tried installing Istio v 1.20.1 using `istioctl install -f <custom-operator-api.yaml>`, with separate namespace for istio-ingressgateway. 

what you expected to happen:
Expected ingressgateway to install in a separate (istio-gateway) namespace. 

and what actually happened:
I see istio-ingressgateway pod install in the istio-system namespace

Here is the <custom-operator-api.yaml> file:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
      namespace: istio-gateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      namespace: istio-gateway
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
        podAnnotations:
          prometheus.io/path: /prometheus
          prometheus.io/port: "8443"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 8Gi
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata: {}
    enablePrometheusMerge: false
  profile: default
  tag: 1.20.1
  values:
    base:
      enableCRDTemplates: false
      validationURL: ""
    defaultRevision: default
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        env: {}
        name: istio-egressgateway
        secretVolumes:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: NodePort
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: ""
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: true
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: default:info
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ""
        enabled: false
      network: ""
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ""
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ""
        excludeInboundPorts: ""
        excludeOutboundPorts: ""
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 5
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        startupProbe:
          enabled: true
          failureThreshold: 600
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 256Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ""
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 2
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      env: {}
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      traceSampling: 100
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
```

### Version

```Text
❯ istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.15.3 (5 proxies), 1.18.3 (1 proxies), 1.20.1 (1 proxies)

❯ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.8-eks-8cb36c9
```

### Additional Information

To be clear, I am able to install ingressgateway on a custom namesapce, AFTER installing istio with minimal profile.. [as mentioned in this document](https://istio.io/latest/docs/setup/additional-setup/gateway/).

But, I wanted to do the installation at the same time (within the same IstioOperator API spec). Instead of installing minimum profile first and do gateway later as a two-step process.

**Comment by hanxiaop** [comment]
I think this is dup with https://github.com/istio/istio/issues/47991.

**Comment by zirain** [comment]
I recall an issue related to this,  the namespace must exists otherwise there's a error. not 100% sure about the latest code.

**Comment by hanxiaop** [comment]
> I think this is dup with #47991.

Sorry this is not a dup, like @zirain said, do you have errors like ns not found? You can also use `istioctl manifest generate` to check the generated manifests.

**Comment by bhaskar-reddy** [comment]
> ..the namespace must exists otherwise there's a error..

@zirain, where do you suggest the namespace should exist? As mentioned in the title, I've included the custom namespace in `spec.components.ingressGateways.namespace`, as per [reference doc here](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec). For additional reference, to this bug, I have attached the `IstioOperator` custom API that I have used for installing.

> ..do you have errors like ns not found? You can also use istioctl manifest generate to check the generated manifests.

@hanxiaop, I do not see any errors when I run `istioctl install -f <custom-operator-api.yaml>`. Just the creation of `istiod` and `istio-ingressgateway` pods in the `istio-system` namespace. Also, performing`istioctl manifest generate` and looking into the generated manifest shows the `istio-ingressgateway` deployment set to be installed in `istio-system` namespace.

**Comment by hanxiaop** [comment]
@bhaskar-reddy I can not reproduce. Tried the same IOP yaml you provided, and the deployment is in `istio-gateway` namespace.

**Comment by bhaskar-reddy** [comment]
@hanxiaop, you are right. I noticed the same as well.
Upon deeper comparison when I saw the issue, the IOP yaml I tried has the hub value referencing to my local ECR. So, instead of:
`hub: docker.io/istio`
my IOP yaml has:
`hub: xxx.dkr.ecr.us-west-2.amazonaws.com/istio`.
I just changed the hub values back and forth, and found the cause. Not sure, why this is creating issue. Looking further into why.

**Comment by hanxiaop** [comment]
> @hanxiaop, you are right. I noticed the same as well. Upon deeper comparison when I saw the issue, the IOP yaml I tried has the hub value referencing to my local ECR. I changed the hub back to docker.io when I updated here. So, instead of: `hub: docker.io/istio` my IOP yaml has: `hub: xxx.dkr.ecr.us-west-2.amazonaws.com/istio`. I tested the hub values back and forth, and found the issue happening. Not sure, why this is creating issue. Looking further into why.

@bhaskar-reddy I tried to replace it with your hub value, and still cannot reproduce the issue. Feel free to report if you have more clue. The IOP I'm using is:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
      namespace: istio-gateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      namespace: istio-gateway
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
        podAnnotations:
          prometheus.io/path: /prometheus
          prometheus.io/port: "8443"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 8Gi
  hub: xxx.dkr.ecr.us-west-2.amazonaws.com/istio
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata: {}
    enablePrometheusMerge: false
  profile: default
  tag: 1.20.1
  values:
    base:
      enableCRDTemplates: false
      validationURL: ""
    defaultRevision: default
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        env: {}
        name: istio-egressgateway
        secretVolumes:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: NodePort
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: ""
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: true
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: default:info
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ""
        enabled: false
      network: ""
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ""
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ""
        excludeInboundPorts: ""
        excludeOutboundPorts: ""
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 5
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        startupProbe:
          enabled: true
          failureThreshold: 600
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 256Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ""
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 2
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      env: {}
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      traceSampling: 100
    telemetry:
      enabled: true
      v2:
        enabled: true
```
