### ISSUE TITLE
opentelemetry tracing breaks sidecar injection

### ISSUE THREAD

**Issue by tcolgate** [istio/istio#48698]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When deploying istio with helm and the following values for tracing:
```yaml
global:
  proxy:
    tracer: opentelemetry

meshConfig:
  enableTracing: true
  defaultConfig:
    tracing: {}
  defaultProviders:
      tracing:
      - "opentelemetry"
  extensionProviders:
  - name: "opentelemetry"
    opentelemetry:
      service: otel-node-collector.kube-system.svc.cluster.local
      port: 4317

proxy:
  enableTracing: true
```
results in the following meshConfig that seem to track with the required settings for opentelemetry tracing:

```yaml
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing: {}
    defaultProviders:
      tracing:
      - opentelemetry
    enablePrometheusMerge: true
    enableTracing: true
    extensionProviders:
    - name: opentelemetry
      opentelemetry:
        port: 4317
        service: otel-node-collector.kube-system.svc.cluster.local
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

With this config in place, pods cannot be created. The logs for istiod show the follow
```
2024-01-09T08:40:35.239386Z     error   Pod injection failed: failed to run injection template: failed applying injection overlay: unmarshal patched pod: json: cannot unmarshal string into Go struct field Probe.spec.containers.readinessProbe.failureThreshold of type int32
```
And an event with the same text appears in the relevant replicatset or statefulset.
Removing the `global.proxy.tracer` setting allows pods to start, but the resulting mesh.defaultConfig (combined with a Telemetry object), no longer results in traces being sent to the collector.

### Version

```Text
istio:
client version: 1.20.0
control plane version: 1.20.1
data plane version: 1.20.1 (6 proxies)

kubernetes:
Client Version: v1.27.5-dispatcher
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

**Comment by tcolgate** [comment]
Some additional info.adding `readiness.status.sidecar.istio.io/failureThreshold` in pod templates results in complaint about other fields. I've tried setting a few others.

**Comment by tcolgate** [comment]
The actual value that seems to cause the injection failure is the `istio-system/istio-sidecar-injector` configmap `values` key of `global.proxy.tracer`.
- If this is set to `zipkin`, injection works.
- If this is set to `opentelemetry`, or an arbitrary value (e.g. `blah`), injection fails with the mentioned error
- If the key is deleted, injection works, and the opentelemetry config from the `istio` configmap can be leveraged

**Comment by tcolgate** [comment]
There's definitely a fix to be made to the helm chart, as it currently puts up a bit of a fight to get working config out. That said, the actual injection failure seems like an actual bug (I've found one previous reference to this in #42150, but that was closed as the user there didn't seem to be actually trying to configure tracing (probably just trying to turn it off).

**Comment by zirain** [comment]
I think you should just ignore `global. proxy.tracer`, for me it's a kind of deprecated configuration.

**Comment by hanxiaop** [comment]
> Removing the global.proxy.tracer setting allows pods to start, but the resulting mesh.defaultConfig (combined with a Telemetry object), no longer results in traces being sent to the collector.

BTW my env works great with simple configs in https://github.com/istio/istio/tree/master/samples/open-telemetry/tracing#update-mesh-config, there's no need to config parts like `tracer` for otel tracing to work.

**Comment by tcolgate** [comment]
Unfortunately the helm chart defaults the value of `global.proxy.tracer`, I don't think it is possible to deploy a working otel tracing setup via helm at present (this should be an easy fix, though I am not sure if the change can be backward compatible. If `global.proxy.tracer` is deprecated, that should also be documented somewhere.

Also, the error caused here is obscure, and this does appear to be triggering a bug of some kind.

**Comment by zirain** [comment]
the following configuration work as expected:
```
helm install istiod istio/istiod -n istio-system --wait -f - <<EOF
global:
  proxy:
    tracer: none

meshConfig:
  enableTracing: true
  defaultConfig:
    tracing: {}
  defaultProviders:
    tracing:
      - "opentelemetry"
  extensionProviders:
    - name: "opentelemetry"
      opentelemetry:
        service: otel-node-collector.kube-system.svc.cluster.local
        port: 4317
EOF
```
