### ISSUE TITLE
Intermittent CORS issue

### ISSUE THREAD

**Issue by ojasgo** [istio/istio#48754]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have Istio installed on kubernetes cluster using Istio Helm chart version `1.16.5`. Its working just fine in most cases. These are the relevent pieces of code. 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'automation_asm:networking.istio.io/Gateway:tilda-gateway/frontend-gateway'
  labels:
    app.kubernetes.io/instance: automation_asm
  name: frontend-gateway
  namespace: gateway
spec:
  selector:
    asm: ingressgateway
  servers:
    - hosts:
        - xxx.xxx.xxx
      port:
        name: https-svc
        number: 443
        protocol: HTTPS
      tls:
        credentialName: tls-certificate-xxx
        mode: SIMPLE
```
This is out gateway Definition. 

```

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'automation_asm:networking.istio.io/VirtualService:tilda/tilda-health'
  labels:
    app.kubernetes.io/instance: automation_asm
  name: health-svc
  namespace: gateway
spec:
  gateways:
    - tilda-gateway/frontend-gateway
  hosts:
    - xxx.xxx.xxx
  http:
    - corsPolicy:
        allowCredentials: true
        allowHeaders:
          - Content-Type
          - authorization
          - cache-control
          - credentials
          - content-type
          - origin
          - organization
          - x-requested-with
        allowMethods:
          - HEAD
          - OPTIONS
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - CONNECT
        allowOrigins:
          - regex: 'https://xxx.xxx.xxx/*'
      match:
        - authority:
            exact: xxx.xxx.xxx
          uri:
            exact: /special-route
      name: special-svc
      redirect:
        uri: /someroute
    - corsPolicy:
        allowCredentials: true
        allowHeaders:
          - Content-Type
          - authorization
          - cache-control
          - credentials
          - content-type
          - origin
          - organization
          - x-requested-with
        allowMethods:
          - HEAD
          - OPTIONS
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - CONNECT
        allowOrigins:
          - regex: 'https://xxx.xxx.xxx/*'
      name: default-routes
      route:
        - destination:
            host: default-svc.default.svc.cluster.local
            port:
              number: 80
            subset: v1
```
and this is the virtual service. virtual service has two parts,  if its a special route it goes to special-svc, there are bunch of such services and configuration for each.  The last block is `default-routes` if nothing matches, default-svc handles it. 

we are seeing intermittent CORS errors on default routes. Just the fact that they dont always show up tells me there is little chance that there is an issue with the configuration. 

I would like to know if anyone else has seen such behaviour or any pointer about how this can be debugged. I have info level logs set and do not see anything related to CORS. 

This behaviour is seen occasionally when frontend makes request to backend service. 

Please let me know if additional information is required. 

### Version

```Text
$ istioctl version                     
client version: 1.20.1
control plane version: 1.12.1
data plane version: 1.12.1 (21 proxies)

$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-gke.900

$ helm version --short
v3.13.2+g2a2fb3b
```

### Additional Information

There are no bugs.
