### ISSUE TITLE
Must we specify CA certificate into secret for mutual TLS ?

### ISSUE THREAD

**Issue by nature502** [istio/istio#48764]
To access the external service with mutual TLS from internal applications in the mesh, we follow the guide in https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#configure-mutual-tls-origination-for-egress-traffic-at-sidecar. It works fine when specifying ca into secret.  The ca in secret is used to verify sever certificate. but here the server certificate is signed by public CA, and the server CA already installed os. If my understanding is right, we could omit ca in secret as server certificate is signed by public CA.  Like accessing a website in browser,  if server certificate is signed by public CA,    no need install CA into browser. The problem is that I got **TLS error: Secret is not supplied by SDS< HTTP/1.1 503 Service Unavailable** when I don't specify CA into secret. Looks like we must specify CA certificate into secret whether CA is public or self-signed.

**Comment by jewertow** [comment]
> If my understanding is right, we could omit ca in secret as server certificate is signed by public CA

No. The `client-credential` secret in that example contains client CA, not the server CA.

**Comment by nature502** [comment]
Got it, the client certificate is signed by public CA, for this situation, do we still need to specify public CA into secret ?

**Comment by nature502** [comment]
> > If my understanding is right, we could omit ca in secret as server certificate is signed by public CA
> 
> No. The `client-credential` secret in that example contains client CA, not the server CA.

Really ? It says that the CA certificate in secret is used to verify the server certificate in https://istio.io/latest/zh/docs/reference/config/networking/destination-rule/#ClientTLSSettings.
![Uploading Screenshot 2024-01-12 at 13.39.30.png…]()

**Comment by jewertow** [comment]
Oh, right... I'm really sorry for confusion.

> Looks like we must specify CA certificate into secret whether CA is public or self-signed.

So as you found in the docs, the CA cert is used to verify the server certificate and it is required. If you don't want to validate server certificate, because it's signed by a trusted CA, you can mount a secret with your client cert and key into a pod and set `clientCertificate` and `privateKey`.

To mount a secret into your pod, you can add the following annotations to the deployment:
```
spec: 
  template: 
    metadata: 
      annotations: 
        sidecar.istio.io/userVolume: '[{"name":"client-cert", "secret":{"secretName":"client-cert"}}, {"name":"client-key", "secret":{"secretName":"client-key"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"client-cert", "mountPath":"/etc/certs", "readonly":true}, {"name":"client-key", "mountPath":"/etc/certs", "readonly":true}]'
```
and then set:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: db-mtls
spec:
  host: mydbserver.prod.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/cert.pem
      privateKey: /etc/certs/key.pem
```
