### ISSUE TITLE
SNI support for ingress/gateway

### ISSUE THREAD

**Issue by costinm** [istio/istio#4879]
For ingress/gateway, if multiple domains and certificates are used we need to generate something like:

```
      - filter_chain_match:
            sni_domains: {{ $domain }}
          tls_context:
            common_tls_context:
              tls_certificates:
                - certificate_chain: { filename: "/etc/istio/ingress-certs/{{ $domain }}-tls.crt" }
                  private_key: { filename: "/etc/istio/ingress-certs/{{ $domain }}-tls.key" }
          filters:
          - name: envoy.http_connection_manager
          ...
```

Current code only generate a single filter-chain-match.

**Comment by andraxylia** [comment]
I see some code is in, but no unit tests.

**Comment by hamon-e** [comment]
Any news on this ?

**Comment by rshriram** [comment]
The Istio ingress gateway supports SNI. Kube Ingress controller SNI is not supported.

**Comment by twittyc** [comment]
The Kubernetes ingress documentation shows they support the SNI TLS extension. Is that different then what you guys are referring to here with the kube ingress controller? Can you help me understand why support isn't being added? Is it not needed? I'd really like to use Istio, but no SNI support is blocking us.

https://kubernetes.io/docs/concepts/services-networking/ingress/#types-of-ingress

**Comment by ZackButcher** [comment]
What Andra and Shriram mean is that Istio supports SNI (this was added in 0.8), but SNI in Istio is not configurable via the Kubernetes Ingress API resource and we do not intent to extend our implementation of the Kubernetes Ingress API to implement SNI support. Instead, the only way that Istio supports configuring SNI is via Istio's [Gateway API](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway).

The experimental Istio command [`convert-networking-config`](https://istio.io/docs/reference/commands/istioctl/#istioctl%20experimental%20convert-networking-config) can be used to help convert Kubernetes Ingress resources into their pair of Istio Gateway+VirtualService, to aid the transition from Kubernetes Ingress to Istio Gateway.

**Comment by ZackButcher** [comment]
Sorry for the late reply, got tied up with DockerCon last week. Yes, the Gateway allows for multiple certificates. The config would look like:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    app: my-ingress-gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - foo.com
    tls:
      mode: SIMPLE
      serverCertificate: /etc/certs/foo/server.pem
      privateKey: /etc/certs/foo/privatekey.pem
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - bar.com
    tls:
      mode: SIMPLE
      serverCertificate: /etc/certs/bar/server.pem
      privateKey: /etc/certs/bar/privatekey.pem
```
This effectively wires up two listeners in Envoy, both on port 443, that will attempt to match the request based on SNI to either `foo.com` or `bar.com`, and will serve `/etc/certs/foo/server.pem` and `/etc/certs/bar/server.pem` for requests with those two hosts respectively.


A pure wildcard `host` (`"*"`) will not work with SNI as Envoy itself does not support that behavior (@rshriram keep me honest here please).

Finally note that with the current implementation, all [`Server`s](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Server) on the same port _must_ use the same protocol (HTTPS in this case).
