### ISSUE TITLE
The backend service warm-up using Ingress Gateway is not meeting expectations

### ISSUE THREAD

**Issue by xlq20080808** [istio/istio#48816]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a backend service that utilizes IngressGateway with warmup configured. The warmup window is set to 30 seconds, and  **locality load balancing is disabled**. However, there seems to be an issue where the traffic warmup time for a pod is significantly greater than the configured 30 seconds.
<img width="1031" alt="image" src="https://github.com/istio/istio/assets/33999699/bb32c6b4-afa7-4cb2-94b5-25278e018d0e">
The configuration for the VirtualService is as follows
```  
trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
      warmupDurationSecs: 30s
```

### Version

```Text
istio control plane version: 1.16.5
istio data plane version: 1.16.5
```
