### ISSUE TITLE
Tomcat/Istio "Transfer-Encoding: chunked" results in Upstream Error

### ISSUE THREAD

**Issue by alpkahvecioglu** [istio/istio#48822]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Basically the same issue as this [one](https://github.com/istio/istio/issues/24753). We are running two tomcat applications and the response includes two **transfer-encoding** headers with different capitalization and istio fails to successfully return a response. 

I understand that the RFC disallows this configuration but I am unable to remove the headers with the following **EnvoyFilter**:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-headers
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER 
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          server_header_transformation: PASS_THROUGH
  - applyTo: ROUTE_CONFIGURATION
    patch:
      operation: MERGE
      value:
        response_headers_to_remove:
        - "x-envoy-upstream-service-time"
        - "server"
        - "Transfer-Encoding"
```

None of the previous discussion helped me with a solution so I would like to know whether my **EnvoyFilter** is misconfigured or I am not familiar with a solution in the istio configuration.

Thanks in advance.

### Version

```Text
❯ istioctl version
client version: 1.19.3
control plane version: 1.20.0
data plane version: 1.20.0 (7 proxies)

❯ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```

**Comment by howardjohn** [comment]
I think it breaks long before it reaches the code to mess with the headers. In general you cannot really use these header manipulation points in Envoy to manipulate internal headers like TE, etc. The only fixes I know are to fix the application or treat the traffic as raw TCP (https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)

**Comment by zirain** [comment]
I recall there's a feature flag in envoy, but it's removed long ago.

**Comment by alpkahvecioglu** [comment]
```
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9080
```

On the service side, it looks like the protocol is already set to TCP. Am I missing something?

**Comment by hzxuzhonghu** [comment]
In istio we can use port name, here it is https

**Comment by alpkahvecioglu** [comment]
I tried changing both the **port.name** to tcp and **appProtocol** to TCP in my service definition but neither of those worked.

For further context, I have the following option enabled in istio `ENABLE_TLS_ON_SIDECAR_INGRESS:  true`.
and these are my **VirtualService** and **Gateway** configuration.

**VirtualService**:
```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: test-virtualservice
    namespace: test-vs
  spec:
    gateways:
    - test-gateway
    hosts:
    - test-vs.example.com
    tls:
    - match:
      - port: 443
        sniHosts:
        - test-vs.example.com
      route:
      - destination:
          host: test-vs
          port:
            number: 443
```

**Gateway**:
```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: test-gateway
    namespace: test-vs
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - test-vs.example.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
```
