### ISSUE TITLE
IPv4 ServiceEntry is not tracked properly on EKS when using ISTIO_ENABLE_IPV4_OUTBOUND_LISTENER_FOR_IPV6_CLUSTERS

### ISSUE THREAD

**Issue by mmerickel** [istio/istio#48829]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

On an IPv6 EKS cluster, with the IPv4 link-local egress, I'm using the new flag ISTIO_ENABLE_IPV4_OUTBOUND_LISTENER_FOR_IPV6_CLUSTERS. It appears to properly allow IPv4 egress traffic from my pods, which it did not without the flag.

When viewing the traffic in the sample/addons configs for prometheus and kiali, all IPv4 traffic is tagged as PassthroughCluster as the destination.

When comparing this behavior to my IPv4-only EKS clusters, the IPv4 traffic that matches a ServiceEntry definition is properly tracked as targeting that ServiceEntry object, and not PassthroughCluster. This allows me to differentiate which traffic I have proper ServiceEntry definitions for, versus unlabeled traffic.

To restate the above:

| Cluster Type | Egress Traffic Type | Label |
|--------|--------|--------|
| IPv4 | IPv4 | ServiceEntry ✅  |
| IPv6 | IPv6 | ServiceEntry ✅  |
| IPv6 | IPv4 | PassthroughCluster :x: |

Example ServiceEntry:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: smtp-traffic
spec:
  exportTo:
  - .
  hosts:
  - email-smtp.us-east-1.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - name: smtp
    number: 587
    protocol: TCP
  resolution: DNS
```

### Version

```Text
Tested with istio 1.20.1.
```

### Additional Information

Related: https://github.com/istio/istio/issues/46719 https://github.com/istio/istio/pull/46800
