### ISSUE TITLE
Recommended approach for TLS requests from services outside of mesh to services within mesh

### ISSUE THREAD

**Issue by satish2** [istio/istio#48836]
In Istio documentation for [MTLS migration](https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/#lock-down-to-mutual-tls-by-namespace), if the service cannot be migrated to mesh, recommendation is to use Permissive instead of STRICT for PeerAuthentication. 

Link: https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/
Recommended approach in documentation: 
![image](https://github.com/istio/istio/assets/1057750/9cbf0588-4057-4ec6-99bc-04f31e7a2370)

**May I know if following is recommended approach ?** 
legacy namespace: We have services in legacy namespace that do not have Istio-proxy sidecar. But, they do need to communicate with services, sleep and httpbin in namespace foo. And, entire namespace foo has Istio injection enabled and peerAuthentication for "foo" namespace is set to STRICT. 

Instead of PERMISSIVE mode, we need STRICT mTLS. And, while making API requests from sleep from legacy namespace, we are including client private-key and client certificate issued by CA trusted by Istio (Basically using CA key and certificate included secret cacerts in istio-system namespace). This ensure services within foo namespace are able to verify requests from legacy/sleep. 

Opening this issue to understand if this approach can also be followed ? And, why doesn't Istio recommend this approach for users who would like STRICT mTLS in their cluster irrespective of services are within mesh or otherwise ?

**Comment by howardjohn** [comment]
The vast majority of users don't have a setup where they can provision compatible certificates and use them for their legacy workloads, so it's not typical

**Comment by lusains** [comment]
I am also dealing with mTLS from outside of mesh to service within mesh. I use spire to act as the ca authority of the entire cluster, so it is ok with mTLS when I set strict mode, But there is a problem with the mode of Permissive.
client code :

```
testApi.Get("/mtls", func(c *context.Context) (interface{}, error) {
			mtlsOnce.Do(func() {
				source, err := workloadapi.NewX509Source(c, workloadapi.WithClientOptions(workloadapi.WithAddr("unix:///run/spire/sockets/socket")))
				if err != nil {
					log.Errorf("NewX509Source err, %v", err)
					return
				}
				svid, _ := source.GetX509SVID()
				for _, v := range svid.Certificates {
					log.Infof("svid Certificates: %v", v)
				}

				tlsConfig := tlsconfig.MTLSClientConfig(source, source, tlsconfig.AuthorizeAny())
				tlsConfig.NextProtos = []string{"h2", "http/1.1"}
				tlsConfig.MinVersion = tls.VersionTLS12
				mtlsClient = &http.Client{
					Transport: &http.Transport{
						TLSClientConfig: tlsConfig,
					},
				}
			})

			if mtlsClient == nil {
				return nil, errors.New("mtls client create fail")
			}
			reqBody := strings.NewReader("")
			ret, err := mtlsClient.Post("https://xxxx:7443/v2/risk-control", "application/json", reqBody)
			if err != nil {
				return nil, err
			}
			defer ret.Body.Close()
			log.Infof("mtls resp status, %d", ret.StatusCode)
			body, err := io.ReadAll(ret.Body)
			if err != nil {
				return nil, err
			}
			return string(body), nil
		})
```

I wanted the sidecar to route to the upstream service's 8080 port after tls termination, so I built a port-translated envoyfliter

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: port-translation
  namespace: tls-test
spec:
  workloadSelector:
    labels:
      app-name: aaa
  configPatches:
    - applyTo: LISTENER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 7443
          filterChain:
            transportProtocol: tls
      patch:
        operation: ADD
        value:
          name: "listener_0.0.0.0_7443"
          address:
            socket_address:
              address: "0.0.0.0"
              port_value: 7443
          filter_chains:
            - filters:
                - name: "envoy.http_connection_manager"
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: "ingress_http_7443"
                    route_config:
                      name: "local_route_7443"
                      virtual_hosts:
                        - name: "local_service_7443"
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: "outbound|8080||aaa.tls-test.svc.cluster.local"
                    http_filters:
                      - name: "envoy.filters.http.router"
```

The error is as follows

```
client:
{"code":500,"data":{},"msg":"Post \"https://xxx:7443/v2/risk-control\": http: server gave HTTP response to HTTPS client"}
service accesslog:
{"downstream_remote_address":"10.80.240.211:60336","upstream_cluster":"InboundPassthroughClusterIpv4","bytes_sent":156,"route_name":null,"upstream_transport_failure_reason":null,"user_agent":null,"authority":null,"request_id":null,"x_forwarded_for":null,"response_flags":"-","start_time":"2024-01-18T14:29:25.282Z","downstream_local_address":"10.80.248.236:7443","path":null,"response_code":0,"protocol":null,"method":null,"requested_server_name":null,"connection_termination_details":null,"duration":0,"upstream_service_time":null,"upstream_local_address":"127.0.0.6:54665","response_code_details":null,"upstream_host":"10.80.248.236:7443","bytes_received":255}
```

Could you please explain it? How can I run it successfully in PERMISSIVE mode?  @howardjohn
