### ISSUE TITLE
Configure SDS socket filename through configuration

### ISSUE THREAD

**Issue by asayah** [istio/istio#48845]
**Describe the feature request**

 Envoy SDS defined socket path is  "/run/secrets/workload-spiffe-uds/socket",  we need a way to configure it since sometimes we may encounter mounting issues, example in distroless 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Why are their mounting issues? I don't think distroless makes it so you cannot mount a volume..?

**Comment by hzxuzhonghu** [comment]
`/run/secrets/workload-spiffe-uds` is an inner container path, donot need mount.

**Comment by hzxuzhonghu** [comment]
[The path that mounted by spire ](https://tetrate.io/blog/managing-certificates-in-istio-with-cert-manager-and-spire/)

The volumes mounted by istio sidecar is same as the spire agent, but the mounted pathes can be different.

**Comment by RunlinXiao** [comment]
@asayah thanks for raising the issue!

@howardjohn @hzxuzhonghu To provide more context:
Istio SPIRE requires the spire-agent have `socket_path = "/run/secrets/workload-spiffe-uds/socket"` so that istio can directly use this path that hardcoded at this moment: [WorkloadIdentitySocketPath](https://github.com/istio/istio/blob/1.22.1/pkg/security/security.go#L49). 
The current usage is mount the directory directly and the socket file with name `socket` could be found.
```
        spire: |
          spec:
            containers:
            - name: istio-proxy
              volumeMounts:
              - name: workload-socket
                mountPath: /run/secrets/workload-spiffe-uds
                readOnly: true
            volumes:
              - name: workload-socket
                csi:
                  driver: "csi.spiffe.io"
                  readOnly: true
```

But for companies that adopt spire-agent already, and use socket path like: [/spiffe-workload-api/spire-agent.sock](https://github.com/spiffe/helm-charts-hardened/blob/2fdebf09a8a09888b994d2b5c627eef764ac8ace/charts/spire/README.md) (whatever socket file name that is not `socket`), then istio won't able to find the socket. Hopefully this makes sense :)

**Comment by hzxuzhonghu** [comment]
Cannot you customize this name like https://github.com/istio/istio/blob/master/samples/security/spire/istio-spire-config.yaml

**Comment by RunlinXiao** [comment]
>Cannot you customize this name like https://github.com/istio/istio/blob/master/samples/security/spire/istio-spire-config.yaml

@hzxuzhonghu Sorry I may not follow, I don't see above example allow us to customize the name, only the path is allowed to customize. Btw, I'm not talking about the name of the volume, I'm talking about the socket file name itself.

**Comment by bleggett** [comment]
1. We recommend the SPIRE CSI driver for a good reason. The security posture is better, and it obsoletes all of these operational problems. Which is why it's the only way we document SPIRE integration with Istio at this time, and the only supported way to do this (by SPIRE, and by us - the SPIRE folks will tell you the same thing).

2. If you don't want to use the CSI driver, you can hack injection templates yourself to mount $any_host_sds_socket_path into the fixed/hardcoded Istio path, using standard K8S `volume/volumeMount` semantics - this requires a bit of work and has some operational corner cases, which is another reason why (1) is recommendation.

Can you help us understand your use case, and why neither (1) or (2) are options for you?

**Comment by RunlinXiao** [comment]
@bleggett Thanks for the reply! 
> Can you help us understand your use case, and why neither (1) or (2) are options for you?

(1) We are already using CSI driver, but this problem is actually caused by the spire-agent side socket file name. 
(2) The path is not the problem, but the socket name is, like you mentioned above, you could give the socket any path you want, but you are not able to configure the socket file name itself. 

To help better understand this issue, here is the step to reproduce it:
1. Install spire-agent with socket path `socket_path = "/run/secrets/workload-spiffe-uds/workload_api.sock"`  (a simple search and replace from [samples/security/spire/spire-quickstart.yaml](https://raw.githubusercontent.com/istio/istio/release-1.22/samples/security/spire/spire-quickstart.yaml) provided by [istio / SPIRE](https://istio.io/latest/docs/ops/integrations/spire/))
2. Configure the CSI driver
```
    sidecarInjectorWebhook:
      templates:
        spire: |
          spec:
            containers:
            - name: istio-proxy
              volumeMounts:
              - name: workload-socket
                mountPath: /run/secrets/workload-spiffe-uds
                readOnly: true
            volumes:
              - name: workload-socket
                csi:
                  driver: "csi.spiffe.io"
                  readOnly: true
```
3. Now if you spin up a pod, you would see below logs
```
{"level":"info","time":"2024-07-01T18:25:46.237751Z","msg":"Workload SDS socket not found. Starting Istio SDS Server"}
{"level":"error","time":"2024-07-01T18:25:47.260588Z","scope":"sds","msg":"SDS grpc server for workload proxies failed to set up UDS: failed to remove unix://./var/run/secrets/workload-spiffe-uds/socket: remove ./var/run/secrets/workload-spiffe-uds/socket: read-only file system"}
```
and when you exec into the istio-proxy container, and check the socket, you are seeing
```
istio-proxy@httpbin-6c764dc657-2jxg5:/run/secrets/workload-spiffe-uds$ ll
total 0
drwxr-xr-x 2 root root  31 Jul  1 16:11 ./
drwxr-xr-x 8 root root 138 Jul  1 18:25 ../
srwxrwxrwx 1 root root   0 Jul  1 16:11 workload_api.sock=
```
The socket file name itself is not matching [what istio expected](https://github.com/istio/istio/blob/1.22.1/pkg/security/security.go#L49), istio is expecting this:
```
istio-proxy@httpbin-57b7f96d4f-nlngt:/run/secrets/workload-spiffe-uds$ ll
total 0
drwxr-xr-x 2 root root  20 Jul  1 17:48 ./
drwxr-xr-x 8 root root 138 Jul  1 17:48 ../
srwxrwxrwx 1 root root   0 Jul  1 17:13 socket=
```
I hope this help clarify the issue here, again, it's the socket file name itself, not the socket path.
