### ISSUE TITLE
Override templates using sidecarInjectorWebhook

### ISSUE THREAD

**Issue by asayah** [istio/istio#48864]
Using sidecarInjectorWebhook doesn't allow us to override previous template or hardcoded values 

**Describe the feature request**
sidecarInjectorWebhook, provide a mode where template B can override Template A can override Hardcoded helm value. 

example: override https://github.com/istio/istio/blob/ed7e5a1705e58b8a3f689537412e26badf5846b9/manifests/charts/istiod-remote/files/gateway-injection-template.yaml#L192C11-L192C11

**Describe alternatives you've considered**
Copying the full altered Injection template as a new template, but this is not maintainable. 
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
does https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection address this?

**Comment by asayah** [comment]
closing this, the problem was relate to the mount, adding `emptyDir: null` fixes the issue 

```
sidecarInjectorWebhook:
  templates:
    spire: |
      spec:
        containers:
        - name: istio-proxy
          volumeMounts:
          - name: workload-socket
            mountPath: /run/secrets/workload-spiffe-uds
            readOnly: true
        volumes:
          - name: workload-socket
            csi:
              driver: "csi.spiffe.io"
              readOnly: true
    spire-gw: |
      spec:
        containers:
        - name: istio-proxy
          volumeMounts:
          - name: workload-socket
            mountPath: /run/secrets/workload-spiffe-uds
            readOnly: true
        volumes:
          - name: workload-socket
            emptyDir: null # <----------- This is important 
            csi:
              driver: "csi.spiffe.io"
              readOnly: true
        initContainers:
        - name: wait-for-spire-socket
          image: busybox:1.28
          volumeMounts:
            - name: workload-socket
              mountPath: /run/secrets/workload-spiffe-uds
              readOnly: true
          env:
            - name: CHECK_FILE
              value: /run/secrets/workload-spiffe-uds/socket
          command:
            - sh
            - "-c"
            - |-
              echo "$(date -Iseconds)" Waiting for: $${CHECK_FILE}
              while [[ ! -e $${CHECK_FILE} && ! -L $${CHECK_FILE} ]] ; do
                echo "$(date -Iseconds)" File does not exist: $${CHECK_FILE}
                sleep 15
              done
              ls -l $${CHECK_FILE}

```
