### ISSUE TITLE
Max request size per route

### ISSUE THREAD

**Issue by WesleyFreitas472** [istio/istio#48902]
**Describe the feature request**

Would be nice to have an away to set the max payload size for incoming requests on the routes defined inside the virtualservice.

**Describe alternatives you've considered**

I have a route defined as `/uploads` on my virtualservice that points to a service with 2 endpoints, `/uploads` and `/uploads/stream`. Each endpoint has its own max body size to the incoming requests handled by the application itself. In order to create these config on istio, avoiding my app to handle large file uploads, I created an envoyfilter applied on the gateway to handle max request size globally and another envoyfilter with a lua script to handle the limit for each endpoint. 

The problem with this approach is that if I need to apply the limit to a new endpoint Its necessary to create one more if section on the lua script filter and also I need to have two filters, a global and a more specific for each endpoint.

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  gateways:
    - istio-ingressgateway
  hosts:
    - "myhost.example.com"
  http:
    - match:
        - uri:
            prefix: /uploads
      route:
        - destination:
            host: myapp.default.svc.cluster.local
            port:
              number: 8080
      retries:
        attempts: 5
        perTryTimeout: 10s
        retryOn: >-
          gateway-error,connect-failure,refused-stream,5xx,deadline-exceeded,unavailable,cancelled
      timeout: 30s
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-size-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
            max_request_bytes: 32505856 # 31 MB.
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-size-limit
  namespace: default
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: myapp
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                if request_handle:headers():get(":path") == "/uploads" then
                  local totalSize = request_handle:body():length()
                  if totalSize > (21 * 1024 * 1024) then
                    request_handle:respond({
                          [":status"] = 413,
                          ["content-type"] = "application/json",
                        }, "{}"
                      )
                  end
                end
              
                if request_handle:headers():get(":path") == "/uploads/stream" then
                  local totalSize = request_handle:body():length()
                  if totalSize > (31 * 1024 * 1024) then
                    request_handle:respond({
                          [":status"] = 413,
                          ["content-type"] = "application/json",
                        }, "{}"
                      )
                  end
                end
              end
```

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Comment by howardjohn** [comment]
I have some concerns with ever providing this as an API in Istio. In order to limit body size we either need to buffer (as you are doing) or cut an in-progress request once it hits the limit (probably bad). Neither of these are behaviors that are going to be generally acceptable outside of niche cases I think, which are best served by extensibility mechanisms you are already using (lua, etc).

BTW: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/buffer_filter#per-route-configuration may be of use

**Comment by skarasev** [comment]
Managed to achieve desired result with the suggested buffer and setting limit on per route basis in EnvoyFilter
First you have to create a route and a match in VirtualService **and give them names**
```
spec:
  http:
    - name: myCoolRoute
      match:
        - method:
            exact: POST
          name: myCoolMatch
          uri:
            prefix: /foo/api/
```
Then you can reference that match by name in EnvoyFilter

```
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            route:
              name: myCoolRoute.myCoolMatch
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.buffer:
              '@type': >-
                type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
              buffer:
                max_request_bytes: 104857600
```
