### ISSUE TITLE
Envoy Buffer Per Route not being applied

### ISSUE THREAD

**Issue by MaggGomes** [istio/istio#48939]
*Description*:
>Hey! First of all, I am new to Istio/Envoyproxy, so the issue that I am describing here, may have been already mentioned, although I did not find anyghin related to the subject. So my sincere apologies if I am mistaken.

**What I am trying to achieve:**
I am trying to use Istio configured with an Envoy filter in order to have a global buffer, in order to filter requests bigger than `10 MB`. Moreover, I want that for some particular routes/endpoints (i.e. `/shipments`), the max request size is smaller than the global filter (i.e. `5 MB`).

**What I did:**
The following `yaml` describes the implementation of a global filter of `10 MB` using `envoy.extensions.filters.http.buffer.v3.Buffer`, as well as the implementation of a more specific filter of `5 MB` to the route `/shipments` using `envoy.extensions.filters.http.buffer.v3.Buffer`.

**What is not working:**
Although the global filter is working, the **buffer per route is not.** I already tried reading the documentation more carefully, but without success. 

I'm not sure the `yaml` is 100% correct, neither if this is the best way to implement this as I don't fully grasp Envoy's capabilities.
Any suggestion is welcomed

Thanks

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: global-buffer
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
            max_request_bytes: 104857606 # 10 MB.

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: buffer-per-route-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.buffer.BufferPerRoute
          match:
            prefix: "/shipments"
          typed_per_filter_config:
            envoy.filters.http.buffer:
              "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
              buffer:
                max_request_bytes: 5242880 # 5 MB.

**Comment by zengyuxing007** [comment]
Maybe vhost needs to be set and the route match should be written above.



```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: buffer-per-route-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            name: "xxxx" ## your vhost name, such as "*:80", you can find the name by envoy configdump
            route: 
                name: "yyyy"  ## the route config name       
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.buffer:
              "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
              value:
                 buffer:
                    max_request_bytes: 5242880 # 5 MB.
```
