### ISSUE TITLE
Support for mesh mTLS on PASSTHROUGH gateway ports

### ISSUE THREAD

**Issue by mikebryant** [istio/istio#48955]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

We'd like to route TLS outbound traffic through an egress Gateway, and be able to apply AuthorizationPolicies based on source principal / namespace etc

e.g.

```
client ->(TLS)-> envoy ->(TLS-over-mTLS)-> gateway ->(TLS)-> external host
```

**Describe alternatives you've considered**

- We can use `mode: PASSTHROUGH`, but this doesn't let us apply AuthorizationPolicy based on mTLS attributes
- We can change all clients to use HTTP instead of HTTPS - but this is complicated and very invasive, and challenging for things like modifying the upstream AWS client libraries etc

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

- Previously raised here with no resolution: https://github.com/istio/istio/issues/39210
- Documented as [not possible in Anthos docs](https://cloud.google.com/service-mesh/docs/security/egress-gateways-best-practices): `Additionally, it is not currently possible to use mTLS and passthrough together.`
- [An idea using tcp](https://gist.github.com/yangminzhu/2123c6614825aeadba38279110450b62) - but needs a different Gateway port per service

**Comment by mikebryant** [comment]
Feels like maybe we want a combination of these two bits: https://github.com/istio/istio/blob/8c8721de00578dd0cd5b2b610e4513c220d87ff9/pilot/pkg/networking/core/v1alpha3/gateway.go#L795-L812

`buildGatewayNetworkFiltersFromTLSRoutes` + `tlsContext:     buildGatewayListenerTLSContext(lb.push.Mesh, server, lb.node, istionetworking.TransportProtocolTCP),`?

Not really familiar with the internals though

**Comment by mikebryant** [comment]
I have achieved what I want (mostly) with the following:

```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default
  namespace: istio-egress
spec:
  selector:
    istio: gateway-egress
  servers:
  # HTTP traffic from service gets (m)TLS added on
  - port:
      number: 80
      name: https-port-for-tls-origination
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: ISTIO_MUTUAL
  # HTTPS traffic from service gets routed out
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
---
# https://github.com/istio/istio/issues/48955
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-tls-over-mtls
  namespace: istio-egress
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 443
        filterChain:
          filter:
            name: istio.stats
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.metadata_exchange
        typedConfig:
          '@type': type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
          protocol: istio-peer-exchange
  - applyTo: FILTER_CHAIN
    match:
      context: GATEWAY
      listener:
        portNumber: 443
    patch:
      operation: MERGE
      value:
        transportSocket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            commonTlsContext:
              alpnProtocols:
              - istio-peer-exchange
              - h2
              - http/1.1
              combinedValidationContext:
                defaultValidationContext: {}
                validationContextSdsSecretConfig:
                  name: ROOTCA
                  sdsConfig:
                    apiConfigSource:
                      apiType: GRPC
                      grpcServices:
                      - envoyGrpc:
                          clusterName: sds-grpc
                      setNodeOnFirstMessageOnly: true
                      transportApiVersion: V3
                    initialFetchTimeout: 0s
                    resourceApiVersion: V3
              tlsCertificateSdsSecretConfigs:
              - name: default
                sdsConfig:
                  apiConfigSource:
                    apiType: GRPC
                    grpcServices:
                    - envoyGrpc:
                        clusterName: sds-grpc
                    setNodeOnFirstMessageOnly: true
                    transportApiVersion: V3
                  initialFetchTimeout: 0s
                  resourceApiVersion: V3
            requireClientCertificate: true
  workloadSelector:
    labels:
      istio: gateway-egress
```

Basically took a dump of the listener config for tcp+mtls, and then shoehorning it into the passthrough config

Only weirdness is the logging now goes:
```
{"level":"debug","time":"2024-01-24T14:00:55.763278Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.763343Z","scope":"envoy rbac","msg":"enforced allowed, matched policy ns[istio-egress]-policy[cnn]-rule[0]","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:156","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.796605Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.796943Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.796983Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.799995Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.841821Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"level":"debug","time":"2024-01-24T14:00:55.842462Z","scope":"envoy rbac","msg":"checking connection: requestedServerName: edition.cnn.com, sourceIP: 10.52.161.17:49666, directRemoteIP: 10.52.161.17:49666,remoteIP: 10.52.161.17:49666, localAddress: 10.52.133.97:443, ssl: uriSanPeerCertificate: spiffe://sbx-mettle.co.uk/ns/sample/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:90","thread":56}
{"envoy":{"duration":92,"response_flags":"-","upstream_host":"151.101.3.5:443"},"network":{"bytes_written":2505476,"destination":{"ip":"10.52.133.97","port":443},"client":{"ip":"10.52.161.17","port":49666},"bytes_read":791},"@timestamp":"2024-01-24T14:00:55.751Z","http":{"useragent":null,"status_code":0,"x_forwarded_for":null,"url_details":{"path":null,"host":null},"method":null,"version":null}}
```

Something seems to be looping a lot, and I'm not sure what or how I managed that...

Would definitely still like it if we could get first-class support for this use-case though :)

**Comment by mikebryant** [comment]
> That (if I am thinking about it correctly) is probably intentional? mTLS and PASSTHROUGH don't mix/are mutually incompatible by design.
> 
> If you're using client-originated TLS, Istio has no real way to apply any policy against it, because it cannot attest to the validity of any source attributes - you can't securely enforce policy against assumptions, and with only client originated TLS that's pretty much all you have, so PASSTHROUGH or drop is all that we can securely do.

Mhm, that's fair - I was meaning to suggest it as a thing that honours the `tls` section of a VirtualService. It gets most of the config I want, except for the mTLS piece.

> That being said, not using PASSTHROUGH, and wrapping the client-originated TLS in Istio mTLS for the egress gateway to unencapsulate, should work via the egress gateway, agreed.

The main issue here I think is - with a `Gateway.spec.servers[].port.protocol: TLS`, and a `VirtualService.tls[]` section, if you have `tls.mode: ISTIO_MUTUAL` it ignores all of the `VirtualService.tls` section, but it maps them in `tls.mode: PASSTHROUGH`. Looking at the code I linked above - it doesn't check whether `protocol: TCP` is used, it just assumes TCP.

So one way this could be mapped in the API is saying that under the `TLS / ISTIO_MUTUAL` combination those `tls` routes should be configured, for use within the mTLS wrapper? That feels like unused space in the API

**Comment by howardjohn** [comment]
If what you want is `client ->(TLS)-> envoy ->(TLS-over-mTLS)-> gateway ->(TLS)-> external host`, then this isn't "passthrough" from Istio's POV.

You want to terminate the mTLS in the gateway. This is ISTIO_MUTUAL. 

I assume you then want to route based on the properties of the *inner* TLS stream? Istio cannot expose this in it's API, and envoy almost cannot do this. Technically it is possible by sending it back to itself (via https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/internal_listener or sending to 127.0.0.1), but its not something Istio will ever expose.

Instead, I would recommend putting whatever info you need into the mTLS layer. Presumably that is the SNI, which can be set in DestinationRule

**Comment by mikebryant** [comment]
> If what you want is `client ->(TLS)-> envoy ->(TLS-over-mTLS)-> gateway ->(TLS)-> external host`, then this isn't "passthrough" from Istio's POV.
> 
> You want to terminate the mTLS in the gateway. This is ISTIO_MUTUAL.

Yes, it's ISTIO_MUTUAL, in that it's:
```
ISTIO_MUTUAL: Secure connections from the downstream using mutual TLS by presenting server certificates for authentication. Compared to Mutual mode, this mode uses certificates, representing gateway workload identity, generated automatically by Istio for mTLS authentication. When this mode is used, all other fields in TLSOptions should be empty.
```

But I talk about PASSTHROUGH because I want this bit of the docs:
```
PASSTHROUGH: The SNI string presented by the client will be used as the match criterion in a VirtualService TLS route to determine the destination service from the service registry.
```

Currently if you have ISTIO_MUTUAL and you send inner tls through it.. I can't remember what the exact failure mode was, but it certainly didn't do anything useful with it, I think it just got dropped with some error

> 
> I assume you then want to route based on the properties of the _inner_ TLS stream? 

Yes
There's two bits of routing in play here:
- The client-side envoy, wants to route based on "Oh, this SNI is configured for external egress through our egress gateway, so I'll send it there" - this bit works fine, using the current api, and it wraps it in mtls too
- The gateway envoy, we would like to unwrap the mtls (and do AuthorizationPolicy etc, so we can restrict which clients internally can access that external endpoint), and then route based on VirtualService tls statements

> Istio cannot expose this in it's API

While I accept that this is currently the case - this is why I've raised this issue. I don't agree it's wholly impossible though. I've two suggestions:
- One is that ISTIO_MUTUAL, when it has a tls port defined in the Gateway and VirtualService tls listeners, applies the same rules as passthrough, instead of having no rules and dropping the traffic.
- Another would be, idk, ISTIO_MUTUAL_USE_TLS_SNI_ROUTING, if you wanted to be explicit about a new mode. 

> , and envoy almost cannot do this. Technically it is possible by sending it back to itself (via https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/internal_listener or sending to 127.0.0.1), but its not something Istio will ever expose.

It can - I've demonstrated the config above. This is live and working for us. (And I'll add the current set of config below, for a full example). The config generated by PASSTHROUGH works, when I inject the `istio-peer-exchange` bits that the ISTIO_MUTUAL config would generate.

> 
> Instead, I would recommend putting whatever info you need into the mTLS layer. Presumably that is the SNI, which can be set in DestinationRule

Do you have an example of this? I'm using DestinationRule to set SNI attributes, and trying to route on them, but with ISTIO_MUTUAL on the gateway it ignores all the tls listeners, so I have no way of routing the traffic based on the SNI.
...At least, that's my recollection - I don't believe I could get it working without the EnvoyFilter, but if you have a way I'd love to hear it :) 


So, here's our current working config:

```
# Set up ISTO_MUTUAL, along with the autogenerated SNI routes from PASSTHROUGH
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-tls-over-mtls-public
  namespace: istio-egress
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: istio.stats
        portNumber: 443
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.metadata_exchange
        typedConfig:
          '@type': type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
          protocol: istio-peer-exchange
  - applyTo: FILTER_CHAIN
    match:
      context: GATEWAY
      listener:
        portNumber: 443
    patch:
      operation: MERGE
      value:
        transportSocket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            commonTlsContext:
              alpnProtocols:
              - istio-peer-exchange
              - h2
              - http/1.1
              combinedValidationContext:
                defaultValidationContext: {}
                validationContextSdsSecretConfig:
                  name: ROOTCA
                  sdsConfig:
                    apiConfigSource:
                      apiType: GRPC
                      grpcServices:
                      - envoyGrpc:
                          clusterName: sds-grpc
                      setNodeOnFirstMessageOnly: true
                      transportApiVersion: V3
                    initialFetchTimeout: 0s
                    resourceApiVersion: V3
              tlsCertificateSdsSecretConfigs:
              - name: default
                sdsConfig:
                  apiConfigSource:
                    apiType: GRPC
                    grpcServices:
                    - envoyGrpc:
                        clusterName: sds-grpc
                    setNodeOnFirstMessageOnly: true
                    transportApiVersion: V3
                  initialFetchTimeout: 0s
                  resourceApiVersion: V3
            requireClientCertificate: true
  workloadSelector:
    labels:
      app.kubernetes.io/instance: istio-gateway-egress-public
```

```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: vpn
  namespace: istio-egress
spec:
  selector:
    app.kubernetes.io/instance: istio-gateway-egress-vpn
  servers:
  - hosts:
    - '*'
    port:
      name: https-port-for-tls-origination
      number: 80
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
  - hosts:
    - '*'
    port:
      name: tls
      number: 443
      protocol: TLS
    tls:
      # Ideally this would be ISTIO_MUTUAL, and the EnvoyFilter wouldn't exist
      mode: PASSTHROUGH
---
# Set up subset for mtls-wrapped-tls
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: example-egress-gateway
  namespace: istio-egress
spec:
  host: istio-gateway-egress-vpn.istio-egress.svc.cluster.local
  subsets:
  - name: example-egress-https
    trafficPolicy:
      outlierDetection:
        consecutive5xxErrors: 1
      tls:
        mode: ISTIO_MUTUAL
        sni: example.com-https
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-egress
  namespace: istio-egress
spec:
  hosts:
  - example.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-egress
  namespace: istio-egress
spec:
  gateways:
  - istio-egress/vpn
  - mesh
  hosts:
  - example.com
  - example.com-https
  tls:
  # For mesh envoys, read sni, and wrap it in mtls sending to egress gateway
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - example.com
    route:
    - destination:
        host: istio-gateway-egress-vpn.istio-egress.svc.cluster.local
        port:
          number: 443
        subset: example-egress-https
  # For egress gateway envoy, route based off incoming mtls sni
  # This is the bit that seems not to work for me, if I use ISTIO_MUTUAL
  - match:
    - gateways:
      - istio-egress/vpn
      port: 443
      sniHosts:
      - example.com-https
    route:
    - destination:
        host: example.com
        port:
          number: 443
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: example-egress-ext-svc
  namespace: istio-egress
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/test/sa/some-service
    when:
    - key: connection.sni
      values:
      - example.com
      - example.com-https
  selector:
    matchLabels:
      app.kubernetes.io/instance: istio-gateway-egress-vpn

# Note: I did have to do some find/replace to remove confidential commercial relationships here, so hopefully this is still valid..
```

**Comment by howardjohn** [comment]
Sorry I was getting confused by the multiple steps here. I think what you want is simply "Terminate TLS and route based on SNI" which is not really related to PASSTHROUGH.

**Comment by howardjohn** [comment]
```
Gateway:
 servers:
 - hostname: host1
   tls: terminate
 - hostname: host2
   tls: terminate

VirtualService:
  host: host1
  gateway: gw
  tcp: 
    match: {} # None
    backend: host1

VirtualService:
  host: host2
  gateway: gw
  tcp: 
    match: {} # None
    backend: host2
```

is what you need

**Comment by mikebryant** [comment]
I've sketched out where I think there's a gap in the api here: https://github.com/istio/istio/pull/52066

Currently if you supply a port protocol of TLS, and tls mode ISTIO_MUTUAL, it's [treated the same](https://github.com/istio/istio/blob/8c8721de00578dd0cd5b2b610e4513c220d87ff9/pilot/pkg/networking/core/v1alpha3/gateway.go#L795-L796) as if you'd specified a port protocol of TCP.

What I'd like is if you specify a port protocol of TLS then the bits listed under [Port](https://istio.io/latest/docs/reference/config/networking/gateway/#Port) here come into play, namely `TLS can be either used to ... or to route traffic based on SNI header to the destination without terminating the TLS connection.`

**Comment by mikebryant** [comment]
> tls: terminate

Which mode do you mean out of the ones listed here? https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-TLSmode

`ISTIO_MUTUAL`?

**Comment by mikebryant** [comment]
That was interesting - just been playing with that concept.

I've got it working as you suggested, thank you!

I found it quite surprising that these two things behave so differently (And I'd never considered trying that):
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: ISTIO_MUTUAL
  - port:
      number: 443
      name: tls2
      protocol: TLS
    hosts:
    - example.com
    tls:
      mode: ISTIO_MUTUAL
```
vs 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    - example.com
    tls:
      mode: ISTIO_MUTUAL
```

One thing that is somewhat tricky here is that in exposing this to our users we can't use individual objects for different hosts, like we can with VirtualServices - the central Gateway object needs to be updated with one server section per host, can't use `hosts: ["*"]`. But I guess we can do some magic with Kyverno to generate an appropriate Gateway

For anyone else finding this later - this was the config I've just been testing locally:

I was able to route both hosts through the egress gateway, with tls being terminated at the remote server - and AuthorizationPolicy works, so cnn was allowed from sleep and example wasn't.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: ISTIO_MUTUAL
  - port:
      number: 443
      name: tls2
      protocol: TLS
    hosts:
    - example.com
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 443
  # - match:
  #   - gateways:
  #     - istio-egressgateway
  #     port: 443
  #     sniHosts:
  #     - edition.cnn.com
  #   route:
  #   - destination:
  #       host: edition.cnn.com
  #       port:
  #         number: 443
  #     weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-example
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: example
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example
spec:
  hosts:
  - example.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-example-through-egress-gateway
spec:
  hosts:
  - example.com
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - route:
    - destination:
        host: example.com
        port:
          number: 443
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - example.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: example
        port:
          number: 443
  # - match:
  #   - gateways:
  #     - istio-egressgateway
  #     port: 443
  #     sniHosts:
  #     - edition.cnn.com
  #   route:
  #   - destination:
  #       host: edition.cnn.com
  #       port:
  #         number: 443
  #     weight: 100


---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
spec: {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: cnn
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/sleep"]
    when:
    - key: connection.sni
      values:
      - edition.cnn.com
  selector:
    matchLabels:
      istio: egressgateway

```

@howardjohn Thank you again for taking the time to work through this with me

**Comment by mikebryant** [comment]
I'm thinking now I might try to raise a PR with another section after https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic, something like how to do `Egress gateway for HTTPS traffic with Authorization`?

That was the real sticking point for me with the guides - they all use PASSTHROUGH for this use-case, which doesn't work with auth. And when I tried to set up my Gateway with ISTIO_MUTUAL it wasn't working because I had things like `hosts: ["*"]` - because I wasn't wanting to specify all the hosts up front.

**Comment by shanmugara** [comment]
@mikebryant This is interesting, I am trying solve a similar issue. Just curious, why is this section commented out?
# - match:
  #   - gateways:
  #     - istio-egressgateway
  #     port: 443
  #     sniHosts:
  #     - edition.cnn.com
  #   route:
  #   - destination:
  #       host: edition.cnn.com
  #       port:
  #         number: 443
  #     weight: 100
  
  How does egress route the traffic after the traffic is in egressgateway ?

**Comment by mikebryant** [comment]
> Just curious, why is this section commented out?

Oh, that was from the previous iteration where I was trying to use a tls match instead of a tcp one

> How does egress route the traffic after the traffic is in egressgateway ?

That's this section of the VirtualService:
```
  tcp:
  - route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
```

> Would this work in a scenario where egress gateway is sending the traffic through an upstream squid proxy?

No idea, not something I've tried
