### ISSUE TITLE
Adding env var using secretKeyRef in IstioOperator ingressGateway not working as expected

### ISSUE THREAD

**Issue by blaivs** [istio/istio#48961]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

I've been trying to add a env variable from a secret to an ingressGateway using IstioOperator. This is the syntax supported:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
            - name: MY_ENV_VAR_FROM_SECRET
              valueFrom:
                secretKeyRef:
                  key: value
                  localObjectReference:
                    name: my-secret
```
as specified [here](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#SecretKeySelector). The generated deployment contains the same spec which is not valid in my k8s version (1.24) due to `localObjectReference` field:

```Deployment.spec.template.spec.containers[0].env[0].valueFrom.secretKeyRef): unknown field "localObjectReference" in io.k8s.api.core.v1.SecretKeySelector```

Not sure if the intention was to transform the localObjectReference field into `secretKeyRef` type but right now is not happening, so maybe marshalling can be fixed or add support for standard:
```yaml
           - name: MY_ENV_VAR_FROM_SECRET
              valueFrom:
                secretKeyRef:
                  key: value
                  name: my-secret
```

### Version

```Text
$ istioctl version
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (5 proxies)
```

**Comment by hanxiaop** [comment]
Maybe something like:
```
values:
    gateways:
      istio-ingressgateway:
        env:
          MY_ENV_VAR_FROM_SECRET:
            valueFrom:
              secretKeyRef:
                key: value
                name: my-secret
```

**Comment by blaivs** [comment]
Hey @hanxiaop, yeah, sorry wasn't clear on the description, If i use 

```yaml
env:
  - name: MYSECRET
     valueFrom:
        secretKeyRef:
          key: value
          name: my-secret
```
I get the following error, as type doesn't support name:
`Error: error unmarshaling JSON: while decoding JSON: unknown field "name" in istio.operator.v1alpha1.SecretKeySelector:`
