### ISSUE TITLE
External Authorization outside of the mesh not work (envoyExtAuthzGrpc)

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#48983]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I used internal External Authorization, it works excellent, both for restful and grpc.
However, it does not work when set External Authorization outside of the mesh (envoyExtAuthzGrpc)
![image](https://github.com/istio/istio/assets/17720035/062ee82a-0c2f-4712-a8e6-b318b78ce5dc)

Here is configuration in istio mesh configmap
```
$ k get cm -n istio-system istio -oyaml
apiVersion: v1
data:
  mesh: |-
    ... ...
    extensionProviders:
    - name: "sample-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "token-validation-auth-itg.api....com"
        port: "443"
```

Here is serviceEntry definition. 
```
[Try 1: protocol: GRPC]
$ k get serviceentries -n default     external-authz-grpc  -oyaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-authz-grpc
  namespace: default
spec:
  hosts:
  - token-validation-auth-itg.api...com
  location: MESH_EXTERNAL
  ports:
  - name: grpc
    number: 443
    protocol: GRPC
  resolution: DNS

[Try 2: protocol: HTTPS]
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-authz-grpc
spec:
  hosts:
  - token-validation-auth-itg.api...com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

Authorization Policy Configure
```
$ k get authorizationpolicies.security.istio.io -n onecloud-dev   try01  -oyaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: try01
  namespace: onecloud-dev
spec:
  action: CUSTOM
  provider:
    name: sample-ext-authz-grpc
  rules:
  - to:
    - operation:
        paths:
        - /try01/version
  selector:
    matchLabels:
      app: try01
```

Test result:
Always return 403 even for correct token. I looked into cluster 2 service log, found:
The check request from cluster 1 had NEVER arrived  at all.

```
$  curl https://try01-onecloudsol-dev.api...com/try01/version -H 'Authorization: Bearer eyJ... .._HfBsA' -v
*   Trying 18.246.204.34:443...
* TCP_NODELAY set
* Connected to try01-onecloudsol-dev.api...com (...) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
,,,
,,,
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x564d797da240)
> GET /try01/version HTTP/2
> Host: ,,,,
> user-agent: curl/7.68.0
> accept: */*
> authorization: Bearer eyJ,,,,,,HfBsA
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 403
< date: Thu, 25 Jan 2024 06:46:16 GMT
< content-length: 0
< x-oc-traceid: 0f056eabfe4d7e2b03778f39c5aef3c2

```

From tracing, you can find it may return 14 unavailalbe sometimes. [For grpc protocol set in serviceentry]
 

From Tracing, you can find it may timeout  sometimes  [For grpc/ https protocol set in serviceentry]
 

Note that I set similar external authz in cluster2, for validation the check of cluster 2, it works well  
```
    extensionProviders:
    - name: "sample-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "token-validation.auth-itg.svc.cluster.local"
        port: "3000"
```
 
So, the problem should be configure in cluster 1.

### Version

```Text
Istio version: 1.19.3
K8s version: 1.27
AWS EKS
```

### Additional Information

$ kubectl exec -it $ISTIOD -n istio-system -- curl localhost:8080/debug/registryz | jq '.[] | .hostname' | grep hponecloud.io
"try01-onecloud-dev.api...com"
"token-validation-auth-itg.api...com"

The network between two clusters should work,  like below: in cluster 1 nginx container, call cluster 2 api successfully.
cluster1$ k exec -n test nginx --    curl https://golang-app-onecloud-dev.api..com/golang-app/health
 {"status":"healthy"}

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by johnzheng1975** [comment]
[grpc_protocal.log](https://github.com/istio/istio/files/14048066/grpc_protocal.log)
[https_protocal.log](https://github.com/istio/istio/files/14048069/https_protocal.log)

**Comment by johnzheng1975** [comment]
From https://github.com/istio/istio/issues/33595, seems istio does not support this? 
Pls check, thanks. @yangminzhu

**Comment by howardjohn** [comment]
Looks like the backend expects TLS and you never configured it? You need a Destinationrule

**Comment by johnzheng1975** [comment]
Hi @howardjohn 
Thanks for your answer.  Sorry I did get well.
For the Destinationrule you mentioned, do you means  [doc](https://istio.io/latest/docs/reference/config/networking/service-entry/)
![image](https://github.com/istio/istio/assets/17720035/5c951f59-7b49-4551-a177-466df365899f)
If yes, can I know how can configure it since I have no certificate provided? It will be great if you provide an example. Thanks..

Also, can I know why backend expects TLS?
If I configure service entry httpbin.org with https, I always call it successfully without destinationrule, right?
```
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: external-httpbin
    namespace: istio-system
  spec:
    hosts:
    - httpbin.org
    location: MESH_EXTERNAL
    ports:
    - name: https
      number: 443
      protocol: HTTPS
    resolution: DNS


$ k exec -ti -n onecloudsol-dev nginx2 --    curl  https://httpbin.org/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.88.1",
    "X-Amzn-Trace-Id": "Root=1-65b3bff2-059e5894666f12f817db187e"
  },
  "origin": "54.201.90.109",
  "url": "https://httpbin.org/get"
}


-- istio-proxy log
{"user_agent":null,"requested_server_name":"httpbin.org","x_b3_traceid":null,"downstream_remote_address":"10.212.148.127:35412","oc_internal_act_sa":null,"upstream_host":"52.73.4.39:443","grpc_status_number":null,"route_name":null,"x_forwarded_for":null,"oc_basic_client_id":null,"upstream_cluster":"outbound|443||httpbin.org","response_code":0,"bytes_sent":6024,"start_time":"2024-01-26T14:21:38.686Z","method":null,"authority":null,"connection_termination_details":null,"upstream_service_time":null,"bytes_received":844,"oc_internal_tenants":null,"duration":795,"request_id":null,"oc_path_client_id":null,"oc_token_client_id":null,"oc_token_sa":null,"downstream_local_address":"34.196.123.121:443","response_code_details":null,"response_flags":"-","path":null,"protocol":null,"upstream_transport_failure_reason":null,"upstream_local_address":"10.212.148.127:39024"}

```

Note that both cluster1 and cluster2 are installed with istio STRICT MTLS.
but not installed with multiple clusters.

Appreciate your support!

**Comment by johnzheng1975** [comment]
If I configure with 
![image](https://github.com/istio/istio/assets/17720035/4cda019a-772a-4c40-a2d4-0b75bd46fdee)
I can find it in cluster 2 AWS ALB Logs although it did not arrive ingress gateway.
```
https 2024-01-26T14:12:14.254582Z app/non-prod-apigee/7e9922376919b5c7 54.201.90.109:11456 - -1 -1 -1 400 - 468 370 "POST http://outbound_.443_._.token-validation-auth-itg.api.non-prod-uw2.hponecloud.io:443/envoy.service.auth.v3.Authorization/Check HTTP/1.1" "-" - - - "-" "-" "-" - 
```

**Comment by johnzheng1975** [comment]
[grpc_protocal_config_dump.txt](https://github.com/istio/istio/files/14067173/grpc_protocal_config_dump.txt)
[https_protocal_config_dump.txt](https://github.com/istio/istio/files/14067178/https_protocal_config_dump.txt)

**Comment by johnzheng1975** [comment]
@howardjohn   @yangminzhu

**Comment by howardjohn** [comment]
If its TLS you need a DestinationRule with mode SIMPLE. The `protocol: HTTPS` does **not** mean TLS is added

**Comment by johnzheng1975** [comment]
Hi @howardjohn 
I tried below two, still not work.
```	
# type 1
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: allow-publicdomain-nomtls
spec:
  host: "token-validation-auth-itg.api.non-prod-uw2.hponecloud.io"
  trafficPolicy:
    tls:
      mode: SIMPLE

# type 2
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: allow-publicdomain-nomtls
  namespace: istio-system
spec:
  host: token-validation-auth-itg.api.non-prod-uw2.hponecloud.io
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: DISABLE
```

**Comment by johnzheng1975** [comment]
Thanks @howardjohn , with your suggestion:  tls mode simple [type 1], seems made progress.
The logs like below:  grpcs, http2
```
grpcs 2024-01-26T16:46:20.717958Z app/non-prod-apigee/7e9922376919b5c7 54.201.90.109:32319 10.200.131.243:30443 0.009 0.001 0.000 200 200 3111 72 "POST https://outbound_.443_._.token-validation-auth-itg.api.non-prod-uw2.hponecloud.io:443/envoy.service.auth.v3.Authorization/Check HTTP/2.0" "-" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:789619356883:targetgroup/grpc-non-prod-uw2-blue-apigee/f1a10e561046e855 "Root=1-65b3e1dc-521755036918274959f247c9" "-" "session-reused" 1 2024-01-26T16:46:20.707000Z "waf,forward" "-" "-" "10.200.131.243:30443" "200" "-" "-"
```

**Comment by johnzheng1975** [comment]
I tried to add this specific domain into cluster 2 virtual service, but raise error.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: token-validation-apigee
  namespace: auth-itg
spec:
  gateways:
  - istio-system/apigee-gateway
  hosts:
  - token-validation-auth-itg.api.non-prod-uw2.hponecloud.io
  - token-validation-auth-itg.api.non-prod-us.hponecloud.io
  - outbound_.443_._.token-validation-auth-itg.api.non-prod-uw2.hponecloud.io
  http:
  - match:
    - uri:
        regex: ^/tokenValidationServiceAPI/.+$
   ... ...
```

Name: "token-validation-apigee", Namespace: "auth-itg"
for: "token-val-vs.yaml": error when patching "token-val-vs.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: domain name "outbound_.443_._.token-validation-auth-itg.api.non-prod-uw2.hponecloud.io" invalid (label "outbound_" invalid)

Any suggestions? ~_~
Thanks!

**Comment by johnzheng1975** [comment]
Ok, I use below envoyfilter to change domain, now all works.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-changedomain-pre-handle
  namespace: istio-system
spec:
  priority: -200
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          defaultSourceCode:
            inlineString: |
              function envoy_on_request(request_handle)
                request_handle:logDebug("******* Enter V0.1 Onecloud ratelimit pre-handle envoy_on_request ... ... ")
                headers = request_handle:headers()
                h_authority = ""
                h_authority = headers:get(":authority")
                if h_authority == "outbound_.443_._.token-validation-auth-itg.api.non-prod-uw2.hponecloud.io" then
                  request_handle:headers():replace(":authority","token-validation-auth-itg.api.non-prod-uw2.hponecloud.io")
                end
              end
```

**Comment by johnzheng1975** [comment]
Here is summary:
For External Authorization Outside of the Mesh (envoyExtAuthzGrpc), it does works as below.
![image](https://github.com/istio/istio/assets/17720035/ec78133b-bac3-459c-9aba-878c65031372)

Let us say, there two clusters, cluster 1 need set external authorization, but authz server is in cluster2.
Both cluster1 and cluster2 are MTLS enabled. 
Istio multiple clusters are NOT necessary.

Step 1. Change istio mesh configmap.
```
$ k get cm -n istio-system istio -oyaml
apiVersion: v1
data:
  mesh: |-
    ... ...
    extensionProviders:
    - name: "sample-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "token-validation-auth-itg.api...com"
        port: "443"
```

Step 2. Add serviceentry in cluster 1.
```
$ k get se external-authz-grpc -n istio-system -oyaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-authz-grpc
  namespace: istio-system
spec:
  hosts:
  - token-validation-auth-itg.api.non-prod-uw2.hponecloud.io
  location: MESH_EXTERNAL
  ports:
  - name: grpc
    number: 443
    protocol: GRPC
  resolution: DNS
```

Step 3.  Add DestinationRule
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: allow-publicdomain-nomtls
spec:
  host: "token-validation-auth-itg.api.non-prod-uw2.hponecloud.io"
  trafficPolicy:
    tls:
      mode: SIMPLE
```

Step 4. Add custom authorization Policy
```
$ k get authorizationpolicies.security.istio.io -n onecloudsol-dev try01 -oyaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: try01
  namespace: onecloudsol-dev
spec:
  action: CUSTOM
  provider:
    name: sample-ext-authz-grpc
  rules:
  - to:
    - operation:
        paths:
        - /try01/version
  selector:
    matchLabels:
      app: try01
```

Step 5 Need add an envoyfilter in cluster2, to remove domain prefix 'outbound_.443_._.'
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-changedomain-pre-handle
  namespace: istio-system
spec:
  priority: -200
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          defaultSourceCode:
            inlineString: |
              function envoy_on_request(request_handle)
                request_handle:logDebug("******* Enter V0.1 Onecloud ratelimit pre-handle envoy_on_request ... ... ")
                headers = request_handle:headers()
                h_authority = ""
                h_authority = headers:get(":authority")
                if h_authority == "outbound_.443_._.token-validation-auth-itg.api...com" then
                  request_handle:headers():replace(":authority","token-validation-auth-itg.api...com")
                end
              end
```
