### ISSUE TITLE
East-west gateway without external IP

### ISSUE THREAD

**Issue by fizos** [istio/istio#49045]
I am using Istio 1.17.3 and I want to deploy a multicluster mesh where each cluster is in a different network. I am following the [Install Multi-Primary on different networks 29](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/) guide and my environment doesn’t support external load balancers. So when I install an east-west gateway it doesn’t get an external IP and I cannot get any cross-cluster traffic.

Is there any workaround for this (e.g. accessing the gateway using a nodePort)?

**Comment by stevenctl** [comment]
Yes, we do support NodePort for multi-network. 

The docs have you use the gen-eastwest-gateway.sh. After generating the YAML using that command, you'd need to edit one section

```
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
        type: NodePort # add this
```

**Comment by fizos** [comment]
very appreciate for you help 😄 

I currently need to form a large service mesh cluster using a multi-primary, multi-network mode with three clusters. Is it necessary for each cluster to configure the access credentials of the other two clusters' API-Server? Does Istio support this configuration ? Do East-West gateways also need to be configured for mutual communication between each pair? 
Is there a best practice in the community for three clusters with multi-primary and multi-network?

**Comment by stevenctl** [comment]
Istio's multi-cluster design currently requires API server access to be shared with each primary cluster. 

[Primary-Remote](https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/) would only require supplying the remote clusters' credentials to each primary (you could have 1 primary, 2 remote). 

Another option would be more manual: creating `WorkloadEntry` resources and `Gateway` resources by hand that represent resources that exist in other clusters. An example can be found in this [integration test](https://github.com/istio/istio/blob/master/tests/integration/pilot/workloadentry_test.go). A `Gateway` represents a remote eastwest gateway, we say the address `1.2.3.4:15443` can be used to reach any endpoint on `network-foo`.  Then we create a `WorkloadEntry` on `network-foo` with no address. A service selecting that `WorkloadEntry` would go through the gateway. 

The caveats being:

1. You don't get automated updates if you have no workloads behind that "virtual" workloadentry.
2. You don't get automated updates for the Gateway resource
3. The WorkloadEntry may not have the correct weight for the # of workloads in the remote network. 

TL;DR we have APIs that can be used to configure some cross-network traffic without sharing API server credentials, but you lose most of the automation that Istio provides.

**Comment by fizos** [comment]
> Yes, we do support NodePort for multi-network.
> 
> The docs have you use the gen-eastwest-gateway.sh. After generating the YAML using that command, you'd need to edit one section
> 
> ```
>   values:
>     gateways:
>       istio-ingressgateway:
>         injectionTemplate: gateway
>         type: NodePort # add this
> ```
> 
> The multi-cluster service discovery machinery is setup to handle node port.

I have added the type NodePort in eastwestgateway istiooperator，and exposed the gateway with Gateway CRD.
But it seems that the traffic from the west cluster did not find the eastwestgateway in east cluster by nodeport
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
spec:
  revision: ""
  profile: empty
  tag: 1.17.3
  components:
    ingressGateways:
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: east-network
      enabled: true
      k8s:
        env:
        # traffic through this gateway should be routed inside the network
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: east-network
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tls
            port: 15443
            targetPort: 15443
          - name: tls-istiod
            port: 15012
            targetPort: 15012
          - name: tls-webhook
            port: 15017
            targetPort: 15017
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
        type: NodePort
    global:
      network: east-network
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
    hosts:
    - "*.local"
```
Besides the eastwestgateway generated by gen-eastwest-gateway.sh did not contain mesh-id info, Is this right?
