### ISSUE TITLE
Inconsistent Performance of Istio Ingress Gateway in PASSTHROUGH Mode

### ISSUE THREAD

**Issue by SiN11l** [istio/istio#49059]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello,

We have three microservices:
- auth-service-ui: an HTTPS web interface (NodeJS)
- inspection-service-ui: an HTTPS web interface (NodeJS)
- gate-service-api: an HTTPS API server with proxy functionality (.NET)

We encountered an issue where, when the gate-service-api operates on port 443 in PASSTHROUGH mode along with other services like inspection-service-ui and auth-service-ui, the traffic redirection does not function correctly. Requests intended for inspection-service-ui are mistakenly routed to gate-service-api.

Occasionally, everything works as expected until a certain point, but after the first malfunction, all requests, even those meant for services like inspection-service-ui, are redirected to gate-service-api (as can be seen in the screenshots). For instance, /static/v1.154.18.1538.js should not be sent to gate-service-api (though the issue may occur with any other JavaScript file).
![1](https://github.com/istio/istio/assets/113104747/f8274f3f-7816-44d1-955a-97297d6ff7c0)
![2](https://github.com/istio/istio/assets/113104747/ad9504c0-71fe-47bc-b28a-c0d26f6bea12)

When gate-service-api is moved to a different port - 7443, everything functions correctly. The services auth-service-ui and inspection-service-ui on port 443 operate without issues when gate-service-api is not present.

Tests Conducted:
- PASSTHROUGH/inspection-service-ui:443 + PASSTHROUGH/gate-service-api:443 = fails.
- PASSTHROUGH/inspection-service-ui:443 + SIMPLE/gate-service-api:443 = fails.
- SIMPLE/inspection-service-ui:443 + PASSTHROUGH/gate-service-api:443 = fails.
- SIMPLE/inspection-service-ui:443 + SIMPLE/gate-service-api:443 = works.
- PASSTHROUGH/inspection-service-ui:443 + PASSTHROUGH/gate-service-api:7443 = works.

It seems that adding a proxy service using PASSTHROUGH mode on the same port as other services causes everything to malfunction.
No suspicious activity was found in the istiod logs.

Has anyone encountered a similar problem? Any thoughts?

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*.local'
  - port:
      number: 443
      name: https-passthrough
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - 'auth-service-ui.qa.rrt'
    - 'inspection-service-ui.qa.rrt'
    - 'gateservice.qa.rrt'

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-service-ui
  namespace: qa
spec:
  hosts:
  - 'auth-service-ui.qa.rrt'
  gateways:
  - istio-system/main
  tls:
  - match:
    - sniHosts:
        - 'auth-service-ui.qa.rrt'
    route:
      - destination:
          host: auth-service-ui
          port:
            number: 443

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inspection-ui
  namespace: qa
spec:
  hosts:
  - 'inspection-service-ui.qa.rrt'
  gateways:
  - istio-system/main
  tls:
  - match:
    - sniHosts:
        - 'inspection-service-ui.qa.rrt'
    route:
      - destination:
          host: inspection-service-ui
          port:
            number: 443

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateservice
  namespace: qa
spec:
  hosts:
  - 'gateservice.qa.rrt'
  gateways:
  - istio-system/main
  tls:
  - match:
    - sniHosts:
        - 'gateservice.qa.rrt'
    route:
      - destination:
          host: gate-service-api
          port:
            number: 443
```

### Version

```Text
./istioctl version
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (71 proxies)

kubectl version --short
Client Version: v1.26.5
Kustomize Version: v4.5.7
Server Version: v1.26.5

helm version --short
v3.12.0+gc9f554d
```
