### ISSUE TITLE
Istio Gateway does not accept subdomain certificates.

### ISSUE THREAD

**Issue by todor-dobrev-kasha** [istio/istio#49091]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have ISTIO setup in Digital Ocean DOKS
The issue is that I have the cert-manager installed and configured with clusterissuer to generate certificates using DNS Cloudflare.
All generated certificates are valid.
However, when I put a subdomain certificate to the Istio Gateway it does not terminate it. 
For instance, if I create a gateway/virtual service like

```
resource "kubectl_manifest" "gateway_vault" {
  depends_on = [helm_release.istio-ingressgateway, kubernetes_namespace.vault]
  yaml_body  = <<YAML
apiVersion: "networking.istio.io/v1alpha3"
kind: "Gateway"
metadata:
  name: "vault-gateway"
  namespace: "vault"
spec:
  selector:
    istio: "ingressgateway"
  servers:
    - hosts:
        - "${local.vault_hostname}"
      port:
        name: "vault"
        number: 443
        protocol: "HTTPS"
      tls:
        mode: "SIMPLE"
        credentialName: "vault-gateway-certs"
YAML
}

resource "kubectl_manifest" "vs_vault" {
  depends_on = [kubernetes_namespace.vault, kubectl_manifest.gateway_vault]
  yaml_body  = <<YAML
apiVersion: "networking.istio.io/v1alpha3"
kind: "VirtualService"
metadata:
  name: "vault-virtual-service"
  namespace: "vault"
spec:
  gateways:
    - "vault-gateway"
  hosts:
    - "${local.vault_hostname}"
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: "vault-system.vault.svc.cluster.local"
            port:
              number: 8200
YAML
}
```
And I try to access 
${local.vault_hostname} (which is for instance vault.xxxx.xxxx )I get that there is no certificate
however the certificate when checked in sslshopper it says that it is valid and issued for the correct domain vault.xxxx.xxxx/ *.vault.xxxx.xxxx but when I check https://vault.xxxx.xxxx there is no certificate

However, if I use a wild-card certificate for the entire domain in the gateway like *.xxxx.xxxx/xxxx.xxxx it does gets terminated.

The interesting part is that I have also teleport installed on the cluster that generates and terminates the tls using the same cluster-issuer and lets encrypt and I have the gateway with tls passthrough configured for it and it does get a valid certificate when I access tp.xxxx.xxxx and everything works.

So my conclusion, all the certificates issued by cert-manager are valid. It is that the Istio Gateway is not terminating the subdomain certificates only the domain certificate

Any idea why this is happening. 

Also strange thing is that if I have two entirely different gateways(names, namespaces, port names) using the same domain wild card certificate the routing to the respective virtual services is corrupted.... and looks like only one gateway takes affect...

I have another project in AWS that uses ROUTE53 DNS and I haven't experienced such issue...
Cannot find anything in the logs if you would help me with some debugs will be highly appreciated.

### Version

```Text
the latest version is installed via Helm.
```
