### ISSUE TITLE
Matching priority of Virtual Service

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49112]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The matching priority of virtual service is inconsistent. When I `curl -H"header2: value2" -H"Host: www.example.com" http://1.1.1.1:8080`, the traffic is routed to `ratings` rather than `productpage`. Previous discussions (#10464 #10485) have reached some conclusions about the priority, such as VS name order and creation timestamp. However, in this case, virtual service `example.com` has smaller name order and creation timestamp than `vs-1`, but the traffic is routed to vs-1. When I replace `hosts` of `example.com` to `www.example.com`, the result shows traffic is routed to `example.com`. Is there a clear specification on virtual service matching priorities? 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example.com
spec:
  hosts:
  - '*.example.com'
  http:
  - match:
    - headers:
        header2:
          exact: value2
    route:
    - destination:
        host: productpage.default.svc.cluster.local
        subset: v2
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
  - www.example.com
  http:
  - match:
    - {
      }
    route:
    - destination:
        host: ratings.default.svc.cluster.local
        port:
          number: 9090
```

### Version

```Text
client version: 1.21-alpha.e6a76f0f5e5aa801a5204e8ae7f2dc42df7546f1
control plane version: 1.21-alpha.74298d46d92d3cfc1ddbcd0536df74ca580281b1
data plane version: 1.21-alpha.74298d46d92d3cfc1ddbcd0536df74ca580281b1 (7 proxies)

Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```
