### ISSUE TITLE
HTTP routing is not based on Host in Ambient

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49149]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In istio-sidecar, HTTP traffic is routed based on its Host/Authority header. But in Ambient, I found that the same configuration leads to different behaviors comparing to istio-sidecar. When I run `curl -vv -H "Host:ratings.default.svc.cluster.local:8080" http://1.1.1.1:8080` in istio-sidecar, `ratings` pods successfully received traffic and responded with 200 OK. On the contrary in Ambient, the `ratings` pods could not receive requests and `curl` gets 5XX error.

```
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 8080
    targetPort: 9080
    name: http-0
---
apiVersion: v1
kind: Pod
metadata:
  name: ratings-v2
  labels:
    version: v2
    app: ratings
---
apiVersion: v1
kind: Pod
metadata:
  name: ratings-v1
  labels:
    version: v1
    app: ratings

```

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (5 proxies)
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by howardjohn** [comment]
This is an intentional change in ambient to better align with Kubernetes

**Comment by zengyuxing007** [comment]
> ### Is this the right place to submit this?
> * [x]  This is not a security vulnerability or a crashing bug
> * [x]  This is not a question about how to use Istio
> 
> ### Bug Description
> In istio-sidecar, HTTP traffic is routed based on its Host/Authority header. But in Ambient, I found that the same configuration leads to different behaviors comparing to istio-sidecar. When I run `curl -vv -H "Host:ratings.default.svc.cluster.local:8080" http://1.1.1.1:8080` in istio-sidecar, `ratings` pods successfully received traffic and responded with 200 OK. On the contrary in Ambient, the `ratings` pods could not receive requests and `curl` gets 5XX error.
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   name: ratings
> spec:
>   selector:
>     app: ratings
>   ports:
>   - port: 8080
>     targetPort: 9080
>     name: http-0
> ---
> apiVersion: v1
> kind: Pod
> metadata:
>   name: ratings-v2
>   labels:
>     version: v2
>     app: ratings
> ---
> apiVersion: v1
> kind: Pod
> metadata:
>   name: ratings-v1
>   labels:
>     version: v1
>     app: ratings
> ```
> 
> ### Version
> ```
> $ istioctl version
> client version: 1.20.0
> control plane version: 1.20.0
> data plane version: 1.20.0 (5 proxies)
> $ kubectl version
> Client Version: v1.28.2
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.27.3
> ```
> 
> ### Additional Information
> _No response_

@NaturezzZ 

This is because Ambient's current L7 design is based on HTTP connect IP (HBONE), for filter chain matching.

It does seem inconsistent with sidecar mode..  there are some confuses here. 

@howardjohn 

Most users are more accustomed to sidecar semantics.

curl http://ratings:8080
curl http://$ratings-clusterip:8080
curl -H''host: ratings:8080" http://$pod-or-others-ip:9080

IMO, All three of these should be interpreted as access to the ratings service. We can support this by adapting the logic of the filter matcher tree under the current waypoint. If this is approved, I am glad to submit a PR.

**Comment by howardjohn** [comment]
I disagree that is the intended behavior, and it's also impossible to implement in our architecture given the node proxy cannot see host headers.

**Comment by zengyuxing007** [comment]
> I disagree that is the intended behavior, and it's also impossible to implement in our architecture given the node proxy cannot see host headers.

@howardjohn  Don't quite understand.  

ztunnel can recognize this is a request to access the ratings service by the dst ip, the ip canbe pod ip or others ip, if it is not pod ip or outside of kuberntes  or a fake VIP, we can configure it by serviceEntry.

I think the traffic will going through waypoint because we configured it.    What we need to do is route the traffic to the right filter chain at waypoint.

We can do this by modifying the logic of the waypoint existing main_internal's matcher tree.  The changed configuration is similar to the following:

```yaml
    filter_chain_matcher:
      matcher_tree:
        input:
          name: "servername"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.FilterStateInput"
            key: "envoy.string"
        exact_match_map:
          map:
            "ratings:8080":
                action:
                  name: "inbound-vip|9080||reviews.default.svc.cluster.local-http"
                  typed_config:
                    "@type": "type.googleapis.com/google.protobuf.StringValue"
                    value: "inbound-vip|9080||reviews.default.svc.cluster.local-http"
            "9.9.9.9:8080":
                action:
                  name: "inbound-vip|9080||reviews.default.svc.cluster.local-http"
                  typed_config:
                    "@type": "type.googleapis.com/google.protobuf.StringValue"
                    value: "inbound-vip|9080||reviews.default.svc.cluster.local-http"
```

The current implementation of ”direct-http“ does not support VirtualService configuration.
