### ISSUE TITLE
Mysql enable mTls,  can access in  k8s  cluster, block from outside

### ISSUE THREAD

**Issue by whmmm** [istio/istio#49140]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
> helm chart template
```yml

{{ if .Values.mysqlThird.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-third
  namespace: {{.Release.Namespace}}
  labels:
    app: mysql-third
  annotations:
    app: mysql-third
spec:
  selector:
    matchLabels:
     app: mysql-third
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-third
      annotations:
        # sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        nxy.org/mysql: "third"
      volumes:
        - name: local-path
          hostPath:
            path: {{.Values.mysqlThird.localPath}}
        - name: config
          configMap:
            name: mysql-third-config
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: mysql-third-5-7-44
        image: mysql:5.7.44
        dnsPolicy: ClusterFirst
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: local-path
          mountPath: /var/lib/mysql
          subPath: data-dir
        - name: config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{.Values.mysqlThird.password}}
        ports:
        - containerPort: 3306
          name: mysql3306
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits:
            cpu: 4000m
            memory: 4096Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-third-config
  namespace: {{.Release.Namespace}}
data:
  my.cnf: |-
    [mysqld]
    # 设置mysql的字符集
    character-set-server=utf8mb4
    # 设置mysql的时区
    default-time-zone='+8:00'
    # 设置mysql的最大连接数
    max_connections=1000
    # 设置mysql的最大连接数
    max_connect_errors=1000
    # 设置mysql的最大连接数
    max_allowed_packet=1024M
    slow_query_log = ON
    long_query_time = 10
    log_output = TABLE
    # ONLY_FULL_GROUP_BY,
    sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-third-svc
  namespace: {{.Release.Namespace}}
  labels:
    app: mysql-third
spec:
  # type: ClusterIP
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: tcp-3306
    nodePort: 30056
    # appProtocol: mysql
  selector:
    app: mysql-third

---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "mtls-mysql-policy"
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: mysql-third
  mtls:
    # mode: DISABLE
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-mtls
spec:
  host: mysql-third-svc
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      # mode: DISABLE
---
{{ end  }}
```
### 
 `mTls: mode: STRICT` only access  mysql in cluster , such as `jdbc:mysql://mysql-third-svc:3306/testdb`,
 when I use `outerIp:30056(nodePort)`, error occur :  `ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0 `
 
 disable `mtls` can  reslove , but when I disable `mtls` , the istio traffic metrics lost.
 
Is there a solution here?
 

### Version

```Text
$ `istioctl version`

client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (12 proxies)
```
$ `kubectl version --short`
```
Client Version: v1.27.9+k3s1
Kustomize Version: v5.0.1
Server Version: v1.27.9+k3s1
```
```


### Additional Information

_No response_
