### ISSUE TITLE
Locality based routing via VirtualServices

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#49198]
**Describe the feature request**
Locality based routing via VirtualServices

**Describe alternatives you've considered**
Use serviceentry to route traffic, but then when using ServiceEntry, the endpoint for local region is pointing to kubernetes service, which results in envoy not using EDS for local communication, which has its disadvantages, for instance, then envoy is depending on kube-proxy to do the routing.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by j2gg0s** [comment]
Do you mean https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting?

**Comment by nirvanagit** [comment]
> Do you mean https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting?

The one you mentioned is different. What I am looking for is, be able to define two destinations in virtualservice, which have a matching criteria based on locality, just like what is available in service entries.

For example:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
spec:
  endpoints:
  - address: aws-lb-east.com
    labels:
      type: rollout
    locality: us-east-2
    ports:
      http: 443  
  - address: aws-lb-west.com
    labels:
      type: rollout
    locality: us-west-2
    ports:
      http: 443
  hosts:
  - foobar.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS
```

**Comment by howardjohn** [comment]
I am almost certain this already works today:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
spec:
  hosts:
  - foobar.global
  http:
  - match:
     sourceLabels:
       topology.kubernetes.io/region: us-east-2
     route:
     - destination:
          host: aws-lb-east.com
  - match:
     sourceLabels:
       topology.kubernetes.io/region: us-west-2
     route:
     - destination:
          host: aws-lb-west.com
```

Make sure you are on 1.20 or so, there were some recent improvements here that indirectly enabled this
