### ISSUE TITLE
Should a single "bad" entry in Telemetry API cause the control plane and virtually everything to shutdown?

### ISSUE THREAD

**Issue by mikebell90** [istio/istio#49223]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I was playing with a POC using the Classifying Metrics entry in the Istio docs. And I added this to my global  (istio-system , no workload selector) telemetry API

```
  - overrides:
    - disabled: false
      match:
        metric: REQUEST_COUNT
        mode: CLIENT_AND_SERVER
      tagOverrides:
        request_method:
          operation: UPSERT
          value: 'has(request.method) ? request.method : ''-'''
        request_operation:
          operation: UPSERT
          value: 'has(http_endpoint) ? http_endpoint : ''-''' 
```

Ok more accurately I added the request_operation label - the request_method already existed. 

 I followed (wrongly as it turns out) the pattern of checking whether the variable is already defined with has(http_endpoint). This turns out to be wrong in CEL, where that can only be used against a FIELD, not a bare scalar property. (The correct would simply be value: 'string(http_endoint)' or similar.

Anyway I applied it, and it WORKED against my live payload with attributegen bound to it. I also checked other istio_requests_total for other pods and they were happily populated with 'unknown'

However in fact this was a **ticking timebomb**. When ANY pod (including the bound attributegen proxy) was restarted, they would absolutely flip out and give errors about being unable to connect to istiod. istiod itself generated some interesting errors about "Error adding/updating listener(s) virtualInbound: failed to create an expression: No overloads provided for FunctionStep creation" and such (some of the proxies did too)

Fortunately this was QA and easily reverted.

My question is: Yes of course it's reasonable that someone can have a bad CEL expression. But should this literally bring down the entire mesh? (Ok, the scope depends on the scope of telemetry api, sure). Without looking at the code, I'd still say from a consumer POV - no! - Generate an error sure. Ignore or drop this entry. But don't flip out. Especially since
it wasn't obvious how to diagnose this - it looked like the entire control plane was freaking out!

### Version

```Text
client version: 1.19.4
control plane version: 1.20.2-solo
data plane version: 1.20.2-solo (1230 proxies
```

### Additional Information

Let me know if you need this and need me to replicate.
