### ISSUE TITLE
After enabling the ENABLE_NATIVE_SIDECARS variable initContainers prevent pod from starting

### ISSUE THREAD

**Issue by avisaradir** [istio/istio#49221]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After upgrading the k8s version to v1.29 and enabling the ENABLE_NATIVE_SIDECARS variable all the application stoped working after applying a new deployment I can see this error in the events

Error creating: Pod "my-server-xxxxxxxx-xxxxx" is invalid: [spec.initContainers[1].readinessProbe: Forbidden: may not be set for init containers without restartPolicy=Always, spec.initContainers[1].startupProbe: Forbidden: may not be set for init containers without restartPolicy=Always] 

can't seem to find out what caused this issue, maybe I am missing something in the documentation 

### Version

```Text
istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1 (16 proxies)

kubectl version 
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-eks-c417bb3

helm version
v3.13.3+gc8b9489
```

### Additional Information
None

**Comment by mikebell90** [comment]
I wonder if you turn off rewriteAppHTTPProbe whether it will work ? (Just as an experiment that clearly isn’t a good real solution ) That the injector is getting confused?

**Comment by avisaradir** [comment]
> I wonder if you turn off rewriteAppHTTPProbe whether it will work ? (Just as an experiment that clearly isn’t a good real solution ) That the injector is getting confused?

Will try, the problem is that it isn't consistent, for 20 deployments almost the same minor differences as labels, name and image being pulled only 25% of them stoped working.

**Comment by avisaradir** [comment]
After a couple of hours I figured out the solution, because the validation for the service account used in the gatekeeper failed inside the istio proxy the pod didn't came up.

**Comment by avisaradir** [comment]
> After a couple of hours I figured out the solution, because the validation for the service account used in the gatekeeper failed inside the istio proxy the pod didn't came up.

 boy i was wrong.
 
 it is something related to istio and service account.
 
 ```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXX:role/eks-XXXX-XXXX-irsa
  name: sleep

---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
    project: sleep
    env: dev
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    app: sleep
    project: sleep
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
        project: sleep
        env: dev
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: curlimages/curl
          command: ["/bin/sleep", "infinity"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/sleep/tls
              name: secret-volume
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 200m
      volumes:
        - name: secret-volume
          secret:
            secretName: sleep-secret
            optional: true
```

lets take this as an example:
1. when applying this without istio injection everything works perfect.

2. when applying this with istio injection I see this message in the event log
```
Message:             Error creating: Pod "sleep-f4d49bc47-s9jkn" is invalid: [spec.initContainers[1].readinessProbe: Forbidden: may not be set for init containers without restartPolicy=Always, spec.initContainers[1].startupProbe: Forbidden: may not be set for init containers without restartPolicy=Always] 
```

3. when applying this with istio injection changing the service account and removing the annotation it works fine
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
```

4. when applying this with istio injection and removing the service account from the deployment it works as well
