### ISSUE TITLE
Request for Configurable Timeout Parameters in Istio Resources

### ISSUE THREAD

**Issue by sakatkoori** [istio/istio#49247]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Currently, we are experiencing http-related timeouts and tcp socket timeout issues in our deployments. Specifically, we are using the transport_socket_connect_timeout for TCP and stream_idle_timeout and max_stream_duration for HTTP in Envoy filters.

We would like to request the ability to configure these timeouts directly through Istio resources in VirtualService to reduce the reliance on EnvoyFilters.

Reason for Request:
The current approach of defining these timeouts in EnvoyFilters involves a relatively complicated format, increases the chance of introducing errors, and is challenging to maintain. Having these timeout parameters configurable through standard Istio resources would greatly simplify the configuration process and enhance maintainability.

Requested Timeout Parameters:

* transport_socket_connect_timeout for TCP
* stream_idle_timeout for HTTP
* max_stream_duration for HTTP

**Describe alternatives you've considered**
Currently these parameters are configurable in envoy filters as below:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-timeouts
spec:
  workloadSelector:
    labels:
      app: sample
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.tcp_proxy"
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.tcp_proxy
          config:
            stat_prefix: "outbound_tcp"
            transport_socket:
              name: envoy.transport_sockets.raw_buffer
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
                **transport_socket_connect_timeout:** 5s 

    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          config:
            stat_prefix: "outbound_http"
            http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            http_protocol_options:
              **idle_timeout: 10s** 
              max_stream_duration:
                **max_stream_duration: 30s** 
```
Proposing these "transport_socket_connect_timeout", "idle_timeout" and "max_stream_duration" to be also configurable params from the Virtual service istio resource as below as an example 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
  - my-service.example.com
  http:
  - route:
    - destination:
        host: my-service
        subset: v1
   - stream_idle_timeout
       value
   -  max_stream_duration
       value
  tcp:
  - match:
    - port: 5000
    route:
    - destination:
        host: my-tcp-service
        port:
          number: 6000
    - transport_socket_connect_timeout
        value
```

If there is some general agreement on this, I would be happy to open the PRs for istio/api and istio/istio.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
