### ISSUE TITLE
Ambient + Cilium: Cilium NetPol enforcement no longer silently ignores host probes

### ISSUE THREAD

**Issue by bleggett** [istio/istio#49277]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As part of the inpod ambient work, in order to prevent host-originating status probes from the kubelet from being proxied thru the ztunnel, Istio modifies the source IPs for host probes to bypass their capture via iptables SNAT.

This causes an issue when using Istio+Cilium, as Cilium uses the host source IP to silently bypass NetPol enforcement for host traffic.

This means that when using Istio+Cilium, healthprobes are no longer silently ignored by Cilium for NetPol enforcement, and have to be explicitly considered in NetPol.

For instance, with plain Cilium and no Istio ambient, given a pod with a healthcheck endpoint on 8080, applying the following ingress NetPol:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-hbone
spec:
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 15008
```

would result in host probes to 8080 silently being allowed thru, even though 8080 is not allowlisted in the NetPol.

However, with Istio ambient added to the mix, NetPol starts to apply to host probes, and the above causes (as you might expect) probe traffic on 8080 to start to be rejected.

This means the following ingress NetPol is required:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-hbone
spec:
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 15008
      # Istio modifies the source IPs for host probes to bypass their capture.
      # Cilium uses the host source IP to bypass host traffic enforcement for NetPol.
      # This means that when using Istio+Cilium, healthprobes are no longer silently ignored by
      # Cilium for NetPol enforcement, and have to be explicitly considered in NetPol.
    - protocol: TCP
      port: 8080
```

The use (and pitfalls, and alternatives) of host-probe SNATs was discussed here: https://github.com/istio/istio/pull/48253/files#r1424242669

While this is certainly better than previous large-scale incompatibilities with Cilium, this is still not ideal. Calico does not seem to have this issue AFAICT, so it probably allowlists host probes thru NetPol enforcement via a different mechanism than Cilium.

### Version

```Text
N/A
```

**Comment by PlatformLC** [comment]
Hmm, it looks like cilium identity health probe by `host source ip`, but we utilize SNATed well-know ip to do that, both are intended to bypass the further process. 
I may lost some background or discussion on why we choose SNAT here. I'm wondering if we could also just use `host source ip` to identity the health probe as well.  IIRC, in previous redirection mode, we bypass the health probe just by `host ip ` and we have an API to emulate how `kubelet` to get the `host source ip`(since istio-cni daemonset and kubelet are in the same host network namespace).

**Comment by bleggett** [comment]
> Hmm, it looks like cilium identity health probe by `host source ip`, but we utilize SNATed well-know ip to do that, both are intended to bypass the further process. I may lost some background or discussion on why we choose SNAT here. I'm wondering if we could also just use `host source ip` to identity the health probe as well. 

2 reasons why we didn't do this:

1. "getting the canonical host IP" from the perspective of packets entering a given pod network namespace in a way that works for all CNIs and all networking setups is actually quite tricky and varies widely by CNI, and there is no one reliable way to do it. All ways we had done it in the past did not work in all cases, for all CNIs.

2. Filtering on "the host IP" is not actually sufficient in some cases - as we see in https://github.com/istio/ztunnel/issues/642 it is entirely possible for packets from LoadBalanced services that did *not* originate on the host to arrive at the pod with the host IP - bypassing those wholesale is not desirable.

**Comment by shashankram** [comment]
The way Cilium ignores host probes from network policies is as follows:
- There is a controller in the agent that periodically syncs the host's IP addresses to the bpf lxcmap and ipcache. As a part of this, it maps the host IP addresses to a reserved host identity in Cilium. This notifies the network-policy cache on changes.
- In Kubernetes mode (other modes reserved for VMs, etc.), localhost traffic is always allowed to reach local endpoints. This is realized by adding an ALLOW entry  to the bpf policy map that is lower in priority than explicit DENY entries, with the identity key for this entry being the reserved host identity noted in the step above.

Summary: Cilium assigns a reserved host identity to host local endpoints and adds an explicit ALLOW entry to the bpf policy map for ingress traffic from endpoints that have the reserved host identity (applicable localhost endpoints in this case).

**Comment by bleggett** [comment]
That's annoying - despite all the machinery it's still just allow-listing host IPs and treating them as identities, which means it has the same conceptual gaps but is harder to change.

Calico clearly does something different here, as well.

Haven't looked much, but I wonder if https://docs.cilium.io/en/stable/security/policy/language/#host-policies could be an option.

**Comment by bleggett** [comment]
Tested - this can be solved by applying the following `CiliumClusterwideNetworkPolicy`

```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-ambient-hostprobes"
spec:
  description: "Allows SNAT-ed kubelet health check probes into ambient pods"
  endpointSelector: {}
  ingress:
  - fromCIDR:
      - "169.254.7.127/32"
```

where `fromCIDR` is the [SNAT-ed host probe IP ambient uses](https://github.com/istio/istio/tree/master/cni#notable-env-vars)
