### ISSUE TITLE
No listener created for TCP ingress

### ISSUE THREAD

**Issue by con5cience** [istio/istio#49317]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I can't get a TCP service to route properly. Istio doesn't seem to want to create a listener for it. All the HTTP stuff works fine on other services. When I set this particular service to HTTP then it appears to create a listener, but this is a non-HTTP protocol that I need to route and Istio throws codec errors when I use HTTP (presumably because of the protocol mismatch).

I saw some issues from a couple years ago that suggested creating the VS before the Gateway, that didn't change the behavior. I have no idea what I'm doing wrong but all the ports and protocols and standardized names seem to line up. I've been staring at manifests all day and I'm probably just missing something silly. Any help would be greatly appreciated.

Logs:
```
istiod discovery 2024-02-11T21:53:02.122738Z	warn	gateway sentry-0:26656 listener missed network filter
istiod discovery 2024-02-11T21:53:02.122854Z	info	gateway omitting listener "0.0.0.0_26656" due to: must have more than 0 chains in listener "0.0.0.0_26656"
```

Ingress Gateway:
```
apiVersion: v1                                                                                                                                                                                                                                       
kind: Service                                                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                                                            
  annotations:                                                                                                                                                                                                                                       
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp                                                                                                                                                                               
    service.beta.kubernetes.io/aws-load-balancer-name: sentry                                                                                                                                                                           
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip                                                                                                                                                                                 
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'                                                                                                                                                                                 
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing                                                                                                                                                                             
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <redacted>
  finalizers:                                                                                                                                                                                                                                        
  - service.kubernetes.io/load-balancer-cleanup                                                                                                                                                                                                      
  labels:                                                                                                                                                                                                                                            
    app: sentry                                                                                                                                                                                                                         
    app.kubernetes.io/managed-by: Helm                                                                                                                                                                                                               
    app.kubernetes.io/name: sentry                                                                                                                                                                                                      
    app.kubernetes.io/version: 1.20.2                                                                                                                                                                                                                
    helm.sh/chart: gateway-1.20.2                                                                                                                                                                                                                    
    istio: sentry                                                                                                                                                                                                                       
  name: sentry                                                                                                                                                                                                                          
  namespace: istio-ingress                                                                                                                                                                         
spec:                                                                                                                                                                                                                                                
  allocateLoadBalancerNodePorts: true                                                                                                                                                                                                                
  clusterIP: 172.20.143.155                                                                                                                                                                                                                          
  clusterIPs:                                                                                                                                                                                                                                        
  - 172.20.143.155                                                                                                                                                                                                                                   
  externalTrafficPolicy: Cluster                                                                                                                                                                                                                     
  internalTrafficPolicy: Cluster                                                                                                                                                                                                                     
  ipFamilies:                                                                                                                                                                                                                                        
  - IPv4                                                                                                                                                                                                                                             
  ipFamilyPolicy: SingleStack                                                                                                                                                                                                                        
  ports:                                                                                                                                                                                                                                             
  - name: status-port                                                                                                                                                                                                                                
    nodePort: 31116                                                                                                                                                                                                                                  
    port: 15021                                                                                                                                                                                                                                      
    protocol: TCP                                                                                                                                                                                                                                    
    targetPort: 15021                                                                                                                                                                                                                                
  - name: p2p                                                                                                                                                                                                                                        
    nodePort: 31721                                                                                                                                                                                                                                  
    port: 26656                                                                                                                                                                                                                                      
    protocol: TCP                                                                                                                                                                                                                                    
    targetPort: 26656                                                                                                                                                                                                                                
  - name: rpc                                                                                                                                                                                                                                        
    nodePort: 30975                                                                                                                                                                                                                                  
    port: 26657                                                                                                                                                                                                                                      
    protocol: TCP                                                                                                                                                                                                                                    
    targetPort: 26657                                                                                                                                                                                                                                
  selector:                                                                                                                                                                                                                                          
    app: sentry                                                                                                                                                                                                                         
    istio: sentry
  sessionAffinity: None                                                                                                                                                                                                                              
  type: LoadBalancer                                                                                                                                                                                                                                 
status:                                                                                                                                                                                                                                              
  loadBalancer:                                                                                                                                                                                                                                      
    ingress:                                                                                                                                                                                                                                         
    - hostname: c.com
```

Gateway:
```
apiVersion: networking.istio.io/v1beta1                                                                                                                                                                                                              
kind: Gateway                                                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                                                            
  name: sentry-0                                                                                                                                                                                                                 
  namespace: sentry                                                                                                                                                                                                                             
spec:                                                                                                                                                                                                                                                
  selector:                                                                                                                                                                                                                                          
    istio: sentry                                                                                                                                                                                                                       
  servers:                                                                                                                                                                                                       
  - hosts:                                                                                                                                                                                                                                           
    - '*'                                                                                                                                                                                                                                            
    port:                                                                                                                                                                                                                                            
      name: rpc                                                                                                                                                                                                                                      
      number: 26657                                                                                                                                                                                                                                  
      protocol: http                                                                                                                                                                                                                                 
  - hosts:                                                                                                                                                                                                                                           
    - '*'                                                                                                                                                                                                                                            
    port:                                                                                                                                                                                                                                            
      name: p2p                                                                                                                                                                                                                                      
      number: 26656                                                                                                                                                                                                                                  
      protocol: tcp
```

VirtualService:
```
apiVersion: networking.istio.io/v1beta1                                                                                                                                                                                                              
kind: VirtualService                                                                                                                                                                                                                                 
metadata:                                                                                                                                                                                                                                            
  name: sentry-0                                                                                                                                                                                                                 
  namespace: sentry                                                                                                                                                                                                                             
spec:                                                                                                                                                                                                                                                
  gateways:                                                                                                                                                                                                                                          
  - sentry-0                                                                                                                                                                                                                     
  hosts:                                                                                                                                                                                                                                             
  - a.com
  - b.com
  http:                                                                                                                                                                                                                                              
  - match:                                                                                                                                                                                                                                           
    - name: http-rpc                                                                                                                                                                                                                                 
      port: 26657                                                                                                                                                                                                                                    
    route:                                                                                                                                                                                                                                           
    - destination:                                                                                                                                                                                                                                   
        host: sentry-0.sentry.svc.cluster.local                                                                                                                                                                             
        port:                                                                                                                                                                                                                                        
          number: 26657                                                                                                                                                                                                                              
  - match:                                                                                                                                                                                                                                           
    - name: tcp-p2p                                                                                                                                                                                                                                  
      port: 26656                                                                                                                                                                                                                                    
    route:                                                                                                                                                                                                                                           
    - destination:                                                                                                                                                                                                                                   
        host: sentry-0.sentry.svc.cluster.local                                                                                                                                                                             
        port:                                                                                                                                                                                                                                        
          number: 26656
```

Application Service:
```
apiVersion: v1                                                                                                                                                                                                                                       
kind: Service                                                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                                                            
  labels:                                                                                                                                                                                                                                            
    app: sentry-0                                                                                                                                                                                                                
  name: sentry-0                                                                                                                                                                                                                 
  namespace: sentry                                                                                                                                                                                                                             
spec:                                                                                                                                                                                                                                                
  clusterIP: 172.20.38.224                                                                                                                                                                                                                           
  clusterIPs:                                                                                                                                                                                                                                        
  - 172.20.38.224                                                                                                                                                                                                                                    
  internalTrafficPolicy: Cluster                                                                                                                                                                                                                     
  ipFamilies:                                                                                                                                                                                                                                        
  - IPv4                                                                                                                                                                                                                                             
  ipFamilyPolicy: SingleStack                                                                                                                                                                                                                        
  ports:                                                                                                                                                                                                                                             
  - name: http-rpc                                                                                                                                                                                                                                   
    port: 26657                                                                                                                                                                                                                                      
    protocol: TCP                                                                                                                                                                                                                                    
    targetPort: 26657                                                                                                                                                                                                                                
  - name: tcp-p2p                                                                                                                                                                                                                                    
    port: 26656                                                                                                                                                                                                                                      
    protocol: TCP                                                                                                                                                                                                                                    
    targetPort: 26656                                                                                                                                                                                   
  selector:                                                                                                                                                                                                                                          
    app: sentry-0                                                                                                                                                                                                                
  sessionAffinity: None                                                                                                                                                                                                                              
  type: ClusterIP
```

Excerpt of pod spec:
```
    name: sentry-0                                                                                                                                                                                                               
    ports:                                                                                                                                                                                                                                           
    - containerPort: 26657                                                                                                                                                                                                                           
      name: rpc                                                                                                                                                                                                                                      
      protocol: TCP                                                                                                                                                                                                                                  
    - containerPort: 26656                                                                                                                                                                                                                           
      name: p2p                                                                                                                                                                                                                                      
      protocol: TCP
```

### Version

```Text
▶ istioctl version
client version: 1.20.3
control plane version: 1.20.2
data plane version: 1.20.2 (2 proxies)

▶ kubectl version        
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde

▶ helm version --short
v3.14.0+g3fc9f4b
```


### Additional Information

```
▶ istioctl --context=sentry bug-report

Target cluster context: sentry
Running with the following config: 

context: sentry
istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-02-11 15:29:40.330738 -0700 MST



Cluster endpoint: <redacted>
CLI version:
version.BuildInfo{Version:"1.20.3", GitRevision:"Homebrew", GolangVersion:"go1.21.7", BuildStatus:"Homebrew", GitTag:"1.20.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.20.2", GitRevision:"5f5d657c72d30a97cae97938de3a6831583e9f15", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.20.2}


Fetching logs for the following containers:

istio-ingress/sentry/sentry/istio-proxy
istio-system/istiod/istiod/discovery

Fetching Istio control plane information from cluster.


Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0162] (Gateway sentry/sentry-0) The gateway is listening on a target port (port 443) that is not defined in the Service associated with its workload instances (Pod selector istio=sentry). If you need to access the gateway port through the gateway Service, it will not be available.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
```

Re: IST0162, I may eventually put things behind TCP/443 on this thing, but am not at the moment. Known issue.

Re: IST0102, I don't deploy anything into `default`. Known issue.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by jewertow** [comment]
Istio does not match your VirtualService and Gateway configs, because you defined TCP protocol for the port 26656, and only HTTP matching rules in the VirtualService.

This is what you need:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sentry-0
spec:
  gateways:
  - sentry-0
  hosts:
  - a.com
  - b.com
  http:
  - match:
    - name: http-rpc
      port: 26657
    route:
    - destination:
        host: sentry-0.sentry.svc.cluster.local
        port:
          number: 26657
  tcp:
  - match:
    - port: 26656
    route:
    - destination:
        host: sentry-0.sentry.svc.cluster.local
        port:
          number: 26656
```
