### ISSUE TITLE
DNS_ROUND_ROBIN (Logical DNS) unable to connect (503) - new deployments only

### ISSUE THREAD

**Issue by Stono** [istio/istio#49315]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've got a really strange problem.
By default we've historically used `resolution: DNS` on the `ServiceEntry` for some of our common egress hosts such as `accounts.google.com`.

However, it makes more sense for these to be `DNS_ROUND_ROBIN` (logical dns) as their IPs change all the time, causing cluster drains.

I felt this would be a simple change, so I made it, and our e2e tests run, and then our tests which validate egress traffic works failed with 503s.

Digging into it more; `istioctl proxy-config clusters` doesn't show the clusters!?

Looking at pilot logs; we see:

```
    '        "outbound|443||www.googleapis.com": {\n' +
    '            "proxy": "e2e-6401-ts-egress-hosts-649f5cccd5-wrtbz.e2e-6401-ts-egress-hosts",\n' +
    '            "message": "LOGICAL_DNS cluster without endpoints outbound|443||www.googleapis.com found while pushing CDS"\n' +
    '        },\n' +
```

Odd... If I edit the `ServiceEntry` and change it to `DNS`, the cluster gets propogated...

If i edit the `ServiceEntry` again and change it back to `DNS_ROUND_ROBIN` that also seems to be fine.

So it seemed to specifically be when a _new_ service comes up with these service entries.   

I decided to create the service entry in another namespace, same error, but then in another namespace it started working.  

Tried a different cluster, mixed results too, so it seems really racey.

I'm 100% able to recreate this however with our end to end tests (creating entirely new deployments), so I am more than happy to jump on a call with someone and demonstrate the behaviour.

Example (trivial) service entry:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: karl
spec:
  exportTo:
  - .
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - name: http-port
    number: 80
    protocol: HTTP
    targetPort: 443
  - name: https-port
    number: 443
    protocol: HTTPS
  resolution: DNS_ROUND_ROBIN
```

### Version

```Text
1.20.3, but also tried 1.20.2.
```
