### ISSUE TITLE
Ingress Gateway Webhook won't be executed

### ISSUE THREAD

**Issue by kworkbee** [istio/istio#49342]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've configured the ingress gateway in the external control plane cluster as follows:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
            alb.ingress.kubernetes.io/healthcheck-port: "31001" # Status Node Port
          service:
            type: NodePort
            ports:
              - port: 15021
                targetPort: 15021
                nodePort: 31001
                name: status-port
              - port: 15012
                targetPort: 15012
                nodePort: 31002
                name: tls-xds
              - port: 15017
                targetPort: 15017
                nodePort: 31003
                name: tls-webhook
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-istiod-gw
  namespace: external-istiod
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15012
        protocol: https
        name: https-XDS
      tls:
        mode: SIMPLE
        credentialName: aws-load-balancer-tls
      hosts:
      - HIDDEN
    - port:
        number: 15017
        protocol: https
        name: https-WEBHOOK
      tls:
        mode: SIMPLE
        credentialName: aws-load-balancer-tls
      hosts:
      - HIDDEN
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
   name: external-istiod-vs
   namespace: external-istiod
spec:
  hosts:
  - HIDDEN
  gateways:
  - external-istiod-gw
  http:
  - match:
    - port: 15012
    route:
    - destination:
        host: istiod.external-istiod.svc.cluster.local
        port:
          number: 15012
  - match:
    - port: 15017
    route:
    - destination:
        host: istiod.external-istiod.svc.cluster.local
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-istiod-dr
  namespace: external-istiod
spec:
  host: istiod.external-istiod.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: SIMPLE
      connectionPool:
        http:
          h2UpgradePolicy: UPGRADE
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

I'm using AWS EKS clusters and configured ALB to configure webhook traffic to flow to Ingress Gateway through ALB when a sample application deployment which deployed on remote cluster is created. But it resulted in no sidecar being injected into the sample application deployment deployed on the remote cluster.

ALB configuration confirms that traffic has not been delivered successfully in ALB -> Ingress Gateway, not abnormal in health check or target group configuration.
(response_processing_time is indicated as -1)

I have confirmed that `Connection Refused` will be returned if I send curl request directly from Pod to 15017 which is webhook port, is there anything else I can check here?

```
istio-proxy@istio-ingressgateway-69b98d4474-884rr:/$ curl -k localhost:15017/inject
curl: (7) Failed to connect to localhost port 15017 after 0 ms: Connection refused
```

### Version

```Text
$ istioctl version                                                                                                                                                                                              
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (1 proxies)

$ kubectl version                                                                                                                                                                                                     
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k3s1
```

### Additional Information

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-02-13 15:06:38.273148 +0900 KST

CLI version:
version.BuildInfo{Version:"1.20.2", GitRevision:"Homebrew", GolangVersion:"go1.21.6", BuildStatus:"Homebrew", GitTag:"1.20.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.20.2", GitRevision:"5f5d657c72d30a97cae97938de3a6831583e9f15", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.20.2}

### Affected product area

- [ ] Ambient
- [x] Docs
- [ ] Dual Stack
- [x] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
