### ISSUE TITLE
WorkloadSelector is ignored when resolution is set to NONE

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49345]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In ServiceEntry, when resolution is set to NONE, WorkloadSelector is ignored but with no warning. In the following case, traffic with Host `www.example.com` is not routed to pods selected by `workloadSelector`. Is is a normal behavior?

The documentation of ServiceEntry seems to suggest that workloadSelector is ignored when resolution is set to NONE. However, I did not find any warnings or errors for ignoring this field.
> the proxy will forward the connection to the IP address to which the connection was bound.

I think it will be better to prohibit workloadSelector or raise a warning to make it less confusing.

```
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
  - www.example.com
  ports:
  - number: 80
    protocol: HTTP
    name: port-1
    targetPort: 9080
  resolution: NONE
  workloadSelector:
    labels:
      app: ratings
```

### Version

```Text
$ istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1
$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```
