### ISSUE TITLE
Upgrading from 1.20.1 to 1.20.3 broke wildcard host VirtualService routes

### ISSUE THREAD

**Issue by backjo** [istio/istio#49364]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When upgrading pods from 1.20.1 to 1.20.3, we observed that routes that were previously working with a wildcard hostname are no longer working. 

Using a virtualservice below, we capture all traffic to subdomains of `dev.apigw.domain.com`. In 1.20.1, this correctly routed all HTTP requests to subdomains to the destination `kong-proxy`. Upon upgrading to 1.20.3, we observed 503 errors in our workloads. Upon further inspection, we realized (using istioctl proxy-config route)  that the Envoy sidecars no longer had routes to the wildcard host configured. When we run the same istioctl command to get routes on 1.20.1 workloads, we observe that the route exists. 

This may potentially be related to the fix in #48071 . 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:  labels:
    app.kubernetes.io/instance: kong-gateway-usw2-dev
  name: tls-routing
  namespace: kong-gateway-usw2-dev
spec:
  hosts:
  - '*.dev.apigw.domain.com'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kong-proxy
```

### Version

```Text
$ istioctl version
client version: 1.20.3
istiod version: 1.20.1
istiod version: 1.20.1
istiod version: 1.20.3
istiod version: 1.20.3
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
```
