### ISSUE TITLE
Gateway API's GRPCRoute support

### ISSUE THREAD

**Issue by eguzki** [istio/istio#49373]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

> This issue is a duplicate of https://github.com/istio/istio/issues/46976. However, I cannot reopen it and the proposed solution does not work. I am happy to close this issue if #46976 is re-opened.

In [kuadrant](https://kuadrant.io), we are looking forward to providing traffic service protection for GRPC traffic using Gateway API GRPCRoute having Istio as the Gateway API provider. 

I am afraid it does not work. I have tried plaintext gRPC and gRPC over TLS (the gateway is the TLS termination endpoint) without luck. 

## What I see
When running `grpcurl` targeting the gateway, I get kind of `404 Not Found`. 
```
$ grpcurl -vv -insecure -authority grpc.example.com $INGRESS_HOST:$INGRESS_PORT main.HelloWorld/Greeting
Error invoking method "main.HelloWorld/Greeting": failed to query for service descriptor "main.HelloWorld": server does not support the reflection API
```
The service is correctly deployed. When the `grpcurl` targets the service, the response is as expected
```
$ kubectl port-forward service/grpc-tls-echo -n grpc-tls-echo 8004
$ grpcurl -plaintext -authority grpc.example.com 127.0.0.1:8004 main.HelloWorld/Greeting
{
  "hostname": "grpc-tls-echo-655f787889-dqlkl",
  "clientAddress": "127.0.0.1:52040"
}
```

There is `attachedRoutes: 0` in Gateway and no `status` section in the `GRPCRoute`. The gateway status shows being accepted and programmed. Also, the listeners are accepted and programmed with no errors. 

Besides, when the GRPCRoute is created, istiod does not log any notification about the newly created GRPCRoute nor pushing configuration to the gateway. I have tested the HTTPRoute and works as expected.

To me, it looks like the GRPCRoute is not being handled by istio.

### kind v0.20.0
```
kind create cluster --name grpc
```

### Gateway API CRDs (v1.0.0 experimental to have GRPCRoute)
```
kustomize build github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.0.0 | kubectl apply -f -
```

### metallb
```
kustomize build github.com/metallb/metallb/config/native?ref=v0.13.7 | kubectl apply -f -
kubectl -n metallb-system wait --for=condition=Available deployments controller --timeout=300s
kubectl -n metallb-system wait --for=condition=ready pod --selector=app=metallb --timeout=60s
```

### Configure metallb
```
cat <<\METALLB | /bin/bash | kubectl apply -n metallb-system -f -
# Generates a MetalLB IpAddressPool for the given docker network.
# https://metallb.org/configuration/#defining-the-ips-to-assign-to-the-load-balancer-services
#
# Example:
# ./utils/docker-network-ipaddresspool.sh kind | kubectl apply -n metallb-system -f -

set -euo pipefail

## Parse kind network subnet
## Take only IPv4 subnets, exclude IPv6
SUBNET=$(docker network inspect kind --format '{{json .IPAM.Config }}' | \
    yq '.[] | select( .Subnet | test("^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}/\d+$")) | .Subnet')
if [[ -z "$SUBNET" ]]; then
   echo "Error: parsing IPv4 network address for 'kind' docker network"
   exit 1
fi

# shellcheck disable=SC2206
subnetParts=(${SUBNET//./ })
cidr="${subnetParts[0]}.${subnetParts[1]}.200.0/24"

cat <<EOF | ADDRESS=$cidr yq '(select(.kind == "IPAddressPool") | .spec.addresses[0]) = env(ADDRESS)'
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kuadrant-local
spec:
  addresses: [] # set by make target
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
EOF
METALLB
```

### Istio v1.20.0
```
istioctl operator init
```
*EDITED*: Added `PILOT_ENABLE_ALPHA_GATEWAY_API` env var to the pilot
```
kubectl apply -f - <<EOF
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        env:
          - name: PILOT_ENABLE_ALPHA_GATEWAY_API
            value: "true"
        resources:
          requests:
            cpu: "0"
  values:
    pilot:
      autoscaleEnabled: false
    global:
      istioNamespace: istio-system
EOF
```

### GRPC service deployment
```
kubectl create namespace grpc-tls-echo
```
```
kubectl apply -n grpc-tls-echo -f - <<EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-tls-echo
  labels:
    app: grpc-tls-echo
spec:
  selector:
    matchLabels:
      app: grpc-tls-echo
  template:
    metadata:
      labels:
        app: grpc-tls-echo
    spec:
      containers:
        - name: grpc-tls-echo
          image: kalmhq/echoserver
          ports:
            - containerPort: 8004
              name: grpc
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-tls-echo
spec:
  selector:
    app: grpc-tls-echo
  ports:
    - name: grpc
      port: 8004
      protocol: TCP
      targetPort: grpc
EOF
```
### Gateway API Gateway
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout grpc.example.com.key -out grpc.example.com.crt -subj "/CN=grpc.example.com"
kubectl create secret tls grpc-example-com-tls --key="grpc.example.com.key" --cert="grpc.example.com.crt" -n grpc-tls-echo
```
```
kubectl apply -n grpc-tls-echo -f - <<EOF
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grpc-tls
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: http.example.com
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: grpc.example.com
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: grpc-example-com-tls
      mode: Terminate
EOF
```
### GRPCRoute
```
kubectl apply -n grpc-tls-echo -f - <<EOF
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpc-tls-echo
spec:
  hostnames:
  - grpc.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: grpc-tls
    namespace: grpc-tls-echo
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: grpc-tls-echo
      port: 8004
      weight: 1
EOF
```
### Test GRPCRoute
```
export INGRESS_HOST=$(kubectl get gtw grpc-tls -n grpc-tls-echo -o jsonpath='{.status.addresses[0].value}')
export INGRESS_PORT=$(kubectl get gtw grpc-tls -n grpc-tls-echo -o jsonpath='{.spec.listeners[?(@.name=="https")].port}')
grpcurl -vv -insecure -authority grpc.example.com $INGRESS_HOST:$INGRESS_PORT main.HelloWorld/Greeting
```

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (1 proxies)

$ kubectl version 
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by eguzki** [comment]
Thanks for the quick response. I appreciate it.

Setting `PILOT_ENABLE_ALPHA_GATEWAY_API` to `true` made some progress. 

```
$ kubectl get deployment istiod -n istio-system -o jsonpath='{.spec.template.spec.containers[?(@.name=="discovery")].env[?(@.name=="PILOT_ENABLE_ALPHA_GATEWAY_API")]}' | yq e -P
name: PILOT_ENABLE_ALPHA_GATEWAY_API
value: "true"
```
When the GRPCRoute is being created, the discovery controller logs about it
```
2024-02-15T15:46:09.695025Z	info	ads	Push debounce stable[13] 1 for config GRPCRoute/grpc-tls-echo/grpc-tls-echo: 100.805649ms since last change, 100.805441ms since last push, full=true
2024-02-15T15:46:09.695174Z	info	ads	XDS: Pushing Services:7 ConnectedEndpoints:1 Version:2024-02-15T15:46:09Z/10
2024-02-15T15:46:09.695843Z	info	ads	CDS: PUSH for node:grpc-tls-istio-5974cdb459-kqflb.grpc-tls-echo resources:14 size:14.2kB cached:10/13
2024-02-15T15:46:09.695951Z	info	ads	EDS: PUSH for node:grpc-tls-istio-5974cdb459-kqflb.grpc-tls-echo resources:13 size:2.4kB empty:0 cached:13/13
2024-02-15T15:46:09.696192Z	info	ads	LDS: PUSH for node:grpc-tls-istio-5974cdb459-kqflb.grpc-tls-echo resources:2 size:4.5kB
2024-02-15T15:46:09.696219Z	warn	constructed http route config for route https.443.default.grpc-tls-istio-autogenerated-k8s-gateway-https.grpc-tls-echo on port 443 with no vhosts; Setting up a default 404 vhost
2024-02-15T15:46:09.696245Z	warn	constructed http route config for route http.80 on port 80 with no vhosts; Setting up a default 404 vhost
2024-02-15T15:46:09.696277Z	info	ads	RDS: PUSH for node:grpc-tls-istio-5974cdb459-kqflb.grpc-tls-echo resources:2 size:148B cached:0/0
```

Unfortunately, the GRPCRoute seems to have no effect. The `grpcurl` commands still returns 404.

I queried the "routes" config of the gateway pod (the envoy process) and no trace of the grpc route settings

```yaml
$ istioctl proxy-config routes grpc-tls-istio-5974cdb459-kqflb -n grpc-tls-echo -o json | yq e -P
- name: http.80
  virtualHosts:
    - name: blackhole:80
      domains:
        - '*'
  validateClusters: false
  maxDirectResponseBodySizeBytes: 1048576
  ignorePortInHostMatching: true
- name: https.443.default.grpc-tls-istio-autogenerated-k8s-gateway-https.grpc-tls-echo
  virtualHosts:
    - name: blackhole:443
      domains:
        - '*'
  validateClusters: false
  maxDirectResponseBodySizeBytes: 1048576
  ignorePortInHostMatching: true
- virtualHosts:
    - name: backend
      domains:
        - '*'
      routes:
        - match:
            prefix: /stats/prometheus
          route:
            cluster: prometheus_stats
- virtualHosts:
    - name: backend
      domains:
        - '*'
      routes:
        - match:
            prefix: /healthz/ready
          route:
            cluster: agent
```
I would expect something there. 

Maybe out of the scope, but do you happen to know how to deploy the gateway with logging level in `debug` ? Maybe it can be helpful to debug why the request is not routed.
