### ISSUE TITLE
Local rate limits per path are not working

### ISSUE THREAD

**Issue by paula-fc** [istio/istio#49432]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

I have an application deployed in an AKS cluster for which I would like to apply local rate limit per path, for example:

x requests for route `/product/action1`
y requests for route `/product/action2`

All those routes are exposed by the same API (thus one k8s service + one virtualservice).

I have enabled the istio-injection for the namespace of the application and the pods got the istio-proxy containers. Then I applied the following EnvoyFilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: product
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|80"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - header_value_match:
                      descriptor_value: "action1"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /product/action1
                            ignore_case: true
                  - header_value_match:
                      descriptor_value: "action2"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /product/action2
                            ignore_case: true
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 5
                tokens_per_fill: 5
                fill_interval: 60s
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                    - key: header_match
                      value: action1
                  token_bucket:
                    max_tokens: 10
                    tokens_per_fill: 10
                    fill_interval: 60s
                - entries:
                    - key: header_match
                      value: action2
                  token_bucket:
                    max_tokens: 3
                    tokens_per_fill: 3
                    fill_interval: 60s
```

However, the default rate limits (which are 5req/60s) are applied to all the calls, even to those to `/product/action1` or `/product/action2`. 

I have tried using also the below EnvoyFilter, but I got the same results:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: product
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|80"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - request_headers:
                      header_name: ":path"
                      descriptor_key: path
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 5
                tokens_per_fill: 5
                fill_interval: 60s
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                    - key: path
                      value: /product/action1
                  token_bucket:
                    max_tokens: 10
                    tokens_per_fill: 10
                    fill_interval: 60s
                - entries:
                    - key: path
                      value: /product/action2
                  token_bucket:
                    max_tokens: 3
                    tokens_per_fill: 3
                    fill_interval: 60s
```

I have a single pod running behind the service.

I expect when I call `/product/action1` to be able to do max 10 requests/minute, when I call `/product/action2` to do max 3 requests per minute and for the other calls (like for example `/product/action3`, `/product/action4` ...) to have a max. of 5 calls per minute.

Instead, no matter which path I call (`/product/action1`, `/product/action2`, `/product/action3`, ...), I always get the 429 response after 5 calls per minute, which is the default rate limit for the service.

### Version

```Text
$ istioctl version
client version: 1.13.4
control plane version: 1.19.6
data plane version: 1.19.6 (72 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.27.7
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
```

### Additional Information

$ istioctl bug-report --istio-namespace istio-system
Error: open .../bug-report.log: The system cannot find the path specified.

**Comment by akashjain971** [comment]
You can leverage another type of action called the [header_value_match](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit-action-headervaluematch) and provide exclusive action and descriptor keys for `/product/action1` and `/product/action2`. The rest will match the default bucket.

```
- actions:
  - header_value_match:
      descriptor_key: product-action1
      descriptor_value: product-action1
      headers:
      - name: :path
        string_match: 
          exact: /product/action1
```

```
descriptors:
 - entries:
   - key: product-action1
     value: product-action1
   token_bucket:
      max_tokens: 10
      tokens_per_fill: 10
      fill_interval: 60s
```

**Comment by paula-fc** [comment]
Hi! I tried also with your example with `header_value_match` as you mentioned above, but this doesn't work either, it has the same behavior and only the default rate limit is taken into account, no matter what call I do. This means when I call `/product/action1` or `/product/action2`, I always get the 429 response after 5 calls per minute. One additional information (tough I don't know if this affects in any way or not), I upgraded, meanwhile, Istio and Kubernetes versions to:

```
$ istioctl version
client version: 1.13.4
control plane version: 1.21.0
data plane version: 1.21.0 (2 proxies), 1.20.4 (26 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.29.2
WARNING: version difference between client (1.25) and server (1.29) exceeds the supported minor version skew of +/-1
```

**Comment by akashjain971** [comment]
@paula-fc I do not think the Istio or Kubernetes version should matter here.
Can you share the entire envoy filter?

**Comment by paula-fc** [comment]
Yes, here it is:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: product
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|80
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_key: action1
                descriptor_value: action1
                headers:
                - name: :path
                  string_match:
                    exact: /product/action1
            - header_value_match:
                descriptor_key: action2
                descriptor_value: action2
                headers:
                - name: :path
                  string_match:
                    exact: /product/action2
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: http_local_rate_limiter
            token_bucket:
              max_tokens: 5
              tokens_per_fill: 5
              fill_interval: 60s
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enabled
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enforced
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            descriptors:
            - entries:
              - key: action1
                value: action1
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 10
                fill_interval: 60s
            - entries:
              - key: action2
                value: action2
              token_bucket:
                max_tokens: 3
                tokens_per_fill: 3
                fill_interval: 60s
```

**Comment by akashjain971** [comment]
@paula-fc the EnvoyFilter is correct and I was able to get rate limiting working by changing the port in `routeConfiguration`.
Make sure you provide the correct port your app is listening on. I was testing with httpbin and it works on port 8000.
```
      routeConfiguration:
        vhost:
          name: inbound|http|80 <= check this port
          route:
            action: ANY
```

You can verify if your application proxy received the EnvoyFilter by port forwarding the Envoy's admin port 15000 and checking the `config_dump` for the paths to be rate limited.

Run `kubectl port-forward pod/<pod_name> 15000:15000` on terminal.
Open http://localhost:15000/config_dump in the boowser.
Search for `/product/action` in the dump.

**Comment by Anonymous-Coward** [comment]
This ticket isn't stale. I just checked again, and still can't get the envoy filter to work properly.

I have a default rate limit for the envoy filter applied to the particular workload for which I try to make it work, and another one set globally. I can see that the default rate limit is respected - meaning the port is correct.

But either the entries in the descriptors or the descriptors altogether are ignored. None of the per path rate limits is applied.

Here's the filter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: local-app
spec:
  workloadSelector:
    labels:
      label: some-label
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|80
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_key: path
                headers:
                - name: :path
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            descriptors:
            - entries:
              - key: path
                value: /some/heavy/call
              token_bucket:
                fill_interval: 30s
                max_tokens: 2
                tokens_per_fill: 2
            - entries:
              - key: path
                value: /another/heavy/call
              token_bucket:
                fill_interval: 30s
                max_tokens: 6
                tokens_per_fill: 6
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enabled
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enforced
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 30s
              max_tokens: 10
              tokens_per_fill: 10
```

There's also a rate limit of 200 applied to the istio ingress gateway into the cluster. What I always get, when calling `/some/heavy/call` for 30 seconds is a limit of 20 `200 OK` responses, with several thousands of `429 Too Many Requests`. If the port wouldn't be OK, I'd get 100 or 200 `200 OK` responses - the rate limit of the istio ingress gateway.
