### ISSUE TITLE
HTTP traffic passthroughs cluster when SE endpoints set to internal address

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49430]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

A service entry (with DNS resolution) sets its endpoints to an internal address (e.g., ratings.default.svc.cluster.local). When `curl -H "Host:www.example.com" http://1.1.1.1:80`, the traffic passthroughs istio and itsio is trying to set up HTTP connection to `10.96.69.95 (which is svc's cluster IP)` in the external network.  The following screenshot shows that wireshark captures traffic sent to external network.

![wireshark](https://github.com/istio/istio/assets/46887061/b319f1a6-2aaf-457c-a21a-d1210bdcbd6e)

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
  - www.example.com
  ports:
  - number: 80
    protocol: HTTP
    name: port-80
  - number: 9080
    protocol: HTTP
    name: port-0
  resolution: DNS
  endpoints:
  - address: ratings.default.svc.cluster.local #svc
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 9080
    targetPort: 9080
    name: http-1
```

### Version

```Text
client version: 1.21-alpha.e6a76f0f5e5aa801a5204e8ae7f2dc42df7546f1
control plane version: 1.20.0
data plane version: 1.20.0 (5 proxies)

K8s cluster is installed in Kind
```

**Comment by NaturezzZ** [comment]
IMO, we should keep HTTP traffic inside the cluster if endpoints in SE is set to internal IP/domains.
On the contrary to setting service in endpoints, when I set the pod's IP in the endpoints-address, the same request does not passthrough the cluster. 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
  - www.example.com
  ports:
  - number: 80
    protocol: HTTP
    name: port-80
  - number: 9080
    protocol: HTTP
    name: port-0
  resolution: DNS
  endpoints:
  - address: <IP of pod>
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 9080
    targetPort: 9080
    name: http-1
```
