### ISSUE TITLE
One of Ingressgateways does not work when two istio cluster are created by kind on one machine

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49446]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I create two istio clusters based on kind, one of ingressgateways does not work.

I am using kind as k8s runtime and MetalLB as load balancer. I created two clusters, cluster-1 and cluster-2, and installed istio with `./istioctl/istioctl install --set profile=demo -y`. Then I got external IP's of both ingressgateway, 172.18.255.200 and 172.18.255.211. 

However, the ingressgateway of later-created cluster does not work. I tried to create a load balancer nginx service, to classify if kind and metalLB are ok. The results show that the nginx service worked well, which means there is something wrong with ingressgateway.

The configuration of metalLB is as follows,
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-sta
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.200-172.18.255.210     
    # 172.18.255.211-172.18.255.220 for the other cluster
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: sta
  namespace: metallb-system
spec:
  ipAddressPools:
    - example-sta
```

The istio configurations are as follows,
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - 'www.bookinfo.com'
  gateways:
    - gw-0
    - mesh
  http:
    - route:
        - destination:
            host: productpage.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-0
spec:
  servers:
    - port:
        number: 9090
        protocol: HTTP
        name: port-0
      hosts:
        - 'www.bookinfo.com'
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
spec:
  selector:
    app: productpage
  ports:
    - port: 9080
      targetPort: 9080
      name: http-1
```

### Version

```Text
client version: 1.21-alpha.e6a76f0f5e5aa801a5204e8ae7f2dc42df7546f1
control plane version: 1.20.0
data plane version: 1.20.0 (4 proxies)
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
kind v0.20.0 go1.21.1 darwin/arm64
MacOS Docker desktop
```
