### ISSUE TITLE
WorkloadSelector in SE makes no effect when the packet is partially matched in VS

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49440]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Given the configuration below. `curl -H"Host:www.example.com" http://1.1.1.1:9080/ -vv` can get the ratings service, which means that the workloadSelector in SE specifies the endpoints as backing instances.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
    - www.example.com
  ports:
    - number: 9080
      protocol: HTTP
      name: http-0
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - port: 9080
      targetPort: 9080
      name: http-0
```
But after I apply the VS, `curl -H"Host:www.example.com" http://1.1.1.1:9080/ -vv` doesn't get ratings service anymore. In my understanding, it is because the packet is partially matched in VS (actually, host matched but uri not). Is it a real bug, for the workloadSelector in SE makes no effect in this case?
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - www.example.com
  http:
    - match:
        - uri:
            exact: /details
      route:
        - destination:
            host: ratings.default.svc.cluster.local
```

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)
$ kubectl version --short
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
