### ISSUE TITLE
TLS origination doesn't work with resolution NONE in ServiceEntry

### ISSUE THREAD

**Issue by jdomag** [istio/istio#49450]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I configured Istio for TLS origination with the following configuration. I used VirtualService to remove unnecessary headers before sending the traffic to original destination.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: dev
spec:
  exportTo:
  - .
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  - name: https-port
    number: 443
    protocol: HTTPS
  resolution: NONE
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin.org
  namespace: dev
spec:
  exportTo:
  - .
  hosts:
  - httpbin.org
  http:
  - match:
    - ignoreUriCase: true
      uri:
        prefix: /
    name: default
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
        subset: tls-origination
      headers:
        request:
          remove:
          - X-Service-Technical-Key
          - X-Workspace-Id
          - X-Organization-Id
          - X-Preferred-Username
          - X-Credential-Username
          - X-Quota-Amount
          - X-Envoy-Peer-Metadata
          - X-Envoy-Peer-Metadata-Id
```

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin.org
  namespace: dev
spec:
  host: httpbin.org
  subsets:
  - name: tls-origination
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          sni: httpbin.org
```

Accessing http://httpbing.org/get from istio enabled pod ends like below:
```
# curl -sSL -D - "http://httpbin.org/get"

HTTP/1.1 503 Service Unavailable
content-length: 213
content-type: text/plain
date: Tue, 20 Feb 2024 12:00:11 GMT
server: envoy

upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```
 Chaning `resolution: NONE` to `resolution: DNS` in ServiceEntry fixes the issue:

```
# curl -sSL -D - "http://httpbin.org/get"
HTTP/1.1 200 OK
date: Tue, 20 Feb 2024 13:24:27 GMT
content-type: application/json
content-length: 468
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 370
```

It looks very similar to issue https://github.com/istio/istio/issues/25844 which was fixed by @howardjohn long time ago in PR https://github.com/istio/istio/pull/26619

### Version

```Text
╰─ istioctl version
client version: 1.17.5
control plane version: 1.17.5
data plane version: 1.17.5 (363 proxies

kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.7
```

### Additional Information
I need to stop using DNS in ServiceEntry due to coreDNS flooding issue - with hundreds of ServiceEntries multiplied by hundreds of istio enabled Pods istio kills coreDNS. Described also by @howardjohn  here: https://github.com/istio/istio/issues/13710
