### ISSUE TITLE
Different routing behavior between 1.20 and 1.22 alpha

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49458]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

`curl -vv -H "Host:ANY.ANY.ANY.example.com" -H "header3:ANY" http://1.1.1.1:80` gets `200 OK` in 1.20.0, but `502 Error` in 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769.

IMO, 1.20.0 is correct.

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
  - '*.example.com'
  gateways:
  - mesh
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: ratings.default.svc.cluster.local
        subset: v1
        port:
          number: 9090
```

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (4 proxies)

client version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
control plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
data plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769 (4 proxies)
```
