### ISSUE TITLE
With no side cars traffic distribution is not correct

### ISSUE THREAD

**Issue by andreosipov** [istio/istio#49465]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

We are running setup with no sidecars, we use just istio control plane and ingress gateway pods. We need this functionality to start using canary releases in k8s via argo-rollouts.
So the traffic flow is:
AWS LB -> istio ingress gateway pod -> application pod (wiremock)

The problem we found during performance testing is that during first 5-7min distribution is not correct: 
<img width="1216" alt="distribution" src="https://github.com/istio/istio/assets/43088906/6cf36e36-d94b-4d26-9444-941ac6fbf3a7">

For some reasons in more than 50% of our test attempts traffic distribution is not equal between application pods in the beginning. As application pods for performance tests on this stage we use wiremock if it matters. We don't use warmup options, destination rules, load balancer policies adjustments.

Gateway configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway-internal
spec:
  selector:
    istio: ingressgateway-internal
  servers:
    - hosts:
        - host1.example.domain.net
      port:
        name: http
        number: 80
        protocol: HTTP
```

Virtual service configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
spec:
  exportTo:
    - .
  gateways:
    - <namespace>/istio-ingressgateway-internal
  hosts:
    - '*.example.domain.net'
  http:
    - delegate:
        name: wiremock-internal
      match:
        - uri:
            exact: /path1
        - uri:
            prefix: /path2
```
Delegate:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wiremock-internal
spec:
  exportTo:
    - .
  http:
    - name: primary
      route:
        - destination:
            host: wiremock
            port:
              number: 8080
          weight: 100
        - destination:
            host: wiremock-canary
            port:
              number: 8080
          weight: 0
```

Observations I'd like to clarify:
1. In case of performance tests with sidecars traffic distribution is always correct, k8s service type doesn't affect.
2. In case of performance tests with NO sidecars traffic distribution is not correct first minutes in more than a half of test attempts. As we figured out this happens only when k8s service is of a kind `type: ClusterIP`, in case of a headless service distribution appears to be correct all the time. Could this be considered as a bug or is this behavior expected? 
3. Do statements above confirm, that in case of "no side cars" schema the best practice is to use headless service? But why does traffic distribution work fine when side cars are installed? Are there any difference how istio resolves endpoints with/no side cars? Initially we were thinking that with ClusterIP istio routing works till k8s service and then k8s routing goes into play, however [here](https://istio.io/latest/docs/concepts/traffic-management/#introducing-istio-traffic-management) it's written that 

> In order to direct traffic within your mesh, Istio needs to know where all your endpoints are, and which services they belong to. To populate its own service registry, Istio connects to a service discovery system

and we see in kiali that istio is seeing all the endpoints (wiremock) behind the service with any type of k8s service. Moreover changing k8s service we don't see any differences in envoy config dump taken from the istio gateway  pod.

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (3 proxies)

$kubectl version 
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.12-eks-5e0fdde
```
