### ISSUE TITLE
Inconsistent matching priority of VS between 1.20 release and 1.22 alpha

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49464]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Given the configuration below. `curl -H"host:www.bookinfo.com" http://1.1.1.1:8080/ -vv` behaves different between 1.20 release and 1.22 alpha. It goes to ratings service in 1.20 release while goes to productpage service in 1.22 alpha.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - '*.bookinfo.com'
  http:
    - route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
    - 'www.bookinfo.com'
  http:
    - route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 8080
```
According to previous issue(#49112), exact matches have precedence over wildcard matches in host. But in 1.20 release, behavior goes against the above view. Is there anyone used to find and fix it? If not, why does it behave differently between 1.20 release and 1.22 alpha?

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)

client version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
control plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
data plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769 (2 proxies)
```
