### ISSUE TITLE
ServiceEntry captures traffic that doesn't match host?

### ISSUE THREAD

**Issue by mmerickel** [istio/istio#49476]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

If I define the following service entry, and then watch traffic from my pod literally anything over 443 is captured and matches the entry.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
spec:
  exportTo:
  - .
  hosts:
  - sts.us-east-2.amazonaws.com
  - '*.s3.dualstack.us-east-2.amazonaws.com'
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: NONE
```

Hit a different endpoint:

```
$ curl https://www.google.com
```

Observe the traffic logs in the istio-proxy container:

`[2024-02-22T07:00:21.655Z] "- - -" 0 - - - "-" 883 24794 136 - "-" "-" "-" "-" "[2607:f8b0:4009:81b::2004]:443" outbound|443||*.s3.dualstack.us-east-2.amazonaws.com [2600:1f16:40:5306:1f57::10]:43380 [2607:f8b0:4009:81b::2004]:443 [2600:1f16:40:5306:1f57::10]:43364 www.google.com -`

Why is the `*.s3.dualstack.us-east-2.amazonaws.com` host showing up here? Why is the ServiceEntry matching for any reason? It appears to do this for any traffic over port 443.

### Version

```Text
EKS 1.29
Istio 1.20.3


ENABLE_NATIVE_SIDECARS: true
ISTIO_ENABLE_IPV4_OUTBOUND_LISTENER_FOR_IPV6_CLUSTERS: true
```
