### ISSUE TITLE
Regression in service entry merging in 1.19 -> 1.20

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49489]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-443
spec:
  exportTo:
  - .
  hosts:
  - www.google.co.uk
  location: MESH_EXTERNAL
  ports:
  - name: i443
    number: 443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-8443
spec:
  exportTo:
  - .
  hosts:
  - www.google.co.uk
  location: MESH_EXTERNAL
  ports:
  - name: i8443
    number: 8443
    protocol: TLS
  resolution: DNS
```

In 1.20: `STRICT_DNS cluster without endpoints outbound|443||www.google.co.uk found while pushing CDS`

cc @stevenctl @ramaraochavali @hzxuzhonghu  - I haven't looked into it yet, but all 4 of us have PRs in this area around this time
