### ISSUE TITLE
Wildcard host in SE results in route error

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49485]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Configurations as below. For `curl -H"host:www.bookinfo.com" http://1.1.1.1:9090`, I expect this packet goes to productpage service. But in fact, this packet goes to ratings service.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - www.bookinfo.com
  http:
    - route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
    - '*.bookinfo.com'
  ports:
    - number: 9090
      protocol: HTTP
      name: port-1
      targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
```
Furthermore, when I replace the `*.bookinfo.com` with `www.bookinfo.com`, this packet gets productpage service correctly, showing that it is indeed wildcard host in SE which results in route error.

Besides, I look up the RDS and discover that when using SE with wildcard, this packet skips the VS.
[route-wildcard.log](https://github.com/istio/istio/files/14374538/route-wildcard.log)
[route-exact.log](https://github.com/istio/istio/files/14374540/route-exact.log)

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
