### ISSUE TITLE
Wildcard host in SE cannot match the host in Destination

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49482]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Configurations as below. `curl -H"host:www.example.com" http://1.1.1.1:9090` can get ratings service, while `curl -H"host:www.bookinfo.com" http://1.1.1.1:9090` cannot. In other words, wildcard host in SE cannot match the host in Destination.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
  - '*.bookinfo.com'
  http:
  - route:
    - destination:
        host: www.example.com
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-1
spec:
  hosts:
  - www.bookinfo.com
  ports:
  - number: 9090
    protocol: HTTP
    name: port-0
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
  - '*.example.com'
  ports:
  - number: 9090
    protocol: HTTP
    name: port-0
    targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
```
Looking up the RDS, I find that `curl -H"host:www.bookinfo.com" http://1.1.1.1:9090` is routed to `outbound|9090||www.example.com` instead of `outbound|9090||*.example.com`. Why service `*.example.com` in the registry cannot match the host `www.example.com` in the Destination, like se-0 match `curl -H"host:www.example.com" http://1.1.1.1:9090`?

[route.log](https://github.com/istio/istio/files/14373065/route.log)
[cluster.log](https://github.com/istio/istio/files/14373071/cluster.log)

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
