### ISSUE TITLE
SE disables VS on port 80

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49508]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Given the configuration below, `curl -H"host:any.example.com" http://1.1.1.1:80` can get the productpage service.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
    - '*.example.com'
  http:
    - route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 8080
```
But since I add the SE, `curl -H"host:any.example.com" http://1.1.1.1:80` returns 502. I look up the RDS, and find that there is no domain `*.example.com` in `name: "80"`.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
    - www.example.com
  ports:
    - number: 80
      protocol: HTTP
      name: port-0
  resolution: DNS
```
This error occurs in both of 1.20 release and 1.22 alpha. Why does this SE affect traffic that is not related to it? @keithmattix 

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (5 proxies)

client version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
control plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
data plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769 (5 proxies)
```
