### ISSUE TITLE
Route error under multiple VS and SE in 1.22 alpha

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49509]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As the configuration below, `curl -H"host:www.example.com" http://1.1.1.1:80` cannot get productpage service as expected in 1.22 alpha. For reference, it can get the correct service in 1.20 release.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - www.bookinfo.com
  http:
    - route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
    - '*.example.com'
  http:
    - route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
    - www.bookinfo.com
  ports:
    - number: 80
      protocol: HTTP
      name: port-2
  resolution: DNS
```
I believe that this route error results from something underlying multiple VS and SE, since it disappears without one of the resources.

### Version

```Text
client version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
control plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769
data plane version: 1.22-alpha.b652ff114d85c2ed15034e1c3c87447d96b9c769 (7 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
