### ISSUE TITLE
netstat timer column shows keepalive for non-keepalive connections

### ISSUE THREAD

**Issue by deepakdeore2004** [istio/istio#49510]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

create serviceentry to include external host into servicemesh, send traffic to that destination, `netstat -panto` shows `keepalive` off for one connection and is on for other one

```
$ netstat -panto |grep 443 | grep ESTA
tcp        0      0 10.244.1.57:56177       142.250.71.4:443        ESTABLISHED -                    keepalive (26.26/0/0)
tcp        0      0 10.244.1.57:53338       142.250.71.4:443        ESTABLISHED 19/envoy             off (0.00/0/0)
```

adding `keepalive` in destination rule shows all connections have keepalive on
```
$ netstat -panto |grep 443 | grep ESTA
tcp        0      0 10.244.1.57:32847       142.250.71.36:443       ESTABLISHED -                    keepalive (6.95/0/0)
tcp        0      0 10.244.1.57:41336       142.250.71.36:443       ESTABLISHED 19/envoy             keepalive (17.15/0/0)
```

### Version

```Text
$ istioctl version
client version: 1.20.2
istiod version: 1.18.5
data plane version: 1.18.5 (1 proxies)

$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.26.0
```

### Additional Information

steps to reproduce:
1. deploy vegeta load testing pod - `kubectl create deploy vegeta --image peterevans/vegeta` with istio injection
2. add external host into service mesh
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
```
4. exec into the vegeta pod and call external site - `echo "GET https://www.google.com/" | vegeta attack -rate=3 -duration=60s | vegeta report`
5. exec into istio-proxy container from another tearminal and check connections, it shows one connection in keepalive and other one as off, expected should be `off` since there is no keepalive enabled yet - `netstat -panto |grep 443 | grep ESTA`
6. now enable keepalive
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: google
spec:
  host: 'www.google.com'
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        tcpKeepalive:
          time: 20s
          interval: 5s
```
7. run same test as above and check netstat, last column shows all connections have keepalive enabled
