### ISSUE TITLE
Traffic is not dropped when VS HTTPMatch is not matched by port

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49516]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In this case, `curl -H "Host:any.bookinfo.com" http://1.1.1.1:80` gets `ratings` workload, which should be dropped according to doc and https://github.com/istio/istio/issues/49440#issuecomment-1954058003. 

More interestingly, if I change vs-1's HTTPMATCH to `exact: /ratings`, the same `curl` gets a 404 error rather than successfully gets `ratings` workload. Is there any differences between uri and port? IMO, just on the perspective of users, both of them should have the same behavior.

Thank you!
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
  - '*.bookinfo.com'
  gateways:
  - mesh
  http:
  - match:
    - port: 9080
    route:
    - destination:
        host: delegate-2
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
  - '*.bookinfo.com'
  ports:
  - number: 80
    protocol: HTTP
    name: port-1
    targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
```

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)
$ kubectl version --short
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by keithmattix** [comment]
Both should fail; https://github.com/istio/istio/pull/49403 fixes a bug where the VS doesn't get applied if the service isn't in the service registry and the port is 80

**Comment by NaturezzZ** [comment]
I can still reproduce this bug in the dev version 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297. Does it contain #49403  fix?

```
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (2 proxies)
```

**Comment by NaturezzZ** [comment]
@keithmattix Yes, it occurs in 1.19.0.

**Comment by hzxuzhonghu** [comment]
if you look carefully the service port defined in SE is 80, but the match port defined in vs is 9080, so the HTTP route does not match the service, so they donot match

**Comment by NaturezzZ** [comment]
any.bookinfo.com is matched by vs-1 via its host, but not matched by port. IMO the request will be caught by vs-1 but cannot find any satisfiable http routes, and thus got a 503.

**Comment by hzxuzhonghu** [comment]
```
  http:
  - match:
    - port: 9080
    route:
    - destination:
        host: delegate-2
```

This port 9080 does not match a service, so this route will be ignorred.


I feel kind of understand your confusion: here the service and vs match with host, but only the port does not match, so the request will not be routed by the vs.

If the port also matches, like change it to 80, then the request will be routed to host `delegate-2`.
