### ISSUE TITLE
WithoutHeaders deny packets without the target header

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49537]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

According to [https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest](url), withoutHeaders deny packets when a header is matched with a matching rule among withoutHeaders. However, in practical test, I find that withoutHeaders deny the packets without the target header. This should be an inconsistency between documentation and actual behavior.

For example, as configuration below, `curl -H"host:www.example.com" http://1.1.1.1:80` cannot get productpage service in 1.20 release and 1.22 alpha. After I remove withoutHeaders, it is OK.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - www.example.com
  http:
    - match:
        - withoutHeaders:
            header1:
              exact: "value1"
      route:
        - destination:
            host: productpage.default.svc.cluster.local
```

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (5 proxies)

client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (5 proxies)
```
