### ISSUE TITLE
Header operation does not take effect if value is set to empty string 

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49553]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When the value of header operation in virtual service is set to empty, it does not take effect. In the add operation as below, header `app:""` is not added into the egress request. BTW, HTTP with empty header value is legal in RFC and has been supported by many tools (e.g., curl).

In the RDS, `requestHeadersToAdd` does not contain `value`, which is different from scenarios with a non-empty header.
```
requestHeadersToAdd:
      - header:
          key: app
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
  - www.bookinfo.com
  http:
  - route:
    - destination:
        host: productpage.default.svc.cluster.local
      headers:
        request:
          add:
            app: ""
```

### Version

```Text
client version: 1.21-alpha.e6a76f0f5e5aa801a5204e8ae7f2dc42df7546f1
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (6 proxies)

Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```
