### ISSUE TITLE
EnvoyFilter priority is not merged across cluster level and namespaced resources

### ISSUE THREAD

**Issue by Stono** [istio/istio#49555]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The `priority` field of an `EnvoyFilter` is only honoured when the resources are in the same namespace, when they're in a different namespace - the ordering doesn't apply.

For example:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-1 
  namespace: istio-test-app-2
spec:
  priority: -5
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
                request_handle:headers():replace("filter", "filter-1")
            end
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-2 
  namespace: istio-system 
spec:
  priority: -1
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
                request_handle:headers():replace("filter", "filter-2")
            end
```

In this example `filter-2` has a higher priority than `filter-1` but the `filter` header returns as `filter-1`.  

Putting both resources in the same namespace, eg `istio-system`, results in the expected behaviour with the priorities.

What I appear to observe from my testing in terms of priority is a sub ordering, eg:

```
[
   ...filtersFromIstioSystemPriorityOrdered,
   ...filtersFromNamespacePriorityOrdered
]
```

### Version

```Text
1.20.3
```
