### ISSUE TITLE
W3C trace context header is not properly injected when using OpenTelemetry

### ISSUE THREAD

**Issue by npuichigo** [istio/istio#49557]
When global mesh config is configured to use OpenTelemetry, W3C trace context header doesn't show up just like b3 headers for Zipkin.
```
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing: {}
  defaultProviders:
      tracing:
      - otel-tracing
      metrics:
      - prometheus
    enableTracing: true
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    meshNetworks: 'networks: {}'
```
The headers are like:
```
curl -H "Host: httpbin.istioinaction.io" http://$INGRESS_HOST/headers     
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.istioinaction.io", 
    "User-Agent": "curl/8.4.0", 
    "X-Amzn-Trace-Id": "Root=1-65dc71a1-3d19fda8559df9223c0792f9", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Envoy-Internal": "true", 
    "X-Envoy-Peer-Metadata": "..."
    "X-Envoy-Peer-Metadata-Id": "..."
  }
}
```

The expected header should be `traceparent`
