### ISSUE TITLE
metrics: how to get the original host if rewrite host

### ISSUE THREAD

**Issue by kytool** [istio/istio#49556]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

1.  Telemetry

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-telemetry
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_COUNT
          tagOverrides:
            request_host:
              value: request.host
      providers:
        - name: prometheus
```

2. VirtualService
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-vs
  namespace: default
spec:
  gateways:
    - default/default-gateway
  hosts:
    - local.my.cn
  http:
    - match:
        - ignoreUriCase: true
          uri:
            prefix: /abc/
      name: v1
      rewrite:
        authority: local2.my.cn
        uri: /
      route:
        - destination:
            host: myapp.default.svc.cluster.local
```

and then， the metrcs of istio_requests_total export request_host=local2.my.cn，but  I want get local.my.cn
Same goes for path, but path is available via request.headers['X-Envoy-Original-Path']
Whether there is a param like X-Envoy-Original-Host

### Version

```Text
$ istioctl version
client version: 1.13.9
control plane version: 1.13.9
data plane version: 1.13.9 (1 proxies)

$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.20.7
```
