### ISSUE TITLE
Collision between SEs with the same host

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49550]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As configuration below, there are two SEs defined on the same host but different ports. I expect both port 8080 and 9080 can be accessed. However, only one of them can be accessed in practice, sometimes 8080 while sometimes 9080. Which port can be accessed seems to be random, which makes me confused.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
  - www.bookinfo.com
  ports:
  - number: 8080
    protocol: HTTP
    name: port-1
    targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-1
spec:
  hosts:
  - www.bookinfo.com
  ports:
  - number: 9080
    protocol: HTTP
    name: port-3
    targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: productpage
```

I look up the RDS and find that both `www.bookinfo.com:8080` and `www.bookinfo.com:9080` exists.
[route.log](https://github.com/istio/istio/files/14400395/route.log)

To find out, I look up the CDS and EDS. Here is the result.
```shell
$ istioctl pc cluster sender-3 --fqdn "www.bookinfo.com" 
SERVICE FQDN         PORT     SUBSET     DIRECTION     TYPE     DESTINATION RULE
www.bookinfo.com     8080     -          outbound      EDS      
www.bookinfo.com     9080     -          outbound      EDS 

$ istioctl pc endpoint sender-3 --cluster "outbound|8080||www.bookinfo.com" 
ENDPOINT     STATUS     OUTLIER CHECK     CLUSTER

$ istioctl pc endpoint sender-3 --cluster "outbound|9080||www.bookinfo.com"
ENDPOINT              STATUS       OUTLIER CHECK     CLUSTER
10.244.1.90:9080      DRAINING     OK                outbound|9080||www.bookinfo.com
10.244.2.134:9080     DRAINING     OK                outbound|9080||www.bookinfo.com
```

Why no endpoints for `outbound|8080||www.bookinfo.com`, since port 8080 should be accessible and it exists in RDS and CDS?

### Version

```Text
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (2 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
