### ISSUE TITLE
IstioOperator: annotation 'proxy.istio.io/config' erase 'meshConfig.defaultConfig'

### ISSUE THREAD

**Issue by eraac** [istio/istio#49560]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Configuration set in `meshConfig.defaultConfig` via IstioOperator, is fully overridden by pod annotation `proxy.istio.io/config` even though they have different fields.

The [documentation](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig) suggests that configurations with different fields should be merged
> If both are configured, the two are merged with per field semantics; the field set in annotation will fully replace the field from mesh config defaults. This is different than a deep merge provided by protobuf

### Version

```Text
$ istioctl version
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (24 proxies)

$ kubectl version
Client Version: v1.25.13
Kustomize Version: v4.5.7
Server Version: v1.25.16-gke.1268000
```

### Additional Information

In this case, `proxyStatsMatcher` isn't set on the ingress gateway

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal

  meshConfig:
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*upstream_rq_retry.*"
          - ".*upstream_cx_.*"
        inclusionSuffixes:
          - "upstream_rq_timeout"

// ...
  components:
    ingressGateways:
    - name: gateway
      k8s:
        podAnnotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 60s
```

**Comment by leosarra** [comment]
I will reproduce it and take a look

**Comment by leosarra** [comment]
I tested using the following operator to install istiod + an ingress gateway named "my-gateway"

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig:
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*upstream_rq_retry.*"
          - ".*upstream_cx_.*"
        inclusionSuffixes:
          - "upstream_rq_timeout"
  components:
    ingressGateways:
    - name: my-gateway
      enabled: true
      k8s:
        podAnnotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 33s
```

If I check the logs of the "my-gateway" pod,I see that both config got merged correctly in the "effective config"

```
2024-02-27T13:54:56.409133Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
proxyAdminPort: 15000
proxyStatsMatcher:
  inclusionRegexps:
  - .*outlier_detection.*
  - .*upstream_rq_retry.*
  - .*upstream_cx_.*
  inclusionSuffixes:
  - upstream_rq_timeout
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 33s
tracing:
  zipkin:
    address: zipkin.istio-system:9411
```
