### ISSUE TITLE
Can not enable L7 routing in Ambient for services introduced by SE

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49578]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi, I am trying to enable L7 routing in Ambient. When the hosts field in the VS is a service host introduced by a SE, it does not route the request to the endpoints specified in the VS.

More specifically, I want to route `www.google.com` to an internal workload when `curl http://www.google.com`. I have started waypoint and it worked well on k8s intrinsic services. 

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (1 proxies)
```

**Comment by NaturezzZ** [comment]
Hi @ilrudie! I read #49436 and [doc](https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit?pli=1). I can enable L7 for services but still can not enable L7 routing/redirecting for service entries. The following is my configuration. I have two questions,
1. If I add annotation `istio.io/waypoint-for: all-traffic` in the waypoint configuration, is the traffic to the service entry sent to waypoint?
2. What IP address should I use in the `curl`. I can not simply `curl http://address.internal` because `address.internal` is not resolvable. Does service entries have a VIP? What about wildcard service entries?

Could you please help me? Thank you!
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: default
  namespace: default
  annotations:
    istio.io/waypoint-for: all-traffic
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
  annotations:
    istio.io/use-waypoint: default
spec:
    hosts:
    - address.internal
    location: MESH_INTERNAL
    ports:
    - name: http-0
      number: 80
      protocol: HTTP
    resolution: STATIC
    workloadSelector:
      labels:
        app: we
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
  - 'address.internal'
  gateways:
  - mesh
  http:
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: productpage.default.svc.cluster.local
```

I am using 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297.
```
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (6 proxies)
```
