### ISSUE TITLE
HTTPMatch affects which VS to choose for Gateway

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49588]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Given the configuration below, I apply it into Istio.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - www.bookinfo.com
  gateways:
    - gw-0
    - mesh
  http:
    - route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-0
spec:
  servers:
    - port:
        number: 9090
        protocol: HTTP
        name: port-0
      hosts:
        - www.bookinfo.com
```
After that, I create such a VS in Istio. Since Istio choose the oldest VS, I expect that the packet from ingress gateway with host `www.bookinfo.com` can get ratings service. But in practice, it gets productpage service, which shows that `vs-1` takes effect.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
    - www.bookinfo.com
  gateways:
    - gw-0
    - mesh
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 8080
```
However, after I remove the HTTPMatch in `vs-1`, the packet from ingress gateway with host `www.bookinfo.com` gets ratings service, showing that the oldest VS takes effect. This confuses me, since I think HTTPMatch should not affect which VS to choose for Gateway.

Here are the RDS with and without HTTPMatch.
[route-with-match.log](https://github.com/istio/istio/files/14427589/route-with-match.log)
[route-without-match.log](https://github.com/istio/istio/files/14427591/route-without-match.log)

### Version

```Text
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (7 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
