### ISSUE TITLE
Different route behavior under VSs with same host between gateway and sidecar

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49589]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As configuration below, I look up the RDS and find some differences in route behavior between gateway and sidecar. For sidecar, only one route under `www.bookinfo.com:80`, which shows that only one of the VSs with the same host takes effect. However, for gateway, there are two routes under `www.bookinfo.com:9090`, showing both VSs take effect.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
  - www.bookinfo.com
  gateways:
  - gw-0
  - mesh
  http:
  - route:
    - destination:
        host: ratings.default.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
  - www.bookinfo.com
  gateways:
  - gw-0
  - mesh
  http:
  - match:
      - uri:
          prefix: /productpage
    route:
    - destination:
        host: productpage.default.svc.cluster.local
        port:
          number: 8080
```
In practice, Istio's behavior confirm the difference. So I wonder whether it is the expected behavior according to the design of Istio.

[route-sc.log](https://github.com/istio/istio/files/14427858/route-sc.log)
[route-gw.log](https://github.com/istio/istio/files/14427860/route-gw.log)

### Version

```Text
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (7 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
