### ISSUE TITLE
Istio Ingress Gateway route to external service 503

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#4958]
Build 0.8.0-pre20180414-09-15
When trying to create a virtualservice that routes to an externalservice using DNS discovery i get a 503 UF every time.

```
[2018-04-14T01:54:15.767Z] "GET /api/breeds/list/all HTTP/1.1" 503 UF 0 57 0 - "174.82.221.133, 100.117.13.192" "PostmanRuntime/7.1.1" "6292770b-033a-9b87-bad4-f50001da776d" "my-ingress.weather.com" "[2400:cb00:2048:1::6818:6aaa]:80"
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ExternalService
metadata:
  name: dogs-dev
  namespace: istio-system
spec:
  hosts:
  - dog.ceo
  ports:
  - number: 80
    name: http
    protocol: http
  discovery: "DNS"
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dogs
  namespace: istio-system
spec:
  hosts:
  - my-ingress.weather.com
  gateways:
  - istio-ingressgateway
  http:
  - route:
    - destination:
        host: dog.ceo
```

CDSZ
```json
      {
        "name": "outbound|http||dog.ceo",
        "type": "STRICT_DNS",
        "connectTimeout": "1.000s",
        "hosts": [
          {
            "socketAddress": {
              "address": "dog.ceo",
              "portValue": 80
            }
          }
        ],
        "circuitBreakers": {
          "thresholds": [
            {}
          ]
        }
      }
```
