### ISSUE TITLE
VS withoutHeaders does not work as expected

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#49593]
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - {{ .dstSvc }}
  http:
  - match:
    - withoutHeaders:
        end-user:
          regex: \*
    route:
    - destination:
        host: {{ .dstSvc }}
    fault:
      abort:
        percentage:
          value: 100
        httpStatus: 403
  - route:
    - destination:
        host: {{ .dstSvc }}
```

With the above VS applied, we expect that a request without `end-user` header to be routed to dstSvc successfully, and any request with `end-user`should get 403. 

But according to the test https://github.com/istio/istio/pull/49540/files#r1505244888, a request with `"end-user", "jason"` also get 403. 

This is a bug, i haven't know the cause yet.
