### ISSUE TITLE
Distributed Tracing with Filters Example Request

### ISSUE THREAD

**Issue by Disturbing** [istio/istio#4963]
https://istio.io/docs/tasks/telemetry/distributed-tracing.html

I noticed that the zipkin addons is now missing -- but I wanted to ask and see if there's a specific way to control istio to filter tracing by the labels of pods only?

Use case is to launch Jaeger to listen to only show services A and B labeled app="service-a" and app="service-b".

_I noticed you can filter this type of stuff with the FluentD example, would be great to add config example to filter for tracing as well!_

```
# Configuration for logentry instances
apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: newlog
  namespace: istio-system
spec:
  severity: '"info"'
  timestamp: request.time
  variables:
    source: source.labels["app"] | source.service | "unknown"
    user: source.user | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    responseCode: response.code | 0
    responseSize: response.size | 0
    latency: response.duration | "0ms"
  monitored_resource_type: '"UNSPECIFIED"'
---
```

**Comment by douglas-reid** [comment]
@Disturbing There are a few related efforts underway to add dynamic tracing configuration to Istio. 

One is to add API level control of tracing (for sampling, etc.). An initial exploratory PR is (https://github.com/istio/api/pull/363). 

Another is adding trace templates (and tracing adapters) to Mixer -- so that Mixer can control the generation and shape of trace spans. This would, I believe, closely match your request for functionality matching the fluentd configuration.

If you have a few moments, it would be great to bring this to the next Policy and Telemetry WG meeting for discussion.

cc: @jeffmendoza who is helping to add tracing features to Istio.

**Comment by Disturbing** [comment]
Thanks for the invite - couldn't find the time for the next meeting? Where can i get more information?

Also -- I was thinking that this can simply be done with rules?

```
---
# Rule to send logentry instances to the fluentd handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: newlogtofluentd
  namespace: istio-system
spec:
  match: "true" # match for all requests
  actions:
   - handler: handler.fluentd
     instances:
     - newlog.logentry
---
```

For instance above --- isn't it possible to route rules to filter only N services somehow using:

```
  match: destination.service == "service1.ns.svc.cluster.local" && request.headers["x-user"] == "user1"
```

My thought is having Rules for the logs but somehow controlling them to be consumed by specific Kibana, Jaeger or Prometheus instances?

So if I have Service A + B, Kibana AB sees both of them.  IF I have Service C and D, Kibana CD sees them.  
Same would go for Jaeger and Prometheus.

Any thoughts on how to do this with Rules? Would love any tip being new to all of this :)
