### ISSUE TITLE
SourceLabel disables all VS in sidecar

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49631]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As configuration below, I want to divide the traffic on host `*.example.com` into two VS by the source label. However, in Pod with label `v2`, `curl -H"host:www.example.com" http://1.1.1.1:8080` cannot get ratings service.  I look up the RDS and find that `vs-1` doesn't take effect in Pod with label `v2`.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - '*.example.com'
  http:
    - match:
        - sourceLabels:
            version: v1
      route:
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
    - '*.example.com'
  http:
    - match:
        - sourceLabels:
            version: v2
      route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
    - 'www.example.com'
  ports:
    - number: 8080
      protocol: HTTP
      name: port-1
      targetPort: 9080
  resolution: DNS
```
[route-v2-dev.log](https://github.com/istio/istio/files/14448690/route-v2-dev.log)

For reference, in 1.19.0 release, `curl -H"host:www.example.com" http://1.1.1.1:8080"` can get correct service in Pod with label `v2`. So is there a bug after 1.19?

### Version

```Text
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
data plane version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297 (7 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
