### ISSUE TITLE
503 nc cluster_not_found istio

### ISSUE THREAD

**Issue by Andreik8s** [istio/istio#49663]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio 1.20 does not find cluster, or does not resolve dns

### Version

```Text
istioctl version 1.20.3
kubectl versio 1.28
```

### Additional Information

Hi

We have a EKS cluster running istio 1.19.7 and the bellow resources are working fine.
We do not use injection/mesh, just "Istio core" "Istiod" "Ingress gateways" so we route traffic where we want.

After I upgraded to istio 1.20.0/3, I get in browser error 503, in logs I get 503 nc cluster_not_found istio. All upgrades/downgrades where done with istioctl from the related version. 

I resolved partially by adding ServiceEntry, I see trafic is going fine but I get No healthy upstream.

 I see the relese notes for ExternalName but that is not enabled.

 Another fix that works for us is when we have created an Endpoint in same Namespace in k8s and added the IP of the EC2 instance.

Somehow istio does not resolve anymore the ec2 hostname, or does not route correctly the traffic to the ec2 - what has changed in 1.20 regarding this and what I should tweak to make it work as it was in 1.19.7?
```

--- # only with istio 1.20.3
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: serviceentry
  namespace: example
spec:
  hosts:
  - application.qa.domain.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
    # end istio 1.20.3
--- 
#  istio 1.19.7
apiVersion: v1
kind: Service
metadata:
  labels:
    app: application
  name: serviceapp
  namespace: example
spec:
  ports:
    - port: 80
  type: ExternalName
  externalName: application.qa.domain.com #ec2 running webapp on port 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: application
  name: appvservice
  namespace: example
spec:
  gateways:
  - app-gateway
  hosts:
  - application.sub.domain.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: serviceapp.example.svc.cluster.local
        port:
          number: 80
      weight: 100
    timeout: 3600s
    headers:
      request:
        set:
            X-Forwarded-Proto: https
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app: application
  name: app-gateway
  namespace: example
spec:
  selector:
    istio: internal-ingressgateway
  servers:
  - hosts:
    - application.sub.domain.com
    port:
      name: http
      number: 80
      protocol: HTTP

---
```
