### ISSUE TITLE
Service defined on port 80 causes VS cannot capture traffic with specific host

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49673]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Here is the configuration, for `curl -H"host:ratings.default.svc.cluster.local" http://1.1.1.1:80/ratings`, I expect it can be captured by `vs` and redirected to ratings service. But in practice, it returns 403.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - '*.default.svc.cluster.local'
  http:
  - match:
    - uri:
        prefix: /ratings
    route:
    - destination:
        host: ratings.default.svc.cluster.local
        port:
          number: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 9090
    targetPort: 9080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 9080
    name: http
```
However, if I delete test service or change the port test service defined on, this packet can be captured and redirected correctly. So why is this happening?

### Version

```Text
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (6 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
