### ISSUE TITLE
Inconsistent routing behavior in Ambient virtual service

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#49680]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

If I set the VS together with the following configuration in Ambient mode, and `curl -H "Host:ratings.default.svc.cluster.local" http://test.default.svc.cluster.local`. The traffic goes to `test` svc.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - 'ratings.default.svc.cluster.local'
  http:
    - route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 80
```
However, if I change the VS hosts to a wildcard (shown below), the same `curl -H "Host:ratings.default.svc.cluster.local" http://test.default.svc.cluster.local` goes to ratings.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-0
spec:
  hosts:
    - '*.default.svc.cluster.local'
  http:
    - route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 80
```

Basic configuration,
```
apiVersion: v1
kind: Service
metadata:
  name: productpage
  annotations:
    istio.io/use-waypoint: default
spec:
  selector:
    app: productpage
  ports:
    - port: 80
      targetPort: 9080
      name: http-1
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  annotations:
    istio.io/use-waypoint: default
spec:
  selector:
    app: ratings
  ports:
    - port: 80
      targetPort: 9080
      name: http-0
---
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    istio.io/use-waypoint: default
spec:
  selector:
    app: test
  ports:
    - port: 80
      targetPort: 9080
      name: http-0
---
```

### Version

```Text
client version: 1.22-alpha.0554fb92631497bf4d0e7017b85fbaec834d0297
control plane version: 1.22-alpha.77704a50bbd2623b642a767ae372c5865e071dbc
data plane version: 1.22-alpha.77704a50bbd2623b642a767ae372c5865e071dbc (6 proxies)
```
