### ISSUE TITLE
Delegate VirtualService support for rewrite in root VirtualService

### ISSUE THREAD

**Issue by akamac** [istio/istio#49692]
**Describe the feature request**
Right now delegate and root VS [route merging logic](https://github.com/istio/istio/blob/master/pilot/pkg/model/virtualservice.go#L278) requires delegate match conditions to be a subset of the one's of the root VS. My use case is to configure match conditions in delegate VS after root VS rewrite rules.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

My sample config (delegate VS is used solely to enable statistics gathering for specific endpoints):
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: ns
  name: root-svc-1
spec:
  gateways:
  - istio-ingress-http-internal/ingress-gateway
  hosts:
  - example.com
  http:
  - match:
    - uri:
        prefix: /api/
    rewrite:
      uri: /
    delegate:
      namespace: ns
      name: api

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: ns
  name: root-svc-2
spec:
  gateways:
  - istio-ingress-http-internal/ingress-gateway
  hosts:
  - api.example.com
  http:
  - delegate:
      namespace: ns
      name: api

# delegate virtual service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: ns
  name: api
spec:
  http:
  - match:
    # tier1
    - uri:
        exact: /1.1/critical
      method:
        exact: GET
      statPrefix: tier=tier1.method=GET.path=/1.1/critical#
    # catch all
    - name: catchall
    route:
    - destination:
        host: k8s-service
        port:
          number: 8080
```
