### ISSUE TITLE
WDS for Non-HBONE Gateways

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#49699]
Currently the reference from a Service or Workload to a Waypoint uses `GatewayAddress`. 

```protobuf
message GatewayAddress {
  oneof destination {}
  uint32 hbone_mtls_port = 3;
  uint32 hbone_single_tls_port = 4;
}
```

In the [waypoint capture](https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit) doc we've decided that Waypoints may expose other protocols than mTLS. We need somewhere to put the desired port and protocol. 

I'm pretty sure we want the GatewayAddress to capture this as it's the what we're using to join a redirected entity and the gateway. `GatewayAddress.destination` is similar to HTTPRoute's `parentRefs[].name`. We're missing a `parentRefs[].sectionName` equivilant to pick which of the listeners on the gateway we want.

```protobuf
message GatewayAddress {
  // Port exposed on the gateway. This can get mapped using Service target ports or replaced by the ztunnel's port for sandwich
  uint32 port;
  // Protocol we use on the last hop from any zTunnel to this waypoint.
  ApplicationProtocol protocol;
} 

enum TunnelProtocol {
  // Uncaptured traffic
  NONE = 0; 
  // HTTP CONNECT
  HBONE = 1;
  // TLS-SNI
  HTTPS = 2;
}

message Workload {
  // If set, this workload does not use zTunnel to deal with tunnel_protocol.
  bool native_tunnel;

  // The protocol we use to connect to this Workload in zTunnel outbound path.
  // Not evaluated for sandwiched Waypoints since a Waypoint may have multiple.
  // If native_tunnel is false, this _must_ be HBONE
  TunnelProtocol tunnel_protocol;
}

enum ApplicationProtocol {
 // Simply copy bytes
 UNSPECIFIED/TCP = 0;
 // Add PROXY protocol headers before copying bytes
 PROXY = 2;
}

```

A sandwiched waypoint has `tunnel_protocol = HBONE` and `native_tunnel = false`. It may have any application protocol. `TCP` would allow the "simple http" gateway case, or PROXY for more advanced waypoint implementations. 

The following example demonstrates why GatewayAddress might need it's own tunnel protocol

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: hedgerow
spec:
  gatewayClassName: nginx
  listeners:
  - name: foo  
    # Will match listener based on rule #1 above
    hostname: foo.hedgerow.svc.cluster.local
    port: 80
    protocol: HTTP
  - name: bar
    hostname: bar.hedgerow.svc.cluster.local
    port: 80
    protocol: HTTP
```
