### ISSUE TITLE
Having RequestAuthentication with 50+ JWT issuers causes significant Envoy performance degradation

### ISSUE THREAD

**Issue by videlov** [istio/istio#49691]
**Describe the feature request**

We have an customer use-case at SAP when we need 50+ different JWT issuers configured in a RequestAuthentication. For example:

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: xxx-request-authentication
  namespace: istio-ingress
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: https://issuer1/oauth/token
    jwksUri: https://issuer1/token_keys
  - forwardOriginalToken: true
    issuer: https://issuer2/oauth/token
    jwksUri: https://issuer2/token_keys
  ...
  - forwardOriginalToken: true
    issuer: https://issuer50/oauth/token
    jwksUri: https://issuer50/token_keys
```

For this multi-tenancy case each tenant has a separate identity provider. When processing array of JWT providers, [see code](https://github.com/hzxuzhonghu/istio/blob/cca6484d31375dc7309ff7849b3ad5c541411533/pilot/pkg/security/authn/policy_applier.go#L371-L375):

```
	// If there are more than one provider, filter should OR of
	// {P1, P2 .., AND of {OR{P1, allow_missing}, OR{P2, allow_missing} ...}}
	// where the innerAnd enforce a token, if provided, must be valid, and the
	// outer OR aids the case where providers share the same location (as
	// it will always fail with the innerAND).
```

Istio creates an `envoy_jwt.JwtRequirement` with OR for all providers and additionally has the complexity for having no token option and creates additional AND array for each provider (token OR no-token). This could lead to some heavy processing on envoy side when having many JWT providers.

we assume envoy processes this configuration and verifies incoming JWT tokens in a serial way going one by one:
https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/jwt_authn

***Performance tests***

Configuration similar to:
1 gateway pod
5 fortio pods as echo server
Executing fortio from ccloud
16 connections (4*4CPU = 16 threads)
command: `fortio load -H Authorization:"Bearer $TOKEN" -qps 92 -c 16 -t 5m -a -labels "initial auth single" $URL`

***Results***:

With 1 JWT issuer:
![image](https://github.com/istio/istio/assets/10164673/f934f91c-a240-4812-b86a-56f682b326ab)

CPU:
![image](https://github.com/istio/istio/assets/10164673/ae537be5-7893-43de-81b0-62113d15f02c)

CPU pprof:
![image](https://github.com/istio/istio/assets/10164673/8a691b82-a678-46e1-a461-3f9ee123f18e)

---

With 50 JWT issuers:
![image](https://github.com/istio/istio/assets/10164673/d4f34612-14d0-430c-8eb0-6af4abe5bea0)

CPU:
![image](https://github.com/istio/istio/assets/10164673/5f58945d-4115-4ead-98af-e3879db7fd71)

CPU pprof:
![image](https://github.com/istio/istio/assets/10164673/3be96535-77d7-4fc4-bc84-25be3b4605a2)

**Describe alternatives you've considered**

* Customer did try scaling up horizontally the `istio-ingressgateway` which generally uses lot of resources for basic request loads. It brings improvements but it is not feasible at the moment and not the bottleneck because they want to apply JWT configuration individually to workload sidecars.

* We advised customer to try using 50 RA (RequestAuthentication's) and see if there are performance improvements. When handling single JWT provider like mentioned [in code](https://github.com/hzxuzhonghu/istio/blob/cca6484d31375dc7309ff7849b3ad5c541411533/pilot/pkg/security/authn/policy_applier.go#L351C2-L351C84):
```yaml
// If there is only one provider, simply use an OR of {provider, `allow_missing`}.
```

having 50 RAs we assumed it would generate Envoy configuration like `AND of {OR{P1, allow_missing}, OR{P2, allow_missing}`. This did not bring noticeable improvements.

* We will currently try to to see if a configuration like `OR of {P1, P2, ... P50}` with a custom Istio image will bring anything meaningful.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Additionally idea would be if Envoy when verifying could map the JWT token to provider per `iss` [claim](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1) and not iterating the map. Do you think is feasible at all or there are other limitations. We could also ask Envoy?

If more details are needed or you want to discuss, you can ping me on Slack. Many Thanks in advance.

**Comment by linsun** [comment]
Hi @videlov - what Istio build are you using?

cc @hzxuzhonghu or @howardjohn if they are aware of anything related to this.

**Comment by videlov** [comment]
Hi @linsun, we are currently using the [latest release Istio 1.20.3](https://github.com/istio/istio/releases/tag/1.20.3)

fyi, we did advise customer to apply EnvoyFilter that will patch `envoy.filters.http.jwt_authn` filter to have only OR list of providers and inline JWKS keys, e.g.:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt-issuers-or-list
  namespace: <NAMESPACE>
spec:
  workloadSelector:
    labels:
      app: <APP_LABEL_SELECTOR>
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.jwt_authn
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.http.jwt_authn
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
          providers:
            origins-0:
              forward: true
              issuer: ...
              localJwks:
                inlineString: |-
                ...
            ...
            origins-49:
              forward: true
              issuer: ...
              localJwks:
                inlineString: |-
                ...
          rules:
          - match:
              prefix: /
            requires:
              requiresAny:
                requirements:
                - providerName: origins-0
                ...
                - providerName: origins-49
```

and he said performance throughput improved slightly from 1830 req/s to 2142 req/s with his setup. for comparison, same scenario with 1 JWT issuer has a throughput of 6600 req/s so its factor 3x.

CPU with 1 JWT:
![image](https://github.com/istio/istio/assets/10164673/1655fcbe-c1de-481e-9fcc-9a7a86da81db)

CPU with 50 JWTs:
![image](https://github.com/istio/istio/assets/10164673/5329d8ce-9cbb-4412-a0ff-487f294dd7d9)
