### ISSUE TITLE
AuthorizationPolicy CUSTOM external-authz should support more rules (like request.auth.principal is *)

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#49716]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Currently, AuthorizationPolicy CUSTOM can support rule "to", with path. It is good.
However, it does not support "when", not support "from".

For below common requirement:
- If token exists in "authorizaiton: Bearer", need do CUSTOM action.
- If token not exists, bypass this authorizationpolicy.
Cannot be supported.

**Describe alternatives you've considered**
I will send the to ext-auth server even has no token, which bring perf concern. (some health api is allowed has no token.)

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[*] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

This is supported:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: try01-ext-authz
  namespace: onecloudsol-dev
spec:
  action: CUSTOM
  provider:
    name: ext-authz-server-grpc
  rules:
  - to:
    - operation:
        paths:
        - /try01/version
  selector:
    matchLabels:
      app: try01
```

This is not support:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: try01-ext-authz
  namespace: onecloudsol-dev
spec:
  action: CUSTOM
  provider:
    name: ext-authz-server-grpc
  rules:
  - to:
    - operation:
        paths:
        - /try01/version
    when:
    - key: request.auth.principal
      values:
      - '*'
  selector:
    matchLabels:
      app: try01
```

Error for "when not support": 
```
error: authorizationpolicies.security.istio.io "try01-ext-authz" could not be patched: admission webhook "validation.istio.io" denied the request: configuration is invalid: invalid policy try01-ext-authz.onecloudsol-dev: request.auth.principal is currently not supported with CUSTOM action
```

Error for "from not support"
```
error: authorizationpolicies.security.istio.io "try01-ext-authz" could not be patched: admission webhook "validation.istio.io" denied the request: configuration is invalid: invalid policy try01-ext-authz.onecloudsol-dev: From.Namespaces is currently not supported with CUSTOM action
```
