### ISSUE TITLE
Unit test fails if Kubernetes configuration has file references

### ISSUE THREAD

**Issue by esnible** [istio/istio#4973]
Using HEAD from April 16th

Running `make` or `go test -p 1  ./pilot/pkg/serviceregistry/kube -run TestServices
` with KUBECONFIG and pilot/pkg/kube/config pointed to a configuration that contains file references causes the test to fail:

```
--- FAIL: TestServices (0.01s)
	controller_test.go:40: invalid configuration: unable to read certificate-authority ca-hou02-istio07.pem for istio07 due to open ca-hou02-istio07.pem: no such file or directory
FAIL
FAIL	istio.io/istio/pilot/pkg/serviceregistry/kube	0.055s
```

This is a problem for IBM Cloud, which has a file reference for the certificate authority, e.g.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca-hou02-istio07.pem
    server: https://169.47.72.34:23478
  name: istio07
```

A work-around for these errors is to edit your $KUBECONFIG and/or _pilot/pkg/kube/config_ so that the files are referred to by absolute path, e.g.

```
cluster:
  certificate-authority: /home/vagrant/golang/src/istio.io/istio/pilot/pkg/kube/ca-hou02-istio07.pem
```

This is related to #4908 which describes a similar problem in E2E tests.
