### ISSUE TITLE
"Copy JWT Claims to HTTP Headers" not work as expect when I have Chinese character in jwt

### ISSUE THREAD

**Issue by DreamParadise** [istio/istio#49779]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Raw JWT Payload：
![image](https://github.com/istio/istio/assets/3191003/5df49f1e-d0aa-40c0-a350-c049d1171416)

request authentication:
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt
  namespace: xxx
spec:
  jwtRules:
    - issuer: oxxx
      outputClaimToHeaders:
        - claim: empName
          header: x-claim-emp-name
  selector:
    matchLabels:
```
read from header in target pod
![image](https://github.com/istio/istio/assets/3191003/06a3980e-08e8-4e59-a97c-564493ac74b0)

### Version

```Text
helm chart: Istio (102.3.1+up1.18.2)
```
