### ISSUE TITLE
istio-proxy got stuck in podInitializing status. Init containers can't startup and external traffic blocked for init containers while istio-proxy stuck

### ISSUE THREAD

**Issue by mp1947** [istio/istio#49787]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have micro-service gitlab installation in k8s cluster.
I use istio with CNI plugin + cilium CNI, installed with command: `istioctl upgrade -f istiooperator.yaml`

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-config
spec:
  profile: default
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    cni:
      enabled: true
```

I have problem with two gitlab services: gitlab-sidekiq and gitlab-webserver , which have several init containers and they starts before istio-proxy. 
holdApplicationUntilProxyStarts set to true in IstioOperator.

part of init containers starts before istio-proxy and they need internet access to the database and redis outside the k8s.

But they can't reach db/redis because of connection problems: `Error checking main: connection to server at "*.*.*.*", port 5432 failed: Connection refused`

istio-proxy has PodInitializing status all the time and his status never changes:

<img width="1352" alt="Screenshot 2024-03-07 at 13 49 08" src="https://github.com/istio/istio/assets/6707562/3fac1a88-2a77-451e-9388-d90e9c4cebed">

Istio-validation logs:

<img width="1431" alt="Screenshot 2024-03-07 at 13 50 13" src="https://github.com/istio/istio/assets/6707562/98ed781f-9a19-4e83-bf58-e26dd50ea814">

In istiod logs i see the following all the time:

`2024-03-07T10:40:48.960007Z    info    Sidecar injection request for gitlab/gitlab-toolbox-77b8ff87c5-***** (actual name not yet known)` and nothing more.

Any workarounds for this issue ? Is there any annotation for injection as the very first container?

### Version

```Text
└[~]> istioctl version
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (21 proxies)

└[~]> kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6

└[~]> cilium version
cilium-cli: v0.16.0 compiled with go1.22.1 on darwin/arm64
cilium image (default): v1.15.1
cilium image (stable): v1.15.1
```
