### ISSUE TITLE
Apply LuaPerRoute filter to the weighted cluster

### ISSUE THREAD

**Issue by style95** [istio/istio#49781]
According to the guide of [Per-Route configuration for the lua filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#per-route-configuration) in Envoy, we can apply the [LuaPerRoute](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#envoy-v3-api-msg-extensions-filters-http-lua-v3-luaperroute) configuration on the virtual host, route, or weighted cluster.

I could apply LuePerRoute against a certain virtual host and route but I could not find a way to match a weighted cluster.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-lua-per-route
  namespace: sample
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        name: http.8080
        vhost:
          name: hello-world.com:80
          route:
            name: test-route
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.lua:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
            disabled: true
  workloadSelector:
    labels:
      istio: istio-ingressgateway-sample

```

In [the spec of EnvoyFilter.RouteConfigurationMatch](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch), it seems it supports route name match and VirtualHostMatch but no match for weighted cluster.

<img width="1349" alt="image" src="https://github.com/istio/istio/assets/3447251/84ef0ec1-74d7-43bc-afee-b3528753cae2">

Isn't it supported yet or do I miss anything?
