### ISSUE TITLE
WASM introduces bad (wrongly extracted?) metrics in Envoy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49807]
Prometheus shows
```
envoy_extension_config_discovery_http_filter_extenstions_istio_io_wasmplugin_default_bad_filter_config_rbac{authz_enforce_result="allowed"} 0
```

from
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: bad-filter-config
  namespace: default
spec:
  sha256: f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
  url: https://bad-url.wasm
---
```
