### ISSUE TITLE
istioctl experimental describe pod missing portLevel mTLS mode

### ISSUE THREAD

**Issue by taitelman** [istio/istio#49802]
istioctl provides many experimental CLI flags. one of I use to detect mTLS strict mode.
for example:
```istioctl experimental describe pod myapp.mynamespace```

```
Pod: myapp.ns
   Pod Revision: default
   Pod Ports: 15090 (istio-proxy), 6001 (myapp), 7001 (myapp), 9080 (myapp), 9100 (myapp)
--------------------
Service: myapp.myns
   Port: grpc 6001/GRPC targets pod port 6001
   Port: grpc-d2d 7001/GRPC targets pod port 7001
   Port: http 9080/HTTP targets pod port 9080
   Port: http-prom 9100/HTTP targets pod port 9100
6001 DestinationRule: internal-mtls.istio-system for "*.svc.cluster.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL
7001 DestinationRule: internal-mtls.istio-system for "*.svc.cluster.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL
9080 DestinationRule: internal-mtls.istio-system for "*.svc.cluster.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL
9100 DestinationRule: internal-mtls.istio-system for "*.svc.cluster.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL
--------------------
Service: d-headless.myns
   Port: grpc 6001/GRPC targets pod port 6001
DestinationRule: internal-mtls.istio-system for "*.svc.cluster.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL   <--------------- look at this line
--------------------
Service: dispatcher-to-dispatcher.ibm-secretsmanager
   Port: grpc 7001/GRPC targets pod port 7001
DestinationRule: internal-mtls.istio-system for "*.svc.cluster.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL <--------------- look at this line
--------------------
Effective PeerAuthentication:
   Workload mTLS mode: STRICT  <--------------- look at this line
Applied PeerAuthentication:
   mtls.istio-system
```

the above output is if you use PeerAuthentication with STRICT mode and a simple DestinationRule like:
```

apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: mtls
  namespace: istio-system
spec:
  mtls:
    mode: STRICT

--- 

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: internal-mtls
  namespace: istio-system
spec:
  host: '*.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

so what is the problem ?
If edit the DR to be based on port level:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: internal-mtls
  namespace: istio-system
spec:
trafficPolicy:
    portLevelSettings:
    - port:
        number: 9080  
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 6001 
      tls:
        mode: DISABLE
```

if applying the "port level" DR  the `istioctl experimental describe pod` command will no longer show the mTLS mode , I won't see `Traffic Policy TLS Mode: ISTIO_MUTUAL` . it will only say there is some vague portLevelSettings and will not fetch the relevant mode value for each port .

**Describe the feature request**
to show the mTLS mode for evvery port even if DR is using portLevelSettings.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
