### ISSUE TITLE
Istio Service Entry Load balancing not accurate 

### ISSUE THREAD

**Issue by vinay-g** [istio/istio#49832]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Using service entry with weights and configured with LEAST_REQUEST in destination rules, the traffic split between endpoints is not accurate. There is higher traffic going to the lower weighted endpoint. 
My setup for testing has 2 kubernetes services with weights configured 95/5
The client is on the same cluster so no ingress is used, i tried with ingress (PASS THROUGH) as well similar results were seen.
The servers are hello world test applications from istio samples.

Not sure if this is a bug or some tuning that is missing from my setup.

Service Entry
```
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: test-se
    namespace: admiral-sync
  spec:
    addresses:
    - 241.2.14.4
    endpoints:
    - address: helloworld-v1.helloworld.svc.cluster.local
      ports:
        http: 5000
      weight: 95
    - address: helloworld-v2.helloworld.svc.cluster.local
      ports:
        http: 5000
      weight: 5
    hosts:
    - test.helloworld.global
    location: MESH_INTERNAL
    ports:
    - name: http
      number: 80
      protocol: http
    resolution: DNS
```
Destination rule 
```
- apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    name: test
    namespace: admiral-sync
  spec:
    host: test.helloworld.global
    trafficPolicy:
      connectionPool:
        http:
          http2MaxRequests: 1000
          maxRequestsPerConnection: 5
      loadBalancer:
        simple: LEAST_REQUEST
      outlierDetection:
        consecutive5xxErrors: 0
        consecutiveGatewayErrors: 0
      tls:
        mode: ISTIO_MUTUAL
```

Example output in grafana

![image](https://github.com/istio/istio/assets/3385702/5bac4754-713a-466a-8245-3786bef16d30)

Grafana dashboard
[proxy-dashboard.json](https://github.com/istio/istio/files/14554926/proxy-dashboard.json)

### Version

```Text
ISTIO
control plane version: 1.20.1
data plane version: 1.20.1 (5 proxies)

KUBERNETES
Client Version: v1.25.16
Kustomize Version: v4.5.7
Server Version: v1.25.16+k3s4
```
