### ISSUE TITLE
Istio telemetry with als extension provider seems to have some sort of session stickiness

### ISSUE THREAD

**Issue by joelmathew003** [istio/istio#49833]
### Discussed in https://github.com/istio/istio/discussions/49831

<div type='discussions-op-text'>

<sup>Originally posted by **joelmathew003** March 11, 2024</sup>
I have a telemetry resource in my test namespace which looks like:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
spec:
  accessLogging:
  - providers:
    - name: my-http-als
    - name: my-tcp-als
```
and have described these providers in the istio configmap mesh 
```
apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: JSON
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      extraStatTags:
      - request_method
      - request_path
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enableEnvoyAccessLogService: true
    extensionProviders:
    - envoyHttpAls:
        port: 9999
        service: app.my-ns.svc.cluster.local
      name: my-http-als
    - envoyTcpAls:
        port: 9999
        service: app.my-ns.svc.cluster.local
      name: my-tcp-als
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
```
My `app` want the access logs of the traffic in my test namespace and does some processing. I have an hpa resource created for `app` which scales on 60% utilization. On some stress testing(~200 tps) and new replicas are created by hpa, I see that the older replicas receive most of the traffic, even after the new replicas are created and ready. Sometimes the older replicas cross the limit and restarts, on which the newer replicas start receiving the load. Is there some sort of session stickiness that causes this? Ideally I want the load to get distributed evenly among all ready replicas.</div>
