### ISSUE TITLE
Customize Span Name

### ISSUE THREAD

**Issue by drewcorlin1** [istio/istio#49854]
**Describe the feature request**
Add the ability to customize span names based on attributes of the incoming request.

I'm emitting spans to Jaeger via the OpenTelemetry collector. The root spans coming from the ingress gateway are all named identically: "istio-ingressgateway.istio-system egress ${my API domain}". This makes it pretty difficult to visually grep the page to distinguish different API calls from one another. https://github.com/istio/istio/issues/21100 mentioned a way to customize this but it's pretty unergonomic in my opinion. My team doesn't typically name routes on our VS so it would be a large undertaking and also would require us to complicate our VirtualServices significantly (currently we use a lot of prefix-based rules to route multiple methods + paths to a given workload, but as far as I understand it we'd need each method + endpoint combination to have it's own rule in the VS to leverage the approach mentioned in that issue).

Instead I'd propose functionality similar to [tracing's custom tags](https://istio.io/latest/docs/reference/config/telemetry/#Tracing-CustomTag) (admittedly I have almost no idea if envoy has the features to support something like this). In my case I run a WasmPlugin at the istio ingress gateway that adds an `operation-id` header to incoming requests (determining it from an OpenAPI spec), and it would be amazing to be able to use that header as the span name.

**Describe alternatives you've considered**

https://github.com/istio/istio/issues/21100

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by xhdnoah** [comment]
I have encountered the same problem looking for a solution

**Comment by drewcorlin1** [comment]
I got around this via the [opentelemetry span processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanprocessor) since I'm using the OTel collector in my stack. Here's the relevant part of my helm chart values (using the otel helm chart)
```yaml
config:
  processors:
    span:
      name:
        from_attributes: [http.method, http.url]
        separator: " - "
      include:
        match_type: strict
        attributes:
          - key: istio.canonical_service
            value: istio-ingressgateway
  service:
    pipelines:
      traces:
        processors: [span]
# ...
```
