### ISSUE TITLE
No access logs for responses with response_code=0

### ISSUE THREAD

**Issue by svenmueller** [istio/istio#49853]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In our Prometheus istio metrics (`istio_requests_total`) we see requests with labels `reponse_code=0` and `response_flagsDC`. To be able to see more details about these failed requests, we enabled filtered access logs via Istio Telemetry API using the following API resource

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-exception-logging
spec:
  accessLogging:
    - providers:
        - name: file-json
      filter:
        expression: "response.code >= 500 || response.code < 200"
```

After that we can see access logs for response code >= `500`  and also < `200` but there are no access logs with response_code `0` logged (allthough we can see them in the istio metrics).

Any idea? is this a bug, is this somehow expected or is there an issue with the used filter expression?

Thx a lot,
Sven

### Version

```Text
$ istioctl version
client version: 1.20.3
control plane version: 1.18.7
data plane version: 1.18.7 (2 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.4
Kustomize Version: v4.5.7
Server Version: v1.26.12-gke.1111000

$ helm version --short
v3.14.1+ge8858f8
```

**Comment by howardjohn** [comment]
Its in your filter. `"!has(response.code) || response.code >= 500"`  would probably be what you want; there is no `response.code` attribute at all on the failures

**Comment by howardjohn** [comment]
This is a super subtle and easy mistake to make, if you have any feedback on what changes could have made that solveable (docs, etc), please let us know

**Comment by svenmueller** [comment]
Using filter expression `"!has(response.code) || response.code >= 500"` works!

Note: The logged access log events do actually have the field `response_code=0`.

**Comment by howardjohn** [comment]
I believe it's a quirk of the logging vs filtering that it will plug in default values for unset fields. Really tricky to get right though, so needs some more investigation IMO

**Comment by yasithab** [comment]
Could this solution be CPU-intensive? I'm asking because I've noticed spikes in the Istio-proxy sidecars while using the following setting.

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: "response.code >= 400"
```
