### ISSUE TITLE
Update on ServiceEntry targetPort doesn't trigger update on EDS

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49878]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Here is the ServiceEntry. I change the `targetPort` from 20000 to 9080, but this doesn't trigger the update on EDS. The traffic still goes to port 20000 on endpoints.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-1
spec:
  hosts:
  - '*.bookinfo.com'
  ports:
  - number: 9090
    protocol: HTTP
    name: port-4
    targetPort: 20000
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
```

### Version

```Text
client version: 1.22-alpha.97536b6c3b72353b8f58aa22ed23a761034aa201
control plane version: 1.22-alpha.42572fab5be79af8de284953ec72cbf439631da8
data plane version: 1.22-alpha.42572fab5be79af8de284953ec72cbf439631da8 (6 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
