### ISSUE TITLE
It alway return 404 when I call api via istio gateway

### ISSUE THREAD

**Issue by DreamParadise** [istio/istio#49877]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

My authorization policy config:
```yml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: api
  namespace: prod
spec:
  action: DENY
  rules:
    - to:
        - operation:
            methods:
              - GET
  selector:
    matchLabels:
      auth-required: auth
```
If I call my service api inside k8s it will return 403 with `RBAC: access denied`, it's what expected.
But if I call outside k8s via istio gateway it return 404 with `Sorry, Page Not Found`.

### Version

```Text
rancher-istio:102.5.0+up1.19.6
```
