### ISSUE TITLE
Update Destination rule to include attributes value

### ISSUE THREAD

**Issue by Justin-DynamicD** [istio/istio#49870]
Currently the destination rule only supports `name`, `path`, `ttl` for defining a cookie for sticky sessions. Envoy allows another value: `attributes`.

This additional attribute would be really handy as it would eliminate the need to use lua scripts on an `EnvoyFilter` as a workaround for adding things like SecureSite or the upcoming partitioned attribute to cookies.

Example:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myrule
  namespace: awesome-ns
spec:
  host: myapp.awesome-ns.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: sessionID
          path: /
          ttl: 0s
          attributes:
            - 'SameSite=None'
            - 'Secure'
            - 'Partitioned'
```

[DestinationRule](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB-HTTPCookie)

[Envoy attributes support](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-msg-config-route-v3-routeaction-hashpolicy-cookie)
>Any extra documentation required to understand the issue.
