### ISSUE TITLE
Service on port 15021 cannot be accessed

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49905]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I create a Service defined on port 15021, with no errors or warnings. However, I cannot get `ratings` service and there is even no `name: "15021"` item in RDS.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 15021
    targetPort: 9080
    name: http
```

### Version

```Text
client version: 1.21.0-rc.1
control plane version: 1.21.0-rc.1
data plane version: 1.21.0-rc.1 (6 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by qts0312** [comment]
Maybe this issue is same as #41239. However, I think it is better to give a warning during validation, instead of silence the Service with only debug items in the log.

**Comment by qts0312** [comment]
However, when I define ServiceEntry on port 15021. I cannot get correct service as well, and there is even no debug items like `buildSidecarOutboundListeners: skipping service port %s:%d for node %s as it conflicts with static listener` in the log. Here may also need some warns?
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-0
spec:
  hosts:
    - www.bookinfo.com
  ports:
    - number: 10521
      name: http
      protocol: HTTP
      targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: productpage
```
[se-15021.log](https://github.com/istio/istio/files/14600880/se-15021.log)
