### ISSUE TITLE
JWT Token always fails with 403 in Istio 1.21.0

### ISSUE THREAD

**Issue by juanes30** [istio/istio#49913]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I upgrade Istio using Istioctl from version 1.20.3 to 1.21.0 all requests to our api fail with http status code 403.

The following configuration files work correctly in version 1.20.3:

**AuthorizationPolicy**

```
apiVersion: "security.istio.io/v1"
kind: "RequestAuthentication"
metadata:
  name: "foo-jwt"
  namespace: foo
spec:
  selector:
    matchLabels:
      app: foo
  jwtRules:
    - issuer: "https://example.keycloak.com/realms/realm-name"
      jwksUri: "https://example.keycloak.com/realms/realm-name/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-foo
  namespace: foo
spec:
  selector:
    matchLabels:
      app: foo
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: [ "https://example.keycloak.com/realms/realm-name/*" ]
      to:
        - operation:
            methods: [ "GET", "POST", "PUT", "OPTIONS", "DELETE", "PATCH" ]
            paths: [ "/api/v1/some-path/*" ]
      when:
        - key: request.auth.claims[emailVerified]
          values: [ "true" ]
        - key: request.auth.claims[roles]
          values: [ "admin", "user" ]
```

The previous configuration works flawlessly with Istio version 1.20.3.

As a test we apply the following AuthorizationPolicy without deleting the previous configuration and all the requests work again but it is because in the following configuration it overrides any validation of the token

```
apiVersion: "security.istio.io/v1"
kind: "AuthorizationPolicy"
metadata:
  name: "http-foo"
  namespace: foo
spec:
  selector:
    matchLabels:
      app: foo
  rules:
    - to:
        - operation:
            methods: ["GET", "POST", "PUT", "OPTIONS", "DELETE"]
```

### Version

```Text
istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (71 proxies)

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-eks-c417bb3
```

**Comment by kyessenov** [comment]
Please supply a config dump from Envoy to further triage (specifically jwt_authn filter and RBAC filter).

**Comment by juanes30** [comment]
This is the config dump generated

[config_dump.json](https://github.com/istio/istio/files/14609660/config_dump.json)

**Comment by ebensom** [comment]
We are facing the same issue. It seems that in Istio 1.21.0, the URI-like issuers are parsed erroneously into `<ISS>/<SUB>`. Snippet from the pushed envoy config:

```
                          "and_ids": {
                           "ids": [
                            {
                             "metadata": {
                              "filter": "envoy.filters.http.jwt_authn",
                              "path": [
                               {
                                "key": "payload"
                               },
                               {
                                "key": "iss"
                               }
                              ],
                              "value": {
                               "string_match": {
                                "exact": "https:"
                               }
                              }
                             }
                            },
                            {
                             "metadata": {
                              "filter": "envoy.filters.http.jwt_authn",
                              "path": [
                               {
                                "key": "payload"
                               },
                               {
                                "key": "sub"
                               }
                              ],
                              "value": {
                               "string_match": {
                                "prefix": "/kymatest.accounts400.ondemand.com/"
                               }
                              }
                             }
                            }
                           ]
                          }

```

**Comment by kyessenov** [comment]
The bug is in xDS:
```
                         {
                          "metadata": {
                           "filter": "envoy.filters.http.jwt_authn",
                           "path": [
                            {
                             "key": "payload"
                            },
                            {
                             "key": "roles"
                            }
                           ],
                           "value": {
                            "or_match": {
                             "value_matchers": [
                              {
                               "list_match": {
                                "one_of": {
                                 "string_match": {
                                  "exact": "user"
                                 }
                                }
                               }
                              },
                              {
                               "string_match": {
                                "exact": "user"
                               }
                              }
                             ]
                            }
                           }
                          }
                         }
```

It seems to unroll the value list with multiple matchers, instead of one matcher with a list value.

**Comment by kyessenov** [comment]
The issue for repeated values and not values is the difference in how JWT is matched between Envoy and Istio. I'll send a patch for that. Re: iss difference, I'll look further. Sorry about this, we don't have a good coverage for this that would have caught it earlier.

**Comment by jankotulak** [comment]
Same issue here with `AuthorizationPolicy` spec defined as:

```
spec:
  action: DENY
  rules:
  - when:
    - key: request.auth.audiences
      notValues:
      - aud1
      - aud2
```

This is now (in v1.21.1) translated to this envoy config:
```
{
    "name": "envoy.filters.http.rbac",
    "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC",
        "rules": {
            "action": "DENY",
            "policies": {
                "ns[<redacted_ns>]-policy[<redacted_name>]-rule[0]": {
                    "permissions": [
                        {
                            "and_rules": {
                                "rules": [
                                    {
                                        "any": true
                                    }
                                ]
                            }
                        }
                    ],
                    "principals": [
                        {
                            "and_ids": {
                                "ids": [
                                    {
                                        "not_id": {
                                            "or_ids": {
                                                "ids": [
                                                    {
                                                        "metadata": {
                                                            "filter": "istio_authn",
                                                            "path": [
                                                                {
                                                                    "key": "request.auth.audiences"
                                                                }
                                                            ],
                                                            "value": {
                                                                "string_match": {
                                                                    "exact": "aud1"
                                                                }
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "metadata": {
                                                            "filter": "istio_authn",
                                                            "path": [
                                                                {
                                                                    "key": "request.auth.audiences"
                                                                }
                                                            ],
                                                            "value": {
                                                                "string_match": {
                                                                    "exact": "aud2"
                                                                }
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        },
        "shadow_rules_stat_prefix": "istio_dry_run_allow_"
    }
}
```

vs this for v1.20.x:
```
{
    "name": "envoy.filters.http.rbac",
    "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC",
        "rules": {
            "action": "DENY",
            "policies": {
                "ns[<redacted_ns>]-policy[<redacted_name>]-rule[0]": {
                    "permissions": [
                        {
                            "and_rules": {
                                "rules": [
                                    {
                                        "any": true
                                    }
                                ]
                            }
                        }
                    ],
                    "principals": [
                        {
                            "and_ids": {
                                "ids": [
                                    {
                                        "not_id": {
                                            "metadata": {
                                                "filter": "envoy.filters.http.jwt_authn",
                                                "path": [
                                                    {
                                                        "key": "payload"
                                                    },
                                                    {
                                                        "key": "aud"
                                                    }
                                                ],
                                                "value": {
                                                    "or_match": {
                                                        "value_matchers": [
                                                            {
                                                                "string_match": {
                                                                    "exact": "aud1"
                                                                }
                                                            },
                                                            {
                                                                "string_match": {
                                                                    "exact": "aud2"
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        },
        "shadow_rules_stat_prefix": "istio_dry_run_allow_"
    }
}
```

@kyessenov do you see any issue why this throws "RBAC: access denied" in v1.21.1
