### ISSUE TITLE
Local Rate Limiting EnvoyFilter stops working with traffic.sidecar.istio.io/includeInboundPorts annotation.

### ISSUE THREAD

**Issue by akashjain971** [istio/istio#49917]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am testing local rate-limiting EnvoyFilters in my local minikube and I have an obsevation.
The rate limiting works fine for httpbin app running on port 8000 with the following EnvoyFilter.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-rate-limit
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.20.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|8000
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_key: getquota
                descriptor_value: getquota
                headers:
                - name: :path
                  string_match:
                    safe_regex:
                      regex: /get
                - name: :method
                  string_match:
                    safe_regex:
                      regex: get|GET
                - name: user-id
                  string_match:
                    exact: abcd
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              descriptors:
                - entries:
                  - key: getquota
                    value: getquota
                  token_bucket:
                    max_tokens: 5
                    tokens_per_fill: 5
                    fill_interval: 30s
              filter_enabled:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enabled
              filter_enforced:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enforced
              stat_prefix: http_local_rate_limiter
              token_bucket:
                fill_interval: 1s
                max_tokens: 100
                tokens_per_fill: 100
  workloadSelector:
    labels:
      app: httpbin
```

But it stops working when I add this annotation to the httpbin deployment spec template.
[traffic.sidecar.istio.io/includeInboundPorts: "8000"](https://istio.io/latest/docs/reference/config/annotations/#SidecarTrafficIncludeInboundPorts).
It starts working again the moment I remove this annotation from the deployment and the pod restarts.
No change in EnvoyFilter is made during this process.
```
template:
  metadata:
    annotations:
      traffic.sidecar.istio.io/includeInboundPorts: "8000"
```

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.20.2
data plane version: 1.20.2 (3 proxies)

$ kubectl version 
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.16
```
