### ISSUE TITLE
HTTP external calls are returning 502

### ISSUE THREAD

**Issue by kirankumar-grootan** [istio/istio#49928]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

when performing http request to public network 502 is returning but works fine in 443
```
curl -Lvvv http://www.google.com
* processing: http://www.google.com
*   Trying 142.250.182.132:80...
* Connected to www.google.com (142.250.182.132) port 80
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< content-length: 110
< content-type: text/plain
< date: Fri, 15 Mar 2024 04:57:36 GMT
< server: envoy
< 
* Connection #0 to host www.google.com left intact
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: protocol error
```

added serviceentry too
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-https
  namespace: ezto
spec:
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```

### Version

```Text
istioctl --kubeconfig kubeconfig.yaml version
client version: 1.20.3
control plane version: 1.22-alpha.d8003c4dbdfade2b2640f4ca41e58a92bc235748
data plane version: 1.22-alpha.503c3c25acece2826d11f2cfcb0a1de58d310bf8 (10 proxies), 1.22-alpha.d8003c4dbdfade2b2640f4ca41e58a92bc235748 (2 proxies)

kubectl --kubeconfig kubeconfig.yaml version   
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by kirankumar-grootan** [comment]
If I remove protocol it works fine. But if I enforce its not working

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-https
  namespace: ezto
spec:
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
  - number: 80
    name: http
  resolution: DNS
```
