### ISSUE TITLE
Traffic Routing - Virtual Service

### ISSUE THREAD

**Issue by TejasD10** [istio/istio#49966]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are on GKE with Istio running as a sidecar.

Problem Statement: I am attempting to create environments  using K8s namespaces for my service and running into routing problems.

> Note:  We have to prefix our endpoints with `awesome-service` as there are other network level routing rules via that allow traffic based on that prefix

Service Endpoint for DEV under the namespace "service-dev"
`/awesome-service`

Virtual Service Configuration:

```
gateways:
  - default/ingress-gateway
  http:
  - match:
    - headers:
        cookie:
           regex: ^(.*?;)?\s*(cdt=on)(;.*)?$
      uri:
        prefix: /awesome-service
    route:
    - destination:
        host: awesome-service.service-dev.svc.cluster.local
        port:
          number: 3000
        subset: v1
      weight: 100
```

Service endpoint for DEV2 under the namespace "service-dev2"
`/awesome-service/dev2`

Virtual Service Configuration:

```
gateways:
  - default/ingress-gateway
  http:
  - match:
    - headers:
        cookie:
           regex: ^(.*?;)?\s*(cdt=on)(;.*)?$
      uri:
        prefix: /awesome-service/dev2 # Tried withe exact but behavior is the same
    route:
    - destination:
        host: awesome-service.service-dev2.svc.cluster.local
        port:
          number: 3000
        subset: v1
      weight: 100
```

The behavior I am notificing is that both the below calls go the `/awesome-service` deployment.
`/awesome-service`
`/awesome-service/dev2`

Please let me know your thoughts.

### Version

```Text
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:39:12Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.15-gke.1115000", GitCommit:"8922ac8b63ea86d2286554c8503c86ce06c628e9", GitTreeState:"clean", BuildDate:"2023-11-09T11:02:31Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

❯ istioctl version
client version: 1.19.0
control plane version: 1.18.2
data plane version: 1.18.2 (257 proxies)
```
