### ISSUE TITLE
Gateway helm chart rendering no longer succeeds when setting CPU resource field to ~

### ISSUE THREAD

**Issue by shydefoo** [istio/istio#49962]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

On previous versions of istio (before v1.21.0), this configuration had no issues:
```
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: ~
      memory: 1Gi
```

However, on v1.21.0, passing this additional values file throws this error:
```
➜ helm template . -f my_values.yaml
Error: values don't meet the specifications of the schema(s) in the following chart(s):
gateway:
- resources.limits.cpu: Invalid type. Expected: string, given: null
```

Upon inspecting the helm chart, it seems that a new `defaults` field is introduced, and fields under `defaults` get overwritten by the top level fields of the same name. The workaround seems to be to overwrite the fields under `defaults`, ie:
```
defaults: 
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: ~
      memory: 1Gi
```
Is there a way to unset the cpu field without having to move `resources` under `defaults`?

### Version

```Text
➜ istioctl version
client version: 1.19.3
control plane version: 1.20.3
data plane version: 1.20.3 (7 proxies)
➜ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1286000
➜ helm version --short
v3.13.1+g3547a4b
```
