### ISSUE TITLE
Selective ext proc filters - how?

### ISSUE THREAD

**Issue by tfrokt** [istio/istio#49961]
I would like to patch the envoy config by adding an ext proc [[1](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-externalprocessor)] for _some_ routes.

This is my EnvoyFilter (which adds the ext proc to the http filter):
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: <our name>
  namespace: <our namespace>
spec:
  workloadSelector:
    labels:
      edgeType: <edge label>
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_proc
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
          value:
            stat_prefix: <our stat prefix>  # stat prefix gets added into ext proc metrics name
            failure_mode_allow: true
            async_mode: false
            message_timeout:
              seconds: 0
              nanos: 30000000
            processing_mode:
              request_header_mode: "SEND"
              response_header_mode: "SEND"
              request_body_mode: "NONE"
              response_body_mode: "NONE"
              request_trailer_mode: "SKIP"
              response_trailer_mode: "SKIP"
            grpc_service:
              google_grpc:
                target_uri: <our uri>:9090
                stat_prefix: required_but_does_nothing
```

It works 👍 

Now I am overriding it for all vhosts:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: <our name>-disable
  namespace: <our namespace>
spec:
  workloadSelector:
    labels:
      edgeType: <edge label>
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        name: envoy.filters.http.ext_proc
        typed_per_filter_config:
          envoy.filters.http.ext_proc:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute"
            disabled: true
```

This successfully _disables_ all ext procs again. 👍 

Is there a way to re-enable the ext proc for _some_ routes or is a looong [denylist](https://en.wikipedia.org/wiki/Blacklist_(computing)#:~:text=In%20computing%2C%20a%20blacklist%2C%20disallowlist,the%20list%20are%20denied%20access.) the only option?

[1] https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-externalprocessor

**Comment by Pawan-Bishnoi** [comment]
when do you want to enable it?

If the logic to enable is based on presence or absence of request headers, you can try composite filter at Gateway Level.

**Comment by tfrokt** [comment]
> when do you want to enable it?
> 
> If the logic to enable is based on presence or absence of request headers, you can try composite filter at Gateway Level.

The "when" is not too important as long as it is on the incoming request, getting it working is the main objective currently. 
Later would be better as we can execute other logic first, that might block requests already (so there is overall less work on the system).

I will have a look at [Composite Filters](https://www.envoyproxy.io/docs/envoy/v1.26.4/configuration/http/http_filters/composite_filter.html).

**Comment by thiagomata** [comment]
I could create this envoy.yaml that does the job:
```yaml
# Should call ext-proc:
# curl -s www.foo.com:8081/foo
# curl -s www.bar.com:8081/bar

# Should not call ext-proc
# curl -s www.bar.com:8081/foo
# curl -s www.foo.com:8081/bar
# curl -s www.foo.com:8081/something
# curl -s www.bar.com:8081/something

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8081 }
      access_log:
        - name: envoy.access_loggers.file
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: /var/log/envoy/access.log
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: echo_service }
                http_filters:
                  - name: composite
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
                      extension_config:
                        name: composite
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
                        #  {
                        #    "matcher": config.common.matcher.v3.Matcher) # deprecated
                        #    "xds_matcher": .xds.type.matcher.v3.Matcher # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher
                        #    "extension_config": config.core.v3.TypedExtensionConfig # https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/extension.proto#envoy-v3-api-msg-config-core-v3-typedextensionconfig
                        #  }
                      xds_matcher:
                        #  {
                        #    "matcher_list": .xds.type.matcher.v3.Matcher.MatcherList  # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist
                        #    "matcher_tree": .xds.type.matcher.v3.Matcher.MatcherTree  # https://www. envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#xds-type-matcher-v3-matcher-matchertree
                        #    "on_no_match":  .xds.type.matcher.v3.Matcher.OnMatch      # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-onmatch
                        #  }
                        matcher_list:
                          # .xds.type.matcher.v3.Matcher.MatcherList # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist
                          #  {
                          #    "matchers": [].xds.type.matcher.v3.Matcher.MatcherList.FieldMatcher # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-fieldmatcher
                          #  }
                          matchers: # .xds.type.matcher.v3.Matcher.MatcherList.FieldMatcher # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-fieldmatcher
                            #  {
                            #    "predicate": .xds.type.matcher.v3.Matcher.MatcherList.Predicate, REQUIRED  # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                            #    "on_match":  .xds.type.matcher.v3.Matcher.OnMatch, REQUIRED                # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-onmatch
                            #  }
                            predicate:
                              # .xds.type.matcher.v3.Matcher.MatcherList.Predicate # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                              #  {
                              #    "single_predicate": .xds.type.matcher.v3.Matcher.MatcherList.Predicate.SinglePredicate # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-singlepredicate
                              #    "or_matcher":       .xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                              #    "and_matcher":      .xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                              #    "not_matcher":      .xds.type.matcher.v3.Matcher.MatcherList.Predicate                 # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                              #  }
# not_matcher can be used to create block lists
                              or_matcher:
# currently, using the allowed list approach
# so, only www.foo.com:8081/foo or www.bar.com:8081/bar should have the filter
                              # (.xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList)   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                              #  {
                              #    "predicate": [].xds.type.matcher.v3.Matcher.MatcherList.Predicate, REQUIRED # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                              #  }
                                predicate:
# foo
# if host is www.foo.com:8081 and path starts with /foo
                                  - and_matcher:
# istio currently has problem parsing generic objects with arrays
# json: cannot unmarshal object into Go value of type []json.RawMessage
                                      # (.xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList)   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                                      #  {
                                      #    "predicate": [].xds.type.matcher.v3.Matcher.MatcherList.Predicate, REQUIRED # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                                      #  }
                                      predicate:
                                        # .xds.type.matcher.v3.Matcher.MatcherList.Predicate # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                                        #  {
                                        #    "single_predicate": .xds.type.matcher.v3.Matcher.MatcherList.Predicate.SinglePredicate # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-singlepredicate
                                        #    "or_matcher":       .xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                                        #    "and_matcher":      .xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                                        #    "not_matcher":      .xds.type.matcher.v3.Matcher.MatcherList.Predicate                 # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                                        #  }
                                        - single_predicate:
                                            input:
                                              name: host
                                              typed_config:
                                                "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                                header_name: "host"
                                            value_match:
                                              exact: "www.foo.com:8081"
                                        - single_predicate:
                                            input:
                                              name: path-prefix
                                              typed_config:
                                                "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                                header_name: ":path"
                                            value_match:
                                              prefix: "/foo"
# bar
# if host is www.bar.com:8081 and path starts with /bar
                                  - and_matcher:
                                      # (.xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList)   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                                      #  {
                                      #    "predicate": [].xds.type.matcher.v3.Matcher.MatcherList.Predicate, REQUIRED # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                                      #  }
                                      predicate:
                                        # .xds.type.matcher.v3.Matcher.MatcherList.Predicate # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                                        #  {
                                        #    "single_predicate": .xds.type.matcher.v3.Matcher.MatcherList.Predicate.SinglePredicate # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-singlepredicate
                                        #    "or_matcher":       .xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                                        #    "and_matcIher":      .xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList   # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate-predicatelist
                                        #    "not_matcher":      .xds.type.matcher.v3.Matcher.MatcherList.Predicate                 # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-matcherlist-predicate
                                        #  }
                                        - single_predicate:
                                            input:
                                              name: host
                                              typed_config:
                                                "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                                header_name: "host"
                                            value_match:
                                              exact: "www.bar.com:8081"
                                        - single_predicate:
                                            input:
                                              name: path-prefix
                                              typed_config:
                                                "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                                header_name: ":path"
                                            value_match:
                                              prefix: "/bar"
                            on_match:
                              # .xds.type.matcher.v3.Matcher.OnMatch, REQUIRED # https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#envoy-v3-api-msg-xds-type-matcher-v3-matcher-onmatch
                              # Precisely one of matcher, action must be set.
                              #  {
                              #    "matcher": .xds.type.matcher.v3.Matcher,
                              #    "action": .xds.core.v3.TypedExtensionConfig
                              #  }
                              action:
                                name: composite-action
                                typed_config:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                                  typed_config:
                                    name: envoy.filters.http.ext_proc
                                    typed_config:
                                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                                      type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
                                      value:
                                        stat_prefix: my_grpc_service # stat prefix gets added into ext proc metrics name
                                        failure_mode_allow: true
                                        async_mode: false
                                        message_timeout:
                                          seconds: 5
                                          nanos: 0
                                        processing_mode:
                                          request_header_mode: "SEND"
                                          response_header_mode: "SKIP"
                                          request_body_mode: "NONE"
                                          response_body_mode: "NONE"
                                          request_trailer_mode: "SKIP"
                                          response_trailer_mode: "SKIP"
                                        grpc_service:
                                          google_grpc:
                                            target_uri: "my-grpc-service:9090"
                                            stat_prefix: required_but_does_nothing
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: echo_service
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: echo_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      # echo service only returns what it receives
                      address: echo
                      port_value: 8080
```
```bash
# call ext-proc my-grpc-service:9090
curl -s www.foo.com:8081/foo
curl -s www.bar.com:8081/bar

# Do not call ext-proc my-grpc-service:9090
curl -s www.bar.com:8081/foo
curl -s www.foo.com:8081/bar
curl -s www.foo.com:8081/something
curl -s www.bar.com:8081/something
```

But when we try to set the same settings in the Istio deployment, using the settings below, ...

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-grpc-service
  namespace: my-cluster
spec:
  workloadSelector:
    labels:
      clusterLabelTag: cluster-label-tag-value
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: composite
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: composite
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
            xds_matcher: # also tested with "matcher" instead of "xds_matcher" # same result
              matcher_list:
                matchers:
                  predicate:
                    or_matcher:
                      predicate:
                        # www.foo.com/foo
                        - and_matcher:
                            predicate:
                              - single_predicate:
                                  input:
                                    name: host
                                    typed_config:
                                      "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                      header_name: "host"
                                  value_match:
                                    exact: "www.foo.com"
                              - single_predicate:
                                  input:
                                    name: path-prefix
                                    typed_config:
                                      "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                      header_name: ":path"
                                  value_match:
                                    prefix: "/foo"
                        # www.bar.com/bar
                        - and_matcher:
                            predicate:
                              - single_predicate:
                                  input:
                                    name: host
                                    typed_config:
                                      "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                      header_name: "host"
                                  value_match:
                                    exact: "www.bar.com"
                              - single_predicate:
                                  input:
                                    name: path-prefix
                                    typed_config:
                                      "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                      header_name: ":path"
                                  value_match:
                                    prefix: "/bar"
                  on_match:
                    action:
                      name: composite-action
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                        typed_config:
                          name: envoy.filters.http.ext_proc
                          typed_config:
                            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                            type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
                            value:
                              stat_prefix: my_grpc_service
                              failure_mode_allow: true
                              async_mode: false
                              message_timeout:
                                seconds: 5
                                nanos: 0
                              processing_mode:
                                request_header_mode: "SEND"
                                response_header_mode: "SKIP"
                                request_body_mode: "NONE"
                                response_body_mode: "NONE"
                                request_trailer_mode: "SKIP"
                                response_trailer_mode: "SKIP"
                              grpc_service:
                                google_grpc:
                                  target_uri: "my-grpc-service:9090"
                                  stat_prefix: required_but_does_nothing

```

... we are getting the following error:

```js
Resource: 
  "networking.istio.io/v1alpha3, Resource=envoyfilters", 
  GroupVersionKind: "networking.istio.io/v1alpha3, Kind=EnvoyFilter"
  Name: "my-grpc-service", Namespace: "my-cluster"
for: ".../example.yaml": error when patching ".../example.yaml": 
admission webhook "validation.istio.io" denied the request: 
configuration is invalid: 
Envoy filter: 
can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher: 
json: cannot unmarshal object into Go value of type []json.RawMessage
```

That error seems related to the parsing of the array elements into the "and_matcher."

I have also tested a similar settings file:
```yaml
# ... same as the file above
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: "type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher"
            value:
              - name: composite
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
                  extension_config:
                    name: composite
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
                  xds_matcher:
# ... same as the file above
```

that generates a similar error message:
```js
admission webhook "validation.istio.io" denied the request: 
configuration is invalid: 
Envoy filter: 
can't unmarshal Any nested proto type.googleapis.com/udpa.type.v1.TypedStruct: 
bad StructValue: json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```

Both error messages make me believe that Istio has issues parsing nested array elements, "and_matcher" in special, since they don't match the expected type ``map[string] RawMessage``.
