### ISSUE TITLE
Cannot use envoy early http header mutation features

### ISSUE THREAD

**Issue by pisto** [istio/istio#49978]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In a cluster with Istio installed via Helm chart and a single gateway, I have been unable to use the `early_header_mutation_extensions` field of the `envoy.filters.network.http_connection_manager` filter (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extension-category-envoy-http-early-header-mutation). The intent is to sanitize the the `x-forwarded-for` field, and set only the value obtained from the PROXY protocol.

This is the envoy filter configuration:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-proxy-protocol
spec:
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.listener.proxy_protocol
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          early_header_mutation_extensions:
          - name: envoy.http.early_header_mutation.header_mutation
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.http.early_header_mutation.header_mutation.v3.HeaderMutation
              mutations:
              - remove: x-forwarded-for
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 0
```

The admission webhook passes it, however in the gateway logs I get:
```
2024-03-19T16:22:07.645721Z	warning	envoy config external/envoy/source/common/config/grpc_subscription_impl.cc:128	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: Early header mutation extension not found: 'envoy.http.early_header_mutation.header_mutation'
```
It is interesting to note that if I intentionally mispell the type name of the extension (`'@type': type.googleapis.com/envoy.extensions.http.early_header_mutation.header_mutation.v3.HeaderMutation_zzzzzz`), the admission webhook rejects the modification:

```
error: envoyfilters.networking.istio.io "device-ingress-proxy-protocol" could not be patched: admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: could not resolve Any message type: type.googleapis.com/envoy.extensions.http.early_header_mutation.header_mutation.v3.HeaderMutation_zzzzzz
```

This makes me think that it maybe an issue in the build system of the proxy, for example this #46321 is a bug in 1.18 where some extension were missing from the build system.

The correct usage of this field is shown in a [test case of envoy](https://github.com/envoyproxy/envoy/blob/708fa7b4d8269372fdac39b11caf2a3bf7b18d53/test/extensions/filters/network/http_connection_manager/config_test.cc#L2495-L2500).

### Version

```Text
Istio helm chart version 1.17.8

kubernetes 1.26.13

helm version 3.2.1
```
