### ISSUE TITLE
Gateway API: hostnames in HTTPRoute make no effect

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49973]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am using Gateway API in Istio and create two HTTPRoutes with same `parentRefs` but different `hostnames`. I try `curl -H"host:www.bookinfo.com" http://back.default.svc.cluster.local:80`, but this packet is routed to ratings service, implying that `hostnames` in HTTPRoute makes no effect actually.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr-0
spec:
  parentRefs:
    - port: 80
      group: ''
      kind: Service
      name: back
  hostnames:
    - www.example.com
  rules:
    - backendRefs:
        - name: ratings
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr-1
spec:
  parentRefs:
    - port: 80
      group: ''
      kind: Service
      name: back
  hostnames:
    - www.bookinfo.com
  rules:
    - backendRefs:
        - name: productpage
          port: 9090
```

### Version

```Text
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (4 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
