### ISSUE TITLE
AuthorizationPolicy rules.from.source.requestPrincipals with https URL not working

### ISSUE THREAD

**Issue by kaiburjack** [istio/istio#49979]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When trying to validate JWT tokens issued by Google (in our case for PubSub push messages) with a `RequestAuthentication` and configuring a correct issuer and jwksUri:
```yaml
spec:
  jwtRules:
    - issuer: "https://accounts.google.com"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
```
and then trying to use a `AuthorizationPolicy` with a `requestPrincipals` that is using the pattern ([according to the Istio documentation](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source)) `<iss>/<sub>` (issuer in this case will be `https://accounts.google.com` and the subject (sub claim) will be `1234567890123456` - both have been verified by inspecting the actual JWT token):
```yaml
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
            - "https://accounts.google.com/1234567890123456"
      to:
        - operation:
            hosts:
              - the.host.tld # <-- actual value different
```
then requests are rejected with an `rbac_access_denied_matched_policy[none]` status.

However, if we instead do not use the requestPrincipal but a "when" clause as follows:
```yaml
spec:
  action: ALLOW
  rules:
    - when:
        - key: "request.auth.claims[iss]"
          values: ["https://accounts.google.com"]
        - key: "request.auth.claims[sub]"
          values: ["1234567890123456"]
      to:
        - operation:
            hosts:
              - the.host.tld # <-- actual value different
```
then everything works fine.

I would have expected both cases to be practially identical and have the assumption that there could be an issue in Istio/Envoy when the issuer is a URL with slashes in them?

### Version

```Text
Istio Version: 1.21.0
```
