### ISSUE TITLE
Seeing intermittent  503 connection reset error on both ingress gateway and sidecar

### ISSUE THREAD

**Issue by anannaya** [istio/istio#49975]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are having a similar usecase as mentioned here https://github.com/istio/istio/pull/36566 , We have added the environment varible DROP_INVALID as well, still the issue is seen. 

### Version

```Text
istioctl version
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (797 proxies)
```

**Comment by anannaya** [comment]
Without a istio sidecar its working fine.  Wondering if any workaround to solve the issue with sidecar .

**Comment by shonecyx** [comment]
@anannaya  Did you check the sidecar iptable rules after enable the DROP_INVALID flag and could you paste the iptable rules? 
If there is still connection reset, what's the frequency? And it might be related with ingressgw to upstream keep alive config and you can try to create a DestinationRule in istio namespace with tcp keep alive configuration like below:
```
        tcp:
          connectTimeout: 1s
          maxConnections: 20000
          tcpKeepalive:
            interval: 10s
            probes: 10
            time: 700s
```
