### ISSUE TITLE
Gateway API: different route behavior between different GatewayClass

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49974]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am using Gateway API in Istio and the configuration is below. When using Istio GatewayClass, the traffic from gateway chooses the first rule, while it chooses the second rule under [Contour](https://github.com/projectcontour/contour) GatewayClass. This case is deployed under Istio proxies, so which route behavior is more reasonable? What about the reason?
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    name: gateway
    kind: Gateway
  hostnames:
  - www.example.com
  rules:
  - matches:
    - path:
        type: Exact
        value: /productpage
    backendRefs:
    - name: ratings
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /productpage
    backendRefs:
    - name: productpage
      port: 9080
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: contour # or istio
  listeners:
  - name: port-1
    port: 80
    protocol: HTTP
    hostname: www.example.com
    allowedRoutes:
      namespaces:
        from: All
```

### Version

```Text
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (4 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
