### ISSUE TITLE
Gateway API: no validation of RegularExpression in HTTPRoute

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49993]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Here is my configuration. Istio doesn't reject it but RegularExpression makes HTTPRoute take no effect. 
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr
spec:
  parentRefs:
  - name: back
    kind: Service
    group: ''
    port: 80
  rules:
  - matches:
    - headers:
      - name: host
        type: RegularExpression
        value: "*.example.com"
    backendRefs:
    - name: ratings
      port: 8080
```

According to #49607, it is better to add validation for RegularExpression in HTTPRoute instead of only add warn in log to avoid confusion. For example, if I add RegularExpression in existing HTTPRoute, it won't trigger update and will keep on the old behavior.

### Version

```Text
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (2 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
