### ISSUE TITLE
Support mirrorPercentage for Gateway API resources

### ISSUE THREAD

**Issue by yshch** [istio/istio#49999]
**User story**

I need to mirror some percentage of requests processed by Istio ingress-gateway configured via Gateway API resources.

Currently i have the Gateway object:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.example.com'
    name: example-http2
    port: 80
    protocol: HTTP
```

And related HTTPRoute object, attached to the receiving Service:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example
spec:
  hostnames:
  - httpbin.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: httpbin
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /

```

This works just fine.

And i can mirror the traffic by adding requestMirror filter to HTTPRoute spec like this:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example
spec:
  hostnames:
  - httpbin.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: httpbin
      port: 80
      weight: 1
    filters:
    - requestMirror:
        backendRef:
          group: ""
          kind: Service
          name: httpbin-mirror
          port: 80
      type: RequestMirror
    matches:
    - path:
        type: PathPrefix
        value: /

```

This also works fine, but mirrors 100% of the traffic.

Gateway API specification for requestMirror filter doesn't seem to support any additional configuration. It does, however, support separate filter configurations per backendRef. This, theoretically, would allow me to specify two backends with the same basic ref, but different weights and filter configurations. However, [Istio does not support requestMirror filtering on backendRefs](https://github.com/istio/istio/blob/1.20.4/pilot/pkg/config/kube/gateway/conversion.go#L1312-L1335). This is understandable, since implementing separate requestMirror filters for separate backendRefs seems very tricky with the current model.

**Describe the feature request**

Istio should support mirrorPercentage for Gateway API resources in some way. This is an important feature and a blocker for Gateway API migration for significant number of users. Especially, because there is no officially supported way to use VirtualService together with Gateway API resources, see https://github.com/istio/istio/issues/46662

There are a few options to implement this, that come to mind:
- Implement extension filter, that will allow configuration of mirrorPercentage, in the same way it is done with VirtualService. Obviously, creating Istio-specific extension is not ideal, but there seems to be no other easy way around it.
- Support separate requestMirror filters for separate backendRefs. This approach does not require extending the standard API, but seems really difficult to implement, due to the structure of internal model.

Supporting attachment of VirtualServices to Gateway API Gateways would also solve this issue in an ugly way.

**Describe alternatives you've considered**

The only supported alternative right now, seems to be to abandon Gateway API and revert to Istio API.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane
