### ISSUE TITLE
Port 80 not open automatically under demo-profile-no-gateways

### ISSUE THREAD

**Issue by qts0312** [istio/istio#49991]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I install Istio under demo-profile-no-gateways ([samples/bookinfo/demo-profile-no-gateways.yaml](https://raw.githubusercontent.com/istio/istio/release-1.21/samples/bookinfo/demo-profile-no-gateways.yaml)), following the guide of official documentation. The configuration is below, I try `curl -H"host:www.example.com" http://1.1.1.1:80` but it pass through the cluster. However, after I change one of the ports of ratings service to 80, `curl -H"host:www.example.com" http://1.1.1.1:80` can get correct service. Since Istio always open port 80 for VirtualService by default, this route behavior is not reasonable.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - www.example.com
  http:
    - route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
  - port: 9090  # change to 80
    targetPort: 9080
    name: http-1
  - port: 8080
    targetPort: 9080
    name: http-0
```

RDS before and after the change.
[route-before.log](https://github.com/istio/istio/files/14659278/route-before.log)
[route-after.log](https://github.com/istio/istio/files/14659382/route-after.log)

### Version

```Text
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (2 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
