### ISSUE TITLE
Istiod helm chart should support mounting the cacerts volume with the Kubernetes CSI Secrets store driver

### ISSUE THREAD

**Issue by zioproto** [istio/istio#50036]
**Describe the feature request**

When using Istio in multicluster the [CA certs must be provided](https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/#configure-trust) because each cluster cannot have a self-signed autogenerated cert.

Currently `/etc/cacerts` can be mounted only from a Kubernetes secret.

https://github.com/istio/istio/blob/70c91d105eae1a90b258fdaddae0469d14ec1500/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L225-L228

Istio users on public cloud do not store private keys in Kubernetes secrets as a best practice, but they use [Kubernetes Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/) to mount the secrets from their public cloud secret store.

The helm chart template should support to use the Kubernetes Secrets Store CSI Driver passing the necessary information in the values.

**Describe alternatives you've considered**

Currently I am patching the the `IstioOperator` as follows to solve this problem:
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 components:
   pilot:
     enabled: true
     k8s:
       overlays:
         - kind: Deployment
           name: istiod-1-20-1 # https://github.com/istio/istio/issues/31076
           patches:
             - path: spec.template.spec.volumes[name:cacerts]
               value:
                 name: cacerts
                 csi:
                   driver: secrets-store.csi.k8s.io
                   readOnly: true
                   volumeAttributes:
                     secretProviderClass: "istio-tls"
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane
