### ISSUE TITLE
Support multiple virtual services with same host

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#5006]
I am trying to create two different virtual services with the same host and get the following error. Note that the virtual services have different destinations.

using docker.io/istionightly/proxyv2:circleci-nightly from today
docker sha
```
4db79f932279897a18428a17d3c59111f011709c4323ee5f1a5fc6820588b50a
```

```
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Only unique values for domains are permitted. Duplicate entry of domain my-ingress.weather.com
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: locationservice-controller
spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - my-ingress.weather.com
  http:
  - match:
    - uri:
        exact: /v2/location
    route:
    - destination:
        host: controller
        port:
        name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: locationservice-router
spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - my-ingress.weather.com
  http:
  - match:
    - uri:
        exact: /origin/v2/location/search
    rewrite:
      uri: /v2/location/search
    route:
    - destination:
        host: my-location.weather.com
        port:
          name: http
---

```

**Comment by nmnellis** [comment]
@rshriram similar error to https://github.com/istio/istio/issues/4845

**Comment by nmnellis** [comment]
im closing this for now, i realized the route/match are incorrect

**Comment by rshriram** [comment]
You can have only one virtual service per host. Each virtual service can have multiple rules. So combine both rules into one.

**Comment by rshriram** [comment]
See examples in istio/api/networking/v1alpha3/virtual_service.proto

**Comment by nmnellis** [comment]
We have 100+ route rules under the same host, this VirtualService will be thousands of lines long.

**Comment by linsun** [comment]
I know the spec currently has " **A host name can be defined by only one VirtualService**. " however, I would encourage us to reconsider this limitation as this is a huge usability issue when user has many route rules for the same host like Nick mentioned, and this is something the k8s ingress controller provides nicer support today.

Today, users can specify multiple ingress controller yaml files pointing to the same host and I can fan out the yaml files onto different team where each team will be in charge of their own delivery within the host for one or more given paths.

Examples:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: users-api
spec:
  rules:
  - host: api.weather.com
    http:
      paths:
      - backend:
          serviceName: users-api
          servicePort: 80
        path: /users/.*
```

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: billing-api
spec:
  rules:
  - host: api.weather.com
    http:
      paths:
      - backend:
          serviceName: billing-api
          servicePort: 80
        path: /billing-api/.*
```

@louiscryan @rshriram @frankbu @ZackButcher @costinm ^^^ thoughts?   cc @esnible @ijsnellf @GregHanson
