### ISSUE TITLE
Ztunnel missing writeable /tmp dir for gathering pprof

### ISSUE THREAD

**Issue by ably77** [istio/istio#50060]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When attempting to gather a `debug/pprof/profile` for `ztunnel` on a default install the user is met with an empty response
![Screenshot 2024-03-21 at 5 14 09 PM](https://github.com/istio/istio/assets/31321277/46f28ac8-ddf7-4c81-9d98-ca54eeaa3cb9)

To resolve this, the following `volume` and `volumeMount` is required to add a `/tmp` directory in the ztunnel daemonset manually, or using helm:
```
helm upgrade --install ztunnel istio/ztunnel \
-n kube-system \
--version=1.21.0 \
-f -<<EOF
hub: docker.io/istio
tag: 1.21.0
resources:
  requests:
      cpu: 500m
      memory: 2048Mi
istioNamespace: istio-system
# Additional volumeMounts to the ztunnel container
volumeMounts:
  - name: tmp
    mountPath: /tmp
# Additional volumes to the ztunnel pod
volumes:
  - name: tmp
    emptyDir:
      medium: Memory
EOF
```

Should we be including this missing `volume` and `volumeMount` in the default ztunnel deployment templates? or alternatively, if we decide not to fix the template so it "just works" should we upgrade the handler to have a meaningful reply if `ztunnel` doesn't have the writable location it requires?

cc: @ilrudie @bleggett 

### Version

```Text
% istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (25 proxies)

% kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1118000
```
