### ISSUE TITLE
Dynamic Host selection from Application Service Entry

### ISSUE THREAD

**Issue by sambitr** [istio/istio#50071]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

We have a setup, where we have multiple application namespaces defined. As part of platforms team, we define egress rules(service entry, destination rule, virtual service) for every Azure resource in the application namespace, as well as in the istio-system namespace. But this way of working is repetitive and we want to avoid that. We have bunch of Azure resources application teams connect to from the AKS cluster.

It would be good to have something that will automatically detect the host name from the istio-proxy side car container and route traffic through egress gateway using the hostname, rather than manually setting up service registry and all in istio-system namespace. This way, we will have control as to what is cleared for connection from application namespace level and at the same time, we don't have to fiddle istio-system namespace changes.

We can have a common hostname defined in the istio-system namespace service entries, virtual services and destination rules, where the hostname values will be replaced from the istio-proxy side car host name in the run time.

We have outboundPolicy ALLOW_ANY. But that will skip istio-proxy side car altogether and it won't go through egress gateway it self. We don't want that option. 

I tried to experiment on this idea, where as I defined the dts-demo-dev-kv.vault.azure.net KV in the service entry, destination-rule and virtualservice in application namespace. Whereas, I have defined host: www.vault.azure.net in istio-system namespace.

From istio-proxy, the connection is forwarded to the egressgateway in istio-system namespace. When it tries to resolve the host name to the IP, it resolves the hostname of www.vault.azure.net. But he IP thus received is not the IP for KV: dts-demo-dev-kv.vault.azure.net and hence it results in KV not found issue

istio-proxy:

[2024-03-24T21:54:46.155Z] "- - -" 0 - - - "-" 517 0 6 - "-" "-" "-" "-" "172.0.2.14:8443" outbound|443|kv|istio-egressgateway.istio-system.svc.cluster.local 172.0.3.12:32978 52.146.137.169:443 172.0.3.12:55040 demo-dev-kv.vault.azure.net 

egress-gateway

[2024-03-24T21:54:47.111Z] "- - -" 0 - - - "-" 1157 7333 1761 - "-" "-" "-" "-" "**20.62.134.229**:443" outbound|443||www.vault.azure.net 172.0.2.14:40670 172.0.2.14:8443 172.0.2.12:43700 demo-dev-kv.vault.azure.net -

We are using Istio version 1.19.6 and Kubernetes Version: 1.27.7

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
>When it tries to resolve the host name to the IP, it resolves the hostname of [www.vault.azure.net](http://www.vault.azure.net/). But he IP thus received is not the IP for KV: dts-demo-dev-kv.vault.azure.net and hence it results in KV not found issue


Not quite understand, how do you access external service, what's your SE look like?

**Comment by sambitr** [comment]
Hi @hzxuzhonghu 
This is the service entry that we have in istio-system:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kv
  namespace: istio-system
spec:
  hosts:
  - "www.vault.azure.net"
  exportTo: ["."]
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: NONE
  location: MESH_EXTERNAL
```


This service entry is the one, which we have in application namespace:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kv
  namespace: demo
spec:
  hosts:
  - "demo-dev-kv.vault.azure.net"
  exportTo: ["."]
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
```
