### ISSUE TITLE
opentelemetry tracing only see egress traffic

### ISSUE THREAD

**Issue by xhdnoah** [istio/istio#50117]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have set up my distributed tracing according to this [document](https://github.com/istio/istio/tree/master/samples/open-telemetry/tracing), the only difference is I used the jaeger-collector directly as the receiver as it has supported otlp.
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: telemetry
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
```
```
extensionProviders:
  - name: "otel-tracing"
     opentelemetry:
       service: "jaeger-collector.istio-system.svc.cluster.local"
       port: "4317"
```
Then I used the bookinfo example to test, when I start trying `curl https://${GATEWAY_IP}/productpage`, the response is correct but I can only see two services on jaeger ui
<img width="301" alt="image" src="https://github.com/istio/istio/assets/40939515/757c3f36-5005-4464-8fdf-f67e46e91d71">
and the ingressgateway only have traces named `shentu-ingressgateway.istio-system: egress example.com`. I cannot see the tracing reported by the productpage service or other services. thanks for any help.

### Version

```Text
client version: 1.17.0
control plane version: 1.17.0
data plane version: 1.17.0 (8 proxies)
```

### Additional Information

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-03-27 11:03:12.138077 +0800 CST

CLI version:
version.BuildInfo{Version:"1.17.0", GitRevision:"c8c901a56861021dc25412f2e557b72a235b554c", GolangVersion:"go1.20", BuildStatus:"Clean", GitTag:"1.17.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.17.0", GitRevision:"c8c901a56861021dc25412f2e557b72a235b554c", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.17.0}

Fetching proxy logs for the following containers:

default/details-v1/details-v1-698d88b-rw8vb/details
default/details-v1/details-v1-698d88b-rw8vb/istio-proxy
default/productpage-v1/productpage-v1-657695b794-dm4xd/istio-proxy
default/productpage-v1/productpage-v1-657695b794-dm4xd/productpage
default/ratings-v1/ratings-v1-6484c4d9bb-r6lxk/istio-proxy
default/ratings-v1/ratings-v1-6484c4d9bb-r6lxk/ratings
default/reviews-v1/reviews-v1-5b5d6494f4-hlrfv/istio-proxy
default/reviews-v1/reviews-v1-5b5d6494f4-hlrfv/reviews
default/reviews-v2/reviews-v2-5b667bcbf8-qq6px/istio-proxy
default/reviews-v2/reviews-v2-5b667bcbf8-qq6px/reviews
default/reviews-v3/reviews-v3-5b9bd44f4-b72bw/istio-proxy
default/reviews-v3/reviews-v3-5b9bd44f4-b72bw/reviews
istio-system/istio-ingressgateway/istio-ingressgateway-d7bdf9bd8-ccdbn/istio-proxy
istio-system/istiod/istiod-96994958b-lpqjm/discovery
istio-system/jaeger/jaeger-69dc846f95-v7bgj/jaeger
xyz/httpbin/httpbin-6bd588b867-j9knb/httpbin
xyz/httpbin/httpbin-6bd588b867-j9knb/istio-proxy

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0118] (Service istio-system/jaeger-agent) Port name config-rest (port: 5778, targetPort: 5778) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name c-tchan-trft (port: 14267, targetPort: 14267) doesn't follow the naming convention of Istio port.

**Comment by zirain** [comment]
you should check the logging from otel-collector first, does it receive tracing from all the proxies.

**Comment by xhdnoah** [comment]
> you should check the logging from otel-collector first, does it receive tracing from all the proxies.

I have checked the jaeger log, it only receive tracing from jaeger itself and the ingressgateway.

**Comment by zirain** [comment]
> > you should check the logging from otel-collector first, does it receive tracing from all the proxies.
> 
> I have checked the jaeger log, it only receive tracing from jaeger itself and the ingressgateway.

check the listener config dump and proxy log(you may need change log level)

**Comment by hanxiaop** [comment]
How did you name your jaeger port? Make sure the name is following the convention https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection, for example `grpc-xxx`

**Comment by xhdnoah** [comment]
> How did you name your jaeger port? Make sure the name is following the convention https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection, for example `grpc-xxx`

I paid attention to this
```
spec:
  ports:
    - name: http-zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: grpc-http
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: c-tchan-trft
      protocol: TCP
      port: 14267
      targetPort: 14267
    - name: http-c-binary-trft
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: grpc-otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
```
