### ISSUE TITLE
AUTO_SNI does not respect Authority rewrite

### ISSUE THREAD

**Issue by vsfomin** [istio/istio#50126]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I installed istio version 1.21.0 via Helm into a cluster. 
After that I made a deploy of my application.  I need DR because on the application side, HTTPS works, **not** HTTP.
The settings concerning Istio are:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: preapproved-service
  namespace: cnv-preprod
spec:
  host: preapproved-service
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: preapproved-service
  namespace: cnv-preprod
spec:
  gateways:
    - istio-ingress/cnv-ingress-gateway-https
  hosts:
    - preprod-cnv-srv.example.com
  http:
    - match:
        - uri:
            prefix: /preapproved-service
      name: preapproved-service
      rewrite:
        uri: /
      route:
        - destination:
            host: preapproved-service
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnv-ingress-gateway-https
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - preprod-cnv-srv.example.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: tls-certs-opaque-preprod-cnv-srv
        mode: SIMPLE
```
After I try to connect my application: https://preprod-cnv-srv.example.com/preapproved-service/healthCheck and see the error:

> upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end

**When I downgrade istiod from 1.21.0 to 1.20.1 (my dev and test clusters using this version of istio) the error disappears.**
The configuration does not change in any way.  Probably it's not a bug and something wrong in my configuration, I don't know for sure

### Version

```Text
PS .\istioctl.exe version --kubeconfig C:\Users\Vladimir.Fomin\.kube\preprod-cnv-kubeconfig.yaml
client version: 1.20.1
control plane version: 1.21.0
data plane version: 1.20.1 (2 proxies)

helm version --short
v3.14.0+g3fc9f4b
```

### Additional Information

[bug-report.log](https://github.com/istio/istio/files/14776532/bug-report.log)

**Comment by hzxuzhonghu** [comment]
Maybe try to add InsecureSkipVerify in DR

**Comment by hzxuzhonghu** [comment]
ENABLE_AUTO_SNI has been changed to `true` now

**Comment by vsfomin** [comment]
> Maybe try to add InsecureSkipVerify in DR
Thanks, but unfortunately, it doesn't make any result. The error still appears.

**Comment by vsfomin** [comment]
The error desappers when I've done this in DR:. Need configure mode to MUTUAL.
```
spec:
  host: preapproved-service
 trafficPolicy:
    credentialName: tls-certs-opaque-preprod-cnv-srv
     mode: MUTUAL
     insecureSkipVerify: true
```
     
   instead of this:
  ```
spec:
  host: preapproved-service
  trafficPolicy:
    tls:
      mode: SIMPLE
```

**Comment by hzxuzhonghu** [comment]
So is it because your application requires strict tls?

And to compare the diff, you can dump both 1.20 and 1.21 cluster configuration

**Comment by ChrisV78** [comment]
@vsfomin we also experienced this when upgrading from 1.20 to 1.22  but solved it with the SNI option like this:

```
spec:
  host: <hostname>
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: <hostname>
```
      
https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings:

> SNI string to present to the server during TLS handshake. If unspecified, SNI will be automatically set based on downstream HTTP host/authority header for SIMPLE and MUTUAL TLS modes.

**Comment by hzxuzhonghu** [comment]
SNI is a breaking change, which has been documented https://istio.io/latest/news/releases/1.21.x/announcing-1.21/

But as [ChrisV78](https://github.com/ChrisV78), some users can upgrade by skipping minor versions. So they may miss that, so would suggest checking with `istioctl experimental precheck`

**Comment by howardjohn** [comment]
Why is the SNI part breaking apps? I get the CA verification breaking things, but why SNI?

**Comment by Phil1602** [comment]
Hi,

I'm not 100% sure if this is related, but we face the same issue  when using an `VirtualService` to expose an external Service (`ServiceEntry`) via Istio IngressGateway.

We can fix the problem, if we define the SNI explicitly within the `DestinationRule` for our `ServiceEntry` (see examples below). 

But IMHO this was kind of breaking change for us (worked without the SNI override within 1.20.x, but was broken in 1.21.3) @howardjohn. Actually, I would have thought, that the `AUTO_SNI` setting would not influence the SNI header if the `Authority` has been overriden using the Rewrite functionality of the VirtualService.


Our setup basically looks like this and worked with Istio 1.20.x:
Internal URL -> Istio IngressGateway -> VirtualService -> ServiceEntry (external URL) + DestinationRule (HTTPS mode, Simple TLS)

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-external-foo
  namespace: some-other-namespace
spec:
  gateways:
  - istio-ingress/my-gateway # GW implemented by the Istio IngressGateway
  hosts:
  - service.internal.foo # This is the downstream URL, served by the Istio IngressGateway
  http:
  - match:
    - uri:
        exact: "/some/path"
    rewrite:
      authority: service.external.foo # We did this because of HTTP Host & SNI and seems to work until 1.21.x
    route:
    - destination:
        host: service.external.foo # This is the ServiceEntry, see below
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service-external-foo
  namespace: istio-ingress # Namespace of the Istio IngressGateway
spec:
  host: service.external.foo
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          # sni: service.external.foo # Adding this line fixes the problem. But worked without this in Istio 1.20.
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: service-external-foo
  namespace: istio-ingress # Namespace of the Istio IngressGateway
spec:
  hosts:
    - service.external.foo
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS

```

**Comment by howardjohn** [comment]
OK so I think before it was setting empty SNI, and now `service.internal.foo`, which is wrong IMO. I cannot find the original issue but there was some discussion that this should respect the rewrite @kfaseela

**Comment by kfaseela** [comment]
> OK so I think before it was setting empty SNI, and now `service.internal.foo`, which is wrong IMO. I cannot find the original issue but there was some discussion that this should respect the rewrite @kfaseela 

I am on vacation currently, @leosarra do you think you will be able to fix this?

**Comment by hzxuzhonghu** [comment]
The tricky point is we could not know if this is the only place we need fix.

**Comment by leosarra** [comment]
> > OK so I think before it was setting empty SNI, and now `service.internal.foo`, which is wrong IMO. I cannot find the original issue but there was some discussion that this should respect the rewrite @kfaseela 
> 
> I am on vacation currently, @leosarra do you think you will be able to fix this?

I remember checking some weeks ago why envoy ignores the rewrite if auto sni is enabled. I will need to check again but I recall it being intended, I feel that we will have to disable auto sni if we have a rewrite in a VS.
This week I have limited availability but perhaps I can manage to take a look.

**Comment by leosarra** [comment]
I checked the Envoy logic and  I think I got an idea on what is going on when both auto_sni and host_literal_rewrite are set.
In Envoy router the auto_sni is taken into consideration first when handling requests and as such auto_sni will end up setting transport socket SNI based on the **original** request header (code [here](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L579-L609)).
The value that will be used for SNI is coming from the host header or another header specified by the [_override_auto_sni_header_](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-upstreamhttpprotocoloptions) option.

After the SNI value has been set in the later stages of flow Envoy will "[finalize the headers](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L723)" and [replace](https://github.com/envoyproxy/envoy/blob/main/source/common/router/config_impl.cc#L921) the host value with the host_literal_rewrite before forwarding the request. Sadly the host_literal_rewrite will have no impact on the SNI value that Envoy will compute as part of auto_sni handling.

I suspect that the only way forward for us is to disable auto_sni if the users is also setting a rewrite.
Do you have any other idea on how to handle it? Otherwise I will start looking on how to disable auto_sni for this scenario.

**Comment by hzxuzhonghu** [comment]
We can know if user rewrite host with VS, but cannot know if a envoyfilter does

**Comment by howardjohn** [comment]
It would be very hard to do "if they set in VS do not do it" because you can have multiple VS point to the same cluster. We would need envoy support IMO

**Comment by ramaraochavali** [comment]
> We would need envoy support IMO

+1

**Comment by leosarra** [comment]
I will open an issue in envoy. If the Envoy community agrees on the approach I can take care of doing in envoy (and any adaptation that may be require from Istio side)

**Comment by leosarra** [comment]
FYI I have raised https://github.com/envoyproxy/envoy/issues/35330

**Comment by DekelMalul** [comment]
@leosarra I'm going throw the thread because I just hit this issue. I wonder what is the right way to resolve it until the fix released at 1.25

I understand that I can solve the issue with `sni` field in the DestinationRule
```
  spec:
  host: <hostname>
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: <hostname>
```

What is the way to solve it cluster wide? is it `compatibilityVersion`?

I'm using helm chart to install istio and didn't saw option at the values to specfiy it. Thanks

**Comment by DekelMalul** [comment]
@leosarra I'm going throw the thread because I just hit this issue. I wonder what is the right way to resolve it until the fix released at 1.25

I understand that I can solve the issue with `sni` field in the DestinationRule
```
  spec:
  host: <hostname>
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: <hostname>
```

What is the way to solve it cluster wide? is it `compatibilityVersion`?

I'm using helm chart to install istio and didn't saw option at the values to specfiy it. Thanks

**Comment by leosarra** [comment]
You can either set the correct SNI field in the DR rules where the authority rewrite is being ignored, or set pilot.env.ENABLE_AUTO_SNI=false during installation to disable auto_sni mesh-wide.

**Comment by DMSwimTech** [comment]
@leosarra I tried to use ENABLE_AUTO_SNI=false on istio version 1.23. It didnt work, but the compatibility version did.

Here is the values I'm using:
```
pilot:
  autoscaleMax: 1
  autoscaleMin: 3
  resources:
    requests:
      memory: 1024Mi
  env:
    ENABLE_AUTO_SNI: "false"
```

**Comment by leosarra** [comment]
Looks like you set it correctly there.
Are you sure the behavior you experienced is not related to the new default
value of  VERIFY_CERTIFICATE_AT_CLIENT? The compatibility version is
setting that one to false as well.

Try to set both VERIFY_CERTIFICATE_AT_CLIENT and ENABLE_AUTO_SNI to false
without relying on compatibility version and check if the issue is still
reproducible.

**Comment by DMSwimTech** [comment]
@leosarra the `VERIFY_CERTIFICATE_AT_CLIENT` works but I think there is an issue with the `ENABLE_AUTO_SNI`.

For example if both of the env variables are not used, and I'm using the following spec
```
  spec:
  host: <hostname>
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: <hostname>
 ```
 
I'm getting a valid and successful outcome (The hostname has 100% valid certificate). 

At istio version 1.19.5 I didn't used the `sni` field and I hope to get the same behavior without setting `VERIFY_CERTIFICATE_AT_CLIENT` to false. Thanks for any help
