### ISSUE TITLE
EnvoyFilter can't set lb_policy to "ROUND_ROBIN" for cluster

### ISSUE THREAD

**Issue by yefengzhichen** [istio/istio#50137]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I set lb_policy to "ROUND_ROBIN" for cluster in  EnvoyFilter, but the lb_policy is "LEAST_REQUEST" in the sleep pod's envoy config. But the result is normal when lb_policy is "RING_HASH" or "RANDOM. The EnvoyFilter is:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test
  namespace: foo
spec:
  workloadSelector:
    labels:
      app: sleep
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        name: outbound|5000||helloworld.foo.svc.cluster.local
    patch:
      operation: MERGE
      value: # cluster specification
        lb_policy: ROUND_ROBIN
        connect_timeout: "50s"
```

### Version

```Text
istioctl version 
client version: 1.19.5
control plane version: 1.19-dev
data plane version: 1.19.5 (10 proxies)
kubectl version
Client Version: v1.28.7+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7+k3s1
```
