### ISSUE TITLE
Should workloadSelector take effect in SE with resolution DNS?

### ISSUE THREAD

**Issue by qts0312** [istio/istio#50164]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

According to #49429, workloadSelector doesn't take effect in the SE with resolution DNS. However, I try setting workloadSelector in the SE below, I receive warning but the workloadSelector takes effect actually. So should workloadSelector be disabled in the SE with resolution DNS?
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-1
spec:
  hosts:
  - www.example.com
  ports:
  - number: 9080
    protocol: HTTP
    name: port-2
    targetPort: 9080
  resolution: DNS
  workloadSelector:
    labels:
      app: httpbin
```

### Version

```Text
client version: 1.21.0
control plane version: 1.22-alpha.da54969573378cea11e528e0197e5c5ca0afe5e7
data plane version: 1.22-alpha.da54969573378cea11e528e0197e5c5ca0afe5e7 (6 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by ramaraochavali** [comment]
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
The answer is yes, but we will miss warning like https://github.com/istio/istio/pull/42185/files
 and i am not clear what happens when we have a workload, whose address is not a domain, maybe we have filtered out. Need to have a test.

**Comment by hzxuzhonghu** [comment]
>and i am not clear what happens when we have a workload, whose address is not a domain, maybe we have filtered out

**Comment by zirain** [comment]
both of following two case are valid:
case 1:
```
apiVersion: networking.istio.io/v1
kind: WorkloadEntry
metadata:
  name: httpbin-we
spec:
  address: httpbin.org
  labels:
    app: httpbin-org
  # ports:
  #   http: 8000
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  exportTo:
    - "*"
  hosts:
    - httpbin.org
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
  workloadSelector:
    labels:
      app: httpbin-org

```

case 2:
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  exportTo:
    - "*"
  hosts:
    - httpbin.org
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
```
