### ISSUE TITLE
CDS EDS are missing for SE defined on the same host and different port as Service

### ISSUE THREAD

**Issue by qts0312** [istio/istio#50163]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Here is my configuration, the SE is defined on the same host and different port as Service. It returns 503 when trying `curl -H"host:productpage.default.svc.cluster.local" http://1.1.1.1:9080`. According to RDS, SE takes effect and this packet should be routed to `outbound|9080||productpage.default.svc.cluster.local`. But this cluster is missing in CDS and EDS.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-1
spec:
  hosts:
  - productpage.default.svc.cluster.local
  ports:
  - number: 9080
    protocol: HTTP
    name: port-2
    targetPort: 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
spec:
  selector:
    app: productpage
  ports:
  - port: 80
    targetPort: 9080
    name: port-5
```

### Version

```Text
client version: 1.21.0
control plane version: 1.22-alpha.da54969573378cea11e528e0197e5c5ca0afe5e7
data plane version: 1.22-alpha.da54969573378cea11e528e0197e5c5ca0afe5e7 (6 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
