### ISSUE TITLE
Pseudo header uri in HTTPMatch results in route error

### ISSUE THREAD

**Issue by qts0312** [istio/istio#50169]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In my configuration, pseudo header `:uri` in HTTPMatch results in rejection to all packets, even the packet with uri `/details`.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-1
spec:
  hosts:
    - '*.bookinfo.com'
  gateways:
    - mesh
  http:
    - match:
        - headers:
            :uri:
              exact: /details
      route:
        - destination:
            host: httpbin.default.svc.cluster.local
            port:
              number: 8080
```

Besides, same thing happens on `withoutHeaders` field. There, pseudo header `:uri` will cause acceptance to all packets, even packet with target uri.

### Version

```Text
client version: 1.21.0
control plane version: 1.22-alpha.49b7997c687b7e0492c64311ea58df0064ba3d6c
data plane version: 1.22-alpha.49b7997c687b7e0492c64311ea58df0064ba3d6c (6 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
