### ISSUE TITLE
[BUG] Destination rule proxyProtocol in Ambient enabled environment

### ISSUE THREAD

**Issue by sando38** [istio/istio#50215]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Today I switch from sidecar mode to ambient. Actually it was a smooth transfer, however, one thing does not want to work. 
I run a XMPP server (TCP/TLS connections, no HTTP) behind an istio-ingressgateway and I use a destinationRule to send the proxyProtocol header upstream to the XMPP server:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ejabberd-xmpp
  namespace: ejabberd
spec:
  host: ejabberd.ejabberd.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    proxyProtocol:
      version: V2
```

The XMPP server complains, that the proxy protocol header cannot be parsed. When I removed the `proxyProtocol` section in the destinationRule, all runs fine (of course I do not see the actual client public IP address)

### Version

```Text
~/istio-1.21.0$ ./bin/istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (2 proxies)

~/istio-1.21.0$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2+k3s1

~/istio-1.21.0$ helm version --short
v3.14.0+g3fc9f4b
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/14845639/bug-report.tar.gz)

Just let me know, if I can help anywhere with further information!

**Comment by howardjohn** [comment]
Are you using a waypoint here or just ztunnel?

**Comment by sando38** [comment]
Just ztunnel.

**Comment by sando38** [comment]
Ah, I just remember something, which I read somewhere, maybe slack:

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "no-mtls-for-tls-passthrough"
  namespace: ejabberd
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app.kubernetes.io/name: ejabberd
  portLevelMtls:
    "5222":
      mode: DISABLE
    "5223":
      mode: DISABLE
``` 
With sidecar mode I needed to disable mTLS to make the proxyProtocol work. I think what I read was, that Ambient does not allow to disable mTLS, right?
