### ISSUE TITLE
Pre-check incorrectly highlighting IST0169

### ISSUE THREAD

**Issue by Stono** [istio/istio#50243]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Using the new `precheck` command we get:

```
Warning [IST0169] (DestinationRule zendesk-controller/zendesk) The configuration "VERIFY_CERTIFICATE_AT_CLIENT" changed in release 1.20: previously, TLS verification was skipped. Set `insecureSkipVerify` if this behavior is desired. Or, install with `--set compatibilityVersion=1.20` to retain the old default.
```

On our destinationrule we explicitly set:

```
      tls:
        caCertificates: /etc/ssl/certs/ca-certificates.crt
        mode: SIMPLE
        sni: whatever.zendesk.com
```

My understanding was that this implicitly enabled TLS verification, so this warning feels incorrect?

### Version

```Text
1.21.0
```

**Comment by Stono** [comment]
Ah it's because it's a complex DR (as we're doing tls origination) under portLevelSettings:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: zendesk
  namespace: zendesk-controller
spec:
  exportTo:
  - .
  host: autotraderukpreprod.zendesk.com
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: DO_NOT_UPGRADE
      tcp:
        connectTimeout: 2s
        maxConnectionDuration: 5m
        tcpKeepalive:
          interval: 30s
          time: 30s
    portLevelSettings:
    - connectionPool:
        http:
          h2UpgradePolicy: DO_NOT_UPGRADE
        tcp:
          connectTimeout: 2s
          maxConnectionDuration: 5m
          tcpKeepalive:
            interval: 30s
            time: 30s
      port:
        number: 443
      tls:
        mode: DISABLE
    - connectionPool:
        http:
          h2UpgradePolicy: DO_NOT_UPGRADE
        tcp:
          connectTimeout: 2s
          maxConnectionDuration: 5m
          tcpKeepalive:
            interval: 30s
            time: 30s
      port:
        number: 80
      tls:
        caCertificates: /etc/ssl/certs/ca-certificates.crt
        mode: SIMPLE
        sni: autotraderukpreprod.zendesk.com
```
