### ISSUE TITLE
404 error when calling static IP proxying through Istio egress gateway

### ISSUE THREAD

**Issue by ktruy** [istio/istio#50247]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

404 error when proxying through Istio egress when calling static IP

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gitlab
  namespace: test
spec:
  hosts:
  - gitlab.egress
  addresses:
  - 192.168.68.61/32
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: STATIC
  location: MESH_EXTERNAL 
  endpoints:
  - address: 192.168.68.61
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-gitlab
  namespace: test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: gitlab
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-gitlab-through-egress-gateway
  namespace: test
spec:
  hosts:
  - gitlab.egress
  gateways:
  - istio-system/istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: gitlab
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-system/istio-egressgateway
      port: 80
    route:
    - destination:
        host: gitlab.egress
        port:
          number: 80
      weight: 100

```

route_not_found 404 error occurs when calling static IP

### Version

```Text
# istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (3 proxies)

# kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6
```
