### ISSUE TITLE
JSON AccessLogsEncoding with OpenTelemetry ALS 

### ISSUE THREAD

**Issue by AlessandroFazio** [istio/istio#50245]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello, I installed istio v1.21 with Helm Chart with the following command:
```bash
helm install istiod istio/istiod -n istio-system --set profile=demo --values istio/istiod-values.yaml
```
 After a lot of time spent on Github issues I came up with the following values.yaml configuration:
```yaml
global:
  proxy:
    tracer: none
meshConfig:
  enableTracing: true
  defaultConfig:
    tracing: {}
  defaultProviders:
    tracing:
      - opentelemetry
    accessLogging:
      - otel
  accessLogEncoding: JSON
  extensionProviders:
    - name: opentelemetry
      opentelemetry:
        service: "otel-collector.opentelemetry-system.svc.cluster.local"
        port: 4317
    - name: otel
      envoyOtelAls:
        service: "otel-collector.opentelemetry-system.svc.cluster.local"
        port: 4317
        logFormat:
        accessLogFormat: '{
          "authority": "%REQ(:AUTHORITY)%",
          "bytes_received": "%BYTES_RECEIVED%",
          "bytes_sent": "%BYTES_SENT%",
          "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
          "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
          "duration": "%DURATION%",
          "method": "%REQ(:METHOD)%",
          "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "protocol": "%PROTOCOL%",
          "requested_server_name": "%REQUESTED_SERVER_NAME%",
          "response_code": "%RESPONSE_CODE%",
          "response_flags": "%RESPONSE_FLAGS%",
          "route_name": "%ROUTE_NAME%",
          "start_time": "%START_TIME%",
          "upstream_cluster": "%UPSTREAM_CLUSTER%",
          "upstream_host": "%UPSTREAM_HOST%",
          "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
          "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
          "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
          "user_agent": "%REQ(USER-AGENT)%",
          "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%"
        }'
  defaultProviders:
    tracing: 
      - opentelemetry
    accessLogging:
      - otel
```
However, it seems that logFormatEncoding is ignored when EnvoyProxy AccessLogsService is OpenTelemetry. This is what I see in the Otel Collector stdout:
```text
{"level":"info","ts":1712223579.8756313,"msg":"ResourceLog #0
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-04-04 09:39:39.482752 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str([2024-04-04T09:39:39.482Z] \"POST /opentelemetry.proto.collector.metrics.v1.MetricsService/Export HTTP/2\" 200 - via_upstream - \"-\" 5505 7 1 0 \"-\" \"OTel-OTLP-Exporter-Java/1.34.1\" \"dbf0b5cd-fd48-9e87-9548-b4f693558de8\" \"otel-collector.opentelemetry-system.svc.cluster.local:4317\" \"10.244.0.18:4317\" outbound|4317||otel-collector.opentelemetry-system.svc.cluster.local 10.244.0.20:34300 10.96.244.185:4317 10.244.0.20:52174 - default
)
Trace ID:
Span ID:
Flags: 0
ResourceLog #1
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-04-04 09:39:39.485203 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str([2024-04-04T09:39:39.485Z] \"POST /opentelemetry.proto.collector.metrics.v1.MetricsService/Export HTTP/2\" 200 - via_upstream - \"-\" 5513 7 0 0 \"-\" \"OTel-OTLP-Exporter-Java/1.34.1\" \"020579e8-f0a3-9c17-a49f-425160457da4\" \"otel-collector.opentelemetry-system.svc.cluster.local:4317\" \"10.244.0.18:4317\" outbound|4317||otel-collector.opentelemetry-system.svc.cluster.local 10.244.0.22:40364 10.96.244.185:4317 10.244.0.22:38648 - default
)
Trace ID:
Span ID:
Flags: 0
ResourceLog #2
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-04-04 09:39:39.494191 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str([2024-04-04T09:39:39.494Z] \"POST /opentelemetry.proto.collector.metrics.v1.MetricsService/Export HTTP/2\" 200 - via_upstream - \"-\" 5519 7 0 0 \"-\" \"OTel-OTLP-Exporter-Java/1.34.1\" \"2c20e318-2e5c-9cb6-b22e-77d314d6fc1c\" \"otel-collector.opentelemetry-system.svc.cluster.local:4317\" \"10.244.0.18:4317\" outbound|4317||otel-collector.opentelemetry-system.svc.cluster.local 10.244.0.21:38756 10.96.244.185:4317 10.244.0.21:44662 - default
)
Trace ID:
Span ID:
Flags: 0
","kind":"exporter","data_type":"logs","name":"logging"}
```

Actually I don't know if it is possible have both OpenTelemetry ALS and JSON encoding and after searching a lot online I still don't have a final answer (likely I overlooked something here) and maybe you can point me to the right direction.

In the end, my use case is to have metadata in the payload sent to OtelCollector in order to perform disambiguation downstream. I basically thought about this 2 options:
- having a JSON body for the EnvoyAL onto which apply processing to extract metadata (filled in by the EnvoyAL operators)
- adding metadata directly to EnvoyLogs (this seems not feasable with Istio TelemetryAPI and not simple / scalable in general)

Hope you can help me with this. Thanks in advance for your time.

### Version

```Text
$ istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (4 proxies)
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
$ helm version --short
v3.14.2+gc309b6f
```

**Comment by zirain** [comment]
why did you use that configuration? it seems invalid.

**Comment by AlessandroFazio** [comment]
Hello, @zirain. Thanks for the quick reply. 
As I said, that configuration is kind of a collage of various pieces of config I came across in differnt Github issues about Otel integration and I'm aware those pieces can be incosistent with each other or invalid per se. However this is the best I could do. 

Still my questions: is it possible to have JSON Encoding with OpenTelemetry ALS and if so how? 
Sorry, but this is not 100% in docs.

**Comment by howardjohn** [comment]
I think you want something like this:

```yaml
global:
  proxy:
    tracer: none
meshConfig:
  enableTracing: true
  defaultConfig:
    tracing: {}
  defaultProviders:
    tracing:
      - opentelemetry
    accessLogging:
      - otel
  accessLogEncoding: JSON
  extensionProviders:
    - name: opentelemetry
      opentelemetry:
        service: "otel-collector.opentelemetry-system.svc.cluster.local"
        port: 4317
    - name: otel
      envoyOtelAls:
        service: "otel-collector.opentelemetry-system.svc.cluster.local"
        port: 4317
        logFormat:
          labels:
            authority": "%REQ(:AUTHORITY)%"
            bytes_received": "%BYTES_RECEIVED%"
            bytes_sent": "%BYTES_SENT%"
            downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%"
            downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%"
            duration": "%DURATION%"
            method": "%REQ(:METHOD)%"
            path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            protocol": "%PROTOCOL%"
            requested_server_name": "%REQUESTED_SERVER_NAME%"
            response_code": "%RESPONSE_CODE%"
            response_flags": "%RESPONSE_FLAGS%"
            route_name": "%ROUTE_NAME%"
            start_time": "%START_TIME%"
            upstream_cluster": "%UPSTREAM_CLUSTER%"
            upstream_host": "%UPSTREAM_HOST%"
            upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%"
            upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
            upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
            user_agent": "%REQ(USER-AGENT)%"
            x_forwarded_for": "%REQ(X-FORWARDED-FOR)%
```
