### ISSUE TITLE
EnvoyFilter can't replace without type_url when apply to NETWORK_FILTER

### ISSUE THREAD

**Issue by yefengzhichen** [istio/istio#50341]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

EnvoyFilter can't replace without type_url when apply to NETWORK_FILTER. The error is "Proto constraint validation failed (DubboProxyValidationError.StatPrefix: value length must be at least 1 characters): " in sidecar's config_dump. The envoyfilter is:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test
  namespace: servicemesh
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          destinationPort: 20880
          filter:
            name: envoy.filters.network.tcp_proxy
        name: virtualInbound
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.dubbo_proxy
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.dubbo_proxy.v3.DubboProxy"
          value:
            routeConfig:
            - interface: '*'
              name: inbound|20880||
              routes:
              - match:
                  method:
                    name:
                      safeRegex:
                        googleRe2: {}
                        regex: .*
                route:
                  cluster: inbound|20880||
            statPrefix: inbound|20880||
```
 But when modifing the typed_config  as follow:
```
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.network.dubbo_proxy.v3.DubboProxy
```
The sidecar's config_dump is correct. But both ways are shown in official document("https://istio.io/latest/docs/reference/config/networking/envoy-filter/").

### Version

```Text
istioctl version 
client version: 1.19-dev
control plane version: 1.19-dev
data plane version: 1.19.5 (6 proxies)
kubectl version
Client Version: v1.28.2
Server Version: v1.28.2
```
