### ISSUE TITLE
stats-filters are still generated when using istio-operator to install istio

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#50350]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Dear experts,
I am using istio-operator (version: 1.20.3) to install my istio. 
I know for istio after 1.18, the stats-filters should not be installed by default(instead Telemetry API would be used).
However, for my case, I still see stats-filters-1.17/1.18/1.19/1.20, also tcp-stats-filters with same versions got installed.

Below is my istiooperator yaml.

I am wondering **is there any configs to switch smoothly from current situation to the new Telemetry API way**?

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogFormat: |
      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)% requestSize=%BYTES_RECEIVED% responseSize=%BYTES_SENT% requestPath=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
    defaultConfig:
      extraStatTags:
      - request_url_path
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin:
          address: otel-collector.monitoring.svc:9411
  values:
    cni:
      excludeNamespaces:
      - istio-system
      - kube-system
      - kube-node-lease
      - kube-public
    sidecarInjectorWebhook:
      neverInjectSelector:
      - matchExpressions:
        - key: app-istio-inject
          operator: In
          values:
          - disable
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          configOverride:
            gateway:
              metrics:
              - dimensions:
                  request_url_path: request.url_path.matches('^/(callback|login|logout|extendsession|api/user).*$')?"request-router-auth":"unknown"
                name: requests_total
            inboundSidecar:
              metrics:
              - dimensions:
                  request_url_path: request.url_path.matches('^/(callback|login|logout|extendsession|api/user).*$')?"request-router-auth":"unknown"
                name: requests_total
            outboundSidecar:
              metrics:
              - dimensions:
                  request_url_path: request.url_path.matches('^/(callback|login|logout|extendsession|api/user).*$')?"request-router-auth":"unknown"
                name: requests_total
    egressGateways:
    - enabled: true
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: pool
                  operator: In
                  values:
                  - application
        podDisruptionBudget:
          minAvailable: 1
        replicaCount: 2
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: pool
                  operator: In
                  values:
                  - application
        podDisruptionBudget:
          minAvailable: 1
        replicaCount: 2
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        service:
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: https-status-port
            port: 15921
            protocol: TCP
            targetPort: 15921
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tcp
            port: 31400
            protocol: TCP
            targetPort: 31400
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
          type: ClusterIP
      name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: pool
                  operator: In
                  values:
                  - application
        podDisruptionBudget:
          minAvailable: 1
        replicaCount: 2


```

### Version

```Text
Istio version:
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3 (33 proxies)

k8s version:
Client Version: v1.29.1
Server Version: v1.27.9
```
