### ISSUE TITLE
Add tests for readiness and liveness probes on statefulsets with multiple replicas.

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#5037]
istio sidecar injection causes readliness and liveness probe failure with `statefulsets` on the second pod

  Warning  Unhealthy              5m    kubelet, gke-joy-test-default-pool-cf9a73c3-0pcq  Readiness probe failed: Get http://10.44.10.13:9001/healthz: read tcp 10.44.10.1:33344->10.44.10.13:9001: read: co

```
kind: StatefulSet
spec:
  replicas: 2
....
    spec:
      containers:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9001
        name: esp
        ports:
        - containerPort: 9001
          name: health
          protocol: UDP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9001
```

**Comment by xiaolanz** [comment]
Same problem observed on replicasets too

**Comment by xiaolanz** [comment]
Filed an issue: https://github.com/kubernetes/kubernetes/issues/62798

**Comment by xiaolanz** [comment]
added

  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10

1) Increase the number of pilot pods
2) Change the discoveryRefreshDelay from 1s to 5s.

**Comment by morvencao** [comment]
Please refer to: https://github.com/istio/istio/issues/2628

**Comment by liamawhite** [comment]
@xiaolanz is this still an issue in 0.8?

**Comment by wattli** [comment]
I believe this should be solved in 0.8, will give a try and update this issue soon.

**Comment by aneslozo** [comment]
I can confirm that issue is still present in 0.8. 
As soon as I remove readiness and liveness everything is working fine.

**Comment by csabakollar** [comment]
having the same issue with istio-0.8.0 and postgres (timescaledb).

I set liveness and readiness probes to:
```
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - su - postgres -c "pg_isready --host=$POD_IP"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: timescaledb
        ports:
        - containerPort: 5432
          name: psql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - su - postgres -c "pg_isready --host=$POD_IP"
```
(POD_IP env var is a fieldRef from fieldPath: status.podIP)

Replaced the $POD_IP with 127.0.0.1, the pod stays alive.
Maybe this "workaround" will help for some.
