### ISSUE TITLE
Added header not available in EnvoyFilter

### ISSUE THREAD

**Issue by vjerci** [istio/istio#50383]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have virtual service in which i add `X-Custom-Header`
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  generation: 1
  labels:
    app: grafana
  name: grafana-vsvc
spec:
  gateways:
  - mygateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /prefix/grafana
    rewrite:
      uri: /prefix/grafana
    route:
    - destination:
        host: grafana.prefix.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          add:
            X-Custom-Header: customHeaderValue
```

However when i try to access that header in `EnvoyFilter` it doesn't appear to be there

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt-to-teknoir-header-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      teknoir.org/activity-logs-enabled: "true"
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                request_handle:logDebug("Header is: " .. request_handle:headers():get("X-Custom-Header")
              end
```

Debug doesn't show header.

I am not sure if i am doing something wrong or if it is a bug?

### Version

```Text
client version: 1.21.0
data plane version: 1.17.8-asm.20

Client Version: v1.27.9-dispatcher
Kustomize Version: v5.0.1
Server Version: v1.27.8-gke.1067004
```
