### ISSUE TITLE
EnvoyFilter is a no-op on certain ROUTE_CONFIGURATION fields.

### ISSUE THREAD

**Issue by dwj300** [istio/istio#50402]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to disable `ignore_port_in_host_matching` on a gateway, and was using the following EnvoyFilter with no success:
```
    - applyTo: ROUTE_CONFIGURATION
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          ignore_port_in_host_matching: false
```
I also tried
```
    - applyTo: ROUTE_CONFIGURATION
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          vhost:
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          name: envoy.config.route.v3.RouteConfiguration
          ignore_port_in_host_matching: true
```
Which was referenced in https://github.com/istio/istio/issues/41876. Is there logic that ignores certain fields? 

### Version

```Text
1.19.7
```
