### ISSUE TITLE
What values to set for METRIC_ROTATION_INTERVAL / METRIC_GRACEFUL_DELETION_INTERVAL 

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#50419]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,
I am trying to enable metrics rotation feature by adding env to my pilot config.

But I am confused what is the difference between these 2 envs(didn't find any documents to explain this): METRIC_ROTATION_INTERVAL, METRIC_GRACEFUL_DELETION_INTERVAL.

Also, how should I set those values to avoid losing my metrics data? 
I am using Prometheus to scrape my metrics with a scraping interval to 30s.

### Version

```Text
Istio version:
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3 (3 proxies), 1.21.0 (7 proxies)

K8s version:
Client Version: v1.16.0
Server Version: v1.27.3
```

**Comment by zirain** [comment]
`METRIC_ROTATION_INTERVAL>METRIC_GRACEFUL_DELETION_INTERVAL>=2*prometheus_scrape_interval`

**Comment by suxiaoxiaomm** [comment]
@zirain Thanks a lot for the suggestion.
However, I got below errors after I set the envs. Could you please help?
```
2024-04-18T08:56:57.012339Z     info    klog    k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1alpha1.IstioOperator: unknown field "env" in istio.operator.v1alpha1.ComponentSpec
2024-04-18T08:56:57.012398Z     error   klog    k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.IstioOperator: failed to list *v1alpha1.IstioOperator: unknown field "env" in istio.operator.v1alpha1.ComponentSpec
```

Below is my IstioOperator yaml :

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: demo
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin:
          address:  "zipkin.monitoring:9411" 
  components:
    pilot:
      enabled: true
      env:
        METRIC_ROTATION_INTERVAL: 10m
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
      k8s:
        podDisruptionBudget:
          minAvailable: 1
        replicaCount: 2
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        podDisruptionBudget:
          minAvailable: 1
        replicaCount: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2"
        service:
          type: ClusterIP
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: https-status-port
            port: 15921
            protocol: TCP
            targetPort: 15921
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tcp
            port: 31400
            protocol: TCP
            targetPort: 31400
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        podDisruptionBudget:
          minAvailable: 1
        replicaCount: 2
    cni:
      enabled: true
      namespace: kube-system
  values:
    cni:
      excludeNamespaces:
      - {{ .Release.Namespace | quote }}
      - kube-system
      - kube-node-lease
      - kube-public
    sidecarInjectorWebhook:
      neverInjectSelector:
      - matchExpressions:
        - {key: app-istio-inject, operator: In, values: [disable]}
```
