### ISSUE TITLE
Gateway configured with wildcard certificate cannot configure ProtocolVersion for individual hosts.

### ISSUE THREAD

**Issue by qRainBirdp** [istio/istio#50410]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We referred to this document: https://istio.io/latest/docs/ops/common-problems/network-issues/?_ga=2.182956965.285059795.1712821973-1216388677.1712562175#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate
So we configured only one gateway for the wildcard domain, corresponding to multiple virtual services.
However, we were unable to configure TLS parameters such as ProtocolVersion for individual hosts as a result. We attempted the following configuration, but encountered the initial 404 issue:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: widecard-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.test.net"
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "*.test.net"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: widecard-credential
      mode: SIMPLE
  - hosts:
    - "tls.test.net"
    port:
      name: https-tls
      number: 443
      protocol: HTTPS
    tls:
      credentialName: widecard-credential
      mode: SIMPLE
      minProtocolVersion: TLSV1_2
      cipherSuites:
        - TLS_ECDHE-ECDSA-AES256-GCM-SHA384
        - TLS_ECDHE-RSA-AES256-GCM-SHA384
        - TLS_ECDHE-ECDSA-CHACHA20-POLY1305
        - TLS_ECDHE-RSA-CHACHA20-POLY1305
        - TLS_ECDHE-ECDSA-AES128-GCM-SHA256
        - TLS_ECDHE-RSA-AES128-GCM-SHA256
        - TLS_DHE-RSA-AES256-GCM-SHA384
        - TLS_DHE-RSA-AES128-GCM-SHA256
```
I wonder if there's a way to meet both of these requirements simultaneously.

### Version

```Text
istio: 1.10.6

root@hun16-207:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-508b6b3", GitCommit:"3e34c037fbb04e926cd6e064d95b384933ac06e2", GitTreeState:"clean", BuildDate:"2024-01-29T21:01:13Z", GoVersion:"go1.19.13", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

Null
