### ISSUE TITLE
Second Telemetry API doesn't take effect

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#50414]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Dear Experts,
I am currently working on using Telemetry API to customize my metrics.
I have 2 types of customization: add some customization tags and remove some unneeded tags.

I applied below 2 Telemetry yaml. **However, my second telemetry: `remove-tag`s, doesn't really take effect.**
If I only apply `remove-tags`, I can see it takes effects.

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-tags
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_url_path:
              value: request.url_path.matches('^/(login|logout|extendsession).*$')?"request-router-auth":"unknown"
        - match:
            metric: REQUEST_DURATION
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_url_path:
              value: request.url_path.matches('^/(login|logout|extendsession).*$')?"request-router-auth":"unknown"
```
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: remove-tags
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: ALL_METRICS
            mode: CLIENT_AND_SERVER
          tagOverrides:
            controller_revision_hash:
              operation: REMOVE
            destination_app:
              operation: REMOVE 
            destination_canonical_revision:
              operation: REMOVE 
            destination_canonical_service:
              operation: REMOVE
            destination_principal:
              operation: REMOVE
            destination_cluster:
              operation: REMOVE
            destination_service_name:
              operation: REMOVE
            destination_service_namespace:
              operation: REMOVE
            istio:
              operation: REMOVE
            istio_io_rev:
              operation: REMOVE
            operator_istio_io_component:
              operation: REMOVE
            release:
              operation: REMOVE
            service_istio_io_canonical_name:
              operation: REMOVE
            service_istio_io_canonical_revision:
              operation: REMOVE
            source_app:
              operation: REMOVE
            source_canonical_revision:
              operation: REMOVE
            source_canonical_service:
              operation: REMOVE
            source_principal:
              operation: REMOVE
```

### Version

```Text
Istio version:
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3 (3 proxies), 1.21.0 (7 proxies)

K8s version:
Client Version: v1.16.0
Server Version: v1.27.3
```
