### ISSUE TITLE
Unexpected matchlabels added

### ISSUE THREAD

**Issue by jack9410** [istio/istio#50481]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

While installing istio with istioctl 1.16.7 My ingress gateway deployment suddenly has extra matchLabels  even though I didn't add any matchLabels.

Changed matchLabels
```
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      chart: gateways
      heritage: Tiller
      istio: ingressgateway
      release: istio
``` 

My former mathLabels were like this

```
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
```

Because of these specs I'm unnable to upgrade my istio version to 1.18  with error Invalid value: 
`v1.LabelSelector{MatchLabels:map[string]string{"app":"istio-ingressgateway", "istio":"ingressgateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

But installing with the same specs back to 1.16 works just fine even though I didn't add any match labels

Does anyone have the same problem?

### Version

```Text
istioctl version
client version: 1.16.7
istiod version: 1.16.7
data plane version: 1.16.7 (1316 proxies)

kubectl version --short
Client Version: v1.25.15
Kustomize Version: v4.5.7
Server Version: v1.25.16-eks-508b6b3

helm version --short
v3.13.1+g3547a4b
```
