### ISSUE TITLE
Istio merges non-Istio conditions into the Istio-controlled status stanzas of HTTPRoutes

### ISSUE THREAD

**Issue by guicassolato** [istio/istio#50484]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When a Gateway API HTTPRoute object specifies a parentRef that is an Istio-controlled object (e.g. an Istio-provided Gateway API Gateway), and therefore Istio also starts managing that HTTPRoute object, Istio maintains a parent status stanza in the route object, with controllerName set equal to [`istio.io/gateway-controller`](https://github.com/istio/istio/blob/98a69d96ce5c36e5cdc35367abec7e1c24bae5a4/pilot/pkg/features/pilot.go#L237-L238). In cases where another gateway controller is running in the same Kubernetes cluster and acting on the same HTTPRoute object managed by Istio, if the other gateway controller also creates a parent status stanza in the route object (with its own identifier specified in the controllerName field) _and_ the parentRef happens to coincide with the parentRef controlled by Istio (i.e. same group, kind, name, namespace, etc), Istio will merge all status conditions from the non-Istio parent status into the conditions of the Istio-maintained one.

In a test where a second controller with `controllerName: kuadrant.io/policy-controller` added a second parent status to an Istio-controlled HTTPRoute, for the same parentRef as the Istio-managed one, the route ended up with two parent statuses where the Istio-created one (`controllerName: istio.io/gateway-controller`) contained all its route-related conditions (i.e. `Accepted`, `ResolvedRefs`), plus a copy of each condition from the other controller's parent status.

**Note:** The use case involves 2 controllers that set statuses in the route for the same Istio-provided gateway parent, hence identical parentRefs.

**Observed:**

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: {…}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-ingressgateway
    namespace: istio-system
  rules: […]
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-04-15T15:19:48Z"
      message: Route affected by policy kuadrant.io/v1beta2, Kind=AuthPolicy
        in namespace default with name allow-toys
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: kuadrant.io/AuthPolicyAffected
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: Route affected by policy kuadrant.io/v1beta2, Kind=RateLimitPolicy
        in namespace default with name high-limit-toys
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: kuadrant.io/RateLimitPolicyAffected
    controllerName: kuadrant.io/policy-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-ingressgateway
      namespace: istio-system
  - conditions:
    - lastTransitionTime: "2024-04-15T15:19:48Z"
      message: Route affected by policy kuadrant.io/v1beta2, Kind=AuthPolicy
        in namespace default with name allow-toys
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: kuadrant.io/AuthPolicyAffected
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: Route affected by policy kuadrant.io/v1beta2, Kind=RateLimitPolicy
        in namespace default with name high-limit-toys
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: kuadrant.io/RateLimitPolicyAffected
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: Route was valid
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: All references resolved
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: istio.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-ingressgateway
      namespace: istio-system
```

**Expected:**

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: {…}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-ingressgateway
    namespace: istio-system
  rules: […]
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-04-15T15:19:48Z"
      message: Route affected by policy kuadrant.io/v1beta2, Kind=AuthPolicy
        in namespace default with name allow-toys
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: kuadrant.io/AuthPolicyAffected
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: Route affected by policy kuadrant.io/v1beta2, Kind=RateLimitPolicy
        in namespace default with name high-limit-toys
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: kuadrant.io/RateLimitPolicyAffected
    controllerName: kuadrant.io/policy-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-ingressgateway
      namespace: istio-system
  - conditions:
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: Route was valid
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-04-15T15:26:12Z"
      message: All references resolved
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: istio.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-ingressgateway
      namespace: istio-system
```

I understand the behavior described happens at https://github.com/istio/istio/blob/0108bc4c71d89fc27b81e35a1e68637fa5856568/pilot/pkg/config/kube/gateway/conditions.go#L154-L156 

Assuming the behavior is not by design, I suppose it could be fixed by adding `&& s.ControllerName != k8s.GatewayController(features.ManagedGatewayController)` to the condition.

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (1 proxies)

$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
