### ISSUE TITLE
AuthorizationPolicy is allowing to use Prefix, Suffix match together in rules.from.source.principals

### ISSUE THREAD

**Issue by sonuchoudhari** [istio/istio#50504]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

AuthorizationPolicy is allowing to use Prefix, Suffix match together in rules.from.source.principals

**Istio Version** 1.20.3

**Example AuthorizationPolicy:**

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: remote-auth
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["*.abc-ext.mesh/abc*"]
    to:
    - operation:
        hosts: ["distributor.demo.com", "receiver.demo.com"]     
  selector:
    matchLabels:
      istio: {{ .Release.Name }}
```

**Expected Behaviour:** 

It should not allow prefix and suffix usage together like `*.abc-ext.mesh/abc*` because in that scenario it's giving access rights to more names however in current scenario it's allowing the access from names which follow the pattern `*.abc-ext.mesh/abc*`

### Version

```Text
NA
```
