### ISSUE TITLE
DestinationRule tls-example from https://istio.io/docs/reference/config/istio.networking.v1alpha3.html invalid

### ISSUE THREAD

**Issue by esnible** [istio/istio#5052]
To reproduce, try to create a rule from tls-example, like this:

```
echo | istioctl create -f- <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tls-example
spec:
  name: example.com
  trafficPolicy:
    tls:
      mode: SIMPLE # initiates HTTPS when talking to example.com
EOF
```

The result is 
```
* empty domain name not allowed
*  is not a valid IP
```
