### ISSUE TITLE
RequestAuthentication's fromCookies does not work properly.

### ISSUE THREAD

**Issue by jy-kkkim** [istio/istio#50588]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

```
spec:
  jwtRules:
  - fromCookies:
    - user_access_token
```
For example, the fromCookies item in the RequestAuthentication resource was set as shown above.
The behavior I expected is that the user cannot access the service when there is no 'user_access_token' item in the Cookie item in the web browser or the token value of the 'user_access_token' item is incorrect.
However, in actual operation, if there is no 'user_access_token' item among the browser's Cookie items, the service is accessed directly.
I don't understand how this works.

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ap-test
spec:
  rules:
  - from:
    - source:
        requestPrincipals:
        - '*'
```
Also, the strange thing is that if you create an AuthorizationPolicy like above, if there is no 'user_access_token' item, the user's access is blocked.
There are two services running in my deployment. The web service is running on port 80 and the sftp service is running on port 22.
The problem is that if you only create RequestAuthentication, you can connect to both web and sftp services normally, but you can connect even if there is no 'user_access_token' in the browser's Cookie items. If you also create AuthorizationPolicy, the connection is rejected if there is no 'user_access_token', but the sftp service does not allow connection. The point is that it cannot be done.
How to solve this? Please help me...

### Version

```Text
1.21.0
```
