### ISSUE TITLE
Force the calling of ValidatingWebhookConfiguration for all Istio-objects

### ISSUE THREAD

**Issue by miono** [istio/istio#50663]
**Describe the feature request**
Currently the ValidatingWebhookConfiguration only matches objects with the `istio.io/rev` label set (to the current running revision).
This means that if someone creates an object (our use case is that our tenants can create VirtualServices in their own namespaces) they can bypass the validating webhook simply by not setting that label on their VirtualService.
```
  objectSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - 1-19-4
```
My proposal is to add another configuration-value allowing us to disable that objectSelector, effectively sending all istio-related objects to the webhook for validation.

**Describe alternatives you've considered**
I suppose this will get baked in when https://github.com/istio/istio/issues/46151 is completed, but it doesn't seem to be near completion right now. (currently blocked by CEL cost-limits)

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by miono** [comment]
Thanks, I'll go ahead and explore that path!

**Comment by miono** [comment]
I have now done some more digging around this and while tagging a revision as `default` will generate a new validatingwebhook, this new webhook has an objectSelector like this:
```
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist

```
This means that a tenant can set a label on the VirtualService to "whatevervalue", and that will then bypass the validation.
