### ISSUE TITLE
DNS ServiceEntry endpoint ordering is not stable

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50749]
I *think* this will be more expensive to envoy, so we should sort in some way.

Reproducer config:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se1
spec:
  hosts:
  - example.com
  ports:
  - name: port1
    number: 80
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: 1.example.com
  - address: 2.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se2
spec:
  hosts:
  - example.com
  ports:
  - name: port1
    number: 80
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: 3.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se3
spec:
  hosts:
  - example.com
  ports:
  - name: port1
    number: 80
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: 4.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se4
spec:
  hosts:
  - example.com
  ports:
  - name: port1
    number: 80
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: 5.example.com
```

order will switch around.

It may apply to `STATIC` as well, I did not check
