### ISSUE TITLE
How to unset "retry_host_predicate" using EnvoyFilter?

### ISSUE THREAD

**Issue by ktalg** [istio/istio#50756]
Requests routed using the consistency hash lb are retried and the target host is affected by envoy's 'retry_host_predicate', and the target host is different from the initial request, which is not what I expected, so I would like to use EnvoyFilter to unset this configuration, but I found that EnvoyFilter can hardly merge fields of this array type when configuring

original config_dump：

```json
{
  "name": "httpbin.infra-al-cn-gdsz-1.svc.cluster.local:8000",
  "domains": [
    "httpbin.infra-al-cn-gdsz-1.svc.cluster.local"
  ],
  "routes": [
    {
      "match": {
        "prefix": "/"
      },
      "route": {
        "cluster": "outbound|8000||httpbin.infra-al-cn-gdsz-1.svc.cluster.local",
        "timeout": "0s",
        "retry_policy": {
          "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
          "num_retries": 2,
          "retry_host_predicate": [
            {
              "name": "envoy.retry_host_predicates.previous_hosts"
            }
          ],
          "host_selection_retry_max_attempts": "5",
          "retriable_status_codes": [
            503
          ]
        },
        "hash_policy": [
          {
            "header": {
              "header_name": "xxy"
            }
          }
        ],
        "max_stream_duration": {
          "max_stream_duration": "0s",
          "grpc_timeout_header_max": "0s"
        }
      },
      "decorator": {
        "operation": "httpbin.infra-al-cn-gdsz-1.svc.cluster.local:8000/*"
      },
      "name": "default"
    }
  ],
  "include_request_attempt_count": true
}
```

envoyfilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: set-retry-predicate
  namespace: infra-al-cn-gdsz-1
spec:
  workloadSelector:
    labels:
      app: grpc-c
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: ANY
        routeConfiguration:
          vhost:
            name: httpbin.infra-al-cn-gdsz-1.svc.cluster.local:8000
            route:
              action: ROUTE
              name: default
          name: "8000"
      patch:
        operation: MERGE
        value:
          route:
            retry_policy:
              retry_host_predicate: [ ] # NOT work !
              host_selection_retry_max_attempts: 1 # work !
```

new config_dump
```json
{
  "name": "httpbin.infra-al-cn-gdsz-1.svc.cluster.local:8000",
  "domains": [
    "httpbin.infra-al-cn-gdsz-1.svc.cluster.local"
  ],
  "routes": [
    {
      "match": {
        "prefix": "/"
      },
      "route": {
        "cluster": "outbound|8000||httpbin.infra-al-cn-gdsz-1.svc.cluster.local",
        "timeout": "0s",
        "retry_policy": {
          "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
          "num_retries": 2,
          "retry_host_predicate": [
            {
              "name": "envoy.retry_host_predicates.previous_hosts"
            }
          ],
          "host_selection_retry_max_attempts": "1",
          "retriable_status_codes": [
            503
          ]
        },
        "hash_policy": [
          {
            "header": {
              "header_name": "xxy"
            }
          }
        ],
        "max_stream_duration": {
          "max_stream_duration": "0s",
          "grpc_timeout_header_max": "0s"
        }
      },
      "decorator": {
        "operation": "httpbin.infra-al-cn-gdsz-1.svc.cluster.local:8000/*"
      },
      "name": "default"
    }
  ]
}
```
You can see that the string type host_selection_retry_max_attempts was successfully set to 1, while the array type retry_host_predicate was not. How should I set it correctly? Or is it some kind of bug?
