### ISSUE TITLE
No longer getting traffic metrics via prometheus after enabling opencensus tracing

### ISSUE THREAD

**Issue by iamasmith** [istio/istio#50860]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I routed all tracing via the defaultProvider setting to an OTEL collector which in turn is sending the traffic to a debug out and the zipkin endpoint of jaeger for some OTEL testing - I wanted to check how the tracing worked with an instrumented app alongside Istio.

Prometheus endpoint seems now to report some metrics all istio_agent metrics but no metrics like istio_requests_total - only istio_agent_* and envoy_* - this observation is from curling the endpoint direct and not possible issues associated with dropped labels in scrape configs.

I have even explicitly added prometheus into the defaultProviders just in case there was an issue caused by an overwrite of the defaultConfig missing the prometheus config but this seems to produce the same result.

Apart from the missing metrics Istio works fully as expected (although I now have no traffic views in Kiali because of the missing metrics on the endpoints).

Changes have only been applied using istioctl install -f <this file>

YAML supplied which I used to apply these changes
```
# istioctl install -f <thisfile>
# For now tune the service for LoadBalancer and the deployment for nodeSelector
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    cni:
      cniBinDir: /var/snap/microk8s/current/opt/cni/bin
      cniConfDir: /var/snap/microk8s/current/args/cni-network
    global:
      variant: distroless
    gateways:
      # Enable gateway injection
      istio-ingressgateway:
        injectionTemplate: gateway
      istio-egressgateway:
        injectionTemplate: gateway
  meshConfig:
    enableTracing: true
    defaultProviders:
      tracing:
      - "opencensus"
      metrics:
      - "prometheus"
    extensionProviders:
    - name: "opencensus"
      opencensus:
          service: "opentelemetry-collector.istio-system.svc.cluster.local"
          port: 55678
          context:
          - W3C_TRACE_CONTEXT
    - name: "prometheus"
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      tracing:
        sampling: 100.0
  components:
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
      k8s:
        serviceAnnotations:
          external-mdns.blakecovarrubias.com/hostnames: <redacted>
          external-mdns.blakecovarrubias.com/without-namespace: "true"
          metallb.universe.tf/ip-allocated-from-pool: <redacted>
        nodeSelector:
          kubernetes.io/arch: amd64
        service:
          type: LoadBalancer
          loadBalancerIP: <redacted>
    egressGateways:
    - name: istio-egressgateway
      namespace: istio-system
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: egresssgateway
      k8s:
        nodeSelector:
          kubernetes.io/arch: amd64
        service:
          type: ClusterIP
```

### Version

```Text
andrews@AndrewsiMac ~ % istioctl version       
client version: 1.21.1
control plane version: 1.21.1
data plane version: 1.20.3 (2 proxies), 1.21.1 (8 proxies)
andrews@AndrewsiMac ~ % kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
andrews@AndrewsiMac ~ %
```

### Additional Information

andrews@AndrewsiMac ~ % istioctl bug-report

Target cluster context: microk8s

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-05-04 20:01:35.604862 +0100 BST

Cluster endpoint: https://<readacted>:16443
CLI version:
version.BuildInfo{Version:"1.21.1", GitRevision:"ee6e9f6a314224fd9bcb808ca1d74d1dc66adba8", GolangVersion:"go1.22.2", BuildStatus:"Clean", GitTag:"1.21.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.21.1", GitRevision:"ee6e9f6a314224fd9bcb808ca1d74d1dc66adba8", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.21.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.20.3, 1.21.1}

Fetching logs for the following containers:

cnpg-operator/cnpg-operator-cloudnative-pg/cnpg-operator-cloudnative-pg-7985d8744d-hprfh/manager
external-mdns/external-mdns/external-mdns-5476fc976b-56jhg/external-mdns
gitlab/kubernetes-gitlab-runner/kubernetes-gitlab-runner-b5696bf84-g52tz/kubernetes-gitlab-runner
grafana-system/loki-stack-grafana/loki-stack-grafana-8664f6d7d9-q6csn/grafana
grafana-system/loki-stack-grafana/loki-stack-grafana-8664f6d7d9-q6csn/grafana-sc-datasources
grafana-system/loki-stack-promtail/loki-stack-promtail-gdmbb/promtail
grafana-system/loki-stack-promtail/loki-stack-promtail-qk28r/promtail
ingress-nginx/ingress-nginx-controller/ingress-nginx-controller-6f445c6458-xtw7f/controller
istio-system/istio-egressgateway/istio-egressgateway-77b476db56-hz24w/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-599b45666c-rmlv8/istio-proxy
istio-system/istiod/istiod-774c587c5-gv5n4/discovery
istio-system/jaeger/jaeger-644d89557b-krths/jaeger
istio-system/opentelemetry-collector/opentelemetry-collector-7d6c546857-gmr4k/opentelemetry-collector
kiali-system/kiali/kiali-6d6b955cd7-8csbc/istio-proxy
kiali-system/kiali/kiali-6d6b955cd7-8csbc/kiali
metallb-system/metallb-controller/metallb-controller-596f4f7b78-8x8ng/controller
metallb-system/metallb-speaker/metallb-speaker-bbb6n/speaker
metallb-system/metallb-speaker/metallb-speaker-rrv44/speaker
squid/proxy/proxy-5bfb5b9684-w9rvg/squid
test/hop-b/hop-b-687d69f78f-btzvm/hopper
test/hop-b/hop-b-687d69f78f-btzvm/istio-proxy
test/hop-c/hop-c-668975f666-tdlf7/hopper
test/hop-c/hop-c-668975f666-tdlf7/istio-proxy
test/hopper/hopper-5798cc5bf4-2ncxk/hopper
test/hopper/hopper-5798cc5bf4-2ncxk/istio-proxy
test/lpserver/lpserver-5fbbfd987-8fg7j/istio-proxy
test/lpserver/lpserver-5fbbfd987-8fg7j/lpserver
test/lpserver/lpserver-5fbbfd987-zcb69/istio-proxy
test/lpserver/lpserver-5fbbfd987-zcb69/lpserver
test/redis/redis-c779dfc45-k8rjr/istio-proxy
test/redis/redis-c779dfc45-k8rjr/redis
wiki-js/wiki-js/wiki-js-f87c88cd7-np9l5/wiki

Fetching Istio control plane information from cluster.

Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0158] (Namespace test) The Istio proxy images of the pods running in the namespace do not match the image defined in the injection configuration (pod names: [redis-c779dfc45-k8rjr]). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pods.
Warning [IST0162] (Gateway test/hopper) The gateway is listening on a target port (port 443) that is not defined in the Service associated with its workload instances (Pod selector istio=ingressgateway). If you need to access the gateway port through the gateway Service, it will not be available.
Warning [IST0162] (Gateway kiali-system/kiali) The gateway is listening on a target port (port 443) that is not defined in the Service associated with its workload instances (Pod selector istio=ingressgateway). If you need to access the gateway port through the gateway Service, it will not be available.
Warning [IST0162] (Gateway test/lpserver) The gateway is listening on a target port (port 443) that is not defined in the Service associated with its workload instances (Pod selector istio=ingressgateway). If you need to access the gateway port through the gateway Service, it will not be available.
Info [IST0102] (Namespace metallb-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace metallb-system istio-injection=enabled' to enable it, or 'kubectl label namespace metallb-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service cnpg-operator/cnpg-webhook-service) Port name webhook-server (port: 443, targetPort: webhook-server) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service grafana-system/loki-stack-grafana) Port name service (port: 80, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service metallb-system/metallb-webhook-service) Port name  (port: 443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service postgres/pg1-r) Port name postgres (port: 5432, targetPort: 5432) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service postgres/pg1-ro) Port name postgres (port: 5432, targetPort: 5432) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service postgres/pg1-rw) Port name postgres (port: 5432, targetPort: 5432) doesn't follow the naming convention of Istio port.
Creating an archive at /Users/andrews/bug-report.tar.gz.
Time used for creating the tar file is 142.565173ms.
Cleaning up temporary files in /var/folders/z1/0xmgt1h13msgf24k3gskkrch0000gn/T/bug-report.
Done.
andrews@AndrewsiMac ~ %

**Comment by iamasmith** [comment]
Additional testing - still with 1.21.1

* removed istio completely with istioctl uninstall --purge and reinstalled with this config, this produced the same results.
* removed the meshconfig section for defaultProviders, enableTracing and extensionProviders. Uninstalled and einstalled with tracing specified in the defaultConfig area specifying a zipkin endpoint and suddenly the Prometheus metrics again started to be created.

**Comment by iamasmith** [comment]
Removed istio again and reinstalled with 1.21.2 using the config shown above.

The problem returns, no Prometheus metrics at all.

**Comment by iamasmith** [comment]
OK, I'm looking at code now.

It strikes me this config is impacting the loading of envoy.filters.network.istio_stats in the proxy.. I'll keep digging.

**Comment by iamasmith** [comment]
the bootsrap node extensions collection holds the same entries from the config_dump between the two different configs so the filter is at least being loaded..

**Comment by howardjohn** [comment]
```
  meshConfig:
    enableTracing: true
    defaultProviders:
      tracing:
      - "opencensus"
      metrics:
      - "prometheus"
    extensionProviders:
    - name: "opencensus"
      opencensus:
          service: "opentelemetry-collector.istio-system.svc.cluster.local"
          port: 55678
          context:
          - W3C_TRACE_CONTEXT
    - name: "prometheus"
```

I think this is probably creating an invalid extensionProvider named `prometheus` but with no type. You want

```
    - name: "prometheus"
      prometheus: {}
```

I suspect?

Note the `name` field is an opaque thing, there is no special name in general... except a few built-in extension providers by name, of which one is `prometheus`

**Comment by iamasmith** [comment]
@howardjohn the result is the same with or without the prometheus entries in from a complete istioctl uninstall --purge so there should be no config left behind when reinstalled.

As mentioned, the Prometheus endpoint is present but lacks all entries normally added by envoy.filters.network.istio_stats, i.e. it reports all envoy_* metrics and all istio_agent_* metrics but no traffic counters.

**Comment by iamasmith** [comment]
@howardjohn yes, this seems to be exacly it.

The explicit Prometheus entry is required to enable the filter but there is a basic Prometheus implementation that delivers the metrics not related to traffic.

Thanks so much for the reply on this one, the working config is as follows 

```
# istioctl install -f <thisfile>
# For now tune the service for LoadBalancer and the deployment for nodeSelector
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    cni:
      cniBinDir: /var/snap/microk8s/current/opt/cni/bin
      cniConfDir: /var/snap/microk8s/current/args/cni-network
    global:
      variant: distroless
    gateways:
      # Enable gateway injection
      istio-ingressgateway:
        injectionTemplate: gateway
      istio-egressgateway:
        injectionTemplate: gateway
  meshConfig:
    enableTracing: true
    defaultProviders:
      tracing:
      - opencensus
      metrics:
      - prometheus
    extensionProviders:
    - name: opencensus
      opencensus:
          service: "opentelemetry-collector.istio-system.svc.cluster.local"
          port: 55678
          context:
          - W3C_TRACE_CONTEXT
          - B3
          - GRPC_BIN
          - CLOUD_TRACE_CONTEXT
    - name: prometheus
      prometheus: {}
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      tracing:
        openCensusAgent: {}
        sampling: 100.0
  components:
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
      k8s:
        serviceAnnotations:
          external-mdns.blakecovarrubias.com/hostnames: kiali, lpserver, hopper
          external-mdns.blakecovarrubias.com/without-namespace: "true"
          metallb.universe.tf/ip-allocated-from-pool: pre-linksys
        nodeSelector:
          kubernetes.io/arch: amd64
        service:
          type: LoadBalancer
          loadBalancerIP: 10.90.1.6
    egressGateways:
    - name: istio-egressgateway
      namespace: istio-system
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: egresssgateway
      k8s:
        nodeSelector:
          kubernetes.io/arch: amd64
        service:
          type: ClusterIP
```
