### ISSUE TITLE
Envoy can't start the egress listener(configured by Sidecar) on VM workload

### ISSUE THREAD

**Issue by CadenGuo** [istio/istio#50954]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a VM workload connected to a single primary istio cluster. For the VM workload, I am using Sidecar to configure ingress and egress listeners
- sidecar:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: "mesh-east-vm"
  namespace: "mesh-east-vm-istio"
spec:
  workloadSelector:
    labels:
      app: "mesh-east-vm"
  ingress:
    - port:
        number: 21100
        protocol: GRPC
        name: grpc-ingress
      captureMode: NONE
      defaultEndpoint: 127.0.0.1:8087
    - port:
        number: 21101
        protocol: HTTP
        name: http-ingress
      captureMode: NONE
      defaultEndpoint: 127.0.0.1:8088
  egress:
    - port:
        number: 15050
        protocol: GRPC
        name: grpc-egress
      bind: 127.0.0.1
      hosts:
        - istio-workload/client-000.istio-workload.svc.cluster.local
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
```

After applying the the Sidecar, I can see the ingress listeners are configured and envoy is correctly listening on both `127.0.0.1:8087` and `127.0.0.1:8088`. But for the egress listener, envoy seems to be ignoring it.

However, after checking the the envoy's configuration, I found envoy did received the configurations of the egress listener and the related upstream cluster from xDS. 
```bash
# curl 127.0.0.1:15000/clusters 2>/dev/null | grep 15050
outbound|15050||server-000.istio-workload.svc.cluster.local::observability_name::outbound|15050||server-000.istio-workload.svc.cluster.local
outbound|15050||server-000.istio-workload.svc.cluster.local::default_priority::max_connections::4294967295
outbound|15050||server-000.istio-workload.svc.cluster.local::default_priority::max_pending_requests::4294967295
outbound|15050||server-000.istio-workload.svc.cluster.local::default_priority::max_requests::4294967295
outbound|15050||server-000.istio-workload.svc.cluster.local::default_priority::max_retries::4294967295
outbound|15050||server-000.istio-workload.svc.cluster.local::high_priority::max_connections::1024
outbound|15050||server-000.istio-workload.svc.cluster.local::high_priority::max_pending_requests::1024
outbound|15050||server-000.istio-workload.svc.cluster.local::high_priority::max_requests::1024
outbound|15050||server-000.istio-workload.svc.cluster.local::high_priority::max_retries::3
outbound|15050||server-000.istio-workload.svc.cluster.local::added_via_api::true
outbound|15050||server-000.istio-workload.svc.cluster.local::eds_service_name::outbound|15050||server-000.istio-workload.svc.cluster.local
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::cx_active::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::cx_connect_fail::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::cx_total::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::rq_active::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::rq_error::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::rq_success::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::rq_timeout::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::rq_total::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::hostname::
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::health_flags::healthy
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::weight::1
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::region::ap-southeast-1
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::zone::ap-southeast-1c
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::sub_zone::
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::canary::false
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::priority::0
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::success_rate::-1
outbound|15050||server-000.istio-workload.svc.cluster.local::10.169.159.23:21100::local_origin_success_rate::-1
```

Also from the envoy config_dump, we can also find the dynamic_listener config, routeConfig and cluster config related to the egress configuration in Sidecar.

It's just, envoy doesn't actually start listener on `127.0.0.1:15050`. And I can't find any informative debug logs generated by Istio and Envoy.

### Version

```Text
$ istioctl version
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3 (10 proxies), 1.21.2 (1 proxies)

$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.23.17-eks-7a52527
```

**Comment by howardjohn** [comment]
Showing the full config dump would be handy here

**Comment by CadenGuo** [comment]
Hi @howardjohn . Thanks for the reply. I get the the full config_dump, plus some findings. Now I changed the Sidecar obj a bit, by having 2 different egress listeners:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: "mesh-east-vm"
  namespace: "mesh-east-vm-istio"
spec:
  workloadSelector:
    labels:
      app: "mesh-east-vm"
  ingress:
    - port:
        number: 21100
        protocol: GRPC
        name: grpc-ingress
      captureMode: NONE
      defaultEndpoint: 127.0.0.1:8087
    - port:
        number: 21101
        protocol: HTTP
        name: http-ingress
      captureMode: NONE
      defaultEndpoint: 127.0.0.1:8088
  egress:
    - port:
        number: 15050
        protocol: GRPC
        name: grpc-egress
      bind: 127.0.0.1
      captureMode: NONE
      hosts:
        - "istio-workload-payment/server-000.istio-workload-payment.svc.cluster.local"
        - "istio-workload-payment/server-001.istio-workload-payment.svc.cluster.local"
    - port:
        number: 15051
        protocol: HTTP
        name: http-egress
      bind: 127.0.0.1
      hosts:
        - "istio-workload-payment/client-000.istio-workload-payment.svc.cluster.local"
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
```

The major difference between them is the egress listener listening on port `15050` has `captureMode: NONE` configured while the other listener (on 15051) doesn't have this configuration. 
With this Sidecar applied, the full config dump is like this(the file below):
[config_dump_istio_2024-05-10T03_23_56+0000.json](https://github.com/istio/istio/files/15270101/config_dump_istio_2024-05-10T03_23_56%2B0000.json)

After comparing the dynamic listeners of port 15050 and port 15051, I found the dynamic listener config of 15051 has this line added
```
```
