### ISSUE TITLE
envoy sidecar Sending local reply with details upgrade_failed

### ISSUE THREAD

**Issue by JacobLi11** [istio/istio#50980]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I use istio to proxy my headscale service, I always get 403 upgrade_filed when upgrading the protocol

### Version

```Text
~ istioctl version                                                                                 
client version: 1.21.0
control plane version: 1.23-alpha.f653b34fe27ec8f781e9d837d43cd6234e3a34b6
data plane version: 1.23-alpha.044be69f174a7afe8a827ddc4e9717df7ee97cd3 (2 proxies), 1.23-alpha.08111f35b2039f6653f2c1b9091f370af06e91f2 (1 proxies), 1.23-alpha.0f02c6e9352d9c45f24b2e9fb2013afa82ad5ad0 (2 proxies), 1.23-alpha.247709fd134c3dfaa5f41f4b182dcd2f1a5d7cbf (1 proxies), 1.23-alpha.445747860dfcb96411cddd82d6bf1ca346626851 (1 proxies), 1.23-alpha.713cd5d19404bad19669540656f4fa31b4641a08 (1 proxies), 1.23-alpha.9108eff3809e9e79ac2dd687171c2c9fedc66b29 (1 proxies), 1.23-alpha.9f7a6912dca503ded3d12827b386c16113fc54fc (1 proxies), 1.23-alpha.f3c6047d3984b169aebf4ad7bebe944ac1309ba2 (10 proxies), 1.23-alpha.f653b34fe27ec8f781e9d837d43cd6234e3a34b6 (20 proxies)
~ kubectl version                                                                     
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:14:46Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.15-eks-adc7111", GitCommit:"28dec7aeda929bdde90b9a27f64c73d542faae9e", GitTreeState:"clean", BuildDate:"2024-04-01T19:25:42Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/amd64"}
```

#####
istio sidecar log

2024-05-10T09:07:29.295005Z	trace	envoy http external/envoy/source/common/http/filter_manager.cc:1245	[Tags: "ConnectionId":"3219","StreamId":"9716528423736969404"] encode headers called: filter=istio.metadata_exchange status=0	thread=33
2024-05-10T09:07:29.295019Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1772	[Tags: "ConnectionId":"3219","StreamId":"9716528423736969404"] closing connection due to connection close header	thread=33
2024-05-10T09:07:29.295029Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1838	[Tags: "ConnectionId":"3219","StreamId":"9716528423736969404"] encoding headers via codec (end_stream=true):
':status', '403'
'date', 'Fri, 10 May 2024 09:07:29 GMT'
'server', 'envoy'
'connection', 'close'
	thread=33
2024-05-10T09:07:29.295042Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:525	[Tags: "ConnectionId":"3219"] writing 116 bytes, end_stream false	thread=33
2024-05-10T09:07:29.295052Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1950	[Tags: "ConnectionId":"3219","StreamId":"9716528423736969404"] Codec completed encoding stream.	thread=33
2024-05-10T09:07:29.295058Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:252	[Tags: "ConnectionId":"3219","StreamId":"9716528423736969404"] doEndStream() resetting stream	thread=33
2024-05-10T09:07:29.295064Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1907	[Tags: "ConnectionId":"3219","StreamId":"9716528423736969404"] stream reset: reset reason: local reset, response details: -	thread=33
2024-05-10T09:07:29.295130Z	trace	envoy main external/envoy/source/common/event/dispatcher_impl.cc:228	item added to deferred deletion list (size=1)	thread=33
2024-05-10T09:07:29.295142Z	trace	envoy misc external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60	enableTimer called on 0x15ebbe74e380 for 3600000ms, min is 3600000ms	thread=33
2024-05-10T09:07:29.295146Z	trace	envoy main external/envoy/source/common/event/dispatcher_impl.cc:228	item added to deferred deletion list (size=2)	thread=33
2024-05-10T09:07:29.295154Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:146	[Tags: "ConnectionId":"3219"] closing data_to_write=116 type=2	thread=33
2024-05-10T09:07:29.295162Z	debug	envoy connection external/envoy/source/common/network/connection_impl_base.cc:53	[Tags: "ConnectionId":"3219"] setting delayed close timer with timeout 1000 ms	thread=33
2024-05-10T09:07:29.295180Z	trace	envoy http external/envoy/source/common/http/http1/codec_impl.cc:943	[Tags: "ConnectionId":"3219"] message complete	thread=33
2024-05-10T09:07:29.295183Z	trace	envoy http external/envoy/source/common/http/http1/codec_impl.cc:951	[Tags: "ConnectionId":"3219"] Pausing parser due to upgrade.	thread=33
2024-05-10T09:07:29.295190Z	trace	envoy http external/envoy/source/common/http/http1/codec_impl.cc:696	[Tags: "ConnectionId":"3219"] parsed 666 bytes	thread=33
2024-05-10T09:07:29.295193Z	trace	envoy http external/envoy/source/common/http/http1/codec_impl.cc:623	[Tags: "ConnectionId":"3219"] direct-dispatched 0 bytes	thread=33
2024-05-10T09:07:29.295199Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:146	[Tags: "ConnectionId":"3219"] closing data_to_write=116 type=2	thread=33
2024-05-10T09:07:29.295207Z	trace	envoy main external/envoy/source/common/event/dispatcher_impl.cc:122	clearing deferred deletion list (size=2)	thread=33
2024-05-10T09:07:29.295230Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:610	[Tags: "ConnectionId":"3219"] socket event: 2	thread=33
2024-05-10T09:07:29.295236Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:733	[Tags: "ConnectionId":"3219"] write ready	thread=33
2024-05-10T09:07:29.295273Z	trace	envoy connection external/envoy/source/common/network/raw_buffer_socket.cc:70	[Tags: "ConnectionId":"3219"] write returns: 116	thread=33
2024-05-10T09:07:29.295281Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:784	[Tags: "ConnectionId":"3219"] write flush complete	thread=33
2024-05-10T09:07:29.295363Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:610	[Tags: "ConnectionId":"3218"] socket event: 3	thread=34
2024-05-10T09:07:29.295374Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:733	[Tags: "ConnectionId":"3218"] write ready	thread=34
2024-05-10T09:07:29.295378Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:650	[Tags: "ConnectionId":"3218"] read ready. dispatch_buffered_data=0	thread=34
2024-05-10T09:07:29.295421Z	trace	envoy connection external/envoy/source/common/network/raw_buffer_socket.cc:25	[Tags: "ConnectionId":"3218"] read returns: 411	thread=34
2024-05-10T09:07:29.295433Z	trace	envoy connection external/envoy/source/common/network/raw_buffer_socket.cc:39	[Tags: "ConnectionId":"3218"] read error: Resource temporarily unavailable, code: 0	thread=34
2024-05-10T09:07:29.295439Z	trace	envoy filter external/envoy/source/common/tcp_proxy/tcp_proxy.cc:833	[Tags: "ConnectionId":"3217"] upstream connection received 411 bytes, end_stream=false	thread=34
2024-05-10T09:07:29.295475Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:525	[Tags: "ConnectionId":"3217"] writing 411 bytes, end_stream false	thread=34
2024-05-10T09:07:29.295489Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:610	[Tags: "ConnectionId":"3217"] socket event: 2	thread=34
2024-05-10T09:07:29.295493Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:733	[Tags: "ConnectionId":"3217"] write ready	thread=34
2024-05-10T09:07:29.295517Z	trace	envoy connection external/envoy/source/common/network/raw_buffer_socket.cc:70	[Tags: "ConnectionId":"3217"] write returns: 411	thread=34
2024-05-10T09:07:29.295532Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:610	[Tags: "ConnectionId":"3219"] socket event: 6	thread=33
2024-05-10T09:07:29.295536Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:632	[Tags: "ConnectionId":"3219"] remote early close	thread=33
2024-05-10T09:07:29.295541Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:272	[Tags: "ConnectionId":"3219"] closing socket: 0	thread=33
2024-05-10T09:07:29.295582Z	trace	envoy connection external/envoy/source/common/network/connection_impl.cc:465	[Tags: "ConnectionId":"3219"] raising connection event 0	thread=33
#### envoyFilter
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: websocket-filter
  namespace: ingress-nginx
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: ingress-nginx
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: tailscale_ws
          upgrade_configs:
          - upgrade_type: tailscale-control-protocol
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.http.router
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        name: my-router
        config:
          timeout: 5s
```
