### ISSUE TITLE
The randomSamplingPercentage field in the namespace level telemetry api cannot override the corresponding field at the mesh level

### ISSUE THREAD

**Issue by fizos** [istio/istio#51004]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

According to the documentation：https://istio.io/latest/docs/tasks/observability/telemetry/#configuring-namespace-scoped-tracing-behavior,  the sampling frequency of tracing can be override by the namespace-level or workload-level telemetry API. Currently, I configured the randomSamplingPercentage as 1% at the mesh level and 100% in the default namespace, 
expecting traces in the default namespace to be sampled at a frequency of 100，however the actual observation did not meet the expectation.

namespace-scope telemetry
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-ns
  namespace: default
spec:
  tracing:
  - providers:
    - name: "otel-tracing"
    randomSamplingPercentage: 100
```

mesh-scope telemetry
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: "otel-tracing"
    randomSamplingPercentage: 1
```

### Version

```Text
istioctl version
client version: 1.21.2
control plane version: 1.21.2
data plane version: 1.21.2 (8 proxies)

kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

**Comment by zirain** [comment]
I try to reproduce what you said, but worked as expected.

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: "zipkin"
      randomSamplingPercentage: 100.00
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: ns-level
  namespace: default
spec:
  tracing:
    - providers:
        - name: "zipkin"
      randomSamplingPercentage: 99.00
```

output:
```console
istioctl pc l sleep-7656cf8794-qsff2  --port 8000 -oyaml | grep randomSampling -A1
          randomSampling:
            value: 99
```
