### ISSUE TITLE
Istio Envoy Service time sometimes slow down

### ISSUE THREAD

**Issue by 3-commerce** [istio/istio#51001]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I just installed Istio in my new Kubernetes cluster hosted in AWS EKS.

First, I installed the Istio Operator with init command. After that, I apply this Istio Operator yaml;
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-global-1-21-2
spec:
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
    - enabled: true
      name: istio-gw-public
      label:
        istio: istio-igw-public
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        hpaSpec:
          minReplicas: 1
          maxReplicas: 10
    pilot:
      enabled: true
  hub: docker.io/istio
  profile: default
  revision: 1-21-2
  tag: 1.21.2
  values:
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
    global:
      configValidation: true
      istioNamespace: istio-system
```

And then, I installed booking services sample by Istio with Istio API based on documentation. After deployment, services are up and running also Gateways and VirtualService installed.

I test to curl the web page. The result is really fast for 1-2 times and then next request randomly slow down and fast again.

```
curl -sI https://domain/productpage
HTTP/2 200
server: istio-envoy
date: Sun, 12 May 2024 14:57:06 GMT
content-type: text/html; charset=utf-8
content-length: 4294
x-envoy-upstream-service-time: 14

curl -sI https://domain/productpage
HTTP/2 200
server: istio-envoy
date: Sun, 12 May 2024 14:57:15 GMT
content-type: text/html; charset=utf-8
content-length: 4294
x-envoy-upstream-service-time: 16

curl -sI https://domain/productpage
HTTP/2 200
server: istio-envoy
date: Sun, 12 May 2024 14:57:21 GMT
content-type: text/html; charset=utf-8
content-length: 5289
x-envoy-upstream-service-time: 5024

curl -sI https://domain/productpage
HTTP/2 200
server: istio-envoy
date: Sun, 12 May 2024 14:57:28 GMT
content-type: text/html; charset=utf-8
content-length: 5294
x-envoy-upstream-service-time: 5036

curl -sI https://domain/productpage
HTTP/2 200
server: istio-envoy
date: Sun, 12 May 2024 14:57:30 GMT
content-type: text/html; charset=utf-8
content-length: 5289
x-envoy-upstream-service-time: 23

curl -sI https://domain/productpage
HTTP/2 200
server: istio-envoy
date: Sun, 12 May 2024 14:57:42 GMT
content-type: text/html; charset=utf-8
content-length: 5294
x-envoy-upstream-service-time: 5033
```

As you can see the `x-envoy-upstream-service-time` value is increase to 5000s or 5 seconds and suddenly to 14-25ms.

### Version

```Text
% istioctl version
client version: 1.21.2
control plane version: 1.21.2
data plane version: 1.21.2 (2 proxies)

% kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3-eks-adc7111
murz@IKM202300155 ~ % istioctl bug-report
```

### Additional Information

```
% istioctl bug-report

Target cluster context: arn:aws:eks:ap-southeast-3:1234567890:cluster/eks-deployer-shared-3df4

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-05-12 22:17:41.431909 +0700 WIB



Cluster endpoint: https://CCA6C70DF6E1FCC379816F1A94682CA7.btc.ap-southeast-3.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.21.2", GitRevision:"ed90e14d3473bc3fe54f98298eb16664002d14d1", GolangVersion:"go1.22.2", BuildStatus:"Clean", GitTag:"1.21.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision 1-21-2:
&version.MeshInfo{
    {
        Component: "istiod",
        Revision:  "1-21-2",
        Info:      version.BuildInfo{Version:"1.21.2", GitRevision:"ed90e14d3473bc3fe54f98298eb16664002d14d1", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.21.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision 1-21-2: Versions {1.21.2}


Fetching logs for the following containers:

argo-cd/argo-cd-applicationset-controller/argo-cd-applicationset-controller-6cc88b957c-gnkl6/applicationset-controller
argo-cd/argo-cd-dex-server/argo-cd-dex-server-d5599654f-9k7ps/dex-server
argo-cd/argo-cd-notifications-controller/argo-cd-notifications-controller-79cd9d8b9f-mg4sn/notifications-controller
argo-cd/argo-cd-redis/argo-cd-redis-5957b66946-5xdgb/redis
argo-cd/argo-cd-repo-server/argo-cd-repo-server-7889499f85-7vwbg/repo-server
argo-cd/argo-cd-server/argo-cd-server-5b64d9d7fb-jpjcf/server
booking/details-v1/details-v1-698d88b-6z668/details
booking/productpage-v1/productpage-v1-67ddbc8b7f-687lb/productpage
booking/ratings-v1/ratings-v1-866f5845c6-9494w/ratings
booking/reviews-v1/reviews-v1-5b5d6494f4-z5w5f/reviews
booking/reviews-v2/reviews-v2-5b667bcbf8-rtt5p/reviews
booking/reviews-v3/reviews-v3-5b9bd44f4-lwvjl/reviews
default/ubuntuz/ubuntuz-5745f7c8c4-w96pt/ubuntuz
istio-operator/istio-operator-1-21-2/istio-operator-1-21-2-5f47589b69-jvc2n/istio-operator
istio-system/istio-ingressgateway-private/istio-ingressgateway-private-7cb6cbc46-sdf5z/istio-proxy
istio-system/istio-ingressgateway-public/istio-ingressgateway-public-8495546b98-25hl4/istio-proxy
istio-system/istiod-1-21-2/istiod-1-21-2-7bbc59f685-j5lk9/discovery
karpenter/karpenter/karpenter-5466d6c5b6-jbx5z/controller
karpenter/karpenter/karpenter-5466d6c5b6-t858n/controller
keda/keda-admission-webhooks/keda-admission-webhooks-6fb4f894d6-47fft/keda-admission-webhooks
keda/keda-admission-webhooks/keda-admission-webhooks-6fb4f894d6-f29qx/keda-admission-webhooks
keda/keda-operator-metrics-apiserver/keda-operator-metrics-apiserver-76fd95ffc8-8bhpm/keda-operator-metrics-apiserver
keda/keda-operator-metrics-apiserver/keda-operator-metrics-apiserver-76fd95ffc8-tt69k/keda-operator-metrics-apiserver
keda/keda-operator/keda-operator-5d98474fb-2z7nm/keda-operator
keda/keda-operator/keda-operator-5d98474fb-jsh9b/keda-operator
monitoring/node-exporter/node-exporter-jl4ph/node-exporter
monitoring/node-exporter/node-exporter-smhd9/node-exporter

Fetching Istio control plane information from cluster.


Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0162] (Gateway booking/bookinfo-gateway) The gateway is listening on a target port (port 443) that is not defined in the Service associated with its workload instances (Pod selector istio=istio-igw-public). If you need to access the gateway port through the gateway Service, it will not be available.
Warning [IST0162] (Gateway booking/bookinfo-gateway) The gateway is listening on a target port (port 80) that is not defined in the Service associated with its workload instances (Pod selector istio=istio-igw-public). If you need to access the gateway port through the gateway Service, it will not be available.
Info [IST0102] (Namespace argo-cd) The namespace is not enabled for Istio injection. Run 'kubectl label namespace argo-cd istio-injection=enabled' to enable it, or 'kubectl label namespace argo-cd istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace booking) The namespace is not enabled for Istio injection. Run 'kubectl label namespace booking istio-injection=enabled' to enable it, or 'kubectl label namespace booking istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-operator istio-injection=enabled' to enable it, or 'kubectl label namespace istio-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace karpenter) The namespace is not enabled for Istio injection. Run 'kubectl label namespace karpenter istio-injection=enabled' to enable it, or 'kubectl label namespace karpenter istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace keda) The namespace is not enabled for Istio injection. Run 'kubectl label namespace keda istio-injection=enabled' to enable it, or 'kubectl label namespace keda istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace monitoring) The namespace is not enabled for Istio injection. Run 'kubectl label namespace monitoring istio-injection=enabled' to enable it, or 'kubectl label namespace monitoring istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service keda/keda-admission-webhooks) Port name metrics (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service keda/keda-operator-metrics-apiserver) Port name metrics (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service keda/keda-operator) Port name metrics (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service keda/keda-operator) Port name metricsservice (port: 9666, targetPort: 9666) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service monitoring/node-exporter) Port name metrics (port: 9100, targetPort: 9100) doesn't follow the naming convention of Istio port.
Creating an archive at /Users/halving/bug-report.tar.gz.
Time used for creating the tar file is 77.502584ms.
Cleaning up temporary files in /var/folders/cb/0r0vsn4j2kg9svfcst7mpv6h0000gn/T/bug-report.
Done.
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions
