### ISSUE TITLE
Istio 1.21.0 BOOTSTRAP_XDS_AGENT and EnvoyFilter custom stats_config - backwards compatibility issue

### ISSUE THREAD

**Issue by maciekdude** [istio/istio#51005]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

With the depreciation of BOOTSTRAP_XDS_AGENT env variable how do we update istio/envoy with custom dimensions/tags to be used with Prometheus.

Hence, with istio 1.21 all previously working metircs are no longer working. 
e.g 
`token_service_auth_response_duration_milliseconds_code___200____bucket` I would expect metric to be displayed as `token_service_auth_response_duration_milliseconds_code_bucket{code=200}` 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: aml-ingress-odp-machine-learning-bootstrap-tags
  namespace: istio-system
spec:
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        stats_config:
          stats_tags:
          - regex: (user=\.=(.*?);\.;)
            tag_name: user
          - regex: (code=\.=(.*?);\.;)
            tag_name: code
          - regex: (path=\.=(.*?);\.;)
            tag_name: path
```

### Version

```Text
client version: 1.21.2
control plane version: 1.21.0
data plane version: 1.21.0 (14 proxies)

Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```
