### ISSUE TITLE
Service specific Wasmplugin does not work in ambient mode

### ISSUE THREAD

**Issue by adilmp1** [istio/istio#51014]
I encountered an issue while configuring a WasmPlugin in Istio to enforce authentication specifically for the reviews service within the bookinfo applications. 

Initially, I installed Istio in ambient mode and deployed test applications to ensure functionality. Following this, I configured WasmPlugin for the gateway and successfully validated traffic via the gateway. Subsequently, I deployed a waypoint proxy and verified traffic without WasmPlugin.  

I applied the WasmPlugin targeting the service directly, ensuring that only requests directed towards the reviews service are subjected to the authentication mechanism. 

```
kubectl apply -f - <<EOF
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: basic-auth-for-service
spec:
  targetRefs:
    - kind: Service
      group: ""                       
      name: reviews
  url: oci://ghcr.io/istio-ecosystem/wasm-extensions/basic_auth:1.12.0
  phase: AUTHN
  pluginConfig:
    basic_auth_rules:
      - prefix: "/reviews"
        request_methods:
          - "GET"
          - "POST"
        credentials:
          - "ok:test"
          - "MXQtaW4zOmFkbWluMw=="
EOF
```

However, despite providing credentials, requests to other services like reviews were also passing through without authentication.

```
kubectl exec deploy/sleep -- curl -s -w "%{http_code}" -o /dev/null http://reviews:9080/reviews/1
200
```

I tested a different configuration by targeting the Gateway instead of the service directly. 

```
kubectl apply -f - <<EOF
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: basic-auth-for-service
spec:
  targetRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: reviews-svc-waypoint
  url: oci://ghcr.io/istio-ecosystem/wasm-extensions/basic_auth:1.12.0
  phase: AUTHN
  pluginConfig:
    basic_auth_rules:
      - prefix: "/reviews"
        request_methods:
          - "GET"
          - "POST"
        credentials:
          - "ok:test"
          - "MXQtaW4zOmFkbWluMw=="
EOF
```

This configuration worked as expected, enforcing authentication only for the reviews service.

```
kubectl exec deploy/sleep -- curl -s -w "%{http_code}" -o /dev/null http://reviews:9080/reviews/1
401
```

Additionally, when I ran the following commands to fetch the listener configuration for both the waypoint proxy and the reviews-svc-waypoint proxy, after applying WasmPlugin directly to the service:

```
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# go run ./istioctl/cmd/istioctl pc listener deploy/waypoint -o json | grep -A 5 -B 10 Wasm
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# go run ./istioctl/cmd/istioctl pc listener deploy/reviews-svc-waypoint -o json | grep -A 5 -B 10 Wasm
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# 
```

Neither of them produced any output, indicating that the Wasm configuration was not applied.

However, when I applied WasmPlugin targeting the Gateway, the second command outputted the Wasm configuration, confirming successful application.

```
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# go run ./istioctl/cmd/istioctl pc listener deploy/waypoint -o json | grep -A 5 -B 10 Wasm
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# go run ./istioctl/cmd/istioctl pc listener deploy/reviews-svc-waypoint -o json | grep -A 5 -B 10 Wasm
                            "httpFilters": [
                                {
                                    "name": "extenstions.istio.io/wasmplugin/default.basic-auth-for-service",
                                    "configDiscovery": {
                                        "configSource": {
                                            "ads": {},
                                            "initialFetchTimeout": "0s",
                                            "resourceApiVersion": "V3"
                                        },
                                        "typeUrls": [
                                            "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
                                            "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
                                        ]
                                    }
                                },
                                {
--
                            "httpFilters": [
                                {
                                    "name": "extenstions.istio.io/wasmplugin/default.basic-auth-for-service",
                                    "configDiscovery": {
                                        "configSource": {
                                            "ads": {},
                                            "initialFetchTimeout": "0s",
                                            "resourceApiVersion": "V3"
                                        },
                                        "typeUrls": [
                                            "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
                                            "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
                                        ]
                                    }
                                },
                                {
root@debian-s-4vcpu-8gb-blr1-01:~/go/src/projects/istio# 
```
