### ISSUE TITLE
Detect `tag: ...-distroless`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51040]
From slack:

"""
is distroless default in 1.22 ambient profile? was just on 1.21.x and minimal profile
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: ambient
  hub: gcr.io/istio-release
  tag: {{ istioVersion }}-distroless
```
getting image pull errors now
Back-off pulling image "gcr.io/istio-release/pilot:1.22.0-distroless-distroless"

The issue is tag: {{ istioVersion }}-distroless
This is the old way to configure the image type. Now there is variant
Ambient defaults to `vartiant: distroless`
So you end up with `<hub>/image:<tag>-<variant>`

You should do
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: ambient
  hub: gcr.io/istio-release
  tag: {{ istioVersion }}
```
for ambient
or if you want distroless off-ambient
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: gcr.io/istio-release
  tag: {{ istioVersion }}
  variant: distroless
```

Probably we should automatically detect/warn/fix this case
"""

---

We can probably detect this in istioctl and warn or automatically correct it
