### ISSUE TITLE
Telemetry API: disableSpanReporting breaks context propagation

### ISSUE THREAD

**Issue by drewcorlin1** [istio/istio#51140]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am trying to use the [disableSpanReporting](https://istio.io/latest/docs/reference/config/telemetry/#Tracing-TracingSelector:~:text=No-,disableSpanReporting,-BoolValue) field in the Telemetry API to suppress client and server spans from istio, but when I do so my server spans are no longer correlated with the trace from the calling client.

I can see that the `traceparent` header on the incoming request looks to have the trace ID from the correct client span, but when viewing traces in jaeger they are not correlated with one another (and they are correlated with one another correctly when I am not using `disableSpanReporting` (albeit with an istio client + server span in between my 2 services).

Please let me know if I can provide any more information.

### Version

```Text
istioctl version
client version: 1.20.1
control plane version: 1.17.3
data plane version: 1.17.3 (88 proxies)

kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.16-eks-adc7111
WARNING: version difference between client (1.29) and server (1.25) exceeds the supported minor version skew of +/-1
```

### Additional Information

I'm using Jaeger as my tracing backend and the OpenTelemetry collector as the receiver of spans. Here is my Telemetry API configuration. My context for this change is that I'm trying to setup the [OTel servicegraph connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/servicegraphconnector/README.md) and with istio's client and server spans showing up between microservice A and microservice B it renders the connector useless, since it just sees that microservice A depends on istio and istio depends on microservice B but not that microservice A depends on microservice B.

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: app-default
  namespace: app
spec:
  metrics: # ...
  tracing:
  - customTags:
      operation-id:
        header:
          name: operation-id
    disableSpanReporting: true
    match:
      mode: CLIENT_AND_SERVER
    providers:
    - name: opentelemetry
```
