### ISSUE TITLE
VM Workload Auto-registration Fails due to Can't find Workloadgroup

### ISSUE THREAD

**Issue by CadenGuo** [istio/istio#51211]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using Istio's auto-registration function for VM workloads, I found the auto registration process always fails. On the istio-sidecar side in the VM, envoy prints the following log:
```
upstream terminated with unexpected error rpc error: code = FailedPrecondition desc = auto-registration WorkloadEntry of ip-10-10-65-247.mesh-east-istio failed: cannot find WorkloadGroup mesh-east-istio/mesh-east-istio-vm
```

My setup is as follow:

- workloadgroup:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "mesh-east-istio-vm"
  namespace: "mesh-east-istio"
spec:
  metadata:
    labels:
      app: mesh-east-istio-vm
  probe:
    tcpSocket:
      port: 8087
  template:
    labels:
      app: mesh-east-istio-vm
    network: vm-network
    serviceAccount: mesh-east-istio
```

- mesh config on the VM
```yaml
defaultConfig:
  binaryPath: /usr/local/bin/istio-envoy # envoy binary file for istio to use, should be distinguishable from the Consul' envoy
  discoveryAddress: istiod-nlb-mesh-001.stg.mngd.int.engtools.net:15012
  meshId: mesh1
  proxyMetadata:
    CANONICAL_REVISION: latest
    CANONICAL_SERVICE: mesh-east-istio-vm
    ISTIO_META_CLUSTER_ID: mngd-eks-stg-mesh-001
    ISTIO_META_AUTO_REGISTER_GROUP: mesh-east-istio-vm
    ISTIO_META_DNS_CAPTURE: "false"
    ISTIO_META_MESH_ID: mesh1
    ISTIO_META_NETWORK: vm-network
    ISTIO_META_WORKLOAD_NAME: mesh-east-istio-vm
    ISTIO_METAJSON_LABELS: '{"app":"mesh-east-istio-vm","service.istio.io/canonical-name":"mesh-east-istio-vm","service.istio.io/canonical-revision":"latest"}'
    POD_NAMESPACE: mesh-east-istio
    SERVICE_ACCOUNT: mesh-east-istio
    TRUST_DOMAIN: cluster.local
  readinessProbe:
    tcpSocket:
      port: 8087
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
```

- envoy's cluster.env
```
CANONICAL_REVISION='latest'
CANONICAL_SERVICE='mesh-east-istio-vm'
ISTIO_INBOUND_PORTS='*'
ISTIO_LOCAL_EXCLUDE_PORTS='22,15090,15021,15020'
ISTIO_METAJSON_LABELS='{"app":"mesh-east-istio-vm","service.istio.io/canonical-name":"mesh-east-istio-vm","service.istio.io/canonical-revision":"latest"}'
ISTIO_META_AUTO_REGISTER_GROUP='mesh-east-istio-vm'
ISTIO_META_CLUSTER_ID='mngd-eks-stg-mesh-001'
ISTIO_META_DNS_CAPTURE='false'
ISTIO_META_MESH_ID='mesh1'
ISTIO_META_NETWORK='vm-network'
ISTIO_META_WORKLOAD_NAME='mesh-east-istio-vm'
ISTIO_NAMESPACE='mesh-east-istio'
ISTIO_SERVICE='mesh-east-istio-vm.mesh-east-istio'
ISTIO_SERVICE_CIDR='*'
POD_NAMESPACE='mesh-east-istio'
SERVICE_ACCOUNT='mesh-east-istio'
```

This setup used to work in the 1.21.2 version, but right now it doesn't work with 1.22.0 and the error logs stated at the begin are printed by envoy.

### Version

```Text
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.22.0 (36 proxies)

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.12-eks-adc7111
```

**Comment by howardjohn** [comment]
`    ISTIO_META_AUTO_REGISTER_GROUP: mesh-east-istio-vm`

But your WG name is `mesh-east-istio`? (No -vm)

**Comment by CadenGuo** [comment]
Workload group name is also `mesh-east-istio-vm`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "mesh-east-istio-vm"
  namespace: "mesh-east-istio"
spec:
  metadata:
    labels:
      app: mesh-east-istio-vm
  probe:
    tcpSocket:
      port: 8087
  template:
    labels:
      app: mesh-east-istio-vm
    network: vm-network
    serviceAccount: mesh-east-istio
```

And from the error log
```
upstream terminated with unexpected error rpc error: code = FailedPrecondition desc = auto-registration WorkloadEntry of ip-10-10-65-247.mesh-east-istio failed: cannot find WorkloadGroup mesh-east-istio/mesh-east-istio-vm
```
We can see istio is searching for workloadgroup `mesh-east-istio-vm` under the namespace `mesh-east-istio`
