### ISSUE TITLE
applying then deleting a ServiceEntry with the same host results in missing endpoint

### ISSUE THREAD

**Issue by puertomontt** [istio/istio#51212]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Apply se1. Apply se2, then delete se1. Only difference between the two is the exportTo field. The endpoint for `httpbin-vd.internal.com` will be removed and the service will become unreachable.

Restarting istiod or reapplying se1 will restore the endpoint.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se1
  namespace: httpbin
spec:
  addresses:
  - 250.59.249.145
  exportTo:
  - default
  - httpbin
  - istio-system
  hosts:
  - httpbin-vd.internal.com
  location: MESH_INTERNAL
  ports:
  - name: http-8000
    number: 8000
    protocol: HTTP
    targetPort: 8080
  resolution: STATIC
  subjectAltNames:
  - spiffe://mgmt-cluster/ns/httpbin/sa/httpbin
  workloadSelector:
    labels:
      app: httpbin
```

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se2
  namespace: httpbin
spec:
  addresses:
  - 250.59.249.145
  exportTo:
  - istio-system
  - httpbin
  hosts:
  - httpbin-vd.internal.com
  location: MESH_INTERNAL
  ports:
  - name: http-8000
    number: 8000
    protocol: HTTP
    targetPort: 8080
  resolution: STATIC
  subjectAltNames:
  - spiffe://mgmt-cluster/ns/httpbin/sa/httpbin
  workloadSelector:
    labels:
      app: httpbin
```

### Version

```Text
reproduced on 1.19.10, 1.20.6, 1.22.0
```
