### ISSUE TITLE
Bad outbound listener

### ISSUE THREAD

**Issue by costinm** [istio/istio#5121]
Wrong generated listener - one of the hosts is picked up and takes over port 443, 
error messages for the others. Also no other 443 rule is picked up.

```
piVersion: networking.istio.io/v1alpha3
kind: ExternalService
metadata:
  name: wikipedia-range
spec:
  hosts:
    - 91.198.174.192/27
    - 103.102.166.224/27
    - 198.35.26.96/27
    - 208.80.153.224/27
    - 208.80.154.224/27
  ports:
    - number: 443
      protocol: TCP
      name: tcp-port

```

Generated listener:
```
   {
        "name": "tcp_0.0.0.0_443",
        "address": {
          "socketAddress": {
            "address": "0.0.0.0",
            "portValue": 443
          }
        },
        "filterChains": [
          {
            "filterChainMatch": {
              
            },
            "filters": [
              {
                "name": "envoy.tcp_proxy",
                "config": {
                  "deprecated_v1": true,
                  "value": {
                    "route_config": {
                      "routes": [
                        {
                          "cluster": "outbound|tcp-port||103.102.166.224_27"
                        }
                      ]
                    },
                    "stat_prefix": "outbound|tcp|443"
                  }
                }
              }
            ]
          }
        ],
        "deprecatedV1": {
          "bindToPort": false
        }
      },
```
