### ISSUE TITLE
Multi-tenancy for tracing using grafana-tempo - design questions

### ISSUE THREAD

**Issue by slawekww** [istio/istio#51254]
**Describe the feature request**

Goal is to have integration of istio operator/istio gateway with multitenancy setup to separate traces per tenant:

1. one istio operator per cluster

2. one virtual gateway per cluster

3. each tenants have in tenant's dedicated namespace :
   - CR virtualservices
   - collector service working as zipkin input and otlp output to grafana-tempo service
   - grafana-tempo service
   
 4. istiod helm values (selected)

```
defaults:
  pilot:
    deploymentLabels:
      app.kubernetes.io/name: istiod
      app: istiod
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      sidecar.istio.io/inject: "false"
    podLabels:
      app.kubernetes.io/name: istiod
      app: istiod
      install.operator.istio.io/owning-resource: unknown
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      sidecar.istio.io/inject: "false"
    traceSampling: 1.0
    image: pilot
    autoscaleMin: 2
    autoscaleMax: 6
    replicaCount: 2
    rollingMaxSurge: 100%
    rollingMaxUnavailable: 25%
    cpu:
      targetAverageUtilization: 80
    resources:
      requests:
        cpu: 500m
        memory: 900Mi
  global:
    hub: docker.io/istio 
    targetRevision: 1.21.1
    logging:
      level: "default:info"
    proxy:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 700m
          memory: 256Mi
      logLevel: warning
      privileged: false
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    accessLogFormat: |
      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)%
    defaultConfig:
      tracing: {}
    extensionProviders:
      # add zipkin connector provider per tenant
      # follow multi tenancy pattern: tenant's connectors (add header x-scope-orgid) -> grafana-tempo
      - name: zipkin-tenant1
        zipkin:
          service: collector.tenant1.svc.cluster.local
          port: 9411
          maxTagLength: 99999
      - name: zipkin-tenant2
        zipkin:
          service: collector.tenant2.svc.cluster.local
          port: 9411
          maxTagLength: 99999
      - name: zipkin-tenant3
        zipkin:
          service: collector.tenant3.svc.cluster.local
          port: 9411
          maxTagLength: 99999
    defaultProviders:
      metrics:
      - prometheus
```

5. For each tenant in istio-system namespace:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tracing-<tenant_name> # like tenant1, tenant2,tenant3
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin-<tenant_name> # like tenant1, tenant2,tenant3
    randomSamplingPercentage: 100
```

6. Pod spec for tracing monitoring:

```
  # Pod template at deployment
  template:
    metadata:
      annotations:
        # optional debug for istio sidecar 
        #sidecar.istio.io/agentLogLevel: "debug"
        #sidecar.istio.io/componentLogLevel: "misc:debug"
        #sidecar.istio.io/logLevel: "debug"
        proxy.istio.io/config: |
          tracing:
            sampling: 100
            zipkin:
              address: collector.<tenant_name>.svc.cluster.local:9411
```

In this case, istio sidecar produces traces however some traces from non-tenant namespaces are sent to tenant's zipkin collector (even if no pod config updated for sidecar) and it looks like isolation is broken, sometimes zipkin endpoint is not updated on sidecar config.
Is is bug or missing configuration?

Noticed that pods without annotations as defined in point 6 has injected the 1st zipkin endpoint defined in `extensionProviders`. 

How to create design or update config to allow keeping isolation of traces between tenants?

**Describe alternatives you've considered**
Not known.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jewertow** [comment]
Hello @slawekww,

I am not 100% sure what you mean by multitenancy in this context and what's the tenant, but I see that the 5th step is wrong.
You can read in the Telemetry [documentation](https://istio.io/latest/docs/tasks/observability/telemetry/):
```
Telemetry API resources inherit configuration from parent resources in the Istio configuration hierarchy:

1. root configuration namespace (example: istio-system)
2. local namespace (namespace-scoped resource with no workload selector)
3. workload (namespace-scoped resource with a workload selector)
```
This means that you shouldn't create more than one Telemetry resource in the istio-system namespace. Instead, you should create tenant's specific Telemetry resource in all tenant's namespaces:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tracing-<tenant_name>
  namespace: <tenant-namespaces>
spec:
  tracing:
  - providers:
    - name: zipkin-<tenant_name>
    randomSamplingPercentage: 100
```

6th step is also wrong, because you don't have to configure tracing in the proxy config if you use Telemetry API. Instead, you can disable v2.telemetry settings in helm values and set `tracer: none`.
