### ISSUE TITLE
Telemetry API for mesh-wide tracing settings does not working.

### ISSUE THREAD

**Issue by mugioka** [istio/istio#51256]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

According to the following document, it is stated that we can apply Tracing settings to the entire mesh by configuring as follows:
https://istio.io/latest/docs/reference/config/telemetry/#examples
However, it seems that these settings are not working in my environment.
IstioOperator
```yaml
apiVersion: [install.istio.io/v1alpha1](http://install.istio.io/v1alpha1)
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing: {} # disabled MeshConfig tracing option
    extensionProviders:
      - name: datadog
        datadog:
          service: datadog.MY_NS.svc.cluster.local
          port: 8126
  # nits
```

Telemetry
```yaml
apiVersion: [telemetry.istio.io/v1](http://telemetry.istio.io/v1)
kind: Telemetry
metadata:
  name: enable-datadog-tracing
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: "datadog"
      randomSamplingPercentage: 100.00
```

Output of `istioctl pc l ${ISTIO_INGRESSGATEWAY_NAME} -oyaml`.
```yaml
# nits
tracing:
  clientSampling:
    value: 100
  customTags:
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_allow_shadow_effective_policy_id
    tag: istio.authorization.dry_run.allow_policy.name
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_allow_shadow_engine_result
    tag: istio.authorization.dry_run.allow_policy.result
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_deny_shadow_effective_policy_id
    tag: istio.authorization.dry_run.deny_policy.name
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_deny_shadow_engine_result
    tag: istio.authorization.dry_run.deny_policy.result
  - literal:
      value: latest
    tag: istio.canonical_revision
  - literal:
      value: istio-ingressgateway
    tag: istio.canonical_service
  - literal:
      value: Kubernetes
    tag: istio.cluster_id
  - literal:
      value: cluster.local
    tag: istio.mesh_id
  - literal:
      value: istio-system
    tag: istio.namespace
  overallSampling:
    value: 100
  randomSampling:
    value: 1
# nits
```

When I added the following selector to Telemetry as a test, I was able to confirm that the intended setting was injected into istio-ingressgateway.

Telemetry
```yaml
apiVersion: [telemetry.istio.io/v1](http://telemetry.istio.io/v1)
kind: Telemetry
metadata:
  name: enable-datadog-tracing
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  tracing:
    - providers:
        - name: "datadog"
      randomSamplingPercentage: 100.00
```

Output of `istioctl pc l ${ISTIO_INGRESSGATEWAY_NAME} -oyaml`.
```yaml
# nits
tracing:
  clientSampling:
    value: 100
  customTags:
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_allow_shadow_effective_policy_id
    tag: istio.authorization.dry_run.allow_policy.name
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_allow_shadow_engine_result
    tag: istio.authorization.dry_run.allow_policy.result
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_deny_shadow_effective_policy_id
    tag: istio.authorization.dry_run.deny_policy.name
  - metadata:
      kind:
        request: {}
      metadataKey:
        key: envoy.filters.http.rbac
        path:
        - key: istio_dry_run_deny_shadow_engine_result
    tag: istio.authorization.dry_run.deny_policy.result
  - literal:
      value: latest
    tag: istio.canonical_revision
  - literal:
      value: istio-ingressgateway
    tag: istio.canonical_service
  - literal:
      value: Kubernetes
    tag: istio.cluster_id
  - literal:
      value: cluster.local
    tag: istio.mesh_id
  - literal:
      value: istio-system
    tag: istio.namespace
  maxPathTagLength: 512
  overallSampling:
    value: 100
  provider:
    name: envoy.tracers.datadog
    typedConfig:
      '@type': type.googleapis.com/envoy.config.trace.v3.DatadogConfig
      collectorCluster: outbound|8126||datadog.fensi-system.svc.cluster.local
      collectorHostname: datadog.fensi-system.svc.cluster.local
      serviceName: istio-ingressgateway.istio-system
  randomSampling:
    value: 100
# nits
```

### Version

```Text
istioctl version
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.21.1 (2 proxies), 1.22.0 (185 proxies)

kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.12-gke.1115000
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
```
```


### Additional Information

_No response_

**Comment by zirain** [comment]
do you have multi `mesh-wide` Telemetry API resources?

**Comment by mugioka** [comment]
> do you have multi mesh-wide Telemetry API resources?

yes

i have multi mesh-wide Telemetry API resources.
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: override-metrics-requests-total
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_COUNT
        mode: CLIENT_AND_SERVER
      tagOverrides:
        request_host:
          value: request.host

```
