### ISSUE TITLE
Service Account Annotation Formatting Error

### ISSUE THREAD

**Issue by asef145** [istio/istio#51289]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The istiod helm chart does not correctly format the `serviceaccount.yaml` file when `pilot.serviceAccountAnnotations` is provided.

When this values file is supplied:
 ```yaml
pilot:
  serviceAccountAnnotations:
    test: test
```

The service account template produces:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    release: release-nameannotations:    test: test
---
```

This is the expected Output:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    release: release-name
  annotations:
    test: test
---
```

I believe this can be solved by removing the extra dashes in [this file](https://github.com/istio/istio/blob/06d6b174468f14b43b7c56d80366cc5d99f7aa34/manifests/charts/istiod-remote/templates/serviceaccount.yaml#L16) as such:
```yaml
apiVersion: v1
kind: ServiceAccount
  {{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
metadata:
  name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: {{ .Values.global.istioNamespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
  {{ if .Values.pilot.serviceAccountAnnotations -}}
  annotations:
{{ toYaml .Values.pilot.serviceAccountAnnotations | indent 4 }}
  {{- end }}
---
```

### Version

```Text
$ istioctl version
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.21.2 (14 proxies), 1.22.0 (9 proxies)
$ helm version --short
v3.14.1+ge8858f8
```
