### ISSUE TITLE
holdApplicationUntilProxyStarts not working

### ISSUE THREAD

**Issue by sschepens** [istio/istio#51310]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After migrating to istio 1.21.2 we realized that `holdApplicationUntilProxyStarts` stopped working, Istio stopped adding `postStart` hook to istio-proxy container. 
We're using Helm to deploy Istio and we use the following relevant config in `values.yaml`:
```yaml
meshConfig:
      defaultConfig:
        holdApplicationUntilProxyStarts: true
```

This configuration works for Istio 1.20 but doesn't work with Istio 1.21

### Version

```Text
1.21.2
```
