### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by junandaip** [istio/istio#51376]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi all, I'm trying to install multi primary (2 vCluster) setup using vCluster managed by Loft in a single network and a single physical cluster. I followed these steps for the setup:
- Create CA: https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
- Install Multi Primary: https://istio.io/latest/docs/setup/install/multicluster/multi-primary/
- Verify: https://istio.io/latest/docs/setup/install/multicluster/verify/
- Troubleshoot: https://istio.io/latest/docs/ops/diagnostic-tools/multicluster/

I tried using istio version 1.20, 1.21, and 1.22, but at the end of the day istiod always throws this error `https://console-loft.example.com/kubernetes/project/myproject/virtualcluster/vcluster-1api/v1/namespaces?limit=500&resourceVersion=0": tls: failed to verify certificate: x509: certificate signed by unknown authority`

The error happens after I ran `istioctl create-remote-secret --context="${CTX_CLUSTER2}" --name=cluster2 | kubectl apply -f - --context="${CTX_CLUSTER1}"` on each cluster

Both cluster is having the same ca-root cert and there's only one endpoint shown when I run `istioctl --context $CTX_CLUSTER1 proxy-config endpoint <pod-name>.<namespace> | grep helloworld`

You guys have any idea what I might be missing?

### Version

```Text
istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0

kubectl version
Client Version:  1.27
Kustomize Version: v5.0.1
Server Version: 1.26
```

### Additional Information

The endpoint `https://console-loft.example.com` is reachable from both cluster (tested using curl from both cluster) and the TLS certificate is created using Let's Encrypt.

**Comment by howardjohn** [comment]
the output of `istioctl create-remote-secret --context="${CTX_CLUSTER2}" --name=cluster2` is a kubeconfig . You can point kubectl at this. Does it give the same error? I assume so

can you post it? *it will probably have credentials you should remove*

**Comment by junandaip** [comment]
Dear @howardjohn, thank you for replying. After doing what you suggested it turned out to be misconfiguration of remote-secret when generated by using istioctl command. At least, that's what I'm guessing at

Here is my kubeconfig where istioctl create the secret from (notice that there's no `certificate-authority-data` in here)
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://console-loft.example.com/kubernetes/project/myproject/virtualcluster/vcluster-1
  name: vcluster-1
- cluster:
    insecure-skip-tls-verify: true
    server: https://console-loft.example.com/kubernetes/project/myproject/virtualcluster/vcluster-2
  name: vcluster-2
- context:
    cluster: vcluster-1
    user: vcluster-1
  name: vcluster-1
- context:
    cluster: vcluster-2
    user: vcluster-2
  name: vcluster-2
kind: Config
preferences: {}
users:
- name: vcluster-1
  user:
    token: <64-chars-token>
- name: vcluster-2
  user:
    token: <64-chars-token>
```


Here's the kube secret when generated using istioctl (generated `certificate-authority-data` and changed the `token` into long string)
```
./istio-test$ istioctl create-remote-secret --context="${CTX_CLUSTER1}" --name=cluster1
# This file is autogenerated, do not edit.
apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: cluster1
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-cluster1
  namespace: istio-system
stringData:
  cluster1: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRDGHTsrtYsXNmTVRNd05qUXhXaGNOTXpRd05qQXhNVE13TmpReApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTVRjME1qQXdNREV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTRFlpc0Q0R2NLOHZ4Ly9LbHZ0UGJFUjF5c0U0SENWQVRuVG5xYlNlb0IKUUdwQzRDNVR6ZDZocUtmaFdjejB1c0N5d1ljVUZpT3JXMmJvellOQmtHTEpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU5rNHZnY1NDS0pUQmh2OVdyd20zCkYvL083RG93Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTmRRNm9GN0gxR2t0NG5ycTIyT1BzQnV1amE4NWhhd1gKTHF3QkxlK1BPYUlDSUV4U25rTUI4Z3JDOGRaL0VLU2g2ZVhKMzd6dnVuSkgzUUtoRG4rV284asdadadadadUtLS0tLQo=
        server: https://console-loft.example.com/kubernetes/project/myproject/virtualcluster/vcluster-1
      name: cluster1
    contexts:
    - context:
        cluster: cluster1
        user: cluster1
      name: cluster1
    current-context: cluster1
    kind: Config
    preferences: {}
    users:
    - name: cluster1
      user:
        token: PD2cGasdRRGHHWRSDDDDGGNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5lqweqweqwdJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImlzdGlvLXJlYWRlci1zZXJ2aWNlLWFjY291bnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5OWEzMzc2OS1kZDI1LTQ2NjYtOTI2MS1iODE1NmNiZWY0NTMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aXN0aW8tc3lzdGVtOmlzdGlvLXJlYWRlci1zZXJ2aWNlLWFjY291bnQifQ.ZcuarEasdadadadasdasdpliemAt6rDSAXZdCKpZmyW_UFW2iw1UC10fkWSNN5k91VYpWZ1wyB7TKwOntXJ5J_KUgwVYDf86Nci2cTBLkUYV0Ki10P3eVa_eANMKepxekHey0N3Y3ahtvwmGJWgtC0gN5NVawNtprLtMh6uFMZZyn4GJ8BKwDzqrI5g51iHanNV2r8fF6_sPpnhIpvlq30atZQxBRA847G3m-Nssdsdfdg
```

Using the generated kubeconfig will always result in `tls: failed to verify certificate: x509: certificate signed by unknown authority`. So I adjusted the secret using my kubeconfig and now the Istio is working fine.
```
~/istio-test$ istioctl --context $CTX_CLUSTER1 proxy-config endpoint sleep-bc9998558-7gj8h.sample | grep helloworld
172.16.84.124:5000                                      HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
172.16.89.221:5000                                      HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```
