### ISSUE TITLE
[Istio Installation] Add defaultProviders in meshconfig for helm install, will make metrics (istio_requests_total) is missing

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#51384]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

[Istio Installation] Add defaultProviders in meshconfig for helm install, will make metrics (istio_requests_total) is missing

I only change accesslog part, why metrics is impacted. Please take a look, thanks.

### Version

```Text
istio 1.21.2
k8s 1.27
```

### Additional Information

the config which istio_request_total metrics can be collected.
```
    meshConfig:
      enablePrometheusMerge: true
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
      accessLogFormat: |
         {
              "authority": "%REQ(:AUTHORITY)%",
              "bytes_received": "%BYTES_RECEIVED%"
          }
      extensionProviders:
      - name: otel
        zipkin:
          service: splunk-otel.infra.svc.cluster.local
          port: 9411
      - name: "ext-authz-server-grpc"
        envoyExtAuthzGrpc:
          service: ${EXT_AUTHZ_SERVER}
          port: "443"
```

The configmap without  istio_request_total metrics
```
    meshConfig:
      enablePrometheusMerge: true
      defaultProviders:
        accessLogging:
        - access-log-standard
      extensionProviders:
      - name: "access-log-onlyErr"
        envoyFileAccessLog:
          path: /dev/null
          logFormat:
            labels: {}
      - name: "access-log-standard"
        envoyFileAccessLog:
          path: /dev/stdout
          logFormat:
            labels:
              "authority": "%REQ(:AUTHORITY)%"
              "bytes_received": "%BYTES_RECEIVED%"
      - name: otel
        zipkin:
          service: splunk-otel.infra.svc.cluster.local
          port: 9411
      - name: "ext-authz-server-grpc"
        envoyExtAuthzGrpc:
          service: ${EXT_AUTHZ_SERVER}
          port: "443"
```
