### ISSUE TITLE
Helm Chart for Gateway does not Support Private Registry

### ISSUE THREAD

**Issue by edwardwu-hkjc** [istio/istio#51387]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Support specifying Private Registry in Helm Chart for Gateway

**Describe alternatives you've considered**
Tested populating values.yaml with `global.hub="registry url"`

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Trying to install istio/gateway helm chart in a k8s cluster with no access to docker hub but has a private container registry (e.g. Azure Container Registry)

**Comment by nmnellis** [comment]
Can you please provide an example values.yaml and helm install command?

**Comment by edwardwu-hkjc** [comment]
> Can you please provide an example values.yaml and helm install command?

Hi, I've used the below helm install command and values.yaml. Thanks.

`helm install istio-gateway istio/gateway -n istio-gateway --values istio-gateway-values.yaml`

```yaml
---
defaults:
  global:
    hub: "<example>.azurecr.io/istio"
# other values below, they are working fine
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    loadBalancerIP: "<Private IP Address>" 
```
