### ISSUE TITLE
Bug in Istio RequestAuthenticaion API RemoteJWKS setting

### ISSUE THREAD

**Issue by aryan16** [istio/istio#51398]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We added the `Envoy` mode for RequestAuthn API which will let envoy fetch the JWKS PublicKey from jwksURI. We will build the [remote JWKS config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-remotejwks) in jwt_authn filter. 

Now if the jwksURI is an external https server backed by default public certs, in this case users have to create ServiceEntry and DestinationRule. But there might be a chance that for some other path to `jwksURI` server, user is already generating a TLS traffic directly from the application and if we have a DestRule, we will start seeing double encryption and requests will fail.

Example - 
Assume `jwksURI` server is `userServer.com`. User will create SE and DR for that.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - userServer.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-mtls
spec:
  host: userServer.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: userServer.com
 ```

```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "remote-jwks-policy"
spec:
  jwtRules:
  - issuer: "test-issuer-1@istio.io"
    jwksUri: "https://userServer.com/jwks"
```

With the above defined SE and DR, reqAuthn will work but direct TLS traffic from application will fail as we are asking use to apply DR that adds one additional TLS.

Even if we create a new SE for reqAuthn with dummy hostname, it won't work cuz in the remoteJWKS setting http_uri will have that dummy host and envoy will use that host in the `authority` header while making a request to jwksURI and request will fail because of that.

### Version

```Text
istioctl version - 1.18.2
kubectl version - 
Client Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.15-dispatcher", GitCommit:"5490d28d307425a9b05773554bd5c037dbf3d492", GitTreeState:"clean", BuildDate:"2024-04-18T22:39:05Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
```

**Comment by howardjohn** [comment]
```yaml
kind: VirtualService
spec:
  host: userServer.com
  routes:
  # Send all user traffic to subset
  - destination:
    - name: userServer.com
      subset: direct
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-mtls
spec:
  host: userServer.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: userServer.com
  # Make 'direct' subset to not do TLS
  subset:
  - name: direct
    trafficPolicy:
      tls:
        mode: NONE
# Rest is the same
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - userServer.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "remote-jwks-policy"
spec:
  jwtRules:
  - issuer: "test-issuer-1@istio.io"
    jwksUri: "https://userServer.com/jwks"
```
