### ISSUE TITLE
Istio metrics customization using Telemetry custom resource

### ISSUE THREAD

**Issue by praddy26** [istio/istio#51434]
In the earlier version(1.15.x) of istio we used `EnvoyFilter` custom resource to add custom tags to the metrics. As part of this we could add several match conditions to map value to an output attribute.

For example in the following `EnvoyFilter` the output attribute `istio_operationId` value will be mapped based on several conditions.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: "vault-ef"
  labels:
    app: vault
spec:
  workloadSelector:
    labels:
      app: "vault"
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.15.*'
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "istio.stats"
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.attributegen
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "attributes": [
                      {
                        "output_attribute": "istio_operationId",
                        "match": [
                            {
                                "value": "/api/v1/{cusID}/decode",
                                "condition": "request.url_path.matches('/api/v1/[[:alnum:]]*/decode')"
                            },
                            {
                                "value": "/api/v1/{cusID}/encode",
                                "condition": "request.url_path.matches('/api/v1/[[:alnum:]]*/encode')"
                            },
                            {
                                "value": "/api/v1/{cusID}/tokens/{keyName}/import",
                                "condition": "request.url_path.matches('/api/v1/[[:alnum:]]*/tokens/[[:alnum:]]*/import')"
                            },
                            {
                                "value": "/api/v1/{cusID}/tokens/{keyName}/revolve",
                                "condition": "request.url_path.matches('/api/v1/[[:alnum:]]*/tokens/[[:alnum:]]*/revolve')"
                            },
                            {
                                "value": "probes",
                                "condition": "request.url_path == '/ready'"
                            },
                            {
                                "value": "probes",
                                "condition": "request.url_path == '/live'"
                            },
                        ]
                      },
                    ]
                  }
              vm_config:
                runtime: envoy.wasm.runtime.null
                code:
                  local: { inline_string: "envoy.wasm.attributegen" }

```

To upgrade to the latest istio version(1.22.x), since `EnvoyFilter` is no longer supported, we tried to achieve the above configuration using `Telemetry` object as below

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: vault-telemetry
spec:
  metrics:
    - overrides:
      - match:
          metric: ALL_METRICS
          mode: SERVER
        tagOverrides:
          method:
            value: request.method
          istio_operationId:
            value: | 
              request.url_path.matches("/api/v1/[[:alnum:]]*/keys/[[:alnum:]]*/import") ? "/api/v1/{cusID}/keys/{keyName}/import" :
              request.url_path.matches("/api/v1/[[:alnum:]]*/keys/[[:alnum:]]*/revolve") ? "/api/v1/{cusID}/keys/{keyName}/revolve" :
              request.url_path.matches("/api/v1/[[:alnum:]]*/encode") ? "/api/v1/{cusID}/encode" :
              request.url_path.matches("/api/v1/[[:alnum:]]*/decode") ? "/api/v1/{cusID}/decode" :
              request.url_path.matches("/ready") ? "probes" :
              request.url_path.matches("/live") ? "probes" :
              "unknown"
      providers:
        - name: prometheus
  selector:
    matchLabels:
      app: vault
```

After replacing `EnvoyFilter` with the `Telemetry`(above) we are seeing latency degradation for our APIs. 
So we suspect the nested ternary conditional operator(`exp ? e1 : e2`) that we have used with the [CEL](https://github.com/google/cel-spec) to evaluate the value might be the cause for this.

**_Is there any other optimized approach to achieve this without impacting the latency of APIs?_**

**Istio Version: 1.15.3**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
