### ISSUE TITLE
istio_mutual between sidecar & egress gateway not working

### ISSUE THREAD

**Issue by krissell** [istio/istio#51471]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi all,
I have a simple egress example setup. Without ISTIO_MUTUAL:
````
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sample-gateway
spec:
  selector:
    istio: dlkdev15-egress-gateway
  servers:
  - hosts:
    - google.com
    port:
      name: tls
      number: 443
      protocol: TLS
    tls: {}
````

Everything is working. Due to a security requirement, I need to add mtls between the sidecar & egress gateway. However, when I do this, the listener on 443 is completely removed from the gateway:

````
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sample-gateway
spec:
  selector:
    istio: dlkdev15-egress-gateway
  servers:
  - hosts:
    - google.com
    port:
      name: tls
      number: 443
      protocol: TLS
    tls: 
      mode: ISTIO_MUTUAL
````

Any idea what's going on here?

### Version

```Text
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2
```

**Comment by krissell** [comment]
Here's a more details.

Here is the complete simple example for egress:

````
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sample-se
spec:
  exportTo:
  - .
  - dlkdev15-egress
  hosts:
  - google.com
  ports:
  - name: tls
    number: 443
    protocol: TLS 
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sample-gw
spec:
  selector:
    istio: dlkdev15-egress-gateway
  servers:
  - hosts:
    - google.com
    port:
      name: tls
      number: 443
      protocol: TLS
    tls: {}
      # mode: ISTIO_MUTUAL # this causes the gateway not to listen on port 443
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: sample-destination-rule
spec:
  exportTo:
  - .
  host: dlkdev15-egress-gateway.dlkdev15-egress.svc.cluster.local
  subsets:
  - name: sample-mtls
    # trafficPolicy:
    #   tls:
    #     mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: sample--mesh-vs
spec:
  exportTo:
  - .
  - dlkdev15-egress
  gateways:
  - mesh
  - sample-gw
  hosts:
  - google.com
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - google.com
    route:
    - destination:
        host: dlkdev15-egress-gateway.dlkdev15-egress.svc.cluster.local
        port:
          number: 443
        subset: sample-mtls
      weight: 100 
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sample-gw-virtualservice
spec:
  exportTo:
  - .
  - dlkdev15-egress
  gateways:
  - sample-gw
  hosts:
  - google.com
  tls:
  - match:
    - gateways:
      - sample-gw
      port: 443
      sniHosts:
      - google.com
    route:
    - destination:
        host: google.com
        port:
          number: 443
      weight: 100
````

With that, egress is working to the named domain & I can see the gateway listening on 443:
````
ADDRESS PORT  MATCH           DESTINATION
0.0.0.0 80    ALL             Route: http.80
0.0.0.0 443   SNI: google.com Cluster: outbound|443||google.com
0.0.0.0 9080  ALL             Route: http.9080
0.0.0.0 15021 ALL             Inline Route: /healthz/ready*
0.0.0.0 15090 ALL             Inline Route: /stats/prometheus*
````

But when I udpate the above example to uncomment the 2 section to enable ISTIO_MUTUAL the gateway listener stops listening on 443:
````
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 80    ALL   Route: http.80
0.0.0.0 9080  ALL   Route: http.9080
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus
````

I'd thought it should instead listen for the new sni name which the sidecar now sets:
sni: outbound_.443_.sample-mtls_.dlkdev15-egress-gateway.dlkdev15-egress.svc.cluster.local
