### ISSUE TITLE
Traefik Router unable to communicate with STRICT mTLS enabled services in Istio Mesh

### ISSUE THREAD

**Issue by palashbasik** [istio/istio#51482]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are encountering a problem where the Traefik router, configured to use Let's Encrypt for TLS termination, is unable to communicate with microservices that have STRICT mTLS enabled in the Istio mesh in a K3S cluster. 

Steps to Reproduce:
1) Install istiod helm chart in the K3S cluster.
2) Configure Traefik with Let's Encrypt Certificate Resolver for TLS.
3) Create a router to access microservices in mesh from outside of the cluster. 

Configuration Snippets:
1) Traefik router
```
example-service:
  entryPoints:
    - websecure
  rule: "Host(`example.app.com`) && PathPrefix(`/`)"
  tls:
    certResolver: leresolver
  service: example-service.default.svc.cluster.local:8000

```
2) Istio PeerAuthentication for default and traefik namespace.
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mtls-default
  namespace: default
spec:
  mtls:
    mode: STRICT
```
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mtls-traefik
  namespace: traefik
spec:
  mtls:
    mode: STRICT
```

I can access example-service inside a mesh.
```
kubectl exec -it <any-pod in default namespace> /bin/sh
wget http://example-service.default.svc.cluster.local:8000/user
```

When attempting to access https://example.app.com/user from a browser, the following error occurs.
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```
However, changing the PeerAuthentication mtls.mode to PERMISSIVE makes https://example.app.com/user accessible. 

How can I make it accessibe when the mtls.mode is STRICT? 

Expected Behaviour:
Since both traefik and the microservices has istio-proxy sidecar https://example.app.com/user should be accessible from a browser when the mtls.mode is STRICT.

Note:
Since I am using traefik for ingress, I don't want to use istio-ingressgateway.

@AquamanRanda

### Version

```Text
Istio helm chart version:
1.22.0-rc.0

$ helm version
version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}

$ kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.25.6+k3s1

Cluster type:
Single node on-prem K3S

Ingress Controller:
Traefik v2.9.8
```

**Comment by howardjohn** [comment]
Traefik is probably routing directly to a pod instead of a service. Unless this can be configured with traefik then there isn't many options to make this work. 

The new ambient mode does support direct-to-pod traffic

**Comment by palashbasik** [comment]
I have installed Istio Ingress Gateway and redirected the traffic from the Traefik router to the Istio Ingress Gateway.
I am able to access the example.app.com in STRICT mtls mode.

The snippet from the scenario mentioned above is as follows.
Note: I changed the port for istio-ingressgateway to avoid conflict with traefik.

## Directing traefik router to the Istio ingress gateway rather than the intended service.
```
example-service:
  entryPoints:
    - websecure
  rule: "Host(`example.app.com`) && PathPrefix(`/`)"
  tls:
    certResolver: leresolver
  service: istio-ingressgateway.istio-system.svc.cluster.local:8077
```
## Defining the gateway and virtual service in Istio to handle traffic from Traefik.  
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-app-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 8077
      name: http
      protocol: HTTP
    hosts:
    - "example.app.com"
``` 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-app-vs
  namespace: default
spec:
  hosts:
  - "example.app.com"
  gateways:
  - example-app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: example-service.default.svc.cluster.local
        port:
          number: 8000
```         
Should I go with this approach?
Is having two ingress (traefik and istio-ingressgateway) architecturally good?

I also tried istio ambient mode with strict mtls peerauthentication applied on both traefik and default namespace.
No luck.

**Comment by howardjohn** [comment]
With sidecars, sending to istio-ingressgateway is probably the best bet, unless there is a way in traefik to send to service IP instead of pod IP; I don't know of one.

Ambient should work. Would love to have more info on what you tried and what failed there

**Comment by Phenix66** [comment]
> With sidecars, sending to istio-ingressgateway is probably the best bet, unless there is a way in traefik to send to service IP instead of pod IP; I don't know of one.
> 
> Ambient should work. Would love to have more info on what you tried and what failed there

You're saying Ambient mode should allow the third party ingress to function with STRICT mTLS _without_ the Istio gateway? I have had no success there. I do not want to use the Istio gateway as an intermediary as then I have to worry about securing that traffic.

Here's my minimal reproducible deployment
```
minikube start --nodes 3
istioctl install --set profile=ambient --skip-confirmation
kubectl create namespace ingress-nginx
kubectl label namespaces ingress-nginx istio.io/dataplane-mode=ambient
kubectl label namespaces default istio.io/dataplane-mode=ambient

kubectl apply -n istio-system -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
EOF

minikube addons enable ingress
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io -n ingress-nginx ingress-nginx-admission
kubectl create secret tls tls-secret --cert=grafana.crt --key=grafana.key

helm install grafana grafana --repo=https://grafana.github.io/helm-charts \
    --set-json 'ingress={"enabled":true,"ingressClassName":"nginx","hosts":["grafana.example.net"],"tls":[{"secretName":"tls-secret","hosts":["grafana.example.net"]}]}'
```

And the result via curl
```
$ curl -vk https://grafana.example.net
* Host grafana.example.net:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.49.2
*   Trying 192.168.49.2:443...
* Connected to grafana.example.net (192.168.49.2) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to grafana.example.net:443 
* Closing connection
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to grafana.example.net:443
```

If I remove the PeerAuthentication policy it works right away.

**Comment by howardjohn** [comment]
I expect that to work. Thanks for the reproducer, I'll try it out next week

**Comment by howardjohn** [comment]
Oh sorry, my bad. I misread the setup. 

The problem here is the ztunnel is processing _inbound_ traffic to ingress-nginx. This is plaintext since its (usually) coming from external clients through the load balancer. This is where it is denied

You will need to turn off strict mode from the ingress-nginx pod specifically, then the rest can be STRICT.

**Comment by Phenix66** [comment]
> Oh sorry, my bad. I misread the setup.
> 
> The problem here is the ztunnel is processing _inbound_ traffic to ingress-nginx. This is plaintext since its (usually) coming from external clients through the load balancer. This is where it is denied
> 
> You will need to turn off strict mode from the ingress-nginx pod specifically, then the rest can be STRICT.

Oh wow, out of all the attempted solutions I tried (and there were many) I never thought to just apply another mTLS policy that would override the mesh level one. That seems to have fixed it in my reproducer, will test it out on my actual project this week. Thank you!

For anyone reading this in the future, this is all I had to apply to my above example to get it to cooperate:
```
kubectl apply -n ingress-nginx -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ingress-mtls
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-nginx
  mtls:
    mode: PERMISSIVE
EOF
```
The ztunnel logs in my minikube instance indicate that the traffic is being secured as desired now but I will definitely be verifying this via tcpdump on my non-minikube clusters.
