### ISSUE TITLE
tlss passthrough requires sectionName in parentRef instead of choosing correct listener by hostname

### ISSUE THREAD

**Issue by rwong2888** [istio/istio#51502]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

the below gateway listeners and tlsRoute did not work without sectionName in the tlsRoute's parentRef

expectation would be that it would filter on hostname like a httpRoute without requiring sectionName

gateway

```
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.foo.bar.com'
    name: https-foo-bar-01
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
  - allowedRoutes:
      namespaces:
        from: All
    hostname: foo.bar.com
    name: https-foo-bar-02
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
```

tlsroute

```
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1alpha2
  kind: TLSRoute
  metadata:
    name: foo-tlsroute
    namespace: foo-bar
  spec:
    hostnames:
    - foo.bar.com
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-internal-01
      namespace: istio-ingress
      sectionName: https-foo-bar-02
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: production-foo-bar
        port: 443
        weight: 1
```

### Version

```Text
❯ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (80 proxies)

❯ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-gke.1043002
```

**Comment by pratikkumar-mohite** [comment]
I would like to work on this, @howardjohn can you please assign?

**Comment by rwong2888** [comment]
any traction @pratikkumar-mohite ?

**Comment by pratikkumar-mohite** [comment]
@rwong2888 Sorry I didnt get time to work on this, Looking into this, will be providing the updates soon

**Comment by rwong2888** [comment]
@howardjohn , @pratikkumar-mohite can be reopened?

**Comment by stelucz** [comment]
I am having same or similar problem. However in my case, tlsroute is not attached to gateway even when I specify `sectionName:` in tlsroute.

```
istioctl version
client version: 1.23.3
control plane version: 1.23.3
data plane version: 1.23.3 (1 proxies)
```

gateway:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-istio-gw
  namespace: istio-system
spec:
  gatewayClassName: istio 
  infrastructure:
    annotations:
      service.beta.kubernetes.io/port_443_health-probe_protocol: tcp
  listeners:
  - name: https
    port: 443
    protocol: TLS
    hostname: "<mydomain>"
    tls:
       mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
```
tlsroute:
```
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: tlsroute-istio
spec:
  parentRefs:
    - name: tls-istio-gw
      namespace: istio-system
      sectionName: https
  hostnames:
    - "<mydomain>"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: passthrough-echoserver
          port: 443
          weight: 1
```

Istio was deployed by:
```
istioctl install --set profile=minimal -y -f values.yaml

cat values.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  values:
    global:
      proxy:
        clusterDomain: "<mycluster>"
```
