### ISSUE TITLE
combine the locality loadbalancer behaviour with the LEAST_REQUEST loadbalance in multi-cluster

### ISSUE THREAD

**Issue by fizos** [istio/istio#51537]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

Currently, we have three different clusters formed a multi-primary multi-network Istio meshes. Now, we need to achieve LEAST_REQUEST load balancing between clusters while ensuring regional affinity. In other words, when a request enters a cluster, it should be processed first within that cluster and then gradually routed to other clusters based on the LEAST_REQUEST strategy. Additionally, we also need the ability to transfer across clusters when a pod responds abnormally.

Is there currently any configuration supporting this scenario?
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: simple-backend-dr
spec:
  host: simple-backend.demo.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10
        maxRequestsPerConnection: 10
    loadBalancer:
      simple: LEAST_REQUEST
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 1
      interval: 10s
```
When I tried to use the above configuration, only the regional affinity was effective.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
