### ISSUE TITLE
IST0128 and IST0129  reports raised even when credentialName and workloadSelector are used

### ISSUE THREAD

**Issue by leosarra** [istio/istio#51567]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Currently if you have the following DR

```
# No caCertificates when mode is simple at port level
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: db-tls
spec:
  host: mydbserver.prod.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          credentialName: db-credential
  workloadSelector:
      matchLabels:
        app: db

```
you will get an IST0129 (IST0128 depending on where you are defining the tls settings) report despite the db-credential and workloadselector being set.

I think the warning can be lifted for this scenario, although it needs to be retained in case the workloadSelector is missing.
The reason to retain the warning in case of absence of the workloadSelector is due to the following behavior (from istio.io doc about credentialName):

```
NOTE: This field is applicable at sidecars only if DestinationRule has a workloadSelector specified. Otherwise the field will be applicable only at gateways, and sidecars will continue to use the certificate paths.
```

### Version

```Text
1.22.1
```

### Additional Information

-
