### ISSUE TITLE
Istio Egress gateway for TCP traffic port 22

### ISSUE THREAD

**Issue by bhat39a** [istio/istio#51616]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team,

We are getting the below error in the istio-proxy sidecar container, we have egress for wildcard and its working fine but traffic for port 22 is not being routed to egressgateway, below is our configuration file. I am not sure what are we missing in here.

Error From istio-proxy sidecar :

[2024-06-18T13:17:50.593Z] "- - -" 0 - - - "-" 2313 7962 130 - "-" "-" "-" "-" “xx.xx.xx.xx:8443" outbound|443|wildcard|egressgateway.istio-egress.svc.cluster.local xx.xx.xx.xx:46114 xx.xx.xx.xx:443 xx.xx.xx.xx:47368 ec2.eu-west-1.amazonaws.com -
[2024-06-18T13:17:50.729Z] "- - -" 0 - - - "-" 2306 7960 89 - "-" "-" "-" "-" “xx.xx.xx.xx:8443" outbound|443|wildcard|egressgateway.istio-egress.svc.cluster.local xx.xx.xx.xx:46120 xx.xx.xx.xx:443 xx.xx.xx.xx:50828 ec2.eu-west-1.amazonaws.com -
[2024-06-18T13:17:50.821Z] "- - -" 0 NC - - "-" 0 0 0 - "-" "-" "-" "-" "-" - - xx.xx.xx.xx:22 xx.xx.xx.xx:33264 - -
[2024-06-18T13:17:50.821Z] "- - -" 0 NC - - "-" 0 0 0 - "-" "-" "-" "-" "-" - - xx.xx.xx.xx:22 xx.xx.xx.xx:33266 - -
[2024-06-18T13:17:17.231Z] "- - -" 0 - - - "-" 105136 93604 89986 - "-" "-" "-" "-" “xx.xx.xx.xx:8443" outbound|443|wildcard|egressgateway.istio-egress.svc.cluster.local xx.xx.xx.xx:47366 xx.xx.xx.xx:443 xx.xx.xx.xx:47536 xx.xx.xx.com -

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-port-22
  namespace: istio-system
spec:
  hosts:
  - "example.com"
  addresses:
  - 10.0.0.0/8
  ports:
  - number: 22
    name: tcp
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: tcp
      protocol: TCP
    hosts:
    - "example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-tcp
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - "example.com"
  tcp:
  - match:
    - port: 22
    route:
    - destination:
        host: "istio-egressgateway.istio-system.svc.cluster.local"
        port:
          number: 22


```

### Version

```Text
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
```

**Comment by howardjohn** [comment]
`outbound|443|wildcard|egressgateway.istio-egress.svc.cluster.local ` implies its going to subset=wildcard. That is not defined anywhere in your config in the issue. I am fairly confident you have some config that is not in the issue causing this.,

**Comment by bhat39a** [comment]
> Ah sorry, got it. Do you have port 22 defined on the gateway Service?

do you mean this. Posted the entire config file above. 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: tcp
      protocol: TCP
    hosts:
    - "example.com"
```

**Comment by howardjohn** [comment]
That just configures the GW, it still needs to be in the Service object as well

**Comment by bhat39a** [comment]
> That just configures the GW, it still needs to be in the Service object as well

Yes added the same but its still the same issue. Sharing the entire config file.

```
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-egressgateway
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    istio: egressgateway
  ports:
  - port: 22
    name: tcp-egress
    targetPort: 22
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-port-22
  namespace: istio-system
spec:
  hosts:
  - "example.com"
  addresses:
  - 10.0.0.0/8
  ports:
  - number: 22
    name: tcp
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: tcp-egress
      protocol: TCP
    hosts:
    - "example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-tcp
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - "example.com"
  tcp:
  - match:
    - port: 22
    route:
    - destination:
        host: "istio-egressgateway.istio-system.svc.cluster.local"
        port:
          number: 22
```
