### ISSUE TITLE
gateways listeners disappears after the 1.22 upgrade

### ISSUE THREAD

**Issue by eraac** [istio/istio#51630]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I try to upgrade my Istio configuration from 1.21.3 to 1.22.1, as soon the istiod is rollout the gateway stop serving traffic

### Version

```Text
$ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.21.3 (19 proxies), 1.22.0 (1 proxies), 1.22.1 (8 proxies)

$ kubectl version
Client Version: v1.27.15
Kustomize Version: v5.0.1
Server Version: v1.28.9-gke.1209000
```

### Additional Information

I've one warning from istiod pod 
```
2024-06-19T12:09:02.869061Z     warn    buildGatewayRoutes: no gateways for router ingress-gateway-global-6cf6597779-kkjjl.istio-ingress
```

Via the `proxy-config listener`, it's seems the listener is missing
```
ADDRESSES PORT  MATCH DESTINATION
0.0.0.0   15021 ALL   Inline Route: /healthz/ready*
0.0.0.0   15090 ALL   Inline Route: /stats/prometheus*
```

My configuration
<details>
<summary>operator.yaml</summary>

```yml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal

  meshConfig:
    # same as default, without the X-FORWARDED-FOR header (we can't store client IPs)
    # DOWNSTREAM_REMOTE_ADDRESS is the load balancer IP
    accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"

    discoverySelectors:
    - matchLabels:
        istio-discovery: enabled

  values:
    global:
      multiCluster:
        clusterName: "xxxx"

      proxy:
        privileged: true

    pilot:
      autoscaleEnabled: false

    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false

    sidecarInjectorWebhook:
      templates:
        sleep: |
          spec:
            containers:
            - name: istio-proxy
              lifecycle:
                preStop:
                  exec:
                    command:
                      - "/bin/sh"
                      - "-c"
                      - "sleep 180s"

  components:
    pilot:
      enabled: true

      k8s:
        priorityClassName: critical

        podDisruptionBudget:
          minAvailable: 1

        resources:
          requests:
            cpu: 100m
            memory: 500Mi

        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:
          - path: spec.template.metadata.labels.app\.kubernetes\.io/name
            value: istiod

    ingressGateways:

      #######
      # GLB #
      #######

    - name: ingress-gateway-global
      namespace: istio-ingress
      enabled: true
      label:
        app.kubernetes.io/name: ingress-gateway-global

      k8s:
        tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "istio"
          effect: "NoSchedule"

        resources:
          requests:
            cpu: 300m

        podDisruptionBudget:
          minAvailable: 1

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "cloud.google.com/gke-nodepool"
                  operator: "In"
                  values:
                  - "istio-01"

        serviceAnnotations:
          cloud.google.com/neg: '{"exposed_ports": {"8443": {}}, "ingress": true}'

        podAnnotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 60s
            proxyStatsMatcher:
              inclusionRegexps:
                - ".*upstream_rq_retry.*"
                - ".*upstream_cx_.*"
                - ".*downstream_cx_.*"
              inclusionSuffixes:
                - "upstream_rq_timeout"
                - "downstream_rq_timeout"

        service:
          type: ClusterIP
          ports:
          - name: https
            port: 8443
            protocol: TCP
            targetPort: 8443

        strategy:
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1

        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: ingress-gateway-global
          patches:

            # set a startupProbe
          - path: spec.template.spec.containers.[name:istio-proxy].startupProbe
            value: |
              initialDelaySeconds: 1
              failureThreshold: 30
              httpGet:
                path: "/healthz/ready"
                port: 15021
                scheme: HTTP

            # increase the termination grace periods, must be higher than 'terminationDrainDuration'
            # 3 minutes 30 secondes (Google recommendation)
          - path: spec.template.spec.terminationGracePeriodSeconds
            value: 210

            # delay the SIGTERM signal, to ensure NEG is update before
          - path: spec.template.spec.containers.[name:istio-proxy].lifecycle.preStop.exec.command
            value: ["/bin/sh", "-c", "sleep 120s"]

      #######
      # ILB #
      #######

    - name: ingress-gateway-internal
      namespace: istio-ingress
      enabled: true
      label:
        app.kubernetes.io/name: ingress-gateway-internal

      k8s:
        tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "istio"
          effect: "NoSchedule"

        resources:
          requests:
            cpu: 200m

        podDisruptionBudget:
          minAvailable: 1

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "cloud.google.com/gke-nodepool"
                  operator: "In"
                  values:
                  - "istio-01"

        serviceAnnotations:
          cloud.google.com/neg: '{"exposed_ports": {"8443": {}}, "ingress": true}'

        podAnnotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 60s
            proxyStatsMatcher:
              inclusionRegexps:
                - ".*upstream_rq_retry.*"
                - ".*upstream_cx_.*"
                - ".*downstream_cx_.*"
              inclusionSuffixes:
                - "upstream_rq_timeout"
                - "downstream_rq_timeout"

        service:
          type: ClusterIP
          ports:
          - name: https
            port: 8443
            protocol: TCP
            targetPort: 8443

        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0

        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: ingress-gateway-internal
          patches:

            # set a startupProbe
          - path: spec.template.spec.containers.[name:istio-proxy].startupProbe
            value: |
              initialDelaySeconds: 1
              failureThreshold: 30
              httpGet:
                path: "/healthz/ready"
                port: 15021
                scheme: HTTP

            # increase the termination grace periods, must be higher than 'terminationDrainDuration' and preStop hook duration
            # 3 minutes 30 secondes (Google recommendation)
          - path: spec.template.spec.terminationGracePeriodSeconds
            value: 210

            # delay the SIGTERM signal, to ensure NEG is update before
          - path: spec.template.spec.containers.[name:istio-proxy].lifecycle.preStop.exec.command
            value: ["/bin/sh", "-c", "sleep 120s"]
```

</details>

<details>
<summary>gateway.yml</summary>

```yml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: glb-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
    service.istio.io/canonical-name: ingress-gateway-global
  servers:
  - port:
      number: 8443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: istio-gateway-certificate
```
</details>

The only changes is the Istio version, I've try all release between 1.21.2 and 1.22.1, the issue occurs only on 1.22.x versions. I don't think having a fanzy configuration, I'm a bit confuse

**Comment by zirain** [comment]
not sure why this happen, but `service.istio.io/canonical-name: ingress-gateway-global` seems be redundant.

**Comment by eraac** [comment]
> not sure why this happen, but `service.istio.io/canonical-name: ingress-gateway-global` seems be redundant.

There are more than one gateway, using only `istio: ingressgateway` lead to multiple gateway being selected. But I've also try removing the other gateways and the selector, the issue is still here

**Comment by zirain** [comment]
can you check the labels of your gateway pods, seems there's a mismatch.

**Comment by eraac** [comment]
There is no mismatch

```yml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    istio.io/rev: default
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    proxy.istio.io/config: |
      terminationDrainDuration: 60s
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*upstream_rq_retry.*"
          - ".*upstream_cx_.*"
          - ".*downstream_cx_.*"
        inclusionSuffixes:
          - "upstream_rq_timeout"
          - "downstream_rq_timeout"
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2024-06-19T14:57:54Z"
  generateName: ingress-gateway-global-558b9cc655-
  labels:
    app: istio-ingressgateway
    app.kubernetes.io/name: ingress-gateway-global
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    pod-template-hash: 558b9cc655
    service.istio.io/canonical-name: ingress-gateway-global
    service.istio.io/canonical-revision: latest
    sidecar.istio.io/inject: "false"
  name: ingress-gateway-global-558b9cc655-7dk27
```
