### ISSUE TITLE
Load Imbalance since 1.22 upgrade

### ISSUE THREAD

**Issue by Stono** [istio/istio#51642]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I apologise in advance for how vague this issue is, but i felt it right to get it on the radar sooner rather than later - and I can update the thread if/when i find anything.

Not long after upgrade some workloads, our alerts for imbalanced proxy cpu load set off; here's an example of one workload:

![image](https://github.com/istio/istio/assets/1486729/9829bd38-7110-4db1-970f-301ff3c32d3d)

You can see one pod is trending up above the others.  There are 6 pods, 2 in each locality (zone).  Locality Routing is enabled.

The pod with the higher load is in `west4-b`, it is one of 2 pods in that zone, so i can't understand why they aren't getting an even distribution of the load.

I decided to roll back to a `1.21.2` proxy, at 07:35 here:

<img width="1920" alt="Screenshot 2024-06-20 at 08 51 26" src="https://github.com/istio/istio/assets/1486729/a9949fb2-6f83-4bf6-98b7-9c4ad7c82d14">

As you can see the outlier pod went away, what i found interesting is that two pods were lower than the others.  

If i draw the same graph but remove the pod label (so just zone) you can see that on 1.22.1 more of the traffic was being weighted towards west4-b, whereas on 1.21.1 must less of the traffic was being sent to west4-b.

<img width="1920" alt="Screenshot 2024-06-20 at 09 08 53" src="https://github.com/istio/istio/assets/1486729/c687e878-3096-4731-a2d9-651c6c6f9816">

I rolled proxy versions forward and back to validate this behaviour and i consistently see different traffic distribution between 1.21 and 1.22:

<img width="1920" alt="Screenshot 2024-06-20 at 08 59 56" src="https://github.com/istio/istio/assets/1486729/57b3615f-44a1-4501-bc21-bad3b2cc2c02">

The spec for the `DestinationRule` of this workload is:

```
spec:
  host: app.native-apps-service.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
        idleTimeout: 2m
      tcp:
        tcpKeepalive:
          interval: 30s
          time: 30s
    loadBalancer:
      localityLbSetting:
        enabled: true
      simple: LEAST_REQUEST
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 0
      consecutiveGatewayErrors: 5
      interval: 5s
      maxEjectionPercent: 35
      minHealthPercent: 50
    tls:
      mode: ISTIO_MUTUAL
```

So now here's the real kicker... as all signed pointed towards _something_ locality related, I disabled `localityLbSetting` and it didn't fix it.  5 of the pods ended up closer together in terms of load however there was still one outlier on 1.22.1 vs 1.21.2.

So i'm stumped.

### Version

```Text
1.22.1
```
