### ISSUE TITLE
Already install self-signed root CA on OS, DestinationRule still unable to get local issuer certificate

### ISSUE THREAD

**Issue by nature502** [istio/istio#51679]
I expose httpbin application as Istio(version 1.21) service according to https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/, and deploy sleep application - It's a ubuntu container with curl installed that can be used as a request source for invoking other services. Below is my configuration

Configure a TLS ingress gateway for a single host
```
$ cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: httpbin-credential # must be the same as secret
    hosts:
    - httpbin.example.com
----
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
EOF
```
Configure mutual TLS origination for egress traffic at sidecar
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: originate-mtls-for-httpbin
spec:
  hosts:
  - httpbin.example.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-httpbin
spec:
  workloadSelector:
    matchLabels:
      app: sleep
  host: httpbin.example.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: MUTUAL
        clientCertificate: /etc/certs/cert.pem
        privateKey: /etc/certs/key.pem
        sni: httpbin.example.com
EOF
```
If we don't specify CA here, the proxy will verify the server’s certificate using the OS CA certificates according to https://istio.io/latest/zh/docs/reference/config/networking/destination-rule/#ClientTLSSettings. To verify this, I installed self-singed CA into **sleep** images according to https://www.geeksforgeeks.org/how-to-add-a-ca-root-certificate-inside-a-docker-image/. 
Execute `kubectl exec "$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -sS http://httpbin.example.com/status/418`, and Istio proxy complains below.
```
2024-06-21T17:48:15.356082Z	debug	envoy connection external/envoy/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc:325	verify cert failed: X509_verify_cert: certificate verification error at depth 0: unable to get local issuer certificate	thread=22
```
Looks like the proxy couldn't identify the CA installed by me, but the root CA is already installed on OS, because the curl without CA is working fine, get OK by sending `curl -v --cert /etc/certs/cert.pem --key /etc/certs/key.pem "https://httpbin.example.com/status/418"` inside the sleep pod.
