### ISSUE TITLE
reenable metric with Telemetry API without overrides not working

### ISSUE THREAD

**Issue by zirain** [istio/istio#51697]
you can reproduce with following configuration:
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable-metrics
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - disabled: true
          match:
            metric: ALL_METRICS
            mode: CLIENT_AND_SERVER
      providers:
        - name: prometheus
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: empty-prometheus
  namespace: default
spec:
  metrics:
    - providers:
        - name: prometheus
      # reenable all metrics won't work without the following override
      # overrides:
      #   - match:
      #       metric: ALL_METRICS
```
