### ISSUE TITLE
gateway listeners are very slow to update if no Service selects a gateway at creation time

### ISSUE THREAD

**Issue by birkland** [istio/istio#51726]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istod will eventually configure listeners on gateways that match the `targetPort` of services that select the gateway.  If a service exists already at time of gateway pod creation, that gateway is immediately configured correctly.  However, if the service is created _after_ the gateway has been started, then several minutes will pass (I've seen 5-10 minutes) before the gateway has the corresponding listener configured.

To demonstrate:
1.  Install Istio `istioctl install --set profile=minimal`
2. Install httpbin `kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml`
3. Create gateway namespace:  `kubectl create namespace istio-ingress`
4. install routing objects:
```
kubectl apply -n istio-ingress -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /httpbin
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
EOF
```
4. Install a gateway using type None (to create no Service)
```
helm install istio-ingressgateway istio/gateway -n istio-ingress --set service.type=None
```
5. Then, once the gateway is up,  create a service that selects it:
```
kubectl apply -n istio-ingress -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  name: istio-ingressgateway
spec:
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
EOF
```

If you curl the gateway, it will not work. 
```
 export GATEWAY=$(kubectl  get -n istio-ingress services istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
curl  http://$GATEWAY/httpbin/get

curl: (7) Failed to connect to 172.20.1.1 port 80 after 0 ms: Connection refused
```

 You can see why by loooking at the listeners, port is 80, but the service selects 8080
```
istioctl -n istio-ingress proxy-config listener istio-ingressgateway-778d69499b-4k6j2
ADDRESSES PORT  MATCH DESTINATION
0.0.0.0   80    ALL   Route: http.80
0.0.0.0   15021 ALL   Inline Route: /healthz/ready*
0.0.0.0   15090 ALL   Inline Route: /stats/prometheus*
```

6. You can keep trying for a few minutes without success, then re-start the gateway:
```
kubectl rollout restart -n istio-ingress deployment istio-ingressgateway 
```

curl now works!
```
curl  http://$GATEWAY/httpbin/get
```

you can see the listener was updated to listen on the port the service is selecting:
```
istioctl proxy-config listener -n istio-ingress istio-ingressgateway-84b57c574f-qkwq8 
ADDRESSES PORT  MATCH DESTINATION
0.0.0.0   8080  ALL   Route: http.8080
0.0.0.0   15021 ALL   Inline Route: /healthz/ready*
0.0.0.0   15090 ALL   Inline Route: /stats/prometheus*
```

If you do step 5 before 4 (i.e. create the service before the gateway), everything just works from the start

### Version

```Text
istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (1 proxies)
```
