### ISSUE TITLE
provide default request for cpu/mem for sidecar

### ISSUE THREAD

**Issue by linsun** [istio/istio#5175]
We should provide a default requested resource for cpu/mem for our default envoy side car so that if users want to explore auto scaling, it can work without extra work.

Currently our docs ask people to either modify the yaml or modify the config template (https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl) and use the --injectconfigfile.  That is fine for advanced case but for simple case, people can just take a default value for cpu and mem.

**Comment by ymesika** [comment]
If I'm not mistaken the `istio-sidecar-injector-configmap-release.yaml.tmpl` (or the whole _install/kubernetes/templates_) won't exist anymore in the release. Therefore the ConfigMap to be injected is the one embedded into the `istioctl` binary or a custom one provided by the user.

I can modify the _sidecar-template_ of _istioctl_ to inject the `istio-proxy` container with:
```yaml
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

or just:
```yaml
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
```

so that any manually injected sidecar will hold these attributes.
