### ISSUE TITLE
Retry not Retrying

### ISSUE THREAD

**Issue by Stono** [istio/istio#51762]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have the following `VirtualService` which configures a `retryOn: 503` 

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  annotations:
    atcloud.io/fault-injection: "true"
    meta.helm.sh/release-name: unified-registration-system
    meta.helm.sh/release-namespace: unified-registration-system
  name: iovox
  namespace: unified-registration-system
spec:
  exportTo:
  - .
  hosts:
  - api.voxanalytics.com
  http:
  - match:
    - port: 80
    name: httpPort
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,502,503
    route:
    - destination:
        host: api.voxanalytics.com
        port:
          number: 80
      headers:
        request:
          remove:
          - x-envoy-attempt-count
          - x-envoy-decorator-operation
          - x-envoy-expected-rq-timeout-ms
          - x-envoy-hedge-on-per-try-timeout
          - x-envoy-is-timeout-retry
          - x-envoy-max-retries
          - x-envoy-original-path
          - x-envoy-peer-metadata
          - x-envoy-peer-metadata-id
          - x-envoy-retriable-header-names
          - x-envoy-retriable-status-codes
          - x-envoy-retry-grpc-on
          - x-envoy-retry-on
          - x-envoy-upstream-alt-stat-name
          - x-envoy-upstream-rq-per-try-timeout-ms
          - x-envoy-upstream-rq-timeout-alt-response
          - x-envoy-upstream-rq-timeout-ms
          - x-envoy-upstream-service-time
          - x-envoy-upstream-stream-duration-ms
          set:
            host: api.voxanalytics.com
      weight: 100
    timeout: 10s
  - match:
    - port: 444
    name: httpsPort
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,502,503
    route:
    - destination:
        host: api.voxanalytics.com
        port:
          number: 444
      headers:
        request:
          remove:
          - x-envoy-attempt-count
          - x-envoy-decorator-operation
          - x-envoy-expected-rq-timeout-ms
          - x-envoy-hedge-on-per-try-timeout
          - x-envoy-is-timeout-retry
          - x-envoy-max-retries
          - x-envoy-original-path
          - x-envoy-peer-metadata
          - x-envoy-peer-metadata-id
          - x-envoy-retriable-header-names
          - x-envoy-retriable-status-codes
          - x-envoy-retry-grpc-on
          - x-envoy-retry-on
          - x-envoy-upstream-alt-stat-name
          - x-envoy-upstream-rq-per-try-timeout-ms
          - x-envoy-upstream-rq-timeout-alt-response
          - x-envoy-upstream-rq-timeout-ms
          - x-envoy-upstream-service-time
          - x-envoy-upstream-stream-duration-ms
          set:
            host: api.voxanalytics.com
      weight: 100
    timeout: 10s
```

However we see requests in Jaeger that aren't be retried:

<img width="1920" alt="Screenshot 2024-06-27 at 11 16 30" src="https://github.com/istio/istio/assets/1486729/049bc841-5b4c-4390-a14b-792bd983ad2f">

The response to the app from envoy was: `upstream connect error or disconnect/reset before headers. reset reason: connection termination`.

I wasn't sure if this was because retries aren't recorded as spans, so I enabled envoy metrics for retries, which confirm that no retry was attempted:

```
# TYPE envoy_cluster_voxanalytics_com_upstream_rq_retry counter
envoy_cluster_voxanalytics_com_upstream_rq_retry{cluster_name="outbound|444||api"} 0
envoy_cluster_voxanalytics_com_upstream_rq_retry{cluster_name="outbound|80||api"} 0
# TYPE envoy_cluster_voxanalytics_com_upstream_rq_retry_backoff_exponential counter
envoy_cluster_voxanalytics_com_upstream_rq_retry_backoff_exponential{cluster_name="outbound|444||api"} 0
envoy_cluster_voxanalytics_com_upstream_rq_retry_backoff_exponential{cluster_name="outbound|80||api"} 0
# TYPE envoy_cluster_voxanalytics_com_upstream_rq_retry_backoff_ratelimited counter
envoy_cluster_voxanalytics_com_upstream_rq_retry_backoff_ratelimited{cluster_name="outbound|444||api"} 0
envoy_cluster_voxanalytics_com_upstream_rq_retry_backoff_ratelimited{cluster_name="outbound|80||api"} 0
# TYPE envoy_cluster_voxanalytics_com_upstream_rq_retry_limit_exceeded counter
envoy_cluster_voxanalytics_com_upstream_rq_retry_limit_exceeded{cluster_name="outbound|444||api"} 0
envoy_cluster_voxanalytics_com_upstream_rq_retry_limit_exceeded{cluster_name="outbound|80||api"} 0
# TYPE envoy_cluster_voxanalytics_com_upstream_rq_retry_overflow counter
envoy_cluster_voxanalytics_com_upstream_rq_retry_overflow{cluster_name="outbound|444||api"} 0
envoy_cluster_voxanalytics_com_upstream_rq_retry_overflow{cluster_name="outbound|80||api"} 0
# TYPE envoy_cluster_voxanalytics_com_upstream_rq_retry_success counter
envoy_cluster_voxanalytics_com_upstream_rq_retry_success{cluster_name="outbound|444||api"} 0
envoy_cluster_voxanalytics_com_upstream_rq_retry_success{cluster_name="outbound|80||api"} 0
```

(note: i've raised a [separate issue](https://github.com/istio/istio/issues/51761) because the cluster_name here is not being built correctly in my opinion.  However i'm linking it from here because i'm wondering if it's another symptom of the tls origination setup).

### Version

```Text
1.21.2
```
