### ISSUE TITLE
Istio outbound traffic via egress gateway - tcp port 22 is not working

### ISSUE THREAD

**Issue by bhat39a** [istio/istio#51770]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio outbound traffic via egress gateway for port 22 is not working, could you please check our config and let us know if we are missing anything.

Configuration : 

```
---
apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    istio: egressgateway
  ports:
  - port: 22
    name: tcp22
    targetPort: 22
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tcp22
  namespace: istio-system
spec:
  hosts:
  - ssh-tcp22.tcp.svc
  addresses:
  - "10.0.0.0/8"
  ports:
  - number: 22
    name: tcp22
    protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: tcp22
      protocol: TCP
    hosts:
    - ssh-tcp22.tcp.svc
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-ssh-tcp22
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: ssh-tcp22
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-ssh-tcp22-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - ssh-tcp22.tcp.svc
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - 10.0.0.0/8
      port: 22
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: ssh-tcp22
        port:
          number: 22
  - match:
    - gateways:
      - istio-egressgateway
      port: 22
    route:
    - destination:
        host: ssh-tcp22.tcp.svc
        port:
          number: 22
      weight: 100

```

Testing the connection

$kubectl exec "$SOURCE_POD" -c sleep -- ssh -vv xx.xx.xx.xx

ssh_exchange_identification: Connection closed by remote host
command terminated with exit code 255

Logs from istio-proxy sidecar container

[2024-06-27T15:59:08.495Z] "- - -" 0 - - - "-" 21 0 0 - "-" "-" "-" "-" "xx.xx.xx.xx:22" outbound|22|ssh-tcp22|istio-egressgateway.istio-system.svc.cluster.local 100.64.79.128:52020 xx.xx.xx.xx:22 100.64.79.128:43924 - -

Logs from egress gateway container

[2024-06-27T15:59:08.495Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" outbound|22||ssh-tcp22.tcp.svc - xx.xx.xx.xx:22 100.64.79.128:52020 - -

### Version

```Text
$ istioctl version

client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (2 proxies)
```
