### ISSUE TITLE
TLS Gateway Passthrough requires disabling mTLS

### ISSUE THREAD

**Issue by joberdick** [istio/istio#51799]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are connecting clusters with an east west gateway. Services connect to each other via mTLS. The gateway on the destination cluster is configured to do passthrough for TLS. For some reason we have to also disable mTLS via destination rule from the gateway to the service. It seems when using passthrough mode, it should be aware that using in cluster mTLS would conflict?

**Note: we are not using Istio native cluster syncing as its not a scalable solution for many clusters. We also enable mTLS globally via config namespace.

Will provide complete setup if needed. Here are the relevant bits for the destination cluster

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: helloworld
  namespace: istiotesting
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - helloworld.ourdomain.com
      port:
        name: tls-passthrough
        number: 15443
        protocol: TLS
      tls:
        mode: PASSTHROUGH
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld
  namespace: istiotesting
spec:
  gateways:
    - mesh
    - helloworld
  hosts:
    - helloworld.ourdomain.com
  tls:
    - match:
        - port: 15443
          sniHosts:
            - helloworld.ourdomain.com
      route:
        - destination:
            host: helloworld.istiotesting.svc.cluster.local
            port:
              number: 80
```

Only works if we add this
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-mtls
  namespace: istiotesting
spec:
  host: helloworld.istiotesting.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

Otherwise the destination proxy returns a 400 DPE error. It seems unexpected to have to disable TLS to honor the original passthrough TLS.

### Version

```Text
client version: 1.21.2
control plane version: 1.21.2
data plane version: 1.21.2 (12 proxies)

Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.12+rke2r1
```
