### ISSUE TITLE
SE may break api-server connectivity in ambient

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51802]
In discussions with @danielloader, it sounds like there may be issues with ambient api-server connectivity in some scenarios.

My repro attempt on kind:

```yaml

apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: k8s-api-ext
spec:
  hosts: [kubernetes.default.svc.cluster.local]
  addresses: [10.96.0.1]
  endpoints:
  - address: 10.96.0.1
  location: MESH_EXTERNAL
  resolution: STATIC
  ports:
  - number: 443
    name: https-k8s
    protocol: HTTPS
```

Internal representation in ztunnel:

```json
  "/10.96.0.1": {
    "endpoints": {
      "Kubernetes/discovery.k8s.io/EndpointSlice/default/kubernetes/172.18.0.5:/172.18.0.5": {
        "address": "/172.18.0.5",
        "port": {
          "443": 6443
        },
        "service": "default/kubernetes.default.svc.cluster.local",
        "workloadUid": "Kubernetes/discovery.k8s.io/EndpointSlice/default/kubernetes/172.18.0.5"
      },
      "Kubernetes/networking.istio.io/ServiceEntry/default/k8s-api-ext/10.96.0.1:/10.96.0.1": {
        "address": "/10.96.0.1",
        "port": {
          "443": 443
        },
        "service": "default/kubernetes.default.svc.cluster.local",
        "workloadUid": "Kubernetes/networking.istio.io/ServiceEntry/default/k8s-api-ext/10.96.0.1"
      }
    },
    "hostname": "kubernetes.default.svc.cluster.local",
    "name": "kubernetes",
    "namespace": "default",
    "ports": {
      "443": 6443
    },
    "subjectAltNames": [],
    "vips": [
      "/10.96.0.1"
    ]
  },
```

Note this actually works -- it will load balance between directly hitting the API server endpoint (172.18.0.5) and the service (10.96.0.1, kube-proxy will translate it for us). Definitely wonky though.

Opening this issue to track as I cannot yet reproduce it. Trying on AWS next
