### ISSUE TITLE
ServiceEntry does not affect when using Ambient Mode.

### ISSUE THREAD

**Issue by laiminhtrung1997** [istio/istio#51819]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello everyone, I am a newbie with Istio but my project. We currently use Sidecar Mode but wanna upgrade to use Ambient Mode. There is a problem with the connection to the PostgreSQL cluster. We are using Postgres Operator developed by Zalando, the operator creates a service but no selector. The istio cannot route the traffic to endpoints. So we must make the ServiceEntry to solve it.
Refer: https://github.com/zalando/postgres-operator/issues/772#issuecomment-567321183
And now, when we use the Ambient Mode, the ServiceEntry is unaffected and the traffic fails. Can someone please help me with this?
```
2024-07-01T07:17:15.411348Z     warn    access  connection failed       src.addr=10.100.109.97:60970 dst.addr=10.100.148.254:5432 direction="outbound" error="no healthy upstream: 10.100.148.254:5432"
```
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: postgresql-cluster
  namespace: datastore
spec:
  hosts:
  - "*.postgresql.datastore.svc.cluster.local"
  location: MESH_INTERNAL
  ports:
  - name: tcp-postgresql
    number: 5432
    protocol: TCP
  - name: http-8080
    number: 8080
    protocol: TCP
  - name: http-8008
    number: 8008
    protocol: TCP
  resolution: NONE
```

### Version

```Text
client version: 1.22.2
control plane version: 1.22.2
data plane version: 1.22.2 (5 proxies)
```
