### ISSUE TITLE
404 NR 0 0 0  when using Istio-proxy for outbound communication

### ISSUE THREAD

**Issue by bharatnc** [istio/istio#5182]
I'm using istio with services trying to talk to Google OAuth through port 443: I get the following error when I log the isitio-proxy containers.
```

[2018-04-24T19:12:46.484Z] "POST /o/oauth2/token HTTP/1.1" 404 NR 0 0 0 - "-" "Go-http-client/1.1" "cf149902-c381-923e-9acb-7ced28707fe0" "accounts.google.com" "-"
[2018-04-24T19:12:46.480Z] "GET /login?state=state&code=4/AAAhshFeMPSj5OcorAk1WQZ2gpuJ-FfwyQoi38ZLa4wA_jtHrj6b5a8IlXXnEbLafFdtMlKFCZ8kIhr_MoDJyeE HTTP/1.1" 500 - 0 133 5 4 "10.36.57.25" 

```
This happens even when I have an egress rule that looks like this:
```

apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: www-googleapis-com
spec:
  destination:
    service: www.googleapis.com
  ports:
    - port: 443
      protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: googleapis-com
spec:
  destination:
    service: "*.google.com"
---

```

Along with a route rule:

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: googleapis-com
spec:
  destination:
    service: "*.google.com"
```
