### ISSUE TITLE
Bug: When the port is not explicitly designated as HTTP by other services, the protocol sniffing server port cannot route services using only the host.

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#51820]
**Normal case**
In our cluster, we have two services, productpage and reviews, both running on port 9080. The 9080 port of the productpage service is explicitly designated as an HTTP port, while the 9080 port of the reviews service is not designated with a protocol.
```
# productpage
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
# reviewss
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
  selector:
    app: reviews
```
For testing purposes, we access the reviews service from a [sleep deployment](https://raw.githubusercontent.com/istio/istio/release-1.22/samples/sleep/sleep.yaml) that is also injected with a sidecar. We can access it in two ways: using the cluster IP or the host.
```
# access reviews by cluster ip
curl -H "host: xxxx" 192.168.156.244:9080/reviews/1

# access reviews by host with any ip
curl -H "host: reviews:9080" 1.1.1.1:9080/reviews/1
```
Now, everything is ok. Note that the above curl commands will both hit default route of `reviews.default.svc.cluster.local:9080` not `allow_any`.

**Bad case**
If I delete the productpage service or change the port of the productpage service, I can no longer access the reviews service using the host.
The following access will fail.
```
# access reviews by host with any ip
curl -H "host: reviews:9080" 1.1.1.1:9080/reviews/1
```

**Version**
I have tested several recent major versions, and the same issue exists in all of them.

**Reason**
After reading the source code, I found that in the normal case, the protocol-sniffing port for the reviews service will have two listeners: one for clusterip_9080 and another that merges into the 0.0.0.0_9080 listener. However, in the bad case, since the port is not explicitly designated as an HTTP protocol port, the 0.0.0.0_9080 listener does not exist; only the clusterip_9080 listener is present. Therefore, we can no longer route the reviews service using only the host.

I am not sure if this behavior is expected or if it is a bug. However, it is extremely dangerous that deleting one service affects the access to another service. If this is a bug, I would like to attempt to fix it.

@howardjohn @hzxuzhonghu
