### ISSUE TITLE
operation name inconsistent depending on VirtualService configuration

### ISSUE THREAD

**Issue by Stono** [istio/istio#51857]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm not _entirely sure_ this is a bug, as it might just be working as intended (but i can't see the reason) and I'm raising it as confusing from a UX perspective.

I noticed in Jaeger that the `operation` field on requests to `search-one-read` did not match the format of all the others, eg usually its `app.thing.svc.cluster.local:80/*` but for some reason on the `search-one-read` operations it's `name-of-the-virtualservice:80/*`.

![Screenshot 2024-07-02 at 19 35 20](https://github.com/istio/istio/assets/1486729/b62736c5-8089-4bfa-a67e-9e368db35c41)

And in the `config_dump`: 
```
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/search-one-read/virtual-service/search-one-read-app"
            }
           }
          },
          "decorator": {
           "operation": "search-one-read-app:80/*"
          },
```

It's a bit confusing for users who are used to operation being the url (but I'm unsure if that expectation is incorrect?).

The only difference between the `VirtualService` for `search-one-read` and all the other `VirtualServices` is that `search-one-read` has multiple Destinations.

```
spec:
  hosts:
  - app.search-one-read.svc.cluster.local
  - app.search-one-read.preprod.k8.atcloud.io
  - app.search-one-read.bcp.k8.atcloud.io
  http:
  - match:
    - port: 80
    name: default
    retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted
    route:
    - destination:
        host: app.search-one-read.svc.cluster.local
        port:
          number: 80
      weight: 100
    - destination:
        host: app.search-one-read.bcp.k8.atcloud.io
        port:
          number: 443
      headers:
        request:
          add:
            x-forwarded-host: app.search-one-read.svc.cluster.local
            x-forwarded-port: "80"
            x-forwarded-proto: http
          set:
            host: app.search-one-read.bcp.k8.atcloud.io
      weight: 0
    timeout: 5s
```

Whereas one of the others that gives `app.thing.svc.cluster.local:80/*` looks like:
```
spec:
  hosts:
  - app.manufacturer-endorsed-display-service.svc.cluster.local
  - app.manufacturer-endorsed-display-service.preprod.k8.atcloud.io
  http:
  - match:
    - port: 80
    name: default
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted
    route:
    - destination:
        host: app.manufacturer-endorsed-display-service.svc.cluster.local
        port:
          number: 80
      weight: 100
    timeout: 10s
```

### Version

```Text
1.22.2
```
