### ISSUE TITLE
Invalid pod lifecycle with native sidecars

### ISSUE THREAD

**Issue by hamishforbes** [istio/istio#51865]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When Native Sidecars are enabled the Istio injection template adds a default exec preStop on the sidecar container [here](https://github.com/istio/istio/blob/d71c1b62024245e0bd9d905f69e9aa7825ec6720/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L231)

If the user defined pod spec has an httpGet preStop configured the final post-injection pod spec has both the `exec` and `httpGet` fields and is rejected by the kubernetes API preventing the pod from being launched.

e.g.
```
apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
    - name: my-app
      image: "foobar:latest"
    - name: istio-proxy
      image: "auto"
      lifecycle:
        preStop:
          httpGet:
            path: "/foo"
            port: 80
            scheme: HTTP
```

It's a pretty niche scenario but ideally the injector shouldn't generate an invalid pod spec

### Version

```Text
> istioctl version
client version: 1.22.0
control plane version: 1.22.2
data plane version: 1.22.1 (65 proxies), 1.22.2 (43 proxies)
> kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b
```

### Additional Information

Came across this because Knative is adding an httpGet prestop to all containers, i think this is an issue on their side and have opened a bug [there](https://github.com/knative/serving/issues/15367) as well.

**Comment by howardjohn** [comment]
TBH I am not sure this is so wrong. The other options are:

(1) Catch this and give an error (same result but with a better error)
(2) Silently ignore the configured lifecycle

**Comment by hamishforbes** [comment]
I think as a user if I have explicitly configured a custom preStop I would expect that to take precedence over the default

So I think the correct thing to do is if the incoming pod has a preStop already don't add the one from the template at all?

**Comment by howardjohn** [comment]
Hmm. I think with other fields we expect users explicitly `null` out the other fields.

There is not really a good reason to override this. Knative should not modify it, which seems to be the real issue here. Letting knative override it will break Istio semantics.

**Comment by hamishforbes** [comment]
> Hmm. I think with other fields we expect users explicitly `null` out the other fields.

As far as I can tell you can't?
If i try to create a deployment with

```
      lifecycle:
        preStop:
          exec: null
          httpGet:
            path: "/foo"
            port: 80
            scheme: HTTP
```

the exec field just disappears, its not in the deployment any more and so i still end up with the default istio exec preStop and an invalid pod spec

> There is not really a good reason to override this. Knative should not modify it, which seems to be the real issue here. Letting knative override it will break Istio semantics.

I totally agree that Knative should fix their side which will solve my immediate issue.
However anyone who wants (for whatever reason...) to use a custom `httpGet` preStop on their istio sidecar will run into this issue too. It's not specific to Knative

Exec preStops work as expected, if i create this pod then the only preStop configuration in the final pod is my sleep command
```
apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
    - name: my-app
      image: "foobar:latest"
    - name: istio-proxy
      image: "auto"
      lifecycle:
        preStop:
          exec:
            command:
             - /bin/sh
             - -c
             - sleep 10
```

But if i use an httpGet the pod spec is invalid, the pod is never created and (I think) the only workaround is to edit the sidecar template in the istio-sidecar-injector configmap
Which is global and also not very user friendly.

I did try using the strategic merge patch `$patch` directives in the template to try and remove anything else in the preStop map but couldn't get that to work either.

If you're saying that modifying the preStop *at all* from what Istio wants to configure is incorrect and shouldn't be done, then maybe Istio should enforce that by deleting the preStop in the incoming pod spec before templating over it?
