### ISSUE TITLE
ambient: improper handling of duplicate hostnames

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51863]
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: http
spec:
  addresses: [240.240.0.10]
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: http2
spec:
  addresses: [240.240.0.11]
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```

With this config, only `http2` shows up.

Change http2 to `not-httpbin.org`, and the same thing; `http` is lost. Restart istiod fixes this.

This is due to violating `krt` rules and having a non-distinct resourcename: https://github.com/istio/istio/blob/476572cfefdb5ade6bf695466d89050a511289b3/pilot/pkg/model/service.go#L985
