### ISSUE TITLE
Unable to limit the upstream connections from sidecar to app container 

### ISSUE THREAD

**Issue by sakatkoori** [istio/istio#51873]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have below setup, need help in limiting the max upstream connections at 3rd hop

![image](https://github.com/istio/istio/assets/133105384/508d8724-a35c-4dc6-8a60-4976d68cf242)

During HTTP2 flow control or concurrent stream exhaustion, then default behavior is that new connection will open towards app container, this depends on how much max streams configured at app side, in this scenario, we see lot of connections are getting opened towards app container and app is not able to handle those many connections, so, wanted to limit the connections b/w side car to app container.

In attached setup, at 3rd hop, that is between producer and its side car the connections have to restrict, in the given example, 40 connections are being initiated by envoy, and if we want to limit those connections then what exactly the configuration? is it supported? Tried below config as well:

```yaml
apiVersion: [networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)
 kind: EnvoyFilter
 metadata:
 name: set-local-connection-limits
 namespace: default # Replace with your namespace if different
 spec:
 workloadSelector:
   labels:
     app: your-app-label # Replace with your app's label
 configPatches:
 - applyTo: CLUSTER
   match:
     context: SIDECAR_OUTBOUND
     cluster:
       service: your-app-service-name.default.svc.cluster.local # Replace with your local service name
   patch:
     operation: MERGE
     value:
       connect_timeout: 0.25s
       circuit_breakers:
         thresholds:
           - priority: DEFAULT
             max_connections: 100 # Set your max connections limit here
             max_pending_requests: 1000
             max_requests: 1000
             max_retries: 3
       http2_protocol_options:
         max_concurrent_streams: 50 # Set your max concurrent streams limit here
```

### Version

Istio version 1.21 and older versions also

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
