### ISSUE TITLE
Native Sidecar pods not terminating if they never initially became ready

### ISSUE THREAD

**Issue by Stono** [istio/istio#51883]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Grab a coffee whilst you try and digest this...  For starters, I'm not actually convinced this is a bug with Istio, it could well be native Sidecars.  But seeing as it affects the Native Sidecar feature of Istio it felt right to raise it here initially in case others run into it.

Today we had two separate instances of an app deployment failed, because the previous replicas didn't terminate.  When looking at the Pod status we could see that the `istio-proxy` `initContainer` had started, the other `initContainers` had not started, and the pod was in a `deleted` state.

![image](https://github.com/istio/istio/assets/1486729/2908f9f8-5f55-46d2-8838-6999278f57df)

The kubelet logs:
[journalctl.log](https://github.com/user-attachments/files/16086997/journalctl.log) are interesting because they showed that the `istio-proxy` container never became ready:

```
Jul 03 09:34:59 gke-delivery-platform-normal-20240415-5f10739d-si0b kubelet[2835]: I0703 09:34:59.647257    2835 prober.go:107] "Probe failed" probeType="Readiness" pod="vds-kee-importer/vds-kee-importer-97b8f9c47-bgwrc" podUID="c7a48d28-e225-47e7-bc0b-fe4b7f7d06cd" containerName="istio-proxy" probeResult="failure" output="Get \"http://10.198.29.36:15021/healthz/ready\": dial tcp 10.198.29.36:15021: connect: connection refused"
```

And you can also see the pod was deleted just one second after it was created:
```
Jul 03 09:10:44 gke-delivery-platform-normal-20240415-5f10739d-si0b kubelet[2835]: I0703 09:10:44.341732    2835 kubelet.go:2415] "SyncLoop ADD" source="api" pods=["vds-kee-importer/vds-kee-importer-97b8f9c47-bgwrc"]
Jul 03 09:10:45 gke-delivery-platform-normal-20240415-5f10739d-si0b kubelet[2835]: I0703 09:10:45.611314    2835 kubelet.go:2431] "SyncLoop DELETE" source="api" pods=["vds-kee-importer/vds-kee-importer-97b8f9c47-bgwrc"]
```

From this i could infer the sequence of events was:

- Pod scheduled
- istio-proxy starts
- Pod deleted
- istio-proxy never became ready 
- Pod stuck in terminating state

But the next question was why was it stuck Terminating?  What I discovered for the workloads affected was that they had particularly high `terminationGracePeriodSeconds`.  What was happening here is kubernetes was waiting for that container to exit, but it never actually started, and from what i can see from the proxy-logs, **also never got a termination signal**.

This is rather convoluted, but this is how you reproduce it:

- Edit the `ConfigMap` `istio-system/istio-sidecar-injector` and change the `readinessProbe` and `startupProbe` for `istio-proxy` port from `15021` to `15022` (effectively breaking it)
- Have a workload with a high `terminationGracePeriod`
- Delete one of the pods (to trigger a new pod + injection)
- Edit the `ConfigMap` back to `15021`
- Delete the pod that's stuck in the `Init` phase (because its probes aren't passing) and you'll see it will sit in a `Terminating` state indefinitely (well, until `terminationGracePeriodSeconds`). 

I had suspicions that the `preStop` hook added by `istio` to `istio-proxy` to connection drain might be blocking that termination signal so I removed it, and could still recreate the issue.  So that's why it feels a bit kubernetesy. 

We did a mass rollout of all our apps today (750ish), and this happened on 2 of them.  But before moving to sidecar containers, this never happened (in the many years we've been using istio in `containers`).  So it's certainly at least, a "gotcha".  I do not know why the istio-proxy readiness probes started failing in the first place for the original broken deployments, I had to force the failure to reproduce.  My only guess is some sort of race condition between the eventual consistency of the proxies + pilot.

### Version

```Text
1.22.2
```

**Comment by Stono** [comment]
@howardjohn this looks to be an istio problem rather than kubernetes.

Created a noddy Dockerfile with this script:

```
#!/bin/bash
set -e 
trap 'echo "saw an exit signal"; sleep 5; exit' EXIT

while true; do
  echo "hello"
  sleep 1
done
```

Used it in a deployment with a startupProbe that would never pass:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karl-test
  template:
    metadata:
      labels:
        app: karl-test
        sidecar.istio.io/inject: 'false'
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: karl-test-init
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        startupProbe:
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          failureThreshold: 600 
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      containers:
      - name: karl-test
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
```

`kubectl delete` the pod and I _do_ see:

```
k logs karl-test-deployment-76448794cf-z6hdw karl-test-init                       
hello
hello
hello
hello
saw an exit signal
```

My original suspicion was that initContainers that never became ready weren't getting the termination signal.  However it seems they absolutely are, but in this case, istio-proxy isn't acting on it.
