### ISSUE TITLE
AuthorizationPolicy with requestPrincipals not working since upgrade 1.20->1.22

### ISSUE THREAD

**Issue by christianlafleur** [istio/istio#51901]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio 1.20.x Working AuthorizationPolicy/RequestAuthentication config :
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  jwtRules:
  - audiences:
    - api://xyz
    - xyz
    forwardOriginalToken: true
    issuer: https://sts.windows.net/xyz/
    jwksUri: https://login.microsoftonline.com/common/discovery/keys
  - audiences:
    - xyz
    forwardOriginalToken: true
    issuer: https://login.microsoftonline.com/xyz/v2.0
    jwksUri: https://login.microsoftonline.com/common/discovery/v2.0/keys
  selector:
    matchLabels:
      app: httpbin
```
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals:
        - https://sts.windows.net/xyz/*
        - https://login.microsoftonline.com/xyz/*
    to:
    - operation:
        methods:
        - POST
        - PUT
        paths:
        - /v2/transactions*
        - /v2/transactionGroupings*
        - /v1/transactionGrouping*
    when:
    - key: request.auth.claims[roles]
      values:
      - xyz
  - from:
    - source:
        namespaces:
        - workload-ns
    to:
    - operation:
        methods:
        - POST
        - PUT
        - PATCH
        paths:
        - /v2/transactions*
        - /v2/transactionGroupings*
        - /v1/transactionGrouping*
        - /internal/*
  - to:
    - operation:
        paths:
        - /actuator/health
        - /actuator/health/**
        - /metrics
  selector:
    matchLabels:
      app: httpbin
```

After upgrade to 1.22.x requestPrincipals seem not to be recognized and POST fail with 403 : "response_code":403.0,"response_code_details":"rbac_access_denied_matched_policy[none]

We set compatibility mode to 1.20 for 1.22 controlplane.

### Version

```Text
client version: 1.22.2
istiod version: 1.20.5
istiod version: 1.20.5
istiod version: 1.22.2
istiod version: 1.22.2
data plane version: 1.22.2 (3 proxies)

Client Version: v1.28.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b

istio is deployed with kustomize@flux (manifests generated from helm template) including cni
```
