### ISSUE TITLE
Unable adding lifecycle into IstioOperator

### ISSUE THREAD

**Issue by 3-commerce** [istio/istio#51907]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Adding some scenarios of IstioOperator values;

```
values:
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
      istio-ingressgateway-public:
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 200"]
```

or

```
unvalidatedValues:
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway:
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 200"]
              command: [ "/bin/sh","-c","sleep 200" ]
```

or

```
values:
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
    global:
      proxy:
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 200"]
```

I cannot add lifecycle.preStop into ingress gateway through IstioOperator. I believe there is bug of how IstioOperator reading the struct.

### Version

```Text
$ istioctl version
client version: 1.21.2
control plane version: 1.21.2
data plane version: 1.21.2 (2 proxies)

$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```
