### ISSUE TITLE
Some traces generated via istio-proxy are Missing 

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#51991]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Dear Experts,
We enable istio's tracing function with 100% sampling rate. We configured the tracing endpoints to opentelemetry collector's Zipkin receiver. 

In the meanwhile, some of our application also generate traces with Opentelemetry SDK and report traces directly to Opentelemetry collector while it otlp receiver.

The strangest thing:
Traces generated by above application(which supports opentelemetry sdk), or the istio-proxy side-car that run along with those application, can be found in our trace backend(which is now Tempo).

However, if the application doesn't generate traces itself(not using opentelemetry sdk). I expect at least I can find the traces generated via istio-proxy. But I cannot! Which I am not sure where is the root cause.
If check the istio-proxy's accesslog, there is traceID logged(I configured the accesslog to log something like `traceID=%REQ(x-b3-traceid)%` )

I am wondering if there is **any way to check where istio-proxy has reported the traces to the configured endpoints**? So that I can make sure where is the root cause?

### Version

```Text
Istio:
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3

Kubernetes:
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3
```

**Comment by zirain** [comment]
By default, Istio use 1% sampling rate, is that the root cause?

you can check it by running:
```shell
istioctl pc l -n <pod_namespace> <pod_name> --port <the service port you request> -oyaml | grep randomSampling -A1
```

**Comment by suxiaoxiaomm** [comment]
@zirain Thanks for the reply. I just checked and it is 100%.

![image](https://github.com/user-attachments/assets/8ccbc029-534e-44f7-93d3-9ce88c79c6b8)

I found where is the cause:
I put below parameters inside my istiooperator resource to enable the metrics rotation. And this will cause the traces missing.
  ```
values:
    pilot:
      enabled: true
      env:
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
        METRIC_ROTATION_INTERVAL: 10m
```

After I removed this block.  I can see all my traces.

Do you know why could this happen?

Thank you for your help.


Below is my full istiooperator resource:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    pilot:
      enabled: true
      env:
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
        METRIC_ROTATION_INTERVAL: 10m
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    # customized need traceID=%REQ(x-b3-traceid)%
    accessLogFormat: | 
      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)% traceIDParent=%REQ(traceparent)% requestSize=%BYTES_RECEIVED% responseSize=%BYTES_SENT% requestPath=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin: 
          address: "otel-collector.monitoring:9411"
```

**Comment by zirain** [comment]
![image](https://github.com/user-attachments/assets/fa818eed-3a83-4698-8fd3-6c2894a2c290)
this means 1% sample rate.

I don't think METRIC_GRACEFUL_DELETION_INTERVAL or METRIC_GRACEFUL_DELETION_INTERVAL will affect tracing, it only working for `istio.stats` filter.

**Comment by suxiaoxiaomm** [comment]
@zirain It is strange. I am using demo profile, it is by default 100%? right?

**Is my IstioOperator resource file valid below?**
Maybe the block I added about "METRIC_GRACEFUL_DELETION_INTERVAL" and "METRIC_ROTATION_INTERVAL" , overwrite some demo profiles' default configs?

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    pilot:
      enabled: true
      env:
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
        METRIC_ROTATION_INTERVAL: 10m
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    # customized need traceID=%REQ(x-b3-traceid)%
    accessLogFormat: | 
      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)% traceIDParent=%REQ(traceparent)% requestSize=%BYTES_RECEIVED% responseSize=%BYTES_SENT% requestPath=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin: 
          address: "otel-collector.monitoring:9411"
```
