### ISSUE TITLE
200 UPE upstream_reset_after_response_started{protocol_error} in multi-cluster mesh

### ISSUE THREAD

**Issue by Byunk** [istio/istio#52009]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a mesh with multi-cluster in different network. Let's say cluster 1, 2.
We have a client (cluster2), a server (cluster1), and a gateway (cluster2). 
The request flow is client -> gateway (TLS termination) -> (cluster --> cluster1) -> Istio eastwest gateway -> istio-proxy for server -> server.

However, I got `200 UPE upstream_reset_after_response_started{protocol_error}` error from the gateway's access log. And, both `200 UPE upstream_reset_after_response_started{protocol_error}` and `200 DC downstream_remote_disconnect` errors from the istio-proxy for server.

### Version

```Text
$ istioctl version
client version: 1.20.2
control plane version: 1.22.2
data plane version: 1.22.2 (11 proxies)
$ kubectl --context $cluster1 version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
$ kubectl --context $cluster2 version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
$ helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}
```

## Logs

myGateway:

```
[...] "GET ...timeoutSeconds=540&watch=true HTTP/2" 200 UPE upstream_reset_after_response_started{protocol_error} - "-" 0 0 17227 57 "10.244.0.10" "manager/v0.0.0 (linux/amd64) kubernetes/$Format" "6d9239e8-3e34-400f-b8cb-9e8aeac19fc7" ...
```

sidecar proxy of the server:

```
[...] "GET ...timeoutSeconds=540&watch=true HTTP/1.1" 200 UPE upstream_reset_after_response_started{protocol_error} - "-" 0 0 16197 26 "10.244.0.10" "manager/v0.0.0 (linux/amd64) kubernetes/$Format" ...
...
[...] "GET ...timeoutSeconds=594&watch=true HTTP/1.1" 200 DC downstream_remote_disconnect - "-" 0 0 59503 26 "10.244.0.10" "manager/v0.0.0 (linux/amd64) kubernetes/$Format" "f0e2caa1-506d-432c-9973-d0e7b84850c5" ...
```

the server:

If the istio-proxy has the `200 UPE upstream_reset_after_response_started{protocol_error}`, the server doesn't have any log, while it has the following log if the istio-proxy has the `200 DC downstream_remote_disconnect` message.

```
... GET ...timeoutSeconds=543&watch=true 200 OK in 27 milliseconds
```

## Cluster1

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ...
  namespace: ...
spec:
  host: "server"
  subsets:
  - name: cluster1
    labels:
      topology.istio.io/network: network1
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
    hosts:
    - "*.local"
```

## Cluster2

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ...
  namespace: ...
spec:
  hosts:
  - "*"
  gateways:
  - "istio-system/myGateway"
  http:
  - match:
    - port: 6443
    headers:
      request:
        remove:
          - "Authorization"
    route:
    - destination:
        host: "server"
        port:
          number: 6443
        subset: "cluster1"
```

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ...
  namespace: ...
spec:
  host: "server"
  subsets:
  - name: cluster1
    labels:
      topology.istio.io/network: network1
  - name: cluster2
    labels:
      topology.istio.io/network: network2
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ...
  namespace: ...
spec:
  hosts:
  - "*"
  gateways:
  - "istio-system/myGateway"
  http:
  - match:
    - uri:
        regex: ".*/.../.*"
      method:
        exact: GET
    headers:
      request:
        remove:
          - "Authorization"
    rewrite:
      uriRegexRewrite:
        match: "/.../"
        rewrite: "/.../"
    route:
    - destination:
        host: "server"
        subset: "cluster1"
  - match:
    - uri:
        regex: ".*/.../.*"
    headers:
      request:
        remove:
          - "Authorization"
    route:
    - destination:
        host: "server"
        subset: "cluster2"
```

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: myGateway
  namespace: ...
spec:
  selector:
    istio: ...
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 6443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: ...
      privateKey: ...
```

**Comment by zirain** [comment]
for protocol-error please check you port name as https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by Byunk** [comment]
I think it is not just protocol selection error. The server attaches to the following service and it works if the request is not through Istio east-west gateway.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-server
  namespace: my-namespace
  labels:
    service: my-server
spec:
  ports:
  - port: 6443
    name: http
  selector:
    app: my-server
```
