### ISSUE TITLE
503s with routerule change 

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#5204]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

Y

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.7.1
kubectl version: v1.9.6-gke.1
```

**Is Istio Auth enabled or not ?**
No

**What happened**:
Changing routerule causes Istio to briefly returning 503s.  This happens even if all pods were ready for a while.

**What you expected to happen:**
No 503s.

**How to reproduce it:**
I'm using a GKE cluster with Istio 0.7.1 installed.  Using the attached files.

In one shell, run
$ kubectl apply -f initial.yaml
$ curl.sh

Wait until we get 200s from the initial route.

In another shell, run
$ kubectl apply -f updated.yaml

This updates the route, so traffic is routed 100% to new version.

We should see a brief window where 503s is returned, before things go back to normal.

**Feature Request:**
N

**Describe the feature:**
N/A

### Code below can be used for repro

*curl.sh*
```shell
#!/usr/bin/env bash

SERVICE_HOST=""

while [ -z $SERVICE_HOST ]; do
  SERVICE_HOST=$(kubectl get ing ingress -o jsonpath={.spec.rules[0].host} 2>/dev/null)
done
echo "SERVICE_HOST=$SERVICE_HOST"

SERVICE_IP=""

while [ -z $SERVICE_IP ]; do
  export SERVICE_IP=$(kubectl get ing ingress -o jsonpath="{.status.loadBalancer.ingress[*]['ip']}" 2>/dev/null)
done
echo "SERVICE_IP=$SERVICE_IP"

LAST_STATUS="Unknown"
CURRENT_STATUS="Unknown"

while true
do
  CURRENT_STATUS=$(curl -is --header "Host:$SERVICE_HOST" -w "%{http_code}\n" -o /dev/null  http://${SERVICE_IP})
  if [ $CURRENT_STATUS != $LAST_STATUS ]; then
    echo "$(date): ${LAST_STATUS} -> ${CURRENT_STATUS}"
  fi
  LAST_STATUS=$CURRENT_STATUS
done
```

*initial.yaml*
```
# The deployments
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server-one
  name: server-one-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-one
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: server-one
    spec:
      containers:
      - env:
        - name: TARGET
          value: version-one
        image: docker.io/tcnghia/helloworld:latest
        imagePullPolicy: IfNotPresent
        name: webserver
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server-two
  name: server-two-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-two
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: server-two
    spec:
      containers:
      - env:
        - name: TARGET
          value: version-two
        image: docker.io/tcnghia/helloworld:latest
        imagePullPolicy: IfNotPresent
        name: webserver
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
# The services
apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-one
  name: server-one-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: server-one
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-two
  name: server-two-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: server-two
  type: NodePort
status:
  loadBalancer: {}
---
# The ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: repro.com
    http:
      paths:
      - backend:
          serviceName: main-service
          servicePort: http
---
# The route rule
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: routerule
  namespace: default
spec:
  appendHeaders: null
  destination:
    name: main-service
  match:
    request:
      headers:
        authority:
          regex: repro.com
  route:
  - destination:
      name: server-one-service.default
    weight: 100
```

*updated.yaml*
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: routerule
  namespace: default
spec:
  appendHeaders: null
  destination:
    name: main-service
  match:
    request:
      headers:
        authority:
          regex: repro.com
  route:
  - destination:
      name: server-two-service.default
    weight: 100
```

**Comment by tcnghia** [comment]
I also notice that if we change the update to include existing route, but with 0%, we won't see 503s.  In other words, this version of *updated.yaml* will work fine.

*updated.yaml* 
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: routerule
  namespace: default
spec:
  appendHeaders: null
  destination:
    name: main-service
  match:
    request:
      headers:
        authority:
          regex: repro.com
  route:
  - destination:
      name: server-one-service.default
    weight: 0
  - destination:
      name: server-two-service.default
    weight: 100
```
