### ISSUE TITLE
communication with mTLS within two namespaces

### ISSUE THREAD

**Issue by avisaradir** [istio/istio#52043]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have two services in different namespaces let's say team-a and team-b so how can I restrict that only services in team-a can access to services in team-b.

I have been following more than a few documentation files trying to figure out what is the problem but without any success.
I applied this authorization policy but I think the issue is on the side of namespace-a.

when Im running curl -v service.namespace.svc.cluster.local Im getting the following errors

```
without service entry:
* Request completely sent off
* Recv failure: Connection reset by peer
* Closing connection
curl: (56) Recv failure: Connection reset by peer
```

with service entry in getting this error in istio-proxy container in the pod getting the request
```
{
    "downstream_remote_address": "xx.xx.xx.xx:54000", #  this is the curl pods ip (clusterip).
    "downstream_local_address": "172.20.123.123:3000", # this is the service ip (internal)
    "upstream_cluster": "BlackHoleCluster",
    "response_flags": "UH",
 }
```

followed all these documentations, issues and discussions and couldn't find any solution to this bug.
#48413 
https://istio.io/latest/docs/ops/configuration/security/security-policy-examples/#namespace-isolation
https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/
https://istio.io/latest/docs/ops/configuration/security/security-policy-examples/#namespace-isolation
https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source

### Version

```Text
istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1 (278 proxies)

kubectl version 
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b

helm version
v3.13.3+gc8b9489
```

### Additional Information

these are all the configurations I have:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-base-to-istio-system-ip
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - xx.xx.xx.xx/24
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-base-to-istio-system
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - fluent-bit
              - gatekeeper-system
              - istio-system
              - k8s-event-logger
              - keda
              - kube-node-lease
              - kube-public
              - kube-system
              - logstash
              - monitoring
              - velero
              - xray
------------------------------------------------------------------------------------------------------------------------
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: istio-system-sidecar
  namespace: istio-system
spec:
  egress:
    - hosts:
        - ./*
        - istio-system/*
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-system-peer-namespace-communication
  namespace: istio-system
spec:
  mtls:
    mode: PERMISSIVE
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-b-to-a
  namespace: team-a
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-b
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-a-to-b
  namespace: team-b
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-a
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-b-to-b
  namespace: team-b
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-b
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-a-to-a
  namespace: team-a
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-a
------------------------------------------------------------------------------------------------------------------------
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-service-entry-from-team-a-to-b
  namespace: team-a
spec:
  addresses: []
  hosts:
    - "*.team-b.svc.cluster.local"
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 3000
      protocol: TCP
  resolution: NONE
------------------------------------------------------------------------------------------------------------------------
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-service-entry-from-team-b-to-a
  namespace: team-b
spec:
  addresses: []
  hosts:
    - "*.team-a.svc.cluster.local"
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 3000
      protocol: TCP
  resolution: NONE
```
