### ISSUE TITLE
Add env settings in pilot config will set tracing sampling to 1%

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#52047]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Dear Experts,
I am using istiooperator to install my istio system. And I use demo profile. So I expect my tracing sampling rate should be 100%.
At the beginning, it works fine.

But After I input some env settings to setup my pilot component, I found the tracing sampling rate was somehow set to 1%.

Below is my istiooperator yaml file content:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  **values:
    pilot:
      enabled: true
      env:
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
        METRIC_ROTATION_INTERVAL: 10m**
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin: 
          address: "otel-collector.monitoring:9411"
```

If I remove below block, the tracing sampling rate then get back to 100% again.
```
      env:
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
        METRIC_ROTATION_INTERVAL: 10m
```

Could you suggest what is wrong here?

### Version

```Text
istio version:
client version: 1.21.0
control plane version: 1.20.3
data plane version: 1.20.3 (10 proxies)

kuberentes version:
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by zirain** [comment]
https://github.com/istio/istio/issues/51991#issuecomment-2225305745, please kindly don't recreate for same problem.

**Comment by zirain** [comment]
there's should be something wrong with istioctl when merge profile on v1.20, here's the workaround:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  **values:
    pilot:
      enabled: true
      traceSampling: 100 # add this
      env:
        METRIC_GRACEFUL_DELETION_INTERVAL: 5m
        METRIC_ROTATION_INTERVAL: 10m**
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 100 # configure in default config
        zipkin: 
          address: "otel-collector.monitoring:9411"
```
