### ISSUE TITLE
Does wasmplugin oci support aliyun mirror address?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#52041]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Does wasmplugin oci support aliyun image address?

I found that when I used aliyun's image address, istiod reported that get wasm module failed. But I can get my wasm program using the file address. I don't know why? Are there any restrictions here?

My configuration is as follows:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: productpage
  namespace: default
spec:
  selector:
    matchLabels:
      app: productpage
  url: oci://registry.cn-shenzhen.aliyuncs.com/xxxx/wasmpulgin:1.0
  imagePullPolicy: IfNotPresent
```

### Version

```Text
$ istioctl version
client version: 1.14.6
control plane version: 1.13.9
data plane version: 1.13.9 (17 proxies)
```
