### ISSUE TITLE
Multi-Cluster mesh Client Authentication Failure

### ISSUE THREAD

**Issue by Byunk** [istio/istio#52065]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The following error is occurred at every second for multi-primary Istio mesh on different network.

```
2024-07-15T16:32:07.556007Z	error	security	Failed to authenticate client from ...: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster Kubernetes's kube client
```

However, the [verification](https://istio.io/latest/docs/setup/install/multicluster/verify/) is successful.

### Testing Environment

I am using Plug in CA Certificates.

```bash
$ helm upgrade -i istio-base istio/base -n istio-system \
  --set defaultRevision=default
$ helm upgrade -i istiod istio/istiod -n istio-system --wait \
  --set global.meshID=mesh1 \
  --set global.multiCluster.enabled=true \
  --set global.multiCluster.clusterName=$cluster \
  --set global.network=$network
$ helm upgrade -i istio-eastwestgateway istio/gateway -n istio-system \
  --set networkGateway=$network \
  --set "topology.istio.io/network"=$network
$ istioctl create-remote-secret \
  --context="context-1" \
  --name=cluster-1 \
  --namespace istio-system |
kubectl apply -f - --context="context-2"
$ istioctl create-remote-secret \
  --context="context-2" \
  --name=cluster-2 \
  --namespace istio-system \
  --server="$server" |
kubectl apply -f - --context="context-1"
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
    hosts:
    - "*.local"
```

### Version

```Text
$ istioctl version
client version: 1.20.2
control plane version: 1.22.2
data plane version: 1.22.2 (11 proxies)
$ kubectl --context $cluster1 version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
$ kubectl --context $cluster2 version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
$ helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}
```
