### ISSUE TITLE
Local rate limits by path not working

### ISSUE THREAD

**Issue by Anonymous-Coward** [istio/istio#52088]
This is reopening https://github.com/istio/istio/issues/49432 - that ticket was closed as being stale, but we did provide the required feedback in time, we just didn't get any answer from the istio developers.

We use this envoy filter to enable distinct local rate limits by path:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: local-app
spec:
  workloadSelector:
    labels:
      label: some-label
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|80
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_key: path
                headers:
                - name: :path
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            descriptors:
            - entries:
              - key: path
                value: /some/heavy/call
              token_bucket:
                fill_interval: 30s
                max_tokens: 2
                tokens_per_fill: 2
            - entries:
              - key: path
                value: /another/heavy/call
              token_bucket:
                fill_interval: 30s
                max_tokens: 6
                tokens_per_fill: 6
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enabled
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enforced
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 30s
              max_tokens: 10
              tokens_per_fill: 10
```

With it applied, we expect the following number of successful requests per 30s:
- /some/heavy/call - 2 requests per pod
- /another/heavy/call - 6 requests per pod
- any other path: 10 requests per pod

There's also a rate limit of 100 requests per 30s applied to the istio ingress gateway into the cluster (two istio ingress gateway pods each allowing 100 requests per minute amounts to 200 requests per 30s overall).

If I start hammering some path outside of the namespace where the local rate limits envoy filter is applied, I get the 200 requests per 30s I expect answered with `200 OK`, alongside several thousands answered with `429 Too many requests`. If I hammer some path other than the two configured with special limits in the namespace where the envoy filter is applied, I get 20 requests per 30s answered with `200 OK`, and again, several thousands answered with `429 Too many requests` (10 requests for each of the two pods answering them). If I hammer either of the two special paths, instead of getting the small number of requests configured for them answered with `200 OK`, I still get 20 requests per 30s answered with `200 OK`, as if no rate limits by path are applied.

The generic rate limit for the entire namespace specified in the envoy filter _is_ applied, which means the port settings and everything else is correct. Why are the per path rate limits not applied?

Istio was deployed using `istioctl`, not `helm`.

```
$ istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (17 proxies)

$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4

```

**Comment by zirain** [comment]
A working example as following:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: inbound|http|8000
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - header_value_match:
                      descriptor_key: path
                      descriptor_value: ip
                      headers:
                        - name: :path
                          string_match:
                            prefix: /ip
                            ignore_case: true
                  - header_value_match:
                      descriptor_key: path
                      descriptor_value: headers
                      headers:
                        - name: :path
                          string_match:
                            prefix: /headers
                            ignore_case: true
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              descriptors:
                - entries:
                    - key: path
                      value: /ip
                  token_bucket:
                    fill_interval: 30s
                    max_tokens: 2
                    tokens_per_fill: 2
                - entries:
                    - key: path
                      value: /headers
                  token_bucket:
                    fill_interval: 30s
                    max_tokens: 6
                    tokens_per_fill: 6
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              filter_enabled:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enabled
              filter_enforced:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enforced
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              stat_prefix: http_local_rate_limiter
              token_bucket:
                fill_interval: 30s
                max_tokens: 10
                tokens_per_fill: 10
```

**Comment by Anonymous-Coward** [comment]
I will compare the working configuration with mine, do what changes are needed and check again. If it doesn't work, I'll provide my updated configuration and the logs from the istiod and gateway containers.

**Comment by cam634** [comment]
Do you check the config dump to see the rate limit limit is applied? A quick check is checking the [headers](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/common/ratelimit/v3/ratelimit.proto.html#enum-extensions-common-ratelimit-v3-xratelimitheadersrfcversion) to make sure the filter is actually working.
 In my experience rate limit by path does work. 
If you would like to look in the config to see it if exists run [istioctl](https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-dashboard) dashboard <pod> -n <namespace>   and look at the config dump it should show if the buckets exist and on what routes.

**Comment by Anonymous-Coward** [comment]
There is no such command as `istioctl dashboard -n`. If I run:

```
istioctl proxy-config all some-pod-....somens -o json
```

on one of the pods, before and after applying the envoy filter, I do see some changes in the configuration, but no rate limit settings appears anywhere in the after config dump.

I already specified above that I get an error when applying the envoy filter, and attached the error message from the istiod log. How can I overcome that error? I suspect that once istiod is able to apply the envoy filter without errors the local rate limits should work.

**Comment by Anonymous-Coward** [comment]
Pinging this just to avoid it getting closed automatically, and to re-iterate the problem I found.

The problem, it seems, isn't that the envoy filter isn't attempting to set the rate limits correctly, but that istiod encounters an error _after_ the envoy filter was applied without errors, and is unable to set rate limits on the pods in the targeted namespace.

The error message as logged by istiod is attached above.

**Comment by eeelkhan** [comment]
I am using request_headers instead of header_value_match and it works. Tried everything else in vain, example:

`    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - request_headers:
                      header_name: ":path"
                      descriptor_key: path`

**Comment by Anonymous-Coward** [comment]
@eeelkhan I tried with `request_headers` too, but, as I was explaining above, my problem doesn't seem to be caused by whether I use `request_headers` or `header_value_match`, but by the fact that istiod fails to push the configuration to the procies. Please see my comments above.

**Comment by zhihuizhang17** [comment]
Hi, the local rate limit descriptor's token bucket fill interval must be a multiple of the global token bucket's fill interval to avoid envoy exception “local rate descriptor limit is not a multiple of token bucket fill timer”. This means if your global rate limit is set to refill every 10 seconds, then the fill interval for each descriptor must be either 10 seconds or a multiple of 10 seconds (e.g., 10 seconds, 20 seconds, etc.).

**Comment by lusains** [comment]
![image](https://github.com/user-attachments/assets/538bbf60-973f-49ac-a50a-5d53dbedc338)
![image](https://github.com/user-attachments/assets/e9e8cf94-c881-4809-93ca-25d388f646aa)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit-grid-d
  namespace: develop
spec:
  workloadSelector:
    labels:
      app-name: test-service-grid-d
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: inbound|http|8080
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - header_value_match:
                      descriptor_key: path
                      descriptor_value: /actuator/health
                      headers:
                        - name: :path
                          string_match:
                            prefix: /actuator/health
                            ignore_case: true
                  - header_value_match:
                      descriptor_key: path
                      descriptor_value: /misc/ping
                      headers:
                        - name: :path
                          string_match:
                            prefix: /misc/ping
                            ignore_case: true
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              descriptors:
                - entries:
                    - key: path
                      value: /actuator/health
                  token_bucket:
                    max_tokens: 100
                    tokens_per_fill: 100
                    fill_interval: 10s
                - entries:
                    - key: path
                      value: /misc/ping
                  token_bucket:
                    max_tokens: 100
                    tokens_per_fill: 100
                    fill_interval: 10s
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              filter_enabled:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enabled
              filter_enforced:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enforced
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              stat_prefix: http_local_rate_limiter
              token_bucket:
                fill_interval: 10s
                max_tokens: 10
                tokens_per_fill: 10
```
@eeelkhan @Anonymous-Coward  @cam634 The configuration has taken effect on the data plane, but the sub-router's local-rate-limiter seems not work. I want the local-rate-limiter not to limit the health check,Is there a better way?

**Comment by shuang-qin** [comment]
@zirain I created a configuration based on your sample, but it does not work. Could you help on it? thanks!
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
                name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        name: http.8080
        vhost:
          name: "*:80"
          route:
            action: ANY        
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
            - actions:
                - header_value_match:
                    descriptor_key: path
                    descriptor_value: events
                    headers:
                      - name: :path
                        string_match:
                          prefix: /api/v1/events
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: events_api_ratelimit
            descriptors:
                - entries:
                    - key: path
                      value: events
                  token_bucket:
                    fill_interval: 120s
                    max_tokens: 1
                    tokens_per_fill: 1
            filter_enabled:
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              default_value:
                numerator: 100
                denominator: HUNDRED
            response_headers_to_add:
              - append: 
                header:
                  key: Retry-After
                  value: '30'
```
