### ISSUE TITLE
Istio ingress gateway TCP keepalive setting not working for AWS NLB

### ISSUE THREAD

**Issue by pk-hugo** [istio/istio#52143]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We use AWS NLB for our istio ingress gateway. We also have an ALB in front of this NLB. So our setup looks like 

AWS ALB <> AWS NLB <> Istio Ingress Gateway. 

The AWS ALB has connection idle timeout of 60 seconds(configurable). The NLB has a connection idle timeout as 360 seconds(not configurable). 

With this setup we are frequently getting 520 errors to our clients. When we checked our istio gateway logs we see a lot of `0` response code with response code details showing `downstream_remote_disconnect`. 

After going through the below github issues: 
https://github.com/istio/istio/issues/28879
https://github.com/istio/istio/issues/32289

We have tried setting the below envoy filter that sets keep alive probes interval to 120s which less than the NLB interval of 360s. 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-tcp-keepalive-protocol
  namespace: service
spec:
  workloadSelector:
    labels:
      name: istio-ingress
  configPatches:
    - applyTo: LISTENER
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          socket_options:
            - int_value: 1   # (level: 1, name: 9) -> With the above configuration, TCP Keep-Alives can be enabled in socket with Linux, which can be used in listener’s or admin’s socket_options.
              level: 1  # SOL_SOCKET
              name: 9  # SO_KEEPALIVE
              state: STATE_PREBIND
            - int_value: 9  # TCP_KEEPIDLE (level: 6, name: 6) -> Sets the idle time before keepalive probes start to 9 seconds.
              level: 6
              name: 6
              state: STATE_PREBIND  # This indicates that the socket option should be set before the socket is bound to an address.
            - int_value: 120  # TCP_KEEPALIVE (level: 6, name: 4) -> Sets the interval between keepalive probes to 120 seconds.
              level: 6
              name: 4
              state: STATE_PREBIND
            - int_value: 30  # TCP_KEEPINTVL (level: 6, name: 5) -> Sets the time between individual keepalive probes when no response is received to 30 seconds.
              level: 6
              name: 5
              state: STATE_PREBIND
```

We have tried the states `STATE_PREBIND` , `STATE_BOUND`, `STATE_LISTENING` none of which solved our problem. 

I don't think the keep alive probes are passing on to the client. 

### Version

```Text
istio
client version: 1.22.2
control plane version: 1.22.1
data plane version: 1.22.1 (17 proxies)

k8s
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b

helm 
v3.14.4+g81c902a
```
