### ISSUE TITLE
Istio's 1.21 AuthorizationPolicy requestPrincipals aren't processed correctly if JWT contains "/*" in "sub" claim as well as exact match

### ISSUE THREAD

**Issue by antonsukhanov** [istio/istio#52217]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After upgrading from Istio v1.20.4 to v1.21.4, `requestPrincipals` from JWT tokens with `/*` symbols are not processed correctly. As well as exact matches (see below).

Example JWT token (GitHub Actions OIDC):
```json
{
  ...
  "sub": "repo:my-github-org/some-repo:ref:refs/heads/main",
  "iss": "https://token.actions.githubusercontent.com/",
  ...
}
```

`requestPrincipals` match tests:
❌ `https://token.actions.githubusercontent.com/repo:my-github-org/some-repo:ref:refs/heads/main`
❌ `https://token.actions.githubusercontent.com/repo:my-github-org/*`
✅ `https://token.actions.githubusercontent.com/repo:my-github-org*`
✅ `https://token.actions.githubusercontent.com/repo:*`

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  ...
spec:
  jwtRules:
    - forwardOriginalToken: true
      issuer: 'https://token.actions.githubusercontent.com'
      jwksUri: 'https://token.actions.githubusercontent.com/.well-known/jwks'
      outputClaimToHeaders:
        - claim: repository
          header: repository
  selector:
    matchLabels:
      ...
```

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  ...
spec:
  rules:
    - from:
        - source:
            namespaces:
              - istio-gateway
            requestPrincipals:
              - https://token.actions.githubusercontent.com/repo:my-github-org/*
      to:
        - operation:
            paths:
              - /api/*
            ports:
              - '8080'
  selector:
    matchLabels:
      ...
```

### Version

```Text
$ istioctl version
istiod version: 1.20.4
istiod version: 1.21.4
data plane version: 1.20.4 (N proxies), 1.21.4 (N proxies)

$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```
