### ISSUE TITLE
Opentelemetry tracing provider causing prometheus metrics scraping to fail for some services

### ISSUE THREAD

**Issue by jdgeisler** [istio/istio#52237]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We seem to be running into an odd issue with the istio opentelemetry tracing provider. 

For some reason, enabling opentelemetry tracing causes prometheus scrapes to fail with `server returned HTTP status 503 Service Unavailable` when the metric port is using istio protocol selection like below
```
- name: http-metrics
  port: 2023
  protocol: TCP
  targetPort: http-metrics
```
For example, that above port configuration in a service breaks metrics scraping for one our services. If I then change the port to either of these two configurations it works
```
- name: http-metrics
  port: 2023
  protocol: TCP
  targetPort: 2023
- name: metrics
  port: 2023
  protocol: TCP
  targetPort metrics
```
When I then enable the zipkin tracing provider instead, prometheus scraping works again with the regular port names. There are no other changes besides just the telemetry crd type I have deployed.

### Version

```Text
istioctl version
client version: 1.13.4
control plane version: 1.19.7
data plane version: 1.19.7 (43 proxies)

kubectl version --short
Client Version: v1.27.3
Server Version: v1.27.13-eks-3af477
```

### Additional Information

Here is a snippet of our istio configuration. The default tracing config is set to empty and we add the two extension providers for opentelemetry and zipkin.

```
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  tracing: {}
defaultProviders:
  metrics:
  - prometheus
enablePrometheusMerge: true
extensionProviders:
- name: otel-tracing
  opentelemetry:
    port: 4317
    resource_detectors:
      environment: {}
    service: opentelemetry-tracing-agent.istio-system.svc.cluster.local
- name: zipkin-tracing
  zipkin:
    port: 9411
    service: opentelemetry-tracing-agent.istio-system.svc.cluster.local
```
We then deploy the following telemetry crd to set the otel-tracing provider as the mesh default
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: otel-tracing
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
    customTags:
      trace:
        literal:
          value: otel
```
As soon as we do this, the prometheus metrics scraping breaks for services with the aforementioned port configuration.

Then, when we switch to zipkin tracing using this telemetry crd below it starts working again
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: zipkin-tracing
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin-tracing
    randomSamplingPercentage: 100
    customTags:
      trace:
        literal:
          value: zipkin
```
