### ISSUE TITLE
How to get the real client IP from istio?

### ISSUE THREAD

**Issue by jahnavisana2812** [istio/istio#52304]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Setting Up a Web Application Firewall in Kubernetes

We're encountering an issue with retrieving the real client IP from Istio. Instead of the real client IP, Istio exposes the cluster IP range of our cluster.We are exposing our ingress gateway service using Nodeport.

Here are the steps we’ve taken so far:

1. **Setting `externalTrafficPolicy` to `Local`:**
   - This configuration blocked all traffic, preventing access to any site.

2. **Updating the Envoy Filter Configuration:**
   - Set `use_remote_address` to `true` and `xff_num_trusted_hops` to `1`.

3. **Using a Lua Script in the Envoy Filters:**
   - Attempted to extract the real client IP from the `X-Forwarded-For` (XFF) headers, but this approach did not work.

### Envoy Filter Configuration:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-x-real-ip-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              local xff_header = request_handle:headers():get("X-Forwarded-For")
              local first_ip = string.match(xff_header, "([^,]+)")
              if first_ip then
                request_handle:headers():add("X-Custom-User-IP", first_ip)
              end
            end
  workloadSelector:
    labels:
      app: istio-ingressgateway
```

### Request for Suggestions:
Can you please suggest any other ways we can retrieve the real client IP in a clean and effective manner?

### Version

```Text
version 1.22.2
```
