### ISSUE TITLE
Installing DNS Proxy doesn't work with revision labels

### ISSUE THREAD

**Issue by jpenagg** [istio/istio#52307]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We deploy Istio using revision tags. We are currently trying to set up a multi-primary cluster with DNS proxying but the Istio sidecar fails to start since it is expecting a service named `istiod.istio-system.svc` to be present, but since we use revision labels the service is actually named `istiod-1-19-3.istio-system.svc`.

Full error:

```
2024-07-23T18:20:42.923606Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:190	StreamAggregatedResources gRPC config stream to xds-grpc closed since 383s ago: 14, connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc on 172.20.0.10:53: no such host"	thread=15
```

We tried adding in the `discoveryAddress` like so:

```
  meshConfig:
    defaultConfig:
      discoveryAddress: "istiod-1-19-3.istio-system.svc:15012"
      meshId: "dev"
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: true
        ISTIO_META_DNS_AUTO_ALLOCATE: true
```

but `PROXY_CONFIG` ends up being empty. Is there a way I can deploy DNS proxying at the cluster level using Istio revision labels? Is there something that I am missing?

### Version

```Text
istiod-1-19-3
```
