### ISSUE TITLE
`builtin://` causes noisy logs`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52311]
```yaml
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: ingress-gateway
    namespace: istio-ingress
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: tls-443
        number: 443
        protocol: HTTPS
      tls:
        credentialName: builtin://
        mode: SIMPLE
```

causes `failed to parse resource name "default": unknown resource type: default`

I think this is from some of the new k8s gw code
