### ISSUE TITLE
Priority not set when workload entry and service entry are used for discovering local and remote endpoints

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#52342]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have an application which is deployed in us-east-2, and us-west-2. 
There is a client in the same cluster as the application in us-east-2.

We created a ServiceEntry and WorkloadEntry combination so that the client can discover both the remote and the local endpoint of the application.

When we looked at the endpoints of the application in the client proxy, using `istioctl pc endpoints`, we observed, that the application hosts do not show priority. This will result in traffic going to both local and remote region in round robin fashion.

We then looked at the endpoints for the application from istio-ingressgateway in istio-system, and found that it has the priority set correctly.

Question: Why is there a different view of the application between the client application, and istio-ingressgateway?

This is preventing us from using WorkloadEntry/ServiceEntry for discovering both local and remote endpoints.

Service Entry:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test.mesh-se
  namespace: ns1
spec:
  hosts:
  - test.mesh
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS
  workloadSelector:
    labels:
      app: test
```

WorkloadEntry:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: test.mesh
  namespace: ns1
spec:
  address: abc-elb
  locality: us-east-2
  ports:
    http-80: 15443
  labels:
    app: test
```

istioctl pc endpoints in ingressgateway, shows that it has priority:
```yaml
- addedViaApi: true
  hostStatuses:
  - address:
      socketAddress:
        address: xxxxxxxxxxxxxx
        portValue: 15443
    healthStatus:
      edsHealthStatus: HEALTHY
    hostname: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.us-east-2.elb.amazonaws.com.
    locality:
      region: us-east-2
    priority: 0
    weight: 1
  - address:
      socketAddress:
        address: xxxxxxxxxxxxx
        portValue: 8090
    healthStatus:
      edsHealthStatus: HEALTHY
    hostname: xxxxxxxxxxxxx
    locality:
      region: us-west-2
      zone: us-west-2a
    weight: 1
    priority: 1
  name: outbound|8090||test.mesh
  observabilityName: outbound|8090||test.mesh
```

istioctl pc endpoints in namespace other than the application, shows that it doesn't have any priority:
```yaml
- addedViaApi: true
  hostStatuses:
  - address:
      socketAddress:
        address: xxxxxxxxxxxxxx
        portValue: 15443
    healthStatus:
      edsHealthStatus: HEALTHY
    hostname: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.us-east-2.elb.amazonaws.com.
    locality:
      region: us-east-2
    weight: 1
  - address:
      socketAddress:
        address: xxxxxxxxxxxxx
        portValue: 8090
    healthStatus:
      edsHealthStatus: HEALTHY
    hostname: xxxxxxxxxxxxx
    locality:
      region: us-west-2
      zone: us-west-2a
    weight: 1
  name: outbound|8090||test.mesh
  observabilityName: outbound|8090||test.mesh
```

### Version
```Text
client version: 1.20.2
control plane version: 1.20-9108cfa
data plane version: 1.20-9108cfa
```

**Comment by nirvanagit** [comment]
We also observed when we have this locality lb setting on the DR:
```yaml
      localityLbSetting:
        distribute:
        - from: us-west-2/*
          to:
            us-east-2/*: 100
```

The config dump on ingress shows only the east endpoint,

but the config dump on the client application shows both (east and west) and weight as 1, without any priority.
