### ISSUE TITLE
Central Istio Ingressgateway in a multi tenant cluster

### ISSUE THREAD

**Issue by sambitr** [istio/istio#52379]
We use multi-tenant clusters with each tenant running in their own namespace. Everything is locked down with policies, RBAC ect. Currently we deploy an Ingress Gateway in each tenant namespace for them and they then control routing to their pods/services using Virtual Services. There is an app gateway running outside of the clusters which routes traffic to the appropriate tenant ingress using path based routing.

This works fine however it is wasteful having so many ingress gateways. Is there a way that we can create a central Ingress Gateway which routes to the appropriate tenant namespace using path based routing? We would still need the tenants to do additional path based routing within their namespace.

E.g.
Central Ingress gateway /app1/* => some service in app1 namespace
/app1/microservice1 => microservice1 pod/svc in app1 namespace
/app1/microservice2 => microservice2 pod/svc in app1 namespace

We would need to ensure that app2 couldn’t route traffic intended for app1 to their namespace.

**Comment by sambitr** [comment]
any ideas or suggestions will be very helpful for me. Currently we have a multitenant cluster and because of multiple ingress gateways, there are lots of overheads involved in it. We identified a central ingress gateway approach is the right way to manage those overheads. If anyone can help us with valuable suggestions, it will be helpful

**Comment by hzxuzhonghu** [comment]
Super curious, why deploying a controlplane per tenant is wasty?

Comeback to this problem, you can make use of a central gateway for all the services. But this gateway should be charged by a global istio cp, which can discovery all the services/policies across the cluster.

**Comment by sambitr** [comment]
Currently we have multiple applications deployed to our AKS cluster. Each namespace has it's own ingress gateway. On top of that there is application gateway, which does the path based routing. In app gateway, we need to define the LB IP of ingress service, in the backend pool setting, so that traffic gets routed to the appropriate cluster's ingress resource. By having a central ingress gateway, it will help in reducing the usage of IP addresses. 

Also, we will have one central place to update all the ingress changes, rather than doing it across namespaces. Being said that, I understand there is RBAC thing we need to take care.

**Comment by nicole-lihui** [comment]
(💭 a brainstorming idea)
Your requirements seem to be twofold:

1. a central gateway entry point and then maintain complex gateway routes to each tenant's API configuration.
2. Namespace isolation between each tenant.

**point 1**  I thought of **Delegate** nesting:


**point 2** I thought of **Sidecar**  +  Register_only Mode

**Comment by sambitr** [comment]
Hi All, got some time today to go through everything and I think here is what should work. Obviously it needs to be tested on the cluster

First Part: istio-system
1. Define central istio-ingressgateway in istio-system namespace
2. Create delegate virtual service that would route traffic to the respective virtualservices in the tenant namespaces

Second Part: tenant namespace
1. Modify the existing virtualservice and gateway to use central ingressgateway in istio-system, rather than ingress gateway defined in tenant namespace
2. Add ingress spec to sidecar configuration
3. Add/update authorization policy to DENY connection from other application namespaces


Combination of option 3 & 4 will make sure app1 n in one namespace could not route traffic intended for that namespace to other namespace and vice versa

app2 couldn’t route traffic intended for app1 to their namespace.

**Comment by nicole-lihui** [comment]
Look forward to the results of your experiment

**Comment by sambitr** [comment]
Hi @nicole-lihui & @hzxuzhonghu need your help on one thing:

We need the rewrite option to work from delegate VS, so that after rewriting the path, it should delegate to the tenant Virtual service. Right now, the rewrite option is not working in delegate VS. Is there a way we can achieve it?

First option is working perfectly without any issues and I can see traffic flowing from central ingregateway to the application deployed in tenant namesapce. 

But the second option where I am trying to use rewrite, it is not working. Is there a way we can route it?

spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - '*'
  http:
  - delegate:
      name: nginx-vs
      namespace: demo
    match:
    - uri:
        prefix: /nginx
  **- delegate:
      name: nginx-vs-new
      namespace: demo
    match:
    - uri:
        prefix: /override/nginx
    rewrite:
      uri: /nginx**

**Comment by nicole-lihui** [comment]
'trying to use rewrite, it is not working'? How do you define vs and what does not work mean?

**Comment by sambitr** [comment]
This is the delegate virtual service:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: delegate-virtualservice
  namespace: istio-system
spec:
  hosts:
  - '*'
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: "/upgrade/nginx"
    rewrite:
        uri: "/nginx"
    delegate:
       name: nginx-vs-new
       namespace: demo 
```
 
This is the virtual service defined in tenant namespace:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs-new
  namespace: demo
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway  # Use the ingress gateway in the istio-system namespace
  http:
  - match:
    - uri:
        prefix: "/nginx"  # Route traffic with the path /nginx to this service, after doing rewrite from delegate VS
    route:
    - destination:
        host: nginx-service-new.demo.svc.cluster.local
        port:
          number: 80
```

This causes 404 route_not_found error in istio-ingressgateway log.

But it works, when in delegate VS, I have below with no rewrite in delegate VS, forwarding the traffic as it is and then doing rewriting in tenant VS. I think delegate VS's job is ONLY to delegate traffic and not to do any modifications on it before delegateing:

```
spec:
  hosts:
  - '*'
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: "/upgrade/nginx"
    delegate:
       name: nginx-vs-new
       namespace: demo 
```

And in tenant VS, I have:

```
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway  
  http:
  - match:
    - uri:
        prefix:"/upgrade/nginx"  # Route traffic with the path match with delegate VS and then rewrite 
    rewrite:
       uri: "/nginx"
    route:
    - destination:
        host: nginx-service-new.demo.svc.cluster.local
        port:
          number: 80
```

**Comment by nicole-lihui** [comment]
The sense of usage is problematic, and I'll give you an example

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-parent-vs
  namespace: default
spec:
  hosts:
  - '*'
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: "/upgrade/nginx"
    rewrite:
        uri: "/nginx"    ##trying to forward/delegate traffic after rewriting the prefix
    delegate:
       name: delegate-sub-vs
       namespace: demo 
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: delegate-sub-vs
  namespace: demo
spec:
  http:
  - match:
    - uri:
        prefix: "/upgrade/nginx"
    rewrite:
        uri: "/nginx"   
    route:
    - destination:
        host: nginx-service-new.demo.svc.cluster.local
        port:
          number: 80

```
delegate-sub-vs host& gateway is empty

![image](https://github.com/user-attachments/assets/4390b2ec-4267-4a74-a9e4-7b29e3188bf6)

**Comment by sambitr** [comment]
@nicole-lihui ok. I re read the documentation and see that the tenant namespace's VS does not have host and gateway component. But I think this is not taken in to consideration while routing traffic, even if it is present.

Also, the screenshot explains what I was thinking. The HTTPMatchRequest should match exactly as declared in delegate VS. That's why the traffic was not routing. Basically, delegate VS does not take rewrite into consideration.

I will give it a try with out specifying host and gateway in tenant VS and let you know

**Comment by sambitr** [comment]
Hi @nicole-lihui I am hitting one more hurdle. This is for custom domains. Some apps use custom domains and from Azure app gateway I can manage the traffic routing by appending override of /vatchecker/ in it.

In below spec, the users will hit the custom domain like: https://appname.com. But app GW will send the traffic to ingress as https://appname.com  --> https://appname.com/vatchecker/
https://appname.com/api --> https://appname.com/vatchecker/api

I am handling that scenario as below in delegate virtualservice

```
spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - '*'
  http:
  - delegate:
      name: nginx-vs
      namespace: demo
    match:
    - uri:
        prefix: /vatchecker/api
  - delegate:
      name: nginx-vs-test
      namespace: demo
    match:
    - uri:
        prefix: /vatchecker/
```

The above one works fine. But as soon as I change the order, all the traffic goes to the virtualservice marked with prefix: /vatchecker/

Is there anyway, we can handle it?


```
spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - '*'
  http:
  - delegate:
      name: nginx-vs-test
      namespace: demo
    match:
    - uri:
        prefix: /vatchecker/
  - delegate:
      name: nginx-vs
      namespace: demo
    match:
    - uri:
        prefix: /vatchecker/api
```
