### ISSUE TITLE
Local ratelimit not working as expected

### ISSUE THREAD

**Issue by jwillker** [istio/istio#52385]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm following the Istio docs about how to apply local ratelimit: https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#local-rate-limit

I have created some EnvoyFilters for a lot of applications, but they have not been enforced, just to capture the metrics and analyze if the quotas are right. But for some applications seems right and for others not. My desire is to create a rate limit by pod based on the max request count by pod, so I analyze the RPS by pod of the application and add this max number as the max token of the ratelimit. But sometimes, the application faces a rate limit of half of the max tokens.

Example of a EnvoyFilter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lrlimit-my-application
  namespace: my-application
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: local_rate_limit_enabled
            request_headers_to_add_when_not_enforced:
            - append: false
              header:
                key: x-ifood-local-rate-limit
                value: "true"
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 1s
              max_tokens: 140
              tokens_per_fill: 140
  workloadSelector:
    labels:
      app: my-application
```

my-application metrics: (429 don't have metrics because the filter is not enforced)

Envoy metrics from local ratelimit filters:

![image](https://github.com/user-attachments/assets/fea733b5-0081-4249-aff5-712304cb604c)

Istio requests count:
![image](https://github.com/user-attachments/assets/96ef8347-2c3b-46b4-9413-b40d4f5c336e)

Based on that, we can see the maximum RPS is 90, and the max token is 140, with 140 tokens per fill and an interval of 1s.
We have cases where this doesn't happen, the rate limit only occurs when the RPS is almost the maximum number of tokens and that's exactly what I want, but sometimes this doesn't work and I don't know why.

I have some apps with HTTP and others with GRPC traffic, but I have problems with both protocols.

Is this expected? 
Does the config of token_bucket correspond to my desire?

### Version

```Text
$ istioctl version
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (1353 proxies)

$kubectl version --short
Client Version: v1.27.13
Kustomize Version: v5.0.1
Server Version: v1.27.13
```
