### ISSUE TITLE
Doing HBONE to backend prevents setting other TLS methods

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52396]
Example:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
spec:
  parentRefs:
  - name: gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - name: echo
      port: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: echo
spec:
  host: echo.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
```

This will not send TLS to the backend like they want.

We fixed this for waypoints in https://github.com/istio/istio/pull/51085, now needed in sidecars/ingressgw
