### ISSUE TITLE
External service connection reset

### ISSUE THREAD

**Issue by janekmichalik** [istio/istio#52403]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Environment details:
- mTLS STRICT mode
- meshConfig.outboundTrafficPolicy.mode set to REGISTRY_ONLY

I am unable to access https://google.com from within the application pod that has an Istio-proxy sidecar, even though the service entry is correctly defined and the documentation has been followed

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: google-com
  namespace: test
spec:
  hosts:
  - google.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```

```
non-root@test-8955d6fdc-xz9kb:/source$ curl -I https://google.com
curl: (35) Recv failure: Connection reset by peer
```

without above service entry, I got:
```
non-root@test-8955d6fdc-xz9kb:/source$ curl -I https://google.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443
```

This behavior is expected according to the Istio documentation. However, the service entry is supposed to allow the connection, but it is still being blocked. Everything works correctly when meshConfig.outboundTrafficPolicy.mode is set to ALLOW_ANY.

Is there something missing from the documentation, or am I doing something wrong? Please help me understand the issue.

### Version

```Text
istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (45 proxies)

kubectl version
Client Version: v1.29.3+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3+k3s1
```

### Additional Information

I have changed mTLS mode to PERMISSIVE, but still the same error.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
using `istioctl pc cluster -oyaml` to dump the `outbound|443||google.com`

**Comment by janekmichalik** [comment]
@hzxuzhonghu 

```
- circuitBreakers:
    thresholds:
    - maxConnections: 4294967295
      maxPendingRequests: 4294967295
      maxRequests: 4294967295
      maxRetries: 4294967295
      trackRemaining: true
  commonLbConfig:
    localityWeightedLbConfig: {}
  connectTimeout: 10s
  dnsLookupFamily: V4_ONLY
  dnsRefreshRate: 60s
  filters:
  - name: istio.metadata_exchange
    typedConfig:
      '@type': type.googleapis.com/udpa.type.v1.TypedStruct
      typeUrl: type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
      value:
        enable_discovery: true
        protocol: istio-peer-exchange
  lbPolicy: LEAST_REQUEST
  loadAssignment:
    clusterName: outbound|443||google.com
    endpoints:
    - lbEndpoints:
      - endpoint:
          address:
            socketAddress:
              address: google.com
              portValue: 443
        loadBalancingWeight: 1
        metadata:
          filterMetadata:
            istio:
              workload: ;;;;
      loadBalancingWeight: 1
      locality: {}
  metadata:
    filterMetadata:
      istio:
        external: true
        services:
        - host: google.com
          name: google.com
          namespace: default
  name: outbound|443||google.com
  respectDnsTtl: true
  type: STRICT_DNS
```
