### ISSUE TITLE
istioctl analyze shouldn't report IST0145 for wildcard host and specific subdomain

### ISSUE THREAD

**Issue by Unichron** [istio/istio#52413]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

istioctl analyze reports IST0145 for gateways when one contains a wildcard host (e.g. *.example.com) and the other a specific subdomain (e.g. foo.example.com). The config works just fine as expected though.

Example config
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-wildcard
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.example.com'
      port:
        name: example-wildcard
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-subdomain
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - 'foo.example.com'
      port:
        name: example-subdomain
        number: 80
        protocol: HTTP
```

istioctl analyze output
```
Error [IST0145] (Gateway istio-system/example-subdomain) Conflict with gateways istio-system/example-wildcard (workload selector istio=ingressgateway, port 80, hosts foo.example.com).
Error [IST0145] (Gateway istio-system/example-wildcard) Conflict with gateways istio-system/example-subdomain (workload selector istio=ingressgateway, port 80, hosts *.example.com).
```

### Version

```Text
client version: 1.22.2
control plane version: 1.21.2
data plane version: 1.21.2 (94 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
