### ISSUE TITLE
How outlierDectection works in multi cluster 

### ISSUE THREAD

**Issue by stefan-marc** [istio/istio#52435]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

Not sure if this is a real issue or if this is how it was designed to work.

I have Istio installed in a Multi-Primary setup running on different networks with two GKE clusters, called `gke1` and `gke2`.

On `gke2`, I have the server application composed out of 2 deployments, `server-app-canary` and `server-app-stable`, scaled between 5 to 50 pods. These deployments are exposed through the same service called lb. I have a DR and VS as shown below:
```
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: lb
  namespace: server-app
spec:
  exportTo:
  - .
  - istio-system
  - client-app
  host: lb.server-app.svc.cluster.local
  subsets:
  - labels:
      app: server-app
      partition: stable
    name: stable
  - labels:
      app: server-app
      partition: canary
    name: canary
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: DEFAULT
        http1MaxPendingRequests: 5000
        http2MaxRequests: 5000
        idleTimeout: 30s
        maxRequestsPerConnection: 0
        maxRetries: 3
        useClientProtocol: false
      tcp:
        connectTimeout: 10s
        maxConnections: 100000
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutiveGatewayErrors: 0
      consecutive5xxErrors: 2 <--- to emphasise my point
      interval: 5m
      baseEjectionTime: 1m
      maxEjectionPercent: 10
      minHealthPercent: 0
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lb
  namespace: server-app
spec:
  exportTo:
  - .
  - client-app
  hosts:
  - lb.server-app.svc.cluster.local
  http:
  - match:
    - ignoreUriCase: true
      uri:
        prefix: /
    retries:
      attempts: 3
      perTryTimeout: 32s
      retryOn: connect-failure,reset
    route:
    - destination:
        host: lb.server-app.svc.cluster.local
        port:
          number: 80
        subset: stable
      weight: 80
    - destination:
        host: lb.server-app.svc.cluster.local
        port:
          number: 80
        subset: canary
      weight: 20
    timeout: 30s
```
The exact same objects (DR+VS) I have deployed in the `server-app` namespace of gke1.
The `client-app` is deployed on `gke1` in it's own namespace and is calling the `server-app`

Looking at the  `proxy-config endpoints` we see that the next hop to reach `server-app` is the east-west gateway of cluster `gke2`. Which is to be expected.
```
❯ istioctl proxy-config endpoints client-app-7895bfdfb6-fcf6c.client-app | grep server-app
10.91.33.56:15443                                       HEALTHY     OK                outbound|80|canary|lb.server-app.svc.cluster.local
10.91.33.56:15443                                       HEALTHY     OK                outbound|80|stable|lb.server-app.svc.cluster.local
10.91.33.56:15443                                       HEALTHY     OK                outbound|80||lb.server-app.svc.cluster.local
```

However, what I've noticed during my testing is that if I trigger 2 * 500 errors from a one of the client pods I start getting 503 errors

```
root@client-app-7895bfdfb6-f8vrj:/# curl -v -H "x-set-response-status-code: 500" http://lb.server-app/
* Host lb.server-app:80 was resolved.
* IPv6: (none)
* IPv4: 10.91.33.215
*   Trying 10.91.33.215:80...
* Connected to lb.server-app (10.91.33.215) port 80
> GET / HTTP/1.1
> Host: lb.server-app
> User-Agent: curl/8.5.0
> Accept: */*
> x-set-response-status-code: 500
>
< HTTP/1.1 500 Internal Server Error
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 955
< etag: W/"3bb-oQg/s+5ag/QV2ON6ergm/K+g1YI"
< date: Wed, 31 Jul 2024 08:13:45 GMT
< x-envoy-upstream-service-time: 19
< server: envoy
<
{
  "path": "/",
  "headers": {
    "host": "lb.server-app",
    "user-agent": "curl/8.5.0",
    "accept": "*/*",
    "x-set-response-status-code": "500",
    "x-forwarded-proto": "http",
    "x-request-id": "914dc88e-8f17-489d-88ad-a9ba56128798",
    "x-envoy-attempt-count": "1",
    "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/server-app/sa/default;Hash=dd2962210b1e37cdbaf8cb384a2b9d8d7d6228bd1246eac23ddf6ad5eeeed190;Subject=\"\";URI=spiffe://cluster.local/ns/client-app/sa/default",
    "x-b3-traceid": "c3181d343bab56e1b985e667ec0ad8ff",
    "x-b3-spanid": "0f7cbc1b098a0020",
    "x-b3-parentspanid": "b985e667ec0ad8ff",
    "x-b3-sampled": "0"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "lb.server-app",
  "ip": "::ffff:127.0.0.6",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "server-app-stable-695896998c-6dsgn"
  },
  "connection": {}
* Connection #0 to host lb.server-app left intact
}root@client-app-7895bfdfb6-f8vrj:/# curl -v -H "x-set-response-status-code: 500" http://lb.server-app/
* Host lb.server-app:80 was resolved.
* IPv6: (none)
* IPv4: 10.91.33.215
*   Trying 10.91.33.215:80...
* Connected to lb.server-app (10.91.33.215) port 80
> GET / HTTP/1.1
> Host: lb.server-app
> User-Agent: curl/8.5.0
> Accept: */*
> x-set-response-status-code: 500
>
< HTTP/1.1 500 Internal Server Error
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 955
< etag: W/"3bb-OxVJz0hncdeXaTIU9CSg0x0VQNE"
< date: Wed, 31 Jul 2024 08:13:47 GMT
< x-envoy-upstream-service-time: 21
< server: envoy
<
{
  "path": "/",
  "headers": {
    "host": "lb.server-app",
    "user-agent": "curl/8.5.0",
    "accept": "*/*",
    "x-set-response-status-code": "500",
    "x-forwarded-proto": "http",
    "x-request-id": "1dcf45be-1cc1-427e-87ef-1517e160587b",
    "x-envoy-attempt-count": "1",
    "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/server-app/sa/default;Hash=dd2962210b1e37cdbaf8cb384a2b9d8d7d6228bd1246eac23ddf6ad5eeeed190;Subject=\"\";URI=spiffe://cluster.local/ns/client-app/sa/default",
    "x-b3-traceid": "eb3bec1f83f04d0410b7609d2759448e",
    "x-b3-spanid": "2da6ea55a158d6ec",
    "x-b3-parentspanid": "10b7609d2759448e",
    "x-b3-sampled": "0"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "lb.server-app",
  "ip": "::ffff:127.0.0.6",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "server-app-stable-695896998c-45krs"
  },
  "connection": {}
* Connection #0 to host lb.server-app left intact
}root@client-app-7895bfdfb6-f8vrj:/# curl -v -H "x-set-response-status-code: 500" http://lb.server-app/
* Host lb.server-app:80 was resolved.
* IPv6: (none)
* IPv4: 10.91.33.215
*   Trying 10.91.33.215:80...
* Connected to lb.server-app (10.91.33.215) port 80
> GET / HTTP/1.1
> Host: lb.server-app
> User-Agent: curl/8.5.0
> Accept: */*
> x-set-response-status-code: 500
>
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Wed, 31 Jul 2024 08:13:48 GMT
< server: envoy
<
* Connection #0 to host lb.server-app left intact

❯ istioctl proxy-config endpoints client-app-7895bfdfb6-f8vrj.client-app | grep server-app
10.91.33.56:15443                                       HEALTHY     OK                outbound|80|canary|lb.server-app.svc.cluster.local
10.91.33.56:15443                                       HEALTHY     FAILED            outbound|80|stable|lb.server-app.svc.cluster.local
10.91.33.56:15443                                       HEALTHY     OK                outbound|80||lb.server-app.svc.cluster.local
```

So to clarify. After 2 consecutive 500 errors the outlierDetection triggers and the east-west gw is removed, even though there are more than 5 pods that could answer the request behind the gw. Is this expected? If the client would've reside in the `gke2` cluster, the outlierDectection would've require much more effort to trigger.

Now based on all this information, is this how it should be working? Shouldn't the `client-app` in `gke1` treat the outlierDetection the same way as if it would be running in `gke2`, where the `server-app` is located?

Does my question make sense?

Thanks!

### Version

```Text
❯ istioctl version
client version: 1.21.2
control plane version: 1.19.4
data plane version: 1.19.4 (16 proxies)

❯ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.14-gke.1042001
```

**Comment by kebe7jun** [comment]
Yes, from the perspective of the client's Envoy, stable lb only has one endpoint, even though it actually corresponds to 50 Pods. This is what the traffic will look like if it passes through the eastwest gw. You can try adding a few more IPs/ports. .

**Comment by stefan-marc** [comment]
Hi @kebe7jun, thanks for your comment. What do you mean by, "You can try adding a few more IPs/ports."?

**Comment by kebe7jun** [comment]
I mean, you can configure more addresses for this east-west gw, such as 1.1.1.1:15443,1.1.1.1:15444, but they all addresses to one east-west gateway. This mitigates the risk of the entire service becoming unavailable due to one of the Endpoints being marked as unhealthy.

**Comment by stefan-marc** [comment]
That sounds interesting! I guess you mean something like this?
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: east-west-gateway
spec:
  hosts:
  - "istio-eastwestgateway.istio-system.svc.cluster.local"
  addresses:
  - 1.1.1.1
  - 2.2.2.2
  ports:
  - number: 15443
    name: http-port1
    protocol: HTTP
  - number: 15444
    name: http-port2
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: "1.1.1.1"
    ports:
      http-port1: 15443
      http-port2: 15444
  - address: "2.2.2.2"
    ports:
      http-port1: 15443
      http-port2: 15444
```
Or how exactly?
