### ISSUE TITLE
How does Istio track the time taken to process specific API requests?

### ISSUE THREAD

**Issue by Cairry** [istio/istio#52486]
Version: istio/pilot:1.14.0

Require:
I want to use Istio to track the specific API request processing time, so that I can clearly know which APIs take a long time, which will have certain benefits for the stability of our system. Can Istio realize my demand analysis?

Thank you!

**Comment by zirain** [comment]
I cannot recall there's something like that, but https://medium.com/airbnb-engineering/improving-istio-propagation-delay-d4da9b5b9f90 will give you a little help.

**Comment by AleksanderBrzozowski** [comment]
Aren't we talking about proper usage of `istio_request_duration_milliseconds ` [metric](https://istio.io/latest/docs/reference/config/metrics/#metrics)?

I guess that you can also use tracing to find requests that take longer than X seconds.

The question is the level of granularity that you want to have - with metrics, you can get this per service basis, but without any information of HTTP path, or method.

With traces, though, you can get more details - like HTTP attributes, and so on.

Can you describe your use case in more detail?

**Comment by Cairry** [comment]
For example, I want to count the processing time of all API requests and display it on a dashboard. Is this feasible?

<img width="767" alt="image" src="https://github.com/user-attachments/assets/d6d3d1a2-1fff-40d5-a891-745928d6bb88">

**Comment by AleksanderBrzozowski** [comment]
Yeah, it should be possible. However, I am not sure if Istio allows to get metrics per HTTP path.

I guess that you would need to use VirtualService, and name every route (?), and then use [route components](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html) to have metrics per path.

I am not sure if there is an easier way to do this in Istio, maybe someone else can help :)

**Comment by zirain** [comment]
if you're talking about this, Telemetry API allow to put path on label/tag, see https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/#classify-metrics-by-request.

Be careful when you're using a restful style API.

**Comment by AleksanderBrzozowski** [comment]
It might be also possible to use proper CEL expressions inside tag override in the Telemetry resource.

This might be helpful to avoid additional WASM plugin.

**Comment by keithmattix** [comment]
Also there's been a lot of updates in this are recently. 1.14 is also no longer supported. Please upgrade

**Comment by Cairry** [comment]
I referred to the "Policy to add dimensions to all Prometheus metrics for the foo namespace" in "https://istio.io/latest/docs/reference/config/telemetry/#examples" to add request_url and request_route dimensions to the metric, but the final effect was not ideal. The dimensions I added could not be found in the istio_requests_total metric. Why is this? Does any expert know? Please help me, thank you.

Telemetry example
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: namespace-metrics
  namespace: ztest
spec:
  # no selector specified, applies to all workloads in the namespace
  metrics:
  - providers:
    - name: prometheus
    overrides:
    # match clause left off matches all istio metrics, client and server
    - tagOverrides:
        request_method:
          value: "request.method"
        request_host:
          value: "request.host"
        request_route:
          value: "request.route"
        request_url:
          value: "request.url"
```

**Comment by zirain** [comment]
please try with latest/supported version, Istio move to native cpp filter, which also remove dependence with `extraStatTags`.

**Comment by Cairry** [comment]
Updating the version is difficult for us. Is there any other way to solve this problem?

I tried changing the indicator in other ways, but I ran into another problem.

EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-url-filter
  namespace: ztest
spec:
  workloadSelector:
    labels:
      app: node-service
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.14.*'
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "istio.stats"
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.attributegen
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: https://js-design-ops.oss-cn-beijing.aliyuncs.com/ops/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
          value:
            config:
              configuration:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "attributes": [
                      {
                        "output_attribute": "istio_url_path",
                        "match": [
                          {
                            "value": "ready",
                            "condition": "request.url_path == '/healthz/ready'"
                          }
                        ]
                      }
                    ]
                  }
              vm_config:
                runtime: envoy.wasm.runtime.null
                code:
                  local: { inline_string: "envoy.wasm.attributegen" }
```

stats-filter-1.14.yaml
```
{
                    "debug": "false",
                    "stat_prefix": "istio",
                    "disable_host_header_fallback": true,
                    "metrics": [
                      {
                        "dimensions": {
                          "destination_cluster": "node.metadata['CLUSTER_ID']",
                          "source_cluster": "downstream_peer.cluster_id"
                        }
                      },
                      {
                        "name": "requests_total",
                        "dimensions": {
                          "request_url_path": "istio_url_path"
                        }
                      }
                    ]
                  }
```

Unexpected conclusions:
I understand that it should add a new label, why does it modify the metric name?

Change before: `istio_requests_total`
Change After`request_url_path___unknown___istio_requests_total`

```
request_url_path___unknown___istio_requests_total{response_code="200",reporter="destination",source_workload="gateway",source_workload_namespace="ztest",source_principal="spiffe://cluster.local/ns/ztest/sa/default",source_app="gateway",source_version="default",source_cluster="Kubernetes",destination_workload="node-service",destination_workload_namespace="ztest",destination_principal="spiffe://cluster.local/ns/ztest/sa/default",destination_app="node-service",destination_version="default",destination_service="node-service.ztest.svc.cluster.local",destination_service_name="node-service",destination_service_namespace="ztest",destination_cluster="Kubernetes",request_protocol="http",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="gateway",destination_canonical_service="node-service",source_canonical_revision="default",destination_canonical_revision="default"} 5
```

Should be: `istio_requests_total{request_url_path:'xxx'}`
