### ISSUE TITLE
Expose "allow_requests_without_proxy_protocol" property under gatewayTopology.proxyProtocol

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [istio/istio#52490]
**Describe the feature request**

Currently, Istio allows to enable proxy protocol by using `gatewayTopolocy.proxyProtocol` config, see the guide - https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#proxy-protocol.

However, it is impossible to customize Envoy's Proxy Protocol filter. As a result, we end up with a default values for the [Proxy Protocol Envoy Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol).

Basically, once the proxy protocol is enabled, Envoy will start to reject connections that are not using Proxy Protocol:

> If the filter is enabled, the Proxy Protocol must be present on the connection (either version 1 or version 2). The standard does not allow parsing to determine if it is present or not. However, the filter can be configured to allow the connection to be accepted without the Proxy Protocol header (against the standard). See [allow_requests_without_proxy_protocol](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto#envoy-v3-api-field-extensions-filters-listener-proxy-protocol-v3-proxyprotocol-allow-requests-without-proxy-protocol).

The problem that we are facing is that we currently use AWS NLB (Network Load Balancer) with disabled Proxy Protocol. It is impossible to enable Proxy Protocol in AWS NLB, and at the same time enable Envoy Filter. Therefore, we would like to first add Envoy Filter with `allow_requests_without_proxy_protocol` set to `false`, then modify AWS NLB to enable Proxy Protocol, and eventually disable `allow_requests_without_proxy_protocol`. 

This isn't possible by the existing configuration of `proxyProtocol` object. So, my proposal is to add a new property, `allow_requests_without_proxy_protocol` to the `proxyProtocol` object that will control the behavior of the same property from Envoy Proxy Protocol Filter.

**Describe alternatives you've considered**

The alternative which should work is to use the `EnvoyFilter` resource instead of `proxyProtocol` config property.

However, since we already have the `proxyProtocol` config, it would be nice to add this property.

Adding this property will allow existing ingresses to migrate to the Proxy Protocol without any downtime.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Make sense, this is a reasonable requirement

**Comment by alita-moore** [comment]
to apply this behavior using envoy filters use the following:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: proxy_protocol
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"
            allow_requests_without_proxy_protocol: true
        - name: tls_inspector
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
  workloadSelector:
    labels:
      istio: ingressgateway
```
[source](https://discuss.istio.io/t/preserve-source-ip-of-external-tcp-service-proxy-protocol/14712)
