### ISSUE TITLE
Unable to connect to TLS services outside the cluster

### ISSUE THREAD

**Issue by upodroid** [istio/istio#52503]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have the following configuration.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: borg-prod
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-borg
      protocol: HTTP
    hosts:
    - '*.borg.dev'
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-443-borg
      protocol: HTTPS
    hosts:  
    - '*.borg.dev'
    tls:
      mode: SIMPLE 
      credentialName: borg-wild-cert
      minProtocolVersion: TLSV1_2
      maxProtocolVersion: TLSV1_3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: hassio
  name: hassio
  namespace: default
spec:
  hosts:
    - home.borg.dev
  gateways:
  - istio-system/borg-prod
  http:
  - route:
    - destination:
        host: hassio
        port:
          number: 8123
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-hassio
  namespace: default
spec:
  host: hassio
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 8123
      tls:
        mode: SIMPLE
---
apiVersion: v1
kind: Service
metadata:
  name: hassio
  namespace: default
spec:
  ports:
  - port: 8123
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hassio
  namespace: default
subsets:
- addresses:
  - ip: 10.150.8.20
  ports:
  - port: 8123
    protocol: TCP
```

This used to work at Istio 1.15 and older but now I'm getting the following errors.

```
[2024-08-03T23:32:20.960Z] "GET / HTTP/2" 503 URX,UF upstream_reset_before_response_started{remote_connection_failure,TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:T │
│ [2024-08-03T23:32:29.545Z] "GET / HTTP/2" 503 URX,UF upstream_reset_before_response_started{remote_connection_failure,TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:T │
│ [2024-08-03T23:32:30.181Z] "GET / HTTP/2" 503 URX,UF upstream_reset_before_response_started{remote_connection_failure,TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:T │
│ [2024-08-03T23:32:32.461Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 795 - "-" "-" "-" "-" "-" - - 10.244.0.189:8443 146.70.138.13:34291 - -                                                                   │
│ [2024-08-03T23:32:32.465Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 797 - "-" "-" "-" "-" "-" - - 10.244.0.189:8443 146.70.138.13:46145 - -                                                                   │
│ [2024-08-03T23:32:32.466Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 797 - "-" "-" "-" "-" "-" - - 10.244.0.189:8443 146.70.138.13:47261 - -                                                                   │
│ [2024-08-03T23:32:44.075Z] "HEAD / HTTP/2" 503 URX,UF upstream_reset_before_response_started{remote_connection_failure,TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end: │
```

The endpoint has a self-signed cert which hasn't expired yet and I can curl both the service and the IP from the ingress gateway pods.

```
 mahamed  MAHAALI-M-2PY9  ~  Desktop  Git  te-ee-sandbox  $  curl https://home.borg.dev -i && echo
HTTP/2 503
content-length: 253
content-type: text/plain
date: Sat, 03 Aug 2024 23:45:00 GMT
server: istio-envoy

upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end
```

What changed recently?

### Version

```Text
mahamed  MAHAALI-M-2PY9  ~  $  k version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7+k3s1
 mahamed  MAHAALI-M-2PY9  ~  $  istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.21.1 (1 proxies), 1.22.3 (2 proxies)
```

**Comment by upodroid** [comment]
The service is reachable from the ingress-gateway pod.

```
 mahamed  MAHAALI-M-2PY9  ~  $  k exec istio-ingressgateway-778d69499b-n2mnz -c istio-proxy -- curl https://hassio.default:8123 -ksI -XGET
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
Server:
X-Frame-Options: SAMEORIGIN
Content-Length: 4148
Date: Sat, 03 Aug 2024 23:46:51 GMT

```

**Comment by upodroid** [comment]
After some digging, I found https://github.com/istio/istio/pull/48952 and setting insecureSkipVerify in tls block fixed this issue. :(

**Comment by sambo2021** [comment]
@upodroid i think in your case you can some how mount that ouside service cacert in egress gateway instances , but ofcourse insecureSkipVerify is perfect for now 
and just FYI this is a change in istio-v1.21 stats that 
"Updated the default value of the feature flag VERIFY_CERT_AT_CLIENT to true. This means server certificates will be automatically
verified using the OS CA certificates when not using a DestinationRule caCertificates field. If undesired, please use the new
compatibilityVersion feature to fallback to old behavior, or insecureSkipVerify field in DestinationRule to skip the verification."
https://istio.io/latest/news/releases/1.21.x/announcing-1.21/change-notes/

**Comment by marsteg** [comment]
Manually setting the sni setting might also help (from: https://github.com/istio/istio/issues/50997)

**Comment by jbilliau-rcd** [comment]
I had this exact same issue upgrading from Istio `1.19` to `1.22`. Setting `.spec.trafficPolicy.tls.sni` to my desired host header fixed it. Not sure why I need to do this though....my `VirtualService` explicitly already states to set the host header, now I have to specify that as well in the `DestinationRule`?

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: beta-whale
  namespace: beta-whale
spec:
  exportTo:
    - istio-system
  host: beta-whale.xxxxx.zone
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: beta-whale.xxxxx.zone
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: beta-whale
  namespace: beta-whale
spec:
  gateways:
    - beta-whale-gateway
  hosts:
    - api.beta.xxxxx.xxxx.zone
  http:
    - headers:
        request:
          set:
            host: beta-whale.xxxxxx.zone
      match:
        - uri:
            prefix: /amortization/
      rewrite:
        uri: /api/amortizationCalculator/
      route:
        - destination:
            host: beta-whale.xxxxxx.zone
```
