### ISSUE TITLE
Applying DestinationRule with exportTo seems inconsistent.  

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#52519]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm not sure if this is a bug or the expected behavior.
I need to apply different DestinationRules on the same host to istio-ingressgateway and sidecar proxies. I'm trying to use `exportTo` in the DRs to achieve that.

Here is the DR that I used to apply on istio-ingressgateway:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-ingress-dr
  namespace: test
spec:
  exportTo:
    - istio-system
  host: httpbin.mesh.global
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
```

Here is the one for dataplane proxies
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-dr
  namespace: test
spec:
  exportTo:
    - sleep
    - httpbin
  host: httpbin.mesh.global
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 5
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
```

### Expected Behavior
Since both the DRs have specific namespaces in the `exportTo`, the expectation was that they would be applied correctly to their respective proxies.

### Actual Behavior
When I apply the DR for sidecar proxies, it gets applied correctly.
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/86096284-3d9a-4da7-9ca5-1f82f1f9cdee">

But when I apply DR for the ingressgateway, it doesn’t get applied.
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/c3fd62ae-22ef-458b-81ef-a3ae56a85f5a">

Only after I delete the sidecar DR does the ingress DR get applied.
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/fa90422c-6811-4f9a-85d2-46619db1544b">

I repeated the same but this time I applied the ingressgateway DR and then the sidecar DR. The same thing happened. The Ingressgateway DR got applied but not the sidecar DR. 
But this time even after deleting the ingress DR, the sidecar DR did not get picked. I had to delete the sidecar DR and re-apply it.

Steps to reproduce:

1. Add an SE in a `test` NS
2. Add a DR in `test` NS on the same host with exportTo to `istio-system` NS
3. Add another in `test` NS on the same host with exportTo to `sleep` NS
4. Run the following `istioctl` command on ingress pod
```
istioctl pc cluster <INGRESS_POD> -n istio-system --fqdn <HOST>
```
5. Run the following `istioctl` command on the sleep pod.
```
istioctl pc cluster <INGRESS_POD> -n sleep --fqdn <HOST>
```

### Version

```Text
$ istioctl version
client version: 1.17.4
control plane version: 1.20.0
data plane version: 1.20.0 (4 proxies)
```

**Comment by hzxuzhonghu** [comment]
call the /debug/sidecarz interface to dump the sidecarscope of both sidecar and ingressgateway to see whether the destinationRules inside sidecarscope is expected

**Comment by shriramsharma** [comment]
@hzxuzhonghu , I can see the following on the sleep pod
```
    "destinationRules": {
        "httpbin.mesh.global": [
            {}
        ]
    },
```
But on the ingress pod the `destinationRules` is empty
```
"destinationRules": {}
```

**Comment by hzxuzhonghu** [comment]
I will try to reproduce to get more details

**Comment by hzxuzhonghu** [comment]
>Only after I delete the sidecar DR does the ingress DR get applied.

I am nos sure how you tested this. From my understanding, the dr in namespace different from both ingress gateway (istio-system) and servie namespace cannot be applied to ingress gateway.

You can see the pushContext.destinationRule https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1165

And we use this function to build sidecarscope, so no destinationrule would be found for the ingress gateway

**Comment by hzxuzhonghu** [comment]
So where does the service ` httpbin.mesh.global` reside

**Comment by shriramsharma** [comment]
@hzxuzhonghu , `httpbin.mesh.global` is a ServiceEntry residing in the same namespace as both the DRs

Here are the istio resources

#### ServiceEntry
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin-mesh-ep-se
  namespace: test
spec:
  addresses:
  - 240.0.10.1
  endpoints:
  - address: httpbin.httpbin.svc.cluster.local.
    labels:
      security.istio.io/tlsMode: istio
      type: deployment
    locality: us-east-2
    ports:
      http: 8000
  hosts:
  - httpbin.mesh.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
    targetPort: 80
  resolution: DNS
```

#### DestinationRule on Ingress
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-ingress-dr
  namespace: test
spec:
  exportTo:
    - istio-system
  host: httpbin.mesh.global
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
```

#### DesinationRule on dataplane proxies
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-dr
  namespace: namespace
spec:
  exportTo:
    - sleep
    - httpbin
  host: httpbin.mesh.global
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 5
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
```
