### ISSUE TITLE
[Ambient] Restrict outgoing traffic through an egress gateway

### ISSUE THREAD

**Issue by laiminhtrung1997** [istio/istio#52532]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I configured the egress gateway to restrict the outgoing traffic following [this document](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic). Here are my manifests as follows:
1. Istio Gateway
```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: egressgateway
  namespace: common-gateway
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - "*"
    port:
      name: tls
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```

2. K8S Gateway
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: waypoint
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
```

3. Istio ServiceEntry
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: genk
  namespace: istio-egress
spec:
  hosts:
  - genk.vn
  ports:
  - name: tls
    number: 443
    protocol: TLS
  resolution: DNS
```

4. Istio DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-genk
  namespace: istio-egress
spec:
  host: istio-egressgateway.common-gateway.svc.cluster.local
  subsets:
  - name: genk
```

5. Istio VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-genk-through-egress-gateway
  namespace: istio-egress
spec:
  hosts:
  - genk.vn
  gateways:
  - mesh
  - common-gateway/istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - genk.vn
    route:
    - destination:
        host: istio-egressgateway.common-gateway.svc.cluster.local
        subset: genk
        port:
          number: 443
  - match:
    - gateways:
      - common-gateway/istio-egressgateway
      port: 443
      sniHosts:
      - genk.vn
    route:
    - destination:
        host: genk.vn
        port:
          number: 443
      weight: 100
```

6. K8S NetworkPolicy
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - ports:
    - protocol: TCP
      port: 15008
  - ports:
    - protocol: TCP
      port: 15012
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: common-gateway
  policyTypes:
  - Ingress
  - Egress
```

When I curl the external service https://genk.vn, the result failed. Here are the logs as follows:

1. Pod tools.istio-egress logs
```
root@tools:/# curl -Iv https://genk.vn
*   Trying 240.240.0.4:443...
* Connected to genk.vn (240.240.0.4) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to genk.vn:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to genk.vn:443
```

2. Pod ztunnel logs
```
2024-08-06T14:43:38.102580Z     info    access  connection complete     src.addr=10.100.100.121:34564 src.workload="tools" src.namespace="istio-egress" src.identity="spiffe://cluster.local/ns/istio-egress/sa/default" dst.addr=10.100.100.175:15008 dst.hbone_addr=240.240.0.4:443 dst.service="genk.vn" dst.workload="waypoint-574c4b648-zb5bd" dst.namespace="istio-egress" dst.identity="spiffe://cluster.local/ns/istio-egress/sa/waypoint" direction="outbound" bytes_sent=517 bytes_recv=0 duration="10009ms"
```

3. Pod waypoint.istio-egress logs
```
[2024-08-06T14:43:28.093Z] "- - -" 0 UF,URX - - "-" 0 0 10008 - "-" "-" "-" "-" "123.30.151.74:443" inbound-vip|443|tcp|genk.vn - 240.240.0.4:443 10.100.100.121:39690 - -
```

I don't know why the traffic goes to the waypoint in the same namespace istio-egress of pod tools instead of istio-egressgateway.common-gateway as I expected.

### Version

```Text
$ istioctl -i kube-system version
client version: 1.23-alpha.749dbacd692ea417455ce20d29ba80b7a0cce21b
control plane version: 1.23-alpha.749dbacd692ea417455ce20d29ba80b7a0cce21b
data plane version: 1.23-alpha.749dbacd692ea417455ce20d29ba80b7a0cce21b (12 proxies)
```

**Comment by howardjohn** [comment]
I think the problem is you are mixing up the old sidecar egress approach with the new waypoint approach.

Here is what you need:

Install with `--set values.cni.ambient.dnsCapture=true --set values.pilot.env.PILOT_ENABLE_IP_AUTOALLOCATE=true`. You need to be using 1.23.

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: egress
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: istio-egress
  labels:
    istio.io/use-waypoint: egress
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```

Thats it

**Comment by laiminhtrung1997** [comment]
@howardjohn It is still not working.
```
~ $ curl -Iv https://genk.vn
* Host genk.vn:443 was resolved.
* IPv6: 2001:2::2
* IPv4: 240.240.0.2
*   Trying 240.240.0.2:443...
* Connected to genk.vn (240.240.0.2) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /cacert.pem
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS alert, record overflow (534):
* OpenSSL/3.3.1: error:0A0000C6:SSL routines::packet length too long
* closing connection #0
curl: (35) OpenSSL/3.3.1: error:0A0000C6:SSL routines::packet length too long
```

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    gateway.istio.io/controller-version: "5"
  creationTimestamp: "2024-08-09T06:50:33Z"
  generation: 1
  labels:
    istio.io/waypoint-for: all
  name: waypoint
  namespace: istio-egress
  resourceVersion: "1174871"
  uid: ba27e932-93d7-468a-94c5-cd918285b1dc
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
status:
  addresses:
  - type: IPAddress
    value: 10.100.142.127
  conditions:
  - lastTransitionTime: "2024-08-09T06:50:33Z"
    message: Resource accepted
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2024-08-10T06:40:33Z"
    message: Resource programmed, assigned to service(s) waypoint.istio-egress.svc.cluster.local:15008
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
  listeners:
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2024-08-09T06:50:33Z"
      message: No errors found
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-08-09T06:50:33Z"
      message: No errors found
      observedGeneration: 1
      reason: NoConflicts
      status: "False"
      type: Conflicted
    - lastTransitionTime: "2024-08-09T06:50:33Z"
      message: No errors found
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2024-08-09T06:50:33Z"
      message: No errors found
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    name: mesh
    supportedKinds: []
```

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  creationTimestamp: "2024-08-09T06:50:33Z"
  generation: 4
  labels:
    istio.io/use-waypoint: waypoint
  name: istio-egress
  namespace: istio-egress
  resourceVersion: "1193425"
  uid: b0ac4747-fbc0-4529-b05b-215f9f88bd2f
spec:
  hosts:
  - genk.vn
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 443
    protocol: HTTP
  resolution: DNS
status:
  addresses:
  - host: genk.vn
    value: 240.240.0.2
  - host: genk.vn
    value: 2001:2::2
```

Logs from waypoint.istio-egress
```
[2024-08-10T07:08:46.653Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 240.240.0.2:443 10.100.194.202:48926 - -
```

**Comment by howardjohn** [comment]
You are sending https but configuring it to be http. You'll either need to configure it to be https, or send http (and then you can add TLS with a destination rule)

**Comment by laiminhtrung1997** [comment]
@howardjohn, I configured it to be https in the first place which I posted about this issue. That's a problem for me so that why I need you to help me with it.

**Comment by howardjohn** [comment]
Your original configuration is trying to configure the legacy egress gateway way so its wrong beyond just the HTTPS part.

You just need

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  labels:
    istio.io/use-waypoint: waypoint
  name: istio-egress
  namespace: istio-egress
spec:
  hosts:
  - genk.vn
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
```

**Comment by laiminhtrung1997** [comment]
@howardjohn Yeah, I did it too. But it still raises this message
```
* Host httpbin.org:443 was resolved.
* IPv6: 2001:2::2
* IPv4: 240.240.0.2
*   Trying 240.240.0.2:443...
* Connected to httpbin.org (240.240.0.2) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /cacert.pem
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.org:443 
* closing connection #0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.org:443
```

I have no idea what I am missing or misconfiguring.

**Comment by laiminhtrung1997** [comment]
Here are my yaml files.
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/use-waypoint: waypoint
    istio.io/dataplane-mode: ambient
  name: istio-egress
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: waypoint
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: istio-egress
  namespace: istio-egress
  labels:
    istio.io/use-waypoint: waypoint
spec:
  hosts:
  - httpbin.org
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-egressgateway
  namespace: istio-egress
spec:
  host: waypoint.istio-egress.svc.cluster.local
  subsets:
  - name: istio-egress
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  hosts:
  - httpbin.org
  gateways:
  - mesh
  - common-gateway/herculesdev9-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 80
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: istio-egressgateway.common-gateway.svc.cluster.local
        subset: istio-egress
        port:
          number: 80
  - match:
    - gateways:
      - common-gateway/herculesdev9-egressgateway
      port: 80
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: httpbin.org
        port:
          number: 80
      weight: 100
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - ports:
    - protocol: TCP
      port: 15008
  - ports:
    - protocol: TCP
      port: 15012
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: common-gateway
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: direct-httpbin-to-egress-gateway
  namespace: istio-egress
spec:
  parentRefs:
  - kind: ServiceEntry
    group: networking.istio.io
    name: istio-egress
  rules:
  - backendRefs:
    - name: waypoint
      port: 15008
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forward-httpbin-from-egress-gateway
  namespace: istio-egress
spec:
  parentRefs:
  - name: waypoint
  hostnames:
  - httpbin.org
  rules:
  - backendRefs:
    - kind: Hostname
      group: networking.istio.io
      name: httpbin.org
      port: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-tls-for-httpbin-org
  namespace: istio-egress
spec:
  host: httpbin.org
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

**Comment by howardjohn** [comment]
@laiminhtrung1997 this is the config you need. Note the 4 configs I have removed

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/use-waypoint: waypoint
    istio.io/dataplane-mode: ambient
  name: istio-egress
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: waypoint
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: istio-egress
  namespace: istio-egress
  labels:
    istio.io/use-waypoint: waypoint
spec:
  hosts:
  - httpbin.org
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: istio-egressgateway
#   namespace: istio-egress
# spec:
#   host: waypoint.istio-egress.svc.cluster.local
#   subsets:
#   - name: istio-egress
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: istio-egress
#   namespace: istio-egress
# spec:
#   hosts:
#   - httpbin.org
#   gateways:
#   - mesh
#   - common-gateway/herculesdev9-egressgateway
#   tls:
#   - match:
#     - gateways:
#       - mesh
#       port: 80
#       sniHosts:
#       - httpbin.org
#     route:
#     - destination:
#         host: istio-egressgateway.common-gateway.svc.cluster.local
#         subset: istio-egress
#         port:
#           number: 80
#   - match:
#     - gateways:
#       - common-gateway/herculesdev9-egressgateway
#       port: 80
#       sniHosts:
#       - httpbin.org
#     route:
#     - destination:
#         host: httpbin.org
#         port:
#           number: 80
#       weight: 100
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - ports:
    - protocol: TCP
      port: 15008
  - ports:
    - protocol: TCP
      port: 15012
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: common-gateway
  policyTypes:
  - Ingress
  - Egress
---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: direct-httpbin-to-egress-gateway
#   namespace: istio-egress
# spec:
#   parentRefs:
#   - kind: ServiceEntry
#     group: networking.istio.io
#     name: istio-egress
#   rules:
#   - backendRefs:
#     - name: waypoint
#       port: 15008
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: forward-httpbin-from-egress-gateway
#   namespace: istio-egress
# spec:
#   parentRefs:
#   - name: waypoint
#   hostnames:
#   - httpbin.org
#   rules:
#   - backendRefs:
#     - kind: Hostname
#       group: networking.istio.io
#       name: httpbin.org
#       port: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-tls-for-httpbin-org
  namespace: istio-egress
spec:
  host: httpbin.org
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

Note depending on the version, you may be running into two bugs:
* https://github.com/istio/istio/issues/52746 - if traffic is failing entirely its probably this one. You can see with the 0.0.0.0 here:
```
$ istioctl pc l waypoint-7f8df594db-grxcl --waypoint
LISTENER                  CHAIN                            MATCH                  DESTINATION
envoy://connect_originate                                  ALL                    Cluster: connect_originate
envoy://main_internal     inbound-vip|443||httpbin.org-tcp ip=0.0.0.0 -> port=443 Cluster: inbound-vip|443|tcp|httpbin.org
```
* https://github.com/istio/istio/pull/52747 - portLevelSettings does not work in waypoint. I would just remove it and make it like this:
```yaml
spec:
  host: httpbin.org
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: SIMPLE
```

Note you also need `--set values.pilot.env.PILOT_ENABLE_IP_AUTOALLOCATE=true --set values.cni.ambient.dnsCapture=true`

**Comment by laiminhtrung1997** [comment]
@howardjohn That's great. I very much appreciate it. Let me check whether I got these bugs.

**Comment by laiminhtrung1997** [comment]
@howardjohn I configured exactly everything you commented but the traffic still failed. Do we need to consider there is a bug? 

```
$ istioctl pc l waypoint-5749789b5-rmj65 --waypoint -n istio-egress -i kube-system
LISTENER                  CHAIN                                                     MATCH                                                DESTINATION
envoy://connect_originate                                                           ALL                                                  Cluster: connect_originate
envoy://main_internal     inbound-vip|443||httpbin.org-tcp                          ip=240.240.0.1 -> port=443                           Cluster: inbound-vip|443|tcp|httpbin.org
envoy://main_internal     inbound-vip|443||httpbin.org-tcp                          ip=2001:2::1 -> port=443                             Cluster: inbound-vip|443|tcp|httpbin.org
envoy://main_internal     inbound-vip|80||sleep.istio-egress.svc.cluster.local-http ip=10.100.110.192 -> port=80                         Cluster: inbound-vip|80|http|sleep.istio-egress.svc.cluster.local
envoy://main_internal     direct-tcp                                                ip=10.100.224.172 -> ANY                             Cluster: encap
envoy://main_internal     direct-http                                               ip=10.100.224.172 -> application-protocol='h2c'      Cluster: encap
envoy://main_internal     direct-http                                               ip=10.100.224.172 -> application-protocol='http/1.1' Cluster: encap
envoy://connect_terminate default                                                   ALL                                                  Inline Route: 
envoy://                                                                            ALL                                                  Inline Route: /healthz/ready*
envoy://                                                                            ALL                                                  Inline Route: /stats/prometheus*
```

```
$ kubectl -n istio-egress exec -it deploy/sleep -- sh
~ $ curl -Iv https://httpbin.org
* Host httpbin.org:443 was resolved.
* IPv6: 2001:2::1
* IPv4: 240.240.0.1
*   Trying 240.240.0.1:443...
* Connected to httpbin.org (240.240.0.1) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /cacert.pem
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.org:443 
* closing connection #0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.org:443 
```

```
$ kubectl -n kube-system logs -f ds/ztunnel | grep istio-egress
2024-08-20T07:40:25.262643Z     info    access  connection complete     src.addr=10.100.224.172:52180 src.workload="sleep-5577c64d7c-vk2rd" src.namespace="istio-egress" src.identity="spiffe://cluster.local/ns/istio-egress/sa/sleep" dst.addr=10.100.224.173:15008 dst.hbone_addr=240.240.0.1:443 dst.service="httpbin.org" dst.workload="waypoint-5749789b5-rmj65" dst.namespace="istio-egress" dst.identity="spiffe://cluster.local/ns/istio-egress/sa/waypoint" direction="outbound" bytes_sent=517 bytes_recv=0 duration="10001ms"
```

```
[2024-08-20T07:40:15.263Z] "- - -" 0 UF,URX - - "-" 0 0 9997 - "-" "-" "-" "-" "44.217.225.103:443" inbound-vip|443|tcp|httpbin.org - 240.240.0.1:443 10.100.224.172:44594 - -
```

**Comment by howardjohn** [comment]
That sounds like the waypoint cannot call httpbin at `44.217.225.103:443`. That doesn't seem likely an Istio misconfig, but lack of network connectivity. Can you do `curl https://httpbin.org` fromthe waypoint?

**Comment by howardjohn** [comment]
Your

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-egress
  namespace: istio-egress
```

doesn't allow the waypoint itself to call external
