### ISSUE TITLE
Istioctl says fromNamespaces in CUSTOM AuthZ policy is not valid, but it appears to be

### ISSUE THREAD

**Issue by Stono** [istio/istio#52553]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using a filter of namespace in a `CUSTOM` authz policy, eg:

```
spec:
  action: CUSTOM
  provider:
    name: some-external
  rules:
  - from:
    - source:
        namespaces:
        - whatever
```

Validate throws up:

```
AuthorizationPolicy//pip: invalid policy pip.platform-testing: From.Namespaces is currently not supported with CUSTOM action
```

But it works (i've tested it on the cluster).  So feels like this is validation for an old condition which is no longer the case?

Older issue, same subject: https://github.com/istio/istio/issues/47157

### Version

```Text
1.22
```

**Comment by hzxuzhonghu** [comment]
How do you make it pass the src namespace to external authz server?

**Comment by hzxuzhonghu** [comment]
Actually, in this custom authz case, all the decision is made by the server, the From.SourceNamespace does not apply to external authz server. You can configure whatevere policies on the authz server in another way

**Comment by Stono** [comment]
@hzxuzhonghu i don't think i understand you?
I'm saying:

```
spec:
  action: CUSTOM
  provider:
    name: some-external
  rules:
  - from:
    - source:
        namespaces:
        - whatever
```

Is valid config, is accepted by the API server, and it works as expected (only applies to requests from the `whatever` namespace).

However `istioctl validate` rejects it.

**Comment by howardjohn** [comment]
Do you not run a validation webhook?

```
$  cat <<EOF | kubectl apply -f -
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin
spec:
  action: CUSTOM
  provider:
    name: some-external
  rules:
  - from:
    - source:
        namespaces:
        - whatever
EOF
Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: configuration is invalid: invalid policy httpbin.default: From.Namespaces is currently not supported with CUSTOM action
```

**Comment by Stono** [comment]
![Screenshot 2024-08-09 at 10 54 08](https://github.com/user-attachments/assets/de2101c7-fa19-49e1-9a37-469ccccea5a0)
yup 🤔 

```
❯ cat <<EOF | kubectl apply -f -
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin
spec:
  action: CUSTOM
  provider:
    name: some-external
  rules:
  - from:
    - source:
        namespaces:
        - whatever
EOF
authorizationpolicy.security.istio.io/httpbin created
```

lol
