### ISSUE TITLE
Consider allowing some namespace policies to apply  to waypoints

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52590]
For a variety of reasons, we chose to make Authorization policies that are namespace scoped not apply to waypoints. We did the same for other types. We may want to cosnider allowing these to apply.

For example:

```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: public-gateway
  namespace: public
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
```
