### ISSUE TITLE
Hosts without dots disable VirtualService

### ISSUE THREAD

**Issue by qts0312** [istio/istio#52605]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As the VirtualService below, I try `curl -H"host:ratings" http://1.1.1.1:80` but get 502. After I change `ratings` to `ratings.com`, I try `curl -H"host:ratings.com" http://1.1.1.1:80` and get correct response (productpage service). Why does this happen? Does the dot in host matter?

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - "ratings"
  http:
    - route:
        - destination:
            host: productpage
            port:
              number: 9080
```

### Version

```Text
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (6 proxies)

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```
