### ISSUE TITLE
Confusing behavior from HTTPRetry if HTTPRoute route timeout not specified

### ISSUE THREAD

**Issue by esnible** [istio/istio#5260]
The default timeout for https://istio.io/docs/reference/config/istio.networking.v1alpha3.html#HTTPRoute is 0s.  This is different from Envoy's default and confusing when there is an HTTPRetry on a VirtualService with unspecified timeout.

Given a VirtualService with timeout unspecified:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - retries:
      attempts: 2
      perTryTimeout: 2.123s
```

 The generated Envoy configuration was

```
"retry_policy": {
  "num_retries": 2,
  "per_try_timeout": "2.123s",
  "retry_on": "5xx,connect-failure,refused-stream"
},
"timeout": "0.000s",
```

The retry didn't happen.  Envoy has a default of 15s if the timeout is unspecified.  Istio supplies Envoy with "0.000s" if the Istio VirtualService timeout is unspecified, and 0 doesn't mean "forever" as in Python, it means that Envoy will spend at most 0s before giving up retrying. (edited)

We should document our default _timeout_.  We should consider defaulting to something like Envoy's 15s.  We should consider adding validation to warn the user if an HTTPRetries is supplied that can't retry.

Envoy documents their default at https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction
