### ISSUE TITLE
Inconsistent priority between VirtualService and Service

### ISSUE THREAD

**Issue by qts0312** [istio/istio#52603]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As the VirtualService below, `curl -H"host:example" http://ratings:8080` goes to ratings service, implying that Service wins when both Service and VirtualService match the traffic.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - "example"
  http:
    - route:
        - destination:
            host: productpage
            port:
              number: 9080
```

However, when change the VirtualService as below, traffic `curl -H"host:ratings" http://ratings:8080` is captured by VirtualService and goes to productpage service, which indicates inconsistent priority between Service and VirtualService.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - "ratings"
  http:
    - route:
        - destination:
            host: productpage
            port:
              number: 9080
```

### Version

```Text
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (6 proxies)

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```
