### ISSUE TITLE
Custom sidecar injection in broken on OpenShift deployment

### ISSUE THREAD

**Issue by sridhargaddam** [istio/istio#52614]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using custom sidecar injection in an OpenShift deployment by adding an "istio-proxy" container to the Pod, traffic interception fails because the userID of the sidecar proxy matches with the application pod.

Lets assume that we add the following `istio-proxy` container to the pod.

```
    spec:
      containers:
      - image: auto                                                                                                                                                                           
        name: istio-proxy
        resources: {}
        securityContext:
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: curlimages/curl
        name: sleep
        command:
        - /bin/sleep                                                                                                                                                                          
        - infinity
```

this is what would be seen by the Istio webhook handler

```
    spec:
      containers:
      - image: auto                                                                                                                                                                           
        name: istio-proxy
        resources: {}
        securityContext:
          runAsUser: 1000620000
          ...
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ...
      - image: curlimages/curl
        name: sleep
        command:
        - /bin/sleep                                                                                                                                                                          
        - infinity
        securityContext:
          runAsUser: 1000620000
          ...
```

OpenShift automatically assigns a SecurityContext.RunAsUser to all containers in the Pod, even if the Pod's
YAML does not explicitly set this value. Istio treats the values specified in the istio-proxy container as
overrides and preserves them in the final Pod yaml as expected. However, the RunAsUser value which is
automatically set by OpenShift would be the same for all containers within the Pod, which is a problem.
Because the RunAsUser is identical for both the application container and the proxy container, traffic
interception fails for the pod.

### Version

```Text
$ istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (12 proxies)

The same issue is seen even with the latest build.

kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5+58452d8
sgaddam@fedora:~/deployk8s/ocp$
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
