### ISSUE TITLE
HTTP/2 grpc traffic are not being handled while HTTP/1.1 works fine (delayed connect error: 111)

### ISSUE THREAD

**Issue by pwmb** [istio/istio#52627]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

So I am deploying a ASP.net app in k8s with Istio Service mesh and facing some problems and any help would be great

In this cluster we already have apps serving traffic fine with `http1.1` but when it comes to serving `http2` with `grpc` having some issue with traffic routing through the istio service mesh to outside world.

So when I do 
- `kubectl port-forward svc/history -n test1 9239` 
- `curl --http2-prior-knowledge http://localhost:9239/health -v` 

I get the desired response back, but 

when I call the same service through the service mesh using the host name I get this error

`curl --http2-prior-knowledge http://dev.mybookstore.cloud/history/health -v`

```bash
< HTTP/2 503
< content-length: 152
< content-type: text/plain
< date: Sat, 10 Aug 2024 09:36:00 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 36
<
* Connection #0 to host dev.mybookstore.cloud left intact
upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111
```

A bit more context about the app. Its a `grpc` simple [greeter app with ASP.net core](https://learn.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-8.0) and interesting thing I noticed at the beginning is that initially the server was listening on `http://[::]:9239` and then the envoy proxy was simply returning 503 status without any body

I tried binding the server to `0.0.0.0` (same 503 response without any body) and `127.0.0.1` (current config where it is giving delayed connect error: 111)

I am suspecting that I am missing some config to make the virtual service or destination route to correctly route the traffic to the pod with correct protocol but I could be wrong

Configs looks like this: 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: history
  namespace: test1
spec:
  clusterIP: 10.0.252.37
  clusterIPs:
  - 10.0.252.37
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http2
    name: http2
    port: 9239
    protocol: TCP
    targetPort: 9239
  selector:
    app: history
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  generation: 3
  name: history
  namespace: test1
spec:
  gateways:
  - istio-system/http-gateway
  hosts:
  - dev.mybookstore.cloud
  http:
  - match:
    - uri:
        prefix: /hist
    - uri:
        prefix: /history
    route:
    - destination:
        host: history
        port:
          number: 9239
```

```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  generation: 2
  name: history
  namespace: test1
spec:
  host: history
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
    tls:
      mode: DISABLE
```
 
```yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  generation: 2
  name: http-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - dev.mybookstore.cloud
    port:
      name: http-port
      number: 80
      protocol: HTTP2
```

### Version

```Text
$ istioctl version
client version: 1.22.3
control plane version: 1.22.2
data plane version: 1.22.2 (9 proxies)

$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7

$ helm version --short
v3.15.2+g1a500d5
```

**Comment by perezjasonr** [comment]
i thought i was going crazy but im having the exact same problem.


same setup w/ svc appProtocol says grpc instead of http2 seems to be only real difference between urs and mine. and we also noticed the same thing, that is to say, port-forward to the svc seems to work fine (been using grpcurl tool to test), but through istio igw it doesn't. It gets even stranger because we have 2 grpc services actually with basically identical setup, but one works and one gets this error. i cannot figure out what the difference is at all.


and you can see istio-igw logs seems to be attempting to send to the correct place via the outbout svc, so confused.


```
[2024-09-16T15:01:44.563Z] "POST /frostcore.v2.FrostCore/is_initialized HTTP/2" 200 URX,UF **upstream_reset_before_response_started{remote_connection_failure,delayed_connect_error:_111}** - "delayed_connect_error:_111" 12 0 37 - "10.1.81.33" "grpcurl/v1.9.1 grpc-go/1.61.0" "ad2dee26-65cf-99e9-9c66-b577a956a41a" "10.1.20.65:80" "10.66.2.21:50051" **outbound|50051||frost-core-service.frostbite.svc.cluster.local** - 10.66.229.180:8080 10.1.81.33:54834 - - traceID=3149b9a55a785369d6e1757fb20559ad


[2024-09-16T15:01:51.797Z] "POST /frostcore.v2.FrostCore/get_active_connections HTTP/2" 200 URX,UF **upstream_reset_before_response_started{remote_connection_failure,delayed_connect_error:_111}** - "delayed_connect_error:_111" 12 0 59 - "10.1.81.33" "grpcurl/v1.9.1 grpc-go/1.61.0" "d65cce1a-98f9-9e12-b44c-c3f2ff701ab3" "10.1.20.65:80" "10.66.2.21:50051" **outbound|50051||frost-core-service.frostbite.svc.cluster.loca**l - 10.66.229.180:8080 10.1.81.33:4642 - - traceID=b9d1bfe796ab6869ad49f29d0096e28c
2024-09-16T15:07:50.985784Z     info    xdsproxy        connected to delta upstream XDS server: istiod.istio-system.svc:15012   id=616


THE BELOW WORKS, NO ERROR, FOR SOME REASON EVEN THOUGH ITS THE SAME GATEWAY, VS, SVC SETUP


[2024-09-16T15:08:26.482Z] "POST /frostrbd.FrostRBD/list_pools HTTP/2" 200 - via_upstream - "-" 5 81 145 - "10.1.81.33" "grpcurl/v1.9.1 grpc-go/1.61.0" "4f377876-c3fb-9ee7-8f69-d9d7ce15dd43" "10.1.20.65:80" "10.66.2.48:50051" **outbound|50051||grpc-poc.frostbite.svc.cluster.local** 10.66.229.180:34828 10.66.229.180:8080 10.1.81.33:15380 - - traceID=5608457ccb784520ccd39f16b436090f
```

**Comment by perezjasonr** [comment]
this setup fails:


```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grpc-poc-frost-core
  namespace: frostbite
spec:
  gateways:
  - frostbite/frostbite-gw
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /frostcore.v2.FrostCore/get_active_connections
    - uri:
        prefix: /frostcore.v2.FrostCore/is_initialized
    route:
    - destination:
        host: frost-core-service
        port:
          number: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: frost-core-service
  namespace: frostbite
spec:
  clusterIP: 10.105.111.2
  clusterIPs:
  - 10.105.111.2
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: grpc
    name: frost-core-grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: frost-core
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```


and for some reason this setup works

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grpc-poc
  namespace: frostbite
spec:
  gateways:
  - frostbite/frostbite-gw
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /frostrbd.FrostRBD/list_pools
    route:
    - destination:
        host: grpc-poc
        port:
          number: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-poc
  namespace: frostbite
spec:
  clusterIP: 10.98.81.202
  clusterIPs:
  - 10.98.81.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: grpc
    name: frostrbd-grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: frostrbd
    app.kubernetes.io/name: frostrbd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

i have tried different things to try to isolate the difference, i moved the workload to the same node, they are in the same namespace, using the same gw/istio-igw. cannot figure out for the life of me why one works and one doesn't, and why they both work when doing port-forward > svc

**Comment by perezjasonr** [comment]
and for thoroughness sake here's the port-forward and the failing one works:

```
kubectl port-forward -n frostbite service/frost-core-service 50051:50051
Forwarding from 127.0.0.1:50051 -> 50051
```

```
grpcurl -import-path /protos -proto core.proto -plaintext -d '{"vm_name": "FT01a"}' 127.0.0.1:50051 frostcore.v2.FrostCore/get_active_connections
{}       # <--- expected response

grpcurl -import-path /protos -proto core.proto -plaintext -d '{"vm_name": "FT01a"}' 127.0.0.1:50051 frostcore.v2.FrostCore/is_initialized
{
  "initialization": "NOT_INITIALIZED"
}
# ^ expected response
```

**Comment by pwmb** [comment]
I solved with with this

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: history
spec:
  gateways:
    - istio-system/gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /history/
        - uri:
            exact: /history
      rewrite:
        uri: /
      route:
        - destination:
            host: history
            port:
              number: 9239
```
