### ISSUE TITLE
Unable to trigger outlier detection on istio-ingressgateway

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#52665]
## Problem Statement

I’m trying to enable outlier detection on istio-ingressgateway proxy through the following DR. It is an L4 proxy and according to [envoy’s documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier), the TCP failures should be map to consective_5xx errors.

> For TCP traffic, outlier_detection.consecutive_5xx is the correct parameter to set and transparently maps to TCP connection failures.

I tried to test it by manually killing the application container on most of the pods and also tried to kill some pods itself. I see UF/URX errors on ingress but the outlier never gets triggered. I enabled the outlier metrics as well, but data is always 0.
```
   host: httpbin.httpbin.svc.cluster.local
   ...
    outlierDetection:
      consecutive5xxErrors: 5
      consecutiveGatewayErrors: 0
      maxEjectionPercent: 100
      interval: 60s
      baseEjectionTime: 5m
```

## Steps to Reproduce
1. Create the following DR
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: outlier-detection-test-on-ingress 
spec:
  host: httpbin.httpbin.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      consecutiveGatewayErrors: 0
      maxEjectionPercent: 100
      interval: 60s
      baseEjectionTime: 5m
    tls:
      mode: ISTIO_MUTUAL
```
2. Add additional outlier metrics to the istio-ingressgateway deployment
```
metadata:                                                                                                                                                                                                                       
  annotations:                                                                                                                                                                                                                                                                                                                                                                                                                   
    proxy.istio.io/config: |                                                                                                                                                                                                        
          proxyStatsMatcher:
            inclusionRegexps:
              - ".*ejections_enforced_total.*"
              - ".*ejections_active.*"
              - ".*ejections_overflow.*"
              - ".*ejections_detected_consecutive_5xx.*"
```

I'm not sure if I'm missing something? Can someone please help with this?
