### ISSUE TITLE
Upgrading from istio 1.19.x to 1.2x.x breaks envoyFilter ordering. 

### ISSUE THREAD

**Issue by BenCoughlan15** [istio/istio#52673]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Referencing PR's 
https://github.com/istio/proxy/pull/4891
https://github.com/istio/istio/pull/46498
https://github.com/istio/istio/pull/46517

Historically, the metadata exchange happened after ext_authz. 

This has been reordered everywhere, which broke our auth, routing, etc.  

I was deploying this on version 1.19.4: 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio.io/rev: canary
  name: metadata-exchange-after-authz-canary
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.ext_authz
    patch:
      operation: INSERT_AFTER
      value:
        name: istio.metadata_exchange
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            configuration:
              '@type': type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
            vm_config:
              code:
                local:
                  inline_string: envoy.wasm.metadata_exchange
              runtime: envoy.wasm.runtime.null
  priority: 1
  workloadSelector:
    labels:
      istio: ingressgateway
      revision: canary
```

This would allow us to use headers to do auth routing, region routing, etc. 

since upgrading, the filter chain has changed from: 

`curl 127.0.0.1:15000/config_dump | jq '.configs[] | select( ."@type" == "type.googleapis.com/envoy.admin.v3.ListenersConfigDump" ).dynamic_listeners[] | select( .name == "0.0.0.0_80" ).active_state.listener.filter_chains.[].filters[] | select(.name == "envoy.filters.network.http_connection_manager").typed_config.http_filters[] | .name '`

```
"istio.metadata_exchange"
"envoy.filters.http.rbac"
"envoy.filters.http.ext_authz"
**"istio.metadata_exchange"**
"envoy.filters.http.grpc_stats"
"istio.alpn"
"envoy.filters.http.fault"
"envoy.filters.http.cors"
"istio.stats"
"envoy.filters.http.router"
```

to: 

```
"istio.metadata_exchange"
"envoy.filters.http.rbac"
"envoy.filters.http.ext_authz"
"envoy.filters.http.grpc_stats"
"istio.alpn"
"envoy.filters.http.fault"
"envoy.filters.http.cors"
"istio.stats"
"envoy.filters.http.router"

```
I've tried this, by mimicking the new metadata filter: 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio.io/rev: canary
  name: metadata-exchange-after-authz-canary
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.ext_authz
    patch:
      operation: ADD
      value:
        name: istio.metadata_exchange
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/io.istio.http.peer_metadata.Config
          value:
            upstream_discovery:
            - istio_headers: {}
            - workload_discovery: {}
            upstream_propagation:
            - istio_headers: {}
  priority: 1
  workloadSelector:
    labels:
      istio: ingressgateway
      revision: canary
```

The result is that I see these errors in istiod, and in the api-gw. 

api-gw: 
`2024-08-14T16:06:41.906273Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: Error: terminal filter named envoy.filters.http.router of type envoy.filters.http.router must be the last filter in a http filter chain.
0.0.0.0_443: Error: terminal filter named envoy.filters.http.router of type envoy.filters.http.router must be the last filter in a http filter chain.
	thread=14
2024-08-14T16:06:42.930025Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2024-08-14T16:06:44.929728Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2024-08-14T16:06:46.929951Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2024-08-14T16:06:48.929910Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected`

Do you have any idea how I can restore this behaviour? 

I'm right on the edge of what's comfortable with this filter to be honest, so I hope this isn't asking too much.  

### Version

```Text
kubectl version
client version: 1.22.3
pilot version: 1.19.4
pilot version: 1.19.4
pilot version: 1.19.4
istiod version: 1.20.8
istiod version: 1.20.8
istiod version: 1.20.8
data plane version: 1.19.4 (103 proxies), 1.20.8 (59 proxies)

> kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-gke.1043004
```

### Additional Information

> istioctl bug-report

Target cluster context: dev-eu

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-08-14 17:20:54.780965 +0100 BST

Cluster endpoint: https://xxx
CLI version:
version.BuildInfo{Version:"1.22.3", GitRevision:"Homebrew", GolangVersion:"go1.22.5", BuildStatus:"Homebrew", GitTag:"1.22.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision canary:
&version.MeshInfo{
    {
        Component: "istiod",
        Revision:  "canary",
        Info:      version.BuildInfo{Version:"1.20.8", GitRevision:"8e297d015674d2e6a21a52fbff4bff8db8380989", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.8"},
    },
    {
        Component: "istiod",
        Revision:  "canary",
        Info:      version.BuildInfo{Version:"1.20.8", GitRevision:"8e297d015674d2e6a21a52fbff4bff8db8380989", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.8"},
    },
    {
        Component: "istiod",
        Revision:  "canary",
        Info:      version.BuildInfo{Version:"1.20.8", GitRevision:"8e297d015674d2e6a21a52fbff4bff8db8380989", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.8"},
    },
}

Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.19.4", GitRevision:"930b482af113506a9aac0f4c3c547aa4f81965bb", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.19.4"},
    },
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.19.4", GitRevision:"930b482af113506a9aac0f4c3c547aa4f81965bb", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.19.4"},
    },
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.19.4", GitRevision:"930b482af113506a9aac0f4c3c547aa4f81965bb", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.19.4"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.19.4, 1.20.8}
Revision canary: Versions {1.20.8}

Fetching logs for the following containers:
