### ISSUE TITLE
`DestinationRule` affects `Deployment`/`Pod` with unmatched `workloadSelector`

### ISSUE THREAD

**Issue by bozaro** [istio/istio#52691]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have two namespaces:

 - `echo-server` with `echo` server (xDS);
 - `echo-client` with `echo` service client (xDS).

Both client and server use proxyless xDS setup with `grpc-agent` sidecar.

In `echo-server` namespace I have `DestinationRule` and `PeerAuthentication` with enabling mTLS for `echo` service.

In this configuration `echo-client` works fine.

After creating another `DestinationRule` in `echo-client` namespace with host `*` and `workloadSelector` for unrelated `Deployment` (with exactly same `trafficPolicy`) `echo-client` lost mTLS setting for `echo.echo-server.svc.cluster.local` service.

### Version

```Text
$ istioctl version
istioctl version
client version: 1.22.3
control plane version: 1.20.2
data plane version: 1.20.2 (509 proxies)

$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-eks-db838b0
```

### Additional Information

Resources looks like:
```
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - appProtocol: grpc
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    service: echo-server
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echo
  namespace: echo-server
spec:
  host: 'echo'
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection: {}
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echo-foo
  namespace: echo-client
spec:
  host: '*'
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection: {}
    tls:
      mode: ISTIO_MUTUAL
  workloadSelector:
    matchLabels:
      app.kubernetes.io/instance: echo-foo
      app.kubernetes.io/name: echo-foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: echo-client
    app.kubernetes.io/name: echo-client
  name: echo-client
  namespace: echo-client
spec:
  ...
```
