### ISSUE TITLE
Waypoints do not mirror traffic

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#52713]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Configuring request mirroring is working on the side of a workload with the sidecar proxy, however, when you apply the same to a waypoint traffic is NOT mirrored. Below are sample configuration that I used. FYI, mirroring doesn't work with Istio API either (VirtualServices).

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reviews
  namespace: httpbin
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: reviews
    namespace: bookinfo-backends
    port: 9080
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: reviews-v1
      namespace: bookinfo-backends
      port: 9080
      weight: 80
    - group: ""
      kind: Service
      name: reviews-v2
      namespace: bookinfo-backends
      port: 9080
      weight: 20
    filters:
    - type: RequestMirror
      requestMirror:
        backendRef:
          name: echo-service
          port: 80
          namespace: bookinfo-backends
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reviews
  namespace: bookinfo-backends
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: reviews
    namespace: bookinfo-backends
    port: 9080
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: reviews-v1
      namespace: bookinfo-backends
      port: 9080
      weight: 80
    - group: ""
      kind: Service
      name: reviews-v2
      namespace: bookinfo-backends
      port: 9080
      weight: 20
    filters:
    - type: RequestMirror
      requestMirror:
        backendRef:
          name: echo-service
          port: 80
          namespace: bookinfo-backends
```

### Version

```Text
1.23.0-rc.0
```
