### ISSUE TITLE
Unable to Remove Specific Tags and Metrics in Prometheus Despite Telemetry Configurations in Istio 1.21.4

### ISSUE THREAD

**Issue by haidernafees93** [istio/istio#52763]
I am upgrading my istio from 1.20.4 to 1.21.4. My initial config for istio_control_plane was 
 
```
---
apiVersion: install.istio.io/v1alpha1 
kind: IstioOperator
metadata:
  <some metadata>
spec:
  <some specifications>
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      autoscalingv2API: true
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi     
        autoInject: "disabled"
      imagePullPolicy: "IfNotPresent"
      imagePullSecrets:
      <some secrets>
    sidecarInjectorWebhook:
    <some values>
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                # Remove these tags from all Istio metrics
                - tags_to_remove: ["array of tags"]
                # Remove response tags from some metrics
                - name: request_duration_milliseconds
                  tags_to_remove: ["response_code", "response_flags"]
                - name: request_bytes
                  tags_to_remove: ["response_code", "response_flags"]
                - name: response_bytes
                  tags_to_remove: ["response_code", "response_flags"]
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                # Remove these tags from all Istio metrics
                - tags_to_remove: ["array of tags"]
                # Remove response tags from some metrics
                - name: request_duration_milliseconds
                  tags_to_remove: ["response_code", "response_flags"]
                - name: request_bytes
                  tags_to_remove: ["response_code", "response_flags"]
                - name: response_bytes
                  tags_to_remove: ["response_code", "response_flags"]
            gateway:
              debug: false
              stat_prefix: istio
              disable_host_header_fallback: true
              metrics:
                # Remove these tags from all Istio metrics
                - tags_to_remove: ["array of tags"]
                # Remove response tags from some metrics
                - name: request_duration_milliseconds
                  tags_to_remove: ["response_code", "response_flags"]
                - name: request_bytes
                  tags_to_remove: ["response_code", "response_flags"]
                - name: response_bytes
                  tags_to_remove: ["response_code", "response_flags"]
                  
```
This was working before but upon upgrading to version 1.21.4, I get an error that configOverride is not valid. There is no good documentation out there that is telling me how to fix this issue.

I have used the telemetry like this but still doesn't remove the tags from prometheus. Is there something, I am missing?
```
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-telemetry-outbound
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
          overrides:
            # Apply to all outbound sidecars
            - match:
                mode: CLIENT_AND_SERVER
              tagOverrides:
                destination_canonical_service: 
                  operation: REMOVE
                source_canonical_service: 
                  operation: REMOVE
                destination_principal: 
                  operation: REMOVE
                source_principal: 
                  operation: REMOVE
                connection_security_policy:
                  operation: REMOVE
                grpc_response_status: 
                  operation: REMOVE
                source_version: 
                  operation: REMOVE
                destination_version:
                  operation: REMOVE
                request_protocol: 
                  operation: REMOVE
                source_canonical_revision: 
                  operation: REMOVE
                destination_canonical_revision: 
                  operation: REMOVE

            # Remove response tags from specific metrics
            - match:
                metric: REQUEST_DURATION
                mode: CLIENT_AND_SERVER
              tagOverrides:
                response_code: 
                  operation: REMOVE
                response_flags: 
                  operation: REMOVE

            - match:
                metric: REQUEST_SIZE
                mode: CLIENT_AND_SERVER
              tagOverrides:
                response_code: 
                  operation: REMOVE
                response_flags: 
                  operation: REMOVE

            - match:
                metric: RESPONSE_SIZE
                mode: CLIENT_AND_SERVER
              tagOverrides:
                response_code: 
                  operation: REMOVE
                response_flags: 
                  operation: REMOVE
```
