### ISSUE TITLE
Connection Loss Whenever Istiod Configmap is Updated

### ISSUE THREAD

**Issue by LERUfic** [istio/istio#52788]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Whenever I update my Istiod configmap, such as editing the accessLogFormat, my service pods suddenly lose connection to Redis and the database for 1 or 2 minutes. My cluster is relatively small, with only 4 services running Istio sidecars, but it's set up as a multi-master with 6 clusters joined in the mesh.

I tried to check istiod logs and sidecar but has no error log.

### Version

```Text
$ istioctl version
client version: 1.18.1
control plane version: 1.18.2
data plane version: 1.18.2 (8 proxies)

$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7-gke.1026001

$ helm version --short
v3.14.3+gf03cc04
```

### Additional Information

Helm chart istiod
```yaml
pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  replicaCount: 1
  rollingMaxSurge: 100%
  rollingMaxUnavailable: 25%
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
  cpu:
    targetAverageUtilization: 80
  nodeSelector:
    cloud.google.com/gke-preemptible: "true"
  tolerations:
    - effect: NoSchedule
      key: cloud.google.com/gke-preemptible
      operator: Equal
      value: 'true'
  serviceAnnotations:
    prometheus.io/scrape: "true"
  deploymentLabels: {}
  configMap: true

sidecarInjectorWebhook:
  neverInjectSelector: []
  alwaysInjectSelector: []
  injectedAnnotations: {}
  enableNamespacesByDefault: false
  rewriteAppHTTPProbe: true
  templates: {}
  defaultTemplates: []

istiodRemote:
  injectionURL: ""
  injectionPath: "/inject"

telemetry:
  enabled: true
  v2:
    enabled: true
    metadataExchange:
      wasmEnabled: false
    prometheus:
      enabled: true
      wasmEnabled: false
      configOverride:
        gateway: {}
        inboundSidecar: {}
        outboundSidecar: {}
    stackdriver:
      enabled: false
    accessLogPolicy:
      enabled: false

meshConfig:
  accessLogEncoding: JSON
  accessLogFile: /dev/stdout
  accessLogFormat: |
      {
      "@timestamp": "%START_TIME%",
      "protocol": "%PROTOCOL%",
      "upstreamProtocol": "%UPSTREAM_PROTOCOL%",
      "method": "%REQ(:METHOD)%",
      "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      "responseCode": "%RESPONSE_CODE%",
      "duration": "%DURATION%",
      "responseCodeDetails": "%RESPONSE_CODE_DETAILS%",
      "connectionTerminationDetails": "%CONNECTION_TERMINATION_DETAILS%",
      "responseDuration": "%RESPONSE_DURATION%",
      "requestDuration": "%REQUEST_DURATION%",
      "requestTXDuration": "%REQUEST_TX_DURATION%",
      "responseTXDuration": "%RESPONSE_TX_DURATION%",
      "downstreamHandshakeDuration": "%DOWNSTREAM_HANDSHAKE_DURATION%",
      "upstreamName": "%UPSTREAM_CLUSTER%",
      "traceId": "%REQ(X-B3-Traceid)%",
      "XforwardedFor": "%REQ(X-Forwarded-For)%",
      "responseFlags": "%RESPONSE_FLAGS%",
      "routeName": "%ROUTE_NAME%",
      "downstreamRemoteAddress": "%DOWNSTREAM_REMOTE_ADDRESS%",
      "downstreamDirectRemoteAddress": "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS%",
      "upstreamHost": "%UPSTREAM_HOST%",
      "upstreamLocalAddress": "%UPSTREAM_LOCAL_ADDRESS%",
      "upstreamRemoteAddress": "%UPSTREAM_REMOTE_ADDRESS%",
      "upstreamTransportFailureReason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
      "downstreamTransportFailureReason": "%DOWNSTREAM_TRANSPORT_FAILURE_REASON%",
      "downstreamLocalURISan": "%DOWNSTREAM_LOCAL_URI_SAN%",
      "downstreamLocalAddress": "%DOWNSTREAM_LOCAL_ADDRESS%",
      "connectionId": "%CONNECTION_ID%",
      "streamId": "%STREAM_ID%",
      "requestHeaders": "%DYNAMIC_METADATA(envoy.lua:request_headers)%",
      "requestBody": "%DYNAMIC_METADATA(envoy.lua:request_body)%",
      "responseHeaders": "%DYNAMIC_METADATA(envoy.lua:response_headers)%",
      "responseBody": "%DYNAMIC_METADATA(envoy.lua:response_body)%",
      "requestAttempts": "%REQ(X-ENVOY-ATTEMPT-COUNT)%",
      "requestHeadersBytes": "%REQUEST_HEADERS_BYTES%",
      "responseHeadersBytes": "%RESPONSE_HEADERS_BYTES%",
      "responseTrailersBytes": "%RESPONSE_TRAILERS_BYTES%",
      "bytesReceived": "%BYTES_RECEIVED%",
      "bytesSent": "%BYTES_SENT%",
      "upstreamRequestAttemptCount": "%UPSTREAM_REQUEST_ATTEMPT_COUNT%",
      "upstreamWireBytesSent": "%UPSTREAM_WIRE_BYTES_SENT%",
      "upstreamWireBytesReceived": "%UPSTREAM_WIRE_BYTES_RECEIVED%",
      "upstreamHeaderBytesSent": "%UPSTREAM_HEADER_BYTES_SENT%",
      "upstreamHeaderBytesReceived": "%UPSTREAM_HEADER_BYTES_RECEIVED%",
      "downstreamWireBytesSent": "%DOWNSTREAM_WIRE_BYTES_SENT%",
      "downstreamWireBytesReceived": "%DOWNSTREAM_WIRE_BYTES_RECEIVED%",
      "downstreamHeaderBytesSent": "%DOWNSTREAM_HEADER_BYTES_SENT%",
      "downstreamHeaderBytesReceived": "%DOWNSTREAM_HEADER_BYTES_RECEIVED%"
      }
  ingressService: istio-ingress-gateway
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      EXIT_ON_ZERO_ACTIVE_CONNECTIONS: "true"
    terminationDrainDuration: 30s
  enablePrometheusMerge: true
  enableTracing: false
  enableAutoMtls: true
  rootNamespace: istio-system
  trustDomain: "cluster.local"
  defaultHttpRetryPolicy:
    retries:
      attempts: 0

global:
  istioNamespace: istio-system
  certSigners:
    - clusterissuers.cert-manager.io/cloud-dns-issuer
  defaultPodDisruptionBudget:
    enabled: false
  defaultResources:
    requests:
      cpu: 10m
  hub: gcr.io/istio-release
  tag: 1.18.2
  variant: ""
  imagePullPolicy: ""
  imagePullSecrets: []
  istiod:
    enableAnalysis: false
  logAsJson: false
  logging:
    level: "default:info"
  omitSidecarInjectorConfigMap: false
  oneNamespace: false
  operatorManageWebhooks: false
  priorityClassName: ""
  proxy:
    image: proxyv2
    autoInject: enabled
    clusterDomain: "cluster.local"
    componentLogLevel: "misc:error"
    enableCoreDump: false
    excludeInboundPorts: ""
    includeInboundPorts: "*"
    includeIPRanges: "*"
    excludeIPRanges: ""
    includeOutboundPorts: ""
    excludeOutboundPorts: "15090"
    logLevel: warning
    privileged: false
    readinessFailureThreshold: 30
    readinessInitialDelaySeconds: 1
    readinessPeriodSeconds: 2
    resources:
      requests: null
      limits: null
    statusPort: 15020
    tracer: "zipkin"
    holdApplicationUntilProxyStarts: false
  tracer:
    zipkin:
      address: <zipkin_address>
  proxy_init:
    image: proxyv2
  remotePilotAddress: ""
  caAddress: istiod.istio-system.svc:15012
  externalIstiod: false
  configCluster: true
  jwtPolicy: "third-party-jwt"
  meshID: "<mesh_id>"
  mountMtlsCerts: true
  multiCluster:
    enabled: true
    clusterName: "<mycluster>"
  network: "<mycluster_network>"
  pilotCertProvider: istiod
  sds:
    token:
      aud: istio-ca
  useMCP: false
  caName: ""
  autoscalingv2API: true
base:
  enableIstioConfigCRDs: true
  validateGateway: false
  ```
