### ISSUE TITLE
Seems missmatch codestyle waypoint.yaml in manifests

### ISSUE THREAD

**Issue by ur-os** [istio/istio#52809]
```
 volumeMounts:
        - name: workload-socket
          mountPath: /var/run/secrets/workload-spiffe-uds
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /etc/istio/pod
          name: istio-podinfo
```

Looks incorrect style subsequence of paris name, mouthPath in first element of array  

https://github.com/istio/istio/blob/89d73dc1f639d1625135923c381e4ec222247059/manifests/charts/istio-control/istio-discovery/files/waypoint.yaml#L221
