### ISSUE TITLE
Proxy memory usage spike during startup

### ISSUE THREAD

**Issue by rravi-sift** [istio/istio#52802]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

During deployments, istio-proxy container gets `OOMKilled` and never starts. This was the proxy resource config
```
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 128Mi
```
We then increased the memory limit to 2G, and this worked. The proxy eventually starts but does get OOMKilled once or twice. We notice a spike in memory usage when the container starts but then falls back to normal usage. Could you help us debug this issue?

![image](https://github.com/user-attachments/assets/db872935-63d5-4dbf-9358-23c0693bb0fa)

### Version

```Text
❯ istioctl version
client version: 1.17.3
istiod version: 1.17.3
data plane version: 1.17.3 (204 proxies)

❯ kubectl version --short
Client Version: v1.27.15-dispatcher
Server Version: v1.27.12-gke.1115000
```
