### ISSUE TITLE
wasm  DispatchHttpCall: upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by mark8s** [istio/istio#52824]
I have a question for everyone. 

When I call `dashscope.aliyuncs.com`  in wasm, it reports

`Callback responseBody: upstream connect error or disconnect/reset before headers. reset reason: connection termination`

my logic:
```
headers = append(headers, [2]string{":method", method}, [2]string{":path", path}, [2]string{":authority", "dashscope.aliyuncs.com"}, [2]string{"accept", "*/*"}, [2]string{":scheme", "https"})
	proxywasm.LogInfof("Headers: %v", headers)
_, err := proxywasm.DispatchHttpCall("outbound|443||dashscope.aliyuncs.com", headers, body, nil, 30000, func(numHeaders, bodySize, numTrailers int) {
		respBody, err := proxywasm.GetHttpCallResponseBody(0, bodySize)
		if err != nil {
			proxywasm.LogCriticalf("failed to get response body: %v", err)
		}
		respHeaders, err := proxywasm.GetHttpCallResponseHeaders()
		if err != nil {
			proxywasm.LogCriticalf("failed to get response headers: %v", err)
		}
		proxywasm.LogInfof("CallResponseHeaders: %v", respHeaders)
		code := http.StatusBadGateway
		var normalResponse bool
		headers := make(http.Header)
		for _, h := range respHeaders {
			if h[0] == ":status" {
				code, err = strconv.Atoi(h[1])
				if err != nil {
					proxywasm.LogErrorf("failed to parse status: %v", err)
					code = http.StatusInternalServerError
				} else {
					normalResponse = true
				}
			}
			headers.Add(h[0], h[1])
		}
		proxywasm.LogDebugf("http call end, id: %s, code: %d, normal: %t, body: %s",
			requestID, code, normalResponse, respBody)
		callback(code, headers, respBody)
	})
```

Does anyone know what this could be?

My ServiceEntry Config:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: qwen
spec:
  hosts:
  - dashscope.aliyuncs.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: STATIC
  endpoints:
  - address: 47.93.243.29
```

When I curl `dashscope.aliyuncs.com` in `sleep` pod , I found that the IP address is wrong. It's strange. Is this a problem with my cluster? Can you tell me how to troubleshoot it?

The correct IP address should be 47.93.243.29, right?

![image](https://github.com/user-attachments/assets/58893e5d-dd14-4c6c-a7e6-90a38ec62682)
