### ISSUE TITLE
Force Gateway Api Manual deployments to have required lablels

### ISSUE THREAD

**Issue by Piroddi** [istio/istio#52828]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When deploying a Gateway Api manually as per documentation:

https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment

Native istio resources targeting this Gateway wont work unless the manual deployment has the following label:

`gateway.networking.k8s.io/gateway-name`

Therefore I think it make sense to have this label as a requirement for manual deployments

### Version

```Text
control plane version: 1.22.3
```

### Additional Information

Example: 

An `AuthorizationPolicy` with the following spec:

```
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: httpbin-gateway
 ```
 
 wont work unless the gateway deployment has been labeled correctly.
