### ISSUE TITLE
Skewed load distribution when destinationrule with `consistenthash`ing is enabled

### ISSUE THREAD

**Issue by SachinHg** [istio/istio#52871]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have 5 pods fronted by istio gateway and a corresponding virtualservice to route the traffic to these pods. I also have the below destinationrule applied which ensure stickiness based on consistent hashing done on a request header.
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
 name: httpbin
 namespace: httpbin
spec:
 host: httpbin.httpbin.svc.cluster.local
 trafficPolicy:
   loadBalancer:
     consistentHash:
       httpHeaderName: "custom-request-id"
```

When I make requests from mutliple clients parallelly with each client having a unique value for `"custom-request-id"`, I observe that the traffic is skewed towards some pods and the pattern of this inconsistency is not consistent as well. The subset of pods receiving majority of the traffic dont receive the same amount of traffic in the next run. In some runs, I observed that none of the calls land on few pods.

Could someone help me understand the below things:

1. Why do we see the skewness wrt load distribution?
2. What can be done to have a better load distribution?

Thanks

### Version

```Text
istioctl version
1.20.0

istio control plane version
1.20.3
istio dataplane version
1.20.3
k8s version
1.30
```
