### ISSUE TITLE
Istio intercepting connections to Google Cloud Storage on Kubernetes

### ISSUE THREAD

**Issue by emostafa** [istio/istio#5288]
Hi,

Kubernetes master version: 1.9.3-gke.0 
Istioctl version: 0.7.1

I have a small django app that connects to Google PubSub, Google Datastore and Google Cloud Storage. This application is deployed on GKE, the machines were created with the appropriate scopes and using automatic authentication for the client libraries. I installed istio-system as instructed in the documentation, added auto injection label to my namespace and deleted the pod to allow it to be recreated and proxy was injected successfully but the application failed to boot. Based on the logs it can't get the default application credentials (default service account for Google compute engine). After further investigation I found the proxy is blocking egress traffic. Creating an egress rule for metadata.google.internal didn't work but using the ip it worked. It's as follows:

```yaml
apiVersion: "config.istio.io/v1alpha2"                                            
kind: EgressRule                                                                  
metadata:                                                                         
  name: google-meta-egress-rule                                                   
spec:                                                                             
  destination:                                                                    
    service: "169.254.169.254"                                                    
  ports:                                                                          
    - port: 80                                                                    
      protocol: http
```

Now it doesn't crash but still not working. Failure related to connection Google Cloud Storage bucket. Add the following egress rule in hope it would fix it.

```yaml
apiVersion: config.istio.io/v1alpha2                                            
kind: EgressRule                                                                
metadata:                                                                       
  name: gooleapis-egress-rule                                                   
spec:                                                                           
  destination:                                                                  
      service: "*.googleapis.com"                                               
  ports:                                                                        
      - port: 443                                                               
        protocol: https                                                         
      - port: 80                                                                
        protocol: http
```

Also tried to inject the pod with --includeIPRanges with my cluster ips and still no luck.

I am not interested in tracking external calls. I would be satisfied by ignoring them, by allowing Google end points.

Thanks.

**Comment by Stono** [comment]
This is interesting as i'm on 0.7.1, and use `--includeIPRanges` to just cover the ranges of my cluster (as defined in https://cloud.google.com/kubernetes-engine/docs/how-to/ip-aliases) and I have a service which talks to GCS (and other external services) just fine.

Can you maybe paste some logs?

> Based on the logs it can't get the default application credentials (default service account for Google compute engine)

Are you mounting the application-credentials of the service account as a json jwt into your container and exposing them correctly?

**Comment by vadimeisenbergibm** [comment]
@emostafa Sorry, I saw your issue only now. Currently, Istio Egress Rules cover either HTTP-originated requests for domains with wildcards or HTTPS-originated requests for IP blocks.  HTTPS protocol in the egress rule means that the request is originated as HTTP and Istio performs TLS origination for it, forwarding the request by HTTPS.

The following rule will work only if you originate your request as HTTP, either to port 80 or to port 443.
```
apiVersion: config.istio.io/v1alpha2                                            
kind: EgressRule                                                                
metadata:                                                                       
  name: gooleapis-egress-rule                                                   
spec:                                                                           
  destination:                                                                  
      service: "*.googleapis.com"                                               
  ports:                                                                        
      - port: 443                                                               
        protocol: https                                                         
      - port: 80                                                                
        protocol: http
```

See examples at https://istio.io/docs/tasks/traffic-management/egress.html. 

Alternatively, you can use a TCP Egress Rule for HTTPS-originated traffic or any other TCP traffic, see this example https://istio.io/docs/tasks/traffic-management/egress-tcp.html. For TCP Egress Rule, you have to use an IP or IP block.

As yet another alternative, mentioned above, you can use `--includeIPRanges` option.

**Comment by emostafa** [comment]
Thanks you guys, adding the ips to the template worked.

**Comment by ldemailly** [comment]
for reference I access cloud storage using egress rules
by connecting on port 443 using http which is then forwarded and upgrad d to https by envoy, see istio/admin-sites fortio sub directory for an example

**Comment by owenhaynes** [comment]
I agree it isn't convenient at all when google uses many IP address for theses services

**Comment by ldemailly** [comment]
I was on the phone earlier but here is the link
https://github.com/istio/admin-sites/blob/master/fortio/fortio.yaml#L5-L14

**Comment by owenhaynes** [comment]
This only works if you have control of the code calling GCS, if using the generated api code provided by google this does not work

**Comment by thelinuxer** [comment]
I was having this problem with boto library and adding the ips to the injection istio-init configmap fixed it. Here's an excerpt of the configmap

```
....
      - name: istio-init                                                           
        image: docker.io/istio/proxy_init:0.7.1                                    
        args:                                                                      
        - "-p"                                                                     
        - {{ .MeshConfig.ProxyListenPort }}                                        
        - "-u"                                                                     
        - 1337                                                                     
        - "-i"                                                                                                                                                                                                     
        - "10.101.0.0/14,10.102.240.0/20"  
....
```

This was the only way it worked for me while using boto. I think egress rules worked properly with default google cloud client libraries but I am not sure.

**Comment by ldemailly** [comment]
> This only works if you have control of the code calling GCS, if using the generated api code provided by google this does not work

yes indeed

but this is improved in 0.8 I believe though I haven't followed the latest

**Comment by psandhu79** [comment]
I am seeing issues also using Istio 1.0 accessing the google default creaditionals to use pub/sub.

Should i be using the
 gcloud container clusters describe XXXXXXX --zone=XXXXXX | grep -e clusterIpv4Cidr -e 
servicesIpv4Cidr 

and inject these into the sidecar i would like to use the quick start guide
kubectl apply -f install/kubernetes/istio-demo.yaml

but i need to disable the side car installation correct ?

I am not sure where to find this example in the current source code

```
$ kubectl apply -f install/kubernetes/istio.yaml
$ ./install/kubernetes/webhook-create-signed-cert.sh \
    --service istio-sidecar-injector \
    --namespace istio-system \
    --secret sidecar-injector-certs
$ kubectl apply -f install/kubernetes/istio-sidecar-injector-configmap-release.yaml
$ cat install/kubernetes/istio-sidecar-injector.yaml | \
    ./install/kubernetes/webhook-patch-ca-bundle.sh > \
    install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml
$ kubectl apply -f install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml
$ kubectl apply -f install/kubernetes/addons/zipkin.yaml
$ kubectl apply -f ./install/kubernetes/addons/zipkin-to-stackdriver.yaml
```

**Comment by SaschaRodekamp** [comment]
Hi,
my current working solution to use 'google cloud storage' API with ISTIO 1.0. 

Two learning on my side :
- the name resolution for metadata.google.internal doesn't work. I had to use the IP address (anyway the IP is also hardcoded in the google oauth java client, so I feeling OK with that :) ).
- communication with the metaserver is done via http (not https). Thats why both ports (443 and 80) are configured. 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-google-api
spec:
  hosts:
  - storage.googleapis.com
  - 169.254.169.254 # metadata.google.internal
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: storage-tls-routing
spec:
  hosts:
  - storage.googleapis.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - storage.googleapis.com
    route:
    - destination:
        host: storage.googleapis.com
```

Hope that helps.
