### ISSUE TITLE
ambient based egress gateway - httpbin.org example - reset reason: protocol error

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#52935]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Setting up the ambient based egress gateway - loosely following https://www.solo.io/blog/egress-gateways-made-easy/ and https://istio.io/latest/docs/ambient/usage/waypoint/#deploy-a-waypoint-proxy

### Version

```Text
istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (13 proxies)

kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.29.7-eks-2f46c53
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1
```

### Additional Information

```yml
- altStatName: inbound-vip|80|http|httpbin.org;
  circuitBreakers:
    thresholds:
    - maxConnections: 4294967295
      maxPendingRequests: 4294967295
      maxRequests: 4294967295
      maxRetries: 4294967295
      trackRemaining: true
  commonLbConfig:
    localityWeightedLbConfig: {}
  connectTimeout: 10s
  dnsLookupFamily: V4_ONLY
  dnsRefreshRate: 60s
  lbPolicy: LEAST_REQUEST
  loadAssignment:
    clusterName: inbound-vip|80|http|httpbin.org
    endpoints:
    - lbEndpoints:
      - endpoint:
          address:
            socketAddress:
              address: httpbin.org
              portValue: 80
        loadBalancingWeight: 1
        metadata:
          filterMetadata:
            istio:
              workload: ;;;;
      loadBalancingWeight: 1
      locality: {}
  metadata:
    filterMetadata:
      istio:
        services:
        - host: httpbin.org
          name: httpbin.org
          namespace: istio-egress
        subset: http
  name: inbound-vip|80|http|httpbin.org
  respectDnsTtl: true
  transportSocket:
    name: internal_upstream
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.transport_sockets.internal_upstream.v3.InternalUpstreamTransport
      passthroughMetadata:
      - kind:
          host: {}
        name: envoy.filters.listener.original_dst
      transportSocket:
        name: raw_buffer
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
  type: STRICT_DNS
  typedExtensionProtocolOptions:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      explicitHttpConfig:
        http2ProtocolOptions: {}
```

error from curl:
curl httpbin.org/get -v
* Host httpbin.org:80 was resolved.
* IPv6: 2001:2::1b
* IPv4: 240.240.0.27
*   Trying 240.240.0.27:80...
* Connected to httpbin.org (240.240.0.27) port 80
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< content-length: 87
< content-type: text/plain
< date: Fri, 30 Aug 2024 01:16:14 GMT
< server: istio-envoy
< x-envoy-decorator-operation: :80/*
< 
* Connection #0 to host httpbin.org left intact
upstream connect error or disconnect/reset before headers. reset reason: protocol error

bug report:
[bug-report.tar.gz](https://github.com/user-attachments/files/16809053/bug-report.tar.gz)
