### ISSUE TITLE
How to setup Istio to ingress a gRPC

### ISSUE THREAD

**Issue by JCzz** [istio/istio#5295]
I am looking for a way to expose a grpc service - to connect an app to the service via grpc.

grpc_cli ls localhost:3000  does not work:
`Received an error when querying services endpoint. `

I can see something about specifying http2 or grpc, but unable to connect to the service.

Can you help?
 

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcd-test
  labels:
    app: gcd
spec:
  selector:
    matchLabels:
      app: gcd-test
  replicas: 1
  template:
    metadata:
      labels:
        app: gcd-test
    spec:
      containers:
      - name: gcd
        image: local/gcd
        imagePullPolicy: Never
        ports:
        - name: gcd-port
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-gcd
spec:
  # type: LoadBalancer
  selector:
    app: gcd
  ports:
  - port: 3000
    # targetPort: gcd-service

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcd-test
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: grpc-gcd
          servicePort: 3000
```
