### ISSUE TITLE
AuthorizationPolicy TCP traffic (namespaces and principals don't worked)

### ISSUE THREAD

**Issue by justlucknb** [istio/istio#53048]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello.
hi, please tell me why my AuthorizationPolicy dont work with TCP traffic (but work with HTTP)

I understand about HTTP headers (its not work for tcp), but why namespaces and principals are not taken?

1) Not worked for me
```
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
          name: xxx-policy
          namespace: xxx
    spec:
      selector:
        matchLabels:
          app: xxx-label
      action: ALLOW
      rules:
        - from:
          - source:
              namespaces:
              - xxx
          to:
            - operation:
                ports: ["5432"]
```

2) Not worked for me
```
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
          name: xxx-policy
          namespace: xxx
    spec:
      selector:
        matchLabels:
          app: xxx-label
      action: ALLOW
      rules:
        - from:
          - source:
              principals:
              - xx/xxx
          to:
            - operation:
                ports: ["5432"]
```
3) Worked for me

```
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
          name: xxx-policy
          namespace: xxx
    spec:
      selector:
        matchLabels:
          app: xxx-label
      action: ALLOW
      rules:
      - to:
            - operation:
                ports: ["5432"]
```

And also the question is why do I have to specify a selector to work with it?

1) Not woked with me
```
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
          name: xxx-policy
          namespace: xxx
    spec:
   # No selector
      action: ALLOW
      rules:
      - to:
            - operation:
                ports: ["5432"]
```

### Version

```Text
Istio v1.18
kubectl version        
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```
