### ISSUE TITLE
RequestAuthentication could cause duplicated payload sending to the upstream server with envoy ext-proc filter.

### ISSUE THREAD

**Issue by xr** [istio/istio#53061]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

## Problem

When enable both istio `RequestAuthentication` (at least one JWTRules) and envoy `ext-proc` filter, enabled over `envoyFilter` CRD, the upstream server got double buffering.

### 1. `RequestAuthentication` CRD:

```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: request-authentication
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: unity-gateway
  jwtRules:
    - issuer: https://test.com
      jwksUri: https://test.com/.well-known/jwks.json

```

### 2. EnvoyFilter patch:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-ext-proc
  namespace: test-ns
spec:
  workloadSelector:
    labels:
      app: test-gateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.jwt_authn
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            grpc_service:
              google_grpc:
                stat_prefix: ext_proc
                target_uri: test-side-server:20001
            processing_mode:
              request_body_mode: STREAMED
              request_header_mode: SEND
              response_body_mode: STREAMED
              response_header_mode: SEND

```

### 3. **_Note!!!_** you need to run the side stream server somewhere to match the`target_uri:test-side-server:20001` above.

here is one example of ext-proc side stream server implementation to use: https://gist.github.com/xr/94a6cb60e11028c837f46fac01ae37bd

### 4. Fake upstream server i used, image: https://hub.docker.com/r/liangular/fake-backend
shortcut for applying to cluster:
```
apiVersion: v1
kind: Service
metadata:
  name: fakebackend
  namespace: test-ns
  labels:
    app: fakebackend
    service: fakebackend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: fakebackend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebackend
  namespace: test-ns
  labels:
    app: fakebackend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebackend
      version: v1
  template:
    metadata:
      labels:
        app: fakebackend
        version: v1
    spec:
      containers:
        - image: liangular/fake-backend
          imagePullPolicy: Always
          name: fakebackend
          ports:
            - containerPort: 8080

```

**Note: All the virtual services, service entires etc are not included in the descriptions as they are not the key parts.**

Then just trigger a HTTP request like:
```
curl --location 'https://you-istio-cluster.com/' \
--header 'Content-Type: application/octet-stream' \
--data '@/path/to/file.bin'
```

The size of `file.bin` i used is `1048576` bytes.

### Results

Then you will see the upstream server is actually getting `2097152` bytes which is doubling the actual size.
```
received chunk length: 25520, total: 851968
received chunk length: 32768, total: 884736
received chunk length: 14496, total: 899232
received chunk length: 18272, total: 917504
received chunk length: 9664, total: 927168
received chunk length: 23104, total: 950272
received chunk length: 32768, total: 983040
received chunk length: 1208, total: 984248
received chunk length: 31560, total: 1015808
received chunk length: 32768, total: 1048576
received total payload size: 1048576
received chunk length: 11441, total: 11441
received chunk length: 19705, total: 31146
received chunk length: 19712, total: 50858
received chunk length: 9856, total: 60714
received chunk length: 19911, total: 80625
received chunk length: 8128, total: 88753
received chunk length: 12736, total: 101489
received chunk length: 7034, total: 108523
received chunk length: 9222, total: 117745
received chunk length: 9664, total: 127409
received chunk length: 14496, total: 141905
received chunk length: 4832, total: 146737
received chunk length: 9664, total: 156401
received chunk length: 9664, total: 166065
received chunk length: 19328, total: 185393
received chunk length: 27456, total: 212849
received chunk length: 11200, total: 224049
received chunk length: 9664, total: 233713
received chunk length: 19328, total: 253041
received chunk length: 9664, total: 262705
received chunk length: 9664, total: 272369
received chunk length: 9664, total: 282033
received chunk length: 28992, total: 311025
received chunk length: 9664, total: 320689
received chunk length: 19328, total: 340017
received chunk length: 19328, total: 359345
received chunk length: 9664, total: 369009
received chunk length: 19328, total: 388337
received chunk length: 9664, total: 398001
received chunk length: 19328, total: 417329
received chunk length: 19328, total: 436657
received chunk length: 19328, total: 455985
received chunk length: 9664, total: 465649
received chunk length: 14496, total: 480145
received chunk length: 14496, total: 494641
received chunk length: 9664, total: 504305
received chunk length: 19328, total: 523633
received chunk length: 19328, total: 542961
received chunk length: 9664, total: 552625
received chunk length: 9664, total: 562289
received chunk length: 19328, total: 581617
received chunk length: 9664, total: 591281
received chunk length: 9664, total: 600945
received chunk length: 19328, total: 620273
received chunk length: 9664, total: 629937
received chunk length: 19328, total: 649265
received chunk length: 9664, total: 658929
received chunk length: 9664, total: 668593
received chunk length: 13288, total: 681881
received chunk length: 16912, total: 698793
received chunk length: 15704, total: 714497
received chunk length: 30200, total: 744697
received chunk length: 19328, total: 764025
received chunk length: 9664, total: 773689
received chunk length: 28992, total: 802681
received chunk length: 28992, total: 831673
received chunk length: 32616, total: 864289
received chunk length: 30200, total: 894489
received chunk length: 15704, total: 910193
received chunk length: 15704, total: 925897
received chunk length: 33824, total: 959721
received chunk length: 6935, total: 966656
received chunk length: 16384, total: 983040
received chunk length: 16384, total: 999424
received chunk length: 16384, total: 1015808
received chunk length: 14496, total: 1030304
received chunk length: 18272, total: 1048576
received chunk length: 2808, total: 1051384
received chunk length: 54912, total: 1106296
received chunk length: 57728, total: 1164024
received chunk length: 60544, total: 1224568
received chunk length: 60544, total: 1285112
received chunk length: 4224, total: 1289336
received chunk length: 64768, total: 1354104
received chunk length: 53504, total: 1407608
received chunk length: 11264, total: 1418872
received chunk length: 64768, total: 1483640
received chunk length: 64768, total: 1548408
received chunk length: 63360, total: 1611768
received chunk length: 65536, total: 1677304
received chunk length: 65408, total: 1742712
received chunk length: 65536, total: 1808248
received chunk length: 28800, total: 1837048
received chunk length: 35200, total: 1872248
received chunk length: 64768, total: 1937016
received chunk length: 64768, total: 2001784
received chunk length: 65536, total: 2067320
received chunk length: 29832, total: 2097152
received total payload size: 2097152

```

From the ext-proc side stream server part, everything was good, it received in chunks and response properly:
```
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 28992, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 14496, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 14496, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 13288, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 16912, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 15704, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 30200, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 19328, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 9664, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 28992, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 28992, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 32616, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 30200, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 15704, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 15704, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 33824, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 6935, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 16384, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 16384, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 16384, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 14496, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 18272, endOfStream: false
Received request type: *ext_procv3.ProcessingRequest_RequestBody
Received request body size 0, endOfStream: true
Received end of stream
Received request type: *ext_procv3.ProcessingRequest_ResponseHeaders
Received request type: *ext_procv3.ProcessingRequest_ResponseBody
Stream closed by proxy
```

### Others findings
- Tests without any `JWTRules` or remove `RequestAuthentication` works fine
- Tests with pure Envoy + Envoy JWT authentication + ext-proc without patching with istio works fine.
- Replace `RequestAuthentication` with pure envoy [envoy.filters.http.jwt_authn](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto) works. (injected through istio envoyFilter crd)

### Envoy trace dumps

here is the logs from istio data plane envoy trace logs:
[log-trace-dump.txt](https://github.com/user-attachments/files/16936804/log-trace-dump.txt)

### Version

```Text
istio version: 1.23.0
k8s version: v1.27.11-gke.1062004
```

### Additional Information

Revision 1-23-0:
&version.MeshInfo{
    {
        Component: "istiod",
        Revision:  "1-23-0",
        Info:      version.BuildInfo{Version:"1.23.0", GitRevision:"d0ca037e58f90f58b38b33c5769fec25b6bfa9f3", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.0"},
    },
    {
        Component: "istiod",
        Revision:  "1-23-0",
        Info:      version.BuildInfo{Version:"1.23.0", GitRevision:"d0ca037e58f90f58b38b33c5769fec25b6bfa9f3", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.0"},
    },
    {
        Component: "istiod",
        Revision:  "1-23-0",
        Info:      version.BuildInfo{Version:"1.23.0", GitRevision:"d0ca037e58f90f58b38b33c5769fec25b6bfa9f3", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.0"},
    },
}
