### ISSUE TITLE
Error setting platform as global on gateway template after https://github.com/istio/istio/pull/52981

### ISSUE THREAD

**Issue by fjglira** [istio/istio#53077]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After this [PR](https://github.com/istio/istio/pull/52981). The changes done to the test logic inside the helm integration tests relies on the `istio.test.openshift` test flag to set the overrides Values to be used on the helm install command later, so, setting the helm values flag to `istio.test.kube.helm.values=global.platform=openshift,platform=openshift` will not work as expected because the resulting `values.yaml` is going to be for example:

```
cat /home/fedora/istio/prow/artifacts/helm-54806afa50bf4921a3374d5b0b/TestDefaultInstall/_test_context/helm-install-test2373458453/values.yaml

global:
  hub: image-registry.openshift-image-registry.svc:5000/istio-system
  tag: istio-testing
  variant: ""
  platform: openshift
```

With this values.yaml (with platform as global) when the helm install command is being set to install the ingress is not taking into account the avoid of setting `runAsUser` and `runAsgroup` here: https://github.com/istio/istio/blob/68dce232547af3103f271f19d5c8f75853eaac7b/manifests/charts/gateway/templates/deployment.yaml#L73

I see some possible solutions:
* Modify the scope of the var recently added into the helm test:
from this (In the correct places where is used inside the helm test): 
```
	overrideValuesStr := `
global:
  hub: %s
  tag: %s
  variant: %q
  %s
````
To this:
```
	overrideValuesStr := `
global:
  hub: %s
  tag: %s
  variant: %q
%s
```
Placing the `platform` in the correct place to be replaced later by the template

* Change the condition in the template to `{{- if not (eq .Values.global.platform "openshift") }}`
* Make additional changes to correctly accept the set of `values.platform=openshift`

Note: this was not happening because the profile yaml had before both variables by default:
```
global:
  platform: openshift
pilot:
  cni:
    enabled: true
    provider: "multus"
platform: openshift
```

```Text
Running the test from master branch
```
