### ISSUE TITLE
istio egress connection on port 22 for ssh traffic

### ISSUE THREAD

**Issue by bhat39a** [istio/istio#53095]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team,

We have a requirement to send all outbound TCP 22 (SSH), HTTP and HTTPS traffic through the istio egress gateway from an application running in Kubernetes to github.

We want to configure istio egress for ssh traffic on port 22(for github.com), we did the setup and can see connections are being forwarded from istio-proxy sidecar to istio-egressgateway pod but from istio-egressgateway can't see much movement. 

FYI our wildcard https egress is working fine, we are just facing issue with only tcp traffic.

_**Logs from istio-proxy sidecar container in the main pod**._

[2024-09-12T09:20:27.654Z] "- - -" 0 - - - "-" 42 0 2 - "-" "-" "-" "-" "10.232.64.202:3042" outbound|22|ssh-traffic|istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local 100.64.5.168:45872 4.208.26.197:22 100.64.5.168:55718 - -
[2024-09-12T09:20:27.668Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "10.232.64.202:3042" outbound|22|ssh-traffic|istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local 100.64.5.168:45876 4.208.26.197:22 100.64.5.168:55724 - -
[2024-09-12T09:20:27.681Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "10.232.64.202:3042" outbound|22|ssh-traffic|istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local 100.64.5.168:45880 4.208.26.197:22 100.64.5.168:55738 - -
[2024-09-12T09:20:27.693Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "10.232.64.202:3042" outbound|22|ssh-traffic|istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local 100.64.5.168:45896 4.208.26.197:22 100.64.5.168:55744 - -
[2024-09-12T09:20:27.705Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "10.232.64.202:3042" outbound|22|ssh-traffic|istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local 100.64.5.168:45904 4.208.26.197:22 100.64.5.168:55760 - -

_**Logs from the istio-egressgateway pod**_

[2024-09-12T09:20:27.655Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "envoy://sni_listener/" sni_cluster envoy://internal_client_address/ 10.232.64.202:3042 100.64.5.168:45872 - -
[2024-09-12T09:20:27.669Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "envoy://sni_listener/" sni_cluster envoy://internal_client_address/ 10.232.64.202:3042 100.64.5.168:45876 - -
[2024-09-12T09:20:27.682Z] "- - -" 0 - - - "-" 42 0 0 - "-" "-" "-" "-" "envoy://sni_listener/" sni_cluster envoy://internal_client_address/ 10.232.64.202:3042 100.64.5.168:45880 - -
[2024-09-12T09:20:27.694Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "envoy://sni_listener/" sni_cluster envoy://internal_client_address/ 10.232.64.202:3042 100.64.5.168:45896 - -
[2024-09-12T09:20:27.706Z] "- - -" 0 - - - "-" 42 0 1 - "-" "-" "-" "-" "envoy://sni_listener/" sni_cluster envoy://internal_client_address/ 10.232.64.202:3042 100.64.5.168:45904 - -

Below is our configuration for SSH traffic. Could you please have a look and let us know if we are missing anything. 

```
---
apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway-for-tcp-svc
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    istio: egressgateway
  ports:
  - port: 22
    name: tcp22
    targetPort: 3042
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-for-tcp
  namespace: istio-system 
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 22
        name: ssh
        protocol: TCP
      hosts:
        - github.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ssh-tcp22
  namespace: istio-system 
spec:
  host: istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local
  subsets:
    - name: ssh-traffic
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tcp22-se
  namespace: istio-system  
spec:
  hosts:
    - github.com
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-ssh-tcp22-through-egress-gateway
  namespace: istio-system 
spec:
  hosts:
    - github.com
  gateways:
    - mesh
    - istio-egressgateway-for-tcp
  tcp:
    - match:
        - gateways:
            - mesh
          port: 22
      route:
        - destination:
            host: istio-egressgateway-for-tcp-svc.istio-system.svc.cluster.local
            subset: ssh-traffic
            port:
              number: 22
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway-for-tcp
          port: 22
      route:
        - destination:
            host: github.com
            port:
              number: 22
          weight: 100

```

### Version

```Text
% istioctl version                     
client version: 1.22.1
control plane version: 1.23.0
data plane version: 1.23.0 (5 proxies)
%
```
