### ISSUE TITLE
[Ambient mode]Application failedhealthness checks(liveness, readiness, startup), no NetworkPolicy configured

### ISSUE THREAD

**Issue by Yufeireal** [istio/istio#53105]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi team, 
I am currently rolling out Ambient mesh to our cluster, hit very weird issues. When I add label to the deployment: `istio.io/dataplane-mode: ambient` and roll it out. The new pods will fail every configured probes. I've read this article and some related issue, doesn't seem to be a match as we don't have a networkpolicy configured in that namespace.

Workload:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vonline
    app.kubernetes.io/instance: vonline
    appInst: vonline
    cost_center: vonline
    tags.datadoghq.com/service: vonline
  name: vonline
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      appInst: vonline
  strategy:
    rollingUpdate:
      maxSurge: 5%
      maxUnavailable: 5%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        admission.datadoghq.com/enabled: "true"
        app: vonline
        appInst: vonline
        cost_center: vonline
        istio.io/dataplane-mode: ambient
        tags.datadoghq.com/service: vonline
    spec:
      containers:
      - env:
        - name: CLUSTER
          value: staging2
        - name: GOMAXPROCS
          value: "1"
        - name: JWT_ENABLED
          value: "true"
        image: xxx
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "25"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        name: vonline
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config
          name: config
        - mountPath: /var/run/secrets/cross_server_tokens
          name: cross-server-tokens
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: vonline
      serviceAccountName: vonline
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            appInst: vonline
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      volumes:
      - configMap:
          defaultMode: 420
          name: vonline-config-4b445d7
        name: config
      - name: cross-server-tokens
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: verkada
              expirationSeconds: 7200
              path: verkada
          - serviceAccountToken:
              audience: vonline
              expirationSeconds: 7200
              path: vonline
          - serviceAccountToken:
              audience: remotesh
              expirationSeconds: 7200
              path: remotesh
          - serviceAccountToken:
              audience: globaldevice
              expirationSeconds: 7200
              path: globaldevice
```

ztunnel logs:

istio-cni-node logs:

```
contexts:
- context:
    cluster: local
    user: istio-cni
  name: istio-cni-context
current-context: istio-cni-context
kind: Config
preferences: {}
users:
- name: istio-cni
  user:
    token: REDACTED

2024-09-12T04:53:04.695695Z	info	install	install/install.go:72	missing (or invalid) configuration detected, (re)writing CNI config file at
2024-09-12T04:53:04.695718Z	info	install	install/cniconfig.go:105	Using CNI config template from CNI_NETWORK_CONFIG environment variable.
2024-09-12T04:53:04.695737Z	info	install	install/cniconfig.go:124	CNI config: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "debug",
  "log_uds_address": "/var/run/istio-cni/log.sock",
  "ambient_enabled": true,
  "cni_event_address": "/var/run/istio-cni/pluginevent.sock",
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "kube-system" ]
  }
}
2024-09-12T04:53:04.695948Z	info	install	install/cniconfig.go:217	CNI config file /host/etc/cni/net.d/10-aws.conflist exists. Proceeding.
2024-09-12T04:53:04.696331Z	info	install	install/cniconfig.go:166	Created CNI config /host/etc/cni/net.d/10-aws.conflist
2024-09-12T04:53:04.696365Z	info	install	install/install.go:97	Installation succeed, start watching for re-installation.
2024-09-12T04:53:04.798242Z	info	cni-agent	nodeagent/ztunnelserver.go:196	received hello from ztunnel. V1
2024-09-12T04:53:04.798283Z	info	cni-agent	nodeagent/ztunnelserver.go:341	Sending local pod 95e68d91-3261-4fa9-8b97-5ed84871f606 ztunnel
2024-09-12T04:57:36.688571Z	info	cni-agent	nodeagent/net.go:137	adding pod to the mesh	ns=default name=vonline-56dcd96c94-rbnrn
2024-09-12T04:57:36.689090Z	info	iptables	iptables/iptables.go:416	Running iptables-legacy-restore with the following input:
* nat
-N ISTIO_OUTPUT
-A OUTPUT -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -d 169.254.7.127 -p tcp -m tcp -j ACCEPT
-A ISTIO_OUTPUT -p tcp -m mark --mark 0x111/0xfff -j ACCEPT
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -j ACCEPT
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -p tcp -m mark ! --mark 0x539/0xfff -j REDIRECT --to-ports 15001
COMMIT
* mangle
-N ISTIO_PRERT
-N ISTIO_OUTPUT
-A PREROUTING -j ISTIO_PRERT
-A OUTPUT -j ISTIO_OUTPUT
-A ISTIO_PRERT -m mark --mark 0x539/0xfff -j CONNMARK --set-xmark 0x111/0xfff
-A ISTIO_PRERT -s 169.254.7.127 -p tcp -m tcp -j ACCEPT
-A ISTIO_PRERT ! -d 127.0.0.1/32 -p tcp -i lo -j ACCEPT
-A ISTIO_PRERT -p tcp -m tcp --dport 15008 -m mark ! --mark 0x539/0xfff -j TPROXY --on-port 15008 --tproxy-mark 0x111/0xfff
-A ISTIO_PRERT -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ISTIO_PRERT ! -d 127.0.0.1/32 -p tcp -m mark ! --mark 0x539/0xfff -j TPROXY --on-port 15006 --tproxy-mark 0x111/0xfff
-A ISTIO_OUTPUT -m connmark --mark 0x111/0xfff -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
COMMIT
2024-09-12T04:57:36.689157Z	info	dependencies/implementation_linux.go:253	Running command (with wait lock): iptables-legacy-restore --noflush -v --wait=30
2024-09-12T04:57:36.692380Z	info	cni-agent	nodeagent/ztunnelserver.go:313	sending pod add to ztunnel	id=b1f7b4f0-5ace-42d7-9725-f1d0461bbbb7 name=vonline-56dcd96c94-rbnrn namespace=default serviceAccount=vonline
```

### Version

```Text
client version: 1.22.4
control plane version: 1.22.3
data plane version: 1.22.3 (173 proxies), 1.22.4 (12 proxies)

Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.30.3-eks-2f46c53
```

### Additional Information

We're running AWS EKS
CNI is Amazon CNI
