### ISSUE TITLE
require different image hubs in wasmplugin

### ISSUE THREAD

**Issue by MaYuan-02** [istio/istio#53123]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
I am deploying Istio in primary-remote mode, and my two data plane clusters are in different network environments where they cannot access the public Internet. I need to use a WASM plugin to implement some extended capabilities, but the image hub URIs for the two clusters are different. For example, the URI for Cluster A is `registry.region-a.com/wasm/plugin:latest`, while for Cluster B, it is `registry.region-b.com/wasm/plugin:latest`. 

Is it possible to support automatically using different image URIs to pull the WASM binaries in different network environments? For instance, we could use `${REGION}` in the URI to reference the `environmentVariables` field configured in the ProxyConfig. This would perfectly solve the issue.
example: 
```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test-wasm
  namespace: istio-system
spec:
  imagePullPolicy: IfNotPresent
  imagePullSecret: secret-wasm
  selector:
    matchLabels:
      istio: ingressgateway
  url: registry.${REGION}/wasm/plugin:latest
  phase: AUTHN
```
