### ISSUE TITLE
mTLS with External API

### ISSUE THREAD

**Issue by MarcoDelGamba** [istio/istio#53168]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

### Brief Summary
Currently trying to establish a mTLS connection with an external API but I keep getting the following 503 error:
`TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end.
`

I expect the app to make a plain HTTP request which is intercepted by the sidecar from which the mTLS session is originated.

I tested this with istio versions 1.20.2 and 1.23.0.

I also mounted the client-credential secret containing the client cert and key and the server ca inside the envoy and reference all of them as local files in the destination rule but nothing changed.

Everything is deployed via Helm.

### Current Setup

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    <some_annotations>
  labels:
    component: idocs-adapter-bead
    <some_other_label>
  name: <application_destination_rule>
  namespace: <application_namespace>
spec:
  host: <external_api>
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 80
        tls:
          credentialName: client-credential
          mode: MUTUAL
  workloadSelector:
    matchLabels:
      component: idocs-adapter-bead # label present on the pod
```
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  annotations:
    meta.helm.sh/release-name: idocs-adapter-bead
    meta.helm.sh/release-namespace: development-idocs-adapter
  creationTimestamp: '2024-09-17T07:29:04Z'
  generation: 3
  labels:
    component: idocs-adapter-bead
    <other_labels>
  name: <service-entry-name>
  namespace: <application_namespace>
  hosts:
    - <external_api>
  ports:
    - name: http-port
      number: 80
      protocol: HTTP
      targetPort: 443
    - name: https-port
      number: 443
      protocol: HTTPS
  resolution: DNS
```

 istioctl proxy-config secret deploy/idocs-adapter-bead-deployment -n development-idocs-adapter 
RESOURCE NAME                      TYPE           STATUS     VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE
kubernetes://client-credential     Cert Chain     ACTIVE     true           8f64256012cb67c242a1b992f842224      2026-01-26T22:59:59Z     2024-01-26T17:30:55Z
default                            Cert Chain     ACTIVE     true           a42196793bf894b19ad9caeda777ae57     2024-09-18T12:48:27Z     2024-09-17T12:46:27Z
ROOTCA                             CA             ACTIVE     true           b2a8c80f5c3b2efeb1748998eb2d294d     2034-04-17T11:00:08Z     2024-04-19T11:00:08Z

istioctl analyze -n development-idocs-adapter                                                 
Warning [IST0129] (DestinationRule development-idocs-adapter/idocs-adapter-bead-serviceentry) DestinationRule development-idocs-adapter/idocs-adapter-bead in namespace development-idocs-adapter has TLS mode set to MUTUAL but no caCertificates are set to validate server identity for host: <external_api> at port number:80

Even if the ca certificate is present inside the secret

### From Postman
The REST API call works fine from postman. I added the Server CA and Intermediate and the client certificate and key. I get 200 as a result.

### Conclusion
Has anyone faced the same issue?
Thank you in advance

Marco

### Version

```Text
istioctl version:
client version: 1.21.0
control plane version: 1.23.0
data plane version: 1.20.2 (111 proxies), 1.23.0 (1 proxies)

kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7-eks-2f46c53

helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```
