### ISSUE TITLE
cannot do grpc (delayed connect error: 111)

### ISSUE THREAD

**Issue by perezjasonr** [istio/istio#53162]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

heres the full error:

`upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: delayed connect error: 111`

for context, i have 2 grpc services running and reachable via istio igw. they are exposed in identical manner shown below. for some reason one works and one does not. but if i kubectl port-forward they both work.

ingress gateway logs:

```
[2024-09-16T15:01:44.563Z] "POST /frostcore.v2.FrostCore/is_initialized HTTP/2" 200 URX,UF **upstream_reset_before_response_started{remote_connection_failure,delayed_connect_error:_111}** - "delayed_connect_error:_111" 12 0 37 - "10.1.81.33" "grpcurl/v1.9.1 grpc-go/1.61.0" "ad2dee26-65cf-99e9-9c66-b577a956a41a" "10.1.20.65:80" "10.66.2.21:50051" **outbound|50051||frost-core-service.frostbite.svc.cluster.local** - 10.66.229.180:8080 10.1.81.33:54834 - - traceID=3149b9a55a785369d6e1757fb20559ad


[2024-09-16T15:01:51.797Z] "POST /frostcore.v2.FrostCore/get_active_connections HTTP/2" 200 URX,UF **upstream_reset_before_response_started{remote_connection_failure,delayed_connect_error:_111}** - "delayed_connect_error:_111" 12 0 59 - "10.1.81.33" "grpcurl/v1.9.1 grpc-go/1.61.0" "d65cce1a-98f9-9e12-b44c-c3f2ff701ab3" "10.1.20.65:80" "10.66.2.21:50051" **outbound|50051||frost-core-service.frostbite.svc.cluster.loca**l - 10.66.229.180:8080 10.1.81.33:4642 - - traceID=b9d1bfe796ab6869ad49f29d0096e28c
2024-09-16T15:07:50.985784Z     info    xdsproxy        connected to delta upstream XDS server: istiod.istio-system.svc:15012   id=616


THE BELOW WORKS, NO ERROR, FOR SOME REASON EVEN THOUGH ITS THE SAME GATEWAY, VS, SVC SETUP


[2024-09-16T15:08:26.482Z] "POST /frostrbd.FrostRBD/list_pools HTTP/2" 200 - via_upstream - "-" 5 81 145 - "10.1.81.33" "grpcurl/v1.9.1 grpc-go/1.61.0" "4f377876-c3fb-9ee7-8f69-d9d7ce15dd43" "10.1.20.65:80" "10.66.2.48:50051" **outbound|50051||grpc-poc.frostbite.svc.cluster.local** 10.66.229.180:34828 10.66.229.180:8080 10.1.81.33:15380 - - traceID=5608457ccb784520ccd39f16b436090f
```

this setup fails:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grpc-poc-frost-core
  namespace: frostbite
spec:
  gateways:
  - frostbite/frostbite-gw
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /frostcore.v2.FrostCore/
    route:
    - destination:
        host: frost-core-service
        port:
          number: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: frost-core-service
  namespace: frostbite
spec:
  clusterIP: 10.105.111.2
  clusterIPs:
  - 10.105.111.2
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: grpc
    name: frost-core-grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: frost-core
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

and for some reason this setup works

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grpc-poc
  namespace: frostbite
spec:
  gateways:
  - frostbite/frostbite-gw
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /frostrbd.FrostRBD/
    route:
    - destination:
        host: grpc-poc
        port:
          number: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-poc
  namespace: frostbite
spec:
  clusterIP: 10.98.81.202
  clusterIPs:
  - 10.98.81.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: grpc
    name: frostrbd-grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: frostrbd
    app.kubernetes.io/name: frostrbd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
  
```
  
i have tried different things to try to isolate the difference, i moved the workload to the same node, they are in the same namespace, using the same gw/istio-igw. cannot figure out for the life of me why one works and one doesn't, and why they both work when doing port-forward > svc

```
kubectl port-forward -n frostbite service/frost-core-service 50051:50051
Forwarding from 127.0.0.1:50051 -> 50051
grpcurl -import-path /protos -proto core.proto -plaintext -d '{"vm_name": "FT01a"}' 127.0.0.1:50051 frostcore.v2.FrostCore/get_active_connections
{}       # <--- expected response

grpcurl -import-path /protos -proto core.proto -plaintext -d '{"vm_name": "FT01a"}' 127.0.0.1:50051 frostcore.v2.FrostCore/is_initialized
{
  "initialization": "NOT_INITIALIZED"
}
# ^ expected response
```

the strangest part is that even on the failing service i can get list and describe to work

```
./grpcurl -import-path protos -proto core.proto --plaintext 10.1.20.65:80 list frostcore.v2.FrostCore
frostcore.v2.FrostCore.get_active_connections
frostcore.v2.FrostCore.get_active_processes
frostcore.v2.FrostCore.get_os_version
frostcore.v2.FrostCore.get_pdbinfo
frostcore.v2.FrostCore.initialize_introspection
frostcore.v2.FrostCore.is_initialized



./grpcurl -import-path protos -proto core.proto --plaintext 10.1.20.65:80 describe frostcore.v2.FrostCore
frostcore.v2.FrostCore is a service:
service FrostCore {
  rpc get_active_connections ( .frostcore.v2.VMRequest ) returns ( .frostcore.v2.ActiveConnections );
  rpc get_active_processes ( .frostcore.v2.VMRequest ) returns ( .frostcore.v2.ActiveProcesses );
  rpc get_os_version ( .frostcore.v2.VMRequest ) returns ( .frostcore.v2.OSVersion );
  rpc get_pdbinfo ( .frostcore.v2.GetPDBInfo ) returns ( .frostcore.v2.PDBInfo );
  rpc initialize_introspection ( .frostcore.v2.InitializeIntrospection ) returns ( .frostcore.v2.Initialization );
  rpc is_initialized ( .frostcore.v2.VMRequest ) returns ( .frostcore.v2.Initialization );
}


./grpcurl -import-path protos -proto core.proto --plaintext 10.1.20.65:80 describe frostcore.v2.FrostCore.get_active_connections
frostcore.v2.FrostCore.get_active_connections is a method:
rpc get_active_connections ( .frostcore.v2.VMRequest ) returns ( .frostcore.v2.ActiveConnections );
```

and finally if i use -v for verbosity, it even acknowledges via method descriptor what im trying to reach. why would one work and not the other they have identical setups

```
./grpcurl -v -import-path protos -proto core.proto -plaintext -d '{"vm_name": "FT01a"}' 10.1.20.65:80 frostcore.v2.FrostCore/is_initialized
                                                                                                                                                        Resolved method descriptor:
rpc is_initialized ( .frostcore.v2.VMRequest ) returns ( .frostcore.v2.Initialization );

Request metadata to send:
(empty)
                                                                                                                                                        Response headers received:
(empty)

Response trailers received:
content-type: application/grpc
date: Mon, 16 Sep 2024 20:09:47 GMT
Sent 1 request and received 0 responses
ERROR:
  Code: Unavailable
  Message: upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: delayed connect error: 111
```

I'm kindof at wits end here, normally id question the app/image itself, but port-forward is working just fine.

### Version

```Text
istio version: 1.22.3

kubernetes version:

Client Version: v1.28.12
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.12

other notes:

ENABLE_NATIVE_SIDECARS is true with the appropriate featureGate also set to true, we are using istio-cni
```
