### ISSUE TITLE
Ambient will not send HBONE to hostPort calls

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53176]
Example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
      - name: echo
        image: gcr.io/istio-testing/app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          hostPort: 12345
        args:
        - --port=80
        env:
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  internalTrafficPolicy: Local
  selector:
    app: echo
  ports:
  - name: http
    port: 80
```

Call `HOST:12345` and mTLS will not be used.

In theory we could detect the hostPort allocation and be smart enough to do mTLS, though likely we should continue the existing behavior, and treat it as a hostNetwork pod. In that case, this issue is mostly a tracker to let users find this
