### ISSUE TITLE
Setting ENABLE_AUTO_SNI to "false" dosen't work as expected

### ISSUE THREAD

**Issue by DMSwimTech** [istio/istio#53186]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Following discussion https://github.com/istio/istio/issues/50126#issuecomment-2352274883 I created ticket regards ssl certificate verification issue. 

From istio version 1.21 we had stumble across certificate verification issue when it comes to accessing external-mesh resources via serviceEntry.

I'm deploying istio with the istiod helm chart, with the following values

```
compatibilityVersion: ""
pilot:
  autoscaleMax: 1
  autoscaleMin: 3
proxyMetadata:
  ISTIO_DELTA_XDS: true
```

Here is the VirtualService, ServiceEntry and DestinationRule 

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: example
  namespace: example
spec:
  gateways:
  - ingress/ingress
  hosts:
  - custom_domain.com
  http:
  - route:
    - destination:
        host: example_external.com
        port:
          number: 443
```

Destination Rule:
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: example
  namespace: example
spec:
  host: example_external.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```

ServiceEntry:

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: example
  namespace: example
spec:
  hosts:
  - example_external.com
  location: MESH_EXTERNAL
  ports:
  - name: service-http
    number: 443
    protocol: HTTP
  resolution: DNS
```

The above got ssl validation to fail since the update to 1.21. The workaround we found was to do the following:

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: example
  namespace: example
spec:
  host: example_external.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: example_external.com
```

Implementing it on a wide cluster setup with `ENABLE_AUTO_SNI=false` didn't work. We tried to supplied the following values file:
```
pilot:
  autoscaleMax: 1
  autoscaleMin: 3
  env:
    ENABLE_AUTO_SNI: "false"
```

I know the certificate of `example_external.com` because it's a provided domain from our cloud provider (managed service).

The current workarond that works for us is the following:
```
pilot:
  autoscaleMax: 1
  autoscaleMin: 3
  env:
    VERIFY_CERTIFICATE_AT_CLIENT: "false"
```

### Version

```Text
istio version

client version: 1.23.0
control plane version: 1.23.1
data plane version: 1.23.1 (137 proxies)
```

kube version

```
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.3-gke.1639000
```
```


### Additional Information

_No response_
