### ISSUE TITLE
gwapi: dots in Gateway listener names prevent LDS & RDS syncing

### ISSUE THREAD

**Issue by lukassup** [istio/istio#53200]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using [Gateway API](https://gateway-api.sigs.k8s.io/) to create a [Gateway](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Gateway) and setting listener to include dots (`.`) in the listener name Service is never created and Ingress Gateways do not receive LDS and RDS updates:

## Example output

Gateway

```yml
# gateway.yml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.example.com'
    name: example.com
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.example.com'
    name: example.com-ssl
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: example.com
      mode: Terminate
```

Output

```
% kubectl get gtw -n istio-ingress
NAME               CLASS   ADDRESS   PROGRAMMED   AGE
internal-gateway   istio             False        9d

% kubectl get svc -n istio-ingress
No resources found in istio-ingress namespace.

% istioctl pc listeners internal-gateway-istio-5dfcc558df-jk9ct.istio-ingress
ADDRESSES PORT  MATCH DESTINATION
0.0.0.0   15021 ALL   Inline Route: /healthz/ready*
0.0.0.0   15090 ALL   Inline Route: /stats/prometheus*

% istioctl ps --namespace istio-ingress
<...>
internal-gateway-istio-5dfcc558df-jk9ct.istio-ingress  cluster       SYNCED (7s)        SYNCED (7s)        SYNCED (6s)        IGNORED            IGNORED     istiod-5585b6f675-5j7ff     1.23.1
```

### Fix

Replacing all dots (`.`) in listener `name` field to dashes (`-`) fixes the issue:

```yml
# gateway.yml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.example.com'
    name: http-example-com
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.example.com'
    name: https-example-com
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: example.com
      mode: Terminate
```

Output

```
% kubectl get gateway -n istio-ingress
NAME               CLASS   ADDRESS   PROGRAMMED   AGE
internal-gateway   istio             False        87s

% kubectl get svc -n istio-ingress
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                      AGE
internal-gateway-istio   LoadBalancer   10.126.135.231   <pending>     15021:32746/TCP,80:32598/TCP,443:31225/TCP   82s

% istioctl proxy-status --namespace istio-ingress
NAME                                                      CLUSTER     CDS             LDS             EDS             RDS             ECDS        ISTIOD                      VERSION
internal-gateway-istio-5dfcc558df-ek9ct.istio-ingress  cluster       SYNCED (1s)     SYNCED (1s)     SYNCED (0s)     SYNCED (1s)     IGNORED     istiod-5585b6f675-gxd6d     1.23.1

```

Note that RDS is now in `SYNCED` state.

### Version

```Text
Gateway API version:

% kubectl get crd gateways.gateway.networking.k8s.io -o jsonpath="{.metadata.annotations['gateway\.networking\.k8s\.io\/bundle-version']}"
v1.1.0

% istioctl version
client version: 1.23.1
control plane version: 1.23.1
data plane version: 1.20.5 (1 proxies), 1.22.2 (617 proxies), 1.23.1 (793 proxies)

% kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.27.15
WARNING: version difference between client (1.31) and server (1.27) exceeds the supported minor version skew of +/-1
```
