### ISSUE TITLE
Istio Kubernetes Gateway API cannot find route entry

### ISSUE THREAD

**Issue by Silvest89** [istio/istio#53216]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

One random listener stops working (It changes randomly whenever I kill the gateway pod)

This is how my gateway spec looks like (they all use the same base domain):
The wildcard listener routes always work. But the bypass-listener and harbor-listener take turns into working (killing the gateway pod and it switches randomly)

```
    - name: wildcard-listener
      protocol: HTTPS
      hostname: "*.test.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-test-dev-mtls
        options:
          gateway.istio.io/tls-terminate-mode: MUTUAL
      port: 443
      allowedRoutes:
        namespaces:
          from: All
    - name: bypass-listener
      hostname: "nextcloud.test.dev"
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-test-dev-tls
      port: 443
      allowedRoutes:
        namespaces:
          from: All
    - name: harbor-listener
      hostname: "harbor.test.dev"
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-test-dev-tls
      port: 443
      allowedRoutes:
        namespaces:
          from: All
```

```
2024-09-20 10:47:00.357Z 2024-09-20T10:47:00.357198Z    debug   envoy filter source/extensions/filters/http/alpn/alpn_filter.cc:61      cannot find route entry thread=23
2024-09-20 10:47:00.357Z 2024-09-20T10:47:00.357232Z    debug   envoy router external/envoy/source/common/router/router.cc:457  [Tags: "ConnectionId":"707","StreamId":"8854065204894526130"] no route match for URL '/index.php/apps/files/preview-service-worker.js' thread=23
2024-09-20 10:47:00.357Z 2024-09-20T10:47:00.357256Z    debug   envoy http external/envoy/source/common/http/filter_manager.cc:1025     [Tags: "ConnectionId":"707","StreamId":"8854065204894526130"] Preparing local reply with details route_not_found       thread=23
```

### Version

```Text
client version: 1.23.1
control plane version: 1.23.1
data plane version: 1.23.1 (1 proxies)
```

**Comment by hzxuzhonghu** [comment]
How did you define the route rules, looks there is a conflct there

**Comment by Silvest89** [comment]
> How did you define the route rules, looks there is a conflct there

Routes are pretty plain. The istio gateway pods probably checks intermittently picks the wildcard listener becaues of hostname: "*.test.dev" but it should only happen when there is not a specific specification. Furthermore I specifically say sectionName: "bypass-listener"

```
  hostnames:
    - nextcloud.test.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: tls-gateway
      namespace: gateway
      sectionName: bypass-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: nextcloud
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```

```
  hostnames:
    - harbor.test.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: tls-gateway
      namespace: gateway
      sectionName: harbor-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: harbor
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```
