### ISSUE TITLE
[RequestAuthentication] - ClaimToHeader overrides already existing header even if the header is not present in JWT

### ISSUE THREAD

**Issue by mamilic** [istio/istio#53212]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've setup the RequestAuthentication as follows

```
jwtRules:
  - forwardOriginalToken: false
    issuer: "https://test.com"
    outputClaimToHeaders:
    - claim: "test"
      header: "x-user-id-as"
```

I've tried 2 scenarios. 
- JWT is not present in request, I've put **x-user-id-as** header with value **test**, and in the Spring Boot service after the RequestAuthentication the header **x-user-id-as** is not present, which means that RequestAuthentication somehow removed it if I specify the mentioned header in **outputClaimToHeaders**
- JWT is present but does not have **x-user-id-as**, again it is the same scenario, even if the header is not present in provided JWT, the header is removed

Is this behaviour intened?

### Version

```Text
$kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0
$istioctl version
client version: 1.23.1
control plane version: 1.23.0
data plane version: 1.23.0 (2 proxies)
```
