### ISSUE TITLE
Help request: HTTP2 Ingress

### ISSUE THREAD

**Issue by 2ZZ** [istio/istio#53235]
I want to enable HTTP2 on traffic coming in via the Istio ingress gateways.

`[client] --HTTP2--> [istio-ingressgateway] --HTTP-or-HTTP2--> [any target]`

I tried configuring the gateway port protocol as HTTP2 and created a destination rules with h2UpgradePolicy, but the traffic remains on HTTP1/1.

This is an example GW/VS I have been testing

```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: example
spec:
  selector:
    istio: my-nlb-ingressgateway
  servers:
  - hosts:
    - mywebsite.com
    port:
      name: http
      number: 80
      protocol: HTTP2
  - hosts:
    - mywebsite.com
    port:
      name: https
      number: 443
      protocol: HTTP2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example
spec:
  exportTo:
  - istio-system
  gateways:
  - example
  hosts:
  - mywebsite.com
  http:
  - route:
    - destination:
        host: mywebsite.com.s3.us-east-1.amazonaws.com
        port:
          number: 80
```

And this is my destination rule

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example
spec:
  host: mywebsite.com
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
``` 

And my test showing HTTP/1.1 still in use

```
curl -v -k --http2 https://mywebsite.com
*   Trying 1.2.3.4:443...
* Connected to mywebsite.com (1.2.3.4) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: mywebsite.com
> User-Agent: curl/8.1.2
> Accept: */*
>
```

If you got this to work and see something missing please let me know!
