### ISSUE TITLE
403 response and Connection: close when "upgrade: TLS/1.2"

### ISSUE THREAD

**Issue by Stono** [istio/istio#53239]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Someone upgraded their [httpclient5](https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5) from `5.3.1` to `5.4` and in doing so, all outbound requests fail when the application is running behind Istio.

Digging into it more, it looks like the client is adding the following upgrade headers:

```
curl -v -H "connection: Upgrade" -H "upgrade: TLS/1.2" http://app.search-one-read.svc.cluster.local
```

On face value this doesn't seem to make sense to me, as the protocol is `http://` 🤷 so I'll raise that issue on the httpclient5 library.

However if I take envoy _out_ of the picture, the remote webserver returns just fine (effectively ignoring the upgrade).  That's the behaviour I'd expect; similar to the way h2 upgrades work (h1 is just returned).

However envoy returns `403 Forbidden` - which is odd in itself! 

Envoy logs show:

```
{"time":"2024-09-21T19:41:59.061090Z","level":"debug","scope":"envoy http","msg":"Sending local reply with details upgrade_failed","caller":"external/envoy/source/common/http/filter_manager.cc:1075","thread":"38","ConnectionId":"351","StreamId":"14014941417083207925"}
{"time":"2024-09-21T19:41:59.061122Z","level":"debug","scope":"envoy http","msg":"closing connection due to connection close header","caller":"external/envoy/source/common/http/conn_manager_impl.cc:1759","thread":"38","ConnectionId":"351","StreamId":"14014941417083207925"}
{"time":"2024-09-21T19:41:59.061133Z","level":"debug","scope":"envoy http","msg":"encoding headers via codec (end_stream=true):\n':status', '403'\n'date', 'Sat, 21 Sep 2024 19:41:58 GMT'\n'connection', 'close'\n","caller":"external/envoy/source/common/http/conn_manager_impl.cc:1825","thread":"38","ConnectionId":"351","StreamId":"14014941417083207925"}
{"time":"2024-09-21T19:41:59.061149Z","level":"debug","scope":"envoy http","msg":"Codec completed encoding stream.","caller":"external/envoy/source/common/http/conn_manager_impl.cc:1937","thread":"38","ConnectionId":"351","StreamId":"14014941417083207925"}
{"time":"2024-09-21T19:41:59.061157Z","level":"debug","scope":"envoy http","msg":"doEndStream() resetting stream","caller":"external/envoy/source/common/http/conn_manager_impl.cc:250","thread":"38","ConnectionId":"351","StreamId":"14014941417083207925"}
{"time":"2024-09-21T19:41:59.061163Z","level":"debug","scope":"envoy http","msg":"stream reset: reset reason: local reset, response details: -","caller":"external/envoy/source/common/http/conn_manager_impl.cc:1894","thread":"38","ConnectionId":"351","StreamId":"14014941417083207925"}
```

This is going to be a nasty problem for us when other people start upgrading their httpclient5.

### Version

```Text
1.23.1
```

**Comment by howardjohn** [comment]
> However if I take envoy out of the picture, the remote webserver returns just fine (effectively ignoring the upgrade).

So envoy isn't configured to support the `tls/1.2` upgrade. Will need to find out what the standards say on whether you should proxy an unknown upgrade request through or not

**Comment by Stono** [comment]
Fair enough, to be clear though the destination web servers don't support it either, and all seem to just ignore it.

It's one of those interop type problems that causes devex pain, where the (aspiring) transparent service mesh isn't so transparent and services deployed behind istio work differently to when the developers are working locally.

**Comment by autotrader-chris** [comment]
https://www.ietf.org/rfc/rfc2817.txt

```
3.1 Optional Upgrade

   A client MAY offer to switch to secured operation during any clear
   HTTP request when an unsecured response would be acceptable:
 
 ...
 
   In this case, the server MAY respond to the clear HTTP operation
   normally, OR switch to secured operation (as detailed in the next
   section).
```
   
Since a server that pre-dated the introduction of the upgrade header would respond normally, and the rfc does not explicitly state what should happen in that case, probably responding normally (i.e. proxying the request in this case) should be the default behaviour.

**Comment by howardjohn** [comment]
Thanks! That seems reasonable. We'll need to see how/if envoy can be configured to do so..

**Comment by Stono** [comment]
@howardjohn I went down a few rabbitholes today with envoyfitlters to try and think about mitigations to this.  At first I wondered if I could remove the header by mutating the inbound request but the request is rejected before i can process it with lua.

Then i wondered if i could add tls/1.2 to the upgrade_configs, eg:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: karl
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            upgrade_configs:
              - upgrade_type: TLS/1.2
  priority: 0
```

But that didn't work. 
Definitely out of my depth on this one so if you can think of any cluster-wider workarounds i can do before it becomes a bigger issue it'd be super appreciated.

Thanks as always
Karl

**Comment by howardjohn** [comment]
On slack we determined ^ works but needs to be applied to outbound as well. But when @Stono did so, they saw 1s delayand 101. When I did it, I got  200 and no delay. Unclear why the difference

**Comment by Stono** [comment]
@howardjohn sussed it, it's when we have `h2UpgradePolicy: UPGRADE` in the `istio-test-app-2` `DestinationRule` - we get the 101 + 1s delay 🤷

**Comment by Stono** [comment]
This extremely hacky EnvoyFilter puts a plaster on it, basically allows TLS1.2 on both inbound and outbound listeners, but then uses some lua to look for the TLS connection upgrade header and remove it.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: karl
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            upgrade_configs:
              - upgrade_type: TLS/1.2
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            upgrade_configs:
              - upgrade_type: TLS/1.2
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                local upgrade_header = request_handle:headers():get("upgrade")
                if upgrade_header and upgrade_header == "TLS/1.2" then
                  request_handle:headers():remove("upgrade")
                  request_handle:headers():remove("connection")
                end
              end
  priority: 0
```

feels utterly wrong to do though! :'(

**Comment by howardjohn** [comment]
The 1s delay is from https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto `delayed_close_timeout` fwiw. Not sure I entirely grok why its being triggered though

**Comment by chlunde** [comment]
What is the best way forward here? I expect a lot of issues soon as spring boot will upgrade.

Would it make sense to _add the possibility to discard the upgrade_ header in `upgrade_configs` in Envoy?

```yaml
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            upgrade_configs:
              - upgrade_type: TLS/1.2
                discard: true
```

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig
