### ISSUE TITLE
Dynamic routing based on an header injected by external authorization

### ISSUE THREAD

**Issue by davidebettio** [istio/istio#53246]
Hi,
Is it possible to inject an header by external authorization and then route the request with an header match based on that header?
Or in general is it possible to use an external data to choose how to route a request?

**Comment by hzxuzhonghu** [comment]
In theory it should be able to mutate/add headers before routing, 

MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.HeadersToUpstreamOnAllow can be set to have a try

**Comment by ramaraochavali** [comment]
yes. It depends on ClearRouteCache config in ext authz filter

**Comment by davidebettio** [comment]
Many thanks!!! 
clear_route_cache = true works!

**Comment by chrisguidry** [comment]
Hi folks, I'm very interested in this as well, but I'm not sure exactly where `clear_route_cache` would be set.  I see it in the [`.proto` for the envoy filter](https://github.com/envoyproxy/envoy/blob/c6761de5f33e97758471c6b973a57a5c2e5db925/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L71), and we install the `ext_authz` filter via the helm chart with the [`envoyExtAuthzHttp` setting](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider), but it [doesn't seem to support this field](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider).

Any other ideas of how we may set this configuration?

**Comment by davidebettio** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto

**Comment by jimid27** [comment]
Following up here: We configured an `EnvoyFilter` with the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz-clear-route-cache
  namespace: istio-system  # Use the namespace where Istio is installed
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.ext_authz
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            "clear_route_cache": true
```
Is this similar to your solution?

**Comment by chrisguidry** [comment]
Update on @jimid27 and my explorations.  `clear_route_cache` was indeed a big part of the solution, but we had a few other things in our way.

We had a number of separate `AuthorizationPolicy` attached to our _workloads_, but not to the _gateway_.  We needed to move to a single `AuthorizationPolicy` attached to the gateway that would call `ext_authz` from the gateway before making routing decisions, instead of from the workloads where it was too late to switch to a different service.

In our use case, we needed another kind of global catchall `VirtualService` that caught all traffic that didn't have any auth headers so that the gateway had at least one matching route to attempt to do the `ext_authz` check.  This is where `clear_route_cache` starts to matter, after the `ext_authz` check happens and you have some new headers to inform routing.

We got a recommendation from someone in the Istio Slack community to enable `trace` logging, which really did unlock this whole puzzle for us.  Leaving this note here for anyone that may be struggling with the same issue.

**Comment by davidebettio** [comment]
> Following up here: We configured an `EnvoyFilter` with the following:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: ext-authz-clear-route-cache
>   namespace: istio-system  # Use the namespace where Istio is installed
> spec:
>   configPatches:
>     - applyTo: HTTP_FILTER
>       match:
>         context: ANY
>         listener:
>           filterChain:
>             filter:
>               name: envoy.filters.network.http_connection_manager
>               subFilter:
>                 name: envoy.filters.http.ext_authz
>       patch:
>         operation: MERGE
>         value:
>           typed_config:
>             "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
>             "clear_route_cache": true
> ```
> 
> Is this similar to your solution @davidebettio ?

Sorry for the delay @jimid27 , my code is:

```
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            allowed_headers:
              patterns:
                - exact: x-dst
                - exact: x-port
            clear_route_cache: true
            http_service:
              authorization_request:
                headers_to_add:
                  - key: X-Envoy-External-Address
                    value: '%REQ(X-ENVOY-EXTERNAL-ADDRESS)%'
                  - key: X-Forwarded-For
                    value: '%REQ(X-FORWARDED-FOR)%'
                  - key: X-Forwarded-Host
                    value: '%REQ(HOST)%'
                  - key: Original-Request-Uri
                    value: '%REQ(:path)%'
                  - key: Original-Request-Method
                    value: '%REQ(:method)%'
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: authorization
                    - exact: x-original-authorization
                    - exact: x-tunnel-type
                    - exact: x-dst
                    - exact: x-port
              server_uri:
                cluster: outbound|50052||vpn-tunnel-ext-authz.prod.svc.cluster.local
                timeout: 5s
                uri: http://vpn-tunnel-ext-authz:50052
```
