### ISSUE TITLE
allow ztunnel timeout to be configurable and have init containers tolerate request failures with a retry and an exponential backoff

### ISSUE THREAD

**Issue by rwong2888** [istio/istio#53271]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

allow ztunnel timeout to be configurable

have init containers tolerate request failures with a retry and an exponential backoff

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

vault init sidecar is stuck initializing due to timeout

```
ztunnel-5gt2s istio-proxy 2024-09-24T19:19:03.390475Z	warn	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-75qx6}:outbound{id=49c03c734e951a3da914556019f0615b}	timed out waiting for workload from xds
ztunnel-5gt2s istio-proxy 2024-09-24T19:19:03.390502Z	warn	access	connection failed	src.addr=10.246.9.5:49636 dst.addr=34.48.26.163:443 direction="outbound" error="unknown source: 10.246.9.5"
ztunnel-5gt2s istio-proxy 2024-09-24T19:19:05.848236Z	warn	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-qgwhb}:outbound{id=c89530856c591704ca5e3191e51a6cd7}	timed out waiting for workload from xd
```

slack thread:

https://istio.slack.com/archives/C041EQL1XMY/p1727205751941369

**Comment by rwong2888** [comment]
cc @howardjohn , @bleggett

**Comment by howardjohn** [comment]
The 5s timeout is already pretty outrageously long (and is the result of retrying! just the hard limit). Did we find it was simply not waiting long enough? it seems more likely its just not working at all, and we could wait forever.

**Comment by bleggett** [comment]
```
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.538045Z	debug	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=69b10a9c40ba35af3cc9545b7d8a6de7}	fetch workload	addr=/10.246.12.12
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.538133Z	debug	xds::client:xds{id=3}	sending response	type_url="type.googleapis.com/istio.workload.Address" nonce="2024-09-24T19:30:12Z/1198193f0d0-c78b-4911-abdc-cf9a3de926e8" type=Ack
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.538151Z	debug	xds::client	sending request	type_url="type.googleapis.com/istio.workload.Address"
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.538189Z	debug	h2::codec::framed_write:xds{id=3}:Connection{peer=Client}	send	frame=Data { stream_id: StreamId(1) }
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.539817Z	debug	h2::codec::framed_read:xds{id=3}:Connection{peer=Client}	received	frame=WindowUpdate { stream_id: StreamId(0), size_increment: 111 }
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.539837Z	debug	h2::codec::framed_read:xds{id=3}:Connection{peer=Client}	received	frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
ztunnel-57pgk istio-proxy 2024-09-24T19:41:47.539842Z	debug	h2::codec::framed_write:xds{id=3}:Connection{peer=Client}	send	frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
ztunnel-57pgk istio-proxy 2024-09-24T19:41:52.095412Z	warn	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=69b10a9c40ba35af3cc9545b7d8a6de7}	timed out waiting for workload from xds
ztunnel-57pgk istio-proxy 2024-09-24T19:41:52.095443Z	warn	access	connection failed	src.addr=10.246.12.12:35208 dst.addr=34.48.26.163:443 direction="outbound" error="unknown source: 10.246.12.12"
ztunnel-57pgk istio-proxy 2024-09-24T19:41:52.095524Z	debug	proxy::outbound:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=69b10a9c40ba35af3cc9545b7d8a6de7}	connection completed	component="outbound" dur=5.001912636s
ztunnel-57pgk istio-proxy 2024-09-24T19:41:54.929442Z	debug	proxy::outbound:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=00ef8d3e1a59ac53fde3e2b92eff2181}	connection started	component="outbound"
ztunnel-57pgk istio-proxy 2024-09-24T19:41:54.929471Z	debug	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=00ef8d3e1a59ac53fde3e2b92eff2181}	wait for workload	addr=/10.246.12.12
ztunnel-57pgk istio-proxy 2024-09-24T19:41:54.929477Z	debug	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=00ef8d3e1a59ac53fde3e2b92eff2181}	got sub, waiting for workload	addr=/10.246.12.12
ztunnel-57pgk istio-proxy 2024-09-24T19:41:54.929480Z	debug	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=00ef8d3e1a59ac53fde3e2b92eff2181}	fetch workload	addr=/10.246.12.12
ztunnel-57pgk istio-proxy 2024-09-24T19:41:59.931396Z	warn	state:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=00ef8d3e1a59ac53fde3e2b92eff2181}	timed out waiting for workload from xds
ztunnel-57pgk istio-proxy 2024-09-24T19:41:59.931421Z	warn	access	connection failed	src.addr=10.246.12.12:54718 dst.addr=34.48.26.163:443 direction="outbound" error="unknown source: 10.246.12.12"
ztunnel-57pgk istio-proxy 2024-09-24T19:41:59.931515Z	debug	proxy::outbound:proxy{wl=da-dashboard2/staging-b4d9ddcc8-hnhlz}:outbound{id=00ef8d3e1a59ac53fde3e2b92eff2181}	connection completed	component="outbound" dur=5.002102465s
ztunnel-57pgk istio-proxy 2024-09-24T19:42:01.781411Z	debug	h2::codec::framed_read:xds{id=3}:Connection{peer=Client}	received	frame=Data { stream_id: StreamId(1) }
ztunnel-57pgk istio-proxy 2024-09-24T19:42:01.781470Z	info	xds::client:xds{id=3}	received response	type_url="type.googleapis.com/istio.workload.Address" size=1 removes=0
ztunnel-57pgk istio-proxy 2024-09-24T19:42:01.781500Z
```

logs from the issue.

either 
- the wait is blocking the processing of new pushes (pretty sure it can't)
- we need to wait longer
- something about the use of init containers makes `istiod` delay the push

**Comment by bleggett** [comment]
@rwong2888 Can you install latest Istio (1.23.2) with `istiod` logging set to debug? 

e.g. `--set values.global.logging.level="all:debug"`

e.g. `istioctl install --set profile=ambient  --set values.ztunnel.logLevel="debug" --set values.global.logging.level="all:debug"`

and reproduce this, giving us the full dump of the `istiod`/`ztunnel` debug logs from startup, through the stall, until you manually restart the pod with the init container and it begins working?

I can't repro this with an init container doing network queries, and it simply should not take that long for `istiod` to push that workload.


```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup httpbin.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
---
````

If there's also some way you could repro this with your injected Vault container and our sleep sample, and give us a lightly redacted Pod yaml that doesn't work, that would help.
