### ISSUE TITLE
Enabling meshConfig.defaultProviders in Helm chart for istiod disables Telemetry V2

### ISSUE THREAD

**Issue by codehexes** [istio/istio#53332]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

While trying to set up a new Istio mesh based on some previous work from a colleague, I happened to copy over a configuration setting that intended to set the default provider for tracing to OpenTelemetry in the `values.yaml` file for `istiod`:
```yaml
meshConfig:
  defaultProviders:
    tracing:
      - opentelemetry
```
However, I also had configured `telemetry.v2` in the same file:
```yaml
telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true
    stackdriver:
      enabled: false
```

I also configured telemetry via the Telemetry API:
```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: opentelemetry
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: opentelemetry
    randomSamplingPercentage: 100
```

With this configuration, I was unable to find certain metrics like `istio_requests_total` from the proxy stats endpoint.  After much digging, I found that the `telemetry v2` settings are ignored if the `defaultProviders` block is populated in the yaml file.  After removing the `defaultProviders` block and rolling deployments, I was able to start seeing these metrics (and Kiali started working properly, too).

This feels like a bug, or at least undocumented, as there is no mention that `defaultProviders` is for the old way of configuring telemetry (at least, as far as I can see!).

### Version

```Text
$ istioctl version
client version: 1.21.1
control plane version: 1.23.0
data plane version: 1.23.0 (2 proxies)
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
$ helm version --short
v3.15.3+g3bb50bb
```
