### ISSUE TITLE
Documented setup of of OpenTelemetryTracingProvider breaks apps that write to those same URL's directly via https

### ISSUE THREAD

**Issue by jbilliau-rcd** [istio/istio#53382]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This is a bit of a long one, buckle in. We are currently on Istio 1.19.7 and trying to migrate to 1.22.5. We also use Dynatrace, which as of Istio 1.22, uses OpenTelemetry instead of OpenTracing for its traces/spans, due to OpenTracing being removed in Envoy 1.30, which Istio 1.22 uses.

Dynatrace docs mimic the Istio docs pretty much, and say to use the below block in the `IstioOperator` spec to configure the sidecars to send OTEL traces to their platform.

```
meshConfig:
      extensionProviders:
      - name: dynatrace-otel
        opentelemetry:
          port: 443
          service: "istio-config/${dynatraceTenantId}.live.dynatrace.com"
          http:
            path: "/api/v2/otlp/v1/traces"
            timeout: 10s
            headers:
            - name: "Authorization"
              value: "Api-Token ${apiToken}"
          resource_detectors:
            dynatrace: {}
          dynatrace_sampler:
            tenant: ${dynatraceTenantId}
            cluster_id: ${dynatraceClusterId} 
```

In addition, we are advised to deploy this `DestinationRule`:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dynatrace-dr-otel
  namespace: istio-config
spec:
  host: "akpxxxxx.live.dynatrace.com"
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

These steps seem to mimic the docs [here](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-OpenTelemetryTracingProvider). Presumably, this is because the OTEL piece of Envoy only sends to HTTP, and we need a `DestinationRule` to upgrade it to TLS/HTTPS. Otherwise, it wouldn't work since the Dynatrace SaaS URL doesn't accept HTTP traffic obviously.

Now, this is all fine and dandy except after rolling this out to a nonprod cluster as a test, it broke all the apps that, in their own code, write to the same URL custom metrics **but over https already**. Presumably, this is because Istio is trying to originate an already HTTPS connection. This is what we get when trying to do a `curl -v https://apxxxx.live.dynatrace.com`

`[2024-10-01T18:26:32.694Z] "GET / HTTP/1.1" 503 URX,UF "TLS_error:|268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER:TLS_error_end:TLS_error_end" 0 248 118 - "-" "curl/8.5.0" "8eab814f-fade-964b-9a1d-589c94107e55" "akp68187.live.dynatrace.com" "52.86.80.198:80" outbound|80||akp68187.live.dynatrace.com - 107.23.191.74:80 10.212.253.38:33358 - default -`

So basically, it seems like the documented setup for configuring an OpenTelemetryTracingProvider inherently breaks any apps that are ALSO trying to write to that same URL over HTTPS. If we remove the `DestinationRule` above, it goes back to working. 

So my question is; why can't the OpenTelemetryTracingProvider section be configured to write to an HTTPS endpoint directly, which is the same thing all our apps do and wouldn't require upgrading of the connection at all? Or, is there a way to configure Istio to allow *both* HTTPS passthrough AND http>https upgrades, which would allow both the app to work (writing custom metrics) AND the sidecar to work (sending OTEL traces configured via the IstioOperator)? We've tried everything and can't get it to work.

Tagging @joaopgrassi since he was involved in the other issue over on the Envoy GitHub.

### Version

```Text
$ istioctl version
client version: 1.23.0
istiod version: 1.22.4
data plane version: 1.22.4 (88 proxies)

$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.12-eks-a18cd3a
```

**Comment by joaopgrassi** [comment]
Hi @jbilliau-rcd 

Did you get the `ServiceEntry` snippets from Dynatrace or from the Istio docs? From our Istio deployment page, we have since Dynatrace version 1.299 changed the `ServiceEntry` and `DestinationRule` snippets. Please take a look there, but the content should be this:

MeshConfig:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    extensionProviders:
    - name: dynatrace-otel
      opentelemetry:
        port: 80
        service: "istio-system/akpxxxxx.live.dynatrace.com"
        http:
          path: "/api/v2/otlp/v1/traces"
          timeout: 10s
          headers:
            - name: "Authorization"
              value: "Api-Token <API_TOKEN>"
        resource_detectors:
          dynatrace: {}
        dynatrace_sampler:
          tenant: "<TENANT>"
          cluster_id: <ID>
```
ServiceEntry/DestinationRule:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dynatrace-se-otel
spec:
  hosts:
  - akpxxxxx.live.dynatrace.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dynatrace-dr-otel
spec:
  host: akpxxxxx.live.dynatrace.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE
```

Trying that in a pod and trying to invoke the custom metrics endpoint works for me:

```
curl -X 'POST' \
  'https://akpxxxxx.live.dynatrace.com/api/v2/metrics/ingest' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'Content-Type: text/plain; charset=utf-8' \
  -d 'server.cpu.temperature,cpu.id=0 42'
```
Returns `{"error":{"code":401,"message":"Missing authorization parameter."}}` because the request is not authenticated. 

Envoy needs the TLS configurations in order to be able to use HTTPS. If you provide the HTTPS URL without the TLS config, the export will fail (you can try it yourself). This new config then configures envoy to export to HTTP, but then Istio upgrades the request to HTTPS.

**Comment by jbilliau-rcd** [comment]
@joaopgrassi to the rescue again, I used your objects and it works now....it looks like we were. missing `location` and `targetPort` on our `ServiceEntry` as well as using `port: 443` on the istiooperator object. Outdated docs :(

This Istio 1.22 migration to OTEL is going to be the end of me, lol.....it's been nothing but issues and frustration. We are going to look into filtering the `OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message` from going to Splunk for now and hope that Istio releases a patch release soon with the back ported Envoy fixes. 

Thanks! Closing issue.

**Comment by joaopgrassi** [comment]
> We are going to look into filtering the OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message from going to Splunk for now and hope that Istio releases a patch release soon with the back ported Envoy fixes.

I guess you figured it out, but just for completion. If you increase the export interval as I mentioned [here](https://github.com/envoyproxy/envoy/issues/35997#issuecomment-2388492731), then the requests will be less often, preventing Dynatrace from throttling the requests and then no more logs in Envoy with 503s.

**Comment by joaopgrassi** [comment]
> create that configmap and that annotation on our thousands of deployments 

Hum I'm not a k8s expert, but maybe there's a way to do this by default like "to all pods in a namesmace"? Then you wouldn't need to change the manifest of all deployments.

**Comment by joaopgrassi** [comment]
@jbilliau-rcd  Actually I think I found another way out for you 😅. We can configure a set of default runtime values via the MeshConfig https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig. 


```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      runtimeValues:
        tracing.opentelemetry.flush_interval_ms: "300000" <<<<< ADD HERE
```

Those land in the same place, as a static layered config in Envoy:

```
      - name: global config
        static_layer:
          envoy.deprecated_features:envoy.config.listener.v3.Listener.hidden_envoy_deprecated_use_original_dst: true
          envoy.reloadable_features.http_reject_path_with_fragment: false
          overload.global_downstream_max_connections: "2147483647"
          re2.max_program_size.error_level: "32768"
          tracing.opentelemetry.flush_interval_ms: "300000"
```
So you get the same result, without having to run a collector. Just tried and it worked.
