### ISSUE TITLE
The IstioOperator does not honor the podAntiAffinityLabelSelector and podAntiAffinityTermLabelSelector

### ISSUE THREAD

**Issue by yasithab** [istio/istio#53397]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have athe following istio-config.yaml (only showing the necessary settings), and it worked well with Istio version **1.21.6**

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
        podAntiAffinityLabelSelector:
        - key: app
          operator: In
          values: istio-ingressgateway
          topologyKey: kubernetes.io/hostname
        podAntiAffinityTermLabelSelector:
        - key: app
          operator: In
          values: istio-ingressgateway
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

When trying to upgrade it to version **1.22.5** using the command below;

```
istioctl install --readiness-timeout 10m0s -y -f istio-config.yaml
```

It gives the following error.

```
│ Error: generate config: validation errors (use --force to override):
│ unknown field "key" in k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelector
```

I can reproduce this error in Istio **1.23.2** as well.

Could you please help me to fix this?

### Version

```Text
istioctl version
client version: 1.23.2
control plane version: 1.23.2
data plane version: 1.23.2 (3 proxies)

kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599
```

**Comment by yasithab-pf** [comment]
I managed to resolve the issue by moving the affinity block to the ingressGateway component.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: true
      k8s:
        nodeSelector:
          nodegroup: app
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istio-ingressgateway
              topologyKey: kubernetes.io/hostname
```
