### ISSUE TITLE
Otel configuration shows HTTP Authorization headers

### ISSUE THREAD

**Issue by markusobsil** [istio/istio#53408]
**Describe the feature request**

If you want to configure, e.g. Otel tracing via HTTP export, you would need to create a configuration like shown the [docs](https://istio.io/latest/docs/tasks/observability/distributed-tracing/opentelemetry/#exporting-via-http):

```
cat <<EOF | istioctl install -y -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4318
        service: opentelemetry-collector.observability.svc.cluster.local
        http:
          path: "/v1/traces"
          timeout: 5s
          headers:
            - name: "custom-header"
              value: "custom value"
        resource_detectors:
          environment: {}
EOF
``` 

When your Open Telemetry collector is configured to require a simple authentication with HTTP authorization header for tokens/Apikeys/etc., you would need to create a configuration like this (adapted previous example):

```
        http:
          path: "/v1/traces"
          timeout: 5s
          headers:
            - name: "Authorization"
              value: "Apikey 123456789abcdef"
``` 

This means the Key/Token/Secret is stored in clear-text in the meshConfig. In today's systems where everything is stored in git, that should get applied to a Kubernetes Cluster via CD, this becomes a big problem, because you would expose this to everyone who has access to git. 
This issue is not limited to Open Telemetry configuration. You will have the same issue with LightstepTracingProvider configuration, SkyWalkingTracingProvider configuration, and Open Telemetry with Dynatrace configuration. At least that's the ones I found browsing through the [meshConfig documentation](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) page. Maybe there are more examples and this is not only needed for tracing. 

In my eyes it should be possible to refer in the meshConfig, which is stored as a Kubernetes config-map, to Kubernetes secrets. Furthermore it would make sense to store it to Kubernetes Secrets, because with correct Kubernetes RBAC rules in place, I maybe want to give people access to config-maps, but not to secrets. 

The Argo CD project solved this problem already (referring in a config-map to data of a Kubernetes secret). Here is an example for this: [clientSecret is referring to a Kubernetes Secret](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#2-configure-argo-cd-for-sso). Adding this as a generic functionality (not focused on Tracing/Telemetry configuration) would be future-proof and would work for any Secrets that are needed in the meshConfig. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ X ] Ambient
[ ] Docs
[ ] Dual Stack
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
make sense to me.

Another thinking is that, you should store a template in git(or other VCS), CI will render secret part when deploying(like what Github did for `GITHUB_TOKEN`).

**Comment by markusobsil** [comment]
In a setup, where you take the official Istio helm charts and configure them with the available values, it is hard to put custom templating in there. 
Putting this logic into your CI system would work in some environments, but I think it would not work everywhere.

**Comment by zirain** [comment]
not stale

**Comment by markusobsil** [comment]
Thank you @zirain.
You are great 👏

**Comment by zirain** [comment]
@markusobsil your're welcome.

**Comment by ebirkholz** [comment]
Hi @markusobsil and @zirain ,

I'm using Istio 1.29 and trying to reference a secret defined via envVarFrom in the istiod container inside meshConfig.extensionProviders.opentelemetry.http.headers.value.

Current configuration (Helm template)
```
istiod:
  envVarFrom:
    - name: ISTIO_DYNATRACE_TOKEN
      valueFrom:
        secretKeyRef:
          name: "secretName" # Secret from GCP Secret Manager imported using ExternalSecrets
          key: istioToken
  meshConfig:
    extensionProviders:
      - name: dynatrace-otel
        opentelemetry:
          service: istio-system/server.live.dynatrace.com
          port: 80
          http:
            path: "/api/v2/otlp/v1/traces"
            timeout: 10s
            headers:
              - name: "Authorization"
                value: "Api-Token ${env:ISTIO_DYNATRACE_TOKEN}"
          resource_detectors:
            dynatrace: {}
```

### Expected behavior

I expected ${env:ISTIO_DYNATRACE_TOKEN} to be resolved from the istiod container environment and the actual token value to be propagated to the proxies.

### Actual behavior

The value appears to be passed literally (Api-Token ${env:ISTIO_DYNATRACE_TOKEN}), and the proxies return 401 Unauthorized, which suggests the environment variable is not being interpolated.

### Question

Is environment variable interpolation supported in meshConfig.extensionProviders?

If not, what is the recommended way to reference a Kubernetes Secret for HTTP headers in an OpenTelemetry extension provider configuration?

Thanks in advance.
