### ISSUE TITLE
Configurable 403 rbac response body

### ISSUE THREAD

**Issue by cathal-c** [istio/istio#53438]
**Describe the feature request**

Firstly, sorry for the issue repetition, this is very similar to the last one. Just wanted to separate concerns.

We are looking to invest eng time in the upstream codebase to move some of our long standing EnvoyFilters back into the codebase, as first class features - if the use cases are considered acceptable.

--

We would like to be able to configure the body returned in Gateway rbac 403 responses. We are mandated to use a more "anonymous" body value by security org.

**Describe alternatives you've considered**

Today we use an EnvoyFilter;

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rbac-message-override
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: 443
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            local_reply_config:
              mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 403
                          runtime_key: local-reply-runtime-key # This key is REQUIRED for filter compilation. See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-comparisonfilter
                  body:
                    inline_string: "Forbidden"
```

This works well, but we always want to eliminate EnvoyFilters in place of first class APIs where possible.

I would be willing to invest resources in this myself, if the Istio developers consider this is reasonable and feasible. I don't consider it important enough at all to waste your time. Having said that, I am not as familiar with the Istio codebase as I'd like to be, so I can't estimate the difficulty of supporting this.

We have a somewhat similar API available for the server response header (thanks John!), so something similar could be considered here? 

Greatly appreciate any feedback! Thanks.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
