### ISSUE TITLE
Configurable gateway server header

### ISSUE THREAD

**Issue by cathal-c** [istio/istio#53431]
**Describe the feature request**

We would like to be able to configure the server header returned in Gateway responses. We are mandated to use a more "anonymous" header value by security org.

**Describe alternatives you've considered**

Currently we use an EnvoyFilter;

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: server-name-override
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: 443
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            server_name: "WebServer"
```

This works well, but we always want to eliminate EnvoyFilters in place of first class APIs where possible.

I would be willing to invest resources in this myself, if the Istio developers consider this is reasonable and feasible. I don't consider it important enough at all to waste your time. Having said that, I am not as familiar with the Istio codebase as I'd like to be, so I can't estimate the difficulty of supporting this.

Also not sure what API would be most appropriate to configure this.

Greatly appreciate any feedback! Thanks.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
