### ISSUE TITLE
Attempt Count headers cannot be disabled

### ISSUE THREAD

**Issue by abaguas** [istio/istio#53475]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Using an image with curl installed (e.g. praqma/network-multitool) I did the following request: `curl -X GET "http://httpbin.org/headers" -H "accept: application/json"` to see my request headers. Among others, I saw the following headers added by istio/envoy.
```
    "X-Envoy-Attempt-Count": "1",
    "X-Envoy-Peer-Metadata": "Cho.......c2Fnc3F1aWQ=",
    "X-Envoy-Peer-Metadata-Id": "sidecar~172.16.42.7~osagsquid-667966dff4-h7dx8.proxy-6-11856~proxy-6-11856.svc.cluster.local"
  }
```
I tried to remove them using the following annotation according to https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-ProxyHeaders-AttemptCount:
```
      annotations:
        proxy.istio.io/config: |
          proxyHeaders:
            attemptCount:
              disabled: true
            metadataExchangeHeaders:
              mode: IN_MESH
```

However, only the Metadata ones were removed, the `X-Envoy-Attempt-Count` remained

### Version

```Text
╰─➤  istioctl version
client version: 1.23.2
control plane version: 1.23.2
data plane version: 1.23.2 (257 proxies)

╰─➤  kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.4
```
