### ISSUE TITLE
Manually create waypoints with helm and k8s Gateway API

### ISSUE THREAD

**Issue by antonioberben** [istio/istio#53473]
**Describe the feature request**

Docs claim that you can [create manually a gateway](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment). However, it only works for ingress gateway and not waypoints.

How to reproduce:

```
istioctl install -y --set profile=ambient --set meshConfig.accessLogFile=/dev/stdout --set components.ztunnel.values.logLevel=debug

kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml\; }

kubectl create ns httpbin

kubectl label namespace httpbin istio.io/dataplane-mode=ambient

kubectl -n httpbin apply -f https://raw.githubusercontent.com/solo-io/gloo-mesh-use-cases/main/policy-demo/httpbin.yaml
kubectl -n httpbin apply -f https://raw.githubusercontent.com/istio/istio/refs/heads/master/samples/sleep/sleep.yaml

kubectl label svc/httpbin -n httpbin  istio.io/use-waypoint=httpbin-waypoint

helm upgrade --install httpbin-waypoint istio/gateway -n httpbin -f - <<EOF
labels:
  istio.io/waypoint-for: all
podAnnotations:
  inject.istio.io/templates: "waypoint"
service:
  type: ClusterIP
  ports:
  - appProtocol: tcp
    name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - appProtocol: hbone
    name: mesh
    port: 15008
    protocol: TCP
    targetPort: 15008
EOF

kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-waypoint
  namespace: httpbin
  labels:
    istio.io/waypoint-for: all
    istio.io/for-service-account: httpbin-waypoint # Trying this to see if solves the issue with the service account, but it seems that not
  annotations:
    istio.io/for-service-account: httpbin-waypoint # Trying this to see if solves the issue with the service account, but it seems that not
spec:
  addresses:
  - value: httpbin-waypoint.httpbin.svc.cluster.local
    type: Hostname
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
EOF
```

The ReplicaSet for the `httpbin-waypoint` throws an error about not able to inject the ServiceAccount:
```
│ Events:                                                                                                                                                                                                                                  │
│   Type     Reason        Age                   From                   Message                                                                                                                                                            │
│   ----     ------        ----                  ----                   -------                                                                                                                                                            │
│   Warning  FailedCreate  7m27s (x18 over 18m)  replicaset-controller  Error creating: admission webhook "object.sidecar-injector.istio.io" denied the request: failed to run injection template: template: inject:4:10: executing "injec │
│ t" at <.ServiceAccount>: can't evaluate field ServiceAccount in type *inject.SidecarTemplateData
```

And istiod throws another error about the same: not able to inject the ServiceAccount in the template:

```
error	Invalid template: template: inject:4:10: executing "inject" at <.ServiceAccount>: can't evaluate field ServiceAccount in type *inject.SidecarTemplateData
```

**Describe alternatives you've considered**

The alternative is to create the Waypoint applying directly the resources which is not the best approach since the template injection is the way Istio suggests as good practice.

**Affected product area (please put an X in all that apply)**

[ x ] Ambient
[ x ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
