### ISSUE TITLE
Telemetry supports workload selector for all namespaces

### ISSUE THREAD

**Issue by Kuromesi** [istio/istio#53481]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
I'm working on configuring different tracing providers for various clusters. Some clusters are located within the same intranet as the tracing collector, allowing them to export traces to an intranet endpoint. However, other clusters are outside of the intranet and can only export traces to a public endpoint.

I tried to configure telemetry like this first:

```yaml
// export traces to public endpoint
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin
    randomSamplingPercentage: 100
---
// export traces to intranet endpoint for workloads with label region=region-a
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: zipkin-internal
spec:
  selector:
    matchLabels:
      region: region-a
  tracing:
  - providers:
    - name: zipkin-internal
```

It works fine for default namespace while other namespaces fail. It seems like workload selector only match workload within the same namespace.

```go
matcher := PolicyMatcherForProxy(proxy).WithService(svc)
for _, telemetry := range t.NamespaceToTelemetries[namespace] {
	spec := telemetry.Spec
	// TODO in many other places, empty selector matches all policy
	if len(spec.GetSelector().GetMatchLabels()) == 0 {
		continue
	}
	if matcher.ShouldAttachPolicy(gvk.Telemetry, telemetry.NamespacedName(), spec) {
		ct = appendApplicableTelemetries(ct, telemetry, spec)
	} else {
		log.Debug("There isn't a match between the workload and the policy. Policy is ignored.")
	}
}
```

Is it possible to configure telemetry with workload selector for all namespaces?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin
    randomSamplingPercentage: 100
```

this should be worked, do you have a provider named as `zipkin`?

**Comment by Kuromesi** [comment]
> ```yaml
> apiVersion: telemetry.istio.io/v1
> kind: Telemetry
> metadata:
>   name: default
>   namespace: istio-system
> spec:
>   tracing:
>   - providers:
>     - name: zipkin
>     randomSamplingPercentage: 100
> ```
> 
> this should be worked, do you have a provider named as `zipkin`?

Yes, zipkin provider export traces to public endpoint, while zipkin-internal export traces to intranet endpoint. What I expected is workloads in all namespaces with label `region=region-a` will export traces to zipkin-internal.

**Comment by zirain** [comment]
can you try with
```
// export traces to public endpoint
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin
    randomSamplingPercentage: 100
---
// export traces to intranet endpoint for workloads with label region=region-a
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: zipkin-internal
  namespace: istio-system
spec:
  selector:
    matchLabels:
      region: region-a
  tracing:
  - providers:
    - name: zipkin-internal
```

**Comment by zirain** [comment]
can you try with
```
// export traces to public endpoint
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: zipkin
    randomSamplingPercentage: 100
---
// export traces to intranet endpoint for workloads with label region=region-a
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: zipkin-internal
  namespace: istio-system
spec:
  selector:
    matchLabels:
      region: region-a
  tracing:
  - providers:
    - name: zipkin-internal
```
