### ISSUE TITLE
Add resource annotations for ephemeral-storage

### ISSUE THREAD

**Issue by B1F030** [istio/istio#53509]
**Describe the feature request**

Since we can claim istio-proxy's CPU request by setting `sidecar.istio.io/proxyCPU`,
and claim CPU limit by setting `sidecar.istio.io/proxyCPULimit`,
is there any way I can claim `ephemeral-storage` request & limit?

Usercase:

In the `istio-proxy` sidecar, there's constantly a large amount of logs output,
which will be stored in `/var/lib/docker/containers` (when using docker as CRI),
and takes up `ephemeral-storage` depends on config, for example:
```shell
cat /etc/docker/daemon.json 
```
```json
{
    "exec-opts": ["native.cgroupdriver=systemd"],
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "100m",
        "max-file": "10"
    }
}
```
In this case, each pod of `istio-proxy` will take up about 1Gi of disk,
and may be eventually `Evicted` because of using ephemeral-storage out of request:
```yaml
Status:       Failed
Reason:       Evicted
Message:      The node was low on resource: ephemeral-storage.
              Container istio-proxy was using 942888Ki, which exceeds its request of 0.
```

Feature Request:

So, Is it possible to add resource annotations for ephemeral-storage?
like for CPU and Memory, `sidecar.istio.io/proxyEphemeralStorage` &
`sidecar.istio.io/proxyEphemeralStorageLimit`? I'll be glad to help.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
I donot know how k8s pod allow setting empheral storage.

**Comment by B1F030** [comment]
> That's pretty easy to set this option

Yes, `ephemeral-storage` is basically the same level of resource as `cpu` and `memory`,
and it should be easy to implement this feature.

Now we are using webhook to inject resource for istio-proxy container, but since istio have
`sidecar.istio.io/proxyCPU` and `sidecar.istio.io/proxyCPULimit`, it will be convenient for users
if we can have similar annotation like `sidecar.istio.io/proxyEphemeralStorage`.

**Comment by zirain** [comment]
IMO, https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection will be better for such solution.

**Comment by B1F030** [comment]
> IMO, https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection will be better for such solution.

Agree, we can customize `istio-sidecar-injector` configmap like this:
```
        "proxy": {
          "resources": {
            "limits": {
              "cpu": "200m",
              "ephemeral-storage": "300Mi",
              "memory": "512Mi"
            },
            "requests": {
              "cpu": "100m",
              "ephemeral-storage": "300Mi",
              "memory": "256Mi"
            }
          },
        },
```

But on the other hand, since cpu and memory are configurable by [annotations](https://istio.io/latest/docs/reference/config/annotations/) on the pod,
I think adding support for ephemeral-storage is also worth considering.

**Comment by B1F030** [comment]
> I'm not sure that it's a common user case.

I've searched issues about `ephemeral-storage` but didn't find any issue related...
I thought this might be common in production environment, since istio-proxy
do output a lot of logs, but since nobody mentioned this before, so I agree that
we may need more user feedback about this scenario. Thanks for your reply!

**Comment by zirain** [comment]
Istio support to custom [userVolume](https://istio.io/latest/docs/reference/config/annotations/#SidecarUserVolume) and gRPC ALS, I think that's fine for most of the cases.

I'm curious in what circumstances a large "temporary storage" is needed.

**Comment by jbilliau-rcd** [comment]
hey folks, speak of the devil, if you wondering if it's a common use case, it is at least for us as of a week ago. We have a user whose pod is constantly crashing with:

`The node was low on resource: ephemeral-storage. Threshold quantity: 10736158060, available: 7877828Ki. Container istio-proxy was using 26688Ki, request is 0, has larger consumption of ephemeral-storage. `

So regardless of how often it is needed by users, it can't hurt to add, and is outright required in this use-case. Not sure what else the answer is for a pod that constantly terminates due to istio-proxy using too much ephemeral storage.

**Comment by jbilliau-rcd** [comment]
@B1F030 where would I configure that configMap if using istioctl and an `IstioOperator` object to deploy Istio? Is that configurable as part of that spec? trying to think of a way to increase this number cluster-wide so we don't have dev's needing to add custom pod settings, which isn't very user-friendly and not even possible in how we currently do things.

**Comment by B1F030** [comment]
> @B1F030 where would I configure that configMap if using istioctl and an `IstioOperator` object to deploy Istio?

```
kubectl get configmaps -n istio-system istio-sidecar-injector
```
data.values: |-
"global".""proxy""

Edit it like [this](https://github.com/istio/istio/issues/53509#issuecomment-2475681774) and apply, it should work.

[FYI](https://github.com/istio/istio/blob/master/pkg/config/analysis/analyzers/testdata/common/sidecar-injector-configmap.yaml#L413)

**Comment by jbilliau-rcd** [comment]
So I get that, but we have 200+ clusters, manually editing a configmap isn't really feasible, plus would just get overridden next time we upgrade Istio presumably. Is there a way in the `IstioOperator` spec to pass in this override? This way I can deploy this change via gitops to all our clusters?

**Comment by B1F030** [comment]
> Is there a way in the `IstioOperator` spec to pass in this override?

Refer to [custom-templates-experimental](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  values:
    sidecarInjectorWebhook:
      templates:
        custom: |
          spec:
            containers:
            - name: istio-proxy
              env:
              - name: GREETING
                value: hello-world
```
also, i found similar config in my environment:
```
spec:
  values:
    global:
      proxy:
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            ephemeral-storage: 500Mi   # add here
            memory: 250Mi
```
this might work too.
