### ISSUE TITLE
Sidecar -> Ztunnel doesn't translate `ISTIO_MUTUAL` to HBONE

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53526]
```yaml
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: default
  namespace: istio-system
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

expectation: sidecar -> ambient uses HBONE
reality: it uses old Istio mTLS style
