### ISSUE TITLE
Downstream connections spamming our logging servers too hard.

### ISSUE THREAD

**Issue by akshaysgithub** [istio/istio#53536]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

We have Istio 1.23.2 helm-chart installed. And currently we are experiencing spam on our logging servers because of these 2 errors

```
2024-10-15T02:40:13.507636Z	warning	envoy main external/envoy/source/server/server.cc:843	Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.downstream_connections` instead.This runtime key will be removed in future.	thread=19
````

And

```
2024-10-15T02:40:31.455880Z	warning	envoy main external/envoy/source/server/server.cc:936	There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.	thread=12
```

For both of them, I am setting values in Proxy section of values.yaml, but they are not taking effect(pods have been restarted). Can someone tell me how to stop this warning for good.

Values.yaml
```
global:
  proxy:
    resourceMonitors:
      - name: envoy.resource_monitors.downstream_connections
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
          max_active_downstream_connections: 10000
```

I have spent a lot of man-hours fixing this issue, but no luck.

Any idea would be really helpful. 

Thanks a lot. :-) 

### Version

```Text
1.23.2
K8s: 1.30
```
