### ISSUE TITLE
regex matching not supported

### ISSUE THREAD

**Issue by sambitr** [istio/istio#53564]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

i have 2 virtualservices defining below

VS1:
```
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /demo/api
    route:
    - destination:
        host: api.demo.svc.cluster.local
        port:
          number: 80
    timeout: 30s
  - match:
    - uri:
        prefix: /demo/swagger
    route:
    - destination:
        host: api.demo.svc.cluster.local
        port:
          number: 80
    timeout: 30s
```

VS2:

```
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /demo/
    route:
    - destination:
        host: web.demo.svc.cluster.local
        port:
          number: 80
    timeout: 30s
```

They are deployed in the same order in which they are defined above. But after deployment, what I am finding is: all traffic with /demo/api* is getting directed to web service than the api service.

I think it is due to the Istio routing order and I am not sure how it maintains the order.

I tried to use regex in web virtualservice to drop all traffic /demo/api/* and /demo/swagger*. But again those complex regex is not supported in envoy.

is there a way to do so? I understand by putting all virtualservices in a single file will solve the issue. Problem is, we have near about 20 application teams following the multiple virtualservice.yml file method to create virtualservice services from different helm releases. it would be good, if someone can put some light on to this.
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X  ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
