### ISSUE TITLE
panic:  when applying multiple serviceentry at the same time with a EnvoyFilter applied

### ISSUE THREAD

**Issue by toolchainx** [istio/istio#53590]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It seems like related to https://github.com/golang/protobuf/issues/1609 from the error message

Reproducing steps:

I applied the following EnvoyFilter

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: dns-refresh-rate
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        dns_failure_refresh_rate:
          base_interval: 60s
          max_interval: 300s
        dns_refresh_rate: 300s
        respect_dns_ttl: false
```
then applied the multiple serviceentrys at the same time in a single file
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example1.com 
  namespace: default
spec:
  host: www.example1.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example1.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example2.com 
  namespace: default
spec:
  host: www.example2.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example2.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example3.com 
  namespace: default
spec:
  host: www.example3.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example3.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example4.com 
  namespace: default
spec:
  host: www.example4.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example4.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example5.com 
  namespace: default
spec:
  host: www.example5.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example5.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example6.com 
  namespace: default
spec:
  host: www.example6.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example6.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example7.com 
  namespace: default
spec:
  host: www.example7.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example7.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example8.com 
  namespace: default
spec:
  host: www.example8.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example8.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example9.com 
  namespace: default
spec:
  host: www.example9.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example9.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example10.com 
  namespace: default
spec:
  host: www.example10.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example10.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example11.com 
  namespace: default
spec:
  host: www.example11.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example11.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example12.com 
  namespace: default
spec:
  host: www.example12.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example12.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example13.com 
  namespace: default
spec:
  host: www.example13.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example13.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example14.com 
  namespace: default
spec:
  host: www.example14.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example14.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example15.com 
  namespace: default
spec:
  host: www.example15.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example15.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example16.com 
  namespace: default
spec:
  host: www.example16.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example16.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example17.com 
  namespace: default
spec:
  host: www.example17.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example17.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example18.com 
  namespace: default
spec:
  host: www.example18.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example18.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example19.com 
  namespace: default
spec:
  host: www.example19.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example19.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example20.com 
  namespace: default
spec:
  host: www.example20.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example20.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example21.com 
  namespace: default
spec:
  host: www.example21.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example21.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example22.com 
  namespace: default
spec:
  host: www.example22.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example22.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example23.com 
  namespace: default
spec:
  host: www.example23.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example23.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example24.com 
  namespace: default
spec:
  host: www.example24.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example24.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example25.com 
  namespace: default
spec:
  host: www.example25.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example25.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example26.com 
  namespace: default
spec:
  host: www.example26.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example26.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example27.com 
  namespace: default
spec:
  host: www.example27.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example27.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example28.com 
  namespace: default
spec:
  host: www.example28.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example28.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: www.example29.com 
  namespace: default
spec:
  host: www.example29.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: www.example29.com
---

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example1.com
  namespace: default
spec:
  hosts:
    - www.example1.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example2.com
  namespace: default
spec:
  hosts:
    - www.example2.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example3.com
  namespace: default
spec:
  hosts:
    - www.example3.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example4.com
  namespace: default
spec:
  hosts:
    - www.example4.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example5.com
  namespace: default
spec:
  hosts:
    - www.example5.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example6.com
  namespace: default
spec:
  hosts:
    - www.example6.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example7.com
  namespace: default
spec:
  hosts:
    - www.example7.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example8.com
  namespace: default
spec:
  hosts:
    - www.example8.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example9.com
  namespace: default
spec:
  hosts:
    - www.example9.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example10.com
  namespace: default
spec:
  hosts:
    - www.example10.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example11.com
  namespace: default
spec:
  hosts:
    - www.example11.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example12.com
  namespace: default
spec:
  hosts:
    - www.example12.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example13.com
  namespace: default
spec:
  hosts:
    - www.example13.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example14.com
  namespace: default
spec:
  hosts:
    - www.example14.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example15.com
  namespace: default
spec:
  hosts:
    - www.example15.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example16.com
  namespace: default
spec:
  hosts:
    - www.example16.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example17.com
  namespace: default
spec:
  hosts:
    - www.example17.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example18.com
  namespace: default
spec:
  hosts:
    - www.example18.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example19.com
  namespace: default
spec:
  hosts:
    - www.example19.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example20.com
  namespace: default
spec:
  hosts:
    - www.example20.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example21.com
  namespace: default
spec:
  hosts:
    - www.example21.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example22.com
  namespace: default
spec:
  hosts:
    - www.example22.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example23.com
  namespace: default
spec:
  hosts:
    - www.example23.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example24.com
  namespace: default
spec:
  hosts:
    - www.example24.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example25.com
  namespace: default
spec:
  hosts:
    - www.example25.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example26.com
  namespace: default
spec:
  hosts:
    - www.example26.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example27.com
  namespace: default
spec:
  hosts:
    - www.example27.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example28.com
  namespace: default
spec:
  hosts:
    - www.example28.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: www.example29.com
  namespace: default
spec:
  hosts:
    - www.example29.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
  resolution: DNS
---

```

Finally, I got this error:
```	
{
    "severity": "Error",
    "timestamp": "2024-10-16T08:54:19.976949599Z",
    "message": 

    "marshaling envoy.config.cluster.v3.Cluster: size mismatch (see https://github.com/golang/protobuf/issues/1609): calculated=3, measured=0"
error marshaling Any name:  "outbound|80||www.example.com"
alt_stat_name:  "outbound|80||www.example.com;"
type:  STRICT_DNS
connect_timeout:  {
  seconds:  10
}
lb_policy:  LEAST_REQUEST
load_assignment:  {
  cluster_name:  "outbound|80||www.example.com"
  endpoints:  {
    locality:  {}
    lb_endpoints:  {
      endpoint:  {
        address:  {
          socket_address:  {
            address:  "www.example.com"
            port_value:  443
          }
        }
      }
      metadata:  {
        filter_metadata:  {
          key:  "istio"
          value:  {
            fields:  {
              key:  "workload"
              value:  {
                string_value:  ";;;;"
              }
            }
          }
        }
      }
      load_balancing_weight:  {
        value:  1
      }
    }
    load_balancing_weight:  {
      value:  1
    }
  }
}
circuit_breakers:  {
  thresholds:  {
    max_connections:  {
      value:  4294967295
    }
    max_pending_requests:  {
      value:  4294967295
    }
    max_requests:  {
      value:  4294967295
    }
    max_retries:  {
      value:  4294967295
    }
    track_remaining:  true
  }
}
dns_refresh_rate:  {
  seconds:  300
}
dns_failure_refresh_rate:  {
  base_interval:  {
    seconds:  60
  }
  max_interval:  {
    seconds:  300
  }
}
respect_dns_ttl:  true
dns_lookup_family:  V4_ONLY
common_lb_config:  {}
transport_socket:  {
  name:  "envoy.transport_sockets.tls"
  typed_config:  {
    [type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext]:  {
      common_tls_context:  {
        tls_params:  {
          tls_minimum_protocol_version:  TLSv1_2
          tls_maximum_protocol_version:  TLSv1_3
        }
        combined_validation_context:  {
          default_validation_context:  {}
          validation_context_sds_secret_config:  {
            name:  "file-root:system"
            sds_config:  {
              api_config_source:  {
                api_type:  GRPC
                transport_api_version:  V3
                grpc_services:  {
                  envoy_grpc:  {
                    cluster_name:  "sds-grpc"
                  }
                }
                set_node_on_first_message_only:  true
              }
              resource_api_version:  V3
            }
          }
        }
      }
      sni:  "www.example.com"
    }
  }
}
metadata:  {
  filter_metadata:  {
    key:  "istio"
    value:  {
      fields:  {
        key:  "alpn_override"
        value:  {
          string_value:  "false"
        }
      }
      fields:  {
        key:  "config"
        value:  {
          string_value:  "/apis/networking.istio.io/v1alpha3/namespaces/biz/destination-rule/www.example.com"
        }
      }
      fields:  {
        key:  "external"
        value:  {
          bool_value:  true
        }
      }
      fields:  {
        key:  "services"
        value:  {
          list_value:  {
            values:  {
              struct_value:  {
                fields:  {
                  key:  "host"
                  value:  {
                    string_value:  "www.example.com"
                  }
                }
                fields:  {
                  key:  "name"
                  value:  {
                    string_value:  "www.example.com"
                  }
                }
                fields:  {
                  key:  "namespace"
                  value:  {
                    string_value:  "biz"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
filters:  {
  name:  "istio.metadata_exchange"
  typed_config:  {
    [type.googleapis.com/udpa.type.v1.TypedStruct]:  {
      type_url:  "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange"
      value:  {
        fields:  {
          key:  "enable_discovery"
          value:  {
            bool_value:  true
          }
        }
        fields:  {
          key:  "protocol"
          value:  {
            string_value:  "istio-peer-exchange"
          }
        }
      }
    }
  }
}
: marshaling envoy.config.cluster.v3.Cluster: size mismatch (see https://github.com/golang/protobuf/issues/1609): calculated=3, measured=0
}```

### Version

```Text
istioctl version

client version: 1.20.3
istiod version: 1.23.2-asm.2
istiod version: 1.23.2-asm.2
data plane version: 1.23.2-asm.2 (149 proxies)
```
kubectl version
```
Client Version: v1.30.5-dispatcher
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4-gke.1348001
```
```


### Additional Information

_No response_
