### ISSUE TITLE
Enabling native sidecar injection to particular namespace only

### ISSUE THREAD

**Issue by rifler** [istio/istio#53605]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Hello!
We faced issue with collecting istio-proxy sidecar's metrics in native sidecar mode - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7287

However, there are namespaces where only Jobs live and that's why metrics collection is not so important in such namespaces.

Also this feature will allow smooth transition to native sidecar feature.

**Describe alternatives you've considered**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    istio-injection-mode: native-sidecar
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
