### ISSUE TITLE
Sidecar EgressListener Wildcard Options

### ISSUE THREAD

**Issue by pickmylight** [istio/istio#53634]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

Describe alternatives you've considered
There is a possibility to enhance the usage of resources by using a Sidecar Object. The feature is quite useful in multi cluster environments. There is however a significant wildcard feature missing from the documentation:

One can set a wildcard definition for the IstioEgressListener Object:

```yaml
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
    - "*/*.foo.service"  <- wildcard DNS config
```
The wildcard definition of a DNS definition is quite a cool feature. Would it be possible to specify wildcard Namespace definitions? This could look like this:

```yaml
spec:
  egress:
  - hosts:
    - "./*"
    - "*-system/*" # <- wildcard namespace AND wildcard DNS config
```

Developers could then scope the Sidecar usage to their namespaces if they adhere to a specific namespace schematic without editing the Sidecar Object every time a new namespace is created.

**Describe alternatives you've considered**

Alternatives could be writing a new operator for just the Sidecar Object containing all the namespaces in a specific scheme. This would be quite a complicated feature, since it has to listen to every namespace created. Thus there would be no possibility to use this feature if there is another namespace outside of the scheme to be added.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[x] Multi Control Plane
