### ISSUE TITLE
`istio-csr` fails in Istio 1.24+ with `missing selected ALPN property` error message

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53659]
This is a preemptive warning about a breakage in 1.24 impacting `istio-csr`. If you see the above error message in the istio-proxy container, you can:

* Upgrade istio-csr to a version with https://github.com/cert-manager/istio-csr/pull/422. At the time of writing, the latest version, v0.12.0 does NOT have this fix; likely it will be v0.13.0 or v0.12.1
* Set in the install of istio:
```yaml
meshConfig
  defaultConfig
    proxyMetadata:
      GRPC_ENFORCE_ALPN_ENABLED: "false"
```
