### ISSUE TITLE
How to Change Istio Trust Domain Without Downtime for Multi-Cluster Mesh Configuration

### ISSUE THREAD

**Issue by praveenjindal62** [istio/istio#53666]
Hello Community,

I currently have multiple Kubernetes clusters running with Istio versions 1.22 and 1.23. Istio is deployed in our clusters using the istiod Helm charts, and we are using the configuration shown below. We aim to transition to a multi-cluster Istio mesh, which requires establishing trust between the Istio meshes of two clusters. Since we haven't specified any `trustDomain` configuration inside `meshConfig`, Istio is currently using the default trust domain, which I believe is `cluster.local`.

When I attempt to update the `trustDomain` and restart the control plane, the mesh breaks, and communication between proxies results in a "CERTIFICATE_VERIFY_FAILED" error (as mentioned below). Is there a way to change the trust domain without breaking the mesh and causing downtime? Ideally, we are looking for a phased approach to propagate changes gracefully and achieve a multi-cluster Istio mesh configuration.

Thank you.

```yaml
  istio_cni:
    enabled: true
  global:
    hub: docker.io/istio
    tag: 1.23.1
    logAsJson: true
    proxy:
      image: proxyv2
    multiCluster:
      enabled: true
      clusterName: ""
    defaultPodDisruptionBudget:
      enabled: false
    configValidation: false

  pilot:
    image: pilot
    env:
      ENABLE_LEGACY_FSGROUP_INJECTION: "false"
      PILOT_SCOPE_GATEWAY_TO_NAMESPACE: "true"
      VERIFY_CERTIFICATE_AT_CLIENT: "true"
    autoscaleMax: 8
    autoscaleMin: 2
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    accessLogFormat: |
      {
        "authority": "%REQ(:AUTHORITY)%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "duration": "%DURATION%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "route_name": "%ROUTE_NAME%",
        "start_time": "%START_TIME%",
        "trace_id": "%REQ(X-B3-TRACEID)%",
        "traceparent": "%REQ(TRACEPARENT)%",
        "upstream_cluster": "%UPSTREAM_CLUSTER_RAW%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
        "user_agent": "%REQ(USER-AGENT)%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "downstream_resp_send_duration": "%COMMON_DURATION(DS_TX_BEG:DS_TX_END:ms)%",
        "upstream_req_send_duration": "%COMMON_DURATION(US_TX_BEG:US_TX_END:ms)%",
        "downstream_req_recv_duration": "%COMMON_DURATION(DS_RX_BEG:DS_RX_END:ms)%",
        "upstream_resp_recv_duration": "%COMMON_DURATION(US_RX_BEG:US_RX_END:ms)%",
        "upstream_duration": "%COMMON_DURATION(US_TX_BEG:US_RX_END:ms)%",
        "downstream_duration": "%COMMON_DURATION(DS_RX_BEG:DS_TX_END:ms)%"
      }
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      extraStatTags:
        - request_operation
      tracing:
        zipkin:
          address: opentelemetry-collector.lightops-obs-agent:9411
    extensionProviders:
      - envoyExtAuthzHttp:
          headersToDownstreamOnDeny:
            - content-type
            - set-cookie
          headersToUpstreamOnAllow:
            - authorization
            - path
            - x-auth-request-user
            - x-auth-request-email
            - x-auth-request-access-token
            - x-auth-request-groups
          includeRequestHeadersInCheck:
            - authorization
            - cookie
            - x-forwarded-proto
          includeAdditionalHeadersInCheck:
            x-forwarded-host: '%REQ(:authority)%'
            x-auth-request-redirect: '%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%'
          port: 4180
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        name: oauth2-proxy
  telemetry:
    enabled: true
    v2:
      enabled: false
      prometheus:
        enabled: false
```

After changing `trustDomain` when I try to reach any service through Istio Gateway, I see below error on web browser
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end
```

This error goes away, if I restart the proxy of gateway and the service.
