### ISSUE TITLE
[1.20-4-asm.0] Gateway with TLS passthrough does not work when another gateway with TLS termination has a wildcard domain defined

### ISSUE THREAD

**Issue by nvoskresenskiy** [istio/istio#53662]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am using the following configuration:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  ...
    components:
      ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        k8s:
          service: 
            type: LoadBalancer
            loadBalancerIP: x.x.x.x
            ports:
              - name: status-port
                port: 15020
              - name: https
                port: 443
                targetPort: 10443
                protocol: TCP
              - name: tls-passthrough
                port: 8443
                targetPort: 8443
                protocol: TCP            
...
```

With two gateways, 1 VirtualService each:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - hosts:
        - "*.api.dev.gcp.myorg.com"
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: tls-keys
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myservice
  namespace: mynamespace
spec:
  hosts:
    - myservice.api.dev.gcp.myorg.com
  gateways:
    - istio-system/api-gateway
  http:
    - match:
        - uri: 
            prefix: /
      route:
        - destination:
            host: myservice.api.dev.gcp.myorg.com
            port:
              number: 443
```

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: eck-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - hosts:
        - "opensearch-cluster-master.eck.dev.gcp.myorg.com"
      port:
        number: 443
        name: tls-passthrough
        protocol: TLS
      tls:
        mode: PASSTHROUGH
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: opensearch-cluster-master
  namespace: opensearch-system
spec:
  hosts:
    - opensearch-cluster-master.eck.dev.gcp.myorg.com
  gateways:
    - istio-system/eck-gateway
  tls:
   - match:
        - port: 8443
          sniHosts:
            - opensearch-cluster-master.eck.dev.gcp.myorg.com
      route:
        - destination:
            host: opensearch-cluster-master.opensearch-system.svc.cluster.local
            port:
              number: 9200
```

Applying this configuration results in a log message

> gateway omitting listener "0.0.0.0_8443" due to: must have more than 0 chains in listener
and the address https://opensearch-cluster-master.eck.dev.gcp.myorg.com:8443/ stays unavailable with "Connection Refused"
the service on api-gateway at https://myservice.api.dev.gcp.myorg.com remains accessible as expected
logs contain no further details at debug level

However, if i change spec.servers.hosts in api-gateway to list the first service CN explicitly and not use the wildcard, both services become available, AND they can now coexist on the same ingressgateway port 443

The workaround is suboptimal because it defeats the purpose of having a plug-and-play gateway configuration

### Version

```Text
client version: 1.20-4-asm.7
control plane version: 1.20-4-asm.0
data plane version: 1.20-4-asm.0

k8s version: 1.30.5-gke.1014001
```
