### ISSUE TITLE
A duplicate ServiceEntry in two different namespaces is causing issues

### ISSUE THREAD

**Issue by iampratapak** [istio/istio#53667]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I have two namespaces, **dx-system** and **dx-prod**, each containing a ServiceEntry. The ServiceEntry in the dx-system namespace has HTTP on port 1024 and TLS on port 443, defined as follows:
```
spec:
  exportTo:
  - '*'
  hosts:
  - cptawcwqy.fusionapps.ocs.oc-test.com
  location: MESH_EXTERNAL
  ports:
  - name: http-servicemesh-port-1024
    number: 1024
    protocol: HTTP
  - name: tls-origination-port-1024
    number: 443
    protocol: TLS
  resolution: DNS
```
Meanwhile, the ServiceEntry in the dx-prod namespace has only TLS on port 443:
```
spec:
  exportTo:
  - '*'
  hosts:
  - cptawcwqy.fusionapps.ocs.oc-test.com
  location: MESH_EXTERNAL
  ports:
  - name: tls-443
    number: 443
    protocol: TLS
  resolution: DNS
```
When I use curl from a pod in the dx-system namespace with the HTTP protocol, the calls fail with a 503 Service Unavailable error, while HTTPS calls work as expected.

```
HTTP/1.1
> Host: cptawcwqy.fusionapps.ocs.oc-test.com:1024
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Mon, 28 Oct 2024 02:48:57 GMT
< server: envoy
<
* Connection #0 to host cptawcwqy.fusionapps.ocs.oc-test.com left intact
upstream connect error or disconnect/reset before headers. reset reason: connection timeoutbash-4.4$
```

It seems that the ServiceEntry in the dx-prod namespace is being used even for requests originating from the dx-system namespace. If I add port 1024 to the ServiceEntry in dx-prod, HTTP calls work as expected, and no 503 Service Unavailable error occurs.

We only noticed this issue after upgrading Istio to 1.22.3, whereas in 1.21.2, the same configuration worked for both HTTP and HTTPS calls originating from the dx-system namespace.

Is adding port 1024 to the dx-prod ServiceEntry the correct fix for this issue, or should we take another approach? Is spec.exportTo = "*" causing the issue?

### Version

```Text
client version: 1.15.1
control plane version: 1.22
data plane version: 1.22-dev (36 proxies)

Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.30.1
```
