### ISSUE TITLE
[helm charts] gateway chart does not correctly template "null" values for resources

### ISSUE THREAD

**Issue by morremeyer** [istio/istio#53673]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This is a follow-up issue to #49962.

Unfortunately, #52514 does not resolve the issue of resources not being able to be unset.

Due to the custom value processing in [`templates/zzz_profile.yaml`](https://github.com/istio/istio/blob/14bf1bd58ad1f3010055920fe8dd9e088ad292ce/manifests/charts/gateway/templates/zzz_profile.yaml), when setting any resource to `null`, the templated manifest contains the `null` literally instead of removing the resource configuration.

This is different than how helm works without custom value processing, where setting a `null` value removes the key, and effectively makes it impossible to unset the default values for the configured resources.

### Expected behavior

```
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
helm template test istio/gateway --version 1.23.2 --set resources.limits.cpu=null | grep -C 10 resources
```

should contain

```
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

but does contain

```
          resources:
            limits:
              cpu: null
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

### Version

```Text
1.23.2
```

**Comment by rifler** [comment]
it is also impossible to unset `global.proxy.resources.limits.cpu` is istio/istiod chart

**Comment by keithmattix** [comment]
Thanks for raising this! Out of curiosity, does using ~ instead of "null" work as expected?

**Comment by morremeyer** [comment]
No, none of the values that represent a null value in yaml work.

**Comment by keithmattix** [comment]
Yikes /cc @howardjohn. Looks like the helm profile merging might need to have some explicit logic for null values

**Comment by wilreichert** [comment]
Hitting this in the Istio 1.24.2 gateway chart

helm values
```
resources:
  limits:
    cpu: ~
    memory: ~
  requests:
    cpu: "4"
    memory: 10Gi
```

helm template:
```
        resources:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: "4"
            memory: 10Gi
```

helm upgrade:
```
STDERR:
  Error: UPGRADE FAILED: unable to find a previously successful release when attempting to rollback. original upgrade error: failed to create resource: Deployment.apps "istio-gateway-private-1-24" is invalid: [spec.template.spec.containers[0].resources.requests: Invalid value: "4": must be less than or equal to cpu limit of 0, spec.template.spec.containers[0].resources.requests: Invalid value: "10Gi": must be less than or equal to memory limit of 0]
```

Previously in 1.20 we just had an empty `limits:` field which worked. The updated schema changes broke that approach.
