### ISSUE TITLE
Sidecar resources is not effectively capturing calls to the canary version

### ISSUE THREAD

**Issue by alexandresavicki** [istio/istio#53674]
## Description

A have `app-a` that make calls to `app-b` for `app-a` i have declared sidecar like this:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app-a
  namespace: prod
spec:
  egress:
  - hosts:
    - istio-system/*
    - '*/app-b.prod.svc.cluster.local'
  workloadSelector:
    labels:
      app: app-a
```

I've using [ArgoRollouts](https://argoproj.github.io/argo-rollouts/) to make canary releases integrated with Istio here my virtual service configuration:

```yaml 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-a
  namespace: prod
spec:
  gateways:
  - mesh
  hosts:
  - app-a
  http:
  - match:
    - sourceLabels:
        app: prometheus
      uri:
        prefix: /metrics
    route:
    - destination:
        host: app-a
        port:
          number: 80
  - fault:
      abort:
        httpStatus: 403
        percentage:
          value: 100
    match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: app-a
        port:
          number: 80
  - name: primary
    route:
    - destination:
        host: app-a
        port:
          number: 80
        subset: stable
      weight: 50
    - destination:
        host: app-a
        port:
          number: 80
        subset: canary
      weight: 50
```

I've using prometheus metrics to monitor which services isn't declare sidecar correctly:

```
sum by (destination_workload, source_workload, destination_app, destination_service_name) (rate(istio_requests_total{destination_service_name="PassthroughCluster",destination_workload!="unknown",source_workload!="blackbox-exporter"}[7d])) > 0
```

So when a deploy my `app-a` the process of canary starts and i start to see metrics with `PassthroughCluster` even i've declared the `app-b` on my sidecar configuration.

```
{destination_app="app-b", destination_service_name="PassthroughCluster", destination_workload="app-b-75df8bc989", source_workload="app-a-576989dc85"}
```

Today we use `global.outboundTrafficPolicy.mode` as `ALLOW_ANY`

Is that an expected behavior? In the future we would like to change to `REGISTRY_ONLY` to prevent calls going outside of k8s cluster and came back to access an app that live in the service mesh, but i'm worry with my apps using canary release i think the canary revision won't be able to communicate with services even i declare it on sidecar resource.

**Comment by howardjohn** [comment]
I don't get it. The traffic is `app-a -> app-b`? But the virtual service is customizing the behavior of calling `app-a`, not `app-b`?

Is the virtuyal service supposed to be for `app-b`?

**Comment by howardjohn** [comment]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: shell
  namespace: prod
spec:
  egress:
  - hosts:
    - istio-system/*
    - '*/echo.prod.svc.cluster.local'
  workloadSelector:
    labels:
      app: shell
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo
  namespace: prod
spec:
  gateways:
  - mesh
  hosts:
  - echo
  http:
  - match:
    - sourceLabels:
        app: prometheus
      uri:
        prefix: /metrics
    route:
    - destination:
        host: echo
        port:
          number: 80
  - fault:
      abort:
        httpStatus: 403
        percentage:
          value: 100
    match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: echo
        port:
          number: 80
  - name: primary
    route:
    - destination:
        host: echo
        port:
          number: 80
        subset: stable
      weight: 50
    - destination:
        host: echo
        port:
          number: 80
        subset: canary
      weight: 50
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: echo
spec:
  host: echo.prod.svc.cluster.local
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: shell
        image: howardjohn/shell
        imagePullPolicy: IfNotPresent
        args:
          - /bin/sleep
          - infinity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
      - name: echo
        image: gcr.io/istio-testing/app:latest
        imagePullPolicy: IfNotPresent
        args:
        - --tcp=9090
        - --tcp=9091
        - --server-first=9091
        - --port=80
        - --grpc=7070
        - --port=443
        - --tls=443
        - --crt=/cert.crt
        - --key=/cert.key
        env:
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: tcp
    port: 9090
  - name: tcp-sf
    port: 9091
  - name: grpc
    port: 7070
```

With this config, it seems to work fine

**Comment by alexandresavicki** [comment]
> I don't get it. The traffic is `app-a -> app-b`? But the virtual service is customizing the behavior of calling `app-a`, not `app-b`?
> 
> Is the virtuyal service supposed to be for `app-b`?

Sorry, the virtual service it's from app-a which is in process of canary deployment, so ArgoRollouts shift traffic using `trafficRouting`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
spec:
  minReadySeconds: 5
  replicas: 6
  selector:
    matchLabels:
      app: app-a
      release: app-a-prod
  strategy:
    canary:
      abortScaleDownDelaySeconds: 120
      steps:
        - setWeight: 1
        - pause:
            duration: 30m
        - analysis:
            args:
              - name: app-name
                valueFrom:
                  fieldRef:
                    fieldPath: 'metadata.labels[''application_name'']'
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: canary-template-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: stable-template-hash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: analisys-time
                value: 30m
            templates:
              - clusterScope: true
                templateName: global-success-hash-rate
        - setWeight: 10
        - pause:
            duration: 1h
        - analysis:
            args:
              - name: app-name
                valueFrom:
                  fieldRef:
                    fieldPath: 'metadata.labels[''application_name'']'
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: canary-template-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: stable-template-hash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: analisys-time
                value: 1h
            templates:
              - clusterScope: true
                templateName: global-success-hash-rate
        - setWeight: 65
        - pause:
            duration: 3h
        - analysis:
            args:
              - name: app-name
                valueFrom:
                  fieldRef:
                    fieldPath: 'metadata.labels[''application_name'']'
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: canary-template-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: stable-template-hash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: analisys-time
                value: 3h
            templates:
              - clusterScope: true
                templateName: global-success-hash-rate
        - setWeight: 100
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: app-a
            stableSubsetName: stable
          virtualService:
            name: app-a
            routes:
              - primary
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-a
status:
  HPAReplicas: 7
  availableReplicas: 7
  blueGreen: {}
  canary:
    weights:
      canary:
        podTemplateHash: 54d5b6c46d
        weight: 10
      stable:
        podTemplateHash: 7c49b45bb
        weight: 90
  conditions:
    - lastTransitionTime: '2024-10-28T12:15:17Z'
      lastUpdateTime: '2024-10-28T12:15:17Z'
      message: Rollout has minimum availability
      reason: AvailableReason
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-10-28T14:38:16Z'
      lastUpdateTime: '2024-10-28T14:38:16Z'
      message: Rollout is not healthy
      reason: RolloutHealthy
      status: 'False'
      type: Healthy
    - lastTransitionTime: '2024-10-28T14:38:16Z'
      lastUpdateTime: '2024-10-28T14:38:16Z'
      message: RolloutCompleted
      reason: RolloutCompleted
      status: 'False'
      type: Completed
    - lastTransitionTime: '2024-10-28T15:10:24Z'
      lastUpdateTime: '2024-10-28T15:10:24Z'
      message: Rollout is paused
      reason: RolloutPaused
      status: Unknown
      type: Progressing
    - lastTransitionTime: '2024-10-28T15:10:24Z'
      lastUpdateTime: '2024-10-28T15:10:24Z'
      message: Rollout is paused
      reason: RolloutPaused
      status: 'True'
      type: Paused
  controllerPause: true
  currentPodHash: 54d5b6c46d
  currentStepHash: 7fd74588d7
  currentStepIndex: 4
  message: CanaryPauseStep
  observedGeneration: '56'
  pauseConditions:
    - reason: CanaryPauseStep
      startTime: '2024-10-28T15:10:24Z'
  phase: Paused
  readyReplicas: 7
  replicas: 7
  selector: 'app=app-a,release=app-a-prod'
  stableRS: 7c49b45bb
  updatedReplicas: 1
  workloadObservedGeneration: '10'
```

And app-a make calls to app-b internally using service mesh (aka http://app-b) during the canary process.

**Comment by howardjohn** [comment]
I am super confused. You are calling `app-b`, but everything about the canary is about calling `app-a`....?

**Comment by alexandresavicki** [comment]
Yes, it's a internal dependency... app-a it's a frontend that calls app-b backend using service mesh.

I don't know if you are familiar with Argo Rollouts canary process. Let me try to explain for you.

Here i have a simplified virtual service for app-a

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-a
  namespace: prod
spec:
  gateways:
    - mesh
  hosts:
    - app-a
  http:
    - name: primary
      route:
        - destination:
            host: app-a
            port:
              number: 80
            subset: stable
          weight: 35
        - destination:
            host: app-a
            port:
              number: 80
            subset: canary
          weight: 65
```

When ArgoRollouts start deployment process a new replicaset (canary) of app-a will be created:

*Canary version*
```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-a-54d5b6c46d
  namespace: prod
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: app-a
      release: app-a-prod
      rollouts-pod-template-hash: 54d5b6c46d
```

*Stable version*
```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-a-7c49b45bb
  namespace: prod
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: app-a
      release: app-a-prod
      rollouts-pod-template-hash: 7c49b45bb
```

Argo Rollouts will control the traffic using destination rule like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-a
  namespace: prod
spec:
  host: app-a
  subsets:
    - labels:
        app: app-a
        rollouts-pod-template-hash: 54d5b6c46d
      name: canary
    - labels:
        app: app-a
        rollouts-pod-template-hash: 7c49b45bb
      name: stable
```

Then Argo Rollout start to analyze prometheus metrics (we use _istio_requests_totals_) of error rate of new version for app-a, once reach the  treshould configured to app-a, ArgoRollouts will shift more traffic into canary version increasing the weight on virtual service of app-a.

```yaml
  http:
    - name: primary
      route:
        - destination:
            host: app-a
            port:
              number: 80
            subset: stable
          weight: 20
        - destination:
            host: app-a
            port:
              number: 80
            subset: canary
          weight: 80
```

In the mean time app-a are making calls do app-b since it's a internal dependency.

This is how ArgoRollouts make progressive delivery using Istio.

Now let's try to explain the main problem, because of Istio service discovery every POD receive configs of all apps that runs on service mesh this can increase a lot os memory consumption of `istio-proxy` container. 
To avoid this behavior we use [Istio's Sidecar resource ](https://istio.io/latest/docs/reference/config/networking/sidecar/) to limite app-a only to receive configs from app-b.

Since my app-a doesn't need to receive config of all others ~1k services running in service mesh we declare only app-b on sidecar because app-a only needs to call app-b

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app-a
  namespace: prod
spec:
  egress:
  - hosts:
    - istio-system/*
    - '*/app-b.prod.svc.cluster.local'
  workloadSelector:
    labels:
      app: app-a
```

But i observe the behavior of `PassthroughCluster` which means the requests from app-a to app-b it's bypassing service mesh even i've declared on Sidecar resource the Egress to app-b.

I'm sorry for the lengthy text in the Bible. I appreciate your understanding.
