### ISSUE TITLE
Smart merging of HttpProtocolOptions in EnvoyFilter Cluster patch

### ISSUE THREAD

**Issue by wtzhang23** [istio/istio#53685]
**Describe the feature request**
Similar to how the transport socket is smartly merged [here](https://github.com/istio/istio/blob/4b6da345431ffd447a1dfe246b9140b7c51f49eb/pilot/pkg/networking/core/envoyfilter/cluster_patch.go#L33-L66), we should consider specially handling [typed_extension_protocol_options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions).

**Describe alternatives you've considered**
Currently, users will have to fill out all fields. This is not a major concern, but requires care that the values are correctly copied and introduces risk should there be changes (e.g. changing the protocol of a service from http1 <-> 2)

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Use cases include:

Patch for selective auto sni when `ENABLE_AUTO_SNI=false`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auto-sni
  namespace: istio-system # apply globally
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        service: "*.example.com"
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            upstream_http_protocol_options:
              # This will ensure that the SNI is set to the value of the host header
              auto_sni: true
              # This will ensure that the certificate returned by the server has a valid subject or SAN
              # that matches the host header
              auto_san_validation: true
            explicit_http_config:
              http2_protocol_options: {}
```

Adding upstream HTTP filter (e.g. admission control filter)
