### ISSUE TITLE
Envoyfilter setting Header from JWT not occuring before routing

### ISSUE THREAD

**Issue by FischlerA** [istio/istio#53689]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have an Envoyfilter, that checks the incoming request for the existence of a JWT and validates it validity. After checking the JWT the sub claim from the JWT is read and set as header, the envoyfilter works as a i can see the JWT when i add the header to the accesslog.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    meta.helm.sh/release-name: test-istio-configuration
    meta.helm.sh/release-namespace: istio-system
  generation: 3
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router 
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.jwt_authn
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
            providers:
              idsrvprovider:
                claim_to_headers:
                  - claim_name: sub
                    header_name: sub
                forward: true
                issuer: xxx
                remote_jwks:
                  cache_duration: 3600s
                  http_uri:
                    cluster: idsrv
                    timeout: 10s
                    uri: >-
                      xxx/.well-known/openid-configuration/jwks
            rules:
              - match:
                  prefix: /hc
              - match:
                  prefix: /health
              - match:
                  prefix: /
                requires:
                  requires_any:
                    requirements:
                      - provider_name: idsrvprovider
                      - allow_missing_or_failed: {}
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value:
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: idsrv
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: xxx
                          port_value: 443
          name: idsrv
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': >-
                type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              sni: xxx
          type: LOGICAL_DNS
  workloadSelector:
    labels:
      app: istio-ingress
```

I have a VirtualService that routes based on the presence and value of the sub header.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
  name: fake-host
  namespace: fake
spec:
  gateways:
    - istio-ingress/fake-host-gateway
  hosts:
    - yyy
    - zzz
  http:
    - match:
        - headers:
            sub:
              regex: fake1|fake2
      name: a-b-test
      route:
        - destination:
            host: fake-host
            port:
              number: 8080
            subset: canary
          weight: 100
    - name: http
      route:
        - destination:
            host: fake-host
            port:
              number: 8080
            subset: stable
          weight: 100
        - destination:
            host: fake-host
            port:
              number: 8080
            subset: canary
          weight: 0
```

Whenever i add the sub header manually and send a request with Postman my request reaches the canary.

However, when sending a request with a JWT the sub header is added but my request is being routed to stable, not the canary.
I'm assuming that the Envoyfilter occurs after routing decisions have already been made.

The experimental Claims to header https://istio.io/latest/docs/tasks/security/authentication/claim-to-header/ doesn't seem to match what we need, as we have some requests that need to be allowed into the cluster even though they do not have any JWT.

What can i do to make the Envoyfilter occur before the routing decisions? 
Any help would be greatly appreciated.

### Version

```Text
Istio 1.22.1
```
