### ISSUE TITLE
Waypoint proxy not applying AuthorizationPolicy with JWT rule

### ISSUE THREAD

**Issue by stephen-tatari** [istio/istio#53723]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have an ingress gateway that enables an extension provider to authenticate against Okta prior to serving up requests. This works fine in ambient mode.

My issue is that I want to further restrict authorization such that a specific service (`jaeger-query` in the `jaeger-system` namespace in my pasted configuration) requires the viewer to be a member of a specific group.

I was able to go through the Layer 7 authorization policy testing in the `bookinfo` demo as part of the official documentation, and I've verified once I create an AuthorizationPolicy in the `jaeger-system` namespace that does simple HTTP request method rules that they're applied as expected.

However, I cannot get the following resources to work:

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: oauth2-waypoint
  namespace: jaeger-system
spec:
  jwtRules:
    - forwardOriginalToken: true
      issuer: https://tatari.okta.com/oauth2/default
      jwksUri: https://tatari.okta.com/oauth2/default/v1/keys
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-waypoint
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: oauth2-waypoint
  namespace: jaeger-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              - '*'
      when:
        - key: request.auth.claims[groups]
          values:
            - data-platform
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-waypoint
```

Additionally, though I can see logs from the waypoint when these resources are defined, I don't see any logs indicating that they're being evaluated while attempting to access the `jaeger-query` service (even after setting `rbac`, `jwt`, `oauth2` and `ext_authz` to `debug`).

From the viewer's perspective (who is not a member of the above group), accessing the Jaeger UI through the ingress first prompts them to log in to Okta, but then they're able to see the Jaeger UI.

Here's the namespace:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
    istio.io/dataplane-mode: ambient
    kubernetes.io/metadata.name: jaeger-system
  name: jaeger-system
spec:
  finalizers:
    - kubernetes
```
and the service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-query
    app.kubernetes.io/part-of: jaeger
    istio.io/use-waypoint: istio-waypoint
  name: jaeger-query
  namespace: jaeger-system
  ownerReferences:
    - apiVersion: jaegertracing.io/v1
      controller: true
      kind: Jaeger
      name: jaeger
      uid: 502cfc8b-d58c-4448-bfd5-b45051d39c6e
spec:
  clusterIP: 172.20.21.147
  clusterIPs:
    - 172.20.21.147
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
    - name: admin-http
      port: 16687
      protocol: TCP
      targetPort: 16687
  selector:
    app: jaeger
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-query
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP

```

### Version

```Text
❯ istioctl version
client version: 1.23.2
control plane version: 1.23.2
data plane version: 1.23.2 (73 proxies)
❯ kubectl version
Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4-eks-a737599
```

### Additional Information

[bug-report.tar.gz](https://github.com/user-attachments/files/17578940/bug-report.tar.gz)

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
The config dump looks correct to me; it's pretty weird you aren't getting envoy logs for rbac. Maybe set the log level to trace as a last resort?

**Comment by stephen-tatari** [comment]
Nope. ran `istioctl pc log -n jaeger-system deploy/istio-waypoint --level rbac: trace`, attempted the same operation, no logs.

**Comment by stephen-tatari** [comment]
Nope. ran `istioctl pc log -n jaeger-system deploy/istio-waypoint --level rbac: trace`, attempted the same operation, no logs.

**Comment by stephen-tatari** [comment]
Not sure if it helps here, but I did notice if I add a single L4 Auth Policy to the namespace, ztunnel starts rejecting connections that don't match..

Tested with:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-monitoring
  namespace: jaeger-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - opencost
              - jaeger-system
              - prometheus-system
```

Then saw logs indicating that connections from my `ingress-gateways` namespace (where all the ingress lives) were being rejected to the `jaeger-query` service:

```
istio-system ztunnel-dckfd istio-proxy 2024-10-31T19:31:23.837358Z      error   access  connection complete     src.addr=10.0.33.29:52614 src.workload="oauth2-ingress-gateway-istio-64f6bc5b87-v756z" src.namespace="ingress-gateways" src.identity="spiffe://cluster.local/ns/ingress-gateways/sa/oauth2-ingress-gateway-istio" dst.addr=10.0.17.117:15008 dst.hbone_addr=10.0.17.117:16686 dst.service="jaeger-query.jaeger-system.svc.cluster.local" dst.workload="jaeger-query-56d575c9fc-zqbvj" dst.namespace="jaeger-system" dst.identity="spiffe://cluster.local/ns/jaeger-system/sa/jaeger" direction="inbound" bytes_sent=0 bytes_recv=0 duration="0ms" error="connection closed due to policy rejection"
```

Somehow the ztunnel is not handing off policy evaluation to the waypoint.

**Comment by stephen-tatari** [comment]
Also, I tried creating a `sleep` pod in the `jaeger-system` namespace, then called curl against the `jaeger-query` service. This time, I got `RBAC: access denied` with similar logs from waypoint:

```
jaeger-system istio-waypoint-564ffd64c7-x7gg9 istio-proxy {"time":"2024-10-31T20:16:46.192787Z","level":"debug","scope":"envoy rbac","msg":"checking request: requestedServerName: , sourceIP: 10.0.24.38:38028, directRemoteIP: envoy://internal_client_address/, remoteIP: 10.0.24.38:38028,localAddress: 172.20.21.147:16686, ssl: none, headers: ':authority', 'jaeger-query.jaeger-system.svc.cluster.local:16686'\n':path', '/'\n':method', 'GET'\n':scheme', 'http'\n'user-agent', 'curl/8.10.1'\n'accept', '*/*'\n'x-forwarded-proto', 'http'\n'x-request-id', '4447f472-95e0-414c-b5bd-01facedc3589'\n, dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:132","thread":"21"}
jaeger-system istio-waypoint-564ffd64c7-x7gg9 istio-proxy {"time":"2024-10-31T20:16:46.192832Z","level":"debug","scope":"envoy rbac","msg":"enforced denied, matched policy none","caller":"external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:194","thread":"21"}
```

and if I modify the policy to allow a GET from that pod:
```
  - from:
    - source:
        principals:
        - cluster.local/ns/jaeger-system/sa/sleep
    to:
    - operation:
        methods:
        - GET
```

I can see it allowing the request:

```
jaeger-system istio-waypoint-564ffd64c7-x7gg9 istio-proxy {"time":"2024-10-31T20:18:25.250323Z","level":"debug","scope":"envoy rbac","msg":"checking request: requestedServerName: , sourceIP: 10.0.24.38:38028, directRemoteIP: envoy://internal_client_address/, remoteIP: 10.0.24.38:38028,localAddress: 172.20.21.147:16686, ssl: none, headers: ':authority', 'jaeger-query.jaeger-system.svc.cluster.local:16686'\n':path', '/'\n':method', 'GET'\n':scheme', 'http'\n'user-agent', 'curl/8.10.1'\n'accept', '*/*'\n'x-forwarded-proto', 'http'\n'x-request-id', 'd59687c1-8034-45a9-908a-3fe6573b0bd8'\n, dynamicMetadata: ","caller":"external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:132","thread":"21"}
jaeger-system istio-waypoint-564ffd64c7-x7gg9 istio-proxy {"time":"2024-10-31T20:18:25.250361Z","level":"debug","scope":"envoy rbac","msg":"enforced allowed, matched policy ns[jaeger-system]-policy[oauth2-waypoint]-rule[0]","caller":"external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:182","thread":"21"}
```
