### ISSUE TITLE
Istio VirtualService is not forwarding TCP request

### ISSUE THREAD

**Issue by panasiuk-r** [istio/istio#53780]
Hi guys,

I am attempting to deploy the Pritunl VPN into my Kubernetes cluster and configure Istio to forward all requests on port 1194 to Pritunl. I've successfully started the VPN server and managed to connect to it via port forwarding, but the Istio VirtualService does not forward requests to Pritunl as expected.

Here is my VirtualService configuration:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vpn-virtual-service
  namespace: aks-istio-ingress
spec:
  gateways:
    - aks-external-gateway
  hosts:
    - '*'
  tcp:
    - match:
        - port: 1194
      route:
        - destination:
            host: pritunl.pritunl.svc.cluster.local
            port:
              number: 1194
```
Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: aks-external-gateway
  namespace: aks-istio-ingress
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
    - hosts:
        - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - '*'
      port:
        name: vpn
        number: 1194
        protocol: TCP
```
I've been able to connect to the VPN server using port forwarding:
```
$ telnet 127.0.0.1 45285
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```
DNS resolution works inside the cluster too:
```
$ kubectl run -it --rm --restart=Never test-pod --image=alpine -- sh
If you don't see a command prompt, try pressing enter.
/ # nc -zv pritunl.pritunl.svc.cluster.local 1194
pritunl.pritunl.svc.cluster.local (10.0.150.161:1194) open
```
I have successfully forwarded HTTP traffic via different VirtualService and same gateway, so the IP and ingress gateway configurations seem correct. Any suggestions on why the TCP traffic on port 1194 is not being forwarded to Pritunl?
