### ISSUE TITLE
RequestAuthentication and AuthorizationPolicy applied to Gateway

### ISSUE THREAD

**Issue by scorgatelli** [istio/istio#53790]
I have a situation where we would like to use `RequestAuthentication` to validate JWT tokens on a per-route basis where other routes require different forms of authentication that may not be in a valid JWT format. When other authorization methods are used, we get an error `Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections`.

I tried working around this by applying the `RequestAuthentication` and `AuthorizationPolicy` to a `Gateway` using a configuration like the one below. I do not want to apply the `RequestAuthentication` to the entire ingress gateway to avoid the problem I described above. This did not appear to work but the docs make it look like it should. Is this not a supported scenario?

Istio Version: 1.22 - Sidecar mode via AKS addon

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
spec:
  selector:
    istio: aks-istio-ingressgateway-internal
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-service
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
  - route:
    - destination:
        host: test-host
        port:
          number: 3000
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: test-request-auth
spec:
  targetRefs:
  - name: test-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  jwtRules:
  - issuer: "https://[REDACTED].us.auth0.com/"
    jwksUri: "https://[REDACTED].us.auth0.com/.well-known/jwks.json"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: test-ingress-auth
spec:
  targetRefs:
  - name: test-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  action: ALLOW
  rules:
  - to:
    - operation:
        paths: ["/"]
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        paths: ["/weatherforecast"]
```

**Comment by ilrudie** [comment]
Your Gateway is `networking.istio.io` (Istio API) so it would not use Kubernetes Gateway API style binding with TargetRef (for Gateway.gateway.networking.k8s.io). The section on targetRef in the configuration reference explains it in a bit more detail [here](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy).

**Comment by keithmattix** [comment]
Your gateway that you posted isn't a gateway api gateway but rather an istio gateway. I don't see how the RA resource would even be applying to the ingress gateway

**Comment by scorgatelli** [comment]
Thanks. I completely missed that. I did switch to using the gateway-api but it's still not working for me. I'm wondering if it has something to do with running under the AKS Istio add-on.

**Comment by keithmattix** [comment]
If you're using the managed gateways in the AKS addon, then you'll need to do something like this to use Gateway API - https://azure.github.io/AKS/2024/08/06/istio-with-gateway-api.

**Comment by scorgatelli** [comment]
I did set things up like in that article and the gateway-api and routing work. However, any `RequestAuthentication` or `AuthorizationPolicy` applied to the gateway using `targetRefs` do not appear to work (all requests are allowed, and it doesn't appear to be validating JWTs).

**Comment by keithmattix** [comment]
Can you post the relevant resources here now that you've set up Gateway api correctly (including HTTPRoutes)?

**Comment by scorgatelli** [comment]
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: aks-istio-ingress
spec:
  gatewayClassName: istio
  addresses:
  - value: aks-istio-ingressgateway-internal
    type: Hostname
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-host
  namespace: app
spec:
  parentRefs:
  - name: ingress-gateway
    namespace: aks-istio-ingress
  rules:
  - backendRefs:
    - name: test-host
      port: 3000
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: auth0-authn
  namespace: aks-istio-ingress
spec:
  targetRefs:
  - name: ingress-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  jwtRules:
  - issuer: "https://[REDACTED].us.auth0.com/"
    jwksUri: "https://[REDACTED].us.auth0.com/.well-known/jwks.json"
    outputPayloadToHeader: "x-auth-istio-validated-token"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ingress-gateway-authz
  namespace: aks-istio-ingress
spec:
  targetRefs:
  - name: ingress-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        paths: ["/weatherforecast"]
```
