### ISSUE TITLE
Gateway annotation "networking.istio.io/service-type" does not work

### ISSUE THREAD

**Issue by serhii-ciq** [istio/istio#53802]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello all,
I have tried to override the Service type for the resource Gateway using the annotation
`networking.istio.io/service-type: ClusterIP`. 
Codebase
https://github.com/istio/istio/blob/44a38b2c3e660bb4ec0835d4c8ee7d98ed5e8211/pilot/pkg/config/kube/gateway/deploymentcontroller.go#L350

The resource I have deployed into k8s:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-dev
  namespace: istio-system
  annotations:
    networking.istio.io/service-type: ClusterIP
```

**The issue is:** pilot omits this annotation and creates the Service with default type (LoadBalancer)

### Version

```Text
istioctl version:
client version: 1.23.3
control plane version: 1.23.3
data plane version: 1.23.3 (2 proxies)

kubectl version:
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.30.4-eks-a737599
WARNING: version difference between client (1.27) and server (1.30) exceeds the supported minor version skew of +/-1
```
