### ISSUE TITLE
Envoyfilter with workload selector cause all listeners got modified

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#53800]
When we apply a envoyfilter to replace the listener_filters_timeout of a specific listener `virtualInbound`.

But after sometime, we see all the listeners listener_filters_timeout  are modified, and this happens to all sidecars as well.

```
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    generation: 1
    name: test
    namespace: default
  spec:
    configPatches:
    - applyTo: LISTENER
      match:
        context: ANY
        listener:
          name: virtualInbound
      patch:
        operation: MERGE
        value:
          listener_filters_timeout: 0.01s
    workloadSelector:
      labels:
        app: httpbin
```

I suspect the proro merge will modify the global `Mesh.ProtocolDetectionTimeout`, which is `ProtocolDetectionTimeout *duration.Duration`
