### ISSUE TITLE
Unable to change the max_response_headers_kb using EnvoyFilter

### ISSUE THREAD

**Issue by SabySen** [istio/istio#53812]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Trying to increase the Max header size of the response being sent back from the application, otherwise istio gives 503 because headers sizeif more than 64KB. This is as per the document in envoy https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto

trying to update the "max_response_headers_kb" but keep getting this error.

```
Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: unknown field "max_response_headers_kb" in envoy.config.core.v3.Http1ProtocolOptions
```

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
 name: http-header-count-size-control
 annotations: {}
 labels:
  install.operator.istio.io/owning-resource: istio-operator
  install.operator.istio.io/owning-resource-namespace: istio-system
  operator.istio.io/managed: Reconcile
 namespace: istio-system
spec:
 workloadSelector:
  labels:
   app: my-app
 configPatches:
   - applyTo: CLUSTER
     match:
      cluster:
      context: SIDECAR_OUTBOUND
     patch:
      operation: MERGE
      value:
        "@type": type.googleapis.com/envoy.config.core.v2.HttpProtocolOptions
        common_http_protocol_options:
               max_response_headers_kb: 200
`

### Version

```Text
./istioctl version
client version: 1.23.3
control plane version: 1.21.5
data plane version: 1.21.5 (64 proxies)

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5-gke.1014001
```

**Comment by hzxuzhonghu** [comment]
This envoyfilter is not indented well, and you donot need to set `"@type": type.googleapis.com/envoy.config.core.v2.HttpProtocolOptions`

**Comment by SabySen** [comment]
Hi Zhonghu Xu
So sorry submitted the issue and realized the formatting was screwed up. Here is the updated on
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
 name: http-header-count-size-control
 annotations: {}
 labels:
  install.operator.istio.io/owning-resource: istio-operator
  install.operator.istio.io/owning-resource-namespace: istio-system
  operator.istio.io/managed: Reconcile
 namespace: istio-system
spec:
 workloadSelector:
  labels:
   app: my-app
 configPatches:
   - applyTo: CLUSTER
     match:
      cluster:
      context: SIDECAR_OUTBOUND
     patch:
      operation: MERGE
      value:
        "@type": type.googleapis.com/envoy.config.core.v2.HttpProtocolOptions
        common_http_protocol_options:
               max_response_headers_kb: 200

```
