### ISSUE TITLE
Can not use filter with accessLogging

### ISSUE THREAD

**Issue by serhii-ciq** [istio/istio#53816]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Trying to apply the Telemetry. But get the error:
```
The telemetries "mesh-default" is invalid: : ValidatingAdmissionPolicy 'stable-channel-default-policy.istio.io' with binding 'stable-channel-default-policy-binding.istio.io' denied request: failed expression: !(
  variables.isTelemetry && (
    (has(object.spec.tracing) ? object.spec.tracing : {}).exists(t, has(t.useRequestIdForTraceSampling)) ||
    (has(object.spec.metrics) ? object.spec.metrics : {}).exists(m, has(m.reportingInterval)) ||
    (has(object.spec.accessLogging) ? object.spec.accessLogging : {}).exists(l, has(l.filter))
  )
```

Telemetry config:
```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: "response.code >= 400"
```        

### Version

```Text
istioctl version:
client version: 1.23.3
control plane version: 1.23.3
data plane version: 1.23.3 (2 proxies)

kubectl version:
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.30.4-eks-a737599
WARNING: version difference between client (1.27) and server (1.30) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
