### ISSUE TITLE
Istio-proxy connection drops during Istio version upgrades/downgrades

### ISSUE THREAD

**Issue by Jpatel86** [istio/istio#53827]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are experiencing significant connection drops in istio-proxy when upgrading or downgrading between major Istio versions. This issue was first encountered during an upgrade from 1.21 to 1.22, and we are currently observing similar behavior while testing upgrades and downgrades between 1.22 and 1.23.

Interestingly, we have not observed connection drops when upgrading between minor versions within the same major release (e.g., 1.22.2 to 1.22.6 or 1.23.1 to 1.23.3). However, downgrading from 1.23 to 1.22 consistently triggers the issue.

After enabling debug logs, we observed that istio-proxy drains all its listeners during these problematic upgrades/downgrades.

Please find attached the relevant metrics graphs illustrating the connection drops.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/e21b217f-96a2-488d-807d-05296ce8bafc">
<img width="748" alt="image" src="https://github.com/user-attachments/assets/c07bd47b-f092-4a62-abcd-1c24f500fc25">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/10f45a01-7ece-4ff5-b0b6-adf3842e27b9">
<img width="747" alt="image" src="https://github.com/user-attachments/assets/e82a2b78-c3bb-4fc3-b84d-b4daef6ba28f">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/6de24003-4381-4c08-8d51-a19813f2833c">

We are experiencing significant connection drops particularly for websocket services.

```bash
{"time":"2024-11-07T22:55:12.383604Z","level":"debug","scope":"envoy connection","msg":"current connecting state: true","caller":"external/envoy/source/common/network/connection_impl.h:98","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:55:12.383611Z","level":"debug","scope":"envoy connection","msg":"connecting to 172.17.43.59:8000","caller":"external/envoy/source/common/network/connection_impl.cc:1017","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:55:12.383704Z","level":"debug","scope":"envoy connection","msg":"connection in progress","caller":"external/envoy/source/common/network/connection_impl.cc:1036","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:55:12.383923Z","level":"debug","scope":"envoy connection","msg":"connected","caller":"external/envoy/source/common/network/connection_impl.cc:746","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:55:12.383936Z","level":"debug","scope":"envoy pool","msg":"attaching to next stream","caller":"external/envoy/source/common/conn_pool/conn_pool_base.cc:328","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:55:12.383940Z","level":"debug","scope":"envoy pool","msg":"creating stream","caller":"external/envoy/source/common/conn_pool/conn_pool_base.cc:182","thread":"140","ConnectionId":"884319"}

{"time":"2024-11-07T22:57:22.111256Z","level":"debug","scope":"envoy pool","msg":"draining busy client 884319 for cluster outbound|80||websockets.xxx.svc.cluster.local","caller":"external/envoy/source/common/conn_pool/conn_pool_base.cc:441","thread":"140"}

{"time":"2024-11-07T22:57:22.115820Z","level":"debug","scope":"envoy connection","msg":"remote close","caller":"external/envoy/source/common/network/connection_impl.cc:714","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:57:22.115829Z","level":"debug","scope":"envoy connection","msg":"closing socket: 0","caller":"external/envoy/source/common/network/connection_impl.cc:276","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:57:22.116187Z","level":"debug","scope":"envoy pool","msg":"client disconnected, failure reason: ","caller":"external/envoy/source/common/conn_pool/conn_pool_base.cc:495","thread":"140","ConnectionId":"884319"}
{"time":"2024-11-07T22:57:22.130772Z","level":"debug","scope":"envoy pool","msg":"destroying stream: 0 remaining","caller":"external/envoy/source/common/conn_pool/conn_pool_base.cc:215","thread":"140","ConnectionId":"884319"}
```

**Suspected EnvoyFilter Configuration**
We have the following EnvoyFilters in our Istio-system namespace, which we suspect might be contributing to the connection drops, although we are not certain:

```yaml
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  spec:
    configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            tracing:
              client_sampling:
                value: x
              overall_sampling:
                value: x
              random_sampling:
                value: x
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  spec:
    configPatches:
    - applyTo: ROUTE_CONFIGURATION
      match:
        context: ANY
      patch:
        operation: MERGE
        value:
          response_headers_to_remove:
          - x-envoy-foo
## We have not migrated to Telemtry API yet(beacasue of disable_host_header_fallback support), so we are still using EnvoyFilter based istio stats
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  spec:
    configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND # similar applied to SIDECAR_OUTBOUND GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.stats
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/stats.PluginConfig
            value:
              disable_host_header_fallback: true
              metrics:
              - dimensions:
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  spec:
    configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND # similar applied to SIDECAR_OUTBOUND GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.stats
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/stats.PluginConfig
            value:
              disable_host_header_fallback: true
              metrics:
              - dimensions:
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  spec:
    configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            strip_trailing_host_dot: true
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  spec:
    configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            max_request_headers_kb: xxx
          
```

### Version

```Text
❯ istioctl version
client version: 1.22.2
control plane version: 1.22.4
data plane version: 1.22.4 (2353 proxies)

❯ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6
```

**Comment by hzxuzhonghu** [comment]
Didn't you upgrade dataplane? 

You can dump the listener configuration geenrated by both 1.23 and 1.22 and  then compare, should find out what diff they have

**Comment by Jpatel86** [comment]
Hi @hzxuzhonghu, thanks for responding.

To clarify, we are only updating the istiod deployment and not making any changes to the data plane. The only change in the control plane configuration during the 1.22 to 1.23 upgrade was the removal of the enableProtocolSniffingForOutbound field from the mesh config - https://github.com/istio/istio/pull/51989.

We observed some differences in the istio-proxy listeners after upgrading to 1.23. but we couldn't identify a definitive cause for the connection drops. 

1.  `The InitialReadBufferSize: 512` attribute was added to the envoy.filters.listener.tls_inspector listener filter.
2. The `proxy100Continue: true` attribute was added to the envoy.filters.http.router listener filter.
3. A filterChainMatch block, which included a `prefixRanges` definition, was removed.

Here are the relevant snippets from the listener configurations:

**Added:**
```yaml
listenerFilters:
- name: envoy.filters.listener.tls_inspector
  typedConfig:
    '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    initialReadBufferSize: 512
 ```
 ```yaml
 - name: envoy.filters.http.router
  typedConfig:
    '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
maxRequestHeadersKb: 320
normalizePath: true
pathWithEscapedSlashesAction: KEEP_UNCHANGED
proxy100Continue: true
```

**Removed**
```yaml
- filterChainMatch:
    prefixRanges:
    - addressPrefix: 0.0.0.0
      prefixLen: 0
```
