### ISSUE TITLE
Ambient status should report about `istio.io/ingress-use-waypoint`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53845]
```

status:
  conditions:
  - lastTransitionTime: "2024-11-09T10:46:36Z"
    message: Successfully attached to waypoint podinfo/waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
  loadBalancer: {}
```

is what we have today.

We can say "Successfully attached to waypoint podinfo/waypoint. Ingress traffic will traverse the waypoint" on success, and give a message on error (error is if it cannot be parsed as a bool?)
