### ISSUE TITLE
istio install Multi-Primary and DNS Proxying, but dns and service discovery not work when I add a rust wasm envoy-filter 

### ISSUE THREAD

**Issue by 90wukai** [istio/istio#53866]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm install istio Multiple primary clusters on the same network and DNS Proxying. Verify the installation is ok.
But, dns and service discovery not work when I add a rust wasm envoy-filter, the filter just do something for http calls, why dns is not working?

### Version

```Text
istioctl version

client version: 1.24.0
control plane version: 1.22.3
data plane version: 1.22.3 (44 proxies)

kubectl version 

Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.26.1
WARNING: version difference between client (1.31) and server (1.26) exceeds the supported minor version skew of +/-1
```

**Comment by 90wukai** [comment]
Sidecar restriction 
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  egress:
  - hosts:
    - "./*"
```
