### ISSUE TITLE
1.24.0 istioctl install fails with "all goroutines are asleep - deadlock"

### ISSUE THREAD

**Issue by Shohou** [istio/istio#53878]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to upgrade to istio 1.24.0 and getting deadlock error during istioctl install command execution. Running the same command on 1.23.3 works fine.
```
$ ~/istio-1.24.0/bin/istioctl install -f istio.yaml -y
        |\
        | \
        |  \
        |   \
      /||    \
     / ||     \
    /  ||      \
   /   ||       \
  /    ||        \
 /     ||         \
/______||__________\
____________________
  \__       _____/
     \_____/

WARNING: Istio is being upgraded from 1.23.3 to 1.24.0.
         Running this command will overwrite it; use revisions to upgrade alongside the existing version.
         Before upgrading, you may wish to use 'istioctl x precheck' to check for upgrade warnings.
✔ Istio core installed ⛵️

✔ Istiod installed 🧠
✔ CNI installed 🪢
✔ Egress gateways installed 🛫
✔ Ingress gateways installed 🛬
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc0003d7848?)
        runtime/sema.go:71 +0x25
sync.(*WaitGroup).Wait(0xc0003d78b0?)
        sync/waitgroup.go:118 +0x48
istio.io/istio/operator/pkg/install.Installer.install({0x0, 0x0, 0x0, {0x3cb86d0, 0xc000a8ea20}, 0xc000cad110, 0x45d964b800, {0x3c7bd78, 0xc000bcc210}, 0xc00189e0c0}, ...)
        istio.io/istio/operator/pkg/install/install.go:151 +0x6de
istio.io/istio/operator/pkg/install.Installer.InstallManifests({0x0, 0x0, 0x0, {0x3cb86d0, 0xc000a8ea20}, 0xc000cad110, 0x45d964b800, {0x3c7bd78, 0xc000bcc210}, 0xc00189e0c0}, ...)
        istio.io/istio/operator/pkg/install/install.go:77 +0x1cb
istio.io/istio/operator/cmd/mesh.Install({0x3cb86d0, 0xc000a8ea20}, 0xc000296ba4, 0xc000a13260, {0x3c21740, 0xc0000c0060}, {0x3c7bd78, 0xc000bcc210}, {0x3c4e688, 0xc000ad86a0})
        istio.io/istio/operator/cmd/mesh/install.go:192 +0x733
istio.io/istio/operator/cmd/mesh.InstallCmdWithArgs.func2(0xc00082cf08, {0xc0008278c0?, 0x4?, 0x365057b?})
        istio.io/istio/operator/cmd/mesh/install.go:127 +0x1f1
github.com/spf13/cobra.(*Command).execute(0xc00082cf08, {0xc000827860, 0x3, 0x3})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007e5508)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000720b0?)
        github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.main()
        istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xd9

goroutine 56 [chan receive, 2 minutes]:
istio.io/istio/operator/pkg/install.Installer.install.func2()
        istio.io/istio/operator/pkg/install/install.go:126 +0xd9
created by istio.io/istio/operator/pkg/install.Installer.install in goroutine 1
        istio.io/istio/operator/pkg/install/install.go:122 +0x3e5

goroutine 28 [chan receive, 2 minutes]:
istio.io/istio/pilot/pkg/config/aggregate.(*storeCache).Run(0xc0016f0000?, 0xc001bcdc00)
        istio.io/istio/pilot/pkg/config/aggregate/config.go:202 +0xc5
created by istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).Init in goroutine 1
        istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:240 +0x625
```

### Version

```Text
$ ~/istio-1.24.0/bin/istioctl version
client version: 1.24.0
control plane version: 1.24.0
data plane version: 1.21.0 (5 proxies), 1.23.1 (21 proxies), 1.23.3 (2 proxies), 1.24.0 (6 proxies)

$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4-eks-a737599

not using helm
```

**Comment by shree1999** [comment]
Same for me.. @Shohou have you found any workaround?

**Comment by ilrudie** [comment]
https://github.com/istio/istio/pull/53880 fixes this. Should be in 1.24.1 when that is out.

**Comment by Shohou** [comment]
> Same for me.. @Shohou have you found any workaround?

@shree1999 does staying on 1.23.3 counts as a workaround? It's ok for me, I'll just wait for 1.24.1

**Comment by ilrudie** [comment]
If either of you would be able to post your IOP file I can go ahead and double check it against my code to make sure it doesn't deadlock with my fix.

**Comment by Shohou** [comment]
@ilrudie  IOP is the file used in installation command, right?
here it is
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  #Based on default.yaml, add only changes
  profile: default

  meshConfig:
    enableTracing: true
    accessLogFile: "/dev/stdout"
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 100.0
        zipkin:
          address: jaeger-aio-collector.jaeger.svc.cluster.local:9411
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
      istio-egressgateway:
        autoscaleEnabled: false
    pilot:
      autoscaleEnabled: false
      env:
        ENABLE_NATIVE_SIDECARS: true
  components:
    # Istio CNI feature
    cni:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 384Mi
          limits:
            cpu: "1"
            memory: 384Mi

    pilot:
      k8s:
        replicaCount: 2
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            cpu: '2'
            memory: 512Mi

    # Istio Gateway feature
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          service:
            externalTrafficPolicy: Local
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
            service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxx
            service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-xxx
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 256Mi
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: kind
                  value: DaemonSet
                # can leave value unset to delete the node
                # ref: https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#K8sObjectOverlay-PathValue
                - path: spec.strategy
                  value:
                  # this is the default value for ds.spec.updateStrategy.rollingUpdate
                - path: spec.updateStrategy
                  value:
                    rollingUpdate:
                      maxUnavailable: 1
      - name: istio-ingressgateway-internal
        label:
          istio: istio-ingressgateway-internal
        enabled: true
        k8s:
          replicaCount: 2
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxx
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 256Mi
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          replicaCount: 2
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: '2'
              memory: 256Mi
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
              - port: 5432
                targetPort: 5432
                name: postgresql
                protocol: TCP
```
