### ISSUE TITLE
PeerAuthentication with port specification not overriding global default in ambient mode

### ISSUE THREAD

**Issue by stephen-tatari** [istio/istio#53884]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have OpenTelemetry Operator running in sidecar mode with the following Peer Authentication set:

```
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  labels:
    argocd.argoproj.io/instance: apps-opentelemetry-operator
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  portLevelMtls:
    '9443':
      mode: PERMISSIVE
  selector:
    matchLabels:
      control-plane: controller-manager
```
this allows workloads to hit its webhook without certificate errors.

If I switch the `opentelemetry-operator-system` namespace to ambient mode, I get errors like this:

```
ztunnel-c2kv8 istio-proxy 2024-11-13T17:36:10.380963Z   error   access  connection complete     src.addr=10.0.0.240:49872 dst.addr=10.0.21.243:9443 dst.service="opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc.cluster.local" dst.workload="opentelemetry-operator-controller-manager-89f9575cd-q2nsp" dst.namespace="opentelemetry-operator-system" direction="inbound" bytes_sent=0 bytes_recv=0 duration="0ms" error="connection closed due to policy rejection: explicitly denied by: istio-system/istio_converted_static_strict"
```

and I have to modify the PeerAuthentication to the following to get it to work again:

```
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  labels:
    argocd.argoproj.io/instance: apps-opentelemetry-operator
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      control-plane: controller-manager
```

I don't recall seeing this error in Istio 1.23 with ambient mode enabled.

### Version

```Text
❯ istioctl version
client version: 1.24.0
control plane version: 1.24.0
data plane version: 1.24.0 (13 proxies)
❯ kubectl version
Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4-eks-a737599
```

### Additional Information

[bug-report.tar.gz](https://github.com/user-attachments/files/17737020/bug-report.tar.gz)
