### ISSUE TITLE
AuthorizationPolicy is not applied to MESH_EXTERNAL ServiceEntry. No Egress ingress enabled.

### ISSUE THREAD

**Issue by domedellolio** [istio/istio#53904]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**Context**: 

We're running on Azure Kubernetes Service, with the Istio add-on enabled. No egress.
My customer would like to expose an external API (on prem legacy / not-containerized) via the mesh in order to leverage security / traffic management capability.

**Issue**:
AuthorizationPolicy is not applied to a ServiceEntry MESH_EXTERNAL.

Based on the documentation I would expect policy evaluation to be client side.

<img width="703" alt="image" src="https://github.com/user-attachments/assets/c7a72750-6790-4558-a4bf-535f939fd346">

Here the policies we've applied.

```yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: block-sidecar-outbound
  namespace: aks-istio-system
spec:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY`

```

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test-service-entry
  namespace: aks-istio-system
spec:
  hosts:
  - abc.externalservice.com
  location: MESH_EXTERNAL
  ports:
  - name: http-onprem
    number: 443
    protocol: TLS
  resolution: DNS

```

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-abc-externalservice
  namespace: ns3 # Applies the policy only to workloads in the "ns3" namespace
spec:
  action: DENY
  rules:
  - from:
    - source:
        namespaces:
        - ns3 # Requests originating from workloads in this namespace
    to:
    - operation:
        hosts:
        - "abc.externalservice.com"

```

**Environment (please complete the following information):**
 - Kubernetes version 1.29
 - Istio add-on 1.23
