### ISSUE TITLE
Enhance Integration Test

### ISSUE THREAD

**Issue by fjglira** [istio/istio#53990]
Hi, while reviewing the integration test framework, I identified some improvements that could enhance its flexibility and support testing with the [sail-operator](https://github.com/istio-ecosystem/sail-operator). Currently, the integration tests use the IstioOperator API to configure the control plane. Based on this, here are the proposed changes:

- [ ] Avoid hardcoding IstioOperator setting on test setups. Example:

Currently, the framework does [this](https://github.com/istio/istio/blob/809657ab107cfc7e4c27351e85ac2c1f1c5fb021/tests/integration/pilot/analysis/main_test.go#L34C1-L35C1):
```
Setup(istio.Setup(nil, func(_ resource.Context, cfg *istio.Config) {
			cfg.ControlPlaneValues = `
values:
  pilot:
    env:
      PILOT_ENABLE_STATUS: true
  global:
    istiod:
      enableAnalysis: true
`
```

Instead of hardcoding values as strings for populating the IstioOperator API values, use a struct with existing types to provide flexibility. This approach will enable the framework to support future enhancements more effectively.

- [ ] Enable Helm-based setup for the testing framework. Adding the possibility of installing the control plane using Helm will improve testing coverage.

- [x] Enable integration tests against a control plane installed by the Sail operator, this means, updating the framework to support running tests against an externally installed control plane. Currently, skipping control plane deployment works only for shared setups; new setups can't be managed within the same job. Additionally, translating IstioOperator values to Istio values in Sail is complex. Improving this will enhance test coverage for Sail and extend the framework to other projects.

cc @howardjohn
