### ISSUE TITLE
Policy binding to GatewayClass

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#53991]
[This slack discussion](https://istio.slack.com/archives/C041EQL1XMY/p1732046155332809) brings up a very good point.

The long and the short of it is that the layered architecture makes ambient `default-deny` pattern difficult to implement once waypoints are introduced. The waypoint proxies traffic using its own identity which means ztunnel allows all traffic from the waypoint (or none but why would you want to block your own waypoint?). Once introduced the waypoint becomes the ideal PEP for most policies however ambient doesn't presently implement a great way to attach a policy to all waypoints (which is fairly critical for the default-deny posture).

[Ambient Working Group](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit?tab=t.0#bookmark=id.c9otet6wwuxb) discussion landed on implementing attachment to GatewayClass among a few other options. Please refer to the community notes for details.

## Rough Implementation steps.
- [ ] Validate binding to a GatewayClass is conformant with Gateway API
- [ ] CEL updates (istio/api)
- [ ] Controller Updates (istio/istio)

**Comment by ilrudie** [comment]
Gunna self assign. If you feel strongly about this impl please lmk and we'll figure it out.

**Comment by keithmattix** [comment]
Might need to check with the gateway api community about policies binding to gatewayclass, but I'm pretty sure the GEP allows it last time I checked

**Comment by ilrudie** [comment]
Ah, that's a good point @keithmattix. I'll update the steps to include

**Comment by ca-scribner** [comment]
Thinking purely as a user (and ignoring any implementation complexity or consistency with gateway api), it feels intuitive that I could define an AuthorizationPolicy that applies many Gateway (or Service) objects as defined by a pattern.  So something like:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: example-allow-nothing-for-all-waypoints
spec:
  targetRefs:
  - name: *
    kind: Gateway
    group: gateway.networking.k8s.io
```

or

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: example-allow-nothing-for-all-waypoints
spec:
  targetRefs:
  - name: *
    kind: Service
```

Then Istio's typical namespacing logic could still apply (create this in istio's root namespace and its global, create it in a specific namespace and its namespaced)
