### ISSUE TITLE
envoyfilter tests are failing on remove metrics (istio_requests_total)

### ISSUE THREAD

**Issue by benyahman** [istio/istio#54006]
I tried using the following EnvoyFilter to filter the metrics ('istio_requests_total') in the sidecar, but I still see values being collected from http://localhost:9090/api/v1/query?query=istio_requests_total. Is there an issue with the EnvoyFilter configuration?"

Version
```
$ istioctl version
client version: 1.13.5
control plane version: 1.13.5
```
envoyfilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-istio-requests-total
  namespace: sample
spec:
  workloadSelector:
    labels:
      app: helloworld
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.stats
      patch:
        operation: MERGE
        value:
          name: envoy.filters.http.stats
          config:
            stats_matcher:
              exclusion_list:
                patterns:
                  - exact: "istio_requests_total"

    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.stats
      patch:
        operation: MERGE
        value:
          name: envoy.filters.http.stats
          config:
            stats_matcher:
              exclusion_list:
                patterns:
                  - exact: "istio_requests_total"


```

**Comment by benyahman** [comment]
These configurations might be a result of trial and error during testing. I would like to there are better examples for filtering metrics using EnvoyFilter.

**Comment by zirain** [comment]
Telemetry would be simpler:
```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: remove-request-count
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - disabled: true
          match:
            mode: CLIENT_AND_SERVER
            metric: REQUEST_COUNT
```
