### ISSUE TITLE
Add arbitrary label to x-envoy-peer-metadata

### ISSUE THREAD

**Issue by RicHincapie** [istio/istio#54000]
**Describe the feature request**
Currently, `x-envoy-peer-metadata` cannot be tweaked to include an arbitrary label present in the sidecar `node.metadata.LABELS` section. I'd like to be able to insert arbitrary labels I can later use as a metric dimension to correlate origin and destination. This would need to be done using telemetry in this way:
```
    - overrides:
        - match:
            metric: ALL_METRICS
            mode: CLIENT
          tagOverrides:
            custom-upstream-metadata:
              value: upstream_peer.labels['foo'].value
``` 
It'd be very useful in custom observability requirements as once passed on to, say, Prometheus, it can leverage new ways of understanding traffic:

![Screenshot from 2024-11-21 11-12-04](https://github.com/user-attachments/assets/d3cc005f-e141-496c-980a-1d5a161517fe)

**Describe alternatives you've considered**

* Tried prepending custom label with `service.istio.io/` as the filter picks up `service.istio.io/canonical-name` and `service.istio.io/canonical-revision`
* Tried accessing `filter_state["wasm.upstream_peer"]`
 
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
proposal: https://docs.google.com/document/d/1NPl9TyBadejvcOfsTO6rWz9quru4zU6WQmAzQX6iphI

cc @kyessenov @lei-tang @howardjohn

**Comment by keithmattix** [comment]
Let's discuss this in the next combined WG meeting

**Comment by lei-tang** [comment]
@zirain Can you grant the commenting permission of your proposal https://docs.google.com/document/d/1NPl9TyBadejvcOfsTO6rWz9quru4zU6WQmAzQX6iphI to Istio WG?

**Comment by zirain** [comment]
> @zirain Can you grant the commenting permission of your proposal https://docs.google.com/document/d/1NPl9TyBadejvcOfsTO6rWz9quru4zU6WQmAzQX6iphI to Istio WG?

Sorry, allow anyone to comment now.

**Comment by hebestreit** [comment]
Hi,

I'm trying to add custom labels for all Istio metrics using below Telemetry configuration. Currently I'm stuck how to reference the labels from the client proxy which in my case is the Istio ingress gateway.


As you can see `source_k8s_app_name` and `source_k8s_app_component` (correct, because not available) is set to "unknown".

```
curl <istio_gw_ip>:15020/stats/prometheus
```

`
istio_response_bytes_count{reporter="source",source_workload="istio-gw-priv-ingress-1-26-6",source_workload_namespace="istio-system",source_app="istio-gw-priv-ingress-1-26-6",source_cluster="Kubernetes",destination_workload="trino-coordinator",destination_workload_namespace="trino",destination_app="unknown",destination_service="trino.trino.svc.cluster.local",destination_service_name="trino",destination_service_namespace="trino",destination_cluster="Kubernetes",destination_k8s_app_component="coordinator",destination_k8s_app_name="trino",source_k8s_app_component="unknown",source_k8s_app_name="unknown"} 0
`

Snippet from my istiod Helm values.yaml:
```yaml
env:
  PILOT_MX_ADDITIONAL_LABELS: "app.kubernetes.io/name,app.kubernetes.io/component"

meshConfig:
  defaultConfig:
    extraStatTags:
      - source_k8s_app_name
      - source_k8s_app_component
      - destination_k8s_app_name
      - destination_k8s_app_component
```


```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: ALL_METRICS
            mode: CLIENT
          tagOverrides:
            source_k8s_app_name:
              operation: UPSERT
              value: "labels['app.kubernetes.io/name']" # How to reference?
            source_k8s_app_component:
              operation: UPSERT
              value: "labels['app.kubernetes.io/component']" # How to reference?
            destination_k8s_app_name:
              operation: UPSERT
              value: "filter_state.upstream_peer.labels['app.kubernetes.io/name']"
            destination_k8s_app_component:
              operation: UPSERT
              value: "filter_state.upstream_peer.labels['app.kubernetes.io/component']"
```


```yaml
apiVersion: apps/v1                                                                                                                                                                                                                                                                                                                                                                           
kind: Deployment                                                                                                                                                                                                                                                                                                                                                                              
metadata:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  labels:                                                                                                                                                                                                                                                                                                                                                                                     
    app: istio-gw-priv-ingress-1-26-6                                                                                                                                                                                                                                                                                                                                                         
    app.kubernetes.io/instance: istio-gw-priv-ingress-1-26-6                                                                                                                                                                                                                                                                                                                                  
    app.kubernetes.io/managed-by: Helm                                                                                                                                                                                                                                                                                                                                                        
    app.kubernetes.io/name: istio-gw-priv-ingress-1-26-6                                                                                                                                                                                                                                                                                                                                      
    app.kubernetes.io/part-of: istio                                                                                                                                                                                                                                                                                                                                                          
    app.kubernetes.io/version: 1.26.6                                                                                                                                                                                                                                                                                                                                                         
    helm.sh/chart: gateway-1.26.6                                                                                                                                                                                                                                                                                                                                                             
    istio: gw-priv-ingress                                                                                                                                                                                                                                                                                                                                                                    
    istio.io/dataplane-mode: none                                                                                                                                                                                                                                                                                                                                                             
  name: istio-gw-priv-ingress-1-26-6                                                                                                                                                                                                                                                                                                                                                          
  namespace: istio-system                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
spec:          
...
```

**Comment by zirain** [comment]
FYI: it's pod label, not the deployment.

BTW, I do believe we didn't need `defaultConfig.extraStatTags` any more.

**Comment by hebestreit** [comment]
> BTW, I do believe we didn't need defaultConfig.extraStatTags any more.

Yes, you're right. 


> FYI: it's pod label, not the deployment.

Thanks for the clarification. I got confused by this comment in a test file when I was trying to understand the details:

https://github.com/zirain/istio/blob/master/pkg/test/framework/components/echo/config.go#L239-L240

---

As you can see below the label is set for the Pod but it's not clear to me how to access the metadata of the client itself.

> Peer metadata is available as attributes upstream_peer for outbound and downstream_peer for inbound with the following fields:
>...
> For example, the expression for the peer app label to be used in an outbound configuration is filter_state.downstream_peer.app or filter_state.upstream_peer.app.
> https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/


```yaml
source_k8s_app_name:
  operation: UPSERT
  value: "labels['app.kubernetes.io/name']" #  Should it work like this?
```

```yaml
apiVersion: v1           
kind: Pod                                                                                                                                                                                                                
metadata:                                                                                                                             
  labels:                                                                                                                                                                                                                    
    app: istio-gw-priv-ingress-1-26-6                                                                                                                                                                                        
    app.kubernetes.io/instance: istio-gw-priv-ingress-1-26-6                                                                                                                                                                 
    app.kubernetes.io/managed-by: Helm                                                                                                                                                                                       
    app.kubernetes.io/name: istio-gw-priv-ingress-1-26-6                                                                                                                                                                     
    app.kubernetes.io/part-of: istio                                                                                                                                                                                         
    app.kubernetes.io/version: 1.26.6                                                                                                                                                                                        
    helm.sh/chart: gateway-1.26.6                                                                                                                                                                                            
    istio: gw-priv-ingress                                                                                                                                                                                                   
    istio.io/dataplane-mode: none                                                                                                                                                                                            
    istio.io/rev: 1-26-6                                                                                                                                                                                                     
    pod-template-hash: 7945ccf849                                                                                                                                                                                            
    service.istio.io/canonical-name: istio-gw-priv-ingress-1-26-6                                                                                                                                                            
    service.istio.io/canonical-revision: 1.26.6                                                                                                                                                                              
    sidecar.istio.io/inject: "true"                                                                                                                                                                                          
  name: istio-gw-priv-ingress-1-26-6-7945ccf849-d84p5                                                                                                                                                                        
  namespace: istio-system                                                                                                                                                                                                                                                                                                                                                                                 
spec:     
...
```
Secondly do you know by any chance if it's also possible to concat two labels into one tag?

```yaml
destination_k8s_service_name:
  operation: UPSERT
  value: "filter_state.upstream_peer.labels['app.kubernetes.io/name'] + '-' + filter_state.upstream_peer.labels['app.kubernetes.io/component']"
```

Thank you in advance!
