### ISSUE TITLE
istio-proxy does not respect ProxyConfig terminationDrainDuration

### ISSUE THREAD

**Issue by ale-xepelin** [istio/istio#54012]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi all, Istio proxy is ignoring the terminationDrainDuration. I am using istio 1.23.3.
```
meshConfig:
  enablePrometheusMerge: true
  holdApplicationUntilProxyStarts: true
  accessLogEncoding: json
  defaultConfig:
    terminationDrainDuration: 30s
```
Here the output:
```
 kubectl exec hello-world-7799bb459d-7lx9w -c istio-proxy -n hello-world -- pilot-agent request GET config_dump | grep -i terminationDrainDuration
       "terminationDrainDuration": "5s",
```
I restarted istiod and the application too. But the problem persists.
Any tips ?

### Version

```Text
control plane version: 1.23.3
data plane version: 1.23.3 (223 proxies)
```
