### ISSUE TITLE
EnvoyFilter LocalRateLimit multiplie entries in a descriptor are not working

### ISSUE THREAD

**Issue by IgorIgnatevSky** [istio/istio#54024]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,
I'm trying to configure the local rate limit with multiple conditions for the bucket, but all requests are passed without any limitation, while limits work when conditions are separate. I want to combine the conditions for path (eq /header) and header value (api-key). Also, do you have any suggestions on dynamically creating a bucket per header value (I tried * and %req(api-key)% but no results)?

<details>
  <summary>Envoy Filters</summary>

  ### multiplie entries in a descriptors bucket (not working)
  ```
  apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: httpbin
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8000"
            route:
              action: ROUTE
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          route:
            rate_limits:
              - actions:
                  - request_headers:
                      header_name: api-key
                      descriptor_key: api_key
              - actions:
                  - request_headers:
                      header_name: ":path"
                      descriptor_key: path
              - actions:
                  - header_value_match:
                      descriptor_value: "header_path"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /headers
                            ignore_case: true
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http
              # global token_bucket settings, all routes contribute to consume this quota.
              token_bucket:
                max_tokens: 2147483647
                tokens_per_fill: 2147483647
                fill_interval: 10s
              # This adds the ability to see headers for how many tokens are left in the bucket, how often the bucket refills, and what is the token bucket max.
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              filter_enabled:
                runtime_key: http_local_rate_limiter
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: http_local_rate_limiter
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                    - key: header_match
                      value: header_path
                    - key: api_key
                      value: "111"
                  token_bucket:
                    max_tokens: 2
                    tokens_per_fill: 2
                    fill_interval: 10s

  ```

  ### bucket per descriptors entry (works)
  ```
  apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: httpbin
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8000"
            route:
              action: ROUTE
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          route:
            rate_limits:
              - actions:
                  - request_headers:
                      header_name: api-key
                      descriptor_key: api_key
              - actions:
                  - request_headers:
                      header_name: ":path"
                      descriptor_key: path
              - actions:
                  - header_value_match:
                      descriptor_value: "header_path"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /headers
                            ignore_case: true
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http
              # global token_bucket settings, all routes contribute to consume this quota.
              token_bucket:
                max_tokens: 2147483647
                tokens_per_fill: 2147483647
                fill_interval: 10s
              # This adds the ability to see headers for how many tokens are left in the bucket, how often the bucket refills, and what is the token bucket max.
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              filter_enabled:
                runtime_key: http_local_rate_limiter
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: http_local_rate_limiter
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                    - key: header_match
                      value: header_path
                  token_bucket:
                    max_tokens: 2
                    tokens_per_fill: 2
                    fill_interval: 10s
                - entries:
                    - key: api_key
                      value: "111"
                  token_bucket:
                    max_tokens: 2
                    tokens_per_fill: 2
                    fill_interval: 10s

  ```
</details>

### Version

```Text
client version: 1.24.0
control plane version: 1.23.2
data plane version: 1.23.2 (18 proxies)

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.6-eks-7f9249a
```

**Comment by hzxuzhonghu** [comment]
```
            descriptors:
              - entries:
                  - key: header_match
                    value: header_path
                  - key: api_key
                    value: "111"
```

These two entries should be matched simultaneously

**Comment by IgorIgnatevSky** [comment]
Yes, that's what I expected, but it's not working. 

Tried with
```
curl -s https://httpbin.mydomain.com/headers --header 'x-api-key: 111' -o /dev/null -w "%{http_code}\n"; sleep 0.1; done
```
And got no effect all requests passed with 200

**Comment by brainfair** [comment]
Sorry, copy-pasted the wrong test run. 
Proper is but still not working

```
for i in {1..100}; do curl -s https://httpbin.mydomain.com/headers --header 'api-key: 111' -o /dev/null -w "%{http_code}\n"; sleep 0.1; done
```

**Comment by hzxuzhonghu** [comment]
NOt sure, i saw envoy docs has an example with two entries too

**Comment by IgorIgnatevSky** [comment]
Yes, that is why I raised the issue, because from docs, it should work, but when I tried to use such an example, I unfortunately got a negative result. It only works when I separate entries to different buckets and rate limiting work with separate conditions, but when I try to combine it simultaneously, then no.

**Comment by hzxuzhonghu** [comment]
Should report this to envoy

**Comment by zirain** [comment]
can you share the logs from ratelimit server?

**Comment by IgorIgnatevSky** [comment]
there is no rate limit server; it's a local rate limiter

**Comment by zirain** [comment]
> there is no rate limit server; it's a local rate limiter

oh, sorry I read it wrong.

can you enable log by running `istioctl pc log <pod_name> -n <pod_ns> --level ratelimit:debug`

**Comment by IgorIgnatevSky** [comment]
@zirain got an error
`Error: unrecognized logger name: ratelimit`

**Comment by zirain** [comment]
> @zirain got an error `Error: unrecognized logger name: ratelimit`

sorry, `istioctl pc log <pod_name> -n <pod_ns> --level filter:debug`

BTY, can you try to change your configuration like following:
```
rate_limits:
            - actions:
                - header_value_match:
                    descriptor_value: "header_path"
                    expect_match: true
                    headers:
                      - name: :path
                        string_match:
                          prefix: /headers
                          ignore_case: true
                - request_headers:
                    header_name: api-key
                    descriptor_key: api_key
            - actions:
                - request_headers:
                    header_name: ":path"
                    descriptor_key: path
               
```
