### ISSUE TITLE
[0.8] [Helm] Ingress generates 404 NR

### ISSUE THREAD

**Issue by BastienM** [istio/istio#5409]
Hi,

I am currently encountering some difficulties with deploying a RocketChat instance with Istio.

The pod is healthy and correctly registered but when querying it from the outside the js and css assets fails to load.
Using `kubectl port-forward` with the pod let me checked that the Rocketchat container was indeed responsive and served correctly the assets.

#### kubectl cmds
```
$ kubectl get ns -L istio-injection                                                                                                                           update-mongo-cmd ✱ ◼
NAME           STATUS    AGE       ISTIO-INJECTION
default        Active    7d        disabled
istio-system   Active    1d
kube-public    Active    7d
kube-system    Active    7d
rocketchat     Active    1d        enabled


$ kubectl get all -o wide -n rocketchat
NAME                              READY     STATUS    RESTARTS   AGE       IP                NODE
pod/rocketchat-84cfbf9f84-b7jp5   2/2       Running   0          4h        100.105.244.145   ip-172-20-47-4.eu-west-1.compute.internal

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE       SELECTOR
service/rocketchat   ClusterIP   100.67.240.168   <none>        3000/TCP   4h        app=rocketchat

NAME                               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS   IMAGES                          SELECTOR
deployment.extensions/rocketchat   1         1         1            1           4h        rocketchat   rocketchat/rocket.chat:0.64.0   app=rocketchat

NAME                                          DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES                          SELECTOR
replicaset.extensions/rocketchat-5d697fdd6f   0         0         0         4h        rocketchat   rocketchat/rocket.chat:0.64.0   app=rocketchat,pod-template-hash=1825398829
replicaset.extensions/rocketchat-84cfbf9f84   1         1         1         4h        rocketchat   rocketchat/rocket.chat:0.64.0   app=rocketchat,pod-template-hash=4079695940

NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS   IMAGES                          SELECTOR
deployment.apps/rocketchat   1         1         1            1           4h        rocketchat   rocketchat/rocket.chat:0.64.0   app=rocketchat

NAME                                    DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES                          SELECTOR
replicaset.apps/rocketchat-5d697fdd6f   0         0         0         4h        rocketchat   rocketchat/rocket.chat:0.64.0   app=rocketchat,pod-template-hash=1825398829
replicaset.apps/rocketchat-84cfbf9f84   1         1         1         4h        rocketchat   rocketchat/rocket.chat:0.64.0   app=rocketchat,pod-template-hash=4079695940


$ kubectl get all -n istio-system                                                                                                                             update-mongo-cmd ✱ ◼
NAME                                            READY     STATUS    RESTARTS   AGE
pod/grafana-595db6d9f9-kwrc5                    1/1       Running   0          1d
pod/istio-citadel-7fd696b4c8-gz28f              1/1       Running   0          1d
pod/istio-egressgateway-9f45c9fd-hjcbc          1/1       Running   0          1d
pod/istio-ingress-9d8cfd47d-8tlmb               1/1       Running   0          1d
pod/istio-ingressgateway-67b97b7664-8g4fj       1/1       Running   0          1d
pod/istio-mixer-delete-cr-gzhk4                 0/1       Error     0          1d
pod/istio-mixer-delete-cr-k4hwh                 0/1       Error     0          1d
pod/istio-mixer-delete-cr-n69cl                 0/1       Error     0          1d
pod/istio-mixer-delete-cr-rdg4q                 0/1       Error     0          1d
pod/istio-mixer-delete-cr-rx652                 0/1       Error     0          1d
pod/istio-mixer-delete-cr-zm8b2                 0/1       Error     0          1d
pod/istio-pilot-5c78759d4f-hqdrp                2/2       Running   0          1d
pod/istio-policy-b458575ff-rnqjt                2/2       Running   0          1d
pod/istio-sidecar-injector-68df48d647-xc6br     1/1       Running   0          1d
pod/istio-statsd-prom-bridge-6dbb7dcc7f-5k8xq   1/1       Running   0          1d
pod/istio-telemetry-597b8fd589-4p8tq            2/2       Running   0          1d
pod/jaeger-deployment-559c8b9b8-pxqjz           1/1       Running   0          1d
pod/prometheus-586d95b8d9-j9grf                 1/1       Running   0          1d
pod/zipkin-759b669cd-9fbm4                      1/1       Running   0          1d

NAME                               TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)                                                               AGE
service/grafana                    ClusterIP      100.68.178.209   <none>             3000/TCP                                                              1d
service/istio-citadel              ClusterIP      100.69.158.56    <none>             8060/TCP,9093/TCP                                                     1d
service/istio-egressgateway        ClusterIP      100.66.190.25    <none>             80/TCP,443/TCP                                                        1d
service/istio-ingress              LoadBalancer   100.64.255.96    a5aa3cfa34eb1...   80:31144/TCP,443:30396/TCP                                            1d
service/istio-ingressgateway       LoadBalancer   100.66.208.57    a5aaf57fd4eb1...   80:31380/TCP,443:31390/TCP,31400:31400/TCP                            1d
service/istio-pilot                ClusterIP      100.67.152.168   <none>             15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   1d
service/istio-policy               ClusterIP      100.69.214.36    <none>             9091/TCP,15004/TCP,9093/TCP                                           1d
service/istio-sidecar-injector     ClusterIP      100.71.49.160    <none>             443/TCP                                                               1d
service/istio-statsd-prom-bridge   ClusterIP      100.70.191.243   <none>             9102/TCP,9125/UDP                                                     1d
service/istio-telemetry            ClusterIP      100.71.188.33    <none>             9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 1d
service/jaeger-agent               ClusterIP      None             <none>             5775/UDP,6831/UDP,6832/UDP                                            1d
service/jaeger-collector           ClusterIP      100.70.25.20     <none>             14267/TCP,14268/TCP,9411/TCP                                          1d
service/jaeger-query               LoadBalancer   100.64.16.147    a0f7227844ec4...   80:30091/TCP                                                          1d
service/prometheus                 ClusterIP      100.67.149.200   <none>             9090/TCP                                                              1d
service/zipkin                     ClusterIP      None             <none>             9411/TCP                                                              1d

NAME                                             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/grafana                    1         1         1            1           1d
deployment.extensions/istio-citadel              1         1         1            1           1d
deployment.extensions/istio-egressgateway        1         1         1            1           1d
deployment.extensions/istio-ingress              1         1         1            1           1d
deployment.extensions/istio-ingressgateway       1         1         1            1           1d
deployment.extensions/istio-pilot                1         1         1            1           1d
deployment.extensions/istio-policy               1         1         1            1           1d
deployment.extensions/istio-sidecar-injector     1         1         1            1           1d
deployment.extensions/istio-statsd-prom-bridge   1         1         1            1           1d
deployment.extensions/istio-telemetry            1         1         1            1           1d
deployment.extensions/jaeger-deployment          1         1         1            1           1d
deployment.extensions/prometheus                 1         1         1            1           1d
deployment.extensions/zipkin                     1         1         1            1           1d

NAME                                                        DESIRED   CURRENT   READY     AGE
replicaset.extensions/grafana-595db6d9f9                    1         1         1         1d
replicaset.extensions/istio-citadel-7fd696b4c8              1         1         1         1d
replicaset.extensions/istio-egressgateway-9f45c9fd          1         1         1         1d
replicaset.extensions/istio-ingress-9d8cfd47d               1         1         1         1d
replicaset.extensions/istio-ingressgateway-67b97b7664       1         1         1         1d
replicaset.extensions/istio-pilot-5c78759d4f                1         1         1         1d
replicaset.extensions/istio-policy-b458575ff                1         1         1         1d
replicaset.extensions/istio-sidecar-injector-68df48d647     1         1         1         1d
replicaset.extensions/istio-statsd-prom-bridge-6dbb7dcc7f   1         1         1         1d
replicaset.extensions/istio-telemetry-597b8fd589            1         1         1         1d
replicaset.extensions/jaeger-deployment-559c8b9b8           1         1         1         1d
replicaset.extensions/prometheus-586d95b8d9                 1         1         1         1d
replicaset.extensions/zipkin-759b669cd                      1         1         1         1d

NAME                                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/grafana                    1         1         1            1           1d
deployment.apps/istio-citadel              1         1         1            1           1d
deployment.apps/istio-egressgateway        1         1         1            1           1d
deployment.apps/istio-ingress              1         1         1            1           1d
deployment.apps/istio-ingressgateway       1         1         1            1           1d
deployment.apps/istio-pilot                1         1         1            1           1d
deployment.apps/istio-policy               1         1         1            1           1d
deployment.apps/istio-sidecar-injector     1         1         1            1           1d
deployment.apps/istio-statsd-prom-bridge   1         1         1            1           1d
deployment.apps/istio-telemetry            1         1         1            1           1d
deployment.apps/jaeger-deployment          1         1         1            1           1d
deployment.apps/prometheus                 1         1         1            1           1d
deployment.apps/zipkin                     1         1         1            1           1d

NAME                                                  DESIRED   CURRENT   READY     AGE
replicaset.apps/grafana-595db6d9f9                    1         1         1         1d
replicaset.apps/istio-citadel-7fd696b4c8              1         1         1         1d
replicaset.apps/istio-egressgateway-9f45c9fd          1         1         1         1d
replicaset.apps/istio-ingress-9d8cfd47d               1         1         1         1d
replicaset.apps/istio-ingressgateway-67b97b7664       1         1         1         1d
replicaset.apps/istio-pilot-5c78759d4f                1         1         1         1d
replicaset.apps/istio-policy-b458575ff                1         1         1         1d
replicaset.apps/istio-sidecar-injector-68df48d647     1         1         1         1d
replicaset.apps/istio-statsd-prom-bridge-6dbb7dcc7f   1         1         1         1d
replicaset.apps/istio-telemetry-597b8fd589            1         1         1         1d
replicaset.apps/jaeger-deployment-559c8b9b8           1         1         1         1d
replicaset.apps/prometheus-586d95b8d9                 1         1         1         1d
replicaset.apps/zipkin-759b669cd                      1         1         1         1d

NAME                                                       REFERENCE                         TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-egressgateway    Deployment/istio-egressgateway    <unknown>/80%   1         1         1          1d
horizontalpodautoscaler.autoscaling/istio-ingress          Deployment/istio-ingress          <unknown>/80%   1         1         1          1d
horizontalpodautoscaler.autoscaling/istio-ingressgateway   Deployment/istio-ingressgateway   <unknown>/80%   1         1         1          1d

NAME                              DESIRED   SUCCESSFUL   AGE
job.batch/istio-mixer-delete-cr   1         0            1d
```

#### ingress logs
```
[2018-05-04T12:24:45.867Z] "GET /68dad035195be8b48a8584596e12172e88c27a72.css?meteor_css_resource=true HTTP/1.1" 404 NR 0 0 0 - "172.20.48.196" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "441d64fa-1416-9d91-a922-3c1d00fa788f" "chat.sandbox.cloud.domain.tld" "-"
[2018-05-04T12:24:45.871Z] "GET /theme.css?a0841a7963c7b338ebfc6f33c1432ca8e8360f47 HTTP/1.1" 404 NR 0 0 0 - "100.105.244.128" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "08f04039-1769-9719-8cff-ccdb5a692379" "chat.sandbox.cloud.domain.tld" "-"
```

#### istio-proxy logs
```
[2018-05-04T12:24:46.260Z] "GET / HTTP/1.1" 200 - 0 26851 9 8 "100.105.244.128" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "6a6d4a9d-0205-9a8b-b8a5-95e250e25f76" "chat.sandbox.cloud.domain.tld" "127.0.0.1:3000"
[2018-05-04T12:24:46.616Z] "GET / HTTP/1.1" 200 - 0 26851 9 8 "100.105.244.128" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "edf5fbe2-d0fd-9f59-85c6-b4b669da12b4" "chat.sandbox.cloud.domain.tld" "127.0.0.1:3000"
```

#### yaml files

```yaml
# app-deployment.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  labels:
    app: rocketchat
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: rocketchat
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketchat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
      - name: rocketchat
        image: rocketchat/rocket.chat:0.64.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3000"
        - name: ROOT_URL
          value: http://chat.sandbox.cloud.domain.tld
        - name: MONGO_URL
          value: "mongodb://rocketchat-db-mongodb-replicaset-0.rocketchat-db-mongodb-replicaset.default.svc.cluster.local/rocketchat?replicaSet=rs0"
        - name: MONGO_OPLOG_URL
          value: mongodb://rocketchat-db-mongodb-replicaset-0.rocketchat-db-mongodb-replicaset.default.svc.cluster.local/local?replicaSet=rs0
        ports:
        - containerPort: 3000
```

```yaml
# app-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rocketchat
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: rocketchat
          servicePort: 3000
```

```yaml
# app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rocketchat-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - chat.sandbox.cloud.domain.tld
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rocketchat
spec:
  hosts:
  - rocketchat
  - chat.sandbox.cloud.domain.tld
  gateways:
  - rocketchat-gateway
  http:
  - route:
    - destination:
        host: rocketchat
        port:
          number: 3000
```

I tried to replicate what is being done in the *bookinfo* samples.
Did I missed something ?
