### ISSUE TITLE
Unable to get the istio gateway verify the pods enabled with https

### ISSUE THREAD

**Issue by SatishNaidi** [istio/istio#54090]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have all out backend pods running on https and when trying to implement the istio gateway with services pods that are already in https, getting server validation errors, Even though made use of destination rules with CA certs as opaque credentials as documented by istio.

```yml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: bookingrequest-api-service-gw
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
    - port:
        number: 443
        name: https
        protocol: https
      tls:
        mode: SIMPLE
        credentialName: istio-credential
      hosts:
        - istio-sit.XXXXXX.com     
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookingrequest-api-service-vs
spec:
  hosts:
  - istio-sit.XXXXXX.com 
  gateways:
  - bookingrequest-api-service-gw
  http:
  - match:
    - uri:
        prefix: /v1/BookingRequests/Ping
    route:
    - destination:
        port:
          number: 443
        host: bookingrequest-api-service
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: bookingrequest-api-service-ds
spec:
  host: bookingrequest-api-service #Name of the service  
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: deliver-credential-opq

```
![SSLErrorIstio](https://github.com/user-attachments/assets/f3f88911-90e6-4d10-99b4-67a9dc179345)

### Version

```Text
$kubectl describe pod istiod-asm-1-22-657588dc5d-l8dff -n aks-istio-system
Name:                 istiod-asm-1-22-657588dc5d-l8dff
Namespace:            aks-istio-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      istiod-asm-1-22
Node:                 aks-sclinbalv2-18057762-vmss0001f5/10.12.64.151
Start Time:           Fri, 15 Nov 2024 06:48:20 +0530
Labels:               app=istiod
                      install.operator.istio.io/owning-resource=unknown
                      istio=istiod
                      istio.io/dataplane-mode=none
                      istio.io/rev=asm-1-22
                      kubernetes.azure.com/managedby=aks
                      operator.istio.io/component=Pilot
                      pod-template-hash=657588dc5d
                      sidecar.istio.io/inject=false


$kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9
```

### Additional Information

failed to fetch ca certificate for kubernetes://deliver-credential-opq-cacert: secret aks-istio-ingress/deliver-credential-opq not found

**Comment by howardjohn** [comment]
Do you have the secret deliver-credential-opq created?

**Comment by howardjohn** [comment]
probably the auto san validation is expecting the cert to be signed for bookingrequest-api-service.ns.svc.cluster.local. What is it signed for?

**Comment by hzxuzhonghu** [comment]
It is expecting the san `istio-sit.XXXXXX.com ` from downstream

**Comment by keithmattix** [comment]
> probably the auto san validation is expecting the cert to be signed for bookingrequest-api-service.ns.svc.cluster.local. What is it signed for?

A completely different SAN. I'm confused though: the transport socket configuration has no SAN validation matcher

**Comment by keithmattix** [comment]
> It is expecting the san `istio-sit.XXXXXX.com ` from downstream 

This is SIMPLE TLS; which downstream are you referring to?

**Comment by hzxuzhonghu** [comment]
@keithmattix the downstream here is the client that access the gateway, it use `istio-sit.XXXXXX.com`, with auo san set, it is expecting this san.

This can be seen dumping the whole cluster configuration

**Comment by keithmattix** [comment]
> probably the auto san validation is expecting the cert to be signed for bookingrequest-api-service.ns.svc.cluster.local. What is it signed for?

It's signed for a Microsoft specific FQDN. The weird thing is that the Envoy config doesn't show any SAN validation in the transport socket. Should I be looking elsewhere?

> @keithmattix the downstream here is the client that access the gateway, it use istio-sit.XXXXXX.com, with auo san set, it is expecting this san.
> 
> This can be seen dumping the whole cluster configuration

Ah, I worked with @SatishNaidi on this, and the browser fully trusts the downstream cert, so that doesn't seem to be the issue. The error seems to be with the upstream connection

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/93a7a8503a4cc1fe2781cbe1a44c3b8be7cc0f20/pilot/pkg/networking/core/cluster_tls.go#L317 looks like its not on transport socket

**Comment by Randgalt** [comment]
This is happening to us too - anything we can do to help get it resolved?

**Comment by keithmattix** [comment]
I will look into it more next week

**Comment by keithmattix** [comment]
Yep, it is indeed auto san validation; it's in the http protocol options and not the transport socket like I thought. I'm thinking subjectAltNames will solve this

**Comment by Randgalt** [comment]
@SatishNaidi is there a PR that I can see where the fix is?

**Comment by SatishNaidi** [comment]
Ops. that was an erraneous closure, I thought it didn't go through, Can you please re-open as I was getting permissions error.

**Comment by keithmattix** [comment]
Can you please share what permissions error you were running into?

**Comment by praveenvdell** [comment]
Please reopen this defect.

**Comment by benmurden** [comment]
I ran into this issue with a DestinationRule for an AWS service external to the Kubernetes cluster. I think the certificate is being validated against the downstream hostname, instead of the one being requested.

The fix was to add the following to the DestinationRule:

```yaml
spec:
  host: some-external-service-id.service-name.region.amazonaws.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      subjectAltNames:
      - "*.service-name.region.amazonaws.com"
```

Unfortunately, this has to match a SAN on the certificate exactly, so you'll need to inspect the certificate claims first.

We are using the new Gateway API (Ambient mode), so we can't rewrite the request `authority` header using a `VirtualService`, but I did find that the following change to the `HTTPRoute` also works:

```yaml
spec:
  parentRefs:
    - name: my-service-gateway
      namespace: my-service
  hostnames:
    - "custom.host.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: some-external-service
          port: 443
      filters:
        # Rewrite the hostname to match the upstream request
        - type: URLRewrite
          urlRewrite:
            hostname: anything.service-name.region.amazonaws.com
```

This changes the hostname of the upstream request to match the returned certificate.
