### ISSUE TITLE
Enable trace in Telemetry API whitelist

### ISSUE THREAD

**Issue by yuzujoe** [istio/istio#54106]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
With the current settings for the workload selector in the Telemetry API, it is possible to disable span reporting for workloads that match the label, but it is not possible to enable only specific workloads.

I would like to see an enhancement that allows you to set it so that only specific workloads are allowed to send traces, rather than enabling tracing for the entire system all at once.

I want to do this below.

```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: ex-app
  tracing:
  - enableSpanReporting: true
```

**Describe alternatives you've considered**
Adding a common label to the resources you want to disable sending, you can prevent the span from being transferred.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
you can make it default off, and then enable it base on selector.

for a long term, we can support `disabled` in `metrics` and `tracing`, just like what we did in `accesslogging`.

**Comment by hzxuzhonghu** [comment]
Another way should be disable all the traces by a global telemetry if the meshConfig cannot be mutated later, and then enable specific workload trace

**Comment by yuzujoe** [comment]
@zirain @hzxuzhonghu 
Thanks response.

After setting it up as follows, it worked as expected.

```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-demo
spec:
  tracing:
    - disableSpanReporting: true
```

```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: app
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
      disableSpanReporting: false
```

Thanks.
