### ISSUE TITLE
Feature Request - Vizceral addon

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#5410]
Create an addon to view Istio metrics in Vizceral. The metrics can be gathered from Prometheus. I'd like to propose to name it Vistio :)

Can reference this project as a starting point https://github.com/nghialv/promviz

**Comment by linsun** [comment]
subscribe and + @esnible

**Comment by jmazzitelli** [comment]
FYI: Kiali is a front end to istio currently in development (no official release just yet) - it does take the Prometheus metrics and visualizes them (along with visualizing the mesh and other things such as visualizing circuit breakers, route rules and integrating Jaeger tracing). See https://kiali.github.io/ for details. We have a JIRA issue created to propose it as an istio add-on which would address this istio issue... see https://issues.jboss.org/browse/KIALI-386

**Comment by objectiser** [comment]
@nmnellis Having options is always good  :)

If you get a chance to give Kiali a try, we would be very interested in your feedback, and if there are any features you would like to see let us know.

**Comment by esnible** [comment]
When I tested Promviz there were three difficult things I had to do.  Nick has already talked about needing to add a complex set of values to _promviz/helm/promviz/values.yaml_

_Promviz_ expects "standard" storage which is not provided by IBM Cloud.  My work-around was to make "standard" a synonym for bronze but there shouldn’t be a requirement on a storage type.  Also it might be good to have a way to run without storage for folks who are experimenting with the free cluster.

```
kubectl get storageclasses ibmc-file-bronze -o yaml | \
    sed s/ibmc-file-bronze/standard/ | \
    kubectl create -f -
```

Promviz-Front (specifically _promviz-front/src/app.jsx_) calls `WebFont.load()` and does nothing until the font because active.  On my browsers the font never became active; I had to modify the code so that it would call `fontsActive()` even if WebFont.load() reported _inactive_ status.

**Comment by nmnellis** [comment]
i want to look and see if we can just provide an inmem solution that translates prometheus metrics to vizceral. that would make it a lot easier to install and use for first time users.

**Comment by AlexRRR** [comment]
@nmnellis  would you happen to have sample configuration for promviz I could  use as starting point? I have no clue whatsoever where to start. (great talk at Kubecon btw)

**Comment by nmnellis** [comment]
for my demo i used statsd-to-prometheus to get metrics from envoy directly
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promviz-config
  namespace: monitoring
data:
  promviz.yaml: |-
    graphName: Istio
    globalLevel:
      maxVolume: 50
      clusterConnections:
        - query: sum(rate(envoy_upstream_rq_count[1m])) by (job, status)
          prometheusURL: http://prometheus:9090
          source:
            replacement: INTERNET
          target:
            label: job
          status:
            label: status
            warningRegex: ^4..$
            dangerRegex: ^5..$
    clusterLevel:
      - cluster: envoy
        maxVolume: 10
        serviceConnections:
          - query: sum(rate(envoy_upstream_rq_count[1m])) by (cluster,status,job)
            prometheusURL: http://prometheus:9090
            source:
              label: job
            target:
              label: cluster
            status:
              label: status
              warningRegex: ^4..$
              dangerRegex: ^5..$
            notices:
              - name: HighErrorRate
                title: "[{{ .value }}] HighErrorRate"
                statusType: danger
                severityThreshold:
                  warning: .05
                  error: .10
```
