### ISSUE TITLE
TCPRoute not implemented in waypoint

### ISSUE THREAD

**Issue by snpsuen** [istio/istio#54119]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We followed the steps in https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/ to test out the redirection of tcp-echo services.
```
kubectl -n istio-io-tcp-traffic-shifting apply -f samples/curl/curl.yaml
kubectl -n istio-io-tcp-traffic-shifting apply -f samples/tcp-echo/tcp-echo-services.yaml
kubectl -n istio-io-tcp-traffic-shifting apply -f samples/tcp-echo/gateway-api/tcp-echo-all-v1.yaml
```

We are able to move all the tcp-echo requests to tcp-echo:v1 through tcp-echo-gateway-istio in the north-west direction.

Unfortunately, the same cannot be achieved with the east-west traffic inside a service mesh.
Define a east-west bound TCPRoute by setting the .spec.parentRefs[*] to the K8s service tcp-echo.
```
kubectl -n istio-io-tcp-traffic-shifting apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-echo-ew
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: tcp-echo
  rules:
  - backendRefs:
    - name: tcp-echo-v1
      port: 9000
EOF
```
Nevertheless, the traffic is still observed to shift randomly between tcp-echo:v1 and tcp-echo:v2.
```
kubectl -n istio-io-tcp-traffic-shifting exec deploy/curl -- sh -c "while true 
do
        date | nc tcp-echo 9000
        sleep 2
done"
two Sun Dec  1 17:12:34 UTC 2024
two Sun Dec  1 17:12:36 UTC 2024
one Sun Dec  1 17:12:38 UTC 2024
two Sun Dec  1 17:12:40 UTC 2024
two Sun Dec  1 17:12:42 UTC 2024
two Sun Dec  1 17:12:44 UTC 2024
one Sun Dec  1 17:12:46 UTC 2024
two Sun Dec  1 17:12:48 UTC 2024
two Sun Dec  1 17:12:50 UTC 2024
one Sun Dec  1 17:12:52 UTC 2024
two Sun Dec  1 17:12:54 UTC 2024
one Sun Dec  1 17:12:56 UTC 2024
```

### Version

```Text
istioctl version
client version: 1.24.0
control plane version: 1.24.0
data plane version: 1.22.0 (1 proxies), 1.24.0 (4 proxies)

kubectl version
kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.27.3
```

**Comment by zirain** [comment]
> There is a common misconception (due to docs over-simplification) that TCP=Ztunnel, HTTP=Waypoint. This is not quite true - TCPRoute is only implemented in the waypoint.

good to know that

**Comment by snpsuen** [comment]
Still no luck after deploying a waypoint proxy in the namespace.
```
keyuser@ubunclone:~/istio-1.24.0$ istioctl waypoint apply -n istio-io-tcp-traffic-shifting --enroll-namespace --overwrite --wait
waypoint istio-io-tcp-traffic-shifting/waypoint applied
namespace istio-io-tcp-traffic-shifting labeled with "istio.io/use-waypoint: waypoint"
keyuser@ubunclone:~/istio-1.24.0$
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get gtw
NAME               CLASS            ADDRESS        PROGRAMMED   AGE
tcp-echo-gateway   istio            172.18.0.11    True         2m15s
waypoint           istio-waypoint   10.96.173.44   True         40s
keyuser@ubunclone:~/istio-1.24.0$
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get svc
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                           AGE
curl                     ClusterIP      10.96.65.161    <none>        80/TCP                            2m53s
tcp-echo                 ClusterIP      10.96.47.112    <none>        9000/TCP,9001/TCP                 2m41s
tcp-echo-gateway-istio   LoadBalancer   10.96.135.250   172.18.0.11   15021:30999/TCP,31400:30343/TCP   2m22s
tcp-echo-v1              ClusterIP      10.96.61.128    <none>        9000/TCP                          2m22s
tcp-echo-v2              ClusterIP      10.96.49.160    <none>        9000/TCP                          2m22s
waypoint                 ClusterIP      10.96.173.44    <none>        15021/TCP,15008/TCP 
```
Unfortunately, our east-west TCPRoute still stubbornly refuses to work.
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-echo-ew
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: tcp-echo
  rules:
  - backendRefs:
    - name: tcp-echo-v1
      port: 9000
EOF
tcproute.gateway.networking.k8s.io/tcp-echo-ew created
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get tcproute
NAME          AGE
tcp-echo      5m2s
tcp-echo-ew   20s
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting exec deploy/curl -- sh -c "while true
do
        date | nc tcp-echo 9000
        sleep 2
done"
two Mon Dec  2 23:43:57 UTC 2024
two Mon Dec  2 23:44:00 UTC 2024
two Mon Dec  2 23:44:02 UTC 2024
one Mon Dec  2 23:44:04 UTC 2024
two Mon Dec  2 23:44:06 UTC 2024
two Mon Dec  2 23:44:08 UTC 2024
one Mon Dec  2 23:44:10 UTC 2024
one Mon Dec  2 23:44:12 UTC 2024
two Mon Dec  2 23:44:14 UTC 2024
two Mon Dec  2 23:44:16 UTC 2024
```
And everything looks OK from the status of the TCPRoute tcp-echo-ew.
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get tcproute tcp-echo-ew -o yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1alpha2","kind":"TCPRoute","metadata":{"annotations":{},"name":"tcp-echo-ew","namespace":"istio-io-tcp-traffic-shifting"},"spec":{"parentRefs":[{"group":"","kind":"Service","name":"tcp-echo"}],"rules":[{"backendRefs":[{"name":"tcp-echo-v1","port":9000}]}]}}
  creationTimestamp: "2024-12-02T23:42:21Z"
  generation: 1
  name: tcp-echo-ew
  namespace: istio-io-tcp-traffic-shifting
  resourceVersion: "3439506"
  uid: caca7255-abee-4a94-a12c-6775e4ca50ba
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: tcp-echo
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: tcp-echo-v1
      port: 9000
      weight: 1
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-12-02T23:42:21Z"
      message: Route was valid
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-12-02T23:42:21Z"
      message: All references resolved
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: istio.io/gateway-controller
    parentRef:
      group: ""
      kind: Service
      name: tcp-echo
```

**Comment by snpsuen** [comment]
Did I miss anything to link up the TCPRoute tcp-echo-ew and waypoint?
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get tcproute
NAME          AGE
tcp-echo      65m
tcp-echo-ew   60m
keyuser@ubunclone:~/istio-1.24.0$
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get gtw
NAME               CLASS            ADDRESS        PROGRAMMED   AGE
tcp-echo-gateway   istio            172.18.0.11    True         65m
waypoint           istio-waypoint   10.96.173.44   True         63m
```

**Comment by snpsuen** [comment]
Interestingly, the controller name of the east-west tcproute, namely tcp-echo-ew,  is shown to map to istio.io/gateway-controller, instead of istio.io/mesh-controller.
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get tcproute tcp-echo-ew -o yaml
......
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-12-03T19:39:26Z"
      message: Route was valid
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-12-03T19:39:26Z"
      message: All references resolved
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: istio.io/gateway-controller
    parentRef:
      group: ""
      kind: Service
      name: tcp-echo
```
Suppose tcp-echo-ew is be handled by the following waypoint proxy:
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get gtw
NAME               CLASS            ADDRESS        PROGRAMMED   AGE
tcp-echo-gateway   istio            172.18.0.11    True         4h44m
waypoint           istio-waypoint   10.96.243.31   True         4h24m
```
Then, its controller name should point to istio.io/mesh-controller, which is the controller name of the gateway class, istio-waypoint.
```keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting get gatewayclass
NAME             CONTROLLER                    ACCEPTED   AGE
istio            istio.io/gateway-controller   True       27d
istio-remote     istio.io/unmanaged-gateway    True       27d
istio-waypoint   istio.io/mesh-controller      True       27d
```

**Comment by howardjohn** [comment]
> Suppose tcp-echo-ew is be handled by the waypoint proxy of the gateway class, istio-waypoint.

I think this is just a bug in the status reporting, seems to be the same in HTTPRoute which seems to work. So I think this should be fixed probably but is not likely tied to the issue.

However I do think I just generally see it doesn't work and think thats a bug. Thanks for bringing this up.

**Comment by snpsuen** [comment]
Done an ugly-dirty hack to force the waypoint proxy to honor a specific east/west tcproute by using envoyfilter to patch the relevant filter of the "main-internal" listener accordingly.
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-echo-filter
  namespace: istio-io-tcp-traffic-shifting # as defined in meshConfig resource.
spec:
  workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: waypoint
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND # will match inbound listeners in all sidecars
      listener:
        name: "main_internal"
        filterChain:
          name: "inbound-vip|9000|tcp|tcp-echo.istio-io-tcp-traffic-shifting.svc.cluster.local"
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: REPLACE
      value:
        name: "envoy.filters.network.tcp_proxy"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
          statPrefix: "inbound-vip|9000|tcp|tcp-echo.istio-io-tcp-traffic-shifting.svc.cluster.local"
          weightedClusters:
            clusters:
            - name: "inbound-vip|9000|tcp|tcp-echo-v1.istio-io-tcp-traffic-shifting.svc.cluster.local"
              weight: 90
            - name: "inbound-vip|9000|tcp|tcp-echo-v2.istio-io-tcp-traffic-shifting.svc.cluster.local"
              weight: 10
EOF
EnvoyFilter exposes internal implementation details that may change at any time. Prefer other APIs if possible, and exercise extreme caution, especially around upgrades.
envoyfilter.networking.istio.io/tcp-echo-filter configured
```
Now, we can shift 90% of the tcp-echo traffic to v1 simply by accessing the tcp-echo k8s service itself.
```
keyuser@ubunclone:~/istio-1.24.0$ kubectl -n istio-io-tcp-traffic-shifting exec deploy/curl -- sh -c "while true
do
        date | nc tcp-echo 9000
        sleep 2
done"
one Mon Dec  9 20:18:19 UTC 2024
one Mon Dec  9 20:18:21 UTC 2024
one Mon Dec  9 20:18:23 UTC 2024
one Mon Dec  9 20:18:25 UTC 2024
one Mon Dec  9 20:18:27 UTC 2024
one Mon Dec  9 20:18:29 UTC 2024
one Mon Dec  9 20:18:31 UTC 2024
one Mon Dec  9 20:18:33 UTC 2024
one Mon Dec  9 20:18:35 UTC 2024
one Mon Dec  9 20:18:37 UTC 2024
two Mon Dec  9 20:18:39 UTC 2024
one Mon Dec  9 20:18:41 UTC 2024
one Mon Dec  9 20:18:43 UTC 2024
one Mon Dec  9 20:18:45 UTC 2024
two Mon Dec  9 20:18:47 UTC 2024
one Mon Dec  9 20:18:49 UTC 2024
one Mon Dec  9 20:18:51 UTC 2024
one Mon Dec  9 20:18:53 UTC 2024
one Mon Dec  9 20:18:55 UTC 2024
^C
```
