### ISSUE TITLE
Thanos-Querier error "rpc error: code = DeadlineExceeded desc = context deadline exceeded" with istio cross-cluster commnunication 

### ISSUE THREAD

**Issue by inboxamitraj** [istio/istio#54115]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**What happened**:
We are using Prometheus Operator in EKS with cross cluster communication setup with Istio Service Mesh.
We have Grafana and Thanos-Querier on Cluster A, which works as centralised Grafana/Querier.
For each clusters, e.g. Cluster B, C, D we have a Thanos-Querier running on our Centralised Cluster A which queries thanos-store and thanos-sidecar running on other cluster.

we recently upgraded Istio to 1.20 from 1.19 since then Grafana does not show latest prometheus metrics on other clusters. however we can see  prometheus metrics before 2 hours. This means- Thanos-Querier can talk to Thanos-Store but not able to connect to live Thanos-SideCar which has latest prometheus metrics.

**What you expected to happen**:
Centralised Grafana should show latest prometheus metrics from other clusters after Istio upgrade 

**How to reproduce it (as minimally and precisely as possible)**:
Two EKS 1.29 Clusters
Upgrade Istio from 1.19 to 1.20
Prometheus Operator running on both the Clusters and one of the cluster working as Centralised Cluster.

 
**Full logs to relevant components**:
```
ts=2024-12-01T03:34:36.827530034Z caller=endpointset.go:460 level=warn component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from test-component-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-component-metrics-grpc-consumer.test:10901
ts=2024-12-01T03:34:36.827530004Z caller=endpointset.go:460 level=warn component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from test-cluster-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-cluster-metrics-grpc-consumer.test:10901
ts=2024-12-01T03:34:36.827616429Z caller=endpointset.go:433 level=debug component=endpointset msg="updated endpoints" activeEndpoints=1
ts=2024-12-01T03:34:36.827667822Z caller=endpointset.go:354 level=debug component=endpointset msg="starting to update API endpoints" cachedEndpoints=1
```

**Anything else we need to know**:
What we have done so far-
added --query.grpc.client.serverName
increased timeouts 
attempted with latest Thanos v0.37.0 image.

Thanos-Querier Deployment in Cluster A
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        tls: permissive
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:9090
        - --store=kube-prometheus-stack-prometheus-sidecar-grpc.monitoring.svc.cluster.local:10901
        - --store=test-cluster-metrics-grpc-consumer.test:10901
        - --store=test-component-metrics-grpc-consumer.test:10901
        - --store=thanos-store-test.monitoring.svc.cluster.local:10901
        name: thanos-querier
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: cstack-thanos-s3
        secret:
          defaultMode: 420
          secretName: cstack-thanos-sealed-s3-test
```

Service Entry in Cluster A
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-cluster-metrics-grpc-consumer-import
  namespace: monitoring
spec:
  endpoints:
  - address: test-e01-shared-mesh.istio-eastwest-internal
    labels:
      security.istio.io/tlsMode: istio
  exportTo:
  - .
  hosts:
  - test-cluster-metrics-grpc-consumer.test
  location: MESH_INTERNAL
  ports:
  - name: grpc-10901
    number: 10901
    protocol: GRPC
  resolution: DNS
```
Destination Rule in Cluster A
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: 
  name: test-cluster-metrics-grpc-consumer-import
  namespace: monitoring
spec:
  exportTo:
  - .
  host: test-cluster-metrics-grpc-consumer.test
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: outbound_.10901_._.cluster-metrics-grpc-provider.monitoring.svc.cluster.local
```

Attached- Grafana screenshot - we cannot see the latest metrics, however metrics older than 2 hours can be seen
<img width="595" alt="Screenshot 2024-12-01 at 11 36 44 AM" src="https://github.com/user-attachments/assets/5d82b80f-236d-4be7-8389-207e9aaa9578">

### Version

```Text
$ istioctl version
client version: 1.23.3
control plane version: 1.20.2
data plane version: 1.20.2 (13 proxies)

$ kubectl version
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.29.10-eks-7f9249a
```

**Comment by inboxamitraj** [comment]
I found a workaround solution to this issue, just add the service name (endpoint) in another cluster to the thanos store.
The new line fixed the issue is : `- --store=kube-prometheus-stack-prometheus-sidecar-grpc.monitoring.svc.cluster.local:10901`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        tls: permissive
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:9090
        - --store=kube-prometheus-stack-prometheus-sidecar-grpc.monitoring.svc.cluster.local:10901
        - --store=gen-prd-cluster-metrics-grpc-consumer.gen-prd:10901

```
