### ISSUE TITLE
`VirtualService` result to 503 for k8s inner coredns host without creating `ServiceEntry`

### ISSUE THREAD

**Issue by so2bin** [istio/istio#54148]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

* Firstly, create the following vs:
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: klink-route-inner-to-mock-inner
  namespace: ai-web-0
spec:
  hosts:
  - "inner-api.atms.cn"
  exportTo:
  - ai-web-0
  http:
  - match:
    - headers:
        x-klink-stress: {}
        x-klink-mock: {}
      uri:
        regex: "^/(get|post|api)/.*"
      port: 80
      sourceNamespace: ai-web-0
      ignoreUriCase: true
      sourceLabels:
        app: otel-server-v1
    route:
    - destination:
        host: otel-upstream-v1.ai-web-0.svc.cluster.local
        port:
          number: 80
  # 没配置gateways，必须配置默认路由
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: inner-api.atms.cn
```
* Now, enter into a pod terminal in namepsace: `ai-web-0`, and access this host will got 503:
```bash
kubectl  exec -it -n ai-web-0  otel-upstream-v1-7b76f6b66f-95j46 sh
$ /app # curl -i http://inner-api.atms.cn/api/11327/3nLRof/ping
HTTP/1.1 503 Service Unavailable
date: Tue, 03 Dec 2024 07:01:43 GMT
server: envoy
content-length: 0
```
* Secondly, create the `ServiceEntry`:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: klink-se-to-mock-inner-api
  namespace: ai-web-0
spec:
  hosts:
  - "inner-api.atms.cn"
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP 
  resolution: DNS
```
* Now access this host will got 200:
```bash
/app # curl -i http://inner-api.atms.cn/api/11327/3nLRof/ping
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
date: Tue, 03 Dec 2024 07:07:38 GMT
content-length: 6
x-envoy-upstream-service-time: 2
server: envoy
```

### Version

```Text
# helm list -n istio-system
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
istio-base      istio-system    1               2024-09-10 16:44:07.348013335 +0800 CST deployed        base-1.21.1     1.21.1     
istiod          istio-system    2               2024-09-10 16:46:03.313335804 +0800 CST deployed        istiod-1.21.1   1.21.1  

kubectl:  1.27.6
```

### Additional Information
* `inner-api.atms.cn` this host is added to coredns:
```yaml
# coredns configmap
rewrite name inner-api.atms.wps.cn istio-ingress.istio-ingress.svc.cluster.local
```

_No response_

**Comment by hzxuzhonghu** [comment]
```  
  route:
    - destination:
        host: inner-api.atms.cn
```

This requires a service defined for this host, so this is correct behavior

**Comment by howardjohn** [comment]
This is working as expected. Istio does not utilize DNS like this. Something must be in its service registry (either via Service or ServiceEntry) to be a destination. There is no transparent forwarding to arbitrary hostnames.

**Comment by so2bin** [comment]
@howardjohn Thanks very much for your explanation, I am still confused about this question. Beacuse generally i am using the `VirtualService` with ingressgateway, like this config:
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: klink-route-inner-to-mock-inner
  namespace: ai-web-0
spec:
  gateways:
  - istio-ingress/llm-gateway
  hosts:
  - "inner-api.atms.cn"
  exportTo:
  - ai-web-0
  http:
  - match:
      uri:
        regex: "^/(get|post|api)/.*"
      port: 80
      sourceNamespace: ai-web-0
      ignoreUriCase: true
      sourceLabels:
        app: otel-server-v1
    route:
    - destination:
        host: otel-upstream-v1.ai-web-0.svc.cluster.local
        port:
          number: 80
```
Here we do not need a `ServiceEntry` for the `inner-api.atms.cn` host. Is it the reason that the ingress-gateway will do DNS discover for this host, but envoy sidecar will not do DNS when routing request?

**Comment by so2bin** [comment]
@howardjohn Another question:

* I have understand the destination/vs host in istio should be a FQDN host or a short name without dots that can be found in the service registry.
* So the following `vs` that without gateway can work correctly for requests with host `hbb-demo-1-v1.ai-web-0.svc.cluster.local` even I have not created a `ServiceEntry` for it, but what will happen if I create a `ServiceEntry`  for this host  `hbb-demo-1-v1.ai-web-0.svc.cluster.local`  at the same time? Will it have some conflict?
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: klink-route-svc-to-mock-svc
  namespace: ai-web-0
spec:
  hosts:
  - "hbb-demo-1-v1.ai-web-0"
  - "hbb-demo-1-v1.ai-web-0.svc.cluster.local"
  exportTo:
  - ai-web-0
  http:
  - match:
    - headers:
        x-klink-stress: {}
        x-klink-mock: {}
      uri:
        regex: "^/(get|post|hbb)/.*"
      port: 80
      sourceNamespace: ai-web-0
      ignoreUriCase: true
      sourceLabels:
        app: otel-server-v1
    route:
    - destination:
        host: otel-upstream-v1.ai-web-0.svc.cluster.local
        port:
          number: 80
  # default route
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hbb-demo-1-v1.ai-web-0.svc.cluster.local  
        port: 
          number: 80
```
