### ISSUE TITLE
Gateway deployment's selector mismatch when updating from 1.23.x to 1.24.x

### ISSUE THREAD

**Issue by joze144** [istio/istio#54145]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I was updating Istio (ambient mode) from 1.23.2 to 1.24.1. 

I'm using a Gateway resource:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: some-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All

```

Gateway resource creates a deployment. Problem is, after I run an Istio update, this resource is not automatically updated.

In istiod can see error logs:
```
2024-12-03T00:36:33.571898Z	error	controllers	error handling default/some-gateway, and retry budget exceeded: apply failed: patch apps/v1, Kind=Deployment/default/some-gateway-istio: Deployment.apps "some-gateway-istio" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"gateway.networking.k8s.io/gateway-name":"some-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable	controller=gateway deployment
```

Seems like selectors changed.

### Version

```Text
$ istioctl version
client version: 1.24.1
control plane version: 1.24.1
data plane version: 1.24.1 (3 proxies)
```
