### ISSUE TITLE
VirtualService support route https with headers?

### ISSUE THREAD

**Issue by so2bin** [istio/istio#54149]
**Describe the feature request**
* I want to route the http request to an k8s service, but now the VirtualService can only match the sniHost like the follow config:
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: klink-route-to-mock-https
  namespace: ai-web-0
spec:
  hosts:
  - "httpbin.org"
  - "*.httpbin.org"
  exportTo:
  - ai-web-0
  tls:
  - match:
    - sniHosts:
      - httpbin.org
      - "*.httpbin.org"
      port: 443
      sourceNamespace: ai-web-0
      sourceLabels:
        app: otel-server-v1
    route:
    - destination:
        host: otel-upstream-v1.ai-web-0.svc.cluster.local
        port:
          number: 443
```

**Describe alternatives you've considered**
* I want to route https request like the http, for example of http route with headers and path:
```yaml
  http:
  - match:
    - headers:
        x-klink-stress: {}
        x-klink-mock: {}
      uri:
        regex: "^/(get|post|hbb)/.*" 
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
This is because you are not setting up tls terminate. So envoy does not parse http protocol at all.

**Comment by so2bin** [comment]
> This is because you are not setting up tls terminate. So envoy does not parse http protocol at all.
@hzxuzhonghu Thanks to reply.

The caller is a pod exist in the k8s and it will call an external https url outof the istio mesh, like https://httpbin.org/get,  now i want to route this https to another k8s local service like `otel-upstream-v1.ai-web-0.svc.cluster.local` here. 
Is it possible to route https with path? like this:
```yaml
  http:
  - match:
    - headers:
        x-klink-stress: {}
        x-klink-mock: {}
      uri:
        regex: "^/(get|post|hbb)/.*" 
```
