### ISSUE TITLE
Helm validation fails due to incompatible type.

### ISSUE THREAD

**Issue by phvel01** [istio/istio#54151]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When trying to install istio through the ambient umbrella chart it fails due to validation failure. 

Unable to save changes: application spec for istio is invalid: InvalidSpecError: Unable to generate manifests in management-system/admin-applications/helmcharts/istio: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template istio --namespace istio-system --kube-version 1.30 --set targetRevision=test --values <path to cached source>/management-system/admin-applications/helmcharts/istio/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: istio-ambient/charts/ambient/charts/ztunnel/templates/rbac.yaml:24:8: executing "istio-ambient/charts/ambient/charts/ztunnel/templates/rbac.yaml" at <eq .Values.platform "openshift">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

### Version

```Text
v3.15.0+gc4e37b3 (Helm version --short)
```

**Comment by howardjohn** [comment]
I cannot reproduce this. Can you upload the full values.yaml or some other way to reproduce the issue?

**Comment by phvel01** [comment]
Sure,

Here is the Chart.yaml file

`
apiVersion: v2
name: istio-ambient
version: 1.24.1
dependencies:
- name: ambient
  version: 1.24.1
  repository: https://istio-release.storage.googleapis.com/charts
`

And here is the values.yaml file

`global:
  variant: distroless

# Overrides for the `istiod-remote` dep
istiod:
  enabled: true
  profile: ambient

# Overrides for the `ztunnel` dep
ztunnel:
  profile: ambient

# Overrides for the `cni` dep
cni:
  profile: ambient
`

The values file was taken from artifacthub: https://artifacthub.io/packages/helm/istio-official/ambient

**Comment by phvel01** [comment]
And when trying to deploy it through Argocd I get the mentioned error

**Comment by howardjohn** [comment]
I still cannot reproduce..

**Comment by phvel01** [comment]
Could you walk me through the steps that you do, and I will try and follow to see if it works?

**Comment by phvel01** [comment]
Because when I try to point the application to my branch where I have added the files to install istio, then I get this error in a popup.

Unable to save changes: application spec for istio is invalid: InvalidSpecError: Unable to generate manifests in management-system/admin-applications/helmcharts/istio: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template istio --namespace istio-system --kube-version 1.30 --set targetRevision=test --values <path to cached source>/management-system/admin-applications/helmcharts/istio/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: istio-ambient/charts/ambient/charts/ztunnel/templates/rbac.yaml:24:8: executing "istio-ambient/charts/ambient/charts/ztunnel/templates/rbac.yaml" at <eq .Values.platform "openshift">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

**Comment by phvel01** [comment]
App in argo shows error as the default branch does not contain the istio files:

<img width="1620" alt="image" src="https://github.com/user-attachments/assets/b86ef18b-e312-4d81-bea4-5d9c0cca7f5a">


Then when I try and edit the application to point to the right branch: 

<img width="1601" alt="image" src="https://github.com/user-attachments/assets/ca822845-40dd-41cb-adce-90e9042f8222">

**Comment by ilrudie** [comment]
Do we just need this type of guard? https://github.com/istio/istio/pull/52017/files

**Comment by phvel01** [comment]
What do you mean by Values.platform? and where would I find it?

**Comment by ilrudie** [comment]
https://argo-cd.readthedocs.io/en/latest/user-guide/helm/#helm-parameters talks about setting these in ArgoCD. I think you might be able to edit that in the UI as well.

The key would be `global.platform` and just set the value to `""` which may unblock you.

**Comment by bleggett** [comment]
We do not currently test the umbrella chart, or chart composition generally. And we do a lot of special istio-only things we don't test with the latter.

I would suggest you use the individual templated charts with Argo if you want something we actually test.

**Comment by phvel01** [comment]
I've experienced a similar error before when working with helm and argocd, and that was because the operator had in a new version removed some values but in their validation they did not update it, so they where still looking for the old values.

**Comment by phvel01** [comment]
Alright, I will switch to using the individual charts, thank you.

**Comment by phvel01** [comment]
Hello again, currently in the process of installing each component seperately with their own helm chart. I ran into the same problem described above when trying to install cni component.

Unable to create application: application spec for istio-cni is invalid: InvalidSpecError: Unable to generate manifests in management-system/admin-applications/helmcharts/istio-cni: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template istio-cni --namespace istio-system --kube-version 1.30 --values <path to cached source>/management-system/admin-applications/helmcharts/istio-cni/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: istio-cni/charts/cni/templates/clusterrole.yaml:17:8: executing "istio-cni/charts/cni/templates/clusterrole.yaml" at <eq (coalesce .Values.platform .Values.global.platform) "openshift">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

Chart that is giving this error: https://artifacthub.io/packages/helm/istio-official/cni

```yaml
apiVersion: v2
name: istio-cni
version: 1.24.1
dependencies:
- name: cni
  version: 1.24.1
  repository: https://istio-release.storage.googleapis.com/charts

```

**Comment by bleggett** [comment]
> Hello again, currently in the process of installing each component seperately with their own helm chart. I ran into the same problem described above when trying to install cni component.
> 
> Unable to create application: application spec for istio-cni is invalid: InvalidSpecError: Unable to generate manifests in management-system/admin-applications/helmcharts/istio-cni: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template istio-cni --namespace istio-system --kube-version 1.30 --values <path to cached source>/management-system/admin-applications/helmcharts/istio-cni/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: istio-cni/charts/cni/templates/clusterrole.yaml:17:8: executing "istio-cni/charts/cni/templates/clusterrole.yaml" at <eq (coalesce .Values.platform .Values.global.platform) "openshift">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format :
> 
> Chart that is giving this error: https://artifacthub.io/packages/helm/istio-official/cni
> 
> ```yaml
> apiVersion: v2
> name: istio-cni
> version: 1.24.1
> dependencies:
> - name: cni
>   version: 1.24.1
>   repository: https://istio-release.storage.googleapis.com/charts
> ```

I also can't reproduce this, when templating a chart directly from the release repo:

```
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
helm template istio/cni --name-template istio-cni --namespace istio-system --kube-version 1.30 --values values.yaml --include-crds
```

(note that `--include-crds` is useless/does not need to be specified for any Istio chart from 1.24+)

and that `values.yaml`:

```
profile:
  ambient
```

**Comment by phvel01** [comment]
Alright, thank you for the information, like you thought I wrote the chart files myself and did not take them from anywhere. Have not worked with helm charts in a long while.

What is the best way to fetch the chart and store it locally?

**Comment by phvel01** [comment]
You can disregard my last comment, it is helm pull like you mentioned before. Sorry to bother you again, thanks and have a nice day.

**Comment by bleggett** [comment]
> You can disregard my last comment, it is helm pull like you mentioned before. Sorry to bother you again, thanks and have a nice day.

No worries! Glad it's working for you.

**Comment by phvel01** [comment]
Hello, hopefully this is the last time I have to re-open this ticket :) 

So I am still having issues installing the cni plugin.

This time I am sure I am doing it correctly.

I start by running: `helm pull istio-official/cni` of course after I have updated the repo to latest version.

I then un package the compressed file with `tar xvf <file_name>`

In the values file i then add my extra config like `profile: ambient` and setting the needed property for running in GKE.

When I then try to create the application within ArgoCD I get the following error:


Unable to create application: application spec for istio-cni is invalid: InvalidSpecError: Unable to generate manifests in management-system/managed-operators/helmcharts/istio/cni: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template istio-cni --namespace kube-system --kube-version 1.30 --values <path to cached source>/management-system/managed-operators/helmcharts/istio/cni/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: cni/templates/clusterrole.yaml:17:8: executing "cni/templates/clusterrole.yaml" at <eq (coalesce .Values.platform .Values.global.platform) "openshift">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

Here is the cart file:

```yaml
apiVersion: v2
appVersion: 1.24.1
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.24.1
```

And here is the values.yaml
```yaml
# "_internal_defaults_do_not_set" is a workaround for Helm limitations. Users should NOT set "._internal_defaults_do_not_set" explicitly, but rather directly set the fields internally.
# For instance, instead of `--set _internal_defaults_do_not_set.foo=bar``, just set `--set foo=bar`.
_internal_defaults_do_not_set:
  hub: ""
  tag: ""
  variant: ""
  image: install-cni
  pullPolicy: ""

  # Same as `global.logging.level`, but will override it if set
  logging:
    level: ""

  # Configuration file to insert istio-cni plugin configuration
  # by default this will be the first file found in the cni-conf-dir
  # Example
  # cniConfFileName: 10-calico.conflist

  # CNI bin and conf dir override settings
  # defaults:
  cniBinDir: "" # Auto-detected based on version; defaults to /opt/cni/bin.
  cniConfDir: /etc/cni/net.d
  cniConfFileName: ""
  # This directory must exist on the node, if it does not, consult your container runtime
  # documentation for the appropriate path.
  cniNetnsDir: # Defaults to '/var/run/netns', in minikube/docker/others can be '/var/run/docker/netns'.


  excludeNamespaces:
    - kube-system

  # Allows user to set custom affinity for the DaemonSet
  affinity: {}

  # Custom annotations on pod level, if you need them
  podAnnotations: {}

  # Deploy the config files as plugin chain (value "true") or as standalone files in the conf dir (value "false")?
  # Some k8s flavors (e.g. OpenShift) do not support the chain approach, set to false if this is the case
  chained: true

  # Custom configuration happens based on the CNI provider.
  # Possible values: "default", "multus"
  provider: "default"

  # Configure ambient settings
  ambient:
    # If enabled, ambient redirection will be enabled
    enabled: false
    # Set ambient config dir path: defaults to /etc/ambient-config
    configDir: ""
    # If enabled, and ambient is enabled, DNS redirection will be enabled
    dnsCapture: false
    # If enabled, and ambient is enabled, enables ipv6 support
    ipv6: true


  repair:
    enabled: true
    hub: ""
    tag: ""

    # Repair controller has 3 modes. Pick which one meets your use cases. Note only one may be used.
    # This defines the action the controller will take when a pod is detected as broken.

    # labelPods will label all pods with <brokenPodLabelKey>=<brokenPodLabelValue>.
    # This is only capable of identifying broken pods; the user is responsible for fixing them (generally, by deleting them).
    # Note this gives the DaemonSet a relatively high privilege, as modifying pod metadata/status can have wider impacts.
    labelPods: false
    # deletePods will delete any broken pod. These will then be rescheduled, hopefully onto a node that is fully ready.
    # Note this gives the DaemonSet a relatively high privilege, as it can delete any Pod.
    deletePods: false
    # repairPods will dynamically repair any broken pod by setting up the pod networking configuration even after it has started.
    # Note the pod will be crashlooping, so this may take a few minutes to become fully functional based on when the retry occurs.
    # This requires no RBAC privilege, but does require `securityContext.privileged/CAP_SYS_ADMIN`.
    repairPods: true

    initContainerName: "istio-validation"

    brokenPodLabelKey: "cni.istio.io/uninitialized"
    brokenPodLabelValue: "true"

  # Set to `type: RuntimeDefault` to use the default profile if available.
  seccompProfile: {}

  # SELinux options to set in the istio-cni-node pods. You may need to set this to `type: spc_t` for some platforms.
  seLinuxOptions: {}

  resources:
    requests:
      cpu: 100m
      memory: 100Mi

  resourceQuotas:
    enabled: false
    pods: 5000

  # The number of pods that can be unavailable during rolling update (see
  # `updateStrategy.rollingUpdate.maxUnavailable` here:
  # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec).
  # May be specified as a number of pods or as a percent of the total number
  # of pods at the start of the update.
  rollingMaxUnavailable: 1

  # Revision is set as 'version' label and part of the resource names when installing multiple control planes.
  revision: ""

  # For Helm compatibility.
  ownerName: ""

  global:
    # Default hub for Istio images.
    # Releases are published to docker hub under 'istio' project.
    # Dev builds from prow are on gcr.io
    hub: docker.io/istio

    # Default tag for Istio images.
    tag: 1.24.1

    # Variant of the image to use.
    # Currently supported are: [debug, distroless]
    variant: ""

    # Specify image pull policy if default behavior isn't desired.
    # Default behavior: latest images will be Always else IfNotPresent.
    imagePullPolicy: ""

    # change cni scope level to control logging out of istio-cni-node DaemonSet
    logging:
      level: info

    logAsJson: false

    # ImagePullSecrets for all ServiceAccount, list of secrets in the same namespace
    # to use for pulling any images in pods that reference this ServiceAccount.
    # For components that don't use ServiceAccounts (i.e. grafana, servicegraph, tracing)
    # ImagePullSecrets will be added to the corresponding Deployment(StatefulSet) objects.
    # Must be set for any cluster configured with private docker registry.
    imagePullSecrets: []
    # - private-registry-key

    # Default resources allocated
    defaultResources:
      requests:
        cpu: 100m
        memory: 100Mi

  # A `key: value` mapping of environment variables to add to the pod
  env: {}

profile: ambient
cni:
  cniBinDir: "/home/kubernetes/bin"
```
