### ISSUE TITLE
gateway: 0.8 httpbin sample task docs are not working with v1alpha3 https

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#5415]
I followed the [gateway docs](https://preliminary.istio.io/docs/tasks/traffic-management-v1alpha3/ingress.html#configuring-a-gateway) including setup tasks, and I get a 404 on http and a connection refused on https.

k8s: 1.9 in IBM Cloud
istio version: istio-0.8.0-pre20180421-09-15 

replication steps:

```
kubectl create ns istio-system

helm template --namespace=istio-system --set sidecar-injector.enabled=true install/kubernetes/helm/istio > sidecarinject.yaml

kubectl create -f sidecarinject.yaml

kubectl label namespace default istio-injection=enabled

kubectl create -f samples/httpbin/httpbin.yaml

 openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -subj "/CN=foo.bar.com"

cat <<EOF | kubectl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  servers:
  - port:
      number: 80
      name: http
  - port:
      number: 443
      name: https
    tls:
      mode: SIMPLE
      serverCertificate: /tmp/tls.crt
      privateKey: /tmp/tls.key
EOF

cat <<EOF | kubectl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  gateways:
  - httpbin-gateway
  http:
  - match:
      uri:
        prefix: /status
    route:
    - destination:
        port:
          number: 8000
        name: httpbin
  - match:
      uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        name: httpbin
EOF
```

```
istio-ingress              LoadBalancer   172.21.131.219   169.X.X.X   80:30999/TCP,443:30823/TCP      
```

```
curl -I http://169.X.X.X:30999/status/200
HTTP/1.1 404 Not Found
date: Fri, 04 May 2018 17:30:55 GMT
server: envoy
content-length: 0
```

```
curl -I -k https://169.X.X.X:30823/status/200
curl: (7) Failed to connect to 169.X.X.X port 30823: Connection refused
```

**Comment by cmluciano** [comment]
cc @GregHanson @frankbu for v1alpha3 verification

**Comment by linsun** [comment]
talked to @frankbu earlier today, the gateway sample is missing a required host field.  @cmluciano, can you try with that to see if it works, see example:  https://github.com/istio/istio/blob/release-0.8/samples/bookinfo/routing/bookinfo-gateway.yaml

**Comment by cmluciano** [comment]
This still does not seem to work, I tried with DAILY=release-0.8-20180425-19-12  too.

Here is the config 

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  servers:
  - port:
      number: 80
      name: http
    hosts:
    - "httpbin"
  - port: 
      number: 443
      name: https
    tls:
      mode: SIMPLE
      serverCertificate: /tmp/tls.crt
      privateKey: /tmp/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  gateways:
  - httpbin-gateway
  http:
  - match:
      uri:
        prefix: /status
    route:
    - destination:
        port:
          number: 8000
        name: httpbin
  - match:
      uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        name: httpbin
---
```

**Comment by ZackButcher** [comment]
You need a host on all servers, but only have it on the first. If you check Pilot logs you should see that the message failed validation.

Your gateway should look like:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  servers:
  - port:
      number: 80
      name: http
    hosts:
    - "httpbin"
  - port: 
      number: 443
      name: https
    hosts:
    - "httpbin"
    tls:
      mode: SIMPLE
      serverCertificate: /tmp/tls.crt
      privateKey: /tmp/tls.ke
```
(note the `hosts: - "httpbin"` in the `:443` server)

**Comment by frankbu** [comment]
Instructions in several v1alpha3 tasks are wrong. Fixes in https://github.com/istio/istio.github.io/pull/1247

**Comment by cmluciano** [comment]
Still no dice with updated hosts and passing the Host in a header explicitly.

```
Name:         httpbin-gateway
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"httpbin-gateway","namespace":"default"},"spec":{"ser...
API Version:  networking.istio.io/v1alpha3
Kind:         Gateway
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-05-04T20:03:57Z
  Generation:          0
  Resource Version:    11200
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/default/gateways/httpbin-gateway
  UID:                 475cd9b4-4fd6-11e8-875c-e23020bb4fed
Spec:
  Servers:
    Hosts:
      httpbin
    Port:
      Name:    http
      Number:  80
    Hosts:
      httpbin
    Port:
      Name:    https
      Number:  443
    Tls:
      Mode:                SIMPLE
      Private Key:         /tmp/tls.key
      Server Certificate:  /tmp/tls.crt
Events:                    <none>

```

```
curl -I -k  -H "Host: httpbin.default.svc.cluster.local" http://169.x.x.x:30792/status/200
HTTP/1.1 404 Not Found
date: Mon, 07 May 2018 15:21:54 GMT
server: envoy
content-length: 0
```

```
curl -I -k  -H "Host: httpbin.default.svc.cluster.local" https://169.x.x.x:30022/status/200
curl: (7) Failed to connect to 169.x.x.x port 30022: Connection refused
```

**Comment by cmluciano** [comment]
Updated to include selector and still not working. 

Gateway/VirtualService config
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.default.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  gateways:
  - httpbin-gateway
  http:
  - match:
      uri:
        prefix: /status
    route:
    - destination:
        port:
          number: 8000
        name: httpbin
  - match:
      uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
---
```

Pilot log reveals:
```
	warn	error translating object for schema model.ProtoSchema{Type:"virtual-service", Plural:"virtual-services", Group:"networking", Version:"v1alpha3", MessageName:"istio.networking.v1alpha3.VirtualService", Gogo:true, Validate:(func(proto.Message) error)(0x1087750)} : YAML decoding error: gateways:
- httpbin-gateway
hosts:
- httpbin
http:
- match:
    uri:
      prefix: /status
  route:
  - destination:
      name: httpbin
      port:
        number: 8000
- match:
    uri:
      prefix: /delay
  route:
  - destination:
      host: httpbin
      port:
        number: 8000
 json: cannot unmarshal object into Go value of type []json.RawMessage
```
