### ISSUE TITLE
No listener created for Gateway API UDPRoute

### ISSUE THREAD

**Issue by MiddleMan5** [istio/istio#54163]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to expose a UDPRoute using the istio gateway api and the routes are not attaching.

As per the documentation [here](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/): _"Istio supports the Kubernetes [Gateway API](https://istio.io/latest/blog/2024/gateway-mesh-ga/) and intends to make it the default API for traffic management"_

According to the gateway api sig documentation [here](https://gateway-api.sigs.k8s.io/implementations/) istio gateway api support is *GA*.

We already have TCPRoutes deployed and working in a very similar configuration.

Nowhere in the documentation or usage examples does it mention that udp is not supported, so I must assume that istio has support for these.

I'm not sure what I'm doing wrong or if there is a bug in the current version of istio (`1.20.0`) that I'm using, I'm not sure how to proceed.

Istiod Logs:
```
{"level":"warn","time":"2024-12-03T16:04:40.047323Z","msg":"gateway udp-service/udp-service-gateway-istio-autogenerated-k8s-gateway-udp-client:9999 listener missed network filter"}
{"level":"info","time":"2024-12-03T16:04:40.047337Z","msg":"gateway omitting listener \"0.0.0.0_9999\" due to: must have more than 0 chains in listener \"0.0.0.0_9999\""}
```

Gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: udp-service-gateway
  namespace: udp-service
  labels:
    istio.io/gateway-name: udp-service-gateway
  annotations:
    # For more information on azure loadbalancer annotations see: https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations
    networking.istio.io/service-type: LoadBalancer
    # Only expose the gateway to the internal load balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # Must disable health probes if using hostname matching
    service.beta.kubernetes.io/port_80_no_probe_rule: "true"
    service.beta.kubernetes.io/port_443_no_probe_rule: "true"
    service.beta.kubernetes.io/port_9999_no_probe_rule: "true"
spec:
  # Use the pre-defined istio gateway class
  gatewayClassName: istio
  listeners:
    - name: udp-client
      port: 9999
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: Same
```

UDPRoute:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: udp-customer
  namespace: udp-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "client.hsa-ground.udp-service.my.domain"
spec:
  parentRefs:
    - name: udp-service-gateway
      sectionName: udp-client
  rules:
    - backendRefs:
        - name: udp-service
          port: 9999
```

Gateway Status:
```yaml
Name:         udp-service-gateway
Namespace:    udp-service
Labels:       istio.io/gateway-name=udp-service-gateway
              kustomize.toolkit.fluxcd.io/name=udp-service
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  gateway.istio.io/controller-version: 5
              networking.istio.io/service-type: LoadBalancer
              service.beta.kubernetes.io/azure-load-balancer-internal: true
              service.beta.kubernetes.io/port_443_no_probe_rule: true
              service.beta.kubernetes.io/port_80_no_probe_rule: true
              service.beta.kubernetes.io/port_9999_no_probe_rule: true
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2024-12-04T00:33:38Z
  Generation:          1
  Resource Version:    2394317258
  UID:                 37fa9655-8ff6-43dc-8c2c-827d85b4afea
Spec:
  Gateway Class Name:  istio
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      udp-client
    Port:      9999
    Protocol:  UDP
Status:
  Addresses:
    Type:   IPAddress
    Value:  10.225.1.63
  Conditions:
    Last Transition Time:  2024-12-04T00:33:38Z
    Message:               Resource accepted
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2024-12-04T00:33:45Z
    Message:               Resource programmed, assigned to service(s) udp-service-gateway-istio.udp-service.svc.cluster.local:9999
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  0
    Conditions:
      Last Transition Time:  2024-12-04T00:33:38Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-12-04T00:33:38Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2024-12-04T00:33:38Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2024-12-04T00:33:38Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    udp-client
    Supported Kinds:
Events:  <none>
```

### Version

```Text
$ istioctl version:
client version: 1.20.3
control plane version: 1.20.0
data plane version: 1.20.0 (161 proxies)

$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.12
```
