### ISSUE TITLE
Lack of support for globs with file extension in AuthPolicy

### ISSUE THREAD

**Issue by kozjan** [istio/istio#54171]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I expected path template `/videos/{*}.m4s` to work in `paths` field in `AuthorizationPolicy`.
Instead I got an error:
```
failde to parse CRD: configuration is invalid: invalid policy httpbin-1.foo: invalid or unsupported path videos/{*}.m4s, found in Paths. Contains '{' or '}' beyond a supported path template
```

### Version

```Text
1.24.1
Tested it on current master version by modifying tests, after reading documentation and seeing discrepancy with Envoy docs.
```

### Additional Information

Path templating support was added in https://github.com/istio/istio/pull/50365.
I don't see anywhere in the discussion a mention of supporting globs with file extension, which is [supported by Envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/path/match/uri_template/v3/uri_template_match.proto.html):
```
/videos/*/*/*.m4s would match videos/123414/hls/1080p5000_00001.m4s
```
Is there any reason for this?

**Comment by howardjohn** [comment]
I believe the current implement is only allow globing of path segments (`foo/{*}/bar`) not a _part of_ a path segment

cc @jaellio

**Comment by kozjan** [comment]
Yes, in Envoy it works almost the same, with only difference being if it's the last path segment - in that case you can match glob with file extension.
Example configuration of envoy:
```
static_resources:

  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: rbac
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                      rules:
                        action: ALLOW
                        policies:
                          foo:
                            permissions:
                              - uri_template:
                                  name: envoy.path.match.uri_template.uri_template_matcher
                                  typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
                                    path_template: "/extension/*.js"
                            principals:
                              - any: true
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite_literal: www.envoyproxy.io
                            cluster: service_envoyproxy_io

  clusters:
    - name: service_envoyproxy_io
      type: LOGICAL_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: service_envoyproxy_io
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: www.envoyproxy.io
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: www.envoyproxy.io
```
In this case, `path_template: "/extension/*.js"` will match `/extension/file.js`, but not `/extension/file`.
My question is: was it a conscious decision and in Istio it's not supposed to work? Are you against it or is it ok to implement?
