### ISSUE TITLE
Support HTTPFaultInjection via GatewayAPI

### ISSUE THREAD

**Issue by jwestbury** [istio/istio#54196]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

The HTTPFaultInjection feature of VirtualService is not supported by GatewayAPI. Per [a comment from earlier this year](https://github.com/istio/istio/pull/47101#issuecomment-2136073948), there is no known plan to support this.

However, this makes fault injection and chaos engineering much more challenging when deploying Istio using the k8s GatewayAPI model.

**Describe alternatives you've considered**

Fault injection could theoretically be done at the Envoy layer, using [Envoy Filters](https://istio.io/latest/docs/reference/config/networking/envoy-filter/). However, the Istio documentation makes it clear that this route has significant drawbacks:

> Some aspects of this API are deeply tied to the internal implementation in Istio networking subsystem as well as Envoy’s XDS API. While the EnvoyFilter API by itself will maintain backward compatibility, any envoy configuration provided through this mechanism should be carefully monitored across Istio proxy version upgrades, to ensure that deprecated fields are removed and replaced appropriately.

There are other ways to inject faults by adding additional transparent proxy layers, but these introduce unnecessary complexity.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Fault injection is a critical part of modern infrastructure. My organization is currently working on rolling out Istio-based circuit breaking; fault injection would make it a breeze to validate the behavior we're trying to implement, but is not available when using Gateway API, so validation becomes a matter of manual testing, which is fraught with peril.

**Comment by howardjohn** [comment]
The best path forward for this would be to get this into the upstream API. Seems like they don't have any feature requests for this right now (https://github.com/kubernetes-sigs/gateway-api/issues?q=is%3Aissue+fault+is%3Aclosed), might be worth opening

**Comment by wulianglongrd** [comment]
cc @scriptkids

**Comment by jgournet** [comment]
Just chucking this for my future-self and anyone having the same issue: a nice workaround is to do the same via EnvoyFilter:
(this only works for sidecar istio - I haven't moved to ambient yet)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fault-injection-on-sidecar-inbound
  namespace: <your_app_namespace>
spec:
  workloadSelector:
    labels:
      <your_label>: <some_value>
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.fault
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
          delay:
            fixed_delay: 10s
            percentage:
              numerator: 100
              denominator: HUNDRED
```
