### ISSUE TITLE
istio letsencrypt cert-manager

### ISSUE THREAD

**Issue by Sophian-Mehboub** [istio/istio#5421]
Hello all,

When i execute this command 
kubectl logs cert-manager-cert-manager-9585579df-tnb86 -n kube-system 
I can see in the logs of cert-manager, i get this error :

I0504 19:18:00.688397       1 helpers.go:162] Found status change for Certificate "istio-ingress-certs" condition "Ready": "False" -> "False"; setting lastTransitionTime to 2018-05-04 19:18:00.688381872 +0000 UTC m=+165474.274591233
I0504 19:18:00.688424       1 sync.go:241] Error preparing issuer for certificate istio-system/istio-ingress-certs: http-01 self check failed for domain "test.example.org"
E0504 19:18:00.692368       1 sync.go:168] [istio-system/istio-ingress-certs] Error getting certificate 'istio-ingress-certs': secret "istio-ingress-certs" not found
E0504 19:18:00.692398       1 controller.go:186] certificates controller: Re-queuing item "istio-system/istio-ingress-certs" due to error processing: http-01 self check failed for domain "test.example.org"

here is my config :

```yaml
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: informatginternet@oxylane.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: informatginternet@oxylane.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-ingress-certs
  namespace: istio-system
spec:
  secretName: istio-ingress-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: test.example.org
  dnsNames:
  - test.example.org
  acme:
    config:
    - http01:
        ingressClass: none
      domains:
      - test.example.org

---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-ingress-www
  namespace: istio-system
  annotations:
    auth.istio.io/8089: NONE
spec:
  ports:
  - port: 8089
    name: http-certingr
  selector:
    certmanager.k8s.io/domain: test.example.org

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
  name: istio-ingress-certs-mgr
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
      - path: /.well-known/acme-challenge/.*
        backend:
          serviceName: cert-manager-ingress-www
          servicePort: http-certingr
    host: test.example.org
`
````

I put test.example.org for the example but we use another fqdn
and the fqdn belongs to us and the dns resolution of this fqdn works very well everywhere.

I get also the error 503 on .well-known/acme-challenge/ after th kubectl apply

curl -v http://test.example.org/.well-known/acme-challenge/
* About to connect() to test.example.org port 80 (#0)
*   Trying 192.168.179.210...
* Connected to test.example.org (192.168.179.210) port 80 (#0)
> GET /.well-known/acme-challenge/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: test.example.org
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Fri, 04 May 2018 19:43:32 GMT
< server: envoy
< 
* Connection #0 to host test.example.org left intact
no healthy upstream
