### ISSUE TITLE
[Help] Istio EnvoyFilter limited service connections

### ISSUE THREAD

**Issue by cyberaa** [istio/istio#54238]
Hey guys,

I need some help to understand what happened. I had a service running the following Envoy Filter for **TLS termination**:

```
apiVersion: [networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)
kind: EnvoyFilter
metadata:
  name: myservice
spec:
  workloadSelector:
    labels:
      app: myservice
  configPatches:
    - applyTo: LISTENER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 4444
      patch:
        operation: ADD
        value:
          name: "myservice_34443"
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 34443
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": [type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager](http://type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager)
                    stat_prefix: "myservice_tls"
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          '@type': [type.googleapis.com/envoy.extensions.filters.http.router.v3.Router](http://type.googleapis.com/envoy.extensions.filters.http.router.v3.Router)
                    route_config:
                      name: tls_route
                      virtual_hosts:
                        - name: backend
                          domains:
                          - "*"
                          routes:
                            - name: default
                              match:
                                prefix: /
                              route:
                                cluster: inbound|4444|myservice.default.svc.cluster.local
                                upgrade_configs:
                                  - enabled: true
                                    upgrade_type: websocket
              transportSocket:
                name: envoy.transport_sockets.tls
                typedConfig:
                  '@type': [type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext](http://type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext)
                  commonTlsContext:
                    alpnProtocols:
                    - istio-peer-exchange
                    - h2
                    - http/1.1
                    combinedValidationContext:
                      defaultValidationContext: {}
                      validationContextSdsSecretConfig:
                        name: ROOTCA
                        sdsConfig:
                          apiConfigSource:
                            apiType: GRPC
                            grpcServices:
                            - envoyGrpc:
                                clusterName: sds-grpc
                            transportApiVersion: V3
                          initialFetchTimeout: 0s
                          resourceApiVersion: V3
                    tlsCertificateSdsSecretConfigs:
                    - name: default
                      sdsConfig:
                        apiConfigSource:
                          apiType: GRPC
                          grpcServices:
                          - envoyGrpc:
                              clusterName: sds-grpc
                          transportApiVersion: V3
                        initialFetchTimeout: 0s
                        resourceApiVersion: V3
```

This filter worked flawlessly.

When I added the following **Envoy Filter**:

```
apiVersion: [networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)
kind: EnvoyFilter
metadata:
  name: myservice-static-cluster
spec:
  workloadSelector:
    labels:
      app: myservice
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          portNumber: 4444
        context: SIDECAR_INBOUND
      patch:
        operation: ADD
        value:
          load_assignment:
            cluster_name: inbound|4444||myservice.default.svc.cluster.local
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 4444
          name: inbound|4444||myservice.default.svc.cluster.local
          type: STATIC
---
```

It capped the number of connections that the service could handle to approximately 50%. A config dump shows no change to `max_connections` allowed.

![image](https://github.com/user-attachments/assets/26a69cb9-289a-4c34-acbe-e1e2eafceb50)

Can you help me understand why?

**Service:**
* Service Type: Cluster IP
* Only the envoy filter is defined in this service.

**Specs**

* **Istio** `v1.20.5` - side car mode
* **EKS** `v1.26`
* **CNI**: AWS VPC CNI
