### ISSUE TITLE
Imbalanced traffic routing

### ISSUE THREAD

**Issue by ec209** [istio/istio#54246]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi, 
We have our backend pods running behind an istio ingress gateway. 
Currently, we are facing a couple of pods serving most of the traffic during the spike. This leads to a latency spike. 
![Screenshot 2024-12-09 at 2 24 59 PM](https://github.com/user-attachments/assets/f36a6380-126e-476a-a47c-c0da23b0db39)
As you can see in this graph, you could see only 2-3 pods are receiving most of the traffics while we have 10+ pods in the pool. 

This is the destinationRule:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ...
  namespace: ...
spec:
  host: ...
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 3m
      consecutive5xxErrors: 500
      interval: 1m
      maxEjectionPercent: 50
 ```
This destination rule has been patched a few times as this issue is recurring for us. 

First, We have Istio ingress Gateway controller per AZ.
Second, The load balancing algorithm has been updated from `LEAST REQUEST` to `ROUND_ROBIN`
Third, The `localityLbSetting` is disabled
However, The traffic is still imbalanced per pod level.
 
 On a side note our backend pods are powered by HPA and Karpenter if anybody uses these two and istio having the same issue as us. Anti-affinity rule(preferred) is applied as well to spread the pod across AZs and nodes

 
 

### Version

```Text
istioctl version
client version: 1.24.1
control plane version: 1.19.5
data plane version: 1.19.5 (69 proxies)

kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.29.10-eks-7f9249a
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1

helm version --short
v3.9.3+g414ff28
```
