### ISSUE TITLE
accessLogging filter and match mode at same time

### ISSUE THREAD

**Issue by ivashchenkoLV** [istio/istio#54268]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I like to exclude from the proxy logs all requests originating from the pod, as well as all requests from Prometheus to pod.
I use Telemetry API to set up logs. Unfortunately only one rule always works. 
My yaml based on documentation:

```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: exclude-outgoing
  namespace: default
spec:
  selector:
    matchLabels:
      app: manager
  accessLogging:
  - providers:
    - name: stdout-json
    match:
      mode: CLIENT
    disabled: true
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: exclude-prometheus
  namespace: default
spec:
  selector:
    matchLabels:
      app: manager
  accessLogging:
  - providers:
    - name: stdout-json
    filter:
      expression: '!has(request.useragent) || !(request.useragent.startsWith("Prometheus"))'
```

### Version

```Text
client version: 1.21.2
control plane version: 1.24.0
data plane version: 1.24.0 (15 proxies)
```

**Comment by zirain** [comment]
accroding https://istio.io/latest/docs/tasks/observability/telemetry/#scope-inheritance-and-overrides
if you merge into one resource, it will be fine.

**Comment by ivashchenkoLV** [comment]
Thanks for the quick reply! After applying the combined manifest, no logs are written to stdout.

**Comment by howardjohn** [comment]
`disabled: true` means it will disable for everything. You need 1 Telemetry object with 2 clauses:

```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: exclude-outgoing
  namespace: default
spec:
  selector:
    matchLabels:
      app: echo
  accessLogging:
  - providers:
    - name: envoy
    match:
      mode: CLIENT
    disabled: true
  - providers:
    - name: envoy
    match:
      mode: SERVER
    filter:
      expression: '!has(request.useragent) || !(request.useragent.startsWith("Prometheus"))'
```
