### ISSUE TITLE
proxyless gRPC: istiod pushes unexpected RDS  to sidecar

### ISSUE THREAD

**Issue by kytool** [istio/istio#54270]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

client inject sidecar，
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grpc-server
  namespace: myns
spec:
  hosts:
    - grpc-server.myns.svc.cluster.local
  http:
    - name: aaa
      route:
        - destination:
            host: grpc-server.myns.svc.cluster.local
          weight: 50
        - destination:
            host: grpc-server.myns-blue.svc.cluster.local
          weight: 50
```
```yaml
kind: Service
apiVersion: v1
metadata:
  name: grpc-server
  namespace: myns
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: grpc2
      protocol: TCP
      port: 1234
      targetPort: 9090
  selector:
    app: grpc-server
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: grpc-server
  namespace: myns-blue
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: grpc2
      protocol: TCP
      port: 1234
      targetPort: 9090
  selector:
    app: grpc-server
  type: ClusterIP
```
1. when  client call `xds:///grpc-server.myns.svc.cluster.local:9090`
 istiod log output: 
info ads RDS: PUSH for node:grpc-client-5578bb6d54-d254g.myns resources:1 size:52.1kB
2. when  client call `xds:///grpc-server.myns.svc.cluster.local:1234`
 istiod log output: 
info ads RDS: PUSH for node:grpc-client-5578bb6d54-d254g.myns resources:1 size:1.2kB
Notes：The cluster has many services at port 9090，two services at port 1234
I see the source code RDS pushes the same port only
 

### Version

```Text
$ istioctl version
client version: 1.13.7
control plane version: 1.13
data plane version: 1.13.7 (3 proxies)
$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.20.7
```
