### ISSUE TITLE
Istio Ambient - DENY L7 AuthorizationPolicy not working

### ISSUE THREAD

**Issue by smilingbullet** [istio/istio#54275]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to use ambient mode on an EKS cluster.

I use IstioOperator to install Istio 1.24.1 with ambient profile and deploy an ingressgateway which creates a NLB on AWS. 

I have a simple application deployed on "foo" namespace. To access this application I have created a gateway and a virtualService

```yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: myapp-gtw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - myapp.internal.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
  - hosts:
    - myapp.internal.com
    port:
      name: https
      number: 443
      protocol: HTTP
    tls:
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: myapp-vs
  namespace: foo
spec:
  gateways:
  - istio-system/myapp-gtw
  hosts:
  - myapp.internal.com
  http:
  - headers:
      request:
        set:
          x-forwarded-port: "443"
          x-forwarded-proto: https
      response:
        add:
          Content-Security-Policy: upgrade-insecure-requests
          Permissions-Policy: accelerometer=(), ambient-light-sensor=(), autoplay=(),
            camera=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(),  magnetometer=(),
            microphone=(), midi=(), payment=(), picture-in-picture=(), speaker=(),
            usb=(), vr=(), sync-xhr=()
          Referrer-Policy: strict-origin-when-cross-origin
          Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
        remove:
        - X-Powered-By
        - Server
        - x-envoy-upstream-service-time
        set:
          X-Content-Type-Options: nosniff
          X-Frame-Options: SAMEORIGIN
    match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: myapp
        port:
          number: 8080
```

I use external-dns to declare automatically my host into AWS Route53 records and attach it to my nlb.

At this point, everything is fine and my application is accessible.

I wanted to test if I can enforce DENY policies, therefore, I deployed a waypoint "my-waypoint" in foo namespace, created a simple AuthorizationPolicy that denies access to "/auth" path and attached to my waypoint :
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-auth-path
  namespace: foo
spec:
  action: DENY
  rules:
  - to:
    - operation:
        paths:
        - /auth/
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: my-waypoint
status:
  conditions:
  - lastTransitionTime: "2024-12-11T14:09:28.697706629Z"
    message: bound to foo/my-waypoint
    reason: Accepted
    status: "True"
    type: WaypointAccepted
```
When I access myapp using "myapp.internal.com"I,  should get an 403 error "RBAC: Access denied" but I can still reach it.

Suprisingly, when I try to access it from another pod with curl, I do get blocked:

```shell
~ $ curl "http://myapp.foo.svc.cluster.local:8080/auth/"
RBAC: access denied
```

Even more surprising, if I change foo namespace to sidecar mode "label: istio-injection: enabled", restart myapp then access it by host, I get blocked as expected.

After numerous researches, I stumbled on this issue #53723 which looks similar to mine and PR #52985 which may help resolving it but since it is not documented yet, I could not confirm.

Any help would be appreciated.

### Version

```Text
➜  ~ istioctl version
client version: 1.24.1
control plane version: 1.24.1
data plane version: 1.24.1 (54 proxies)

➜  ~ kubectl version
Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.6-eks-7f9249a
```
