### ISSUE TITLE
Deprecation warnings for downstream_connections

### ISSUE THREAD

**Issue by RafSad** [istio/istio#54309]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

QQ, I get warnings when I first start the istio-proxy in the form of a sidecar

`2024-12-10T09:20:57.860318Z warning envoy main external/envoy/source/server/server.cc:936 There is no configured limit to the number of allowed active downstream connections. Configure a limit in envoy.resource_monitors.downstream_connections resource monitor. thread=21

2024-12-10T09:20:57.863296Z warning envoy main external/envoy/source/server/server.cc:843 Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to envoy.resource_monitors.downstream_connections instead.This runtime key will be removed in future. thread=21`

Please send me an example of EnvoyFilter to resolve this warnings
Previously attempted in https://github.com/istio/istio/pull/47474, but it was alpha at the time.

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-cluster
  namespace: istio-ingress
spec:
  workloadSelector:
    labels:
      security.istio.io/tlsMode: istio
  configPatches:
    - applyTo: BOOTSTRAP
      patch:
        operation: MERGE
        value:
          resource_monitors:
            - name: envoy.resource_monitors.global_downstream_max_connections
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
                max_active_downstream_connections: 10000
```
```
k apply -f envoy-filter.yaml
Warning: EnvoyFilter exposes internal implementation details that may change at any time. Prefer other APIs if possible, and exercise extreme caution, especially around upgrades.
Warning: Envoy filter: unknown field "resource_monitors" in envoy.config.bootstrap.v3.Bootstrap
envoyfilter.networking.istio.io/envoy-filter-cluster configured
```

**But in documentation:**
**The reboot manager is configured in the Bootstrap reboot_manager field, in which, as I understand it, you need to add the resource monitors:**
https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#limiting-active-connections

**Maybe I need to use this field for the resource monitors**
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto#envoy-v3-api-field-extensions-resource-monitors-downstream-connections-v3-downstreamconnectionsconfig-max-active-downstream-connections

**BOOTSTRAP | DEPRECATED. Applies the patch to bootstrap configuration:**
https://istio.io/latest/docs/reference/config/networking/envoy-filter/

### Version

```Text
1.23.1
```
