### ISSUE TITLE
Gateway API - percent based request mirroring - Istio ignores fraction.denominator

### ISSUE THREAD

**Issue by LiorLieberman** [istio/istio#54357]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When applying an httproute with requestMirror filter and `fraction` it ignores the specified denominator and set it to "MILLION"

Step to reproduce: 

Apply the following gateway:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: same-namespace
  namespace: gateway-conformance-infra
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
```

Apply the following httproute:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: request-percentage-mirror
  namespace: gateway-conformance-infra
spec:
  parentRefs:
  - name: same-namespace
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /percent-mirror
    filters:
    - type: RequestMirror
      requestMirror:
        backendRef:
          name: infra-backend-v2
          namespace: gateway-conformance-infra
          port: 8080
        percent: 20
    backendRefs:
    - name: infra-backend-v1
      port: 8080
      namespace: gateway-conformance-infra
  - matches:
    - path:
        type: PathPrefix
        value: /percent-mirror-fraction
    filters:
    - type: RequestMirror
      requestMirror:
        backendRef:
          name: infra-backend-v2
          namespace: gateway-conformance-infra
          port: 8080
        fraction:
          numerator: 25
          denominator: 50
    backendRefs:
    - name: infra-backend-v1
      port: 8080
      namespace: gateway-conformance-infra
```

run `istioctl proxy-config routes same-namespace-istio-7c9b587845-kqdnn.gateway-conformance-infra -o json` (replace with your same-namespace gateway pod name )

See that the fraction for the `/percent-mirror-fraction` route has a denominator of MILLION and not what you configured.

### Version

```Text
client version: 1.24.1
control plane version: 1.24.1
data plane version: 1.24.1 (11 proxies)
```
