### ISSUE TITLE
Istio - SPIRE : File path based Gateway TLS setting is not working when using SPIRE as workload identity issuer

### ISSUE THREAD

**Issue by sridharjprakasam** [istio/istio#54365]
**Issue Description**

When SPIRE is configured to provide workload identity it replaces the default sds-cluster. However for ingress gateway, the source of the TLS certs is also moved to sds-cluster. The default SDS client, when SPIRE workload api socket is not mount, understand the specific resource name file-cert:<key>~<cert>. However, once it is replaced by SPIRE, the above resource name is passed onto the spire-agent, which is not able to resolve it.

This breaks the file based TLS SIMPLE mode configuration when SPIRE is the workload identity issuer.

Gateway TLS
```
 tls:
        mode: SIMPLE
        privateKey: /etc/ingress-certs/tls.key
        serverCertificate: /etc/ingress-certs/tls.crt
```

Envoy Config Dump - Downstream TLS context
```
"tls_certificate_sds_secret_configs": [
             {
              "name": "file-cert:/etc/ingress-certs/tls.crt~/etc/ingress-certs/tls.key",
              "sds_config": {
               "api_config_source": {
                "api_type": "GRPC",
                "grpc_services": [
                 {
                  "envoy_grpc": {
                   "cluster_name": "sds-grpc"
                  }
                 }
                ],
                "set_node_on_first_message_only": true,
                "transport_api_version": "V3"
               },
               "resource_api_version": "V3"
              }
             }
            ]
```

Error in ingress gateway logs, istio tries to make use of spire agent socket to fetch the file-cert based certificate

```
warning envoy config external/envoy/source/common/config/grpc_stream.h:153      StreamSecrets gRPC config stream to sds-grpc closed: 3, workload is not authorized for the requested identities ["file-cert:/etc/ingress-certs/tls.crt~/etc/ingress-certs/tls.key"]      thread=18
```

Using EnvoyFilter to patch the downstream TLS context to use a simple filename based TLS context doesn't remove the `tls_certificate_sds_secret_configs`, instead adds `tls_certificates {}` along with it
Giving an error **SDS and non-SDS TLS certificates may not be mixed in server contexts**

```
...
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: GATEWAY
        listener:
          name: "0.0.0.0_8443"
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificate_sds_secret_configs: []
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/ingress-certs/tls.crt
                    private_key:
                      filename: /etc/ingress-certs/tls.key
```

```
"transport_socket": {
                    "name": "envoy.transport_sockets.tls",
                    "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
                        "common_tls_context": {
                            "tls_certificates": [
                                {
                                    "certificate_chain": {
                                        "filename": "/etc/ingress-certs/tls.crt"
                                    },
                                    "private_key": {
                                        "filename": "[redacted]"
                                    }
                                }
                            ],
                            "alpn_protocols": [
                                "h2",
                                "http/1.1"
                            ],
                            "tls_certificate_sds_secret_configs": [
                                {
                                    "name": "file-cert:/etc/ingress-certs/tls.crt~/etc/ingress-certs/tls.key",
                                    "sds_config": {
                                        "api_config_source": {
                                            "api_type": "GRPC",
                                            "grpc_services": [
                                                {
                                                    "envoy_grpc": {
                                                        "cluster_name": "sds-grpc"
                                                    }
                                                }
                                            ],
                                            "set_node_on_first_message_only": true,
                                            "transport_api_version": "V3"
                                        },
                                        "resource_api_version": "V3"
                                    }
                                }
                            ]
                        },
                        "require_client_certificate": false
                    }
                }
            }
        ],
        "listener_filters": [
            {
                "name": "envoy.filters.listener.tls_inspector",
                "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
                }
            }
        ],
        "socket_options": [
            {
                "level": "1",
                "name": "9",
                "int_value": "1",
                "state": "STATE_BOUND"
            },
            {
                "level": "6",
                "name": "4",
                "int_value": "180",
                "state": "STATE_BOUND"
            },
            {
                "level": "6",
                "name": "5",
                "int_value": "180",
                "state": "STATE_BOUND"
            }
        ],
        "listener_filters_timeout": "0s",
        "traffic_direction": "OUTBOUND"
    },
    "last_update_attempt": "2024-12-16T06:44:09.425Z",
    "details": "SDS and non-SDS TLS certificates may not be mixed in server contexts"
}
```

Based on the comment in the issue

https://github.com/istio/istio/issues/47481#issuecomment-2136281410

I even tried the below

1. Istio ingress gateway should have the spire agent socket mounted on var/run/secrets/credential-uds/socket so that outbound traffic from gateway uses spire issued svid -- ( using credential-uds )
2. The file based certificates for inbound tls termination at gateway will use the regular istio's well known socket var/run/secrets/workload-spiffe-uds/socket -- ( using istio-sds )

**I tried this out and this completely removes SPIRE out of mesh and serves gateway SVID signed by Istio CA**

Is there a known workaround to overcome this. This stands a blocker in using gateway certificates or site specific certificates that are provider by a different issuer with downstream TLS context when spire is integrated and uses the well known `var/run/secrets/workload-spiffe-uds/socket `socket for serving workload identities.
