### ISSUE TITLE
(Mac OS X only) build process issue: missing version in 0.2.0 release artefact

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#544]
I downloaded the test 0.2.0 (mac) tgz:

ldemailly-macbookpro:istio-0.2.0 ldemailly$ bin/istioctl version
Version: 
GitRevision: 
GitBranch: 
User: @
GolangVersion: go1.8.3

looks like something is missing somewhere ?

**Comment by ldemailly** [comment]
same with kube-inject (which is worse) 
```
        image: 'docker.io/istio/proxy_debug:'
        image: 'docker.io/istio/proxy_init:'
```

**Comment by ldemailly** [comment]
linux version has it so seems to be mac only issue:
```
/istio-0.2.0# bin/istioctl version
Version: 0.2.0
GitRevision: a026827
GitBranch: master
User: jenkins@ubuntu-16-04-build-2523a381b28e60
GolangVersion: go1.8.3
```
```
- context:
    cluster: gke_ldemailly-gcp-1_us-west1-b_cluster-1
    user: gke_ldemailly-gcp-1_us-west1-b_cluster-1
  name: gke_ldemailly-gcp-1_us-west1-b_cluster-1
```
