### ISSUE TITLE
default virtual service route doesn't work

### ISSUE THREAD

**Issue by linsun** [istio/istio#5446]
I have a simple virtual service
```
$ cat test-gateway.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: guestbook-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook
spec:
  hosts:
  - "*"
  gateways:
  - guestbook-gateway
  http:
  - match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: helloworld-service 
        port:
          number: 8080
    route:
    - destination:
        host: guestbook-ui
        port:
          number: 80
```
When this is deployed, one of the destination is lost so my app doesn't work any more.

```
$ kubectl describe virtualservice guestbook
Name:         guestbook
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  networking.istio.io/v1alpha3
Kind:         VirtualService
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-05-07T18:17:36Z
  Resource Version:    5468546
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/guestbook
  UID:                 eb672524-5222-11e8-9658-c6334e2c822f
Spec:
  Gateways:
    guestbook-gateway
  Hosts:
    *
  Http:
    Match:
      Uri:
        Prefix:  /hello
    Route:
      Destination:
        Host:  guestbook-ui
        Port:
          Number:  80
Events:            <none>
```

This works fine:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook
spec:
  hosts:
  - "*"
  gateways:
  - guestbook-gateway
  http:
  - match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: helloworld-service 
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: guestbook-ui
        port:
          number: 80
```
