### ISSUE TITLE
[distributed tracing] Use the pod annotation overwite global default sampling not working... 

### ISSUE THREAD

**Issue by dellnoantechnp** [istio/istio#54472]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Pod annotation override `tarce.sampling` not working.

1. The global sampling percentage is  30%.
![image](https://github.com/user-attachments/assets/9b143168-5b19-487b-a7e9-5bd6b5eadb0c)

I call the `user` app api through the `ingressGateway.virtualservice`, traced sample is `30%`, it's correct.

2. set pod annotation
I use the pod annotation to config `proxy.istio.io/config`  setting `sampling` up to 100%
follow the document page [https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/](https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/)
```yaml
apiVersion: v1                                                                                         
kind: Pod                                                                                              
metadata:                                                                                              
  annotations:                                                                                         
    cni.projectcalico.org/containerID: ecb452fd17c1992e9691ffe19c4826124d02ed62ea3b585c91d137adf0243529
    cni.projectcalico.org/podIP: 172.25.71.101/32                                                      
    cni.projectcalico.org/podIPs: 172.25.71.101/32                                                     
    istio.io/rev: default                                                                              
    kubectl.kubernetes.io/default-container: user                                                      
    kubectl.kubernetes.io/default-logs-container: user                                                 
    kubectl.kubernetes.io/restartedAt: "2023-10-10T11:28:10+08:00"                                     
    prometheus.io/path: /stats/prometheus                                                              
    prometheus.io/port: "15020"                                                                        
    prometheus.io/scrape: "true"                                                                       
    proxy.istio.io/config: |                                                                           
      tracing:                                                                                         
        sampling: 100                                      <---- sampling percent 100%
        custom_tags:                                                                                   
          my_tag_header:                                 <---- custom tag  foo22: bar22
            header:                                                                                    
              foo22: bar22                                                                             
    sidecar.istio.io/inject: "true"                    <---- enable sidecar inject                                            
```

But, I call the app `pod_IP` or `Service_IP` by pass the `ingressgateway` parent sample 30%.
I think my pod annotation `proxy.istio.io/config`  `tracing.sampling: 100` will override global settings, actually not. 

I also receive 30% sampled trace,  Why ?
![QQ_1735119277719](https://github.com/user-attachments/assets/ca35ebf5-c325-4cc2-8aa2-c444cf60555d)

Didn't have `foo22: bar22` trace.

we look around the issue list, find a few about `trace sampling annotation` keywords,  I see from 2021 years or istio v1.9.2 to now , some people have same problem.  what happend ??

### Version

```Text
>_ istioctl version                 
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.23.2 (14 proxies), 1.24.2 (5 proxies)
```

**Comment by zirain** [comment]
And while I don't recommend it, but I double check that, it worked as excepted.
```console
istioctl pc l -n sidecar httpbin-79875c6f45-nj5g5 --port 8000 -oyaml | grep randomSampling -A2
          randomSampling:
            value: 100
        upgradeConfigs:

```

**Comment by dellnoantechnp** [comment]
emm .... 

```yaml
        tracing:
          clientSampling:
            value: 100
          customTags:
          - literal:
              value: bar
            tag: foo
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_effective_policy_id
            tag: istio.authorization.dry_run.allow_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_engine_result
            tag: istio.authorization.dry_run.allow_policy.result
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_effective_policy_id
            tag: istio.authorization.dry_run.deny_policy.name
          - metadata:
              kind:
                - key: istio_dry_run_deny_shadow_effective_policy_id
            tag: istio.authorization.dry_run.deny_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_engine_result
            tag: istio.authorization.dry_run.deny_policy.result
          - literal:
              value: v1
            tag: istio.canonical_revision
          - literal:
              value: user
            tag: istio.canonical_service
          - literal:
              value: Kubernetes
            tag: istio.cluster_id
          - literal:
              value: cluster.local
            tag: istio.mesh_id
          - literal:
              value: dev
            tag: istio.namespace
          overallSampling:
            value: 100
          provider:
            name: envoy.tracers.opentelemetry
            typedConfig:
              '@type': type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
              grpcService:
                envoyGrpc:
                  authority: opentelemetry-collector.open-telemetry.svc.cluster.local
                  clusterName: outbound|4317||opentelemetry-collector.open-telemetry.svc.cluster.local
              resourceDetectors:
              - name: envoy.tracers.opentelemetry.resource_detectors.environment
                typedConfig:
                  '@type': type.googleapis.com/envoy.extensions.tracers.opentelemetry.resource_detectors.v3.EnvironmentResourceDetectorConfig
              serviceName: user.dev
          randomSampling:
            value: 30                <----- ???
        upgradeConfigs:
        - upgradeType: websocket
        useRemoteAddress: false
    transportSocketConnectTimeout: 15s
```

we are different.

**Comment by zirain** [comment]
> The global sampling percentage is 30%.

Telemetry API take first.

Telemetry API support different scopes, see https://istio.io/latest/docs/tasks/observability/telemetry/#scope-inheritance-and-overrides.

e.g.
```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: workload-override
  namespace: myapp
spec:
  selector:
    matchLabels:
      service.istio.io/canonical-name: frontend
  tracing:
  - disableSpanReporting: true
```
