### ISSUE TITLE
503 errors after WASM crash

### ISSUE THREAD

**Issue by skarasev** [istio/istio#54490]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Our setup is bare-metal cluster with Istio Gateway deployed on multiple nodes by a DaemonSet behind L4 HaProxy with proxy-protocol enabled. The pods have no limits for CPU and RAM usage. We have Telemetry and WasmPlugin configured to collect path-based metrics.
For adding _url_path_ label to metrics we use the example from the docs:
```
 - match:
   metric: REQUEST_DURATION
   mode: CLIENT
   tagOverrides:
   request_method:
   value: request.method
   request_operation:
   value: istio_operationId
 - match:
   metric: REQUEST_COUNT
   mode: CLIENT
   tagOverrides:
   request_method:
   value: request.method
   request_operation:
   value: istio_operationId
```
For the WasmPlugin we also use the docs example, although we have around 1k of routes distributed across several manifests. In general they have such format:
```
- condition: request.url_path.matches('^/api/users/[a-zA-Z0-9-]+$') && request.method == 'GET'
  value: /api/users/[a-zA-Z0-9-]+
```

After switching our traffic(~5k RPS) entrypoint from Ingress to Istio everything was working fine for a few hours then some requests started returning 503 errors with the following descriptions:
_http2.remote_reset, downstream_remote_disconnect, wasm_fail_stream_

Investigation showed the errors were occurring only one pod, and they were preceded by the following error message:`error envoy wasm external/envoy/source/extensions/common/wasm/wasm_vm.cc:38 Function: proxy_on_context_create failed: Uncaught RuntimeError: unavailable thread=141`.
As I understand, the WASM VM for some reason failed and this caused a momentarily spike in _wasm_fail_stream_ errors. But I am clueless on why it affects later requests.

Over time the same behavior was observed on all gateway pods. The strange part is only ~2% of the traffic of the pod was affected by those errors, the rest were processed fine. We have not found anything unusual in this 2% of requests - the same exact requests were handled fine a second later by the same exact pod.
For a temporary fix the problematic pod had to be restarted manually as _15021/healthz/ready_ showed `200 OK` but in a few hours the problem appears again. 
After complete removal of all WasmPlugin manifest from cluster the gateway is stable.

For now I see two issues:
1. Unclear reason for the WASM VM failures.
2. WASM VM crash causes disconnects for later requests for some reason. Either the container should not be considered healthy after such an event or it has to be ensured the restart of VM has no lingering effect on the request processing.

### Version

```Text
Istio version: 1.22.0
Helm chart: 1.22.0
OS Version: Ubuntu 20.04.6
```
