### ISSUE TITLE
Ambient conflicting with Cilium (AWS VPC CNI Chaining)

### ISSUE THREAD

**Issue by alexandermarston** [istio/istio#54522]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When attempting to bootstrap Ambient Mesh, we noticed that our `ztunnel` pods were not coming up healthy when a new node was launched and we observed the following in the logs:

```
2025-01-02T15:31:33.565746Z	warn	xds::client:xds{id=31}	XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012/: status: Unknown, message: "client error (Connect)", source: dns error: failed to lookup address information: Temporary failure in name resolution (hint: is the DNS server reachable?), retrying in 15s
```

In our setup, we are running Istio (1.24.2) along with Cilium (1.16.5). Cilium is configured to be chained with AWS VPC CNI.

Cilium Values:

```yaml
values:
  kubeProxyReplacement: true

  k8sServiceHost: "${kubernetes_api}"
  k8sServicePort: 443

  policyAuditMode: false
  policyEnforcementMode: "default"

  # required for AWS VPC CNI & Istio CNI chaining
  cni:
    chainingMode: aws-cni
    exclusive: false

  # required for AWS VPC CNI chaining
  enableIPv4Masquerade: false

  # required for AWS VPC CNI chaining
  routingMode: native

  # required for AWS VPC CNI chaining
  endpointRoutes:
    enabled: true

  socketLB:
    hostNamespaceOnly: true

  loadBalancer:
    algorithm: maglev
    serviceTopology: true
```

It looks like ztunnel is starting up and using the aws-cni CNI before Cilium has come up properly. If I manually delete the failing `ztunnel` pod, it comes up fine as Cilium would have initialised by then.

ref: https://istio.slack.com/archives/C041EQL1XMY/p1735824700514859

### Version

```Text
➜  ~ istioctl version
client version: 1.23.0
control plane version: 1.24.2
data plane version: 1.24.2 (3 proxies)

➜  ~ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.3-eks-56e63d8

➜  ~ helm version
version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"dirty", GoVersion:"go1.23.3"}
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
