### ISSUE TITLE
500 NC cluster_not_found with ExternalName Service

### ISSUE THREAD

**Issue by hmoazzem** [istio/istio#54533]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I want to forward incoming traffic to Istio proxy (of Kubernetes Gateway API) to a workload running outside Kubernetes cluster.

```mermaid
graph TD
    subgraph internet
        direction TB
        
        clients
    end

    subgraph istio-pod
        direction TB
        
        istio_proxy_container["istio-proxy (10.0.2.1/24)"]
        wireguard_container["wireguard (10.0.2.1/24)"]
    end

    subgraph ext-workload
        direction TB
        
        ext_workload["ext-workload (10.0.2.2/24)"]
    end
    internet --> istio-pod --> ext_workload
```

I've almost done it; both `curl EXT_WORKLOAD_IP:PORT` and `curl K8S_SVC_EXTERNAL_NAME:PORT` from inside the Istio pod return 200.

```sh
kubectl -n istio-system exec deploy/istio-default-istio -c istio-proxy -- curl -so /dev/null -w "%{http_code}" 10.0.2.2:8080
kubectl -n istio-system exec deploy/istio-default-istio -c istio-proxy -- curl -so /dev/null -w "%{http_code}" wg-proxy-ext:8080
```

But

```sh
curl http://example.test.vpn --resolve example.test.vpn:80:ISTIO_PROXY_LOAD_BALANCER_IP -so /dev/null -w "%{http_code}"
```

returns 500. And `istio-proxy` logs:

```sh
[2025-01-02T21:54:23.954Z] "GET / HTTP/1.1" 500 NC cluster_not_found - "-" 0 0 0 - "CURL_SRC_IP_ADDR" "curl/8.9.1" "c583f839-4b56-9f6e-9b83-0db1c5a9e382" "example.test.vpn" "-" - - 10.100.0.36:80 CURL_SRC_IP_ADDR:51562 - istio-system.wg-proxy-ext.0
```

Here's the ExternalName Service and HTTPRoute

```yaml
apiVersion: v1
kind: Service
metadata:
  name: wg-proxy-ext
  namespace: istio-system
spec:
  externalName: 10.0.2.2
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ExternalName
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wg-proxy-ext
  namespace: istio-system
spec:
  hostnames:
  - example.test.vpn
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-default
    namespace: istio-system
    sectionName: http-test-vpn
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: wg-proxy-ext
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
```

### Version

```Text
-- istioctl
client version: 1.24.2
control plane version: 1.24.2
-- kubectl
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.0-gke.1358000
```

### Additional Information

istio-proxy logs

```sh
[2025-01-02T21:54:23.954Z] "GET / HTTP/1.1" 500 NC cluster_not_found - "-" 0 0 0 - "CURL_SRC_IP_ADDR" "curl/8.9.1" "c583f839-4b56-9f6e-9b83-0db1c5a9e382" "example.test.vpn" "-" - - 10.100.0.36:80 CURL_SRC_IP_ADDR:51562 - istio-system.wg-proxy-ext.0
```

In case it's useful I've created a gist detailing everything I've done so far at https://gist.github.com/hmoazzem/1e00a222e16590a67fb1bcc83eb1c82b

**Comment by howardjohn** [comment]
Istio doesn't support sending to an ExternalName service like this (and, iirc, it's suggested to *not* support it in the API). However you can create a ServiceEntry that looks very similar and then refer to it as a `kind: Hostname` object

**Comment by howardjohn** [comment]
Sorry to not be clear, I was on my phone before so hard to provide config snippiet. Here is what you need:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wg-proxy-ext
  namespace: istio-system
spec:
  hostnames:
  - example.test.vpn
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-default
    namespace: istio-system
    sectionName: http-test-vpn
  rules:
  - backendRefs:
    - group: networking.istio.io
      kind: Hostname
      name: example.test.vpn # matches up with SE hosts field
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: wg-proxy-ext
  namespace: istio-system
spec:
  endpoints:
  - address: 10.0.2.2
  hosts:
  - example.test.vpn
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 8080
    protocol: HTTP
  resolution: STATIC
```

No Service or WorkloadEntry needed
