### ISSUE TITLE
Istio Ambient mode - Routing egress traffic to wildcard destinations

### ISSUE THREAD

**Issue by bhat39a** [istio/istio#54540]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team,

We are planing to use istio ambient mode to route egress traffic to wild-card domains from our EKS cluster, but traffic is not getting routed to wild card domains. 

Mesh egress traffic follow :- 

For normal domains = pod --> ztunnel --> waypoint  ( working fine)
For wild card domains = pod --> ztunnel --> not getting routed to waypoint as there is no SE for wildcard domains. 

We can't set resolution mode to DNS for wild-card domains it has to be FQDN. 

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: wildcard
  namespace: common-infrastructure
spec:
  hosts:
    - "*.com"
    - "*.net"
    - "*.org"
    - "*.io"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```
--> Error from server: error when creating "wse.yml": admission webhook "validation.istio.io" denied the request: configuration is invalid: hosts must be FQDN if no endpoints are provided for resolution mode DNS.
--> we have fixed the same issue using sidecar approach by referring to https://istio.io/latest/blog/2023/egress-sni/. 

Any inputs to fix this in ambient mode ? 

### Version

```Text
% istioctl version                                                                                  
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (5 proxies)
```

**Comment by howardjohn** [comment]
This is not currently supported.

**Comment by bhat39a** [comment]
> This is not currently supported.

@howardjohn thanks for the update could you please share with any plan to get this feature released.

**Comment by keithmattix** [comment]
Not stale

**Comment by Nova-Logic** [comment]
It is really hard to rely on ambient mesh without wildcard support for egress traffic, there are a lot of use-cases where it would be impossible to definitively know the whole list of subdomains that would be used by an app

**Comment by ceastman-r7** [comment]
We have similar use cases using 3rd party tools where we don't have a list of hostnames they need access to. For instance https://external-secrets.io/latest/ it took looking through various logs to find the ip addresses and hostnames that needed to be created as service entries to allow external secrets to work correctly.

with sidecar data plane mode this service entry worked as expected: 

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: wildcard.amazonaws.com
  namespace: platform-delivery
spec:
  exportTo:
  - .
  hosts:
  - '*.amazonaws.com'
  location: MESH_EXTERNAL
  ports:
  - name: tls
    number: 443
    protocol: TLS
  resolution: NONE
```
