### ISSUE TITLE
gateway still establish mtls with sidecar even `TLS Mode: disable` set  in destinationRule 

### ISSUE THREAD

**Issue by Yufeireal** [istio/istio#54607]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi team, I am going to replace the self signed CA with our plug-in CA (issued by certmanager). The cluster I am going to rollout is a bit huge, thousands of gateway proxies, but very few sidecar proxies inside(can assume no sidecar <-> sidecar communication, only have gateway -> sidecar communication), so looking for a quick way to replace CA.

Based on this doc https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/ 
I've set the tls mode to be disable, so ideally gateway proxy -> workload will be plaintext traffic according to the doc. 

However, it doesn't seem to take effect, if I check on the vprovision-command side, the traffic from gateway source is still mtls.. 
I don't have any strict setting regarding PeerAuthentication to enforce mtls, wondering is this expected behavior? Or am I missing some configs to disable the TLS between gateway pods and workload pods(with sidecar), thanks!

![image](https://github.com/user-attachments/assets/605eda0a-7e42-4a0e-81ba-3a912faf33bb)

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    app.kubernetes.io/instance: routing
    istio.io/rev: 1-24
  name: vprovision-command-1-24
  namespace: default
spec:
  host: vprovision-command.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 307s
    loadBalancer:
      simple: LEAST_REQUEST
    outlierDetection:
      consecutive5xxErrors: 500
      interval: 1m
      maxEjectionPercent: 30
      minHealthPercent: 65
    tls:
      mode: DISABLE
```

### Version

```Text
istio version: 1.24.2
kubernetes version: 1.31 (EKS)
```

**Comment by Yufeireal** [comment]
This is good without the need to restart workload, however, it looks like:
If I change the secret format from
```
Opaque:
  ca-cert.pem: xxx
  ca-key.pem: xxx
  cert-chain.pem: ""
  key.pem: ""
  root-cert.pem:  


```
to TLS secret which used by cert manager
```
  ca.crt: xxx
  tls.crt: xxx
  tls.key: xxx
```
though I satisfied the condition of auto reloading, PCDS will not be triggered.

**Comment by Yufeireal** [comment]
Also saw this https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/#auto-mtls

Is it an istio enforcement that in mesh proxies communications will always be mTLS enforced without the ability to modify and the tls mode I spefied are mainly used if users wants to define their own tls policy, if disable, it will be auto mtls? (not sure tho)

**Comment by howardjohn** [comment]
this should work. wondering if maybe the istio.io/rev label is mismatched so it's ignored? 

run istioctl pc c and it will show you if the DR is applied or not (there is column for the DR)

**Comment by howardjohn** [comment]
also I know this is sidecars, but is it on an install with ambient enabled? 

I know for pure ambient The DISABLE is ignored.. i suspect it shouldn't be here but would be good to know

**Comment by Yufeireal** [comment]
Thanks for the quick response! 

1. I've used  `istioctl pc c verkada-main-gateway-az-a-57ff5ccc5f-jtf2p`, I think it's applied successfully by checking the DestinationRule column, 
![image](https://github.com/user-attachments/assets/b1df6797-18e2-47f9-9d42-ba12463b9fba)

2. Yes, it's using ambient profile.
These are the `peerauthentication` we have in cluster
![image](https://github.com/user-attachments/assets/77059c5e-65ca-4b8f-89be-afed7a4d1cfe)

I patched the namespace to not have ambient, however, the istio_requests_count_total still shows `mutual_tls` as connection_security_policy

`apiVersion: v1
kind: Namespace
metadata:
  labels:
    elbv2.k8s.aws/pod-readiness-gate-inject: "true"
    istio.io/dataplane-mode: none
    istio.io/rev: 1-24
  name: default
spec:
  finalizers:
  - kubernetes
status:
  phase: Active`

**Comment by Yufeireal** [comment]
Let me try more on the second hypothesis, pretty sure the cluster I am going to rotate is still using `default` profile.

**Comment by Yufeireal** [comment]
I switched the profile: ambient -> profile: default and disabled istio-cni + ztunnel. 
It looks like this is it.. After disabling that, traffic with connection_security_policy: mutual_tls disappear

![image](https://github.com/user-attachments/assets/bb1fcafc-ef6c-4771-9387-6508bf212b84)

**Comment by howardjohn** [comment]
hmm, for me it works.

Steps:
* Install with ambient
* Create sidecar, service, GW and VS pointing to it
* Curl the ingress, I see mTLS.
* Add the DR, I see no mTLS

Note I am using logs to determine this, I see you are using metrics. Just to be certain, might be good to look at logs:

```
[2025-01-09T19:08:43.706Z] "GET / HTTP/1.1" 200 ...  10.10.0.29:80 10.10.0.1:0 - default
[2025-01-09T19:08:51.367Z] "GET / HTTP/1.1" 200 ... 10.10.0.29:80 10.10.0.1:0 outbound_.80_._.echo.default.svc.cluster.local default
```

See first line, no mTLS. Second line is mTLS (not very clear but the `outbound_.` thing is the SNI which implies TLS).

**Comment by Yufeireal** [comment]
Do `PeerAuthentication: PERMISSIVE` has any overriden for this behavior? 
Like if destinationRule disable mtls, however, peerauthentication is PERMISSIVE instead of DISABLE, will this somehow make the connection to destination be mtls instead of plaintext, thanks! 
(I will conduct another testing)

**Comment by Yufeireal** [comment]
With mtls (I think destination pod -> another pod connection is broken, I forcily replace the cert to test)

[2025-01-09T19:55:49.308Z] "GET /user/session_accounts HTTP/2" 503 - via_upstream - "-" 0 62 44 42 "104.28.205.136" "curl/8.7.1" "34280f9e-73f3-45cc-bace-e1fefcc2ea6b" "xxxxx.net" "10.37.92.141:8888" outbound|80||vprovision-command.default.svc.cluster.local xxxx:57714 xxxx:443 xxxx:60263 - api_to_vprovision_1

Without mtls

`[2025-01-09T19:58:53.474Z] "GET /user/session_accounts HTTP/2" 200 - via_upstream - "-" 0 23 96 49 "xxxx" "curl/8.7.1" "f552e2cf-d1a4-46e2-9859-a5d37fd962e6" "xxxx.staging2.vcamera.net" "xxxxx" outbound|80||vprovision-command.default.svc.cluster.local xxx xxx xxx - api_to_vprovision_1
`

I was using this to expose logs, is the outbound stuff just indicating the cluster_name? 

```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: access-logs
  namespace: istio-system
spec:
  accessLogging:
  - match:
      mode: CLIENT_AND_SERVER
    providers:
    - name: envoy
  selector:
    matchLabels:
      ca-testing: "true"
```
