### ISSUE TITLE
Istio analyze incorrectly reports "IST0145 Conflict with gateways..." when ports are unique

### ISSUE THREAD

**Issue by Florianisme** [istio/istio#54643]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When updating Istio 1.22.1 to 1.24.1 in an RKE2 Cluster, we see the following message in the istioctl-installer Pod:

<pre>
client version: 1.24.1
control plane version: 1.22.1
data plane version: 1.21.1 (2 proxies), 1.22.1 (73 proxies)
Error: Analyzers found issues when analyzing namespace: istio-system.
See https://istio.io/v1.24/docs/reference/config/analysis for more information about causes and resolutions.
Error [IST0145] (Gateway istio-system/istio-xxx-gateway) Conflict with gateways a, b, c
</pre>

This error is printed for each of our Gateways and prevents us from updating the Istio installation.

All of our Gateways are working as expected on the current Istio version 1.22.1. We are using wildcard hostnames exclusively, with only the port being different for each Gateway.

We suspect this is the same issue as this user encountered, where the port was not part of the conflict check: https://github.com/istio/istio/pull/53973.

These are two exemplary Gateway configurations we are using:
```yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-https-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.ourdomain.com'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: wildcard-cert
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-custom-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.ourdomain.com'
      port:
        name: https
        number: 7120
        protocol: TCP
```

### Version

```Text
$ istioctl version
client version: 1.24.1
control plane version: 1.22.1
data plane version: 1.21.1 (2 proxies), 1.22.1 (73 proxies)

$ kubectl version
Client Version: v1.29.10
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.2+rke2r1
```
