### ISSUE TITLE
Connect to TLS service only possible with insecureSkipVerify

### ISSUE THREAD

**Issue by peter-fe** [istio/istio#54641]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We like to proxy the kube-api via internal LB + Istio GW + Destination Rule + Virtualservice

Running on GKE

This is the (working) config we use
```
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls-kube-api
  namespace: default
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kube-api
  namespace: default
spec:
  hosts:
  - kube-api.mgmt.example.com
  gateways:
  - mgmt-ingress/istio-gateway-mgmt
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kubernetes.default.svc.cluster.local
```

But when we like to get rid of the insecureSkipVerify, and try to provide the SNI instead it does not work anymore, showing error messages like in the issues [here](https://github.com/istio/istio/issues/52503) and [here](https://github.com/istio/istio/issues/50997)

```
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls-kube-api
  namespace: default
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: kubernetes.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kube-api
  namespace: default
spec:
  hosts:
  - kube-api.mgmt.example.com
  gateways:
  - mgmt-ingress/istio-gateway-mgmt
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kubernetes.default.svc.cluster.local
```

Kubectl error without insecureSkipVerify=true and set sni
```
I0110 16:18:12.778363   53520 request.go:1351] Response Body: upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end
E0110 16:18:12.780610   53520 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server is currently unable to handle the request"
I0110 16:18:12.781833   53520 cached_discovery.go:120] skipped caching discovery info due to the server is currently unable to handle the request
I0110 16:18:12.782196   53520 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server is currently unable to handle the request",
  "reason": "ServiceUnavailable",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end"
      }
    ]
  },
  "code": 503
}]
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

Server certificate of kube-api endpoint
```
openssl s_client -connect kubernetes.default.svc.cluster.local:443 </dev/null 2>/dev/null | openssl x509 -noout -text

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            94:0d:0a: .. :8c:67:f4
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = c52c041d- ... -f4b2dea99e25
        Validity
            Not Before: Nov 25 10:11:03 2024 GMT
            Not After : Nov 24 10:13:03 2029 GMT
        Subject: CN = 34.x.y.z
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier:
                DE:01:9E: ... :6D:C2
            X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.x.y.z, IP Address:34.x.y.z, IP Address:35.x.y.z, ...
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
       ...
```

When running the httpbin sample from @howardjohn from issue 50997, setting the sni portion works as expected, but not in our use case.
Not sure if it makes any difference if its an publicly signed certificate or a self-signed one though.

Any thoughts/hints that may help to get this working?

### Version

```Text
Istio version: 1.22.4

Kubectl version:

Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.5-gke.1699000
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by peter-fe** [comment]
Seems to be related with the certificate not publicly signed, so adding `caCertificates` pointing to the pod internal ca bundle was the missing piece.
Both options, providing `sni` or `subjectAltNames` start to work as soon as the caCertificates was set.

The Istio [Security Best Practices](https://preliminary.istio.io/latest/docs/ops/best-practices/security/#configure-tls-verification-in-destination-rule-when-using-tls-origination) doc gave the final hint

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls-kube-api
  namespace: default
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      sni: "kubernetes.default.svc.cluster.local"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kube-api
  namespace: default
spec:
  hosts:
  - kube-api.mgmt.example.com
  gateways:
  - mgmt-ingress/istio-gateway-mgmt
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kubernetes.default.svc.cluster.local
```
