### ISSUE TITLE
`Jaeger` not showing any telemetry data - Services not visible in the dropdown

### ISSUE THREAD

**Issue by dangerouspython** [istio/istio#54656]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am trying to visualize the tracing information from my microservices in a `minikube` cluster using `istio` as the service mesh and `jaeger` (the version info is mentioned below). I am able to access the `Jaeger` UI. But, my services are not visible in the dropdown. 

I am able to make HTTP requests to my services and get back proper responses. I installed `jaeger` into istio by simply '`kubectl apply`ing' the file: https://raw.githubusercontent.com/istio/istio/refs/heads/release-1.24.2-patch/samples/addons/jaeger.yaml 

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (7 proxies)

$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.31.0
```

### Additional Information

Each of my service is exposed on container-port `80` (with additional `spring-actuator` management port at `4004`)

I know that related issues were posted in the past. But, they were all resolved and I am using the latest `istio` version `1.24.2`

Here are the manifests which I am using:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
    name: tracing-gateway
    namespace: istio-system

spec:
    selector:
        istio: ingressgateway
    servers:
        - hosts:
              - "tracing.minikube.me"
          port:
              number: 443
              name: https-tracing
              protocol: HTTPS
          tls:
              mode: SIMPLE
              credentialName: my-certificate

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
    name: tracing-vs
    namespace: istio-system

spec:
    hosts:
        - "tracing.minikube.me"
    gateways:
        - tracing-gateway
    http:
        - route:
              - destination:
                    host: tracing
                    port:
                        number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
    name: tracing
    namespace: istio-system

spec:
    host: tracing
    trafficPolicy:
        tls:
            mode: DISABLE
```
