### ISSUE TITLE
Retry in VS is not working between Egress Gateway and Workload pods

### ISSUE THREAD

**Issue by MengjiaLiang** [istio/istio#54666]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi there,

I am testing a few behaviors of Istio, and found the Retry configuration in VS is not working between the EgressGatway and workload pods.

My setup
- KinD Cluster
- Istio 1.23.0 with demo profile that includes istiod, ingress gateway, and egress gateway
- A delay server inside the mesh
- A virtual service like this
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: delay-server-vs
  namespace: istio-system
spec:
  gateways:
  - mesh
  hosts:
  - delay-server-service.default.svc.cluster.local
  http:
  - name: "retry"
    route:
    - destination:
        host: delay-server-service.default.svc.cluster.local
    retries:
      attempts: 2
      perTryTimeout: 3s
      retryOn: gateway-error,connect-failure,refused-stream,504
```

This works perfectly from another workload pod to the delay server pod.
But I never see the retry happens when I executing a curl command inside the egress gateway pod.

Here's the envoy configuration from the egress gateway
```
{
        "name": "delay-server-service.default.svc.cluster.local:80",
        "domains": [
         "delay-server-service.default.svc.cluster.local"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "outbound|80||delay-server-service.default.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "gateway-error,connect-failure,refused-stream,retriable-status-codes",
            "num_retries": 2,
            "per_try_timeout": "3s",
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
              }
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             504
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/virtual-service/delay-server-vs"
            }
           }
          },
          "decorator": {
           "operation": "delay-server-service.default.svc.cluster.local:80/*"
          },
          "name": "retry"
         }
        ],
        "include_request_attempt_count": true
       },
```

Could you please help me it on confirm whether it is expected or a potential bug in istio? Thank you!

### Version

```Text
╰─ istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (4 proxies)


╰─ kubectl version
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0
```
