### ISSUE TITLE
Helm Deploy of CNI fails with readonly

### ISSUE THREAD

**Issue by Cr0n1c** [istio/istio#54719]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We are deploying istio via helm charts in a declarative way. We are experiencing this problem https://github.com/istio/istio/issues/53849 but can't remediate because we can't directly load manifests (e.g., using  istioctl for creating manifests) into k8s. We are forced to use the helm chart and value files. 

Can we address this fix via exposing the variable in the values? 

### Version

Version: 1.24.2

```Text
2025-01-16T18:28:54.361423Z	info	cni-agent	CNI logging level: info
2025-01-16T18:28:54.361467Z	info	cni-agent	CNI install configuration:
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName:
ChainedCNIPlugin: true
CNIAgentRunDir: /var/run/istio-cni
PluginLogLevel: info
KubeconfigMode: 0600
KubeCAFile:
SkipTLSVerify: false
ExcludeNamespaces:
K8sServiceProtocol:
K8sServiceHost: 34.118.224.1
K8sServicePort: 443
K8sNodeName: istio-cni-node-2cxt6
CNIBinSourceDir: /opt/cni/bin
CNIBinTargetDirs: /host/opt/cni/bin
MonitoringPort: 15014
ZtunnelUDSAddress: /var/run/ztunnel/ztunnel.sock
AmbientEnabled: false
AmbientDNSCapture: false
AmbientIPv6: true
AmbientRedirectTPROXY: true
2025-01-16T18:28:54.361480Z	info	cni-agent	CNI race repair configuration:
Enabled: true
NodeName: gke-staging-us3-staging-us3-node-pool-60488197-bd4c
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: false
LabelPods: false
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg:
InitExitCode: 126
LabelSelectors:
FieldSelectors:
2025-01-16T18:28:54.361511Z	info	ControlZ available at 127.0.0.1:9876
2025-01-16T18:28:54.361944Z	info	cni-agent	starting CNI sidecar repair controller
2025-01-16T18:28:54.363417Z	info	cluster "" kube client started
2025-01-16T18:28:54.395451Z	info	controllers	starting	controller=repair pods
2025-01-16T18:28:54.463598Z	info	cni-agent	initialization complete, watching node CNI dir
2025-01-16T18:28:54.463814Z	error	cni-agent	failed file copy of /opt/cni/bin/istio-cni to /host/opt/cni/bin: open /host/opt/cni/bin/istio-cni.tmp.1476126204: read-only file system
2025-01-16T18:28:54.463860Z	error	cni-agent	installer failed: copy binaries: open /host/opt/cni/bin/istio-cni.tmp.1476126204: read-only file system
2025-01-16T18:28:54.463868Z	info	cni-agent	cleaning up CNI installation
Error: copy binaries: open /host/opt/cni/bin/istio-cni.tmp.1476126204: read-only file system
```

### Additional Information

We are running in gke and here is our config:

`Chart.yaml`
```
apiVersion: v2
name: istio
description: Istio with mTLS

type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
- name: base
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: cni
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: ztunnel
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts

```

`values.yaml`
```
ztunnel:
  profile: ambient

cni:
  profile: ambient

istiod:
  profile: ambient
  defaultRevision: default
```

### Affected product area

- [x] Ambient
- [ ] Docs
- [ ] Dual Stack
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
This is supposed to be fix in 1.24.2. 

This is supposed to have the following configuration on the CNI daemonset:

```
          securityContext:
            privileged: false
            runAsGroup: 0
            runAsUser: 0
            runAsNonRoot: false
            # Both ambient and sidecar repair mode require elevated node privileges to function.
            # But we don't need _everything_ in `privileged`, so explicitly set it to false and
            # add capabilities based on feature.
            capabilities:
              drop:
              - ALL
              add:
              # CAP_NET_ADMIN is required to allow ipset and route table access
              - NET_ADMIN
              # CAP_NET_RAW is required to allow iptables mutation of the `nat` table
              - NET_RAW
              # CAP_SYS_PTRACE is required for repair mode to describe the pod's network namespace
              # in ambient and repair mode.
              - SYS_PTRACE
              # CAP_SYS_ADMIN is required for both ambient and repair, in order to open
              # network namespaces in `/proc` to obtain descriptors for entering pod network
              # namespaces. There does not appear to be a more granular capability for this.
              - SYS_ADMIN
              # While we run as a 'root' (UID/GID 0), since we drop all capabilities we lose
              # the typical ability to read/write to folders owned by others.
              # This can cause problems if the hostPath mounts we use, which we require write access into,
              # are owned by non-root. DAC_OVERRIDE bypasses these and gives us write access into any folder.
              - DAC_OVERRIDE
```

DAC_OVERRIDE is the part that is important and added in 1.24.2 to fix this issue.

Can your confirm your istio-cni-node pod has that?

if not, can you give more info about the host OS and k8s version/distro

**Comment by Cr0n1c** [comment]
Here is the DS
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-cni
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.24.2
    argocd.argoproj.io/instance: istio
    helm.sh/chart: cni-1.24.2
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    k8s-app: istio-cni-node
    operator.istio.io/component: Cni
    release: istio
  name: istio-cni-node
  namespace: istio-system
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/install-cni: unconfined
        prometheus.io/path: /metrics
        prometheus.io/port: '15014'
        prometheus.io/scrape: 'true'
        sidecar.istio.io/inject: 'false'
      labels:
        app.kubernetes.io/instance: istio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: istio-cni
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.24.2
        helm.sh/chart: cni-1.24.2
        istio.io/dataplane-mode: none
        k8s-app: istio-cni-node
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - args:
            - '--log_output_level=info'
          command:
            - install-cni
          env:
            - name: REPAIR_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REPAIR_RUN_AS_DAEMON
              value: 'true'
            - name: REPAIR_SIDECAR_ANNOTATION
              value: sidecar.istio.io/status
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: istio-cni-config
          image: 'docker.io/istio/install-cni:1.24.2-distroless'
          name: install-cni
          ports:
            - containerPort: 15014
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_PTRACE
                - SYS_ADMIN
                - DAC_OVERRIDE
              drop:
                - ALL
            privileged: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/proc
              name: cni-host-procfs
              readOnly: true
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /var/run/istio-cni
              name: cni-socket-dir
            - mountPath: /host/var/run/netns
              mountPropagation: HostToContainer
              name: cni-netns-dir
            - mountPath: /var/run/ztunnel
              name: cni-ztunnel-sock-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      serviceAccountName: istio-cni
      terminationGracePeriodSeconds: 5
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - hostPath:
            path: /opt/cni/bin
          name: cni-bin-dir
        - hostPath:
            path: /proc
            type: Directory
          name: cni-host-procfs
        - hostPath:
            path: /var/run/ztunnel
            type: DirectoryOrCreate
          name: cni-ztunnel-sock-dir
        - hostPath:
            path: /etc/cni/net.d
          name: cni-net-dir
        - hostPath:
            path: /var/run/istio-cni
          name: cni-socket-dir
        - hostPath:
            path: /var/run/netns
            type: DirectoryOrCreate
          name: cni-netns-dir
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
