### ISSUE TITLE
CNI "Readiness probe failed: HTTP probe failed with statuscode: 400" for all pods after the first one is successful

### ISSUE THREAD

**Issue by Cr0n1c** [istio/istio#54726]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I am using ArgoCD to deploy the cni. The first pod comes up perfect (always) but every other pod that comes up returns the following:
```Readiness probe failed: HTTP probe failed with statuscode: 400```. I am having a tough time finding logs to identify why the other ones won't become healthy.

In Argo it states "Waiting for daemon set "istio-cni-node" rollout to finish: 2 of 4 updated pods are available..."

`Chart.yaml`
```
apiVersion: v2
name: istio
description: Istio with mTLS

type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
- name: base
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: cni
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: ztunnel
  version: 1.24.2
  repository: https://istio-release.storage.googleapis.com/charts

```

`values.yaml`
```
ztunnel:
  profile: ambient

cni:
  logging:
    level: debug
  profile: ambient
  cniBinDir: "/home/kubernetes/bin"

istiod:
  profile: ambient
  defaultRevision: default
```

Logs: [install-cni.txt](https://github.com/user-attachments/files/18445144/install-cni.1.txt)

<img width="1145" alt="Image" src="https://github.com/user-attachments/assets/b50f7347-7d7d-4a04-81ff-2dffd4037b78" />

<img width="871" alt="Image" src="https://github.com/user-attachments/assets/c8368a76-2915-4026-a5a4-878011a5c311" />

### Version

```Text
Istio: 1.24.2
GKE Cluster: See attachment
```
