### ISSUE TITLE
No services shown on Jaeger UI / integration with Istio

### ISSUE THREAD

**Issue by vivekyad4v** [istio/istio#54739]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Deployed Jaeger using below Argo manifest - 

```
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 3.3.3
    chart: jaeger
    helm:
      releaseName: jaegar
      values: |
        collector:
          service:
            otlp:
              grpc:
                name: otlp-grpc
                port: 4317
              http:
                name: otlp-http
                port: 4318              
        storage:
          type: elasticsearch
        provisionDataStore:
          cassandra: false
          elasticsearch: true    
        elasticsearch:
          master:
            replicaCount: 1
          data:
            replicaCount: 1
          coordinating:
            replicaCount: 1
          ingest:
            replicaCount: 1
```

Deployed Istio with below params - 
```
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: 'istiod'
        targetRevision: '1.20.3'
        helm:
          releaseName: '{{`{{releaseName}}`}}'
          values: |
            global:
              defaultPodDisruptionBudget:
                enabled: false
            pilot:
              autoscaleEnabled: true
              autoscaleMin: 2
              replicaCount: 2
              autoscaleMax: 2
            podAnnotations:
              prometheus.io/path: /metrics
              prometheus.io/scrape: "true"
            serviceAnnotations:
              prometheus.io/path: /metrics
              prometheus.io/scrape: "true"
            meshConfig:
              enableTracing: true
              enablePrometheusMerge: true
              defaultConfig:                
                discoveryAddress: istiod.istio-system.svc:15012
                tracing: {}
              extensionProviders:
                - name: jaeger
                  opentelemetry:
                    port: 4317
                    service: jaegar-jaeger-collector.istio-system.svc.cluster.local
```

Followed [this](https://istio.io/latest/docs/tasks/observability/distributed-tracing/jaeger/) doc - for Jaeger integration  but ended up with below error on Jaeger collector - 

```
{"level":"info","ts":1737097236.569088,"caller":"grpc@v1.60.0/server.go:983","msg":"[core][Server #3] grpc: Server.Serve
 failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting
 from client: \\\"POST /opentelemetry.prot\\\"\"","system":"grpc","grpc_log":true}
```

Pls suggest.

### Version

```Text
Istio
versionclient version: 1.24.2
control plane version: 1.20.3
data plane version: 1.20.3 (68 proxies)

Kube
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.28.5

Jaeger version - 1.53.0
```

**Comment by vivekyad4v** [comment]
Hey, can someone pls look into this? I tried with Istio Jaeger add on YAML also but no luck. Getting below error with that. Tried both grpc & http ports.

Error -  
```
{"level":"info","ts":1737115253.481744,"caller":"grpc@v1.64.0/server.go:994","msg":"[core][Server #4]grpc: Server.Serve  
failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting
 from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x1c\\\\x01\\\\x00\\\\x01\\\\x18\\\\x03\\\\x03\\\\xbaf\\\\xcd\\\\fS'Y\\\\xc7ac\\\\xbf\\\\x13\\\\xec\\\"\"","syst
em":"grpc","grpc_log":true}
```

**Comment by zirain** [comment]
that paged is tested, you can check out the [scripts](https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/observability/distributed-tracing/jaeger/snips.sh).

**Comment by vivekyad4v** [comment]
Did the same but still getting the shared error.

**Comment by howardjohn** [comment]
that error means client sent TLS while the server expected plaintext

**Comment by vivekyad4v** [comment]
@howardjohn  -  I have disabled mtls at gloo istio integration, nowhere else i have explicitly used TLS. Sharing the gloo config below -  

```
  source:
    repoURL: https://storage.googleapis.com/solo-public-helm
    targetRevision: 1.16.4
    chart: gloo
    helm:
      releaseName: gloo-system
      values: |
        global:
          istioIntegration:
            enabled: true
            enableIstioSidecarOnGateway: true
            disableAutoinjection: true
          istioSDS:
            enabled: true
          glooMtls:
            enabled: false
            istioProxy:
              image:
                registry: docker.io/istio
                repository: proxyv2
                tag: 1.20.3            
            sds:
              image:
                repository: sds
                tag: 1.16.4
          glooStats:
            enabled: true
            serviceMonitorEnabled: true
            podMonitorEnabled: true
            routePrefixRewrite: /stats/prometheus
            setDatadogAnnotations: true
            enableStatsRoute: true
            statsPrefixRewrite: /stats

        gloo:
          deployment:
            replicas: 2
          podDisruptionBudget:
            minAvailable: 1
        gatewayProxies:
          gatewayProxy:
            kind:
              deployment:
                replicas: 2
            podDisruptionBudget:
              minAvailable: 1
            podTemplate: 
              httpPort: 8080
              httpsPort: 8443
            gatewaySettings:
              accessLoggingService:
                accessLog:
                - fileSink:
                    path: /dev/stdout
                    stringFormat: ""              
              customHttpsGateway:
                options:
                  httpConnectionManagerSettings:
                    requestTimeout: "2m9s"
                    idleTimeout: "2m1s"
            httpGateway:
              {{- if .Values.rateLimit.enabled }}
                networkLocalRatelimit:
              {{- toYaml .Values.rateLimit.networkLocalRatelimit | nindent 18 }}
              {{- end }}
```

I have shared most of the relevant config. Can you pls help?
