### ISSUE TITLE
Behavior of Istio Local Rate Limit: Is it normal for the limit to occur at about 75% of the theoretical value?

### ISSUE THREAD

**Issue by hirota-tver** [istio/istio#54759]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Istio Local Rate Limit is implemented using Envoy Filter CRD with 600 tokens per pod and 12 pods running.

```yaml
token_bucket:
  max_tokens: 600
  tokens_per_fill: 600
  fill_interval: 1s
```
I applied 5,330 rps for 5 minutes three times under the same conditions using the k6 load test tool, and the second and third times resulted in the rate limit being enforced for the first two minutes.

![Image](https://github.com/user-attachments/assets/11879305-d3d2-4e91-82f9-482fbd93734b)

My assumption is that rate limits are theoretically enforced at 7,200 rps or more, so I think that rate limits being enforced at about 75% of 7,200 (5,330) rps is too early.

Is this a bug? Or is it reasonable for the rate limit to be enforced at about 75% of the theoretical value?

Incidentally, at about 50% of the theoretical rps, the rate limit was not enforced even once.

### Version

```Text
client version is 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2
```

### Additional Information

envoy filter yaml

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: testapp
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 600
                tokens_per_fill: 600
                fill_interval: 1s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
              local_rate_limit_per_downstream_connection: false

```

The target service is a Google Cloud laod balancer -> Gateway API -> HTTPRoute -> Service -> Argo Rollout -> Pods configuration running on GKE. 

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [x] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
