### ISSUE TITLE
[Istio 1.23.2][ServiceEntry][resolution: NONE][protocol: TCP] "panic: runtime error: invalid memory address or nil pointer dereference" when NO addresses specified

### ISSUE THREAD

**Issue by angroszew** [istio/istio#54756]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

After upgrading to Istio 1.23.2 applying the following ServiceEntry:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se-dns-tcp-all-53
  labels:
    app.kubernetes.io/name: chf-resource
    app.kubernetes.io/instance: chf-resource
    app.kubernetes.io/version: 25.3.1-245
    app.kubernetes.io/component: System-Configuration-and-Management
    app.kubernetes.io/part-of: NCC
    app.kubernetes.io/managed-by: Helm
spec:
  exportTo:
  - .
  hosts:
  - dns-tcp.all
  location: MESH_EXTERNAL
  ports:
  - name: tcp-53
    number: 53
    protocol: TCP
  resolution: NONE
```
is causing the restart of istio-discovery-istiod Pod with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x298a321]

goroutine 16936 [running]:
istio.io/istio/pkg/config/analysis/incluster.NewController.func2(0xc000f17cb0?, {0x2cc0800?, 0xc0047bea80?})
        istio.io/istio/pkg/config/analysis/incluster/controller.go:77 +0x41
istio.io/istio/pkg/config/analysis/incluster.NewController.(*Manager).CreateIstioStatusController.func3({0x0?, 0x0?}, {0x2cc0800?, 0xc0047bea80?})
        istio.io/istio/pilot/pkg/status/manager.go:97 +0x51
istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker.func1()
        istio.io/istio/pilot/pkg/status/resourcelock.go:214 +0x60e
created by istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker in goroutine 16932
        istio.io/istio/pilot/pkg/status/resourcelock.go:182 +0x105

```
The restart of istio-discovery-istiod Pod affects the installation of the application when there is only one istio-discovery-istiod Pod. When there are 2 istio-discovery-istiod Pods, the panic error and pod restart only takes place in one Pod.

The output from _isctioctl analyze -n ig1_ complains about ServiceEntry ig1/se-dns-tcp-all-53:
```
Warning [IST0133] (ServiceEntry ig1/se-dns-tcp-all-53) Schema validation warning: addresses are required for ports serving TCP (or unset) protocol when ISTIO_META_DNS_AUTO_ALLOCATE is not set on a proxy

Warning [IST0134] (ServiceEntry ig1/se-dns-tcp-all-53) ServiceEntry addresses are required for this protocol. 
```
but the documentation for ServiceEntry in Istio 1.23 doesn't specify that addresses are required for ports serving TCP (or unset) protocol when resolution is set to NONE. The Istio 1.23 documentation about [ServiceEntry](https://istio.io/v1.23/docs/reference/config/networking/service-entry/) states the following:
`Service resolution mode for the hosts. Care must be taken when setting the resolution mode to NONE for a TCP port without accompanying IP addresses. In such cases, traffic to any IP on said port will be allowed (i.e. 0.0.0.0:<port>).
`
Based on the documentation above I added:
```
spec:
   addresses:
   - 0.0.0.0/32
```
to the ServiceEntry definition and then I was able to successfully apply this object without panic error in istio-discovery-istiod Pod.

Are addresses required when setting the resolution mode to NONE for a TCP port - and the Istio 1.23 documentation should state this? Or, is there a bug in the code and there should NOT be a panic error when the resolution mode is set to NONE for a TCP port without any address specified?

### Version

```Text
istioctl version is 1.23
```

### Affected product area

- [ ] Ambient
- [x] Docs
- [ ] Dual Stack
- [x] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
