### ISSUE TITLE
MeshConfig documentation is missing the serviceSettings setting

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#54762]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

In our setup, we have configured the following meshConfig setting, which seems to still work and do what we expect it to do:
```
meshConfig:
  serviceSettings:
  - settings:
      clusterLocal: true
    hosts:
    - host1.ns.svc.cluster.local
    - host2.ns.svc.cluster.local
    - host3.ns.svc.cluster.local
```

However, the documentation for this is missing on the mesh config reference page: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/

Part of the settings is still documented, but some crucials parts are missing: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ServiceSettings-Settings

If this documentation and feature is still supported, could the documentation be restored?
Could other settings also be accidentally dropped from the documentation? For example `protocolDetectionTimeout`

### Version

```Text
N/A, it's related to published documentation.
```
