### ISSUE TITLE
Missing permissions for Gateway API

### ISSUE THREAD

**Issue by josemrs** [istio/istio#54789]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi, I'll try to explain what just happened because I cannot figure out if I'm doing something wrong or there is a missing permission in the CrusteRole.

I had a working Istio deployment including a couple of Gateways deployed using Gateway API resources. As we thought we got everything in code, we started redeploying from scratch using our cluster bootstrap process.

Istiod started complaining like this:

```
2025-01-22T09:16:39.836313Z error controllers error handling istio-system/internal-gateway, retrying (retry count: 4): update gateway annotation: gateways.gateway.networking.k8s.io "internal-gateway" is forbidden: User "system:serviceaccount:istio-system:istiod" cannot patch resource "gateways" in API group "gateway.networking.k8s.io" in the namespace "istio-system"  controller=gateway deployment
```

And, indeed, the internal gateway was not programmed. As soon as I added patch permission, the GW is programmed and this annotation added:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    [...]
    gateway.istio.io/controller-version: "5"
    [...]
```

I manually edited istiod associated ClusterRole and added patch permission like this:

```
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - patch
```

**I cannot see that permission anywhere in the istiod helm chart version 1.24.2.**

The Gateway resource looks like this:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    proxy.istio.io/config: '{"gatewayTopology" : { "proxyProtocol": {} }}'
  labels:
    app.kubernetes.io/name: internal-gateway
    app.kubernetes.io/version: default
    istio: ingressgateway # Label used by Kiali
  name: internal-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ include "istio.fullname" . }}-wildcard-tls
```

Is this, and possibly 'update', permissions missing? How is it possible? Am I missing something?

Thank you in advance,
Jose

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.23.3-tetratefips0
data plane version: 1.23.3 (5 proxies)

$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.31.4-eks-2d5f260

Images:
ironbank/tetrate/istio/pilot:1.23.3
ironbank/tetrate/istio/proxyv2:1.23.3
```
