### ISSUE TITLE
Istio automatically managed mTLS does not work for communication between sidecar and egress gateway for HTTPS traffic originated from app container in the source pod

### ISSUE THREAD

**Issue by lc1851** [istio/istio#54793]
Below is my configuration.
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cnn
  namespace: egress-test
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cnn-istio-egressgateway
  namespace: egress-test
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls-passthrough
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cnn-destination-rule
  namespace: egress-test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cnn-through-egress-gateway
  namespace: egress-test
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - cnn-istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      - cnn-istio-egressgateway
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
  namespace: egress-test
---
apiVersion: v1
kind: Service
metadata:
  name: curl
  namespace: egress-test
  labels:
    app: curl
    service: curl
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: curl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: egress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: curl
      containers:
      - name: curl
        image: registry.gitlab.com/mycompany/devops/docker_recipes/imagewithcurl:1.84.5
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/curl/tls
          name: secret-volume
      imagePullSecrets:
      - name: gitlab-docker-registry
      volumes:
      - name: secret-volume
        secret:
          secretName: curl-secret
          optional: true
```

With this configuration, I can access cnn using `curl -sSL -o /dev/null -D - https://edition.cnn.com/politics` and get the following output from the curl pod. I can also confirm the traffic goes through egress gateway by log entries in the egress gateway logs.
```
HTTP/2 200
Content-Type: text/html; charset=utf-8
```

When I put in the below AuthorizationPolicy to block the traffic from the curl pod. The spec.rules.from.source.principals field does not take effect.

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-curl-principal
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: egressgateway
  action: DENY
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/egress-test/sa/curl"]
```

According to AuthorizationPolicy documentation here https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source, for the principals field to take effect, Istio managed mTLS should be in place for communication between the sidecar of the curl pod and the egress gateway. 

The doc here (https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/) states that "Istio automatically configures workload sidecars to use mutual TLS". However, the istio managed mTLS does not seem to be in place for communication between the sidecar of the curl pod and the egress gateway. Could you please help fix this issue?
