### ISSUE TITLE
Isitio 1.24 deploy istio-cni with no missing privilegeds causing pods creation failures

### ISSUE THREAD

**Issue by ormergi** [istio/istio#54815]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hello, 

I am trying to deploy istio 1.24.2 using `istioctl`, but it stuck on deploying CNI stage and eventually fails:
```
...
- Processing resources for CNI. Waiting for DaemonSet/kube-system/istio-cni-node 
✘ CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: context deadline exceeded
  
Error: failed to install manifests: failed to wait for resource: resources not ready after 5m0s: context deadline exceeded
```

Looking into `istio-cni-nodes` pods we see the following error:
```
2025-01-23T14:15:53.782388Z     error   cni-agent       Failed to start up UDS Log Server: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
Error: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
```

We managed to workaround it by patching istio-cni-node to have privileged=true, right after `istioctl install` creates it but its not sustainable and flaky. 

### Version

```Text
$ ./istioctl version 
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (3 proxies)
$ kubectl version 
selecting podman as container runtime
Client Version: v1.30.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.8
```

**Comment by bleggett** [comment]
@ormergi if you set the following `istio-cni` selinux options during install, does it change anything?

```
seLinuxOptions:
  type: spc_t
```

(if using helm, adding that to a file and doing `helm install istio-cni -f <myfile.yaml> should do)

**Comment by ormergi** [comment]
@bleggett hey, thanks for the hint, unfortunately it didn't work for me.

I use istioctl & IstioOperaor CR manifest, adding `seLinuxOptions` under spec.value gives the following error:
```
Error: generate config: could not unmarshal: error unmarshaling JSON: while decoding JSON: unknown field "seLinuxOptions" in istio.operator.v1alpha1.Values

```

**Comment by ormergi** [comment]
@howardjohn hey, is it possible to configure `seLinuxOptions` using istioctl & IstioOperator CR?

**Comment by bleggett** [comment]
> [@bleggett](https://github.com/bleggett) hey, thanks for the hint, unfortunately it didn't work for me.
> 
> I use istioctl & IstioOperaor CR manifest, adding `seLinuxOptions` under `spec.value` gives the following error:
> 
> ```
> Error: generate config: could not unmarshal: error unmarshaling JSON: while decoding JSON: unknown field "seLinuxOptions" in istio.operator.v1alpha1.Values
> ```


Can you share your operator CR?

**Comment by ormergi** [comment]
@bleggett please see bellow CR I use: 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    global:
      jwtPolicy: third-party-jwt
    cni:
      chained: false
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug
    seLinuxOptions:
      type: spc_t
    pilot:
      cni:
        enabled: true
        provider: "multus"
```
