### ISSUE TITLE
istio virtual service host is not filtering traffic

### ISSUE THREAD

**Issue by sambitr** [istio/istio#54814]
Hi There,

We have a configuration in azure application gateway where it will accept traffic based on prefixes in 2 types of urls: internal and external.
We have enabled routing on all paths to both the internal and external URLs.

The aim is to restrict traffic at ingress level through Istio.

The gateway configuration in istio-system looks like

```
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

The istio gateway **virtual service** is configured like

```
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - <internal-url>
  http:
  - match:
    - uri:
        prefix: /app-name/seq/
    - uri:
        prefix: /app-name/seq
    rewrite:
      uri: /
    route:
    - destination:
        host: app-name-seq
        port:
          number: 80

```

This should have restricted traffic to /app-name/seq/ only through internal URL. But the thing is, we can access the application in both the external and internal URLs

https://internal-url/app-name/seq/
https://external-url/app-name/seq/

My understanding is that it should restrict traffic coming to the /app-name/seq/ path only through the internal URL. But it is not restricting traffic.

I am not sure what is wrong here. Can someone explain this?

here is the istio route table
```
$ istioctl proxy-config routes istio-ingressgateway-6bdb9649cb-kpsrz -n istio-system
NAME                                                  VHOST NAME                               			 DOMAINS                              			MATCH                             			VIRTUAL SERVICE
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/tile*              			<anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/tile*                			<anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/definition/*                  <anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/audit/*                       <anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/security/*                    <anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/instance/*                    <anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/tokens/*                      <anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp>/health/*                      <anotherapp>-ingress.<anotherapp>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp2>/pxs*              			<anotherapp2>-web-pxs.<anotherapp2>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp2>/psa*              			<anotherapp2>-web-psa.<anotherapp2>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp2>/tda*              			<anotherapp2>-web-tda.<anotherapp2>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp2>/admin*            			<anotherapp2>-ingress-admin-tile.<anotherapp2>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp2>/client-admin*     			<anotherapp2>-ingress-client-admin-tile.<anotherapp2>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp3>/api/*                    			<anotherapp3>-ingress-api.<anotherapp3>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp3>/swagger*                 			<anotherapp3>-ingress-api.<anotherapp3>
https.443.https.istio-ingressgateway.istio-system     *:443                                    			 *                                    			/<anotherapp3>*                                			<anotherapp3>-ingress-web.<anotherapp3>
https.443.https.istio-ingressgateway.istio-system     <internalurl>:443     							<internalurl>     								/<anotherapp2>/seq/*             			<anotherapp2>-seq.<anotherapp2>
https.443.https.istio-ingressgateway.istio-system     <internalurl>:443     							<internalurl>     								/<anotherapp2>/seq*              			<anotherapp2>-seq.<anotherapp2>
```

**Comment by keithmattix** [comment]
VirtualService doesn't restrict anything from a security perspective. When you create one, it just tells mesh clients what route exists. To get what you want, you need to declare a VS for the external URL and add a least one route so that mesh clients think that's the only route that exists, but I must emphasize that this is NOT a security boundary. If you want real security policies, use authorization policy

**Comment by sambitr** [comment]
hey @keithmattix I tried doing that. But what it is behaving now is that the external URL endpoints are not working and even the one shich supposed to work with internal URL, only works with external URL.

I am very confused with the behaviour  here

```
https.443.https.istio-ingressgateway.istio-system     <externalURL>.com:443     <externalURL>     /<app>/pxs*              <app>-web-pxs.<app>
https.443.https.istio-ingressgateway.istio-system     <externalURL>.com:443     <externalURL>     /<app>/psa*              <app>-web-psa.<app>
https.443.https.istio-ingressgateway.istio-system     <externalURL>.com:443     <externalURL>     /<app>/tda*              <app>-web-tda.<app>
https.443.https.istio-ingressgateway.istio-system     <externalURL>.com:443     <externalURL>     /<app>/admin*            <app>-ingress-admin-tile.<app>
https.443.https.istio-ingressgateway.istio-system     <externalURL>.com:443     <externalURL>     /<app>/client-admin*     <app>-ingress-client-admin-tile.<app>
https.443.https.istio-ingressgateway.istio-system     <internalURL>:443         <internalURL>     /<app>/seq/*             <app>-seq.<app>
https.443.https.istio-ingressgateway.istio-system     <internalURL>:443         <internalURL>     /<app>/seq*              <app>-seq.<app>
```

**Comment by keithmattix** [comment]
Can you be more specific? What do you mean by "not working"? What response code are you receiving? Is the client in the mesh or external to the cluster? What do your virtual services look like?

**Comment by sambitr** [comment]
when we send traffic to https://externalurl/app/admin, we are getting 404 not found.

but the one that should work on internal ONLY URL, works for both external and internal URL

https://externalurl/app/seq/  --> works
https://internalURL/app/seq/   --> also works


Virtualservice for /app/admin

```
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - externalhost
  http:
  - match:
    - uri:
        prefix: /app/admin
    route:
    - destination:
        host: admin-tile
        port:
          number: 80
    timeout: 30s
```

virtualservice for /app/seq/

```
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - internalhost
  http:
  - match:
    - uri:
        prefix: /dataclassifier/seq/
    - uri:
        prefix: /dataclassifier/seq
    rewrite:
      uri: /
    route:
    - destination:
        host: dc-seq
        port:
          number: 80
```
