### ISSUE TITLE
post istio 1.22.6 upgrade issue with connection to azure cosmos paas services

### ISSUE THREAD

**Issue by kalyanteja19** [istio/istio#54877]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

In order to connect from kubernetes workloads, we were using istio service entries with resolution as NONE. It is working before 1.22 istio upgrade. Here is the reference.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: test
spec:
  exportTo:
  - "."
  hosts:
  - xxxx.documents.azure.com 
  addresses:
  - x.x.x.x/32
  ports:
  - number: 10255  # Port where you would want to connect
    name: tcp-xxxx
    protocol: TCP
  - number: 443  # Port where you would want to connect
    name: https-xxx
    protocol: HTTPS    
  resolution: NONE
  location: MESH_EXTERNAL
```

After 1.22 upgrade, we are seeing UH issues with above configurations. We see that xxxx.documents.azure.com is automatically getting converted to xxxx-region.documents.azure.com. You see that it is getting redirected to regional endpoints. This we are seeing issues with only cosmos endpoints. 

New SE with 1.22 change:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: test
spec:
  exportTo:
  - "."
  hosts:
  - xxxx.documents.azure.com 
  endpoints:
  - address: x.x.x.x
  addresses:
  - x.x.x.x/32
  ports:
  - number: 10255  # Port where you would want to connect
    name: tcp-xxxx
    protocol: TCP
  - number: 443  # Port where you would want to connect
    name: https-xxx
    protocol: HTTPS    
  resolution: STATIC
  location: MESH_EXTERNAL
```

### Version

```Text
istioctl version
client version: 1.22.7
control plane version: 1.22.7
data plane version: 1.22.7 (220 proxies)

kubectl version
Client Version: v1.28.13
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.9
```
