### ISSUE TITLE
WASMPlugin Output Attribute Giving Unkown for Every Response

### ISSUE THREAD

**Issue by RishabhKumarGupta** [istio/istio#54870]
I have upgraded istio version from 1.23.1 to 1.24.2 and after the upgrade not getting the proper response in the `istio_request_total metrics` for every request the `request_operation` is giving unkown, The same configuration is working with istio 1.23.1. Is anything change in the upgrade which is causing the issue ?

````yaml
`apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: wasmplugin-reviews
spec:
  selector:
    matchLabels:
      app: reviews
  url: https://storage.googleapis.com/istio-build/proxy/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    attributes:
    - output_attribute: istio_operationId
      match:
        - value: "GetReviews"
          condition: "request.url_path.matches('^/reviews/[[:alnum:]]*$') && request.method == 'GET'"

---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: telemtry-reviews
spec:
  selector:
    matchLabels:
      service.istio.io/canonical-name: reviews
  metrics:
    - providers:
        - name: prometheus
    - overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT
          tagOverrides:
            request_operation:
              value: istio_operationId
````

**Comment by RishabhKumarGupta** [comment]
@zirain Can you please help here

**Comment by RishabhKumarGupta** [comment]
Can anyone else please help with this issue ?

**Comment by zirain** [comment]
this sounds like related to the refacor, will take a look after holidays.

**Comment by RishabhKumarGupta** [comment]
@zirain , Thanks for your response, this is currently causing us to upgrade to 1.24.2 and we have clients which needs istio to be upgraded.  So can you please provide the time when this change can be expected so we can notify the same to clients.

**Comment by RishabhKumarGupta** [comment]
@zirain, I have tried the below configuration and that is still giving unknown reponse.

```yaml

apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: wasmplugin-productpage
spec:
  selector:
    matchLabels:
      app: productpage
  {{- if .Values.wasmOCI.enabled }}
  url: oci://{{ default "slbcentraldev.azurecr.io" .Values.global.containerRegistry }}/wasm/istio/proxy/attributegen:359dcd3a19f109c50e97517fe6b1e2676e870c4d
  imagePullSecret: image-pull-secret
  {{- else }}
  url: https://storage.googleapis.com/istio-build/proxy/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
  {{- end }}
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    attributes:
    - output_attribute: istio_operationId
      match:
        - value: "ListProductpage"
          condition: "request.url_path == '/productpage' && request.method == 'GET'"
        - value: "GetGiveme5"
          condition: "request.url_path == '/giveme5' && request.method == 'GET'"

---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: telemtry-productpage
spec:
  selector:
    matchLabels:
      service.istio.io/canonical-name: productpage
  metrics:
    - providers:
        - name: prometheus
    - overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT
          tagOverrides:
            request_operation:
              value: filter_state['wasm.istio_operationId']

```

**Comment by zirain** [comment]
existing metric will be.there until you rollout/restart the pod.

**Comment by RishabhKumarGupta** [comment]
@zirain Even after the pod/deployment restart it is giving the unkown response

**Comment by zirain** [comment]
please double check you listener configuration with:
```
istioctl pc l <pod> -n <pod_namespace> --port 9080
```

**Comment by RishabhKumarGupta** [comment]
@zirain, I checked the listener configuration 


`istioctl pc l  productpage-v1-589b64c4fb-2666h -n sample-bookinfo --port 9080
ADDRESSES PORT MATCH                                DESTINATION
0.0.0.0   9080 Trans: raw_buffer; App: http/1.1,h2c Route: 9080
0.0.0.0   9080 ALL                                  PassthroughCluster
`

**Comment by zirain** [comment]
please follow this [doc](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/), and it works as expected.
I don't understand why you change the orginal configuration, but something maybe wrong.

**Comment by ricoberger** [comment]
I can confirm that it is working for us with the mentioned change:

```yaml
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: envoy
  metrics:
    - overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_operation:
              value: filter_state['wasm.istio_operationId']
        - match:
            metric: REQUEST_DURATION
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_operation:
              value: filter_state['wasm.istio_operationId']
        - match:
            metric: REQUEST_SIZE
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_operation:
              value: filter_state['wasm.istio_operationId']
      providers:
        - name: prometheus

---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: push-notifications-istio-attributegen-filter
  namespace: push-notifications
spec:
  selector:
    matchLabels:
      app: push-notifications
  url: https://storage.googleapis.com/istio-build/proxy/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    attributes:
      - output_attribute: "istio_operationId"
        match:
          - value: GetHealth
            condition: request.url_path == '/health' && request.method == 'GET'
          - value: GetMetrics
            condition: request.url_path == '/metrics' && request.method == 'GET'
```
