### ISSUE TITLE
Requests get "connection timeout" during rolling restart of Ingress Gateway with externalTrafficPolicy set to Local

### ISSUE THREAD

**Issue by ivanchuchulski** [istio/istio#54905]
Hello, 

We're deploying Ingress Gateway as a Helm chart (gateway-1.22.1) and we're setting an option that sets the property "externalTrafficPolicy" of the Load Balancer service to "Local", in order to achieve preservation of the source IP of incoming requests.

We've read the recommendations: https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client and we're deploying the Gateway with autoscaling with the min number of replicas equal to the number of Nodes and podAntiAffinity based on Node availability zone labels.

However, we're observing, that during a rolling restart of the Gateway Deployment, there are failing requests with connect timeout. We've managed to reproduce this behavior when the connection timeout of the requests is around 2 seconds.

We've tested on K8s version 1.30, which has the ProxyTerminatingEndpoints feature, https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/, that should help with the situation, as initially described in the following issue: https://github.com/kubernetes/kubernetes/issues/85643.

Nonetheless, when the container in the Pod enters a Terminating state, the healthcheck of the Pod is returning 200 and thus the corresponding entry in the EndpointSlices has the "serving" condition property set to true, up until the Pod is terminated. This means, that if traffic is received on the Node it would be forwarded to the Terminating Pod, and that could eventually cause a failure.

There isn't a readiness probe defined in the Deployment spec, but observing the actual Pod, reveals that somehow one is being set like so:

```yaml
readinessProbe:
  failureThreshold: 4
  httpGet:
    path: /healthz/ready
    port: 15021
    scheme: HTTP
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
```

I'd like to ask the following questions:
1. What component is setting the readiness probe in the Pod, when it's not defined in the Deployment spec? Can those parameters be adjusted?
2. Why is the behavior of the readiness probe such that is returns 200, when the Pod enters a Terminating state? Shouldn't it start returning something different that 200, when a SIGTERM is received, when the Pod is marked for deletion?
3. How come making a call to the readiness probe path return 200, even 10 minutes (I stopped the loop after that time) after the Pod is gone from the cluster?
4. Could you provide insight of some other configurations we've missed or we can try to ensure that the incoming requests are not failing during the rolling update of the Gateway Deployment?

Best Regards,
Ivan

**Comment by ivanchuchulski** [comment]
Hello, 

Here are steps to reproduce the issue:
0. Ensure a cluster that has at least 2 nodes. I've managed to reproduce it on AWS cluster.
1. Deploy Istio via Helm charts, tested with versions 1.22.1 - base, istiod, ingress, cni. Ensure there are multiple replicas and anti affinity activated:
```yaml
autoscaling:
  minReplicas: <number_of_nodes>
  maxReplicas: <2*number_of_nodes>
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "topology.kubernetes.io/zone"
          labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                  - "istio-ingressgateway"
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  externalTrafficPolicy: Local
```
3. Create a sample Deployment: https://github.com/istio/istio/blob/master/samples/httpbin/httpbin.yaml
4.  Expose the workload with a Gateway with a VirtualService. The following from the official docs should be relevant: https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#configuring-ingress-using-a-gateway
5.  Setup repeated calls to the endpoint with fortio tool for example: `fortio load -qps 0 -c 300 -t 60s -H "Connection: close"  http://<lb-address>`
6. Trigger a rollout-restart of the Gateway Deployment via `kubectl rollout restart deployment <istio-deployment-name>`

Best Regards,
Ivan
