### ISSUE TITLE
HTTPRoute: unable to add path prefix via URLRewrite

### ISSUE THREAD

**Issue by GDXbsv** [istio/istio#54920]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

It doesn't seem to be possible to add a path prefix via URLRewrite when using HTTPRoute. 

Using the following matches/filters in a rule, I'd expect:
1. call `http://domain.com/product` from browser
2. HTTPRoute call my service with `/public/product`

But actually in my service I see `/publicproduct`

If I call `http://domain.com//product`  then service see a correct `/public/product`

```
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: service
          port: 80
          weight: 1
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /public/
              type: ReplacePrefixMatch
      matches:
        - path:
            type: PathPrefix
            value: /

```

### Version

```Text
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.0-eks-5ca49cb

helm.sh/chart=istiod-1.24.2
istio/pilot:1.24.2-distroless
```
