### ISSUE TITLE
Some Gateway API config errors do not propagate to resource status field

### ISSUE THREAD

**Issue by dudicoco** [istio/istio#54946]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When making misconfiguration for some fields within HTTPRoute, the errors do not propagate to the resource status field.
For example, non-existing backend port or non-existing gateway do not propagate to the status field. Non-existing service does propagate to the status field.

To reproduce:
1. Create an HTTPRoute:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example
  hostnames:
  - example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: my-app
      port: 8080
```
2. Change the backend port to a non-existing port
3. Check the resource status field to verify that no errors appear
4. Revert the change
5. Change the parentRefs gateway name to a non-existent gateway
6. Check the resource status field - it is now totally empty
7. Revert the change
8. Change the backend service name to a non-existent service
9. Check the resource status field - an error should appear

### Version

```Text
$ istioctl version                 
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (2 proxies)

$ kubectl version --short
Client Version: v1.26.15
Kustomize Version: v4.5.7
Server Version: v1.29.12-eks-2d5f260
```
