### ISSUE TITLE
Resource status analysis warnings/errors do not disappear

### ISSUE THREAD

**Issue by dudicoco** [istio/istio#54945]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

After enabling resources status analysis messages by setting the environment variable `PILOT_ENABLE_ANALYSIS: true` within the istiod container, any warning/error messages which appear in a resource status field will not disappear after getting resolved.

To reproduce:
1. Enable resources status analysis messages
2. Create a VS:
```yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: my-app
spec:
  gateways:
  - my-gateway
  hosts:
  - example.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: my-app.kube-system.svc.cluster.local
        port:
          number: 8080
```
3. Change the gateway's name to a non-existing gateway
4. Confirm that you see errors within the VS status
5. Revert the gateway name to the correct gateway
6. Check the VS status - the errors do not disappear

### Version

```Text
$ istioctl version                 
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (2 proxies)

$ kubectl version --short
Client Version: v1.26.15
Kustomize Version: v4.5.7
Server Version: v1.29.12-eks-2d5f260
```
