### ISSUE TITLE
Can't specify Gateway image tag in 1.24

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#54955]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We get a helm error with the following IstioOperator

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: install
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        tag: "special-tag"
```

```bash
$ out/linux_amd64/istioctl manifest generate --dry-run -f iop.yaml
Error: helm render: render chart: template: istio-ingress/templates/deployment.yaml:43:48: executing "istio-ingress/templates/deployment.yaml" at <index $gateway.labels "app.kubernetes.io/version">: error calling index: index of untyped nil
```

Seems like everything works fine if I give it an empty labels:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: install
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        tag: "special-tag"
        labels: {}
```

Originally, I thought the cause is because `DeepClone` turns empty maps into null in render/manifest.go:203. But what's really bizarre is that commit ab87e9c671d2b4b257dc5db18c97224d19ecaf27 introduced this error, so the null transformation was already happening. The commit just bumped go.mod deps and none of them seem to be directly related to helm.

### Version

```Text
Istio is not present in the cluster: unable to retrieve Pods: the server rejected our request for an unknown reason (get pods)
client version: 1.24.2
```
