### ISSUE TITLE
Istio overrides the traceparent header that's created in EnvoyFilter

### ISSUE THREAD

**Issue by namm2** [istio/istio#54977]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I'm using Istio behind a Google Load Balancer and wanted to transform the trace Id that's created Google in the X-Cloud-Trace-Context header to the W3C standard `traceparent` like in this article https://dzone.com/articles/transforming-proprietary-trace-context . But there's an issue: Istio overrides the `traceparent` header that's created by EnvoyFilter by a newly generated one. 

I verified this behaviour by modify the script to clone the `traceparent` header to another `x-traceparent` header:

<details><summary>EnvoyFilter</summary>
<p>

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gcp-trace-context-transformer-gateway
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
    patch:
      operation: INSERT_BEFORE
      value: 
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)

              local z = request_handle:headers():get("traceparent")
              if z ~= nil then
                return
              end

              local x = request_handle:headers():get("x-cloud-trace-context")
              if x == nil then
                return
              end

              local y = string.gmatch(x, "%x+")
              local traceid = y()
              if (traceid == nil) then
                return
              end

              request_handle:headers():add("x-trace-id", traceid)

              -- generate a new 16 hex-character random span
              math.randomseed(os.time())
              local parentid = math.random(0xffffffff, 0x7fffffffffffffff)
              local traceparent = string.format("00-%s-%016x-01", traceid, parentid)
              request_handle:headers():add("x-traceparent", traceparent)

            end

            function envoy_on_response(response_handle)
              return
            end
```

</p>
</details> 

<details><summary>meshConfig</summary>
<p>

```yaml
  extensionProviders:
    - name: file-json
      envoyFileAccessLog:
        path: /dev/stdout
        logFormat:
          labels:
            "start_time": "[%START_TIME%]"
            "method": "%REQ(:METHOD)%"
            # log path without query parameter as they may contain PII
            # "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            "path": "%REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            "protocol": "%PROTOCOL%"
            "response_code": "%RESPONSE_CODE%"
            "response_flags": "%RESPONSE_FLAGS%"
            "response_code_details": "%RESPONSE_CODE_DETAILS%"
            "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%"
            "failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
            "bytes_received": "%BYTES_RECEIVED%"
            "bytes_sent": " %BYTES_SENT%"
            "duration": "%DURATION%"
            "envoy_upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
            "forwarded_for": "%REQ(X-FORWARDED-FOR)%"
            "user_agent": "%REQ(USER-AGENT)%"
            "request_id": "%REQ(X-REQUEST-ID)%"
            "authority": "%REQ(:AUTHORITY)%"
            "host": "%UPSTREAM_HOST%"
            "upstream_cluster": "%UPSTREAM_CLUSTER%"
            "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%"
            "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%"
            "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%"
            "requested_server_name": "%REQUESTED_SERVER_NAME%"
            "route_name": "%ROUTE_NAME%"
            "cloud_trace_context": "%REQ(X-CLOUD-TRACE-CONTEXT)%"
            "traceparent": "%REQ(TRACEPARENT)%"
            "tracestate": "%REQ(TRACESTATE)%"
            "trace_id": "%REQ(X-TRACE-ID)%"
            "x_traceparent": "%REQ(X-TRACEPARENT)%"
```

</p>
</details> 

Then as I suspected: the `x-traceparent` header contains the trace Id that's collected from the x-cloud-trace-context, but the `traceparent` header is not.

```json
{
    "duration": 15,
    "host": "10.24.5.13:9080",
    "downstream_local_address": "10.24.3.44:80",
    "bytes_received": 0,
    "traceparent": "00-856192fa39549336e16f35a517d9e471-affa68b5f2c31aeb-01",
...
    "request_id": "8a28fc8f-3a56-9c75-9b70-495596933558",
    "route_name": null,
    "x_traceparent": "00-c4b5308189dcf1573ed01c2cf856c819-67ff51203d067c00-01",
...
    "cloud_trace_context": "c4b5308189dcf1573ed01c2cf856c819/11831666918529767904",
    "response_code_details": "via_upstream",
    "trace_id": "c4b5308189dcf1573ed01c2cf856c819",
...
}
```

Is it possible for Istio to respect the previously created header(s) in the HTTP_FILTER like this one?

### Version

```Text
istioctl version
client version: 1.23.4
control plane version: 1.24.2
data plane version: 1.24.2 (2 proxies)
```
