### ISSUE TITLE
Traffic to ServiceEntry not being routed through Waypoint unless adding the addresses field

### ISSUE THREAD

**Issue by JesperBerggren** [istio/istio#54981]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hello,

I'm using Ambient mesh with Waypoints.

When I make a ServiceEntry in a namespace that has the following labels:
```
istio.io/dataplane-mode: ambient
istio.io/use-waypoint: waypoint
```
Then traffic is not routed to through the Waypoint. Only if I use TCP as protocol in the ServiceEntry,
I'm unsure if it's related to #54818 

To make it easy to reproduce I have this test namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: waypoint-test
    istio.io/dataplane-mode: ambient
  name: waypoint-test
```
Then I create the Waypoint:
```
$ istioctl waypoint apply --enroll-namespace --namespace waypoint-test
```
And then I apply the sleep pod in the namespace:
```
$ kubectl apply -f https://raw.githubusercontent.com/istio/istio/refs/heads/master/samples/sleep/sleep.yaml
```
Then I create a ServiceEntry for httpbin.org using HTTP as protocol and DNS resolution:
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: waypoint-test
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```
If a do a curl with protocol HTTP now:
```
$ kubectl exec -it -n waypoint-test sleep-74b947b6c9-mjfgb -- curl -I httpbin.org
HTTP/1.1 200 OK
```
It works but no traffic in the Waypoint - only in the Ztunnel.
On the other hand, if I update the ServiceEntry to match this:
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: waypoint-test
spec:
  addresses:
  - 3.211.25.71
  - 54.86.137.185
  hosts:
  - httpbin.org
  ports:
  - name: tcp-80
    number: 80
    protocol: TCP
```
And then do a curl with protocol TCP:
```
$ kubectl exec -it -n waypoint-test sleep-74b947b6c9-mjfgb -- curl -I httpbin.org
HTTP/1.1 200 OK
```
It still works and now I also get this log line on the Waypoint:.
```
[2025-02-05T14:05:46.771Z] "- - -" 0 - - - "-" 76 295 252 - "-" "-" "-" "-" "54.86.137.185:80" inbound-vip|80|tcp|httpbin.org 10.1.116.210:41052 54.86.137.185:80 10.1.116.254:58510 - -
```
I would very much like not to hardcode the external ServiceEntries :-)

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (5 proxies)

$ kubectl version
Client Version: v1.31.5
Kustomize Version: v5.4.2
Server Version: v1.28.15
WARNING: version difference between client (1.31) and server (1.28) exceeds the supported minor version skew of +/-1
```

**Comment by JesperBerggren** [comment]
@keithmattix I've already done that multiple times, just to make sure :)
Here's the output:

Ztunnel config:
```
$ istioctl zc services
NAMESPACE         SERVICE NAME                                   SERVICE VIP    WAYPOINT ENDPOINTS
cert-manager      cert-manager                                   10.152.183.61  None     1/1
cert-manager      cert-manager-cainjector                        10.152.183.143 None     1/1
cert-manager      cert-manager-webhook                           10.152.183.125 None     1/1
default           kubernetes                                     10.152.183.1   None     1/1
integration-tools iet-admin                                      10.152.183.186 waypoint 1/1
integration-tools iet-admin-db                                   10.30.61.20    waypoint 1/1
integration-tools redis-headless                                                waypoint 4/4
integration-tools redis-master                                   10.152.183.57  waypoint 1/1
integration-tools redis-metrics                                  10.152.183.106 waypoint 4/4
integration-tools redis-replicas                                 10.152.183.195 waypoint 3/3
integration-tools sleep                                          10.152.183.25  waypoint 1/1
integration-tools waypoint                                       10.152.183.203 None     1/1
istio-system      istiod                                         10.152.183.230 None     1/1
istio-system      servicemeshtooling-gateway-istio               10.152.183.100 None     1/1
istio-system      sleep                                          10.152.183.107 None     1/1
kiali             kiali                                          10.152.183.50  None     1/1
kube-system       coredns                                        10.152.183.10  None     1/1
kube-system       coredns-metrics                                10.152.183.121 None     1/1
kube-system       kube-prometheus-stack-coredns                                 None     0/0
kube-system       kube-prometheus-stack-kube-controller-manager                 None     0/0
kube-system       kube-prometheus-stack-kube-proxy                              None     0/0
kube-system       kube-prometheus-stack-kube-scheduler                          None     0/0
kube-system       kube-prometheus-stack-kubelet                                 None     1/1
kube-system       metrics-server                                 10.152.183.179 None     1/1
metallb-system    metallb-webhook-service                        10.152.183.36  None     1/1
monitoring        kube-prometheus-stack-grafana                  10.152.183.231 None     1/1
monitoring        kube-prometheus-stack-kube-state-metrics       10.152.183.207 None     1/1
monitoring        kube-prometheus-stack-operator                 10.152.183.102 None     1/1
monitoring        kube-prometheus-stack-prometheus               10.152.183.153 None     1/1
monitoring        kube-prometheus-stack-prometheus-node-exporter 10.152.183.232 None     1/1
monitoring        prometheus-operated                                           None     1/1
oauth2-authz      graph.microsoft.com                                           waypoint 1/1
oauth2-authz      login.microsoftonline.com                                     waypoint 1/1
oauth2-authz      login.windows.net                                             waypoint 1/1
oauth2-authz      oauth2-proxy                                   10.152.183.103 waypoint 1/1
oauth2-authz      sleep                                          10.152.183.104 waypoint 1/1
oauth2-authz      sts.windows.net                                               waypoint 1/1
oauth2-authz      waypoint                                       10.152.183.221 None     1/1
observability     jaeger-agent                                                  None     1/1
observability     jaeger-collector                               10.152.183.135 None     1/1
observability     jaeger-collector-headless                                     None     1/1
observability     jaeger-operator-metrics                        10.152.183.123 None     1/1
observability     jaeger-operator-webhook-service                10.152.183.215 None     1/1
observability     jaeger-query                                   10.152.183.206 None     1/1
platform-argocd   argocd-applicationset-controller               10.152.183.183 None     1/1
platform-argocd   argocd-dex-server                              10.152.183.164 None     1/1
platform-argocd   argocd-redis                                   10.152.183.174 None     1/1
platform-argocd   argocd-repo-server                             10.152.183.84  None     1/1
platform-argocd   argocd-server                                  10.152.183.96  None     1/1
waypoint-test     httpbin.org                                                   waypoint 1/1
waypoint-test     sleep                                          10.152.183.44  waypoint 1/1
waypoint-test     waypoint                                       10.152.183.93  None     1/1
```

Ztunnel logs:
```
$ kubectl exec -it sleep-74b947b6c9-mjfgb -n waypoint-test -- curl -I httpbin.org
HTTP/1.1 200 OK
Date: Thu, 06 Feb 2025 09:26:03 GMT
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Length: 9593
Content-Type: text/html; charset=utf-8
Via: 1.1 wsa01.atp.kmdnet.dk:80 (Cisco-WSA/11.8.3-021)
Connection: keep-alive

$ kubectl logs -n istio-system ztunnel-cvwnw | egrep -v "redis|argocd" | tail -n 1
2025-02-06T09:26:03.513001Z	info	access	connection complete	src.addr=10.1.116.254:50714 src.workload="sleep-74b947b6c9-mjfgb" src.namespace="waypoint-test" dst.addr=3.211.25.71:80 direction="outbound" bytes_sent=76 bytes_recv=295 duration="204ms"
```

ServiceEntry config/status:
```
$ kubectl get serviceentry httpbin.org -oyaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1","kind":"ServiceEntry","metadata":{"annotations":{},"name":"httpbin.org","namespace":"waypoint-test"},"spec":{"hosts":["httpbin.org"],"ports":[{"name":"http","number":80,"protocol":"HTTP"}],"resolution":"DNS"}}
  creationTimestamp: "2025-02-06T09:24:05Z"
  generation: 1
  name: httpbin.org
  namespace: waypoint-test
  resourceVersion: "11013768"
  uid: 8b33df91-d46f-435a-8667-dc2616b3cf6f
spec:
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
status:
  conditions:
  - lastTransitionTime: "2025-02-06T09:24:05.783710436Z"
    message: Successfully attached to waypoint waypoint-test/waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```

Namespaces with use-waypoint label:
```
$ kubectl get namespaces -L istio.io/use-waypoint
NAME                STATUS   AGE     USE-WAYPOINT
cert-manager        Active   33d     
default             Active   2y54d   
integration-tools   Active   21d     waypoint
istio-system        Active   33d     
kiali               Active   30d     
kiali-operator      Active   30d     
kube-node-lease     Active   2y54d   
kube-public         Active   2y54d   
kube-system         Active   2y54d   
metallb-system      Active   33d     
monitoring          Active   30d     
oauth2-authz        Active   30d     waypoint
observability       Active   30d     
platform-argocd     Active   33d     
waypoint-test       Active   21h     waypoint
```

Waypoint programmed?:
```
$ kubectl get gateways.gateway.networking.k8s.io
NAME       CLASS            ADDRESS         PROGRAMMED   AGE
waypoint   istio-waypoint   10.152.183.93   True         20h
```

**Comment by JesperBerggren** [comment]
Ok, I've debugged some more, and it's not really the protocol that defines if it works or not.

No matter if protocol is TCP, HTTP or TLS then it works if _addresses_ is added to the ServiceEntry.

E.g. traffic to this ServiceEntry is routed through the Waypoint (notice the addresses field):
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1","kind":"ServiceEntry","metadata":{"annotations":{},"name":"httpbin.org","namespace":"waypoint-test"},"spec":{"hosts":["httpbin.org"],"ports":[{"name":"http","number":80,"protocol":"HTTP"}],"resolution":"DNS"}}
  creationTimestamp: "2025-02-06T09:24:05Z"
  generation: 2
  name: httpbin.org
  namespace: waypoint-test
  resourceVersion: "11043128"
  uid: 8b33df91-d46f-435a-8667-dc2616b3cf6f
spec:
  addresses:
  - 54.86.137.185
  - 3.211.25.71
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
status:
  conditions:
  - lastTransitionTime: "2025-02-06T12:45:01.669638140Z"
    message: Successfully attached to waypoint waypoint-test/waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```
If the addresses field is removed then it stops working again.

**Comment by keithmattix** [comment]
Ok yep this is what I suspected; the ztunnel config confirmed it so thanks for uploading it! You need either DNS proxying or service entry autoallocation (probably both?) on for this to work: https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#address-auto-allocation. Without a VIP, ztunnel has no way to know what service your connection corresponds to because it can't read the host header of your request. Configuring those two should make this work without you manually setting addresses

**Comment by JesperBerggren** [comment]
@keithmattix Well, I've read (and re-read) the documentation and implemented as suggested but it still doesn't work.

First I tried the _Address auto allocation_ as described in your link. It did not work.

Then I tried the _DNS Auto Allocation V2_ as described here: https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#dns-auto-allocation-v2. We are using Istio v. 1.24.2.

It did not work either. I tried setting _networking.istio.io/enable-autoallocate-ip_ to both _true_ and _false_. It did not have any effect at all.

My istio configmap:
```
apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: ""
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_ENABLE_HBONE: "true"
      tracing:
        sampling: 100
        zipkin:
          address: jaeger-collector.observability.svc.cluster.local:9411
    defaultProviders:
      metrics:
      - prometheus
    defaultServiceExportTo:
    - .
    enablePrometheusMerge: true
    extensionProviders:
    - envoyExtAuthzHttp:
        headersToDownstreamOnDeny:
        - content-type
        - set-cookie
        headersToUpstreamOnAllow:
        - authorization
        - path
        - x-auth-request-user
        - x-auth-request-email
        - x-auth-request-access-token
        includeHeadersInCheck:
        - authorization
        - cookie
        port: "4180"
        service: oauth2-proxy.oauth2-authz.svc.cluster.local
      name: oauth2-proxy
    meshMTLS:
      minProtocolVersion: TLSV1_2
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
  creationTimestamp: "2025-01-03T14:35:03Z"
  labels:
    app.kubernetes.io/instance: istio-istiod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.24.2
    argocd.argoproj.io/instance: istio
    helm.sh/chart: istiod-1.24.2
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio-istiod
  name: istio
  namespace: istio-system
```
And my environment variables on istiod:
```
    Environment:
      REVISION:                      default
      PILOT_CERT_PROVIDER:           istiod
      POD_NAME:                      istiod-75647d6d89-2bg4z (v1:metadata.name)
      POD_NAMESPACE:                 istio-system (v1:metadata.namespace)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      KUBECONFIG:                    /var/run/secrets/remote/config
      CA_TRUSTED_NODE_ACCOUNTS:      istio-system/ztunnel
      PILOT_ENABLE_AMBIENT:          true
      PILOT_ENABLE_IP_AUTOALLOCATE:  true
      PILOT_TRACE_SAMPLING:          100
      PILOT_ENABLE_ANALYSIS:         false
      CLUSTER_ID:                    Kubernetes
      GOMEMLIMIT:                    node allocatable (limits.memory)
      GOMAXPROCS:                    node allocatable (limits.cpu)
      PLATFORM:                      
```
My ServiceEntry:
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  creationTimestamp: "2025-02-06T09:24:05Z"
  generation: 3
  labels:
    networking.istio.io/enable-autoallocate-ip: "true"
  name: httpbin.org
  namespace: waypoint-test
  resourceVersion: "11244426"
  uid: 8b33df91-d46f-435a-8667-dc2616b3cf6f
spec:
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
status:
  addresses:
  - host: httpbin.org
    value: 240.240.0.5
  - host: httpbin.org
    value: 2001:2::5
  conditions:
  - lastTransitionTime: "2025-02-07T11:09:16.252773466Z"
    message: Successfully attached to waypoint waypoint-test/waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```
When I do the curl it looks like it's still just doing it's external DNS lookup. I would suspect it should be the 240.240.0.5 from the addresses field in the status of the ServiceEntry!?
```
$ kubectl exec -it sleep-5d58d9d4bb-tm9pv -- curl -v http://httpbin.org
* Host httpbin.org:80 was resolved.
* IPv6: (none)
* IPv4: 3.230.67.98, 3.211.25.71
*   Trying 3.230.67.98:80...
* Connected to httpbin.org (3.230.67.98) port 80
* using HTTP/1.x
> GET / HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/8.12.0
> Accept: */*
...
```
By the way. The output from the curl command is completely identical no matter if I set:
```
  labels:
    networking.istio.io/enable-autoallocate-ip: "true"
```
or
```
  labels:
    networking.istio.io/enable-autoallocate-ip: "false"
```
or simply just omit the label all together.

**Comment by keithmattix** [comment]
@ilrudie knows more about this feature than I do, but turning on dns proxing probably requires a ztunnel restart? Let me know if you did that already; the fact you get the external ip implies that the redirection may not be working

**Comment by JesperBerggren** [comment]
Hi @keithmattix and @ilrudie Yes, I've restarted ztunnel. I've also tried to restart istiod, waypoints.... and just to be sure every single deployment in the cluster :)

**Comment by ilrudie** [comment]
Reading through the issue now and I'll investigate. Thanks for the detailed information.

**Comment by ilrudie** [comment]
@JesperBerggren, Trying locally with the steps you showed (and strictly following the instructions) I get ztunnel configured correctly but ambient DNS capture isn't enabled so ServiceEntries don't behave as you might expect. This is just a bug/flaw in our instructions. In 1.25 it should be ok because dnsCapture in enabled out of the box with the ambient profile but 1.24 requires `--set values.cni.ambient.dnsCapture=true` (if using istioctl installation, set the equivalent value in the values.yaml if using helm) and this is not present on the instructions, which are more oriented towards the sidecar data plane.

With ambient DNS capture enabled things should work as expected with DNS Autoallocation V2.

```yaml
$ kubectl get configmaps -n istio-system istio-cni-config -o yaml
apiVersion: v1
data:
  AMBIENT_DNS_CAPTURE: "true"
  AMBIENT_ENABLED: "true"
  AMBIENT_IPV6: "true"
  CHAINED_CNI_PLUGIN: "true"
  CURRENT_AGENT_VERSION: 1.24.2
  EXCLUDED_NAMESPACES: kube-system
  REPAIR_BROKEN_POD_LABEL_KEY: cni.istio.io/uninitialized
  REPAIR_BROKEN_POD_LABEL_VALUE: "true"
  REPAIR_DELETE_PODS: "false"
  REPAIR_ENABLED: "true"
  REPAIR_INIT_CONTAINER_NAME: istio-validation
  REPAIR_LABEL_PODS: "false"
  REPAIR_REPAIR_PODS: "true"
kind: ConfigMap
...
```
This is what your cni config should look like when setup correctly. Note the value of `AMBIENT_DNS_CAPTURE` which is the operative field here and it set during installation from the value mentioned above.
