### ISSUE TITLE
Issue with Istio ServiceEntry: Same Host, Different Port, and Resolutions

### ISSUE THREAD

**Issue by srmars** [istio/istio#54988]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

**Summary:**
In Istio version 1.24.1, when defining multiple ServiceEntry resources with the same host but differing port and resolutions, unexpected behaviors occur. Specifically, when one ServiceEntry uses resolution: NONE and another uses resolution: DNS, leading to connectivity issues.

**Steps to Reproduce:**
Create a ServiceEntry with the following configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-entry-1
spec:
  addresses:
  - "192.168.1.100"
  exportTo:
  - "."
  hosts:
    - "example.com"
  ports:
    - number: 9093
      name: https-example
      protocol: HTTPS
  resolution: NONE
```
Create another ServiceEntry with the same host but different port and resolution:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example-service-entry-2
spec:
  exportTo:
  - "."
  hosts:
  - "example.com" 
  ports:
  - number: 443
    name: https-example
    protocol: HTTPS
  resolution: DNS
```
**Current Behavior in 1.24.1:**
Ex:
- Successful Connection: The connection to example.com:9093 works as expected.
- Failed Connection: The connection to example.com:443 fails.
- Istio Access Log: For the failed connection, the Istio access log shows the error NC (NoClusterFound)

### Version

```Text
Istio Version: 1.24.1
Kubernetes Version: 1.30.X
```

**Comment by howardjohn** [comment]
I can reproduce this. Thanks for the report

**Comment by srmars** [comment]
Thank you for the update, Will this issue be fixed in 1.24.3?

**Comment by howardjohn** [comment]
No, 1.24.3 just shipped and this issue occurs in the lastest code.

**Comment by kalyanteja19** [comment]
> No, 1.24.3 just shipped and this issue occurs in the lastest code.

Hi @howardjohn , We are seeing above issue in istio 1.22.7 version, can you please confirm if issue is expected in that version too?

**Comment by srmars** [comment]
@howardjohn which version this will be fixed

**Comment by howardjohn** [comment]
@srmars there is no fix currently developed. So that question cannot be answered.

**Comment by srmars** [comment]
Could you please let me know, is there any future plan for the fix in 1.24.x

In out cluster lot of service entry having this pattern

Any workaround would be appreciated

**Comment by howardjohn** [comment]
The technical explanation is egressListenerServices has both but servicesByHostname has only one.

Behavior across versions:

```
1.23 no sidecar: only 9093 has config at all
1.23 with sidecar: listener has 9093 and 443, cluster only 9093

1.24.3, 1.25.0, master: listener has 9093 and 443, cluster only 9093
```

So this wasn't really ever "working" as far as I can. The only case someone could be working on older version and broken on newer version is if they had a config completely ignored; if so, the easy path forward is to remove the duplicate config.

We likely still want consistency between cluster and listener path here but I don't think this is a regression.

**Comment by srmars** [comment]
We did not faced this issue in 1.20.x

**Comment by srmars** [comment]
lifecycle/staleproof

**Comment by robertbublik** [comment]
We are running Istio 1.25.2 and have a similar issue. We had two `ServiceEntry`s like this:

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: github.com-22
spec:
  exportTo:
  - .
  hosts:
  - github.com
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 22
    protocol: TCP
  resolution: DNS
```

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: github.com-443
spec:
  exportTo:
  - .
  hosts:
  - github.com
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 443
    protocol: TCP
  resolution: DNS
```

When I try to download something in a pod sidecar from github.com on port 443 I would get the following error: `curl: (35) Recv failure: Connection reset by peer`.

After running `istioctl proxy-config cluster` on the corresponding pod we only saw one cluster created for the 22 port. Trying to reach github.com on port 443 also printed the following log:

> {"clientDuration":86,"clientIPs":null,"method":null,"path":null,"protocol":null,"responseCode":0,"targetDuration":null,"tenantId":null,"traceId":null,"traceparent":null,"upstreamHost":"140.82.121.3:443","upstreamName":"PassthroughCluster;"}

Our temporary fix is to create the second entry as www.github.com which fortunately works with Github but won't work if hosts don't have www setup as subdomain.
