### ISSUE TITLE
Envoy stat monitor duplicated metrics - part II

### ISSUE THREAD

**Issue by pecastro** [istio/istio#54986]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Using Prometheus: 2.52.0

Running Istio in a K8s cluster with metric merging.

We find intermittent issues scrapping metrics in some of the pods in the istio mesh.

```
[pod/prometheus-prometheus-kube-prometheus-prometheus-2/prometheus] 2025-02-03T16:47:03.980211264Z ts=2025-02-03T16:47:03.980Z caller=scrape.go:1738 level=warn component="scrape manager" scrape_pool=podMonitor/monitoring/envoy-stats/0 target=http://100.116.73.204:15020/stats/prometheus msg="Error on ingesting samples with different value but same timestamp" num_dropped=4
```

Sometimes all of the pods in a given deployment will suddenly start exhibiting this issue after having been running without issues for hours.
In other cases only a single pod of a deployment will start showing this behavior.

Deeper investigation as led to 4 specific istio metrics being at fault.

```
istio_tcp_connections_closed_total
istio_tcp_connections_opened_total
istio_tcp_received_bytes_total
istio_tcp_sent_bytes_total
```

These metrics are being exposed with duplicate labels and a different value during the scrapes which leads Prometheus to complain about the same timestamp.

```
"curl http://100.117.80.12:15020/stats/prometheus" | grep -E "(istio_tcp_connections_closed_total|istio_tcp_connections_opened_total|istio_tcp_received_bytes_total|istio_tcp_sent_bytes_total)" | grep -v "^#" | grep "istio_tcp_received_bytes_total"

istio_tcp_received_bytes_total{reporter="source",source_workload="cid-sync-soap-routing-service",source_canonical_service="cid-sync-soap-routing-service",source_canonical_revision="1.16.0",source_workload_namespace="if-corp-sync",source_principal="spiffe://cluster.local/ns/if-corp-sync/sa/cid-sync-soap-routing-service",source_app="",source_version="",source_cluster="Kubernetes",destination_workload="rabbitmq-core-server",destination_workload_namespace="rabbitmq-server",destination_principal="spiffe://cluster.local/ns/rabbitmq-server/sa/rabbitmq-core-server",destination_app="unknown",destination_version="unknown",destination_service="rabbitmq-core.rabbitmq-server.svc.cluster.local",destination_canonical_service="rabbitmq-core",destination_canonical_revision="latest",destination_service_name="rabbitmq-core",destination_service_namespace="rabbitmq-server",destination_cluster="Kubernetes",request_protocol="tcp",response_flags="-",connection_security_policy="unknown"} 480082
istio_tcp_received_bytes_total{reporter="source",source_workload="cid-sync-soap-routing-service",source_canonical_service="cid-sync-soap-routing-service",source_canonical_revision="1.16.0",source_workload_namespace="if-corp-sync",source_principal="spiffe://cluster.local/ns/if-corp-sync/sa/cid-sync-soap-routing-service",source_app="",source_version="",source_cluster="Kubernetes",destination_workload="rabbitmq-core-server",destination_workload_namespace="rabbitmq-server",destination_principal="spiffe://cluster.local/ns/rabbitmq-server/sa/rabbitmq-core-server",destination_app="unknown",destination_version="unknown",destination_service="rabbitmq-core.rabbitmq-server.svc.cluster.local",destination_canonical_service="rabbitmq-core",destination_canonical_revision="latest",destination_service_name="rabbitmq-core",destination_service_namespace="rabbitmq-server",destination_cluster="Kubernetes",request_protocol="tcp",response_flags="-",connection_security_policy="unknown"} 8
istio_tcp_received_bytes_total{reporter="source",source_workload="cid-sync-soap-routing-service",source_canonical_service="cid-sync-soap-routing-service",source_canonical_revision="1.16.0",source_workload_namespace="if-corp-sync",source_principal="unknown",source_app="",source_version="",source_cluster="Kubernetes",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app="unknown",destination_version="unknown",destination_service="unknown",destination_canonical_service="unknown",destination_canonical_revision="latest",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",destination_cluster="unknown",request_protocol="tcp",response_flags="UH",connection_security_policy="unknown"} 0
```

This bug is the second part of #52221

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.1
data plane version: 1.24.1 (72 proxies)

$ kubectl version --short 
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.7
Kustomize Version: v5.0.1
Server Version: v1.30.8-eks-2d5f260
```

**Comment by MaliFotouhi** [comment]
Thank you for reopening this issue. I can confirm that this problem persists even in the latest version of Istio, specifically affecting TCP metrics. After thoroughly examining all metrics on the pods, I've observed that no other metrics show duplication within the same timestamp.

Interestingly, for each attempt, the second line, which displays a lower number, remains constant. This observation leads us to suspect that the initial container on the pod might be the source of this anomaly.


```
curl localhost:8080/stats/prometheus | grep -E "(istio_tcp_connections_closed_total|istio_tcp_connections_opened_total|istio_tcp_received_bytes_total|istio_tcp_sent_bytes_total|destination_service_namespace)" | grep -v "^#" | grep "istio_tcp_connections_closed_total"

istio_tcp_connections_closed_total{reporter="source",source_workload="XX",source_canonical_service="XX",source_canonical_revision="1.24.2",source_workload_namespace="KK",source_principal="",source_app="",source_version="",source_cluster="Kubernetes",destination_workload="YY",destination_workload_namespace="YY",destination_principal="default",destination_app="unknown",destination_version="unknown",destination_service="",destination_canonical_service="",destination_canonical_revision="latest",destination_service_name="",destination_service_namespace="YY",destination_cluster="Kubernetes",request_protocol="",response_flags="-",connection_security_policy="unknown"} 11024797
istio_tcp_connections_closed_total{reporter="source",source_workload="XX",source_canonical_service="XX",source_canonical_revision="1.24.2",source_workload_namespace="KK",source_principal="",source_app="",source_version="",source_cluster="Kubernetes",destination_workload="YY",destination_workload_namespace="YY",destination_principal="default",destination_app="unknown",destination_version="unknown",destination_service="",destination_canonical_service="",destination_canonical_revision="latest",destination_service_name="",destination_service_namespace="YY",destination_cluster="Kubernetes",request_protocol="",response_flags="-",connection_security_policy="unknown"} 36
```
**Version**
```
$ istioctl version
client version: 1.18.2
control plane version: 1.24.2
data plane version: 1.24.2 (355 proxies)
```

**To summerised our observation:**

1. The issue is consistently reproducible with TCP metrics in the latest Istio version.
2. No other metrics exhibit duplication within the same timestamp.
3. The second line of the output (with the lower value) remains unchanged across multiple trials.
4. We hypothesize that the pod's initial container may be contributing to this behavior.

**Comment by howardjohn** [comment]
Is the source a sidecar?

Can you check the config dump to ensure there is no somehow a duplicate istio.stats filter?

cc @zirain

**Comment by pecastro** [comment]
The source is the istio-proxy sidecar attached to a workload pod.
The workload metrics are merged into istio's with the help of the Istio specific annotations.

Regarding the duplicate istio.stats filter, can you be a bit more specific as there are many instances of istio.stats throughout the config ?

```
./istioctl pc all affetcted-pod -o json | jq . | grep -E "istio.stats"  | wc -l
480

./istioctl pc all affected-pod -o json | jq . | grep -E "istio.stats"  | grep filter
              "name": "envoy.filters.network.istio_stats",
              "name": "envoy.filters.http.istio_stats",
```

In our particular case we've noticed that these duplicate metrics always seem to involve the same destination service.

**Comment by zirain** [comment]
can you share the config dump of one listener that contains a `istio.stats` with yaml/json output by following command:
```console
istioctl pc l -n <pod_ns> <pod_name> -oyaml --port <one of outbound port>
```

**Comment by MaliFotouhi** [comment]
I've checked the specific service with reported problems using `istioctl proxy-status`, and the Istio configuration appears to be consistent across clusters and listeners.:

```
istioctl proxy-status <service-name>                                         
Clusters Match
Listeners Match
```
We've defined 5 times istio.stats for each unique listeners and it seems the `istio.stats` filter is present in the expected locations without duplication.

```
istioctl pc all <pod-name>  -o json | jq . | grep -E "istio.stats" | wc -l
5

 istioctl pc all <pod-name> -o json | jq . | grep -E "istio.stats"        
              "name": "envoy.filters.network.istio_stats",
              "name": "envoy.filters.http.istio_stats",
                            "name": "istio.stats",
                      "name": "istio.stats",
                            "name": "istio.stats",
```

```
istioctl pc all <pod-name>  -o json | jq '. | .. | objects | select(.name? == "istio.stats")'
"dynamic_listeners": [
    {
     "name": "port1",
     "active_state": {
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "port1",
       "address": {
        "socket_address": {
         "address": "X.X.X.X",
         "port_value": 35
        },
        ....
        {
          "name": "istio.stats",
          "typed_config": {
            "@type": "type.googleapis.com/stats.PluginConfig",
            "disable_host_header_fallback": true
          }
        }
```
This a config dump of one listener that we have duplicate metrics on it. 

```
istioctl pc l <pod-name> -oyaml --port 35           

- accessLog:
  - filter:
      responseFlagFilter:
        flags:
        - NR
    name: envoy.access_loggers.file
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      logFormat:
        textFormatSource:
          inlineString: |
            [%START_TIME%] .....
      path: /dev/
  address:
    socketAddress:
      address: X.X.X.X
      portValue: 35
  filterChains:
  - filters:
    - name: istio.stats
      typedConfig:
        '@type': type.googleapis.com/stats.PluginConfig
        disableHostHeaderFallback: true
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] ...
            path: /dev/
        cluster: outbound|35||<app-svc>.svc.cluster.local
        statPrefix: outbound|35||<app-svc>.svc.cluster.local
    transportSocketConnectTimeout: 15s
  name: port1
  trafficDirection: OUTBOUND

```

**Comment by zirain** [comment]
so there's no duplicated stats filter, @MaliFotouhi may I know the protocl of the service?

**Comment by pecastro** [comment]
Hi everyone.
Any more news or insights on this ? Is there any other info I can provide ?

**Comment by pecastro** [comment]
Hi everyone.
Any thoughts or interesting suggestions of things one might try ?

**Comment by pattkrajnik** [comment]
For others facing this on 1.24.3 who need to stop the Prometheus errors (and can afford to lose these specific metrics), adding the following metricRelabelings rule to the PodMonitor spec successfully works around the issue by dropping the duplicate metrics before ingestion:
YAML

```
# Add this under spec.podMetricsEndpoints in your PodMonitor
metricRelabelings:
- sourceLabels: [ __name__ ]
  regex: 'istio_request_messages_total|istio_response_messages_total'
  action: drop
```

I've identified those duplicate metrics with `curl http://localhost:15090/stats/prometheus > envoy_metrics_output.txt` for me it were just those two, for You it might be something else.

Hope this helps others encountering the same problem while waiting for a fix in Istio itself.
