### ISSUE TITLE
[ Side car Mode ][Gateway API]When setting the revision and installing Istio, the Envoy and Gateway are not created.

### ISSUE THREAD

**Issue by riokuha** [istio/istio#54999]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When installing Istio with the revision enabled, the Istio Sidecar is not injected. Additionally, the creation of the Gateway fails.

```
$ istioctl install -f myconfig.yaml --readiness-timeout 600m --set revision=$( date +%F )
$ kubectl get all -n istio-system 
NAME                                     READY   STATUS    RESTARTS   AGE
pod/istio-cni-node-2r7fd                 1/1     Running   0          45s
pod/istio-cni-node-cpl66                 1/1     Running   0          45s
pod/istiod-2025-01-31-6fb57bff58-tgnpj   1/1     Running   0          49s

NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
service/istiod-2025-01-31   ClusterIP   172.20.34.169   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP   50s

NAME                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/istio-cni-node   2         2         2       2            2           kubernetes.io/os=linux   46s

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istiod-2025-01-31   1/1     1            1           50s

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/istiod-2025-01-31-6fb57bff58   1         1         1       50s

NAME                                                    REFERENCE                      TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istiod-2025-01-31   Deployment/istiod-2025-01-31   cpu: 0%/80%   1         5         1          50s

$ kubectl label ns bookinfo istio-injection=enabled
namespace/bookinfo labeled

$ kubectl -n bookinfo apply -f samples/bookinfo/platform/kube/bookinfo.yaml
service/details created
serviceaccount/bookinfo-details created
deployment.apps/details-v1 created
service/ratings created
serviceaccount/bookinfo-ratings created
deployment.apps/ratings-v1 created
service/reviews created
serviceaccount/bookinfo-reviews created
deployment.apps/reviews-v1 created
deployment.apps/reviews-v2 created
deployment.apps/reviews-v3 created
service/productpage created
serviceaccount/bookinfo-productpage created
deployment.apps/productpage-v1 created

$ kubectl get pod
NAME                             READY   STATUS    RESTARTS   AGE
details-v1-79dfbd6fff-f2dlz      1/1     Running   0          6s
productpage-v1-dffc47f64-mtwfg   1/1     Running   0          6s
ratings-v1-65f797b499-k9hf2      1/1     Running   0          6s
reviews-v1-5c4d6d447c-zm5hq      1/1     Running   0          6s
reviews-v2-65cb66b45c-x6bvx      1/1     Running   0          6s
reviews-v3-f68f94645-2gdnt       1/1     Running   0          6s

$ kubectl apply -f bookinfo-gateway-with-annotaion.yaml 
gateway.gateway.networking.k8s.io/bookinfo-gateway created
httproute.gateway.networking.k8s.io/bookinfo created

$ kubectl -n bookinfo get gtw,httproute
NAME                                                 CLASS   ADDRESS   PROGRAMMED   AGE
gateway.gateway.networking.k8s.io/bookinfo-gateway   istio             False        40s

NAME                                           HOSTNAMES   AGE
httproute.gateway.networking.k8s.io/bookinfo               40s
```

### Version

```Text
$ kubectl version
Client Version: v1.29.0-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.4-eks-2d5f260

$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
```

### Additional Information

myconfig.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY  # or REGISTRY_ONLY
    defaultConfig:
      tracing:
        sampling: 100.0
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: "true"
  components:
    cni:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
```

bookinfo-gateway-with-annotaion.yaml
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo-gateway
  rules:
  - matches:
    - path:
        type: Exact
        value: /productpage
    - path:
        type: PathPrefix
        value: /static
    - path:
        type: Exact
        value: /login
    - path:
        type: Exact
        value: /logout
    - path:
        type: PathPrefix
        value: /api/v1/products
    backendRefs:
    - name: productpage
      port: 9080
```

[bug-report.tar.gz](https://github.com/user-attachments/files/18699789/bug-report.tar.gz)
[istioctl_manifestgenerate.txt](https://github.com/user-attachments/files/18699788/istioctl_manifestgenerate.txt)
