### ISSUE TITLE
Issue with duplicate ServiceEntry

### ISSUE THREAD

**Issue by srmars** [istio/istio#54990]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

**Summary:**
In Istio 1.24.1, when defining multiple ServiceEntry resources with overlapping IP addresses, Istio skipping adding ServiceEntry address to the listener.

Example:-
ServiceEntry 1 - [**a**] --> Able to see the IP[a] in the listener
ServiceEntry 2 - [b] --> Able to see the IP[b] in the listener
ServiceEntry 3 - [**a**,c,b] --> Not Able to see the IP's[c] in the listener and the connection to the "c" is blocked.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tcp-service-entry
spec:
  hosts:
  - "example-host.com"  # Updated with example host
  addresses:
  - "192.168.1.1"  # Replace with the IP address if needed, or use the host
  ports:
  - number: 12345  # Replace with the appropriate port number
    name: tcp-port
    protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tcp-service-entry-2
spec:
  hosts:
  - "example-host.com"  # Updated with example host
  addresses:
  - "192.168.1.2"  # Replace with the IP address if needed, or use the host
  ports:
  - number: 12345  # Replace with the appropriate port number
    name: tcp-port
    protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tcp-service-entry-3
spec:
  hosts:
  - "example-host.com"  # Updated with example host
  addresses:
  - "192.168.1.1"
  - "192.168.1.3"
  - "192.168.1.2"  # Replace with the IP address if needed, or use the host
  ports:
  - number: 12345  # Replace with the appropriate port number
    name: tcp-port
    protocol: TCP
  resolution: NONE
```

### Version

```Text
Istio Version: 1.24.1
Kubernetes Version: 1.30.X
```
