### ISSUE TITLE
Istio Ambient and X-Forwarded-Client-Cert

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#54995]
### Discussed in https://github.com/istio/istio/discussions/54888

<div type='discussions-op-text'>

<sup>Originally posted by **jgournet** January 27, 2025</sup>
Hi,

I'm starting to move to istio ambient, and so far, it seems that X-Forwarded-Client-Cert is not forward to the target pod.
And we do rely on it.
=> is there a way to have it in ambient mode ? 
Or has someone already written a filter to add it maybe ?</div>

**Comment by keithmattix** [comment]
Not stale

**Comment by dkulchinsky** [comment]
Hey folks 👋🏼 was going to file an issue for the same and came across this one.

We're testing Istio ambient mode now as a replacement for Linkerd and need to be able to provide the identity of the client in a header.

In the Waypoint debug logs, I can see the CONNECT (from ztunnel?) includes the necessary information:
```
waypoint-7f9bd98969-6xj28 istio-proxy ':method', 'CONNECT'
waypoint-7f9bd98969-6xj28 istio-proxy ':authority', '172.27.6.10:9898'
waypoint-7f9bd98969-6xj28 istio-proxy ':scheme', 'https'
waypoint-7f9bd98969-6xj28 istio-proxy 'baggage', 'k8s.cluster.name=Kubernetes,k8s.namespace.name=my-app,k8s.pod.name=podinfo-istio-ambient-2,service.name=podinfo-istio-ambient-2,service.version=8.7.1,cloud.region=us-central1,cloud.availability_zone=us-central1-c'
waypoint-7f9bd98969-6xj28 istio-proxy 'forwarded', 'for="172.26.11.151:53310";host=podinfo-istio-ambient-svc.my-app.svc.cluster.local'
waypoint-7f9bd98969-6xj28 istio-proxy 'traceparent', '00-a73e953887eb6066712fd77bd2019958-24d758af0e8f3240-00'
waypoint-7f9bd98969-6xj28 istio-proxy 'x-forwarded-proto', 'https'
waypoint-7f9bd98969-6xj28 istio-proxy 'x-request-id', '56c09fb4-dca4-448d-86f3-769bcec9f839'
waypoint-7f9bd98969-6xj28 istio-proxy 'x-forwarded-client-cert', 'By=spiffe://cluster.local/ns/my-app/sa/waypoint;Hash=87d2e5554bffb0cea89ed370b2d60b798ff6755532b7ae338dd05857c8d26ef8;Subject="";URI=spiffe://cluster.local/ns/my-app/sa/podinfo-istio-ambient-2'
waypoint-7f9bd98969-6xj28 istio-proxy 'x-envoy-expected-rq-timeout-ms', '15000'
```

however, I'm unable to figure out a way to pass this on to the target.

based on this issue, I'm assuming this is not supported? or perhaps requires some configuration I'm not aware of?

**Comment by dkulchinsky** [comment]
Not stale, hopefully

**Comment by keithmattix** [comment]
Not stale. To do this, we'd have to add config in the waypoint to do the following:
1. Read the XFFCC header out of the connect tunnel and read it to filter state
2. Write the value in filter state to the XFFCC header for the inner HTTP request

I imagine this would be behavior that's off by default (especially at first) and configurable via proxy config annotation (or in meshconfig).

WDYT @ramaraochavali @howardjohn

**Comment by howardjohn** [comment]
I don't think you need to read data from xfcc at the tunnel layer or that xfcc should be set in the tunnel layer at all. The waypoint can just read the tls state and set the header in the inner http layer. I'm 95% sure I've done this manually with envoyFilter/virtualservice in the past. 

The thing we want to forward is just the downstream tls so no need for xfcc in the tunnel. And envoy setting xfcc in the tunnel would destroy our ability to pool

**Comment by keithmattix** [comment]
~~That'll work if the contract is just "what's the downstream's identity" but if we want the append semantics of XFFCC, I think we need to read the actual header.~~

On second thought, I forgot this is a waypoint not an ingress; there's only going to be one client cert really. Your approach is simpler in that case

**Comment by keithmattix** [comment]
And if I'm reading the previous comments correctly, the cert is already being set in the tunnel? I think envoy may be setting automatically because the tunnel contains the TLS

**Comment by dkulchinsky** [comment]
not stale

**Comment by PetrMc** [comment]
Been digging into this. Posting options, not pitching one.

To summarize: waypoint HCM, Envoy's XFCC logic reads the active peer cert (ztunnel), not filter state. but the real client identity is sitting in filter state `io.istio.peer_principal`  set here [filters.go#L315](https://github.com/istio/istio/blob/master/pilot/pkg/xds/filters/filters.go#L315)  because ztunnel uses per-workload SDS certs. Envoy's HCM just can't reach filter state for XFCC. XFCC config on the waypoint: [listener_waypoint.go#L211](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/listener_waypoint.go#L211).

few options:

1. Envoy change — let `SetCurrentClientCertDetails` read filter state. Clean, but Envoy-wide and long cycle.
2. istiod only — header-mutation/Lua filter on waypoint HCM writing `%FILTER_STATE(io.istio.peer_principal:PLAIN)%` into XFCC. Hook: [buildWaypointHTTPFilters](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/listener_waypoint.go#L814). Fast but a bolt-on.
3. istio/proxy C++ filter — new HTTP filter that reads `io.istio.peer_principal` from filter state and writes a proper XFCC entry (`By=`, `Hash=`, `URI=` formatting, header merge/sanitize). Similar shape to the existing [peer_metadata filter](https://github.com/istio/proxy/tree/master/source/extensions/filters/http/peer_metadata). Middle ground — cleaner than istiod string-stitching, avoids upstream Envoy.

as a side note #58818 added a similar "filter state into waypoint HCM" pattern for tracing, partially reusable for 2/3.

Open questions either way:
- XFCC entry vs separate header?
- If we synthesize, do we flip waypoint to `SANITIZE_SET` so inbound XFCC isn't trusted?
- Opt-in knob or default?
- Just URI or also Subject/DNS/Hash?

Can prototype 2 if useful. What do folks think is the right long-term answer?

**Comment by keithmattix** [comment]
> : waypoint HCM, Envoy's XFCC logic reads the active peer cert (ztunnel), not filter state. but the real client identity is sitting in filter state io.istio.peer_principal 

Ztunnel doesn't have its own cert; can you clarify what the HCM sees?

**Comment by PetrMc** [comment]
terrible wording - sorry. Ztunnel uses the source workload's SPIFFE cert via SDS.
the gap to address is HCM XFCC runs on the main_internal listener where mTLS is already terminated — no peer cert to read. 
identity is in filter state `io.istio.peer_principal`, but `SetCurrentClientCertDetails` can't read filter state. No changes in options above just great clarification point

**Comment by keithmattix** [comment]
Yep ok that matches my understanding. I think I'm fine with 2)

**Comment by luistilingue** [comment]
Hi.

I'm able to extract HBONE mTLS spiffe/cert infos and forward them via XFCC to the final upstream workload using these envoyFilters. In my case due to using dedicated (internal) gateways, the destination waypoint wasn't used/received traffic to forward to the final upstream workload, as is stated in [Istio docs](https://istio.io/latest/docs/ambient/usage/waypoint/#ingress-and-waypoints).

All my traffic for this case is east-west (downstream -> internal-gateway -> upstream).

Istio v1.29.x OSS/Vanilla on AKS.

My architecture using Ambient (gateway api):

```
downstream-app (namespace A) ->
             ztunnel (node where is downstream-app) ->
                       waypoint (namespace B) ->
                             internal-gateway (namespace B) ->
                                   ztunnel (node where is upstream-app) ->
                                            upstream-app (namespace C)

```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: waypoint-gateway-internal-capture-cert
  namespace: gateway-api-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: waypoint
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        listener:
          name: connect_terminate
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.set_filter_state
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
            on_request_headers:
              - object_key: custom.peer_cert_pem
                factory_key: envoy.string
                shared_with_upstream: ONCE
                format_string:
                  text_format_source:
                    inline_string: "%DOWNSTREAM_PEER_CERT%"
              - object_key: custom.peer_uri_san
                factory_key: envoy.string
                shared_with_upstream: ONCE
                format_string:
                  text_format_source:
                    inline_string: "%DOWNSTREAM_PEER_URI_SAN%"
              - object_key: custom.peer_cert_fingerprint
                factory_key: envoy.string
                shared_with_upstream: ONCE
                format_string:
                  text_format_source:
                    inline_string: "%DOWNSTREAM_PEER_FINGERPRINT_256%"
              - object_key: custom.true_client_ip
                factory_key: envoy.string
                shared_with_upstream: ONCE
                format_string:
                  text_format_source:
                    inline_string: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
    - applyTo: HTTP_FILTER
      match:
        listener:
          name: main_internal
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.header_mutation
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
            mutations:
              request_mutations:
                - remove: x-forwarded-client-cert
                - append:
                    header:
                      key: x-forwarded-client-cert
                      value: >-
                        By=%FILTER_STATE(io.istio.local_principal:PLAIN)%;Hash=%FILTER_STATE(custom.peer_cert_fingerprint:PLAIN)%;Subject="";URI=%FILTER_STATE(custom.peer_uri_san:PLAIN)%;Cert=%FILTER_STATE(custom.peer_cert_pem:PLAIN)%
                    append_action: OVERWRITE_IF_EXISTS_OR_ADD
                - append:
                    append_action: APPEND_IF_EXISTS_OR_ADD
                    header:
                      key: x-forwarded-for
                      value: '%FILTER_STATE(custom.true_client_ip:PLAIN)%'
    - applyTo: NETWORK_FILTER
      match:
        listener:
          name: main_internal
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            forward_client_cert_details: ALWAYS_FORWARD_ONLY
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: internal-gateway-always-forward-xfcc
  namespace: gateway-api-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal-gateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            forward_client_cert_details: ALWAYS_FORWARD_ONLY
```
