### ISSUE TITLE
TLS termination at istio proxy side car

### ISSUE THREAD

**Issue by cyberaa** [istio/istio#54991]
Hey folks,

I have a business requirement to have encrypted comms e2e. However, I wanted to pass that responsibility to the service mesh instead of doing it on the application side. Most of my services are secured with mTLS, however, I have some services that use dedicated NLBs with TLS, so I need to terminate TLS before it reaches the application. 

IMO, the best place would be at the istio proxy but I couldn't find a suitable solution just yet.

Currently, I have the following setup:
![Image](https://github.com/user-attachments/assets/955580d0-2890-4e8c-88cb-947863a526de)

What are my options to implement TLS termination at **my-app** istio/envoy side-car?

I have tried sidecar "hybrid mode" from https://github.com/istio/istio/pull/36210 but it didn't seem to work.

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: my-app
  namespace: default
spec:
  ingress:
    - bind: 127.0.0.1
      defaultEndpoint: 127.0.0.1:5000
      port:
        name: http
        number: 5000
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/certs/tls.key
        serverCertificate: /etc/certs/tls.crt
  workloadSelector:
    labels:
      app: my-app
```

Any ideas?

Thanks!
