### ISSUE TITLE
Multi root-cert

### ISSUE THREAD

**Issue by ro-distefano** [istio/istio#55005]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hello Istio community,

I am attempting to merge two Istio multicluster meshes. Currently, the clusters of the two meshes are configured whit different root certificates. To enable communication between two meshes, I have to set the same one without creating any downtime. I read that this functionality it's available in Istio and i follow this guide: [reference](https://github.com/zirain/istio-root-cert-rotation/tree/main/kubecon-eu-2024) to enable it but don't work. 

I use the follow istio configuration: 
``` yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  labels:
    version: 1.24.2
spec:
  profile: default
  meshConfig:
    dnsRefreshRate: 600s
    enableTracing: true
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        PROXY_CONFIG_XDS_AGENT: "true"
      tracing:
        <tracing config>
        zipkin:
          address: <zipkin address>
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
    pilot:
      k8s:
        env:
          - name: ISTIO_MULTIROOT_MESH
            value: "true"
        hpaSpec:
          maxReplicas: 80
          minReplicas: 2
        resources:
          < limits and requests>
  values:
    pilot:
      env:
        ISTIO_MULTIROOT_MESH: true
    telemetry:
      v2:
        enabled: true
    global:
      hub: .../docker.io/istio
      proxy_init:
        image: .../proxyv2:1.24.2
      proxy:
        image: .../proxyv2:1.24.2
        resources:
          <limits>
      meshID: <mesh-id>
      multiCluster:
        enabled: true
        includeEnvoyFilter: true
        clusterName: <cluster-id>
      network: <network-id>
```

and i set new cacert in this way: 
``` bash
# after recovering files: root-key.pem, root-ca.conf, root-cert.csr, root-cert.pem
# after created combined-root-cert.pem (pseudo code: 
# for root-cert.pem in trusted-root-cert:
#        root-cert.pem >> combined-root-cert.pem
# )
kubectl delete secret cacerts -n istio-system --ignore-not-found
kubectl --kubeconfig="${KUBECONF_SA}" --context="${DOMAIN}" create secret generic cacerts -n istio-system \
          --from-file="${ISTIO_CLUSTER}"/ca-cert.pem \
          --from-file="${ISTIO_CLUSTER}"/ca-key.pem \
          --from-file=root-cert.pem=combined-root-cert.pem \
          --from-file="${ISTIO_CLUSTER}"/cert-chain.pem \

```

After installing everything, the config maps "istio-ca-root-cert" are correctly configured with the combined-root-cert.pem. Analyzing the istio-proxy container, the environment variable "PROXY_CONFIG_XDS_AGENT" is set correctly to "true". Similarly, analyzing the istiod configuration, the environment variable ISTIO_MULTIROOT_MESH is correctly set to "true". But trying comunication in cluster or whith the other clusters in mesh i receve the follow error:
``` bash
curl -s <service-to-test>.<namespace>
```
``` 
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, 
transport failure reason: TLS_error:|67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01|67109000:RSA 
routines:OPENSSL_internal:PADDING_CHECK_FAILED|184549382:X.509 certificate routines:OPENSSL_internal:public key 
routines|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end
```

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
$ kubectl version
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.8-eks-2d5f260
```
