### ISSUE TITLE
istioctl get all

### ISSUE THREAD

**Issue by esnible** [istio/istio#5502]
Support `istioctl get all`, similar to `kubectl get all`.  The command would get and display all of the current types (routerule, egressrule, destinationpolicy, httpapispec, httpapispecbinding, quotaspec, quotaspecbinding, servicerole, servicerolebinding, virtualservice, gateway, serviceentry, destinationrule, policy) and support the `-o yaml` option but print tables by default.

In discussion on #networking Costin said "+1" and Lin Sun said "that seems useful.  today i do kubectl get crd to see which ones are istio".

**Comment by kyessenov** [comment]
It should also fetch all mixer Cards.

**Comment by ayj** [comment]
CRD can be assigned to categories (see https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions). 

```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: rules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: rule
    plural: rules
    singular: rule
    categories:
    - istio    
  scope: Namespaced
  version: v1alpha2
```

You can then get by category, e.g.

```bash
$ kubectl get istio
NAME                                        AGE
routerule.config.istio.io/reviews-default   19m

NAME                                              AGE
servicerolebinding.config.istio.io/bind-ratings   19m

NAME                                                AGE
checknothing.config.istio.io/denyreviewsv3request   19m

NAME                                          AGE
denier.config.istio.io/denyreviewsv3handler   19m

NAME                                         AGE
servicerole.config.istio.io/ratings-viewer   19m

NAME                                 AGE
rule.config.istio.io/denyreviewsv3   19m
```

You could further categorize CRD by component type so things like `kubectl get istio-mixer` and `kubectl get istio-pilot` would work.
