### ISSUE TITLE
Ambient mode bookinfo HTTPRoute issue

### ISSUE THREAD

**Issue by eraserx99** [istio/istio#55025]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

  Currently, we're testing the Istio 1.24.2/Ambient with our EKS (Kubernetes v1.29). We deployed it via ArgoCD + Helm Chart and it looked good at first glance. Then, we installed the BookInfo sample application by following the guide too. We deployed the bookinfo.yaml
, bookinfo-versions.yaml, and bookinfo-gateway.yaml. However, we found some concerns from the ztunnel logs. 

  The bookinfo.yaml has the definition of Service productpage.

```
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
```

  The bookinfo-versions.yaml has the definition of Service productpage-v1.

```
apiVersion: v1
kind: Service
metadata:
  name: productpage-v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
    version: v1
```

  The HTTPRoute refers only to productpage.

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
  rules:
  - matches:
    - path:
        type: Exact
        value: /productpage
    - path:
        type: PathPrefix
        value: /static
    - path:
        type: Exact
        value: /login
    - path:
        type: Exact
        value: /logout
    - path:
        type: PathPrefix
        value: /api/v1/products
    backendRefs:
    - name: productpage
      port: 9080
      kind: Service
      group: ''
      weight: 100
```

After pumping the loads (accessing the http://<LOAD_BALANCER_URL>/productpage) for a while, we could see that the traffic went through the service productpage-v1 to the workload. It looked very weird.

```
ztunnel-s6fsg istio-proxy 2025-02-10T01:24:09.917931Z   info    access  connection complete     src.addr=10.50.10.244:33718 src.workload="bookinfo-gateway-istio-7c96b56dfd-x497d" src.namespace="istio-demo" src.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-gateway-istio" dst.addr=10.50.10.249:15008 dst.hbone_addr=10.50.10.249:9080 dst.service="productpage-v1.istio-demo.svc.cluster.local" dst.workload="productpage-v1-5c5fb9b4b4-lzht7" dst.namespace="istio-demo" dst.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-productpage" direction="inbound" bytes_sent=9603 bytes_recv=1041 duration="2024ms"
ztunnel-s6fsg istio-proxy 2025-02-10T01:24:13.377045Z   info    access  connection complete     src.addr=10.50.10.244:33718 src.workload="bookinfo-gateway-istio-7c96b56dfd-x497d" src.namespace="istio-demo" src.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-gateway-istio" dst.addr=10.50.10.249:15008 dst.hbone_addr=10.50.10.249:9080 dst.service="productpage-v1.istio-demo.svc.cluster.local" dst.workload="productpage-v1-5c5fb9b4b4-lzht7" dst.namespace="istio-demo" dst.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-productpage" direction="inbound" bytes_sent=9603 bytes_recv=1041 duration="2054ms"
ztunnel-s6fsg istio-proxy 2025-02-10T01:24:16.807341Z   info    access  connection complete     src.addr=10.50.10.244:33714 src.workload="bookinfo-gateway-istio-7c96b56dfd-x497d" src.namespace="istio-demo" src.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-gateway-istio" dst.addr=10.50.10.249:15008 dst.hbone_addr=10.50.10.249:9080 dst.service="productpage-v1.istio-demo.svc.cluster.local" dst.workload="productpage-v1-5c5fb9b4b4-lzht7" dst.namespace="istio-demo" dst.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-productpage" direction="inbound" bytes_sent=15243 bytes_recv=1041 duration="2054ms"
```

Then, we removed the productpage-v1 in the bookinfo-versions.yaml and re-deployed. The traffic went through the service productpage only as expected.

``
ztunnel-s6fsg istio-proxy 2025-02-10T01:39:43.011957Z   info    access  connection complete     src.addr=10.50.10.244:33714 src.workload="bookinfo-gateway-istio-7c96b56dfd-x497d" src.namespace="istio-demo" src.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-gateway-istio" dst.addr=10.50.10.249:15008 dst.hbone_addr=10.50.10.249:9080 dst.service="productpage.istio-demo.svc.cluster.local" dst.workload="productpage-v1-5c5fb9b4b4-lzht7" dst.namespace="istio-demo" dst.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-productpage" direction="inbound" bytes_sent=15247 bytes_recv=1041 duration="2031ms"
ztunnel-s6fsg istio-proxy 2025-02-10T01:39:46.540492Z   info    access  connection complete     src.addr=10.50.10.244:33718 src.workload="bookinfo-gateway-istio-7c96b56dfd-x497d" src.namespace="istio-demo" src.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-gateway-istio" dst.addr=10.50.10.249:15008 dst.hbone_addr=10.50.10.249:9080 dst.service="productpage.istio-demo.svc.cluster.local" dst.workload="productpage-v1-5c5fb9b4b4-lzht7" dst.namespace="istio-demo" dst.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-productpage" direction="inbound" bytes_sent=15247 bytes_recv=1041 duration="2023ms"
ztunnel-s6fsg istio-proxy 2025-02-10T01:39:50.161424Z   info    access  connection complete     src.addr=10.50.10.244:33718 src.workload="bookinfo-gateway-istio-7c96b56dfd-x497d" src.namespace="istio-demo" src.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-gateway-istio" dst.addr=10.50.10.249:15008 dst.hbone_addr=10.50.10.249:9080 dst.service="productpage.istio-demo.svc.cluster.local" dst.workload="productpage-v1-5c5fb9b4b4-lzht7" dst.namespace="istio-demo" dst.identity="spiffe://cluster.local/ns/istio-demo/sa/bookinfo-productpage" direction="inbound" bytes_sent=15247 bytes_recv=1041 duration="2027ms"
```

  Any explanation?



### Version

```Text
> istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (16 proxies)

> kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.29.12-eks-2d5f260
WARNING: version difference between client (1.32) and server (1.29) exceeds the supported minor version skew of +/-1

> helm version
version.BuildInfo{Version:"v3.17.0", GitCommit:"301108edc7ac2a8ba79e4ebf5701b0b6ce6a31e4", GitTreeState:"clean", GoVersion:"go1.23.4"}
```
