### ISSUE TITLE
VirtualService with 4K+ redirects cause istiod and sidecars OOM

### ISSUE THREAD

**Issue by MiticoBerna** [istio/istio#55054]
### Bug Description

After a domain migration, I need to create some redirects in one VirtualService. Paths change from old domain to the new one.
Redirects are around **4500**.
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: olddomain-redirects
  namespace: default
spec:
  gateways:
    - mesh
    - istio-system/gateway
  hosts:
    - www.olddomain.com
  http:
    - match:
        - uri:
            exact: /page1
          authority: 
            exact: www.olddomain.com
      redirect:
        uri: /page2
        authority: www.newdomain.com
    - match:
        - uri:
            exact: /page3
          authority: 
            exact: www.olddomain.com
      redirect:
        uri: /page4
        authority: www.newdomain.com
    - match:
        - uri:
            exact: /page5
          authority: 
            exact: www.olddomain.com
      redirect:
        uri: /page6
        authority: www.newdomain.com
[...]
    # Catch-all for non matching entries
    - match:
        - uri:
            prefix: /
          authority: 
            exact: www.olddomain.com
      redirect:
        authority: www.newdomain.com
```

Tested with ~300 redirects, all goods
With 4500+ redirects I get OOM of istiod and after that also multiple istio-proxy sidecars are killed with OOM.

Config (istio installed via istioctl):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: gcr.io/istio-release
  values:
    telemetry:
      enabled: true
      v2:
        enabled: true
        stackdriver:
          enabled: false
    global:
      logAsJson: true
      variant: distroless
      proxy:
        autoInject: "disabled"
        # logLevel: debug
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 256Mi
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      terminationDrainDuration: 20s
      tracing:
        zipkin:
          address: jaeger-zipkin.tools.svc.cluster.local:9411
        sampling: 5
  components:
    pilot:
      k8s:
        overlays:
          - kind: PodDisruptionBudget
            name: istiod
            patches:
              - path: spec.minAvailable
              - path: spec.maxUnavailable
                value: 1
          - kind: Deployment
            name: istiod
            patches:
              - path: spec.template.spec.topologySpreadConstraints
                value:
                  - maxSkew: 1
                    topologyKey: topology.kubernetes.io/zone
                    whenUnsatisfiable: DoNotSchedule
                    labelSelector:
                      matchLabels:
                        istio: pilot
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 1Gi
        hpaSpec:
          minReplicas: 2
          maxReplicas: 2
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          overlays:
            - kind: PodDisruptionBudget
              name: istio-ingressgateway
              patches:
                - path: spec.minAvailable
                - path: spec.maxUnavailable
                  value: 1
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.topologySpreadConstraints
                  value:
                    - maxSkew: 1
                      topologyKey: topology.kubernetes.io/zone
                      whenUnsatisfiable: DoNotSchedule
                      labelSelector:
                        matchLabels:
                          istio: ingressgateway
          podAnnotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              memory: 1Gi
          hpaSpec:
            minReplicas: 2
            maxReplicas: 2
          service:
            loadBalancerIP: 35.205.49.155
            sessionAffinity: None
            externalTrafficPolicy: Local
            loadBalancerSourceRanges:
              - "173.245.48.0/20" # Cloudflare IPs (https://www.cloudflare.com/ips-v4)
              - "103.21.244.0/22"
              - "103.22.200.0/22"
              - "103.31.4.0/22"
              - "141.101.64.0/18"
              - "108.162.192.0/18"
              - "190.93.240.0/20"
              - "188.114.96.0/20"
              - "197.234.240.0/22"
              - "198.41.128.0/17"
              - "162.158.0.0/15"
              - "104.16.0.0/13"
              - "104.24.0.0/14"
              - "172.64.0.0/13"
              - "131.0.72.0/22"
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: sftp
                port: 2022
                protocol: TCP
                targetPort: 2022

```

If I remove `gateways: - mesh` and leave only `istio-system/gateway` no problem at all.
Could you please help me understand why this happen?

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (238 proxies)

$ kubectl version        
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.5-gke.1023000
```
