### ISSUE TITLE
listener extra bind is not empty when dual stack is not enabled

### ISSUE THREAD

**Issue by kanurag94** [istio/istio#55081]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

As per https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/listener.go#L272 -- there should be no additional bindings returned when dual stack is not enabled.

But seems like this PR https://github.com/istio/istio/pull/51967 removed this check causing the listener to have `additionalAddresses` without dual stack enabled. I am not sure if this is the behavior we want.

We are getting hit with https://github.com/envoyproxy/envoy/issues/37373 probably due to this change while updating the following service entry:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example
spec:
  addresses:
    - 10.1.1.1/32
    - 10.1.1.2/32
    - 10.1.1.3/32
  hosts:
    - ignored.subdomain
  ports:
    - name: TCP-9999
      number: 9999
      protocol: TCP
    - name: TCP-443
      number: 443
      protocol: TCP
```

Would like to know if this is an acceptable behavior, and we shall wait for envoy fix or revert to not setting additionalAddresses without dual stack enabled?

### Version

```Text
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (3 proxies)
```
