### ISSUE TITLE
Auto inject default labelSelector for `topologySpreadConstraints` in Helm Charts

### ISSUE THREAD

**Issue by chansuke** [istio/istio#55111]
**Describe the feature request**

It would be helpful if `labelSelector` could be automatically injected when configuring `topologySpreadConstraints` in values.yaml for Istio’s Helm chart. 
Currently, users need to manually specify labelSelector, which can lead to misconfigurations or inconsistencies. By adding default labels automatically, we can simplify deployment configuration and reduce the risk of errors.

A similar approach can be found in other Helm charts:

[argocd-server/deployment.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/deployment.yaml#L487-L496)
[karpenter/templates/deployment.yaml](https://github.com/aws/karpenter-provider-aws/blob/75f432284841d7e3598bc8f20a78e2f8bd6e722e/charts/karpenter/templates/deployment.yaml#L209-L211)

The goal is to reduce the configuration complexity for users by eliminating the need to manually define labelSelector. Instead, the Helm chart should automatically apply a default label when labelSelector is not explicitly provided.

**From**:
```
topologySpreadConstraints: 
 - maxSkew: 1
   topologyKey: kubernetes.io/hostname
   whenUnsatisfiable: DoNotSchedule
   labelSelector:
     matchLabels:
       app.kubernetes.io/name: istiod
 - maxSkew: 1
   topologyKey: kubernetes.io/zone
   whenUnsatisfiable: DoNotSchedule
   labelSelector:
     matchLabels:
       app.kubernetes.io/name: istiod
```

**To**:

```
topologySpreadConstraints: 
 - maxSkew: 1
   topologyKey: kubernetes.io/hostname
   whenUnsatisfiable: DoNotSchedule
 - maxSkew: 1
   topologyKey: kubernetes.io/zone
   whenUnsatisfiable: DoNotSchedule
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
