### ISSUE TITLE
Istio Gateway does not create a listener for a UNIX domain socket

### ISSUE THREAD

**Issue by oliver-goetz** [istio/istio#55112]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

According to the [documentation](https://istio.io/latest/docs/reference/config/networking/gateway/#Server-bind). I expect that this Istio Gateway definition would create a Listener and the socket `@kube-apiservers/shoot--local--local--kube-apiserver`.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app: kubernetes
    role: apiserver
  name: domain-socket
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - bind: unix://@default/domain-socket
    hosts:
    - "*"
    port:
      name: tls
      number: 0
      protocol: TLS
    tls: {}
```

However, when applying this file I neither find the listener in the envoy config dump of istio-gateway nor the socket in its pod.

```
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  3      [ ]         STREAM     CONNECTED     3492055
unix  2      [ ACC ]     STREAM     LISTENING     1872867  var/run/secrets/workload-spiffe-uds/socket
unix  3      [ ]         STREAM     CONNECTED     3491148  etc/istio/proxy/XDS
unix  2      [ ACC ]     STREAM     LISTENING     1872868  etc/istio/proxy/XDS
```

When I change bind to `127.0.0.1` and the port to something like `12345` the listener is created and istio starts listing on this port. 

```
...
    {
     "name": "127.0.0.1_12345",
     "active_state": {
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "127.0.0.1_12345",
       "address": {
        "socket_address": {
         "address": "127.0.0.1",
         "port_value": 12345
        }
       },
...
```

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State
...
tcp        0      0 localhost:12345         0.0.0.0:*               LISTEN
tcp        0      0 localhost:12345         0.0.0.0:*               LISTEN
tcp        0      0 localhost:12345         0.0.0.0:*               LISTEN
tcp        0      0 localhost:12345         0.0.0.0:*               LISTEN
```

### Version

```Text
❯ istioctl version
client version: 1.24.3
control plane version: 1.23.4
data plane version: 1.23.4 (2 proxies)
```
