### ISSUE TITLE
Nodes get irregularly unuseable

### ISSUE THREAD

**Issue by dan-m8t** [istio/istio#55139]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi,

I am not sure if this is the right place to discuss this issue, because it is probably laying in the network stack.
We use OKD 4.14 with OVN Network Layer.

We deployed istio in ambient-mode (we deployed in istio-system, contrary as documented, we use the privileged SCC for istio-system and this is working).

Since one of our customers starts using istio more we do have irregularly node issues. 
First istio-cni starts to get non-ready and furthermore ztunnel because it relies on istio-cni. The node completely  becomes non-reachable via network. No ssh, no debug session possible, no ping, nothing, just dead.

From the logs we cannot see very much, even after we rebooted the node there is not much. With our network team we digged down in OVN, as I am not a Network guy and our network guys are not Kubernetes guys, I try to deliver what we got.

We can see different mangle tables on the nodes, so a node with the issue had this one:

```
        chain ISTIO_OUTPUT {
                ip daddr 169.254.7.127 ip protocol tcp  counter packets 0 bytes 0 accept
                ip protocol tcp meta mark & 0x00000fff == 0x00000111 counter packets 0 bytes 0 accept
                ip daddr != 127.0.0.1 oifname "lo" counter packets 4549 bytes 273012 accept
                ip daddr != 127.0.0.1 ip protocol tcp meta mark & 0x00000fff != 0x00000539 counter packets 1609715 bytes 96582900 redirect to :15001
        }
```

and other nodes had this one:

```
table ip mangle {
        chain KUBE-IPTABLES-HINT {
        }

        chain KUBE-KUBELET-CANARY {
        }

        chain OVN-KUBE-ITP {
        }

        chain OUTPUT {
                type route hook output priority mangle; policy accept;
                counter packets 122327674 bytes 641811082005 jump OVN-KUBE-ITP
                counter packets 22567146 bytes 178830670492 jump ISTIO_OUTPUT
        }

        chain ISTIO_PRERT {
                meta mark & 0x00000fff == 0x00000539 counter packets 13207 bytes 792420 ct mark set ct mark xor 0x111 and 0xfffff000
                ip saddr 169.254.7.127 ip protocol tcp  counter packets 0 bytes 0 accept
                ip daddr != 127.0.0.1 iifname "lo" ip protocol tcp counter packets 1738817 bytes 71798999 accept
                tcp dport 15008 meta mark & 0x00000fff != 0x00000539 counter packets 0 bytes 0 # TPROXY redirect 0.0.0.0:15008 mark 0x111/0xfff
                ip protocol tcp ct state related,established counter packets 1663950 bytes 705867855 accept
                ip daddr != 127.0.0.1 ip protocol tcp meta mark & 0x00000fff != 0x00000539 counter packets 34154 bytes 2049240 # TPROXY redirect 0.0.0.0:15006 mark 0x111/0xfff
        }

        chain ISTIO_OUTPUT {
                ct mark and 0xfff == 0x111 counter packets 64151 bytes 4366280 meta mark set ct mark
        }

        chain PREROUTING {
                type filter hook prerouting priority mangle; policy accept;
                counter packets 31325649 bytes 424465003964 jump ISTIO_PRERT
        }
}
```

so these differs, probably because the problematic node tried to write iptables rules for the workload on that node.

We already enabled debug logs on istiod, ztunnel and istio-cni with not much information regarding those issues, so I cannot provide any.

We are **not** able to reproducde the issue, this just happens for no reason I can see.

Heres my mesh config:

```
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    discoverySelectors:
    - matchLabels:
        mycompany/istio-enabled: "true"
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

istio-cni config:

```
data:
  AMBIENT_DNS_CAPTURE: "false"
  AMBIENT_ENABLED: "true"
  AMBIENT_IPV6: "true"
  CHAINED_CNI_PLUGIN: "false"
  CNI_CONF_NAME: istio-cni.conf
  CNI_NET_DIR: /etc/cni/multus/net.d
  CURRENT_AGENT_VERSION: 1.23.4
  EXCLUDED_NAMESPACES: kube-system
  REPAIR_BROKEN_POD_LABEL_KEY: cni.istio.io/uninitialized
  REPAIR_BROKEN_POD_LABEL_VALUE: "true"
  REPAIR_DELETE_PODS: "false"
  REPAIR_ENABLED: "false"
  REPAIR_INIT_CONTAINER_NAME: istio-validation
  REPAIR_LABEL_PODS: "false"
  REPAIR_REPAIR_PODS: "true"
```

As I said I am not sure if this is a istio related issue, but it happened since we use more istio workloads.

I am kinda lost where to look.

To "fix" the issue temporarly we drain the node and reboot. Well, this leads of course to some action as the pods needs to get scheduled onto another node. 

Any hint where to look into? 

Thanks!

### Version

```Text
istioctl version
client version: 1.24.2
control plane version: 1.23.4
data plane version: 1.23.4 (84 proxies)
kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.27.1-3474+5c56cc35e3edc1-dirty
WARNING: version difference between client (1.32) and server (1.27) exceeds the supported minor version skew of +/-1
```

### Additional Information

As the bug report is really big and contains customer data I try to provide anything that could help:

from bug-report.log:

```
2025-02-17T12:46:59.027600Z error   previous terminated container "istio-proxy" in pod "ztunnel-mxwj9" not found, previous terminated container "istio-proxy" in pod "ztunnel-g2ckx" not found, previous terminated container "istio-proxy" in pod "ztunnel-r9ng4" not found, previous terminated container "istio-proxy" in pod "ztunnel-t4ljr" not found, previous terminated container "istio-proxy" in pod "ztunnel-hs7cc" not found, previous terminated container "istio-proxy" in pod "ztunnel-m6wd9" not found, previous terminated container "istio-proxy" in pod "ztunnel-62nk7" not found, previous terminated container "istio-proxy" in pod "ztunnel-ppscn" not found, previous terminated container "istio-proxy" in pod "ztunnel-kjfgm" not found
```
from versions:

```
CLI version:
version.BuildInfo{Version:"1.24.2", GitRevision:"unknown", GolangVersion:"go1.23.4", BuildStatus:"unknown", GitTag:"unknown"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.23.4", GitRevision:"e0508c3e94a50a41e33f39362e0825913b6d0521", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.4"}}, version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.23.4", GitRevision:"e0508c3e94a50a41e33f39362e0825913b6d0521", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.4"}}, version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.23.4", GitRevision:"e0508c3e94a50a41e33f39362e0825913b6d0521", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.4"}}}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.23.4}
```

from bug-report/analyze/allNamespaces/allNamespaces:

Only warnings regarding AuthorizationPolicies (not matching workloads)
Info about non-mesh namespaces
Info services that services doesnt follow naming convention

in cluster nothing I could share easily. Same for cni,istio,proxies - if you can tell me what to grep for I could provide such logs.
