### ISSUE TITLE
need better logging in networking library when black hole clusters are created

### ISSUE THREAD

**Issue by esnible** [istio/istio#5514]
If I create a VirtualService

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook
spec:
  gateways:
  - guestbook-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: helloworld-service
```

the Envoy configuration generated by Pilot points to the BlackHoleCluster:

```
                      "name": "guestbook:80",
                      "routes": [
                        {
                          "decorator": {
                            "operation": "guestbook"
                          },
                          "match": {
                            "prefix": "/hello"
                          },
                          "route": {
                            "cluster": "BlackHoleCluster",
                            "timeout": "0.000s",
                            "use_websocket": false
                          }
                        }
                      ]
```

If I add 

```
        port:
          number: 8080
```

to the _destination_ the Envoy config route correctly changes to 

```
                          "route": {
                            "cluster": "outbound|http||helloworld-service.default.svc.cluster.local",
                            "timeout": "0.000s",
                            "use_websocket": false
                          }
```

For this experiment, helloworld-service has a single Port:

```
  ports:
  - name: http
    nodePort: 32262
    port: 8080
    protocol: TCP
    targetPort: 8080
```

According to the documentation https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#Destination "Many services only expose a single port or label ports with the protocols they support, in these cases it is not required to explicitly select the port."
