### ISSUE TITLE
[Ambient] ServiceEntry exportTo not respected by tunnel

### ISSUE THREAD

**Issue by infnada** [istio/istio#55163]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Having the following example ServiceEntry, all requests to `example.com` from Pods in `namespace-a` are correctly sent trough `egress-gateway` waypoint:

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: example
  namespace: istio-gateway
  labels:
    istio.io/use-waypoint: egress-gateway
    istio.io/use-waypoint-namespace: istio-gateway
spec:
  exportTo:
    - "namespace-a"
  location: MESH_EXTERNAL
  resolution: DNS
  hosts:
    - example.com
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
```

The problem resides when Pods in `namespace-b` makes a request to `example.com`. ZTunnel also tries to reach the waypoint:

```
ztunnel-vc2vp 2025-02-18T16:25:48.175861Z    error    access    connection complete    src.addr=10.xx.xx.xx:37048 src.workload="xxx" src.namespace="namespace-b" src.identity="spiffe://cluster.local/ns/namespace-b/sa/xxx" dst.addr=10.xx.xx.xx:15008 dst.hbone_addr=240.240.0.9:80 dst.service="example.com" dst.workload="egress-gateway-78d7cb9ddc-xwxtk" dst.namespace="istio-gateway" dst.identity="spiffe://cluster.local/ns/istio-gateway/sa/egress-gateway" direction="outbound" bytes_sent=0 bytes_recv=0 duration="10000ms" error="connection timed out, maybe a NetworkPolicy is blocking HBONE port 15008: deadline has elapsed"
```

Since we make use of strict network policies Pods from `namespace-b` don't have access to the egress waypoint. But they should not go trough it, right?

### Version

```Text
$ istioctl version                                                                                                                                                                                                                                         
client version: 1.23.1
control plane version: 1.24.1
data plane version: 1.24.1 (15 proxies)

$ kubectl version                                                                                                                                                                                                                                          
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.12-eks-2d5f260
```

### Additional Information

`namespace-a` & `namespace-b` are in ambient mode.

Extra waypoint config:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-gateway
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: egress-gateway
  name: istio-gateway
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: egressgateway-for-example
  namespace: istio-gateway
spec:
  host: example.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: egress-gateway
  namespace: istio-gateway
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-gateway-mtls
  namespace: istio-gateway
spec:
  host: 'egress-gateway.istio-gateway.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

### Affected product area

- [x] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
