### ISSUE TITLE
BookInfo Tracing not functioning as documented with OpenTelemetry

### ISSUE THREAD

**Issue by stephenbuchanan-scout** [istio/istio#55172]
I am working on enabling telemetry for our POC test environment. I have followed the instructions in the documentation to set up Istio as well as the book info application. Everything in the initial setup worked as described in the [Getting Started](https://istio.io/latest/docs/ambient/getting-started/) documentation for Ambient mode.

However, when attempting to follow the [OpenTelemetry instructions](https://istio.io/latest/docs/tasks/observability/distributed-tracing/opentelemetry/#cleanup) for distributed tracing, I was not able to get traces from my application traffic to my existing OpenTelemetry collector.

In initial testing using the OpenTelemetry collector provided in the Istio documentation, traces did appear in the logs of the otel collector similar to what was described in the [documentation](https://istio.io/latest/docs/tasks/observability/distributed-tracing/opentelemetry). However, while the traces were received, the formatting of the traces was not identical to what was described in the documentation. When attempting to export to our existing collector, the traces are not being processed or exported to our observability platform.

In addition, I have configured access logging to operate alongside tracing. Both access logging and tracing are configured to go to the same opentelemetry collector using the grpc otel port, 4317. The access logging is being consumed and exported to our log aggregation tool as expected following the documentation, but traces are not being exported. The issue does not appear to be connectivity, so I'm wondering if there's an issue with the format of the traces.

Expected output of tracing example from documentation:

```
Resource SchemaURL:
Resource labels:
      -> service.name: STRING(productpage.default)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope
Span #0
    Trace ID       : 79fb7b59c1c3a518750a5d6dad7cd2d1
    Parent ID      : 0cf792b061f0ad51
    ID             : 2dff26f3b4d6d20f
    Name           : egress reviews:9080
    Kind           : SPAN_KIND_CLIENT
    Start time     : 2024-01-30 15:57:58.588041 +0000 UTC
    End time       : 2024-01-30 15:57:59.451116 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message :
Attributes:
      -> node_id: STRING(sidecar~10.244.0.8~productpage-v1-564d4686f-t6s4m.default~default.svc.cluster.local)
      -> zone: STRING()
      -> guid:x-request-id: STRING(da543297-0dd6-998b-bd29-fdb184134c8c)
      -> http.url: STRING(http://reviews:9080/reviews/0)
      -> http.method: STRING(GET)
      -> downstream_cluster: STRING(-)
      -> user_agent: STRING(curl/7.74.0)
      -> http.protocol: STRING(HTTP/1.1)
      -> peer.address: STRING(10.244.0.8)
      -> request_size: STRING(0)
      -> response_size: STRING(441)
      -> component: STRING(proxy)
      -> upstream_cluster: STRING(outbound|9080||reviews.default.svc.cluster.local)
      -> upstream_cluster.name: STRING(outbound|9080||reviews.default.svc.cluster.local)
      -> http.status_code: STRING(200)
      -> response_flags: STRING(-)
      -> istio.namespace: STRING(default)
      -> istio.canonical_service: STRING(productpage)
      -> istio.mesh_id: STRING(cluster.local)
      -> istio.canonical_revision: STRING(v1)
      -> istio.cluster_id: STRING(Kubernetes)
      -> my-attribute: STRING(default-value)

```

Actual output from tracing tests:

```
2025-02-13T00:45:58.275Z	INFO	loggingexporter/logging_exporter.go:72	LogsExporter	{"#logs": 3}
2025-02-13T00:45:58.275Z	DEBUG	loggingexporter/logging_exporter.go:82	ResourceLog #0
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-02-13 00:45:57.184563 +0000 UTC
Severity:
Body: [2025-02-13T00:45:57.184Z] "GET /details/0 HTTP/1.1" 200 - via_upstream - "-" 0 178 3 2 "-" "curl/8.7.1" "90706b00-ee24-4f00-b988-f7b2cbff6be7" "details:9080" "envoy://connect_originate/10.11.11.134:9080" inbound-vip|9080|http|details.sbuchanan-testapp.svc.cluster.local envoy://internal_client_address/ 172.20.74.43:9080 10.11.10.67:55962 - default

Trace ID:
Span ID:
Flags: 0
LogRecord #1
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-02-13 00:45:57.193094 +0000 UTC
Severity:
Body: [2025-02-13T00:45:57.193Z] "GET /reviews/0 HTTP/1.1" 200 - via_upstream - "-" 0 358 2 1 "-" "curl/8.7.1" "90706b00-ee24-4f00-b988-f7b2cbff6be7" "reviews:9080" "envoy://connect_originate/10.11.10.133:9080" inbound-vip|9080|http|reviews-v1.sbuchanan-testapp.svc.cluster.local envoy://internal_client_address/ 172.20.246.104:9080 10.11.10.67:55962 - sbuchanan-testapp.reviews.0

Trace ID:
Span ID:
Flags: 0
ResourceLog #1
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-02-13 00:45:57.176879 +0000 UTC
Severity:
Body: [2025-02-13T00:45:57.176Z] "GET /productpage HTTP/1.1" 200 - via_upstream - "-" 0 9429 20 20 "10.11.8.216" "curl/8.7.1" "90706b00-ee24-4f00-b988-f7b2cbff6be7" "localhost:8080" "envoy://connect_originate/10.11.10.67:9080" outbound|9080||productpage.sbuchanan-testapp.svc.cluster.local envoy://internal_client_address/ 127.0.0.1:80 127.0.0.1:33900 - sbuchanan-testapp.bookinfo.0

Trace ID:
Span ID:
Flags: 0
```

## Configuration details:

```
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (11 proxies)
```

Deployed using ArgoCD.

Chart.yaml:

```
apiVersion: v2
name: istio
description: A Helm chart for istio

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: base
  version: "1.24.2"
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: "1.24.2"
  repository: https://istio-release.storage.googleapis.com/charts
- name: cni
  version: "1.24.2"
  repository: https://istio-release.storage.googleapis.com/charts
- name: ztunnel
  version: "1.24.2"
  repository: https://istio-release.storage.googleapis.com/charts

```

Values file:

```
spec:
  environment: dev

istiod:
  profile: ambient
  meshConfig:
    enableTracing: true
    extensionProviders:
    - name: otel
      opentelemetry:
        port: 4317
        service: otel-collector.internal-system.svc.cluster.local
        resource_detectors:
          environment: {}
      envoyOtelAls:
        service: otel-collector.internal-system.svc.cluster.local
        port: 4317

cni:
  profile: ambient

```

Telemetry config:

```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel
    randomSamplingPercentage: 100.00
  accessLogging:
  - providers:
    - name: otel
```

Additional `isitio-system` namespace installations:
- [Jaeger](https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/jaeger.yaml)
- [Prometheus](https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/prometheus.yaml)
- [Kiali](https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/kiali.yaml)

BookInfo installations:
- [BookInfo base](https://raw.githubusercontent.com/istio/istio/release-1.24/samples/bookinfo/platform/kube/bookinfo.yaml)
- [BookInfo Versions](https://raw.githubusercontent.com/istio/istio/release-1.24/samples/bookinfo/platform/kube/bookinfo-versions.yaml)
- [BookInfo Gateway](https://raw.githubusercontent.com/istio/istio/release-1.24/samples/bookinfo/gateway-api/bookinfo-gateway.yaml)

BookInfo waypoint describe output:

```
Name:                     waypoint
Namespace:                sbuchanan-testapp
Labels:                   gateway.istio.io/managed=istio.io-mesh-controller
                          gateway.networking.k8s.io/gateway-name=waypoint
Annotations:              networking.istio.io/traffic-distribution: PreferClose
Selector:                 gateway.networking.k8s.io/gateway-name=waypoint
Type:                     ClusterIP
IP Family Policy:         PreferDualStack
IP Families:              IPv4
IP:                       172.20.47.246
IPs:                      172.20.47.246
Port:                     status-port  15021/TCP
TargetPort:               15021/TCP
Endpoints:                10.11.8.224:15021
Port:                     mesh  15008/TCP
TargetPort:               15008/TCP
Endpoints:                10.11.8.224:15008
Session Affinity:         None
Internal Traffic Policy:  Cluster
Events:                   <none>
```
BookInfo Gateway describe output:

```
Name:                     bookinfo-gateway-istio
Namespace:                sbuchanan-testapp
Labels:                   gateway.istio.io/managed=istio.io-gateway-controller
                          gateway.networking.k8s.io/gateway-name=bookinfo-gateway
                          istio.io/dataplane-mode=none
Annotations:              networking.istio.io/service-type: ClusterIP
Selector:                 gateway.networking.k8s.io/gateway-name=bookinfo-gateway
Type:                     ClusterIP
IP Family Policy:         PreferDualStack
IP Families:              IPv4
IP:                       172.20.167.120
IPs:                      172.20.167.120
Port:                     status-port  15021/TCP
TargetPort:               15021/TCP
Endpoints:                10.11.8.216:15021
Port:                     http  80/TCP
TargetPort:               80/TCP
Endpoints:                10.11.8.216:80
Session Affinity:         None
Internal Traffic Policy:  Cluster
Events:                   <none>
```

Traffic generated by running the following:
```
$ kubectl port-forward svc/bookinfo-gateway-istio 8081:80 -n sbuchanan-testapp
$ for i in $(seq 1 500); do curl -s -o /dev/null "http://localhost:8081/productpage"; done
```
