### ISSUE TITLE
TCPRoute doesn't bind to multiple listeners

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#55173]
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: echo
  namespace: gw
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echo
      port: 80
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: gw
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: default
    port: 80
    protocol: TCP
  - allowedRoutes:
      namespaces:
        from: Same
    name: alt
    port: 8080
    protocol: TCP
```

We only bind to one of them!
