### ISSUE TITLE
Add egress rules to istioctl

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#552]
Add egress-rule to istioctl, without taking egress-rules into effect yet. Part of https://github.com/istio/istio/issues/496

Format:
```yaml
type: egress-rule
spec:
    name: cnn
    domain:  "*cnn.com"
    ports:
      - port: 80
         protocol: http
      - port: 8080
         protocol: http
   use_egress_proxy: true
```
