### ISSUE TITLE
proxyless gRPC: max requests 1024 exceeded on service

### ISSUE THREAD

**Issue by kytool** [istio/istio#55202]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

grpc client error: code = Unavailable desc = max requests 1024 exceeded on service outbound|9090||grpc-server.test.svc.cluster.local
I configured DR, but it didn't work
 ```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test
  namespace: istio-system
spec:
  host: grpc-server.test.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: DO_NOT_UPGRADE
        http1MaxPendingRequests: 3000
        http2MaxRequests: 3000
        idleTimeout: 120s
        maxRetries: 3
      tcp:
        connectTimeout: 2s
        maxConnections: 3000
    loadBalancer:
      simple: ROUND_ROBIN
```
because grpcgen does not apply ConnectionPool to CircuitBreakers

![Image](https://github.com/user-attachments/assets/22a3b517-7c7b-460d-8f7e-31e61876d519)

 

### Version

```Text
$ istioctl version
client version: 1.13.7
control plane version: 1.13

grpc-go version: v1.44.0
```
