### ISSUE TITLE
Sticky Session [ Consistent hash ] Not working with Istio Ambient Mode

### ISSUE THREAD

**Issue by Prashant-Dwivedi-08-01** [istio/istio#55259]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I am trying to validate the L7 features of Istio in it's Ambient Mode. I was trying to validate the Consistent hash load balancing ( https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB ) in Ambient mode. However, the functionality do not seem to work as expected and the traffic is being randomly routed to any random instance/endpoint of the deployment.

### Version

```Text
Istioctl Version Output

client version: 1.23.0
control plane version: 1.23.3
data plane version: 1.23.3 (12 proxies)

Kubectl Version 

Client Version: v1.25.16
Kustomize Version: v4.5.7
Server Version: v1.31.5-eks-8cce635
```

### Additional Information

As part of my setup; I have a deployment with 5 replicas. This deployment in exposed via a service. 
Then I configured a destination rule that implements the consistent hash or sticky-session.

### Destination Rule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sticky-session-destination-rule
  namespace: sticky-session
spec:
  host: helloworld-svc
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: test
          ttl: 60s
```

All are part of same namespace. And the namespace is enabled for ambient data-plane mode. Also I have configured the waypoint proxy ( of type service ) and have attached it to the namespace for it to be used.

After this, I have making a curl call from another client helloworld app in same namespace,  but this curl call goes to different pods every time even though we have the Destination Rule Configured for the same.

### Waypoint Logs
```
[2025-02-25T12:06:03.943Z] "GET /?1 HTTP/1.1" 200 - via_upstream - "-" 0 146 7 7 "-" "curl/7.61.1" "f68bef8e-cf1b-9fd2-9ebe-e249a0cd9dea" "helloworld-svc" "envoy://connect_originate/100.72.5.240:8000" inbound-vip|80|http|helloworld-svc.sticky-session.svc.cluster.local envoy://internal_client_address/ 10.100.121.193:80 100.72.4.210:38318 - default
[2025-02-25T12:06:03.957Z] "GET /?2 HTTP/1.1" 200 - via_upstream - "-" 0 146 7 6 "-" "curl/7.61.1" "04c68f39-c62c-9ded-86fe-ee629e075d1d" "helloworld-svc" "envoy://connect_originate/100.72.12.146:8000" inbound-vip|80|http|helloworld-svc.sticky-session.svc.cluster.local envoy://internal_client_address/ 10.100.121.193:80 100.72.4.210:38318 - default
[2025-02-25T12:06:03.965Z] "GET /?3 HTTP/1.1" 200 - via_upstream - "-" 0 146 7 6 "-" "curl/7.61.1" "eb06972b-8ac1-9944-b382-8383ab234394" "helloworld-svc" "envoy://connect_originate/100.72.85.204:8000" inbound-vip|80|http|helloworld-svc.sticky-session.svc.cluster.local envoy://internal_client_address/ 10.100.121.193:80 100.72.4.210:38318 - default
```

#### Note: Same Setup works fine when using Sidecar Mode

**Comment by howardjohn** [comment]
Thanks. https://github.com/istio/istio/blob/2a2cc8e452fe69a778519de52a960008b9e8f4f0/pilot/pkg/networking/core/listener_waypoint.go#L797  vs https://github.com/istio/istio/blob/c39842db8ef6e28ad5e85d50626585f147d9686b/pilot/pkg/networking/core/route/route.go#L553 is the gap in why its not showing up. I think its time we spend some effort merging these codepaths to reduce the risk of behavioral divergence like this

**Comment by Prashant-Dwivedi-08-01** [comment]
@howardjohn If I understood that right, then it means that Sticky Session wont work currently with Waypoint Proxies sitting in there.
Just FYI, I also tried the same setup with an http route as well; and it doesn't seem to work.
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-sticky-session
  namespace: sticky-session
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: helloworld-svc
      port: 80
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: helloworld-svc
          port: 80
      sessionPersistence:
        cookieConfig:
          lifetimeType: Session
        sessionName: "test"
```

When can we expect the stable working?
I have the similar issue with below features as well;( neither working with Virtual Service nor with Http route )
1. Retry
2. Mirroring

**Comment by howardjohn** [comment]
@Prashant-Dwivedi-08-01 yeah I think that field has the same gap. I am working to make them share a codepath so they cannot diverge

**Comment by howardjohn** [comment]
Actually I think `sessionPersistence` is not implemented in Istio at all so that part won't change.

**Comment by howardjohn** [comment]
Mirror and retry should already work though, if you can share your config it would help

**Comment by plstryagain** [comment]
Will the fix be available in 1.24.x?

**Comment by shixinh70** [comment]
I tested the `consistenthash` feature in version `1.26.0-beta.0`, but the behavior is still not as expected
Here are my test settings and results, wondering if there's anything I might have missed.

### Version
#### Istio
client version: 1.26.0-beta.0
control plane version: 1.26.0-beta.0
data plane version: 1.26.0-beta.0 (6 proxies)
#### Kubectl
client version: 1.22
server version: 1.32
#### Setup
- Ambient data-plane is enabled in both the `src` and `src1` namespaces.  
- Waypoint proxies are deployed for both namespaces.  
- In the `src1` namespace, there is a `helloworld` service with two endpoints.
- Curl from src to src1 with cookie user with command
`curl -sS --cookie "user=test"  helloworld.src1.svc.cluster.local:5000/hello`
#### Result
Not working as expected.
I also test the `httpHeaderName` field, but it fails too.
```
Hello version: v1, instance: helloworld-v1-846974f68c-z4hdh
Hello version: v1, instance: helloworld-v1-846974f68c-xjv8s
Hello version: v1, instance: helloworld-v1-846974f68c-xjv8s
Hello version: v1, instance: helloworld-v1-846974f68c-z4hdh
Hello version: v1, instance: helloworld-v1-846974f68c-xjv8s
Hello version: v1, instance: helloworld-v1-846974f68c-z4hdh
```
However, if I set the `src` namesapce to sidecar data-plane, it works
#### Infromation
##### DestinationRule
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: hellodr
spec:
  host: helloworld.src1.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 1h
```
##### Other
istioctl zc service
```
NAMESPACE    SERVICE NAME         SERVICE VIP   WAYPOINT ENDPOINTS
src          helloworld           10.96.21.132  waypoint 1/1
src          waypoint             10.96.169.3   None     1/1
src1         helloworld           10.96.172.31  waypoint 2/2
src1         waypoint             10.96.30.96   None     1/1
```
istioctl pc cluster deploy/waypoint -n src1
```
SERVICE FQDN                          PORT     SUBSET     DIRECTION       TYPE             DESTINATION RULE
helloworld.src1.svc.cluster.local     5000     http       inbound-vip     EDS              hellodr.src1
```

**Comment by shenshouer** [comment]
How to use consistentHash in ambient mode ?

**Comment by tarangini-shetty** [comment]
i am facing behaviour where session stickiness doesnt work with waypoint proxy. is it the same problem?  are there any workarounds?

**Comment by keithmattix** [comment]
@howardjohn looks like #55280 didn't fix this

**Comment by tarangini-shetty** [comment]
workaround mentioned in https://github.com/istio/istio/issues/56218#issuecomment-2966675118, made the waypoint proxy and session stickiness(using destination rule) to work together in a namespace. 
Ie., adding a virtualservice to the service of the pods that needs stickiness. 

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: <name>
spec:
  hosts:
  - <servicehostname>
  http:
  - name: "default-route"
    route:
    - destination:
        host: <servicehostname>
```

Is it the expected behaviour? would this have any other implications?
