### ISSUE TITLE
Issue with DNS autoallocate V2 - traffic going out the wrong VIP

### ISSUE THREAD

**Issue by jbilliau-rcd** [istio/istio#55266]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We recently upgraded to Istio `1.24` (canary install), using the new functionality `PILOT_ENABLE_IP_AUTOALLOCATE`. Our `ServiceEntries` now have VIP's propagated right under their `status` field. Most of our apps are going smoothly and fine....until today. 

We had a developer contact us that his RabbitMQ cluster was borked. Turns out, the requests for `x.zone:5671` are going out the VIP for the `ServiceEntry` for `x.zone:5672`!

ServiceEntries in-place:

```YAML
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: rabbitmq-test-novarabbit
  namespace: rabbitmq-test
spec:
  exportTo:
    - .
  hosts:
    - rabbitmq-test-amqp.nova-np.x.zone
  location: MESH_EXTERNAL
  ports:
    - name: novarabbit
      number: 5672
      protocol: TCP
  resolution: DNS
status:
  addresses:
    - host: rabbitmq-test-amqp.nova-np.x.zone
      value: 240.240.0.159
    - host: rabbitmq-test-amqp.nova-np.x.zone
      value: 2001:2::9f
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: rabbitmq-test-novarabbit-1
  namespace: rabbitmq-test
spec:
  exportTo:
    - .
  hosts:
    - rabbitmq-test-amqp.nova-np.x.zone
  location: MESH_EXTERNAL
  ports:
    - name: novarabbitamqps
      number: 5671
      protocol: TCP
  resolution: DNS
status:
  addresses:
    - host: rabbitmq-test-amqp.nova-np.x.zone
      value: 240.240.0.160
    - host: rabbitmq-test-amqp.nova-np.x.zone
      value: 2001:2::a0
```

In the istio-logs:

```
rabbitmq-test-1 istio-proxy [2025-02-25T19:37:42.136Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster; - 240.240.0.159:5671 100.64.16.49:36288 - - - -
rabbitmq-test-1 istio-proxy [2025-02-25T19:37:47.143Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster; - 240.240.0.159:5671 100.64.16.49:47622 - - - -
rabbitmq-test-1 istio-proxy [2025-02-25T19:37:52.150Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster; - 240.240.0.159:5671 100.64.16.49:47636 - - - -
rabbitmq-test-1 istio-proxy [2025-02-25T19:37:57.157Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster; - 240.240.0.159:5671 100.64.16.49:38500 - - - -
rabbitmq-test-1 istio-proxy [2025-02-25T19:38:02.163Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster; - 240.240.0.159:5671 100.64.16.49:38522 - - - -
rabbitmq-test-1 istio-proxy [2025-02-25T19:38:07.171Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster; - 240.240.0.159:5671 100.64.16.49:44192 - - - -
```

You can see istio is pairing the request out 5671 through the VIP assigned to the SE for 5672. 

Even more interesting is if I disable this new DNS v2 stuff via putting `networking.istio.io/enable-autoallocate-ip: "false"` on the ServiceEntry as described [here](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#dns-auto-allocation-v2), everything goes back to working just fine. 

TL;DR - Does DNS AutoAllocate V2 work with 2 `ServiceEntries` for the same TCP hostname, but going out different ports? My testing seems to say it doesn't.

### Version

```Text
istioctl version
client version: 1.23.0
istiod version: 1.22.5
istiod version: 1.22.5
istiod version: 1.22.5
istiod version: 1.24.2
istiod version: 1.24.2
istiod version: 1.24.2
data plane version: 1.24.2 (68 proxies)


kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.9-eks-8cce635
```
