### ISSUE TITLE
ServiceEntry not published to envoy with some extra labels

### ISSUE THREAD

**Issue by pachas7** [istio/istio#55272]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We have some problems when we are trying to open conections TCP to a database from an application. Seems that the serviceentries with some extra labels are not published to the envoy. 

The problem is only reproduced when we create some serviceentries. With only one serviceentry is working.
I will attach two yaml files, one with labels(KO) and another one without it(OK). Also the debug logs from the envoy.

**Control-plane values config** 

```yaml
global:
  meshID: test
  multiCluster:
    enabled: true
    clusterName: "test"
    globalDomainSuffix: "local"
    includeEnvoyFilter: false
  network: test

pilot:
  env:
    PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING: "false"

meshConfig:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"

env:
  PILOT_FILTER_GATEWAY_CLUSTER_CONFIG: true
```

There are the labels affected:
**Labels Affected**
```
istio-request/general-id: "xxx"  
istio-request/item-id: "xxx"  
istio-sec/port-XXX-XXX: "true"  
istio-sec/protocol: tcp
```

Extra info and commands debug: the cluster is not published on the envoy for the connectivity

**istioctl pc listener --port 1554**
```
0.0.0.0   1554 ALL                    Non-HTTP/Non-TCP
0.0.0.0   1554 Addr: 10.148.42.0/24   Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.215.32/27   Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.210.224/27  Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.211.32/27   Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.211.0/27    Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.219.64/27   Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.219.32/27   Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.219.0/27    Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.218.224/27  Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.20.42.0/24    Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.211.64/27   Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.215.0/27    Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.214.224/27  Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.214.192/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.212.192/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.210.192/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.214.160/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.212.160/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.210.160/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.214.128/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.212.128/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.27.210.128/27 Cluster: outbound|1554||cnn.com
0.0.0.0   1554 Addr: 10.0.215.64/27   Cluster: outbound|1554||cnn.com
```

**istioctl pc clusters --port 1554**
```
NULL
```

[se-fail.txt](https://github.com/user-attachments/files/18982424/se-fail.txt)
[se-works.txt](https://github.com/user-attachments/files/18982425/se-works.txt)
[envoy.log](https://github.com/user-attachments/files/18982451/envoy.log)

### Version

```Text
$ istioctl version
client version: 1.24.3
control plane version: 1.24.3
data plane version: 1.24.2 (68 proxies), 1.24.3 (33 proxies)

$ kubectl version
Client Version: v1.31.4
Kustomize Version: v5.4.2
Server Version: v1.30.9+IKS
```

**Comment by AgustinICAI** [comment]
What we have found is that also using other labels such as pepe-sec/port-xxxx-xxxx: "true" at 20 or 30 different serviceentries referring TCP - mesh external different ports/address is not working.

Is there any limit in the cardinality of keys of the labels? Maybe we shouldn't have included that information as labels, and it should be annotations. This is the way we are going to solve it, but is there any limit in the number o different labels that can be used at a serviceentry?

**Comment by pachas7** [comment]
I reproduced the bug with less ServiceEntries. 
Seems that after configure the label `networking.istio.io/enable-autoallocate-ip`  the scenario is reproduced.
If you create the below file, the cluster on the envoy is not created, and if we create the same objects without labels, works.

Also, seems that not all time is failing, sometimes creates the cluster, anothers no.

```yaml
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test-1
  labels:
    istio-request/general-id: "7459"
    istio-request/item-id: "0"
    istio-sec/port-1521-1535: "true"
    istio-sec/protocol: tcp
    ssi/agrupacion-43ca21e6e6636a5d: "true"
    ssi/modelizacion-9dcfca5d09f2b702: "true"
    ssi/modelizacion-treePath-b9ae95b69db80af6: "true"
    networking.istio.io/enable-autoallocate-ip: "false"
spec:
  addresses:
  - 10.0.214.192/27
  - 10.0.212.192/27
  - 10.0.210.192/27
  - 10.0.214.160/27
  - 10.0.212.160/27
  - 10.0.210.160/27
  - 10.0.214.128/27
  - 10.0.212.128/27
  - 10.0.210.128/27
  exportTo:
  - .
  hosts:
  - test.test.test.com
  location: MESH_EXTERNAL
  ports:
  - name: tcp1521
    number: 1521
    protocol: TCP
  - name: tcp1522
    number: 1522
    protocol: TCP
  - name: tcp1523
    number: 1523
    protocol: TCP
  - name: tcp1524
    number: 1524
    protocol: TCP
  - name: tcp1525
    number: 1525
    protocol: TCP
  - name: tcp1526
    number: 1526
    protocol: TCP
  - name: tcp1527
    number: 1527
    protocol: TCP
  - name: tcp1528
    number: 1528
    protocol: TCP
  - name: tcp1529
    number: 1529
    protocol: TCP
  - name: tcp1530
    number: 1530
    protocol: TCP
  - name: tcp1531
    number: 1531
    protocol: TCP
  - name: tcp1532
    number: 1532
    protocol: TCP
  - name: tcp1533
    number: 1533
    protocol: TCP
  - name: tcp1534
    number: 1534
    protocol: TCP
  - name: tcp1535
    number: 1535
    protocol: TCP
  resolution: NONE

---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test-2
  labels:
    istio-request/general-id: "7459"
    istio-request/item-id: "0"
    istio-sec/port-1554-1556: "true"
    istio-sec/protocol: tcp
    ssi/agrupacion-43ca21e6e6636a5d: "true"
    ssi/modelizacion-9dcfca5d09f2b702: "true"
    ssi/modelizacion-treePath-b9ae95b69db80af6: "true"
    networking.istio.io/enable-autoallocate-ip: "false"
spec:
  addresses:
  - 10.0.214.192/27
  - 10.0.212.192/27
  - 10.0.210.192/27
  - 10.0.214.160/27
  - 10.0.212.160/27
  - 10.0.210.160/27
  - 10.0.214.128/27
  - 10.0.212.128/27
  - 10.0.210.128/27
  exportTo:
  - .
  hosts:
  - test.test.test.com
  location: MESH_EXTERNAL
  ports:
  - name: tcp1554
    number: 1554
    protocol: TCP
  - name: tcp1555
    number: 1555
    protocol: TCP
  - name: tcp1556
    number: 1556
    protocol: TCP
  resolution: NONE
```
