### ISSUE TITLE
Configuration to trust "trust domains" between two or more service mesh clusters

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#55288]
**Describe the feature request**
We have two service mesh clusters, using SPIRE with shared root CA for certificate lifecycle management.

When setting up istio in cluster1, we use trustDomain: `dev.cluster1.internal`, and for cluster2 we use `dev.cluster2.internal`.

When client in cluster 1 connects to server in cluster 2, it fails TLS handshake, with the error: Unknown CA.

How can the two clusters be configured to trust each other?

**Describe alternatives you've considered**
Use trustDomain aliases.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Dual Stack
[ ] Installation
[] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by tjons** [comment]
Hey @nirvanagit - can you add more information about your SPIRE setup? Since you have two different trust domains, you should be using two different SPIRE server deployments, as SPIRE only supports one trust domain per server deployment. Are you federating these two SPIRE deployments together? If you add some more details, I can better understand what might be going wrong. https://istio.io/latest/docs/ops/deployment/deployment-models/#trust-between-meshes has some docs about the design decisions the Istio project has taken here. You can federate via the SPIFFE federation spec but the operator is responsible for this, not Istio itself. 

If it does appear your SPIRE servers are federated properly, you should test that mTLS handshake with issued SVIDs works successfully outside the context of Istio.

**Comment by jewertow** [comment]
@nirvanagit you probably need DestinationRule with SAN for both trust domains, like:
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin-federated-trust-domain
spec:
  host: httpbin.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      subjectAltNames:
      - spiffe://dev.cluster1.internal/ns/default/sa/httpbin
      - spiffe://dev.cluster2.internal/ns/default/sa/httpbin
```

You can try this [demo](https://github.com/jewertow/upstream-istio/tree/samples-spire-federation/samples/security/spire-trust-domain-federation) to see how it works, but you have to fetch that branch and build istioctl, because that setup relies on recent changes in gateway injection template.
