### ISSUE TITLE
grpc-timeout header overrides timeout when route timeout not specified

### ISSUE THREAD

**Issue by wtzhang23** [istio/istio#55287]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

[max_grpc_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto) is set to 0 when the route timeout is not configured. This is due to the following [code](https://github.com/istio/istio/blob/c37260f4e21afb08f42f1c070eacc25d80753f1d/pilot/pkg/networking/core/route/route.go#L1302-L1306) which uses the [Notimeout constant](https://github.com/istio/istio/blob/c37260f4e21afb08f42f1c070eacc25d80753f1d/pilot/pkg/networking/core/route/route.go#L68) instantiated to 0. According to Envoy documentation:
> If configured as 0, the maximum allowed timeout for gRPC requests is infinity.

This results in the sidecar always respecting the propagated `grpc-timeout` header. This results in Envoy enforcing the timeout rather than deferring the timeout to the upstream service.

This has been around for a long time, so it might as well be a feature at this point. A pilot environment variable or VirtualService api change enabling toggling grpc timeouts on or off can help though for users (aka us :)) who don't want this feature.

### Version

```Text
Relevant helm chart configs:

chart: istiod
repoURL: https://istio-release.storage.googleapis.com/charts
targetRevision: 1.22.3
```

**Comment by wtzhang23** [comment]
We wanted to disable this due to the issue described in https://github.com/envoyproxy/envoy/issues/10184. Mitigation exists through an Envoy filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: map-upstream-timeout-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            local_reply_config:
              mappers:
                - filter:
                    and_filter:
                      filters:
                        - response_flag_filter:
                            flags: ["UT"]
                        - grpc_status_filter:
                            statuses: ["UNAVAILABLE"]
                  status_code: 200
                  headers_to_add:
                    - header:
                        key: "grpc-status"
                        value: "4"
                      append_action: OVERWRITE_IF_EXISTS_OR_ADD
```
