### ISSUE TITLE
Potential security hole - to be confirmed

### ISSUE THREAD

**Issue by stephaneey** [istio/istio#55295]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi,

As I'm not sure whether we can call this a security vulnerability or not or a "crashing bug" so I report this as a problem here.

I'm using the Istio Egress gateway. For TCP workloads such as SQL, I'm tunneling traffic from the workload namespace to the egress one. Everything works fine. However, any non-Istio-injected pod can just tunnel the traffic to the Istio egress gateway as well...

Here are the steps to reproduce the problem:

1) ServiceEntry

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-sql-db
  namespace: application1-egress
spec:
  hosts:
  - adatabase.database.windows.net
  addresses:
  - <an Azure Private Endpoint>
  location: MESH_EXTERNAL
  ports:
  - number: 1433
    name: sql
    protocol: TCP
  resolution: DNS  
---
```

2) Routing

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sql-egress-gateway  
  namespace: application1-egress
spec:
  selector:
    istio: app1-egressgateway
  servers:
  - port:
      number: 1433
      name: sql
      protocol: TCP
    hosts:
    - "adatabase.database.windows.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressdr-for-sql
  namespace: application1-egress
spec:
  host: app1-egressgateway.application1-egress.svc.cluster.local
  trafficPolicy:
    tls:      
      mode: ISTIO_MUTUAL #no effect here
  subsets:
  - name: sql
  exportTo: [".","application1-app-ns1"]
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-sql-through-egress-gateway  
  namespace: application1-egress
spec:
  hosts:
  - "adatabase.database.windows.net"
  gateways:
  - sql-egress-gateway
  - mesh
  tcp:
  - match:    
    - gateways:
      - mesh
      port: 1433    
    route:
    - destination:
        host: app1-egressgateway.application1-egress.svc.cluster.local
        subset: sql
        port:
          number: 1433  
  - match:
    - gateways:
      - sql-egress-gateway
      port: 1433
    
    route:
    - destination:
        host: adatabase.database.windows.net
        port:
          number: 1433
  exportTo: [".","application1-app-ns1"]
---
```

With that, any Istio injected workload that is in the 'application1-app-ns1' namespace and trying to connect to the sql database is routed to the egress gateway and everything works fine.

However, if I exec into a non-injected pod (busybox) in the same namespace and perform the following commands:

```
vi /etc/hosts ==> there I add a line <egress gateway pod ip> <adatabase.database.windows.net>
apk update
apk add freetds 
tsql -H adatabase.database.windows.net -p 1433 -U <user> -P <password>
```

I'm on the database...although I'm not part of Istio's world but I can leverage the egress gateway pod as a tunnel to my destination. Is it the expected behavior. Is there anything I missed?

Trying to put network policies does not help here because the routing takes place first before Calico kicks in so the egress gateway is what is seen as the next hop.

### Version

```Text
client version: 1.24.3
control plane version: 1.24.3
data plane version: 1.20.0 (2 proxies), 1.24.3 (7 proxies)

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.9", GitCommit:"a87cd6906120a367bf6787420e943103a463acba", GitTreeState:"clean", BuildDate:"2025-01-16T18:49:42Z", GoVersion:"go1.22.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.30) exceeds the supported minor version skew of +/-1
```

**Comment by keithmattix** [comment]
By default, istio allows non mTLS traffic to hit meshed pods. If you want to prevent that, use a  PeerAuthentication with mTLS mode = STRICT

**Comment by stephaneey** [comment]
Hi @keithmattix,

Thanks for your answer but I of course did it already. I just forgot to mention it but I always use Istio in STRICT mode. This however, seems to apply only to istio-injected pods. Gateways, being ingress and egress are not injected by default. I have tried to inject them but no luck.

**Comment by keithmattix** [comment]
h right; gateways don't enforce peer authn. What you can probably do it deploy an authz policy to the egress gateway and require the presence of a source principal. This is equivalent to STRICT PeerAuthentication

**Comment by stephaneey** [comment]
that won't work if the gateway isn't injected and as I said, it is not. I tried to force the injection but no luck.

**Comment by keithmattix** [comment]
Gateways still support Authorization policy with label selector; they always have. Injection is an implementation detail. You have two options:
1. AuthorizationPolicy targeting your egress gateway that requires a source principal
2. Use the `Gateway` resource (networking.istio group) to set the TLS mode of the egress gateway to ISTIO_MUTUAL like so (preferred):
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: egress
  namespace: istio-egress
spec:
  selector:
    istio: egressgateway
  servers:
...
    tls:
      mode: ISTIO_MUTUAL
```

**Comment by howardjohn** [comment]
If you are not sure, please report privately in the future... Thanks.

**Comment by stephaneey** [comment]
> If you are not sure, please report privately in the future... Thanks.

Well, I would have liked to but the process doesn't seem that straightforward. In any case, if you consider this as a security issue, I'm fine to close this one (even delete) and keep the conversation in private if you provide me with an email or any other communication channel.

Thanks

**Comment by keithmattix** [comment]
@stephaneey IIUC, you want your traffic path to be:
```
istio sidecar (Istio mTLS) --> (enforces Istio mTLS) egress gateway --> (tcp) Azure SQL
```

Is this correct? If so, then your egress gateway protocol on 1433 should be TLS. If you change the protocol in your `Gateway` to TLS, you should be rid of that error message

**Comment by howardjohn** [comment]
> > If you are not sure, please report privately in the future... Thanks.
> 
> Well, I would have liked to but the process doesn't seem that straightforward. In any case, if you consider this as a security issue, I'm fine to close this one (even delete) and keep the conversation in private if you provide me with an email or any other communication channel.
> 
> Thanks

On the template you filled out, when you checked "This is not a security vulnerability or a crashing bug" there is a link to https://istio.io/latest/docs/releases/security-vulnerabilities/ which has an email which can be used for the future. No need to move this one

**Comment by keithmattix** [comment]
If you can share error messages that will be helpful. Your sidecar injected pods should work fine with an ISTIO_MUTUAL TLS mode

**Comment by stephaneey** [comment]
Well, I have a SQL client (console app) that simply returns this:

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake`

if I only switch from 'tcp' to 'tls'. Now, even if I try to update my VS and my DR accordingly, it keeps failing. I only manage to make it work with 'tcp' but then, we're back to square 1. What I want to achieve is exactly what you highlighted:

`istio sidecar (Istio mTLS) --> (enforces Istio mTLS) egress gateway --> (tcp) Azure SQL`

but I have tried thousands things and never got it working. So, if you see how to configure this, please let me know as currently, my conclusion is that it is not possible and thus, I have a security issue that any non-Istio pod can leverage the egress gateway as a tunnel to a destination for TCP traffic.

**Comment by keithmattix** [comment]
There's not a security hole here; this is certainly possible to do. I'll respond next week with a working configuration

**Comment by keithmattix** [comment]
@stephaneey I just went through these docs and was successful in getting mTLS + TLS origination working: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/. It will largely be the same for TCP; the things I see missing from your original config are:
1. ISTIO_MUTUAL TLS on the _subset_ of your destinationRule. You'll also need to set the SNI you want to use (likely adatabase.database.windows.net, whatever the certificate is for the DB).
2. An extra DestinationRule to set up SIMPLE TLS for when your egress gateway talks to the DB:
```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-tls-for-azuresq;
spec:
  host: adatabase.database.windows.net
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 1443
      tls:
        mode: SIMPLE # initiates HTTPS for connections to adatabase.database.windows.net
```

**Comment by stephaneey** [comment]
Hi @keithmattix,

Thanks for your answer but I doubt this could work. First, TLS Origination assumes that the application container starts the conversation in HTTP instead of HTTPS. That is something that I don't want to do, plus it doesn't even apply here given we're talking in raw TCP, not in HTTP. Secondly, if you look carefully at my previous posts, you'll see that I had already applied ISTIO_MUTUAL to my destination rule. TLS origination is rather meant to compensate legacy apps that were still talking HTTP and let the gateway initiate the TLS traffic instead of the app itself. Do you have an end to end example that is doing this:

`istio sidecar (Istio mTLS) --> (enforces Istio mTLS) egress gateway --> (tcp) Azure SQL`

knowing that the application is using the SQL SDK. Remember that I'm already able to let my Istio pods route their traffic to SQL through the egress gateway but my problem is that non-istio pods can do the same.

Thanks
Best Regards

**Comment by keithmattix** [comment]
> First, TLS Origination assumes that the application container starts the conversation in HTTP instead of HTTPS. That is something that I don't want to do, plus it doesn't even apply here given we're talking in raw TCP, not in HTTP

I used HTTP in this scenario just because it's plaintext; HTTP vs. TCP is just an implementation detail.

> knowing that the application is using the SQL SDK. Remember that I'm already able to let my Istio pods route their traffic to SQL through the egress gateway but my problem is that non-istio pods can do the same.

Ok so what you're describing is a bit different than that flow chart. The way I interpret this is:

```
app (TLS) --> (passthrough) istio sidecar (initiate Istio mTLS) --> (terminate Istio mTLS) egress gateway (passthrough original application TLS) --> Azure SQL
```

Is that correct?

**Comment by stephaneey** [comment]
You mean an implementation detail at Istio level, because in the OSI model, there are two different layers? Given that my connection string has these parameters: "Encrypt=True;TrustServerCertificate=False;", I guess that that this:

`app (TLS) --> (passthrough) istio sidecar (initiate Istio mTLS) --> (terminate Istio mTLS) egress gateway (passthrough original application TLS) --> Azure SQL`

is indeed the right flow. I just want to make sure that the tunnel made available by the Istio egress gateway cannot be reused by a non-istio pod.

**Comment by keithmattix** [comment]
Yes exactly; as long as HTTP attributes aren't being used to route, TCP vs. HTTP is effectively an implementation detail in this context. What really matters is plaintext vs. HTTP. 

> I just want to make sure that the tunnel made available by the Istio egress gateway cannot be reused by a non-istio pod.

If you're not using TLS origination or otherwise giving your egress gateway special certificates or access to your off-cluster assets, then there's no real damage a non-mesh client can do even if they talk to the egress gateway. To that point, if your Azure SQL client is initiating TLS on its own, what are you wanting to use the egress gateway for? Why not just have your sidecar proxy the data through?

FWIW, the reason I'm asking all of this is because in sidecar mode, the egress gateway UX is rough because it's very literal. There's no magic that Istio is going to do for you; the user has to understand and configure the SNI, TLS mode, etc. at every step, so if you can avoid it, you'll be better off. In ambient mode, the egress gateway experience is far better because it's based on waypoints.

**Comment by stephaneey** [comment]
We use the egress gateway because we want to identify the set of nodes from which traffic leaves the cluster, which is the primary reason why you use them whether working with HTTP or HTTPS. Here is a quote from the Istio web site:

> Consider an organization that has a strict security requirement that all traffic leaving the service mesh must flow through a set of dedicated nodes

The fact that a non-authenticated pod can simply talk to the egress gateway one is simply a problem. If you look back at what I said, I could reach out to the database server with the TSQL client and run queries against it through the egress gateway. The firewall sees this as legitimate traffic (because it comes from one of the egress nodes), although that should be restricted to Istio pods only. I think that we clearly have a problem here.

**Comment by keithmattix** [comment]
> We use the egress gateway because we want to identify the set of nodes from which traffic leaves the cluster, which is the primary reason why you use them whether working with HTTP or HTTPS

This use-case is precisely why non-meshed pods can go through the egress gateway. If an organization wants all traffic to egress through a dedicated set of nodes, then whether that traffic is meshed or not is an orthogonal concern. And it's certainly not a security issue; it's a legitimate use-case that we support by design.

> If you look back at what I said, I could reach out to the database server with the TSQL client and run queries against it through the egress gateway

Your gateway is doing its own TLS and auth; the _only_ reason a non-Istio pod can reach your database is because the DB allows it.

> The firewall sees this as legitimate traffic (because it comes from one of the egress nodes), although that should be restricted to Istio pods only. I think that we clearly have a problem here.

Ok, THIS is the missing piece from your description; you're the IP(s) of the egress gateway(s) as a firewall rule in front of your DB. That's the security hole in your setup, not anything inherent to Istio. 

I _think_ this is still possible, but I didn't test it because I thought you were wanting TLS origination. I'll give it a try and get back to you. Do be aware though, that this is a double-encrypt flow that means neither your egress gateway nor your sidecar will be able to enforce HTTP policies or emit HTTP telemetry (metrics, traces, logs)
```
app (TLS) --> (passthrough) istio sidecar (initiate Istio mTLS) --> (terminate Istio mTLS) egress gateway (passthrough original application TLS) --> Azure SQL
```

**Comment by stephaneey** [comment]
Since we use the _Istio Egress Gateway_, I think it is legitimate to expect Istio to restrict traffic to Istio-only pods. The fact that the firewall only sees the egress node IPs is by design. I don't see why this is a flaw. It is exactly the same as putting an API gateway as a policy enforcement point and whitelist that gateway for upstream traffic. Source pod IPs are anyway not static so you can't (shouldn't) try to whitelist them. So, if you start form the assumption that you can rule container-level traffic with Istio and Calico so that only authorized service entries and meshed pods  can talk to the egress gateway, you can then trust the egress gateway...Now, if anything can use that egress gateway as a proxy no matter whether meshed or not, you can't trust it anymore. Sorry to say but I don't consider this a non-istio issue. The ask is pretty simple: restrict egress gateway to istio-only pods, nothing else! So, is that possible or not?

**Comment by keithmattix** [comment]
Sure, you can configure it to work like that, but we support other configurations as well. Egress Gateway within Istio is a use-case, not a specific product; the exact same binary and CRD configurations are used for the ingress gateway. I now understand what use-case you're trying to address, and I'm not saying it's flawed or invalid. Just keep in mind that Istio is a platform that services a lot of use-cases. Regardless, here's the configuration you need (I adapted this from the cnn example and confirmed it worked for tls passthrough, so double-check the SNI hosts and ports for your use-case. I've tried to do some substitution for you):
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: azuredb
spec:
  hosts:
  - adatabase.database.windows.net
  ports:
  - number: 1443
    name: tcp
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 1443
      name: mtls-terminate-then-passthrough
      protocol: TLS
    hosts:
    - adatabase.database.windows.net
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 1443
        tls:
          mode: ISTIO_MUTUAL
          sni: adatabase.database.windows.net
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: direct-azuredb-through-egress-gateway
  namespace: default
spec:
  gateways:
  - istio-egressgateway
  - mesh
  hosts:
  - adatabase.database.windows.net
  tls:
  - match:
    - gateways:
      - mesh
      port: 1443
      sniHosts:
      - adatabase.database.windows.net
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 1443
        subset: cnn
      weight: 100
  tcp:
  - match:
    - gateways:
      - istio-egressgateway
      port: 1443
    route:
    - destination:
        host: adatabase.database.windows.net
        port:
          number: 1443
      weight: 100
```

**Comment by stephaneey** [comment]
Hi @keithmattix,

Thanks for the time spent on trying to fix the issue. However, I don't know how you tested but it doesn't work. I have adjusted your code because the port number was wrong 1443 instead of 1433. I also got rid of references to 'CNN'. Here is the adjusted code:

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: sql-istio-egressgateway
  namespace: application1-egress
spec:
  selector:    
    istio: app1-egressgateway
  servers:
  - port:
      number: 1433
      name: mtls-terminate-then-passthrough
      protocol: TLS
    hosts:
    - adatabase.database.windows.net
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: egressgateway-for-sql
  namespace: application1-egress
spec:
  host: app1-egressgateway.application1-egress.svc.cluster.local
  subsets:
  - name: sql
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 1433
        tls:
          mode: ISTIO_MUTUAL
          sni: adatabase.database.windows.net
    
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: direct-azuredb-through-egress-gateway
  namespace: application1-egress
spec:
  gateways:
  - sql-istio-egressgateway
  - mesh
  hosts:
  - adatabase.database.windows.net
  tls:
  - match:
    - gateways:
      - mesh
      port: 1433
      sniHosts:
      - adatabase.database.windows.net
    route:
    - destination:
        host: app1-egressgateway.application1-egress.svc.cluster.local
        port:
          number: 1433
        subset: sql
      weight: 100
  tcp:
  - match:
    - gateways:
      - sql-istio-egressgateway
      port: 1433
    route:
    - destination:
        host: adatabase.database.windows.net
        port:
          number: 1433
      weight: 100
  exportTo: [".","application1-app-ns1"]

```

My SQL client (.NET) just crashes with the usual error:

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)`. To be completely exhaustive, here is the .NET code (very simple):

```
using (SqlConnection conn = new SqlConnection(Environment.GetEnvironmentVariable("conn")))    
{
    try
    {

        SqlCommand command = new SqlCommand("select count(*) from atable", conn);
        conn.Open();
        int count = (int)command.ExecuteScalar();
        Console.WriteLine(count);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
    finally
    {
        if (conn.State == System.Data.ConnectionState.Open)
        {
            conn.Dispose();
            conn.Close();

        }
    }
}

```
