### ISSUE TITLE
Unable to get certificates provided by custom SDS server for ingressgateways

### ISSUE THREAD

**Issue by abhide** [istio/istio#55303]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Currently, in my test setup HTTPs traffic is terminated at istio-ingressgateway using SSL certificates that are specified as a kubernetes secret via Gateway CR

```
apiVersion: networking.istio.io/v1
kind: Gateway
spec:
 selector:
    app: istio-ingressgateway
 servers:
  - hosts:
    - www.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      credentialName: wildcard-cert  # -- this is kubernetes secret
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

I want to use TLS certificates  provided by a custom SDS server that is running as sidecar alongside the istio-ingressgateway. This TLS certificate is fetched and made available to ingressgateway via UDS volumeMount.
I want to use this SDS based certificate selectively for certain hosts. 

In order to do this, I modified the ingressgateway deployment spec to add SDS sidecar, create volumeMounts and added the annotation `proxy.Metadata.credentialSocket` 
I specified the SDS server cluster and tlsSettings using EnvoyFilter CR

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_8443
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls # configure TLS
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext # incoming request
            common_tls_context: # TLS configuration for listener
              tls_certificate_sds_secret_configs:
                - name: sds_server_uds
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        - envoy_grpc:
                            cluster_name: sds_server_uds
- applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
          name: sds_server_uds
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          load_assignment:
            cluster_name: sds_server_uds
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        pipe:
                          path: /tmp/uds_path
```

I updated the gateway CR to reference the sds certificate

```
$ k get gateway test-gateway -oyaml
 tls:
   credentialName: sds://sds_server_uds
   minProtocolVersion: TLSV1_2
   mode: SIMPLE

```
I can see that endpoint and cluster getting added to the ingressgateway
```
$ istioctl pc cluster istio-ingressgateway-6c97679967-ptq4k | less
SERVICE FQDN                                                                                           PORT      SUBSET     DIRECTION     TYPE       DESTINATION RULE
sds_server_uds                                                                                         -         -          -             STATIC

$ istioctl pc endpoint istio-ingressgateway-6c97679967-ptq4k | less
ENDPOINT                                                STATUS      OUTLIER CHECK     CLUSTER
unix:///tmp/uds_path                                    HEALTHY     OK                sds_server_uds
```

The downstreamTlsContext is also updated for the listener
```
$ istioctl pc cluster istio-ingressgateway-6c97679967-ptq4k | less
        "transport_socket": {
          "name": "envoy.transport_sockets.tls",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
           "common_tls_context": {
            "tls_params": {
             "tls_minimum_protocol_version": "TLSv1_2",
            },
            "alpn_protocols": [
             "h2",
             "http/1.1"
            ],
            "tls_certificate_sds_secret_configs": [
             {
              "name": "kubernetes:sds://sds_server_uds",
              "sds_config": {
               "api_config_source": {
                "api_type": "GRPC",
                "grpc_services": [
                 {
                  "envoy_grpc": {
                   "cluster_name": "sds_server_uds"
                  }
                 }
                ]
               }
              }

```
There are no errors in ingressgateway logs. 

However, the configuration that's getting generated is `kubernetes:sds://sds_server_uds` which seems incorrect. 

### Version

```Text
$ istioctl version
client version: 1.24.3
control plane version: 1.23.3
data plane version: 1.23.3 (1 proxies)

$ kubectl version
Client Version: v1.31.1
Server Version: v1.29.13
```
