### ISSUE TITLE
Cors and rbac filter has unexpected behavior, Cors is not responding instantly

### ISSUE THREAD

**Issue by mhbahmani** [istio/istio#55318]
I'm using istio as API Gateway and have several filters configured.
The problem is that I want to put `cors` filter, ahead of the `rbac` filter, meaning that if the incoming request matches with the cors policy, the envoy instantly responds with 200 (or 204), and the request doesn't go through the `rbac` filter. However, even when I managed to put cors as the first http_filter, the request still goes through the `rbac` filter. This will make us add OPTIONS to authorization policy resources (with allow action).

To make sure that the cors is the first filter in the chain, I'm using the config below in my envoyfilter (there are other INSERT_FIRST filters that are above this filter in EnvoyFilter, so in enovy config, they are added after the cors filter): 
```yaml
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.cors
        portNumber: 5050
    patch:
      operation: REMOVE
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 5050
    patch:
      operation: INSERT_FIRST
      value:  
        name: envoy.filters.http.cors
        typed_config:

```

`cors` filter is at the top, but still is should add `OPTIONS` to my authorization policy. For now, I added an all-inclusive authorization policy that allows all the `OPTIONS` (in rbac filter).

**Expected behaivour**
If incoming request matches the criteria for `cors` filter, the filters responds instantly and the request doesn't go through rbac filter.   
[Same issue at envoy project](https://github.com/envoyproxy/envoy/issues/38556)
