### ISSUE TITLE
mTLS origination in ambient mode

### ISSUE THREAD

**Issue by mosessond** [istio/istio#55329]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I am trying to use istio ambient to do mTLS origination, and am running into a problem where the gateway cannot read the secret.

 The current error showing in istiod logs is that the waypoint is not authorized to read secrets, when a DestinationRule is configured to originate mTLS: warn ads proxy waypoint-<>.<ns> attempted to access unauthorized certificates <secret-name>: waypoint/<ns> is not authorized to read secrets I have verified that the following commands both return yes:
kubectl auth can-i list secrets --as=system:serviceaccount:istio-system:waypoint --namespace=istio-system
kubectl auth can-i list secrets --as=system:serviceaccount:<workload ns>:default --namespace=istio-system
The DR config is:
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: <>
  namespace: <>
spec:
  host: <fqdn>
  trafficPolicy:
     tls:
       credentialName: <secretName>
       mode: MUTUAL
```

The code doing this I think is here: https://github.com/istio/istio/blob/6f6b4a6a71d8aa87ab0b205302ef267270b7fc16/pilot/pkg/xds/sds.go#L263C1-L266C66, and I was not able to find a reference to a ReferencePolicy that I could create that would allow this, and as above, I did give workload pod RBAC to list secrets in the istio-system namespace.
Any ideas how this could be resolved? I would think something like this is the common case for mTLS origination

### Version

```Text
client version: 1.25.0-rc.1
control plane version: 1.25.0-rc.1
data plane version: 1.25.0-rc.1

client version: v1.29.10
server version: v1.31.6
```

**Comment by JesperBerggren** [comment]
Hi guys!

Any news on this error?

We're making a big move from the classic sidecar model to ambient mesh for our clusters and currently this issue is obstructing us from progressing any further.

**Comment by mosessond** [comment]
We finally got a handle on this, and probably docs should get updated to more clearly cover this case. We ended up with:

- Gateway in istio-system
- TLS secret in istio-system
- RBAC explicitly allowing listing of secrets by the waypoint service account (note: the kubectl can-i check actually doesn't matter because istio does it's own check and it does it differently I think)
- ServiceEntry/DestinationRule can live in either the workload or istio-system namespaces, both work.
- On the workload namespace, you need to set the labels:
  - istio.io/dataplane-mode: ambient
  - istio.io/use-waypoint: waypoint
  - istio.io/use-waypoint-namespace: istio-system

**Comment by JesperBerggren** [comment]
Hi @mosessond 

Thanks for sharing your findings!

I still hope for some response from the developers because this seems like a workaround rather than the final solution.

In your testing, did you find that it was actually necessary to move the waypoint to istio-system namespace? I would really prefer not to do that, and at first glance it looks like an rbac issue that could be solved by allowing the waypoint in a given namespace access to read secrets in that namespace!?

Also, can you share your rbac for the waypoint? :)

**Comment by JesperBerggren** [comment]
Hi again,

To answer my own question, then it's perfectly possible to keep the waypoint and secret in any given namespace.

We added this role and rolebinding to the waypoint in a namespace called metadefender:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waypoint-read-secrets
  namespace: metadefender
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waypoint-read-secrets-binding
  namespace: metadefender
subjects:
  - kind: ServiceAccount
    name: waypoint
    namespace: metadefender
roleRef:
  kind: Role
  name: waypoint-read-secrets
  apiGroup: rbac.authorization.k8s.io
```

After that it was necessary to restart the waypoint and then everything works perfectly :)

Now I agree with @mosessond, the documentation should be updated to clarify this.
