### ISSUE TITLE
2 ServiceEntry selecting 1 pod is broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#55334]
Config:

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: s1
spec:
  hosts:
  - s1.internal
  ports:
  - name: http
    number: 8000
    protocol: HTTP
    targetPort: 80
  resolution: STATIC
  workloadSelector:
    labels:
      app: echo
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: s2
spec:
  hosts:
  - s2.internal
  ports:
  - name: http
    number: 8000
    protocol: HTTP
    targetPort: 80
  resolution: STATIC
  workloadSelector:
    labels:
      app: echo
```

Check instances by `istioctl x internal-debug instancesz | jq '.["echo-5cb8c4f97c-842bw.default"]' | rg hostname`

1. Apply s1
2. instances: [s1]
3. Apply s2
4. instances: [s2]. BROKEN, should be [s1,s2]
5. Remove s2
6. instances: []. BROKEN, should be [s1]
