### ISSUE TITLE
Missing cni ambient reconcileIptablesOnStartup in istio operator

### ISSUE THREAD

**Issue by kiddo3** [istio/istio#55347]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi,
I'm trying to set up new configuration for istio `1.25.0` and found right now is not possible to configure it on operator:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    accessLogFile: /dev/stdout
...
  values:
    cni:
      ambient:
        enabled: true
        reconcileIptablesOnStartup: true
```

Error when generating manifest:
```
Error: could not unmarshal: error unmarshaling JSON: while decoding JSON: unknown field "reconcileIptablesOnStartup" in istio.operator.v1alpha1.CNIAmbientConfig
```

For now I'm using a workaround using `cni.k8s.overlays` to set env variable `AMBIENT_RECONCILE_POD_RULES_ON_STARTUP`.

### Version

```Text
istioctl 
client version: 1.25.0
```

**Comment by Nova-Logic** [comment]
tbh this istio operator deprecation made life 1000 times worse. It is becoming a total mess with upgrading and managing istio with istioctl. some of the features from helm charts are unavailable in istioctl IstioOperator manifests

**Comment by howardjohn** [comment]
@Nova-Logic you can use the exact same `IstioOperator` configuration with `istioctl install` or `istioctl manifest generate`. Or if you specifically want an operator, you can migrate to one of the options here: https://istio.io/latest/blog/2024/in-cluster-operator-deprecation-announcement/#how-do-i-migrate; a few are even API compatible.

**Comment by howardjohn** [comment]
While we should expose reconcileIptablesOnStartup in the IstioOperator API, fwiw you can workaround it by putting it under `unvalidatedValues` instead of `values` (or use `--force`, but I wouldn't recommend that since it would force _all_ errors)

**Comment by Nova-Logic** [comment]
@howardjohn Thanks for your suggestion. I had written it just to highlight a problem a bit, especially since unvalidatedValues not so-well documented, I already spent quite some time into digging how to configure affinity/tolerations for a waypoints. But all of us know that running on a bleeding edge sometimes requires an additional effort:-)

**Comment by Yufeireal** [comment]
New to istio, hit similar issue.  We use a customized script to generate manifests based on istioctl generate manifests.  Set unvalidatedValues worked. 

Also filed a PR, new to istio, would appreciate some reviews/comments, thanks!
https://github.com/istio/istio/pull/55744

**Comment by aaronjwood** [comment]
> While we should expose reconcileIptablesOnStartup in the IstioOperator API, fwiw you can workaround it by putting it under `unvalidatedValues` instead of `values` (or use `--force`, but I wouldn't recommend that since it would force _all_ errors)

FWIW I followed what was suggested here and upon a `rollout restart ds` I still see `2025-04-13T23:11:43.946935Z     warn    cni-agent       reconcile is needed but no-reconcile flag is set. Unexpected behavior may occur due to preexisting iptables rules       component=host`

The CM seems to have what it needs via `AMBIENT_RECONCILE_POD_RULES_ON_STARTUP` unless it's for something else entirely:
```
data:
  AMBIENT_DNS_CAPTURE: "true"
  AMBIENT_ENABLED: "true"
  AMBIENT_IPV6: "true"
  AMBIENT_RECONCILE_POD_RULES_ON_STARTUP: "true"
  CHAINED_CNI_PLUGIN: "true"
  CURRENT_AGENT_VERSION: 1.25.1
  EXCLUDED_NAMESPACES: kube-system
  REPAIR_BROKEN_POD_LABEL_KEY: cni.istio.io/uninitialized
  REPAIR_BROKEN_POD_LABEL_VALUE: "true"
  REPAIR_DELETE_PODS: "false"
  REPAIR_ENABLED: "true"
  REPAIR_INIT_CONTAINER_NAME: istio-validation
  REPAIR_LABEL_PODS: "false"
  REPAIR_REPAIR_PODS: "true"
```
