### ISSUE TITLE
Access log format is wrong when upgrading to 1.23

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [istio/istio#55349]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi! We want to upgrade Istio from 1.22.6 to 1.23.5. One of the changes that were made between these two versions is a switch from "UPSTREAM_CLUSTER" to "UPSTREAM_CLUSTER_RAW" in the access log format.

This issue is related to this change - https://github.com/istio/istio/pull/52384

Basically, for workloads that use 1.22, the log format should use "UPSTREAM_CLUSTER", and for 1.23+, it should be "UPSTREAM_CLUSTER_RAW".

However, we spot an issue here, which is probably related to accesslog cache (?), see https://github.com/istio/istio/pull/39751

The issue is that for a workload that uses version 1.22.6, it receives an access log format that is intended for 1.23+.

Here are the resources that I use:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
#      annotations:
#        sidecar.istio.io/proxyImage: docker.io/istio/proxyv2:1.22.6
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep infinity; done;"]
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: faulty-telemetry
spec:
  accessLogging:
    - filter:
        expression: request.url_path.contains('/msisdn')
      providers:
        - name: envoy
```

Steps to reproduce:
- deploy dummy telemetry
- deploy dummy workload that uses 1.23.5 proxy (without annotation)
- dump the config using istioctl: `istioctl proxy-config all deploy/ubuntu-deployment -o yaml > /tmp/ubuntu-local.yaml`
- The dump has access log format that uses "UPSTREAM_CLUSTER_RAW"
- Change proxy version to 1.22.6 by uncommenting annotation from deployment. Apply deployment change.
- Dump config from pod that uses 1.22.6 proxy - `istioctl proxy-config all ubuntu-deployment-6857584b8c-8w222 -o yaml > /tmp/ubuntu-local.yaml`
- The dump contains error: `details: 'Not supported field in StreamInfo: UPSTREAM_CLUSTER_RAW'`

This issue can be fixed by removing telemetry and adding it again. I am assuming that by doing this, the cache is cleared, and the proper config is sent to the workload.

The desired state is that the cache (if it is causing the issue) should contain workload version as a key, so that when a workload version is changed, the cache is cleared.

### Version

```Text
$ istioctl version
client version: 1.23.3
control plane version: 1.23.5
data plane version: 1.22.6 (1 proxies), 1.23.3 (2 proxies), 1.23.5 (2 proxies)

$ kubectl version --context eu1tst-eks001
Client Version: v1.30.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.9-eks-8cce635
```
