### ISSUE TITLE
Use ILB for istio mc

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#5535]
We are now using pod ip for istio mc, the problem is that once the pod restart, ip will be changed and we need to re-install istio-remote.

We should use ILB and assign a ILB IP for those services.

/cc @sdake @sbezverk @linsun

**Comment by sbezverk** [comment]
@gyliu513 I am not sure if it is a problem, as pilot runs a controller which is watching changes on the remote cluster, so in theory it should detect ip address change. I have not tested it though.

**Comment by gyliu513** [comment]
@sbezverk Even if the local istio control panel using `LoadBalancer` for `pilot`, `policy` etc, the remote cluster still need to use `pilot pod ip`, 'policy pod ip' to connect back to local istio control panel, I did not see much that the local istio control panel using `LoadBalancer` can help. Am I missing anything?

**Comment by sbezverk** [comment]
@gyliu513 my bad, I missed the point that you were talking about pilot's pod. If instead, we use pilot's service external IP and have it resolvable via external DNS, then remote cluster's proxy should not have any problem communicating with pilot. WDYT?

**Comment by sdake** [comment]
@sbezverk right - and that is what @gyliu513 was talking about with using ILBs I thought?

**Comment by gyliu513** [comment]
@sbezverk @sdake any comments on what kind of service/ep that need to be run on remote cluster if I have some ILB running on local istio control plane?

Now checking if service mesh expansion can help for this case https://preliminary.istio.io/docs/setup/kubernetes/mesh-expansion.html

**Comment by costinm** [comment]
Mesh expansion is what you should use for now - it provides a fixed IP, and has been
used for this purpose for some time.

In 1.0 we can add an external IP using a Gateway to the pilot GRPC-TLS port, but it's not
 ready or tested in 0.8.

**Comment by linsun** [comment]
Following up the discussion here, are we saying for 0.8, we can't expose pilot as a LB service and use that LB ip as the PilotEndpoint when configuring the remote-istio?   If so, this is a major limitation we should document in release note.

What is the main hurdle for supporting this in 0.8?

**Comment by gyliu513** [comment]
@linsun for multi-cluster, we already mentioned the current limitation for ip change at https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install.html#helm-configuration-parameters

I'm now checking for how to use ILB for mc in istio 0.8 but not sure if I can catch this release as I need do more checking for how can service mesh expansion can help this case.

When 0.8 will be released? Want to check if I can catch up this release.

**Comment by linsun** [comment]
Talked to @costinm, he believes this is a doc issue and we should be able to use LB ip.  @gyliu513 @sdake comments?

**Comment by gyliu513** [comment]
Thanks @linsun Let me do some test first ...

**Comment by gyliu513** [comment]
Still not clear for how to leverage mesh expansion ILB in Multi-Cluster support.



The above is current solution for Multi-Cluster support, we are using pilot pod ip, policy pod ip and statsd pod ip in remote cluster to create the service end point and connect back to the local cluster.

But with ILB, even if I expose pilot, policy and statsd as ILB services, how can the remote cluster use those services? How to make the remote cluster register back to local cluster?

@costinm @sdake any comments for this? Thanks.

**Comment by sbezverk** [comment]
@gyliu513 @costinm @sdake 
I hope I am wrong but I just do not see how it could work without some sort of global/dynamic dns where all services which are part of MC gets registered.
I would greatly appreciate a detailed walk through with the current implementation to demonstrate how the use case presented by @gyliu513 can work.
I would like to mention two options which imho could solve this use case:
1. Addition to the remote cluster controller a piece of code, which dynamically creates and updates in case of a change, records for istio services required on a remote cluster (pilot, policy and statsd) with ip address of local cluster's ingress. In this case when remote cluster needs to access one of these services a simple dns resolution against of a local kube dns will provide an actual address.  
2. Revisit k8s federation for the purpose of global services visibility.
Appreciate your comments.

**Comment by sdake** [comment]
@gyliu513 the istio-remote helm chart allows you to specify the endpoints for pilot/statsd/policy.  The model is to instantiate the remotes first, then the istio control plane last with the keys from the remotes.  It may make sense to automate istio-remote with a controller/operator as @sbezverk had mentioned,

@sbezverk re global service visibility - coredns looks like a good solution and will come standard in 1.11 of Kubernetes.  I think we should just consider using that for service discovery cross-cluster.

RE k8s federation, folks are welcome to try this model, however, we found three complete blockers during rampup on Istio:
1. sidcars (iirc) run with --privileged mode.  Sadly k8s federation does not implement this functionlaity
1. using k8s federation for managing the Istio control plane doesn't work - tons of gaps in k8s federation.
1. k8s federation (take 1) supports about 8-10 objects in Kubernetes.  There are roughly ~50 objects in Kubernetes making it difficult to federate applications effectively.

I did see the federation effort is taking a mulligan - which might make the next rev more viable for Istio's usage.

**Comment by sdake** [comment]
@sbezverk i can provide a walkthrough on Saturday or early next week if you like.  The implementation works well enough, although there are some usability problems that need attention.

**Comment by sdake** [comment]
@gyliu513 Istio 0.8 is in the final stretch and coming RSN.  I am not sure we can fix the pod's being killed and restarted with a new IP problem prior to 0.8.

I'd still encourage the work proceed one way or another targeting 1.0.

**Comment by sbezverk** [comment]
@sdake it would be great if you could comment how `coredns` as is, would solve inter cluster services visibility.

**Comment by gyliu513** [comment]
Did more test today and ILB works fine, commit the ILB file to https://github.com/gyliu513/work/blob/master/k8s/istio/mc/istio-mc-ilb.yaml , the content is as follows:

```
# Currently specific to GKE. Annotations specific to other providers should be added
# after they get tested.
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot-ilb
  namespace: istio-system
  labels:
    istio: pilot
spec:
  type: LoadBalancer
  loadBalancerIP: 9.111.255.5
  ports:
  - name: https-pilot-1
    port: 15003
    protocol: TCP
  - name: https-pilot-2
    port: 15005
    protocol: TCP
  - name: https-pilot-3
    port: 15007
    protocol: TCP
  - name: https-pilot-4
    port: 15010
    protocol: TCP
  - name: https-pilot-5
    port: 15011
    protocol: TCP
  - port: 8080
    name: http-pilot-6
    protocol: TCP
  - name: https-pilot-7
    port: 9093
    protocol: TCP
  selector:
    istio: pilot
---
apiVersion: v1
kind: Service
metadata:
  name: istio-policy-ilb
  namespace: istio-system
  labels:
    istio: mixer
spec:
  type: LoadBalancer
  loadBalancerIP: 9.111.255.7
  selector:
    istio: mixer
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: istio-statsd-prom-bridge-ilb
  namespace: istio-system
  labels:
    istio: statsd-prom-bridge
spec:
  type: LoadBalancer
  loadBalancerIP: 9.111.255.4
  selector:
    istio: statsd-prom-bridge
  ports:
  - name: statsd-udp
    port: 9125
    protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: zipkin-ilb
  namespace: istio-system
spec:
  type: LoadBalancer
  loadBalancerIP: 9.111.255.3
  ports:
  - name: http
    port: 9411
  selector:
    app: jaeger

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-citadel
  name: istio-citadel
  namespace: istio-system
spec:
  type: LoadBalancer
  loadBalancerIP: 9.111.255.10
  ports:
  - name: grpc-citadel
    port: 8060
  - name: http-monitoring
    port: 9093
  selector:
    istio: citadel
```

Please note I was hard-coding the `loadBalancerIP` due to I only have limited IP address so have to hardcode those IP address.

After the ILB running well, update the remote istio service endpoint by using ILB address, it works.

```
root@gyliu-ubuntu-1:~# kubectl get ep -n istio-system
NAME                       ENDPOINTS                                                          AGE
istio-citadel              9.111.255.10:9093,9.111.255.10:8060                                3h
istio-pilot                9.111.255.5:9093,9.111.255.5:15010,9.111.255.5:15007 + 4 more...   3h
istio-policy               9.111.255.7:9093,9.111.255.7:9091,9.111.255.7:15004                3h
istio-statsd-prom-bridge   9.111.255.4:9125                                                   3h
zipkin                     9.111.255.3:9411                                                   1h
```
