### ISSUE TITLE
Envoy TCP metrics not getting reported

### ISSUE THREAD

**Issue by psikka1** [istio/istio#55367]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We are interested in getting some Envoy level [TCP metrics](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats.html#tcp-statistics), specifically 
```
cx_tx_percent_retransmitted_segments
cx_rtt_us
```
But unable to get that to work. We have tried building istio proxy by removing the [tcp_stats](https://github.com/istio/proxy/blob/c299ef83326a08f59303b1b2f23a5c65d1cfcfb9/bazel/extension_config/extensions_build_config.bzl#L504-L507)  from the disabled extensions list. And included in proxyConfig as such - 

```yaml
     proxy.istio.io/config: |
         proxyStatsMatcher:
           inclusionSuffixes:
             - "cx_tx_percent_retransmitted_segments"
             - "cx_rtt_us"
```
But envoy is not emitting these metrics as observed by `localhost:15000/stats` 

### Version

```Text
❯ istioctl version
client version: 1.23.5
control plane version: 1.23-a6b65f3
data plane version: 1.23-a6b65f3 (1434 proxies)
❯ kubectl version
Client Version: v1.30.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.9-eks-8cce635
```

### Additional Information

Kernel version - 5.10.230-223.885.amzn2.x86_64

**Comment by zirain** [comment]
same as https://istio.slack.com/archives/C382V8Q92/p1741129304116539?

**Comment by psikka1** [comment]
[ingress-config-dump.json](https://github.com/user-attachments/files/19090071/ingress-config-dump.json)

**Comment by psikka1** [comment]
I was able to get it to work with this config - 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-stats-transport-socket-1.23
  namespace: istio-system
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      proxy:
        proxyVersion: ^1\.23.*
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tcp_stats
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tcp_stats.v3.Config
            transport_socket:
              name: envoy.transport_sockets.raw_buffer
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
            update_period: 30s
```
