### ISSUE TITLE
Validation is rejecting connectionPool.tcp.IdleTimeout=0s

### ISSUE THREAD

**Issue by leosarra** [istio/istio#55409]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Currently the validation webhook is rejecting DR that have the are setting the idletimeout=0s for connectionPool.

For example, the following configuration would end up rejected although it is valid:
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: dr-mykind
spec:
  exportTo:
  - .
  host: example.com
  trafficPolicy:
    connectionPool:
      tcp:
        idleTimeout: 0s
    portLevelSettings:
```

In our doc we mention:

> The idle timeout for TCP connections. The idle timeout is defined as the period in which there are no bytes sent or received on either the upstream or downstream connection. If not set, the default idle timeout is 1 hour. **If set to 0s, the timeout will be disabled.** ...

### Version

```Text
-
```
