### ISSUE TITLE
SidecarScope no longer merging ports in Istio 1.23.4

### ISSUE THREAD

**Issue by dwj300** [istio/istio#55428]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We're upgrading from 1.21.5 to 1.23.4, and have noticed the following behavior change. We have a SeviceEntry (on the config cluster A) and Service (on workload cluster B) with the same FQDN, but slightly different ports, and on 1.21.5, noticed that the ports list is merged, but on 1.21.5, we only see the ports present in the k8s Service. We're seeing the listener is correct on the the client sidecar, but it's missing the cluster for 8075. The cluster registryz debug output is the same between 1.21 and 1.23, but the newer SidecarScope doesn't have port 8075.
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: mesh-e2e-server-mesh-a-ea1t-us-se
  namespace: mesh-e2e-mesh-a-ea1t-us
spec:
  addresses:
  - 100.124.135.171
  hosts:
  - mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a
  location: MESH_INTERNAL
  ports:
  - name: grpc-8079
    number: 8079
    protocol: grpc
  - name: http-8080
    number: 8080
    protocol: http
  - name: tcp-8075
    number: 8075
    protocol: tcp
  resolution: STATIC
  workloadSelector:
    labels:
      app: mesh-e2e-server-mesh-a-ea1t-us
---
apiVersion: v1
kind: Service
metadata:
  name: mesh-e2e-server-mesh-a-ea1t-us
  namespace: mesh-e2e-mesh-a-ea1t-us
spec:
  clusterIP: 100.124.59.110
  clusterIPs:
  - 100.124.59.110
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-8078
    port: 8078
    protocol: TCP
    targetPort: 8078
  - name: grpc-8079
    port: 8079
    protocol: TCP
    targetPort: 8079
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  publishNotReadyAddresses: true
  selector:
    app: mesh-e2e-server-mesh-a-ea1t-us
    mini-announcer-status: ready
  type: ClusterIP
```

Here is the `/debug/sidecarz` output for the client pod that's missing the 8075 cluster (from 1.21 and 1.23):
```
{
  "destinationRules": {
    "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a": [
      {}
    ]
  },
  "name": "mesh-e2e-tcp-client-mesh-a-ea1t-us",
  "namespace": "mesh-e2e-mesh-a-ea1t-us",
  "outboundTrafficPolicy": {
    "mode": "ALLOW_ANY"
  },
  "services": [
    {
      "Attributes": {
        "ServiceRegistry": "Kubernetes",
        "Name": "mesh-e2e-server-mesh-a-ea1t-us",
        "Namespace": "mesh-e2e-mesh-a-ea1t-us",
        },
        "ExportTo": null,
        "LabelSelectors": {
          "app": "mesh-e2e-server-mesh-a-ea1t-us",
          "mini-announcer-status": "ready"
        },
        "Aliases": null,
        "ClusterExternalAddresses": null,
        "ClusterExternalPorts": null,
        "PassthroughTargetPorts": null,
        "Type": "ClusterIP",
        "ExternalName": "",
        "NodeLocal": false
      },
      "ports": [
        {
          "name": "tcp-8078",
          "port": 8078,
          "protocol": "TCP"
        },
        {
          "name": "grpc-8079",
          "port": 8079,
          "protocol": "GRPC"
        },
        {
          "name": "http-8080",
          "port": 8080,
          "protocol": "HTTP"
        }
      ],
      "creationTime": "2024-07-29T20:07:33Z",
      "hostname": "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a",
      "clusterVIPs": {
        "Addresses": {
          "mesh-a-ea1t-us": [
            "100.124.59.110"
          ]
        }
      },
      "defaultAddress": "100.124.59.110",
      "Resolution": 0,
      "MeshExternal": false,
      "ResourceVersion": "1231860397"
    }
  ],
  "servicesByHostname": {
    "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a": {
      "Attributes": {
        "ServiceRegistry": "Kubernetes",
        "Name": "mesh-e2e-server-mesh-a-ea1t-us",
        "Namespace": "mesh-e2e-mesh-a-ea1t-us",
        },
        "ExportTo": null,
        "LabelSelectors": {
          "app": "mesh-e2e-server-mesh-a-ea1t-us",
          "mini-announcer-status": "ready"
        },
        "Aliases": null,
        "ClusterExternalAddresses": null,
        "ClusterExternalPorts": null,
        "PassthroughTargetPorts": null,
        "Type": "ClusterIP",
        "ExternalName": "",
        "NodeLocal": false
      },
      "ports": [
        {
          "name": "tcp-8078",
          "port": 8078,
          "protocol": "TCP"
        },
        {
          "name": "grpc-8079",
          "port": 8079,
          "protocol": "GRPC"
        },
        {
          "name": "http-8080",
          "port": 8080,
          "protocol": "HTTP"
        }
      ],
      "creationTime": "2024-07-29T20:07:33Z",
      "hostname": "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a",
      "clusterVIPs": {
        "Addresses": {
          "mesh-a-ea1t-us": [
            "100.124.59.110"
          ]
        }
      },
      "defaultAddress": "100.124.59.110",
      "Resolution": 0,
      "MeshExternal": false,
      "ResourceVersion": "1231860397"
    }
  },
  "sidecar": {
    "workloadSelector": {
      "labels": {
        "app": "mesh-e2e-tcp-client-mesh-a-ea1t-us"
      }
    },
    "egress": [
      {
        "hosts": [
          "./mesh-e2e-tcp-client-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a",
          "mesh-e2e-mesh-a-ea1t-us/mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a"
        ]
      }
    ]
  },
  "version": "2025-03-07T05:35:59Z/4872"
}
```
Compared to the `/debug/sidecarz` from 1.21.5:
```
{
  "destinationRules": {
    "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a": [
      {}
    ]
  },
  "name": "mesh-e2e-tcp-client-mesh-a-ea1t-us",
  "namespace": "mesh-e2e-mesh-a-ea1t-us",
  "outboundTrafficPolicy": {
    "mode": "ALLOW_ANY"
  },
  "rootNamespace": "istio-system",
  "services": [
    {
      "Attributes": {
        "ServiceRegistry": "External",
        "Name": "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a",
        "Namespace": "mesh-e2e-mesh-a-ea1t-us",
        "ExportTo": null,
        "LabelSelectors": {
          "app": "mesh-e2e-server-mesh-a-ea1t-us"
        },
        "Aliases": null,
        "ClusterExternalAddresses": null,
        "ClusterExternalPorts": null,
        "Type": "",
        "ExternalName": "",
        "NodeLocal": false
      },
      "ports": [
        {
          "name": "grpc-8079",
          "port": 8079,
          "protocol": "GRPC"
        },
        {
          "name": "http-8080",
          "port": 8080,
          "protocol": "HTTP"
        },
        {
          "name": "tcp-8075",
          "port": 8075,
          "protocol": "TCP"
        },
        {
          "name": "tcp-8078",
          "port": 8078,
          "protocol": "TCP"
        }
      ],
      "creationTime": "2024-07-29T20:07:22Z",
      "hostname": "mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a",
      "clusterVIPs": {
        "Addresses": null
      },
      "defaultAddress": "100.124.135.171",
      "Resolution": 0,
      "MeshExternal": false,
      "ResourceVersion": ""
    }
  ],
  "sidecar": {
    "workloadSelector": {
      "labels": {
        "app": "mesh-e2e-tcp-client-mesh-a-ea1t-us"
      }
    },
    "egress": [
      {
        "hosts": [
          "./mesh-e2e-tcp-client-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a",
          "mesh-e2e-mesh-a-ea1t-us/mesh-e2e-server-mesh-a-ea1t-us.mesh-e2e-mesh-a-ea1t-us.svc.ea1t.us.a"
        ]
      }
    ]
  },
  "version": "2025-03-07T05:40:41Z/5929"
}
```

### Version

```Text
istio 1.23.4
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
