### ISSUE TITLE
help: can't seem to apply this envoy filter

### ISSUE THREAD

**Issue by jack4it** [istio/istio#55429]
would be great if someone can help cross check if anything is wrong with the yaml. really appreciate it!

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: host-rewrite
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          vhost:
            name: kourier-internal.kourier-system.svc.cluster.local:80
            # route:
            #   name: default
      patch:
        operation: MERGE
        value:
          host_rewrite_header: '%REQ(knative-service)%'
  # workloadSelector:
  #   labels:
  #     service.istio.io/canonical-name: test
```
