### ISSUE TITLE
Upgrade to istio 1.22.8 , error toJsonMAP

### ISSUE THREAD

**Issue by anaykhairatkar** [istio/istio#55434]
Just upgraded to istio  1.22.8 and we are seeing the below errors in pod logs

```
 resources:
      {{ template "resources" . }}
        volumeMounts:
        - name: workload-socket
          mountPath: /var/run/secrets/workload-spiffe-uds
        {{- if eq .Values.global.caName "GkeWorkloadCertificate" }}
        - name: gke-workload-certificate
          mountPath: /var/run/secrets/workload-spiffe-credentials
          readOnly: true
        {{- else }}
        - name: workload-certs
          mountPath: /var/run/secrets/workload-spiffe-credentials
        {{- end }}
        {{- if eq .Values.global.pilotCertProvider "istiod" }}
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        {{- end }}
        - mountPath: /var/lib/istio/data
          name: istio-data
        # UDS channel between istioagent and gRPC client for XDS/SDS
        - mountPath: /etc/istio/proxy
          name: istio-xds
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        {{- if .Values.global.mountMtlsCerts }}
        # Use the key and cert mounted to /etc/certs/ for the in-cluster mTLS communications.
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
        {{- end }}
        - name: istio-podinfo
          mountPath: /etc/istio/pod
        {{- end }}
          {{- if isset .ObjectMeta.Annotat{"level":"error","time":"2025-03-09T19:38:36.292659Z","msg":"failed to create discovery service: error initializing sidecar injector: failed to create injection webhook: failed reading config: template: inject:7: function \"toJsonMap\" not defined. YAML:\n# defaultTemplates defines the default template to use for pods that do not explicitly specify a template\ndefaultTemplates: [sidecar]\npolicy: enabled\nalwaysInjectSelector:\n  []\nneverInjectSelector:\n  []\ninjectedAnnotations:\ntemplate: \"{{ Template_Version_And_Istio_Version_Mismatched_Check_Installation }}\"\ntemplates:\n  sidecar: |\n    {{- define \"resources\"  }}\n      {{- if or (isset .ObjectMeta.Annotations sidecar.istio.io/proxyCPU) (isset .ObjectMeta.Annotations sidecar.istio.io/proxyMemory) (isset .ObjectMeta.Annotations sidecar.istio.io/proxyCPULimit) (isset .ObjectMeta.Annotations sidecar.istio.io/proxyMemoryLimit) }}\n        {{- if or (isset .ObjectMeta.Annotations sidecar.istio.io/proxyCPU) (isset .ObjectMeta.Annotations sidecar.istio.io/proxyMemory) }}\n          requests:\n            {{ if (isset .ObjectMeta.Annotations sidecar.istio.io/proxyCPU) -}}\n            cpu: \"{{ index .ObjectMeta.Annotations sidecar.istio.io/proxyCPU }}\"\n            {{ end }}\n            {{ if (isset .ObjectMeta.Annotations sidecar.istio.io/proxyMemory) -}}\n            memory: \"{{ index .ObjectMeta.Annotations sidecar.istio.io/proxyMemory }}\"\n            {{ end }}\n        {{- end }}\n        {{- if or (isset .ObjectMeta.Annotations sidecar.istio.io/proxyCPULimit) (isset .ObjectMeta.Annotations sidecar.istio.io/proxyMemoryLimit) }}\n          limits:\n            {{ if (isset .ObjectMeta.Annotations sidecar.istio.io/proxyCPULimit) -}}\n            cpu: \"{{ index .ObjectMeta.Annotations sidecar.istio.io/proxyCPULimit }}\"\n            {{ end }}\n            {{ if (isset .ObjectMeta.Annotations sidecar.istio.io/proxyMemoryLimit) -}}\n            memory: \"{{ index .ObjectMeta.Annotations sidecar.istio.io/proxyMemoryLimit }}\"\n            {{ end }}\n        {{- end }}\n      {{- else }}\n        {{- if .Values.global.proxy.resources }}\n          {{ toYaml .Values.global.proxy.resources | indent 6 }}\n        {{- end }}\n      {{- end }}\n    {{- end }}\n    {{ $nativeSidecar := (eq (env \"ENABLE_NATIVE_SIDECARS\" \"false\") \"true\") }}\n    {{- $containers := list }}\n    {{- range $index, $container := .Spec.Containers }}{{ if not (eq $container.Name \"istio-proxy\") }}{{ $containers = append $containers $container.Name }}{{end}}{{- end}}\n    metadata:\n      labels:\n        security.istio.io/tlsMode: {{ index .ObjectMeta.Labels security.istio.io/tlsMode | default \"istio\"  | quote }}\n        {{- if eq (index .ProxyConfig.ProxyMetadata \"ISTIO_META_ENABLE_HBONE\") \"true\" }}\n        networking.istio.io/tunnel: {{ index .ObjectMeta.Labels networking.istio.io/tunnel | default \"http\"  | quote }}\n        {{- end }}\n        service.istio.io/canonical-name: {{ index .ObjectMeta.
```

Deployment logs  - Deployment is not ready: istio-system/istiod - timing out

`
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   
[helm] ready.go:277: [debug] Deployment is not ready: istio-system/istiod. 0 out of 2 expected pods are ready   `
