### ISSUE TITLE
istio-proxy grow memory very rapidly and smoothly even with low QPS

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#55439]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

istio-proxy grow memory very rapidly and smoothly util its reaches OOM even with low QPS.. 

Istio-proxy Memory:
![Image](https://github.com/user-attachments/assets/abf95cdf-e3e7-4f45-99e1-a79b33cb8960)

![Image](https://github.com/user-attachments/assets/63fad841-4834-42f1-b758-0faedfd96925)

Envoy active connection:
![Image](https://github.com/user-attachments/assets/e6ea29c7-5bb2-46a2-9e23-d34a61082e7a)

Istio-proxy outbound QPS, without inbound QPS:

![Image](https://github.com/user-attachments/assets/0ca74d9d-752c-453a-be83-50b3c5324638)

### Version

```Text
$ istioctl version
client version: 1.16.5
istiod version: 1.16
istiod version: 1.16
istiod version: 1.18.7
istiod version: 1.18.7
istiod version: 1.19.10
istiod version: 1.19.10
data plane version: 1.16.5 (3 proxies), 1.18.7 (226 proxies), 1.19.10 (33 proxies), 65536.65536.65536 (3 proxies)
```

**Comment by keithmattix** [comment]
This is fixed in newer, supported versions of istio. Please upgrade

**Comment by Patrick0308** [comment]
This is heap flame graph：

![Image](https://github.com/user-attachments/assets/0ea8cdbd-5d13-4372-9f39-5d61daa2f25f)

@keithmattix @howardjohn Have you ever encountered similarly issue? It seems the trace serialized message data is so large.

**Comment by Patrick0308** [comment]
otel provider config:
```
          provider:
            name: envoy.tracers.opentelemetry
            typedConfig:
              '@type': type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
              grpcService:
                envoyGrpc:
                  authority: otel-collector-grpc.middleware.svc.cluster.local
                  clusterName: outbound|4317||otel-collector-grpc.middleware.svc.cluster.local
                timeout: 3s
          randomSampling:
            value: 100
```
