### ISSUE TITLE
Adding caCertificates to the meshConfig does not work as expected

### ISSUE THREAD

**Issue by penev-ff** [istio/istio#55442]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I am encountering an issue with adding additional trusted CAs to the Istio Mesh configuration.  
What I want to achieve is to configure the envoy proxies to trust client certificates signed by a custom CA.  
Despite following the documented steps, the client certificate is not being accepted.

1. Add the following values to the Istio installation values file (using Helm):

```yaml
pilot:
  env:
    ISTIO_MULTIROOT_MESH: true
meshConfig:
  defaultConfig:
    proxyMetadata:
      PROXY_CONFIG_XDS_AGENT: "true"
  caCertificates:
    - pem: |-
        -----BEGIN CERTIFICATE-----
        %root cert pem%
        -----END CERTIFICATE-----
```

2. After applying the changes, the accepted client certificate CA names (using openssl s_client) are:

```bash
# Before applying changes
Acceptable client certificate CA names
O = cluster.local

# After applying changes
Acceptable client certificate CA names
O = cluster.local
CN = MyRootCA
```

3. However, when I try to connect to the envoy proxy with the client certificate, the certificate is not accepted:

```bash
openssl s_client -connect localhost:9999 -CAfile istio-root-ca.pem -cert client-cert.pem -key client-key.pem

...
SSL handshake has read 2212 bytes and written 1462 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
...
Verify return code: 0 (ok)
---

4057EA1AAB7F0000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1593:SSL alert number 46
```

### Version

```Text
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (30 proxies)
```

### Additional Information

I'm trying to connect an external Envoy proxy client to the Istio Envoy proxy sidecar. 
The connection works successfully when the PeerAuthentication policy is set to PERMISSIVE mode.

Reference: 
- [Istio Mesh Config](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig)
- [Istio Issue - 39935](https://github.com/istio/istio/issues/39935)
