### ISSUE TITLE
Document limitations of wildcard domains in VirtualServices

### ISSUE THREAD

**Issue by czenker** [istio/istio#55475]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

The istio documentation references usage of VirtualServices with wildcard hosts (["Could be a DNS name with wildcard prefix or an IP address"](https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService) or [the example for `TLSRoute`](https://istio.io/latest/docs/reference/config/networking/virtual-service/#TLSRoute)). But it does not mention that Istio does not merge wildcard hosts with non-wildcard hosts.

This might come as a surprise to the unsuspecting user (aka "me" 😄)

# Example

Start with a VirtualService using a wildcard host:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: foo
spec:
  gateways:
  - istio-system/gateway
  hosts:
  - *.example.com
  http:
  - match:
    - uri:
        prefix: /foo/
    route:
    - destination:
        host: foo-service
```
This service is accessible from https://www.example.com/foo/ as well as https://sub.example.com/foo/ So far, so good.

Later add a second service that should only be accessed from www.example.com, but not sub.example.com:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bar
spec:
  gateways:
  - istio-system/gateway
  hosts:
  - www.example.com
  http:
  - match:
    - uri:
        prefix: /bar/
    route:
    - destination:
        host: bar-service
```
This works as expected for the bar service: It is accessible from https://www.example.com/bar/ and not from https://sub.example.com/foo/

**BUT, the foo service can no longer be reached on https://www.example.com/foo/.**

In our project we have hundreds of "foo services" already and migrating them to _not_ use wildcards in their host is quite some work and tricky to do without downtime.

# Conclusion

From an envoy proxy perspective it seems reasonable and efficient thing to only check one host configuration. But from the perspective of a user it is counter intuitive that the creation of an additional `VirtualService` resource makes unrelated VirtualServices inaccessible from a domain. Most CRDs in Kubernetes work additively and don't influence the function of a different resource negatively.

I don't expect that there is an easy fix. Istio probably _might_ inject virtualservices from wildcard hosts into other hosts if they match, before pushing config to envoy, but I am not sure if this is possible or wanted.

Anyways, I think this issue should be documented and warned about. Probably in https://istio.io/latest/docs/ops/best-practices/traffic-management or https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService

Let me know if I can help with that.

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (88 proxies)
$ kubectl version
Client Version: v1.31.6
Kustomize Version: v5.4.2
Server Version: v1.31.6-eks-bc803b4
```
