### ISSUE TITLE
istioctl manifest generate ignoring values.base.enableIstioConfigCRDs

### ISSUE THREAD

**Issue by sfc-gh-vranghabhatla** [istio/istio#55511]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We currently use `istioctl manifest generate -f <istio_operator.yaml>` to generate manifests for multiple meshes destined to a cluster and rely on `values.base.enableIstioConfigCRDs` to generate CRDs in only one of the meshes and skip for the other(s).
This is broken in 1.24.2 and CRDs are generated irrespective.

### Version

```Text
istioctl 1.24.2
```

**Comment by djchie** [comment]
After some digging on a local build, I've found:

- Both `enableCRDTemplates` and `enableIstioConfigCRDs` are correctly consumed by `istioctl` as I can see the values in the logs.
- In this [line in helm.go](https://sourcegraph.com/github.com/istio/istio@1.24.4/-/blob/operator/pkg/helm/helm.go?L100), when `enableIstioConfigCRDs` is set to `false`, `crdFiles` is correctly set to an empty list.
- However, in [this line](https://sourcegraph.com/github.com/istio/istio@1.24.4/-/blob/operator/pkg/helm/helm.go?L120), when the key `base/templates/crds.yaml` is processed, the rendering logic in [crds.yaml](https://sourcegraph.com/github.com/istio/istio@1.24.4/-/blob/manifests/charts/base/templates/crds.yaml?L1-2) is applied.
   - If `enableCRDTemplates` is `true`, we render everything in [crd-all.gen.yaml](https://sourcegraph.com/github.com/istio/istio@1.23.4/-/blob/manifests/charts/base/crds/crd-all.gen.yaml) unless if it's excluded in the `excludedCRDs` field.
   - If `enableCRDTemplates` is `false`, we render everything in [crd-all.gen.yaml](https://sourcegraph.com/github.com/istio/istio@1.23.4/-/blob/manifests/charts/base/crds/crd-all.gen.yaml) regardless.

This effectively means [this whole block in helm.go](https://sourcegraph.com/github.com/istio/istio@1.23.4/-/blob/operator/pkg/helm/helm.go?L135-144) for checking the `enableIstioConfigCRDs` is no longer effective at the moment, since CRDs are rendered from [crds.yaml](https://sourcegraph.com/github.com/istio/istio@1.24.4/-/blob/manifests/charts/base/templates/crds.yaml?L1-2) regardless. So that's why we were still seeing CRDs generated even with `enableIstioConfigCRDs` set to `false`.

As a fix to prevent the CRDs from generating, we'll need to set `enableCRDTemplates` to `true` and explicitly add all the CRDs to exclude to `excludedCRDs` like so:

```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
      ...

    pilot:
      enabled: true
      ...

  values:
    ...
    base:
      enableCRDTemplates: true
      excludedCRDs: 
        - wasmplugins.extensions.istio.io
        - destinationrules.networking.istio.io
        - envoyfilters.networking.istio.io
        - gateways.networking.istio.io
        - proxyconfigs.networking.istio.io
        - serviceentries.networking.istio.io
        - sidecars.networking.istio.io
        - virtualservices.networking.istio.io
        - workloadentries.networking.istio.io
        - workloadgroups.networking.istio.io
        - authorizationpolicies.security.istio.io
        - peerauthentications.security.istio.io
        - requestauthentications.security.istio.io
        - telemetries.telemetry.istio.io

    ...
```
