### ISSUE TITLE
Circuit Breaker with external service (ServiceEntry)

### ISSUE THREAD

**Issue by rtagliabue** [istio/istio#55516]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

 
Hi everyone, we are trying to use Istio to use the circuit breaker features when contacting some external services (service out of the Kubernetes Cluster).
We are using Istio 1.25 in ambient mode in an EKS Cluster 1.31 on AWS.
We have tested the use of the circuit breaker feature using an internal service (Service inside of the Kubernetes cluster) and it worked as expected.
We would like to test this use case with a Fortio Pod as the source of the traffic, and contact the external endpoint example.org as the destination.
 
In a similar way as described in this Istio Documentation:
https://discuss.istio.io/t/circuit-breaker-for-external-service/4253/2
 
These are the steps we have done until now:
We have installed the CRD to support the Gateway resource in Kubernetes.
We have enabled the waypoint in the Kubernetes namespace of the source pods with the following command:
istioctl waypoint apply --enroll-namespace --wait
 
We have deployed our fortio pod in the same namespace of the waypoint and we test from it with the following command:
kubectl exec "$FORTIO_POD" -c fortio -- /usr/bin/fortio load -c 3 -qps 0 -n 30 -loglevel Warning http://example.org/
 
 
We have created the Service Entry of the external service with the following resource:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example-org
spec:
  hosts:
  - example.org
  ports:
  - number: 80
    name: http
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
```
 
We have created the Destination Rule with the circuit beaker config with the following resource:
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: example-org
spec:
  host: example.org
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
```
 
 
We have enabled the logging of the waypoint with the following resource:
```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  accessLogging:
    - providers:
      - name: envoy
```
 
 
However, even if we are testing just in HTTP for the moment, we are getting this output from Fortio.
```
IP addresses distribution:
240.240.0.31:80: 21
Code  -1 : 20 (66.7 %)
Code 200 : 10 (33.3 %)
```
 
From the log of the waypoint we get this kind of error for the request that represent that -1 code:
Successful request (Code 200):
```
[2025-03-13T15:58:26.103Z] "- - -" 0 UO - - "-" 0 0 0 - "-" "-" "-" "-" "-" inbound-vip|80|tcp|example.org - 240.240.0.31:80 10.255.90.129:54358 - -
```
Blocked request by circuit breaker (Code -1):
```
[2025-03-13T15:58:26.103Z] "CONNECT - HTTP/2" 503 UF upstream_reset_before_response_started{remote_connection_failure|immediate_connect_error:_Invalid_argument|remote_address:envoy://main_internal/} - "immediate_connect_error:_Invalid_argument|remote_address:envoy://main_internal/" 0 205 0 - "-" "-" "00ed7e07-c2fe-4809-aa17-b515e3d3bd7c" "240.240.0.31:80" "envoy://main_internal/" main_internal - 10.255.77.225:15008 10.255.90.129:54358 - -
```

We have tried even to switch the protocol field of the Service Entry resource from TCP to HTTP.
When we changed this protocol the output of Fortio changed in the following way:
```
IP addresses distribution:
240.240.0.39:80: 30
Code  -1 : 10 (33.3 %)
Code 503 : 20 (66.7 %)
```
 
And from the waypoint log we get this other error for the request:
Successful request? (Code -1):
```
[2025-03-13T16:11:34.263Z] "GET / HTTP/1.1" 0 DC downstream_remote_disconnect - "-" 0 0 3000 - "-" "fortio.org/fortio-1.66.5" "06b9f951-daac-4007-a3e4-aec6a3cf6a27" "example.org" "23.215.0.132:80" inbound-vip|80|http|example.org 10.255.77.225:54794 240.240.0.39:80 10.255.90.129:35698 - default
```
Blocked request by circuit breaker (Code 503):
```
[2025-03-13T16:11:10.266Z] "GET / HTTP/1.1" 503 UO upstream_reset_before_response_started{overflow} - "-" 0 81 0 - "-" "fortio.org/fortio-1.66.5" "e12e7ad6-1380-4c6d-8e8c-5c22ffb69efa" "example.org" "-" inbound-vip|80|http|example.org - 240.240.0.39:80 10.255.90.129:35698 - default
```

Can you confirm that this is a bug or are we missing something?

Thank you

### Version

```Text
$ istioctl version
client version: 1.24.3
control plane version: 1.25.0
data plane version: 1.25.0 (5 proxies)

$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.6-eks-bc803b4
```

**Comment by howardjohn** [comment]
By setting maxConnections=1 aren't you basically saying "reject any connections if I have more than 1 open already"? And then having fortio open multiple connections, so some will be rejected?

**Comment by rtagliabue** [comment]
Yes, that is the expected behaviour. But we expect that the client (fortio) get 503 status code for rejected/dropped connections. We actually observe this expected behaviour if we try the same setup but with a Service instead of a ServiceEntry:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/mccutchen/go-httpbin:v2.15.0
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100

```

with this configuration we get
```
$ kubectl exec "$FORTIO_POD" -c fortio -- /usr/bin/fortio load -c 3 -qps 0 -n 30 -loglevel Warning http://httpbin:8000/get

IP addresses distribution:
172.20.146.191:8000: 12
Code 200 : 20 (66.7 %)
Code 503 : 10 (33.3 %)
Response Header Sizes : count 30 avg 220 +/- 155.6 min 0 max 330 sum 6600
Response Body/Total Sizes : count 30 avg 560.66667 +/- 165.9 min 326 max 678 sum 16820
All done 30 calls (plus 0 warmup) 1.873 ms avg, 1533.1 qps
```

**Comment by howardjohn** [comment]
```

  - number: 80
    name: http
    protocol: TCP # THIS
```

means envoy is treatinbg it as opaque TCP. So it cannot send a 503, it can only close the connection.

**Comment by rtagliabue** [comment]
Hi @howardjohn, as mentioned we tried also to set HTTP protocol in the port definition of the ServiceEntry. With that, fortio output is:

```
IP addresses distribution:
240.240.0.39:80: 30
Code  -1 : 10 (33.3 %)
Code 503 : 20 (66.7 %)
```

Fortio does not get any 200 response. In the waypoint's logs we see
```
[2025-03-13T16:11:34.263Z] "GET / HTTP/1.1" 0 DC downstream_remote_disconnect - "-" 0 0 3000 - "-" "fortio.org/fortio-1.66.5" "06b9f951-daac-4007-a3e4-aec6a3cf6a27" "example.org" "23.215.0.132:80" inbound-vip|80|http|example.org 10.255.77.225:54794 240.240.0.39:80 10.255.90.129:35698 - default
```

**Comment by howardjohn** [comment]
Hmm with the same setup, I see

```
[2025-03-17T15:41:02.097Z] "GET /get HTTP/1.1" 503 UO upstream_reset_before_response_started{overflow} - "-" 0 81 0 - "-" "fortio.org/fortio-1.68.0" "0bf6d02b-27df-46fd-becf-3a077b0f5d45" "httpbingo.org" "-" inbound-vip|80|http|httpbingo.org - 240.240.0.1:80 192.168.0.23:57674 - default
[2025-03-17T15:41:02.089Z] "GET /get HTTP/1.1" 200 - via_upstream - "-" 0 611 73 73 "-" "fortio.org/fortio-1.68.0" "ec5ab6a0-6840-4e48-a9cb-e6f5f493aa16" "httpbingo.org" "66.241.125.232:80" inbound-vip|80|http|httpbingo.org 192.168.0.25:37848 240.240.0.1:80 192.168.0.23:57674 - default
```

Are you sure you don't have any other config? Or maybe its the specific external website you are using? I used httpbingo.org and example.org, both worked (though example.org gave 404 instead of 200)

**Comment by rtagliabue** [comment]
Hi @howardjohn, we tried the exact same test in a new cluster with Istio 1.25.1 and now it seems to work as expected.
Not sure if our previous setup had something different (maybe related to AWS network firewall in the way) or if upgrading from 1.25.0 to 1.25.1 fixed the problem. Output:

```
$ kubectl exec -n circuit-breaker-external "$FORTIO_POD" -c fortio -- /usr/bin/fortio load -c 3 -qps 0 -n 30 -loglevel Warning http://httpbingo.org/get
```

```
IP addresses distribution:
240.240.0.8:80: 21
Code 200 : 10 (33.3 %)
Code 503 : 20 (66.7 %)
```

waypoint logs:
```
[2025-04-08T10:06:29.214Z] "GET /get HTTP/1.1" 503 UO upstream_reset_before_response_started{overflow} - "-" 0 81 0 - "-" "fortio.org/fortio-1.66.5" "7d498747-d9c2-4400-86f8-bd20084a3a82" "httpbingo.org" "-" inbound-vip|80|http|httpbingo.org - 240.240.0.8:80 100.64.120.251:59230 - default
[2025-04-08T10:06:29.111Z] "GET /get HTTP/1.1" 200 - via_upstream - "-" 0 613 208 208 "-" "fortio.org/fortio-1.66.5" "8e6fd5b4-3db5-4ced-a44b-89193cb1f49b" "httpbingo.org" "66.241.125.232:80" inbound-vip|80|http|httpbingo.org 100.64.98.229:50948 240.240.0.8:80 100.64.120.251:59230 - default
```


We also tried the same test in HTTPS, but unfortunately we get other errors:

```
$ kubectl exec -n circuit-breaker-external "$FORTIO_POD" -c fortio -- /usr/bin/fortio load -c 3 -qps 0 -n 30 -loglevel Warning https://httpbingo.org/get

E0408 10:45:13.131727   35027 websocket.go:296] Unknown stream id 1, discarding message
{"ts":1744101913.362222,"level":"info","r":1,"file":"logger.go","line":290,"msg":"Log level is now 3 Warning (was 2 Info)"}
Fortio 1.66.5 running at 0 queries per second, 2->2 procs, for 30 calls: https://httpbingo.org/get
Starting at max qps with 3 thread(s) [gomax 2] for exactly 30 calls (10 per thread + 0)
{"ts":1744101913.368337,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.368942,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.370942,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.372499,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.376071,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.385729,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.388476,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.389288,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.391395,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.392026,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.395587,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.396000,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.399755,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.400202,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.402899,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.403425,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.405439,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
{"ts":1744101913.406053,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.408692,"level":"err","r":13,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":0,"run":0}
{"ts":1744101913.409475,"level":"err","r":15,"file":"http_client.go","line":946,"msg":"Unable to TLS connect","dest":{"IP":"240.240.0.8","Port":443,"Zone":""},"err":"EOF","thread":2,"run":0}
Ended after 1.042577102s : 30 calls. qps=28.775
Aggregated Function Time : count 30 avg 0.037671382 +/- 0.04735 min 0.00200013 max 0.127077121 sum 1.13014147
# range, mid point, percentile, count
>= 0.00200013 <= 0.003 , 0.00250007 , 16.67, 5
> 0.003 <= 0.004 , 0.0035 , 46.67, 9
> 0.004 <= 0.005 , 0.0045 , 60.00, 4
> 0.012 <= 0.014 , 0.013 , 63.33, 1
> 0.014 <= 0.016 , 0.015 , 66.67, 1
> 0.1 <= 0.12 , 0.11 , 96.67, 9
> 0.12 <= 0.127077 , 0.123539 , 100.00, 1
# target 50% 0.00425
# target 75% 0.105556
# target 90% 0.115556
# target 99% 0.124954
# target 99.9% 0.126865
Error cases : count 20 avg 0.0043883872 +/- 0.003179 min 0.00200013 max 0.014791695 sum 0.087767744
# range, mid point, percentile, count
>= 0.00200013 <= 0.003 , 0.00250007 , 25.00, 5
> 0.003 <= 0.004 , 0.0035 , 70.00, 9
> 0.004 <= 0.005 , 0.0045 , 90.00, 4
> 0.012 <= 0.014 , 0.013 , 95.00, 1
> 0.014 <= 0.0147917 , 0.0143958 , 100.00, 1
# target 50% 0.00355556
# target 75% 0.00425
# target 90% 0.005
# target 99% 0.0146334
# target 99.9% 0.0147759
# Socket and IP used for each connection:
[0]  10 socket used, resolved to 240.240.0.8:443, connection timing : count 10 avg 0.0033008137 +/- 0.003015 min 0.001370583 max 0.011999576 sum 0.033008137
[1]   1 socket used, resolved to 240.240.0.8:443, connection timing : count 1 avg 0.020325554 +/- 0 min 0.020325554 max 0.020325554 sum 0.020325554
[2]  10 socket used, resolved to 240.240.0.8:443, connection timing : count 10 avg 0.0034611603 +/- 0.002753 min 0.001415286 max 0.011483808 sum 0.034611603
Connection time (s) : count 21 avg 0.0041878711 +/- 0.004579 min 0.001370583 max 0.020325554 sum 0.087945294
Sockets used: 21 (for perfect keepalive, would be 3)
Uniform: false, Jitter: false, Catchup allowed: true
IP addresses distribution:
240.240.0.8:443: 21
Code  -1 : 20 (66.7 %)
Code 200 : 10 (33.3 %)
Response Header Sizes : count 30 avg 103 +/- 145.7 min 0 max 309 sum 3090
Response Body/Total Sizes : count 30 avg 283.33333 +/- 400.7 min 0 max 850 sum 8500
All done 30 calls (plus 0 warmup) 37.671 ms avg, 28.8 qps
```

and we see this type of logs in the waypoint
```
[2025-04-08T10:17:01.745Z] "- - -" 0 UO - - "-" 0 0 2 - "-" "-" "-" "-" "-" inbound-vip|443|tcp|httpbingo.org - 240.240.0.8:443 100.64.120.251:37886 httpbingo.org -
[2025-04-08T10:17:01.745Z] "- - -" 0 UO - - "-" 0 0 2 - "-" "-" "-" "-" "-" inbound-vip|443|tcp|httpbingo.org - 240.240.0.8:443 100.64.120.251:37886 httpbingo.org -
[2025-04-08T10:17:01.751Z] "- - -" 0 UO - - "-" 0 0 0 - "-" "-" "-" "-" "-" inbound-vip|443|tcp|httpbingo.org - 
[2025-04-08T10:17:01.745Z] "- - -" 0 - - - "-" 1373 11098 1323 - "-" "-" "-" "-" "66.241.125.232:443" inbound-vip|443|tcp|httpbingo.org 100.64.98.229:46584 240.240.0.8:443 100.64.120.251:37886 httpbingo.org -
```

This is the ServiceEntry we configured with HTTPS port:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbingo
spec:
  hosts:
  - httpbingo.org
  ports:
  - number: 443
    name: https
    protocol: HTTPS
    targetPort: 443
  resolution: DNS
  location: MESH_EXTERNAL
```

Do you know if this is supposed to work also with HTTPS protocol or are we missing some configuration?

Thank you
