### ISSUE TITLE
Connection Closed Due to Policy Rejection in Ambient Mesh

### ISSUE THREAD

**Issue by ghost** [istio/istio#55533]
I am experiencing an issue in Ambient Mesh where connections to a backend service are being rejected due to a policy restriction. Below is the relevant log output from Istio:

`
2025-03-14T08:38:10.194689Z     error   access  connection complete     src.addr=10.1.26.201:41616 src.workload="istio-ingressgateway-955654497-rv74f" src.namespace="istio-system" src.identity="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account" dst.addr=10.1.27.83:15008 dst.hbone_addr=10.1.27.83:80 dst.service="backend-translation.staging.svc.cluster.local" dst.workload="backend-translation-78f6c4d95-g4zkp" dst.namespace="staging" dst.identity="spiffe://cluster.local/ns/staging/sa/default" direction="inbound" bytes_sent=0 bytes_recv=0 duration="0ms" error="connection closed due to policy rejection"
`

AuthorizationPolicy:
```
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks:
        - 216.128.25.120/32
        remoteIpBlocks:
        - 216.128.25.120/32
  selector:
    matchLabels:
      app: backend-translation
```

client version: 1.23.3
control plane version: 1.23.3
data plane version: 1.23.3 (46 proxies)
