### ISSUE TITLE
istioctl manifest -f ... -f... merging multiple files behavior has changed since 1.24.0

### ISSUE THREAD

**Issue by bricelalu** [istio/istio#55615]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Since 1.24.0, I noticed a different behavior when merging multiple files for installation, for example, when I want to customize the installation of the ingress gateway components, I have those 2 files:
* A base template: ingress-base.yaml
* A custom one: ingress-custom.yaml

In the "ingress-base.yaml" file I have:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingressgateway
spec:
  profile: empty
  hub: docker.io/istio
  tag: 1.24.3
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-ingress
      enabled: true
      label:
        istio: istio-ingressgateway
        app: istio-ingressgateway
      k8s:
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        priorityClassName: "system-node"
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: spec.template.spec.topologySpreadConstraints
                value:
                  - maxSkew: 1
                    topologyKey: topology.kubernetes.io/zone
                    whenUnsatisfiable: DoNotSchedule
                    labelSelector:
                      matchLabels:
                        istio: istio-ingressgateway
                        app: istio-ingressgateway
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
                    labelSelector:
                      matchLabels:
                        istio: istio-ingressgateway
                        app: istio-ingressgateway
``` 

In the ingress-custom.yaml file I have
```
#
#
# Override (merge) ingress-base.yaml values for custom Environment
#
#
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingressgateway
spec:
  profile: empty
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 2000m
            memory: 2048Mi
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: spec.template.spec.topologySpreadConstraints
                value:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
                    labelSelector:
                      matchLabels:
                        istio: istio-ingressgateway
                        app: istio-ingressgateway
``` 

Until release 1.23.5, the manifest generated by this command:
`istioctl manifest generate --set profile=empty -f ingress-base.yaml -f ingress-custom.yaml  > ingress-merged.yaml` contained values from ingress-base.yaml, that were not overriden by ingress-custom.yaml:
* "istio" label: `istio-ingressgateway`
* Namespace: `istio-ingress`
* PriorityClassName: `system-node`

Since 1.24.0, those values are lost (for example `PriorityClassName`)  or revert to default values, like:
* namespace becomes: istio-system
* istio label becomes: istio

Which causes issues during deployment of those components.

### Version

```Text
istioctl version
client version: 1.24.3
control plane version: 1.24.3
data plane version: 1.24.3 (763 proxies)

kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.9-eks-8cce635
```
