### ISSUE TITLE
Cannot upgrade from 1.24.2 to 1.25.0

### ISSUE THREAD

**Issue by josemrs** [istio/istio#55614]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi,

We are having some troubles upgrading our 1.24.2 Istios to 1.25.0. We updated the CRDs, helm chart and images to 1.25.0 to crash against the following error in the istiod pod:

```
Error: failed to create discovery service: error initializing sidecar injector: failed to create injection webhook: failed to process webhook config: failed to create new values config: could not parse configuration values: json: cannot unmarshal string into Go value of type bool
2025-03-21T06:36:46.692039Z	error	failed to create discovery service: error initializing sidecar injector: failed to create injection webhook: failed to process webhook config: failed to create new values config: could not parse configuration values: json: cannot unmarshal string into Go value of type bool
```

We don't use istioctl at all, we deploy istio using a wrapper helm chart with istio chart as dependency. Furthermore, we also use Tetrate images from ironbank/tetrate/istio/proxyv2:1.25.0, however, everything was working just fine in version 1.24.2, it's as soon as we bump the versions the error appears.

It may be something silly, but I cannot help myself to figure out. Sorry, but I'm not sure what config or values you may need to be able to help me, please ask anything that may help you.

We pass these values to the istiod chart (undefined gets defined at deployment time in ArgoCD):

```
istiod:
  global:
    logging:
      level: "default:info"

    meshID: undefined

    multiCluster:
      enabled: true
      clusterName: undefined

    network: undefined

    proxy_init:
      image: nexus.aveng.me:5000/ironbank/tetrate/istio/proxyv2:1.25.0

    proxy:
      image: nexus.aveng.me:5000/ironbank/tetrate/istio/proxyv2:1.25.0
      logLevel: info
      holdApplicationUntilProxyStarts: "true"

  meshConfig:
    serviceSettings:
      # Disable default multi-cluster load-balance
      # https://istio.io/latest/docs/ops/configuration/traffic-management/multicluster/#keeping-traffic-in-cluster
      - settings:
          clusterLocal: true
        hosts:
          - "*"
    proxyMetadata:
      # Enable Istio agent to handle DNS requests for known hosts
      # Unknown hosts will automatically be resolved using upstream dns servers in resolv.conf
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"

  pilot:
    autoscaleEnabled: false

    deploymentLabels:
      contact/owner: EngOps
      contact/jira: ENGOPS

    image: nexus.aveng.me:5000/ironbank/tetrate/istio/pilot:1.25.0

    env:
      COMPLIANCE_POLICY: fips-140-2

    podLabels:
      contact/owner: EngOps
      contact/jira: ENGOPS
```

Thanks a lot for any help,
Jose

### Version

```Text
$ istioctl version
client version: 1.24.2
control plane version: 1.24.2-tetratefips0
data plane version: 1.24.2 (8 proxies)

$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.31.6-eks-bc803b4

$ helm version --short
v3.16.4+g7877b45
```
