### ISSUE TITLE
Istio-injection enabled but failing to allocate sidecar container

### ISSUE THREAD

**Issue by DMSwimTech** [istio/istio#55635]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hey, we are migrating from istioctl command to istio helm charts. After the migration istio fails to allocate sidecar containers to pods

When running `experimental` command I'm getting the following output
```
~ ❯ istioctl experimental check-inject -n default deploy/external-secrets                                                                                                                                                                                          
WEBHOOK                 REVISION  INJECTED      REASON
istio-sidecar-injector  default   ✘             No matching namespace labels (istio.io/rev=default, istio-injection=enabled) or pod labels (istio.io/rev=default, sidecar.istio.io/inject=true)
```

But, when verifying the namespace is labelled as needed:
```
~ ❯ kubectl get ns --show-labels                                                                                                                                                                                                                                                   
NAME                STATUS   AGE     LABELS
default                Active   4d23h   istio-injection=enabled,kubernetes.io/metadata.name=default
```

When running analyze istio does see that the pod is missing sidecar container but rollout restart doesn't help 
```
~ ❯ istioctl analyze  --all-namespaces                                                                                                                                                                                                                                             
Warning [IST0103] (Pod default/external-secrets-68dbbc458d-cpgbx) The pod default/external-secrets-68dbbc458d-cpgbx is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
```

Debugging the MutatingWebhook also looks fine for me
```
~ ❯ kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml | grep "namespaceSelector:" -A5                                                                                                                                                                        
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - default
--
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
--
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: In
      values:
      - enabled
--
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
```

Any idea what I'm missing?

### Version

```Text
~ ❯ istioctl version                                                                                                                                                                                                                                                               
client version: 1.23.1
control plane version: 1.23.1
data plane version: 1.23.1 (10 proxies)

~ ❯ kubectl version                                                                                                                                                                                                                                                            
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.10-eks-bc803b4
```

### Additional Information

Istio values file:
```
global:
    enabled: true
    namespace: istio-system
meshConfig:
    rootNamespace: ingress
pilot:
    autoscaleMax: 5
    autoscaleMin: 4
    cni:
        enabled: true
    env:
        VERIFY_CERTIFICATE_AT_CLIENT: "false"
    replicaCount: 4
```
