### ISSUE TITLE
tracing: no span of `kind=server` reported for ingress-gateway

### ISSUE THREAD

**Issue by joaopgrassi** [istio/istio#55637]
**Describe the feature request**

When using Envoy as gateway, only a span of `kind=client` is reported when sending requests to the ingress-gateway for the outbound request. There is no span of `kind=server` for the inbound request to the gateway.

This is problematic because most observability solutions expect and operate on server spans to detect/monitor/analyze endpoints.

The expected trace when using a ingress-gateway, together with envoy also as sidecars would be something like:

```
-> [SERVER -> CLIENT] -> [SERVER -> CLIENT] -> [SERVER -> CLIENT] -> [SERVER -> CLIENT] -> ...
        Gateway           Inbound Sidecar            App             Outbound Sidecar
```

This is what the [Envoy docs recommend](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#different-types-of-span) for when a gateway is present, which is to be treated as an "separated hop" in the trace chain. 

Envoy exposes a flag which makes such trace possible, and it is recommended to be set for Gateways: [spawn_upstream_span](https://github.com/envoyproxy/envoy/blob/58842b291230613c89620195086160a6e201a33d/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L203).

Right now, this flag is hardcoded for all tracers, being [false](https://github.com/istio/istio/blob/0f67335414a5c13a6adb764708a8311363764e9a/pilot/pkg/networking/core/tracing.go#L153) for all, and [true](https://github.com/istio/istio/blob/0f67335414a5c13a6adb764708a8311363764e9a/pilot/pkg/networking/core/tracing.go#L210) only for Skywalking.

And it also seems this flag is going to be deprecated in Envoy, in favor of the one linked above `spawn_upstream_span`.

**Describe alternatives you've considered**

Not really any, but for now, an Envoy filter can be used as a workaround to set the `spawn_upstream_span` for Gateways, like:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-tweaks
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          tracing:
            spawn_upstream_span: true
```

I believe this is essential for a well-structure trace, thus I think we should allow this to be configured somehow in Istio.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
There was this old issue stating the problem, which is closed with no resolution: https://github.com/istio/istio/issues/23815
