### ISSUE TITLE
AuthorizationPolicy unable to cover all groups from X-Auth-Request-Groups http header

### ISSUE THREAD

**Issue by rmaihge** [istio/istio#55660]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hello community,

I have discovered an issue with the below setup for which I receive a "RBAC access denied" in case the Istio AuthorizationPolicy based on "X-Auth-Request-Groups" header is not configured in a specific way. It does not cover all the needed cases in case an user is part of more than one group.
The workaround was to configure all the combinations of the available groups as you will see below.
 
I have installed Istio with an external authentication provider - oauth2-proxy:

Istio custom values:
```
meshConfig:
  extensionProviders:
  - name: "oauth2-proxy"
    envoyExtAuthzHttp:
      service: "oauth2-proxy.istio-system.svc.cluster.local"
      port: "80"
      headersToDownstreamOnDeny:
        - content-type
        - set-cookie
      headersToUpstreamOnAllow:
        - cookie
        - path
        - x-auth-request-email           
        - x-auth-request-user           
        - x-auth-request-groups               
      includeRequestHeadersInCheck:
        - cookie                              
      includeAdditionalHeadersInCheck:                                            
        X-Auth-Request-Redirect: 'https://%REQ(:authority)%%REQ(:path)%'

profile: ambient

```

Oauth2-proxy custom values:

```
config:
  clientID: "my-client-id"
  clientSecret: "xxxxxxxxx"
  cookieSecret: "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
  cookieName: "_oauth2_proxy_di_istio_ingressgateway"
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "static://200" ]
    provider = "oidc"
    cookie_refresh = "5m"
    cookie_expire = "4h"
    cookie_domains = [ ".test.example.com" ]
    cookie_samesite = "lax"
    set_xauthrequest = true
    set_authorization_header = true
    pass_authorization_header = true 
    pass_host_header = true
    pass_access_token = true
    skip_jwt_bearer_tokens = true
    reverse_proxy = true
    skip_provider_button = true
    http_address = "0.0.0.0:4180"
    silence_ping_logging = true
    oidc_issuer_url = "https://auth.example.com"
    real_client_ip_header = "X-Forwarded-For"
    code_challenge_method = "S256"
    redirect_url= "https://oauth2-proxy.test.example.com/oauth2/callback"
    scope = "openid groups email profile state"
    whitelist_domains = ".test.example.com"
    oidc_groups_claim = "groups"
    oidc_email_claim = "email"

```

Istio policies:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authz-custom-yunikorn
  namespace: yunikorn
spec:
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint-yunikorn           
  action: CUSTOM 
  provider:
    name: "oauth2-proxy"
  rules:
  - to:
    - operation:
        hosts:
        - "yunikorn.test.example.com"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authz-yunikorn
  namespace: yunikorn
spec:
  action: ALLOW
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint-yunikorn  
  - when:
    - key: request.headers[X-Auth-Request-Groups]
      values:
        - group-1
        - group-2

```

Oauth2-proxy logs:

```
[2025/03/25 12:54:43] [oauthproxy.go:1026] No valid authentication in request. Initiating login.
172.16.0.55 - e863fef0-b5ad-475f-afb9-e7922d63eb8d - - [2025/03/25 12:54:43] yunikorn.test.example.com GET - "/" HTTP/1.1 "" 302 505 0.000
172.16.0.65 - b106c345-0778-433f-96db-0d6efe432c20 - my-email@example.com [2025/03/25 12:54:49] [AuthSuccess] Authenticated via OAuth2:
 Session{
 email:my-email@example.com
 user:my-user 
 PreferredUsername: 
 token:true 
 id_token:true created:2025-03-25 12:54:49.867725511 +0000 UTC m=+13013.543863850 expires:2025-03-25 13:54:49.734072263 +0000 UTC m=+16613.410210599
 groups:[group-2 group-1]}
172.16.0.65 - b106c345-0778-433f-96db-0d6efe432c20 - - [2025/03/25 12:54:49] oauth2-proxy.test.example.com GET - "/oauth2/callback?session_state=2OnLN55eIka7AZ4qalU26tMgd8HLYcDrwxp4RJW2XEY%3D.ZUV
aUElQaUpSRGFnRnIrNUw5UUYwbHJZaTdHSlBieFJ6V2RGUm5vbDZLODY0MlpqdUl4eDFobUNQYnhABC5ZzFXMVBLYnF5bnhydkFSQ1dkVXJXdGgzVElScVRscXlFbU1GSS9COXNSR009&state=Sb3L9OTZ2RuUVGwDaj94ejPOarG-5YJIDX-Pm-8DRR8%3Ahttps%3A%2F%2Fyunik
orn.test.example.com%2F&code=382fb4d79b31f51bfc47f66849351db2" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" 302 75 0.
475
```

Working only after updating the authorization policy with all the combinations of the groups the user is part of:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authz-yunikorn
  namespace: yunikorn
spec:
  action: ALLOW
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint-yunikorn  
  - when:
    - key: request.headers[X-Auth-Request-Groups]
      values:
        - "group-1,group-2"
        - "group-2,group-1"

```

Can you please check?

Best regards,
Marian Ghita

### Version

```Text
HELM VERSION
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
istio-base      istio-system    1               2025-03-06 15:58:59.295284783 +0000 UTC deployed        base-1.24.3             1.24.3     
istio-cni       istio-system    3               2025-03-13 08:51:46.901021097 +0000 UTC deployed        cni-1.24.3              1.24.3     
istiod          istio-system    72              2025-03-25 12:54:22.219827013 +0000 UTC deployed        istiod-1.25.0           1.25.0   

KUBECTL VERSION
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.2-r0-27.0.8.3
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
```
