### ISSUE TITLE
Sidecar regex for namespace name

### ISSUE THREAD

**Issue by ro-distefano** [istio/istio#55678]
Hello Istio community,

**Features**

I am writing this issue because I find myself needing to enable outbound communication from a pod to all pods belonging to namespaces that match a certain regex. For example, I wanted to define a sidecar similar to the following:

```
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
    - hosts:
        - *dev*/*
```

In other words, enable communication with all namespaces that have the word "dev" in their name.

**Describe alternatives you've considered**

I tried searching on the internet but it seems that there is no way to implement something like this. It would be simple to create a CronJob that populates the sidecar based on this rule, but I can't find a built-in solution to resolve this circumstance.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X ] Docs
[ ] Dual Stack
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Thank you, goodbye

Roberto Di Stefano
