### ISSUE TITLE
Retry policy for inbound requests causes sidecar memory to constantly increase

### ISSUE THREAD

**Issue by dbason** [istio/istio#55674]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

The majority of our traffic is long lived bidirectional gRPC streams.  When switching to a version that has the retry policy for inbound requests enabled this causes the sidecar memory utilization to continue to grow.

This memory graph illustrates the issue we encoutered
![Image](https://github.com/user-attachments/assets/bfeca313-2b33-4e91-a9a6-dc6e9a9a9315)

This shows the memory usage of the istio-proxy sidecar for one of our gRPC streaming services.  The traffic flow is gRPC client -> istio-gateway -> service.

The memory grew eventually to be over 1GB until we set `ENABLE_INBOUND_RETRY_POLICY` to `"false"` on istiod.  You can see the sharp drop in memory back down to ~180MB when this happened (this behaviour was mirrored across all our gRPC streaming pods).

### Version

```Text
istioctl isn't used (we use helm charts deployed with argocd and are deploying istio v1.24.2)

$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.6-gke.1020000
```

### Additional Information

This is a private production cluster so not comfortable sharing bug-report publicly.  I'm happy to grab any specific information that may help and redact where required though.

We are using side-car injections on specific services and are not using ambient mode.

**Comment by dbason** [comment]
The virtual service spec is as follows;
```yaml
spec:
  gateways:
  - gateway-a
  hosts:
  - api1.example.com
  - api2.example.com
  http:
  - corsPolicy:
      allowHeaders:
      - authorization
      - content-type
      - r-p
      - r-cs
      - x-user-agent
      - x-grpc-web
      allowOrigin:
      - '*'
      exposeHeaders:
      - grpc-message
      - grpc-status
    match:
    - headers:
        r-p:
          exact: match-a
      uri:
        prefix: /server.v1.grpc/ServiceA
    - headers:
        r-p:
          exact: match-a
      uri:
        prefix: /server.v1.grpc/ServiceB
    retries:
      attempts: 0
    route:
    - destination:
        host: service-a.ns.svc.cluster.local
        port:
          number: 8080
  - corsPolicy:
      allowHeaders:
      - authorization
      - content-type
      - r-p
      - r-cs
      - x-user-agent
      - x-grpc-web
      allowOrigin:
      - '*'
      exposeHeaders:
      - grpc-message
      - grpc-status
    match:
    - headers:
        r-p:
          exact: match-a
      uri:
        prefix: /server.v1.grpc/ServiceC
    retries:
      attempts: 0
    route:
    - destination:
        host: service-a.ns.svc.cluster.local
        port:
          number: 8081
  - corsPolicy:
      allowHeaders:
      - authorization
      - content-type
      - r-p
      - r-cs
      - x-user-agent
      - x-grpc-web
      allowOrigin:
      - '*'
      exposeHeaders:
      - grpc-message
      - grpc-status
    match:
    - uri:
        prefix: /server.v1.grpc/ServiceA
    - uri:
        prefix: /server.v1.grpc/ServiceB
    retries:
      attempts: 0
    route:
    - destination:
        host: service-default.ns.svc.cluster.local
        port:
          number: 8080
  - corsPolicy:
      allowHeaders:
      - authorization
      - content-type
      - r-p
      - r-cs
      - x-user-agent
      - x-grpc-web
      allowOrigin:
      - '*'
      exposeHeaders:
      - grpc-message
      - grpc-status
    match:
    - uri:
        prefix:/server.v1.grpc/ServiceC
    retries:
      attempts: 0
    route:
    - destination:
        host: service-default.ns.svc.cluster.local
        port:
          number: 8081

```

The service entry this points to is
```yaml
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: grpc
    name: grpc-a
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc-web-a
    port: 8081
    protocol: TCP
    targetPort: 8079
  selector:
    app: example
  sessionAffinity: None
  type: ClusterIP

```

the istio gateway spec is as follows:
```yaml
spec:
  selector:
    app: istio-gw-prod-public-pig-us
    istio: gw-prod-public-pig-us
  servers:
  - hosts:
     - api1.example.com
     - api2.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingressgateway-cert
      mode: SIMPLE

```
