### ISSUE TITLE
No way to overlay revision based MutatingWebhook

### ISSUE THREAD

**Issue by cathal-c** [istio/istio#55708]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi all, in an effort to update Istio's mutating webhooks from `Never`  to `IfNeeded`, I explored the use of IstioOperator overlays.

We can overlay `istio-sidecar-injector` without issue;
```yaml
        - apiVersion: admissionregistration.k8s.io/v1
          kind: MutatingWebhookConfiguration
          name: istio-sidecar-injector
          patches:
          - path: webhooks.[name:rev\.namespace\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:rev\.object\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:namespace\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:object\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:auto\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
```

But we cannot overlay the versioned webhooks (such as the default `istio-revision-tag-default`);
```yaml
        - apiVersion: admissionregistration.k8s.io/v1
          kind: MutatingWebhookConfiguration
          name: istio-revision-tag-default
          patches:
          - path: webhooks.[name:rev\.namespace\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:rev\.object\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:namespace\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:object\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
          - path: webhooks.[name:auto\.sidecar-injector\.istio\.io].reinvocationPolicy
            value: IfNeeded
```

Open to any alternative suggestions!

This might be a case of [XY Problem](https://en.wikipedia.org/wiki/XY_problem) - perhaps I should just be requesting a feature change to change the ReinvocationPolicy in Istio itself, given its injectors are tested to be idempotent?

Not really sure what the most affected product area is here.

### Version

```Text
N/A
```
