### ISSUE TITLE
ServiceEntry Endpoints Shared Across Different exportTo Namespaces

### ISSUE THREAD

**Issue by minuyim** [istio/istio#55714]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

**Issue Summary:**
When two ServiceEntries with the same host but different resolution types (DNS vs. STATIC with workloadSelector) and distinct exportTo settings are deployed concurrently, they end up registering endpoints in the same cluster. As a result, the istio-proxy in the exportTo namespaces receives all endpoints, contrary to the expected behavior where endpoints should be isolated based on the exportTo configuration.

**Expected Behavior:**
ServiceEntries configured with different exportTo values should have their endpoints separated into distinct clusters or endpoint sets. This isolation ensures that only the intended endpoints are visible to proxies in the specified exportTo namespaces.

**Observed Behavior:**
Both the DNS-based ServiceEntry and the workloadSelector-based ServiceEntry (with STATIC resolution) register endpoints in the same cluster. Despite having different exportTo configurations, the istio-proxy in each namespace ends up sharing all endpoints.

**Steps to Reproduce:**

Deploy the following DNS-based ServiceEntry in one namespace:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-service
spec:
  hosts:
    - example.com
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
    - number: 80
      name: http
      protocol: HTTP
  exportTo:
    - "."  # Only available in the current namespace
Deploy the following workloadSelector-based ServiceEntry (with STATIC resolution) in the same cluster, but intended for a different exportTo namespace:
```
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-service-workload
spec:
  hosts:
    - example.com
  location: MESH_INTERNAL
  resolution: STATIC
  ports:
    - number: 80
      name: http
      protocol: HTTP
  workloadSelector:
    labels:
      app: my-app
  exportTo:
    - "some-other-namespace"  # Should be isolated to this namespace
```
Observe that endpoints from both ServiceEntries are registered in the same cluster and shared across exportTo namespaces.

**Additional Context:**
It appears that the Envoy endpoints for both the DNS and workloadSelector (STATIC) configurations are not being segregated according to their exportTo settings. This might be a bug in how Istio processes or isolates endpoints for ServiceEntries with mixed resolution types. If additional context is needed, please let me know.

### Version

```Text
istio v1.23.5
k8s v1.31.0
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by tjons** [comment]
Hi @minuyim, I tried to replicate this today with both istio 1.23.5 and istio 1.25.1 on `kind` with k8s 1.32.2, installing both via `istioctl install` with the default profile. 

I set up three namespaces:
```
- test-ns-1
- test-ns-2
- config
```
and placed two apps in each, `httpbin` and a curl client.

I then applied the following `ServiceEntry` to the `config` namespace:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-service-workload
spec:
  hosts:
    - example.com
  location: MESH_INTERNAL
  resolution: STATIC
  ports:
    - number: 80
      name: http
      protocol: HTTP
  workloadSelector:
    labels:
      app: httpbin
  exportTo:
    - "test-ns-2"  # Should be isolated to this namespace
```

and the following `ServiceEntry` to the `test-ns-1` namespace:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example-service
spec:
  hosts:
    - example.com
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
    - number: 80
      name: http
      protocol: HTTP
  exportTo:
    - "."  # Only available in the current namespace
```

I then ran a number of requests from the `curl` pod in `test-ns-1`, and observed that all resolved to the external `example.org` domain, as expected. I ran a number of requests from the `curl` pod in `test-ns-2`, and observed that all resolved to the `httpbin` workload in the `config` namespace, again, as expected.

Inspecting the clusters and endpoints for the `curl` pod proxies in `test-ns-1` and `test-ns-2` both yielded the expected results as well: `test-ns-1` has 5 endpoints for the `outbound|80||example.com` cluster, matching IP addresses from `dig example.com`. `test-ns-2` has 1 endpoint for the `outbound|80||example.com` cluster, matching the in-cluster address of the single `httpbin` pod in the `config` namespace.

Can you share any more details about your installation method or other resources that might be relevant? If this is a lab setup, can you provide any results from `istioctl bug-report` that you feel comfortable sharing? Can you reproduce this issue on a fresh `kind` cluster?
