### ISSUE TITLE
ServiceEntry for external HTTPS proxy with multiple CIDRs not working as expected

### ISSUE THREAD

**Issue by qa-philipp-kloeppner** [istio/istio#55716]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Our service needs to reach a resource outside the cluster. This resource can only be reached using a proxy, let's call it the "intranet proxy". This intranet proxy has a domain which resolves to addresses in two CIDRs: `10.0.80.0/23` and `10.0.82.0/24`. We consulted the [documentation article on using external HTTPS proxies](https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/) and came up with this ServiceEntry:
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: intranet-proxy-external
spec:
  hosts:
    - intranet-proxy.placeholder
  addresses:
    - "10.0.82.0/24"
    - "10.0.80.0/23"
  ports:
    - number: 8080
      name: tcp
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```
With this service entry, we could reach the resolved addresses in `10.0.82.0/24`. Whenever our service tried to `HTTP CONNECT` through an intranet proxy instance in `10.0.80.0/23`, envoy returned a 404.

Our current working solution is to use two service entries, one for each CIDR, with different host placeholders (because using the same host with different CIDRs doesn't seem to work; `istioctl proxy-config clusters` shows only one entry when doing so).

It seems that this is not the intended behavior. If it is, please document it somewhere easily discoverable.

### Version

```Text
$ istioctl version
client version: 1.25.0
control plane version: 1.23.4
data plane version: 1.23.4 (11 proxies)
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.31.6-eks-bc803b4
$ helm version --short
v3.17.1+g980d8ac
```
