### ISSUE TITLE
remoteIpBlocks does not work as expected when X-Forwarded-For header contains multiple IPs

### ISSUE THREAD

**Issue by luiof** [istio/istio#55722]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We have an `AuthorizationPolicy` to allow the traffic from a specific set of remote IPs only but from our tests the [remoteIpBlocks](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source-remote_ip_blocks) is not working as expected.

We have the following policy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorization-policy-test
  namespace: test-ns
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
        remoteIpBlocks:
          - "93.34.34.216/32"
  targetRefs:
  - kind: Gateway
    name: istio-gateway-test
    group: gateway.networking.k8s.io
```
where `93.34.34.216` is my IP. This is blocking me, we get 403 `RBAC: access denied` as response from the service mesh.

From the istio logs we see that the `x-forwarded-for` header has the `93.34.34.216, 23.219.81.45,192.168.32.11` value. The public ip is the first one.

If we use:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorization-policy-test
  namespace: test-ns
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
        remoteIpBlocks:
          - "192.168.32.11/32"
  targetRefs:
  - kind: Gateway
    name: istio-gateway-test
    group: gateway.networking.k8s.io
```
we can interact with the service without getting any 403 `RBAC: access denied`. This is a bug, the `remoteIpBlocks` should consider the first IP, not the last one.

We see the same behavior if we use:
```
    when:
    - key: remote.ip
      values: ["192.168.32.11/32"]
```

We could use the following:
```
    when:
    - key: request.headers[x-forwarded-for]
      values: ["93.34.34.216, 23.219.81.45,192.168.32.11"]
```
but this is not expandable. 

### Version

```Text
Istio 1.25.1
Kubernetes 1.31.7 (we see the same behavior with the OpenShift service mesh)
```

### Additional Information

We performed a search in the repository and we see some issues about this, like https://github.com/istio/istio/issues/47947 but we do not understand why they have been closed since this is a bug.

**Comment by tjons** [comment]
@luiof what's your `meshConfig.gatewayTopology.numTrustProxies` value set to?

**Comment by vietwow** [comment]
@tjons I'm using istio v1.25.2 on EKS 1.32 and got the same issue (my topology is : client -> AWS ALB -> Istio-ingressgateway -> pods

I have tried `meshConfig.gatewayTopology.numTrustedProxies` with both 1 and 2 value but no luck.

**Comment by AlfredoFausto** [comment]
There is an issue with the meshConfig gatewayTopology is not configuring the proxies to set the trust hops. I got it working with an envoyfilter

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          xff_num_trusted_hops: 1
```

**Comment by ramaraochavali** [comment]
> There is an issue with the meshConfig gatewayTopology is not configuring the proxies to set the trust hops. I got it working with an envoyfilter

Can you please share your meshConfig and where is it (Gateway or Sidecar) not being applied?

**Comment by terev** [comment]
Same issue here, using 1.25.2 . Applying the envoy filter detailed in https://github.com/istio/istio/issues/30166#issuecomment-1193058420 to my workload seems to get it working. Is it not a bug that the `xff_num_trusted_hops` field is not being propagated to non ingress sidecars?

**Comment by AlfredoFausto** [comment]
@ramaraochavali I think the behavior is correct. The policy should be enforced at the edge (ingress gateway) the xff_num_trusted_hops cannot be applied to sidecars. It's only applied at the gateway https://github.com/istio/istio/blob/ee0c81b3dabd9d05c957b85f58578e0352c5024a/pilot/pkg/networking/core/gateway.go#L709

**Comment by terev** [comment]
Sure it isn't applicable at the moment, but should it be?

My use case is that I'd like to apply an ip allow list authorization policy to a specific workload, without impacting all traffic through my ingress gateway. If this use case isn't / won't be supported the docs should at least reflect that.

**Comment by YvesEarnix** [comment]
Rule with **x-envoy-external-address** work but not remoteIpBlocks.
```
when:
    - key: request.headers[x-envoy-external-address]
      values:
       - 123.123.123.120

```


Seen to be a bug related to remoteIpBlocks more that to NumTrustedProxies

How Istio compute remoteIpBlocks ?

Why this issue was close https://github.com/istio/istio/issues/30166 ?

**Comment by YvesEarnix** [comment]
Partial workaround validated can be apply on Istio Gateway.

1. Set numTrustedProxies on the Gateway
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  tag: 1.26.2
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1 
```

2. On a EnvoyFilter on the Istio Gateway, **overwrite the 'X-Forwarded-For' header** with the **X-Envoy-External-Address**
```
##
# See https://github.com/istio/istio/issues/30166
##
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-x-forwarded-for
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      operator.istio.io/component=IngressGateways
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value:
          name: sanitize-x-forwarded.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                 local headers = request_handle:headers()
                 local client_id = headers:get("X-Envoy-External-Address")
                 headers:replace("x-forwarded-for", client_id)
              end

```
3. Policy should work as expected

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        remoteIpBlocks:
         - 1.1.1.1/24
 ```

**Comment by YvesEarnix** [comment]
Ideally _**numTrustedProxies**_ should be configurable on Waypoint Gateway.
But actually seem to be not supported

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: waypoint
spec:
  gatewayClassName: istio-waypoint
  infrastructure:
    annotations:
      proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 }}'
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE

```
