### ISSUE TITLE
HTTP/2 Connection Reuse Causes 404 NR in Istio with native Kubernetes Gateway API

### ISSUE THREAD

**Issue by prashanth-nani** [istio/istio#55732]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Problem Summary
We are experiencing an issue with Kubernetes Gateway API where browsers reuse HTTP/2 connections across multiple virtual hosts, causing requests to be routed incorrectly and resulting in a 404 NR error. The issue occurs specifically when using both wildcard (`*.example.com`) and apex (`example.com`) domains on the same Gateway with a shared TLS certificate.

With Istio Gateway, it was possible to use the same listener for both wildcard and apex domains since it supports a list of hosts. However, Kubernetes Gateway API only allows a single hostname per listener, leading to this issue.

### Affected Setup
- **Kubernetes Version:** (e.g., v1.31)
- **TLS Configuration:** Single wildcard certificate covering both `example.com` and `*.example.com`

### Gateway YAML (Relevant Excerpt)
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - hostname: "*.example.com"
    name: https-wildcard
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: example-wildcard-tls
      mode: Terminate
  - hostname: "example.com"
    name: https-apex
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: example-wildcard-tls
      mode: Terminate
```

### Steps to Reproduce
1. Deploy the above Gateway and configure appropriate `HTTPRoute` resources.
2. Access `https://example.com` in a browser (this domain hosts the UI).
3. The UI makes a fetch request to `https://api.example.com`.
4. The browser reuses the existing HTTP/2 connection, but the request is misrouted, resulting in a 404 error.

### Expected Behavior
Each request should be routed correctly based on the `Host` header, even when HTTP/2 connection reuse occurs.

### Version

```Text
$ istioctl version
client version: 1.25.0
control plane version: 1.25.0
data plane version: 1.25.0 (90 proxies)

$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.31.4+rke2r1
```

### Additional Information

Related #13589
