### ISSUE TITLE
Catch-all Egress Gateway with mTLS origination

### ISSUE THREAD

**Issue by linouxis9** [istio/istio#55749]
**Describe the feature request**
The goal is to be able to use an Egress gateway to do mTLS traffic with services outside the service mesh. The services might not necessarily have a ServiceEntry, and we have to translate Istio mTLS CA into mTLS with another CA.

If I can be of any help, thanks a lot!

I tried to do something like that, but to no avail:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: egressgateway
...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egressgateway
...
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 8000
        name: http2
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: internal-egressgateway-rule
spec:
  host: egressgateway.default.svc.cluster.local
  subsets:
    - name: internal
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 8000
            tls:
              mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: redirect-to-egressgateway
spec:
  hosts:
  - "*.net" # How to instead have a wildcard for IP addresses, especially useful when a ServiceEntry cannot be created dynamically ?
  gateways:
  - mesh
  - egressgateway
  http:
  - match:
    - gateways:
      - mesh
      port: 8000
    route:
    - destination:
        host: egressgateway.default.svc.cluster.local
        subset: internal
        port:
          number: 8000
  - match:
    - gateways:
      - egressgateway
    - port: 8000
    route:
    # Here, I am getting a "alpn/alpn_filter.cc:68 cannot find cluster outbound|8443|*.net"
    - destination:
        host: "*.net" # Is there a way to specifically match here the host that was matched in VirtualService in a generic way? :(
        port:
          number: 8443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: egressgateway
spec:
  host: "*"
  workloadSelector:
    matchLabels:
      istio: egressgateway
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 8443
        tls:
          mode: MUTUAL
          credentialName: my-secrets
          sni: "MY_SNI"
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
