### ISSUE TITLE
Istio Gateway Not Binding to Private IP Address

### ISSUE THREAD

**Issue by nitindhiman314e** [istio/istio#55774]
Hi Team,

I am trying to configure an Istio Gateway to bind to a specific private IP (10.10.12.201), but the gateway does not bind to this IP. Instead, the ingress gateway pod only has an assigned IP from the cluster network (10.0.1.64/32).
Even after setting bind: 10.10.12.201 in the Istio Gateway YAML, Also I am unable to curl the bind address from another container within the cluster.

I'm using below Ingress Gateway Configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: private-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway  # Uses the default Istio ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
    bind: 10.10.12.201  # Listen on all interfaces for HTTP
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - "*"
    bind: 10.10.12.201  # Listen on all interfaces for HTTPS
    tls:
      mode: SIMPLE  # SIMPLE for regular TLS, use PASSTHROUGH or MUTUAL for other modes
      credentialName: istio-ingressgateway-certs  # Reference the TLS secret you created
      privateKey: sds  # Use SDS (Secret Discovery Service) for secret management
      serverCertificate: sds  # Use SDS (Secret Discovery Service)
```

Check the istio-ingressgateway service type and assigned IPs:

```
kubectl get svc -n istio-system istio-ingressgateway

NAME                   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
istio-ingressgateway   NodePort   10.97.152.185   <none>        80:13784/TCP,443:12567/TCP   3h6m
```

Could you please help me to sort it out?

Thanks.
