### ISSUE TITLE
ServiceEntry with DNS resolution not building clusters when `clusterLocal=true` for all hosts

### ISSUE THREAD

**Issue by Kuromesi** [istio/istio#55798]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I enabled `clusterLocal=true` for all services with configuration like:
```yaml
serviceSettings:
    - settings:
        clusterLocal: true
      hosts:
      - "*"
```

Then I tried to add a `ServiceEntry` like:
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test
  namespace: istio-system
spec:
  exportTo:
  - '*'
  hosts:
  - istio.io
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```

What I expected to see is a cluster like `outbound|80||istio.io` is added in sidecar, however it did not.

It seems like when handling `ServiceEntry` with DNS resolution, locality info is not added to the `IstioEndpoint`.

```go
out = append(out, &model.ServiceInstance{
	Endpoint: &model.IstioEndpoint{
		Addresses:            []string{string(service.Hostname)},
		EndpointPort:         endpointPort,
		ServicePortName:      serviceEntryPort.Name,
		LegacyClusterPortKey: int(serviceEntryPort.Number),
		Labels:               nil,
		TLSMode:              model.DisabledTLSModeLabel,
	},
	Service:     service,
	ServicePort: convertPort(serviceEntryPort),
})
```
So this endpoint is filtered here since `ep.Locality.ClusterID` always equals to "":

![Image](https://github.com/user-attachments/assets/c584c637-48a7-4ea8-9c76-b408dc10273a)

If I configured a `ServiceEntry` with STATIC resolution like:
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test
  namespace: istio-system
spec:
  endpoints:
  - address: 1.1.1.1
  exportTo:
  - '*'
  hosts:
  - istio.io
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
```

It works fine because the `IstioEndpoint` is generated in `func (s *Controller) convertEndpoint` with locality info:
```go
return &model.ServiceInstance{
	Endpoint: &model.IstioEndpoint{
		Addresses:       []string{addr},
		EndpointPort:    instancePort,
		ServicePortName: servicePort.Name,

		LegacyClusterPortKey: int(servicePort.Number),
		Network:              network.ID(wle.Network),
		Locality: model.Locality{
			Label:     locality,
			ClusterID: clusterID,
		},
		...
	},
	Service:     service,
	ServicePort: convertPort(servicePort),
}
```

Can we also add locality info for `ServiceEntry` with DNS resolution so this issue can be resolved? Or is it design like this?

### Version

```Text
istio 1.24.2
```
