### ISSUE TITLE
can't block rerquests to service from ingresss

### ISSUE THREAD

**Issue by mlushpenko** [istio/istio#5582]
We want to block requests to the app behind nginx ingress based on some parameters. We are testing bookinfo app. If we deny requests to one of backend services - it works fine, if we try to deny requests to product page, it it still gets displayed.

This example works fine:

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-test-abort
  namespace: default
spec:
  destination:
    name: ratings
  httpFault:
    abort:
      httpStatus: 500
      percent: 100
  route:
  - labels:
      version: v1
```

and then we get such reponse on the page:
![image](https://user-images.githubusercontent.com/2006610/39993414-114cf75c-5776-11e8-8f68-ccdc3d339351.png)

And then we try to repeat the same on productspage:

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: productpage-test-abort
  namespace: default
spec:
  destination:
    name: productpage
  httpFault:
    abort:
      httpStatus: 500
      percent: 100
  route:
  - labels:
      version: v1
```

And the product page is displayed with no issue. ANy pointers what we are doing wrong?

Latest version of istio.
