### ISSUE TITLE
Istio ambient for opentelemetry trace not work

### ISSUE THREAD

**Issue by g3david405** [istio/istio#55843]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I'm currently using Istio in Ambient mode, and I want to export my API traces to an OpenTelemetry Collector (which is backed by Tempo as the data storage).

Below are my MeshConfig and Telemetry CRD settings.

**meshconfig** 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    enableTracing: true
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.open-telemetry.svc.cluster.local
        resource_detectors:
          environment: {}
    pathNormalization:
      normalization: MERGE_SLASHES
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

**Telemetry CRD**

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: envoy
  tracing:
    - customTags:
        my-attribute:
          literal:
            value: default-value
      providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
```

However, I noticed that only traces from istio-ingress are being recorded, and not from my other services.

![Image](https://github.com/user-attachments/assets/e3f4a260-89c8-415e-ba88-1c77c129d1d2)

My understanding is that the Telemetry in the istio-system namespace is the default for the entire cluster. However, even if I add the Telemetry CRD in each namespace, I am unable to collect traces from services in those namespaces.

In the istio document, all services that should be record as a span, not only istio ingress (ex: app1-svc.app1-ns.svc.cluster.local).

Could you help explain why this is happening?

Thanks!

### Version

```Text
istio version: 1.24.1

kubernetes version: 1.30.4
```

**Comment by howardjohn** [comment]
Do you have a waypoint deployed? Is traffic using the waypoint?

**Comment by g3david405** [comment]
@howardjohn 
yes, I use waypoint for my namespace.
Here is my namespace spec:
```
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
status:
  phase: Active
spec:
  finalizers:
    - kubernetes
```

And here is my Gateway spec:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: waypoint
  namespace: my-namespace
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
```

How can I confirm that waypoint is working?
thanks!
