### ISSUE TITLE
ServiceEntry without exportTo Causes Connectivity Issue Across Namespaces

### ISSUE THREAD

**Issue by srmars** [istio/istio#55879]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Encountering an issue with Istio Service Entries where a pod in one namespace cannot connect to a specific port of an external host due to conflicting Service Entry configurations across namespaces.

**Steps to Reproduce:**
1. Create a Service Entry in namespace-1 with the following configuration
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-http
  namespace: namespace-1
spec:
  hosts:
  - google.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  exportTo:
  - "."
```
 2. Create another Service Entry in namespace-2 with the following configuration:
 ```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-https
  namespace: namespace-2
spec:
  hosts:
  - google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
```

3. Deploy a pod in namespace-1 that attempts to connect to google.com:443 (e.g., using curl https://google.com).

**Expected Behavior:**
The pod in namespace-1 should be able to connect to google.com on port 443, as there is a Service Entry in namespace-2 defining this external service, and namespace-1 should either inherit it or allow the connection.

**Actual Behavior:**
The pod in namespace-1 is unable to connect to google.com:443. 

**Request:**
Could you please clarify if this is expected behavior with exportTo and provide guidance on how to configure Service Entries across namespaces to allow pods in namespace-1 to access google.com:443 without duplicating the configuration? If this is a bug, please advise on next steps.

### Version

```Text
istio version 1.24.3
```
