### ISSUE TITLE
CNI Chaining Race Condition Between cilium and istio-cni

### ISSUE THREAD

**Issue by share-me** [istio/istio#55894]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I have CNI chaining between Cilium and istio-cni

Pods on certain nodes are failing with this error:
_(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2a44c(random)191c": plugin type="istio-cni" failed (add): Get "http://localhost:8080/api/v1/namespaces/kube-system/pods/coredns-57bb6779fb-8vlr8": dial tcp [::1]:8080: connect: connection refused_

This only happens on nodes where istio-cni started faster than the Cilium pod (which is very often the case).
I think it's a race condition because everything returns to normal when I recreate the istio-cni pod.

How can I manage this? I cannot manually restart istio-cni each time a new node is automatically created (ASG and Karpenter).

### Version

```Text
cilium 1.17.1
istio 1.25.1
EKS 1.32 (with prefix delegation)
Bottlerocket OS 1.36.0
```

**Comment by howardjohn** [comment]
Istio is supposed to be detecting if files are changed (by cilium, etc) and overwriting them.

Might be the same as https://istio.slack.com/archives/C041EQL1XMY/p1741270177678979.

Do you have the logs of istio-cni?

**Comment by share-me** [comment]
| node dir       | container install-cni | container cilium-agent |
|:---------------|:----------------------|:-----------------------|
| /opt/cni/bin   | /host/opt/cni/bin     | /host/opt/cni/bin      |
| /proc          | /host/proc            | /hostproc              |
| /etc/cni/net.d | /host/etc/cni/net.d   | /host/etc/cni/net.d    |
| /var/run/netns | /host/var/run/netns   | /var/run/cilium/netns  |

[node1_KO_install-cni.log](https://github.com/user-attachments/files/19736934/node1_KO_install-cni.log)
[node1_OK_install-cni.log](https://github.com/user-attachments/files/19736935/node1_OK_install-cni.log)

I just deleted the istio-cni-node pod to recreate it, and all the other pods with the "Failed to create pod sandbox:" error changed to "running" state.

**Comment by howardjohn** [comment]
Hmm, so that `istio-cni` seems to only have partial config.

The thing causing localhost:8080 is actually `/var/run/istio-cni/istio-cni-kubeconfig` though -- this should be used, but k8s transparently falls back to a default config to localhost:8080 if not present (we should probably make this hard-fail instead)

**Comment by howardjohn** [comment]
FWIW I tried to setup a reproducer...

k3s on a VM. Cilium installed with `--set cni.exclusive=false`. I add a nodeSelector to cilium to make it not run. Then I restart the node.

This guarantees istio-cni starts first. Then I label the node to allow cilium to run. 

During this time it all works fine for me, so I was unable to repro

**Comment by share-me** [comment]
Can you explain the risk of having istio-cni-node start before cilium?
So I can better focus my investigation.

What traces can I provide you with? Can relaunching istio-cni-node with a different log level help?

For the Istio chart 1.25.1, the default values are kept.

Here are the Helm values I'm using with Cilium 1.17.1

```yaml
cni:
  chainingMode: generic-veth
  chainingTarget: istio-cni
  exclusive: false


socketLB:
  hostNamespaceOnly: true

eni:
  enabled: true
  awsEnablePrefixDelegation: true
  awsReleaseExcessIPs: true
  updateEC2AdapterLimitViaAPI: true
egressMasqueradeInterfaces: eth0


nodeinit:
  enabled: false

ipam: 
  mode: eni
cni: 
  customConf: true
  configMap: cni-configuration

routingMode: native

kubeProxyReplacement: true
rollOutCiliumPods: true

# https://docs.cilium.io/en/v1.11/gettingstarted/local-redirect-policy/#node-local-dns-cache
localRedirectPolicy: true

```
