### ISSUE TITLE
ExternalName doesn't work with ServiceEntries

### ISSUE THREAD

**Issue by AlfredoFausto** [istio/istio#55923]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

An existing externalService needs to be used within mesh, I craated a ServiceEntry to map the externalName of a database as following:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: aurora-rds-proxy-gemini-pg-cert0
  namespace: postgresql-client
  annotations:
    networking.istio.io/exportTo: "."
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: ExternalName
  externalName: database-1-instance-1.c3caqxxx02i2lx6.us-west-2.rds.amazonaws.com
```

And the ServiceEntry

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: aurora-rds-proxy-gemini-pg-cert0
  namespace: postgresql-client
spec:
  exportTo: 
  - "."
  hosts:
    - aurora-rds-proxy-gemini-pg-cert0.postgresql-client.svc.cluster.local
  ports:
    - name: tcp
      number: 5432
      protocol: tcp
      targetPort: 5432
  location: MESH_EXTERNAL
  resolution: DNS
```

the following only created a listener for `aurora-rds-proxy-gemini-pg-cert0.postgresql-client.svc.cluster.local` but the cluster is missing and traffic is not routing.

```bash
istioctl pc listeners postgresql-client.postgresql-client | grep aurora
240.240.0.5    5432  ALL                                                     Cluster: outbound|5432||aurora-rds-proxy-gemini-pg-cert0.postgresql-client.svc.cluster.local
istioctl pc clusters postgresql-client.postgresql-client | grep aurora
# there is no cluster 
```
Hence, a connection to the db cannot be made.

This should be supported per the changes in https://istio.io/latest/news/releases/1.21.x/announcing-1.21/upgrade-notes/

### Version

```Text
istioctl version
client version: 1.24.1
control plane version: 1.25.1

kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.30.11-eks-bcf3d70
```
