### ISSUE TITLE
Istio egressgateway connection to oracle db

### ISSUE THREAD

**Issue by bhat39a** [istio/istio#55966]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi Team,

We are having issue while connecting to an Oracle DB, i am sharing the config details please have a look .

Error : 

Istio-proxy sidecar container logs

[2025-04-16T15:57:29.144Z] "- - -" 0 UF,URX - - "-" 0 0 9998 - "-" "-" "-" "-" "192.168.72.132:1521" outbound|1521||oracledb.com - 192.168.72.132:1521 100.64.107.42:51610 - -

Istio Setup : 

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: oracledb
  namespace: istio-system
spec:
  hosts:
  - "oracledb.com"
  addresses:
  - "192.168.72.132"
  ports:
  - number: 1521
    name: db-port
    protocol: tcp
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egressgateway-for-oracle-db
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 1521
      name: db-port
      protocol: tcp
    hosts:
    - "oracledb.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-for-oracle-db
  namespace: istio-system
spec:
  host: "oracledb.com"
  subsets:
  - name: oracledb
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oracle-db-vs
  namespace: istio-system
spec:
  hosts:
  - oracledb.com
  gateways:
  - egressgateway-for-oracle-db 
  http: [] 
  tcp:
  - match:
    - port: 1521
    route:
    - destination:
        host: oracledb.com
        subset: oracledb 
        port: 
          number: 1521
```

### Version

```Text
% kubectl version        
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.30.10-eks-bc803b4
WARNING: version difference between client (1.32) and server (1.30) exceeds the supported minor version skew of +/-1
avijitbhattacharya@MAC-MJ4N56T32X raw_deployments % istioctl version       
client version: 1.24.2
control plane version: 1.23.0
data plane version: 1.23.0 (18 proxies)
%
```
