### ISSUE TITLE
Bookinfo samples are using  Read-only file system

### ISSUE THREAD

**Issue by mgfnv9** [istio/istio#56032]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

All reviews-v1, reviews-v2, reviews-v3 samples Bookinfo are using  read-only filesystem.

```
reviews-v1-758f49bf65-ff86x       1/2     CrashLoopBackOff   9 (2m35s ago)   23m
reviews-v2-5879f5ff45-2l6pf       1/2     CrashLoopBackOff   9 (2m20s ago)   23m
reviews-v3-5757b458f-m9wk7        1/2     CrashLoopBackOff   9 (2m1s ago)    23m


/opt/ol/helpers/runtime/docker-server.sh: line 76: /config/configDropins/defaults/keystore.xml: Read-only file system
```

But we use Kyverno with PSA restricted mode and our pods don't use Read only root filestem true.

### Version

```Text
# kubectl version
Client Version: v1.29.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8

# helm version --short -n istio-system
v3.15.4+gfa9efb0

# istio version 1.25.2

# Bookinfo
https://raw.githubusercontent.com/istio/istio/release-1.25/samples/bookinfo/platform/kube/bookinfo.yaml
```

**Comment by howardjohn** [comment]
I think the issue is not that they use a read-only filesystem, its that they expect to have a writeable filesystem which your Kyverno policy breaks. Which may or may not be something easy to fix, not too familiar with the (very ancient) reviews java codebase

**Comment by mgfnv9** [comment]
> I think the issue is not that they use a read-only filesystem, its that they expect to have a writeable filesystem which your Kyverno policy breaks. Which may or may not be something easy to fix, not too familiar with the (very ancient) reviews java codebase

My mistake, you are right.
Its that they expect to have a writeable filesystem which my Kyverno policy PSA Restricted breaks.

**Comment by majones-services** [comment]
Although I'm running k3s i have hardened the cluster and like you have restricted mode applied. I added the needed yaml like this:
````
    spec:
      securityContext:
        # This is the pod-level securityContext
        runAsNonRoot: true
        runAsUser: 1001 
        runAsGroup: 1001  
        fsGroup: 1001    # Ensures that volumes are writable by this group
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: [ "ALL" ]
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
````
I did originally have readOnlyRootFilesystem set to true and ran into the same error that that you did:

/opt/ol/helpers/runtime/docker-server.sh: line 76: /config/configDropins/defaults/keystore.xml: Read-only file system

Once I update the root file system to not be readonly, the pods worked as designed.
