### ISSUE TITLE
Local rate limiter does not work with multiple descriptor entries

### ISSUE THREAD

**Issue by emilnkrastev** [istio/istio#56060]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I'm trying to create local rate limit with multiple rate limits rules and I'm unable to do it. It works with single rate limit for path perfectly but when I add additional rate limit actions it stops

I'm providing my EnvoyFilter:

````
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit
  namespace: test
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|8080
          route:
            action: ROUTE
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_key: path
                descriptor_value: ip
                headers:
                - name: :path
                  string_match:
                    ignore_case: true
                    prefix: /ip
            - header_value_match:
                descriptor_key: path
                descriptor_value: headers
                headers:
                - name: :path
                  string_match:
                    ignore_case: true
                    prefix: /headers
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            descriptors:
            - entries:
              - key: path
                value: /ip
              token_bucket:
                fill_interval: 30s
                max_tokens: 2
                tokens_per_fill: 2
            - entries:
              - key: path
                value: /headers
              token_bucket:
                fill_interval: 30s
                max_tokens: 6
                tokens_per_fill: 6
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: http_local_rate_limiter
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: http_local_rate_limiter
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http
            token_bucket:
              fill_interval: 10s
              max_tokens: 2147483647
              tokens_per_fill: 2147483647
  workloadSelector:
    labels:
      app: myapp

````

I also tried with request_headers and it does work as well.

### Version

```Text
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.13
Kustomize Version: v4.5.7
Server Version: v1.30.11-eks-bcf3d70
WARNING: version difference between client (1.26) and server (1.30) exceeds the supported minor version skew of +/-1


istio version
1.24.2
```

**Comment by cam634** [comment]
It does work try this 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit
  namespace: test
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
    patch: 
      operation: MERGE
      value: 
        route: 
          rate_limits: 
          - actions: 
            - remote_address: {}
          - actions: 
            - header_value_match: 
                descriptor_value: route1
                headers: 
                - name: :path
                  string_match: 
                    prefix: /ip    
          - actions: 
            - remote_address: {}
          - actions: 
            - header_value_match: 
                descriptor_value: route2
                headers: 
                - name: :path
                  string_match: 
                    prefix: /header   
        typed_per_filter_config: 
          envoy.filters.http.local_ratelimit: 
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            always_consume_default_token_bucket: false
            descriptors: 
            - entries: 
              - key: header_match
                value: route1
              token_bucket: 
                fill_interval: 60s
                max_tokens: 5000
                tokens_per_fill: 5000
            - entries: 
              - key: header_match
                value: route2
              token_bucket: 
                fill_interval: 60s
                max_tokens: 100
                tokens_per_fill: 100
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: http_local_rate_limiter
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: http_local_rate_limiter
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http
            token_bucket:
              fill_interval: 10s
              max_tokens: 2147483647
              tokens_per_fill: 2147483647
```
