### ISSUE TITLE
Workload-level mTLS is not initiated when mTLS is disabled at the mesh-level

### ISSUE THREAD

**Issue by happyyi008** [istio/istio#56084]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Apply the following peer authentication rule
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "mesh-disable"
  namespace: istio-system
spec:
  mtls:
    mode: DISABLE
```

Create test services
```
istioctl kube-inject -f istio/samples/httpbin/httpbin.yaml | k apply -nistio-sandbox -f -
istioctl kube-inject -f istio/samples/curl/curl.yaml | k apply -nistio-sandbox -f -
```

Apply workload level mTLS rule
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "istio-sandbox-httpbin-strict"
  namespace: istio-sandbox
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app: httpbin
```

Given auto mTLS, the expected behavior is for curl to initiate mTLS connections to httpbin, but that's not the case. Requests from curl to httpbin fails with `connection reset`, this indicates the workload level peer authentication rule is applied, and on the httpbin istio proxy we observe `NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.7.156:8080 100.96.6.169:49002 - -`, which alsindicates curl did not initiate an mTLS connection.

Workarounds found are to create a destination rule for `httpbin.istio-sandbox.svc.cluster.local` and set the mTLS mode to ISTIO_MUTUAL or to create a namespace-level peer authentication rule that sets mTLS mode to permissive or strict.

This behavior is odd. It seems like a mesh or namespace-level peer authentication rule somehow interferes with whether a client initiates an mTLS connection, but at the workload level, this is ignored.

### Version

```Text
$ istioctl version
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.3 (15 proxies)

$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.25.13
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [x] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
