### ISSUE TITLE
Ability to create multiple waypoint deployment in one waypoint gateway

### ISSUE THREAD

**Issue by zhuoyang** [istio/istio#56134]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
I want to be able to create multiple waypoint deployment in one waypoint gateway, The use case here is to have 1 deployment per AZ, so that the waypoint in a single AZ can be scaled independently by HPA.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by odellem** [comment]
If you mean multiple pods per deployment, then you can already apply an HPA to that deployment. See below:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: example-waypoint
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-waypoint-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-waypoint
  minReplicas: 2
  maxReplicas: 4
```
