### ISSUE TITLE
Virtual Service Match Rules with multiple Prefixes

### ISSUE THREAD

**Issue by hdattada** [istio/istio#56147]
Hi we are trying to setup virtual service rules to handle multiple prefixes. I have used [this](https://istio.io/latest/docs/reference/config/networking/virtual-service/?_ga=2.268829557.582229627.1746057128-26771323.1744319146#Destination) as a reference, except added a `rewrite` rule for one of the prefixes.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-vs
  namespace: ns
spec:
  gateways:
    - istio-system/istio-internal-gateway
  hosts:
    - PREFIX-xy-https.DOMAIN
  http:
    - match:
      - uri:
          prefix: /xy/inference/service-a/public/
      - uri:
          prefix: /xy/inference/service-a/
      rewrite:
        uri: /xy/inference/service-a/
      route:
        - destination:
            host: service-a.ns.svc.cluster.local
            port:
              number: 8000

```

Intended Behavior:
* Requests to `xy/inference/service-a/` are rightly routed to the destination `service-a.ns.svc.cluster.local`
* Requests to `xy/inference/service-a/public/` are rightly routed to the destination `service-a.ns.svc.cluster.local` , with the URL being rewritten to `xy/inference/service-a/`.

Observed Behavior:
* Requests to `xy/inference/service-a/` are rightly routed to the destination `service-a.ns.svc.cluster.local`
* Requests to `xy/inference/service-a/public/` are rightly routed to the destination `service-a.ns.svc.cluster.local` , However the URL is not  being rewritten and the original prefix is forwarded to the destination eg:  `xy/inference/service-a/public/`.

Can you please suggest whats needed to achieve this behavior.
