### ISSUE TITLE
Istio is not discovering WasmPlugin for ingress gateway

### ISSUE THREAD

**Issue by alexeysofin** [istio/istio#56169]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

wasm plugin is not propagated to envoy, and no visible sign why

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: plugin
spec:
  selector:
    matchLabels:
      app: istio-gateway-public
  url: "oci://repo.com/wasm-plugin:latest"
  imagePullPolicy: IfNotPresent
  imagePullSecret: some-secret
  priority: 1000
  match:
    - mode: SERVER
  vmConfig:
    env:
      - name: SOME_ENV
        valueFrom: HOST
```

Proxy status fine, no events in describe wasmplugin

```
istioctl proxy-status
NAME                                                   CLUSTER        CDS        LDS        EDS        RDS        ECDS     ISTIOD                      VERSION
istio-gateway-5c49c97c7c-ckddb.istio-system            Kubernetes     SYNCED     SYNCED     SYNCED                         istiod-7d858df8f8-96b26     1.25.2
```

### Version

```Text
$ istioctl version
client version: 1.22.0
control plane version: 1.25.2
data plane version: 1.25.2 (2 proxies)

$ kubectl version 
Client Version: v1.31.7
Kustomize Version: v5.4.2
Server Version: v1.32.3-eks-4096722

$ helm version --short
v3.13.2+g2a2fb3b
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [x] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by aliaksei-imi** [comment]
Is this even legal to attach a wasmplugin to ingress GW pods? 

Added the same configuration, but selected injected proxy pod instead of gateway pods, and it worked

**Comment by alexeysofin** [comment]
Is this even legal to attach a wasmplugin to ingress GW pods?

Added the same configuration, but selected injected proxy pod instead of gateway pods, and it worked

**Comment by zirain** [comment]
did you create the wasmplugin in the same namespace with the gateway pods? did the labels matched?

**Comment by alexeysofin** [comment]
yep

```
kubectl -n istio-system get pod -l istio=gateway-public
NAME                                    READY   STATUS    RESTARTS   AGE
istio-gateway-public-6d87f59ddf-j44r9   1/1     Running   0          11h
```

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  creationTimestamp: "2025-05-05T17:15:46Z"
  generation: 4
  labels:
    kustomize.toolkit.fluxcd.io/name: istio-oauth2-login
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: plugin
  namespace: istio-system
spec:
  imagePullPolicy: IfNotPresent
  imagePullSecret: docker-secret
  match:
  - mode: SERVER
  priority: 1000
  selector:
    matchLabels:
      istio: gateway-public
  url: oci://internal-registry.com/plugin:latest
  vmConfig:
    env:
    - name: SECRET
      valueFrom: HOST
    - name: COOKIE_SECURE
      value: "true"
```
