### ISSUE TITLE
istio changes not reflecting for container.apparmor.security.beta.kubernetes.io migration from kubernetes 1.30 version

### ISSUE THREAD

**Issue by sambitr** [istio/istio#56179]
Hi There,

As you know from k8s version 1.30 onwards, container.apparmor.security.beta.kubernetes.io annotation is deprecated in favour of the security context field. I can see from this issue: https://github.com/istio/istio/issues/54721 that @howardjohn mentioned to move to the security context field from annotations.

I am on Istio 1.23.3 and kubernetes 1.30 version

Till this point, I see the apparmor field is added as security context in the main application container's security context, as well as in the sidecar istio-proxy container. This is expected as per the https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/24-apparmor#removing-annotation-support

![Image](https://github.com/user-attachments/assets/1a314b4e-3dae-467a-9c95-65b5b283c3d5)

![Image](https://github.com/user-attachments/assets/8a68035f-f02c-4b64-a8f3-17937ec0bce1)

Interestingly, the ingressgateway pod deployed in istio-system namespace, did not have the annotation copied over to SecurityContext

```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
```

Now I was trying to remove the annotation from the ingress-gateway deployment, as well as the sidecar injection. But once it is deployed and app restarted, the annotations are gone and no security context field got added. 

![Image](https://github.com/user-attachments/assets/a9a985e6-63de-4f91-b71d-5d22d6d85d5b)

I am confused now, as to whether we should remove the annotations from the Istio deployments as of now or is there any work around for this?

Shall I define explicitly in the pod and container security context, like this:

```
podSecurityContext:
      runAsUser: 1337
      runAsGroup: 1337
      runAsNonRoot: true
      appArmorProfile:
        type: RuntimeDefault
```

```
containers:
    - name: istio-proxy
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        appArmorProfile:
          type: RuntimeDefault
```

and in the IstioControlPlane component?

**Comment by sambitr** [comment]
hi There, can anyone help me on this?

**Comment by jaellio** [comment]
Hi @sambitr, taking a look at this issue, I noticed you are using the `IstioControlPlane` resource. I don't believe this resource is supported anymore. How are you using it?

**Comment by sambitr** [comment]
@jaellio I see it now. istiooperator and as well as istiocontrolplane resources are deprecated now from 1.23. As per the documentation, both the commands resulted an empty result. So our clusters are not impacted. I will see by removing it and how does it ipact.

skrout@uk257143 MINGW64 ~
$ kubectl get deployment -n istio-system istio-operator
Error from server (NotFound): deployments.apps "istio-operator" not found

skrout@uk257143 MINGW64 ~
$ kubectl get IstioOperator
error: the server doesn't have a resource type "IstioOperator"

**Comment by sambitr** [comment]
@jaellio that istiocontrolplane component is not the issue. I restored everything else, except the istio controlplane and it did not impact anything. We can ignore this.

On our side, istiod inject the configuration to sidecar through a configmap from istio-system namespace. This includes annoations:

```
---
apiVersion: v1
data:
  config: |-
    # defaultTemplates defines the default template to use for pods that do not explicitly specify a template
    defaultTemplates: [sidecar]
    policy: enabled
    alwaysInjectSelector:
      []
    neverInjectSelector:
      []
    injectedAnnotations:
      "container.apparmor.security.beta.kubernetes.io/istio-init": "runtime/default"
      "container.apparmor.security.beta.kubernetes.io/istio-proxy": "runtime/default"
      "seccomp.security.alpha.kubernetes.io/pod": "runtime/default"
```
image and all. This I had removed previously too. After reinstating this, the annotation field got migrated to security context field for both istio-init and istio-proxy components.

istio-proxy:

```
securityContext:
      allowPrivilegeEscalation: false
      appArmorProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
```


istio-init:

```
 securityContext:
      allowPrivilegeEscalation: false
      appArmorProfile:
        type: RuntimeDefault
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
```
