### ISSUE TITLE
Envfilter, Depending on the request, decide whether to include a body.

### ISSUE THREAD

**Issue by Gamattention** [istio/istio#56195]
At present, ours all requests entering the Kubernetes cluster need to go through the authentication service within the cluster for authorization. Traffic control is implemented via the ext_authz component of Istio’s envoy filter. When the request is sent to the authentication service, it does not include the body; however, for certain fixed-path requests, the body information is required for authorization. How should this be handled?

**Comment by Gamattention** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            statusOnError:
              code: GatewayTimeout
            http_service:
              authorization_request:
                allowed_headers:
                  patterns:
                    - exact: "authorization"
                    - exact: "cookie"
                    - exact: "forwarded"
                    - exact: "referer"
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: "kubeflow-userid"
              server_uri:
                cluster: outbound|8080||lpai-auth-service.lpai.svc.cluster.local
                timeout: 10s
                uri: http://lpai-auth-service.lpai.svc.cluster.local
  workloadSelector:
    labels:
      istio: ingressgateway

```
