### ISSUE TITLE
Istio 1.25.0 gateway api http route - ResponseHeaderModifier not working as expected

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#56211]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I am trying to mask the server header so that it doesn't show:
server: istio-envoy

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: istio-addons-ingress
spec:
  parentRefs:
  - name: ingress-addons
    namespace: istio-addons-ingress
  hostnames: ["kiali.redacted.com"]
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: kiali
        namespace: istio-addons
        port: 20001
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: server
                value: "unknown"
```

with a similar filter I am able to remove the "x-envoy-upstream-service-time" header

### Version

```Text
istioctl version
client version: 1.25.2
control plane version: 1.25.0
data plane version: 1.25.0 (16 proxies)

kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.7-eks-bcf3d70
```

### Affected product area

- [x] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
