### ISSUE TITLE
DestinationRule with ConsistentHash is not working with waypoint

### ISSUE THREAD

**Issue by sachincool** [istio/istio#56218]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I was deploying DestinationRule with loadbalancing type  consistentHash in ambient mesh, but Its not working as expected.
It is using 1.25.2, with waypoint enabled, I can see waypoint logs with envoy_originate ips being rotated as well

```
apiVersion: v1
kind: Namespace
metadata:
  name: ambient
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: ambient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=hello from $(POD_NAME)"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: ambient
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: http-echo
  namespace: ambient
spec:
  host: http-echo.ambient.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: sticky-session
        maglev:
          tableSize: 11213
```

I’m sending request from another pod on same namespace

![Image](https://github.com/user-attachments/assets/39639b40-16a7-4e3b-b129-8fa9283f2053)

### Version

```Text
❯ istioctl version
2025-05-08T12:31:45.540337Z	error	port forward failed: error upgrading connection: error dialing backend: dial tcp 10.10.44.101:10250: i/o timeout
client version: 1.25.2
control plane version: 1.25.1
❯ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.3-eks-d0fe756
Kubecolor Version: v0.5.1
```

**Comment by zirkome** [comment]
I was experiencing the same issue, after digging into Istio's code it looks like consistent hash requires a VirtualService:

https://github.com/istio/istio/blob/60bf05bbf34a7afb85a12ecceefae09048b23811/pilot/pkg/networking/core/route/route.go#L327

```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: http-echo
spec:
  host: http-echo.http-echo.svc.cluster.local
  subsets:
  - name: default
    labels:
      app: http-echo
    trafficPolicy:
      loadBalancer:
        consistentHash:
          httpCookie:
            name: user
            ttl: 0s
          maglev:
            tableSize: 11213
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: http-echo
spec:
  hosts:
  - http-echo.http-echo.svc.cluster.local
  http:
  - name: "default-route"
    route:
    - destination:
        host: http-echo.http-echo.svc.cluster.local
        subset: default
```

```
/ # while true; do curl -sS --cookie user=alpha http-echo.http-echo.svc.cluster.local/http-echo | jq -r .os.hostname; sleep 1; done
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55
http-echo-7d9cd6fc98-65p55

/ # while true; do curl -sS --cookie user=beta http-echo.http-echo.svc.cluster.local/http-echo | jq -r .os.hostname; sleep 1; done
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
http-echo-7d9cd6fc98-hw5h8
```

**Comment by plstryagain** [comment]
@zirkome Hi, what version do you use?

**Comment by zirkome** [comment]
@plstryagain it was 1.26

**Comment by keithmattix** [comment]
That comment refers to an internal data structure, not the VirtualService resource. We'll look into it; I'm pretty sure this is a bug

**Comment by tarangini-shetty** [comment]
workaround mentioned in https://github.com/istio/istio/issues/56218#issuecomment-2966675118, made the waypoint proxy and session stickiness(using destination rule) to work together in a namespace.
Ie., adding a virtualservice to the service of the pods that needs stickiness.

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: <name>
spec:
  hosts:
  - <servicehostname>
  http:
  - name: "default-route"
    route:
    - destination:
        host: <servicehostname>
``` 
Is it the expected behaviour? would this have any other implications?
