### ISSUE TITLE
filter_state.downstream_peer missing mesh_id

### ISSUE THREAD

**Issue by djchie** [istio/istio#56212]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

On 1.23, we have a custom TCP metrics `EnvoyFilter` that relied on `downstream_peer.mesh_id` for the `mesh_id`.  Now on 1.24 (after [this change](https://github.com/istio/proxy/pull/5825) was introduced), we don't have a way of accessing [`mesh_id`](https://github.com/istio/proxy/pull/5825/files#diff-ce6ba18e3bc67a54b552b5e67c5a9107cc26b4199b00a3808e241b06d1eabaa6L47) anymore.

This seems expected as described [1.24 Upgrade Notes](https://istio.io/latest/news/releases/1.24.x/announcing-1.24/upgrade-notes/#standardization-of-the-peer-metadata-attributes), as `mesh_id` isn't listed, but we're wondering if there were any discussions about the field removal in particular.

### Version

```Text
$ istioctl version
client version: 1.24.4
control plane version: 1.24-dev
data plane version: 1-24-4 (7 proxies)

$ kubectl version
Client Version: v1.28.12
Kustomize Version: v5.0.4
Server Version: v1.29.15
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
```
// DO NOT USE.
  // Platform metadata uses prefixed keys GCP uses gcp_* keys
  platform_metadata:[KeyVal];

  // DO NOT USE.
  // Version identifier for the proxy.
  istio_version:string;

  // DO NOT USE.
  // Unique identifier for the mesh. Taken from global mesh id parameter (or
  // the configured trust domain when not specified).
  mesh_id:string;

  // DO NOT USE.
  // List of short names for application containers that are using this proxy.
  // This is only used for kubernetes, and is populated by the sidecar injector.
  app_containers:[string];

  // Identifier for the cluster to which this workload belongs (for k8s workloads).
  cluster_id:string;

  // DO NOT USE.
  // instance ip addresses.
  instance_ips:[string];

  // NOT IMPLEMENTED.
  // Identity of the proxy.
  identity:string;
```
these fileds are marked as `DO NOT USE` before the refactor happened, so I think that's why it's missed.

If you really need it, you can workaround with relabel in prometheus.

For multimesh/multicluster you can change the `.prometheus.server.global.external_labels.[mesh_id|cluster_id]`
Or you can add following configuration to the scrape job:
```yaml
- source_labels:
  - __address__
  target_label: mesh_id
  regex: .*
  replacement: <your_mesh_id>
  action: replace
- source_labels:
  - __address__
  target_label: cluster_id
  regex: .*
  replacement: <your_cluster_id>
  action: replace
```

**Comment by dwj300** [comment]
@zirain We can't use a prometheus rewrite since we need to derive the peer mesh_id from the metadata exchange. In a cross-mesh scenario, the peer's mesh_id isn't equal to the proxy's mesh_id

**Comment by zirain** [comment]
@dwj300 are you it worked on 1.23? from the code, the last work version seems to be `1.22`.

**Comment by djchie** [comment]
@zirain Yeah we were on `1.23.4` when we were still able to grab the `mesh_id`. We started noticing the missing `mesh_id` as we're upgrading to `1.24.4`.

**Comment by zirain** [comment]
I had no luck to make it work on 1.23.5 with following configuration:
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-id
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: ALL_METRICS
            mode: CLIENT
          tagOverrides:
            mesh_id:
              value: |
                has(filter_state.upstream_peer) ? filter_state.downstream_peer.mesh_id : upstream_filter_state.downstream_peer.mesh_id
        - match:
            metric: ALL_METRICS
            mode: SERVER
          tagOverrides:
            mesh_id:
              value: filter_state.downstream_peer.mesh_id
      providers:
        - name: prometheus

```
