### ISSUE TITLE
ambient does not always respect WorkloadEntry target port

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#56251]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When I have a `ports` map on WorkloadEntry, it is only respected if I use a _named_ target port on the Service.  I can reproduce by deploying sleep/helloworld from samples, and then using the following yaml. With sidecars, when I select the service entry for routing, traffic (properly) breaks because I send to 9001. zTunnel does not break, because it doesn't respect the port mapping (validated in WDS dump). 

```
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: helloworld-workload
  namespace: default
spec:
  address: "10.244.2.3" # some actual pod ip from one of the helloworld instances
  labels:
    app: helloworld
  ports:
    http: 9001 # this should cause some traffic to break
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  ports:
  - name: http # we're not looking at this
    port: 5000
    protocol: TCP
 
  selector:
    app: helloworld
```

### Version

```Text
latest master
```

### Additional Information

https://github.com/istio/istio/blob/47b2973bacd351bca61daa4e7f313dc389dad407/pilot/pkg/serviceregistry/kube/controller/ambient/services.go#L75

If target port is not a named string, we should fallback to the port name here. 

### Affected product area

- [x] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
