### ISSUE TITLE
`BackendTLSConfig` fails the request with `_Secret_is_not_supplied_by_SDS`

### ISSUE THREAD

**Issue by stevapple** [istio/istio#56277]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When using `BackendTLSConfig` to supply self-signed CA certificates, the backend cannot be connected with the following error:

```
upstream_reset_before_response_started{remote_connection_failure|TLS_error:_Secret_is_not_supplied_by_SDS} - "TLS_error:_Secret_is_not_supplied_by_SDS"
```

Gateway API objects:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: elastic-gateway
  namespace: elastic
spec:
  gatewayClassName: istio
  listeners:
    - name: elasticsearch-https
      port: 9200
      hostname: elastic.kclab.cloud
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: elastic-service-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: elasticsearch-https-route
  namespace: elastic
spec:
  parentRefs:
    - name: elastic-gateway
      sectionName: elasticsearch-https
  rules:
    - backendRefs:
        - name: elasticsearch-es-http
          port: 9200
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: elasticsearch-upstream-tls
  namespace: elastic
spec:
  targetRefs:
    - kind: Service
      name: elasticsearch-es-http
      group: ""
  validation:
    caCertificateRefs:
      - kind: Secret
        name: elasticsearch-es-http-certs-public
        group: ""
    hostname: elasticsearch-es-http.elastic.svc.cluster.local
```

Generated Envoy config (notice that `validation_context_sds_secret_config` is not parsed correctly):

```json
    {
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|9200||elasticsearch-es-http.elastic.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s",
        "resource_api_version": "V3"
       },
       "service_name": "outbound|9200||elasticsearch-es-http.elastic.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "lb_policy": "LEAST_REQUEST",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295,
         "track_remaining": true
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "services": [
          {
           "namespace": "elastic",
           "name": "elasticsearch-es-http",
           "host": "elasticsearch-es-http.elastic.svc.cluster.local"
          }
         ],
         "alpn_override": "false",
         "config": "/apis/networking.istio.io/v1/namespaces/elastic/destination-rule/elasticsearch-es-http-istio-autogenerated-k8s-gateway"
        }
       }
      },
      "common_lb_config": {},
      "alt_stat_name": "outbound|9200||elasticsearch-es-http.elastic.svc.cluster.local;",
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange",
          "enable_discovery": true
         }
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "hbone",
        "match": {
         "tunnel": "http"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.internal_upstream",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.internal_upstream.v3.InternalUpstreamTransport",
          "passthrough_metadata": [
           {
            "kind": {
             "host": {}
            },
            "name": "envoy.filters.listener.original_dst"
           },
           {
            "kind": {
             "cluster": {}
            },
            "name": "istio"
           },
           {
            "kind": {
             "host": {}
            },
            "name": "istio"
           }
          ],
          "transport_socket": {
           "name": "envoy.transport_sockets.tls",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
            "common_tls_context": {
             "tls_params": {
              "tls_minimum_protocol_version": "TLSv1_2",
              "tls_maximum_protocol_version": "TLSv1_3"
             },
             "combined_validation_context": {
              "default_validation_context": {},
              "validation_context_sds_secret_config": {
               "name": "invalid://",
               "sds_config": {
                "ads": {},
                "resource_api_version": "V3"
               }
              }
             }
            },
            "sni": "elasticsearch-es-http.elastic.svc.cluster.local"
           }
          }
         }
        }
       },
       {
        "name": "user",
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "tls_params": {
            "tls_minimum_protocol_version": "TLSv1_2",
            "tls_maximum_protocol_version": "TLSv1_3"
           },
           "combined_validation_context": {
            "default_validation_context": {},
            "validation_context_sds_secret_config": {
             "name": "invalid://",
             "sds_config": {
              "ads": {},
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "elasticsearch-es-http.elastic.svc.cluster.local"
         }
        }
       }
      ]
     },
     "last_updated": "2025-05-12T14:12:56.312Z"
    }
```

### Version

```Text
$ istioctl version
client version: 1.25.1
control plane version: 1.26.0
data plane version: 1.26.0 (11 proxies)
$ kubectl version        
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.28.11
$ helm version --short
v3.17.2+gcc0bbbd
```

### Additional Information

For now I'm using the following `DestinationRule` as a fallback:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: elasticsearch-upstream-tls
  namespace: elastic
spec:
  host: elasticsearch-es-http.elastic.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: elastic/elasticsearch-es-http-certs-public
      sni: elasticsearch-es-http.elastic.svc.cluster.local
```

I had no idea why the `BackendTLSConfig` doesn't work, because it's basically the same thing.
