### ISSUE TITLE
Tracing - cannot deliver traces to Alloy OTEL Collector

### ISSUE THREAD

**Issue by Ayatallah** [istio/istio#56278]
I'm new to Istio & tried to enable tracing and set tracing provider to Alloy (Distribution of OpenTelemetry Collector) but Alloy is not receiving traces. 

with the below configs:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: '1.25.0'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  values:
    meshConfig:
      enableTracing: true
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: alloy.alloy.svc.cluster.local
            resourceDetectors:
              environment: {}
```
& Telemetry 
```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100.00
```

Here is istio bug report https://github.com/Ayatallah/Istio-test/blob/main/bug-report-21-55-48-674.zip

**Comment by Ayatallah** [comment]
Meanwhile, when Opentelemetry is deployed with below config:
```
    config:
      exporters:
        debug:
          verbosity: detailed
        otlp:
          endpoint: "alloy.alloy.svc.cluster.local:4317"
          tls:
            insecure: true
```

& Istio Tracing provider is changed to opentelemetry instead as below:
```
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: opentelemetry-collector.opentelemetry.svc.cluster.local
            resourceDetectors:
              environment: {}
```

The traces are received successfully by opentelemetry & exported successfully by opentelemetry and gets received successfully by Alloy. 

Does this mean Istio does not support having Alloy distribution as the tracing provider? Or there's warning/error in the bug report that I missed?
