### ISSUE TITLE
Unable to apply patch to service

### ISSUE THREAD

**Issue by alexander-kauerz-at-adesso** [istio/istio#56299]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Trying to install a gateway from the samples with customazations according to the [documentation](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment) to attach the service to a specific loadbalancer (elb):

``` yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gw-options
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
data:
  service: |
    annotations:
      kubernetes.io/elb.id: redacted # Replace it with the ID of your existing load balancer.
      kubernetes.io/elb.ip: redacted # Replace it with the IP of your existing load balancer.
      kubernetes.io/elb.class: union  # Load balancer type
```

My apply works, but the service is not created and istiod states the following error:

`2025-05-14T11:28:21.624645Z    error    controllers    error handling instio-bookinfo-test/bookinfo-gateway, and retry budget exceeded: apply failed: patch /v1, Kind=Service/instio-bookinfo-test/bookinfo-gateway-istio: failed to create typed patch object (instio-bookinfo-test/bookinfo-gateway-istio; /v1, Kind=Service): .annotations: field not declared in schema    controller=gateway deployment`

When I remove the annotations the service is created.
Since I do not get more information from istiod I do not know what is wrong with the service.

### Version

```Text
➜ ./istioctl version
client version: 1.26.0
control plane version: 1.26.0
data plane version: 1.26.0 (3 proxies)
➜ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.30.4-r0-30.0.14.9
```

### Additional Information

_Sorry, the bug-report is including way to much information about the product running in this cluster_

**Comment by sridhargaddam** [comment]
You'll have to update the ConfigMap and move `annotations` under `metadata` as shown below.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
data:
  service: |
    metadata:
      annotations:
        kubernetes.io/elb.id: redacted # Replace it with the ID of your existing load balancer.
        kubernetes.io/elb.ip: redacted # Replace it with the IP of your existing load balancer.
        kubernetes.io/elb.class: union # Load balancer type
```
