### ISSUE TITLE
EnvoyFilter For enabling keep alive probes in Istio Gateway doesn't work after upgrading from 1.19.3 to 1.22.8

### ISSUE THREAD

**Issue by medalliadx** [istio/istio#56307]
Hi Team, 

We are using the following EnvoyFilter configuration in our istio ingress gateway proxies to prevent long-lived connections to be dropped by our load balancer:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-gateway-downstream-tcp-keep-alive
spec:
  configPatches:
    - applyTo: LISTENER
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          socket_options:
            - description: "Enable keep-alive" # Socket level options.
              int_value: 1 # A nonzero value means "yes".
              level: 1 # Means socket level options.
              name: 9 # Means the keep-alive parameter.
              state: STATE_PREBIND
            - description: "Idle time before first keep-alive probe is sent" # TCP protocol
              int_value: 60 # Seconds
              level: 6 # IPPROTO_TCP
              name: 4 # TCP_KEEPIDLE parameter - The time (in seconds) the connection needs to remain idle before TCP starts sending keepalive probes.
              state: STATE_PREBIND
            - description: "Keep-alive interval" # TCP protocol
              int_value: 20 # Seconds
              level: 6 # IPPROTO_TCP
              name: 5 # The TCP_KEEPINTVL parameter - The time (in seconds) between individual keepalive probes.
              state: STATE_PREBIND
            - description: "Keep-alive probes count"
              int_value: 3 # Number of failed probes.
              level: 6 # IPPROTO_TCP
              name: 6 # The TCP_KEEPCNT parameter - The maximum number of keepalive probes TCP should send before dropping the connection.
              state: STATE_PREBIND
```

We have recently upgraded istio from 1.19.3 to 1.22.8 and we discovered that the configuration is not being applied anymore into the istio ingress gateway proxies. Here's the proxy-config output in both cases:

With istio 1.19.3:

```
> istioctl proxy-config listeners istio-ingress-7cdfffd944-mdf2p.istio-ingress --port 443 -o json | jq '.[0].socketOptions'
[
  {
    "description": "Enable keep-alive",
    "level": "1",
    "name": "9",
    "intValue": "1"
  },
  {
    "description": "Idle time before first keep-alive probe is sent",
    "level": "6",
    "name": "4",
    "intValue": "60"
  },
  {
    "description": "Keep-alive interval",
    "level": "6",
    "name": "5",
    "intValue": "20"
  },
  {
    "description": "Keep-alive probes count",
    "level": "6",
    "name": "6",
    "intValue": "3"
  }
]
```

With istio 1.22.8:

```
istioctl proxy-config listeners istio-ingress-6f784b546-47j8f.istio-ingress --port 443 -o json | jq '.[0].socketOptions'
null
```

Can you please please help me with this issue? 
Many thanks, Marcelo

**Comment by zirain** [comment]
it worked as expected on `1.25.2`
```
istioctl pc l -n istio-system istio-ingressgateway-67569c4d74-krrcf --port 8080 -oyaml | grep socketOptions -A 10
  socketOptions:
  - description: Enable keep-alive
    intValue: "1"
    level: "1"
    name: "9"
  - description: Idle time before first keep-alive probe is sent
    intValue: "60"
    level: "6"
    name: "4"
  - description: Keep-alive interval
    intValue: "20"
```
