### ISSUE TITLE
Helm: Expose `maxUnavailable` and `unhealthyPodEvictionPolicy` for Istiod PodDisruptionBudget

### ISSUE THREAD

**Issue by kevin-shelaga** [istio/istio#56327]
**Describe the feature request**

The Istio Helm chart for `istiod` currently hardcodes `minAvailable: 1` for its PodDisruptionBudget (PDB) and does not provide Helm values to configure `spec.maxUnavailable` or `spec.unhealthyPodEvictionPolicy`. This feature request proposes exposing Helm values to allow users to set these PDB fields for more flexible and robust `istiod` deployment configurations, particularly in multi-replica setups.

*How this feature will improve Istio:*
This feature will provide users with more granular control over the `istiod` PDB settings, enabling configurations that can better prevent disruptions during voluntary maintenance (e.g., node drains, upgrades) or when dealing with unhealthy pods. Specifically:
* Exposing `maxUnavailable` allows users with multiple `istiod` replicas (e.g., >=2) to explicitly ensure only one `istiod` instance becomes unavailable at a time during voluntary disruptions. This can be more intuitive and direct than `minAvailable: 1` in certain scenarios.
* Exposing `unhealthyPodEvictionPolicy` (e.g., to `AlwaysAllow`) would allow users to ensure that unhealthy `istiod` pods can be evicted and rescheduled promptly, contributing to faster recovery of the control plane.

*Current Behavior:*
Currently, the Istio Helm chart for `istiod` conditionally creates a PodDisruptionBudget with `spec.minAvailable: 1` hardcoded when `.Values.global.defaultPodDisruptionBudget.enabled` is true. There is no direct Helm value exposed to use `spec.maxUnavailable` instead, nor is there a value to configure `spec.unhealthyPodEvictionPolicy`.

The relevant part of the current Helm template (`templates/istiod-pdb.yaml`) is:
```yaml
{{- if not .Values.istiodRemote.enabled }}
{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    istio.io/rev: {{ .Values.revision | default "default" | quote }}
    install.operator.istio.io/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.istio.io/component: "Pilot"
    release: {{ .Release.Name }}
    istio: pilot
    app.kubernetes.io/name: "istiod"
    {{- include "istio.labels" . | nindent 4 }}
spec:
  minAvailable: 1 # <-- Hardcoded
  selector:
    matchLabels:
      app: istiod
      {{- if ne .Values.revision "" }}
      istio.io/rev: {{ .Values.revision | quote }}
      {{- else }}
      istio: pilot
      {{- end }}
---
{{- end }}
{{- end }}
```

Desired Behavior:
The Istio Helm chart for istiod should expose new Helm values to allow users to:

Optionally use spec.maxUnavailable instead of spec.minAvailable for the istiod PDB. For example, a new value like values.pilot.pdb.maxUnavailable. If both minAvailable and maxUnavailable are specified by the user in Helm values for the PDB, the chart could prioritize one (e.g., maxUnavailable) or produce a Helm template error.

Configure spec.unhealthyPodEvictionPolicy for the istiod PDB. For example, a new value like values.pilot.pdb.unhealthyPodEvictionPolicy.

Example desired configuration via Helm values:

**values.yaml**
```yaml
pilot:
  pdb:
    # To use maxUnavailable instead of minAvailable (if set, minAvailable in the template would be omitted)
    maxUnavailable: 1
    # To set the eviction policy (this field would be added to the PDB spec)
    unhealthyPodEvictionPolicy: AlwaysAllow
    # Potentially, to keep the existing minAvailable configurable if maxUnavailable is not set:
    # minAvailable: 1 # (though this is already the default behavior if enabled)
```

This would then render the PDB manifest with these user-specified values if provided. If pilot.pdb.maxUnavailable is set, the minAvailable field in the PDB spec should be omitted. If pilot.pdb.unhealthyPodEvictionPolicy is set, it should be included in the PDB spec.

*Describe alternatives you've considered*

Manually editing the PDB post-installation: This is not a sustainable solution as it deviates from the Helm-managed configuration, and changes can be overwritten during Helm upgrades or GitOps syncs.

Forking the Helm chart: This introduces a significant maintenance burden for users who need this specific customization.

Affected product area (please put an X in all that apply)

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Affected features (please put an X in all that apply)

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

*Additional context*

Severity: Medium/High (as it impacts control plane stability during disruptions).

Version Context: Observed as a need in Istio 1.26

Affected Components: istiod, Helm charts, PodDisruptionBudget (PDB).
