### ISSUE TITLE
Preserve HTTP1 Header Case

### ISSUE THREAD

**Issue by alapati96** [istio/istio#56362]
Hi, I wanted to have the same header case as my that of my upstream. I was referring to https://github.com/istio/istio/pull/53887, but still I see this is not working, can someone help me out on if I am configuring it properly.

My EnvoyFilter:
`apiVersion: networking.istio.io/v1alpha3`
`kind: EnvoyFilter`
`metadata:`
`  name: lua-envoy-filter`
`  namespace: istio-system`
`spec:`
`  workloadSelector:`
`    labels:`
`      istio: ingressgateway`
`  configPatches:`
`    - applyTo: NETWORK_FILTER`
`      match:`
`        context: ANY # Use SIDECAR_INBOUND or SIDECAR_OUTBOUND for sidecars`
`        listener:`
`          filterChain:`
`            filter:`
`              name: envoy.filters.network.http_connection_manager`
`      patch:`
`        operation: MERGE`
`        value:`
`          typed_config:`
`            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager`
`            codec_type: AUTO`
`            http2_protocol_options:`
`              allow_connect: true # Enable Upgrade: h2c for plaintext HTTP/2`
`            http_protocol_options:`
`              header_key_format:`
`                  stateful_formatter:`
`                    name: preserve_case`
`                    typed_config:`
`                      "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig`

**Comment by keithmattix** [comment]
You can use https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-ProxyHeaders-preserve_http1_header_case in ProxyConfig

**Comment by alapati96** [comment]
This isn't part of EnvoyFilter ?

**Comment by alapati96** [comment]
Also, how to configure this, can you please give me an example. I see the examples showing it to use with IstioOperator, the support of the same was removed, if I am correct.

**Comment by alapati96** [comment]
I have gone through few links and configured meshConfig and when I described, I am getting it like this:

kubectl describe configmap istio-configmap -n istio-system
Name:         istio-configmap
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>

Data
====
mesh:
----
meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    proxyHeaders:
      perserveHttp1HeaderCase: true

BinaryData
====

Events:  <none>

I see with this as well, I am unable to get the actual case of the headers, is this correct ?

**Comment by keithmattix** [comment]
Make sure to restart the proxies, and ensure the protocol is http on the services

**Comment by alapati96** [comment]
Yes, I have restarted the proxies and also protocol is http, still I see the lowercase headers :(

**Comment by keithmattix** [comment]
Did you remove the envoyfilter?

**Comment by alapati96** [comment]
Tried with and without envoyfilter

**Comment by keithmattix** [comment]
You definitely don't want to use EnvoyFilter and this annotation. Also, are you sure your downstream and upstream are both using HTTP 1? If anything is using http/2, you're going to have your headers lowercased by the spec

**Comment by alapati96** [comment]
Yes, both my upstream and downstream are using http 1. Just to be sure, how can I confirm the same ?

**Comment by keithmattix** [comment]
Turn on debug or trace access logs in your envoy sidecars and they should show the http version of the traffic

**Comment by alapati96** [comment]
request_handle:streamInfo():protocol() is showing me as HTTP/1.1, but still I see lower case response headers

**Comment by keithmattix** [comment]
Oh so you're using a Lua filter as well! Can you send the EnvoyFilter you're using to utilize Lua?

**Comment by alapati96** [comment]
Here it is:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-envoy-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            defaultSourceCode:
              inlineString: |
                function envoy_on_request(request_handle)
                    local request_headers = request_handle:headers()

                    local request_headers_map = {}
                    for k, v in pairs(request_headers) do
                      request_headers_map[k] = v
                    end

                    local headers, resp_body = request_handle:httpCall(
                      "my-upstream",
                      request_headers_map,
                      "",
                      5000
                    )
 
                    local response_headers = {}
                    for k, v in pairs(headers) do
                        response_headers[k] = v
                    end

                    request_handle:respond(response_headers, "")
                end
 
                function envoy_on_response(response_handle)
                end
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value:
          name: my-upstream
          type: STATIC
          connect_timeout: 5s
          load_assignment:
            cluster_name: my-upstream
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        pipe:
                          path: /var/my-service.sock
```

**Comment by keithmattix** [comment]
Hmm nothing is standing out to me; will have to find time or someone else to investigate

**Comment by alapati96** [comment]
okay...

**Comment by tjccwccwcc** [comment]
**1. I found that the example of proxyHeaders in the document uses:**

https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-proxy_headers
```
  proxyHeaders:
    perserveHttp1HeaderCase: true
```

But the parameter in the ProxyHeaders section says:`preserveHttp1HeaderCase`
https://istio.io/v1.25/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-ProxyHeaders-preserve_http1_header_case

I don’t know which one to use
- **per**serveHttp1HeaderCase
or
- **pre**serveHttp1HeaderCase

**2. Acctual testing found that if use `perserveHttp1HeaderCase: true`, this function does not take effect**
```
curl -H "My-Header: value1" -H "MY-HEADER: value2" http://httpbin-service.sample.svc.cluster.local:80/headers
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin-service.sample.svc.cluster.local", 
    "My-Header": "value1,value2", 
    "User-Agent": "curl/7.88.1", 
    "X-B3-Parentspanid": "69c5e090a7b75277", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "ef717aa9a82a7906", 
    "X-B3-Traceid": "0f615c43544509df69c5e090a7b75277", 
    "X-Envoy-Attempt-Count": "1"
  }
}
```

**3. If use `preserveHttp1HeaderCase: true`, istio-proxy will report an error when starting:**
```
2025-06-05T09:20:01.478769Z	info	Envoy command: [-c etc/istio/proxy/envoy-rev.json --drain-time-s 45 --drain-strategy immediate --local-address-ip-version v4 --file-flush-interval-msec 1000 --disable-hot-restart --allow-unknown-static-fields -l warning --component-log-level misc:error --skip-deprecated-logs --concurrency 2]
2025-06-05T09:20:01.591315Z	warning	envoy main external/envoy/source/server/server.cc:863	Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.global_downstream_max_connections` instead.This runtime key will be removed in future.	thread=13
2025-06-05T09:20:01.591898Z	warning	envoy main external/envoy/source/server/server.cc:959	There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.global_downstream_max_connections` resource monitor.	thread=13
2025-06-05T09:20:01.621593Z	info	cache	generated new workload certificate	resourceName=default latency=148.153559ms ttl=23h59m59.378409847s
2025-06-05T09:20:01.621757Z	info	cache	Root cert has changed, start rotating root cert
2025-06-05T09:20:01.621833Z	info	cache	returned workload trust anchor from cache	ttl=23h59m59.378168669s
2025-06-05T09:20:53.450692Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:226	DeltaAggregatedResources gRPC config stream to xds-grpc closed since 51s ago: 14, connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc on 172.27.0.10:53: no such host"	thread=13
2025-06-05T09:20:55.617523Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:226	DeltaAggregatedResources gRPC config stream to xds-grpc closed since 54s ago: 14, connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc on 172.27.0.10:53: no such host"	thread=13
2025-06-05T09:21:01.943490Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:226	DeltaAggregatedResources gRPC config stream to xds-grpc closed since 60s ago: 14, connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc on 172.27.0.10:53: no such host"	thread=13
2025-06-05T09:21:11.828458Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:226	DeltaAggregatedResources gRPC config stream to xds-grpc closed since 70s ago: 14, connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc on 172.27.0.10:53: no such host"	thread=13
```
Istio-proxy can only run normally after I delete the configuration of `preserveHttp1HeaderCase`

**Comment by zirain** [comment]
it's `preserveHttp1HeaderCase `, https://github.com/istio/api/pull/3511 will fixed it.

```
Error while dialing: dial tcp: lookup istiod.istio-system.svc on 172.27.0.10:53: no such host
```

this's more like a underlying network issue.

**Comment by tjccwccwcc** [comment]
I found the reason. I set the `revision` to 1-25-3, so the service of istiod is **istiod-1-25-3.istio-system.svc:15012**. 

1. When I added defaultConfig.proxyHeaders.preserveHttp1HeaderCase to the ConfigMap of istio-1-25-3, I added it incorrectly. 
```
    defaultConfig:
      discoveryAddress: istiod-1-25-3.istio-system.svc:15012
      envoyAccessLogService:
        address: istio-accesslog-receiver-use1.istio-accesslog-receiver.svc:9001
      holdApplicationUntilProxyStarts: false
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: "true"
        GRPC_ENFORCE_ALPN_ENABLED: "false"
        PROXY_CONFIG_XDS_AGENT: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
      proxyHeaders:
        preserveHttp1HeaderCase: "true"
```
I set values ​​to a string, **such as "true"**. This caused the istio-proxy configuration to be read abnormally. 
```
2025-06-06T01:41:44.124624Z	info	Apply proxy config from annotation holdApplicationUntilProxyStarts: true
proxyMetadata:
  ISTIO_META_DNS_CAPTURE: "true"
  ISTIO_META_DNS_AUTO_ALLOCATE: "false"
2025-06-06T01:41:44.124747Z	info	cpu limit detected as 2, setting concurrency
2025-06-06T01:41:44.125037Z	info	Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
holdApplicationUntilProxyStarts: true
proxyAdminPort: 15000
proxyMetadata:
  ISTIO_META_DNS_AUTO_ALLOCATE: "false"
  ISTIO_META_DNS_CAPTURE: "true"
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
```

2. After changing it to bool type true, istio-proxy can run normally.
```
    defaultConfig:
      discoveryAddress: istiod-1-25-3.istio-system.svc:15012
      envoyAccessLogService:
        address: istio-accesslog-receiver-use1.istio-accesslog-receiver.svc:9001
      holdApplicationUntilProxyStarts: false
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: "true"
        GRPC_ENFORCE_ALPN_ENABLED: "false"
        PROXY_CONFIG_XDS_AGENT: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
      proxyHeaders:
        preserveHttp1HeaderCase: true
```
istio-proxy log now is normal
```
2025-06-06T01:34:52.302645Z	info	Apply proxy config from annotation holdApplicationUntilProxyStarts: true
proxyMetadata:
  ISTIO_META_DNS_CAPTURE: "true"
  ISTIO_META_DNS_AUTO_ALLOCATE: "false"
2025-06-06T01:34:52.302757Z	info	cpu limit detected as 2, setting concurrency
2025-06-06T01:34:52.303142Z	info	Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod-1-25-3.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService:
  address: istio-accesslog-receiver-use1.istio-accesslog-receiver.svc:9001
holdApplicationUntilProxyStarts: true
meshId: dev-use1-istio-test
proxyAdminPort: 15000
proxyHeaders:
  preserveHttp1HeaderCase: true
proxyMetadata:
  EXIT_ON_ZERO_ACTIVE_CONNECTIONS: "true"
  GRPC_ENFORCE_ALPN_ENABLED: "false"
  ISTIO_META_DNS_AUTO_ALLOCATE: "false"
  ISTIO_META_DNS_CAPTURE: "true"
  PROXY_CONFIG_XDS_AGENT: "true"
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411
```
but **preserveHttp1HeaderCase: true** does not take effect，HTTP/1.x headers is not preserved
```
curl -H "My-Header: value1" -H "MY-HEADER: value2" http://httpbin-service.sample.svc.cluster.local:80/headers
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin-service.sample.svc.cluster.local", 
    "My-Header": "value1,value2", 
    "User-Agent": "curl/7.88.1", 
    "X-B3-Parentspanid": "ee484239cf215e3c", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "59eea48980e2e0bc", 
    "X-B3-Traceid": "c57b2ab1282b6f2aee484239cf215e3c", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/sample/sa/default;Hash=941c14ea9bd489a924dda92d0c49e29ff69fa2ba527dc162e834703b22906d97;Subject=\"\";URI=spiffe://cluster.local/ns/sample/sa/default"
  }
}
```
client is nginx，server is httpbin
client accesslog
```
[2025-06-06T01:43:44.333Z] "GET /headers HTTP/1.1" 200 - via_upstream - "-" 0 586 11 10 "-" "curl/7.88.1" "2e0caf3c-d50d-4d88-9ad1-70ec3cd2fd9e" "httpbin-service.sample.svc.cluster.local" "[server pod ip]:80" outbound|80||httpbin-service.sample.svc.cluster.local [client pod ip]:59690 [server service ip]:80 [client pod ip]:34426 - default
```
server accesslog
```
[2025-06-06T01:43:44.338Z] "GET /headers HTTP/1.1" 200 - via_upstream - "-" 0 586 2 1 "-" "curl/7.88.1" "2e0caf3c-d50d-4d88-9ad1-70ec3cd2fd9e" "httpbin-service.sample.svc.cluster.local" "[server pod ip]:80" inbound|80|| 127.0.0.6:39545 [server pod ip]:80 [client pod ip]:59690 outbound_.80_._.httpbin-service.sample.svc.cluster.local default
```
server service
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: tls
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: httpbin-test
  type: ClusterIP
```

**Comment by keithmattix** [comment]
The fact that the header is not all lower case means the field is working as intended. HTTP 1.1 headers are case insensitive and you declared different values for My-Header|MY-HEADER so the value was interpreted as a list per the spec. This is working as intended

**Comment by zirain** [comment]
You should test it with a simple backend:
```golang
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net"

	"github.com/valyala/fasthttp"
)

func HandleFastHTTP(ctx *fasthttp.RequestCtx) {
	ctx.QueryArgs().VisitAll(func(key, value []byte) {
		if string(key) == "headers" {
			ctx.Response.Header.Add(string(value), "PrEsEnT")
		}
	})
	headers := map[string][]string{}
	ctx.Request.Header.VisitAll(func(key, value []byte) {
		headers[string(key)] = append(headers[string(key)], string(value))
	})
	if d, err := json.MarshalIndent(headers, "", "  "); err != nil {
		ctx.Error(fmt.Sprintf("%s", err), fasthttp.StatusBadRequest)
	} else {
		fmt.Fprintf(ctx, string(d)+"\n")
	}
}

func main() {
	s := fasthttp.Server{
		Handler:                       HandleFastHTTP,
		DisableHeaderNamesNormalizing: true,
	}
	log.Printf("Starting on port 8000")
	l, _ := net.Listen("tcp", ":8000")
	log.Fatal(s.Serve(l))
}
```

**Comment by tjccwccwcc** [comment]
@zirain @keithmattix Thank you for your response and clarification. the results are now as expected.
```
curl -H "MY-HEADER: value2" http://http-test-svc.sample.svc.cluster.local:8000/headers
{
  "Accept": [
    "*/*"
  ],
  "Host": [
    "http-test-svc.sample.svc.cluster.local:8000"
  ],
  "MY-HEADER": [
    "value2"
  ],
  "User-Agent": [
    "curl/7.88.1"
  ],
  "x-b3-parentspanid": [
    "246802147a91f72a"
  ],
  "x-b3-sampled": [
    "0"
  ],
  "x-b3-spanid": [
    "c655da7a6cfe19cc"
  ],
  "x-b3-traceid": [
    "1b157bc0e1518ef3246802147a91f72a"
  ],
  "x-envoy-attempt-count": [
    "1"
  ],
  "x-forwarded-client-cert": [
    "By=spiffe://cluster.local/ns/sample/sa/default;Hash=568709c2379b648bff2b187d70548040659350de2785a7e55cabf86f492bb155;Subject=\"\";URI=spiffe://cluster.local/ns/sample/sa/default"
  ],
  "x-forwarded-proto": [
    "http"
  ],
  "x-request-id": [
    "f0bfd06f-2200-4add-9e1d-2e0d3a1eacc6"
  ]
}
```
```
curl -H "My-Header: value1" -H "MY-HEADER: value2" http://http-test-svc.sample.svc.cluster.local:8000/headers
{
  "Accept": [
    "*/*"
  ],
  "Host": [
    "http-test-svc.sample.svc.cluster.local:8000"
  ],
  "My-Header": [
    "value1",
    "value2"
  ],
  "User-Agent": [
    "curl/7.88.1"
  ],
  "x-b3-parentspanid": [
    "cdd0584984fcd0f2"
  ],
  "x-b3-sampled": [
    "0"
  ],
  "x-b3-spanid": [
    "469f7e5f525a06b7"
  ],
  "x-b3-traceid": [
    "b5bbd2c38494aa5acdd0584984fcd0f2"
  ],
  "x-envoy-attempt-count": [
    "1"
  ],
  "x-forwarded-client-cert": [
    "By=spiffe://cluster.local/ns/sample/sa/default;Hash=568709c2379b648bff2b187d70548040659350de2785a7e55cabf86f492bb155;Subject=\"\";URI=spiffe://cluster.local/ns/sample/sa/default"
  ],
  "x-forwarded-proto": [
    "http"
  ],
  "x-request-id": [
    "06f39880-17e2-49b0-91c4-777c995d8868"
  ]
}
```

**Comment by alapati96** [comment]
@tjccwccwcc, how did you actually configured it, I still see it isn't working in my case.

This is what I have tried..
`kubectl edit configmap istio -n istio-system`

and added the below:

```
  defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyHeaders:
        preserveHttp1HeaderCase: true
```

**Comment by zirain** [comment]
you  need to restart the injected pod.

**Comment by alapati96** [comment]
Did that as well, but not working :(

**Comment by zirain** [comment]
1. please check the log from istiod, anything abnormal?
2. please verify the configuration with following command:
```console
istioctl pc l -n <pod_namespace> <pod_name> -oyaml | grep PreserveCaseFormatterConfig
```

**Comment by tjccwccwcc** [comment]
@alapati96 my istio configmap：
```
apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: ""
    defaultConfig:
      discoveryAddress: istiod-1-25-3.istio-system.svc:15012
      holdApplicationUntilProxyStarts: false
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
      gatewayTopology:
        proxyProtocol: {}
      proxyHeaders:
        preserveHttp1HeaderCase: true
    defaultProviders:
      metrics:
      - prometheus
    discoverySelectors:
    - matchExpressions:
      - key: istio-discovery
        operator: NotIn
        values:
        - disabled
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.25.3
    helm.sh/chart: istiod-1.25.3
    helm.toolkit.fluxcd.io/name: istiod
    helm.toolkit.fluxcd.io/namespace: istio-system
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: 1-25-3
    operator.istio.io/component: Pilot
    release: istiod
  name: istio-1-25-3
  namespace: istio-system
```
maybe you can check you istio-proxy log
`kubectl logs nginx-test-77875d8874-44f2g -n sample -c istio-proxy`

Check if the configuration preserveHttp1HeaderCase: true is in the istio-proxy logs：
```
2025-06-09T09:52:57.030827Z     info    cpu limit detected as 2, setting concurrency
2025-06-09T09:52:57.035801Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod-1-25-3.istio-system.svc:15012
drainDuration: 45s
gatewayTopology:
  proxyProtocol: {}
holdApplicationUntilProxyStarts: true
proxyAdminPort: 15000
proxyHeaders:
  preserveHttp1HeaderCase: true
proxyMetadata:
  ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  ISTIO_META_DNS_CAPTURE: "true"
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2025-06-09T09:52:57.035818Z     info    JWT policy is third-party-jwt
2025-06-09T09:52:57.035823Z     info    using credential fetcher of JWT type in cluster.local trust domain
```
