### ISSUE TITLE
Add Source/Destination SPIFFE principal to ExtAuthz input using waypoint

### ISSUE THREAD

**Issue by remeric** [istio/istio#56379]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

When setting the mesh config to use envoyExtAuthzGrpc to make authorization decisions to Open Policy Agent, the input is missing the SPIFFE source and destination principals when switching to use the waypoint for L7 authorization.  Previously we were using the envoy sidecar in the application, and this information was available in the input passed to OPA via input.attributes.destination.principal and input.attributes.source.principal.  We are deploying OPA as a sidecar to the waypoint deployment - we have successfully been able to use it this way for decisions, just unable to use the SPIFFE identities, or any other way to identify source and destination within the cluster to use in our authorization decisions.

**Describe alternatives you've considered**

I attempted to use an envoy filter to inject headers, possibly being able to grab this information and inject it, but as far as I can tell envoy filters are not working or supported for ambient waypoint.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ilrudie** [comment]
I don't know for sure, I think routing is the last thing in the waypoints' filters so would come after authz. I could be wrong though, its worth taking a look

**Comment by keithmattix** [comment]
Yeah ext authz I think can technically change the destination, so that wouldn't be available.

**Comment by keithmattix** [comment]
Ext-authz filter allows passing the peer certificate to the ext auth service so it's possible in theory. Not sure if we set this friend or not in istio

**Comment by tjons** [comment]
@keithmattix we don't set it today, but it's an easy change. Should have something pushed up next week.

**Comment by remeric** [comment]
Been giving some thought to the destination today again - is it possible to grab the x-forwarded-client-cert at some point in the chain and send it on to external auth in waypoint mode?  The Peer cert will give us source, and the destination we can grab from the :authority header, but the XFCC does seem to capture both source and destination and in our situation would be a more reliable way to identify destination rather than using the :authority header.

**Comment by comigor** [comment]
hey @remeric, @keithmattix, how are you doing?
do we have a workaround for this on Ambient mode?

**Comment by tjons** [comment]
@comigor this is still regretfully in my backlog. Will try to prioritize it in the next week or two.

**Comment by comigor** [comment]
@tjons if you give me some pointers/overall directions on this I can take a look at implementing it! we've migrated to ambient mode and this feature is really important for us. or, of course, if I can help in any other way.

**Comment by comigor** [comment]
In the meantime, we were able to install an EnvoyFilter that injects the SPIFFE principals as headers:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: principal-injector
  namespace: apps
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: waypoint
  priority: 10
  configPatches:
    - applyTo: HTTP_FILTER
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                local fs = request_handle:streamInfo():filterState()
                if not fs then return end

                request_handle:headers():add("x-peer-principal", fs:get("io.istio.peer_principal"))
                request_handle:headers():add("x-local-principal", fs:get("io.istio.local_principal"))
              end
```
