### ISSUE TITLE
Support "Pod Security Admission" for Istio Waypoint

### ISSUE THREAD

**Issue by psiservices-guywatson** [istio/istio#56383]
**Describe the feature request**
The following Gateway definition:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: istio-waypoint
  namespace: example
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
```

Causes automatic generation of an Istio Waypoint deployment.

The pod fails to schedule due to a Pod Security Admission error:
```
    message: 'pods "example-75658ccc49-w6nxf" is
      forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or
      container "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault"
      or "Localhost")'
```

Because the deployment definition, section "securityContext", is missing this:
```
      spec:
        securityContext:
          seccompProfile:
            type: "RuntimeDefault"
```

The section "securityContext" contains this:
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
```

Request: Add the missing entry to the automatic resource generation.

**Describe alternatives you've considered**
- When the missing entry is added manually, the Waypoint appears to work normally.

- Disabling automatic resource generation and using manually created resources works; but relies on the definition of the "Waypoint" resource never changing, since there is no documentation point of reference for how it should be defined.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
References:
https://kubernetes.io/docs/concepts/security/pod-security-admission/
https://istio.io/latest/docs/ambient/usage/waypoint/

**Comment by howardjohn** [comment]
This is possible in 1.26 via https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment.
In the past we have avoided setting this as default because RuntimeDefault means "literally anything the platform wants" which could be incompatible

**Comment by psiservices-guywatson** [comment]
Here's an example for others to reference:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: istio-waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-waypoint
  namespace: default
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            securityContext:
              seccompProfile:
                type: "RuntimeDefault"
```
