### ISSUE TITLE
Configuring idle_timeout and HTTP/2 via ALPN for Egress Gateways with TLS Origination

### ISSUE THREAD

**Issue by kaiburjack** [istio/istio#56393]
**Describe the feature request**

Currently, when using an [Egress Gateway for TLS Origination](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/) the effective configuration of the Envoy upstream cluster towards the external domain/service is going to be:

- no ALPN-based HTTP/1.1 or HTTP/2 protocol selection but _only_ HTTP/1.1
- idle_timeout default of **1h** meaning that we are susceptible to a 503 when the upstream host closes the connection exactly when the Egress Gateway sends a new HTTP request

What I would like to do is:
- being able to configure the cluster HTTP idle_timeout to be compatible with what the upstream domain server uses
- being able to use ALPN-based protocol selection towards the upstream server, such that Envoy preferably chooses HTTP/2

**Describe alternatives you've considered**

I _was_ able to configure an upstream cluster idle_timeout via an EnvoyFilter like so:
```yaml
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        portNumber: 443
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 10s
            explicit_http_config:
              http_protocol_options: {}
  workloadSelector:
    labels:
      app: istio-egressgateway
      istio: egressgateway
```
However, I needed to use `explicit_http_config` to tell that either HTTP/1.1 or HTTP/2 is used statically. What I would like to achieve is to use ALPN-based protocol selection, which _would_ be possible since I was using TLS Origination in the egress gateway and the upstream cluster does have a TLS transport socket.

However, using`auto_config` instead of `explicit_http_config` does _not_ work (i.e. the egress gateway health check does not become ready).

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
