### ISSUE TITLE
namespace to namespace routing through istio ingressgateway is not working

### ISSUE THREAD

**Issue by sambitr** [istio/istio#56436]
Hi There,

I am trying to route traffic from one namespace namespace1 to another namespace: namespace 2 through istio-system/istio-ingressgateway. This is to test the proxy configuration setup. Both the namespaces are in same cluster.

Here is what I have done:

namespace 1:

added a service entry to use the istio-system namespace's ingress gateway LB IP

```
apiVersion: networking.istio.io/v1beta1  
kind: ServiceEntry  
metadata:  
  name: app-proxy 
  namespace: ns1
spec:  
  hosts:  
  - dummy.northeurope.atrema.com  # This isn't used as it is a static rule
  addresses:  
  - 10.111.212.71  # Replace with the actual IP address of the external service  
  ports:  
  - number: 443  
    name: https  
    protocol: HTTPS  
  location: MESH_EXTERNAL  
  resolution: STATIC  
  endpoints:  
  - address: 10.111.212.71  # Replace with the actual IP address of the external service   
```  

Updated the code to call the application deployed in namespace 2 as: 
https://10.111.212.71/ns2/app/api/

The namespace 2 has virtualservice configured for this and uses istio-syste/istio-ingressgateway 

```
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /ns2/app/api/
    route:
    - destination:
        host: app-api
        port:
          number: 80
    timeout: 30s
  - match:
    - uri:
        prefix: /ns2/app/swagger
    route:
    - destination:
        host: app-api
        port:
          number: 80
    timeout: 30s

```

This is the gateway details:

```
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

**Problem:** The issue I am facing is: the application deployed in ns2 requires a service account token so that it can be authenticated.

I can see the traffic hitting the api component of the application in the namespace2, but then gets 403 forbidden error complaining about authorization.

basically, the service auth token is getting scrapped somewhere in the communication process.

```
            var identity = _identityService.Identity;
            if(identity.IsServiceAccount)
            {
                isAuthorized = true;
            }
            else
            {
                var user = await _mediator.Send(new GetUserIdentityQuery(identity.Email));

                if (user != null)
                {
                    isAuthorized = await _authorizationService.IsAdministratorAsync(identity);
                    if (!isAuthorized)
                    {
                        Logger.LogWarning("User not an Administrator: {user}", user.Email);
                    }
                }
            }
```

At the same time, I see in the ingress gateway logs as:

[2025-05-28T11:37:15.492Z] "POST /ns2/app/api/input-templates/batch?applicationId=e81861da-db98-4085-ad34-0efdc13c6a4c HTTP/1.1" **403** - via_upstream - "-" 92146 0 15 - "10.111.212.21" "-" "d70ced77-f264-491a-a522-b54c949fa68e" "10.111.212.71" "172.0.7.123:8080" outbound|80||app-api.sds.svc.cluster.local 172.0.9.104:49044 172.0.9.104:8443 10.111.212.21:38652 - -

Is there a way to preserve that token when the in-cluster communication happens through Istio ingressgateway?
