### ISSUE TITLE
【Help】istio Multi-Cluster - Multi-Control Plane Configuration Problem for Non-flat Networks

### ISSUE THREAD

**Issue by cscowx** [istio/istio#56450]
Hello everyone, can you help me look at this problem? Puzzled me for a long time, not solved.
Thanks again!

《istio Multi-Cluster - Multi-Control Plane Configuration Problem for Non-flat Networks》

**The topology is referenced on the Internet**

![image](https://github.com/user-attachments/assets/7eb71fd2-bb3a-4084-b4e0-778c21d429e9)

**K8s version**
kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3

**istioctl version**  
client version: 1.25.2
control plane version: 1.25.2
data plane version: 1.25.2 (4 proxies)

### **#Create ROOT CA**

```
mkdir -p /opt/kubernetes/cfg/istio-1.25.2/certs && cd /opt/kubernetes/cfg/istio-1.25.2/certs && pwd

cd /opt/kubernetes/cfg/istio-1.25.2/certs
make -f /opt/kubernetes/cfg/istio-1.25.2/tools/certs/Makefile.selfsigned.mk ROOTCA_DAYS=36500 root-ca
```

**#Intermediate cas are created for each cluster separately**

**1. Create an intermediate certificate for the Nanjing cluster**
```
cd /opt/kubernetes/cfg/istio-1.25.2/certs
make -f /opt/kubernetes/cfg/istio-1.25.2/tools/certs/Makefile.selfsigned.mk ROOTCA_DAYS=36500 nanjing-k8s-cluster-cacerts
```

**2. Create intermediate certificates for the Beijing cluster**
```
cd /opt/kubernetes/cfg/istio-1.25.2/certs
make -f /opt/kubernetes/cfg/istio-1.25.2/tools/certs/Makefile.selfsigned.mk ROOTCA_DAYS=36500 beijing-k8s-cluster-cacerts
```

### 【Nanjing station cluster】

**#Create the intermediate CA's secret**
```
kubectl create secret generic cacerts -n istio-system \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/nanjing-k8s-cluster/ca-cert.pem \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/nanjing-k8s-cluster/ca-key.pem \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/nanjing-k8s-cluster/root-cert.pem \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/nanjing-k8s-cluster/cert-chain.pem
```

**#Configure the label of the default network name for the current k8s cluster**
```
kubectl get namespace istio-system && \
kubectl label namespace istio-system topology.istio.io/network=nj-k8s-cluster-network-01
```

**#Register for remote cluster service discovery**
`istioctl create-remote-secret --kubeconfig=/opt/kubernetes/cfg/istio-1.25.2/kube-config/beijing.k8s.cluster.kubeconfig --name="kubernetes-admin-bj-k8s-cluster" | kubectl apply -f -`

```
istioctl remote-clusters
NAME                                SECRET                                                               STATUS     ISTIOD
kubernetes-admin-nj-k8s-cluster                                                                          synced     istiod-77ff955f5c-svtbd
kubernetes-admin-bj-k8s-cluster     istio-system/istio-remote-secret-kubernetes-admin-bj-k8s-cluster     synced     istiod-77ff955f5c-svtbd
```

**#Deploy the istiod control surface**
```
cat > /download/nj-k8s-cluster-01.yaml << EOF
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    networks:
      nj-k8s-cluster-network-01:
        endpoints:
          - fromCidr: 10.244.0.0/16
      bj-k8s-cluster-network-01:
        endpoints:
          - fromCidr: 10.245.0.0/16
    rootNamespace: istio-system
    trustDomain: cluster.local
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: '{"authority":"%REQ(:AUTHORITY)%","bytes_received":"%BYTES_RECEIVED%","bytes_sent":"%BYTES_SENT%","downstream_local_address":"%DOWNSTREAM_LOCAL_ADDRESS%","downstream_remote_address":"%DOWNSTREAM_REMOTE_ADDRESS%","duration":"%DURATION%","istio_policy_status":"%DYNAMIC_METADATA(istio.mixer:status)%","method":"%REQ(:METHOD)%","path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol":"%PROTOCOL%","request_id":"%REQ(X-REQUEST-ID)%","requested_server_name":"%REQUESTED_SERVER_NAME%","response_code":"%RESPONSE_CODE%","response_flags":"%RESPONSE_FLAGS%","route_name":"%ROUTE_NAME%","start_time":"%START_TIME%","trace_id":"%REQ(X-B3-TRACEID)%","upstream_cluster":"%UPSTREAM_CLUSTER%","upstream_host":"%UPSTREAM_HOST%","upstream_local_address":"%UPSTREAM_LOCAL_ADDRESS%","upstream_service_time":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","upstream_transport_failure_reason":"%UPSTREAM_TRANSPORT_FAILURE_REASON%","user_agent":"%REQ(USER-AGENT)%","x_forwarded_for":"%REQ(X-FORWARDED-FOR)%"}'
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "kubernetes-admin-nj-k8s-cluster"
      network: nj-k8s-cluster-network-01
      logAsJson: true
      caAddress: ""
EOF

```

istioctl install -f /download/nj-k8s-cluster-01.yaml -y

### 【Beijing station cluster】

**#Create the intermediate CA's secret**
```
kubectl create secret generic cacerts -n istio-system \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/beijing-k8s-cluster/ca-cert.pem \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/beijing-k8s-cluster/ca-key.pem \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/beijing-k8s-cluster/root-cert.pem \
--from-file=/opt/kubernetes/cfg/istio-1.25.2/certs/beijing-k8s-cluster/cert-chain.pem
```

**#Configure the label of the default network name for the current k8s cluster**
```
kubectl get namespace istio-system && \
kubectl label namespace istio-system topology.istio.io/network=bj-k8s-cluster-network-01
```

**#Register for remote cluster service discovery**
`istioctl create-remote-secret --kubeconfig=/opt/kubernetes/cfg/istio-1.25.2/kube-config/nanjing.k8s.cluster.kubeconfig --name="kubernetes-admin-nj-k8s-cluster" | kubectl apply -f -`

```
istioctl remote-clusters
NAME                                SECRET                                                               STATUS     ISTIOD
kubernetes-admin-bj-k8s-cluster                                                                          synced     istiod-db49fb674-867b8
kubernetes-admin-nj-k8s-cluster     istio-system/istio-remote-secret-kubernetes-admin-nj-k8s-cluster     synced     istiod-db49fb674-867b8
```

**#Deploy the istiod control surface**
```
cat > /download/bj-k8s-cluster-01.yaml << EOF
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    networks:
      nj-k8s-cluster-network-01:
        endpoints:
          - fromCidr: 10.244.0.0/16
      bj-k8s-cluster-network-01:
        endpoints:
          - fromCidr: 10.245.0.0/16
    rootNamespace: istio-system
    trustDomain: cluster.local
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: '{"authority":"%REQ(:AUTHORITY)%","bytes_received":"%BYTES_RECEIVED%","bytes_sent":"%BYTES_SENT%","downstream_local_address":"%DOWNSTREAM_LOCAL_ADDRESS%","downstream_remote_address":"%DOWNSTREAM_REMOTE_ADDRESS%","duration":"%DURATION%","istio_policy_status":"%DYNAMIC_METADATA(istio.mixer:status)%","method":"%REQ(:METHOD)%","path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol":"%PROTOCOL%","request_id":"%REQ(X-REQUEST-ID)%","requested_server_name":"%REQUESTED_SERVER_NAME%","response_code":"%RESPONSE_CODE%","response_flags":"%RESPONSE_FLAGS%","route_name":"%ROUTE_NAME%","start_time":"%START_TIME%","trace_id":"%REQ(X-B3-TRACEID)%","upstream_cluster":"%UPSTREAM_CLUSTER%","upstream_host":"%UPSTREAM_HOST%","upstream_local_address":"%UPSTREAM_LOCAL_ADDRESS%","upstream_service_time":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","upstream_transport_failure_reason":"%UPSTREAM_TRANSPORT_FAILURE_REASON%","user_agent":"%REQ(USER-AGENT)%","x_forwarded_for":"%REQ(X-FORWARDED-FOR)%"'
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "kubernetes-admin-bj-k8s-cluster"
      network: bj-k8s-cluster-network-01
      logAsJson: true
      caAddress: ""
EOF

```

**#Deploy east-west gateways**
```
cat > /download/bj-k8s-cluster-eastwest-gateway.yaml <<EOF 
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
  namespace: istio-system
spec:
  revision: ""
  profile: empty
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        namespace: istio-system
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
          topology.istio.io/network: bj-k8s-cluster-network-01
        enabled: true
        k8s:
          env:
            # traffic through this gateway should be routed inside the network
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: bj-k8s-cluster-network-01
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
                nodePort: 35021
              - name: tls
                port: 15443
                targetPort: 15443
                nodePort: 35443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
                nodePort: 35012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
                nodePort: 35017
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    global:
      network: bj-k8s-cluster-network-01
EOF
```

istioctl install -y -f /download/bj-k8s-cluster-eastwest-gateway.yaml

**#Exposure service**
```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-eastwestgateway
    topology.istio.io/network: bj-k8s-cluster-network-01
  servers:
    - port:
        number: 15443
        name: tls-15443
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
        minProtocolVersion: TLSV1_2
      hosts:
        - "*.sample.svc.cluster.local"
EOF
```

### 【Nanjing station cluster】

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: helloworld-vs
  namespace: sample
spec:
  gateways:
    - mesh
    - istio-system/cross-network-gateway
  hosts:
    - helloworld.sample.svc.cluster.local
  http:
    - match:
        - port: 5000
      route:
      - destination:
          host: helloworld.sample.svc.cluster.local
          subset: v1-http-nj
        weight: 0
      - destination:
          host: helloworld-remote.sample.global
        weight: 100
EOF
```

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-dr
  namespace: sample
spec:
  host: helloworld.sample.svc.cluster.local
  subsets:
    - name: v1-http-nj
      labels:
        version: v1
        topology.istio.io/network: nj-k8s-cluster-network-01
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        outlierDetection:
          consecutiveGatewayErrors: 3
          consecutive5xxErrors: 3
          interval: 10s
          baseEjectionTime: 30s
          maxEjectionPercent: 50
EOF
```

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-remote-dr
  namespace: sample
spec:
  host: helloworld-remote.sample.global
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 5000
        tls:
          mode: ISTIO_MUTUAL
          sni: helloworld.sample.svc.cluster.local
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
EOF
```

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: to-bj-eastwest-gateway-se
  namespace: sample
spec:
  hosts:
    - helloworld-remote.sample.global
  ports:
    - number: 5000
      name: tls-5000
      protocol: TLS
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
    - address: 192.168.110.230
      ports:
        tls-5000: 35443
EOF
```

### 【Beijing station cluster】

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: helloworld-vs
  namespace: sample
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/cross-network-gateway
  tls:
    - match:
        - port: 15443
          sniHosts: 
            - "*"
      route:
        - destination:
            host: helloworld.sample.svc.cluster.local
            port:
                number: 5000
EOF
```

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-dr
  namespace: sample
spec:
  host: "helloworld.sample.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```
