### ISSUE TITLE
ENABLE_NATIVE_SIDECARS breaks custom side-car injection templating

### ISSUE THREAD

**Issue by Jeansen** [istio/istio#56455]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

If followed https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/ and everything works as documented. But when I enable ENABLE_NATIVE_SIDECARS custom templates no longer work and Kuberntes complains that an Init container with the name istio-proxy already exists. 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-system
spec:
  values:
    sidecarInjectorWebhook:
      templates:
        custom: |
          spec:
            containers:
            - name: istio-proxy
              env:
              - name: GREETING
                value: hello-world
  components:
    pilot:
      k8s:
        env:
          - name: ENABLE_NATIVE_SIDECARS
            value: "true"
```

When I remove the `components` part setting the `ENABLE_NATIVE_SIDECARS`, all works well again.

### Version

```Text
client version: 1.25.2
control plane version: 1.25.1
data plane version: 1.25.1 (13 proxies)

Client Version: v1.32.5
Kustomize Version: v5.5.0
Server Version: v1.32.5
```

### Additional Information

The installation as such works. The error only shows, when a Pod is injected.  Here is an example:

```

Error creating: Pod "curl-d98f47cbf-4rzx2" is invalid: [spec.containers[1].image: Required value, spec.initContainers[1].name: Duplicate value: "istio-proxy"]
```
