### ISSUE TITLE
404 Returned when routing to specific routes using VirtualService

### ISSUE THREAD

**Issue by marco-updater** [istio/istio#56461]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We are communicating to an external site which requires mTLS. For this bug report, I named this external site `foo-bar.com`.

I have a DNS record (bug report name: `testing.my-proxy-site.com`) that routes to my ingress gateway and is configured as the host for a `VirtualService` that routes traffic to a `ServiceEntry` for `foo-bar.com`. A DestinationRule is then responsible for attaching the cert. for mTLS (All of these config. can be found below)

`foo-bar.com` site has two routes: 

```
foo-bar.com/health
foo-bar.com/data/v3/my-data
```

Both routes work as expected when supplying a valid cert.
The following responses are valid/expected:

Tests using no routing:
```
# the output returned is expected
curl --cert cert.tls --key key.tls --cacert ca.tls https://foo-bar.com/health
{"gitCommit":"121121212121212121212121212"}
```
```
# the output returned is expected
curl --cert cert.tls --key key.tls --cacert ca.tls https://foo-bar.com/data/v3/my-data
{"title":"Method Not Allowed","detail":"method GET is not allowed, but [POST] are"}
```

However, when I involve the istio routing, only the `/health` endpoint works as expected.
The `/data/v3/my-data` returns '404 page not found`. 

Tests using istio routing:
```
# the output returned is expected
curl https://testing.my-proxy-site.com/health
{"gitCommit":"121121212121212121212121212"}
```
```
# the output returned is not expected
curl https://testing.my-proxy-site.com/data/v3/my-data
404 page not found
```

In the 'istio-gateways' namespace:

```
istioctl proxy-config routes istio-ingress-7885ccd487-c29f7
NAME                                               VHOST NAME                        DOMAINS                                          MATCH                  VIRTUAL SERVICE
https.443.https.ingress-gateway.istio-gateways     testing.my-proxy-site.com:443     testing.my-proxy-site.com                        /*                     foo-bar-vs.foo-bar
http.80                                            testing.my-proxy-site.com:80      testing.my-proxy-site.com                        /*                     foo-bar-vs.foo-bar

```

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-gateways
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        credentialName: wildcard

```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-bar-vs
  namespace: foo-bar
spec:
  hosts:
    - testing.my-proxy-site.com
  gateways:
    - istio-gateways/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: foo-bar.com
            port:
              number: 80

```

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: foo-bar-service
  namespace: foo-bar
spec:
  hosts:
    - foo-bar.com
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
      targetPort: 443
    - number: 443
      name: https-port
      protocol: HTTPS
  resolution: DNS

```

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-mtls-for-foo-bar
  namespace: foo-bar
spec:
  host: foo-bar.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: MUTUAL
          credentialName: foo-bar-credentials
          sni: foo-bar.com

```

Obtained from `kubectl logs istio-ingress-7885ccd487-c29f7 -f`

```
# trace for curl https://testing.my-proxy-site.com/data/v3/my-data
{
    "user_agent": "curl/8.7.1",
    "bytes_received": 0,
    "downstream_remote_address": "omittedForBugReport",
    "upstream_transport_failure_reason": null,
    "path": "/data/v3/my-data",
    "method": "GET",
    "authority": "testing.my-proxy-site.com",
    "response_flags": "-",
    "response_code_details": "via_upstream",
    "downstream_local_address": "omittedForBugReport:443",
    "response_code": 404,
    "connection_termination_details": null,
    "requested_server_name": null,
    "upstream_cluster": "outbound|80||foo-bar.com",
    "start_time": "2025-05-29T19:49:35.383Z",
    "upstream_local_address": "omittedForBugReport",
    "duration": 228,
    "protocol": "HTTP/1.1",
    "x_forwarded_for": "omittedForBugReport",
    "bytes_sent": 19,
    "upstream_service_time": null,
    "route_name": null,
    "upstream_host": "omittedForBugReport:443",
    "request_id": "omittedForBugReport"
}

# trace for curl https://testing.my-proxy-site.com/health

{
    "x_forwarded_for": "omittedForBugReport,omittedForBugReport",
    "downstream_local_address": "omittedForBugReport:443",
    "bytes_received": 0,
    "request_id": "omittedForBugReport",
    "upstream_service_time": null,
    "route_name": null,
    "upstream_transport_failure_reason": null,
    "connection_termination_details": null,
    "upstream_cluster": "outbound|80||foo-bar.com",
    "method": "GET",
    "user_agent": "curl/8.7.1",
    "start_time": "2025-05-29T19:51:44.661Z",
    "path": "/health",
    "response_code": 200,
    "duration": 76,
    "response_code_details": "via_upstream",
    "requested_server_name": null,
    "protocol": "HTTP/1.1",
    "authority": "testing.my-proxy-site.com",
    "response_flags": "-",
    "upstream_local_address": "omittedForBugReport",
    "downstream_remote_address": "omittedForBugReport",
    "upstream_host": "omittedForBugReport:443",
    "bytes_sent": 92
}

```

### Version

```Text
istioctl version
client version: 1.24.0
control plane version: 1.22.3-tetratefips0
data plane version: 1.22.3-tetratefips0 (37 proxies)

kubectl version # --short throws 'error: unknown flag'
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.7-eks-bcf3d70

helm version --short
v3.16.2+g13654a5
```
