### ISSUE TITLE
Ambient mode IPv6 mask for SNAT (AWS EKS, CNI, NetworkPolicy)

### ISSUE THREAD

**Issue by fulder** [istio/istio#56484]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hello,

I would like to understand what IP range and mask I need to set for the IPv6 SNAT inside a NetworkPolicy `ipBlock` `cidr` property in order to make the probes on my pod pass successfully.

The docs at: https://istio.io/latest/docs/ambient/usage/networkpolicy/#ambient-health-probes-and-kubernetes-networkpolicy only state the IPv4 address using the `/32` mask, although the readme here: https://github.com/istio/istio/blob/master/cni/README.md#notable-env-vars states it should be a `/16` range.

For the IPv6 SNAT IP it's even more unclear. Just adding the single `fd16:9254:7127:1337:ffff:ffff:ffff:ffff/128` doesn't work. 

I've tried to narrow the range down with trial and errors and it looks like e.g. `fd16:9254:7127:1337:ffff::/80` and `fd16:9254:7127:1337:ffff::/81` works fine but `fd16:9254:7127:1337:ffff::/128` doesn't.

Which mask should I use?

### Version

```Text
$ kubectl version                                                                                                              
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.3-eks-bcf3d70

helm (terraform provider) version: 2.17.0
```

**Comment by sridhargaddam** [comment]
Istio programs the following IPv6 rules (similar to IPv4) on the host network. These rules SNAT traffic that originates from the host (including kubelet health-check traffic) and is destined for pods in the ambient mesh.

```
* nat
-N ISTIO_POSTRT
-I POSTROUTING 1 -j ISTIO_POSTRT
-A ISTIO_POSTRT -m owner --socket-exists -p tcp -m set --match-set istio-inpod-probes-v6 dst -j SNAT --to-source fd16:9254:7127:1337:ffff:ffff:ffff:ffff
```

Inside the pod’s network namespace, traffic with a source IP of `fd16:9254:7127:1337:ffff:ffff:ffff:ffff` is then allowed to bypass the ztunnel proxy

```
* nat
-N ISTIO_PRERT
-N ISTIO_OUTPUT
-A OUTPUT -j ISTIO_OUTPUT
-A PREROUTING -j ISTIO_PRERT
-A ISTIO_PRERT -s fd16:9254:7127:1337:ffff:ffff:ffff:ffff -p tcp -m tcp -j ACCEPT
-A ISTIO_OUTPUT -d fd16:9254:7127:1337:ffff:ffff:ffff:ffff -p tcp -m tcp -j ACCEPT
...
```

> The docs at: https://istio.io/latest/docs/ambient/usage/networkpolicy/#ambient-health-probes-and-kubernetes-networkpolicy only state the IPv4 address using the /32 mask

Yes, that’s correct. Ambient mode uses a **single fixed IP address** (one for IPv4, one for IPv6). It does not use a range.

> ...although the readme here: https://github.com/istio/istio/blob/master/cni/README.md#notable-env-vars states it should be a /16 range.

Right, that part of the docs was not very clear. I submitted a PR to clarify the usage: https://github.com/istio/istio/pull/57529

> Which mask should I use?

You should use `/32` for IPv4 and `/128` for IPv6. For example...

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress-allow-kubelet-healthprobes
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: my-app
  ingress:
    - from:
      - ipBlock:
          cidr: 169.254.7.127/32
      - ipBlock:
          cidr: fd16:9254:7127:1337:ffff:ffff:ffff:ffff/128
```

**Comment by fulder** [comment]
I have tried chaning the NetworkPolicy to just the single IPv6 SNAT IP, but that makes my pod crash with livness probes warnings like:

>  Warning  Unhealthy  1s    kubelet            Liveness probe failed: Get "http://[2a05:d018:1c6b:204:e83d::3]:8080/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Changing it back to `fd16:9254:7127:1337:ffff::/80` range seems to help the probe. It feels like something else is needed except this single IP? 🤔  or am I doing something wrong?

Also, which kind of ports are needed from istio side? I found: https://istio.io/latest/docs/ops/deployment/application-requirements/#ports-used-by-istio and https://istio.io/latest/docs/ambient/usage/networkpolicy/#ambient-traffic-overlay-and-kubernetes-networkpolicy that state 15008 should be added, but my probes seems to work without the 15008 port as well.

Summarized, here's a working policy (pod Liveness:  `http-get http://:8080/ delay=0s timeout=1s period=10s #success=1 #failure=3`):

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-np
  namespace: my-namespace
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: fd16:9254:7127:1337:ffff::/80
    ports:
      - port: 8080
        protocol: TCP
  podSelector:
    matchLabels:
       name: my-pod
```

and not working variant:


```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-np
  namespace: my-namespace
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: fd16:9254:7127:1337:ffff:ffff:ffff:ffff/128
    ports:
      - port: 8080
        protocol: TCP
      - port: 15008
        protocol: TCP
  podSelector:
    matchLabels:
       name: my-pod
```
