### ISSUE TITLE
[Problem] How can I do a gRPC request throught gateway (istio ingress)?

### ISSUE THREAD

**Issue by g3david405** [istio/istio#56557]
I install istio with the latest version, and my kubernetes version is 1.30.4 (use kubeadm).
I face some problems when I try to connect gRPC server throught istio gateway.

Here is my Gateway config
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - 'grpc.test'
      port:
        name: http
        number: 80
        protocol: GRPC
```

And here is my istio-ingress service
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: istio-ingress
    istio: ingress
  externalIPs:
    - {my master ip}
```

And here is my virtualService
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grpcservice-istio
  namespace: test
spec:
  gateways:
    - istio-ingress/default-gateway
  hosts:
    - grpc.test
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: grpcservice-istio-svc.test.svc.cluster.local
            port:
              number: 80
```

When I port forward my service grpcservice-istio-svc.test.svc.cluster.local,
I can connect it throught postman

<img width="665" alt="Image" src="https://github.com/user-attachments/assets/aa42f9bb-e84e-4171-829d-824036161f98" />

But when I want to use gRPC throught gateway, It can't be connect.
And here is my istio ingress log
```
[2025-06-10T06:34:15.260Z] "POST /greet.Greeter/SayHello HTTP/2" 400 - via_upstream - "-" 11 56 1 0 "192.168.251.194" "grpc-node-js/1.8.10" "67da989a-46b4-4cb5-b2ab-d92bed10e0b5" "grpc.test:80" "192.168.238.229:80" outbound|80||grpcservice-istio-svc.test.svc.cluster.local 192.168.80.62:42526 192.168.80.62:80 192.168.251.194:10823 - -
```

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/4bfbd701-8ae9-4be5-9528-4b193afa3f09" />

What did I do wrong?
thx!
