### ISSUE TITLE
Global rate limit not working with custom headers

### ISSUE THREAD

**Issue by shantanupatil29** [istio/istio#56573]
We are trying to apply rate limiting on the gateway level based on client ids for all services inside kubenetes cluster.
We have added 3 EnvoyFilters,

1. Filter with lua script, which decodes jwt token and adds a custom header "authorization-user_name" and pass onto the next filter.
2. Filter with Header and Descriptor key mapping.
3. Global rate-limit filter to map every request to rate limit service

We have verified that headers are being added by the first filter and we see that rate limit service is not triggered. We have tried different approaches but still not working, We would appreciate your help.

----------------------------------
Lua-filter.yml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt-lua-filter
  namespace: istio-system
spec:
  priority: 0                     # Priority 0 to be executed first
  workloadSelector:
    labels:
      istio: ingress
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            -- Json Parsing based on https://gist.github.com/tylerneylon/59f4bcf316be525b30ab
            -- Base64 decoding based on wikipedia description of 8/6bit encoding.

            -- base64 char array.. note final 2 chars are for RFC4648-URL encoding
            -- as per JWT spec section 2 terminology 'Base64url Encoding'
            local alpha='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'

            -- convert to 6 char long binary string. (max int 64!)
            function toBinaryString(int)
                if int > 64 then
                    error("Bad number "..int.." to convert to binary")
                end        
                local remaining = tonumber(int)
                local bits = ''
                for i = 5, 0, -1 do
                    local pow = 2 ^ i
                    if remaining >= pow then
                        bits = bits .. '1'
                        remaining = remaining - pow
                    else
                        bits = bits .. '0'
                    end
                end
                return bits
            end

            function fromBinaryString(bits)
                return tonumber(bits, 2)
            end

            function decodeBase64(encoded)
                encoded = string.gsub(encoded, " ", "")
                encoded = string.gsub(encoded, "=", "")
                local bitstr = ''
                local decoded = ''
                -- decode chars into bitstring
                for i = 1, string.len(encoded) do
                    local offset, _ = string.find(alpha, string.sub(encoded, i, i))
                    if offset == nil then
                        error("Bad base64 character " .. string.sub(encoded, i, i))
                    end
                    bitstr = bitstr .. toBinaryString(offset-1)
                end
                -- decode bitstring back to chars
                for i = 1, string.len(bitstr), 8 do
                    decoded = decoded .. string.char(fromBinaryString(string.sub(bitstr, i, i+7)))
                end
                return decoded
            end

            -- json handling 

            local json = {}

            local function kind_of(obj)
              if type(obj) ~= 'table' then return type(obj) end
              local i = 1
              for _ in pairs(obj) do
                if obj[i] ~= nil then i = i + 1 else return 'table' end
              end
              if i == 1 then return 'table' else return 'array' end
            end

            local function escape_str(s)
              local in_char  = {'\\', '"', '/', '\b', '\f', '\n', '\r', '\t'}
              local out_char = {'\\', '"', '/',  'b',  'f',  'n',  'r',  't'}
              for i, c in ipairs(in_char) do
                s = s:gsub(c, '\\' .. out_char[i])
              end
              return s
            end

            -- Returns pos, did_find; there are two cases:
            -- 1. Delimiter found: pos = pos after leading space + delim; did_find = true.
            -- 2. Delimiter not found: pos = pos after leading space;     did_find = false.
            -- This throws an error if err_if_missing is true and the delim is not found.
            local function skip_delim(str, pos, delim, err_if_missing)
              pos = pos + #str:match('^%s*', pos)
              if str:sub(pos, pos) ~= delim then
                if err_if_missing then
                  error('Expected ' .. delim .. ' near position ' .. pos)
                end
                return pos, false
              end
              return pos + 1, true
            end

            -- Expects the given pos to be the first character after the opening quote.
            -- Returns val, pos; the returned pos is after the closing quote character.
            local function parse_str_val(str, pos, val)
              val = val or ''
              local early_end_error = 'End of input found while parsing string.'
              if pos > #str then error(early_end_error) end
              local c = str:sub(pos, pos)
              if c == '"'  then return val, pos + 1 end
              if c ~= '\\' then return parse_str_val(str, pos + 1, val .. c) end
              -- We must have a \ character.
              local esc_map = {b = '\b', f = '\f', n = '\n', r = '\r', t = '\t'}
              local nextc = str:sub(pos + 1, pos + 1)
              if not nextc then error(early_end_error) end
              return parse_str_val(str, pos + 2, val .. (esc_map[nextc] or nextc))
            end

            -- Returns val, pos; the returned pos is after the number's final character.
            local function parse_num_val(str, pos)
              local num_str = str:match('^-?%d+%.?%d*[eE]?[+-]?%d*', pos)
              local val = tonumber(num_str)
              if not val then error('Error parsing number at position ' .. pos .. '.') end
              return val, pos + #num_str
            end

            json.null = {}  -- one-off table to represent the null value.

            function json.parse(str, pos, end_delim)
              pos = pos or 1
              if pos > #str then error('Reached unexpected end of input.') end
              local pos = pos + #str:match('^%s*', pos)  -- Skip whitespace.
              local first = str:sub(pos, pos)
              if first == '{' then  -- Parse an object.
                local obj, key, delim_found = {}, true, true
                pos = pos + 1
                while true do
                  key, pos = json.parse(str, pos, '}')
                  if key == nil then return obj, pos end
                  if not delim_found then error('Comma missing between object items.') end
                  pos = skip_delim(str, pos, ':', true)  -- true -> error if missing.
                  obj[key], pos = json.parse(str, pos)
                  pos, delim_found = skip_delim(str, pos, ',')
                end
              elseif first == '[' then  -- Parse an array.
                local arr, val, delim_found = {}, true, true
                pos = pos + 1
                while true do
                  val, pos = json.parse(str, pos, ']')
                  if val == nil then return arr, pos end
                  if not delim_found then error('Comma missing between array items.') end
                  arr[#arr + 1] = val
                  pos, delim_found = skip_delim(str, pos, ',')
                end
              elseif first == '"' then  -- Parse a string.
                return parse_str_val(str, pos + 1)
              elseif first == '-' or first:match('%d') then  -- Parse a number.
                return parse_num_val(str, pos)
              elseif first == end_delim then  -- End of an object or array.
                return nil, pos + 1
              else  -- Parse true, false, or null.
                local literals = {['true'] = true, ['false'] = false, ['null'] = json.null}
                for lit_str, lit_val in pairs(literals) do
                  local lit_end = pos + #lit_str - 1
                  if str:sub(pos, lit_end) == lit_str then return lit_val, lit_end + 1 end
                end
                local pos_info_str = 'position ' .. pos .. ': ' .. str:sub(pos, pos + 10)
                error('Invalid json syntax starting at ' .. pos_info_str)
              end
            end

            function decode_jwt(jwt)
              i=0
              result = {}
              for match in (jwt..'.'):gmatch("(.-)%.") do
                  result[i]=decodeBase64(match)
                  i=i+1
              end
              -- header
              head = json.parse(result[0])
              -- claims
              claims = json.parse(result[1])
              return {head=head,claims=claims}
            end
            function add_header(k,v,prefix,headers)
              if "number" == type (k) then
                headers:add(prefix,v)
              else
                headers:add(prefix.."-"..k,v)
              end
            end
            function add_table_as_headers(table, prefix, headers)
              for k,v in pairs(table) do
                if "string" == type( v ) then
                  add_header(k,v,prefix,headers)
                  print(k, v)
                end
              end
            end

            function is_basic_auth(authorization)
              return string.find(authorization, "Basic ") ~= nil or string.find(authorization, "basic ") ~= nil
            end

            function envoy_on_request(request_handle)
              local jwtHeaderName = "authorization"
              headers = request_handle:headers()
              authorization = headers:get(jwtHeaderName)
              if authorization == nil then
                headers:add("jwt","authorizationnotfound")
              else
                if is_basic_auth(authorization) then
                  basic = string.gsub(authorization, "Basic ", "")
                  basic = string.gsub(basic, "basic ", "")
                  result = decodeBase64(basic)
                  clientid = string.match(result, "(.*):")
                  add_header("client_id", clientid, "authorization_basic_auth", headers)
                else
                  jwt = string.gsub(authorization,"Bearer ","")
                  jwt = string.gsub(jwt,"bearer ","")
                  if jwt == nil then
                      headers:add("jwt","jwtnotfound")
                  else
                      content = decode_jwt(jwt)
                      add_table_as_headers(content["claims"],jwtHeaderName,headers)
                      print("---------------")
                  end
                end
              end
            end
```
----------------------------------

2. mapper-filter.yml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: orchestrator-filter-ratelimit-nlb
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingress
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY             
        routeConfiguration:
          vhost:
            name: "*"
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions:
              - request_headers:
                  header_name: "authorization-user_name"
                  descriptor_key: "USERNAME"
```

----------------------------------

3. global-rate-limit.yml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-nlb
  namespace: istio-system
spec:
  priority: 1                                   # Priority 1 to be executed after jwt-lua-filter that adds extra headers
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingress
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY               
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: ratelimit-istio-nlb
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.seldon.svc.cluster.local
      patch:
        operation: ADD
        # Adds the rate limit service cluster for rate limit service defined in step 1.
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                     socket_address:
                      address: ratelimit.seldon.svc.cluster.local
                      port_value: 8081
```

----------------------------------

ConfigMap.yml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-istio-nlb-config
  namespace: seldon
data:
  config.yaml: |
    domain: ratelimit-istio-nlb
    descriptors:
      - key: USERNAME
        value: "test@gmail.com"
        rate_limit:
          unit: minute
          requests_per_unit: 2
        shadow_mode: false
```

----------------------------------

Rate-limit.yml - rate limit service and redis deployment

```
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: seldon
  labels:
    app: ratelimit
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-port
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: http-debug
    port: 6070
    targetPort: 6070
    protocol: TCP
  selector:
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
  namespace: seldon
  labels:
    app: ratelimit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ratelimit
        version: v1
    spec:
      containers:
      - image: envoyproxy/ratelimit:30a4ce1a
        imagePullPolicy: IfNotPresent
        name: ratelimit
        command: ["/bin/ratelimit"]
        env:
        - name: LOG_LEVEL
          value: debug
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: redis:6379
        - name: USE_STATSD
          value: "false"
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        - name: RUNTIME_WATCH_ROOT
          value: "false"
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"
        - name: HOST
          value: "::"
        - name: GRPC_HOST
          value: "::"
        - name: LIMIT_RESPONSE_HEADERS_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 6070
        volumeMounts:
        - name: config-volume
          mountPath: /data/ratelimit/config
      volumes:
      - name: config-volume
        configMap:
          name: ratelimit-istio-nlb-config

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: seldon
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: redis
        version: v1
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
```
-----------------------

Proxy logs - istio-ingress 

```
Header: :authority = URL
Header: :path = /v2.0/predictions?cache=false
Header: :method = POST
Header: :scheme = http
Header: content-type = application/json
Header: authorization = Bearer token
Header: user-agent = PostmanRuntime/7.44.0
Header: accept = */*
Header: cache-control = no-cache
Header: postman-token = fe8d0ec4-a37b-44d6-b58f-e90e5a5adce7
Header: accept-encoding = gzip, deflate, br
Header: content-length = 866
Header: x-forwarded-for = 10.0.202.34
Header: x-forwarded-proto = http
Header: x-envoy-internal = true
Header: authorization-client_id = XXXX
Header: authorization-jti = XXX
Header: authorization-iss = XXX
Header: authorization-sub = XXX
Header: authorization-user_name = test@gmail.com
2025-06-11T08:00:13.408224Z	debug	envoy jwt external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:143	Called Filter : decodeData	thread=22
2025-06-11T08:00:13.409254Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1175	[Tags: "ConnectionId":"565066","StreamId":"6324323051227369753"] request end stream	thread=22
2025-06-11T08:00:13.409302Z	debug	envoy jwt external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:143	Called Filter : decodeData	thread=22
2025-06-11T08:00:15.634785Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1869	[Tags: "ConnectionId":"565066","StreamId":"6324323051227369753"] encoding headers via codec (end_stream=false):
':status', '200'
'date', 'Wed, 11 Jun 2025 08:00:12 GMT'
'server', 'istio-envoy'
'content-length', '289'
'content-type', 'application/json'
'vary', 'Accept-Encoding'
'content-encoding', 'gzip'
'x-envoy-upstream-service-time', '2223'
	thread=22
2025-06-11T08:00:15.635002Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1974	[Tags: "ConnectionId":"565066","StreamId":"6324323051227369753"] Codec completed encoding stream.	thread=22
2025-06-11T08:00:15.635262Z	debug	envoy jwt external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:46	Called Filter : onDestroy	thread=22
2025-06-11T08:00:17.213465Z	debug	envoy http external/envoy/source/common/http/async_client_impl.cc:106	async http request response headers (end_stream=false):
':status', '200'
'content-type', 'application/json'
'datadog-agent-state', 'b9c699f06eafe2827658e7726da1c7ea04d0cc90b66d7eed932d7bb442a98919'
'datadog-agent-version', '7.63.3'
'date', 'Wed, 11 Jun 2025 08:00:17 GMT'
'content-length', '550'
'x-envoy-upstream-service-time', '0'
	thread=22
2025-06-11T08:00:22.260188Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:393	[Tags: "ConnectionId":"565121"] new stream	thread=23
2025-06-11T08:00:22.260324Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1192	[Tags: "ConnectionId":"565121","StreamId":"15380154930143868863"] request headers complete (end_stream=true):
':authority', '10.0.202.227:15021'
':path', '/healthz/ready'
':method', 'GET'
'user-agent', 'kube-probe/1.31+'
'accept', '*/*'
'connection', 'close'
	thread=23
2025-06-11T08:00:22.260342Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1175	[Tags: "ConnectionId":"565121","StreamId":"15380154930143868863"] request end stream	thread=23
2025-06-11T08:00:22.261043Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1803	[Tags: "ConnectionId":"565121","StreamId":"15380154930143868863"] closing connection due to connection close header	thread=23
2025-06-11T08:00:22.261101Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1869	[Tags: "ConnectionId":"565121","StreamId":"15380154930143868863"] encoding headers via codec (end_stream=true):
':status', '200'
'date', 'Wed, 11 Jun 2025 08:00:22 GMT'
'content-length', '0'
'x-envoy-upstream-service-time', '0'
'server', 'envoy'
'connection', 'close'
	thread=23
2025-06-11T08:00:22.261119Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1974	[Tags: "ConnectionId":"565121","StreamId":"15380154930143868863"] Codec completed encoding stream.	thread=23
2025-06-11T08:00:27.703159Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:393	[Tags: "ConnectionId":"76"] new stream	thread=22
2025-06-11T08:00:27.703373Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1192	[Tags: "ConnectionId":"76","StreamId":"5457999025343787689"] request headers complete (end_stream=true):
':authority', 'localhost:15090'
':path', '/stats/prometheus'
':method', 'GET'
'user-agent', 'Datadog Agent/7.63.3'
'accept', 'text/plain'
'accept-encoding', 'gzip'
	thread=22
2025-06-11T08:00:27.703390Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1175	[Tags: "ConnectionId":"76","StreamId":"5457999025343787689"] request end stream	thread=22
2025-06-11T08:00:27.703652Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:393	[Tags: "ConnectionId":"78"] new stream	thread=14
2025-06-11T08:00:27.703725Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1192	[Tags: "ConnectionId":"78","StreamId":"8388981819137316770"] request headers complete (end_stream=true):
':authority', 'localhost:15090'
':path', '/stats/prometheus'
':method', 'GET'
'user-agent', 'Datadog Agent/7.63.3'
'accept', 'text/plain'
'accept-encoding', 'gzip'
'x-forwarded-proto', 'http'
'x-request-id', '017ca32e-a892-4d70-87cd-92f4edeba3cb'
'x-envoy-expected-rq-timeout-ms', '15000'
	thread=14
2025-06-11T08:00:27.703735Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1175	[Tags: "ConnectionId":"78","StreamId":"8388981819137316770"] request end stream	thread=14
2025-06-11T08:00:27.707896Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1869	[Tags: "ConnectionId":"78","StreamId":"8388981819137316770"] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Wed, 11 Jun 2025 08:00:27 GMT'
'server', 'envoy'
	thread=14
2025-06-11T08:00:27.710593Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1974	[Tags: "ConnectionId":"78","StreamId":"8388981819137316770"] Codec completed encoding stream.	thread=14
2025-06-11T08:00:27.711803Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1869	[Tags: "ConnectionId":"76","StreamId":"5457999025343787689"] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Wed, 11 Jun 2025 08:00:27 GMT'
'server', 'envoy'
'x-envoy-upstream-service-time', '8'
	thread=22
2025-06-11T08:00:27.711894Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1974	[Tags: "ConnectionId":"76","StreamId":"5457999025343787689"] Codec completed encoding stream.	thread=22
2025-06-11T08:00:31.945938Z	debug	envoy http external/envoy/source/common/http/async_client_impl.cc:106	async http request response headers (end_stream=false):
':status', '200'
'datadog-agent-state', 'b9c699f06eafe2827658e7726da1c7ea04d0cc90b66d7eed932d7bb442a98919'
'datadog-agent-version', '7.63.3'
'date', 'Wed, 11 Jun 2025 08:00:31 GMT'
'content-length', '2'
'content-type', 'text/plain; charset=utf-8'
'x-envoy-upstream-service-time', '0'
	thread=23
2025-06-11T08:00:31.950383Z	debug	envoy http external/envoy/source/common/http/async_client_impl.cc:106	async http request response headers (end_stream=false):
':status', '200'
'datadog-agent-state', 'b9c699f06eafe2827658e7726da1c7ea04d0cc90b66d7eed932d7bb442a98919'
'datadog-agent-version', '7.63.3'
'date', 'Wed, 11 Jun 2025 08:00:31 GMT'
'content-length', '2'
'content-type', 'text/plain; charset=utf-8'
'x-envoy-upstream-service-time', '1'
	thread=14
2025-06-11T08:00:31.997641Z	debug	envoy http external/envoy/source/common/http/async_client_impl.cc:106	async http request response headers (end_stream=false):
':status', '200'
'datadog-agent-state', 'b9c699f06eafe2827658e7726da1c7ea04d0cc90b66d7eed932d7bb442a98919'
'datadog-agent-version', '7.63.3'
'date', 'Wed, 11 Jun 2025 08:00:31 GMT'
'content-length', '2'
'content-type', 'text/plain; charset=utf-8'
'x-envoy-upstream-service-time', '0'
	thread=22
2025-06-11T08:00:37.262400Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:393	[Tags: "ConnectionId":"565230"] new stream	thread=22
2025-06-11T08:00:37.262517Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1192	[Tags: "ConnectionId":"565230","StreamId":"15747715854809044968"] request headers complete (end_stream=true):
':authority', '10.0.202.227:15021'
':path', '/healthz/ready'
':method', 'GET'
'user-agent', 'kube-probe/1.31+'
'accept', '*/*'
'connection', 'close'
	thread=22
2025-06-11T08:00:37.262533Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1175	[Tags: "ConnectionId":"565230","StreamId":"15747715854809044968"] request end stream	thread=22
2025-06-11T08:00:37.263063Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1803	[Tags: "ConnectionId":"565230","StreamId":"15747715854809044968"] closing connection due to connection close header	thread=22
2025-06-11T08:00:37.263091Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1869	[Tags: "ConnectionId":"565230","StreamId":"15747715854809044968"] encoding headers via codec (end_stream=true):
':status', '200'
'date', 'Wed, 11 Jun 2025 08:00:37 GMT'
'content-length', '0'
'x-envoy-upstream-service-time', '0'
'server', 'envoy'
'connection', 'close'
	thread=22
2025-06-11T08:00:37.263107Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1974	[Tags: "ConnectionId":"565230","StreamId":"15747715854809044968"] Codec completed encoding stream.	thread=22
`

---------

rate-limit service logs ->
`time="2025-06-11T07:23:42Z" level=info msg="Stats initialized for stdout"
time="2025-06-11T07:23:42Z" level=info msg="Stats flush interval: 10s"
time="2025-06-11T07:23:42Z" level=info msg="Tracing disabled"
time="2025-06-11T07:23:42Z" level=warning msg="connecting to redis on redis:6379 with pool size 10"
time="2025-06-11T07:23:42Z" level=debug msg="Implicit pipelining enabled: false"
time="2025-06-11T07:23:42Z" level=debug msg="loading domain: ratelimit-istio-nlb"
time="2025-06-11T07:23:42Z" level=debug msg="Creating stats for key: 'ratelimit-istio-nlb.USER_NAME_test@gmail.com'"
time="2025-06-11T07:23:42Z" level=debug msg="loading descriptor: key=ratelimit-istio-nlb.USER_NAME_test@gmail.com ratelimit={requests_per_unit=2, unit=MINUTE, unlimited=false, shadow_mode=false}"
time="2025-06-11T07:23:42Z" level=info msg="Waiting for initial ratelimit config update event"
time="2025-06-11T07:23:42Z" level=debug msg="waiting for runtime update"
time="2025-06-11T07:23:42Z" level=info msg="Successfully loaded new configuration"
time="2025-06-11T07:23:42Z" level=info msg="Successfully loaded the initial ratelimit configs"
time="2025-06-11T07:23:42Z" level=debug msg="Waiting for config update event"
time="2025-06-11T07:23:42Z" level=warning msg="Listening for debug on '0.0.0.0:6070'"
time="2025-06-11T07:23:42Z" level=warning msg="Listening for gRPC on '[::]:8081'"
time="2025-06-11T07:23:42Z" level=warning msg="Listening for HTTP on '[::]:8080'"
{"level":"debug","ts":1749626632.608145,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.go.frees","type":"counter","value":"9110.000000"}}
{"level":"debug","ts":1749626632.608283,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.go.pauseTotalNs","type":"counter","value":"413385.000000"}}
{"level":"debug","ts":1749626632.608295,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"runtime.load_attempts","type":"counter","value":"1.000000"}}
{"level":"debug","ts":1749626632.608304,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.redis_pool.cx_total","type":"counter","value":"10.000000"}}
{"level":"debug","ts":1749626632.608313,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.go.totalAlloc","type":"counter","value":"2179344.000000"}}
{"level":"debug","ts":1749626632.608321,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.go.mallocs","type":"counter","value":"13593.000000"}}
{"level":"debug","ts":1749626632.608329,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.go.numGC","type":"counter","value":"1.000000"}}
{"level":"debug","ts":1749626632.608338,"logger":"gostats.loggingsink","msg":"flushing counter","json":{"name":"ratelimit.service.config_load_success","type":"counter","value":"1.000000"}}
{"level":"debug","ts":1749626632.608346,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"runtime.num_values","type":"gauge","value":"1.000000"}}
{"level":"debug","ts":1749626632.608354,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.heapIdle","type":"gauge","value":"4194304.000000"}}
{"level":"debug","ts":1749626632.608361,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.heapObjects","type":"gauge","value":"4483.000000"}}
{"level":"debug","ts":1749626632.608369,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.nextGC","type":"gauge","value":"4194304.000000"}}
{"level":"debug","ts":1749626632.608376,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.numGoroutine","type":"gauge","value":"16.000000"}}
{"level":"debug","ts":1749626632.608385,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.heapSys","type":"gauge","value":"7372800.000000"}}
{"level":"debug","ts":1749626632.608392,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.gcCPUPercent","type":"gauge","value":"0.000000"}}
{"level":"debug","ts":1749626632.608400,"logger":"gostats.loggingsink","msg":"flushing gauge","json":{"name":"ratelimit.go.sys","type":"gauge","value":"0.000000"}}
```
