### ISSUE TITLE
Gateway credentialNames does not work the same way as credentialName

### ISSUE THREAD

**Issue by fisju** [istio/istio#56598]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

[`credentialNames`](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-credential_names) should be the same as [`credentialName`](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-credential_name) but for multiple certificates

> Same as CredentialName but for multiple certificates. Mainly used for specifying RSA and ECDSA certificates for the same server.

However when changed `credentialName` to `credentialNames` with the same value validation fails with

> admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
>	* MUTUAL TLS requires a server certificate
>	* MUTUAL TLS requires a private key
>	* MUTUAL TLS requires a client CA bundle

with this behaviour it's not possible to create Gateway which would read server certificates from one Secret and client CA from other secret.

This prevents us from having server cert auto managed by cert-manager and client certs to be managed manually by users.

It would be nice if istio could read server certs from one specific secret and client certs from others. e.g. introduce `serverCredentialName` which would be allowed to be used in combination with `credentialNames`
Or let `credentialName` (singluar) to be allowed to be used with `credentialNames` (plural) together and use only `credentialName` for server cert.

Similar issue happens with the `caCertificates` which is ignored if the Secret in `credentialName` contains `ca.crt` key - in our case it is Server's CA certificate.

Is there any other option I missed please which would allow us to have auto-managed server's cert with ca.crt and at the same time allow us to configure client CA's certs?

### Version

```Text
$ istioctl version
client version: 1.25.2
control plane version: 1.26.0
data plane version: 1.26.0 (30 proxies)
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.3-eks-4096722
```

**Comment by ramaraochavali** [comment]
Thank you reporting. I will take a look. Can you please share your config?

**Comment by fisju** [comment]
Thank you. This is a sample how I thought it would work

```yaml
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSU..................
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSU..................
  tls.key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSU..................
kind: Secret
metadata:
  name: server-certs
  namespace: istio-gateways
type: kubernetes.io/tls
---
apiVersion: v1
data:
  cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSU..................
kind: Secret
metadata:
  name: client-certs
  namespace: istio-gateways
type: Opaque
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: sample-gateway
  namespace: istio-gateways
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - ns/domain
      port:
        name: https-simple
        number: 443
        protocol: HTTPS
      tls:
        credentialNames:
          - server-certs
          - client-certs
        maxProtocolVersion: TLSV1_2
        minProtocolVersion: TLSV1_2
        mode: MUTUAL
```

**Comment by ramaraochavali** [comment]
>  admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:

MUTUAL TLS requires a server certificate
MUTUAL TLS requires a private key
MUTUAL TLS requires a client CA bundle

Did you get this error with above configuration?

> with this behaviour it's not possible to create Gateway which would read server certificates from one Secret and client CA from other secret.

This prevents us from having server cert auto managed by cert-manager and client certs to be managed manually by users.

This was not the intent of credentialNames. It was intended to support RSA and ECDSA - but with each credential having entire set. What you are asking for is a new requirement.

**Comment by fisju** [comment]
Thank you for your work on this project. I am consistently encountering errors whenever only credentialNames is used in the Gateway configuration. Here are the scenarios I have tested:

- Using credentialNames with only "server-certs"
- Using credentialNames with "server-certs" and "client-certs" (with only cacerts)
- Using credentialNames with "server-certs" and "client-certs" (with all three: tls.key, tls.crt, ca.crt—literally a copy of server-certs into a different Secret)

In all these cases, the configuration fails, even though the documentation indicates this should be supported.

### Documentation Reference
Field | Description
-- | --
[credentialName](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-credential_name)<br>string | For gateways running on Kubernetes, the name of the secret that holds the TLS certs including the CA certificates. Applicable only on Kubernetes. An Opaque secret should contain the following keys and values: tls.key: <privateKey> and tls.crt: <serverCert> or key: <privateKey> and cert: <serverCert>. For mutual TLS, cacert: <CACertificate> and crl: <CertificateRevocationList> can be provided in the same secret or a separate secret named <secret>-cacert. A TLS secret for server certificates with an additional tls.ocsp-staple key for specifying OCSP staple information, ca.crt key for CA certificates and ca.crl for certificate revocation list is also supported. Only one of server certificates and CA certificate or credentialName can be specified.
[credentialNames](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-credential_names)<br>string[] | Same as CredentialName but for multiple certificates. Mainly used for specifying RSA and ECDSA certificates for the same server.
[tlsCertificates](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-tls_certificates)<br>[TLSCertificate[]](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-TLSCertificate) | Only one of server_certificate, private_key, ca_certificates or credential_name or credential_names or tls_certificates should be specified. This is mainly used for specifying RSA and ECDSA certificates for the same server.


### Observed Behavior
**These configurations work as expected:**
```yaml
      tls:
        serverCertificate: /etc/istio/certs/server/cert
        privateKey: /etc/istio/certs/server/key
        caCertificates: /etc/istio/certs/server/cacert
```

```yaml
      tls:
        credentialName: server-certs
```

**These configurations fail:**
```yaml
      tls:
        credentialNames:
          - server-certs
```

> Error from server: error when creating "test-gateway.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
> 	* MUTUAL TLS requires a server certificate
> 	* MUTUAL TLS requires a private key
> 	* MUTUAL TLS requires a client CA bundle

```yaml
      tls:
        credentialNames:
          - server-certs
        serverCertificate: /etc/istio/certs/server/cert
        privateKey: /etc/istio/certs/server/key
```

> Error from server: error when creating "test-gateway.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: MUTUAL TLS requires a client CA bundle

```yaml
      tls:
        credentialNames:
          - server-certs
        tlsCertificates:
          - privateKey: /etc/istio/certs/server/key2
            serverCertificate: /etc/istio/certs/server/cert2
            caCertificates: /etc/istio/certs/server/cacert2
```

> The Gateway "test-gateway" is invalid:
> * spec.servers[0].tls: Invalid value: "object": only one of credentialNames or tlsCertificates can be set
> * spec.servers[0].tls: Invalid value: "object": only one of credentialName or tlsCertificates can be set

```yaml
      tls:
        tlsCertificates:
          - privateKey: /etc/istio/certs/server/key2
            serverCertificate: /etc/istio/certs/server/cert2
            caCertificates: /etc/istio/certs/server/cacert2
```

> Error from server: error when creating "test-gateway.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
> 	* MUTUAL TLS requires a server certificate
> 	* MUTUAL TLS requires a private key
> 	* MUTUAL TLS requires a client CA bundle


**These configurations are accepted, even though according to the documentation they should not be:**
```yaml
      tls:
        credentialNames:
          - server-certs
        serverCertificate: /etc/istio/certs/server/cert
        privateKey: /etc/istio/certs/server/key
        caCertificates: /etc/istio/certs/server/cacert
```

```yaml
      tls:
        credentialName: server-certs
        serverCertificate: /etc/istio/certs/server/cert
        privateKey: /etc/istio/certs/server/key
        caCertificates: /etc/istio/certs/server/cacert
```

```yaml
      tls:
        credentialName: server-certs
        serverCertificate: /etc/istio/certs/server/cert
        privateKey: /etc/istio/certs/server/key
        caCertificates: /etc/istio/certs/server/cacert
        tlsCertificates:
          - privateKey: /etc/istio/certs/server/key2
            serverCertificate: /etc/istio/certs/server/cert2
            caCertificates: /etc/istio/certs/server/cacert2
```

```yaml
      tls:
        credentialName: server-certs
        tlsCertificates:
          - privateKey: /etc/istio/certs/server/key2
            serverCertificate: /etc/istio/certs/server/cert2
            caCertificates: /etc/istio/certs/server/cacert2
```

With these allowed configurations, it is unclear which certificate will actually be used by the server:
```yaml
      tls:
        credentialName: server-certs
        serverCertificate: /etc/istio/certs/server/cert
        privateKey: /etc/istio/certs/server/key
        caCertificates: /etc/istio/certs/server/cacert
        tlsCertificates:
          - privateKey: /etc/istio/certs/server/key2
            serverCertificate: /etc/istio/certs/server/cert2
            caCertificates: /etc/istio/certs/server/cacert2
          - privateKey: /etc/istio/certs/server/key3
            serverCertificate: /etc/istio/certs/server/cert3
            caCertificates: /etc/istio/certs/server/cacert3
```

### Summary and Suggestion
The current implementation does not align with the documentation. Either the documentation needs to be corrected, the implementation updated, or the validation logic redesigned for clarity and consistency.

Additionally, it would be very helpful if the Gateway could support multiple Secrets—one for the server certificate(s), and others for client certificates. This would address common use cases and improve flexibility.

Thank you for considering these points. Please let me know if you need any further details or specific examples.

**Comment by ramaraochavali** [comment]
```
      tls:
        credentialNames:
          - server-certs
  ```

I am not able to reproduce this.  Added test case for that https://github.com/istio/istio/pull/56641 as well.  I do not get any error when I deploy this.

I will take a look at others. Basically when you specify credentialName/credentialNames, you can not specify private key, Ca Certificate and ServerCertificate.

Sorry, if the doc is not clear, I will review your cases and update.

**Comment by ramaraochavali** [comment]
> Additionally, it would be very helpful if the Gateway could support multiple Secrets—one for the server certificate(s), and others for client certificates. This would address common use cases and improve flexibility.

I suggest you please create another issue for this. This was never the intention of `credentialNames`

**Comment by fisju** [comment]
I have tried this configuration with both versions 1.26.0 and 1.26.1, but unfortunately, it consistently fails at the following section:
```yaml
      tls:
        credentialNames:
          - server-certs
```

From what I can see, it appears that this issue has already been addressed in this commit, but the fix has not yet been released:
https://github.com/istio/istio/commit/af4d964e0192748314850ac2f929270ce09afad6

Could you please let me know if this fix will be included in the next release? If possible, do you have an estimate of when that release might be available? Thank you very much for your help.
