### ISSUE TITLE
Add Gateway API ProxyProtocolPolicy filter for outbound PROXY protocol support

### ISSUE THREAD

**Issue by kirgene** [istio/istio#56644]
**Describe the feature request**

Add Gateway API support for configuring outbound PROXY protocol to backend services through a filter extension. Currently, configuring a Gateway to send PROXY protocol to backend services (e.g., after TLS termination) requires creating complex EnvoyFilters.

Proposed implementation using Gateway API filter pattern:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
 name: rabbitmq-route
spec:
 parentRefs:
 - name: gateway
   sectionName: amqp
 rules:
 - backendRefs:
   - name: rabbitmq
     port: 5672
   filters:
   - type: ExtensionRef
     extensionRef:
       group: networking.istio.io
       kind: ProxyProtocolPolicy
       name: send-proxy-v2
```
With corresponding CRD:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ProxyProtocolPolicy
metadata:
  name: send-proxy-v2
spec:
  version: V2  # or V1
```

**Describe alternatives you've considered**

Currently using a 50+ line EnvoyFilter to:

1. Create a custom cluster with PROXY protocol transport socket
2. Modify the TCP proxy filter to use this cluster

This works but is complex, error-prone, and requires deep Envoy knowledge.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Use cases:

- TLS-terminating gateways for TCP services (RabbitMQ, PostgreSQL, Redis) that need original client IPs
- Services requiring client IP for access control, rate limiting, or audit logs
- Common pattern when using cloud load balancers with externalTrafficPolicy: Local

This feature would:

- Follow Gateway API's extension model using filters
- Complement existing inbound PROXY protocol support via gatewayTopology.proxyProtocol
- Make Istio more accessible for TCP/non-HTTP workloads
- Reduce complexity for a common networking pattern
