### ISSUE TITLE
Gateway API: support DaemonSet

### ISSUE THREAD

**Issue by jgournet** [istio/istio#56658]
**Describe the feature request**
Thank you for implementing the "infrastructure" part in gateway API: it helps a lot !
Now, our current setup with istio-ingressgateway is to have it as a daemonset, so we can use NodePort.
=> would it be possible to implement "kind: DaemonSet" ?
Like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
data:
  deployment: |
    kind: DaemonSet
```
(taken from https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/ example)

**Describe alternatives you've considered**
- we tried going the "standard" way with AWS LoadBalancerController, but this setup adds too much bloat that we don't need (the controller itself, plus aws-vpc-cni) and we lose in terms of reactivity: when a node goes down, it takes more time for a new one to appear in the loadbalancer; compared to a DaemonSet where the loadbalancer targets any instance in the ASG
- we tried with Deployment + NodePort, but the NodePort makes max 1 pod per node mandatory, so it is difficult to scale up and down
=> I know that using DaemonSet + NodePort is not really standard, but this works very well in our setup, thus this Feature Request

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
I don't know if many others would want this feature, so I'm kind of hoping it's easy enough to implement.

**Comment by gordianberger** [comment]
This would be nice-to-have. If you want to run with externalTrafficPolicy=local you need a way to run it as daemonset.

**Comment by brandonp42** [comment]
@gordianberger it appears that PR https://github.com/istio/istio/pull/55283 gives you a way to cheat a little to make externalTrafficPolicy=local work. There's not an exact example in that PR but I found some comments in other places that led me to the example below. The biggest drawback is you have to manually set the number of replicas.

edit: to be clear, this isn't ideal but might be workable in some cases

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test123-gateway
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: test123-gateway-options
  listeners:
  - name: http
    hostname: 'test123.example.com'
    port: 80
    protocol: HTTP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test123-gateway-options
data:
  # see https://github.com/istio/istio/pull/55283
  deployment: |
    spec:
      replicas: 3
  service: |
    spec:
      externalTrafficPolicy: Local
```
