### ISSUE TITLE
ambient bypasses ingress ports in network policy

### ISSUE THREAD

**Issue by tareksha** [istio/istio#56659]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I have two pods: client and server. The server pod exposes port 8080 and the client pod sends requests to that port.
The server pod has this network policy attached - it allows traffic from the client only, to port 8080:
```yaml
spec:
  podSelector:
    matchLabels:
      app: test-server
  ingress:
   # traffic from client
   - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: test-client
        podSelector:
          matchLabels:
            app: test-client
     ports:
      - protocol: TCP
        port: 8080 # server port
```
It works just fine. Changing the port in the ingress rule to anything other than 8080 causes client requests to be blocked as expected.
Now I add both pods to ambiesh mesh via label `istio.io/dataplane-mode: ambient`, and add ingress port 15008 to the server network policy:
```yaml
spec:
  podSelector:
    matchLabels:
      app: test-server
  ingress:
   # traffic from client
   - from:
      # .. client pod (unchanged)
     ports:
      - protocol: TCP
        port: 8080 # server port
   # HBONE
   - ports:
      - protocol: TCP
        port: 15008
```
Works in ambient.
However, it seems like the port restriction in the ingress rule does not apply anymore in ambient mode. If I change the port in the network policy to any incorrect value:
```yaml
spec:
  podSelector:
    matchLabels:
      app: test-server
  ingress:
   # traffic from client
   - from:
      # .. client pod (unchanged)
     ports:
      - protocol: TCP
        port: 8083 # INCORRECT server port
   # HBONE
   - ports:
      - protocol: TCP
        port: 15008
```
The client can still send to port 8080, and in fact to any server port. I expected this to block the client as explained earlier. The target port in the ingress rule is simply ignored. Even if I remove all ingress rules from the server's network policy the server is still reachable by clients inside ambient mesh:
```yaml
spec:
  podSelector:
    matchLabels:
      app: test-server
  ingress:
   # HBONE
   - ports:
      - protocol: TCP
        port: 15008
```

This happens only if both the client pod and the server pod are inside the ambient mesh. Removing either pod (or both) from ambient mesh makes the network policy work as expected again: any port other than 8080 in the ingress rule causes client requests to be blocked.

The [documentation](https://istio.io/latest/docs/ambient/usage/networkpolicy/) states clearly that this should not happen:
> ambient does not and will never bypass Kubernetes NetworkPolicy enforcement

### Version

```Text
istio 1.26.1
kubernetes 1.30.10
CNI calico
```

**Comment by keithmattix** [comment]
NetworkPolicy is implemented by your CNI, not by ambient. For workloads in the mesh, use [AuthorizationPolicy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) to set your allow and deny rules. You can read more details [here](https://istio.io/latest/docs/ambient/usage/networkpolicy/). Hope this helps!

**Comment by sridhargaddam** [comment]
Adding to what @keithmattix mentioned above.

The key to understand this is as follows...

```
Once you have added applications to the ambient mesh, ambient’s secure L4 overlay will tunnel traffic between your pods over port 15008. Once secured traffic enters the target pod with a destination port of 15008, the traffic will be proxied back to the original destination port.

However, NetworkPolicy is enforced on the host, outside the pod. This means that if you have preexisting NetworkPolicy in place that, for example, will deny list inbound traffic to an ambient pod on every port but 443, you will have to add an exception to that NetworkPolicy for port 15008. Sidecar workloads receiving traffic will also need to allow inbound traffic on port 15008 to allow ambient workloads to communicate with them.
```

There are two scenarios to consider.

1. Traffic from another pod inside the Ambient Mesh
When you have a client pod that is part of the mesh trying to connect to the server pod, the NetworkPolicy on the host node inspects this packet and sees destination port as 15008. The ztunnel on the server node then receives this traffic, unwraps it, and forwards it to port 8080 inside the pod. So, we need HBONE port 15008 to support this scenario.

2. Traffic from a source outside the Ambient Mesh
When you have a client pod that is NOT part of the mesh trying to connect to the server pod, the NetworkPolicy on the host node inspects this packet and sees destination port as 8080. So we require the Network policy to include even the original port where the server is listening to support this use-case.

**Comment by tareksha** [comment]
> NetworkPolicy is implemented by your CNI, not by ambient. For workloads in the mesh, use [AuthorizationPolicy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) to set your allow and deny rules. You can read more details [here](https://istio.io/latest/docs/ambient/usage/networkpolicy/). Hope this helps!

@sridhargaddam @keithmattix the documentation states clearly
> ambient does not and will never bypass Kubernetes NetworkPolicy enforcement

However what I see here is that existing ingress rules in the network policy gets bypassed once the pods enter ambient mesh. The documentation is confusing because it shows an example of adding port 15008 while retaining existing ports in the policy:
```yaml
spec:
  # ...
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
    - port: 15008
      protocol: TCP
```

I am not questioning about adding port 15008. I am rather concerned about bypassing existing ingress rules in the network policy. If this is an intended behavior then the documentation should state that clearly.

We maintain a large and complex set of network policies with fine grained selectors and ports. Translating existing network policies to istio's authorization policies adds a significant TCO and also requires re-opening several security assessments. Additionally, the AuthorizationPolicy API does support such configurations, especially label selectors on traffic origin.

The documentation should state two things explicitly:
1. Existing ingress rules in NetowrkPolicy do not apply anymore in ambient mode.
2. Existing  NetworkPolicy must be translated to AuthorizationPolicy to retain the same security.
