### ISSUE TITLE
Istio Virtual Service Not Forwarding Traffic to Nginx/Appsmith Service

### ISSUE THREAD

**Issue by amitkbaid** [istio/istio#56679]
**Description**

I am running Istio 1.26.1 in my Kubernetes cluster, utilizing its load balancing functionality. The setup works correctly for five domains, but it fails when routing traffic to a service backed by an Nginx pod or an Appsmith deployment (which uses Nginx internally). When configuring an Istio Virtual Service to route traffic to the Nginx or Appsmith service, I encounter the error:
"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection timeout"

Port-forwarding the service directly shows the Nginx homepage, indicating the service and pod are running correctly. The issue appears specific to Istio's interaction with Nginx-based services (e.g., Nginx pod or Appsmith).

Environment

```
Istio Version: 1.26.1

Kubernetes Version: 1.32

Nginx Image: nginx (official Docker image)

Appsmith: deployed via appsmith helm chart running community edition

Cluster Setup: EKS
```

**Steps to Reproduce**

1. Deploy an Nginx pod:
2. kubectl create pod nginx --image=nginx --port=80
3. Expose the Nginx pod as a service:
4. kubectl expose pod nginx --port=80 --type=ClusterIP
5. Configure an Istio Virtual Service to route traffic to the Nginx service (see configuration below).
6. Access the domain configured in the Virtual Service.

Observe the error in the browser and Istio ingress gateway logs.

**Expected Behavior**

Traffic routed through the Istio Virtual Service should reach the Nginx or Appsmith service, displaying the respective homepage or application.

**Actual Behavior**

The request fails with a 503 error and the following message in the Istio ingress gateway logs:

[2025-06-18T11:01:04.285Z] "GET / HTTP/1.1" 503 URX,UF upstream_reset_before_response_started{connection_timeout} - "-" 0 114 20035 - "10.1.9.207" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36" "b56e8dcc-f79d-4391-9aab-fd3c0833ed89" "d.api.enncrypto.com" "10.1.9.54:80" outbound|443||appsmith.ops.svc.cluster.local - 10.1.10.154:443 10.1.9.207:25769 - -

Configuration - I am offloading SSL on the network load balancer, the certificate is attached to port 443 and after SSL termination Istio uses http protocol to communicate further. This is the reason why port 443 has protocol HTTP.

**Istio Gateway**

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - domain.com
    port:
      name: https
      number: 443
      protocol: HTTP
  - hosts:
    - domain.com
    port:
      name: http
      number: 80
      protocol: HTTP
```

**Istio Virtual Service**

```
spec:
  hosts:
  - domain.com
  gateways:
  - [gateway-name]
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: appsmith.ops.svc.cluster.local
        port:
          number: 443
```

**Additional Context**

The setup works correctly for other APIs/services not using Nginx.

I deployed a standalone Nginx pod to test, as Appsmith uses Nginx internally.

Port-forwarding the Nginx or Appsmith service directly works as expected.

The issue seems related to Istio's handling of Nginx-based services. Could this be a misconfiguration in the Virtual Service, Gateway, or an issue with Istio's compatibility with Nginx?

**Questions**

Is there a known issue with Istio 1.26.1 and Nginx-based services? I have another Istio 1.23 running on EKS 1.32, where the configuration works correctly. 

Are there specific configurations required for routing traffic to Nginx pods or Appsmith through Istio?
