### ISSUE TITLE
【Ask for help】How to implement the failover of the same application Pod between different clusters in istio non-flat network multi-control plane environment

### ISSUE THREAD

**Issue by cscowx** [istio/istio#56690]
Hello everyone

Environment Description:

![Image](https://github.com/user-attachments/assets/305286ed-e386-4853-9bae-a02d82136657)

### 【Nanjing cluster】

**k8s node information**
```
kubectl get node  -o wide --show-labels
NAME                        STATUS   ROLES    AGE   VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME    LABELS
k8s-master-01.k8s.cluster   Ready    <none>   34d   v1.32.3   192.168.110.210   <none>        Ubuntu 22.04.5 LTS   5.15.0-139-generic   containerd://2.0.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-master-01.k8s.cluster,kubernetes.io/os=linux,topology.istio.io/subzone=qinhuai,topology.kubernetes.io/region=china-jiangsu,topology.kubernetes.io/zone=nanjing
k8s-master-02.k8s.cluster   Ready    <none>   34d   v1.32.3   192.168.110.211   <none>        Ubuntu 22.04.5 LTS   5.15.0-140-generic   containerd://2.0.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-master-02.k8s.cluster,kubernetes.io/os=linux,topology.istio.io/subzone=qinhuai,topology.kubernetes.io/region=china-jiangsu,topology.kubernetes.io/zone=nanjing
k8s-node-01.k8s.cluster     Ready    <none>   34d   v1.32.3   192.168.110.218   <none>        Ubuntu 22.04.5 LTS   5.15.0-140-generic   containerd://2.0.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-node-01.k8s.cluster,kubernetes.io/os=linux,topology.istio.io/subzone=qinhuai,topology.kubernetes.io/region=china-jiangsu,topology.kubernetes.io/zone=nanjing
k8s-node-02.k8s.cluster     Ready    <none>   34d   v1.32.3   192.168.110.219   <none>        Ubuntu 22.04.5 LTS   5.15.0-140-generic   containerd://2.0.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-node-02.k8s.cluster,kubernetes.io/os=linux,topology.istio.io/subzone=qinhuai,topology.kubernetes.io/region=china-jiangsu,topology.kubernetes.io/zone=nanjing
```

**istio version:**
```
client version: 1.25.2
control plane version: 1.25.2
data plane version: 1.25.2 (3 proxies)
```

**kubectl get pods -n istio-system**
```
NAME                                    READY   STATUS    RESTARTS   AGE
istio-eastwestgateway-75b5588f4-f7fl9   1/1     Running   0          6d18h
istio-ingressgateway-6c475f9bdc-5q4jh   1/1     Running   0          6d18h
istiod-59c66bbb95-87vlc                 1/1     Running   0          47h
```

**nanjing helloworld pods:**
```
kubectl get pods -n sample -o wide --show-labels
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE                        NOMINATED NODE   READINESS GATES   LABELS
helloworld-v1-86f57ccb45-rv9cn   2/2     Running   0          56s   10.244.134.50   k8s-node-01.k8s.cluster     <none>           <none>            app=helloworld,pod-template-hash=86f57ccb45,security.istio.io/tlsMode=istio,service.istio.io/canonical-name=helloworld,service.istio.io/canonical-revision=v1,topology.istio.io/network=nj-k8s-cluster-network-01,topology.istio.io/subzone=qinhuai,topology.kubernetes.io/region=china-jiangsu,topology.kubernetes.io/zone=nanjing,version=v1
test-source-869888dfdc-9k6bt     2/2     Running   0          23h   10.244.220.54   k8s-master-01.k8s.cluster   <none>           <none>            app=test-source,pod-template-hash=869888dfdc,security.istio.io/tlsMode=istio,service.istio.io/canonical-name=test-source,service.istio.io/canonical-revision=latest,topology.istio.io/network=nj-k8s-cluster-network-01,topology.istio.io/subzone=qinhuai,topology.kubernetes.io/region=china-jiangsu,topology.kubernetes.io/zone=nanjing
```

**helloworld service information**
```
kubectl get service -n sample
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
curl         ClusterIP   10.96.18.117   <none>        80/TCP     33d
helloworld   ClusterIP   10.111.2.182   <none>        5000/TCP   34m
```

### 【Beijing cluster】

**k8s node information**
```
kubectl get node -o wide --show-labels
NAME                           STATUS   ROLES    AGE   VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME    LABELS
bj-k8s-master-01.k8s.cluster   Ready    <none>   34d   v1.32.3   192.168.110.230   <none>        Ubuntu 22.04.5 LTS   5.15.0-140-generic   containerd://2.0.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=bj-k8s-master-01.k8s.cluster,kubernetes.io/os=linux,topology.istio.io/subzone=haidian,topology.kubernetes.io/region=china-beijing,topology.kubernetes.io/zone=beijing
bj-k8s-node-01.k8s.cluster     Ready    <none>   33d   v1.32.3   192.168.110.231   <none>        Ubuntu 22.04.5 LTS   5.15.0-140-generic   containerd://2.0.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=bj-k8s-node-01.k8s.cluster,kubernetes.io/os=linux,topology.istio.io/subzone=haidian,topology.kubernetes.io/region=china-beijing,topology.kubernetes.io/zone=beijing
```

**istio version:**
```
client version: 1.25.2
control plane version: 1.25.2
data plane version: 1.25.2 (3 proxies)
```

**kubectl get pods -n istio-system**
```
NAME                                     READY   STATUS    RESTARTS   AGE
istio-eastwestgateway-77d5cb48bb-8xvqr   1/1     Running   0          8d
istio-ingressgateway-ddd4c67c9-xrcg2     1/1     Running   0          8d
istiod-84cb955954-mxq4r                  1/1     Running   0          27h
```

**beijing helloworld pods:**
```
kubectl get pods -n sample -o wide --show-labels
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE                           NOMINATED NODE   READINESS GATES   LABELS
helloworld-v2-6746879bdd-hpftf   2/2     Running   0          24h   10.245.88.124   bj-k8s-master-01.k8s.cluster   <none>           <none>            app=helloworld,pod-template-hash=6746879bdd,security.istio.io/tlsMode=istio,service.istio.io/canonical-name=helloworld,service.istio.io/canonical-revision=v2,topology.istio.io/network=bj-k8s-cluster-network-01,topology.istio.io/subzone=haidian,topology.kubernetes.io/region=china-beijing,topology.kubernetes.io/zone=beijing,version=v2
test-source-57846b986c-vjsbz     2/2     Running   0          25h   10.245.88.122   bj-k8s-master-01.k8s.cluster   <none>           <none>            app=test-source,pod-template-hash=57846b986c,security.istio.io/tlsMode=istio,service.istio.io/canonical-name=test-source,service.istio.io/canonical-revision=latest,topology.istio.io/network=bj-k8s-cluster-network-01,topology.istio.io/subzone=haidian,topology.kubernetes.io/region=china-beijing,topology.kubernetes.io/zone=beijing
```

**helloworld service information**
```
kubectl get service -n sample
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
curl         ClusterIP   10.116.123.48    <none>        80/TCP     33d
helloworld   ClusterIP   10.125.231.139   <none>        5000/TCP   33d
```

**nodePort information for eastwestgateway**
```
kubectl get service -n istio-system
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                           AGE
istio-eastwestgateway   NodePort       10.125.105.21    <none>        15021:35021/TCP,15443:35443/TCP,15012:35012/TCP,15017:35017/TCP   31d
istio-ingressgateway    LoadBalancer   10.121.75.84     <pending>     15021:31617/TCP,80:31874/TCP,443:31443/TCP                        33d
istiod                  ClusterIP      10.126.210.134   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP  
```

**The requirements I want to implement are as follows**
```
From nanjing cluster test-source-869888dfdc-9k6bt Pod a request on http://helloworld.sample.svc.cluster.local:5000/hello

Dispatch to different subsets based on the weight defined by the VirtualService configuration


When dispatching to a subset: When to-Nanjing-local-subsets, the local helloworld of nanjing cluster is visited, and mTLS is not used. If the node of Nanjing helloworld fails, then failover to Beijing and go to the East-West gateway of Beijing to visit the helloworld node of Beijing.

When dispatching to a subset: To-beijing-eastwestgateway-subsets, go to beijing's East-West gateway to visit Beijing's helloworld node, if the Beijing helloworld node fails, then failover to Nanjing cluster local helloworld
```

### 【Here's the Nanjing cluster configuration】
```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: helloworld-vs
  namespace: sample
spec:
  gateways:
    - mesh
    - istio-system/cross-network-gateway
  hosts:
    - "helloworld.sample.svc.cluster.local"
  http:
    - match:
        - port: 5000
      route:
        - destination:
            host: "helloworld.sample.svc.cluster.local"
            subset: to-nanjing-local-subsets
          weight: 50
        - destination:
            host: "helloworld.sample.svc.cluster.local"
            subset: to-beijing-eastwestgateway-subsets
          weight: 50
EOF


cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-dr
  namespace: sample
spec:
  host: "helloworld.sample.svc.cluster.local"
  subsets:
    - name: to-nanjing-local-subsets
      labels:
        app: "helloworld"
        version: "v1"
        topology.istio.io/network: "nj-k8s-cluster-network-01"
      trafficPolicy:
        portLevelSettings:
          - port:
              number: 5000
            tls:
              mode: DISABLE
        loadBalancer:
          simple: ROUND_ROBIN  
          localityLbSetting:
            enabled: true
            failover:
              - from: "china-jiangsu"
                to: "china-beijing"
    - name: to-beijing-eastwestgateway-subsets
      labels:
        app-gateway: "eastwestgateway"
        region: "china-beijing"
        topology.istio.io/network: "bj-k8s-cluster-network-01"
      trafficPolicy:
        portLevelSettings:
          - port:
              number: 5000
            tls:
              mode: ISTIO_MUTUAL
              sni: helloworld.sample.svc.cluster.local
        loadBalancer:
          simple: ROUND_ROBIN  
          localityLbSetting:
            enabled: true
            failover:
                - from: "china-beijing"
                  to: "china-jiangsu"
  trafficPolicy:
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 3600s
      maxEjectionPercent: 100
EOF

cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: to-bj-eastwest-gateway-se
  namespace: sample
spec:
  hosts:
    - "helloworld.sample.svc.cluster.local"
  ports:
    - number: 5000
      name: https-5000
      protocol: HTTPS
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
    - address: 192.168.110.230
      ports:
        https-5000: 35443
      locality: "china-beijing/beijing/eastwestgateway"
      labels:
        app: "helloworld"
        app-gateway: "eastwestgateway"
        region: "china-beijing"
        topology.istio.io/network: "bj-k8s-cluster-network-01"
EOF
```

### 【Here's the Beijing cluster configuration】
```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-eastwestgateway
    topology.istio.io/network: bj-k8s-cluster-network-01
  servers:
    - port:
        number: 15443
        name: https-15443
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: istio-eastwestgateway-certs
        minProtocolVersion: TLSV1_2
      hosts:
        - "helloworld.sample.svc.cluster.local"
        - "192.168.110.210"
EOF

cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: helloworld-vs
  namespace: istio-system
spec:
  hosts:
    - "helloworld.sample.svc.cluster.local"
    - "192.168.110.210"
  gateways:
    - istio-system/cross-network-gateway
  http:
    - route:
        - destination:
            host: helloworld.sample.svc.cluster.local
            port:
                number: 5000
EOF
```

**Comment by cscowx** [comment]
**istioctl proxy-config listener test-source-869888dfdc-9k6bt -n sample --port 5000**
```
ADDRESSES PORT MATCH                                    DESTINATION
0.0.0.0   5000 Trans: raw_buffer; App: http/1.1,h2c     Route: 5000
0.0.0.0   5000 ALL                                      PassthroughCluster
0.0.0.0   5000 SNI: helloworld.sample.svc.cluster.local Cluster: outbound|5000||helloworld.sample.svc.cluster.local
```

**istioctl proxy-config route test-source-869888dfdc-9k6bt -n sample --name 5000**
```
NAME     VHOST NAME                                   DOMAINS                                       MATCH     VIRTUAL SERVICE
5000     helloworld.sample.svc.cluster.local:5000     helloworld, helloworld.sample + 1 more...     /*        helloworld-vs.sample
```

**istioctl proxy-config cluster test-source-869888dfdc-9k6bt -n sample --fqdn "outbound|5000|to-nanjing-local-subsets|helloworld.sample.svc.cluster.local"**
```
SERVICE FQDN                            PORT     SUBSET                       DIRECTION     TYPE     DESTINATION RULE
helloworld.sample.svc.cluster.local     5000     to-nanjing-local-subsets     outbound      EDS      helloworld-dr.sample
```

**istioctl proxy-config cluster test-source-869888dfdc-9k6bt -n sample --fqdn "outbound|5000|to-beijing-eastwestgateway-subsets|helloworld.sample.svc.cluster.local"**
```
SERVICE FQDN                            PORT     SUBSET                                 DIRECTION     TYPE     DESTINATION RULE
helloworld.sample.svc.cluster.local     5000     to-beijing-eastwestgateway-subsets     outbound      EDS      helloworld-dr.sample
```

**istioctl proxy-config endpoints test-source-869888dfdc-9k6bt -n sample --cluster "outbound|5000|to-nanjing-local-subsets|helloworld.sample.svc.cluster.local"**
```
ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
10.244.134.50:5000     HEALTHY     OK                outbound|5000|to-nanjing-local-subsets|helloworld.sample.svc.cluster.local
```

**istioctl proxy-config endpoints test-source-869888dfdc-9k6bt -n sample --cluster "outbound|5000|to-beijing-eastwestgateway-subsets|helloworld.sample.svc.cluster.local"**
`ENDPOINT     STATUS     OUTLIER CHECK     CLUSTER`

**Why is there nothing here**


**Now the request of http://helloworld.sample.svc.cluster.local:5000/hello, a feedback test results are as follows:**

```
no healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
no healthy upstreamno healthy upstreamno healthy upstreamno healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
no healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
no healthy upstreamno healthy upstreamno healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
no healthy upstreamno healthy upstreamno healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
no healthy upstreamno healthy upstreamno healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
Hello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
no healthy upstreamHello version: v1, instance: helloworld-v1-86f57ccb45-rv9cn
```

**I canceled the synchronization between Nanjing and Beijing**
**Nanjing visits Beijing all by east-west gateway**
```
istioctl remote-clusters
NAME                                SECRET     STATUS     ISTIOD
kubernetes-admin-nj-k8s-cluster                synced     istiod-59c66bbb95-87vlc

istioctl remote-clusters
NAME                                SECRET     STATUS     ISTIOD
kubernetes-admin-bj-k8s-cluster                synced     istiod-84cb955954-mxq4r
```


**Could you please help me see what's going on? Is there something wrong with my configuration? Or is it impossible to fulfill my need?**

Or am I misinterpreting failover and can't use it here?

**Comment by cscowx** [comment]
### I also ran the following tests

**When I delete the helloworld service, I can see the entry**

```
kubectl delete service helloworld -n sample

istioctl proxy-config endpoints test-source-869888dfdc-9k6bt -n sample --cluster "outbound|5000|to-beijing-eastwestgateway-subsets|helloworld.sample.svc.cluster.local"
ENDPOINT                  STATUS      OUTLIER CHECK     CLUSTER
192.168.110.230:35443     HEALTHY     OK                outbound|5000|to-beijing-eastwestgateway-subsets|helloworld.sample.svc.cluster.local
```


**When you add service helloworld, you no longer see this entry**

```
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: 
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
EOF

istioctl proxy-config endpoints test-source-869888dfdc-9k6bt -n sample --cluster "outbound|5000|to-beijing-eastwestgateway-subsets|helloworld.sample.svc.cluster.local"
ENDPOINT                  STATUS      OUTLIER CHECK     CLUSTER
```
