### ISSUE TITLE
istio-cni-node DaemonSet - ArgoCD OutOfSync

### ISSUE THREAD

**Issue by lajchon** [istio/istio#56714]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

The issue is the same as https://github.com/istio/istio/issues/53001, where Istio deployed via ArgoCD is perpetually OutOfSync due to missing `resourceFieldRef.divisor` in istio-cni-node DaemonSet.

```
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: '0'
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: '0'
                  resource: limits.cpu
```

### Version

```Text
Helm Chart Version - istio-cni 1.26.1
```
