### ISSUE TITLE
Missing `grpc-status` trailer on responses with a size of exactly 65535

### ISSUE THREAD

**Issue by a-bigelow** [istio/istio#56734]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

We're experiencing a chronic issue since upgrading to Istio 1.26.1, specifically for requests where the `response_size` is exactly 65535.

In our flow we have two dotnet services, we'll call them A and B. Both services have sidecars. Service A requests data from service B as part of a larger microservice flow.

The issue itself manifests as the below error being emitted from Service A (client):
```
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="No grpc-status found on response.")
```
In both envoy spans from any trace where this occurs, the `response_size` field is **always** 65535. Both envoy spans likewise have `grpc.status_code:0`, which seems to indicate that the trailer is being dropped between Service A's envoy sidecar and Service A's gRPC client.

We did manage to grab some debug logs from one such event:
```
2025-06-18T03:51:33.244200Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1805	[Tags: "ConnectionId":"301"] Http2Visitor: remaining data payload: 16384, stream_id: 3403, end_stream: false	thread=22
2025-06-18T03:51:33.244223Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1805	[Tags: "ConnectionId":"301"] Http2Visitor: remaining data payload: 16384, stream_id: 3403, end_stream: false	thread=22
2025-06-18T03:51:33.244236Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1805	[Tags: "ConnectionId":"301"] Http2Visitor: remaining data payload: 16384, stream_id: 3403, end_stream: false	thread=22
2025-06-18T03:51:33.244242Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1805	[Tags: "ConnectionId":"301"] Http2Visitor: remaining data payload: 16383, stream_id: 3403, end_stream: false	thread=22
2025-06-18T03:51:33.244258Z	debug	envoy client external/envoy/source/common/http/codec_client.cc:129	[Tags: "ConnectionId":"301"] response complete	thread=22
2025-06-18T03:51:33.244273Z	debug	envoy pool external/envoy/source/common/conn_pool/conn_pool_base.cc:254	[Tags: "ConnectionId":"301"] destroying stream: 0 active remaining, readyForStream true, currentUnusedCapacity 536869210	thread=22
2025-06-18T03:51:33.244295Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1938	[Tags: "ConnectionId":"41","StreamId":"13029331410971009804"] encoding trailers via codec:
'grpc-status', '0'
thread=22
2025-06-18T03:51:33.244307Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1386	[Tags: "ConnectionId":"301"] stream 3403 closed: 0	thread=22
2025-06-18T03:51:33.244310Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1449	[Tags: "ConnectionId":"301"] Recouping 0 bytes of flow control window for stream 3403.	thread=22
2025-06-18T03:51:33.244827Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:2021	[Tags: "ConnectionId":"41","StreamId":"13029331410971009804"] Codec completed encoding stream.	thread=22
2025-06-18T03:51:33.244916Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1386	[Tags: "ConnectionId":"41"] stream 14695 closed: 0	thread=22
2025-06-18T03:51:33.244928Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1449	[Tags: "ConnectionId":"41"] Recouping 0 bytes of flow control window for stream 14695.	thread=22
```

I'm not versed in envoy debug logging, but it seems like the data frame completely exhausts *something*, and this might cause trailers to be dropped.

## What we've tried

With an issue like this the obvious first guess is connection/stream size limitations, and adjusting these does help temporarily. E.g.

(rest of `EnvoyFilter` redacted)
```yaml
# Applied to both SIDECAR_INBOUND and SIDECAR_OUTBOUND
typed_config:
  '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
  http2_protocol_options:
    initialConnectionWindowSize: 4194304
    initialStreamWindowSize: 2097152
```
We tried a few combinations of sizes for these parameters, and the consistent behavior was that we could then process 1-2 requests with `response_size:65535` before returning to the old behavior, at which point we'd need to cycle pods to see any change. We do configure our gRPC clients with aggressive connection lifetime and re-use behavior, so it's possible we're over-extending a connection between the client and envoy itself. 

Currently the only "fix" that works is to bypass envoy entirely for the flow between Service A and Service B. This brings its own issues and obviously we'd prefer to keep these services in the mesh, however it does confirm where the issue is originating from.

### Version

```Text
❯ ./istioctl version
client version: 1.26.1
control plane version: 1.26.1
data plane version: 1.26.1 (86 proxies)
```

### Additional Information

`istioctl bug-report` contains a lot of sensitive information that I cannot share here. Below is the high level versioning information.

If any specific debug metrics would be helpful, I can anonymize them. Currently there are no pods running that have experienced the issue since they all have envoy bypassed on the relevant ports.

```
Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2025-06-23 12:03:57.573283576 -0400 EDT



Cluster endpoint: <REDACTED>
CLI version:
version.BuildInfo{Version:"1.26.1", GitRevision:"2ce3ad897b984a045d9d5f80a8c1bb8eefdf88f5", GolangVersion:"go1.24.2", BuildStatus:"Clean", GitTag:"1.26.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.26.1", GitRevision:"2ce3ad897b984a045d9d5f80a8c1bb8eefdf88f5", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.26.1"}}, version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.26.1", GitRevision:"2ce3ad897b984a045d9d5f80a8c1bb8eefdf88f5", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.26.1"}}, version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.26.1", GitRevision:"2ce3ad897b984a045d9d5f80a8c1bb8eefdf88f5", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.26.1"}}, version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.26.1", GitRevision:"2ce3ad897b984a045d9d5f80a8c1bb8eefdf88f5", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.26.1"}}, version.ServerInfo{Component:"pilot", Revision:"default", Info:version.BuildInfo{Version:"1.26.1", GitRevision:"2ce3ad897b984a045d9d5f80a8c1bb8eefdf88f5", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.26.1"}}}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.26.1}
```

**Comment by a-bigelow** [comment]
Per #34169 it seems like there's some confusion about where to put these configs, so I'm open to more direction on what changing these sizes actually looks like in a proper `EnvoyFilter`. As far as I can tell, `DestinationRule` does not support these parameters.

What we currently have, anonymized of course:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http2-protocol-options-service-a
  namespace: acme
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http2_protocol_options:
            initialConnectionWindowSize: 4194304
            initialStreamWindowSize: 2097152
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http2_protocol_options:
            initialConnectionWindowSize: 4194304
            initialStreamWindowSize: 2097152
  workloadSelector:
    labels:
      app: service-a

```

**Comment by jSherz** [comment]
Purely out of interest, have you tried disabling oghttp2?

e.g. in the Helm values file:
```yaml
istiod:
  meshConfig:
    defaultConfig:
      runtimeValues:
        "envoy.reloadable_features.http2_use_oghttp2": "false"
```

I'm in the process of trying to replicate the same error as we saw it after upgrading. With the following applied, and thus nghttp2 in use, the error went away.

**Comment by a-bigelow** [comment]
> Purely out of interest, have you tried disabling oghttp2?
> 
> e.g. in the Helm values file:
> 
> istiod:
>   meshConfig:
>     defaultConfig:
>       runtimeValues:
>         "envoy.reloadable_features.http2_use_oghttp2": "false"
> 
> I'm in the process of trying to replicate the same error as we saw it after upgrading. With the following applied, and thus nghttp2 in use, the error went away.

We haven't tried that. I'll check for details on the setting, but if you have any understanding of how the two behaviors differ, I'm all ears.

**Comment by jSherz** [comment]
> We haven't tried that. I'll check for details on the setting, but if you have any understanding of how the two behaviors differ, I'm all ears.

It's a different codec, with oghttp2 eventually being the only one available.

Thanks to your information about the response size, I've managed to replicate the problem and I've attached two packet captures showing a working request (nghttp2) and a failing one (oghttp2).

[pcaps.zip](https://github.com/user-attachments/files/21922318/pcaps.zip)

I replicated it by crafting a response that was exactly 65535 bytes (as measured by Envoy in the logs). No other requests etc were required - it failed immediately on the first request with the C# error you mentioned.

**Comment by a-bigelow** [comment]
Awesome, glad that datapoint was helpful. I'll give that setting a shot!

**Comment by purkhusid** [comment]
I don't think this issue is resolved. We encountered this as well. I'll give the setting a go but this should also be fixed for the default configuration before marked as resolved.

**Comment by purkhusid** [comment]
I can also confirm that setting 
```
istiod:
  meshConfig:
    defaultConfig:
      runtimeValues:
        "envoy.reloadable_features.http2_use_oghttp2": "false"
```
does work
