### ISSUE TITLE
TCPRoute doesn't bind to multiple parents

### ISSUE THREAD

**Issue by solidDoWant** [istio/istio#56769]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

TCPRoute resources do not bind to multiple parents. Multiple separate routes with one parent each (and everything else the same) work as expected. Traffic is properly handled/passed by one of the gateway instances. The other receives the traffic and ignores/drops it.

### Version

```Text
$ istioctl version
client version: 1.23.3
control plane version: 1.26.2
data plane version: 1.26.2 (7 proxies)
$ kubectl version 
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3
```

### Additional Information

This does not work:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: example-route
spec:
  parentRefs:
    - name: internal-gateway
      namespace: networking
    - name: external-gateway
      namespace: networking
  rules:
    - backendRefs:
        - name: backend
          port: 12345
```

This works:
```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: example-route-internal
spec:
  parentRefs:
    - name: internal-gateway
      namespace: networking
  rules:
    - backendRefs:
        - name: backend
          port: 12345
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: example-route-external
spec:
  parentRefs:
    - name: external-gateway
      namespace: networking
  rules:
    - backendRefs:
        - name: backend
          port: 12345
```
