### ISSUE TITLE
VirtualService doesn't work with Istio Ambient when Waypoint is K8s Gatway API Gateway

### ISSUE THREAD

**Issue by aryan16** [istio/istio#56773]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I have created a waypoint using K8s Gateway API and Istio's VirtualService like following
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE

------
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "productpage.default.svc.cluster.local"
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

The above-mentioned virtualService doesn't work because of this - https://github.com/istio/istio/pull/47101. If I create HTTPRoute instead of VirtualService the routing rule works fine.

But the main issue is that the same virutalService works well with sidecar based mesh using K8s Gateway API Gateway (basically it will be reconciled by sidecars in the mesh). If a user migrates from Istio Sidecar based mesh to Ambient or they are using Ambient in one of the namespaces and somehow using common virtualService then they would be broken until they change their VirutalService to HTTPRoutes. 

Is this intentional? Needs some guidance from maintainers on this.

### Version

```Text
client version: 1.26.1
control plane version: 1.26.1
data plane version: 1.26.1 (11 proxies)
```

**Comment by Stevenjin8** [comment]
@aryan16 can you send your service and the namespace

**Comment by aryan16** [comment]
**Namespace**

```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-06-18T17:12:04Z"
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    kubernetes.io/metadata.name: default
  name: default
  resourceVersion: "1750273569607791001"
  uid: a35f6ddb-83e6-4e29-aca7-406cac63621d
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Service**

```
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
```

**Comment by Stevenjin8** [comment]
Hmmm, I don't see anything clearly wrong. How are you making requests?

**Comment by craigbox** [comment]
What did you expect this VS to do?

If you want it to "attach /productpage to a gateway" like [this example](https://istio.io/latest/docs/examples/bookinfo/#determine-the-ingress-ip-and-port) / [this object](https://raw.githubusercontent.com/istio/istio/release-1.26/samples/bookinfo/networking/bookinfo-gateway.yaml) then the object would have needed to have 

```
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
```

in which case, [the issue you linked above would apply](https://github.com/istio/istio/pull/47101): there is no way to attach this to a Kubernetes Gateway, only [an Istio Gateway](https://istio.io/latest/docs/concepts/traffic-management/#gateways).

What you appear to have a is a _mesh_ route which would take traffic for productpage:9080 and redirect to productpage:9080.

Following the discussion on this at the last WG meeting, there was disagreement on whether something _like_ this would work as a mesh route. 

Let me confirm that you can set up a subset service

```
apiVersion: v1
kind: Service
metadata:
  name: reviews-v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
    version: v1
```

and then use an HTTPRoute:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reviews
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: reviews
    port: 9080
  rules:
  - backendRefs:
    - name: reviews-v1
      port: 9080
```

or a VirtualService: 

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews-v1
EOF
```

and both have the same result.
