### ISSUE TITLE
`WasmPlugin` requires `oci://` prefix, where documentation indicates this is optional

### ISSUE THREAD

**Issue by DerekTBrown** [istio/istio#56772]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

## Problem
Istio's `WasmPlugin` documentation for `.spec.url` states:
> If no scheme is present, defaults to oci://, referencing an OCI image.[^1]

However, when you try to create a `WasmPlugin` with a valid image reference but without the `oci://` prefix, the manifest is rejected with:

```
WasmPlugin.extensions.istio.io "cert-client-id-matches-header" is invalid: spec.url: Invalid value: "string": url must have schema one of [http, https, file, oci]
```

## Impact
I am trying to build a `WasmPlugin` development environment. In order for Tilt to properly handle building, pushing, and replacing the image reference, the image must be a standard Kubernetes image reference. The `oci://` prefix prevents Tilt from working correctly.[^2]

## Proposed Fix
Modify Istio to honor the contract in the documentation; if a protocol scheme prefix is absent, assume `oci://`.

[^1]: https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#WasmPlugin-url
[^2]: https://github.com/tilt-dev/tilt/issues/6579

### Version

```Text
Istio Version: v1.26.2
```

**Comment by zirain** [comment]
what's your value in `.spec.url`?
I can passed the validation with following:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: basic-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://ghcr.io/istio-ecosystem/wasm-extensions/basic_auth:1.12.0
  phase: AUTHN
  pluginConfig:
    basic_auth_rules:
      - prefix: "/productpage"
        request_methods:
          - "GET"
          - "POST"
        credentials:
          - "ok:test"
          - "YWRtaW4zOmFkbWluMw=="

```
