### ISSUE TITLE
Add "ignoreAuthorityCase" similar to "ignoreUriCase" in VirtualService authority match

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#56801]
Is it possible to add `ignoreAuthorityCase` similar to `ignoreUriCase` in VirtualService authority match?

Currently this fails with a 404
```
apiVersion: networking.istio.io/v1
kind: VirtualService
spec:
  hosts:
  - test.uppercase.global
  http:
  - match:
    - authority:
        prefix: test.uppercase.global
    route:
    - destination:
        host: test.namespace.svc.cluster.local
        port:
          number: 8080

$ curl -v http://test.Uppercase.global/status
```

Workaround
```
apiVersion: networking.istio.io/v1
kind: VirtualService
spec:
  hosts:
  - test.uppercase.global
  http:
  - match:
    - authority:
        prefix: test.uppercase.global
    - authority:
        prefix: test.Uppercase.global
    route:
    - destination:
        host: test.namespace.svc.cluster.local
        port:
          number: 8080
```

Feature Request
```
apiVersion: networking.istio.io/v1
kind: VirtualService
spec:
  hosts:
  - test.uppercase.global
  http:
  - match:
    - authority:
        prefix: test.uppercase.global
      ignoreAuthorityCase: true
    route:
    - destination:
        host: test.namespace.svc.cluster.local
        port:
          number: 8080
```

The workaround is fine but since some of our VirtualServices are quite big, it makes it hard to read and debug
