### ISSUE TITLE
Faulty regex in VirtualService blocking Route discovery service

### ISSUE THREAD

**Issue by PavloGomeniuk** [istio/istio#56807]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hi Team, thank you for your efforts in building Istio!

Recently we have faced the issue when one of our Developers had added VirtualService with faulty regex style not RE2 and after some time when we were investigating another issue with Istio and restarted Istio Gateway Pods our all internal domains(attached to this Istio Gateway) started to return 404 error.

Detailed explanation and timeline:
1. Our Developer added VirtualService with faulty regex like this:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: name
    kustomize.toolkit.fluxcd.io/namespace: name
  name: vs
  namespace: test
spec:
  gateways:
  - istio-ingress-int/ingress-config-gateway-int #We have one Gateway for internal domains
  hosts:
  - test.io
  http:
   - match:
    - uri:
        regex: ^/api/data/[a-zA-Z0-9_]{3,20}/import/tests(?.*)?$
    - uri:
        regex: ^/api/data/[a-zA-Z0-9_]{3,20}/(events)(/.*)?(?.*)?$
    route:
    - destination:
        host: test.svc.cluster.local
        port:
          number: 8080
```

  2. After a few days another Developer has come with issue that after changing URL in another VirtualService and namespace new URL still not working but previous does

3. During the investigation Istio gateway pods were restarted.

4. After some time all Developers started reporting that theirs internal domains return 404
In logs for Istio gateway pods we had:
` "method":"GET","bytes_sent":0,"response_code_details":"route_not_found" "response_code":404`

5. With istioctl routes command we found that no routes were created in gateway Pods

6. From istiod pods we found error which was the root cause:
`2025-06-23T10:21:52.467650Z	warn	delta	ADS:RDS: ACK ERROR istio-ingressgateway-int-1-24-1-884fc4986-r8rfb.istio-ingress-int-359772 Internal:invalid perl operator: (?.`

7. After fixing faulty VirtualService regex all works as usual

### Version

```Text
❯ istioctl version #Side-car mode
client version: 1.26.0
control plane version: 1.24.1
data plane version: 1.24.1 (661 proxies)
❯ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.9-gke.1044001
```

### Additional Information

As a mitigation steps we've implemented alerting for this kind of log and istioctl validation step in our pipelines, but I kindly ask you to make changes to Istio to prevent such VirtualService to applying to k8s since its very hard to find after which VS change caused this error. Fortunately, this happened in the QA environment.

Thanks in advance!

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [x] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [x] Test and Release
- [x] User Experience
- [x] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
