### ISSUE TITLE
Istio does not parse certs with negative serial numbers

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#56815]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

As of Go 1.23, parsing x509 certificates with negative serial numbers errors. This comment summarizes it well https://github.com/cert-manager/trust-manager/issues/183#issuecomment-2524807308. Basically, we should gracefully handle certificates with negative serial numbers. This could be by accepting them or if we encounter one, we ignore it. Right now, if there is a file with a bunch of root certs and one has a negative serial number, all certs there are ignored.

### Version

```Text
istio versions built on go 1.23
```

**Comment by GabrielAlacchi** [comment]
We ran into this issue as well when injecting custom ca-certificates to the system certificate store /etc/ssl/certs/ca-certificates.crt. The certs are not in our control, and some have negative serial numbers. 

I believe we can work around this in the short-term by injecting `GODEBUG=x509negativeserial=1` which is a runtime flag that can go back to the pre-1.23 functionality in the golang runtime.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: enable-x509-negative-serial
  namespace: istio-system
spec:
  environmentVariables:
    GODEBUG: "x509negativeserial=1"
```
