### ISSUE TITLE
Multi primary model integrated with multi remote (multi cluster)

### ISSUE THREAD

**Issue by tnubeo1111** [istio/istio#56828]
Hello, I am currently deploying a multi-primary cluster model combined with a multi-remote cluster. I have successfully set up models such as primary-remote and multi-primary. However, I want to combine both of these models and the desired result is that the 2 remotes can see and call each other.

My model is as follows:

![Image](https://github.com/user-attachments/assets/4e98eef7-21a3-4815-9f7d-e60ba98f191f)

But now the result is not expected because the pods at the remotes cannot see each other.
```
root@master-istio:~/istio-primary-remote/values-helm/multi-primary# bash auto-verify-3-4.sh 
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
Hello version: v2, instance: helloworld-v2-7dcd9b496d-r2fdp
```

Here are my config files:
1. values-cluster1.yaml
```
_internal_defaults_do_not_set:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
#  pilot:
#    hub: "vcr.infiniband.vn/meaas/istio"
#    tag: "1.25.2"
  global:
#    hub: "vcr.infiniband.vn/meaas/istio"
#    tag: "1.25.2"
    proxy:
      outlierLogPath: ""
    meshID: mesh1
    multiCluster:
      enabled: true
      clusterName: "cluster1"
    network: "network1"
    meshNetworks:
      network1:
        endpoints:
          - fromRegistry: cluster1   
          - fromRegistry: cluster3
        gateways:
          - address: 172.25.157.223
            port: 15443
          - address: 172.25.157.231
            port: 15443
      network2:
        endpoints:
          - fromRegistry: cluster2
          - fromRegistry: cluster4
        gateways:
          - address: 172.25.157.184
            port: 15443
          - address: 172.25.157.136
            port: 15443
    externalIstiod: true
```
2. values-cluster2.yaml
```
_internal_defaults_do_not_set:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"

#  pilot:
#    hub: "vcr.infiniband.vn/meaas/istio"
#    tag: "1.25.2"
  global:
#    hub: "vcr.infiniband.vn/meaas/istio"
#    tag: "1.25.2"
    proxy:
      outlierLogPath: ""
    meshID: mesh1
    multiCluster:
      enabled: true
      clusterName: "cluster2"
    network: "network2"
    meshNetworks:
      network1:
        endpoints:
          - fromRegistry: cluster1                                                               
          - fromRegistry: cluster3
        gateways:
          - address: 172.25.157.223
            port: 15443
          - address: 172.25.157.231
            port: 15443
      network2:
        endpoints:
          - fromRegistry: cluster2                                                               
          - fromRegistry: cluster4
        gateways:
          - address: 172.25.157.184
            port: 15443
          - address: 172.25.157.136
            port: 15443
    externalIstiod: true
```

3. values-cluster3.yaml
```
_internal_defaults_do_not_set:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  global:
#    hub: "vcr.infiniband.vn/meaas/istio"
#    tag: "1.25.2"
    proxy:
      outlierLogPath: ""
    multiCluster:
      enabled: true
      clusterName: "cluster3"
    network: "network1"
    meshNetworks:
      network1:
        endpoints:
          - fromRegistry: cluster1
          - fromRegistry: cluster3
        gateways:
          - address: 172.25.157.223
            port: 15443
          - address: 172.25.157.231
            port: 15443
      network2:
        endpoints:
          - fromRegistry: cluster2
          - fromRegistry: cluster4
        gateways:
          - address: 172.25.157.184
            port: 15443
          - address: 172.25.157.136
            port: 15443
    configCluster: "true"
    remotePilotAddress: "172.25.157.223"
  istiodRemote:
    enabled: true
    injectionPath: /inject/cluster/cluster3/net/network1
```

4.  values-cluster4.yaml
```
_internal_defaults_do_not_set:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  global:
#    hub: "vcr.infiniband.vn/meaas/istio"
#    tag: "1.25.2"
    proxy:
      outlierLogPath: ""
    multiCluster:
      enabled: true
      clusterName: "cluster4"
    network: "network2"
    meshNetworks:
      network1:
        endpoints:
          - fromRegistry: cluster1
          - fromRegistry: cluster3
        gateways:
          - address: 172.25.157.223
            port: 15443
          - address: 172.25.157.231
            port: 15443
      network2:
        endpoints:
          - fromRegistry: cluster2
          - fromRegistry: cluster4
        gateways:
          - address: 172.25.157.184
            port: 15443
          - address: 172.25.157.136
            port: 15443
    configCluster: "true"
    remotePilotAddress: "172.25.157.184"
  istiodRemote:
    enabled: true
    injectionPath: /inject/cluster/cluster4/net/network2
```

At the same time, I have exposed service port 15443 (cross) on 2 primary clusters.

Hope everyone can help me with my problem. Thanks.
