### ISSUE TITLE
ServiceEntry hostname conflicts across namespaces cause incorrect egress gateway routing

### ISSUE THREAD

**Issue by antony-ramos** [istio/istio#56826]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When multiple ServiceEntry resources are defined in different namespaces for the same hostname (e.g., istio.com), even with specific `exportTo `configurations, Istio experiences routing conflicts when setting TLSRoute. Traffic then gets directed to the wrong egress gateway based on the order in which the resources were created, leading to violations of network policy boundaries and connection failures.

_The code to reproduce the bug is available at the end of the message. Please let me know if you require any further information._

## Expected Behavior

- App-1 (namespace: `app-1`) should route `istio.com` traffic through Gateway-1 (namespace: `gw-1`)
- App-2 (namespace: `app-2`) should route `istio.com` traffic through Gateway-2 (namespace: `gw-2`)
- ServiceEntries with `exportTo: [".", "app-1"]` and `exportTo: [".", "app-2"]` should be properly scoped

## Actual Behavior

- The first created ServiceEntry "wins" globally for the hostname
- Traffic from app-1 and app-2 gets routed to the same egress gateway
- Traffic from the wrong app is routed to the wrong gateway and blocked by network policies
- Connection resets occur due to the network policy

## Root Cause

Despite using targeted `exportTo` configurations:

- `gw-1/ServiceEntry`: `exportTo: [".", "app-1"]`
- `gw-2/ServiceEntry`: `exportTo: [".", "app-2"]`

Istio's service discovery merges entries for the same hostname globally. The Gateway API TLSRoute create conflicting routing decisions where the first registered ServiceEntry determines the backend for all traffic to `istio.com`. This is not the case for HTTPRoute.

The problem stems from https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/gateway/route_collections.go#L389. It looks like exportTo from Service Entries (or their namespaces) isn't being used when Virtual Services are created. I believe this causes a single Virtual Service to be generated for both the Service Entry and global access, which then blocks a second Virtual Service from being made.

## Reproduction Steps

1. Apply gateway configurations in order:

   ```bash
   kubectl apply -f gw-1.yaml
   kubectl apply -f gw-2.yaml
   ```

2. Apply application configurations:

   ```bash
   kubectl apply -f app-1.yaml
   kubectl apply -f app-2.yaml
   ```

3. Test app-1 (succeeds - first gateway wins):

   ```bash
   kubectl exec -n app-1 -it curl-mesh -- curl https://istio.com -I
   # Returns: 200 OK
   ```

4. Test app-2 (fails - routed to gw-1 but blocked by network policy):

   ```bash
   kubectl exec -n app-2 -it curl-mesh -- curl https://istio.com -I
   # Returns: curl: (35) Recv failure: Connection reset by peer
   kubectl logs -n app-2 curl-mesh -c istio-proxy
   # [2025-06-30T09:44:10.630Z] "- - -" 0 UF,URX - - "-" 0 0 10005 - "-" "-" "-" "-" "10.244.2.65:443" outbound|443||internet-egress-gateway-istio.gw-1.svc.cluster.local - 88.99.216.125:443 10.244.3.84:46514 istio.com -
   ```

5. Verify routing conflict by recreating gw-1:
   ```bash
   kubectl delete -f gw-1.yaml
   kubectl apply -f gw-1.yaml
   ```
   Now app-2 works but app-1 fails.

## Architecture Details

- **Gateway namespaces**: `gw-1`, `gw-2` (managed by the infrastructure team)
- **Application namespaces**: `app-1`, `app-2` (managed by separate dev teams)
- **Network isolation**: NetworkPolicies prevent cross-team access
- **ServiceEntry scoping**: `exportTo: [".", "app-X"]` to allow hosts requests to specific namespaces
- **Gateway API**: Using Gateway, HTTPRoute, and TLSRoute resources
- **Sidecar configuration**: `REGISTRY_ONLY` mode to expose only external ressources if declared as Service Entry

## Error Logs

**App-2 sidecar attempting to reach gw-1 (blocked by NetworkPolicy):**

```
[2025-06-30T09:39:15.753Z] "- - -" 0 UF,URX - - "-" 0 0 10001 - "-" "-" "-" "-" "10.244.1.33:443" outbound|443||internet-egress-gateway-istio.gw-1.svc.cluster.local - 88.99.216.125:443 10.244.1.62:52104 istio.com -
```

**App-1 sidecar incorrectly routed to gw-2 after recreation:**

```
[2025-06-30T09:44:10.630Z] "- - -" 0 UF,URX - - "-" 0 0 10005 - "-" "-" "-" "-" "10.244.2.65:443" outbound|443||internet-egress-gateway-istio.gw-2.svc.cluster.local - 88.99.216.125:443 10.244.3.84:46514 istio.com -
```

## Key Observations

1. **Protocol-specific**: HTTP traffic routes correctly, HTTPS/TLS shows the conflict
2. **Creation order dependency**: First ServiceEntry registration determines global routing
3. **exportTo ineffective**: Scoped exports don't prevent hostname routing conflicts

## Code to reproduce

- Kubernetes Cluster 1.31
- Istio must be installed with helm chart following https://istio.io/latest/docs/setup/install/helm/ and with `PILOT_ENABLE_ALPHA_GATEWAY_API `
```
      meshConfig:
        accessLogFile: /dev/stdout
        defaultConfig:
          holdApplicationUntilProxyStarts: true
      pilot:
        env:
          PILOT_ENABLE_ALPHA_GATEWAY_API: "true"

```
- CRD from experimental channel of gateway api must be installed: https://gateway-api.sigs.k8s.io/guides/#install-experimental-channel

<details>
<summary>app-1.yaml</summary>

```yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: app-1
  labels:
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: limit-egress-discovery
  namespace: app-1
spec:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-egress-gateways-system-ns
  namespace: app-1
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gw-1
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    security.radiofrance.dev/reference: allow-to-host-metadata
  name: allow-to-host-metadata
  namespace: app-1
spec:
  egress:
    - ports:
        - port: 80
      to:
        - ipBlock:
            cidr: 169.254.169.254/32
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    security.radiofrance.dev/reference: allow-to-istio-ns
  name: allow-to-istio-ns
  namespace: app-1
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    security.radiofrance.dev/reference: allow-to-kube-dns
  name: allow-to-kube-dns
  namespace: app-1
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-mtls
  namespace: app-1
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl-mesh
    sidecar.istio.io/inject: "true"
    version: v1
  name: curl-mesh
  namespace: app-1
spec:
  containers:
    - args:
        - infinity
      command:
        - sleep
      image: curlimages/curl:latest
      name: curl
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl-no-mesh
    sidecar.istio.io/inject: "false"
    version: v1
  name: curl-no-mesh
  namespace: app-1
spec:
  containers:
    - args:
        - infinity
      command:
        - sleep
      image: curlimages/curl:latest
      name: curl
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
  restartPolicy: Always
```

</details>

<details>
<summary>app-2.yaml</summary>

```yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: app-2
  labels:
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: limit-egress-discovery
  namespace: app-2
spec:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-egress-gateways-system-ns
  namespace: app-2
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gw-2
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    security.radiofrance.dev/reference: allow-to-host-metadata
  name: allow-to-host-metadata
  namespace: app-2
spec:
  egress:
    - ports:
        - port: 80
      to:
        - ipBlock:
            cidr: 169.254.169.254/32
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    security.radiofrance.dev/reference: allow-to-istio-ns
  name: allow-to-istio-ns
  namespace: app-2
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    security.radiofrance.dev/reference: allow-to-kube-dns
  name: allow-to-kube-dns
  namespace: app-2
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-mtls
  namespace: app-2
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl-mesh
    sidecar.istio.io/inject: "true"
    version: v1
  name: curl-mesh
  namespace: app-2
spec:
  containers:
    - args:
        - infinity
      command:
        - sleep
      image: curlimages/curl:latest
      name: curl
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl-no-mesh
    sidecar.istio.io/inject: "false"
    version: v1
  name: curl-no-mesh
  namespace: app-2
spec:
  containers:
    - args:
        - infinity
      command:
        - sleep
      image: curlimages/curl:latest
      name: curl
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
  restartPolicy: Always
```
</details>

<details>
<summary>gw-1.yaml</summary>

```yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: gw-1
  labels:
    istio-injection: enabled
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    networking.istio.io/service-type: ClusterIP
  name: internet-egress-gateway
  namespace: gw-1
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: istio.com
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: istio.com
      name: https
      port: 443
      protocol: TLS
      tls:
        mode: Passthrough
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: direct-istio
  namespace: gw-1
spec:
  parentRefs:
    - group: networking.istio.io
      kind: ServiceEntry
      name: istio.com
  rules:
    - backendRefs:
        - name: internet-egress-gateway-istio
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forward-istio-com
  namespace: gw-1
spec:
  hostnames:
    - istio.com
  parentRefs:
    - name: internet-egress-gateway
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: istio.com
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: direct-istio.com
  namespace: gw-1
spec:
  hostnames:
    - istio.com
  parentRefs:
    - group: networking.istio.io
      kind: ServiceEntry
      name: istio.com
  rules:
    - backendRefs:
        - name: internet-egress-gateway-istio
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: forward-istio.com
  namespace: gw-1
spec:
  hostnames:
    - istio.com
  parentRefs:
    - name: internet-egress-gateway
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: istio.com
          port: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: istio.com
  namespace: gw-1
spec:
  exportTo:
    - .
    - app-1
  hosts:
    - istio.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-mtls
  namespace: gw-1
spec:
  mtls:
    mode: STRICT
```
</details>

<details>
<summary>gw-2.yaml</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: gw-2
  labels:
    istio-injection: enabled
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    networking.istio.io/service-type: ClusterIP
  name: internet-egress-gateway
  namespace: gw-2
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: istio.com
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: istio.com
      name: https
      port: 443
      protocol: TLS
      tls:
        mode: Passthrough
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: direct-google
  namespace: gw-2
spec:
  parentRefs:
    - group: networking.istio.io
      kind: ServiceEntry
      name: istio.com
  rules:
    - backendRefs:
        - name: internet-egress-gateway-istio
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forward-google-fr
  namespace: gw-2
spec:
  hostnames:
    - istio.com
  parentRefs:
    - name: internet-egress-gateway
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: istio.com
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: direct-istio.com
  namespace: gw-2
spec:
  hostnames:
    - istio.com
  parentRefs:
    - group: networking.istio.io
      kind: ServiceEntry
      name: istio.com
  rules:
    - backendRefs:
        - name: internet-egress-gateway-istio
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: forward-istio.com
  namespace: gw-2
spec:
  hostnames:
    - istio.com
  parentRefs:
    - name: internet-egress-gateway
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: Hostname
          name: istio.com
          port: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: istio.com
  namespace: gw-2
spec:
  exportTo:
    - .
    - app-2
  hosts:
    - istio.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-mtls
  namespace: gw-2
spec:
  mtls:
    mode: STRICT
```
</details>

### Version

```Text
- **Istio version**: 1.25.0
- **Helm chart version**: 1.25.0
- **Kubernetes version**: v1.31.2
- **Client version**: v1.31.0
```
