### ISSUE TITLE
Content-based routing doesn't work 

### ISSUE THREAD

**Issue by morvencao** [istio/istio#5701]
**env:**
```
ubuntu: 16.04
istio version: istio-release-0.8-20180518-01-13(daily build)
kubenetes version: v1.10.0
```

**Steps:**
1. Get latest daily build for istio-release-0.8 from https://gcsweb.istio.io/gcs/istio-release-pipeline-data/daily-build/release-0.8-20180518-01-13/
```
curl -LO https://storage.googleapis.com/istio-release-pipeline-data/daily-build/release-0.8-20180518-01-13/istio-release-0.8-20180518-01-13-linux.tar.gz
tar -xzvf istio-release-0.8-20180518-01-13-linux.tar.gz
cd istio-release-0.8-20180518-01-13
export PATH=$PWD/bin:$PATH
```
2. Install Istio core components
```
kubectl apply -f install/kubernetes/istio-demo.yaml
```
3. Deployment bookinfo with manual injection and define the ingress gateway
```
kubectl apply -f <(istioctl kube-inject --debug -f samples/bookinfo/kube/bookinfo.yaml)
istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml
```
4. Access the bookinfo application from browser with `http://${GATEWAY_URL}/productpage`
```
export GATEWAY_URL=$(kubectl get po -l istio=ingressgateway -n istio-system -o 'jsonpath={.items[0].status.hostIP}'):$(kubectl get svc istio-ingressgateway -n istio-system -o 'jsonpath={.spec.ports[0].nodePort}')
echo http://${GATEWAY_URL}/productpage
```
Refresh the page several times, I can see different versions of reviews shown in productpage, presented in a round robin style (red stars, black stars, no stars), since I haven’t yet used Istio to control the version routing.

5. Set the default version for all microservices to v1 and wait a few seconds for the rules to propagate to all pods before attempting to access the application.
```
istioctl create -f samples/bookinfo/routing/route-rule-all-v1.yaml
``` 

6. Open the Bookinfo URL (http://$GATEWAY_URL/productpage) in your browser
**problem:**
I still can see different versions of reviews shown in productpage, presented in a round robin style (red stars, black stars, no stars)
**expected**
The productpage is displayed with no rating stars since reviews:v1 does not access the ratings service.

Looks like there are some mismatched items in `samples/bookinfo/routing/route-rule-all-v1.yaml`
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  gateways:
  - bookinfo
  - mesh #TODO remove this if not needed
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
```
For I just defined gateway named `bookinfo-gateway` in `samples/bookinfo/routing/bookinfo-gateway.yaml`, however after I update `bookinfo` to `bookinfo-gateway`, the results remain unchanged.
Have I missed somethings as I followed the latest doc?

/cc @gyliu513
