### ISSUE TITLE
Redis trace not showing in jaeger

### ISSUE THREAD

**Issue by jtuthehien** [istio/istio#5725]
**Is this a BUG or FEATURE REQUEST?:**
FEATURES REQUEST
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
YES
**Bug:**
Y/N
Not sure
**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
NO
**What happened**:
Jaeger Tracing doesnt show redis trace. The routing works, prometheus metrics shows corresponding redis data, but not jaeger traces
**What you expected to happen:**
Redis trace included would be nice
**How to reproduce it:**
Launch test redis service in cluster. 
Deploy
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-redis
  labels:
    app: test-redis
    version:
spec:
  replicas: 1
  minReadySeconds: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: test-redis
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        command: ["redis-server", "--save", "\"\"", "--appendonly", "no"]
        env:
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 6379
          protocol: TCP
          name: redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
```
Service
```
apiVersion: v1
kind: Service
metadata:
  name: test-redis
  labels:
    app: test-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: redis
    targetPort: redis
    protocol: TCP
  selector:
    app: test-redis
```

**Feature Request:**
Y/N
Y
**Describe the feature:**

**Comment by farcaller** [comment]
Bump. Given istio has redis as a first-class citizen it'd be very useful if it supported redis calls tracing.

**Comment by chenzhenyang** [comment]
already solved ?

**Comment by farcaller** [comment]
Are there any docs on how to pass down the parent span id?

**Comment by Grant1219** [comment]
This is still not working with the sample Istio 1.0.2 installation, so I assume tracing for redis has not been added yet.

**Comment by vadimeisenbergibm** [comment]
Modifying the Redis deployment and service:

```
cat <<EOF | kubectl apply -f -
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-redis
  labels:
    app: test-redis
spec:
  replicas: 1
  minReadySeconds: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: test-redis
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        command: ["redis-server", "--save", "\"\"", "--appendonly", "no"]
        env:
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 6379
          protocol: TCP
          name: redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: test-redis
  labels:
    app: test-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: redis
    targetPort: redis
    protocol: TCP
  selector:
    app: test-redis
EOF
```

Cleanup:
```
kubectl delete deployment/test-redis service/test-redis
```
