### ISSUE TITLE
Automatic sidecar not working on acs-engine

### ISSUE THREAD

**Issue by aminebizid** [istio/istio#5810]
$ ks logs kube-controller-manager-k8s-master-29261444-0 --tail 100 -f

E0524 12:09:23.135394       1 replica_set.go:450] Sync "default/sleep-7c88bf4d94" failed with pods "sleep-7c88bf4d94-glv8x" is forbidden: spec.initContainers[0].imagePullPolicy: **Unsupported value: "IfNotPresent": supported values: "Always"**

**Comment by sdake** [comment]
@aminebizid thank you for the bug report!  Couple questions

* what is ks
* Which version of Istio
* what version of Kubernetes (kubectl and api server specifically)

I have not personally used Azure's cloud with Istio, however, that error seems to indicate that an imagePullPolicy of IfNotPresent is unsupported.

You can always override the default pull policy to `Always` and see if that gets things moving for those init containers.

**Comment by aminebizid** [comment]
@sdake thanks for your ptompt reply
ks is just an alia for  kubernetes -n kube-system :-)

ubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}


when running manually the injection, it works great but when using automatic side-car and putting sidecar.istio.io/inject: "true" as annotations in my deployment, I get this error 
Unsupported value: "IfNotPresent": supported values: "Always
on the controller-manager logs. I think it's the reason why the POD is not created.

I did find replace IfNotPresent/Always on whole istio install directory and on my self deployment without success.

I can't find where the side-car is creating the second container to update the imagePullPolicy.

**Comment by sdake** [comment]
More questions (Note I have no experience with ACS)

* Would you paste a snippet (or the full contents) of your manifest that you are attempting to inject automatically?  Perhaps the YAML is not correct?

* It could be that ACS does not properly configure the api server to support mutating werbhooks in their implementation.  Can you verify ACS has the following options set (you can use ps -ef for this purpose if you have access to the vm underneath Kubernetes): https://preliminary.istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection

`Sidecars can be automatically added to applicable Kubernetes pods using a mutating webhook admission controller. This feature requires Kubernetes 1.9 or later. Verify that the kube-apiserver process has the admission-control flag set with the MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission controllers added and listed in the correct order and the admissionregistration API is enabled.
`

**Comment by aminebizid** [comment]
~ kubectl api-versions | grep admissionregistration
admissionregistration.k8s.io/v1beta1



I'm using this yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
---

```
