### ISSUE TITLE
Istion 0.8 virtualservice weight issue

### ISSUE THREAD

**Issue by shoaibechidna** [istio/istio#5843]
There is some issue in this version. When I try to create a virtualservice with weight 90 and 10 for two different pod versions, it gets routed correctly. But when I try to replace with weight 50-50 or even delete and recreate it, it is still routing with weights 90 and 10. Below is the updated yaml. 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
  namespace: mynamespace
spec:
  hosts:
     - "service-1.mynamespace.svc.cluster.local"
  http:
  - route:
    - destination:
        host: "service-1.mynamespace.svc.cluster.local"
        subset: v1
      weight: 50
    - destination:
        host: "service-1.mynamespace.svc.cluster.local"
        subset: v2
      weight: 50

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-destination
  namespace: mynamespace
spec:
  host: "service-1.mynamespace.svc.cluster.local"
  subsets:
  - name: v1
    labels:
      version: R18_943
  - name: v2
    labels:
      version: R18_944
```
