### ISSUE TITLE
TCP ServiceEntry mesh-external addresses are disregarded, allowing traffic to any IP

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#5916]
This issue is related to https://github.com/istio/istio/issues/5498.

**Comment by ronenschafferibm** [comment]
In order to demonstrate this bug, one can follow these steps:
1. Deploy a recent build from here:

https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-0.8-20180530-09-15/


2. Apply a `ServiceEntry` to `wikipedia.org`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia-ext
spec:
  hosts:
  - wikipedia.org
  addresses:
  - 91.198.174.192/27
  - 103.102.166.224/27
  - 198.35.26.96/27
  - 208.80.153.224/27
  - 208.80.154.224/27
  ports:
  - number: 443
    protocol: TCP
    name: tcp-port
  resolution: NONE
```
(this snippet is taken from [Control Egress TCP Traffic](https://preliminary.istio.io/docs/tasks/traffic-management/egress-tcp/#creating-a-service-entry) task)

3. Deploy the `sleep` sample
``` bash
istioctl kube-inject -f ./samples/sleep/sleep.yaml
```

4. Curl from inside the `sleep` app to an external service other than `wikipedia.org` (e.g. `www.google.com`).
If one receives status 200 it's problem since the access should be forbidden.
``` bash
kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c sleep -- curl -o /dev/null -s -w "%{http_code}\n"  https://www.google.com
```

5. Retrieve the `adsz` through pilot's debug service.
```
kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c istio-proxy -- curl istio-pilot.istio-system:9093/debug/adsz
```
The relevant listener of `sleep`'s proxy looks like:
``` json
{
  "name": "0.0.0.0_443",
  "address": {
    "socketAddress": {
      "address": "0.0.0.0",
      "portValue": 443
    }
  },
  "filterChains": [
    {
      "filters": [
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "deprecated_v1": true,
              "value": {
                    "route_config": {
                          "routes": [
                                {
                                      "cluster": "outbound|443||wikipedia.org"
                                    }
                              ]
                        },
                    "stat_prefix": "outbound|tcp|443"
                  }
            }
        }
      ]
    }
  ],
  "deprecatedV1": {
    "bindToPort": false
  }
}
```
(The full response of adsz is attached here: [adsz.txt](https://github.com/istio/istio/files/2056970/adsz.txt))
Note tha lack of [`destination_ip_list`](https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v1/network_filters/tcp_proxy_filter#route) field that should restrict the access.


The relevant cluster is defined as follows:
```json
{
  "name": "outbound|443||wikipedia.org",
  "type": "ORIGINAL_DST",
  "connectTimeout": "1.000s",
  "lbPolicy": "ORIGINAL_DST_LB",
  "circuitBreakers": {
    "thresholds": [
      {

      }
    ]
  }
}
```

**Comment by vadimeisenbergibm** [comment]
I do not think it was fixed.

**Comment by hklai** [comment]
Any ETA? If it is not available by end of this week, the fix will most likely not be included in 0.8.1.

**Comment by vadimeisenbergibm** [comment]
@costinm ^

**Comment by rshriram** [comment]
@PiotrSikora we could really use support for destination addresses in the filter chains as it will allow us to merge multiple filter chains for the same port for cases like above. This has evne come up in the mailing lists.

**Comment by hklai** [comment]
@PiotrSikora is expecting to merge this by tomorrow.

**Comment by hklai** [comment]
@rshriram is this meant for 1.0?

**Comment by maximbaz** [comment]
I can reproduce this even without specifying `addresses` at all.

Just having this ServiceEntry allows access to _any domain_ via https:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia-ext
spec:
  hosts:
    - "wikipedia.org"
  ports:
    - number: 443
      protocol: TCP
      name: tcp-port
```
