### ISSUE TITLE
Content based routing not working

### ISSUE THREAD

**Issue by tushar00jain** [istio/istio#5940]
The following content based routing mostly taken from the documentation is not working

https://istio.io/docs/tasks/traffic-management-v1alpha3/request-routing.html

After passing the headers `x-version: v2`, there is no difference

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - service.default.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - headers:
        x-version:
          exact: v2
    route:
    - destination:
        name: service.default.svc.cluster.local
        subset: v2
  - route:
    - destination:
        name: service.default.svc.cluster.local
        subset: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr
spec:
  name: service.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
```

**Comment by GregHanson** [comment]
Are you using Istio version 0.7.1 or the 0.8 release candidate?  I also noticed you have a `gateway` listed in in your VirtualService.  The content-based routing task does not have one listed (https://istio.io/docs/tasks/traffic-management/request-routing) - was that intentional?

**Comment by tushar00jain** [comment]
I'm using 0.7.1 and the documentation says that if gateway is not provided it is interpreted as `mesh` by default

**Comment by GregHanson** [comment]
Are you able to upgrade to the latest? Version 0.8 has just been released and in 0.7.1 a lot of v1alpha3 was labeled as "experimental"

**Comment by tushar00jain** [comment]
just upgraded and still doesn't work
i had also provided some weights to default routes before upgrading (which was working but now even that is not working)

**Comment by tushar00jain** [comment]
this is my full configuration with 0.8.0

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - service.default.svc.cluster.local
  http:
  - match:
    - headers:
        x-version:
          exact: v2
    route:
    - destination:
        host: service.default.svc.cluster.local
        subset: v2
      weight: 100
  - route:
    - destination:
        host: service.default.svc.cluster.local
        subset: v1
      weight: 80
    - destination:
        host: service.default.svc.cluster.local
        subset: v2
      weight: 20
    timeout: 10s
    retries:
      attempts: 3
      perTryTimeout: 2s
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - GET
      allowCredentials: false
      allowHeaders:
      - x-fail
      - x-version
      maxAge: "24h"

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr
spec:
  host: service.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      http:
        consecutiveErrors: 1
        interval: 1s
        baseEjectionTime: 3m
        maxEjectionPercent: 100
```

**Comment by frankbu** [comment]
I ran your configuration in release 0.8.0, with just global change `service.default.svc.cluster.local` to `reviews.default.svc.cluster.local` and it works fine.
```
cat <<EOF | istioctl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - reviews.default.svc.cluster.local
  http:
  - match:
    - headers:
        x-version:
          exact: v2
    route:
    - destination:
        host: reviews.default.svc.cluster.local
        subset: v2
      weight: 100
  - route:
    - destination:
        host: reviews.default.svc.cluster.local
        subset: v1
      weight: 100
    timeout: 10s
    retries:
      attempts: 3
      perTryTimeout: 2s
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - GET
      allowCredentials: false
      allowHeaders:
      - x-fail
      - x-version
      maxAge: "24h"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr
spec:
  host: reviews.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      http:
        consecutiveErrors: 1
        interval: 1s
        baseEjectionTime: 3m
        maxEjectionPercent: 100
EOF
```
Test using the sleep service:
```
$ kubectl exec -it sleep-56c46994d8-4b7p6 bash
# curl http://reviews:9080/reviews/0 -H "x-version: v2"
{"id": "0","reviews": [{  "reviewer": "Reviewer1",  "text": "An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!", "rating": {"stars": 5, "color": "black"}},{  "reviewer": "Reviewer2",  "text": "Absolutely fun and entertaining. The play lacks thematic depth when compared to other plays by Shakespeare.", "rating": {"stars": 4, "color": "black"}}]}root@sleep-56c46994d8-4b7p6:/
```
