### ISSUE TITLE
istio-policy in istio-remote do not need to expose statsd port etc

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#5941]
The follows is the istio-policy ep in istio-remote chart, I think we only need port 9091, 15004 and 9093 same as istio control panel.
 
```
---
apiVersion: v1
kind: Endpoints
metadata:
  name: istio-policy
  namespace: istio-system
subsets:
- addresses:
  - ip: {{ .Values.global.policyEndpoint }}
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 9093
  - name: configapi
    port: 9094
  - name: statsd-prom
    port: 9102
  - name: statsd-udp
    port: 9125
    protocol: UDP
  - name: prometheus
    port: 42422
```

@sdake @sbezverk @costinm any comments for this? Due to the issue https://github.com/istio/istio/issues/5905 , I cannot verify if I can remove those port, but based on the logic, I think those port are not needed.
