### ISSUE TITLE
HTTP/1.1 301 Moved Permanently when creating HTTPS ServiceEntry

### ISSUE THREAD

**Issue by grebois** [istio/istio#5969]
From: https://istio.io/docs/tasks/traffic-management/egress#configuring-istio-external-services

I created a ServiceEntry like this:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: *****.com
spec:
  hosts:
  - *****.com
  ports:
  - number: 443
    name: https
    protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: *****.com
spec:
  host: *****.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```

but when I try to access the url from the pod I get:

```
/usr/src # curl -I http://*****.com:443/api/v1/jobs
HTTP/1.1 301 Moved Permanently
server: envoy
date: Fri, 01 Jun 2018 13:44:01 GMT
content-type: text/html
content-length: 185
location: https://*****.com:443/api/v1/jobs
strict-transport-security: max-age=15724800; includeSubDomains;
x-envoy-upstream-service-time: 46
```

Is this the expected behavior?
