### ISSUE TITLE
Confusion around jaeger/tracing services

### ISSUE THREAD

**Issue by Stono** [istio/istio#5987]
Hey, 
Istio: 0.8.0

I'm finding the configuration around jaeger a little confusing.

Looking at the helm values.yaml:

```
tracing:
  enabled: false
  jaeger:
    enabled: false
    memory:
      max_traces: 50000
  replicaCount: 1
```

You have `jaeger.enabled`, however that flag only seems to enable or disable the jaeger services (found in `charts/tracing/templates/service-jaeger.yaml`).  Jaeger itself is always deployed, so long as `tracing.enabled` is true (in ./charts/tracing/templates/deployment.yaml).

Things like `jaeger.memory.max_traces` are using in `./charts/tracing/templates/deployment.yaml`, which feels inconsistent when the parent `enabled` doesn't actually toggle that chart.

And also:
```
jaeger-query                       ClusterIP   10.192.96.109   <none>        80/TCP
```

Is basically:
```
tracing                            ClusterIP   10.192.99.226   <none>        80/TCP
```

As they both point to the tracing deployment (jaeger).

It feels like it should be something like:

```
tracing:
  enabled: false
  memory:
    max_traces: 50000
  replicaCount: 1
  jaeger_services:
    enabled: false
```

**Comment by objectiser** [comment]
Hi @Stono 

Agree that this area needs further work. The eventual aim, as discussed [here](https://github.com/istio/istio/pull/5098#issuecomment-383235928), is to provide some way of seamlessly selecting between different tracing providers.

As a step towards this, the `tracing` subsystem exposes two standard services, `zipkin` as the tracing data collector and `tracing` to provide access to a UI.

However, if users want to use Jaeger natively (i.e. collector and UI via jaeger-query) they can "enable" those additional jaeger specific services.

I think the next step would be to sort out a more generic mechanism that enables other providers to be selected. I took a [stab at this previously](https://github.com/istio/istio/pull/5098), which might provide a possible starting point.

**Comment by sakshigoel12** [comment]
cc. @douglas-reid

**Comment by douglas-reid** [comment]
Thanks @objectiser for a good summary.

@Stono IIRC, the `memory` stanza is jaeger-specific, and should be scoped to reflect that.

Would something like:
```
tracing:
  enabled: false
  replicaCount: 1
  jaeger:
    use_native_jaeger: false
    memory:
      max_traces: 50000
```

be more palatable?
