### ISSUE TITLE
listener conflicts related to headless services (warnings, errors, etc.)

### ISSUE THREAD

**Issue by Stono** [istio/istio#5992]
Hi, 
I'm seeing the following error in istio-pilot/discovery:

```
2018-06-03T00:27:50.659513Z     warn    buildSidecarOutboundListeners: listener conflict (TCP current and new TCP) on 0.0.0.0:9094, destination:outbound|9094||prometheus-alertmanager.istio-system.svc.cluster.local, current Listener: (0.0.0.0_9094 name:"0.0.0.0_9094" address:<socket_address:<address:"0.0.0.0" port_value:9094 > > filter_chains:<filters:<name:"envoy.tcp_proxy" config:<fields:<key:"deprecated_v1" value:<bool_value:true > > fields:<key:"value" value:<struct_value:<fields:<key:"route_config" value:<struct_value:<fields:<key:"routes" value:<list_value:<values:<struct_value:<fields:<key:"cluster" value:<string_value:"outbound|9094||alertmanager.data-platform.svc.cluster.local" > > > > > > > > > > fields:<key:"stat_prefix" value:<string_value:"outbound|tcp|9094" > > > > > > > > deprecated_v1:<bind_to_port:<> > )
```

For context, we have two teams running alertmanager, **in separate namespaces**.

  1. alertmanager.data-platform.svc.cluster.local
  2. prometheus-alertmanager.istio-system.svc.cluster.local

It appears when I use the same port section in the service for each of these, eg:

```
spec:
  ports:
  - name: cluster
    port: 9094
    protocol: TCP
    targetPort: cluster
```

If I rename the port in one of the second services to something else, everything starts working again and the errors in istio pilot go away.

EG: 
```
spec:
  ports:
  - name: cluster
    port: 9094
    protocol: TCP
    targetPort: cluster
```

Adding a prefix resolves it:
```
spec:
  ports:
  - name: http-cluster
    port: 9094
    protocol: TCP
    targetPort: cluster
```

**Comment by Stono** [comment]
Apologies, the late night must have gotten to me, the information above isn't quite right.

Having a port without a prefix (so treated as TCP) results in the error above, eg:

```
spec:
  ports:
  - name: frontend
    port: 9093
    protocol: TCP
    targetPort: frontend
```

Adding a prefix resolves it:
```
spec:
  ports:
  - name: http-frontend
    port: 9093
    protocol: TCP
    targetPort: http-frontend
```

So it seems to be specific to tcp services

**Comment by sakshigoel12** [comment]
@nmittler @rshriram can you take a look at this?

**Comment by rshriram** [comment]
Need config info

**Comment by mandarjog** [comment]
@Stono `https://github.com/istio/istio/blob/master/bin/dump_kubernetes.sh -z`   will gather config / logs etc.

**Comment by Stono** [comment]
Hey, 
I've written these manifests which you can use to recreate the problem..

```
apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: namespace1
spec:
  clusterIP: None
  ports:
  - name: someport
    port: 9999
    protocol: TCP
    targetPort: somepodport
  selector:
    app: someapp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace2
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: namespace2
spec:
  clusterIP: None
  ports:
  - name: someport
    port: 9999
    protocol: TCP
    targetPort: somepodport
  selector:
    app: someapp
  sessionAffinity: None
  type: ClusterIP
```

Gives you:
```
2018-06-05T18:54:34.904181Z     warn    buildSidecarOutboundListeners: listener conflict (TCP current and new TCP) on 0.0.0.0:9999, destination:outbound|9999||service2.namespace2.svc.cluster.local, current Listener: (0.0.0.0_9999 name:"0.0.0.0_9999" address:<socket_address:<address:"0.0.0.0" port_value:9999 > > filter_chains:<filters:<name:"envoy.tcp_proxy" config:<fields:<key:"deprecated_v1" value:<bool_value:true > > fields:<key:"value" value:<struct_value:<fields:<key:"route_config" value:<struct_value:<fields:<key:"routes" value:<list_value:<values:<struct_value:<fields:<key:"cluster" value:<string_value:"outbound|9999||service1.namespace1.svc.cluster.local" > > > > > > > > > > fields:<key:"stat_prefix" value:<string_value:"outbound|tcp|9999" > > > > > > > > deprecated_v1:<bind_to_port:<> > )
```
