### ISSUE TITLE
Change host on Gateway Objects has no effect

### ISSUE THREAD

**Issue by jxadro** [istio/istio#5993]
Istio 0.8 on Ubuntu running on IBM Cloud Private 2.1.0.2 with k8s 1.9.1

kubectl edit commands on Gateway Objects have no effect.

I have crated the gateway:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
Then I edit the object with kubectl edit gateway bookinfo-gateway and change the hosts from "*" to "bookinfo.com".
But in the logs of istio-ingressgateway-xxx pod there are no traces as there are when you remove/create gateways:

```
[2018-06-03 00:44:33.705][215][info][upstream] external/envoy/source/server/lds_api.cc:74] lds: remove listener '0.0.0.0_80'
[2018-06-03 00:44:45.130][215][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_80'
```
And if I tray to add other gateway with hosts set to "*" I gett the error:
```

[2018-06-03 00:51:24.660][215][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
[2018-06-03 00:51:24.660][215][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
```

And after I remove the first one, the edited one I see the trace:
`
[2018-06-03 00:52:20.133][215][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_80'`

And the second one starts to work.
