### ISSUE TITLE
0.8 DestinationRule outlierdetection not working

### ISSUE THREAD

**Issue by jxadro** [istio/istio#5996]
Istio 0.8.0 in ICP 2.1.0.2 with k8s 1.9.2

The outlierdetection configuration does not rise.

I have the following configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myistioapp
spec:
  host: myistioapp
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      http:
        consecutiveErrors: 3
        interval: 60s
        baseEjectionTime: 3m
        maxEjectionPercent: 100
```
I have a deployment with two replicas, one returns an http code 500 and a message saying "Istio RED" and the other a http code 200 saying "Istio GREEN".

In the period of 60 seconds I make continuous invocations and I get response from both replicas. My understanding is that after 3 errors from a specific replica Istio should only invoke the replica returning http code 200.

To replicate the issue:

Service Provider deployment and service:

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: myistioapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myistioapp
    spec:
      hostNetwork: false
      containers:
      - name: myistioapp
        image: jxadro/hellonode:1.0
        imagePullPolicy: IfNotPresent
        ports: []
---
kind: Service
apiVersion: v1
metadata:
  name: myistioapp
  labels:
    app: myistioapp
spec:
  ports:
  - protocol: TCP
    name: node
    port: 8080
    targetPort: 8080
  selector:
    app: myistioapp
  clusterIP: ''
  sessionAffinity: None
  type: NodePort
```

The Service client deployment:

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: myistioappclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myistioappclient
    spec:
      hostNetwork: false
      containers:
      - name: myistioappclient
        image: jxadro/hellonode:1.0
        imagePullPolicy: IfNotPresent
        ports: []
```
I deploy k8s objects with: kubectl apply -f <(istioctl kube-inject --debug -f myfile.yaml)

Now execute:

```
kubectl exec -ti myistioappclient-xxxx -- /bin/bash
curl myistioapp:8080/istio/error?error=true -> this configure one replica to return an error
Call several times to curl myistioapp:8080/istio/op
```

One replica will replay green and the other will reply red, but after three errors only the green replica should reply.

I know the destination rule works for this app because I have tested the maxconnection properties. It is the outlierDetection the part that is failing.
