### ISSUE TITLE
Is there a way to publish two different services by ONE domain name, while each service has its own VirtualService? 

### ISSUE THREAD

**Issue by idouba** [istio/istio#6070]
It's a common case to publish more than one service by one domain name. And can be easily configured by ingress, but seems a little hard to describe it by Gateway&VirtualService.

**Comment by idouba** [comment]
Now we can publish the service productpage and review this way, each can be accessed from outside the cluster by its own domain name respectively: productpage-bookinfo.com, reviews-bookinfo.com
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: default
spec:
  hosts:
  - productpage-bookinfo.com
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
    route:
    - destination:
        host: productpage
        subset: v1
  - route:
    - destination:
        host: productpage
        subset: v2`
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-bookinfo.com
  namespace: default
spec:
  hosts:
  - reviews..bookinfo.com
  http:
  - route:
    - destination:
        host: reviews
        subset: v1`

Since this two service is within the same application bookinfo, it is better to be named bookinfo.com/productpage and bookinfo.com/review like ingress style.
We try this by create another new virtualservice like this:
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: default
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - bookinfo.com
  http:
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: productpage
  - match:
    - uri:
        exact: /reviews/0
    route:
    - destination:
        host: reviews`

And the inner referenced virtulservice is like this:
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: default
spec:
  hosts:
  - productpage
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
    route:
    - destination:
        host: productpage
        subset: v1
  - route:
    - destination:
        host: productpage
        subset: v2`

`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1`

We expect the path in virtualService bookinfo can route the request to the inner virtualService. That is the request from the bookinfo.com with path productpage and header satisfy the cookie condition will route to  v1 version of productpage  service.

But it comes out that the route in inner virtualService seems does not work, the matched request does not be routed to canary version v1 as the rule in productpage described. The request is routed to two productpage's V1 and V2 back-ends in a round-robin way. 

Using v1alpa3 rule  what is the recommend practice to make  two service which belong to one application be published by ONE domain name, and  each service  has its own route rule (virtual service) to do traffic management such as canary release.

**Comment by frankbu** [comment]
The problem is that we don't currently support virtual service chaining. The route destination of the first virtual service is referring to the endpoint services, not to a virtual service with the same name. 

So, currently you will need to put the routing rules into the composite virtual service.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: default
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - bookinfo.com
  http:
  - match:
    - uri:
        exact: /productpage
    - headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
    route:
    - destination:
        host: productpage
        subset: v1
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: productpage
        subset: v2
  - match:
    - uri:
        exact: /reviews/0
    route:
    - destination:
        host: reviews
      subset: v1
```
I think this is not the best UX so we should support chaining or some kind of automatic merging to make this easier.

**Comment by x15zhang** [comment]
Yes. Although the problem can be resloved by composite virtual service,it is complicated to manage these route rules for a series of services in one composite virtual service. 
It is better to support virtual service chaining.

**Comment by idouba** [comment]
Thansks, @frankbu ,@x15zhang. Yes, virtual service chaining will make it more flexible, and we really need it .
Fix the above demo code by adding gateways to 1 &2 virtual service.

**Comment by andraxylia** [comment]
Sorry, I am a bit confused about the need for chaining. You description says "It's a common case to publish more than one service by one domain name. And can be easily configured by ingress, but seems a little hard to describe it by Gateway&VirtualService.".

Do I understand correctly this is bookinfo.com/productpage and booking.com/reviews ?

What does not work when you use a Gateway, and one VirtualService with 2 path matches?

**Comment by blaketastic2** [comment]
@idouba Can you please share how you got things working? 

@frankbu, when you say chaining isn't supported, what about a scenario where I go from IngressGateway -> VirtualService A -> Non-VirtualService B -> VirtualService C(v1 and v2)? In that scenario, I'd be coming from the mesh, not directly a VirtualService.

**Comment by nrjpoddar** [comment]
@idouba I have a proposal for adding this functionality via [VirtualService chaining](https://goo.gl/jSZTjW). It will be great to know if the proposal meets your requirements.

**Comment by voor** [comment]
@nrjpoddar what would be the best way to follow the progress of that proposal?

**Comment by frankbu** [comment]
https://github.com/istio/istio/issues/7793
https://github.com/istio/istio/pull/8113
https://github.com/istio/istio.github.io/pull/2369

**Comment by nrjpoddar** [comment]
@voor the umbrella issue https://github.com/istio/istio/issues/7793 that @frankbu pointed is the best place to track where the community is headed for this overall functionality.

Regarding delegation and the proposal I submitted there was agreement on providing users with the ability to specify the merge behavior but nothing finalized in terms of implementation.

If there's a specific use case which you are trying to solve, it would be interesting to know for the next phase of the VirtualService merging feature.

**Comment by voor** [comment]
Historically, we leveraged the Nginx Ingress controller for Kubernetes, which used the decentralized Ingress type.  Seeing that Istio was approaching the VirtualService as a monolith was just a bit of a surprise for me, that's all.

**Comment by nrjpoddar** [comment]
This PR: https://github.com/istio/istio/pull/8113 addresses the simple Ingress type scenarios where the VirtualService resources with the same hostname only contain routes with no conflicting path match conditions.

**Comment by frankbu** [comment]
@dreadbird You should be able to use [this new feature](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host) to address your requirement.

**Comment by dreadbird** [comment]
> @dreadbird You should be able to use [this new feature](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host) to address your requirement.

@frankbu I'm sorry, there are some mistakes in my description.

My question is about your previous reply:

> The problem is that we don't currently support virtual service chaining. The route destination of the first virtual service is referring to the endpoint services, not to a virtual service with the same name.
> 
> So, currently you will need to put the routing rules into the composite virtual service.
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: bookinfo
>   namespace: default
> spec:
>   gateways:
>   - bookinfo-gateway
>   hosts:
>   - bookinfo.com
>   http:
>   - match:
>     - uri:
>         exact: /productpage
>     - headers:
>         cookie:
>           regex: ^(.*?;)?(user=jason)(;.*)?$
>     route:
>     - destination:
>         host: productpage
>         subset: v1
>   - match:
>     - uri:
>         exact: /productpage
>     route:
>     - destination:
>         host: productpage
>         subset: v2
>   - match:
>     - uri:
>         exact: /reviews/0
>     route:
>     - destination:
>         host: reviews
>       subset: v1
> ```
> I think this is not the best UX so we should support chaining or some kind of automatic merging to make this easier.

**Comment by nrjpoddar** [comment]
@dreadbird the [virtualservice chaining](https://docs.google.com/document/d/17K0Tbp2Hv1RAkpFxVTIYPLQRuceyUnABtt0amd9ZVow/edit#heading=h.m6yvqjh71gxi) proposal is still not implemented.
The example you gave is the primary use case of Virtual Service chaining/delegation but it appears implementing this feature is currently a lower priority.

**Comment by frankbu** [comment]
@dreadbird Although not quite as simple as if we had VirtualService delegation, you can use the feature I mentioned to reduce some of the duplication. All you need are the two inner VirtualServices but they will include the gateway host and paths.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: b-vs
  namespace: default
spec:
  gateways:
  - example-gateway
  hosts:
  - example.com
  - svcB
  http:
  - match:
    - uri:
        exact: /svcB
      headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
    route:
    - destination:
        host: svcB
        subset: v1
  - match:
    - uri:
        exact: /svcB
    route:
    - destination:
        host: svcB
        subset: v2

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: a-vs
  namespace: default
spec:
  gateways:
  - example-gateway
  hosts:
  - example.com
  - svcA
  http:
  - match:
    - uri:
        exact: /svcA
    route:
    - destination:
        host: svcA
      subset: v1
```

**Comment by idouba** [comment]
@frankbu ,does this is supported in 1.1. I see VirtualService spec update the host description and emphasise that "A host name can be defined by only one VirtualService". what does this mean? 

What is the suggested solution in 1.1 and what is he final solution?

> @dreadbird Although not quite as simple as if we had VirtualService delegation, you can use the feature I mentioned to reduce some of the duplication. All you need are the two inner VirtualServices but they will include the gateway host and paths.
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: b-vs
>   namespace: default
> spec:
>   gateways:
>   - example-gateway
>   hosts:
>   - example.com
>   - svcB
>   http:
>   - match:
>     - uri:
>         exact: /svcB
>       headers:
>         cookie:
>           regex: ^(.*?;)?(user=jason)(;.*)?$
>     route:
>     - destination:
>         host: svcB
>         subset: v1
>   - match:
>     - uri:
>         exact: /svcB
>     route:
>     - destination:
>         host: svcB
>         subset: v2
> 
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: a-vs
>   namespace: default
> spec:
>   gateways:
>   - example-gateway
>   hosts:
>   - example.com
>   - svcA
>   http:
>   - match:
>     - uri:
>         exact: /svcA
>     route:
>     - destination:
>         host: svcA
>       subset: v1
> ```

**Comment by frankbu** [comment]
There is no change from 1.0 to 1.1. The docs in 1.1 need to be fixed.

**Comment by idouba** [comment]
@frankbu  ok.

**Comment by idouba** [comment]
@frankbu , the suggested solution[ multiple-virtual-services-and-destination-rules-for-the-same-host](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host)  seems still has limitation:

for two domain name case like this:
myapp.com
      service1  ->   service1.default.svc.cluster.local
      service2  ->   service2.default.svc.cluster.local
	  
myapp2.com
      service12  ->   service1.default.svc.cluster.local
      service22  ->   service2.default.svc.cluster.local

In one service1's virtualservice,(same to service2)
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp-service1
spec:
  hosts:
  - myapp.com
  - myapp2.com
  gateways:
  - myapp-gateway
  http:
  - match:
    - uri:
        prefix: /service1
    route:
    - destination:
        host: service1.default.svc.cluster.local
```

this can only config like this: 

myapp.com
      service1  ->   service1.default.svc.cluster.local
      service2  ->   service2.default.svc.cluster.local
	  
myapp2.com
      service1  ->   service1.default.svc.cluster.local
      service2  ->   service2.default.svc.cluster.local
 
because of the scope of hosts in virtualservice, which is upon all the route of vs.
I think VS chain is what we need.
