### ISSUE TITLE
Configure inter-namespace routing

### ISSUE THREAD

**Issue by maxkondr** [istio/istio#6141]
Hi,

setup is following:
istio: 0.8.0
using v1alpha3 API (Gateway,VirtualService,DestinationRule)

I want to achieve the following scenario:

1. I have istio-system namespace deployed accordingly to https://istio.io/docs/setup/kubernetes/quick-start/#installation-steps point 
`kubectl apply -f install/kubernetes/istio-demo.yaml`
2. I have grafana service deployed into default namespace 
3. I want ingress traffic to be routed to grafana.default service

>kubectl get svc grafana
```
NAME      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
grafana   ClusterIP   10.3.6.183   <none>        3000/TCP   33m
```

>kubectl get ns --show-labels=true
```
NAME           STATUS    AGE       LABELS
default        Active    5d        istio-injection=enabled
```

I have the following istio configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
  - grafana-gateway
  http:
  - route:
    - destination:
        port:
          number: 3000
        host: grafana.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana.default.svc.cluster.local
  namespace: default
spec:
  host: grafana.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
```

and istio-system services are (note: I do not have LoadBalancer, so I set up NodePort Service for ingressgateway):
>kubectl get svc -n istio-system
```
NAME                       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                                                               AGE
istio-ingressgateway       NodePort    10.3.4.20    <none>        80:31380/TCP,443:31390/TCP,31400:31400/TCP                            32m
....
```

When I try to reach < IP >:31380 I get the following:
```
upstream connect error or disconnect/reset before headers
```

in the istio-ingressgateway-7649c89668-cfvt9_istio-system_ingressgateway log I see:
```
{"log":"[2018-06-11T08:09:12.938Z] \"GET / HTTP/1.1\" 503 UC 0 57 9 - \"10.2.0.1\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36\" \"26011146-a00f-9a2c-952b-c0267ad7cafc\" \"192.168.73.108:31380\" \"10.2.0.9:3000\"\n","stream":"stdout","time":"2018-06-11T08:09:16.810630798Z"}
{"log":"[2018-06-11T08:09:13.099Z] \"GET /favicon.ico HTTP/1.1\" 503 UC 0 57 1 - \"10.2.0.1\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36\" \"9b69d50a-94ef-9f42-a1e3-e4b3ba018a24\" \"192.168.73.108:31380\" \"10.2.0.9:3000\"\n","stream":"stdout","time":"2018-06-11T08:09:16.810700975Z"
```

The question is: what the proper way to configure ingress traffic routing to namespace other than istio-system?
If I route ingress traffic to grafana from istio-system namespace - it works well.

**Comment by maxkondr** [comment]
I have solved this issue. The main problem was that I had in config 
```
data:
  mesh: |-
    # Mutual TLS between proxies
    authPolicy: MUTUAL_TLS
    ....
```
and it broke communication in the mesh. Starting from 0.8.0 this option is deprecated (see https://github.com/istio/istio/issues/6028).

You may close the issue
