### ISSUE TITLE
Mutual tls is not working for istio gateway

### ISSUE THREAD

**Issue by ajit-hybris** [istio/istio#6244]
Deployed istio gateway (istio 0.8.0) with following config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argonauts-gateway
  namespace: argonautsmunich
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      caCertificates: /etc/certs/root-certs.pem
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "profile-identity.profile.v2.k8s.stage.yaas.io"
    - "ptms.profile.v2.k8s.stage.yaas.io"

```

But it results in an exception at istio-ingressgateway, logs are

`[2018-06-13 15:17:24.186][70][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: unable to read file: /etc/certs/root-certs.pem`

Setting this up once in any gateway breaks the whole ingress setup and all in/out traffic stops working.

The test case is still in todo state: https://github.com/istio/istio/blob/85edd3f5aebfaaa4161147606428d4a9f89d3c83/tests/e2e/tests/pilot/testdata/v1alpha3/ingressgateway.yaml
