### ISSUE TITLE
Destination rule specification when mTLS is configured

### ISSUE THREAD

**Issue by axel7born** [istio/istio#6279]
Hi,
As proposed on [Istio Developers](https://groups.google.com/forum/#!topic/istio-dev/q-Xja7OUGNg), here is a step by step description on how to reproduce the problem. 
* Set up Istio using mTLS using `kubectl apply -f install/kubernetes/istio-demo-auth.yaml`.
* Deploy the httpbin example: `kubectl apply -f samples/httpbin/httpbin.yaml`
* Deploy a test container: `kubectl apply -f samples/sleep/sleep.yaml`
* Exec into the sleep pod being and make a request to httpbin:
```
$ export SOURCE_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
$ kubectl exec -it $SOURCE_POD -c sleep bash
/# curl -I http://httpbin:8000/status/200
HTTP/1.1 200 OK
server: envoy
date: Thu, 14 Jun 2018 07:59:39 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 22
/# exit
```

* Create a minimal destination rule:
```
cat <<EOF | istioctl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
EOF
```
and make a request
```
$ kubectl exec -it $SOURCE_POD -c sleep bash
/# curl -I http://httpbin:8000/status/200
HTTP/1.1 503 Service Unavailable
content-length: 57
content-type: text/plain
date: Thu, 14 Jun 2018 08:45:48 GMT
server: envoy
```

* Add mtls configuration to the destination rule

```
cat <<EOF | istioctl replace -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```
... and check again:
```
$ kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c sleep bash
/# curl -I http://httpbin:8000/get
HTTP/1.1 200 OK
server: envoy
date: Thu, 14 Jun 2018 08:51:20 GMT
content-type: application/json
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 428
x-envoy-upstream-service-time: 18
```

Especially for new users its very confusing, to get a 503 and there is no hint that can be found int the  logs.
