### ISSUE TITLE
SSL certificates to host several domains

### ISSUE THREAD

**Issue by maxkondr** [istio/istio#6282]
Hi,

istio 0.8.0

In the doc https://istio.io/docs/tasks/traffic-management/ingress/#add-a-secure-port-https-to-our-gateway I see following:
```
Create a Kubernetes Secret to hold the key/cert

Create the secret istio-ingressgateway-certs in namespace istio-system using kubectl. The Istio gateway will automatically load the secret.

The secret MUST be called istio-ingressgateway-certs in the istio-system namespace, or it will not be mounted and available to the Istio gateway.
```

Q: I need to handle several hosts with separate certificates- how should I configure them?

**Comment by ymesika** [comment]
Gateway (with its certs) per host(s)?

**Comment by ntfrnzn** [comment]
https://github.com/istio/istio/issues/7325 appears to address this question.

**Comment by xianyuLuo** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-rocks
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/_.test1.com.pem
      privateKey: /etc/istio/ingressgateway-certs/_.test1.com.key
    hosts:
    - "*.test1.com"
  - port:
      number: 443
      name: https-xyz
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/_.test2.com.pem
      privateKey: /etc/istio/ingressgateway-certs/_.test2.com.key
    hosts:
    - "*.test2.com"
```

Secret is created from the folder
