### ISSUE TITLE
Ingress to VirtualService conversion fails

### ISSUE THREAD

**Issue by andersjanmyr** [istio/istio#6303]
**Describe the bug**
When a new ingress is added it is not converted to a Gateway and VirtualService and the pilot logs shows conversion errors.

**Expected behavior**
I expected the converted resources to be created and the pilot logs to not show any errors.

**Steps to reproduce the bug**
* Deploy Istio 0.8
* Add an Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  labels:
    app: counter
  name: counter
  namespace: default
spec:
  rules:
  - host: counter.default.cluster.example.com
    http:
      paths:
      - backend:
          serviceName: counter
          servicePort: 80
```

* Verify that the gateway and virtual service has not been created.
* Check the pilot logs
```
2018-06-14T20:50:08.921147Z	error	Failed to convert virtual-service object, ignoring: default/counter YAML decoding error: Gateways:
 unknown field "Gateways" in v1alpha3.VirtualService map[Http:[map[Match:[map[URI:map[Prefix:/]]] Route:[map[Destination:map[Host:counter Port:map[Number:80]]]]]] gateways:[counter-gateway] hosts:[counter.default.cluster.quark.vn0wxf9.kubernetes.prod.walmart.com] http:[map[match:[map[uri:map[prefix:/]]] route:[map[destination:map[host:counter port:map[number:80]]]]]] Gateways:[counter] Hosts:[counter.default.cluster.quark.vn0wxf9.kubernetes.prod.walmart.com]]
```

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

```
$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
Not enabled

**Environment**
Proprietary installed cluster.
