### ISSUE TITLE
Datadog tracing APM support

### ISSUE THREAD

**Issue by c-knowles** [istio/istio#6314]
Istio already has a mixer adapter for dogstatsd/datadog metrics. I was trying to figure out if it would be easy to create an adapter for datadog APM tracing but I'm not sure how pluggable the distributed tracing is yet.

From the datadog side, they now support the CNCF OpenTracing:
https://www.datadoghq.com/blog/opentracing-datadog-cncf/
https://github.com/DataDog/dd-trace-go

**Describe the solution you'd like**
First class integration for Datadog APM tracing.

**Describe alternatives you've considered**
Considering running one of these alongside istio:

- https://github.com/flachnetz/dd-zipkin-proxy
- https://github.com/namely/zipkin-proxy

**Comment by douglas-reid** [comment]
@c-knowles it should be fairly straightforward to add a Mixer adapter for datadog tracing. there is a tracing template within Mixer.

I'm not going to be working on building this adapter in any near-term timeline, so I'm going to remove myself from assignment.  However, I'm happy to consult on any work and/or review any such adapter.

**Comment by c-knowles** [comment]
@douglas-reid thanks, will take a look at that.

**Comment by willgittoes-dd** [comment]
Hi @c-knowles , Will from Datadog here :) We've got Datadog APM for envoy working using envoy's generic OpenTracing dynamic load functionality to load our C++ OpenTracing implementation. It should be possible to extend this to working with Istio. 

Currently it's still early days, but our plan is to upstream APM support into envoy (which is more first-class than using the dynamic loading method). That would make Istio support practically free. The plan is for that to land some time this quarter.

If you've got the rare combination of "urgent" yet "happy to deal with wild jankiness", then I'd be happy to help you get our alpha version working.

**Comment by c-knowles** [comment]
@willgittoes-dd that's great news. No huge rush for us, it was something we were investigating as a possible way to get rid of some of our existing tracing mechanisms. If you'd like us to beta test at some stage we could do that.

**Comment by killcity** [comment]
+1

**Comment by c-knowles** [comment]
I believe will be resolved by https://github.com/envoyproxy/envoy/pull/4699 assuming that can be easily configured with the next Envoy release.

**Comment by michaelkipper** [comment]
Any update on this, given that https://github.com/envoyproxy/envoy/pull/4699 was merged upstream?
We'd be happy to beta test something.

**Comment by cgilmour** [comment]
Hi @michaelkipper @c-knowles , Caleb from Datadog here.
Our team did a bit of work internally to add Datadog APM to istio following the change to envoy.
It works, but would need some tidy-up before it can be submitted.

@douglas-reid would you be open to a submission that adds support for Datadog tracing in a similar way to Lightstep?

**Comment by cgilmour** [comment]
@douglas-reid I'd like to move forward on contributing this, unless you have an objection.

From my understanding, it needs
- a PR to `api` to add configuration items
- a PR to `istio` to bump `vendor/istio.io/api`
- a PR to `istio` with the main chunk of functionality (bootstrap, pilot, sidecar configmap, etc)
- docs changes on `istio.io`

Does that sound correct?
Anything else I should be aware of?
Thanks!

**Comment by douglas-reid** [comment]
@cgilmour apologies for missing the updates here -- they were lost in a sea of github emails.

Yes. We would be very open to adding the support.  I think that the steps you've outlined are correct.

In the future, it'd be awesome to have a Mixer adapter for the integration as well -- just to fully support both paths.

**Comment by Rigdon** [comment]
@douglas-reid Thanks for the response! There is currently already a [Datadog mixer adapter for telemetry](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/datadog/) listed already. Should there be an adapter for tracing as well or is that what you meant?

**Comment by douglas-reid** [comment]
@Rigdon I was hoping that we could extend that to support the tracespan template.

**Comment by anthonyhaussman** [comment]
Hi. I want to use the Datadog tracing APM in istio.
I use the release 1.1.3 of istio.
I have modified the istio ConfigMap to use the Datadog tracer.
```
...
      # Set concurrency to a specific number to control the number of Proxy worker threads.
      # If set to 0 (default), then start worker thread for each CPU thread/core.
      concurrency: 2
      #
      tracing:
        datadog:
          # Address of the Datadog Agent
          address: dogstatsd-istio.istio-system:8126
      #    
      # Mutual TLS authentication between sidecars and istio control plane.
      controlPlaneAuthPolicy: NONE
...
```
And relaunch my pod for the envoy sidecar to use the new tracing:
```
...
gateway-78c46ddd57-b9cst istio-proxy 2019-04-26T08:43:37.032663Z    info    FLAG: --datadogAgentAddress="dogstatsd-istio.istio-system:8126"
...
```
For dogstatsd, I use the image `datadog/docker-dd-agent:12.6.5281` with env:
```
      - env:
        - name: TAGS
          value: cluster-name:dev-orscale-04-dm-istio
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_URL
          value: https://app.datadoghq.com
        - name: NON_LOCAL_TRAFFIC
          value: "true"
        - name: MAX_TRACES_PER_SECOND
          value: "500"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: datadog-apikey
              name: dogstatsd-istio
```
When I search for the `cluster-name:dev-orscale-04-dm-istio` tag into Datadog Trace search, I have nothing.
I didn't find error logs into the dogstatsd-istio pod or istio-proxy sidecars container. 
Did I miss something?
