### ISSUE TITLE
Jaeger cannot show trace if the service port name is not `http`

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6316]
Did some test with following YAML template, setting ports name as `nginx`, and inject sidecar, then deploy the nginx, found no tracing in Jaeger.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx
  name: my-nginx
spec:
  ports:
  - name: nginx
    port: 80
  selector:
    app: my-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
        version: v1
    spec:
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
        name: my-nginx
        ports:
        - containerPort: 80
---
```

But if I change the port name to `http`, the tracing works.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx
  name: my-nginx
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: my-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
        version: v1
    spec:
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
        name: my-nginx
        ports:
        - containerPort: 80
---
```

So here the problem is:
1) Why must I set the port name as `http`?
2) How to handle the case if there are multiple ports exposed by a services, how to define the name?
3) All of the service port in `bookInfo` are using `http`, that's why Jaeger can always do tracing for bookinfo.

/cc @rshriram @mandarjog @douglas-reid
