### ISSUE TITLE
Enable using hostname to access service

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6319]
With Ingress Gateway, we have a limitation to access services with hostname at https://istio.io/docs/tasks/traffic-management/ingress/#accessing-istio-service-mesh-by-a-browser , this is different with ingress which can enable us to access service using hostname. I think we need to bring this feature back with Ingress Gateway.

/cc @rshriram @cmluciano

**Comment by rshriram** [comment]
? I don’t understand. There is no relationship between dns and gateways. If you make all dns names in the gateway resolve to the gateway ip, you get the functionality you need. Same is true for kubernetes ingress as well. automatically update dns based on ingress or gateway spec is possible with custom implementations

**Comment by gyliu513** [comment]
@rshriram there are limitations as follows, can this be fixed?

```
Currently, accessing the mesh by a browser is fully supported only for load balancer ingress gateways, and only for the standard ports (80 and 443)
```

**Comment by rshriram** [comment]
We should remove that line. It’s not saying what you think it is (and led you to create this pr)

**Comment by gyliu513** [comment]
Thanks @rshriram , let me check this.

Another question is for
```
For NodePort ingress gateways, access by a browser is supported partially: only for the * hosts in the definition of the VirtualService.
```

So with NodePort Ingress gateway, I will not able to access hosts which is not defined as * ? This is also different with previous ingress.

**Comment by vadimeisenbergibm** [comment]
@todkap I think you can specify the `hosts` field to be `*`, so you will not have to add DNS entries.

**Comment by todkap** [comment]
I had tried this numerous times with wildcarding with failures but this time when I did it, all is good.  Thanks...

**Gateway**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: proxy-etcd-storage-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
**Virtual Service**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: proxy-etcd-storage
spec:
  hosts:
  - "*"
  gateways:
  - proxy-etcd-storage-gateway
  http:
  - match:
    - uri:
        prefix: /storage
    - uri:
        prefix: /web
    - uri:
        prefix: /    
    route:
    - destination:
        port:
          number: 9080
        host: proxy-etcd-storage
```
