### ISSUE TITLE
Use ALPN "istio" for PERMISSIVE mode.

### ISSUE THREAD

**Issue by incfly** [istio/istio#6384]
Current implementation relies on `envoy.tls_inspector`. @PiotrSikora mentions now we ship ALPN in release 0.8. The outcome to authn policy is effectively the same, telling whether it's a traffic originating from istio sidecar or not.

Questions, what does each filter chain match looks like for istio TLS and plaintext respectively?

**Comment by PiotrSikora** [comment]
```
listeners:
- address:
    socket_address: { address: 127.0.0.1, port_value: 10000 }
  listener_filters:
  - name: "envoy.listener.tls_inspector"
    config: {}
  filter_chains:
  - filter_chain_match:
      application_protocols: "istio"
    tls_context:
      common_tls_context:
        tls_certificates:
        - certificate_chain: { filename: "test/common/ssl/test_data/san_dns_cert.pem" }
          private_key: { filename: "test/common/ssl/test_data/san_dns_key.pem" }
    filters:
    - name: ...
      [...]
  - filters:
    - name: ...
       [...]
```

**Comment by incfly** [comment]
Do you still need "envoy.listener.tls_inspector" to use ALPN?

**Comment by PiotrSikora** [comment]
Yes.

**Comment by incfly** [comment]
So the inspector look at FilterChainMatch's contained fields, and may do TLS sniffing or not depends on whether `filter_chain_match.transport_protocol` is set?

I thought one of the ALPN's advantages is to avoid sniffing.

**Comment by incfly** [comment]
One more thing to confirm, so with [above LDS config](https://github.com/istio/istio/issues/6384#issuecomment-398251823), both workload-to-workload TLS and plain text traffic will be dispatched to the second filter chain. In that case, it's application itself to terminate TLS  or simply handle plaintext traffic.

In short, the filter chain without any FilterChainMatch field specified acts as a `default` one.

Is that right?

**Comment by PiotrSikora** [comment]
> One more thing to confirm, so with above LDS config, both workload-to-workload TLS and plain text traffic will be dispatched to the second filter chain. In that case, it's application itself to terminate TLS or simply handle plaintext traffic.

Correct. But, if you also want to terminate TLS in the sidecar, then you can simply add another filter chain (3 in total) to allow mTLS, "legacy" TLS terminated at the sidecar, and unencrypted traffic. Using the same example:

```
listeners:
- address:
    socket_address: { address: 127.0.0.1, port_value: 10000 }
  listener_filters:
  - name: "envoy.listener.tls_inspector"
    config: {}
  filter_chains:
  - filter_chain_match:
      transport_protocol: "tls"
      application_protocols: "istio"
    tls_context:
      common_tls_context:
        tls_certificates:
        - certificate_chain: { filename: "test/common/ssl/test_data/san_dns_cert.pem" }
          private_key: { filename: "test/common/ssl/test_data/san_dns_key.pem" }
    filters:
    - name: ...
      [...]
  - filter_chain_match:
      transport_protocol: "tls"
    tls_context:
      common_tls_context:
        tls_certificates:
        - certificate_chain: { filename: "test/common/ssl/test_data/san_dns_cert.pem" }
          private_key: { filename: "test/common/ssl/test_data/san_dns_key.pem" }
    filters:
    - name: ...
      [...]
  - filters:
    - name: ...
      [...]
```

> In short, the filter chain without any FilterChainMatch field specified acts as a default one.

In this particular case, yes, but that's not always the case, since match on one of the selectors can limit available choices (I'm working on the documentation for that).
