### ISSUE TITLE
Pilot distribute SdsSecretConfig to envoy

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#6411]
Pilot distribute SdsSecretConfig to envoy

[Node Agent](https://github.com/istio/istio/issues/5903) will communicate with envoy through [secret discovery service(SDS)](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/discovery/v2/sds.proto) to distribute key cert pair(to replace secret-mount files today). In order for envoy talks to Node Agent, pilot need to distribute [SdsSecretConfig](https://github.com/envoyproxy/envoy/blob/6d3d5d72986c2131a40268467c3ddcc57ef7bbc7/api/envoy/api/v2/auth/cert.proto#L236) to envoy.

change need to be made -
1. places to construct CommonTlsContext in pilot includes listener, cluster, authN plugin, gateway(gateway probably isn't necessary since key/cert are passed from Gateway customer defined yaml file now)
2. may need to add a flag in meshConfig to indicate to use sds or secret-mount files 

SdsSecretConfig example - 
secretName should be service account in Spiffe format.  
```
    filter_chains:
      tls_context:
        common_tls_context:
          tls_certificate_sds_secret_configs:
          - name: "SPKI"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                - google_grpc:
                    stat_prefix: test
                    target_uri: unix:/tmp/uds_path
                refresh_delay: 60s
```

**Comment by quanjielin** [comment]
TODOs 
1.integration shows that stat_prefix in sds_config is required, otherwise envoy fails to start, need to add stat_prefix
```
          sds_config:
            api_config_source:
              api_type: GRPC
              grpc_services:
              - google_grpc:
                  stat_prefix: test
                  target_uri: unix:/tmp/uds_path
              refresh_delay: 60s
```
2. 
update repo's dependence's sha (https://github.com/istio/istio/blob/master/Gopkg.lock#L1232) to take in https://github.com/grpc/grpc/pull/15909 then remove distribute dummy cert logic

**Comment by quanjielin** [comment]
looks like https://github.com/grpc/grpc/pull/15909 is now in https://github.com/grpc/grpc/releases

**Comment by quanjielin** [comment]
```
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                - google_grpc:
                    stat_prefix: test
                    target_uri: unix:/var/run/sds/uds_path
                    channel_credentials:
                      ssl_credentials:
                        root_certs:
                          filename: /etc/istio/nodeagent-root-cert.pem
                    call_credentials:
                      google_compute_engine: {}
                refresh_delay: 60s
```
1. root cert is required
```
"Failed to load file","file":"external/com_github_grpc_grpc/src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"/usr/share/grpc/roots.pem","referenced_errors":[{"created":"@1532121739.338159947","description":"O
```
2. common name is required in cert by gRPC
```
[{"match":{"prefix":"/service/1"},"route":{"cluster":"local_service_tls"}}]}],"name":"local_route"},"stat_prefix":"ingress_http","codec_type":"auto"}
E0720 23:50:50.471758021       8 ssl_transport_security.cc:251] Could not get common name of subject from certificate.
[2018-07-20 23:50:50.472][8][trace][grpc] external/envoy/source/common/grpc/google_async_client_impl.cc:46] completionThrea
```
