### ISSUE TITLE
Istio injector annotations don't work as described in doc

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#6476]
**Describe the bug**
Istio injector annotations don't work as describe in at https://istio.io/docs/setup/kubernetes/sidecar-injection/#policy, 

* policy=disabled -> The sidecar injector will not inject the sidecar into pods by default. Add the sidecar.istio.io/inject annotation with value true to the pod template spec to enable injection.
* policy=enabled -> The sidecar injector will inject the sidecar into pods by default. Add the sidecar.istio.io/inject annotation with value false to the pod template spec to disable injection

**Expected behavior**
When policy=disabled the sidecar injector will not inject the sidecar into pods by default. Add the sidecar.istio.io/inject annotation with value true to the pod template spec to enable injection.

**Steps to reproduce the bug**
Create a pod in a namespace where policy=disabled or policy unset.  Injection will not happen no matter what we set pod annotation to.

**Version**
0.8

**Is Istio Auth enabled or not?**
No, auth not eabled.

```
helm template --namespace=istio-system \
    --set sidecarInjectorWebhook.enabled=true \
    --set global.proxy.image=proxyv2 \
    --set prometheus.enabled=false \
    install/kubernetes/helm/istio > ../istio.yaml
```
**Environment**
GKE 1.10

**Comment by tcnghia** [comment]
inject_test.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: policy-enabled
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: policy-disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: policy-default
---
apiVersion: v1
kind: Pod
metadata:
  name: nolabel
  namespace: policy-enabled
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: nolabel
  namespace: policy-disabled
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: nolabel
  namespace: policy-default
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: labeled-true
  namespace: policy-enabled
  annotations:
    "sidecar.istio.io/inject": "true"
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: labeled-true
  namespace: policy-disabled
  annotations:
    "sidecar.istio.io/inject": "true"
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: labeled-true
  namespace: policy-default
  annotations:
    "sidecar.istio.io/inject": "true"
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: labeled-false
  namespace: policy-enabled
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: labeled-false
  namespace: policy-disabled
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: labeled-false
  namespace: policy-default
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  containers:
  - image: docker.io/citizenstig/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
```

```
$ kubectl get pods --all-namespaces=true | grep "label\|NAME"
NAMESPACE                NAME                                                READY     STATUS              RESTARTS   AGE
policy-default           labeled-false                                       1/1       Running             0          13s
policy-default           labeled-true                                        1/1       Running             0          13s
policy-default           nolabel                                             1/1       Running             0          13s
policy-disabled          labeled-false                                       1/1       Running             0          13s
policy-disabled          labeled-true                                        1/1       Running             0          13s
policy-disabled          nolabel                                             1/1       Running             0          13s
policy-enabled           labeled-false                                       1/1       Running             0          13s
policy-enabled           labeled-true                                        2/2       Running             0          13s
policy-enabled           nolabel                                             2/2       Running             0          13s
```
