### ISSUE TITLE
Request timeout in VirtualService does not apply.

### ISSUE THREAD

**Issue by ZhiminXiang** [istio/istio#6500]
**Describe the bug**
I want to apply a request timeout on a service. So I tested with [httpbin](https://github.com/istio/istio/tree/master/samples/httpbin) example, and applied a VirtualService with request timeout 0s. And it does not work. Please see below "Steps to reproduce the bug" for more details.

**Expected behavior**
Request to service httpbin should be timed out immediately.

**Steps to reproduce the bug**
Step 1: kubectl apply -f sample/httpbin/httpbin.yaml (I have enabled automatic sidecar injection, and verified sidecar was injected into httpbin pod)

Step 2: apply following VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timeouttest
  namespace: default
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
    - route:
      - destination:
          host: httpbin.default.svc.cluster.local
        timeout: 0s
```

Step 3: log into sidecar, and curl httpbin service:
curl httpbin:8000 -I -v

I successfully got the result:
```
* Rebuilt URL to: httpbin:8000/
*   Trying 10.59.241.226...
* Connected to httpbin (10.59.241.226) port 8000 (#0)
> HEAD / HTTP/1.1
> Host: httpbin:8000
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< server: envoy
server: envoy
< date: Thu, 21 Jun 2018 23:26:31 GMT
date: Thu, 21 Jun 2018 23:26:31 GMT
< content-type: text/html; charset=utf-8
content-type: text/html; charset=utf-8
< content-length: 11602
content-length: 11602
< access-control-allow-origin: *
access-control-allow-origin: *
< access-control-allow-credentials: true
access-control-allow-credentials: true
< x-envoy-upstream-service-time: 5
x-envoy-upstream-service-time: 5
< x-envoy-decorator-operation: default-route
x-envoy-decorator-operation: default-route
```
which is unexpected.

I also got the istio config of httpbin pod:
https://gist.github.com/ZhiminXiang/c4d2ab067ff52c116b22004f52bae9ff

I did not the see request timeout was set.

**Version**
Istio: 0.8.0
k8s: v1.10.4

**Is Istio Auth enabled or not?**
No

**Environment**
I ran my cluster on GKE.
