### ISSUE TITLE
Missing --- separator in helm chart

### ISSUE THREAD

**Issue by olafure** [istio/istio#6517]
There is a bug in the helm template introduced in this commit (19h ago):
https://github.com/istio/istio/pull/6389/commits/69d84ff928265f6aba45c142acc042718c57080f

There's a missing "---" separator in istio/charts/gateways/templates/clusterrolebindings.yaml

Output from "helm template":
```
# Source: istio/charts/gateways/templates/clusterrolebindings.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-ingressgateway-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-istio-egressgateway-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-istio-egressgateway-service-account
    namespace: istio-system
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-ingressgateway-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-istio-ingressgateway-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-istio-ingressgateway-service-account
    namespace: istio-system

```
