### ISSUE TITLE
Request timeout does not work in VirtualService

### ISSUE THREAD

**Issue by ZhiminXiang** [istio/istio#6558]
**Describe the bug**
I want to apply a request timeout on a service. So I tested with httpbin example, and applied a VirtualService with request timeout 1s. And it does not work. Please see below "Steps to reproduce the bug" for more details.

**Expected behavior**
Request to service httpbin should be timed out after 1s.

**Steps to reproduce the bug**
Step 1: kubectl apply -f sample/httpbin/httpbin.yaml (I have enabled automatic sidecar injection, and verified sidecar was injected into httpbin pod)

Step 2: apply following VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timeouttest
  namespace: default
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
    - route:
      - destination:
          host: httpbin.default.svc.cluster.local
          port:
            number: 8000
        weight: 100
      timeout: 1s
```
I think above VirtualService should enforce the request timeout of service httpbin to 1s.

Step 3:
Log into Istio sidecar of httpbin Pod, and run
```
curl httpbin:8000/delay/10
```
The request should be timed out after 1s. But actually the request was succeeded after 10s, which means the 1s timeout does not work.

The response I got was
```
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "httpbin:8000", 
    "User-Agent": "curl/7.47.0", 
    "X-B3-Sampled": "1", 
    "X-B3-Spanid": "37586a7a088e9649", 
    "X-B3-Traceid": "37586a7a088e9649", 
    "X-Request-Id": "268910a2-a073-9a82-9bb4-ca1cac5281f1"
  }, 
  "origin": "127.0.0.1", 
  "url": "http://httpbin:8000/delay/10"
}
```
Note that I got above result when testing version https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-20180608-09-15/ since I want to bypass the timeout issue discussed in https://groups.google.com/forum/#!searchin/istio-users/request$20timeout%7Csort:date/istio-users/I0eGDEbnGhg/CrP0gAOMAgAJ

**Version**
I tested two versions:
1. current 0.8.0 release version
2. nightly version https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-20180608-09-15/ 

Both of these two versions does not work.

**Is Istio Auth enabled or not?**
No

**Comment by ZhiminXiang** [comment]
This is the related config from httpbin Pod sidecar:
```
"route_config": {
            "name": "8000",
            "validate_clusters": false,
            "virtual_hosts": [
             {
              "routes": [
               {
                "route": {
                 "cluster": "outbound|8000||httpbin.default.svc.cluster.local",
                 "use_websocket": false,
                 "timeout": "1.000s"
                },
                "decorator": {
                 "operation": "timeouttest"
                },
                "match": {
                 "prefix": "/"
                },
                "per_filter_config": {}
               }
              ],
              "domains": [
               "httpbin.default.svc.cluster.local",
               "httpbin.default.svc.cluster.local:8000",
               "httpbin",
               "httpbin:8000",
               "httpbin.default.svc.cluster",
               "httpbin.default.svc.cluster:8000",
               "httpbin.default.svc",
               "httpbin.default.svc:8000",
               "httpbin.default",
               "httpbin.default:8000",
               "10.59.247.40",
               "10.59.247.40:8000"
              ],
              "name": "httpbin.default.svc.cluster.local:8000"
             }
            ]
           },
```

**Comment by cmluciano** [comment]
cc @andraxylia @rshriram think we should prioritize/confirm this works for 1.0?

**Comment by ZhiminXiang** [comment]
Thanks @ymesika for looking into this.
I just tried from pod samples/sleep, it works. 

Then I tried to set up below Gateway and VirtualServices so that I can curl from outside of service mesh. But the timeout does not work.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-ingress
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - httpbin-gateway
  http:
    - route:
      - destination:
          host: httpbin
          port:
            number: 8000
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timeouttest
  namespace: default
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
    - route:
      - destination:
          host: httpbin.default.svc.cluster.local
          port:
            number: 8000
        weight: 100
      timeout: 1s
```
I have ran "istioctl proxy-config pilot mesh ads " to verify that these two VirtualServices have been applied. See https://paste.googleplex.com/6272946473533440

**Comment by ymesika** [comment]
In your YAMLs above the ingress traffic is being routed to the httpbin:8000 without any timeout. So it's expected that there won't be any timeout.

**Comment by ZhiminXiang** [comment]
Thanks @ymesika !

Two followup questions:
1. Will the Istio sidecar in server side also check and apply VirtualService? Or only the Istio sidecar in client side applies VirtualService? In my above example, I thought when a request was routed from Gateway to httpbin service, the Istio sidecar in httpbin service would apply VirtualService "timeouttest", which would enforce timeout to 1s. But my understanding seems like incorrect.

2. We have a use case that we may need to set different request timeout in each destination of VirtualService. For example, for below VirtualService, we want to have different timeout for service httpbin and httpbin-1.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-ingress
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - httpbin-gateway
  http:
    - route:
      - destination:
          host: httpbin
          port:
            number: 8000
        weight: 50
     - destination:
          host: httpbin-1
          port:
            number: 8000
        weight: 50
```
Originally I thought I can create a VirtualService like "timeouttest" in my above comment to enforce timeout for service httpbin. But it does not work.
Is there any way to achieve this?
