### ISSUE TITLE
Istio Ingress TLS key management use ACM

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6566]
@truyet commented on [Thu Apr 26 2018](https://github.com/istio/old_issues_repo/issues/305)

**Is this a BUG or FEATURE REQUEST?:**
FEATURE REQUEST
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version  0.7.1
kubectl version 1.10.1
```

**Is Istio Auth enabled or not ?**
Not

**What happened**:
I deploy kubernetes cluster to aws use kops. Istio deployed on this cluster. Now I config Istio Ingress allow HTTPS use TLS Key on Amazon Certificate Manager (ACM) following:
https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws

But Ingress service throw error file not found: /etc/istio/ingress-certs or /etc/certs
 
**What you expected to happen:**
We can apply [ssl-support-on-aws](https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws) to istio ingress service.

**Feature Request:**
Y

**Describe the feature:**
Istio Ingress service support Amazon Certificate Management

Reference:
https://medium.com/kokster/how-to-setup-nginx-ingress-controller-on-aws-clusters-7bd244278509
https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/tls-termination

**Comment by chrisz100** [comment]
I would really like to see this implemented as it will always end up in weird fixes otherwise.

**Comment by sprutner** [comment]
I would love to see this, +1

**Comment by cmcconnell1** [comment]
Hello All, +1 here, don't want to see this go stale.  Thanks

**Comment by rshriram** [comment]
What exactly is the issue here? You can add these annotations to the ingress gateway service (via helm charts). Tls terminates at ELB and you get plain text traffic on port 80.

Isn’t this the same as setting up a normal plain text gateway on port 80 or whatever port you want (even 443).

**Comment by cmcconnell1** [comment]
Hey @rshriram thanks for the response.
I don't see any notes or mention of how this can be done (using AWS IAM or AWS ACM certs) in any Istio docs.  If I'm missing something, would you mind pointing me to where I could find that? 

Regarding annotations in the value.yaml file (or could be provided via command-line but is very messy and error-prone), could you please let me know if the below is correct?
I modified the below (annotations) section in the istio helm chart's values.yaml file

```
ingress:
  enabled: false
  replicaCount: 1
  autoscaleMin: 1
  autoscaleMax: 5
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::0123456789012:server-certificate/my-company-com-crt"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    loadBalancerIP: ""
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    ports:
    - port: 80
      name: http
      nodePort: 32000
    - port: 443
      name: https
    selector:
      istio: ingress
```

And then I'm trying to install via helm with the following syntax:
`helm install -f ./install/kubernetes/helm/istio/values.yaml install/kubernetes/helm/istio --name istio --namespace istio-system`

However when I inspect the AWS ELB that is created with Istio helm installation, I don't see the certificate listed in the the Istio-created ELB for TLS/SSL on port 443

We see this with kubernetes ingress-nginx deployed ELB and the associated AWS IAM certificate:
```
aws elb describe-load-balancers --load-balancer-name a4c1d344fc76b11e8bfc606a2e6fe279 | grep SSL
                        "SSLCertificateId": "arn:aws:iam::0123456789012:server-certificate/my-company-com-crt"
```

But there is no certificate associated with the ELB from the recently deployed Istio ELB:
```
$ aws elb describe-load-balancers --load-balancer-name a648e838ec76c11e8a17d02936d24ced | grep SSL

```
I think that is what this original issue is for (in their case its AWS ACM cert in my case its AWS IAM cert which requires specifying an ARN).

Thank you,

**Comment by rshriram** [comment]
You need to use istio-ingressgateway, not ingress.

**Comment by cmcconnell1** [comment]
Hello All,

Here are two methods I've validated to configure Istio Ingress using AWS IAM cert for 443 Listener on AWS ELB

```
istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean 
```

**Manual kubectl Method 1** 
Following the Istio docs in which we render Istio core components into a kube manifest file
[option-1-install-with-helm-via-helm-template](https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template)

And then modify that file (not in the docs but assuming this is the correct process?) and we add in the annotations noted below

Note that the `aws-load-balancer-connection-idle-timeout` annotation appears valid here in this process using kubectl, but it will **break** your istio deployment if you try to include it in your values.yaml file.  See below.
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::012345678901:server-certificate/my-company-com-crt"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
  labels:
    chart: gateways-1.0.1
    release: istio
    heritage: Tiller
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
...
```
Post `kubectl apply -f istio.yaml` this works and installs the Istio ingress with the requisite AWS IAM certificate.

**Helm Values.yaml Method 2**
Add almost the same annotations to the values.yaml under the gateways.istio-ingressgateway code section.
But do **not** include  `aws-load-balancer-connection-idle-timeout` in your values.yaml file:
i.e. omit from the values.yaml
```
service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "xx"
```

working values.yaml for me
```
gateways:
  enabled: true
  istio-ingressgateway:
    enabled: true
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    replicaCount: 1
    autoscaleMin: 1
    autoscaleMax: 5
    resources: {}
    cpu:
      targetAverageUtilization: 80
    loadBalancerIP: ""
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::012345678901:server-certificate/my-company-com-crt"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    ports:
    - port: 80
      targetPort: 80
      name: http2
      nodePort: 31380
    - port: 443
      name: https
      nodePort: 31390
...
```

Side note, if you do include the `aws-load-balancer-connection-idle-timeout` annotation in the values.yaml file, you will see the below error which I had to look at a couple of times.
It somewhat masks the problematic line/code in the error message, but the key is:
> ...timeout

```
helm install -f ./install/kubernetes/helm/istio/values.yaml install/kubernetes/helm/istio --name istio --namespace istio-system
Error: release istio failed: Service in version "v1" cannot be handled as a Service: v1.Service: ObjectMeta: v1.ObjectMeta: Annotations: ReadString: expects " or n, parsing 206 ...timeout":6... at {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-backend-protocol":"http","service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout":60,"service.beta.kubernetes.io/aws-load-balancer-ssl-cert":"arn:aws:iam::012345678901:server-certificate/my-company-com-crt","service.beta.kubernetes.io/aws-load-balancer-ssl-ports":"https"},"labels":{"app":"istio-ingressgateway","chart":"gateways-1.0.1","heritage":"Tiller","istio":"ingressgateway","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"http2","nodePort":31380,"port":80,"targetPort":80},{"name":"https","nodePort":31390,"port":443},{"name":"tcp","nodePort":31400,"port":31400},{"name":"tcp-pilot-grpc-tls","port":15011,"targetPort":15011},{"name":"tcp-citadel-grpc-tls","port":8060,"targetPort":8060},{"name":"tcp-dns-tls","port":853,"targetPort":853},{"name":"http2-prometheus","port":15030,"targetPort":15030},{"name":"http2-grafana","port":15031,"targetPort":15031}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
```

Hope this helps others out.
I think this information might be very helpful for inclusion in the Istio docs?

**Comment by abuchanan920** [comment]
Not sure if this helps with the issue you were seeing with putting the timeout in, but I was getting that message with an attribute that required "true" and managed to get it working by putting it in as '"true"' (note the single quotes around the double quotes). Not sure if something similar would work for you here...

**Comment by naveeng68** [comment]
> Hello All,
> 
> Here are two methods I've validated to configure Istio Ingress using AWS IAM cert for 443 Listener on AWS ELB
> 
> ```
> istioctl version
> Version: 1.0.2
> GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
> User: root@66ce69d4a51e
> Hub: gcr.io/istio-release
> GolangVersion: go1.10.1
> BuildStatus: Clean 
> ```
> **Manual kubectl Method 1**
> Following the Istio docs in which we render Istio core components into a kube manifest file
> [option-1-install-with-helm-via-helm-template](https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template)
> 
> And then modify that file (not in the docs but assuming this is the correct process?) and we add in the annotations noted below
> 
> Note that the `aws-load-balancer-connection-idle-timeout` annotation appears valid here in this process using kubectl, but it will **break** your istio deployment if you try to include it in your values.yaml file. See below.
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   name: istio-ingressgateway
>   namespace: istio-system
>   annotations:
>     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::012345678901:server-certificate/my-company-com-crt"
>     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
>     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
>     service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
>   labels:
>     chart: gateways-1.0.1
>     release: istio
>     heritage: Tiller
>     app: istio-ingressgateway
>     istio: ingressgateway
> spec:
>   type: LoadBalancer
>   selector:
>     app: istio-ingressgateway
>     istio: ingressgateway
> ...
> ```
> Post `kubectl apply -f istio.yaml` this works and installs the Istio ingress with the requisite AWS IAM certificate.
> 
> **Helm Values.yaml Method 2**
> Add almost the same annotations to the values.yaml under the gateways.istio-ingressgateway code section.
> But do **not** include `aws-load-balancer-connection-idle-timeout` in your values.yaml file:
> i.e. omit from the values.yaml
> 
> ```
> service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "xx"
> ```
> working values.yaml for me
> 
> ```
> gateways:
>   enabled: true
>   istio-ingressgateway:
>     enabled: true
>     labels:
>       app: istio-ingressgateway
>       istio: ingressgateway
>     replicaCount: 1
>     autoscaleMin: 1
>     autoscaleMax: 5
>     resources: {}
>     cpu:
>       targetAverageUtilization: 80
>     loadBalancerIP: ""
>     serviceAnnotations:
>       service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::012345678901:server-certificate/my-company-com-crt"
>       service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
>       service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
>     type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
>     ports:
>     - port: 80
>       targetPort: 80
>       name: http2
>       nodePort: 31380
>     - port: 443
>       name: https
>       nodePort: 31390
> ...
> ```
> Side note, if you do include the `aws-load-balancer-connection-idle-timeout` annotation in the values.yaml file, you will see the below error which I had to look at a couple of times.
> It somewhat masks the problematic line/code in the error message, but the key is:
> 
> > ...timeout
> 
> ```
> helm install -f ./install/kubernetes/helm/istio/values.yaml install/kubernetes/helm/istio --name istio --namespace istio-system
> Error: release istio failed: Service in version "v1" cannot be handled as a Service: v1.Service: ObjectMeta: v1.ObjectMeta: Annotations: ReadString: expects " or n, parsing 206 ...timeout":6... at {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-backend-protocol":"http","service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout":60,"service.beta.kubernetes.io/aws-load-balancer-ssl-cert":"arn:aws:iam::012345678901:server-certificate/my-company-com-crt","service.beta.kubernetes.io/aws-load-balancer-ssl-ports":"https"},"labels":{"app":"istio-ingressgateway","chart":"gateways-1.0.1","heritage":"Tiller","istio":"ingressgateway","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"http2","nodePort":31380,"port":80,"targetPort":80},{"name":"https","nodePort":31390,"port":443},{"name":"tcp","nodePort":31400,"port":31400},{"name":"tcp-pilot-grpc-tls","port":15011,"targetPort":15011},{"name":"tcp-citadel-grpc-tls","port":8060,"targetPort":8060},{"name":"tcp-dns-tls","port":853,"targetPort":853},{"name":"http2-prometheus","port":15030,"targetPort":15030},{"name":"http2-grafana","port":15031,"targetPort":15031}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
> ```
> Hope this helps others out.
> I think this information might be very helpful for inclusion in the Istio docs?

Hi @cmcconnell1,
as per your 1st example its attaching certificate but its not redirect to http to https
example: I defined  hostname under gateway is testservice.com
its open in both ways http:// testservice.com and https://testservice.com
I want if someone type http://testservice.com It should redirect to https://testservice.com
*****
my gateway.yaml is below
-------
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-service-b
  annotations:
   ingress.kubernetes.io/force-ssl-redirect: "true"
   kubernetes.io/ingress.class: "istio-gateway"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - test-service-*****.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-service-b
spec:
  hosts:
  - test-service-*****.com
  gateways:
  - test-service-b
  http:
  - match:
    route:
    - destination:
        host: test-service-b
        port:
          number: 80
-------
My service yaml 
------
kind: Service
apiVersion: v1
metadata:
  name: test-service-b
  labels:
    app: test-service-b
spec:
  ports:
  - name: http
    port: 80
    targetPort: 7081
  selector:
    app: test-service-b
-----

**Comment by naveeng68** [comment]
Hi @cmcconnell1,
as per your 1st example its attaching certificate but its not redirect to http to https
example: I defined hostname under gateway is testservice.com
its open in both ways http:// testservice.com and https://testservice.com
I want if someone type http://testservice.com It should redirect to https://testservice.com

my gateway.yaml is below
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
name: test-service-b
annotations:
ingress.kubernetes.io/force-ssl-redirect: "true"
kubernetes.io/ingress.class: "istio-gateway"
spec:
selector:
istio: ingressgateway # use istio default controller
servers:

port:
number: 80
name: http
protocol: HTTP
hosts:
test-service-*****.com
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
name: test-service-b
spec:
hosts:

test-service-*****.com
gateways:
test-service-b
http:
match:
route:
destination:
host: test-service-b
port:
number: 80
My service yaml
kind: Service
apiVersion: v1
metadata:
name: test-service-b
labels:
app: test-service-b
spec:
ports:

name: http
port: 80
targetPort: 7081
selector:
app: test-service-b

**Comment by naveeng68** [comment]
@cmcconnell1 and @rshriram 
Any update on above issue?

**Comment by eduardobaitello** [comment]
@naveeng68 you need to set the `tls.httpsRedirect` on your gateway to **true**, as used [here](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway):
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    app: my-gatweway-controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - uk.bookinfo.com
    - eu.bookinfo.com
    tls:
      httpsRedirect: true # sends 301 redirect for http requests <<<----------------------
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - uk.bookinfo.com
    - eu.bookinfo.com
```

According to [Server.TLSOptions](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Server-TLSOptions):

> httpsRedirect: If set to true, the load balancer will send a 301 redirect for all http connections, asking the clients to use HTTPS.

**Comment by naveeng68** [comment]
@eduardobaitello .  its not working: (please find my code) I am using AWS certificate 
mention annotation under istio-ingressgateway
annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::****/my-company-com-crt"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
certificte has been attached under my AWS load balancer
***my load balancer port listener entryi***

Load Balancer Protocol | Load Balancer Port | Instance Protocol | Instance Port |  SSLCert
HTTPS                            | 443                          | HTTP                      | 31390             | 110cb58b**(ACM)
HTTP                              | 80                             | HTTP                      | 31380             | N/A

-----------------------
ingress.yaml
------------------------
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-service-a
  annotations:
   ingress.kubernetes.io/force-ssl-redirect: "true"
   kubernetes.io/ingress.class: "istio-gateway"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - test-service-*****.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - test-service-*****.com
    tls:
      httpsRedirect: false . # if I am write true redirect is working but showing error too many redirect
                                          # if I am not enter tls tag under https showing error u have to mention tls tag 
                                           # with cert details
                                           # what I ahve to under tls tag if i am using AWS cert
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-service-a
spec:
  hosts:
  - test-service-*****.com
  gateways:
  - test-service-a
  http:
  - match:
    route:
    - destination:
        host: test-service-a
        port:
          number: 7080
-------------
service.yaml
-------------
kind: Service
apiVersion: v1
metadata:
  name: test-service-a
  labels:
    app: test-service-a
spec:
  ports:
  - name: http
    port: 7080
  selector:
    app: test-service-a
----------
So please guide me.

**Comment by eduardobaitello** [comment]
@naveeng68 when doing [SSL Termination](https://aws.amazon.com/pt/blogs/aws/elastic-load-balancer-ssl-support-options/) the expected backend protocol is **HTTP**, not HTTPS (as I noted in my last comment).

You are even explicit setting [this](https://github.com/kubernetes/kubernetes/blob/8f620950e246fab5b6bac25682a0b5db312bbe25/pkg/cloudprovider/providers/aws/aws.go#L168-L175) in your service `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"`, but your Istio Gateway is using HTTPS protocol on port 443.

Please, try this config, changing your 443 port protocol to HTTP:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-service-a
  annotations:
   ingress.kubernetes.io/force-ssl-redirect: "true"
   kubernetes.io/ingress.class: "istio-gateway"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - test-service-*****.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTP    # <<<< -------- Using HTTP instead of HTTPS
    hosts:
    - test-service-*****.com
    # tls config is not needed anymore
```

**Comment by naveeng68** [comment]
Hi, 
How we implement multiple istio ingress (i want to implement multiple AWS certificate each cert have different domain name).
like in nginx ingress controller we create one more ngnix controller. with separate name.

**Comment by mabushey** [comment]
@naveeng68 In AWS with cert manager you can create one SSL cert with numerous domains and wildcard subdomains.

**Comment by mabushey** [comment]
`aws-load-balancer-connection-idle-timeout` in the helm values.yaml is generated in istio-release-1.1-20181115-09-15 and applies perfect.

**Comment by szymonpk** [comment]
Just FYI, idle-timeout works on 1.0.5 with double quoting `service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '"120"'`, as suggested by @abuchanan920.

**Comment by mabushey** [comment]
@VinceMD I had AWS up our limit on names in the cert to 50. I have numerous entries like
```
*.example.com
*.green.example.com
*.blue.example.com
```

**Comment by r0fls** [comment]
I tried following the instructions [here](https://github.com/istio/istio/issues/6566#issuecomment-427136888). However I still see this error in the istio-ingressgateway pods:

```
[2019-06-04 03:09:36.556][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/istio/ingress-certs/tls.crt
```

These are my service annotations:

```
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:abcdef:ghijklmnop
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
```

The http route works as expected, but https times out. I'm using the istio 1.1.3 version of the helm chart.

**Comment by jamesteague85** [comment]
@r0fls we are having the same issue, did you find a solution?

**Comment by r0fls** [comment]
@jamesteague85 yes, I had to set `k8sIngress.enabled` to `false`. It was loading a file `preconfigured.yaml` which was causing the TLS error.

**Comment by nvcnvn** [comment]
> @jamesteague85 yes, I had to set `k8sIngress.enabled` to `false`. It was loading a file `preconfigured.yaml` which was causing the TLS error.

I need to do the same thing and it work.
I'm not sure if I need to keep the `k8sIngress.enabled` as `true` if I'm using certmanager?

**Comment by r0fls** [comment]
That should not be required for usage with certmanager. That flag is enabling the legacy kubernetes ingress support (i.e. support using ingress class istio on kubernetes Ingress objects). The current way to use istio does not use kubernetes Ingress objects, it uses VirtualServices and Gateways. So, disabling that should be fine for new deployments that don't need to support legacy ingress objects.

**Comment by bjoernw** [comment]
If I terminate TLS at the ELB do I have send the traffic downstream over http? Does that mean that there is 1 hop in my system from the ELB to the istio gateway pod that will be plaintext (im using mtls between all the istio services)?

**Comment by prageethw** [comment]
> @naveeng68 when doing [SSL Termination](https://aws.amazon.com/pt/blogs/aws/elastic-load-balancer-ssl-support-options/) the expected default backend protocol is **HTTP**, not HTTPS (as I noted in my last comment).
> 
> You are even explicit setting [this](https://github.com/kubernetes/kubernetes/blob/8f620950e246fab5b6bac25682a0b5db312bbe25/pkg/cloudprovider/providers/aws/aws.go#L168-L175) in your service `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"`, but your Istio Gateway is using HTTPS protocol on port 443.
> 
> Please, try this config, changing your 443 port protocol to HTTP:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: test-service-a
> spec:
>   selector:
>     istio: ingressgateway # use istio default controller
>   servers:
>   - port:
>       number: 80
>       name: http
>       protocol: HTTP
>     hosts:
>     - test-service-*****.com
>     tls:
>       httpsRedirect: true
>   - port:
>       number: 443
>       name: https
>       protocol: HTTP    # <<<< -------- Using HTTP instead of HTTPS
>     hosts:
>     - test-service-*****.com
>     # tls config is not needed anymore
> ```

tried as above does not work for me, it re-directs for both http and https requests.

`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-demo-7
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-demo-7
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - go-demo.cluster.prageethw.co
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - go-xxxxageethw.co
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - go-xxxxageethw.co`

**Comment by prageethw** [comment]
mysteriously started to work ob below configs, incase if someone still looking for ssl re-direct gateway config

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: go-demo-7
spec:
  hosts:
  - go-demo.cluster.xxxx.co
  gateways:
  - go-demo-7
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: go-demo-7
        port:
          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-demo-7
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-go-demo-7
      protocol: HTTP
    hosts:
    - go-demo.cluster.xxxx.co
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-go-demo-7
      protocol: HTTP #need to set this as http to enable elb ssl offloading.   
    hosts:
    - go-demo.cluster.xxxx.co

```
