### ISSUE TITLE
DNS over TCP egress traffic is hijacked by iptables rules

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6568]
@janosi commented on [Thu Apr 19 2018](https://github.com/istio/old_issues_repo/issues/293)

**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean


kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.

**What happened**:
We realized that all egress TCP traffic is hijacked by the sidecar proxy in a pod based on the investigation of iptables rules. 

**What you expected to happen:**
DNS may use TCP in some cases (DNSSEC, IPv6, etc), so egress traffic to port 53 should be an exception in iptables.
See https://tools.ietf.org/html/rfc7766

**How to reproduce it:**

**Feature Request:**
N

**Describe the feature:**

---

@vadimeisenbergibm commented on [Thu Apr 19 2018](https://github.com/istio/old_issues_repo/issues/293#issuecomment-382726597)

Meanwhile you can define an Egress Rule (https://istio.io/docs/tasks/traffic-management/egress-tcp.html) or an ExternalService (new starting from 0.8) https://istio.io/docs/tasks/traffic-management-v1alpha3/egress-tcp.html, with the port 53, the protocol `tcp`,  and the CIDR block of all the IP addresses `255.255.255.255/0` (or specific IP blocks used by DNS if you can determine them)

**Comment by louiscryan** [comment]
For those not following along on the PR this is some debate about whether a carve out is needed here at all, i.e DNS via the sidecar over TCP using original-destination based routing should work just fine without needing additional config.

**Comment by ZackButcher** [comment]
Given that the PR referenced in this issue was just marked stale, I figure I'll close it with the configuration a user should use instead. Rather than a blanket carve-out of a port, all that's needed is a ServiceEntry for the DNS server's IP addresses exposing port 53 to TCP traffic:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dns-over-tls
spec:
  hosts:
  - my.dns.server # used to refer to the DNS servers in other Istio config
  addresses:
  # the IP addresses applications will use to contact the DNS server
  - 1.2.3.4
  - 4.5.6.7
  location: MESH_EXTERNAL # don't attempt mTLS to the DNS
  ports:
  - number: 53
    name: tcp
    protocol: TCP
  resolution: STATIC # use the endpoints directly
  endpoints:
  # The actual IP addresses we'll route traffic to; we assume
  # they'll serve on port 53 as well, otherwise we could add port
  # mappings per endpoint here. These endpoints do not have to
  # match the `addresses` above.
  - address: 1.2.3.4
  - address: 4.5.6.7
  - address: 8.9.10.11
```

The above configures the IP addresses `1.2.3.4` and `4.5.6.7` to act as virtual IP addresses for the DNS servers at the endpoints `1.2.3.4`, `4.5.6.7`,  `8.9.10.11`, which we gave the name `my.dns.server`. Now applications can make queries to `1.2.3.4` and `4.5.6.7` on port 53 and we'll route the traffic to the three underlying endpoints. We also have the ability to control how this traffic behaves via a VirtualService for the host `my.dns.server`, and we'll get TCP metrics for the traffic to the DNS servers (if reporting is enabled in Istio), neither of which we'd get if we instead omitted port 53 from the IP tables rules.
