### ISSUE TITLE
TCP routing rules are ignored

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6574]
@mydoal commented on [Thu May 10 2018](https://github.com/istio/old_issues_repo/issues/334)

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: release-0.8-20180504-17-20
GitRevision: 1ec141e7b9a735c6bcc2b4fae29c6924bc94c49b
User: root@20f3450616f6
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:
```

**Is Istio Auth enabled or not ?**

Installed from:
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-0.8-20180504-17-20/

**What happened**:

TCP Routing rules are ignored.
Services in the mesh that use "service-mongodb" on port 80 keep reaching that service instead of being forwarded to port 27018 as defined in the routing rules.

**What you expected to happen:**
Services in the mesh that use "service-mongodb" should be routed to port 27018.

**How to reproduce it:**

service-mongodb is defined in a yaml file 
```
apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
  labels:
    app: service-mongodb
spec:
  selector:
    app: service-mongodb
  ports:
  - port: 80
    targetPort: 27017
    name: mongo
    protocol: TCP
```

and deployed to kubernetes using:
```
kubectl apply -f <(istioctl kube-inject --debug -f mongodb.yaml)
```

TCP Routing Rules
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-mongodb-route
spec:
  hosts:
  - service-mongodb
  tcp:
  - match:
    - port: 80
      sourceSubnet: "0.0.0.0/0"
    route:
    - destination:
        host: service-mongodb
        port:
          number: 27018
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-mongodb-destination
spec:
  host: service-mongodb
```

**Feature Request:**
Y/N

**Describe the feature:**

---

@mydoal commented on [Wed May 16 2018](https://github.com/istio/old_issues_repo/issues/334#issuecomment-389490236)

bump... 
Does someone have any insight on this?

**Comment by mydoal** [comment]
If the support for inter service TCP routing rules is postponed until version 1.1, why is it described in the documentation since 0.7? It can be understood that this is already supported.

https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TCPRoute

**Comment by Arttii** [comment]
@mydoal So is it definitely not there in 1.0?. I was trying to get this working and run into the same issue with the traffic just going to one service in the back.

**Comment by rshriram** [comment]
This should be there in 1.0..

**Comment by Arttii** [comment]
@rshriram Then it might be I am doing something wrong. I am trying to have TCP ingress for two PODs(Services) on the same ports via two gateways and two Virtualservices, but all ingress-gateway requests seem to go to just one of the Pods(Services)

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace:  dev
  name:  gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      name: tcp-1
      number: 7801
      protocol: TCP
    hosts:
    - "magic.host.com"
  - port:
      name: tcp-2
      number: 7802
      protocol: TCP
    hosts:
    - "magic.host.com"


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pod-vsvc
  namespace:  dev
spec:
  hosts:
  - "magic.host.com"
  gateways:
  -  gateway
  tcp:
  - match:
    - port:  7801
    route:
    - destination:
        host: "pod-csvc"
        port:
          number: 7801
  - match:
    - port: 7802
    route:
    - destination:
        host: "pod-csvc"
        port:
          number: 7802


---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace:  dev
  name:  gateway2
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      name: tcp-1
      number: 7801
      protocol: TCP
    hosts:
    - "magic2.host.com"
  - port:
      name: tcp-2
      number: 7802
      protocol: TCP
    hosts:
    - "magic2.host.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pod2-vsvc
  namespace:  dev
spec:
  hosts:
  - "magic2.host.com"
  gateways:
  -  gateway2
  tcp:
  - match:
    - port:  7801
    route:
    - destination:
        host: "pod2-csvc"
        port:
          number: 7801
  - match:
    - port: 7802
    route:
    - destination:
        host: "pod2-csvc"
        port:
          number: 7802
```

**Comment by Arttii** [comment]
@rshriram Do you know if this is a supported usecase? Or should I open a new issue if its unrelated.

**Comment by jiribroulik** [comment]
@Arttii I have the same issue. Do you have a solution? Seems like the 'hosts' is ignored

**Comment by rshriram** [comment]
thi sis implemented now..

**Comment by rshriram** [comment]
will be in 1.1 release

**Comment by igas** [comment]
Hi @rshriram,

I'm sure it was asked many times but could not find it. Is there are expected date for 1.1 or roadmap somewhere?

Thank you.

**Comment by erolosty** [comment]
Also looking forward to this

**Comment by rshriram** [comment]
in couple of weeks max.

**Comment by keatz55** [comment]
Did this issue ever get resolved? I'm using istio 1.5 with the following config and the `hosts` option is being completely ignored for me:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vms-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 1935
        name: rtmp
        protocol: TCP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vms-rtmp
spec:
  hosts:
    - subdomain1.test.local
  gateways:
    - vms-gateway
  tcp:
    - route:
        - destination:
            host: nginx-rtmp-server
            port:
              number: 1935
```
