### ISSUE TITLE
Unable to access sql azure when using sidecar

### ISSUE THREAD

**Issue by aminebizid** [istio/istio#6587]
I'm using the ServiceEntry below and I get this error:
```error
A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Success)
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: sqlazure
spec:
  hosts:
  - "*.database.windows.net"
  ports:
    protocol: HTTPS
  - number: 1433
    name: sql
    protocol: TCP

```

It works without sidecar
