### ISSUE TITLE
non cluster scoped authN policy CRD validation fail with namespace passed from istioctl

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#6620]
**Describe the bug**
[non cluster scoped authN policy CRD validation fail](https://github.com/istio/istio/blob/da6d5e4200f06518df5c3532113b717f6c2b5f7e/pilot/pkg/model/validation.go#L1753) with namespace passed from istioctl

**Expected behavior**
CRD validation should pass

**Steps to reproduce the bug**
1. follow https://istio.io/docs/tasks/traffic-management/ingress to setup env(used docker images built from my dev env)
2. apply authN policy below, hit error (
$ istioctl create -f Jwt_policy.yaml -n istio-system
Error: configuration is invalid: 2 errors occurred:

* cluster-scoped authentication policy name must be "default", found "ingressgateway"
* cluster-scoped authentication policy must not have targets

policy applied on ingressgateway 
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "ingressgateway"
spec:
  targets:
  - name: istio-ingressgateway
  origins:
  - jwt:
      issuer: "628645741881-noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/628645741881-noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com"
  principalBinding: USE_ORIGIN
```
Validation pass if add namespace into policy explicitly like
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "ingressgateway"
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  origins:
  - jwt:
      issuer: "628645741881-noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/628645741881-noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com"
  principalBinding: USE_ORIGIN
```

**Version**
1.10.4-gke.0

**Is Istio Auth enabled or not?**
No authN enabled
