### ISSUE TITLE
Fortio can't be accessed through the istio-ingressgateway in release-0.8

### ISSUE THREAD

**Issue by zxDiscovery** [istio/istio#6623]
Have follow the guide to run istio performance test: https://github.com/istio/istio/blob/release-0.8/tools/README.md
The guideline still use istio ingress to access the fortio with sidecar and indeed it works.

But have tried to access the fortio through the istio-ingressgateway, but it doesn't work.
The follow is my gateway and virtualservice definetion:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fortio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fortio1
spec:
  hosts:
  - "*"
  gateways:
  - fortio-gateway
  http:
  - route:
    - destination:
        host: echosrv1.istio.svc.cluster.local
        port:
          number: 8080
          subset: echosrv1
    match:
     - headers:
         uri:
           prefix: /fortio1/ # prefix
    rewrite:
      uri: /  # drop the /fortio1 prefix when talking to fortio such as /fortio1/debug -> /debug
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fortio1
spec:
  host: echosrv1.istio.svc.cluster.local
  subsets:
  - name: echosrv1
    labels:
      app: echosrv1
```

Why the release-0.8 can't support access fortio through istio-ingressgateway?

/cc @gyliu513 @morvencao

**Comment by morvencao** [comment]
Istio-0.8.0 release version still use istio ingress and `routerules` to access fortio service. 
https://github.com/istio/istio/blob/release-0.8/tools/perf_k8svcs.yaml#L67-L84
https://github.com/istio/istio/blob/release-0.8/tools/perf_istio_rules.yaml

**Comment by gyliu513** [comment]
/cc @ldemailly 

@ThanosAndLichKing @morvencao  can we first use ingress to test performance for 0.8?

**Comment by morvencao** [comment]
@gyliu513 OK, istio ingress with `route rule` works fine currently.

**Comment by gyliu513** [comment]
good, let's go ahead to get some data first. @morvencao @ThanosAndLichKing

**Comment by ldemailly** [comment]
the plan is to convert the setup script to v1alpha3 through the swat team or volunteers, unfortunately nobody had time to step up and do it. In theory it’s just a matter of running the conversion tool, but I do expect there maybe a couple of issues to solve.

it would be interesting to define “not working” above, as in what happens exactly as the config appears correct as pasted, to my non pilot specialist eyes

**Comment by morvencao** [comment]
@ThanosAndLichKing 
Try this `gateway` and `virtualservice` settings:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fortio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fortio
spec:
  hosts:
  - "*"
  gateways:
  - fortio-gateway
  http:
  - match:
    - uri:
        prefix: /fortio1/
    route:
    - destination:
        host: echosrv1.istio.svc.cluster.local
        port:
          number: 8080
    rewrite:
      uri: / # drop the /fortio1 prefix when talking to fortio such as /fortio1/fortio -> /fortio
  - match:
    - uri:
        prefix: /fortio2/
    route:
    - destination:
        host: echosrv2.istio.svc.cluster.local
        port:
          number: 8080
    rewrite:
      uri: / # drop the /fortio2 prefix when talking to fortio such as /fortio2/fortio -> /fortio
```

It will rewrite `/fortio1/fortio/` and `fortio2/fortio/` to `/fortio/`, so that you can access `fortio1` service by `http://${ingressgateway}//fortio1/fortio/` and `fortio2` by `http://${ingressgateway}//fortio2/fortio/`
