### ISSUE TITLE
Grafana service improvements

### ISSUE THREAD

**Issue by Lord-Y** [istio/istio#6630]
Hi guys,

Grafana service charts is not good enough. If you want to expose grafana with an internal IP or public IP with firewall you can't with the default chart.
You guys can take example on `stable/grafana` chart service for the improvements from `helm repo url https://kubernetes-charts.storage.googleapis.com`.

With this improvements, people will be able to do:
```
service:
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  type: LoadBalancer
  loadBalancerIP: 10.X.X.X
```

Cheers.
