### ISSUE TITLE
Should have CORS config for a host.

### ISSUE THREAD

**Issue by truyet** [istio/istio#6655]
**Is your feature request related to a problem? Please describe.**
I have a virtualservice same as:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-service
spec:
  hosts:
  - "example.com"
  gateways:
  - "ingress-gateway"
  http:
  - match:
    - uri:
        prefix: /v1
    route:
    - destination:
        port:
          number: 10000
        host: service-v1
  - match:
    - uri:
        prefix: /v2
    route:
    - destination:
        port:
          number: 10000
        host: service-v2
```
I want to add CORS for all match request. I have to add cors config to each match as:
```yaml
  - match:
     route:
     corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - OPTIONS
      - PUT
      - DELETE
      allowCredentials: true
      allowHeaders:
```
On above case, If I have a host for api of multiple match to microservices, I need to duplicate the same cors config for multi match. It's not clean. 
**Describe the solution you'd like**
We need have a cors config for all match in http as:
```yaml
http:
  corsPolicy:
    ....
  - match:
    ....
```

It's will clean for all match. If another has a custom cors, it'll set a custom cors.
