### ISSUE TITLE
VirtualService is configured error http route. Connection is dropped

### ISSUE THREAD

**Issue by truyet** [istio/istio#6656]
**Describe the bug**
I have a virtualservice config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-service
spec:
  hosts:
  - "example.com"
  gateways:
  - "ingress-gateway"
  http:
  - match:
    - uri:
        prefix: /v1
    route:
    - destination:
        port:
          number: 10000
        host: service
   - corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - OPTIONS
      - PUT
      - DELETE
      allowCredentials: true
      allowHeaders:
      - "Content-Type"
      - "Authorization"
```

istio-pilot discovery show warn:
```sh
2018-06-27T04:35:33.289782Z	warn	ads	ADS:LDS: ACK ERROR 100.96.1.206:44928 istio-ingressgateway-6bc7c7c4bc-77tgf.istio-system version_info:"2018-06-27 04:34:39.766149937 +0000 UTC m=+4140.420198847" node:<id:"router~100.96.1.206~istio-ingressgateway-6bc7c7c4bc-77tgf.istio-system~istio-system.svc.cluster.local" cluster:"istio-ingressgateway" metadata:<fields:<key:"POD_NAME" value:<string_value:"istio-ingressgateway-6bc7c7c4bc-77tgf" > > fields:<key:"istio" value:<string_value:"sidecar" > > > build_version:"0/1.7.0-dev//RELEASE" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"2018-06-27 04:35:33.204840538 +0000 UTC m=+4193.858889547" error_detail:<code:13 message:"Error adding/updating listener 0.0.0.0_80: Proto constraint validation failed (HttpConnectionManagerValidationError.RouteConfig: [\"embedded message failed validation\"] | caused by RouteConfigurationValidationError.VirtualHosts[i]: [\"embedded message failed validation\"] | caused by VirtualHostValidationError.Routes[i]: [\"embedded message failed validation\"] | caused by RouteValidationError.Route: [\"embedded message failed validation\"] | caused by RouteActionValidationError.WeightedClusters: [\"embedded message failed validation\"] ....
```

Ingress gateway can work at the moment before request on host died with err_connection on chrome browser, you can't trace why request connection is dropped.

**Expected behavior**
- We need show some error log on discovery or ingressgateway, request should work normal.

**Version**
- istio : 0.8
- kubernetes version:
```sh
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
not

**Environment**
AWS
