### ISSUE TITLE
hit response code 503 after applying authN policy without explicitly set peers.mtls 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#6668]
**Describe the bug**
customer report this issue:
hit response code 503 after applying authN policy without explicitly set peers.mtls 

**Expected behavior**
response code shouldn't be 503(expected 200 or 401).

**Steps to reproduce the bug**
sample policy which causes the problem
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "example-3"
  namespace: foo
spec:
  targets:
  - name: httpbin
  peers:
  - {}
  origins:
  - jwt:
      issuer: "628645741881-noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/628645741881-noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com"
  principalBinding: USE_ORIGIN
```

**Version**
v1.10.4-gke.2

**Is Istio Auth enabled or not?**
authN enabled

**Environment**
gcloud
