### ISSUE TITLE
listener conflict when configure egress,  svcs use the same port and the protocal is tcp

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#6695]
**Describe the bug**

there are two mysql instances(external), port are all 3306,  i set two service entry ,but the pilot log warn that:

`listener conflict (TCP current and new TCP) on 0.0.0.0:3306, destination:outbound|3306||mysql-1.xxx.io, current Listener: (0.0.0.0_3306 name:"0.0.0.0_3306" ...`

i config these according to  [hosts and address](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry)

**Expected behavior**
the service entrys are:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-1
spec:
  hosts:
  - mysql-1.xxx.io
  addresses:
  - 10.12.13.14/32
  location: MESH_EXTERNAL
  ports:
  - number: 3306
    name: tcp
    protocol: TCP
  resolution: NONE
```
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-2
spec:
  hosts:
  - 10.10.55.66
  addresses:
  - 10.10.55.66/32
  location: MESH_EXTERNAL
  ports:
  - number: 3306
    name: tcp
    protocol: TCP
  resolution: NONE
```

I don't know what the problem is. I have been troubled by this for several days，could u help me solve it？
**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
istio:0.8.0
kubernetes:1.9.5
**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
not
**Environment**
Which environment, cloud vendor, OS, etc are you using?
kubernetes
