### ISSUE TITLE
Deploy ingressgateway as daemonset

### ISSUE THREAD

**Issue by jshearer** [istio/istio#6706]
I'm in the process of setting up a bunch of microservices to run in GKE, and have been using ingresses with the nginx ingress controller, but wanted some of the features of istio, specifically more customizable request routing etc. The problem is, we really don't want to use `LoadBalancers` from the cloud provider (GCE), as they are painfully expensive at small scale. We've been running the ingress controller as a DaemonSet exposing ports 80 and 443, and this has worked perfectly for us so far. The issue is, I don't see an option to deploy the istio `ingressgateway` inside a `DaemonSet`. Is this supposed to be a supported solution, or do I have a conceptual misunderstanding?

**Describe the solution you'd like**
I'd love to be able to deploy Istio as the edge load balancer for my cluster by exposing it on every logical/physical host in the cluster.

As some extra context, we've been doing this by running the nginx ingress controller as a `DaemonSet` with the following parameters:

```
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
```

**Comment by rshriram** [comment]
You can do this easily. Simply modify the YAML for ingress gateway to deploy as a daemon set. The ingressgateway we ship is merely an example of how to deploy the gateway. There is nothing preventing you from deploying the gateway as an ILB/daemonset, etc.

**Comment by gitfool** [comment]
@rshriram Presumably the recommended setup would be to use a daemon set when using a cloud provider load balancer like AWS ELB / NLB?

**Comment by swade1987** [comment]
@rshriram @jshearer 

I am actually trying this right now.

However, it doesn't seem to work as the NLB health check (TCP, port 80 on `/`) does not seem to be working. 

```
kind: DaemonSet
metadata:
  name: ingress-gateway
  namespace: istio-system
  labels:
    chart: ingress-gateway-1.0.3
    release: istio
    heritage: Tiller
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: istio-ingressgateway-service-account
      hostNetwork: true
#      nodeSelector:
#        node-role.kubernetes.io/ingress: ""
#      tolerations:
#        - key: node-role.kubernetes.io/ingress
#          operator: Exists
#          effect: NoSchedule
      containers:
        - name: istio-proxy
          image: "docker.io/istio/proxyv2:1.0.3"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
            - containerPort: 31400
              hostPort: 31400
```

**Comment by FierceElements** [comment]
We're also trying to deploy the `istio-ingressgateway` pods as a DaemonSet of privileged pods whose proxies bind to port 80 and 443 directly on the host. We wanted to avoid setting the `nodePorts` of the `istio-ingressgateway` service to those ports, which would require changing the `--service-node-port-range` option of the apiserver to allow such lower ports, and we don't want to give all users the ability to use privileged ports for their service `nodePorts`.

What we're seeing is that the Envoy proxy initially binds to port 80 but not port 443:
```
$ kubectl -n istio-system exec -it istio-ingressgateway-6hzmq bash
root@daldevkubework02:/# netstat -nltp | grep envoy
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      22/envoy
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      22/envoy
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      22/envoy
```

Sometime later Envoy gets some sort of LDS update that causes it to stop listening on port 80:
```
$ kubectl -n istio-system logs istio-ingressgateway-6hzmq | grep _80
[2019-01-03 18:26:34.015][23][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_80'
[2019-01-03 21:53:07.468][23][info][upstream] external/envoy/source/server/lds_api.cc:72] lds: remove listener '0.0.0.0_80'
```

Here's the relevant snippet from the `istio-ingressgateway` DaemonSet manifest:
```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    chart: gateways-1.0.4
    release: istio
    heritage: Tiller
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      hostNetwork: true # ADDED
      dnsPolicy: ClusterFirstWithHostNet # ADDED
      serviceAccountName: istio-ingressgateway-service-account
      containers:
        - name: istio-proxy
          image: "docker.io/istio/proxyv2:1.0.4"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 31400
            - containerPort: 15011
            - containerPort: 8060
            - containerPort: 853
            - containerPort: 15030
            - containerPort: 15031
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
```

We also changed the `istio-ingressgateway` service to `ClusterIP` so as not to expose unnecessary `nodePorts`, but changing it back to `nodePort` didn't change the above behavior.

Any tips on how to troubleshoot/debug this would be appreciated.

**Comment by rmb938** [comment]
When deploying as a daemonset it would also be nice to have node affinity.

**Comment by ZackButcher** [comment]
@FierceElements what Gateways do you have defined? You'll need to write a Gateway targeting the `istio: ingressgateway` deployment which configures ports 80 and 443. [The example in the reference docs does this.](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway)

That _should_ work; if not, it's probably a bug where we're wiring up Gateway listeners as virtual rather than physical. (Ingress gets treated specially compared to sidecars; in sidecars we only configure virtual listeners.) Unfortunately I can't test for myself in a cluster just right this second.

**Comment by FierceElements** [comment]
@ZackButcher, thanks for the follow up. We are indeed using Gateways that have `istio: ingressgateway` selectors and also VirtualServices that reference the Gateways. This works fine while the ingressgateway pods are listening on port 80, but ingress stops working when the port 80 listeners are dropped.

I did also verify that I needed to first define a Gateway for port 443 before the ingressgateway pods listen on that port, so the absence of a port 443 listener is no longer a mystery.

Honestly, we've been having a hard time reproducing the dropped listener issue ourselves. We tried for a while without success. We then wanted to get the ingressgateway pods off of the host network and so used `hostPort` for ports 80 and 443 instead. Since making that change we've also not seen the listeners drop out.

**Comment by sujithvs74** [comment]
@FierceElements Could you able to fix hostport for ingress gateway.

**Comment by JonasJasas** [comment]
If I just change Deplyment to DaemonSet using exported manifest getting this error (using Istio 1.8.2):

`Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[istiod-ca-cert gatewaysdsudspath config-volume ingressgateway-certs istio-envoy istio-ingressgateway-service-account-token-xrpb7 istio-token istio-data podinfo ingressgateway-ca-certs]: timed out waiting for the condition`

Please explain how to fix it.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: ingressgateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        release: istio
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - proxy
        - router
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --serviceCluster
        - istio-ingressgateway
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-name']
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-revision']
        - name: ISTIO_META_WORKLOAD_NAME
          value: istio-ingressgateway
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
        - name: ISTIO_META_ROUTER_MODE
          value: standard
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        image: docker.io/istio/proxyv2:1.8.2
        name: istio-proxy
        ports:
        - containerPort: 15021
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 15012
          protocol: TCP
        - containerPort: 15443
          protocol: TCP
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/ingress_gateway
          name: gatewaysdsudspath
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/pod
          name: podinfo
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          readOnly: true
      securityContext:
        fsGroup: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        runAsUser: 1337
      serviceAccountName: istio-ingressgateway-service-account
      volumes:
      - configMap:
          name: istio-ca-root-cert
        name: istiod-ca-cert
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - emptyDir: {}
        name: istio-envoy
      - emptyDir: {}
        name: gatewaysdsudspath
      - emptyDir: {}
        name: istio-data
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          name: istio
          optional: true
        name: config-volume
      - name: ingressgateway-certs
        secret:
          optional: true
          secretName: istio-ingressgateway-certs
      - name: ingressgateway-ca-certs
        secret:
          optional: true
          secretName: istio-ingressgateway-ca-certs
```

**Comment by anthonyvk** [comment]
How to deploy istio ingress as a daemonset using istioctl?

**Comment by JonasJasas** [comment]
@anthonyvk this is my current solution that works well:
`kubectl patch deployment istio-ingressgateway --patch "$(cat gw-patch.yaml)" -n istio-system`

gw-patch.yaml
```
spec:
  replicas: 9
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0

  template:
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              istio: ingressgateway
```

I have tried daemonset but it causes downtimes during restarts. With this patch, you should have 3 replicas for 3 nodes and no downtimes.

**Comment by dvob** [comment]
@anthonyvk You can use:
```
istioctl install -f istiooperator.yaml
```
* `istiooperator.yaml`
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.strategy
          - path: spec.updateStrategy
            value:
              rollingUpdate:
                maxUnavailable: 33%
              type: RollingUpdate
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
            value: 80
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
            value: 443
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:15021].hostPort
            value: 15021
```
