### ISSUE TITLE
Istio RBAC Guide Not Working as Explained

### ISSUE THREAD

**Issue by jon-whit** [istio/istio#6707]
I'm trying to get the RBAC engine working. I'm following the [guide here](https://istio.io/docs/tasks/security/role-based-access-control/).

I've followed the [Before You Begin](https://istio.io/docs/tasks/security/role-based-access-control/#before-you-begin) section and have successfully deployed the Bookinfo application. Here's a snippet of my `kubectl` output from the _istio-poc_ namespace.

```
$ kubectl get services
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
details       ClusterIP   10.X.X.X    <none>        9080/TCP   22h
productpage   ClusterIP   10.X.X.X   <none>        9080/TCP   22h
ratings       ClusterIP   10.X.X.X    <none>        9080/TCP   22h
reviews       ClusterIP   10.X.X.X   <none>        9080/TCP   22h
```

I am able to hit the application through the browser using the Gateway IP and it shows the product reviews as expected.

I followed the [Enabling Istio RBAC](https://istio.io/docs/tasks/security/role-based-access-control/#enabling-istio-rbac) section and have verified using `kubectl get` that the resource configurations are in place, but I am **not** getting Access Denied on the product page as expected. I did modify the `rbac` configuration to match the _istio-poc_ namespace.
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: rbaccheck
  namespace: istio-system
spec:
  actions:
  - handler: handler.rbac
    instances:
    - requestcontext.authorization
  match: destination.namespace == "istio-poc"
```

What is the best way to debug this problem? Any ideas why this would be occurring?
