### ISSUE TITLE
istio 0.8.0 with tls gateway and virtual service not routing traffic to backend, envoy 404

### ISSUE THREAD

**Issue by JohnDzialo** [istio/istio#6733]
**Describe the bug**
I am using istio 0.8.0 on gke 1.9.6.  

I am trying to create a simple gateway with a simple virtual service to route to my sonatype-nexus service on port 8081.  However envoy produces a 404 everytime I make a request despite hosts being set correctly.

Here are my yaml files...

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: secure-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - hosts:
    - nexus.example.com
    port:
        number: 443
        name: https
        protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nexus-route
  namespace: nexus
spec:
  hosts:
  - nexus.example.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nexus-sonatype-nexus
        port:
          number: 8081
```

**Expected behavior**
I would expect the above to work routing traffic hitting the istio ingress gateway with host nexus.example.com should hit the virtualservice and route to the nexus NodePort 8081.

However I receive the following 404 from envoy in the ingress gateway.

```
istio-ingressgateway-6bc7c7c4bc-tj7xc ingressgateway [2018-06-29T15:21:41.632Z] "GET / HTTP/2" 404 - 0 0 2 - "10.142.0.2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "c3ebc938-5ce9-96b4-affe-77ee6c8a2cda" "nexus.example.com" "-"
```

**Steps to reproduce the bug**
deploy nexus helm chart along with the ingress gateway and virtual service and try to resolve the site through gateway.

**Version**
```
➜  Documents istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

➜  Documents kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7f
e92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64
"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de3
6abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"lin
ux/amd64"}
```

**Is Istio Auth enabled or not?**
helm chart 0.8.0 with istio: rbac: true

**Environment**
GCP gke 1.9.6

**Comment by rshriram** [comment]
is 8081 a nodeport or the service port? We don't support routing to nodeports.
Secondly, can you try using a FQDN in the destination.host instead of a short name, to see if it works? the way you have it, the short name host should resolve to nexus-sonatype-nexus.nexus.svc.cluster.local == is this where the service is running?

**Comment by JohnDzialo** [comment]
oh, I was able to solve it.

I did not reference the gateway in the virtual gateway :(.

so envoy was 404'ing because there was no where for the gateway to send the request.

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nexus-route
  namespace: nexus
spec:
  hosts:
  - nexus.example.com
  gateways:
  - secure-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nexus-sonatype-nexus
        port:
          number: 8081
```
