### ISSUE TITLE
TCP proxy broken if >1 service defined

### ISSUE THREAD

**Issue by costinm** [istio/istio#6753]
I have 2 services, on different ports. 
With only one service it works. It seems the problem is we generate multiple TCP proxy entries for each listener.

In gateway:
```
...
  - port:
      number: 5203
      protocol: TCP
      name: tcp-iperf-tls
    hosts:
    - "*"
  - port:
      number: 5202
      protocol: TCP
      name: tcp-iperf3-noistio
    hosts:
    - "*"
  - port:
      number: 5201
      protocol: TCP
      name: tcp-iperf3
    hosts:
    - "*"
```
Each has a virtual service like:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iperf-tls
spec:
  hosts:
  - "iperf-tls.{{ .Values.domain }}"
  gateways:
  - istio-gateway
  tcp:
  - route:
    - destination:
        host: iperf3-tls.test.svc.cluster.local
        port:
          number: 5203
```

Generated code:
```
{
  "name": "0.0.0.0_5201",
  "address": {
    "socketAddress": {
      "address": "0.0.0.0",
      "portValue": 5201
    }
  },
  "filterChains": [
    {
      "filters": [
        {
          "name": "mixer",
          "config": {
              "mixer_attributes": {
                    "attributes": {
                          "context.reporter.local": {
                                "bool_value": false
                              },
                          "context.reporter.uid": {
                                "string_value": "kubernetes://istio-ingressgateway-86f86875c4-5thk8.istio-system"
                              },
                          "source.uid": {
                                "string_value": "kubernetes://istio-ingressgateway-86f86875c4-5thk8.istio-system"
                              }
                        }
                  },
              "transport": {
                    "attributes_for_mixer_proxy": {
                          "attributes": {
                                "source.uid": {
                                      "string_value": "kubernetes://istio-ingressgateway-86f86875c4-5thk8.istio-system"
                                    }
                              }
                        },
                    "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                    "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
                  }
            }
        },
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "cluster": "outbound|5201||iperf3.test.svc.cluster.local",
              "stat_prefix": "outbound|5201||iperf3.test.svc.cluster.local"
            }
        },
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "cluster": "outbound|5203||iperf3-tls.test.svc.cluster.local",
              "stat_prefix": "outbound|5203||iperf3-tls.test.svc.cluster.local"
            }
        }
      ]
    }
  ]
},
```

**Comment by costinm** [comment]
As an update: I changed the config to use 2 gateways:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-iperf-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 5203
      protocol: TCP
      name: tcp-iperf-tls
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iperf-tls
spec:
  hosts:
  - "iperf-tls.{{ .Values.domain }}"
  gateways:
  - istio-iperf-gateway
  tcp:
  - route:
    - destination:
        port:
          number: 5203
```
And a similar one with only port 5201 for the other app.

Now 5201 looks ok - there is a single tcp proxy and is accepted.

However the config for 5203 is still bad:

```
{
  "name": "0.0.0.0_5203",
  "address": {
    "socketAddress": {
      "address": "0.0.0.0",
      "portValue": 5203
    }
  },
  "filterChains": [
    {
      "filters": [
        {
          "name": "mixer",
          "config": {
              "mixer_attributes": {
                    "attributes": {
                          "context.reporter.local": {
                                "bool_value": false
                              },
                          "context.reporter.uid": {
                                "string_value": "kubernetes://istio-ingressgateway-86f86875c4-5thk8.istio-system"
                              },
                          "source.uid": {
                                "string_value": "kubernetes://istio-ingressgateway-86f86875c4-5thk8.istio-system"
                              }
                        }
                  },
              "transport": {
                    "attributes_for_mixer_proxy": {
                          "attributes": {
                                "source.uid": {
                                      "string_value": "kubernetes://istio-ingressgateway-86f86875c4-5thk8.istio-system"
                                    }
                              }
                        },
                    "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                    "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
                  }
            }
        },
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "cluster": "outbound|5201||iperf3.test.svc.cluster.local",
              "stat_prefix": "outbound|5201||iperf3.test.svc.cluster.local"
            }
        }
      ]
    }
  ]
}],
```
