### ISSUE TITLE
Netework issue encountered when using Istio Gateway for supportting gRPC

### ISSUE THREAD

**Issue by xiajidexue** [istio/istio#6769]
**Describe the bug**
I am a new commer to Istio, i am trying to use Istio Gateway for gRPC traffic supports, the command "wget" fails after executing the command "istioctl kube-inject", but it works before the sider car injected.

![image](https://user-images.githubusercontent.com/6821543/42133234-f507e968-7d58-11e8-89b0-01dee11c17a5.png)

Error pod log in the screen shotcut shown as below:
> --2018-07-01 09:40:04--  (try:19)  http://10.48.147.52:8090/BatchingParameters.prototxt
Connecting to 10.48.147.52:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
> --2018-07-01 09:40:14--  (try:20)  http://10.48.147.52:8090/BatchingParameters.prototxt
Connecting to 10.48.147.52:8090... connected.
HTTP request sent, awaiting response... No data received.
Giving up.

**Expected behavior**
Istio Gateway supports gRPC and  the wget command works after the command "istioctl kube-inject" being executed. 

**Steps to reproduce the bug**

The first, create a Istio Gateway and VirtualService by the command "kubectl create -f   tensor-gateway.yaml" with the following yaml file.

```
$ cat tensor-gateway.yaml

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tensorflow-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
     # name: http
      #protocol: HTTP
      protocol: grpc
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tensorflow
spec:
  hosts:
  - "*"
  gateways:
  - tensorflow-gateway
  - mesh #
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: tf-servering
        port:
          number: 9002
          name: grpc
```

The second, use the command "kubectl apply -f <(istioctl kube-inject -f  tensorflow.yaml)" to  manually inject the sidecar by the following file:
```
$ cat tensorflow.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-servering
 # namespace: ingress-nginx
 # namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-servering
  template:
    metadata:
      labels:
        app: tf-servering
    spec:
      containers:
      - name: tf-servering
        # image: registry.corp.kuaishou.com/aiplatform/tensorflowserving:hdfs-base4
        image: 10.62.216.44/library/tensorflowserving:hdfs-base4
        "command": ["/bin/bash","-c","wget -O /tmp/BatchingParameters.prototxt http://10.48.147.52:8090/BatchingParameters.prototxt;tensorflow_model_server --model_base_path=hdfs://default/home/rl/serving/cchess --port=9002 --enable_batching=true --batching_parameters_file=/tmp/BatchingParameters.prototxt"]
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: tf-servering
#  namespace: istio-system
#  namespace: ingress-nginx
spec:
  ports:
  - name: grpc
    port: 9002
   # targetPort: 9002
    targetPort: 9002
    protocol: TCP
   # name: http
    name: grpc
  selector:
    app: tf-servering
```
The injected yaml is shown as below with the command "$ istioctl kube-inject -f  tensorflow.yaml":
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tf-servering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-servering
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: '{"version":"3045b39bbb493dffe0df221b6a7f55a3f2b7f78c5e1569770f556779ece56cce","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
      labels:
        app: tf-servering
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - wget -O /tmp/BatchingParameters.prototxt http://10.48.147.52:8090/BatchingParameters.prototxt;tensorflow_model_server
          --model_base_path=hdfs://default/home/rl/serving/cchess --port=9002 --enable_batching=true
          --batching_parameters_file=/tmp/BatchingParameters.prototxt
        image: 10.62.216.44/library/tensorflowserving:hdfs-base4
        imagePullPolicy: Always
        name: tf-servering
        ports:
        - containerPort: 9002
        resources:
          limits:
            nvidia.com/gpu: "1"
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - tf-servering
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 10s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-statsd-prom-bridge.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        image: registry.corp.kuaishou.com/aiplatform/proxyv2:0.8.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - 9002,
        - -d
        - ""
        image: registry.corp.kuaishou.com/aiplatform/proxy_init:0.8.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tf-servering
#  namespace: istio-system
#  namespace: ingress-nginx
spec:
  ports:
  - name: grpc
    port: 9002
   # targetPort: 9002
    targetPort: 9002
    protocol: TCP
   # name: http
    name: grpc
  selector:
    app: tf-servering
---
```

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

Kubernetes version:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

istio version:
$ istioctl version
```
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean`
```
**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
I instill Istio follow the guide: https://istio.io/docs/setup/kubernetes/quick-start/#download-and-prepare-for-the-installation

installation steps:
```
1. curl -L https://git.io/getLatestIstio | sh -
2. cd istio-0.8.0
3. export PATH=$PWD/bin:$PATH
4. kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment**

```
CentOS Linux release 7.4.1708 (Core)
```
