### ISSUE TITLE
virtualservice for grpc does not get applied for ingressgateway

### ISSUE THREAD

**Issue by zvikaga** [istio/istio#6770]
**Describe the bug**
Could not make virtualservice routing rule applied to ingressgateway for grpc service.
Other regular http exposed services are reachable through the gateway.

**Expected behavior**
virtualservice config for GRPC routing should be successfully configured.

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: orca-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "sharkorca.example.com"
    - "sharkguru.example.com"
    - "sharkregistry.example.com"
    - "sharkloginregistry.example.com"

----------

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-guru
spec:
  hosts:
  - "sharkguru.example.com"
  gateways:
  - orca-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: guru.default.svc.cluster.local

----------

apiVersion: v1
kind: Service
metadata:
  name: guru
  labels:
    app: guru
spec:
  selector:
    app: guru
  ports:
  - port: 80
    targetPort: 6095
    name: grpc
    protocol: TCP
```

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
Enabled

**Environment**
GKE

--- ingressgateway log ---

> [2018-07-01T10:01:56.756Z] "POST /api.Guru/Action HTTP/2" 200 NR 18 0 2 - "10.128.0.3" "grpc-go/1.11.1" "54121f41-c75b-9deb-84ba-ba5ac0fa54e6" "sharkguru.example.com:443" "-"

There is nothing on the service's istio-proxy log, does not seem to get any traffic from ingressgateway.

Thanks

**Comment by xiajidexue** [comment]
Also encountered the problems when using Istio for support the gRPC:
https://github.com/istio/istio/issues/6769

**Comment by ymesika** [comment]
You have mismatch in names between the gateway (`test-gateway`) and the VirtualService (`orca-gateway`).
Do you have other gateway or is it typo?

**Comment by vadimeisenbergibm** [comment]
@zvikaga Additional issue to the one mentioned in https://github.com/istio/istio/issues/6770#issuecomment-401607709, your GRPC service `guru.default.svc.cluster.local` expects GRPC over HTTPS, doesn't it? In such a case your gateway must not perform TLS termination, so the `tls` `mode` must be `PASSHTROUGH`,  without the key/certificate.

**Comment by zvikaga** [comment]
Thanks Yossi, this is of course a typo and not what was actually configured.
In regards to the tls termination, in our current deployment, the ingress terminates the SSL while the end grpc service listens to port 80.

You may look at the following k8s ingress resource config which was working for a long time:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  tls:
    - secretName: istio-ingress-certs
  rules:
  - host: #CERIBRO_URL#
    http:
      paths:
      - path: /.*
        backend:
          serviceName: ceribro
          servicePort: 80
  - host: #GURU_URL#
    http:
      paths:
      - backend:
          serviceName: guru
          servicePort: grpc
```
The ingress terminated TLS also for the grpc service. I'm looking for the equivalence in the gateway/virtualservice world.

What I understand from the logs (200 NR) is that the route does not get installed in the ingress envoy, so it has no knowledge how to route the incoming request to the upstream service.

**Comment by vadimeisenbergibm** [comment]
OK, I see, so the TLS termination is correct. Let me check the routes.

**Comment by zvikaga** [comment]
Thanks!! this is exactly what we've seen. The GRPC client requires to add the port to the hostname in the URL. That can be seen in the ingressgateway's logs.
Workaround was to you use "*" in the host field of both gateway and the virtualservice of the GRPC service. This of course requires the prefix match to be different.

**Comment by xiajidexue** [comment]
@zvikaga , I am also investigating Istio gateway for supporting  gRPC, can you help to paste all your whole yamls which can be successfully run for our reference? or just send me via the mail: 1214682008@qq.com. 

Your quick response will be much appreciated :)

**Comment by zvikaga** [comment]
The below config works for me.

- Please pay attention to the order of the virtualservice entries. the more general should be the last. The rule is: within the MATCH it's AND, between matches it's OR.

- According to the above bug, I use "*" for the host field. So we'll have to make the prefixes different.

```
*** gateway ***

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: orca-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true # sends 302 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"

*** virtualservice ***

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-all
spec:
  hosts:
  - "*"
  gateways:
  - orca-gateway
  http:
  - match:
    - uri:
        prefix: /api.Guru/
    route:
    - destination:
        port:
          number: 80
        host: guru.default.svc.cluster.local
  - match:
    - uri:
        prefix: /v2/generic-bank-retail/
    route:
    - destination:
        port:
          number: 80
        host: registry.default.svc.cluster.local
  - match:
    - uri:
        prefix: /v2/token
    route:
    - destination:
        port:
          number: 80
        host: portus.default.svc.cluster.local
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: ceribro.default.svc.cluster.local

*** service ***

apiVersion: v1
kind: Service
metadata:
  name: guru
  labels:
    app: guru
spec:
  selector:
    app: guru
  ports:
  - port: 80
    targetPort: 6095
    name: grpc
    protocol: TCP
  type: ClusterIP 
```
