### ISSUE TITLE
Web/Graphical UI can't generate the chart when the fortio deploy on the istio with sidecar

### ISSUE THREAD

**Issue by zxDiscovery** [istio/istio#6777]
**Describe the bug**
I test the istio performance according to the **Istio Load Testing User Guide** ([https://github.com/istio/istio/tree/master/tools#istio-load-testing-user-guide](url))
The case is S1 to S2 (istio service 1 to istio service 2 through the sidecar).
fortio parameter as follows:
QPS (-1), Duration (30s), Threads/Simultaneous connections: 48
Then the fortio doesn't graph the results on Web/Graphical UI.

**Expected behavior**
Fortio is used to perform load testing, graphing results and as a backend echo server.

**Steps to reproduce the bug**
1. Build the work environment deploy istio and forito on the IBMPrivateCloud. Step as follows:
[https://github.ibm.com/IBMPrivateCloud/roadmap/issues/10803](url)
2. Run test case s1 to s2 (run_fortio_test_istio_s1_to_s2)
Open the web UI http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio1/fortio/
fortio parameter as follows:
QPS (-1), Duration (30s), Threads/Simultaneous connections: 48
3. Click the start button

**Version**
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
fortio v1.0.0  

**Is Istio Auth enabled or not?**
not enabled

**Environment**
Which environment, cloud vendor, OS, etc are you using?
OS:  ubuntu
Cloud:  IBMPrivateCloud

**Comment by ThanosAndLichKing** [comment]
Step 1 link content 

**setup VM**

 1. Prepare VM and git & golang env…
 2. update_fortio_on_vm

```
go get istio.io/fortio && cd go/src/istio.io/fortio && git fetch --tags && git checkout latest_release && make submodule-sync && go build -o ~/go/bin/fortio -ldflags "-X istio.io/fortio/version.tag=$(git describe --tag --match v\*) -X istio.io/fortio/version.buildInfo=$(git rev-parse HEAD)" . && sudo setcap 'cap_net_bind_service=+ep' `which fortio` && fortio version
```

3. run_fortio_on_vm
```
pkill fortio; nohup fortio server -http-port 443 > ~/fortio.log 2>&1 &
```
**setup cluster**

1. install_non_istio_svc
```
export FORTIO_NAMESPACE=fortio
kubectl create namespace $FORTIO_NAMESPACE

kubectl -n $FORTIO_NAMESPACE run fortio1 --image=istio/fortio:1.0.0 --port=8080
kubectl -n $FORTIO_NAMESPACE expose deployment fortio1 --target-port=8080
kubectl -n $FORTIO_NAMESPACE run fortio2 --image=istio/fortio:1.0.0 --port=8080
kubectl -n $FORTIO_NAMESPACE expose deployment fortio2 --target-port=8080

cat <<_EOF_ | kubectl apply -n fortio -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortio-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /fortio
spec:
  rules:
  - host: fortio.example.com
    http:
      paths:
       - path: /fortio1/fortio
         backend:
           serviceName: fortio1
           servicePort: 8080
       - path: /fortio2/fortio
         backend:
           serviceName: fortio2
           servicePort: 8080
_EOF_

curl http://fortio.example.com/fortio1/fortio/ --insecure
curl http://fortio.example.com/fortio2/fortio/ --insecure
```
Note: Get ingress loader balancer IP and add DNS record to /ets/hostsby
```
K8S_INGRESS_IP=$(kubectl -n $FORTIO_NAMESPACE get ingress -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
echo "$K8S_INGRESS_IP fortio.example.com" >> /etc/hosts
```
2. Install Istio(helm chart)
```
git clone git@github.ibm.com:IBMPrivateCloud/istio-chart.git && cd istio-chart
export ISTIO_SYSTEM_NAMESPACE=istio-system
kubectl create ns $ISTIO_SYSTEM_NAMESPACE
helm install ./ibm-istio --name istio --namespace $ISTIO_SYSTEM_NAMESPACE -f ./ibm-istio/cv-tests/test-default/values.yaml --tls
```
3. install_istio_svc
```
export ISTIO_NAMESPACE=istio
kubectl create ns $ISTIO_NAMESPACE
curl -LO https://raw.githubusercontent.com/istio/istio/release-0.8/tools/perf_k8svcs.yaml

cat <<_EOF_ | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-for-istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:istio
_EOF_

kubectl -n $ISTIO_NAMESPACE apply -f <(istioctl kube-inject -n $ISTIO_NAMESPACE -f ./perf_k8svcs.yaml)

cat <<_EOF_ | kubectl apply -n $ISTIO_NAMESPACE -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fortio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fortio
spec:
  hosts:
  - "*"
  gateways:
  - fortio-gateway
  http:
  - match:
    - uri:
        prefix: /fortio1/
    route:
    - destination:
        host: echosrv1.istio.svc.cluster.local
        port:
          number: 8080
    rewrite:
      uri: / # drop the /fortio1 prefix when talking to fortio such as /fortio1/fortio -> /fortio
  - match:
    - uri:
        prefix: /fortio2/
    route:
    - destination:
        host: echosrv2.istio.svc.cluster.local
        port:
          number: 8080
    rewrite:
      uri: / # drop the /fortio2 prefix when talking to fortio such as /fortio2/fortio -> /fortio
_EOF_
```

**Get IP**

1. get_vm_ip
```
VM_IP=<your_vm_ip>
VM_URL="http://$VM_IP:443/fortio/"

echo "+++ VM Ip is $VM_IP - visit (http on port 443 is not a typo:) $VM_URL"
```
2. get_fortio_k8s_ip
```
K8S_INGRESS_IP=$(kubectl -n $FORTIO_NAMESPACE get ingress -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')

echo "+++ In k8s non istio ingress for fortio1: http://$K8S_INGRESS_IP/fortio1/fortio/"
echo "+++ In k8s non istio ingress for fortio1: http://$K8S_INGRESS_IP/fortio2/fortio/"
```
3. get_istio_ingressgateway_address
```
ISTIO_INGRESSGATEWAY_IP=$(kubectl get po -l istio=ingressgateway -n istio-system -o 'jsonpath={.items[0].status.hostIP}')
ISTIO_INGRESSGATEWAY_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}')

echo "+++ In k8s istio ingress: http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio1/fortio/"
echo "+++ In k8s istio ingress: http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio2/fortio/"
```
**run_4_tests**

1. run_fortio_test_istio_ingress1
```
echo "istio ingressgateway to fortio1"

LABELS="ingressgateway to fortio1"
QPS=400
DUR=30s
FNAME=igw_f1

curl -s "$VM_URL?labels=$LABELS\&json=on\&save=on\&qps=$QPS\&t=$DUR\&c=48\&load=Start\&url=http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio1/echo" | tee $FNAME.json | grep ActualQPS
```
2. run_fortio_test_istio_ingress2
```
echo "istio ingressgateway to fortio2"
LABELS="ingressgateway to fortio2"
QPS=400
DUR=30s
FNAME=igw_f2

curl -s "$VM_URL?labels=$LABELS\&json=on\&save=on\&qps=$QPS\&t=$DUR\&c=48\&load=Start\&url=http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio2/echo" | tee $FNAME.json | grep ActualQPS
```
3. run_fortio_test_istio_s1_to_s2
```
echo "s1 to s2"
LABELS="s1 to s2"
QPS=400
DUR=30s
FNAME=s1_s2

curl -s "http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio1/fortio/?labels=$LABELS\&json=on\&save=on\&qps=$QPS\&t=$DUR\&c=48\&load=Start\&url=http://echosrv2:8080/echo" | tee $FNAME.json | grep ActualQPS
```
4. run_fortio_test_istio_s2_to_s1
```
echo "s2 to s1"
LABELS="s2 to s1"
QPS=400
DUR=30s
FNAME=s2_s1

curl -s "http://$ISTIO_INGRESSGATEWAY_IP:$ISTIO_INGRESSGATEWAY_PORT/fortio2/fortio/?labels=$LABELS\&json=on\&save=on\&qps=$QPS\&t=$DUR\&c=48\&load=Start\&url=http://echosrv1:8080/echo" | tee $FNAME.json | grep ActualQPS
```
