### ISSUE TITLE
Host without domainsuffix in virtualservice can not be accessed through ingressgateway

### ISSUE THREAD

**Issue by rokii** [istio/istio#6778]
**Describe the bug**
When adding a route in virtualservice , providing the host with format <svc name>.<ns>,  the app can not be accessed through ingressgateway.

**Expected behavior**
Virtualservice appgateway is  created in ns bookinfo. In vs appgateway, there is a route destination to a svc in ns istiosample(host : sampleapp.istiosample),  the sampapp can be access through ingress gateway.

**Steps to reproduce the bug**
1. install bookinfo sample in ns bookinfo
2. install your own sampleapp in ns other than bookinfo
3. istioct create below file in bookinfo ns
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: appgateway
  namespace: bookinfo
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        prefix: /sampleapp
    route:
    - destination:
        host: sampleapp.istiosample
        port:
          number: 9080

```

From the  ingress gateway config_dump, you can find out that the sampleapp cluster is not defined with domain suffix.

```
 "configs": {
  "routes": {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.RoutesConfigDump",
   "staticRouteConfigs": [
    {
     "name": "80",
     "virtualHosts": [
      {
       "name": "appgateway:80",
       "domains": [
        "*"
       ],
       "routes": [
        {
         "match": {
          "path": "/productpage"
         },
         "route": {
          "cluster": "outbound|9080||productpage.bookinfo.svc.cluster.local",
          "useWebsocket": false
         },
         "decorator": {
/sampleapp
...skipping
          "prefix": "/sampleapp"
         },
         "route": {
          "cluster": "outbound|9080||sampleapp.istiosample",
          "useWebsocket": false
         },
         "decorator": {
          "operation": "appgateway"
         }
        }
       ]
      }
     ],
     "validateClusters": false
    }
   ]
  },

```

**Version**
istio 0.8, k8s 1.9.7

**Is Istio Auth enabled or not?**
enabled

**Environment**
self maintained k8s
