### ISSUE TITLE
EnvoyV2 forwards HTTP requests improperly to the upstream server

### ISSUE THREAD

**Issue by zvikaga** [istio/istio#6782]
**Describe the bug**
Puma server, the front end on few of our services supports only HTTP 1.1.
ingress gateway manipulates the request in such a way it gets malformed to the upstream service.
We don't have this behavior in another http service we use.
Also we don't have this issue on Istio 0.7.1

**Expected behavior**
The HTTP 1.1 request should be served properly by the PUMA HTTP server.

**Steps to reproduce the bug**
Calling the exposed http service using standard port HTTPS:

```
curl https://sharkloginregistry.example.com/v2/token/ -v
*   Trying 35.224.34.112...
* TCP_NODELAY set
* Connected to sharkloginregistry.example.com (35.224.34.112) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.example.com
*  start date: Feb 13 08:45:35 2018 GMT
*  expire date: Feb 14 08:45:35 2019 GMT
*  subjectAltName: host "sharkloginregistry.example.com" matched cert's "*.example.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
> GET /v2/token/ HTTP/1.1
> Host: sharkloginregistry.example.com
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Mon, 02 Jul 2018 13:53:56 GMT
< server: envoy
< 
* Connection #0 to host sharkloginregistry.example.com left intact
upstream connect error or disconnect/reset before header
```
*** ingressgateway log ***

> [2018-07-02T13:53:56.471Z] "GET /v2/token/ HTTP/1.1" 503 UF 0 57 6 - "10.128.0.4" "curl/7.55.1" "ea6eee40-5f36-91f1-a220-d74cdb913640" "sharkloginregistry.example.com" "10.4.2.15:3000"

The ingress gateway terminates the TLS and  forwards the request to the upstream service using port 80.

*** Upstream http server logs ***

> 2018-07-02 12:05:22 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>

*** ingressgateway config ***
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: orca-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true # sends 302 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
```

*** virtualservice config ***

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-all
spec:
  hosts:
  - "*"
  gateways:
  - orca-gateway
  http:
  - match:
    - uri:
        prefix: /api.Guru/
    route:
    - destination:
        port:
          number: 80
        host: guru.default.svc.cluster.local
  - match:
    - uri:
        prefix: /v2/generic-bank-retail/
    route:
    - destination:
        port:
          number: 80
        host: registry.default.svc.cluster.local
  - match:
    - uri:
        prefix: /v2/token
    route:
    - destination:
        port:
          number: 80
        host: portus.default.svc.cluster.local
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: ceribro.default.svc.cluster.local

```  
*** upstream service config ***

```
apiVersion: v1
kind: Service
metadata:
  name: portus
  namespace: default
  labels:
    app: portus
spec:
  selector:
    app: portus
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP

```
**Version**
8.0
envoy V2

**Is Istio Auth enabled or not?**
Yes

**Environment**
GKE
