### ISSUE TITLE
Istio 0.8 TLS: Per-service Client Certificate

### ISSUE THREAD

**Issue by arianmotamedi** [istio/istio#6786]
Reading through https://istio.io/docs/reference/config/istio.networking.v1alpha3, looks like you can use your own client certificates when a request is being routed to an upstream server through a DestinationRule:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-mongocluster
spec:
  host: mymongodb.somedomain
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
```

My understanding is in this case all requests going to `mymongodb.somedomain` will use this cert. In our use case we need to be able to have each downstream service pass its own client certificate (so for example `Service A` calling `Service C` passes `a.pem` and `Service B` calling `Service C` passes `b.pem`). It doesn't look like you can define client certs at the `VirtualService` level of the calling service, so I'm wondering if I'm missing something obvious or if this is not currently supported. This is achievable in Envoy:

```
  clusters:
  - name: my-service
    connect_timeout: 0.25s
    type: STATIC
    hosts: [{ socket_address: { address: 10.224.101.70, port_value: 443 }},{ socket_address: { address: 10.224.100.123, port_value: 443 }}]
    tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { filename: /certs/client.pem }
          private_key: { filename: /certs/client.key }
```

**Comment by quanjielin** [comment]
My understanding is DestinationRule.host is service name rather than 'server' (see definition [here](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L111)), and [more examples](https://istio.io/docs/tasks/security/authn-policy/#enable-mutual-tls-for-all-services-in-a-namespace); So probably using two DestinationRules works for your scenario ? Let's know if it doesn't work, thanks.

**Comment by arianmotamedi** [comment]
@quanjielin 

> So probably using two DestinationRules works for your scenario

But how would I distinguish them based on sources? In this case, I'd need to have two destination rules, one for Service A (to load A's client cert) and one for Service B (to load B's client cert) but how would I tell the rule to match on a source? Seems like you can do it at the virtual service level using label selectors (https://istio.io/docs/concepts/traffic-management/rules-configuration/#qualify-rules-by-source-headers) but not for destination rules.

**Comment by quanjielin** [comment]
sourceLabels sounds like a solution to match the source; also VirtualService can be associated with DestinationRules using subset, which is a collection of labels; [example](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.pb.go#L19) and [subset in DestinationRules](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L119).

**Comment by arianmotamedi** [comment]
But a host name can appear only once in a VirtualService, so I can't define multiple VSs with different sourceLabels. This all just doesn't sound right.

**Comment by quanjielin** [comment]
One VS contains multiple [HTTPRoute](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.pb.go#L120), each route could specify source labels and [destination](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L305)(Host + subset)

**Comment by arianmotamedi** [comment]
that's not very maintainable if we want to have each service owner be responsible for their own VirtualService deployment if we're using one vs with multiple routes to multiple destinations :( I'm really hoping there's another solution here, especially considering how easy this is to setup in Envoy.

**Comment by quanjielin** [comment]
Thanks for the feedback, I agree current solution is a bit complicated; hopefully we could improve user experience based on more customer feedback after 1.0 release.

btw, could you point me to how envoy setup looks like for the scenario you mentioned ? that would be helpful for us to redesign user interface in the future, thanks.

**Comment by arianmotamedi** [comment]
I posted the envoy cluster spec for one of our services above in my first post. so the idea here is that calls to `my-service` will load `/certs/client.pem` before sending the request to the upstream cluster, and so each caller will have its own `client.pem` file specific to itself. So maybe I'm confused about how Istio does this and what I'm looking for is in fact supported. From https://istio.io/docs/reference/config/istio.networking.v1alpha3/, we have 

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-mongocluster
spec:
  host: mymongodb.somedomain
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
```

in this case, is `/etc/certs/myclientcert.pem` referring to a file that exists in the **calling service**'s container or does it exist on the upstream service's container (i.e. mymongodb.somedomain)? So in other words if `foo` is calling `mymongodb.somedomain`, is that pem file loaded from `foo`'s container? If so that will be the behavior I'm looking for :)

**Comment by quanjielin** [comment]
DestinationRule is for client side setting(in your example cert should be loaded from foo's container); btw for mTLS, [authN policy](https://istio.io/docs/tasks/security/authn-policy/#enable-mutual-tls-for-all-services-in-a-namespace) is also needed which is for server side setting(right now authN policy only support cert/key generated by Istio).

**Comment by arianmotamedi** [comment]
Thanks @quanjielin. I tried enabling mtls using that link you provided:

```
cat <<EOF | istioctl create -f -
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "mtls-policy"
  namespace: "istio-test"
spec:
  peers:
  - mtls:
EOF
```

It succeeded with `Created config policy/istio-test/mtls-policy at revision 3973093`, and then added a destination rule:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-app-dr
  namespace: istio-test
spec:
  host: my-app
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/client.pem
      privateKey: /etc/certs/client.key.pem
      caCertificates: /etc/certs/client.chain.pem
```

but now all calls to `my-app` return `upstream connect error or disconnect/reset before headers`. Is there anyway I can get envoy logs to see why this is happening?
