### ISSUE TITLE
Mixer adapter HandleAuthorization() called twice in 1.0.0-snapshot.0

### ISSUE THREAD

**Issue by theganyo** [istio/istio#6804]
After upgrading my Mixer and adapter from 0.8 to 1.0.0-snapshot.0, I'm seeing the adapter's HandleAuthorization() function being called twice per request instead of once as expected.

**Comment by kyessenov** [comment]
Can you please elaborate on what attributes you are seeing? Is it happening
for a single sidecar?

**Comment by douglas-reid** [comment]
@theganyo can you share a dump of your rules?  is it possible we have multiple rules configured for the handler?

**Comment by douglas-reid** [comment]
It also looks like the handler is run with two different contexts (differing sets of attributes).

**Comment by theganyo** [comment]
```kubectl get rules --all-namespaces
NAMESPACE      NAME                     AGE
istio-system   apigee-rule              2h
istio-system   kubeattrgenrulerule      2h
istio-system   promhttp                 2h
istio-system   promtcp                  2h
istio-system   stdio                    2h
istio-system   tcpkubeattrgenrulerule   2h```
```

BTW: My apigee-rule is simply:

```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: apigee-rule
  namespace: istio-system
spec:
  match: destination.namespace == "default"
  actions:
  - handler: apigee-handler.apigee
    instances:
    - apigee.authorization
    - apigee.analytics
```
