### ISSUE TITLE
ServiceEntry.Resolution not applied for outbound traffic

### ISSUE THREAD

**Issue by crowfrog** [istio/istio#6811]
**Describe the bug**
I create a ServiceEntry for a non-existent external service called foo.bar.com backed by one ip address "150.132.165.169". And set resolution to STATIC.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
  - foo.bar.com
  #addresses:
  #- 150.132.165.169
  location: MESH_EXTERNAL
  ports:
  - number: 31490
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 150.132.165.169
    ports:
      http: 31490
```

But when I run cmd "curl -i http://foo.bar.com:31490", I still got following issue:
"curl: (6) Could not resolve host: foo.bar.com; Name or service not known"

**Expected behavior**
curl should get successful response from 150.132.165.169

**Steps to reproduce the bug**
see above

**Version**
Minikube 0.25.0

$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
Not

**Environment**
NA
