### ISSUE TITLE
1.0.0-snapshot.0 HTTPS requests fail with SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by markns** [istio/istio#6857]
**Describe the bug**
Using 1.10.4-gke.2 and Istio 1.0.0-snapshot.0, HTTPS requests via Ingress gateway fail with `curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

**Expected behavior**
HTTPS requests should succeed

**Steps to reproduce the bug**

- Create new 1.10.4-gke.2 cluster
- kc create namespace istio-system
- helm template --name istio install/kubernetes/helm/istio --namespace istio-system \
               --set global.tag=1.0.0-snapshot.0 > istio.yaml
- kc create -f istio.yaml
- Create istio-ingressgateway-certs and restart ingress-gateway
- Apply httpbin.yaml: 
```
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    name: httpbin
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*.foobar.xyz'
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - '*.foobar.xyz'
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  hosts:
  - httpbin.foobar.xyz
  gateways:
  - gateway.httpbin.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin.httpbin.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin
        ports:
        - containerPort: 80
```

http cURLs succeed, https fails:

```
$ curl -kI http://httpbin.foobar.xyz/headers
HTTP/1.1 200 OK

$ curl -kI https://httpbin.foobar.xyz/headers
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Version**
Istio 1.0.0-snapshot.0
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.0", GitCommit:"f4c74e18e57148052c59cc0467bb7e99dcc46399", GitTreeState:"clean", BuildDate:"2018-06-21T14:11:26Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
```
helm template --name istio install/kubernetes/helm/istio --namespace istio-system \
               --set global.tag=1.0.0-snapshot.0
```

**Environment**
1.10.4-gke.2
