### ISSUE TITLE
DOC: istio FAQ

### ISSUE THREAD

**Issue by linsun** [istio/istio#686]
Please add FAQs we should be documenting in this issue.  thanks.
https://github.com/istio/istio.github.io/blob/master/troubleshooting/index.md

**Comment by ldemailly** [comment]
Rbac install error:
```
Error from server (Forbidden): error when creating "istio-rbac-beta.yaml": clusterroles.rbac.authorization.k8s.io "istio-pilot" is forbidden: attempt to grant extra privileges:
```
fix
```
kubectl create clusterrolebinding my-admin-access --clusterrole cluster-admin --user ldemailly@google.com
```

**Comment by linsun** [comment]
Auth FAQ:  we don't support headless service with auth.   if you use headless service, you need to disable auth.  
we don't support service enable/disable auth on a service level.

if you use k8s health check, you need to disable auth.

**Comment by linsun** [comment]
I hit an issue when put this app working with istio today:  https://github.com/IBM-Bluemix/investment-insights-for-asset-managers

The web page didn't load (it only has title and blank page but source is correct).  I can access the service via node port fine.
My ingress had configuration like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: investment-insights-gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: investment-insights-ux
          servicePort: 6001
```

It turned out i need to configure path with `- path: /.*` so that the .css and .js from the container can be loaded properly via istio ingress.

https://istio.io/docs/tasks/ingress.html#configuring-ingress-http
