### ISSUE TITLE
Timeouts works in beetween 3 components, but not when chaines

### ISSUE THREAD

**Issue by KresoDenis** [istio/istio#6860]
**Describe the bug**
INGRESS > PUBLICSERVICE  (Timeout 60 works)
PUBLICSERVICE > BACKENDSERVICE (Timeout 60 works)
but
INGRESS > PUBLICSERVICE > BACKENDSERVICE (i get timeout after default 15seconds)

**Expected behavior**
i expect the timeout to be set for 60s throught all flow. Testing timeouts inbetwen each other works

**Steps to reproduce the bug**
contact the backend via publicapi with delay of (sleep 30seconds in backend code)
 curl -H 'Accept:application/json' -w "%{http_code}\n" https://api.publicservice.com/backend

**Version**
istio 0.8.0
kubernetes 1.10.4

**Is Istio Auth enabled or not?**
auth disabled

**Environment**
azure, local vagrant

**Comment by KresoDenis** [comment]
One additional information. If i lower the timeout to 1s on gateway>public or public>backend it works. It will timeout after 1 second. So rule actually works.

It looks like the is additional envoy inbetween them with default timeout

INGRESS > PUBLICSERVICE  > SOME ENVOY  WITH 15s DEFAULT > BACKENDSERVICE

I have destination rules and virtualservices for publicapi (w gateway) and backend.

**Comment by rshriram** [comment]
configs will help

**Comment by KresoDenis** [comment]
public
`apiVersion: v1
kind: Service
metadata:
  name: publicapp
  labels:
    app: publicapp
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: publicapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: publicapp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: publicapp
        version: v1
    spec:
      containers:
      - name: publicapp
        command: ["python", "-u", "/public.py"]
        image: python:3.7-stretch
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: publiccode
            mountPath: "/public.py"
            subPath: "public.py"     
      volumes:
        - name: publiccode
          configMap:
            name: publiccode           
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: publicapp
spec:
  hosts:
  - publicapp
  http:
  - route:
    - destination:
        host: publicapp
        subset: v1
    timeout: 60s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: publicapp
spec:
  host: publicapp
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: publiccode
data:
  public.py: |
    #!/usr/bin/env python

    from http.server import BaseHTTPRequestHandler, HTTPServer
    from time import sleep
    import urllib.request

    PORT = 3000
    SLEEP_TIME = 0

    class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):

      def do_GET(self):
            sleep(SLEEP_TIME)
            contents = urllib.request.urlopen("http://backend:4000").read()
            
            self.send_response(200)

            self.send_header('Content-type','text/html')
            self.end_headers()
            message = str(contents)

            self.wfile.write(bytes(message, "utf8"))
            return

    def run():
      print('starting server...')
      server_address = ('0.0.0.0', PORT)
      httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
      print('running server...')
      httpd.serve_forever()

    run()`

backend
`apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        command: ["python", "-u", "/backend.py"]
        image: python:3.7-stretch
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: backendcode
            mountPath: "/backend.py"
            subPath: "backend.py"     
      volumes:
        - name: backendcode
          configMap:
            name: backendcode     
            
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend
        subset: v1
    timeout: 60s   
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
spec:
  host: backend
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backendcode
data:
  backend.py: |
    #!/usr/bin/env python

    from http.server import BaseHTTPRequestHandler, HTTPServer
    from time import sleep

    PORT = 4000
    SLEEP_TIME = 22

    class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):

      def do_GET(self):
            sleep(SLEEP_TIME)

            self.send_response(200)            
            self.send_header('Content-type','text/html')
            self.end_headers()

            message = "backend-response"
            self.wfile.write(bytes(message, "utf8"))
            return

    def run():
      print('starting server...')
      server_address = ('0.0.0.0', PORT)
      httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
      print('running server...')
      httpd.serve_forever()

    run()`

gateway
`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-80
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myservice
spec:
  hosts:
  - "*"
  gateways:
  - default-80
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: publicapp
        port:
          number: 3000
    timeout: 60s`

**Comment by KresoDenis** [comment]
Dont want to put my code here. So i recreaded issue based on bookinfo example with 3 components.
Public and backend.

backend has sleep 22 seconds and all timeouts on 60s. But it will still timeout after 15 seconds.
If you lower sleep to lets say 10 seconds it will work

Also timeout rules work because if you lower timeout to 1s on "myservice" or "backend" virtualservice. Curl will timeout after 1 second.


PUBLIC
```
apiVersion: v1
kind: Service
metadata:
  name: publicapp
  labels:
    app: publicapp
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: publicapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: publicapp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: publicapp
        version: v1
    spec:
      containers:
      - name: publicapp
        command: ["python", "-u", "/public.py"]
        image: python:3.7-stretch
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: publiccode
            mountPath: "/public.py"
            subPath: "public.py"     
      volumes:
        - name: publiccode
          configMap:
            name: publiccode           
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: publicapp
spec:
  hosts:
  - publicapp
  http:
  - route:
    - destination:
        host: publicapp
        subset: v1
    timeout: 60s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: publicapp
spec:
  host: publicapp
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: publiccode
data:
  public.py: |
    #!/usr/bin/env python

    from http.server import BaseHTTPRequestHandler, HTTPServer
    from time import sleep
    import urllib.request

    PORT = 3000
    SLEEP_TIME = 0

    class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):

      def do_GET(self):
            sleep(SLEEP_TIME)
            contents = urllib.request.urlopen("http://backend:4000").read()
            
            self.send_response(200)

            self.send_header('Content-type','text/html')
            self.end_headers()
            message = str(contents)

            self.wfile.write(bytes(message, "utf8"))
            return

    def run():
      print('starting server...')
      server_address = ('0.0.0.0', PORT)
      httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
      print('running server...')
      httpd.serve_forever()

    run()
```

BACKEND
```
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        command: ["python", "-u", "/backend.py"]
        image: python:3.7-stretch
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: backendcode
            mountPath: "/backend.py"
            subPath: "backend.py"     
      volumes:
        - name: backendcode
          configMap:
            name: backendcode     
            
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend
        subset: v1
    timeout: 60s   
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
spec:
  host: backend
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backendcode
data:
  backend.py: |
    #!/usr/bin/env python

    from http.server import BaseHTTPRequestHandler, HTTPServer
    from time import sleep

    PORT = 4000
    SLEEP_TIME = 22

    class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):

      def do_GET(self):
            sleep(SLEEP_TIME)

            self.send_response(200)            
            self.send_header('Content-type','text/html')
            self.end_headers()

            message = "backend-response"
            self.wfile.write(bytes(message, "utf8"))
            return

    def run():
      print('starting server...')
      server_address = ('0.0.0.0', PORT)
      httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
      print('running server...')
      httpd.serve_forever()

    run()
```

GATEWAY
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-80
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myservice
spec:
  hosts:
  - "*"
  gateways:
  - default-80
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: publicapp
        port:
          number: 3000
    timeout: 60s
```

**Comment by KresoDenis** [comment]
We have some rare request that sometimes lasts just about 15-20s and it causing us big problems.

I have tried a lot of thigs with different hosts. It looks like there is additional envoy in the chain of forwarding packets with default of 15s. Could it be istio-ingress node or am i just not understanding configs.

**Comment by rshriram** [comment]
Its definitely some envoy in middle not respecting the timeout due to conflicts with other flags envloy sets (x-envoy-upstream-request-timeout etc). Either that or we forgot to set this in some intermediary envoy. Debugging

**Comment by KresoDenis** [comment]
i have additional information. The name of this issue is a bit misleading.

Because acctually even if i curl backend from publicapi it wont work.
```curl -v -w "%{http_code}\n" http://backend:4000```

Interestingly. I could make the curl if i put SLEEP to 0 on backend and add fault injection to backend service
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend
        subset: v1
    timeout: 60s   
    fault:
      delay:
        percent: 100
        fixedDelay: 20s   
```

So it works if i inject the delay from tutorial. But it wont work if there is actual delay.

**Comment by KresoDenis** [comment]
Here is some interesting math that can point you in right direction:
If i put 
SLEEP=999 (seconds on backend)
timeout: 60s (on backend virtual service)
fixedDelay: 20s (on backend virtual service)

curl -v -w "%{http_code}\n" http://backend:4000
will actually timeout on 35seconds. Weird.

And if i put 10 seconds lower on fixed delay.
SLEEP=999 (seconds on backend)
timeout: 60s (on backend service)
fixedDelay: 10s (on backend service)

curl will fail after 25 seconds.

So it looks like actual so it looks like actual timeout is (default 15s + fixedDelay)

Not sure if this is relevant.

**Comment by KresoDenis** [comment]
i renamed the issue since on initial bug describe i said timeout between components work. But actually only when using fault delay injection. When using real delay (in app sleep) it doesnt work.

**Comment by KresoDenis** [comment]
I have also created new feature request that could also potentially solve my problems by passing default timeout to all envoys. And having same timeouts for my all istio apps.
https://github.com/istio/istio/issues/6861

**Comment by frankbu** [comment]
The fact that the actual delay is "timeout + fixedDelay" is correct, because when you make the call, envoy will wait for the fixedDelay and then call the backend, which will timeout in 15s by default. If I understand correctly, the only problem is that when you set a timeout >15s it uses 15s. Lower timeout values <15s work as expected. Is that still what you are seeing?

**Comment by frankbu** [comment]
btw, do you realize that this VS:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: publicapp
spec:
  hosts:
  - publicapp
  http:
  - route:
    - destination:
        host: publicapp
        subset: v1
    timeout: 60s
```
is not used in your example, because you are accessing the service via the gateway?

If you want to use subset v1 when calling through the gateway, you need to add the subset in the other VS:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myservice
spec:
  hosts:
  - "*"
  gateways:
  - default-80
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: publicapp
        port:
          number: 3000
        subset: v1
    timeout: 60s
```
