### ISSUE TITLE
Mixer report fails on TCP traffic with lookup failing on response.time

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#6875]
**Describe the bug**
When using a TCP service in Istio, the following error appears in the logs:

```
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNKNOWN:1 error occurred:%0A%0A* evaluation failed at [accesslog.logentry.istio-system]'Variables[responseTimestamp]': 'lookup failed: 'response.time''
```

**Expected behavior**
No error should appear in the logs, an stdio log message should appear instead.

**Steps to reproduce the bug**

1.
```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  name: httpbin-tcp
  labels:
    app: httpbin
spec:
  ports:
  - name: tcp
    port: 8000
  selector:
    app: httpbin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8000
EOF

```

2. Use a $SOURCE_POD to send curl requests.

```
kubectl exec -it $SOURCE_POD -c sleep -- curl httpbin-tcp:8000/headers
```

3. Check the logs:

```
kubectl logs $SOURCE_POD istio-proxy
```

**Version**
Istio: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-20180705-09-15/

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:11:08Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.8-2+af27ab4b096122", GitCommit:"af27ab4b096122049e65b75ee29ac115b1d58f6b", GitTreeState:"clean", BuildDate:"2018-06-14T04:07:19Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
No

**Environment**
Kubernetes on IBM Cloud Container Service.
