### ISSUE TITLE
filterChainMatch not set on a gateway with `*` hosts and a TLS virtual service with `sni_domains`.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#6876]
**Describe the bug**
filterChainMatch not set on a gateway with `*` hosts and a TLS virtual service with `sni_domains`.

**Expected behavior**
If I define a gateway with hosts "*", and two TLS rules, one with sni_domains "www.google.com" and another one with sni_domains "edition.cnn.com", I expected two corresponding filterChains be configured.

**Steps to reproduce the bug**
Follow the steps in https://github.com/istio/istio.github.io/pull/1687, the **Direct HTTPS traffic through an egress gateway** section.

Dump ADS and see that there is no filterChainMatch on the listener of the egress gateway.

**Version**
Istio: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-20180705-09-15/

Kubernetes:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:11:08Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.8-2+af27ab4b096122", GitCommit:"af27ab4b096122049e65b75ee29ac115b1d58f6b", GitTreeState:"clean", BuildDate:"2018-06-14T04:07:19Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
No

**Environment**
Kubernetes on IBM Cloud Container Service.

**Comment by ijsnellf** [comment]
Replicated with the following config:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  - www.google.com
  gateways:
  - istio-egressgateway
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
```

The gateway implementation does not support this at all. This is the only place we set the SNI hosts when building listeners: https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/gateway.go#L414

**Comment by rshriram** [comment]
This is working as intended. The gateway's hosts go directly into filter chain match. Since you declared the gateway to be capable of accepting any host, the matches get mangled. 
You should try to add the hosts in the gateway.

**Comment by vadimeisenbergibm** [comment]
Trying:

```bash
cat <<EOF | istioctl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - www.google.com
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  - www.google.com
  gateways:
  - istio-egressgateway
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
EOF
```

Cleanup:
```bash
istioctl delete serviceentry cnn google
istioctl delete gateway istio-egressgateway
istioctl delete virtualservice direct-through-egress-gateway
```

**Comment by vadimeisenbergibm** [comment]
@rshriram Note the two TCP proxies in the ADS above. I guess Envoy will randomly select _www.google.com_ or _edition.cnn.com_ for either request. The TLS routing by `sni_hosts` must be implemented implemented by setting a different `filterChainMatch` per `VirtualService`, as it is done for the sidecar proxies. I do not see any other option.

**Comment by vadimeisenbergibm** [comment]
Testing the SNI routing without the egress gateway:

```
cat <<EOF | istioctl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
EOF
```

Cleanup:
```bash
istioctl delete serviceentry cnn google

```
