### ISSUE TITLE
EKS side-car injection problem

### ISSUE THREAD

**Issue by kHRISl33t** [istio/istio#6918]
I'm trying to make istio's sidecar injection work in EKS. 
Successfully created the ServiceEntry for my external DB.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: postgres-access
  namespace: istio-system
spec:
  hosts:
  - url-to-db-1.net
  - url-to-db-2.net
  ports:
  - number: 5432
    protocol: TCP
```

But If I run `kubectl get deployment myapp -o yaml | istioctl kube-inject -f - | kubectl apply -f -
` it will successfully manages to do its stuff, but at first 2 tries it cant connect to the db giving me `ECONNREFUSED`. After these 2 tries the 3rd one is always successful and manages to connect to my db.

```bash
myapp-679988bfcc-cxcds   0/2       Pending   0         0s
myapp-679988bfcc-cxcds   0/2       Pending   0         0s
myapp-679988bfcc-cxcds   0/2       Init:0/1   0         0s
myapp-679988bfcc-cxcds   0/2       PodInitializing   0         1s
myapp-679988bfcc-cxcds   2/2       Running   0         2s
myapp-679988bfcc-cxcds   1/2       Error     0         3s
myapp-679988bfcc-cxcds   2/2       Running   1         4s
myapp-679988bfcc-cxcds   1/2       CrashLoopBackOff   1         7s
myapp-679988bfcc-cxcds   2/2       Running   2         28s
```

Log between crashes:

```bash
2018-07-09T09:23:45.483Z - error: Error while starting app process {"name":"SequelizeConnectionRefusedError","parent":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"url-to-db-1.net","port":5432},"original":{"$ref":"$[\"meta\"][\"parent\"]"}}
```

I also tried to create the deployment with:
```
# before applying
kubectl apply -f <(istioctl kube-inject -f <resource.yaml>)
# creating an example of it
istioctl kube-inject -f deployment.yaml -o deployment-injected.yaml
```

but sadly I got the same error.

Anyone has/had the same issue? Or If someone can give me hints/ideas what am I doing wrong.
Thanks!
