### ISSUE TITLE
RedisQuota don't work

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#6966]
**Describe the bug**

memquota work, but the redisquota don't work
**Expected behavior**

redisquota can work 

**Steps to reproduce the bug**
Steps to reproduce the behavior.
in install/kubernetes/istio-demo.yml i don't find redisquota, so i create it using the config below
**redisquota**
```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: redisquotas.config.istio.io
  labels:
    app: mixer
    package: redisquota
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: redisquota
    plural: redisquotas
    singular: redisquota
  scope: Namespaced
  version: v1alpha2
---
```

Then according to the [redisquota](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/redisquota/),the adaptor config is:
```
apiVersion: "config.istio.io/v1alpha2"
kind: redisquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 2
    validDuration: 2s
    bucketDuration: 1s
    rateLimitAlgorithm: ROLLING_WINDOW
    overrides:
    - dimensions:
        destination: svc1
      maxAmount: 1
  redisServerUrl: redis.xxx.xxx:6379
  connectionPoolSize: 1
---

apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: source.labels["app"] | source.service | "unknown"
    sourceVersion: source.labels["version"] | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"

---

apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: handler.redisquota
    instances:
    - requestcount.quota
---
apiVersion: "config.istio.io/v1alpha2"
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: "1"
      quota: requestcount

---
apiVersion: "config.istio.io/v1alpha2"
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: svc1
    namespace: svc
```
**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
istio:0.8.0

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
not

**Environment**
Which environment, cloud vendor, OS, etc are you using?
kubernetes
