### ISSUE TITLE
Istio RBAC Improvements

### ISSUE THREAD

**Issue by liminw** [istio/istio#6984]
Some improvements we can do for Istio RBAC:

- [x] Convert config.istio.io to rbac.istio.io. (https://github.com/istio/istio/pull/6874)

- [x] Support AllAuthenticatedUsers for principals. Today we can set {user: "*"} to represent "AllUsers", including authenticated and unauthenticated identities. In some cases, we may need to accept only the authenticated identities. We can introduce  "AllAuthenticatedUsers" in addition to "AllUsers". ([Authorization V2](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ), https://github.com/istio/istio/pull/11800)

- [x] Support JWT claims that are arrays (or non-string). For example, there can be a claim "groups: ["aaa", "bbb"]". Matching any one of the values in the array should pass the authorization check (https://github.com/envoyproxy/envoy/pull/3964, https://github.com/istio/proxy/pull/1896, https://github.com/istio/istio/pull/7747, https://github.com/istio/proxy/pull/1925)

- [ ] Support Mesh objects for ServiceRole and ServiceRoleBinding. MeshServiceRole can be bound to namespace level ServiceRoleBinding or MeshServiceRoleBinding. (will be done as part of [Authorization V2](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ))

- [x] Allow Multiple values for principals. Currently principals are map<string, string>, which allows a single string value. We can use the "Constraint" definition for principal, so that we can write:
```
   subjects:
   - properties:
     - key: request.auth.claims["group"]
       values: ["g1", "g2"]
```
  ([Authorization V2](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ), https://github.com/istio/istio/pull/11800)

- [x] Support excludedValues for permissions and principals. For example:
```
  rules:
  - constraints:
    - key: destination.service
      excludedValues: ["secret.default.svc.cluster.local"]
```
 ([Authorization V2](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ), https://github.com/istio/istio/pull/11712, https://github.com/istio/istio/pull/11800)

- [x] Support other protocols like TCP and mango (https://github.com/istio/istio/pull/8325, https://github.com/envoyproxy/envoy/pull/4083)

- [x] Query RBAC effect through CLI. In addition to issue #4856, we can provide commands to support  queries like list all permissions a subject has, or list all members that are allowed to access a service. (issue #4856, https://github.com/istio/istio/pull/9036)

**Comment by rshriram** [comment]
convert config.istio.io to rbac.istio.io

**Comment by liminw** [comment]
@rshriram Added. Thanks.

**Comment by rshriram** [comment]
Need RBAC for tcp and mongo. More like a generic RBAC stuff so that any protocol decoder could generate attributes and have RBAC implemented.

**Comment by liminw** [comment]
@rshriram TCP level support is on the roadmap too. I added the item. Thanks for bringing this up.

**Comment by cameronmoreau** [comment]
I am assuming that the example listed above is specifying that both `g1` AND `g2` are required groups for the incoming JWT.
```
   subjects:
   - properties:
     - key: request.auth.claims["group"]
       values: ["g1", "g2"]
```

I was wondering if this functionality will extend to scopes as well, where both `foo.read` AND `foo.write` are required scopes, i.e.
```
   subjects:
   - properties:
     - key: request.auth.claims["scope"]
       values: ["foo.read", "foo.write"]
```
In Istio 1.1.0 snapshot, applying the above example results in a `json: cannot unmarshal array` error.


Also, I've tried the following ServiceRoleBinding in Istio 1.1.0 snapshot, and it appears that the scope is treated as `foo.read` OR `foo.write`:
```
  subjects:
    - properties:
        request.auth.claims[scope]: "cloud_controller.read"
    - properties:
        request.auth.claims[scope]: "openid"
```
Which is a great improvement, but we are wondering how to specify an "AND" relationship for multiple scopes.

**Comment by liminw** [comment]
@cameronmoreau The use case you mentioned is not supported currently. The ones you referred to above are all OR semantics instead of AND. 

But I think we can extend our current semantics to support your use case. Here is what I have in mind. You can write the following configuration:
```
  subjects:
  - properties: 
      request.auth.claims[scope]-1: "foo.read"
      request.auth.claims[scope]-2: "foo.write"
```

All the "properties" are ANDed together. However, the data structure under properties is a "map", so we need to guarantee the uniqueness of the keys. By adding "-1" and "-2" to the attribute name, we can allow users to define different conditions for the same claim (avoid key conflict).

**Comment by peterhaochen47** [comment]
@liminw I see. Thank you!

I'm trying ServiceRoleBinding on Istio-1.1-snapshot.1. And the following yaml is not working:
```
spec:
  subjects:
    - properties:
      - key: request.auth.claims["scope"]
        values: ["openid"]
  roleRef:
    kind: ServiceRole
    name: "productpage-viewer"
```

Error:
```
 json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```

Is this RBAC improvement in a later release/snapshot?

**Comment by peterhaochen47** [comment]
@liminw As a separate discussion, for the AND semantic for list-type claims. I see how `request.auth.claims[scope]-n` would work, but it looks a bit clunky, as least to me? 

For me, a more intuitive grammar would be that the following represents **AND**:
```
   subjects:
   - properties:
     - key: request.auth.claims["scope"]
       values: ["foo.read", "foo.write"]
```
And the following represents **OR**:
```
  subjects:
    - properties:
        request.auth.claims[scope]: "foo.read"
    - properties:
        request.auth.claims[scope]: "foo.write"
```
What do you think? Is there any technical inconsistency with this? Perhaps we could ask some people to chime in?

**Comment by liminw** [comment]
@peterhaochen47 Thanks for the suggestion. Not all improvements mentioned are implemented. The ones that are implemented is checked ([x]). My comments above was just a proposal. 

Currently we have "constraints" defined in ServiceRole, which has the OR semantics for the "values". 
```
   rules:
   - services: ["*"]
     constraints:
     - key: request.headers[version]
       values: ["v1", "v2"]
```
So it would be confusing if we say that the values in "properties" are ANDed together. 

If request.auth.claims[scope]-n looks clunky, another alternative is to specifically call out AND or OR semantics. For example, below statement means that both "foo.read" AND "foo.write" scopes are required. 
```
  subjects:
  - andProperties:
      request.auth.claims[scopes]: "foo.read, foo.write"
```
And the following says that either "foo.read" OR "foo.write" is required.
```
  subjects:
  - orProperties:
      request.auth.claims[scopes]: "foo.read, foo.write"
```
You can have both "andProperties" and "orProperties" (plus other properties) in a subject definition (all of them are ANDed together). For example, 
```
  subjects:
  - user: "a-service-account"
    andProperties: 
      request.auth.claims[domain]: "example.com"
     orProperties:
       request.auth.claims[scopes]: "foo.read, foo.write"
```
What do you think?

**Comment by peterhaochen47** [comment]
@liminw Thanks for explaining! 
For the key, I think `andProperties` and `orProperties` are better than `request.auth.claims[scope]-n`. 

For the value, you used `"foo.read, foo.write"` in your example, which I have a question about: Shouldn't the scopes be in array form (e.g.: `["foo.read", "foo.write"]`) just like your proposed constraints schema in the [top comment](https://github.com/istio/istio/issues/6984#issue-339958911):
```
   subjects:
   - properties:
     - key: request.auth.claims["group"]
       values: ["g1", "g2"]
```

That is, eventually we have this:
```
  subjects:
  - andProperties:
      request.auth.claims[scopes]: ["foo.read", "foo.write"]
```

We are open to making a PR on this `AND` semantic.

**Comment by liminw** [comment]
@peterhaochen47 I would like to use array as well. However, with proto definition, I cannot create a map from a string to a "repeated" field. So, you either write
```
subjects:
   - properties:
     - key: request.auth.claims["group"]
       values: ["g1", "g2"]
```
or
```
subjects:
- properties:
    request.auth.claims[scopes]: "foo.read, foo.write"
```
I think the second is more compact, especially if the majority case is map to a single string. And comma-separated strings are commonly used in many places. 

I am ok with either "properties" (existing term) or "andProperties" (making it more specific). Note that today "properties" are already ANDed. And by default, all entries inside a Subject definition are ANDed. 

If you would like to make a PR to support this AND semantics, that sounds great to me :)

**Comment by peterhaochen47** [comment]
@liminw In your [comment](https://github.com/istio/istio/issues/6984#issuecomment-433177935) you mentioned that "Note that today "properties" are already ANDed." So did you mean that in the following yaml:
```

**Comment by peterhaochen47** [comment]
@liminw Sorry I am a little confused. Thanks for the reply though!
In your [comment](https://github.com/istio/istio/issues/6984#issuecomment-433177935) you mentioned that `Note that today "properties" are already ANDed.` So did you mean that in the following example "g1" and "g2" are ANDed together?
```
subjects:
   - properties:
     - key: request.auth.claims["group"]
       values: ["g1", "g2"]
```

But in an earlier [comment](https://github.com/istio/istio/issues/6984#issuecomment-427203323) you mentioned `The ones you referred to above are all OR semantics instead of AND`. And you also [said](https://github.com/istio/istio/issues/6984#issuecomment-430046864) that `it would be confusing if we say that the values in "properties" are ANDed together`. Did something change in the past few weeks?

Or, when you said `Note that today "properties" are already ANDed` you meant in the following example "g1" and "g2" are ANDed together?
```
  subjects:
    - properties:
        request.auth.claims[group]: "g1"
    - properties:
        request.auth.claims[group]: "g2"
```

**Comment by liminw** [comment]
@peterhaochen47 Let me try to clarify. The item listed below was just an earlier thought. It is not implemented. 
```
subjects:
   - properties:
     - key: request.auth.claims["group"]
       values: ["g1", "g2"]
```
If we go with proposed mechanism below, we will NOT do the above. 
```
subjects:
- properties:
    request.auth.claims[scopes]: "foo.read, foo.write"
```
Currently, if you specify two entries in the properties for a single Subject, they are ANDed together. 
```
subjects:
- properties:
    request.auth.claims[iss]: "accounts.google.com"
    request.auth.claims[aud]: "abc"
```
But if you specify properties in different "Subjects", they are ORed.
```
subjects:
    - properties:
        request.auth.claims[group]: "g1"
    - properties:
        request.auth.claims[group]: "g2"
```

**Comment by liminw** [comment]
Here is a [proposal](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ) on changes to the existing Authorization Policy:

**Comment by derbeneviv** [comment]
Hello! Found this issue and guess it's most suitable to ask here.
>Support JWT claims that are arrays
task is marked as 'done' here but i can't find a proper syntax on how to implement this in configuration in istio 1.1.
Is this released at least i some kind of dev release? What is the syntax, if yes?

**Comment by yangminzhu** [comment]
@derbeneviv Please take a look at the 1.1 doc: https://preliminary.istio.io/docs/tasks/security/rbac-groups/

**Comment by ezra-sc** [comment]
I'm still looking for an answer to how to add multiple groups (OR'd together) to a ServiceRoleBinding. The doc linked by yangminzhu above only shows examples with one group and it makes it look like the field only accepts a single string, so based on the answers above it sounds like I can use:

```
spec:
  subjects:
  - properties:
      request.auth.claims[groups]: "group1"
  - properties:
      request.auth.claims[groups]: "group2"
```

It also sounds like this might work, but I'm less certain about it:
```
spec:
  subjects:
  - group: "group1"
  - group: "group2"
```

Is there a better way of doing this yet?
Thanks!
