### ISSUE TITLE
How to limit rate for dynamic dimensions such as each ip address

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#7002]
**Describe the bug**
Quota seems can only support the enum matches, but how to support the rate limit, such as rate limit of each IP address, or according to the parameters in the request, these parameters are to much , can not listed in dimensions.

**Expected behavior**
dynamic rate limit

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
0.8.0
**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

**Environment**
Which environment, cloud vendor, OS, etc are you using?
kubernetes

**Comment by skydoctor** [comment]
@douglas-reid: Is this possible? This would be quite useful and has a very broad use-case. Say you don't know the set of source IPs sending requests towards your server but want to limit the rate to  100 per unique IP.

**Comment by douglas-reid** [comment]
@skydoctor it is certainly possible and is part of the intended behavior.

Example configuration:

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: memquota
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: requestcount.quota.istio-system
      maxAmount: 1
      validDuration: 1m
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: source.ip | ip("0.0.0.0")

---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: memquota
    instances:
    - requestcount.quota
```

Send two requests for the same source IP, followed immediately by a different IP:

```bash
$ mixc check -a source.ip=a:96:5:6 ... -q RequestCount=1
...
Check RPC completed successfully. Check status was OK
...
  Quota         Granted Amount  Duration
  RequestCount  1               1m0s

$ mixc check -a source.ip=a:96:5:6 ... -q RequestCount=1
...
Check RPC completed successfully. Check status was OK
...
  Quota         Granted Amount  Duration
  RequestCount  0               1m0s

$ mixc check -a source.ip=a:96:0:6 ... -q RequestCount=1
...
Check RPC completed successfully. Check status was OK
...
  Quota         Granted Amount  Duration
  RequestCount  1               1m0s
```
