### ISSUE TITLE
SSL received a record that exceeded the maximum permissible length

### ISSUE THREAD

**Issue by wjwinner** [istio/istio#7009]
**Describe the bug**

**Expected behavior**

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
  name: gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.test.com'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - demo.test.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-echo-deploy
  namespace: mynamespace
spec:
  gateways:
  - gateway.default.svc.cluster.local
  hosts:
  - demo.test.com
  http:
  - route:
    - destination:
        host: demo-echo-deploy
        port:
          number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-echo-deploy
  namespace: mynamespace
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-echo
    reference: demo-echo-deploy
```

```bash
[root@host01 /tmp/tls]# curl -v 'https://demo.test.com'
* About to connect() to demo.test.com port 443 (#0)
*   Trying 10.233.32.89...
* Connected to demo.test.com (10.233.32.89) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)
* SSL received a record that exceeded the maximum permissible length.
* Closing connection 0
curl: (35) SSL received a record that exceeded the maximum permissible length.
```

**Version**
istio 1.0
 
**Is Istio Auth enabled or not?**
no
