### ISSUE TITLE
Problem configuring gateway/virtualservices - Only 404's

### ISSUE THREAD

**Issue by Richard87** [istio/istio#7018]
**Describe the bug**
I have a hard time configuring the gateway, and a hard time troubleshooting/debugging the problem.

**Expected behavior**
Better feedback about what is wrong, tools to troubleshoot, like list all applied virtualservcies to a gateway etc.

**Steps to reproduce the bug**
This is my gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
   # - "*"
    - "vistio.skil-sky.no"
    - "httpbin.skil-sky.no"
```
And my vistio `VirtualService`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vistio
  namespace: istio-vistio
spec:
  gateways:
    - istio-gateway
  hosts:
    - "vistio.skil-sky.no"
  http:
  - match:
    - uri:
        prefix: "/api/*"
    route:
    - destination:
        port:
          number: 9091
        host: vistio-api
  - route:
    - destination:
        port:
          number: 8080
        host: vistio-web
```
and my httpbin `VirtualService`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
    - istio-gateway
  hosts:
    - "httpbin.skil-sky.no"
  http:
  - route:
    - destination:
        port:
          number: 8000
        host: httpbin
```
(notice the gateway and services is in different namespaces... is that a problem?)

The log from istio-ingressgateway:
`"GET / HTTP/1.1" 404 - 0 0 2 - "10.244.5.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "fdd813fe-0233-9f63-8228-0dc295798569" "httpbin.skil-sky.no" "-"`

So the request is coming to istio-ingress-gateway...

**Version**
```
$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Is Istio Auth enabled or not?**
I'm not sure? I Used this command:
`helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml`

**Environment**
I'm running on DigitalOcean, installed with kubeadm, kubernetes 1.11, with digital ocean cloud provider
```
kubectl version     
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Richard87** [comment]
seems `VirtualService` must be in the same namespace as the Gateway to work.

**Comment by dkushner** [comment]
Can we have confirmation that this is working as intended? Is there really no way for a VirtualService to produce routes in a Gateway definition that does not live in the same namespace? For our purposes, we have istio deployed in the `istio-system` namespace, along with the gateway definition for all of our services. We use namespaces to group related services within the cluster and these services need to configure the central gateway that lives in `istio-system`. It _has_ to live in `istio-system` because the gateway configuration relies on TLS secrets that are only present in this namespace.

This can't be intentional, surely?

**Comment by edalford11** [comment]
Need to specify <namespace>/<gateway> in the virtual service and it should work. See #11127

**Comment by grebois** [comment]
Im trying to create an ingress for kiali but I also get only 404 with the following yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "kiali.mydomain.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - "kiali.mydomain.com"
  gateways:
    - kiali
  http:
    - match:
        - uri:
            prefix: /kiali
      route:
        - destination:
            port:
              number: 20001
            host: httpbin
            
```

**Comment by jithinjks** [comment]
They can leave in seprate ns but only 1 condition, the gateway which is in another ns as virtual service must specify along with the ns. 
example , assume my gateway is in ns istio-system and if so my virtualservice looks like this

```
_apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: dev
spec:
  hosts:
    - "*"
  gateways:
  - istio-system/bookinfo-gateway_
```

This worked for me when the gateway used as "istio-system"/<gatewayname> and before applying simply the gateway name i was getting 404.

Hope this helps!
