### ISSUE TITLE
Gateway secret should only be accesible to istio-ingressgateway-service-account

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#7073]
https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/
"Note that by default all the service accounts in the istio-system namespace can access this secret, so the private key can be leaked. You can change the Role-Based Access Control (RBAC) rules to protect it."

We already have rbac rules and a service account called "istio-ingressgateway-service-account", instructions should include rbac protection for the secret and a helm template for it.

**Comment by andraxylia** [comment]
cc @costinm @rshriram

**Comment by andraxylia** [comment]
The expectation is the cluster admin will protect istio-system, so only account with visibility on istio-system will see it, but we still need rbac.

**Comment by vadimeisenbergibm** [comment]
It seems that the sentence "Note that by default all the service accounts in the istio-system namespace can access this secret, so the private key can be leaked. You can change the Role-Based Access Control (RBAC) rules to protect it." is incorrect, maybe I am missing something.

`kubectl auth can-i` returns `no` for the service accounts in the `istio-system` namespace.

```
$ kubectl auth can-i get secrets/istio-ingressgateway-certs -n istio-system --as=system:serviceaccount:istio-system:istio-ingressgateway-service-account
no
$ kubectl auth can-i get secrets -n istio-system --as=system:serviceaccount:istio-system:istio-ingressgateway-service-account
no
$ kubectl auth can-i get secrets -n istio-system --as=system:serviceaccount:istio-system:default
no
$ kubectl auth can-i get secrets/istio-ingressgateway-certs -n istio-system --as=system:serviceaccount:istio-system:default
no
```

Only when you explicitly define a Role and a Rolebinding to get the secret, the answer is yes:
```
cat <<EOF | kubectl apply -f -
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: ingress-gateway-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["istio-ingressgateway-certs"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-gateway-secrets-reader
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: istio-ingressgateway-service-account
  namespace: istio-system
roleRef:
  kind: Role
  name: ingress-gateway-secrets-reader
  apiGroup: rbac.authorization.k8s.io
EOF
```

```
kubectl auth can-i get secrets/istio-ingressgateway-certs -n istio-system --as=system:serviceaccount:istio-system:istio-ingressgateway-service-account
yes
[vadime@vadime-mac istio-1.0.2]$ kubectl auth can-i get secrets -n istio-system --as=system:serviceaccount:istio-system:istio-ingressgateway-service-account
no
[vadime@vadime-mac istio-1.0.2]$ kubectl auth can-i get secrets -n istio-system --as=system:serviceaccount:istio-system:default
no
[vadime@vadime-mac istio-1.0.2]$ kubectl auth can-i get secrets/istio-ingressgateway-certs -n istio-system --as=system:serviceaccount:istio-system:default
no
```

The secret, however, can be mounted to any pod in istio-system, it seems the mounting operation runs with permissions of kubectl, e.g. cluster admin. It is not clear if a secret's mounting can be limited within a namespace.

@andraxylia @costinm @rshriram
