### ISSUE TITLE
Using the Consul Service Registry makes the Pilot readiness check fail

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#7080]
**Describe the bug**
This ticket refers to the discussion here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-users/pePAbg-ikVM/F7ALt38zAQAJ

When configuring a Consul registry for Pilot by adding the command line argument `--registries Consul,Kubernetes` the readiness check seems to fail and the Envoy sidecars no longer seem to be able to fetch the dynamic configuration.

**Expected behavior**
Even when configuring a Consul registry I expect Pilot to work and provision the sidecars with the dynamic configuration.
At the same time it should be possible to have a readiness check for Pilot.

**Steps to reproduce the bug**
Install Istio with the istio-demo.yaml, but change the container spec of the discovery container like this:
```
      containers:
        - name: discovery
          image: "docker.io/istio/pilot:0.8.0"
          imagePullPolicy: IfNotPresent
          args:
          - "discovery"
          - "--consulserverURL"
          - "<IP of Consul server>:8500"
          - "--registries"
          - "Consul,Kubernetes"
...
```

Make sure that Consul is running before and accessible at the given IP. 
For testing purpose it's best to start it outside the K8s cluster.

Then start any Istio service and check the Envoy configuration by creating a port-forward for port 15000 and fetch the configuration via `curl localhost:15000/clusters` and `curl localhost:15000/config_dump`.
The dump should only show the static configuration.

A workaround is to remove the readiness check for this container:
```yaml
    spec:
      serviceAccountName: istio-pilot-service-account
      containers:
        - name: discovery
          image: "docker.io/istio/pilot:0.8.0"
          imagePullPolicy: IfNotPresent
          args:
          - "discovery"
          - "--consulserverURL"
          - "<IP of Consul server>:8500"
          - "--registries"
          - "Consul,Kubernetes"
# TODO(sdake) remove when secrets are automagically registered
          ports:
          - containerPort: 8080
          - containerPort: 15010
          # readinessProbe:
          #   httpGet:
          #     path: /v1/registration
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 5
```

**Version**
```
$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No, Istio was installed with a modified istio-demo.yaml

**Environment**
Running on a local K8s cluster on Docker for Mac.
