### ISSUE TITLE
Gateway with TLS termination produce HTTP/2 without TLS (h2c) connection

### ISSUE THREAD

**Issue by kirgene** [istio/istio#7086]
**Describe the bug**
I have Gateway with domain SSL certificates and configured TLS termination.
When I connect to server via https (HTTP/2 with TLS) I'm getting HTTP 503 error.
I've found that while envoy terminates TLS it doesn't proxy connection from HTTP/2 to HTTP/1.1.
Handling h2c (HTTP/2 without TLS) connection is a very tricky task:
for example nginx cannot handle HTTP/1.1 and HTTP/2 on the same port so there should be separate ports for HTTP/2 and HTTP/1.1.

**Expected behavior**
Gateway should produce HTTP/1.1 connection when TLS termination is used.

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "domain.com"
    - "*.domain.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "domain.com"
    - "*.domain.com"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: website
spec:
  hosts:
  - "www.domain.com"
  gateways:
  - web-gateway
  http:
  - route:
    - destination:
        host: website
        port:
          number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: website
```

**Version**
istio v0.8.0
kubernetes v1.10.5

**Is Istio Auth enabled or not?**
Used istio-auth.yaml

**Environment**
GKE
