### ISSUE TITLE
Enabling prometheus ingress using helm template results in an error

### ISSUE THREAD

**Issue by smawson** [istio/istio#7159]
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set prometheus.ingress.enabled=true > $HOME/istio.yaml

kubectl create namespace istio-system

kubectl create -f $HOME/istio.yaml

Result:
Error from server (Invalid): error when creating "/home/sven/istio.yaml": Ingress.extensions "prometheus" is invalid: spec: Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified

**Comment by LillyWu** [comment]
@smawson  I have tested this in 0.8 in IBM Kubernetes Services, and I countered the same situation with you. 

After I checked the details of the istio.yaml file, I found the `rules` list is empty as 
```
3516 # Source: istio/charts/prometheus/templates/ingress.yaml
3517 apiVersion: extensions/v1beta1
3518 kind: Ingress
3519 metadata:
3520   name: prometheus
3521   namespace: istio-system
3522   labels:
3523     app: prometheus
3524   annotations:
3525 spec:
3526   rules:
``` 
Then I checked the charts template ingress.yaml and found the rules will be set with iteratoring the hosts. the templates is located in `istio-0.8.0/install/kubernetes/helm/istio/charts/prometheus/templates/ingress.yaml`
below is the specific segment to set the rules
```
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 9090
    {{- end -}}
```

And I found the hosts is not set in the values.yaml file with commenting. I just uncomment it and run 
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set prometheus.ingress.enabled=true > $HOME/istio.yaml

kubectl create namespace istio-system

kubectl create -f $HOME/istio.yaml
```
again, it works well and prometheus ingress created successfully with log `ingress.extensions "prometheus" created` when installing istio.

I have submited a PR for this problem to uncomment this to make it work. 
Please check: https://github.com/istio/istio/pull/7211
