### ISSUE TITLE
Proxy communicates with Mixer over plaintext even with auth enabled

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#7166]
Even when auth is enabled, proxy communicates with Mixer over plain text.  
```
global:
  # controlPlaneMtls enabled. Will result in delays starting the pods while secrets are
  # propagated, not recommended for tests.
  controlPlaneSecurityEnabled: true
  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true
```
