### ISSUE TITLE
1.0.0-snapshot.0 issue or pilot error on retries??

### ISSUE THREAD

**Issue by imhotepio** [istio/istio#7231]
**Describe the bug**
I am having issues setting up a retry rule using istio 1.0 preview release. 

I have the following rule setup:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind:       VirtualService
metadata:
  name: retry
spec:
  hosts:
  - svc1
  http:
  - match:
    - headers:
        cookie:
          regex: "^(.*?;)?(fail=true)(;.*)?$"
    route:
    - destination:
        host: svc1
    retries:
      attempts:      5
      perTryTimeout: 500ms
```

Using a special cookie, svc1 calls will fail once every 5 calls. Using this policy I am
expecting the call to be retried 5 times and hence eventually succeed but the mesh never retries
the call once it fails. I have been watching the service logs and don't see any retries attempts. 
To make sure this rule is correctly setup and indeed gets triggered I've injected a faults instead of the  retry and do see the fault being injected. 

What am I missing? or what will be the best way to debug this issue?

I am really trying to reuse resources that I've used prior to the whole api change. In prev releases I had the following rules: What will be the equivalent in the new api version??

```yaml
# In Istio 0.6...
---
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name:      fault
spec:
  precedence: 2
  destination:
    name:      svc1
  match:
    source:
      name: svc2
  httpFault:
    abort:
      percent:    50
      httpStatus: 404
---
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name:      retry
spec:
  precedence: 3
  destination:
    name:      svc1
  httpReqRetries:
    simpleRetry:
      attempts:      5
      perTryTimeout: 500ms
```

Thank you for taking a look and helping out!

**Expected behavior**
I see up to 5 retries attempts, which in the case will make the upstream call succeed.

**Steps to reproduce the bug**
1. Create a service that programmatically fails after x calls
2. Alternatively: setup a fault policy to make the service fail 50% of the time (I have tried that but could not figure out how to make both the failure and retry policy work together. This used to work in Istio 0.5 with precedence. (Help or how to would be appreciated here!)
2. Setup a VirtualService resource with retries as specified above.
3. Setup a bash loop to repeatedly calls the service url. 

Expecting to see no call errors given the retries...

**Version**
Istio; 1.0.0-snapshot.0
Kubernetes: 1.10.0
Minikube: 0.28.0

**Is Istio Auth enabled or not?**
Using istio.yaml

**Environment**
Using minikube on osx
