### ISSUE TITLE
Istio gateway not working with any other port except 80 and 443

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#7242]
**Describe the bug**
Hello,
We are using istio with istio auth enable and expose the istio ingress controller using NodePort.

```
NAME                                       READY     STATUS      RESTARTS   AGE       IP           NODE
grafana-6f6dff9986-sdqqh                   1/1       Running     0          7d        172.16.0.3   node2.example.com
istio-citadel-7bdc7775c7-vfkl6             1/1       Running     0          7d        172.16.2.6   node1.example.com
istio-cleanup-old-ca-2snhr                 0/1       Completed   0          7d        172.16.1.7   node3.example.com
istio-egressgateway-78dd788b6d-sttcs       1/1       Running     0          7d        172.16.1.3   node3.example.com
istio-ingressgateway-7dd84b68d6-2xf5m      1/1       Running     0          7d        172.16.0.5   node2.example.com
istio-ingressgateway-7dd84b68d6-kcm9b      1/1       Running     0          7d        172.16.2.5   node1.example.com
istio-ingressgateway-7dd84b68d6-krcxk      1/1       Running     0          7d        172.16.1.4   node3.example.com
istio-mixer-post-install-ckcfs             0/1       Completed   0          7d        172.16.1.2   node3.example.com
istio-pilot-d5bbc5c59-7ph4m                2/2       Running     1          7d        172.16.0.8   node2.example.com
istio-policy-64595c6fff-p22zh              2/2       Running     0          7d        172.16.0.4   node2.example.com
istio-sidecar-injector-645c89bc64-wmlxx    1/1       Running     0          7d        172.16.0.9   node2.example.com
istio-statsd-prom-bridge-949999c4c-bqwnx   1/1       Running     0          7d        172.16.0.2   node2.example.com
istio-telemetry-cfb674b6c-hcd5p            2/2       Running     0          7d        172.16.1.5   node3.example.com
istio-tracing-754cdfd695-2gbtx             1/1       Running     0          7d        172.16.0.7   node2.example.com
prometheus-86cb6dd77c-8thdj                1/1       Running     0          7d        172.16.0.6   node2.example.com
servicegraph-5849b7d696-vdx69              1/1       Running     0          7d        172.16.1.6   node3.example.com
```

Services:

```
NAME                       TYPE           CLUSTER-IP   EXTERNAL-IP                                    PORT(S)                                                               AGE
grafana                    ClusterIP      10.3.0.229                                                             3000/TCP                                                              7d
istio-citadel              ClusterIP      10.3.0.199   <none>                                         8060/TCP,9093/TCP                                                     7d
istio-egressgateway        ClusterIP      10.3.0.57    <none>                                         80/TCP,443/TCP                                                        7d
istio-ingressgateway       NodePort       10.3.0.253   <none>                                         80:31380/TCP,443:31390/TCP,31400:31400/TCP                            7d
istio-pilot                ClusterIP      10.3.0.123   <none>                                         15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   7d
istio-policy               ClusterIP      10.3.0.103   <none>                                         9091/TCP,15004/TCP,9093/TCP                                           7d
istio-sidecar-injector     ClusterIP      10.3.0.251   <none>                                         443/TCP                                                               7d
istio-statsd-prom-bridge   ClusterIP      10.3.0.250   <none>                                         9102/TCP,9125/UDP                                                     7d
istio-telemetry            ClusterIP      10.3.0.170   <none>                                         9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 7d
prometheus                 ClusterIP      10.3.0.169   <none>                                         9090/TCP                                                              7d
servicegraph               ClusterIP      10.3.0.144   <none>                                         8088/TCP                                                              7d
tracing                    LoadBalancer   10.3.0.224   <pending>                                      80:31379/TCP                                                          7d
zipkin                     ClusterIP      10.3.0.213   <none>                                         9411/TCP                                                              7d
```

Issue is we are not able to use any other ports in istio gateway except standard Ports(80/443) for domain.

We are trying to call our domain with the port 5000 (test.com:5000) but it always gives the following error in ingress log [404 NOTFOUND]:

```
[2018-07-19T12:55:53.271Z] "GET / HTTP/1.1" 404 NR 0 0 3 - "192.168.X.X" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "e59d988c-e99f-9f9e-a6a1-23513dcf8e89" "test.com:5000" "-"
[2018-07-19T12:55:54.462Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "192.168.X.X" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "be272d54-45ba-97a9-8573-bccaaf556f24" "test.com:5000" "-"
[2018-07-19T12:55:55.382Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "192.168.X.X" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "dbeaa57e-3fee-9a43-a7a9-067fda01afae" "test.com:5000" "-"
[2018-07-19T12:56:08.721Z] "GET / HTTP/1.1" 404 NR 0 0 3 - "192.168.X.X" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "08640ff9-bc6a-981e-8902-cf9e57f08754" "test.com:5000" "-"
[2018-07-19T12:56:10.454Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "192.168.X.X" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "291fee82-bb13-9270-ace2-83946b824815" "test.com:5000" "-"
```

But when we tried using port 80 it works [200 OK]:

```
[2018-07-19T12:41:58.143Z] "GET / HTTP/1.1" 200 - 0 11 25 21 "192.168.X.X" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "23e000b5-2307-9ba9-8c6f-c4385e961ba2" "test.com" "172.16.1.58:5000"
[2018-07-19T12:42:16.852Z] "GET / HTTP/1.1" 200 - 0 11 55 24 "192.168.X.X" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "4275d15d-ae9a-9476-a4f9-401b5ab96671" "test.com" "172.16.1.58:5000"
```

gateway.yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myistio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
     - test.com
	port:
	  number: 5000
```

virtualservice.yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-test
  namespace: istio-system
spec:
  hosts:
  - test.com
  gateways:
  - myistio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: service-test.ns-test.svc.cluster.local
        port:
          number: 5000
```

So are we missing something here?

**Version**
Istio - 0.8
Kubernetes - 10.3
etcd - v3

**Is Istio Auth enabled or not?**
Yes it is enabled

**Environment**
We deployed kubernetes on coreos.

Are we missing something here?

Thanks in advance :)

**Comment by rshriram** [comment]
Add a port match. 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-test
  namespace: istio-system
spec:
  hosts:
  - test.com
  gateways:
  - myistio-gateway
  http:
  - match:
    - port: 5000
       uri:
        prefix: /
    route:
    - destination:
        host: service-test.ns-test.svc.cluster.local
        port:
          number: 5000
```

**Comment by ronakpandya7** [comment]
Thanks for your reply @rshriram 

I added the port match but still it is not working.

Here is my Virtualservice after adding port match:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: couchtesting-example
  namespace: istio-system
spec:
  hosts:
  - test.com
  gateways:
  - myistio-gateway
  http:
  - match:
    - port: 5000
      uri:
        prefix: /
    route:
    - destination:
        host: service-testing.ns-testing.svc.cluster.local
        port:
          number: 5000
```
It is giving the same error 404-NOT FOUND

**Comment by wulala-wuwu** [comment]
I have the same issue.

**Comment by rshriram** [comment]
Oh I totally forgot. If you want to expose new ports in the ingressgateway, you have to edit the helm chart (in values.yaml, we have a gateways section that lists the ports that the gateway service in Kubernetes should listen on. This will allow k8s to setup the load balancer properly with the appropriate ports to open up). And then you do the rest (adding new gateway server on the port, etc.)..

Put another way, if you want to open up new ports on the platform specific gateway service, you have ot make sure that these ports are accessible from outside. So, while your gateway definition would have caused Envoy to start listening on port 5000, the K8S load balancer object pointing to the gateway is still only accepting connections on 80/443 per the K8S service declaration (this stuff is happening at the Os level or setting up stuff at cloud provider level for load balancers). All of Istio stuff is confined to Envoy level.

**Comment by ronakpandya7** [comment]
Thanks for the reply @rshriram 
We have allowed 5000 port in our ingress gateway service file :

```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system    
  labels:
    chart: ingressgateway-0.8.0
    release: RELEASE-NAME
    heritage: Tiller
    istio: ingressgateway
spec:
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
    -
      name: http
      nodePort: 31380
      port: 80
    -
      name: https
      nodePort: 31390
      port: 443
    -
      name: tcp
      nodePort: 31400
      port: 31400
    -
      name: tcp-1
      nodePort: 31401
      port: 5000
  externalTrafficPolicy: Local
```
We are able to telnet 31401 port using IP.

gateway.yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myistio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - test.com
    port:
      name: http
      number: 5000
      protocol: HTTP
```

virtualservice.yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: couchtesting-example
  namespace: istio-system
spec:
  hosts:
  - test.com
  gateways:
  - myistio-gateway
  http:
  - match:
    - port: 5000
      uri:
        prefix: /
    route:
    - destination:
        host: service-testing.ns-testing.svc.cluster.local
        port:
          number: 5000
```

But when we try to browse test.com:5000 it is still not working.

Now error code changes from 404 to 503 in ingressgateways logs:

```
[2018-07-23T07:22:24.205Z] "GET / HTTP/1.1" 503 NR 0 0 3 - "192.168.51.2" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "bded057a-0b97-9ac4-ab10-98469e6c758a" "test.com:5000" "-"
[2018-07-23T07:22:24.625Z] "GET /favicon.ico HTTP/1.1" 503 NR 0 0 0 - "192.168.51.2" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "f8939fe7-2d20-94f2-8f0a-7442c45cab8c" "test.com:5000" "-"
```
Are we missing something here?

**Comment by ahmmadkour** [comment]
Make sure that the service "service-test" has port name http, check this for service port name requirements https://istio.io/docs/setup/kubernetes/sidecar-injection/

**Comment by ronakpandya7** [comment]
Hello @ahmmadkour 

I already gave service name as "http", please check my service.yaml file:

```
kind: Service
apiVersion: v1
metadata:
  name: service-testing
  namespace: ns-testing
spec:
  selector:
    app: env-t1
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
```

**Comment by ronakpandya7** [comment]
Can anyone help here?

**Comment by sebastian-garofalo** [comment]
I'm also getting a 503. 
What I'm trying to do is to expose the port 16686 to be able to access the jaeger dashboard.
I created a service to expose the istio jaeger dashboard.

```
kind: Service
apiVersion: v1
metadata:
  name: jaeger-istio-service
spec:
  selector:
    app: jaeger
  ports:
  - name: http
    protocol: TCP
    port: 16686
    targetPort: 16686
```

Created a gateway

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 16686
      name: http-jaeger
      protocol: HTTP
    hosts:
    - "*"
```

and then created the mapping

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  # Be carefull with the order of the match of urls. The first match is the one taking precedence.
  http:
  - timeout: 10s
    match:
    - port: 16686
      uri:
        prefix: /
    route:
    - destination:
        port:
          number: 16686
        host: jaeger-istio-service.istio-system.svc.cluster.local
```

And only get 503s

```
> GET / HTTP/1.1
> Host: localhost:16686
> User-Agent: curl/7.53.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< date: Mon, 30 Jul 2018 15:47:21 GMT
< server: envoy
< content-length: 0
```

Can anyone help with this? Thanks

**Comment by ronakpandya7** [comment]
Hello @sebastian-garofalo,

Change your gateway file to:

**Comment by ahmmadkour** [comment]
@ronakpandya7 regarding your issue I don't see port 5000 exposed in your gateway service  
`istio-ingressgateway       NodePort       10.3.0.253   <none>                                         80:31380/TCP,443:31390/TCP,31400:31400/TCP                            7d`

Are you sure you added your port to gateway deployment and service definition, if you have used helm for installation you can add the port in this file install/kubernetes/helm/istio/values.yaml under ingressgateway section.

**Comment by ronakpandya7** [comment]
Hello @ahmmadkour,

That was the older output of the get service, we already checked by exposing 5000 port in ingressgateway service but it is not working.

Foneally it is working by kubectl create command for gateway and virtualservices instead of istioctl.

**Comment by rshriram** [comment]
You can do the same for the other port. I think the other poster’s point was that you have to match the host header on port as well (foo.com:1234) if the port is not the default port 80

**Comment by sebastian-garofalo** [comment]
Sorry guys but it doesn't work, the only port where Istio replies is on the 80.
I used what @ronakpandya7 suggested, with localhost:80 it works, but as soon as I start using the port 16686 it starts repliying with 404 errors.
I'm using Istio 0.8 and kubernetes 1.10.3 provided by docker edge for windows.

Here are the config files I used:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: seba-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 16686
      name: http
      protocol: HTTP
    hosts:
    - "localhost:16686"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: seba-httpbin
spec:
  hosts:
  - "localhost:16686"
  gateways:
  - seba-gateway
  http:
  - timeout: 5s
    match:
    - uri:
        prefix: /graph
    route:
    - destination:
        host: servicegraph.istio-system.svc.cluster.local
        port:
          number: 8088
```

```
$ curl -v localhost:16686/graph
* timeout on name lookup is not supported
*   Trying ::1...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (::1) port 16686 (#0)
> GET /graph HTTP/1.1
> Host: localhost:16686
> User-Agent: curl/7.53.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< location: http://localhost:16686/graph
< date: Wed, 01 Aug 2018 15:24:36 GMT
< server: envoy
< content-length: 0
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host localhost left intact
```

Any suggestion guys?

**Comment by ronakpandya7** [comment]
Hello @sebastian-garofalo,

Didi you check is your request first comes in the ingress gateway pod?

Can you please paste here logs of the ingressgateway pod after applying your curl.
First we have to check that is your request comes into gateway or not.

Thanks

**Comment by sebastian-garofalo** [comment]
@ronakpandya7 

Here are the logs for the ingress-gateway pod when the curl localhost:16686 request is sent

```
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: adapter_template_kubernetes.output.source_service, source.uid, Exact-keys: context.protocol, destination.service, destination.uid, source.ip,
[2018-08-02T14:35:26.858Z] "GET / HTTP/1.1" 404 - 0 0 53 - "192.168.65.3" "curl/7.53.0" "4051d453-8686-98d8-9960-3c5fe38d975d" "localhost:16686" "-"
[2018-08-02 14:35:31.215][19][info][main] external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain
```

Thanks for your help

**Comment by wansuiye** [comment]
@ronakpandya7 hi, it can not work with kubectl iinstead of istioctl in istio 1.0.0…

**Comment by ronakpandya7** [comment]
@wansuiye yes i checked yesterday, its not working with kubectl anymore :(
please check #6469

**Comment by hustshawn** [comment]
Hi @all, does anyone has a solution?

In my case, I want expose the the Grafana in the `stable/prometheus-operator` with ingress gateway, and find the issue here.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monitoring
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - "*"
  gateways:
  - monitoring
  http:
  - match:
    - uri:
        exact: /grafana
    route:
    - destination:
        host: prometheus-grafana
        port:
          number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    chart: grafana-3.3.9
    heritage: Tiller
    release: prometheus
  name: prometheus-grafana
  namespace: monitoring
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
```
And what I achieved is that I can proxy the service to the grafana, but grafana requires [additional proxy config](https://grafana.com/docs/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-grafana)  to make it work. 
Unfortunately, it still not work well.
Just got some message from grafana
```
If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help
```
Anyone has idea about it?
