### ISSUE TITLE
Tracing helm chart omits type for service "tracing"

### ISSUE THREAD

**Issue by chen23** [istio/istio#7243]
**Describe the bug**
When deploying tracing via helm, the chart does not specify the service type (ClusterIP, NodePort, LoadBalancer) in the template.

**Expected behavior**
specifying "--set tracing.service.type=NodePort" will update both "zipkin" and "tracing" service (currently only updates "zipkin").

**Steps to reproduce the bug**
deploy helm using "--set tracing.enabled=true --set tracing.service.type=NodePort"

Observe in output:

```
---
# Source: istio/charts/tracing/templates/service.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
...
  spec:
    type: NodePort  <--- OK here
...
- apiVersion: v1
  kind: Service
  metadata:
    name: tracing
...
  spec:      <--- missing here
    ports:
      - name: http-query
...
```
Related chart template:

https://github.com/istio/istio/blob/91a85fa9917b45705d8a24ede6c1f167b61e4019/install/kubernetes/helm/istio/charts/tracing/templates/service.yaml#L37

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
istio:  release-1.0 branch b573db99f57f4fba01c5562b8bb36ae5d4bd6928  (July 18th)
k8s: 1.10.5
