### ISSUE TITLE
Gateway SSL Istio 1.0 prelim

### ISSUE THREAD

**Issue by robertfreund** [istio/istio#7284]
Gateway SSL does not work when using 1.0 prelim.

Service is accessible when using 80 but not when using 443. 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "myhost"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
      - "myhost"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
  - "myhost"
  gateways:
  - app-gateway # <---- bind to gateway
  http:
  - match:
    - uri:
        prefix: /app
    route:
    - destination:
        host: app
```

Ingress logs:

[2018-07-20 19:36:21.445][18][warning][config] external/envoy/source/server/listener_manager_impl.cc:259] adding listener '0.0.0.0:443': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
[2018-07-20 19:36:21.445][18][info][upstream] external/envoy/source/server/lds_api.cc:73] lds: add/update listener '0.0.0.0_443'

Certs have been created following example:
```
kubectl get secrets -n istio-system istio-ingressgateway-certs
NAME                         TYPE                DATA      AGE
istio-ingressgateway-certs   kubernetes.io/tls   2         23m

```
Curl response when using ssl. curl -v https://myhost/app/
```
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb13c000000)
> GET /app/ HTTP/1.1
> Host: myhost
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 503 
< date: Fri, 20 Jul 2018 19:52:46 GMT
< server: envoy
```
