### ISSUE TITLE
Question : Istio HTTPS External ServiceEntry Behind Proxy

### ISSUE THREAD

**Issue by james-r-smith** [istio/istio#7302]
I'm new to Istio, so if this is somewhere in the documentation that I missed, please let me know.

I'm working with the Istio Sidecar container injected into my pods, and I can't for the life of me reach a proxied HTTPS service from my application. When I go inside the sidecar container, using `curl slack.com` hangs unless I export the proxy variables.

I have tried the following scenarios :

- HTTP proxy set to HTTP, HTTPS proxy set to HTTPS
```
# Main app
proxyconnect tcp: tls: oversized record received with length 20527
# Istio Sidecar, showing no logs
```

- Both proxies set to HTTP
```
# Main app
post: Post https://slack.com/api/rtm.connect: Not Found
# Istio Sidecar
[2018-07-18T05:41:20.481Z] "CONNECT slack.com:443 HTTP/1.1" 404 - 0 0 0 - "-" "Go-http-client/1.1" "-" "slack.com:443" "-"
```

ServiceEntry Configuration

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  creationTimestamp: null
  name: slack-ext
  namespace: <NAMESPACE>
  resourceVersion: "63072151"
spec:
  hosts:
  - 13.33.114.239 # slack.com
  ports:
  - name: http # I have tried https
    number: 443
    protocol: HTTP # I have tried HTTPS
---
```

Any help is much appreciated!

**Comment by jamalsia** [comment]
have you tried: 
```
hosts:
  - slack.com
```
instead of 
```
 hosts:
  - 13.33.114.239 # slack.com
```

**Comment by ijsnellf** [comment]
The following works for me:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: slack-ext
spec:
  hosts:
  - slack.com
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
```

**Comment by james-r-smith** [comment]
I have tried both versions, it hasn't worked for me. Are you guys testing under a proxy? I've gone through the documentation, it doesn't cover hitting HTTPS services under a proxy. 😢

**Comment by james-r-smith** [comment]
@ijsnellf and @jamalsia,

I'm still not able to connect. When I remove Istio, I can connect just fine. I'm getting 404 from anything that I hit, which make me feel that the ServiceEntry isn't working at all.

Here's three different examples of hits:

```
[2018-08-04T01:37:44.032Z] "CONNECT slack.com:443 HTTP/1.1" 404 - 0 0 0 - "-" "curl/7.61.0" "-" "slack.com:443" "-"
[2018-08-04T01:37:50.883Z] "CONNECT www.slack.com:443 HTTP/1.1" 404 - 0 0 0 - "-" "curl/7.61.0" "-" "www.slack.com:443" "-"
[2018-08-04T01:38:39.587Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "-" "curl/7.61.0" "adf7606c-aaff-9f74-a356-9fe3ddd4bde9" "54.230.4.209" "-"
```

I have tried adding VirtualService, `resolution` as `NONE` and `DNS`, pointing the VirtualService to either slack or my proxy address, adding an additional ServiceEntry for my proxy address.

Please help!

+ @rshriram

**Comment by jamalsia** [comment]
Please refer to

https://github.com/istio/istio/issues/7603#issuecomment-410187816

Le sam. 4 août 2018 à 04:59, James Smith <notifications@github.com> a
écrit :

**Comment by james-r-smith** [comment]
@jamalsia, that doesn't help. I'm failing at the `CONNECT` stage with my proxy.

```
kubectl exec -it <POD_NAME> -c <CONTAINER_NAME> -- curl -vsL -o /dev/null -D - https://slack.com
* Rebuilt URL to: https://slack.com/
* Uses proxy env variable HTTPS_PROXY == '<COMPANY_PROXY>'
*   Trying <IP_ADDR>...
* TCP_NODELAY set
* Connected to <COMPANY_PROXY> (<IP_ADDR>) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to slack.com:443
> CONNECT slack.com:443 HTTP/1.1
> Host: slack.com:443
> User-Agent: curl/7.61.0
> Proxy-Connection: Keep-Alive
```

This give me the output:

```
[2018-08-04T01:37:44.032Z] "CONNECT slack.com:443 HTTP/1.1" 404 - 0 0 0 - "-" "curl/7.61.0" "-" "slack.com:443" "-"
```

Whereas a normal HTTP proxy passes through just fine:

```
[2018-08-04T01:38:39.587Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "-" "curl/7.61.0" "adf7606c-aaff-9f74-a356-9fe3ddd4bde9" "54.230.4.209" "-"
```

So, I'm not sure how to set up my Istio rules to work with my proxy, then dial out to the HTTPS URL.

**Comment by james-r-smith** [comment]
@jamalsia, @ijsnellf, @rshriram, or anyone else,

If you can point me in the right direction for help, I'd greatly appreciate it. I'm understanding that Istio does not cover `CONNECT` requests **while under a proxy** currently. If my assumption is wrong, please inform me be explaining the steps to get external HTTPS connections to work **while under a proxy**. Thanks!

**Comment by xaka** [comment]
@james-r-smith I've found the solution, which is to use TCP proxy:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: proxy
spec:
  addresses:
    - 10.243.127.53/32
  ports:
    - number: 80
      name: http
      protocol: tcp
  resolution: DNS
  location: MESH_EXTERNAL
```

where `10.243.127.53` is your corporate proxy address (you could also use domain name, for that replace `addresses` with `hosts`)

**Comment by james-r-smith** [comment]
@xaka, can you be more specific.

1. Do you have any other Istio configurations involved in your test, for example, the address that you want to hit like `slack.com`.
2. Does your container have the env proxies set?
3. Can you possibly post output showing `CONNECT` from an https service request?

Appreciate it!

**Comment by james-r-smith** [comment]
@xaka, just trying to get more information if you don't mind (appreciate your help, by the way).

1. Using `addresses` only produces the below issues when configuring.

```
Error: 2 errors occurred:

* validation error: service entry must have at least one host
* validation error: CIDR addresses are allowed only for NONE/STATIC resolution types
```

2. Regarding your comment:
> ... because Istio is no longer involved in processing.
I'm reading this as, Istio enables all traffic through the corporate proxy. Doesn't this mean that you aren't taking advantage of the benefits that Istio brings, like its limiting of external hosts, for instance.

3. So I have the above configuration that you suggested to my application, using `hosts` instead of `addresses`, but from the `istio-proxy` container's logs, I can see that it's not getting hit by the proxy, but rather the external service:
```
[2018-08-22T03:29:38.116Z] "CONNECT slack.com:443 HTTP/1.1" 404 - 0 0 0 - "-" "Go-http-client/1.1" "-" "slack.com:443" "-"
```

Are you able to explain how you are getting Istio to get hit by the proxy and let the request pass through? I am still getting the same output from cURL that I posted above. I'll add here with the full output:
```
kubectl exec -it <POD_NAME> -c <CONTAINER_NAME> -- curl -vsL -o /dev/null -D - https://slack.com
* Rebuilt URL to: https://slack.com/
* Uses proxy env variable HTTPS_PROXY == '<COMPANY_PROXY>'
*   Trying <IP_ADDR>...
* TCP_NODELAY set
* Connected to <COMPANY_PROXY> (<IP_ADDR>) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to slack.com:443
> CONNECT slack.com:443 HTTP/1.1
> Host: slack.com:443
> User-Agent: curl/7.61.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< date: Wed, 22 Aug 2018 03:28:53 GMT
date: Wed, 22 Aug 2018 03:28:53 GMT
< server: envoy
server: envoy
< content-length: 0
content-length: 0
<

* Received HTTP code 404 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
```

As you can see, it connects to the proxy then makes the attempt connect. The only log I see from Istio during this whole transaction is the Slack request that I posted above.

Istio configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
    - <COMPANY_PROXY>
  ports:
    - number: 8080 # Our proxy is using 8080 for the port
      name: http
      protocol: tcp
  resolution: DNS
  location: MESH_EXTERNAL
```

**Comment by xaka** [comment]
Try this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
    - <ADDR>
  addresses:
    - <ADDR>/32
  ports:
    - number: 8080
      name: http
      protocol: tcp
  resolution: NONE
  location: MESH_EXTERNAL
```

Though I'm not sure which version of Istio you're using. In my case it's 1.0.0.

The reason you're getting such behavior is because Istio recognizes the traffic as HTTP and tries to proxy it for you, but problem is Istio doesn't support CONNECT and responds back with HTTP 404. 

That's why you have to have a ServiceEntry for a corporate proxy with protocol defined as TCP so Istio wouldn't treat it as HTTP and let it go through.
