### ISSUE TITLE
Can't access external HTTPS ServiceEntry from VirtualService

### ISSUE THREAD

**Issue by kirgene** [istio/istio#7317]
**Describe the bug**
I'm trying to route traffic through my domain gateway to google storage using my domain TLS certificates.
But when I try to connect to `static.mydomain.com` I receive 503 error.

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "static.mydomain.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "static.mydomain.com"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-storage
spec:
  hosts:
  - 'storage.googleapis.com'
  location: MESH_EXTERNAL
  ports:  
  - number: 443 
    name: https
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-storage
spec:
  hosts:
  - "static.mydomain.com"
  gateways:
  - my-gateway
  http:
  - rewrite:
      uri: /static.mydomain.com/
    route:
    - destination:
        host: storage.googleapis.com
        port:
          number: 443
```

**Version**
istio-release-1.0-20180722-02-44
kubernetes v1.10.5

**Is Istio Auth enabled or not?**
Used istio-auth.yaml.
mTLS and sidecar injection are enabled. 

**Environment**
GKE 1.10.5-gke.0

**Comment by jon-whit** [comment]
Having the same issue.

**Comment by rsnj** [comment]
I'm having the same issue as well. Is there anyway around this? I'm trying to transparently route my legacy APIs through Istio
https://service.com/legacy --> https://legacy.com/

**Comment by slql0011** [comment]
> I'm having the same issue as well. Is there anyway around this? I'm trying to transparently route my legacy APIs through Istio
> https://service.com/legacy --> https://legacy.com/

Having the same issue.

**Comment by slql0011** [comment]
> I'm having the same issue as well. Is there anyway around this? I'm trying to transparently route my legacy APIs through Istio
> https://service.com/legacy --> https://legacy.com/

Having the same issue.

**Comment by onixmatt** [comment]
Any update on this issue? Perhaps a workaround?

**Comment by onixmatt** [comment]
After some trial and error I managed to figure out how to accomplish this:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: something-gateway
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - assets.something.com
    - www.something.com
    - something.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - assets.something.com
    - www.something.com
    - something.com
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: something-assets-external
spec:
  hosts:
  - storage.googleapis.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: storage.googleapis.com
    ports:
      http: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: something-assets-vs
spec:
  hosts:
  - "assets.something.com"
  gateways:
  - something-gateway
  http:
  - match:
    - uri:
        prefix: "/" # Rewrite below to match bucket name.
    rewrite:
      uri: "something-assets/" # This is the name of your bucket.
    route:
    - destination:
        host: storage.googleapis.com
        port:
          number: 80
```
