### ISSUE TITLE
GRPC multi version custom headers not working 

### ISSUE THREAD

**Issue by sanguinius69** [istio/istio#7319]
**Describe the bug**
It seems the routing of istio is not working when trying to route to different subsets depending on a custom headers ?

**Expected behavior**
It should route accordingly to my custom header exact match but it is not, it always routing to v1 :(

**Steps to reproduce the bug**
If you have the same grpc service with 2 versions
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-virtual
spec:
  gateways:
  - mesh
  hosts:
  - hello
  http:
  - match:
    - headers:
        app-version:
          exact: v1
    route:
    - destination:
        host: hello
        subset: v1
  - match:
    - headers:
        app-version:
          exact: 3c8306800fc2488a87dcd295b01f16d6
    route:
    - destination:
        host: hello
        subset: 3c8306800fc2488a87dcd295b01f16d6
```

Of course I have the according destinationrule
```
Host:  hello
  Subsets:
    - name: v1
       labels:
         app: hello
         version:  v1
    - name: 3c8306800fc2488a87dcd295b01f16d6
       labels:      
         app: hello
         version:  3c8306800fc2488a87dcd295b01f16d6
```

**Version**
Istio:
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

Kubernetes: v1.9.7-gke.3
Running on GKE

**Is Istio Auth enabled or not?**
No istio Auth

**Environment**
GKE

Any help is welcome, thanks a lot !
