### ISSUE TITLE
Istio gateway not working with multiple domain with different certificates 

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#7325]
**Describe the bug**
Hello,
We are using istio with istio auth disable and expose the istio ingress controller using NodePort.

```
NAME                                       READY     STATUS      RESTARTS   AGE       IP           NODE
grafana-6f6dff9986-sdqqh                   1/1       Running     0          7d        172.16.0.3   node2.example.com
istio-citadel-7bdc7775c7-vfkl6             1/1       Running     0          7d        172.16.2.6   node1.example.com
istio-cleanup-old-ca-2snhr                 0/1       Completed   0          7d        172.16.1.7   node3.example.com
istio-egressgateway-78dd788b6d-sttcs       1/1       Running     0          7d        172.16.1.3   node3.example.com
istio-ingressgateway-7dd84b68d6-2xf5m      1/1       Running     0          7d        172.16.0.5   node2.example.com
istio-ingressgateway-7dd84b68d6-kcm9b      1/1       Running     0          7d        172.16.2.5   node1.example.com
istio-ingressgateway-7dd84b68d6-krcxk      1/1       Running     0          7d        172.16.1.4   node3.example.com
istio-mixer-post-install-ckcfs             0/1       Completed   0          7d        172.16.1.2   node3.example.com
istio-pilot-d5bbc5c59-7ph4m                2/2       Running     1          7d        172.16.0.8   node2.example.com
istio-policy-64595c6fff-p22zh              2/2       Running     0          7d        172.16.0.4   node2.example.com
istio-sidecar-injector-645c89bc64-wmlxx    1/1       Running     0          7d        172.16.0.9   node2.example.com
istio-statsd-prom-bridge-949999c4c-bqwnx   1/1       Running     0          7d        172.16.0.2   node2.example.com
istio-telemetry-cfb674b6c-hcd5p            2/2       Running     0          7d        172.16.1.5   node3.example.com
istio-tracing-754cdfd695-2gbtx             1/1       Running     0          7d        172.16.0.7   node2.example.com
prometheus-86cb6dd77c-8thdj                1/1       Running     0          7d        172.16.0.6   node2.example.com
servicegraph-5849b7d696-vdx69              1/1       Running     0          7d        172.16.1.6   node3.example.com
```

Issue is we are not able to put more then one domain's certificate in istio gateway file.
We have setup tls in gateway using this [link](https://istio.io/docs/tasks/traffic-management/secure-ingress/#configure-a-tls-ingress-gateway).

gateway.yaml

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myistio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - abc.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
  - hosts:
    - xyz.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-tls-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-tls-certs/tls.key
```
Here we have two domains "abc.com" and "xyz.com".
We created two tls secrets named "istio-ingressgateway-certs" and "istio-ingressgateway-tls-certs" for abc.com and xyz.com respectively.

Here when we browse "abc.com" it is working fine
But when we browse "xyz.com" it is not working

Ingress logs gives error: /etc/istio/ingressgateway-tls-certs/tls.crt path not found.

**Version**
Istio - 0.8
Kubernetes - 10.3
etcd - v3

**Is Istio Auth enabled or not?**
No

Are we missing here something?

**Comment by prune998** [comment]
Hi there.
You should try : 

1. put all the certificates in the `istio-ingressgateway-certs` secret, by changing it from a `TLS certificate` to a `regular secret`, with many files. Then, you will be able to use something like : 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myistio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - abc.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/abc.crt
      privateKey: /etc/istio/ingressgateway-certs/abc.key
  - hosts:
    - xyz.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/xyz.crt
      privateKey: /etc/istio/ingressgateway-certs/xyz.key
```
This is because the `IngressGateway` only mount one secret, `istio-ingressgateway-certs` in `/etc/istio/ingressgateway-certs`

2. use a different name for each HTPS port, like : 
```
- hosts:
    - abc.com
    port:
      name: https-abc
      number: 443
      protocol: HTTPS
...
  - hosts:
    - xyz.com
    port:
      name: https-xyz
      number: 443
      protocol: HTTPS
``` 
This was suggested by an Istio dev as, as of 0.8.0 (maybe it's changed in 1.0.0, I haven't been able to test yet) because the port name is added to some Envoy definitions, so if you use the same name some missmatch may occure.

Let me know if this work for you
