### ISSUE TITLE
Secure communication between Prometheus and Istio components

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#7352]
There is a frequent request to ensure that all Istio prometheus endpoints require mTLS.

When endpoints required mTLS, prometheus must be configured with mTLS.
Prometheus scrapes individual endpoints and addresses them as such.

1. Create a listeners for every port annotated for scraping.
2. The outbound cluster should be of type `orig_dst` so it ends up at the intended endpoint.
3. Match a svc by some header that prometheus sets, or by endpoint ip address.

related discussion: https://github.com/istio/istio/issues/5673

**Comment by bianpengyuan** [comment]
Seems like prometheus does not allow adding arbitrary headers. How does envoy match an endpoint ip to svc?

**Comment by maximbaz** [comment]
Is there any known workaround on how to currently feel application's metrics to Prometheus when using mTLS? Something like [using curl for liveness/readiness endpoints](https://istio.io/help/faq/security/#k8s-health-checks) would be more than acceptable.

My team wants to use Istio (with mTLS as the main goal), but we can't let go the application monitoring, so I'm in need of _any option_ of making Prometheus communicate with pods 🙂

**Comment by mandarjog** [comment]
If you can move your application Prometheus endpoint to another port, you can exclude form mtls and then Prometheus can scrape it

**Comment by maximbaz** [comment]
Thanks, I'll check if this is a possibility for us. Just to better understand this, is it the only know workaround at the moment?

**Comment by maximbaz** [comment]
Turns out our application metrics will have sensitive information and so we need to protect it with mTLS, thus excluding the port from mTLS is just not an option for us 😞

**Comment by mandarjog** [comment]
@maximbaz there is no work around for it yet, but we are planning to fix it in soon.

**Comment by maximbaz** [comment]
On the risk of being annoying (sorry!), I'd like to ask if you have at least approximate timeline for this feature? We have to request a temporary security exception for us to start using Istio in production, and it would really really help if we knew at least some dates. I can see this issue is part of `1.1` milestone, any early plans for when `1.1` is planned for the release? Thanks!

**Comment by mandarjog** [comment]
We will have a proposal for this feature out this week, and once the proposal is approved it should be another 2 weeks to implement.

**Comment by mandarjog** [comment]
@maximbaz I have just merged a PR that should address your problem.

**Comment by maximbaz** [comment]
I just wanted to follow-up, although that PR did enable using built-in Prometheus with mTLS (thanks for submitting it!), after a fair amount of testing we ended up disabling Istio's Prometheus and Grafana and opting for using `stable/prometheus-operator` helm chart instead.

In case someone else is looking for a similar setup, here's how to befriend Istio with mTLS and Prometheus deployed via prometheus-operator:

1. When deploying `prometheus-operator`, extend `prometheusSpec.secrets` with `istio.default` secret, this gets Istio's certificates mounted inside Prometheus pod under `/etc/prometheus/secrets/`.
1. In the `ServiceMonitor` object use `https` scheme and point Prometheus to Istio's certificates like so:

    ```
    endpoints:
      - port: http
        interval: 15s
        honorLabels: true
        path: "/api/health/prometheus"
        scheme: https
        tlsConfig:
          caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
          certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
          keyFile: /etc/prometheus/secrets/istio.default/key.pem
          insecureSkipVerify: true
    ```
