### ISSUE TITLE
SNI routing by egressgateway stopped working with Istio Auth

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#7361]
**Describe the bug**
SNI routing by egressgateway stopped working in https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180723-09-15/ with Istio Auth

**Expected behavior**
Directing HTTPS traffic thru the egressgateway, as described in https://preliminary.istio.io/docs/tasks/traffic-management/egress-gateway/#direct-https-traffic-through-an-egress-gateway, must work.
 
**Steps to reproduce the bug**
Follow the steps in https://preliminary.istio.io/docs/tasks/traffic-management/egress-gateway/#direct-https-traffic-through-an-egress-gateway. In step 5, error code 35 will be returned.

Run `istioctl proxy-config listeners $(kubectl get pod -l istio=egressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}') -n istio-system`. You will get `Error: no listeners found`

**Version**
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180723-09-15/

**Is Istio Auth enabled or not?**
Yes

**Environment**
Kubernetes

**Comment by vadimeisenbergibm** [comment]
The bug does not exist in https://github.com/istio/istio/releases/tag/1.0.0-snapshot.1

**Comment by rshriram** [comment]
Your gateway spec doesn't have SNI in the tls section

**Comment by vadimeisenbergibm** [comment]
Gateway TLS options do not have SNI.

**Comment by rshriram** [comment]
Split the virtual service into two parts. Tls route for mesh to egress. And then tcp route for egress gateway. All under same virtual service

**Comment by vadimeisenbergibm** [comment]
To specify the requirements:

1. Allow egress access to edition.cnn.com and to www.google.com, forbid access to anything else:

```
cat <<EOF | istioctl create -f -
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: cnn
    spec:
      hosts:
      - edition.cnn.com
      ports:
      - number: 443
        name: tls
        protocol: TLS
      resolution: DNS
EOF
```
