### ISSUE TITLE
Issue exposing service using Gateway 

### ISSUE THREAD

**Issue by hackintoshrao** [istio/istio#7362]
**Describe the bug**
Unable to expose running service using Gateway.  Want all the incoming traffic to be directed to the service by name `frontend`

As you can see in the list below I have service by name `front-end` running in the `istio-system` namespace. 

```
$ kubectl get svc  -n istio-system
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                                                               AGE
backend                    ClusterIP      10.31.251.217   <none>           80/TCP                                                                5h
frontend                   ClusterIP      10.31.253.56    <none>           80/TCP                                                                5h
grafana                    ClusterIP      10.31.248.255   <none>           3000/TCP                                                              7d
istio-citadel              ClusterIP      10.31.255.31    <none>           8060/TCP,9093/TCP                                                     7d
istio-egressgateway        ClusterIP      10.31.254.128   <none>           80/TCP,443/TCP                                                        7d
istio-ingress              LoadBalancer   10.31.253.245   xx.xxx.9x.2x     80:32000/TCP,443:31999/TCP                                            7d
istio-ingressgateway       LoadBalancer   10.31.247.94    xx.xxx.1xx.1xx  80:31380/TCP,443:31390/TCP,31400:31400/TCP                            7d
istio-pilot                ClusterIP      10.31.240.7     <none>           15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   7d
istio-policy               ClusterIP      10.31.243.123   <none>           9091/TCP,15004/TCP,9093/TCP                                           7d
istio-sidecar-injector     ClusterIP      10.31.247.144   <none>           443/TCP                                                               7d
istio-statsd-prom-bridge   ClusterIP      10.31.249.145   <none>           9102/TCP,9125/UDP                                                     7d
istio-telemetry            ClusterIP      10.31.249.217   <none>           9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 7d
prometheus                 ClusterIP      10.31.243.1     <none>           9090/TCP                                                              7d
servicegraph               ClusterIP      10.31.253.26    <none>           8088/TCP                                                              7d
tracing                    LoadBalancer   10.31.248.172   3x.2xx.xxx.xx   80:32700/TCP                                                          7d
zipkin                     ClusterIP      10.31.248.75    <none>           9411/TCP                                                              7d
```

The `frontend` service (Nginx serving web pages) is running and its healthy,  I verified using the port-forwarding of the service directly and then accessing it, 

```
kubectl port-forward --namespace istio-system $(kubectl get pod --namespace istio-system --selector="app=frontend" --output jsonpath='{.items[0].metadata.name}') 8080:80
```

Here is the gateway configuration I've used, 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend 
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: frontend.istio-system.svc.cluster.local
```
Here is the yaml config for the front-end service, 

```
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend 
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "gcr.io/my-project/container:test"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
```

**Expected behavior**
The Gateway to give access to the `frontend` service.

**Steps to reproduce the bug**
Use the configs above to reproduce. 

**Version**
istio version: `0.8.0`
Kubernetes version: `v1.9.7-gke.3`

**Is Istio Auth enabled or not?**
Auth not enabled

**Environment**
GKE
