### ISSUE TITLE
https external endpoints are all allowed when one service entry is added

### ISSUE THREAD

**Issue by jamalsia** [istio/istio#7364]
**Describe the bug: openbar https **
when creating a service entry  https in istio 1.0.0. it allows all endpoints running over https.
Eg: create 
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-ext
spec:
  hosts:
  - "www.google.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
```
then curl anything with https will work

```
root@sleep-86f6b99f94-gtlqr:/# curl -o /dev/null -sL -w "%{http_code}\n"  https://www.redhat.com
200
root@sleep-86f6b99f94-gtlqr:/# curl -o /dev/null -sL -w "%{http_code}\n"  https://www.google.com
200
root@sleep-86f6b99f94-gtlqr:/#
```

**Expected behavior**
only google.com over https is allowed. this works in 0.8.0. 
```
root@sleep-86f6b99f94-gtlqr:/# curl -o /dev/null -sL -w "%{http_code}\n"  https://www.redhat.com
000
root@sleep-86f6b99f94-gtlqr:/# curl -o /dev/null -sL -w "%{http_code}\n"  https://www.google.com
200
root@sleep-86f6b99f94-gtlqr:/#
```
**Steps to reproduce the bug**

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
cat <<EOF | istioctl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-ext
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
EOF
```

check deployment
```
istioctl get serviceentries
SERVICE-ENTRY NAME   HOSTS         PORTS       NAMESPACE     AGE
google-ext              www.google.com   HTTPS/443   default   11m
```

**Version**

```
istioctl version
Version: 1.0.0-snapshot.2
GitRevision: a66a221bfe4cc068abad0c1fba93093600a5c6ef
User: root@661f2acc021d
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-2+c8f1f59d8d233c", GitCommit:"c8f1f59d8d233c6e9a10cedd8aad4f43ad9ef5c7", GitTreeState:"clean", BuildDate:"2018-06-06T06:07:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
istio.VERSION is :
```
export CITADEL_HUB="docker.io/istio"
export CITADEL_TAG="0.8.0"
export MIXER_HUB="docker.io/istio"
export MIXER_TAG="0.8.0"
export PILOT_HUB="docker.io/istio"
export PILOT_TAG="0.8.0"
export PROXY_HUB="docker.io/istio"
export PROXY_TAG="0.8.0"
export PROXY_DEBUG=""
export ISTIO_NAMESPACE="istio-system"
export PILOT_DEBIAN_URL="https://storage.googleapis.com/istio-release/releases/0.8.0/deb"
export FORTIO_HUB="docker.io/istio"
export FORTIO_TAG="latest_release"
export HYPERKUBE_HUB="quay.io/coreos/hyperkube"
export HYPERKUBE_TAG="v1.7.6_coreos.0"
```

**Is Istio Auth enabled or not?**
using helm
`helm install install/kubernetes/helm/istio --name istio --namespace istio-system`

**Environment**
IBM Cloud

**Comment by ijsnellf** [comment]
Hi @jamalsia. I believe you want to set the `resolution` to `DNS`. In other words:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-ext
spec:
  hosts:
  - "www.google.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
```
If you omit the `resolution` field, we default to `NONE`. Please see the reference for descriptions of the different resolution types: https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry.Resolution
