### ISSUE TITLE
Pods Restart. May be istio-proxy startup order problem.

### ISSUE THREAD

**Issue by icowan** [istio/istio#7388]
**Describe the bug**
See below

**Steps to reproduce the bug**
See below

**Version**
istio 0.7.1 and istio 0.8.0

**Is Istio Auth enabled or not?**
no

**Environment**
centos 7.4

# When multiple pods are on the same node, only one pod is successfully started, and all others fail.

- Kubernetes version: 1.10.3

create a Endpoints:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-test
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-test
subsets:
  - addresses:
    - ip: 10.106.146.8
    ports:
      - port: 3306
        protocol: TCP
---
```

![](https://ofbudvg4c.qnssl.com/images/k8s/WechatIMG2275.jpeg)

my application code:

```go
var user = "root"
var password = "root"
var host = mysql-test.default
var port = 3306
var database = "hello"

var dataSource = fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8&parseTime=true&loc=Local&timeout=20m&collation=utf8mb4_unicode_ci", user, password, host, port, database)

db, err = sql.Open("default", dataSource)
if err != nil {
	panic(err)
}
```

![](https://ofbudvg4c.qnssl.com/images/k8s/WechatIMG2274.jpeg)

When multiple pods are on the same node, only one pod is successfully started, and all others fail.

the error is: panic Database connection error

Distributed on different nodes does not have this problem.

![](https://ofbudvg4c.qnssl.com/images/k8s/15305302261742.jpg)

## I guess

Pods have three containers: **MyProgram**、**istio-proxy**、**filebeat**
and a initcontainer: **istio-init**

**MyProgram**

**MyProgram** starts first and then starts to connect to the external database. But the data connection failed. **MyProgram** panic. Then **MyProgram** restarts 2 times and the network is finally normal. MyProgram success.

I guess:

> **MyProgram** is more than istio-proxy, the network is nowhere. The network fails to connect to the cluster service or external services will fail.

In order to verify this conjecture, I will execute a `time.Sleep(time.Second*10)` service before connecting **MyProgram** to an external service such as mysql. Service started successfully! 

version:

- Kubernetes version: v1.10.0
- istio 0.7.1
- Kubernetes version: v1.10.3
- istio 0.8.0
