### ISSUE TITLE
VirtualService port.name:http does not work but port.number: 80 does

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#7401]
**Describe the bug**
When deploying the following virtual service, if i use `port.name: http` i get `no healthy upstream`

(note port.name)
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-app
  namespace: istio-system
spec:
  hosts:
  - my-app.weather.com
  gateways:
  - istio-ingressgateway # pinned to ingress gateway only
  http:
  - route:
    - destination:
        host: my-app.dev.svc.cluster.local
        port:
          name: http
      weight: 100
```

```
"GET /heartbeat HTTP/1.1" 503 UH 0 19 3 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "my-app.weather.com" "-"
```

The below works instead (note port.number)
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-app
  namespace: istio-system
spec:
  hosts:
  - my-app.weather.com
  gateways:
  - istio-ingressgateway
  http:
  - route:
    - destination:
        host: my-app.dev.svc.cluster.local
        port:
          number: 80
      weight: 100
```
Service definition
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
```

**Expected behavior**
I could use either port.name or port.number and get the same results

**Steps to reproduce the bug**
Deploy an app that does not use istio sidecar and add the virtual service with port.name to your ingressgateway

**Version**
k8s 1.9.9
Istio 1.0-snapshot.2

**Is Istio Auth enabled or not?**
No

**Environment**
AWS Kops
