### ISSUE TITLE
Couchbase not working with istio

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#7418]
Hello,
We are using istio with istio auth disable and trying to setup couchbase with istio.
after browsing we found that couchbase is running fine, but issue came when we try to add one new node in the existing couchbase cluster and it gives the following error:

`
Attention: Join completion call failed. Got HTTP status 500 from REST call post to http://svc-couchbase-2.ns-test:8091/completeJoin. Body was: "[\"Unexpected server error, request logged.\"]"`

We tried to search in google for this error and come across this [link](https://issues.couchbase.com/browse/MB-15035).
It says after adding it again it will work but after adding it gives the following error:

`Attention: Prepare join failed. Node is already part of cluster.`

When we tried to setup couchbase without istio, it is working very fine and also we are able to add node into the existing couchbase cluster.

Below is the couchbase.yaml file:

```
apiVersion: v1
kind: Service
metadata:
  name: svc-couchbase-1
  namespace: ns-test
  labels:
    app: couchbase-1
spec:
  ports:
  - port: 8091
    name: web
    targetPort: 8091
  - port: 8092
    name: views
    targetPort: 8092
  - port: 8093
    name: query
    targetPort: 8093
  - port: 8094
    name: full-text
    targetPort: 8094
  - port: 11207
    name: client-lib
    targetPort: 11207
  - port: 11210
    name: client-lib-node
    targetPort: 11210
  - port: 11211
    name: non-smart-client
    targetPort: 11211
  - port: 18091
    name: web-ssl
    targetPort: 18091
  - port: 18092
    name: view-ssl
    targetPort: 18092
  - port: 18093
    name: query-svc-ssl
    targetPort: 18093
  - port: 4369
    name: erlang-port
    targetPort: 4369
  - port: 6060
    name: query-port
    targetPort: 6060
  selector:
    app: couchbase-1
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pod-couchbase-1
  namespace: ns-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase-1
    spec:
      containers:
      - name: couchbase-container
        image: couchbase/server:community-5.0.1
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 8094
        - containerPort: 11207
        - containerPort: 11210
        - containerPort: 11211
        - containerPort: 18091
        - containerPort: 18092
        - containerPort: 18093
        - containerPort: 4369
        - containerPort: 6060
        volumeMounts:
        - mountPath: /opt/couchbase/var
          name: cb-data-mount
      nodeSelector:
        node2: two
      volumes:
      - name: cb-data-mount
        hostPath:
         path: /var/test/couchbase
```

**Version**
Istio - 0.8
Kubernetes - 10.3
etcd - v3
couchbase - 5.0.1

**Is Istio Auth enabled or not?**
No

Are we missing here something?
