### ISSUE TITLE
Ingressgateway -> ServiceEntry - 503 Service Unavailable

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#7426]
**Describe the bug**
When trying to route traffic from an Istio-ingressgateway to a ServiceEntry dns entry we get `503 Service unavailable`
```
[2018-07-26 17:27:23.655][33][warning][upstream] external/envoy/source/common/upstream/original_dst_cluster.cc:102] original_dst_load_balancer: No downstream connection or no original_dst.
[2018-07-26T17:27:18.745Z] "GET /deflate HTTP/1.1" 503 UH 0 19 1 - "" "PostmanRuntime/7.1.5" "" "my-gateway.example.com"
```

**Expected behavior**
Ingressgateway would be able to forward traffic to ServiceEntries

**Steps to reproduce the bug**
1. Create gateway for host
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - my-gateway.example.com
```
2. Create Service Entry
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: istio-system
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
```
3. create virtual service

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-gateway.example.com
  namespace: istio-system
spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - my-gateway.example.com
  http:
  - route:
    - destination:
        host: httpbin.org
        port:
          number: 80
```

4. call `my-gateway.example.com/deflate` call should be the same response as `http://httpbin.org/deflate` or log into gateway and curl `curl -v -H "Host: my-gateway.example.com" "localhost:80/deflate"`

**Version**
k8s- 1.9.1
istio 1.0-snapshot.2

**Is Istio Auth enabled or not?**
no

**Environment**
kops aws

**Comment by nmnellis** [comment]
gateway config_dump
```json
  "routes": {
      "@type": "type.googleapis.com/envoy.admin.v2alpha.RoutesConfigDump",
      "dynamic_route_configs": [
        {
          "version_info": "2018-07-26T17:27:10Z",
          "route_config": {
            "name": "http.80",
            "virtual_hosts": [
              {
                "name": "my-gateway.example.com:80",
                "domains": [
                  "my-gateway.example.com"
                ],
                "routes": [
                  {
                    "match": {
                      "prefix": "/"
                    },
                    "route": {
                      "cluster": "outbound|80||httpbin.org",
                      "timeout": "0s"
                    },
                    "decorator": {
                      "operation": "httpbin.org:80/*"
                    },
                    "per_filter_config": {
                      "mixer": {
                        "forward_attributes": {
                          "attributes": {
                            "destination.service.namespace": {
                              "string_value": "istio-system"
                            },
                            "destination.service.name": {
                              "string_value": "httpbin.org"
                            },
                            "destination.service": {
                              "string_value": "httpbin.org"
                            },
                            "destination.service.host": {
                              "string_value": "httpbin.org"
                            }
                          }
                        },
                        "mixer_attributes": {
                          "attributes": {
                            "destination.service.host": {
                              "string_value": "httpbin.org"
                            },
                            "destination.service.namespace": {
                              "string_value": "istio-system"
                            },
                            "destination.service.name": {
                              "string_value": "httpbin.org"
                            },
                            "destination.service": {
                              "string_value": "httpbin.org"
                            }
                          }
                        }
                      }
                    }
                  }
                ]
              }
            ],
            "validate_clusters": false
          },
          "last_updated": "2018-07-26T17:27:10.446Z"
        }
      ]
    }
  }
```
cluster
```json
        {
          "version_info": "2018-07-26T17:27:10Z",
          "cluster": {
            "name": "outbound|80||httpbin.org",
            "type": "ORIGINAL_DST",
            "connect_timeout": "1s",
            "lb_policy": "ORIGINAL_DST_LB",
            "circuit_breakers": {
              "thresholds": [
                {}
              ]
            }
          },
          "last_updated": "2018-07-26T17:27:10.444Z"
        },
```

**Comment by ijsnellf** [comment]
What does the listener for port 80 look like on the gateway?

**Comment by nmnellis** [comment]
```yaml
{
  "configs": {
    "listeners": {
      "@type": "type.googleapis.com/envoy.admin.v2alpha.ListenersConfigDump",
      "version_info": "2018-07-26T17:27:10Z",
      "dynamic_active_listeners": [
        {
          "version_info": "2018-07-26T15:47:02Z",
          "listener": {
            "name": "0.0.0.0_80",
            "address": {
              "socket_address": {
                "address": "0.0.0.0",
                "port_value": 80
              }
            },
            "filter_chains": [
              {
                "filters": [
                  {
                    "name": "envoy.http_connection_manager",
                    "config": {
                      "tracing": {
                        "client_sampling": {
                          "value": 100
                        },
                        "operation_name": "EGRESS",
                        "overall_sampling": {
                          "value": 100
                        },
                        "random_sampling": {
                          "value": 100
                        }
                      },
                      "use_remote_address": true,
                      "rds": {
                        "route_config_name": "http.80",
                        "config_source": {
                          "ads": {}
                        }
                      },
                      "stat_prefix": "0.0.0.0_80",
                      "generate_request_id": true,
                      "upgrade_configs": [
                        {
                          "upgrade_type": "websocket"
                        }
                      ],
                      "access_log": [
                        {
                          "name": "envoy.file_access_log",
                          "config": {
                            "path": "/dev/stdout"
                          }
                        }
                      ],
                      "http_filters": [
                        {
                          "name": "mixer",
                          "config": {
                            "transport": {
                              "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                              "network_fail_policy": {
                                "policy": "FAIL_CLOSE"
                              },
                              "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
                              "attributes_for_mixer_proxy": {
                                "attributes": {
                                  "source.uid": {
                                    "string_value": "kubernetes://istio-ingressgateway-7fb978b497-4lmtw.istio-system"
                                  }
                                }
                              }
                            },
                            "service_configs": {
                              "default": {}
                            },
                            "default_destination_service": "default",
                            "mixer_attributes": {
                              "attributes": {
                                "source.uid": {
                                  "string_value": "kubernetes://istio-ingressgateway-7fb978b497-4lmtw.istio-system"
                                },
                                "context.reporter.kind": {
                                  "string_value": "outbound"
                                },
                                "source.namespace": {
                                  "string_value": "istio-system"
                                },
                                "context.reporter.uid": {
                                  "string_value": "kubernetes://istio-ingressgateway-7fb978b497-4lmtw.istio-system"
                                }
                              }
                            },
                            "forward_attributes": {
                              "attributes": {
                                "source.uid": {
                                  "string_value": "kubernetes://istio-ingressgateway-7fb978b497-4lmtw.istio-system"
                                }
                              }
                            }
                          }
                        },
                        {
                          "name": "envoy.cors"
                        },
                        {
                          "name": "envoy.fault"
                        },
                        {
                          "name": "envoy.router"
                        }
                      ]
                    }
                  }
                ]
              }
            ]
          },
          "last_updated": "2018-07-26T15:47:09.514Z"
        }
      ]
    },
```
