### ISSUE TITLE
EKS - creating networking configs time out

### ISSUE THREAD

**Issue by dbathgate** [istio/istio#7449]
I am attempting to setup the latest istio 1.0 snapshot "istio-1.0.0-snapshot.2" on AWS EKS and get timeouts from kubectl when creating anything in the `networking.istio.io/v1alpha3` API.

Install steps:
```bash
tar -xzf istio-1.0.0-snapshot.2-osx.tar.gz
cd istio-1.0.0-snapshot.2/
helm template install/kubernetes/helm/istio --name istio --namespace istio-system > istio.yml
kubectl create namespace istio-system
kubectl create -f istio.yml
```

Book service setup:
```bash
kubectl apply -f <(istioctl kube-inject -f bookservice-install.yml )
kubectl apply -f bookservice-service.yml
```

When I create the following config:
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookservice
spec:
  host: bookservice
  subsets:
  - name: blue
    labels:
      version: "1"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookservice
spec:
  hosts:
  - bookservice
  http:
  - route:
    - destination:
        host: bookservice
        subset: blue
```

This times out on either kubectl or istioctl

```
$ kubectl apply -f bookservice-istio-service.yml
Error from server (Timeout): error when creating "bookservice-istio-service.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when creating "bookservice-istio-service.yml": Timeout: request did not complete within allowed duratio
```

EKS is timing out after 30 seconds and returning a 504 status code
```
2018-07-27T15:27:05.306330Z	info	curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" https://XXXX.sk1.us-east-1.eks.amazonaws.com/apis/networking.istio.io/v1alpha3/namespaces/default/destinationrules
2018-07-27T15:27:35.613574Z	info	POST https://XXXX.sk1.us-east-1.eks.amazonaws.com/apis/networking.istio.io/v1alpha3/namespaces/default/destinationrules 504 Gateway Timeout in 30308 milliseconds
```

**Comment by ZackButcher** [comment]
Webhooks aren't enabled in EKS today, and Istio's sidecar injector webhook is enabled by default today. The combination means that EKS's k8s master hangs processing deployments. If you disable the controller (via the [helm values.yaml](https://github.com/istio/istio/blob/3b526b672e898a31ca829fe56c4581ba70d12086/install/kubernetes/helm/istio/values.yaml#L289) file) things _should_ work on EKS.

**Comment by dbathgate** [comment]
I suspected webhooks might have been the issue based on past reported issues so I tried without webhooks turned off and still the same timeout issue.

I just tried again with a fresh EKS cluster, and was still able to reproduce the timeout.

Setup:
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set sidecarInjectorWebhook.enabled=false > istio.yml
kubectl create namespace istio-system
kubectl apply -f istio.yml
```

Note that I am able to launch my application using `kube-inject`
```
kubectl apply -f <(istioctl kube-inject -f bookservice-install.yml )
```
The contents of `bookservice-instal.yml look like this
```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookservice-1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bookservice
        version: 1
      annotations:
        prometheus.io/scrape: true
    spec:
      containers:
      - name: details
        image: drbathgate/book-service:1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bookservice-api
          containerPort: 8080
        env:
        - name: JVM_ARGS
          value: -Dapp.version=1
```

It is when I create anything with an API version of `networking.istio.io/v1alpha3` that i get the timeout.
This includes VirtualService, DestinationRule, and Gateway.
