### ISSUE TITLE
authentication policy side-effects and debugging

### ISSUE THREAD

**Issue by theganyo** [istio/istio#7464]
I have a service that I want to protect with a JWT. So I create an authentication policy looks like this:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: auth-spec
  namespace: default
spec:
  origins:
  - jwt:
      issuer: https://apigee-cps-test.apigee.net/istio-auth/token
      jwksUri: https://apigee-cps-test.apigee.net/istio-auth/certs
  principalBinding: USE_ORIGIN
  targets:
  - name: helloworld
```

And this worked great! However, I gave it to another user who applied it to their mesh and they started getting a 503 error with this message when curling to their service:

	upstream connect error or disconnect/reset before headers

Not much to go on there, so they asked for my help and I started poking around. Unfortunately, I didn't find anything useful in the logs, they were all similar to this:

    [2018-07-27T17:36:34.765Z] "GET /hello HTTP/1.1" 503 UF 0 57 3 - "10.128.0.12" "curl/7.54.0" "d159de85-7442-969c-a440-2806d61da2b3" "35.184.102.78" "10.48.2.10:5000"

In other words, they reflected what I already knew at the client: The system was returning a 503.

So, I moved to other debugging techniques. After a while, I found that if I curled the pod *container* from inside the mesh without the auth header, I’d get the normally expected 401 error. Aha! So the proxy was doing it's job. On the other hand, if I curled the *service* from inside the mesh, I’d get the 503 error. Well, at least now I knew that something was happening between the service and the pod. But what?

After more futzing around and pouring over docs and such, I finally tried changing my auth policy. I added this little gem to policy above and applied it:

  peers:
  - mtls:

And presto! Things started working! Hmm...

So, the intent to add JWT verification actually overrode the ability of the service to work in the mTLS environment. Ouch. That was an unexpected side-effect - there was nothing in my policy that would have indicated that. (On the contrary, it was the omission of this section that caused the service behavior to be overridden contrary to the existing behavior and the rest of the Istio system.)

Anyway, to sum-up my concerns:
1. there are potentially hidden side-effects to the authentication policy
2. if you run into issues, it's difficult to debug as neither the error message nor the logs help

And my desired behavior is:
1. Separate concerns so there aren't side-effects like this
2. Improve errors and/or logging so that if there are reachability issue, it's obvious why

I hope that all makes sense! Thanks!
