### ISSUE TITLE
Gateway ignores SSL certificate updates

### ISSUE THREAD

**Issue by kirgene** [istio/istio#7479]
**Describe the bug**
I have Gateway with domain SSL certificates and configured TLS termination.
When I update SSL certificate using `istio-ingressgateway-certs` secret I see no changes while connecting to server using following command:
```
echo | openssl s_client -showcerts -servername mydomain.com -connect mydomain.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

**Expected behavior**
SSL certificate should be updated accordingly.

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "mydomain.com"
    - "*.mydomain.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "mydomain.com"
    - "*.mydomain.com"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```

**Version**
istio-release-1.0-20180722-02-44
kubernetes v1.10.5

**Is Istio Auth enabled or not?**
Used istio-auth.yaml.
mTLS and sidecar injection are enabled.

**Environment**
GKE 1.10.5-gke.0
