### ISSUE TITLE
Excess VMs/Services outside mesh

### ISSUE THREAD

**Issue by stunn3r** [istio/istio#7493]
**Is your feature request related to a problem? Please describe.**
1. I want to access pods without sidecar in a different namespace, I used following service entry but with no luck:

```
kind: ServiceEntry
metadata:
  name: redis-egress
  namespace: mui-istio
spec:
  hosts:
  - 'redis-sentinel.redis.svc.cluster.local'
  location: MESH_EXTERNAL
  ports:
  - number: 26379
    name: http
    protocol: HTTP
  resolution: DNS

```
2. I tried reaching out to MongoDB VM using serviceentry that too without any success, I used following servieentry config:

```
kind: ServiceEntry
metadata:
  name: external-svc-mongocluster
  namespace: cbp-istio
spec:
  hosts:
  - mymongodb.somedomain # not used
  addresses:
  - 10.207.133.0/25 # VIPs
  ports:
  - number: 27020
    name: mongodb
    protocol: MONGO
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 10.207.133.19
```

I am not sure what am I missing here. Please update the documents if we have to consider things other than this.

**Describe the solution you'd like**

Please let meknow what is the correct way to achieve these two things. I've tried in google groups too with not much success

**Describe alternatives you've considered**
I tried using "global.proxy.includeIPRanges" too but go to know that is deprecated (not updated in docs)

I went and checked config-map of sidecar-injector pod, I found "includeOutboundIpRanges" but not sure how to use this field?

Do we have to update in annotations of "istio-enabled" microservices or we have to update config-map of sidecar soemhow (but how and where ?). I am not using HELM for istio installation so changing HELM parameters is not what I am looking for, I want to make these changes myself in the deployent/config-map yamls anywhere ...

**Additional context**
using istio 0.8 LTS right now in GKE. Used istio-demo.yaml not HELM.
