### ISSUE TITLE
Istio not working with headless service

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#7495]
Hello,

We are using istio with file istio-demo.yaml.
We enabled auth on our service using istio auth policy.

service.yaml:

```
kind: Service
apiVersion: v1
metadata:
  name: service-testing
  namespace: ns-testing
spec:
  selector:
    app: env-t1
  ports:
  - name: ht
    protocol: TCP
    port: 5000
    targetPort: 5000
  clusterIP: None
```

deployment.yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-testing
  namespace: ns-testing
spec:
  replicas: 1
  template:
    metadata:
      name: frontend-test
      labels:
        app: env-t1
        version: v1
        istio: ingressgateway
    spec:
      containers:
      - name: server-testing
        image: xyz/final_servere
```

Issue is, when we tried to access this service using curl from the pod it self using server-testing container it gives the following error:

```
root@deployment-testing-7cdc8db575-fc2lx:/app# curl http://service-testing.ns-testing:5000/
curl: (56) Recv failure: Connection reset by peer
```

But, when we tried to access this service using curl from the pod it self using istio-proxy container it works:

```
istio-proxy@deployment-testing-7cdc8db575-fc2lx:/$ curl https://service-testing.ns-testing:5000/ --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem -k
Hello World - 200 OK
```

We have unique port names across all the services as per this link #5992.

After removing ClusterIP : None will work fine.

But we have to use headless services in some of our deployments.

**Version**
Istio - 0.8
Kubernetes - 10.3
etcd - v3

What are we missing here?

**Comment by ijsnellf** [comment]
Possibly related to https://github.com/istio/istio/issues/7558

**Comment by ronakpandya7** [comment]
Hello @ijsnellf ,
Thanks for your reply 

But i did not find any workaround in the issue #7558 

Can you please help me here?

**Comment by LinAnt** [comment]
I am hitting this as well for an etcd cluster. I think I will try to get it to run by changing to clusterIP unless @ronakpandya7 has found a solution.

**Comment by jordan-da** [comment]
here is a key quote from #7558  
> The problem with headless services is one of scale. Accessing pods directly instead of service VIPs means we need to construct Envoy listeners for all possible pod IPs, which is not a scalable option. So, we resort to using a special passthrough listener in Envoy listening on the headless service port (0.0.0.0:someport) that forwards traffic for these ports to the IP that the client-app resolved by itself (pod IP). This is as low as things go (linux listen() call with INADDR_ANY on some port).

So I have a similar issue, I am running cassandra in k8s in a statefulset with a headless service. What this means is pods will access the cassadra service directly via the pod IP, which istio doesn't know anything about and blocks the connection. If I remove cassandra from the mesh and create a `MESH_EXTERNAL` serviceentry with the pods ip address (you have to for tcp), it seems to work. BUT, one would never know the pods ip address in advance, and these istio objects go in with all the other helm charts.

You know what does know the pods ip address.. DNS. But you are forced to used a static IP. :disappointed:  An easy fix would be just to allow hostnames for tcp services in serviceentrys. Resolve the destination IP and listen for that address for tcp connections on said ports. There must be a good reason you can't do this, but I am not sure.

OR, allow adding statefulsets to the service registry, manually or automatically. Adding all pod ips doesn't scale, of course, but statefulsets are special. Maybe they should be treated like k8s native services.

The workaround is, predetermining your pod/service ip cidrs and using those values in an ip exclusion or tcp serviceentry.

**Comment by dstockton** [comment]
Helm charts that use more complex headless services features will all break with Istio.

Specifically, Kafka & Zookeeper (https://github.com/helm/charts/blob/master/incubator/zookeeper/templates/service-headless.yaml#L15) use the ```${pod name}.${service name}.${namespace}.svc.cluster.local``` naming which makes it even more of an issue - i.e. dropping the ```clusterIP: None``` won't help because the specific pod within the service is referenced.

The DNS resolution works, but instead of being able to contact the remote pod directly an envoy 404 is returned. I couldn't see how a ServiceEntry for that would help but tried anyway (it didn't make any difference).

**Comment by shioteam** [comment]
@dstockton Had the same 404 issue with envoy and headless services. Managed to solve it by creating a [ServiceEntry](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry) record for all the pod hostnames within the headless service. ``

**Comment by geauxvirtual** [comment]
I've also used the above ServiceEntry example along with a headless service for RabbitMQ to cluster the nodes via the pod dns entry for the headless service.

This was tested on Istio 1.0.1, both with and without mutual tls.

**Comment by silencecorner** [comment]
@geauxvirtual i used a ServiceEntry to route emqtt that is in k8s not in sidecar,but not working
```istio
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: emqtt.emqtt
spec:
  hosts:
  - "emqtt.emqtt"
  ports:
  - number: 1883
    name: emqtt
    protocol: tcp
  location: MESH_INTERNAL
  resolution: DNS
```
istio version is 1.0

**Comment by jordan-da** [comment]
@silencecorner 

> For HTTP services, the addresses field will be ignored and the destination will be identified based on the HTTP Host/Authority header. For non-HTTP protocols such as mongo/opaque TCP/even HTTPS, the hosts will be ignored. 

https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-addresses

Need to use the `addresses` field with IP addresses or cidr for tcp stuff

**Comment by silencecorner** [comment]
> @silencecorner
> 
> > For HTTP services, the addresses field will be ignored and the destination will be identified based on the HTTP Host/Authority header. For non-HTTP protocols such as mongo/opaque TCP/even HTTPS, the hosts will be ignored.
> 
> https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-addresses
> 
> Need to use the `addresses` field with IP addresses or cidr for tcp stuff

@jordan-da thx for your kind reply
when i was using both `hosts` and `addresses` , the application used `emqtt.emqtt:1883` would fail to  access server.
 i've fixed by using location `MESH_EXTERNAL`,i guess the reason is the service cluster is in k8s and not inject to  istio mesh. 
 another confusing is that application is failed to connect to emqtt  server at startup, but can pub/sub message from server.
`emqtt` is a pub/sub server that is written for mqtt protocol

i am not a native speaker, sorry!

**Comment by dstockton** [comment]
> I've also used the above ServiceEntry example along with a headless service for RabbitMQ to cluster the nodes via the pod dns entry for the headless service.
> 
> This was tested on Istio 1.0.1, both with and without mutual tls.

@geauxvirtual - would you be able to post sample YAML for your ```Service``` and ```ServiceEntry``` for your non-HTTP (ie RabbitMQ) example please?

**Comment by geauxvirtual** [comment]
@dstockton Ran through my testing to verify the changes I had made to Istio last week. Without mutual TLS, a ServiceEntry allows the RMQ nodes to cluster.  With mutual TLS, just a Policy and DestinationRule entries are required.

Headless Service
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rmq
  labels:
    app: rmq
    type: LoadBalancer
spec:
  type: ClusterIP
  clusterIP: None
  ports:
   - name: epmd
     protocol: TCP
     port: 4369
     targetPort: 4369
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
   - name: http-api
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: inter-node
     protocol: TCP
     port: 25672
     targetPort: 25672
  selector:
    app: rmq
```

ServiceEntry
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rmq
spec:
  hosts:
  - rmq-0.rabbitmq.default.svc.cluster.local
  - rmq-1.rabbitmq.default.svc.cluster.local
  - rmq-2.rabbitmq.default.svc.cluster.local
  ports:
  - number: 4369
    name: epmd
    protocol: TCP
  - number: 5672
    name: amqp
    protocol: TCP
  - number: 15672
    name: http
    protocol: HTTP
  - number: 25672
    name: inter-node
    protocol: TCP
```

For mutual TLS, I created a Policy and a DestinationRule for each node

Policy
```yaml
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: rabbitmq
spec:
  targets:
  - name: rmq-0
  - name: rmq-1
  - name: rmq-2
  peers:
  - mtls: {}
```

DestinationRule (1 of 3)
```yaml
---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: rmq-0
spec:
  host: rmq-0.rabbitmq.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
    portLevelSettings:
    - port:
        number: 5672
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 15672
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 25672
      tls:
        mode: ISTIO_MUTUAL
```

Clearly scaling this is not automatic, though using something like Ansible to add settings for nodes before scaling the replicas would work.

**Comment by dstockton** [comment]
@geauxvirtual Thank you so much for the quick reply. If I understand correctly, these settings will prevent the connection from being encrypted. Is that your understanding too?

**Comment by geauxvirtual** [comment]
@dstockton If you only set the ServiceEntry, then mutual TLS would not be enabled. Mutual TLS requires a Policy and DestinationRule to enable.

**Comment by aminmithil** [comment]
@dstockton I have tried implement zookeeper with headless service and ServiceEntry. I am getting the same problem. Zookeeper pods are not able to communicate with each other. I don't have mutual TLS enabled. If you have tried and work for you can you put your sample yaml file for zookeeper?

**Comment by JansonLiao** [comment]
> here is a key quote from #7558
> 
> > The problem with headless services is one of scale. Accessing pods directly instead of service VIPs means we need to construct Envoy listeners for all possible pod IPs, which is not a scalable option. So, we resort to using a special passthrough listener in Envoy listening on the headless service port (0.0.0.0:someport) that forwards traffic for these ports to the IP that the client-app resolved by itself (pod IP). This is as low as things go (linux listen() call with INADDR_ANY on some port).
> 
> So I have a similar issue, I am running cassandra in k8s in a statefulset with a headless service. What this means is pods will access the cassadra service directly via the pod IP, which istio doesn't know anything about and blocks the connection. If I remove cassandra from the mesh and create a `MESH_EXTERNAL` serviceentry with the pods ip address (you have to for tcp), it seems to work. BUT, one would never know the pods ip address in advance, and these istio objects go in with all the other helm charts.
> 
> You know what does know the pods ip address.. DNS. But you are forced to used a static IP. 😞 An easy fix would be just to allow hostnames for tcp services in serviceentrys. Resolve the destination IP and listen for that address for tcp connections on said ports. There must be a good reason you can't do this, but I am not sure.
> 
> OR, allow adding statefulsets to the service registry, manually or automatically. Adding all pod ips doesn't scale, of course, but statefulsets are special. Maybe they should be treated like k8s native services.
> 
> The workaround is, predetermining your pod/service ip cidrs and using those values in an ip exclusion or tcp serviceentry.
thank you, from your comment, I solved my problem. The real reason why must put pod address ip the serviceEntry, when your service is statefulset service. cause istio do not support statefulset currently, so the istio-proxy can listen the statefulset ip address.

**Comment by arielb135** [comment]
> @dstockton Ran through my testing to verify the changes I had made to Istio last week. Without mutual TLS, a ServiceEntry allows the RMQ nodes to cluster. With mutual TLS, just a Policy and DestinationRule entries are required.
> 
> Headless Service
> 
> ```yaml
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: rmq
>   labels:
>     app: rmq
>     type: LoadBalancer
> spec:
>   type: ClusterIP
>   clusterIP: None
>   ports:
>    - name: epmd
>      protocol: TCP
>      port: 4369
>      targetPort: 4369
>    - name: amqp
>      protocol: TCP
>      port: 5672
>      targetPort: 5672
>    - name: http-api
>      protocol: TCP
>      port: 15672
>      targetPort: 15672
>    - name: inter-node
>      protocol: TCP
>      port: 25672
>      targetPort: 25672
>   selector:
>     app: rmq
> ```
> 
> ServiceEntry
> 
> ```yaml
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: rmq
> spec:
>   hosts:
>   - rmq-0.rabbitmq.default.svc.cluster.local
>   - rmq-1.rabbitmq.default.svc.cluster.local
>   - rmq-2.rabbitmq.default.svc.cluster.local
>   ports:
>   - number: 4369
>     name: epmd
>     protocol: TCP
>   - number: 5672
>     name: amqp
>     protocol: TCP
>   - number: 15672
>     name: http
>     protocol: HTTP
>   - number: 25672
>     name: inter-node
>     protocol: TCP
> ```
> 
> For mutual TLS, I created a Policy and a DestinationRule for each node
> 
> Policy
> 
> ```yaml
> ---
> apiVersion: "authentication.istio.io/v1alpha1"
> kind: Policy
> metadata:
>   name: rabbitmq
> spec:
>   targets:
>   - name: rmq-0
>   - name: rmq-1
>   - name: rmq-2
>   peers:
>   - mtls: {}
> ```
> 
> DestinationRule (1 of 3)
> 
> ```yaml
> ---
> apiVersion: "networking.istio.io/v1alpha3"
> kind: DestinationRule
> metadata:
>   name: rmq-0
> spec:
>   host: rmq-0.rabbitmq.default.svc.cluster.local
>   trafficPolicy:
>     tls:
>       mode: DISABLE
>     portLevelSettings:
>     - port:
>         number: 5672
>       tls:
>         mode: ISTIO_MUTUAL
>     - port:
>         number: 15672
>       tls:
>         mode: ISTIO_MUTUAL
>     - port:
>         number: 25672
>       tls:
>         mode: ISTIO_MUTUAL
> ```
> 
> Clearly scaling this is not automatic, though using something like Ansible to add settings for nodes before scaling the replicas would work.

Hi, i'm trying to implement this - does this mean we disabled MTLS for rabbit itself? what we disabled there?

**Comment by arielb135** [comment]
> @dstockton Ran through my testing to verify the changes I had made to Istio last week. Without mutual TLS, a ServiceEntry allows the RMQ nodes to cluster. With mutual TLS, just a Policy and DestinationRule entries are required.
> 
> Headless Service
> 
> ```yaml
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: rmq
>   labels:
>     app: rmq
>     type: LoadBalancer
> spec:
>   type: ClusterIP
>   clusterIP: None
>   ports:
>    - name: epmd
>      protocol: TCP
>      port: 4369
>      targetPort: 4369
>    - name: amqp
>      protocol: TCP
>      port: 5672
>      targetPort: 5672
>    - name: http-api
>      protocol: TCP
>      port: 15672
>      targetPort: 15672
>    - name: inter-node
>      protocol: TCP
>      port: 25672
>      targetPort: 25672
>   selector:
>     app: rmq
> ```
> 
> ServiceEntry
> 
> ```yaml
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: rmq
> spec:
>   hosts:
>   - rmq-0.rabbitmq.default.svc.cluster.local
>   - rmq-1.rabbitmq.default.svc.cluster.local
>   - rmq-2.rabbitmq.default.svc.cluster.local
>   ports:
>   - number: 4369
>     name: epmd
>     protocol: TCP
>   - number: 5672
>     name: amqp
>     protocol: TCP
>   - number: 15672
>     name: http
>     protocol: HTTP
>   - number: 25672
>     name: inter-node
>     protocol: TCP
> ```
> 
> For mutual TLS, I created a Policy and a DestinationRule for each node
> 
> Policy
> 
> ```yaml
> ---
> apiVersion: "authentication.istio.io/v1alpha1"
> kind: Policy
> metadata:
>   name: rabbitmq
> spec:
>   targets:
>   - name: rmq-0
>   - name: rmq-1
>   - name: rmq-2
>   peers:
>   - mtls: {}
> ```
> 
> DestinationRule (1 of 3)
> 
> ```yaml
> ---
> apiVersion: "networking.istio.io/v1alpha3"
> kind: DestinationRule
> metadata:
>   name: rmq-0
> spec:
>   host: rmq-0.rabbitmq.default.svc.cluster.local
>   trafficPolicy:
>     tls:
>       mode: DISABLE
>     portLevelSettings:
>     - port:
>         number: 5672
>       tls:
>         mode: ISTIO_MUTUAL
>     - port:
>         number: 15672
>       tls:
>         mode: ISTIO_MUTUAL
>     - port:
>         number: 25672
>       tls:
>         mode: ISTIO_MUTUAL
> ```
> 
> Clearly scaling this is not automatic, though using something like Ansible to add settings for nodes before scaling the replicas would work.

Are you sure that this is working?
i've deployed rabbitMQ with the sidecar, the both pods have IP ready:
![image](https://user-images.githubusercontent.com/33662254/55536522-abf33e00-56c2-11e9-8e04-e7bb65daacb8.png)

i've made the same configuration, and i get errors that the host is not found:
![image](https://user-images.githubusercontent.com/33662254/55536565-c0373b00-56c2-11e9-8661-313b4c6f18fa.png)

**Comment by mbanikazemi** [comment]
headless services work Istio as expected. I am going to close this issue.

**Comment by hansel801** [comment]
@mbanikazemi just wondering what version of Istio supports headless services?

**Comment by Sovietaced** [comment]
> headless services work Istio as expected. I am going to close this issue.

What version of istio supports headless services?

**Comment by MTMcGrath** [comment]
our solution for now was moving the service out of the mesh and adding the port ignore annotations to the service. This way we can non-intrusively remove one service from the mesh instead of changing to much for it.
```annotation: traffic.sidecar.istio.io/excludeOutboundPorts: "<port>"```

**Comment by DiveInto** [comment]
for those who might be struggling with Zookeeper setups, this issuer might be helpful: https://github.com/istio/istio/issues/19280#issuecomment-560531079

and the magic line is:

```sh
echo "quorumListenOnAllIPs=true" >> $ZK_CONFIG_FILE
```

in zk config files

**Comment by Shuliyey** [comment]
> @dstockton Ran through my testing to verify the changes I had made to Istio last week. Without mutual TLS, a ServiceEntry allows the RMQ nodes to cluster. With mutual TLS, just a Policy and DestinationRule entries are required.
> 
> Headless Service
> 
> ```yaml
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: rmq
>   labels:
>     app: rmq
>     type: LoadBalancer
> spec:
>   type: ClusterIP
>   clusterIP: None
>   ports:
>    - name: epmd
>      protocol: TCP
>      port: 4369
>      targetPort: 4369
>    - name: amqp
>      protocol: TCP
>      port: 5672
>      targetPort: 5672
>    - name: http-api
>      protocol: TCP
>      port: 15672
>      targetPort: 15672
>    - name: inter-node
>      protocol: TCP
>      port: 25672
>      targetPort: 25672
>   selector:
>     app: rmq
> ```
> 
> ServiceEntry
> 
> ```yaml
> 
> For mutual TLS, I created a Policy and a DestinationRule for each node
> 
> Policy
> 
> ```yaml
> ---
> apiVersion: "authentication.istio.io/v1alpha1"
> kind: Policy
> metadata:
>   name: rabbitmq
> spec:
>   targets:
>   - name: rmq-0
>   - name: rmq-1
>   - name: rmq-2
>   peers:
>   - mtls: {}
> ```
> 
> DestinationRule (1 of 3)
> 
> ```yaml
> ---
> apiVersion: "networking.istio.io/v1alpha3"
> kind: DestinationRule
> metadata:
>   name: rmq-0
> spec:
>   host: rmq-0.rabbitmq.default.svc.cluster.local
>   trafficPolicy:
>     tls:
>       mode: DISABLE
>     portLevelSettings:
>     - port:
>         number: 5672
>       tls:
>         mode: ISTIO_MUTUAL
>     - port:
>         number: 15672
>       tls:
>         mode: ISTIO_MUTUAL
>     - port:
>         number: 25672
>       tls:
>         mode: ISTIO_MUTUAL
> ```
> 
> Clearly scaling this is not automatic, though using something like Ansible to add settings for nodes before scaling the replicas would work.

Hi @geauxvirtual just wonder if this actually works on `HEADLESS` service for `mtls: STRICT`, i tried with `mtls: STRICT` it didn't work, i also found this https://github.com/arielb135/RabbitMQ-with-istio-MTLS#issue-3---headless-service-dns-entry-cannot-participate-in-mtls, it seems to be indicating `mtls: STRICT` doesn't work with `HEADLESS services (service with `CLUSTERIP: NONE`)

**Comment by ievans-anz** [comment]
Hey @Shuliyey
Would the below approach not work for our use case? Note the caveats regarding scaling...
https://medium.com/airy-science/making-istio-work-with-kubernetes-statefulset-and-headless-services-d5725c8efcc9

**Comment by Shuliyey** [comment]
> Hey @Shuliyey
> Would the below approach not work for our use case? Note the caveats regarding scaling...
> https://medium.com/airy-science/making-istio-work-with-kubernetes-statefulset-and-headless-services-d5725c8efcc9

did the article above work for u @ievans-anz ?

**Comment by Sovietaced** [comment]
> did the article above work for u @ievans-anz ? (the article doesn't seem to have `mtls: STRICT` enabled btw)

I believe some regression was fixed at some point after Istio 1.6.5. In order to get it working with mTLS enabled we had to add an explicit destination rule like so...

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: <service>
  namespace: <namespace>
spec:
  host: <service>.<namespace>.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8085
      tls:
        mode: ISTIO_MUTUAL
```

Also, I was able to get the article working a long time ago with a wildcard service entry. I don't think it is necessary in newer versions of Istio though.
