### ISSUE TITLE
External mesh traffic being incorrectly routed since 1.0

### ISSUE THREAD

**Issue by Stono** [istio/istio#7523]
Given the following manifest:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-internet-http
spec:
  hosts:
  - automotivemxin.com
  - www.google-analytics.com
  - google-analytics.com
  - app.joindrover.com
  - graph.microsoft.com
  - login.microsoftonline.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
```

We are seeing:

```
❯ kn logs oauth2-proxy-765878cdc7-c8tdl  master
2018-07-31T11:35:20.563Z at:oauth2-proxy:server:web starting server on port 4180
2018-07-31T11:35:20.572Z at:oauth2-proxy:server:metrics starting metrics server on port 9090
2018-07-31T11:35:20.575Z at:oauth2-proxy:server:metrics metrics server started
Unhandled Rejection!
{ AggregateError:
    RequestError: Hostname/IP doesn't match certificate's altnames: "Host: login.microsoftonline.com. is not in the cert's altnames: DNS:www.automotivemxin.com, DNS:automotivemxin.com"
        at ClientRequest.req.once.err (/usr/local/autotrader/app/node_modules/got/index.js:182:22)
    RequestError: Hostname/IP doesn't match certificate's altnames: "Host: login.microsoftonline.com. is not in the cert's altnames: DNS:www.automotivemxin.com, DNS:automotivemxin.com"
        at ClientRequest.req.once.err (/usr/local/autotrader/app/node_modules/got/index.js:182:22)
    at rejected (/usr/local/autotrader/app/node_modules/p-some/index.js:49:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'AggregateError' }
```

As you can see, requests to login.microsoftonline.com are going to automotivemxin.com!

I've tried separating each host out into its own service entry too, but to no avail.

Nothing in pilot or istio-proxy logs!

**Comment by Stono** [comment]
This was resolved by removing:
```
  location: MESH_EXTERNAL
  resolution: DNS
```

Which seems strange when reading https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry.Location

**Comment by GregHanson** [comment]
@Stono with `resolution: DNS` if no endpoints are provided in the ServiceEntry, the `hosts` field will be used to populate endpoints.  So when routing, it is matching on the `login.microsoftonline.com` host but then going to one of the endpoints from `hosts`.  If no `resolution` is specified, it defaults to `NONE` which is passthrough - meaning envoy will not touch the host resolution from the original request.

**Comment by rshriram** [comment]
@Stono do not use the none resolution. Instead define virtual services for all the services above, for the HTTPS ports. Something like this:

```
virtualservice:
host:
- automotivemxin.com
tls:
 match:
   sni: automotivemxin.com
 route:
 - destination:
      host: automotivemxin.com
      port: 443
```

Do the above for each host where you are using HTTPS/TLS ports. Otherwise, the traffic ends up being treated as opaque TCP and it results in a collision as multiple services are claiming same port 443 without a service VIP
