### ISSUE TITLE
Enable mixer rules for websockets upgrade

### ISSUE THREAD

**Issue by srinandan** [istio/istio#7544]
**Is your feature request related to a problem? Please describe.**
Enable mixer rules to be invoked before upgrading a http connection to websockets.

**Describe the solution you'd like**
Users may want to apply HTTP based policies (apikeys or JWT verification) before a http connection is upgraded to websockets. 

CC:
@kyessenov @rshriram

**Comment by kyessenov** [comment]
Not stale, but not actively being worked on.

**Comment by kyessenov** [comment]
@douglas-reid I haven't done any specific work for this request. I'd expect the following work items:
- modify envoy to support filters for connection upgrades
- integrate mixerfilter into the connection upgrade pipeline
- add a new protocol to mixer protocol attribute for websockets

**Comment by douglas-reid** [comment]
@kyessenov thanks. a quick look seems to imply that filter chains are supported for upgrades (checking latest docs). is it possible that this may (mostly) just work at this point?

**Comment by kyessenov** [comment]
I'm pretty confident that it won't work by itself, since we need to register mixerfilter in the correct place and implement upgrade-specific interfaces in the filter.

**Comment by douglas-reid** [comment]
@kyessenov so, testing with the Tornado app, hitting the service via ingressgateway, I see the following in prometheus:

query: `sum(istio_requests_total{reporter="destination", destination_workload="tornado"}) by (source_workload, destination_workload, response_code)`


```
{destination_workload="tornado",response_code="200",source_workload="istio-ingressgateway"}	16
{destination_workload="tornado",response_code="304",source_workload="istio-ingressgateway"}	16
{destination_workload="tornado",response_code="404",source_workload="istio-ingressgateway"}	42
{destination_workload="tornado",response_code="101",source_workload="istio-ingressgateway"}	27
```

and

query: `sum(istio_request_bytes_sum{destination_app="tornado", reporter="destination"}) by (source_workload)`

```
{source_workload="istio-ingressgateway"}	240
```

I don't know enough about websockets and connection upgrades, but it feels like we are getting *some* telemetry at least.  The `101` response codes seems to track to connection upgrades. I'm not sure about `304`s (or the `404`s).

I'll try now to see if policy can be applied.

**Comment by douglas-reid** [comment]
Totally works for basic Mixer rules!

Added:

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denyall
  namespace: istio-system
spec:
  compiledAdapter: denier
  adapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyrequest
  namespace: istio-system
spec:
 
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: mixerdenysome
  namespace: istio-system
spec:
  match: request.headers["websocket"] == "yes" && destination.workload.name == "tornado"
  actions:
  # handler and instance names default to the rule's namespace.
  - handler: denyall
    instances:
    - denyrequest.checknothing
```

Then, `$ curl -v --header "websocket: yes"  http://35.188.6.141/`:

```bash 
*   Trying 35.188.6.141...
* TCP_NODELAY set
* Connected to 35.188.6.141 (35.188.6.141) port 80 (#0)
> GET / HTTP/1.1
> Host: 35.188.6.141
> User-Agent: curl/7.60.0
> Accept: */*
> websocket: yes
> 
< HTTP/1.1 403 Forbidden
< content-length: 50
< content-type: text/plain
< date: Wed, 09 Jan 2019 23:44:40 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 4
< 
* Connection #0 to host 35.188.6.141 left intact
PERMISSION_DENIED:denyall.istio-system:Not allowed
```

Then: `$ curl http://35.188.6.141/`:

```
<!DOCTYPE html>
<html>
<head>
<title>tornado WebSocket example</title>
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
</head>
<body>
<div class="container">
<h1>tornado WebSocket example</h1>
<hr>
WebSocket status : <span id="message"></span>
<hr>
...
```

So, I think we can mark this as DONE?
