### ISSUE TITLE
Lot of external MESH traffic problems after upgraded to istio 1.0

### ISSUE THREAD

**Issue by seehait** [istio/istio#7581]
**Describe the bug**
- Node.js application connected to amqp outside MESH is unstable. The error log ```Error: Unexpected close``` from amqp is always occur after pod is running for 2-3 minutes, which toggle pod to be restarted.
- Spring Boot connected to RDS outside MESH log this error for some request (10% of request to the same endpoint with the same request body):

```
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No Operations allowed after connection closed.
```

- I'm not sure if both prior problems is something like connection lost after a period of time. Both problems are gone if I disable istio injection.
- I'm using ServiceEntry for the resource outside MESH.

**Expected behavior**
- It should be working fine with istio.

**Version**
cluster istio version: 1.0
cluster kubernetes version: 1.9

**Is Istio Auth enabled or not?**
enabled

**Comment by ijsnellf** [comment]
Would be useful to see your ServiceEntries.

**Comment by seehait** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db
spec:
  hosts:
  - xxxxx.rds.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - number: 3306
    name: mysql
    protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rabbitmq
spec:
  hosts:
  - rabbitmq.xxxx.tld
  location: MESH_EXTERNAL
  ports:
  - number: 5672
    name: rabbitmq
    protocol: TCP
  resolution: NONE
---
```
