### ISSUE TITLE
Cannot using VirtualService with ServiceEntry

### ISSUE THREAD

**Issue by seehait** [istio/istio#7582]
**Describe the bug**
This is my configuration.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceA
spec:
  hosts:
  - serviceA.elb.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviceAVS
spec:
  hosts:
    - www.serviceA.com
  http:
  - route:
      - destination:
          host: serviceA.elb.amazonaws.com
          port: 8080
        weight: 100
---
```

- My DNS resolve www.serviceA.com to serviceA.elb.amazonaws.com correctly, and I can curl serviceA.elb.amazonaws.com successfully inside the istio injected pod.
- The problem is I cannot connect to www.serviceA.com from the same pod. The envoys log is something like ```GET / HTTP/1.1” 404 NR 0 0 0```
- I've looked to envoys config, It contains config about service entry serviceA.elb.amazonaws.com but not contain config about virtual service www.serviceA.com

**Expected behavior**
- Should istio injected pod be able to connect to www.serviceA.com?

**Version**
cluster istio version: 1.0
cluster kubernetes version: 1.9

**Is Istio Auth enabled or not?**
enabled
