### ISSUE TITLE
Creating a DestinationRule but omitting tls defaults to none

### ISSUE THREAD

**Issue by Stono** [istio/istio#7590]
We have the following default meshPolicy:
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
  labels:
{{ include "istio.labels.standard" . | indent 4 }} 
spec:
  peers:
  - mtls: {}
```

Which enables mTLS for all peers.

We added a destinationrule for a service:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
  name: supply-and-demand-service
spec:
  host: app
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
```

This in turn broke mtls:

```
[atcloud@vehicle-metric-service-5b7f659f5c-w9wpv app]$ curl http://app.supply-and-demand-service
upstream connect error or disconnect/reset before headers
```

Adding:
```
    tls:
      mode: MUTUAL
```

Resolved this.   This behaviour seems a little weird, if that value is omitted, surely it should use the global policy rather than defaulting to none

**Comment by Stono** [comment]
OK it didn't, it got pilot stuck in a crash loop https://github.com/istio/istio/issues/7591

**Comment by vadimeisenbergibm** [comment]
Note that you must specify `ISTIO_MUTUAL`, not `MUTUAL`, in this case. See an example in https://github.com/istio/istio/blob/master/samples/bookinfo/networking/destination-rule-all-mtls.yaml.

**Comment by Stono** [comment]
Thanks @vadimeisenbergibm - I've updated this - I do still think if that value is omitted it should fall back to the global policy, not presume NONE

**Comment by frankbu** [comment]
This is actually a very serious issue, since Tasks that apply DRs, like [this one](https://istio.io/docs/tasks/traffic-management/circuit-breaking/) for example, won't work when mTLS is globally enabled, unless we add alternate instructions (for mTLS on/off) everywhere we apply DRs, which would be ugly.

Why is the default not the global setting, if not specified in the DR? The doc doesn't actually say what the default tls mode is if the [TLSSettings](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSSettings) aren't specified, so we should be able to fix this without making a breaking change.

If we can't fix it, we need to update several tasks and add something in the troubleshooting doc about "503 errors immediately after setting DestinationRule".

**Comment by frankbu** [comment]
Checking for `CONFLICT` under `STATUS` is the way to confirm this has happened:
```
$ istioctl authn tls-check httpbin.default.svc.cluster.local
HOST:PORT                                  STATUS       SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
httpbin.default.svc.cluster.local:8000     CONFLICT     mTLS       HTTP       default/         httpbin/default
```

**Comment by rshriram** [comment]
Okay, this is bad docs on our part (fyi @diemtvu ).
The authentication policy applies to server side policies.. i.e. service owner decides whether they will allow ONLY_MTLS or mix of plaintext and mTLS.

the destination policy applies to client-side only. So, yes, you have to set this in two places. 
Now, the actual intent was that you would set the global authentication policy to be a permissive one(allowing both TLS and plain text). This way, you could incrementally rollout mTLS by setting destination rules (applied client side) for each service to use mTLS (i.e. clients start using mTLS one by one).

**Comment by frankbu** [comment]
So I guess the default global authentication policy should be set to permissive (at least in `install/kubernetes/istio-demo-auth.yaml`) or we've got to fix the tasks that are broken when Istio is setup with mTLS enabled.

Either way, I think we need to document this better.

**Comment by diemtvu** [comment]
We have tried to mention destination rules on security side (e.g [Authentication policies](https://istio.io/docs/concepts/security/#authentication-policies) or [tasks](https://istio.io/docs/tasks/security/authn-policy/), but I guess we miss doing so on the networking side.

Any suggestion to make this concept clearer in all places are welcomed.

**Comment by esnible** [comment]
It would be clearer if there was a new TLSSettings.TLSmode "INHERIT" which means to use the mode that would be used if there was no DestinationRule.  This could be optional or we could make it the default and say that defaulting to `DISABLE` was a bug.

To me it feels like a bug that defining
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews.bookinfo.svc.cluster.local
```
causes reviews to start returning 503 when mTLS is enabled.
