### ISSUE TITLE
Pilot high CPU usage since 1.0

### ISSUE THREAD

**Issue by Stono** [istio/istio#7595]
Hey, 
I'm noticing pilot spiking quite a lot, as you can see from the cpu graphs here:

<img width="804" alt="screen shot 2018-08-02 at 14 36 44" src="https://user-images.githubusercontent.com/1486729/43587222-94361dd6-9661-11e8-8d77-f88e8152aaf9.png">

Any idea what could be causing this?

FYI this cluster has:

  - 155 pods
  - 51 services
  - 24 virtualservices 
  - 33 destinationrules

Pilot is configured with: 2vCPU, 2 gig RAM, with a HPA of 2-4 instances, and it regularly goes to 4.  

The plan for these clusters is to be circa 10-15x what they are now, so I'm slightly worried about scale.

**Comment by Stono** [comment]
Hey folks, any chance of an update / thoughts on this?  I need some sort of confidence around scalability as we have some quite aggressive migration targets.

CC. @nmittler

**Comment by nmittler** [comment]
@costinm assigning to you for now as you've been looking at performance.  Feel free to re-assign as necessary.

**Comment by Stono** [comment]
@costinm if I can provide you any further information/logs/etc from our clusters just ask.  If you know of any "quick wins" I can do to lower the pilot load in the interim - please let me know.  FYI i've already disabled lots of logging.

Our istio config is:
```
❯ kis get configmap istio -o yaml
apiVersion: v1
data:
  mesh: |
    ---
    disablePolicyChecks: false
    enableTracing: true
    accessLogFile: "/dev/null"
    mixerCheckServer: istio-policy.istio-system.svc.cluster.local:15004
    mixerReportServer: istio-telemetry.istio-system.svc.cluster.local:15004
    sdsUdsPath: ''
    sdsRefreshDelay: 15s
    defaultConfig:
      connectTimeout: 10s
      configPath: "/etc/istio/proxy"
      binaryPath: "/usr/local/bin/envoy"
      serviceCluster: istio-proxy
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      zipkinAddress: zipkin.istio-system:9411
      statsdUdpAddress: istio-statsd-prom-bridge.istio-system:9125
      controlPlaneAuthPolicy: MUTUAL_TLS
      discoveryAddress: istio-pilot.istio-system:15005
```
