### ISSUE TITLE
ServiceEntry not working as expected

### ISSUE THREAD

**Issue by facundomedica** [istio/istio#7603]
**Describe the bug**
I want to access an external HTTP API and I'm not able to do so. I've setted the ServiceEntry for other domain and it works, but for `darksky.net` or `api.darksky.net` it doesn't. I've tried inside my Go app and with a `curl` in the Alpine Linux. Running the docker image in my machine works OK.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - googleapis.com # this one works
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: darksky
spec:
  hosts:
  - api.darksky.net # this one doesn't
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
```

cURL output:

```
  / # curl -v https://api.darksky.net/forecast/APIKEYREDACTED/-33.3504409,-60.2558157?lang=es&units=si
[1]-  Done(51)                   curl https://api.darksky.net/forecast/APIKEYREDACTED/-33.3504409,-60.2558157?lang=es
/ # *   Trying 52.200.123.152...
* TCP_NODELAY set
* Connected to api.darksky.net (52.200.123.152) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
* successfully set certificate verify locations:
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=www.google.com
*  start date: Jun 19 11:40:49 2018 GMT
*  expire date: Aug 28 11:32:00 2018 GMT
*  subjectAltName does not match api.darksky.net
* SSL: no alternative certificate subject name matches target host name 'api.darksky.net'
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'api.darksky.net'
```

My Go app tells me the same thing:

`2018/08/02 18:07:59 Get https://api.darksky.net/forecast/REDACTEDAPIKEY/-33.3504409,-60.2558157?lang=es&units=si: x509: certificate is valid for www.google.com, not api.darksky.net`

**Expected behavior**
Make the HTTP request without problems.

**Steps to reproduce the bug**
Use the yaml I copied above and have a container make a curl.

**Version**
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux
/amd64"}
```

Istio 1.0.0 installed with the quickstart link in GKE.

**Is Istio Auth enabled or not?**
I think yes (Installed with the quickstart link in GKE)

**Environment**
Google Cloud

**Cluster state**
I'll upload this later if it's necessary

**Comment by facundomedica** [comment]
More info on this: **Changing the position of the service entries gets different results.** And never all of them works. Sometimes `googleapis.com` work and `darksky.net` doesn't and viceversa.

**Comment by jamalsia** [comment]
yes for some reason, istio is caching the previous google certificate for this request instead of using darksky.net one.... weird
```
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=www.google.com
*  start date: Jun 19 11:40:49 2018 GMT
*  expire date: Aug 28 11:32:00 2018 GMT
*  subjectAltName does not match api.darksky.net
* SSL: no alternative certificate subject name matches target host name 'api.darksky.net'
* stopped the pause stream!
* Closing connection 0
```

**Comment by jamalsia** [comment]
you will need to add a virtual service as well
https://istio.io/docs/tasks/traffic-management/egress/#configuring-the-external-services

**Comment by facundomedica** [comment]
I'll try adding a VirtualService, but it's weird that works without it

**Comment by facundomedica** [comment]
I've tried this (deleting the deployment that makes use of it and recreating it afterwards): 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - googleapis.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: darksky
spec:
  hosts:
  - api.darksky.net
  - darksky.net
  ports:
  - number: 443
    name: tls
    protocol: TLS
  - number: 80
    name: http
    protocol: http
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: darksky
spec:
  hosts:
  - api.darksky.net
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.darksky.net
    route:
    - destination:
        host: api.darksky.net
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: googleapis
spec:
  hosts:
  - googleapis.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - googleapis.com
    route:
    - destination:
        host: googleapis.com
        port:
          number: 443
      weight: 100
```

**Comment by facundomedica** [comment]
I kept trying and changed `googleapis.com` to `www.googleapis.com` and worked! I also removed the `VirtualService`s and it still works. Anyway, I leave this issue open because the behavior was quite erratic, so maybe it helps to solve something.

**Comment by ldounis** [comment]
We are facing the same issue here, when we are adding ServiceEntries, we get the TLS certificate of the first host instead of the host we are requesting. Adding VirtualServices has no difference.

**Comment by facundomedica** [comment]
I found that it's maybe timing related. In my app I had an http request that was launched at the beginning, then I added a delay of a couple of seconds and it worked. 🤔

**Comment by dheerajng** [comment]
I faced similar issue. If you have two (or more) ServiceEntries for TLS, then you can not access external service associated with the latest added ServiceEntry. 
For example, if I add ServiceEntries for "Potato" and "Tomato" in that order, I won't be able to access "tomato" service. 
I looked into the envoy config, and found that there is only filter entry (Potato) for listener "0.0.0.0_443". Hence the issue! 
To avoid this issue, one needs to add VirtualServices. Once VirtualService (for Tomato) is added, I can access Tomato service. After adding VirtualServices, a filter chain is updated in the Envoy config.

**Comment by vadimeisenbergibm** [comment]
@facundomedica Do you still experience the issue? If not, can you close it?

@dheerajng Please note that you have to add a VirtualService in addition to a TLS Service Entry. See the comment 
https://github.com/istio/istio/issues/7603#issuecomment-410238090 of @facundomedica. The documentation on istio.io was updated.

**Comment by iliecirciumaru** [comment]
I have encountered same problem. Virtual Service resolved all problems

**Comment by toantc** [comment]
**Describe the bug**
I'm still getting this problem.


```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: myshopify
spec:
  hosts:
  - "*.myshopify.com"
  endpoints:
    - address: myshopify.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myshopify
spec:
  gateways:
  - istio-egressgateway
  hosts:
  - "*.myshopify.com"
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*.myshopify.com"
    route:
    - destination:
        host: "*.myshopify.com"
        port:
          number: 443
      weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: datadog
  namespace: "default"
spec:
  hosts:
  - "*.logs.datadoghq.eu"
  endpoints:
    - address: datadoghq.eu
  ports:
  - number: 10516
    name: http2
    protocol: HTTP2
  resolution: DNS
  location: MESH_EXTERNAL

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: datadog
  namespace: "default"
spec:
  hosts:
  - "*.logs.datadoghq.eu"
  tls:
  - match:
    - port: 10516
      sni_hosts:
      - "*.logs.datadoghq.eu"
    route:
    - destination:
        host: "*.logs.datadoghq.eu"
        port:
          number: 10516
      weight: 100
---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: datadog-agent
  namespace: default
spec:
  hosts:
  - "*.agent.datadoghq.eu"
  endpoints:
    - address: agent.datadoghq.eu
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: datadog-agent
  namespace: default
spec:
  gateways:
  - istio-egressgateway
  hosts:
  - "*.agent.datadoghq.eu"
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*.agent.datadoghq.eu"
    route:
    - destination:
        host: "*.agent.datadoghq.eu"
        port:
          number: 443
      weight: 100

```

CURL output:

```
$ curl -iv https://6-9-0-app.agent.datadoghq.eu
* About to connect() to 6-9-0-app.agent.datadoghq.eu port 443 (#0)
*   Trying 35.190.30.199...
* Connected to 6-9-0-app.agent.datadoghq.eu (35.190.30.199) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=*.myshopify.com,O=Shopify Inc.,L=Ottawa,ST=Ontario,C=CA
*       start date: Sep 27 00:00:00 2017 GMT
*       expire date: Oct 15 12:00:00 2020 GMT
*       common name: *.myshopify.com
*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
* NSS error -12276 (SSL_ERROR_BAD_CERT_DOMAIN)
* Unable to communicate securely with peer: requested domain name does not match the server's certificate.
* Closing connection 0
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

**Expected behavior**
All secure external web services are accessible

**Steps to reproduce the bug**

1. Install istio using `helm install helm install install/kubernetes/helm/istio --name istio --namespace istio-system`
2. Create 3 ServiceEntry with the yaml file above
3. Make a request to the last domain `curl -iv https://6-9-0-app.agent.datadoghq.eu`

**Version**

```
 ❯ bin/istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

```

**Installation**
Istio 1.0.5 installed with Helm. 

1. Download the latest release `curl -L https://git.io/getLatestIstio | sh - `
2. `helm install helm install install/kubernetes/helm/istio --name istio --namespace istio-system`

**Is Istio Auth enabled or not?**
Yes

**Environment**
DigitalOcean Kubernetes

**Cluster state**
I will upload it later if necessary

**Comment by eduardobaitello** [comment]
@toantc Istio is meticulous about using wildcard hosts **and** `resolution: DNS`. Here are some quotes from official docs:

[1.0.3 release notes:](https://istio.io/about/notes/1.0.3/#behavior-changes)

> Service entry no longer allows wildcard (*) DNS resolution. The API has never allowed this, however ServiceEntry was erroneously excluded from validation in the previous release.

[Service Entry:](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry)

> The following example demonstrates the use of wildcards in the hosts for external services. If the connection has to be routed to the IP address requested by the application (i.e. application resolves DNS and attempts to connect to a specific IP), the discovery mode must be set to NONE.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-wildcard-example
spec:
  hosts:
  - "*.bar.com"
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
```

Git it a try by setting `resolution: STATIC`, and see if it works.

_Another [comment](https://stackoverflow.com/questions/52969899/what-are-the-endpoints-of-amazon-s3#comment93054636_52970096) about this._

**Comment by edalford11** [comment]
I've tried every permutation I can think of between service entries and virtual services. I can't for the life of me figure out how to get my app to curl an external third party api. It always results in 
`error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`

**Comment by toantc** [comment]
Thanks. It's working for me with the `resolution: NONE`. Amazing that `resolution: DNS` is still working with for the 1st ServiceEntry.

**Comment by vadimeisenbergibm** [comment]
@edalford11 VirtualService is not required starting from https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-20190214-09-16/. We just updated the task to reflect that https://preliminary.istio.io/docs/tasks/traffic-management/egress/#access-an-external-https-service.

**Comment by edalford11** [comment]
Migrated to 1.1 and was still receiving the same SSL errors.

I ended up setting

```yaml
outboundTrafficPolicy:
    mode: ALLOW_ANY
```

and set `includeIPRanges` to my cluster cidr. This disabled all external traffic filtering and I was finally able to get my apps to call external services.

**Comment by LucaPrete** [comment]
Same issue with Istio 1.22. Not able to find any valuable solution.

Funny thing is that by default traffic flows to external services. It starts to return `curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number` as soon as I add the service entry (which I would need to make traffic go through an egress gateway).

Any thought?

**Comment by greg-caffeine** [comment]
I am hitting what may be a related problem (in Maistra 2.8).  I believe the problem here is that the hosts: field is being ignored, and the first rule found is being applied to all traffic destined for port 443.

In our environment, when we apply a single ServiceEntry rule with a complete (non-wildcard) hostname, we see traffic to any other hostname at the same port get routed out to the hostname given in the ServiceEntry.  That would explain what you're seeing here with the crossed TLS cert if traffic destined for the second ServiceEntry is actually being captured by the first ServiceEntry rule and routed to that destination first.

**Comment by sneko** [comment]
Hi @vadimeisenbergibm ,

I'm using 2 ServiceEntry, each one having a different host but they have in common:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aaaaa
spec:
  hosts:
    - "aaaa.bbbb.org"
  location: MESH_EXTERNAL
  ports:
    - number: 465
      name: tcp
      protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: bbbbb
spec:
  hosts:
    - "xxxx.yyyyy.org"
  location: MESH_EXTERNAL
  ports:
    - number: 465
      name: tcp
      protocol: TCP
  resolution: DNS
```

but as mentioned above, only 1 of the 2 is considered. I faced this kind of error:
```
x509: certificate is valid for XXXXXXX, not YYYYYYY
```

I tried to add specific VirtualService for those (with sniHosts...) but it still does not work (but I saw you mentioned it was no longer required for a few years).

Any idea? It seems I'm not the only one.
