### ISSUE TITLE
Get the IP address of the client

### ISSUE THREAD

**Issue by facundomedica** [istio/istio#7607]
This is a question.

How can I get the client's IP address from inside my container?

I'm printing the requests that arrive to my container:

```
POST /shared/login HTTP/1.1
Host: primeratest.REDACTED.co
Accept-Encoding: gzip
Content-Length: 364
Content-Type: application/x-www-form-urlencoded
User-Agent: okhttp/3.8.1
X-B3-Sampled: 1
X-B3-Spanid: 5dc565d1235a089c
X-B3-Traceid: 5dc565d1235a089c
X-Envoy-Internal: true
X-Forwarded-For: 10.xxx.0.4 // this is an internal IP
X-Forwarded-Proto: https
X-Request-Id: e78ed2dc-9eb8-934b-b311-75e1bce9869
```

I have a gateway and a VirtualService:

```yaml
---
kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "primeratest.redacted.co"
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "primeratest.redacted.co"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
  - "primeratest.redacted.co"
  gateways:
  - api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: api
        port:
          number: 5000
```

**Comment by merlineus** [comment]
Just meet the same issue. 
Found some suggestions for adding "use_remote_address": true to envoy config but can't figure out how to do that...

**Comment by facundomedica** [comment]
I found exactly the same, but I think that that's something internal, I don't now how to access it either

**Comment by ijsnellf** [comment]
cc @rshriram

**Comment by facundomedica** [comment]
One solution could be use Cloudflare as a Proxy, which adds some useful headers and also adds the client's IP to the x-forwarded-for header.

```
POST /shared/signup HTTP/1.1
Host: primeratest.redacted.co
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-us
Cf-Connecting-Ip: XXX.XXX.XXX.XXX // my client's IP address
Cf-Ipcountry: AR
Cf-Ray: 444b6cef4d4d2eab-MIA
Cf-Visitor: {"scheme":"https"}
Content-Length: 245
Content-Type: multipart/form-data; boundary=53B4D475-D9FE-44F3-B8DE-B471B27DD107
External-Ip: testing
Testing: facundo2
User-Agent: CocoaRestClient/23 CFNetwork/901.1 Darwin/17.6.0 (x86_64)
X-B3-Sampled: 1
X-B3-Spanid: 0e298cff6925ccd3
X-B3-Traceid: 0e298cff6925ccd3
X-Envoy-External-Address: 10.128.0.2
X-Forwarded-For: XXX.XXX.XXX.XXX, 10.128.0.2 // being the first one my client's public IP
X-Forwarded-Proto: https
X-Request-Id: b8b4910b-6273-9b9e-868f-a73e1ee29c1d
```

**Comment by merlineus** [comment]
Unfortunately, I can't use Cloudflare

**Comment by swistaczek** [comment]
Is there any solution for this problem?

**Comment by merlineus** [comment]
@swistaczek you can use NLB instead of ELB https://github.com/istio/istio/issues/8337

But there is an issue in K8S if you run several clusters in same AWS region https://github.com/kubernetes/kubernetes/issues/69264

**Comment by facundomedica** [comment]
I've changed the issue's title to make it more clear

**Comment by Dagon-** [comment]
I'm just running into this as well. According to this:
https://github.com/istio/istio/issues/7679
Setting `externalTrafficPolicy: Local` in the ingress-gateway service will cause the real client IP to be passed through. 

That's causing connectivity issues for me though.

**Comment by jonasdkhansen** [comment]
I also have this problem. I have a GKE cluster, and I'm using the istio ingress as loadbalancer from outside, and sending the traffic to a simple nginx pod. But the nginx is getting the internal istio ingress ip, and not the real users ip.

**Comment by jonasdkhansen** [comment]
I got it working with adding externalTrafficPolicy: Local to the istio-ingressgateway service, and then in my nginx conf i added a header with $http_x_forwarded_for :)

**Comment by jaepyoung** [comment]
I have one container of node.js and it is not getting client ip.  I am using EKS. Is there any workaround to fix this issue? externalTrafficPolicy: Local doesn't work for me. Do I need to set up another thing?

**Comment by songrgg** [comment]
Thanks, externalTrafficPolicy: Local works for me, I hosted Kubernetes on Tencent Cloud.

**Comment by psaia** [comment]
Confirmed: `externalTrafficPolicy: Local` works well on GKE + envoy. 👍

**Comment by facundomedica** [comment]
Fixed by setting `externalTrafficPolicy: Local`

**Comment by flunderveiko** [comment]
using an envoyfilter:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-user-ip
  namespace: ingress
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
    - listenerMatch:
        portNumber: 443
        listenerType: ANY
      filterName: envoy.lua
      filterType: HTTP
      filterConfig:
        inlineCode: |
          function envoy_on_request(request_handle)
            local xff_header = request_handle:headers():get("X-Forwarded-For")
            local first_ip = string.gmatch(xff_header, "(%d+.%d+.%d+.%d+)")();
            request_handle:headers():add("X-Custom-User-IP", first_ip);
          end
```

**Comment by dpeper** [comment]
It took a couple of changes for me to get the real user's IP. I am running istio behind an EC2 ELB which injects or appends the x-forwarded-for header. Setting `externalTrafficPolicy: Local` doesn't help since you just see the ELB internal IP and not the client IP.

The first step is to recompile pilot so that it sets use_remote_address=false in Envoy. This stops Envoy from inserting its IP into the x-forwarded-for chain. 

Secondly I used the above EnvoyFilter with a small modification to get the most righthand IP. This is needed because the client could spoof x-forwarded-for (so then the above would obtain the incorrect lefthand IP).

`
          function envoy_on_request(request_handle)
            local xff_header = request_handle:headers():get("X-Forwarded-For");
            local client_ip
            for ip in  string.gmatch (xff_header, "(%d+.%d+.%d+.%d+)") do
                client_ip = ip
            end
            request_handle:headers():add("x-client-ip", client_ip);
          end
`

The real user's IP is then in the header x-client-ip and this works for IP filtering.

If I am missing an easier way to do this please let me know!

**Comment by springrain** [comment]
Can I only use envoyFilter at the moment?

**Comment by Stolr** [comment]
@dpeper  Having the same issue :/ 

The X forwarder for ip contains the ip of the node where the istio gateway pods runs. I am on bare metal cluster.


How did you recompile pilot ? Can you give me a procedure for this ?

Regards

**Comment by dpeper** [comment]
@Stolr First download the istio repo and put it in ~/go/src/istio.io/istio. Then checkout the tag of the version you'd like to run (e.g. 1.1.2).

I used some of the changes provided by @julianvmodesto in this PR https://github.com/istio/api/pull/897 

This is the diff of the change:

```diff --git a/pilot/pkg/networking/core/v1alpha3/gateway.go b/pilot/pkg/networking/core/v1alpha3/gateway.go
index 41000ea80..9c3721e5d 100644
--- a/pilot/pkg/networking/core/v1alpha3/gateway.go
+++ b/pilot/pkg/networking/core/v1alpha3/gateway.go
@@ -339,7 +339,7 @@ func (configgen *ConfigGeneratorImpl) createGatewayHTTPFilterChainOpts(
                        tlsContext: nil,
                        httpOpts: &httpListenerOpts{
                                rds:              routeName,
-                               useRemoteAddress: true,
+                               useRemoteAddress: false,
                                direction:        http_conn.EGRESS, // viewed as from gateway to internal
                                connectionManager: &http_conn.HttpConnectionManager{
                                        // Forward client cert if connection is mTLS
@@ -372,7 +372,7 @@ func (configgen *ConfigGeneratorImpl) createGatewayHTTPFilterChainOpts(
                tlsContext: buildGatewayListenerTLSContext(server, enableIngressSdsAgent),
                httpOpts: &httpListenerOpts{
                        rds:              routeName,
-                       useRemoteAddress: true,
+                       useRemoteAddress: false,
                        direction:        http_conn.EGRESS, // viewed as from gateway to internal
                        connectionManager: &http_conn.HttpConnectionManager{
                                // Forward client cert if connection is mTLS```

Then build and create the docker image like this:
`export GOOS=linux; make docker.pilot`

Then tag it, push it somewhere and update the istio-pilot deployment in istio-system to use your new image.

**Comment by Stolr** [comment]
Thanks !

**Comment by sidhlipu** [comment]
Hello,
May be a lame question since I am trying for the first time, tried recompiling but facing this issue.

export GOOS=linux; make docker.pilot
If you suffer an unexpected failure, please reference: https://github.com/istio/istio/wiki/Troubleshooting-Development-Environment
Building with the build container: gcr.io/istio-testing/build-tools:master-2020-02-14T13-09-14.
Using docker credential directory /root/.docker.
cp: cannot access '/config/.docker': Permission denied
make: Makefile.core.mk: Permission denied
make: stat: Makefile.core.mk: Permission denied
make: *** No rule to make target 'Makefile.core.mk'.  Stop.
make: *** [docker.pilot] Error 2
[root@daas-devops-docker-slave-node1 istio]# ls docker/

**Comment by vincentDAO** [comment]
I'm using istio 1.5 with AKS and below solution is work for me:

Step 1. externalTrafficPolicy: Local
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    chart: gateways
    heritage: Tiller
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  clusterIP: 10.0.133.19
  externalTrafficPolicy: Local`
`

Step 2. EnvoyFilter thank to **@dpeper**
`
function envoy_on_request(request_handle)
            local xff_header = request_handle:headers():get("X-Forwarded-For");
            local client_ip
            for ip in  string.gmatch (xff_header, "(%d+.%d+.%d+.%d+)") do
                client_ip = ip
            end
            request_handle:headers():add("x-client-ip", client_ip);
          end
`

Step 3: custom the code ( to use x-client-ip instead of X-Forwarded-For)

**Comment by sumantfordev** [comment]
The solutions listed works for http traffic, how can this be handled on TCP type. Seems envoy has support for this https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/ip_transparency
Can this be configured in istio?

**Comment by cameronbraid** [comment]
`externalTrafficPolicy: Local` doesn't work if you also have `type: ClusterIP` since you get the error `Invalid value: "Local": ExternalTrafficPolicy can only be set on NodePort and LoadBalancer service`

So there needs to be a soloution for when using ClusterIP

**Comment by nigeltiany** [comment]
What about IPV6 ```(xff_header, "(%d+.%d+.%d+.%d+)")```?

**Comment by VRanga000** [comment]
> I have one container of node.js and it is not getting client ip. I am using EKS. Is there any workaround to fix this issue? externalTrafficPolicy: Local doesn't work for me. Do I need to set up another thing?

I am also using Istio (1.5.1) in EKS (1.15.11). Just like @jaepyoung, setting `externalTrafficPolicy: Local` in the Istio svc gateway does not set the client ip to the external IP. 
```
➜  thorxre_alb_istio git:(master) ✗ curl sni-test-eks.x1.xcal.tv/headers
{
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "sni-test-eks.x1.xcal.tv", 
    "User-Agent": "curl/7.58.0", 
    "X-B3-Parentspanid": "ccf5a66cd112cd73", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "cad10b58c7dc164f", 
    "X-B3-Traceid": "8500ffcc0f3b4870ccf5a66cd112cd73", 
    "X-Envoy-External-Address": "96.99.172.68", 
    "X-Forwarded-Client-Cert": "xxx"
  }
}
````

Per the [kubernetes documentation, that feature is supported in GKE](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip). Anyone having success getting this to work in EKS? Or is there support in Istio to set the X-Forwarded-For header ?

**Comment by Arpeet-gupta** [comment]
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/

**Comment by brackendawson** [comment]
> What about IPV6 `(xff_header, "(%d+.%d+.%d+.%d+)")`?

I'm using:
```
function envoy_on_request(request_handle)
  local IP
  for x in string.gmatch(request_handle:headers():get("x-forwarded-for"), "([^,]+)") do
    ip = x
  end
  request_handle:headers():replace("x-real-ip", ip)
end
```

**Comment by abdidarmawan007** [comment]
set externalTrafficPolicy: Local in service istio-ingressgateway fix my problem, now i can get client ip public in my logs app, but its make our service downtime for a moment

**Comment by guiguan** [comment]
I can confirm that `externalTrafficPolicy: Local` works in Istio 1.7:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            externalTrafficPolicy: Local
```

But after making the change, you need to manually restart the ingress gateway for it to take effect

**Comment by yuliyantsvetkov** [comment]
Confirmed that it works with EKS, NLB and Istio 1.31.1:

```
service:
  # Type of service. Set to "None" to disable the service entirely
  type: LoadBalancer
  ports:
    ## You can add custom gateway ports
    # Note that AWS ELB will by default perform health checks on the first port
    # on this list. Setting this to the health check port will ensure that health
    # checks always work. https://github.com/istio/istio/issues/12503
  - port: 15020
    targetPort: 15020
    name: status-port
  - port: 80
    targetPort: 80
    name: http2
    nodePort: 31380
  - port: 443
    name: https
    nodePort: 31390
  annotations: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Local
  ```

**Comment by Blitss** [comment]
In case anyone is looking for a solution on how to populate `x-real-ip` header with real client IP address and avoid getting tampered `x-forwarded-for` headers by the client, here's the complete solution which works for me with GKE load balancer.

First, patch the load balancer:
`kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'`

Then apply the envoy filter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: set-remote-address-and-hops
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            use_remote_address: true
            xff_num_trusted_hops: 1
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-x-real-ip-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                request_handle:headers():replace("x-real-ip", request_handle:headers():get("x-envoy-external-address"))
              end
```
I tried to use `downstreamDirectRemoteAddress` instead of `x-envoy-external-address` but that doesn't work in case client passes malformed `x-forwarded-for` header.
