### ISSUE TITLE
1.0 Soft multi-tenancy support

### ISSUE THREAD

**Issue by jaredeis** [istio/istio#7608]
**Describe the bug**
We have been trying to follow https://istio.io/blog/2018/soft-multitenancy/ with 2 installs of istio on the same EKS cluster. We are using two separate namespaces for each istio install. When we deploy the bookinfo app (just into the default namespace) it depolys fine, the pod comes up, and all services are created, but we cannot reach the bookinfo productpage.

**Expected behavior**
If soft multi-tenancy is still supported since this blog was written, it should work as the blog describes, or updated documentation should be created to help users deploy istio in this manner. If it's not supported, then this becomes a feature request.

**Steps to reproduce the bug**
Deploy istio into istio-system-a.
Deploy istio isto istio-system-b.
Depoly bookinfo app (manual sidecar injection) with the `-i istio-system-a` flag to point to that install of istio.
Test the endpoint for productpage and observe no response from the app.

**Version**
istio 1.0, EKS K8s version 1.10.3.

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

**Environment**
EKS AWS

**Cluster state**
If this is needed I can provide later. I don't know what test cluster my colleague was using so I can't create the file until I speak to him tomorrow.

**Comment by sporokh** [comment]
I'd say that this functionality is broken. I've tried to deploy `istio` to another namespace so I generated a yaml from helm with this block:
```
helm template $istio_path/install/kubernetes/helm/istio \
     --name istio \
     --namespace TEST \    <------ NEW NAMESPACE
     --set sidecarInjectorWebhook.enabled=false,galley.enabled=false,servicegraph.enabled=false,prometheus.enabled=false,grafana.enabled=false,global.mtls.enabled=true \
     > ./istio-install.yaml
```

And still see this in the istio-egressgateway configuration:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-egressgateway
  namespace: istio-system-blue
  labels:
    app: egressgateway
    chart: gateways-1.0.0
    release: istio
    heritage: Tiller
    app: istio-egressgateway
    istio: egressgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-egressgateway
        istio: egressgateway
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: istio-egressgateway-service-account
      containers:
        - name: egressgateway
          image: "201777367430.dkr.ecr.us-east-1.amazonaws.com/platform/istio/components/proxyv2:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
          args:
          - proxy
          - router
          - -v
          - "2"
          - --discoveryRefreshDelay
          - '1s' #discoveryRefreshDelay
          - --drainDuration
          - '45s' #drainDuration
          - --parentShutdownDuration
          - '1m0s' #parentShutdownDuration
          - --connectTimeout
          - '10s' #connectTimeout
          - --serviceCluster
          - istio-egressgateway
          - --zipkinAddress
          - zipkin:9411
          - --statsdUdpAddress
          - istio-statsd-prom-bridge:9125
          - --proxyAdminPort
          - "15000"
          - --controlPlaneAuthPolicy
          - NONE
          - --discoveryAddress
          - istio-pilot.istio-system:8080     <----------- LOOK HERE
          resources:
            requests:
              cpu: 10m
```
Which is definitely wrong...
