### ISSUE TITLE
service entry for mysql jdbc

### ISSUE THREAD

**Issue by hpcsc** [istio/istio#7617]
**Describe the bug**
My application is using [flyway](https://flywaydb.org/) for db migration. Flyway is running in a separate pod from our application. The application is written in nodejs and uses sequelize to connect to database (mysql)

Kubernetes is deployed using kops to AWS. MySQL is an instance of AWS RDS

When I define the service entry like following:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rds-service-entry
spec:
  hosts:
  - my-app.xxx.ap-southeast-1.rds.amazonaws.com
  ports:
  - number: 3306
    protocol: tcp
  location: MESH_EXTERNAL
```

My application is able to connect to db but flyway is not (error: `Unable to obtain connection from database (jdbc:mysql://my-app.xxx.ap-southeast-1.rds.amazonaws.com)`)

I suspect the issue is due to the protocol used by flyway is jdbc, so i try to put `jdbc`, `jdbc:mysql` in service entry definition but none works. Adding `addresses` which is the IP of RDS instance also not helping

**Expected behavior**
Able to connect to db from both application and flyway

**Steps to reproduce the bug**
As mentioned above

**Version**

Istio:
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

kubectl:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**

Installed istio using helm chart:

```
helm install install/kubernetes/helm/istio --set global.proxy.includeIPRanges="172.16.32.0/19\,172.16.64.0/19" --set grafana.enabled=true --name istio --namespace istio-system
```
The 2 IP ranges are subnet ip ranges where kubernetes is deployed

**Environment**

AWS
