### ISSUE TITLE
wildcard match in virtual services

### ISSUE THREAD

**Issue by dunjut** [istio/istio#7618]
**Describe the bug**
We want to create one Gateway to serve all l7 traffic, port 80 for http traffic and port 443 for https with SNI.

Now when testing with http traffic, we've created a Gateway like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dastan-gateway
  namespace: dastan
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

Then a virtual service is created like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-service
  namespace: dastan
spec:
  hosts:
    - "foo.com"
    - "*.bar.com"
  gateways:
    - dastan-gateway
  http:
  - match:
    - authority:
        exact: "foo.com"
    route:
    - destination:
        host: test-service
        port:
          number: 10001
  - match:
    - authority:
        regex: "*.bar.com"
    route:
    - destination:
        host: test-service2
        port:
          number: 10001
```

We expect requests of foo.com go to test-service1, and requests of *.bar.com go to test-service2, but it fails.

Am I misconfiguring something or this way itself is not best practice?

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

auth not enabled.

**Environment**
Which environment, cloud vendor, OS, etc are you using?

Kubernetes bare-metal installation under ubuntu 16.04.

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.
