### ISSUE TITLE
the host in grpc request's header has port, but the port in virtualservice hosts are not allowed

### ISSUE THREAD

**Issue by wjwinner** [istio/istio#7620]
**Describe the bug**
the logs of  ignressgateway :

```bash
[2018-08-03T08:29:23.116Z] "POST /server.echo/Echo HTTP/2" 200 NR 5 0 2 - "10.215.96.207" "grpc-go/1.14.0" "6074974f-1e63-9a07-99ee-0d56277c1a97" "demo.test.com:80" "-"
```
the host header is ```demo.test.com:80```

```yaml
spec:
  gateways:
  - gateway.default.svc.cluster.local
  hosts:
  - demo.test.com
  http:
  - match:
    - uri:
        regex: /server.*
    route:
    - destination:
        host: demo-echo-deploy.medusa.svc.cluster.local
        port:
          number: 8081
  - route:
    - destination:
        host: demo-echo-deploy.medusa.svc.cluster.local
        port:
          number: 8080
```
I could not change the hosts to demo.test.com:80

**Expected behavior**

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
istio1.0.0

**Is Istio Auth enabled or not?**
no

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.
