### ISSUE TITLE
Multitenant support breaks with non-cluster scoped roles

### ISSUE THREAD

**Issue by rezie** [istio/istio#7646]
**Describe the bug**
I'm trying to follow the multi-tenancy [blog post](https://istio.io/blog/2018/soft-multitenancy) to deploy an instance of Istio into a single namespace. The post seems to imply that a single control plane and mesh namespace is possible, by ensuring that objects are scoped to a particular tenant's namespace. One of the steps in doing that is converting the ClusterRoles/ClusterRoleBindings (for example, in the istio-demo-auth.yaml scripts) into namespace-scoped resources instead. However, it seems that various Istio components assumes the existence of cluster-scoped Roles, such as Istio Citadel. Without it being given a ClusterRole, on startup it will output errors such as:

```
error	istio.io/istio/security/pkg/pki/ca/controller/secret.go:167: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:istio1:istio-citadel-service-account" cannot list secrets at the cluster scope: User "system:serviceaccount:istio1:istio-citadel-service-account" cannot list all secrets in the cluster
```

This results in secrets that other Istio components (e.g. ingress-gateway) rely on not being created, leading to errors such as:

https://github.com/istio/istio/issues/6499

I realize that multi-tenancy support is still in its infancy (and that blog post was written before 1.0 was released), but I was wondering if there was an assumption made that ClusterRoles *are* indeed required?

**Version**
Istio 1.0 with OpenShift 3.9

**Comment by vadimeisenbergibm** [comment]
cc @rshriram @ZackButcher @costinm

**Comment by rezie** [comment]
The blog post has a snippet that shows the running pods e.g.:

```
$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                       READY     STATUS    RESTARTS   AGE
istio-system    istio-ca-ffbb75c6f-98w6x                   1/1       Running   0          15d
istio-system    istio-ingress-68d65fc5c6-dnvfl             1/1       Running   0          15d
istio-system    istio-mixer-5b9f8dffb5-8875r               3/3       Running   0          15d
istio-system    istio-pilot-678fc976c8-b8tv6               2/2       Running   0          15d
```

Note the omission of components such as Istio Citadel. And given that the post was made in April, I also considered that it had used an older version of Istio so I also tested this using version 0.7.1. In this case, it is the Istio Pilot container that seems to trigger errors due to missing ClusterRoles:

```

error	failed to create discovery service: failed to register custom resources. customresourcedefinitions.apiextensions.k8s.io is forbidden: 
User "system:serviceaccount:istio1:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: 
User "system:serviceaccount:istio1:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope
Error: failed to create discovery service: failed to register custom resources. customresourcedefinitions.apiextensions.k8s.io is forbidden: 
User "system:serviceaccount:istio1:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: 
User "system:serviceaccount:istio1:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope
```

**Comment by rezie** [comment]
Additional findings:

I can get around the Citadel issues by using the `--listened-namespace` flag to specify a single namespace which seems to effectively solve the problem of missing Secrets as well as the errors regarding ClusterRoles. However, the `--appNamespace` flag for Pilot doesn't seem to work the same way.

**Comment by rezie** [comment]
Think I managed to get v1.0.0 working with the following ClusterRole for Pilot:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-pilot
  labels:
    app: istio-pilot
    chart: pilot-1.0.0
    heritage: Tiller
    release: RELEASE-NAME
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["rbac.istio.io"]
  resources: ["rbacconfigs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["authentication.istio.io"]
  resources: ["meshpolicies"]
  verbs: ["get", "watch", "list"]  
```

These seem to be around the minimum list of ClusterRoles needed before I could get the helloworld app working. I say "around" because I didn't verify if all three get/watch/list verbs were necessary for those resources, but most of those are certainly necessary during my testing.

**Comment by monkeymorgan** [comment]
I'm going through a similar process with istio 1.1.0-snapshot.5 and have found that you can configure pilot to use just Roles as opposed to ClusterRoles if you 
a) set --appNamespace to the workload namespace (it can't be a separate namespace unfortunately since otherwise pilot won't discover the policy cluster and reports/checks from envoy proxies will fail) 
b) add a Role for the tenant and for the control plane (mainly to illuminate the different domain since due to 'a' these have to be the same namespace)

I added a .Values.global.tenant variable (again, hoping for 'a' to be addressed in time) and updated the Roles template to : 

```
{{- if .Values.global.oneNamespace }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: istio-pilot-tenant-{{ .Values.global.tenant }}
  namespace: {{ .Values.global.tenant }}
  labels:
    app: {{ template "pilot.name" . }}
    chart: {{ template "pilot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: ["config.istio.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.istio.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["authentication.istio.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["endpoints", "pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: istio-pilot-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pilot.name" . }}
    chart: {{ template "pilot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints", "pods", "services"]
  verbs: ["get", "list", "watch"]
{{- else }}
... <the existing ClusterRole>
{{- end }}
```

and added matching Rolebindings
