### ISSUE TITLE
examples on gRPC-JSON transcode needed

### ISSUE THREAD

**Issue by begoat** [istio/istio#7652]
I try to set up proxy for my gRPC service using istio, but i cannot find enough cules. Could you please give an example on how to do that? 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: backend-grpc
spec:
  workloadLabels:
    app: backend
  filters:
  - listenerMatch:
      portNumber: 9090
    filterName: backend-grpc-transcode
    filterType: HTTP
    filterConfig:
```

how to fill the filterConfig field ? If the server is on 50051 port and exposed in istio-ingressgateway via 9090 port, how to config it?

**Comment by jon-whit** [comment]
Would also like some clarification on this one...

**Comment by begoat** [comment]
@rshriram could u please give us more clues about it?

**Comment by begoat** [comment]
@mukundha cool, bro. though we finally gave up using istio as a solution, thank you anyway

**Comment by tiggerlee2** [comment]
@begoat 
There are two ways: 
## Use k8s configmap

1. Create configmap from descriptor set

    ```
    kubectl create configmap proto-descriptor --from-file=proto.pb
   ```
2. Add annotations to your Deployment spec
    
    ```
    sidecar.istio.io/userVolume: '[{"name":"descriptor","configMap":{"name":"proto-descriptor","items":[{"key":"proto.pb","path":"proto.pb"}]}}]'
    sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
    ```
    
    
3. Create EnvoyFilter for service
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: backend-grpc
spec:
  filters:
    - filterConfig:
        print_options:
          add_whitespace: true
          always_print_enums_as_ints: false
          always_print_primitive_fields: true
          preserve_proto_field_names: false
        proto_descriptor: /etc/envoy/proto.pb
        services:
          - BackendSerivce # Service name defined in proto
      filterName: envoy.grpc_json_transcoder
      filterType: HTTP
      listenerMatch:
        portNumber: 9090
  workloadLabels:
    app: backend

```

## Build custom proxy image from istio/proxyv2

1. Build your custom proxy image

```
FROM istio/proxyv2
COPY proto.pb /etc/envoy
```

2. Add annotation to your deployment

 ```
sidecar.istio.io/proxyImage: customeProxyImage
 ```
3. Create Envoyfilter for service

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: backend-grpc
spec:
  filters:
    - filterConfig:
        print_options:
          add_whitespace: true
          always_print_enums_as_ints: false
          always_print_primitive_fields: true
          preserve_proto_field_names: false
        proto_descriptor: /etc/envoy/proto.pb
        services:
          - BackendSerivce # Service name defined in proto
      filterName: envoy.grpc_json_transcoder
      filterType: HTTP
      listenerMatch:
        portNumber: 9090
  workloadLabels:
    app: backend

```

**Comment by tiggerlee2** [comment]
istio >= 1.5.2 && istio-cni >= 1.5.2

```
apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    name: backend-grpc
  spec:
    configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
          portNumber: 15006 # PROXY_INBOUND_CAPTURE_PORT
      patch:
        operation: INSERT_BEFORE
        value:
          config:
            print_options:
              add_whitespace: true
              always_print_enums_as_ints: false
              always_print_primitive_fields: true
              preserve_proto_field_names: false
            proto_descriptor: /etc/envoy/proto.pb
            services:
            - BackendSerivce # Service name defined in proto
          name: envoy.grpc_json_transcoder
    workloadSelector:
      labels:
        app: backend
```

**Comment by shaneqld** [comment]
Thought I'd chime in here with an updated example.

istio >= 1.9.0

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: myapp-grpc-transcoder
spec:
  workloadSelector:
    labels:
      app: myapp # match your deployment
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 50051 # application port
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.grpc_json_transcoder
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          services:
          - mycompany.myapi.v1.MyService # your gRPC service
          print_options:
            add_whitespace: true
            always_print_enums_as_ints: false
            always_print_primitive_fields: true
            preserve_proto_field_names: false
          convert_grpc_status: true
          proto_descriptor_bin: # base64 encoded proto descriptor
```

**Comment by shuoyang2016** [comment]
Question: I ran into an issue that my proto descriptor is around 1.7MB and is larger than 1MB which is claimed by etcd limit. So I cannot use configmap or embedded base64 encode into EnvoyFilter CRD. Any other suggestions than the custom build image? Maybe mount a persistent volume or something else?

**Comment by juchaosong** [comment]
> Question: I ran into an issue that my proto descriptor is around 1.7MB and is larger than 1MB which is claimed by etcd limit. So I cannot use configmap or embedded base64 encode into EnvoyFilter CRD. Any other suggestions than the custom build image? Maybe mount a persistent volume or something else?

Can you split one envoy filter into multiple?

**Comment by npuichigo** [comment]
> Thought I'd chime in here with an updated example.
> 
> istio >= 1.9.0
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: myapp-grpc-transcoder
> spec:
>   workloadSelector:
>     labels:
>       app: myapp # match your deployment
>   configPatches:
>   - applyTo: HTTP_FILTER
>     match:
>       context: SIDECAR_INBOUND
>       listener:
>         filterChain:
>           filter:
>             name: envoy.filters.network.http_connection_manager
>             subFilter:
>               name: envoy.filters.http.router
>         portNumber: 50051 # application port
>     patch:
>       operation: INSERT_BEFORE
>       value:
>         name: envoy.filters.http.grpc_json_transcoder
>         typed_config:
>           "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
>           services:
>           - mycompany.myapi.v1.MyService # your gRPC service
>           print_options:
>             add_whitespace: true
>             always_print_enums_as_ints: false
>             always_print_primitive_fields: true
>             preserve_proto_field_names: false
>           convert_grpc_status: true
>           proto_descriptor_bin: # base64 encoded proto descriptor
> ```

Could u kindly provide any full example?

**Comment by loeffel-io** [comment]
Hey, 

i am using istio v1.17 and this results in `415: grpc-message: invalid gRPC request content-type "application/json"`. Logs are looking clean - any idea? 🙏 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: %{service}-grpc-json-transcoder
spec:
  workloadSelector:
    labels:
      app: %{service}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
          portNumber: 3000
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_json_transcoder
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
            proto_descriptor: "/etc/mindful/earth/customer/v1/customer_v1_proto-descriptor-set.proto.bin"
            services: [ "mindful.earth.customer.v1.CustomerService" ]
            print_options:
              add_whitespace: true
              always_print_enums_as_ints: true
              always_print_primitive_fields: true
              preserve_proto_field_names: false
            convert_grpc_status: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %{service}
spec:
  replicas: 1
  strategy:
    type: %{strategy}
  selector:
    matchLabels:
      app: %{service}
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyMemory: "100Mi"
        sidecar.istio.io/proxyCPU: "50m"
        sidecar.istio.io/userVolume: '[{"name": "customer-v1-proto-grpc-json-transcoder", "configMap": {"name": "%{service}-customer-v1-proto-grpc-json-transcoder"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name": "customer-v1-proto-grpc-json-transcoder", "mountPath": "/etc/mindful/earth/customer/v1"}]'
      labels:
        app: %{service}
    spec:
      serviceAccountName: %{serviceAccount}
      containers:
        - name: %{service}
          image: %{image}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: 'UTC'
            - name: LOGGER_DEVELOPMENT
              value: "%{loggerDevelopment}"
            - name: IMAGE
              value: %{image}
            - name: GRPC_PORT
              value: '3000'
            - name: SECRET_MANAGER_STRIPE_SECRET_KEY
              value: %{secretManagerStripeSecretKey}
            - name: STRIPE_PAYMENT_METHODS
              value: %{stripePaymentMethods}
            - name: STRIPE_TRIAL_DAYS
              value: "%{stripeTrialDays}"
            - name: STRIPE_BILLING_PORTAL_SESSION_CONFIGURATION
              value: %{stripeBillingPortalSessionConfiguration}
            - name: EARTH_USER_SERVICE_ADDR
              value: %{earthUserServiceAddr}
          livenessProbe:
            grpc:
              port: 3000
            initialDelaySeconds: 10
          readinessProbe:
            grpc:
              port: 3000
            initialDelaySeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: 100Mi
              ephemeral-storage: 32Mi
              cpu: 50m
            limits:
              memory: 100Mi
              ephemeral-storage: 32Mi
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: %{service}
spec:
  type: ClusterIP
  selector:
    app: %{service}
  ports:
    - name: grpc-web
      port: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: %{service}
  labels:
    app: %{service}
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: %{service}
```
