### ISSUE TITLE
External Services example not working

### ISSUE THREAD

**Issue by owenhaynes** [istio/istio#7659]
**Describe the bug**
Trying to run the external service example from the docs
https://istio.io/docs/tasks/traffic-management/egress/#configuring-istio-external-services

When curling google from inside of the sleep container get the following reponse

```
* Rebuilt URL to: https://www.google.com/
* Hostname was NOT found in DNS cache
*   Trying 74.125.206.103...
* Connected to www.google.com (74.125.206.103) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Closing connection 0
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Expected behavior**
See the out curl output of https://www.google.com
**Steps to reproduce the bug**
Follow steps in https://istio.io/docs/tasks/traffic-management/egress/#configuring-istio-external-services

**Version**
Kubernetes version v1.10.5-gke.3
Istio version 1.0.0

**Is Istio Auth enabled or not?**
mTLS disabled

**Environment**
GKE

**Cluster state**
Stable

**Comment by owenhaynes** [comment]
Yes working on a new cluster 
1. helm template install/kubernetes/helm/istio --name istio --namespace istio-system     --set global.mtls.enabled=false     --set global.proxy.autoInject=disabled > istio.yaml
2. kubectl create -f istio.yaml
3. kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml)
4. export SOURCE_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
5.  create rules etc
6. kubectl exec -it $SOURCE_POD -c sleep bash
7. curl https://www.google.com

So going to investigate a bit more on old cluster.

**Comment by owenhaynes** [comment]
Still can not find out what is different from the new cluster vs the old cluster.  Is there any debug command to help with diagnostics?

**Comment by vadimeisenbergibm** [comment]
You may want to run:

```
istioctl proxy-config listeners <your pod> -o json
istioctl proxy-config clusters <your pod> -o json
```

and see the differences.

**Comment by owenhaynes** [comment]
Old cluster has this listeners set
0.0.0.0           443       HTTP
this looks wrong as its on new cluster
0.0.0.0          443       TCP

No idea where istio is finding this.

**Comment by vadimeisenbergibm** [comment]
See https://istio.io/docs/setup/kubernetes/spec-requirements/. Istio infers the protocols from the names of the ports.

**Comment by owenhaynes** [comment]
after a big more digging the old cluster seems to use a envoy.http_connection_manager for a filter and the new cluster uses a mixer.

**Comment by owenhaynes** [comment]
Managed to fix it after reading istio-pilot discover logs i found the following error:

```
 "pilot_conflict_outbound_listener_http_over_current_tcp": {
            "0.0.0.0:443": {
                "proxy": "sleep-546955b66d-2lg5b.default",
                "message": "Listener=0.0.0.0:443 AcceptedHTTP=foo.zone1.svc.cluster.local RejectedTCP=www.google.com HTTPServices=1"
            }
        },
```
foo.zone1.svc.cluster.local  is a service which listens on 443 has a port name of grpc. Changing the port name from grpc seemed to fix this problem and now the HTTPS pass thorough works. A new listener for 10.0.0.20:443 now appears.

This seems like a bug as you could have many services wanting to have a new of grpc?

**Comment by vadimeisenbergibm** [comment]
@owenhaynes The protocol is inferred from the prefix, so you can have names like `grpc-service1`, `grpc-service2` and so on.

**Comment by owenhaynes** [comment]
This still does not fix the error i reported above:
Changed foo.zone1.svc.cluster.local port name from tcp to grpc-test  and the error message is back
```
        "pilot_conflict_outbound_listener_http_over_current_tcp": {
            "0.0.0.0:443": {
                "proxy": "sleep-546955b66d-2lg5b.default",
                "message": "Listener=0.0.0.0:443 AcceptedHTTP=foo.zone1.svc.cluster.local RejectedTCP=www.google.com HTTPServices=1"
            }
        },
```

Which then breaks HTTPS external services. Easy to reproduce:

Make sure no ServiceEntrys, VirutalServices are defined for google.

create a service like:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - name: grpc-my-service
    port: 443
    protocol: TCP
    targetPort: grpc
```

then run as the docs say

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
EOF

```

and now external https forwarding will be broken.  If you have the google entries installed first this will then do the reverse and break my-service

**Comment by i-93** [comment]
Any progress on this issue?

I am able to reproduce it with Istio 1.0.0 and 1.0.1 on KOPS installed K8S (https://groups.google.com/d/msg/istio-users/OOSeCr50CpA/pPe8i1WACwAJ)

**Comment by jmymy** [comment]
Seeing the same issue with Istio 1.0.2 on KOPS and K8S 1.10.5

**Comment by jmymy** [comment]
I changed all the port names to be unique, cleared out all the service entries, and re-tried with multiple rules and got it to work as expected.

**Comment by yudiandreanp** [comment]
@owenhaynes +1
Should be a bug.

**Comment by miv** [comment]
This is a bug. How is egress rule is connected to internal mesh port on some rando service?

**Comment by tshak** [comment]
This is a serious bug that's easy to repro but hard to debug if you aren't aware of how [traffic management applies rules based on port names](https://github.com/istio/istio.io/blob/master/content/help/faq/traffic-management/naming-port-convention.md) in a service. This is not an issue with the example but an issue with how traffic management affects egress rules. @owenhaynes  I recommend changing the title to remove "example" and clarify this issue to try and get more visibility. When triaging it's easy to assume this is an issue with the example as opposed to a severe issue.

**Comment by lukeforehand** [comment]
We are suffering from this bug and unable to move Istio into production until we can debug and resolve.

**Comment by vadimeisenbergibm** [comment]
@lukeforehand Could you please specify the Istio version and what does not work? An example configuration? Does the [Istio egress task](https://istio.io/docs/tasks/traffic-management/egress/) for you?

**Comment by lukeforehand** [comment]
Istio version 1.1.4.  We have an existing Service kind defined with a port
"443" named "grpc".  After injecting an istio sidecar on a pod with no no
other istio resources created, attempts to curl https://www.google.com
result in `SSL23_GET_SERVER_HELLO:unknown protocol`  I searched the pilot
discovery log and found:
```
"pilot_conflict_outbound_listener_http_over_current_tcp": {
    "0.0.0.0:443": {
        "proxy": "redacted",
        "message": "Listener=0.0.0.0:443
AcceptedHTTP=redacted.svc.cluster.local RejectedTCP=redacted HTTPServices=1"
    }
}
```
I used `istioctl proxy-config listeners` and `istioctl proxy-config routes`
command to determine HTTPS requests were being routed to the Service I
previously mentioned.  After I renamed the existing Service's port "https"
everything started working. However we can't rely on this fix.

**Comment by vadimeisenbergibm** [comment]
@lukeforehand Great, you found the problem. First, the port names are important in Istio, see https://istio.io/docs/setup/kubernetes/prepare/requirements/. So you have to use port names according to the Istio expectations for all your services.

Second, as far as I can see, Istio treats GRPC as HTTP, according to
https://github.com/istio/istio/blob/7d61672e25a28b0fa49ef2091f5b49703307572f/pilot/pkg/model/service.go#L259.

So if you use GRPC over TLS, you have to specify the port name as `tls-<some suffix>`. `https-` works too.

cc @rshriram

**Comment by maflaven** [comment]
@vadimeisenbergibm I'm also running through the [external services example w/ TLS origination](https://istio.io/docs/examples/advanced-gateways/egress-tls-origination/), and I'm running into a different issue where external services that share the same subdomain conflict with each other's `DestinationRule`s. In kiali I get a warning "More than one DestinationRules for the same subset host combination".

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service_a
spec:
  hosts:
    - api.service_a.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
    - number: 443
      name: http-port-for-tls-origination
      protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service_a
spec:
  hosts:
    - api.service_a.com
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: api.service_a.com
            port:
              number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service_a
spec:
  host: api.service_a.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing api.service_a.com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service_b
spec:
  hosts:
    - api.service_b.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
    - number: 443
      name: http-port-for-tls-origination
      protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service_b
spec:
  hosts:
    - api.service_b.com
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: api.service_b.com
            port:
              number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service_b
spec:
  host: api.service_b.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing api.service_b.com
---
```
