### ISSUE TITLE
Simple routing

### ISSUE THREAD

**Issue by JCzz** [istio/istio#7662]
**Describe the bug**

I dont know if this is a bug, but I have no idea why the following is not working?

Note: the image does work running with docker on port 8080. The image just replies to the request with some html.

```
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hello-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment-pro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-deployment
        version: pro
    spec:
      containers:
      - name: hello-pro
        image: awear/hello:pro
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-vs
spec:
  hosts:
  - "*"
  gateways:
  - hello-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: hello-service
        port:
          number: 8080
```
