### ISSUE TITLE
Istio does not support protocol except http

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#7664]
Hello All, 
We are using istio with istio auth disable and expose the istio ingress controller using NodePort.

We deploy one sftp pod and trying to get access of that sftp using istio gateway.

gateway.yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myistio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
   - port:
      number: 80
      name: http-backup
      protocol: TCP
    hosts:
    - "bckftp.com:5012"
```
virtualservice.yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsvc-cbbackup
  namespace: istio-system
spec:
  hosts:
  - bckftp.com:5012
  gateways:
  - myistio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: svc-bkp-backup-10.ns-test.svc.cluster.local
        port:
          number: 31536
```

When we are trying to access sftp below command:

`sftp -oPort=5012 backup@bckftp.com`

It gives the following error:

```
ssh_exchange_identification: Connection closed by remote host
Couldn't read packet: Connection reset by peer
```

ingressgateway logs:

```
[2018-08-06T13:38:26.761Z] "- - HTTP/1.1" 0 - 0 0 0 - "-" "-" "-" "-" "-"
[2018-08-06T13:38:28.237Z] "- - HTTP/1.1" 0 - 0 0 0 - "-" "-" "-" "-" "-"
```

Here the issue is we are not finding domain name so our virtual service will not work ofcourse.

Version
Istio - 1.0
Kubernetes - 10.3
etcd - v3

So what we are missing here?

**Comment by vadimeisenbergibm** [comment]
Try to set the `hosts` field of the gateway to `*`.

**Comment by ronakpandya7** [comment]
Hello @vadimeisenbergibm,

Request is handled by the gateway, as we can see logs in the ingressgateway pod.
So i do not see any issue with host.
What do you say?

**Comment by vadimeisenbergibm** [comment]
There is an issue with handling ports by the ingress gateway, see https://github.com/istio/istio/issues/6773, https://github.com/istio/istio/issues/6469.

**Comment by ronakpandya7** [comment]
Yes i knew that,
But here i am talking about the protocol, as we can see the request in gateway logs.
So here which protocol we have to give in gateway definition to get the correct domain and other information for sftp

**Comment by vadimeisenbergibm** [comment]
The first problem is that there is no match (due to the ports problem) between the gateway definition and the virtual service. The request arrives to the gateway, but cannot be routed because there is no matching virtual service (due to the ports problem).

Second, you try to apply `http` match on SFTP protocol, which is not HTTP. I do not think SSH is supported by Istio. @rshriram, @costinm ?

**Comment by rshriram** [comment]
We support HTTP/HTTP2/gRPC/MONGODB and TLS. There is no support for sftp.

**Comment by ronakpandya7** [comment]
Hello @rshriram,
Thanks for the information.

So is there any plan to give support for the sftp and kafka into istio in your next release?

Thanks

**Comment by AndriiNeverov** [comment]
+1 for `sftp` support

**Comment by silencecorner** [comment]
+1  for kafka support

**Comment by esnible** [comment]
@ronakpandya7 sftp just uses SSH.  By default it uses port 22 but it looks like you are using port 5012.

Here is a script I use to talk to github using HTTPS or SSH so that I can do `git clone` etc.  Perhaps you can modify it to talk to your backup site using port 5012.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: make-git-work
spec:
  hosts:
  - github.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 22
    name: ssh
    protocol: tcp
EOF
```
