### ISSUE TITLE
Istio telemetry missing global metrics 

### ISSUE THREAD

**Issue by dmyerscough** [istio/istio#7684]
**Describe the bug**

Istio request metrics do not seem to be captured.

**Expected behavior**

Global QPS and global success rate etc.

**Steps to reproduce the bug**

Installed Istio and enabled the following:-

```yaml
# Configuration for metric instances
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: doublerequestcount
  namespace: istio-system
spec:
  value: "2" # count each request twice
  dimensions:
    reporter: conditional((context.reporter.kind | "inbound") == "outbound", "client", "server")
    source: source.workload.name | "unknown"
    destination: destination.workload.name | "unknown"
    message: '"twice the fun!"'
  monitored_resource_type: '"UNSPECIFIED"'
---
# Configuration for a Prometheus handler
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: doublehandler
  namespace: istio-system
spec:
  metrics:
  - name: double_request_count # Prometheus metric name
    instance_name: doublerequestcount.metric.istio-system # Mixer instance name (fully-qualified)
    kind: COUNTER
    label_names:
    - reporter
    - source
    - destination
    - message
---
# Rule to send metric instances to a Prometheus handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: doubleprom
  namespace: istio-system
spec:
  actions:
  - handler: doublehandler.prometheus
    instances:
    - doublerequestcount.metric
---
# Configuration for logentry instances
apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: newlog
  namespace: istio-system
spec:
  severity: '"warning"'
  timestamp: request.time
  variables:
    source: source.labels["app"] | source.workload.name | "unknown"
    user: source.user | "unknown"
    destination: destination.labels["app"] | destination.workload.name | "unknown"
    responseCode: response.code | 0
    responseSize: response.size | 0
    latency: response.duration | "0ms"
  monitored_resource_type: '"UNSPECIFIED"'
---
# Configuration for a stdio handler
apiVersion: "config.istio.io/v1alpha2"
kind: stdio
metadata:
  name: newhandler
  namespace: istio-system
spec:
 severity_levels:
   warning: 1 # Params.Level.WARNING
 outputAsJson: true
---
# Rule to send logentry instances to a stdio handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: newlogstdio
  namespace: istio-system
spec:
  match: "true" # match for all requests
  actions:
   - handler: newhandler.stdio
     instances:
     - newlog.logentry
---
```

```bash
$ kubectl create -f ~/a 
metric.config.istio.io/doublerequestcount created
prometheus.config.istio.io/doublehandler created
rule.config.istio.io/doubleprom created
logentry.config.istio.io/newlog created
stdio.config.istio.io/newhandler created
rule.config.istio.io/newlogstdio created
```

Output from istio-telemetry - mixer

```bash
2018-08-07T03:54:15.776688Z	info	Publishing 6 events
2018-08-07T03:54:15.776985Z	error	failed to evaluate expression for field 'Dimensions[source]'; unknown attribute source.workload.name
2018-08-07T03:54:15.777021Z	error	failed to evaluate expression for field 'Variables[source]'; unknown attribute source.labels
2018-08-07T03:54:15.777071Z	error	Instance not found: instance='doublerequestcount.metric'
2018-08-07T03:54:15.777079Z	error	No valid instances found
2018-08-07T03:54:15.777083Z	error	No valid actions found in rule
2018-08-07T03:54:15.777094Z	error	Instance not found: instance='newlog.logentry'
2018-08-07T03:54:15.777175Z	error	No valid instances found
2018-08-07T03:54:15.777190Z	error	No valid actions found in rule
2018-08-07T03:54:15.777195Z	info	Built new config.Snapshot: id='6'
2018-08-07T03:54:15.777291Z	info	Cleaning up handler table, with config ID:5
```

**Version**

1.0

**Is Istio Auth enabled or not?**

```bash
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.enabled=true > $HOME/istio.yaml
```

**Environment**

Azure

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.
