### ISSUE TITLE
Helm delete does not clean the custom resource definitions

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#7688]
**Helm**:
```
Client: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
```

**Istio**: `1.0.0`

**Kubectl**:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Following a deletion of Istio 1.0.0 using `helm delete --purge` I notice that it leaves the crds as residue and a reinstall causes the error,
```
Error: customresourcedefinitions.apiextensions.k8s.io "gateways.networking.istio.io" already exists
```

In Tiller logs, I can see,
```
[tiller] 2018/08/07 12:07:28 executing 55 post-delete hooks for is
[kube] 2018/08/07 12:07:28 building resources from manifest
[kube] 2018/08/07 12:07:28 creating 1 resource(s)
```

However, the resources remain,
```
k get customresourcedefinitions | grep istio
adapters.config.istio.io                      1h
apikeys.config.istio.io                       1h
attributemanifests.config.istio.io            1h
authorizations.config.istio.io                1h
bypasses.config.istio.io                      1h
checknothings.config.istio.io                 1h
circonuses.config.istio.io                    1h
deniers.config.istio.io                       1h
destinationrules.networking.istio.io          1h
edges.config.istio.io                         1h
envoyfilters.networking.istio.io              1h
fluentds.config.istio.io                      1h
gateways.networking.istio.io                  1h
handlers.config.istio.io                      1h
httpapispecbindings.config.istio.io           1h
httpapispecs.config.istio.io                  1h
instances.config.istio.io                     1h
....
```

Has anyone noticed this with `Helm v2.10.0-rc.2` ?

**Comment by ymesika** [comment]
That's right. In `1.0.0` there CRDs were taken out of the Helm management into their own YAML file and we require the users (who install with Helm) to first install that CRDs yaml.

Therefore, since they are unmanaged Helm won't delete them. Similar to the installation the users are expected to delete them by executing `kubectl delete -f install/kubernetes/helm/istio/templates/crds.yaml -n istio-system`.

**Comment by nixgadget** [comment]
@ymesika what you have stated which reflects in the Istio installation steps (https://istio.io/docs/setup/kubernetes/helm-install/#installation-steps),
> If using a Helm version prior to 2.10.0, install Istio’s Custom Resource Definitions via kubectl apply, and wait a few seconds for the CRDs to be committed in the kube-apiserver
is right for `Helm < 2.10.0` versions.

What about versions `> 2.10.0` ?
I was under the impression that with `Helm > 2.10.0` there is the possibility to inject crds with `crd-install` hooks and I can see that this is already enabled in Istio 1.0.0.

Reading the documentation I did stumble across this https://github.com/helm/helm/blob/master/docs/charts_hooks.md#automatically-delete-hook-from-previous-release which should enforce a deletion shouldnt it ?

**Comment by ymesika** [comment]
Thanks for clarifying. Yes, that was the plan.
cc @linsun

**Comment by nixgadget** [comment]
@sdake happy to test it out when you are done. thanks for looking into it.

**Comment by squillace** [comment]
me, too. I just tested this with 2.10 and 1.0 of istio, same error. did this happen?

**Comment by amyroh** [comment]
Since helm version > 2.10.0 does not require to install Istio's CRDs on a separate command via kubectl apply, I think it's fair to expect `helm delete istio --purge` should delete the CRDs without having to explicitly delete them.

**Comment by linsun** [comment]
I think this is a helm issue where the `delete istio --purge` didn't clean up CDRs properly even if you are already on helm 2.10, I'm glad you are raising this with helm github repo directly too.

**Comment by nixgadget** [comment]
Yeah I ended up having a custom helm job to do achieve this using,
```
"helm.sh/hook": post-delete
"helm.sh/hook-delete-policy": hook-succeeded
```

**Comment by Keisone** [comment]
> **Helm**:
> 
> ```
> Client: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.10.0-rc.2", GitCommit:"56154102a2f25ebf679c791907fd355bb0377f05", GitTreeState:"clean"}
> ```
> **Istio**: `1.0.0`
> 
> **Kubectl**:
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
> ```
> Following a deletion of Istio 1.0.0 using `helm delete --purge` I notice that it leaves the crds as residue and a reinstall causes the error,
> 
> ```
> Error: customresourcedefinitions.apiextensions.k8s.io "gateways.networking.istio.io" already exists
> ```
> In Tiller logs, I can see,
> 
> ```
> [tiller] 2018/08/07 12:07:28 executing 55 post-delete hooks for is
> [kube] 2018/08/07 12:07:28 building resources from manifest
> [kube] 2018/08/07 12:07:28 creating 1 resource(s)
> ```
> However, the resources remain,
> 
> ```
> k get customresourcedefinitions | grep istio
> adapters.config.istio.io                      1h
> apikeys.config.istio.io                       1h
> attributemanifests.config.istio.io            1h
> authorizations.config.istio.io                1h
> bypasses.config.istio.io                      1h
> checknothings.config.istio.io                 1h
> circonuses.config.istio.io                    1h
> deniers.config.istio.io                       1h
> destinationrules.networking.istio.io          1h
> edges.config.istio.io                         1h
> envoyfilters.networking.istio.io              1h
> fluentds.config.istio.io                      1h
> gateways.networking.istio.io                  1h
> handlers.config.istio.io                      1h
> httpapispecbindings.config.istio.io           1h
> httpapispecs.config.istio.io                  1h
> instances.config.istio.io                     1h
> ....
> ```
> Has anyone noticed this with `Helm v2.10.0-rc.2` ?

I had the same issue and I had to delete manually:

kubectl delete crd gateways.networking.istio.io

**Comment by nixgadget** [comment]
For anyone wanting to fix this until a permanent fix is being released,

```
{{- if .Values.global.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "istio.customJob" . }}-cc-sa
  labels:
    app: {{ template "istio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    istio: customjob-cc
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "istio.customJob" . }}-cc-cr
  labels:
    app: {{ template "istio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    istio: customjob-cc
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "istio.customJob" . }}-cc-crb
  labels:
    app: {{ template "istio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    istio: customjob-cc
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
subjects:
- name: {{ template "istio.customJob" . }}-cc-sa
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
roleRef:
  name: {{ template "istio.customJob" . }}-cc-cr
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "istio.customJob" . }}-cc
  labels:
    app: {{ template "istio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    istio: customjob-cc
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: {{ template "istio.customJob" . }}-cc
      labels:
        app: {{ template "istio.name" . }}
        istio: customjob-cc
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.global.rbacEnabled }}
      serviceAccountName: {{ template "istio.customJob" . }}-cc-sa
      {{- end }}
      restartPolicy: OnFailure
      affinity:
        {{- if .Values.global.kubectl.nodeAffinity }}
        nodeAffinity:
{{ toYaml .Values.global.kubectl.nodeAffinity | indent 10 }}
        {{- end }}
        {{- if eq .Values.global.kubectl.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "istio.name" . }}
                  istio: customjob-cc
                  release: {{ .Release.Name }}
        {{- else if eq .Values.global.kubectl.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "istio.name" . }}
                  istio: customjob-cc
                  release: {{ .Release.Name }}
        {{- end }}
      {{- if .Values.global.kubectl.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.kubectl.nodeSelector | indent 8 }}
      {{- end }}
      containers:
        - name: {{ template "istio.customJob" . }}-cc-kubectl
          image: {{ .Values.global.image.repo }}/{{ .Values.global.kubectl.image }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
          - /bin/bash
          - -c
          - >
              kubectl get customresourcedefinitions | grep "istio.io" | while read -r entry; do
                name=$(echo $entry | awk '{print $1}');
                kubectl delete customresourcedefinitions $name;
              done
```

**Comment by jeremyxu2010** [comment]
template "istio.customJob" not defined， how to resolve it?


> For anyone wanting to fix this until a permanent fix is being released,
> 
> ```
> {{- if .Values.global.rbacEnabled }}
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: {{ template "istio.customJob" . }}-cc-sa
>   labels:
>     app: {{ template "istio.name" . }}
>     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
>     heritage: {{ .Release.Service }}
>     istio: customjob-cc
>     release: {{ .Release.Name }}
>   annotations:
>     "helm.sh/hook": post-delete
>     "helm.sh/hook-delete-policy": hook-succeeded
>     "helm.sh/hook-weight": "1"
> ---
> apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRole
> metadata:
>   name: {{ template "istio.customJob" . }}-cc-cr
>   labels:
>     app: {{ template "istio.name" . }}
>     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
>     heritage: {{ .Release.Service }}
>     istio: customjob-cc
>     release: {{ .Release.Name }}
>   annotations:
>     "helm.sh/hook": post-delete
>     "helm.sh/hook-delete-policy": hook-succeeded
>     "helm.sh/hook-weight": "1"
> rules:
> - apiGroups: ["apiextensions.k8s.io"]
>   resources: ["customresourcedefinitions"]
>   verbs: ["list", "delete"]
> ---
> apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRoleBinding
> metadata:
>   name: {{ template "istio.customJob" . }}-cc-crb
>   labels:
>     app: {{ template "istio.name" . }}
>     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
>     heritage: {{ .Release.Service }}
>     istio: customjob-cc
>     release: {{ .Release.Name }}
>   annotations:
>     "helm.sh/hook": post-delete
>     "helm.sh/hook-delete-policy": hook-succeeded
>     "helm.sh/hook-weight": "2"
> subjects:
> - name: {{ template "istio.customJob" . }}-cc-sa
>   kind: ServiceAccount
>   namespace: {{ .Release.Namespace }}
> roleRef:
>   name: {{ template "istio.customJob" . }}-cc-cr
>   kind: ClusterRole
>   apiGroup: rbac.authorization.k8s.io
> ---
> {{- end }}
> apiVersion: batch/v1
> kind: Job
> metadata:
>   name: {{ template "istio.customJob" . }}-cc
>   labels:
>     app: {{ template "istio.name" . }}
>     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
>     heritage: {{ .Release.Service }}
>     istio: customjob-cc
>     release: {{ .Release.Name }}
>   annotations:
>     "helm.sh/hook": post-delete
>     "helm.sh/hook-delete-policy": hook-succeeded
>     "helm.sh/hook-weight": "3"
> spec:
>   template:
>     metadata:
>       name: {{ template "istio.customJob" . }}-cc
>       labels:
>         app: {{ template "istio.name" . }}
>         istio: customjob-cc
>         release: {{ .Release.Name }}
>     spec:
>       {{- if .Values.global.rbacEnabled }}
>       serviceAccountName: {{ template "istio.customJob" . }}-cc-sa
>       {{- end }}
>       restartPolicy: OnFailure
>       affinity:
>         {{- if .Values.global.kubectl.nodeAffinity }}
>         nodeAffinity:
> {{ toYaml .Values.global.kubectl.nodeAffinity | indent 10 }}
>         {{- end }}
>         {{- if eq .Values.global.kubectl.antiAffinity "hard" }}
>         podAntiAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             - topologyKey: kubernetes.io/hostname
>               labelSelector:
>                 matchLabels:
>                   app: {{ template "istio.name" . }}
>                   istio: customjob-cc
>                   release: {{ .Release.Name }}
>         {{- else if eq .Values.global.kubectl.antiAffinity "soft" }}
>         podAntiAffinity:
>           preferredDuringSchedulingIgnoredDuringExecution:
>           - weight: 1
>             podAffinityTerm:
>               topologyKey: kubernetes.io/hostname
>               labelSelector:
>                 matchLabels:
>                   app: {{ template "istio.name" . }}
>                   istio: customjob-cc
>                   release: {{ .Release.Name }}
>         {{- end }}
>       {{- if .Values.global.kubectl.nodeSelector }}
>       nodeSelector:
> {{ toYaml .Values.global.kubectl.nodeSelector | indent 8 }}
>       {{- end }}
>       containers:
>         - name: {{ template "istio.customJob" . }}-cc-kubectl
>           image: {{ .Values.global.image.repo }}/{{ .Values.global.kubectl.image }}:{{ .Values.global.image.tag }}
>           imagePullPolicy: {{ .Values.global.image.pullPolicy }}
>           command:
>           - /bin/bash
>           - -c
>           - >
>               kubectl get customresourcedefinitions | grep "istio.io" | while read -r entry; do
>                 name=$(echo $entry | awk '{print $1}');
>                 kubectl delete customresourcedefinitions $name;
>               done
> ```

**Comment by nixgadget** [comment]
Heres a much simplified version of the above for the curious,
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-custom-job-cc-sa
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-custom-job-cc-cr
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-custom-job-cc-crb
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
subjects:
- name: istio-custom-job-cc-sa
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
roleRef:
  name: istio-custom-job-cc-cr
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-custom-job-cc
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: istio-custom-job-cc
    spec:
      serviceAccountName: istio-custom-job-cc-sa
      restartPolicy: OnFailure
      affinity:
      containers:
        - name: istio-custom-job-cc-kubectl
          image: gcr.io/istio-release/kubectl:release-1.1-20181101-09-15
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          - >
              kubectl get customresourcedefinitions | grep "istio.io" | while read -r entry; do
                name=$(echo $entry | awk '{print $1}');
                kubectl delete customresourcedefinitions $name;
              done
```
