### ISSUE TITLE
Issues with Kubernetes NetworkPolicy - Calico and Istio 

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#7723]
Hello All,

I have gone through below two issues:
#5815 
#7025 

And configure two deployments :

Deployment1.yaml:

```
kind: Service
apiVersion: v1
metadata:
  name: service-testing1
  namespace: istio-system
spec:
  selector:
    app: testing1
  ports:
  - name: http
    protocol: TCP
    port: 6000
    targetPort: 6000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-testing1
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      name: frontend-test1
      labels:
        app: testing1
        istio: ingressgateway
    spec:
      containers:
      - name: server-testing1
        image: test/server_final
        ports:
        - containerPort: 6000
```

Deployment2.yaml:

```
kind: Service
apiVersion: v1
metadata:
  name: service-testing
  namespace: istio-system
spec:
  selector:
    app: testing
  ports:
  - name: http-test-hel
    port: 5000
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-testing
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      name: frontend-test
      labels:
        app: testing
        istio: ingressgateway
    spec:
      containers:
      - name: server-testing
        image: test/final_servere
        ports:
        - containerPort: 5000
```

Now i applied kubernetes NetworkPolicy default deny on namespace istio-system:

```
kubectl create -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-istio
  namespace: istio-system
spec:
  podSelector:
    matchLabels: 
  policyTypes:  
  - Ingress
EOF
``` 

Everything works fine, service-testing and service-testing1 are unable to connect with each other.
Now issue comes when we apply another NetworkPolicy (i.e service-testing can connect to service-testing1)

```
kubectl create -f -<<EOF
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: np-allow-infra-testing
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      app: testing1
  ingress:  
  - from:
    - podSelector:
        matchLabels:
          app: testing
EOF
```

But it will not take effect as said in issue #5815 as envoy persist the HTTP connections.
So i have restarted both of the pods so that envoys gent new connection.

But after restarting when i curl both the services from one and another it gives below error:

```
curl: (7) Failed to connect to service-testing1 port 6000: Connection refused
curl: (7) Failed to connect to service-testing1 port 5000: Connection refused
```

So what we are missing here?
