### ISSUE TITLE
match uri and headers is reaching wrong endpoint

### ISSUE THREAD

**Issue by JCzz** [istio/istio#7727]
**Describe the bug**

Update: This "error" makes sense, if I think of the `VirtualService` as one big funnel - it that the way to think about the configuration. Meaning anything first in the `VirtualService`  config will win?

I have the following VirtualService defining matches:

```
  - match:
    - headers:
        end-user:
          exact: userone
    - uri:
        exact: /hello1
    route:
    - destination:
        host: helloworld-service
        subset: v1
  - match:
    - uri:
        exact: /hello2
    route:
    - destination:
        host: helloworld-service
        subset: v2
```

**Expected behavior**

1. First `/hello1` is always replying even NOT setting header `end-user ` to `userone`?

2. Setting header `end-user ` to `userone` and requesting `/hello2`  and reaching for `helloworld-service` version `**v2**` it calles `**v1**` like if it was `/hello1`

I would expect that `/hello2` match to reply not `/hello1`

Note: If I do **NOT** set the header `end-user ` to `userone` it is calling the right `helloworld-service` version `**v2**`

**Version**
1.0

**Is Istio Auth enabled or not?**
Dont know?

**Environment**
MacOs Kuberneres for desktop

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.

**Comment by ymesika** [comment]
When I examine the behaviour you described it seems like it works as expected. And by expected I'm referring to:
>  All conditions inside a single match block have AND semantics, while the list of match blocks have OR semantics. The rule is matched if any one of the match blocks succeed.

as described here: https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPRoute

But maybe I just misunderstood your issue.

**Comment by JCzz** [comment]
Hi @ymesika 

I belive you understood my question. I am still having issues with this, did you try it out or did you verify it by reading the yaml?

Thanks

**Comment by JoeLaw91** [comment]
I hope I am not too late to the party
@JCzz , the way you had written the headers and uri is of "or" clause, to make it to check both, you need to indent the uri within the header or the other way around.

```
- headers:
        end-user:
          exact: userone
    uri:
        exact: /hello1
```

Check my identation, it might be abit off after pasting it.
