### ISSUE TITLE
[istio-ingressgateway] couldn't handle full URL request

### ISSUE THREAD

**Issue by veekungx** [istio/istio#7828]
**Describe the bug**
<sub><sup>Istio can't handle full URL</sup></sub>

**Expected behavior**
<sub><sup>Route to the right service with full URL request</sup></sub>

I successful config Istio, Gateway (with TLS and tls.httpsRedirect setting), VirtualService and it can receive HTTP POST.

And here the raw http that request to my service.

```
POST / HTTP/1.1
Host: myurl.com
Content-Type: application/json
Connection: close
Content-Length: 17
X-Forwarded-Proto: https
X-Forwarded-For: XXX.XXX.XXX.XXX

{"hello":"world"}
```
The example http above works fine. I got 200 OK response.

but sometimes I got "FULL URL" on request and seem like Istio can't handle it
```
POST https://myurl.com/ HTTP/1.1  <== HERE THE FULL URL
Host: myurl.com
Content-Type: application/json
Connection: close
Content-Length: 17
X-Forwarded-Proto: https
X-Forwarded-For: XXX.XXX.XXX.XXX

{"hello":"world"}
```

and here the log from 'istio-ingressgateway'

```
POST / HTTP/1.1" 200 - 318 203 210 210 "XXX.XXX.XXX.XXX" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "eab50f1a-2392-9539-920e-ca43f9be8aae" "myurl.com" "10.42.1.205:5000"

POST https://myurl.com/ HTTP/1.1" 404 NR - - - - "XXX.XXX.XXX.XXX" - - "myurl.com" -
```

Is this bug or I just misconfiguration. here my config

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  gateways:
  - "my-gateway"
  hosts:
  - "myurl.com"
  http:
  - route:
    - destination:
        host: my-service.staging.svc.cluster.local
        port:
          number: 80
```
