### ISSUE TITLE
after adding a serviceEntry to an external website in istio, we still cannot connect. It seems istio is forcing SSLv3 and not using TLS1.2 (the site only uses TLSv1.2)

### ISSUE THREAD

**Issue by bshetti** [istio/istio#7837]
**Describe the bug**
after adding a serviceEntry to an external website, we still cannot connect. It seems istio is forcing SSLv3 and not using TLS1.2 (the site only uses TLSv1.2).

following was created:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wavefront
spec:
  hosts:
  - try.wavefront.com
  - try-fixed.wavefront.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https-wavefront
    protocol: HTTPS
    resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wavefront
spec:
  hosts:
  - try.wavefront.com
  - try-fixed.wavefront.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - try.wavefront.com
    route:
    - destination:
        host: try.wavefront.com
        port:
          number: 443
      weight: 100
  - match:
    - port: 443
      sni_hosts:
      - try-fixed.wavefront.com
    route:
    - destination:
        host: try-fixed.wavefront.com
        port:
          number: 443
      weight: 100

```

then after a 
kubectl create -f <FILEABOVE>

then 
kubectl exec -it <POD NUMBER> -c X -- /bin/bash

```yaml
/# curl -v https://try.wavefront.com
* Rebuilt URL to: https://try.wavefront.com/
* Hostname was NOT found in DNS cache
*   Trying 52.25.50.93...
* Connected to try.wavefront.com (52.25.50.93) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to try.wavefront.com:443 
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to try.wavefront.com:443 
```

We tested both out against google using the same serviceEntry file above but with google and the following results:
```yaml
/# curl -v --tlsv1.2 https://www.google.com
* Rebuilt URL to: https://www.google.com/
* Hostname was NOT found in DNS cache
*   Trying 216.58.193.68...
* Connected to www.google.com (216.58.193.68) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=www.google.com
* 	 start date: 2018-08-07 18:34:32 GMT
* 	 expire date: 2018-10-16 18:28:00 GMT
* 	 subjectAltName: www.google.com matched
* 	 issuer: C=US; O=Google Trust Services; CN=Google Internet Authority G3
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.google.com
```

Hence WHY IS ISTIO forcing SSLv3?

Did we miss a simple setting somewhere? (probably ;-)

**Expected behavior**
The curl should output something like the following:
```yaml
 curl -v https://try.wavefront.com
* Rebuilt URL to: https://try.wavefront.com/
*   Trying 52.25.50.93...
* TCP_NODELAY set
* Connected to try.wavefront.com (52.25.50.93) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Palo Alto; O=VMware, Inc; CN=*.wavefront.com
*  start date: Feb 22 03:37:04 2018 GMT
*  expire date: Feb 22 04:07:03 2020 GMT
*  subjectAltName: host "try.wavefront.com" matched cert's "*.wavefront.com"
*  issuer: C=US; O=Entrust, Inc.; OU=See www.entrust.net/legal-terms; OU=(c) 2012 Entrust, Inc. - for authorized use only; CN=Entrust Certification Authority - L1K
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
```

**Steps to reproduce the bug**
Not sure if there is an issue with the istio set up where I need to force no sslv3? the site only uses tlsv1.2
But it seems that istio is trying to connect with sslv3 only

**Version**
Istio version 1.0.0
kubernetes  1.10.3

**Is Istio Auth enabled or not?**
NO

**Environment**
Ubuntu OS
