### ISSUE TITLE
Grpc With Gateway Using 1.0

### ISSUE THREAD

**Issue by namsoila** [istio/istio#7843]
What is the recommended way to receive gRPC traffic using a gateway with version 1.0? Is there a working example or documentation?

I have tried the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-grpc-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 50051
      name: grpc
      protocol: grpc
    hosts:
    - example.com
    - www.example.com
    tls:
      mode: SIMPLE #enables HTTPS on this port
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
But receive an error:
```
admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: server cannot have TLS settings for plain text HTTP
 ports
```
Are you still supposed to use `istio: ingressgateway`?
