### ISSUE TITLE
VirtualService corsPolicy not parsed properly

### ISSUE THREAD

**Issue by kubaj** [istio/istio#7859]
**Describe the bug**
Admission webhook "pilot.validation.istio.io" denies the request when VirtualService with corsPolicy is created. 

**Expected behavior**
VirtualService should be accepted

**Steps to reproduce the bug**
Create and apply following VirtualService:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "example.com"
  gateways:
  - example-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: some-service
    corsPolicy:
      allowOrigin:
      - "*.example.com"
      allowMethods:
      - POST
      - GET
      - OPTIONS
      allowHeaders:
      - "DNT"
      - "User-Agent"
      - "X-Requested-With"
      - "If-Modified-Since"
      - "Cache-Control"
      - "Content-Type"
      - "Range"
      exposeHeaders:
      - "Content-Length"
      - "Content-Range"
      maxAge: "86400s"
```

and error is shown: 
```
Error from server: error when creating "gw.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 7 errors occurred:

* must be in lower case
* must be in lower case
* must be in lower case
* must be in lower case
* must be in lower case
* must be in lower case
* must be in lower case
```

When `allowHeaders` and `exposeHeaders` properties are removed from corsPolicy, then VirtualService is accepted. 

**Version**
Release 1.0.0

**Is Istio Auth enabled or not?**
Yes

**Environment**
GKE cluster
