### ISSUE TITLE
Custom ServiceAccounts not being picked up by Citadel

### ISSUE THREAD

**Issue by rshriram** [istio/istio#7860]
Create a client and server pod.
Assign non default service accounts to these pods during creation. Then enable mTLS policies, plus destination rule (usign ISTIO_MUTUAL)

You will see that client->server access fails consistently. Envoy reports SAN validation failed in the stats on the client side. Inspecting the certs on client/server pod show the standard Istio default service account but not the service account I assigned to the pod. 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: '{"version":"55ca84b79cb5036ec3e54a3aed83cd77973cdcbed6bf653ff7b4f82659d68b1e","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
      labels:
        app: client
    spec:
      serviceAccountName: client1
      containers:
      - command:
        - /bin/sleep
        - infinity
        image: tutum/curl
        imagePullPolicy: IfNotPresent
        name: client
        resources: {}
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - client
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-statsd-prom-bridge.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        image: docker.io/istio/proxyv2:1.0.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - ""
        - -d
        - ""
        image: docker.io/istio/proxy_init:1.0.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
---
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: server-v1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: '{"version":"55ca84b79cb5036ec3e54a3aed83cd77973cdcbed6bf653ff7b4f82659d68b1e","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
      labels:
        app: server
        version: v1
    spec:
      serviceAccountName: server2
      containers:
      - args:
        - --port
        - "80"
        - --version
        - v1
        image: docker.io/istio/app:1.0.0
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 80
        resources: {}
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - server
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-statsd-prom-bridge.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        image: docker.io/istio/proxyv2:1.0.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - 80,
        - -d
        - ""
        image: docker.io/istio/proxy_init:1.0.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
---
```

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dest-rule-server-default
spec:
  host: server.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

```bash
kubectl exec -it client-78fdd5dd9d-xrtvj -c istio-proxy -- cat /etc/certs/cert-chain.pem | openssl x509 -noout -text 
```

shows
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a2:e7:ec:e4:b1:95:54:ee:43:b4:3c:f5:8e:ac:db:7f
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=
        Validity
            Not Before: Aug 13 13:37:01 2018 GMT
            Not After : Aug 14 10:37:01 2018 GMT
        Subject: O=
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c3:f4:5e:b4:7b:1f:70:f5:18:16:97:d9:57:be:
                    ec:15:e5:61:6e:80:0d:b7:d7:e6:6c:f0:d8:b5:99:
                    18:09:e6:3e:de:0e:8c:58:f2:c3:da:87:4c:75:c1:
                    bd:d5:4a:f4:71:b4:20:dc:8e:87:fb:aa:22:58:9f:
                    54:15:71:73:44:55:31:e5:ec:b5:c4:f7:e4:bf:a2:
                    f4:8a:3f:63:ca:10:3f:d0:45:8a:7a:5a:ca:2a:5d:
                    67:80:04:43:a9:1e:96:2b:a7:4e:41:0f:80:a6:fb:
                    af:71:7b:1e:55:13:a9:a3:34:70:8a:25:2b:fa:69:
                    92:02:1c:53:ac:11:0a:3f:75:5e:e8:18:ac:0a:24:
                    b7:df:67:01:00:48:85:e1:8c:87:e8:46:56:c3:82:
                    da:bc:31:4e:d9:6e:1a:d7:c2:d5:1d:b9:39:34:6f:
                    dc:b9:bf:a2:e0:03:80:2f:a2:2b:73:c1:08:cf:ee:
                    83:82:67:36:df:23:45:59:0e:ed:38:dc:15:ef:91:
                    4f:b7:29:c5:77:5f:22:8b:24:b8:b3:26:27:c5:f3:
                    a1:cf:9f:8c:6c:ab:df:f4:51:05:bd:a3:43:64:e7:
                    bc:f7:73:b9:6e:66:6f:5a:bd:cd:c7:ef:08:a6:f1:
                    81:a2:4f:1b:8d:86:f8:7c:0a:79:75:25:35:b9:96:
                    c7:ff
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name: 
                URI:spiffe://cluster.local/ns/default/sa/default
    Signature Algorithm: sha256WithRSAEncryption
         26:f6:50:60:5e:4e:f1:83:53:d9:83:df:96:1f:d2:c2:8c:e7:
         b8:3a:55:0f:64:85:a3:0b:0b:f1:2e:fa:c3:9f:8f:a1:08:08:
         20:a2:10:b7:1c:f6:a4:ce:aa:77:a2:ad:ea:a9:20:a8:6a:5a:
         3c:fa:10:0e:b8:9b:e1:3b:5f:10:03:9f:ab:96:a4:3d:9f:8d:
         e6:4d:45:50:9a:bf:60:c4:b0:74:42:11:e7:00:27:23:35:9c:
         cf:53:ea:6f:36:19:0c:50:d2:23:9c:32:38:1d:7e:d1:71:4e:
         93:26:ee:f1:19:dc:b6:94:a1:9f:5b:ad:f3:75:20:a7:6f:a6:
         96:4f:4e:ed:74:fe:78:67:f8:54:13:14:de:89:95:95:13:d5:
         ad:42:03:92:dc:a2:2e:d4:88:f7:11:93:ab:41:83:0b:ee:cb:
         4e:24:b7:a0:f2:fd:bb:f1:00:22:39:9a:b8:35:97:71:77:12:
         a3:bc:07:d1:c0:9d:01:4e:90:1e:4f:f5:9b:4e:39:cb:76:c5:
         7d:c1:39:57:b5:4d:96:a1:ad:5d:48:51:36:75:7e:48:35:23:
         76:b1:f7:69:0e:3f:de:3e:7e:4c:cd:46:6f:23:d9:63:96:ba:
         3d:7b:d8:78:79:34:2b:cb:60:4b:6f:59:de:5f:64:01:95:3f:
         a9:2a:f5:3b
```

Notice the missing SAN "spiffee://cluster.local/ns/default/sa/server1". 

curl from client to server and the request will fail. Since the service accounts are not being propagated, RBAC breaks as well (i.e. I can't use source principal as a property in the service role binding). 

cc @diemtvu / @wattli / @myidpt / @liminw / @yangminzhu .
