### ISSUE TITLE
Gateway into gRPC - I thought I had it right

### ISSUE THREAD

**Issue by JCzz** [istio/istio#7909]
**Describe the bug**

Update: If you run into problems using gRPC and Istio, I can tell you that I have been using a week and some days without success - see below description. 
I really look forward to see Istio solving this, if it is a bug, or document this if - and probably is - just me who is unable to figure this out :-)

Until this great software and all its telemetries and other cool stuff is working for you, you can use Ambassador. 
Ambassador gets the job done for “north/south” traffic - you can use this if you need to move forward in you development while waiting: https://www.getambassador.io/user-guide/grpc

---
I am trying to call a gRPC service - can you help. The following is the setup:

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 3000
      name: grpc-my
      protocol: grpc # also tried TCP, HTTP/2, HTTP
    hosts:
    - "my-service-grpc.default.svc.cluster.local"
```

Service:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service-grpc
  labels:
    app: my-service-grpc
spec:
  selector:
    app: my-deployment-grpc
  ports:
  - port: 3000
    name: grpc-my
    protocol: grpc # Also tried TCP, HTTP/2, HTTP
```

Deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-deployment-grpc
        version: v1
    spec:
      containers:
      - name: my
        image: my/image:v1.0
        ports:
        - containerPort: 3000
          name: grpc-my
          protocol: TCP
```

VirtualService:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
  - "my-service-grpc.default.svc.cluster.local"
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: /helloworld.Greeter/
    route:
    - destination:
        host: my-service-grpc
```

Istio helm value.yaml file

```
   ingress:...
    - port: 6000
      name: grpc

```
```
   gateways:...
    - port: 15031
      targetPort: 15031
      name: http2-grafana
# Added for gRPC
    - port: 6000
      targetPort: 3000
      name: grpc-app
    secretVolumes:
   ...
```

Then:
`grpc_cli ls localhost:3000 helloworld.Greeter -l`
I get the following error:
```
D0814 16:49:43.653073000 140735522448256 ev_posix.cc:142]              Using polling engine: poll
D0814 16:49:43.693399000 140735522448256 dns_resolver.cc:331]          Using native dns resolver
I0814 16:49:43.740829000 140735522448256 subchannel.cc:646]            Connect failed: {"created":"@1534258183.740786000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv6:[::1]:3000"}
I0814 16:49:43.741021000 140735522448256 subchannel.cc:646]            Connect failed: {"created":"@1534258183.740998000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:3000"}
I0814 16:49:43.741037000 140735522448256 subchannel.cc:470]            Subchannel 0x7fa04cd02150: Retry in 1000 milliseconds
Received an error when querying services endpoint.
I0814 16:49:43.741683000 140735522448256 proto_reflection_descriptor_database.cc:51] ServerReflectionInfo rpc failed. Error code: 14, details: Connect Failed
```

Note: I have all this working with Ambasador, getambassador.io/config: 

Note: `istioctl get gateway istio-autogenerated-k8s-ingress -n istio-system -o yaml`

Only list port 80?
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: istio-autogenerated-k8s-ingress
  namespace: istio-system
  resourceVersion: "813085"
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP2
```

**Expected behavior**

**Steps to reproduce the bug**

**Version**
istio 1.0
kubernetes 1.10

**Is Istio Auth enabled or not?**
No

**Environment**

**Cluster state**
<sub><sup>If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.</sup></sub>

**Comment by ijsnellf** [comment]
Similar issues reported elsewhere:
https://github.com/istio/istio/issues/7843
https://github.com/istio/istio/issues/7980

**Comment by JCzz** [comment]
Hi @rshriram 

Thanks, I now tried opening a new port in helm values.yaml

```
   ...
    - port: 15031
      targetPort: 15031
      name: http2-grafana
# Added for gRPC
    - port: 3000
      targetPort: 3000
      name: grpc-app
    secretVolumes:
   ...
```

Should that be enough?

**Comment by begoat** [comment]
just add 
``` json
      name: grpc
      nodePort: 31399
      port: 9090
      targetPort: 9090
```
in `kind: Service name: istio-ingressgateway`

and then access the gRPC-server  by  ingress service ip : 9090 is ok for me

**Comment by JCzz** [comment]
Thanks @begoat

I am giving up on Istio - thanks for you help

**Comment by xiajidexue** [comment]
> hello, @JCzz
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: backend-gateway
> spec:
>   selector:
>     istio: ingressgateway # use Istio default gateway implementation
>   servers:
>   - port:
>       number: 9090
>       name: grpc-gateway
>       protocol: GRPC
>     hosts:
>     - "*"
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: backend
> spec:
>   hosts:
>   - "*"
>   gateways:
>   - backend-gateway
>   http:
>   - match:
>     - uri:
>         prefix: /
>     route:
>     - destination:
>         host: backend
>         port:
>           number: 50051
> ```
> 
> ```yaml
> apiVersion: v1
> kind: Service
> metadata:
>   name: istio-ingressgateway
>   namespace: istio-system
>   annotations:
>     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
>   labels:
>     chart: gateways-1.0.0
>     release: RELEASE-NAME
>     heritage: Tiller
>     app: istio-ingressgateway
>     istio: ingressgateway
> spec:
>   type: LoadBalancer
>   selector:
>     app: istio-ingressgateway
>     istio: ingressgateway
>   ports:
>     -
>       name: http2
>       nodePort: 31380
>       port: 80
>       targetPort: 80
>     -
>       name: https
>       nodePort: 31390
>       port: 443
>     - 
>       name: grpc
>       nodePort: 31399
>       port: 9090
>       targetPort: 9090
> ```
> 
> I run it on azure platform

@JCzz I just saw you exposed your service via "prefix: /" in **VirtualService**, how can you expose other gRPC services?

**Comment by JCzz** [comment]
Hi @xiajidexue 

I never got it to work. I have asked around a lot, incl. gitter grpc, Ambassador, Istio - no one seems to know. Let me know if you get any closer?

**Comment by facundomedica** [comment]
@JCzz I got it working! And also added TLS! I added the port 30051 to the istio-ingressgateway but you can use 31400 without any changes (I don't know if other service uses this port, but it is enabled by default). My service is called `gateway` and exposes an http server and the gRPC service (if there is too much confusion I'll refactor the examples below).

For my TLS certificates I've used Let's Encrypt.

The gateway:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-gateway
  namespace: development
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 30051
      name: grpc
      protocol: https
    tls:
      mode: SIMPLE      
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "development.redacted.co"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "development.redacted.co"
```

VirtualService:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway
  namespace: development
spec:
  hosts:
  - "development.redacted.co"
  gateways:
  - gateway-gateway
  http:
  - match:
    - uri:
        prefix: /api/
    rewrite:
      uri: /
    route:
    - destination:
        host: gateway
        port:
          number: 5000
  - match:
    - port: 30051
    route:
    - destination:
        host: gateway
        port:
          number: 50051
```

Service:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: development
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 50051
      name: grpc
    - port: 5000
      name: http
```

**Comment by JCzz** [comment]
Hi @facundomedica

Thank you so much for sharing, I will get back and verify this when I deploy. For now I am developing on just port 80.
Very cool!

**Comment by noisyox** [comment]
@facundomedica  I am unable to access grpc application (listen 3000) using loadbalncer and can be accessed using Nodeport. Although if I setup any http application using http config it works without a sweat. Please help.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: grpc-test
      protocol: GRPC
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: frontend
        port:
          number: 3000
          name: grpc-test

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    name: grpc-test

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: prod
    spec:
      containers:
      - name: frontend
        image: ****:grpc
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "frontend-prod"
      imagePullSecrets:
        - name: gitlab-registry
```

**Comment by systemlogic** [comment]
@facundomedica when you say `add port 30051 to the istio-ingressgateway` does it mean you have edited `kubectl edit svc istio-ingressgateway -n istio-system` and added something like
```
  - name: grpc
    nodePort: 31124       #Node port is automatically picked
    port: 30051
    protocol: TCP
    targetPort: 30051
```
I am following the same way. and here is my gateway and VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 30051
      name: grpc
      protocol: GRPC
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc
spec:
  hosts:
  - "*"
  gateways:
  - grpc-gateway
  http:
  - match:
    - port: 30051
    route:
    - destination:
        port:
          number: 50051
        host: grpchelloworld
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpchelloworld
  name: grpchelloworld
  namespace: default
spec:
  clusterIP: 172.21.171.7
  ports:
  - name: http
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpchelloworld
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
```
Let me know what I am doing wrong.
NOTE: I am doing all this on IBM blue cloud and able to access the app using nodeport settings.

**Comment by sjtuprog** [comment]
Thank you guys for the help. I just successfully configured gRPC load balancing with Istio on GKE. The two lessons I learned are 
1. Use local DNS(/etc/hosts) for your self-defined host name, especially when you don't have a public domain.
2. Use port 31400 instead of 80 for Gateway if you are using the default istio-ingressgateway.

**Comment by howardjohn** [comment]
Thanks for all the help on this -- from what I can tell this looks resolved. If there are more issues feel free to open a new bug, as any comments here will probably get lost

**Comment by sandeeplamb** [comment]
> @JCzz I got it working! And also added TLS! I added the port 30051 to the istio-ingressgateway but you can use 31400 without any changes (I don't know if other service uses this port, but it is enabled by default). My service is called `gateway` and exposes an http server and the gRPC service (if there is too much confusion I'll refactor the examples below).
> 
> For my TLS certificates I've used Let's Encrypt.
> 
> The gateway:
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: gateway-gateway
>   namespace: development
> spec:
>   selector:
>     istio: ingressgateway # use istio default controller
>   servers:
>   - port:
>       number: 30051
>       name: grpc
>       protocol: https
>     tls:
>       mode: SIMPLE      
>       serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
>       privateKey: /etc/istio/ingressgateway-certs/tls.key
>     hosts:
>     - "development.redacted.co"
>   - port:
>       number: 80
>       name: http
>       protocol: HTTP
>     hosts:
>     - "development.redacted.co"
> ```
> 
> VirtualService:
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: gateway
>   namespace: development
> spec:
>   hosts:
>   - "development.redacted.co"
>   gateways:
>   - gateway-gateway
>   http:
>   - match:
>     - uri:
>         prefix: /api/
>     rewrite:
>       uri: /
>     route:
>     - destination:
>         host: gateway
>         port:
>           number: 5000
>   - match:
>     - port: 30051
>     route:
>     - destination:
>         host: gateway
>         port:
>           number: 50051
> ```
> 
> Service:
> 
> ```yaml
> kind: Service
> apiVersion: v1
> metadata:
>   name: gateway
>   namespace: development
>   labels:
>     app: gateway
> spec:
>   selector:
>     app: gateway
>   ports:
>     - port: 50051
>       name: grpc
>     - port: 5000
>       name: http
> ```

Is that all you need for grpc tls

**Comment by sands6** [comment]
@sandeeplamb In your case, trying out without `tls` work? I mean setting your Gateway resource to listen without tls.

**Comment by sands6** [comment]
Nevermind. I figured it out. `nginx.ingress.kubernetes.io/upstream-vhost` annotation is required in case Nginx is fronting Istio gateway in case of `GRPC`

**Comment by sandeeplamb** [comment]
> Nevermind. I figured it out. `nginx.ingress.kubernetes.io/upstream-vhost` annotation is required in case Nginx is fronting Istio gateway in case of `GRPC`

@sands6 Yeah for me I am using Istio, so it works with plane GRPC mode without TLS and also with GRPC and TLS. No problem at all.
But I have seen you already have a solution now

**Comment by sands6** [comment]
@sandeeplamb I want to learn from your experience of using Istio-gateway at the edge. Are you running Istio gateway in `host-network` mode or LB fronting istio gateway? How do manage multiple `vhost` endpoints point to gateway with different protocols http/https/grpc as we have to use different port for `grpc`?

**Comment by sandeeplamb** [comment]
> @sandeeplamb I want to learn from your experience of using Istio-gateway at the edge. Are you running Istio gateway in `host-network` mode or LB fronting istio gateway? How do manage multiple `vhost` endpoints point to gateway with different protocols http/https/grpc as we have to use different port for `grpc`? in your example above, port `30051`

In our case, we have AWS-NLB in front as LB which is created using terraform. 
**istio-ingressgateway** service created as NodePort and all ports in service have corresponding NodePort with them. 
`  ports:
    -
      name: status-port
      port: 15020
      targetPort: 15020
      nodePort: 31952
    -
      name: http2
      port: 80
      targetPort: 80
      nodePort: 30314
    -
      name: https
      port: 443
      targetPort: 443
      nodePort: 31454
    - 
      name: grpc
      port: 31400
      nodePort: 31400`
All these nodeports are listening at NLB with Targets are EKS worker nodes.
We have just 4 ports open at NLB 80,443,15020(status), **31400**(we use as grpc).
For more grpc ports, you can add more ports in **istio-ingressgateway** service.
Create gateway with same host together and separate virtual hosts/destination-rules

**Comment by nelsonyaccuzzi** [comment]
> > hello, @JCzz
> > ```yaml
> > apiVersion: networking.istio.io/v1alpha3
> > kind: Gateway
> > metadata:
> >   name: backend-gateway
> > spec:
> >   selector:
> >     istio: ingressgateway # use Istio default gateway implementation
> >   servers:
> >   - port:
> >       number: 9090
> >       name: grpc-gateway
> >       protocol: GRPC
> >     hosts:
> >     - "*"
> > ---
> > apiVersion: networking.istio.io/v1alpha3
> > kind: VirtualService
> > metadata:
> >   name: backend
> > spec:
> >   hosts:
> >   - "*"
> >   gateways:
> >   - backend-gateway
> >   http:
> >   - match:
> >     - uri:
> >         prefix: /
> >     route:
> >     - destination:
> >         host: backend
> >         port:
> >           number: 50051
> > ```
> > 
> > 
> > ```yaml
> > apiVersion: v1
> > kind: Service
> > metadata:
> >   name: istio-ingressgateway
> >   namespace: istio-system
> >   annotations:
> >     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
> >   labels:
> >     chart: gateways-1.0.0
> >     release: RELEASE-NAME
> >     heritage: Tiller
> >     app: istio-ingressgateway
> >     istio: ingressgateway
> > spec:
> >   type: LoadBalancer
> >   selector:
> >     app: istio-ingressgateway
> >     istio: ingressgateway
> >   ports:
> >     -
> >       name: http2
> >       nodePort: 31380
> >       port: 80
> >       targetPort: 80
> >     -
> >       name: https
> >       nodePort: 31390
> >       port: 443
> >     - 
> >       name: grpc
> >       nodePort: 31399
> >       port: 9090
> >       targetPort: 9090
> > ```
> > 
> > 
> > I run it on azure platform
> 
> @JCzz I just saw you exposed your service via "prefix: /" in **VirtualService**, how can you expose other gRPC services?

Someone got this working?

I have several GRPC services that need to be exposed via Istio Ingress Gateway, how do I route to them? I tried changing the prefix and no luck, the istio config in the ingress gateway always set the prefix of the service in "/"

**Comment by joshuakruger** [comment]
@nelsonyaccuzzi by changing the prefix did you mean doing something like this:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - my.domain.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - my.domain.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: my-domain-cert
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs
  namespace: istio-system
spec:
  gateways:
  - istio-system/my-gateway
  hosts:
  - my.domain.com
  http:
  - match:
    - uri:
        prefix: /helloworld.Greeter/
    route:
    - destination:
        host: hello.default.svc.cluster.local
        port:
          number: 3000
  - match:
    - uri:
        prefix: /hotel.Rates/
    route:
    - destination:
        host: hotel.default.svc.cluster.local
        port:
          number: 3000
```

This works for me (using istio 1.5.0). 
* I've made no changes to the `istio-ingressgateway` Service.
* The prefixes are the FQN of the gRPC packages
* TLS is working, if testing with [grcp_cli](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md) be sure to do: `grpc_cli --channel_creds_type=ssl ...`

Hope it helped.
