### ISSUE TITLE
Non-globally unique VirtualService name causes periodical connection drops on the ingress gateway

### ISSUE THREAD

**Issue by nberthet** [istio/istio#7926]
**Describe the bug**
Using the same .metadata.name for VirtualService in different namespaces, causes envoy listener to be added periodically and leads to disconnections (websocket in my case).
The interval of this event is irregular, in my environment, it ranged from a few seconds to half an hour.

To get an idea of the irregularity, here is an extract of the stackdriver logs from the example yaml in the steps to reproduce:
```
 [2018-08-15 04:46:50.819][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 04:46:56.405][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 04:59:19.424][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 05:00:19.427][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 05:10:19.414][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 05:11:19.408][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 05:34:19.421][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
 [2018-08-15 05:35:19.417][24][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
```

**Expected behavior**
Using the same VirtualService name in different namespace should not conflict, or there should be a clear warning / validation error when a conflict happens.

**Steps to reproduce the bug**
- create a gateway 
- create 2 VirtualService with the same name, in different namespaces, each of them bound to the gateway with a different host name
- the ingress gateway logs will contain `[info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'` at irregular intervals
- whenever this message appears in the log, all active connections are closed by envoy

I couldn't confirm, but it seems that having some traffic is necessary for the issue to manifest; the issue seems to take longer (or even not happen) when the cluster is idle. I wasn't able to find a way to make the issue happen systematically, but it seems with enough requests (>1s), the problem would occur almost every minute, at the same second.

Example yaml to reproduce:

Note:  you'll need a proper TLS certificate and to update the domain names

```
---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: ns1
    labels:
      istio-injection: enabled
  spec:
    finalizers:
    - kubernetes
---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: ns2
    labels:
      istio-injection: enabled
  spec:
    finalizers:
    - kubernetes
---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    namespace: ns1
    name: gateway
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    namespace: ns1
    name: buggy
  spec:
    gateways:
    - gateway.ns1.svc.cluster.local
    hosts:
    - 'ns1.example.com'
    http:
    - match:
      - uri:
          prefix: /v1
      route:
      - destination:
          host: dummy
          port:
            number: 8080
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    namespace: ns2
    name: buggy
  spec:
    gateways:
    - gateway.ns1.svc.cluster.local
    hosts:
    - 'ns2.example.com'
    http:
    - match:
      - uri:
          prefix: /v2
      route:
      - destination:
          host: dummy.ns1.svc.cluster.local
          port:
            number: 8080
---
  kind: Service
  apiVersion: v1
  metadata:
    namespace: ns1
    name: dummy
  spec:
    selector:
      app: dummy
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: http
```

**Version**
Istio 0.8 / GKE 1.9.7
```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No

**Environment**
GKE 1.9.7 / Istio 0.8
