### ISSUE TITLE
Istio give `x-forwarded-proto=http` to upstream server when using SSL termination

### ISSUE THREAD

**Issue by chanjarster** [istio/istio#7964]
**Describe the bug**

Istio give `x-forwarded-proto=http` to upstream server when using SSL termination.

**Expected behavior**

Istio give `x-forwarded-proto=https`

**Steps to reproduce the bug**

1. Deploy a nginx with SSL termination on a domain, change `<your domain name>`, [config file][1]
1. Deploy an `echo-server` app, see yaml file below, change `<your domain name>`, [config file][2]
1. `curl http://<your domain name>/echo-server-istio`, got:
   ```
   ...
   Request Headers:
	x-forwarded-port=80
	x-forwarded-proto=http
   ...
   ```
1. `curl https://<your domain name>/echo-server-istio`, got:
   ```
   ...
   Request Headers:
	x-forwarded-port=443
	x-forwarded-proto=http
   ...
   ```

Note the `x-forwarded-port=443` is correct but `x-forwarded-proto=http` is wrong.

**Version**

```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version --short
Client Version: v1.11.2
Server Version: v1.11.1
```

**Is Istio Auth enabled or not?**

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set gateways.istio-ingressgateway.type=NodePort \
  --set gateways.istio-egressgateway.type=NodePort \
  --set tracing.enabled=true \
  --set servicegraph.enabled=true \
  --set grafana.enabled=true
```

**Environment**

On-premise Openstack cloud

**Cluster state**

Too big, not uploaded

[1]: https://gist.github.com/chanjarster/a0529d14466895de1ea69866d69c107c#file-vh_echo-conf
[2]: https://gist.github.com/chanjarster/a0529d14466895de1ea69866d69c107c#file-echo-server-yaml

**Comment by ijsnellf** [comment]
cc @rshriram

**Comment by swistaczek** [comment]
Hey, is there any way to set ```x-forwarded-proto`` header?

**Comment by swistaczek** [comment]
I "hot-fixed" this issue with following VirtualService:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-route
  namespace: keycloak
spec:
  hosts:
  - auth.tonikstudio.xyz
  gateways:
  - keycloak-gateway
  http:
  - match:
    - uri:
        prefix: /auth/realms
    - uri:
        prefix: /auth/resources
    - uri:
        prefix: /auth/js
    - uri:
        prefix: /auth/admin
    route:
    - destination:
        host: keycloak-http
        port:
          number: 80
    appendHeaders:
        "x-forwarded-proto": "https"
        "x-forwarded-port": "443"
```

**Comment by vadimi** [comment]
I'm experiencing the same issue. I have AWS ALB that forwards `x-forwarded-port` and `x-forwarded-proto`, My app receives `x-forwarded-port` as `443`, but `x-forwarded-proto` as `http`. Is there anything in the configuration I need to do?

**Comment by AWKIF** [comment]
Hello,
Do the appendHeaders allow to rewrite the header ? I had no success on my side, i'm able to add headers but not rewriting them.
I saw that in 1.1 we should be able to remove headers, so i could remove and then re-add with the correct value. Is that the way to do it ?
Thanks

**Comment by vadimi** [comment]
@AWKIF `appendHeaders` didn't work for me either. But I was able to setup a filter to do this:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-app-filter
spec:
  workloadLabels:
    app: my-app
  filters:
  - listenerMatch:
      portNumber: 5120
      listenerType: SIDECAR_INBOUND
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:headers():replace("x-forwarded-proto", "https")
        end
        function envoy_on_response(response_handle)
        end
```

**Comment by gunhu** [comment]
Hi,

I will try this work-around today thank you @vadimi :)

Nonetheless I think it will be a good thing to have a KISS method to do this in the future :)

Regards,

**Comment by dstockton** [comment]
👍

**Comment by 6869dan** [comment]
Hi - saw mention of keycloak here...
I am getting the "HTTPS Required" error on a keycloak instance we are accessing via an AWS ALB into istio ingressgateway. If I remove istio ingress from the equation ie ELB -> keycloak it works as expected. 
I tried the filter and appendHeaders suggestions here but without any joy. Was anyone able to get keycloak to work using istio ingressgateway and/or able to offer any more ideas pls?

**Comment by dstockton** [comment]
FYI I couldn't reproduce this with 1.0.2
My issue was that the destination host was fronted by an ELB which itself was replacing the ```X-Forwarded-Proto``` header 🤦‍♂️

**Comment by ermik** [comment]
I am facing this issue on 1.0.4 with istio mesh positioned behind ambassador proxy, which routes requests to `ingressgateway` envoy after terminating TLS. Ambassador does not support L4 and originating another TLS connection going upstream just made `ingressgateway` produce 503s with no logged errors. I finally gave up and decided to route everything after ambassador over http into the mesh, only to hit this issue when request got to the pod where [ory/hydra](github.com/ory/hydra) expected to see `X-Forwarded-Proto:` set to `https` on requests from `127.0.0.1/32`.
```
hydra-web | Dec 11, 2018, 3:39:49 PM | time="2018-12-11T20:39:49Z" level=warning msg="Could not serve http connection" error="Expected X-Forwarded-Proto header to be https, got http"
hydra-web | Dec 11, 2018, 3:39:49 PM | time="2018-12-11T20:39:49Z" level=info msg="started handling request" method=GET remote="127.0.0.1:56914" request=/ request_id=02c724e7-a332-9d93-99a0-8e14cc06ca90
```

**Comment by ermik** [comment]
.

**Comment by fico-jessecarroll** [comment]
Just for everyone else, I too encountered this issue and was able to successfully resolve with the following filter; you can of course make it more specific to a service via the listenerMatch.   Was really a catch-all:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-app-filter
spec:
  workloadLabels:
    istio: ingressgateway
  filters:
  - filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:headers():replace("x-forwarded-proto", "https")
        end
        function envoy_on_response(response_handle)
        end
```

**Comment by springrain** [comment]
Can I only use envoyFilter at the moment?

**Comment by GregoireW** [comment]
Hello,

On Istio the [http route](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRoute)  accept a headers parameter to manipulate those [Description on this](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#Headers)

So you can have in a virtual service:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxxxx
  namespace: yyyyy
spec:
  hosts:
    - "zzzzzz"
  gateways:
    - istio-system/http-gateway
  http:
  - route:
    - destination:
        host: aaaaaaaa
        port:
          number: 8080
    headers:
      request:
        set:
          x-forwarded-proto: https
          x-forwarded-port: "443"
```

**Comment by fico-jessecarroll** [comment]
You would have to do that for every route, where the previous example is a catch-all.

**Comment by azalenski-callpage** [comment]
Is there any update on this one? Unfortunately I am also facing the same issue when Istio sits behind AWS an TLS Terminating Load Balancer. Is there any estimate on when this will be fixed?

**Comment by AWKIF** [comment]
thanks a lot @GregoireW it works fine

**Comment by jh-sz** [comment]
What's the status of this? We have both `http` (for legacy reasons) and `https` traffic coming through to the load balancer, and we don't want to just change the header. Is there a proper solution for this and just having `x-forwarded-proto` header passing through as it is?

**Comment by howardjohn** [comment]
I think this can done with some combination of https://github.com/envoyproxy/envoy/pull/7995 and https://github.com/istio/istio/wiki/EnvoyFilter-Samples#use-remote-address-and-xff-num-trust-hops if someone has a chance to try it out

**Comment by colincoghill** [comment]
Just be careful with some of the workarounds here, if you override set the X-Forwarded-Proto header yourself, instead of thinking they're being accessed over HTTP when they're not, they'll now think they're being accessed over HTTPS when they're not. So things that, eg., redirect the user to HTTPS, won't trigger and a lot of stuff might be being made available insecurely.

Looks like a fix is upstream in envoy now, so hopefully it'll filter through to Istio soon.

**Comment by jh-sz** [comment]
@howardjohn a newbie question, how do i find out what version of envoy that PR merged to? And what version is used by istio 1.2.5? I am keen to test this out today if that's come through to istio

**Comment by jh-sz** [comment]
OK, came across this issue https://github.com/istio/istio/issues/12549 so it's out as part of v1.3.x, i have tested it with istio v1.4.0 and it's working.

slightly different compares to what @howardjohn given, since the discussion relates to ssl termination, therefore mostly the front proxy node (ingressgateway), so i include the label to target specifically for `istio-ingressgateway`.  It's also recommended by the [envoy doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for) to set ``use_remote_address` for edge node only 

> In general, use_remote_address should be set to true when Envoy is deployed as an edge node (aka a front proxy), whereas it may need to be set to false when Envoy is used as an internal service node in a mesh deployment.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff-trust-hops
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          use_remote_address: true
          xff_num_trusted_hops: 1
```

**Comment by saksmt** [comment]
That's just f*cking hilarious. Just got here after losing a battle with #6486 - got an edge ssl terminating reverse proxy and with a run flew into another wall. This one. After five days of after-work nine hour marathons in trying to deploy my very own istio cluster on VDS I end up asking myself if there anything that works properly out-of-the box with istio?

P.S. @jh-sz, thanks, works like a charm

**Comment by fredsted** [comment]
The EnvoyFilter above works for me too, thanks so much!

**Comment by pawelprazak** [comment]
I can confirm that workaround from https://github.com/istio/istio/issues/7964#issuecomment-554241818 works with 1.14 and does not work with 1.13 (at least I couldn't get it to work with this version).

**Comment by fredsted** [comment]
Now that Istio 1.5 is out, does anyone know whether the EnvoyFilter fix applies to the new version, or whether it's needed at all?

**Comment by markitoxs** [comment]
I still need it with ALB and 1.5

**Comment by gustavovalverde** [comment]
OMG, I had 3 full days having the same problems as OP using nginx as a front proxy.

Thank you @jh-sz, this was my last missing piece for my setup and also @Stono, who hit this walls a long time ago and have a few good issues here on the subject

**Comment by IGassmann** [comment]
Any workaround for knative-serving?

**Comment by gustavovalverde** [comment]
With this setup: `nginx --> ingress-gateway --> VirtualService --> Pod` now my actual problem is that nginx is getting an 15s timeout which I don't find a way to change.

**Comment by Cynocracy** [comment]
Still having customer reports of this issue. Any progress?

**Comment by howardjohn** [comment]
See https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/ for info on configuring these with first class API

**Comment by SCLogo** [comment]
any fix for stable version (1.6) ?

**Comment by IGassmann** [comment]
Pinging @howardjohn @hzxuzhonghu to reopen the issue.

**Comment by howardjohn** [comment]
We can reopen but please clarify what is required here that https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/ does not provide

**Comment by SCLogo** [comment]
The only reason is we really don't like to use prealpha in production and we would like to use the stable (at least beta) version of the any api. Probably that will solve the issue, but currently we use 1.6 and not 1.7

**Comment by howardjohn** [comment]
@SCLogo that is a valid concern. We currently have two options:
* EnvoyFilter
* Alpha api

There will not be a third; instead we will promote the alpha API.

Based on this, I think there is no additional work to do here beyond https://github.com/istio/istio/issues/26783. Thanks!

**Comment by HengJunXi** [comment]
For those who decided to go for the EnvoyFilter option, https://github.com/istio/istio/issues/7964#issuecomment-554241818 works for me. 

Due to depreciation, I've changed: 
- `"envoy.http_connection_manager"` => `"envoy.filters.network.http_connection_manager"`
- `"type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"` => `"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"`

Reference: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto

Works well on Istio 1.9

**Comment by dudicoco** [comment]
For anyone who's running into this issue and wants envoy to explicitly set the header (rather than getting it from a proxy in a previous hop), here are two ways to do it currently based on suggestions in this thread:

1. Lua filter

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-gateway
  namespace: my-ns
spec:
  workloadSelector:
    labels:
      app: my-gateway

  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 443
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          defaultSourceCode:
            inlineString: |
              function envoy_on_request(request_handle)
                request_handle:headers():replace("x-forwarded-proto", "https")
              end
```

2. Merge with route configuration:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-gateway
  namespace: my-ns
spec:
  workloadSelector:
    labels:
      app: my-gateway

  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 443
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - header:
            key: x-forwarded-proto
            value: https
          append: false
```


Note that I've set the filters to only modify requests arriving on port 443, when using http redirect this is desired.

The route configuration is definitely preferable as it's much more simple, however, i'm not sure which option would give better performance with less overhead. @howardjohn do you have any input on this matter?
