### ISSUE TITLE
Allow to apply HTTPRewrite on the destination level

### ISSUE THREAD

**Issue by pamelin** [istio/istio#8026]
Currently our app in the kube is sending all requests to the service A. We want to route 50% of requests to this service and 50% to the external service.

We have achieved it with the below `VistualService` however in order for this to work we need to rewrite authority. Currently you can rewrite authority etc... only per route which means that traffic to service in kube will have authority rewritten as well. Ideally we would like to apply rewrite rules on the destination level.

Below is an example `VirtualService` we have used.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: a-route
spec:
  hosts:
  - a
  http:
  - route:
    - destination:
        host: a
      weight: 50
    - destination:
        host: a.com
      weight: 50
    rewrite:
      authority: a.com
```
