### ISSUE TITLE
ingressgateway can't access https service. 

### ISSUE THREAD

**Issue by lubinson** [istio/istio#8029]
**Describe the bug**
_I tried to set up a gateway and virtual service for an https service. But the gateway can only send clear http request to the https service. And the https service return 400 Bad Request - The plain HTTP request was sent to HTTPS port._ 

**Expected behavior**
_https request should be sent from gateway to https service._

**Steps to reproduce the bug**
1, Install the my-nginx project from istio sample. This is a https service. 
2, add gateway as below
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE #enables HTTPS on this port
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
3, add virtual service
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-nginx
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - match:  
    - uri:
        prefix: "/"  
    route:
    - destination:
        host: my-nginx
        port:
          number: 443
```
4, run test
run below command. I use NodePort. The 10.0.0.27 is the node IP, 31390 is the node port. 
```
curl https://10.0.0.27:31390 -k
```
run result
```
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.11.3</center>
</body>
</html>
```
**Version**
_What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`_
istioctl version
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not?**
_Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input._
```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
```
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true
```
**Environment**
_Which environment, cloud vendor, OS, etc are you using?_
```
Linux k8s-m 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
**Cluster state**
_If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue._

**Comment by ijsnellf** [comment]
cc @vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment]
@lubinson @ijsnellf let me describe how to configure it, will submit a PR to istio.io.

**Comment by vadimeisenbergibm** [comment]
@lubinson Here is the example I wrote 
https://preliminary.istio.io/docs/examples/ingress-for-https/

Note that you have to use `PASSTHROUGH` `tls` `mode` since the gateway must not perform TLS termination. Also note that the `VirtualService` should have `tls` match by `sni_hosts`.

**Comment by lubinson** [comment]
@vadimeisenbergibm 

Thanks. I have tried on Nginx Service. It works, even set ```sni_hosts``` to "*" in the VirtualService and even just using ```curl -i https://10.0.0.27:31390 -k```. My Gateway and VirtualService files are listed as below:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-nginx
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*"
    route:
    - destination:
        host: my-nginx
        port:
          number: 443
```
Run 
```
curl -i https://10.0.0.27:31390 -k
```
Result
```
HTTP/1.1 200 OK
Server: nginx/1.11.3
Date: Tue, 21 Aug 2018 18:52:52 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 26 Jul 2016 14:54:48 GMT
Connection: keep-alive
ETag: "579779b8-264"
Accept-Ranges: bytes

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```
Then I apply the same steps to my service. I got below error reported by curl. 
```
curl: (35) Encountered end of file
```
I found the ingress gateway send ```"Unknown CA"``` to the HTTPS service when handshaking. 

I thought it should be successful same as using ```-k``` option (ingore certificate verification) to access Nginx https service. But unfortunately not.

Then I follow your way to generate cert and key, use it to replace the cert and key in my service. Then use curl with ```--cacert``` option. But still the same failure. 

Why I did nothing it succeed when accessing Nginx service. But failed on my own service with all necessary steps. My service is a java service using keystore to store cert and keys. It didn't use secrets in k8s. 

Best Regards.

**Comment by vadimeisenbergibm** [comment]
@lubinson 

Do you manage to call your HTTPS service from inside the cluster? Also note that the example has been moved to https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/.

**Comment by lubinson** [comment]
@vadimeisenbergibm 

This HTTPS service can be directly accessed by web browser by using the Node IP and Service Node Port (not the ingress node port). And also can be directly accessed by ```curl -i https://10.0.0.27:5443 -k ```. 5443 is the service node port. 

All these cmds including the failed and successed cases are running in the master node of the cluster. 

Yes, I have already follow the preliminary url you given. Thanks.

**Comment by vadimeisenbergibm** [comment]
@lubinson Getting back to the issue, did you manage to fix it? Is it still relevant?

**Comment by kongyi-ibm** [comment]
Except the SSL passthrough, do we have any other solution can let ingressgateway to terminal SSL and send https request to backend https service ?

I want to implement the solution like this:

https request --> ingressgateway --> https service 

gateway:
===================================
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt

virtualserivce:
========================================
spec:
  gateways:
  - mygateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /search
    route:
    - destination:
        host: search.default.svc.cluster.local
        port:
          number: 3738

But when I use curl to access, the ingress always report 503. But I can curl from the envoy sidecar and get correct response

[root@pe103 ~]# curl -v -k https://9.112.245.103:31390/search/admin/resources/health/ping
* About to connect() to 9.112.245.103 port 31390 (#0)
*   Trying 9.112.245.103...
* Connected to 9.112.245.103 (9.112.245.103) port 31390 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* Server certificate:
*       subject: CN=*
*       start date: Jun 09 15:40:43 2017 GMT
*       expire date: May 26 03:41:13 2027 GMT
*       common name: *
*       issuer: CN=testcert.watsoncommerce.ibm.com
> GET /search/admin/resources/health/ping HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 9.112.245.103:31390
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Mon, 26 Nov 2018 16:57:17 GMT
< server: envoy
< x-envoy-upstream-service-time: 8
<
* Connection #0 to host 9.112.245.103 left intact

========================================================
[root@pe103 ~]# istioctl authn tls-check search.default.svc.cluster.local
HOST:PORT                                 STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
search.default.svc.cluster.local:3738     OK         HTTP       HTTP       -                -

**Comment by lubinson** [comment]
@vadimeisenbergibm Sorry, not have change to try again after latest reply to you. Will try again these several days.

**Comment by kongyi-ibm** [comment]
@vadimeisenbergibm the TLS PASSTHROUGH can works on my environment.  Thanks!

But I just wondering If there have any other approach which is most like ( enable secret backend on ingress) to terminate TSL at ingressgateway (At Front ) and send https to backend https service

**Comment by lubinson** [comment]
@vadimeisenbergibm 

This time succeed! I don't know what happened. I think most prossibly is the sidecar injection. Last time maybe I forget to inject it again after server times try. ~~ 

Another question is I want to confirm the messages between ingressgateway and service is using http/2. Then I dump the tcp packets. But the packets can't be decode into http messages using wireshark which is ok for direct service calling and packets between test client and ingressgateway.

Thanks.

**Comment by vadimeisenbergibm** [comment]
@kongyi-ibm Yes, terminating TLS and originating TLS by the gateway should work. You just create  a DestinationRule to your service, and specify `tls` mode as SIMPLE. Something like:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-my-service
spec:
  host: myservice
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS
```
