### ISSUE TITLE
port naming issue on gateways with https on istio 1.0.0

### ISSUE THREAD

**Issue by visheyra** [istio/istio#8073]
**Describe the bug**
I'm using istio 1.0.0 and I'm experiencing v3 api on it with some services

I have one services that serve a webapp, and another one that when contacted do a 302 redirect to the external url of the first one.

My istio networking resources are the following:

2 gateways (one per domain / service, sharing the same wildcard certificate)
2 virtualservices (one per service exposed)

My gateways are configured as follows:

redirect
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gate-redirect
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
   - port:
       number: 443
       name: https
       protocol: HTTPS
     hosts:
     - "some.domain.io" # i have letsencrypt for this
     tls:
       mode: SIMPLE
       serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
       privateKey: /etc/istio/ingressgateway-certs/tls.key
```

redirected
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gate-redirect
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
   - port:
       number: 443
       name: https
       protocol: HTTPS
     hosts:
     - "other.domain.io" # i have letsencrypt for this
     tls:
       mode: SIMPLE
       serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
       privateKey: /etc/istio/ingressgateway-certs/tls.key
```
When applied I'm getting the following log

```
port https.443.HTTPS: non unique port name for HTTPS port
```

And when I try to reach the service deployed behind the gateway applied in second I have a => `SSL_SYSCALL_ERROR`

When naming the port as https-redirector / https-redirected it is working

Also when I only set http port, I don't have any issues naming both of them `http` this works.

Also I've attempted top debug using 2 differents certificates for my different domains. For my test one was a wildcard letsencrypt and the other one was a one-line self-sign generation.

**Expected behavior**

This configuration should works

**Steps to reproduce the bug**

apply thos files (+ corresponding virtualservices / services) on istio 1.0.0 setup

**Version**
 istio 1.0.0

**Is Istio Auth enabled or not?**

no

**Environment**

k8s on top of AWS installed w/ kops
