### ISSUE TITLE
istioctl kube-inject panics.

### ISSUE THREAD

**Issue by depohmel** [istio/istio#8143]
**Describe the bug**
I'm trying to use `istioctl` to ingest sidecar into deployment spec and it panics. 

**Expected behavior**
I expect `istioctl` to return updated spec

**Steps to reproduce the bug**
1. install istio into none default namespace.
2. create a simple `deployment.yaml`
```
cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
3. run istioctl 
```
istioctl kube-inject -f deployment.yaml -i test-namespace
panic: template: inject:10: function "annotation" not defined

goroutine 1 [running]:
text/template.Must(0x0, 0x1a88640, 0xc420488720, 0x0)
	/usr/local/go/src/text/template/helper.go:23 +0x54
istio.io/istio/pilot/pkg/kube/inject.injectionData(0xc4205d4000, 0xe25, 0xc4200d7840, 0x40, 0xc420401600, 0xc420401518, 0xc42052a1e0, 0xc420036000, 0x190e9a0, 0xc420401000, ...)
	/workspace/go/src/istio.io/istio/pilot/pkg/kube/inject/inject.go:385 +0x2f8
istio.io/istio/pilot/pkg/kube/inject.intoObject(0xc4205d4000, 0xe25, 0xc420036000, 0x1a935e0, 0xc420401000, 0x0, 0x0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/pilot/pkg/kube/inject/inject.go:539 +0x4df
istio.io/istio/pilot/pkg/kube/inject.IntoResourceFile(0xc4205d4000, 0xe25, 0xc420036000, 0x1a8ab20, 0xc42038e638, 0x1a8ab40, 0xc42000c018, 0xc, 0x1929a85)
	/workspace/go/src/istio.io/istio/pilot/pkg/kube/inject/inject.go:436 +0x279
main.glob..func3(0x25834e0, 0xc4203ea000, 0x0, 0x4, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/istioctl/cmd/istioctl/kubeinject.go:317 +0x72b
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0x25834e0, 0xc42043d180, 0x4, 0x4, 0x25834e0, 0xc42043d180)
	/workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:756 +0x468
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2583740, 0xc42058bf78, 0xc42058bf78, 0x403dfc)
	/workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:846 +0x30a
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(0x2583740, 0x1c, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/workspace/go/src/istio.io/istio/istioctl/cmd/istioctl/main.go:651 +0xb6

```

**Version**
```
istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
**Is Istio Auth enabled or not?**
N/A
**Environment**
```
lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
``` 

**Cluster state**
n/a
