### ISSUE TITLE
OPA adapter: input set condition evaluation error: id='4', error='lookup failed: 'destination.service.name''

### ISSUE THREAD

**Issue by bluecamel** [istio/istio#8163]
**Describe the bug**
I am having a really tough time getting the OPA adapter to work.  I am able to create a combination of authorization instance, rule, and OPA handler that works for the bookinfo app.  However, I am unable to get it to work for our services.

When applying the exact same authorization instance and OPA handler with a rule that only differs by the match service name, we get errors in the istio-policy istio-proxy logs get flooded with this error:

```
input set condition evaluation error: id='4', error='lookup failed: 'destination.service.name''
```

Also, potentially related, the istio-proxy logs for the service show this:

```
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:160] Add a new Referenced for check cache: Absence-keys: destination.service, destination.service.name, source.uid, Exact-keys: context.protocol, context.reporter.kind, destination.namespace, destination.port, destination.uid, source.ip,
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:160] Add a new Referenced for check cache: Absence-keys: destination.service, destination.service.name, source.uid, Exact-keys: context.protocol, context.reporter.kind, destination.namespace, destination.port, destination.uid, source.ip,
```

I can't find documentation on what this means, but it seems that it may be related to what's keeping the attribute from working in a rule match.

When I remove the destination.service.name condition and only match based on destination.namespace, the policy works, but I am unable to apply it to a specific service.

**Expected behavior**
Rule match to work and policy to be applied.

**Steps to reproduce the bug**
```
apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: opa-bookinfo-productpage-instance
  namespace: istio-system
spec:
 subject:
   properties:
     authorization: request.headers["authorization"]
 action:
   namespace: destination.namespace | "default"
   service: destination.service.host | "default"
   path: request.path
   method: request.method
---
apiVersion: config.istio.io/v1alpha2
kind: opa
metadata:
  name: opa-bookinfo-productpage-handler
  namespace: istio-system
spec:
  checkMethod: data.mixerauthz.allow
  failClose: true
  policy:
    - |+
      package mixerauthz

      default deny = true
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: opa-bookinfo-productpage-rule
  namespace: istio-system
spec:
  match: destination.namespace == "bookinfo" && destination.service.name == "productpage"
  actions:
  - handler: opa-bookinfo-productpage-handler.opa
    instances: [ opa-bookinfo-productpage-instance.authorization ]
```

**Version**
1.0.0

**Is Istio Auth enabled or not?**
Not enabled.

**Environment**
GKE 1.9.7-gke.5
