### ISSUE TITLE
Enabling Authentication Policy causes `upstream connect error or disconnect/reset before headers`

### ISSUE THREAD

**Issue by yellowred** [istio/istio#8218]
**Describe the bug**
I have finished Authorization Task and enabled RBAC successfully. But in order to add JWT authorization I need enable Authentication. So I added a Policy from Authentication task:
```
cat <<EOF | kubectl apply -n foo -f -
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: httpbin
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.0/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
EOF
```
After that curl starts to fail:
```
curl --header "Authorization: Bearer $TOKEN" http://${GATEWAY_URL}/productpage -sv

*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /productpage HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer <token>
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Fri, 24 Aug 2018 10:56:41 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
upstream connect error or disconnect/reset before headers
```
After I delete that policy everything works properly.

**Expected behavior**
Expect HTTP 200 or at least HTTP 401.

**Steps to reproduce the bug**
Install Istio 1.0 with mTLS enabled. Complete Authorization task. Add JWT Policy.

**Version**
Istio 1.0
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
yes

**Environment**
Docker for Mac

**Cluster state**
https://www.dropbox.com/s/766iidgp9rlqkvo/istio-dump.tar.gz?dl=0

**Comment by fadeojo** [comment]
I am having the same issue.

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: userjwt
  namespace: pronto
spec:
  targets:
    - name: users-cluster-ip-service
  origins:
    - jwt:
        issuer: "https://fadeojo.auth0.com/"
        jwksUri: "https://fadeojo.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN

```
What am I doing wrong?
