### ISSUE TITLE
1.0.x istio-autogenerated-k8s-ingress gateway uses 0.8 ingress selector

### ISSUE THREAD

**Issue by louisvernon** [istio/istio#8231]
**Describe the bug**
Helm templated YAMLs from the istio-1.0.x release template in the 0.8 ingress selector 
 in the autogenerated gateway.

**Expected behavior**
I would expect the gateway istio-autogenerated-k8s-ingress to have a selector that matches the labels of the istio-ingressgateway service.
```
  selector:
    istio: ingressgateway
```
Instead we get:
```
  selector:
    istio: ingress
```
In this 
https://github.com/istio/istio/blob/8daa232df6ef7cdbb2987de1187255b14e3c3989/install/kubernetes/helm/istio/charts/pilot/templates/gateway.yaml#L8

which is templated in from https://github.com/istio/istio/blob/cf98675aa3d65dbfdfe6c164110cea38de41d87a/install/kubernetes/helm/istio/values.yaml#L16

**Steps to reproduce the bug**
```
$ curl -L https://git.io/getLatestIstio | sh -
$ export PATH="$PATH:/tmp/istio-1.0.1/bin"
$ cd istio-1.0.1/
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system > istio.yaml
$ grep "^kind: Gateway" istio.yaml -A6
kind: Gateway
metadata:
  name: istio-autogenerated-k8s-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingress
```
`istio: ingress`
```
$ grep "^kind: Service$" istio.yaml -A15 | grep "^  name: istio-ingressgateway" -B3 -A14 
--
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
  labels:
    chart: gateways-1.0.1
    release: istio
    heritage: Tiller
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
--
```
`istio: ingressgateway`
**Version**
```
$ istioctl version
Version: 1.0.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:12:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
```

**Is Istio Auth enabled or not?**
No.

**Environment**
N/A

**Comment by louisvernon** [comment]
Thanks @rshriram. I don't quite follow your answer. 
This is what we did - hopefully you can tell me where we went wrong. 
- The default install creates the `istio-ingressgateway` LoadBalancer service (we have been using NodePort, but hopefully not relevant) through which traffic can enter the service mesh. 
- The install also creates a default Istio Gateway `istio-autogenerated-k8s-ingress`. 
- We bound our VirtualService configs to the `istio-autogenerated-k8s-ingress` Gateway, but rules did not effect traffic into the `istio-ingressgateway` k8s service.
- We modified the selector on the `istio-autogenerated-k8s-ingress` gateway to point to `istio: ingressgateway` rather than the default `istio: ingress` and the VirtualService rules took effect for traffic reaching the `istio-ingressgateway`. 

Is this intentional and if so what is the intended purpose of the `istio-autogenerated-k8s-ingress` Gateway?

**Comment by rshriram** [comment]
istio-autogenerated-k8s-ingress should not even be present unless you enabled k8s ingress in Helm.

If you want to use Gateways, VirtualServices with the new gateway, please bind to gateway by name "istio-ingressgateway". Something like this
```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
EOF
```

**Comment by louisvernon** [comment]
I see. We templated our istio.yaml [as follows](https://istio.io/docs/setup/kubernetes/helm-install/):
```
helm template install/kubernetes/helm/istio --name istio --namespace  --set gateways.istio-ingressgateway.type=NodePort --set gateways.istio-egressgateway.type=NodePort istio-system > $HOME/istio.yaml
```
The generated yaml includes the following object:
```
# Source: istio/charts/pilot/templates/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-autogenerated-k8s-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      protocol: HTTP2
      name: http
    hosts:
    - "*"
```
We will follow your advice and deploy and bind our own gateway object to the `istio-ingressgateway `rather than patching the `istio-autogenerated-k8s-ingress` gateway object to select `istio-ingressgateway`. 

Thanks.
