### ISSUE TITLE
Can not get EnvoyFilter to work

### ISSUE THREAD

**Issue by Szymongib** [istio/istio#8261]
**Istio version: 1.0**

We would like to validate client certificate's Common Name with use of `EnvoyFilter`. 

As a begining I wanted to create some simple filter that responds with 403 on every request:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forbidden-lua
  namespace: istio-system
spec:
  workloadLabels:
    app: my-service
  filters:
  - filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:respond({[":status"] = "403"},"nope")
        end
    filterName: envoy.lua
    filterType: HTTP
    listenerMatch:
      listenerType: ANY
```

Although I could not get it to work. The service was working the same as without the filter. Only thing I have found related to the filter in proxy logs was: `[2018-08-27 07:19:26.140][19][info][lua] external/envoy/source/extensions/filters/http/lua/lua_filter.cc:449] envoy_on_response() function not found. Lua filter will not hook responses.` so I guess the filter was detected.

I have also tried some simple examples from Envoy's [documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter) but the outcome was the same.

I am not sure if I am missing something important or is that some kind of bug. Also the documentation on EnvoyFilters seems a bit poor, could you provide some step by step example of how to get it to work?

**Comment by wailua** [comment]
The message in the logs is as expected as you havn't defined an "envoy_on_response" function (which is optional).

Can you also post your deployment?
You have to add "app: my-service" in your depoyment at spec->template->metadata->labels

**Comment by Szymongib** [comment]
Yes, I have mentioned that log because it told me that the EnvoyFilter is visible to the proxy in the pod with desired application.

The label is also set in the deployment:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: my-service
    heritage: Tiller
    release: my-service
  name: my-service
  namespace: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
      release: my-service
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/includeInboundPorts: "8081"
      labels:
        app: my-service
        release: my-service
    spec:
      containers:
      - args:
        - /myservice
        image: my-image
        imagePullPolicy: IfNotPresent
        name: my-service
        ports:
        - containerPort: 8081
          name: my-port
```
And I also have a service:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    "auth.istio.io/8081": NONE
  name: my-service-api
  namespace: integration
  labels:
    app: my-service
    release: my-service
    heritage: my-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: my-port
  selector:
    app: my-service
    release: my-service
```
