### ISSUE TITLE
How can I make the istio-ingressgateway internal on AWS

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#8301]
istio version: 1.0.1

I created kubernetes cluster by kops on AWS.

After I created the istio, I can find an internet-facing load balancer in AWS ec2 dashboard:
![image](https://user-images.githubusercontent.com/1676951/44709314-e917a200-aadb-11e8-9141-97ffbd890f7e.png)

How can I make this load balancer internal?

**Comment by dozer47528** [comment]
I added `--set gateways.istio-ingressgateway.type=NodePort` this flag when I install istio.
And I followed this guide: https://istio.io/docs/tasks/traffic-management/ingress/ but get `curl: (7) Failed to connect to 10.0.12.144 port 31380: Connection refused`

**Comment by dozer47528** [comment]
I reinstalled my kubernetes cluster and reinstalled istio again, it works now.

**Comment by Amit-Thawait** [comment]
Answering this in case someone stumbles upon this issue.

The correct way to **make the istio-ingressgateway internal on AWS** is

edit `install/kubernetes/helm/istio/values.yaml` in istio's helm chart (https://github.com/helm/charts/tree/master/incubator/istio)

Look for the below section 
```
#
# ingress configuration
#
ingress:
  enabled: false
  replicaCount: 1
  autoscaleMin: 1
  autoscaleMax: 5
  service:
    annotations: {}
    loadBalancerIP: ""
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    ports:
    - port: 80
      name: http
      nodePort: 32000
    - port: 443
      name: https
    selector:
      istio: ingress
```
In the above section, just edit the  annotations part from `annotations: {}` to this:
```
annotations:
  "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
```

Last step is to install istio with the modified change.
`helm install install/kubernetes/helm/istio --name istio --namespace istio-system`

In case you have already install istio, then you just need to update the helm installation using the command:
`helm update istio install/kubernetes/helm/istio --namespace istio-system`

In case you are not able to find istio in the helm chart url it is possible that it has moved from incubator to stable..so just look for istio at https://github.com/helm/charts/tree/master/incubator in case the above url doesn't work.
