### ISSUE TITLE
VirtualService with gRPC not working with hosts different than '*'

### ISSUE THREAD

**Issue by maximematheron** [istio/istio#8378]
**Describe the bug**
VirtualService can only set '*' in the hosts for gRPC traffic and fail to be found when specifying a proper host. The reason seems to be that when calling gRPC from clients, we need to explicitly specify the port of the server. When I print the log of the ingress pod, we can see that the host that is forwarded with the traffic is wrong because it includes also the port!

<img width="1861" alt="capture d ecran 2018-08-30 a 17 15 23" src="https://user-images.githubusercontent.com/22519198/44861302-8a3b5f80-ac78-11e8-82b1-213d553cae1c.png">

**Expected behavior**
VirtualService should be found using the ```hosts``` selector and should be able to forward traffic to the corresponding ```Service```.

**Steps to reproduce the bug**

*Gateway*
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ms-gateway
  namespace: microservices
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - hosts:
    - 'your.domain.com'
    port:
      name: https-ms
      number: 443
      protocol: HTTPS
    tls:
      mode: MUTUAL
      serverCertificate: /etc/istio/ingressgateway-certs/ms-tls.crt
      privateKey: /etc/istio/ingressgateway-certs/ms-tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ms-ca.pem
```
*VirtualService*
 ```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: global
  namespace: microservices
spec:
  hosts:
  - 'your.domain.com'
  gateways:
  - ms-gateway
  http:
  - match:
    - uri:
        prefix: /helloworld.Greeter/
    route:
    - destination:
        port:
          number: 8000
        host: hello.microservices.svc.cluster.local
```

And the underlying *Service* (The well-known Hello world example):

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: microservices
  labels:
    app: hello
spec:
  ports:
  - name: hello
    port: 8000
    targetPort: 9999
    protocol: TCP
  type: ClusterIP
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  namespace: microservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: grpc-greet
        image: enm10k/grpc-hello-world
        ports:
        - name: grpc-api
          containerPort: 9999
        env:
          - name: PORT
            value: "9999"
        command:
          - greeter_server
      restartPolicy: Always
```

**Version**
Istio: 1.0.0
kubernetes: v1.9.7

**Is Istio Auth enabled or not?**
Yes, following the setup documentation for GCE

**Environment**
Google cloud engine
