### ISSUE TITLE
DURATION is not supported by metric template

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#8379]
**Describe the bug**
The following error is observed in the mixer when trying to apply a metric configuration having an instance for `request.duration` with an out-of-process Istio adapter.

```
2018-08-30T16:53:30.104396Z	error	config does not conforms to schema of template 'metric': unable to build message field: value, unsupported type: DURATION
```

**Expected behavior**
Metrics depending on `request.duration` should work like any other metrics.

**Steps to reproduce the bug**
Use the following instance configuration.

```yaml
apiVersion: "config.istio.io/v1alpha2"
  kind: instance
  metadata:
    name: requestduration
    namespace: istio-system
  spec:
    template: metric
    params:
      value: response.duration | "0ms"
      dimensions:
        source_service: source.service | "unknown"
        source_version: source.labels["version"] | "unknown"
        destination_service: destination.service | "unknown"
        destination_version: destination.labels["version"] | "unknown"
        response_code: response.code | 200
      monitored_resource_type: '"UNSPECIFIED"'
```

**Version**
Istio:
```
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No

**Environment**
Minikube 0.28 (macOS)
