### ISSUE TITLE
Istio ingress gateway do not support mergeable-ingress-type

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#8394]
For nginx ingress controller, it support `mergeable-ingress-type` as described here https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types

This feature can enable me to configure NGINX to have support for using multiple Ingress Resources which apply to a common host. This allows for easier management when using a large amount of paths.

Like example as follows:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-master
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe-secret
  rules:
  - host: cafe.example.com
```
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-coffee-minion
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-tea-minion
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
```

Then both `cafe.example.com/coffee` and `cafe.example.com/tea` works for me.

But with ingress gateway, this case will not work. If I define multiple common names, only the first one will take effect.

/cc @rshriram comments for this? Thanks.
