### ISSUE TITLE
Unable to connect to external MongoDB instance with istio-proxy

### ISSUE THREAD

**Issue by Stono** [istio/istio#8410]
**Describe the bug**
Using istio `1.0.1` we are unable to create external mesh connections to mongo db clusters.

We have the following ServiceEntry defined on our cluster

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-mongo-all
  namespace: core-system
spec:
  hosts:
  - ourdb-shard-00-00-3duup.gcp.mongodb.net
  - ourdb-shard-00-01-3duup.gcp.mongodb.net
  - ourdb-shard-00-02-3duup.gcp.mongodb.net
  ports:
  - name: mongo
    number: 27017
    protocol: MONGO
  resolution: DNS
```

And I can confirm by jumping onto pod i can connect to mongodb port 27017 with telnet, so traffic is being routed out of envoy, and off the node to mongodb.

However, when the mongo client is used, and it attempts to create a tls connection to mongodb, it just times outs, and observing TCP dumps on the node we're seeing massive traffic.   Envoy appears to be trying to create the tls connection and then failing.

The client connection looks like this:
```
/usr/bin/scl enable rh-python35 python
from pymongo import MongoClient
uri = "mongodb://user:password@ourshard-shard-00-00-3duup.gcp.mongodb.net:27017/test?ssl=true&replicaSet=Valuations-shard-0&authSource=admin&retryWrites=true&compressors=snappy"
client = MongoClient(uri)
db = client.retailValuations
collection = db.coefficient_set
db.collection_names(include_system_collections=False)
```

We cannot see anything in any logs anywhere that is indicating what is wrong, and when we remove istio-proxy from the pod everything works fine.

I have wireshark pcap files from both the working, and non-working examples which I can share privately for someone who can help to debug this problem.  And can give whoever can help access to our cluster to help debug.

Thanks
Karl

**Comment by rshriram** [comment]
If the client is initiating a TLS connection, it is no longer a mongo protocol to envoy. It will be a plain TLS connection (so you won't get mongo stats either). I suggest you make the client talk plain text and let envoy originate the TLS by configuring a destination rule.

Secondly, the configuration you have will cause port collisions and push traffic to a single shared only, as you have 3 services listening on same host 0.0.0.0:27017. Instead, if the client doesnt care about the shard, try this

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-mongo-all
  namespace: core-system
spec:
  hosts:
  - somedummyname.net
  ports:
  - name: mongo
    number: 27017
    protocol: MONGO
  resolution: DNS
  endpoints:
  - address:    ourdb-shard-00-00-3duup.gcp.mongodb.net
     ports:
             mongo: 27017
  ...
```

This will cause all traffic to 27017 to be load balanced across the three shards.. (my syntax may be incorrect. So please check the api spec for the right syntax but you get the idea)

Then add a destination rule for TLS origination from Envoy:
```
DestinationRule....
host: somedymmyname.net
trafficPolicy:
   tls:
       mode: simple
```


And if the client cannot be changed to not use TLS, then change thje service entry to use `protocol: TCP`, skip the destination rule.

**Comment by Stono** [comment]
Hey @rshriram - thanks for the quick reply.  This is really confusing :-(

The client does care about the shard, i need to ensure that if i tries to connect to 01, it goes to 01.   Would I need separate instances for each?

**Comment by rshriram** [comment]
Try this:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-mongo-all
  namespace: core-system
spec:
  hosts:
  - ourdb-shard-00-00-3duup.gcp.mongodb.net
  - ourdb-shard-00-01-3duup.gcp.mongodb.net
  - ourdb-shard-00-02-3duup.gcp.mongodb.net
  ports:
  - name: mongo
    number: 27017
    protocol: TCP
  resolution: NONE
```
