### ISSUE TITLE
Add public/private switch to Gateway

### ISSUE THREAD

**Issue by dunjut** [istio/istio#8428]
**Describe the feature request**
We have some APIs are intended to be accessed from only within the datacenter, such as services running on bare-metals. Meanwhile we also need to expose some APIs to the public network. So it's better we can use a flag to distinguish them in Gateway spec, and make istio-ingressgateway capable of watching and applying Gateway objects which has a pre-defined flag value.

**Describe alternatives you've considered**
Before switching to istio-ingressgateway, we use Ingress with different ingress class to achieve this purpose. The 'public' ingress-controller runs on nodes with public IP addresses, using hostNetwork. 'private' ingress-controller only listens private addresses.

**Comment by dunjut** [comment]
@linsun Can you help take a look at this please?

**Comment by dunjut** [comment]
cc @rshriram

**Comment by rshriram** [comment]
Just like ingress you can run your own gateways. Simply launch additional gateway workloads with different labels. Then you can pin the gateway resources to different gateway workloads.

**Comment by dunjut** [comment]
@rshriram Thanks!

Can you offer more details on how to launch gateway workloads with labels and how to pin gateway resources to them?

**Comment by rshriram** [comment]
```
gateway:
 workloadSelectors:
    mylabel: myvalue # these are pod labels for your gateway
...
```

And to launch your own gateway, checkout the values-istio-gateways.yaml helm chart.

**Comment by dunjut** [comment]
@rshriram Thanks, it works!

For those who have the same demand, here is an example.

**gateway pod deployment**

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        visibility: internal # put a custom label here.
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      ...
```

**create Gateway resource**

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-gateway
spec:
  selector:
    visibility: internal # here we add a workload selector to match our custom labels.
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.example.com"
```
