### ISSUE TITLE
What difference between registered external service and unregistered ones in HTTPS protocol?

### ISSUE THREAD

**Issue by Yisaer** [istio/istio#8439]
Hi, I am using istio1.0.0 release and I set the google external service in the following [doc](https://istio.io/docs/tasks/traffic-management/egress/#configuring-istio-external-services). I send HTTPS request to both `https://www.google.com` and `https://www.bing.com` . And I noticed that both requests were `200 OK`.

 I want to know that what difference between both requests while I only set the google external service since both requests seems to be successful. Is my current situation correct?  Will Istio-proxy log the https requests?

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: istio-test
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
  namespace: istio-test
spec:
  hosts:
  - www.google.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
```

```
root@sleep-776b7bcdcd-lbnkb:/# curl -I https://www.google.com
HTTP/1.1 200 OK
Date: Mon, 03 Sep 2018 11:47:35 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Server: gws
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: 1P_JAR=2018-09-03-11; expires=Wed, 03-Oct-2018 11:47:35 GMT; path=/; domain=.google.com
Set-Cookie: NID=138=TJdfDa2QxS2j2bxF8PqU959FSC29qlb7E9VlaVg9nEWFM48p2rgox0Ud7xPYFF9kUbaTQKFF8LJeQx7H5Ozk2HWoq_wpdGg8KWp8x0PF3JgKyWx2H9VINCOOTP0JIVf7; expires=Tue, 05-Mar-2019 11:47:35 GMT; path=/; domain=.google.com; HttpOnly
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Accept-Ranges: none
Vary: Accept-Encoding

root@sleep-776b7bcdcd-lbnkb:/# curl -I https://www.bing.com
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Length: 0
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
P3P: CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"
Set-Cookie: SRCHD=AF=NOFORM; domain=.bing.com; expires=Thu, 03-Sep-2020 11:47:54 GMT; path=/
Set-Cookie: SRCHUID=V=2&GUID=D79C4C88C59B442590DB76058AD822ED&dmnchg=1; domain=.bing.com; expires=Thu, 03-Sep-2020 11:47:54 GMT; path=/
Set-Cookie: SRCHUSR=DOB=20180903; domain=.bing.com; expires=Thu, 03-Sep-2020 11:47:54 GMT; path=/
Set-Cookie: _SS=SID=217FB8A33A2562232743B4FC3BF5637D; domain=.bing.com; path=/
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-MSEdge-Ref: Ref A: 35078CF6BC4D4907AEE53843B44F6532 Ref B: ASHEDGE0910 Ref C: 2018-09-03T11:47:54Z
Set-Cookie: _EDGE_S=F=1&SID=217FB8A33A2562232743B4FC3BF5637D; path=/; httponly; domain=bing.com
Set-Cookie: _EDGE_V=1; path=/; httponly; expires=Sat, 28-Sep-2019 11:47:54 GMT; domain=bing.com
Set-Cookie: MUID=2BA3A21DD5BA681514C0AE42D46A696D; path=/; expires=Sat, 28-Sep-2019 11:47:54 GMT; domain=bing.com
Set-Cookie: MUIDB=2BA3A21DD5BA681514C0AE42D46A696D; path=/; httponly; expires=Sat, 28-Sep-2019 11:47:54 GMT
Date: Mon, 03 Sep 2018 11:47:54 GMT
```

**Comment by Yisaer** [comment]
And I'm sure the includeIPRange arg for istio-init container in this POD is *.

``` yaml

Name:           sleep-776b7bcdcd-lbnkb
Namespace:      istio-test
Node:           10.111.211.161/10.111.211.161
Start Time:     Mon, 03 Sep 2018 19:33:22 +0800
Labels:         app=sleep
                pod-template-hash=3326367878
Annotations:    sidecar.istio.io/status={"version":"250a1f462190fb065274655b8c50a870c89365a5f3c6afbf9ddf46f768e09beb","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs...
Status:         Running
IP:             172.29.22.23
Controlled By:  ReplicaSet/sleep-776b7bcdcd
Init Containers:
  istio-init:
    Container ID:  docker://25aa3e9e9dbbf73b04b800df5576149ac06693bd2ce1f137257b791d680dba03
    Image:         docker.io/istio/proxy_init:1.0.0
    Image ID:      docker-pullable://istio/proxy_init@sha256:345c40053b53b7cc70d12fb94379e5aa0befd979a99db80833cde671bd1f9fad
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b

      -d

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 03 Sep 2018 19:33:23 +0800
      Finished:     Mon, 03 Sep 2018 19:33:23 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        20m
      memory:     400Mi
    Environment:  <none>
    Mounts:       <none>
```
