### ISSUE TITLE
can not visit istio grafana from outside

### ISSUE THREAD

**Issue by lxkaka** [istio/istio#8441]
Hi,  there 
I want to visit grafana with a external IP, and I use ingress gateway to proxy the request. 
Below is the conf:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 15031
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - grafana-gateway
  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        port:
          number: 3000
        host: grafana
``` 
when I `curl http://172.31.44.231:32283`(IP is node ip of gateway,), the request will be proxy to the pod with port 8888(I have a service with container port 8888).
Is this a misconfiguration ? thanks in advance for any reply.
