### ISSUE TITLE
MongoDB HelmChart breaks with Istio

### ISSUE THREAD

**Issue by Gottox** [istio/istio#8443]
**Describe the bug**
When installing the [official MongoDB helm chart](https://github.com/helm/charts/blob/master/stable/mongodb/Chart.yaml) with `helm install --name mongodb stable/mongodb`, the istio sidecar fails with a `permission denied` error message:
```
 kubectl logs mongodb-sec-enabled-64766bbcdd-mzpdk istio-init
+ iptables -t nat -N ISTIO_REDIRECT
Environment:
------------
ENVOY_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
INBOUND_CAPTURE_PORT=15001
PROXY_UID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=27017,
INBOUND_PORTS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=

iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
+ dump
+ iptables-save
iptables-save v1.6.0: Cannot initialize: Permission denied (you must be root)
```

**Expected behavior**
The expected behavior is that both the init container and the mongodb container start properly.

**Steps to reproduce the bug**`
1. Get a k8s cluster
2. Install helm as described [here](https://docs.helm.sh/using_helm/#installing-helm)
3. Install istio as described [here](https://istio.io/docs/setup/kubernetes/helm-install/)
4. Enable automatic sidecar injection as described [here](https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection)
5. `helm install stable/mongodb --name mongodb-sec-enabled`
6. Inspect the error with `kubectl logs mongodb-sec-enabled-XXX istio-init`

**Version**
Kubernetes:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"archive", BuildDate:"2018-08-25T18:33:09Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
helm:
```
$ helm version
Client: &version.Version{SemVer:"v2.9+unreleased", GitCommit:"", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
Istio:
```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Is Istio Auth enabled or not?**
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/src/cluster-setup/istio/values.yaml
cat ~/src/cluster-setup/istio/values.yaml
global:
  proxy:
    envoyStatsd:
      enabled: false
ingress:
  enabled: false
gateways:
  istio-ingressgateway:
    enabled: false
  istio-egressgateway:
    enabled: false
galley:
  enabled: false
sidecarjectorWebhook:
  enabled: true
mixer:
  enabled: false
prometheus:
  enabled: false
```

**Environment**
AWS, deployed with KOPS

**Cluster state**
Will generate on request. (New cluster needs to be set up, as I don't want to leak sensitive informations)
