### ISSUE TITLE
Enable routing decisions based on attributes in a JWT token

### ISSUE THREAD

**Issue by pieterderycke** [istio/istio#8444]
We would like to perform routing between versions based on functional criteria (like sex, location, age, etc.). With Istio this is currently not convenient, it would require us to push all the necessary functional parameters in the http headers and perform the routing based on these headers.

We are making use of JWT tokens to push the identity of the calling user between the micro-services. We would like to make use attributes in the JWT token to pass the functional data between micro-services. The current options (uri, scheme, method, authority, headers, port) are too limited and to much oriented at technical attributes

**Comment by BarDweller** [comment]
This does sound like it could be really quite useful.

**Comment by frankbu** [comment]
So the issue is that the JWT is encoded, so you can't write rules directly using things in it, is that right? Although I haven't used them, I think there are a couple of possible ways you could do it. You can plug in some lua code in envoy (lua filter) that could extract the fields and maybe add some temporary headers that are used in the route rules. I think you can also add a custom envoy filter of your own to do whatever you want, but I suspect that's harder. There was also some discussion about configuring mixer to be called before routing so that it could be used to add some headers that can affect routing. If somebody wants to experiment with any of these ideas, that would be great.

**Comment by BarDweller** [comment]
Yes, JWTs are base64 encoded, and their claims are often used in the way that http headers used to be, but with the added value of knowing they haven't been tampered with (either via shared-secret, or public cert validation of the JWT). 

At a basic level it would be great to be able to route based on the claims within a JWT, at a more advanced level it would be advantageous to be able to only do so if the JWT passes validation. (although arguably, the end service will be validating the jwt anyway, it just doesn't feel right to potentially route based on  information that you know has been altered)

I'll have a look at the Envoy lua filter .. maybe it could work as you suggest, and expand the claims (or an identified subset) out to headers as jwtheadername.claimname=claimvalue so they could be reliably queried using the existing http headers support.

**Comment by BarDweller** [comment]
See also.. https://github.com/envoyproxy/envoy/issues/3763

**Comment by kyessenov** [comment]
In 1.1, you can utilize Mixer adapters to change request headers. See https://github.com/istio/api/blob/master/policy/v1beta1/cfg.proto#L171. You can then write a networking config to route using the headers. In the next-gen architecture, Mixer functions are going to be executed inside Envoy process, to avoid extra operations and cost of Mixer itself.

**Comment by frankbu** [comment]
Sounds like using Mixer header operations is another experiment that would be good to try, but it seems that it would be a lot more work to configure it this way vs. just adding a little bit of lua code in an [EnovyFilter](https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#EnvoyFilter), assuming that works.

Maybe if we provide a built-in Mixer adapter that does the jwt decoding/extraction, then users wouldn't need to configure very much to use it. Is that the intent @kyessenov?

**Comment by kyessenov** [comment]
Yes, the intent is to have cooperative adapters using basic JWT codecs in proxy and Mixer external adapters if necessary. Policy rules would tie everything together regardless of which component executes them. Lua code may works in the interim, but there is no compatibility guarantees, as with any EnvoyFilter config since it breaks the abstraction barrier.

**Comment by BarDweller** [comment]
I've just tried with an EnvoyFilter configured to add the path as a header to the request, combined with a VirtualService configured with http match rules to match on the header to select which app to route to. 

The routing works when I send the header from my rest client, but does not work if the the EnvoyFilter sets the header.  It's as if the EnvoyFilter is running after the decision is already made by the VirtualService re which app to route to. 

The apps dump the headers received, I can see the header added by my EnvoyFilter with the expected value that should have caused the alternate routing to occur, but didn't.

I tried adding insertPosition index FIRST to the EnvoyFilter, but that didn't help.

Any other ideas I should try for EnvoyFilter, if not, is there an example MixerAdapter that changes Request Headers? I can happily go code the jwt decode & subsequent header injection.

**Comment by frankbu** [comment]
Hmm, I would think that insertPosition index FIRST would do the trick. Maybe, to debug, you could add two lua filters, yours as the first one, and a second one that does something with the header that should have been added by the first, to confirm that the change is getting passed on to the next filter.

@rshriram Do you have an idea what might be the problem here?

**Comment by frankbu** [comment]
Btw, if headers being added by one filter are not being finished before the routing is done, I would guess that the mixer approach will have the same issue.

@kyessenov have Mixer  header operations that add headers been tested in conjunction with route rules that act on those headers?

**Comment by rshriram** [comment]
are you retriggering route computation in the lua filter>? Lua filter is executed after envoy matches the routes, and selects the upstream cluster. IF you add/remove stuff in lua, you have to retrigger route computation for this to take effect.

**Comment by rshriram** [comment]
looking at the lua code in envoy, it is re-triggering route computation. So it depends on how you are adding the headers in Lua

**Comment by BarDweller** [comment]
@rshriram Hi there =)

I'm adding them using the add method, as the example did.. 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hello-lua
spec:
  workloadLabels:
    app: hello
  filters:
  - listenerMatch:
      portNumber: 8080
      listenerType: SIDECAR_INBOUND
    filterName: envoy.lua
    filterType: HTTP
    insertPosition: 
      index: FIRST
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          hdrs = request_handle:headers()
          phdr = hdrs:get(":path")
          hdrs:add("path",phdr)
          hdrs:add("end-user", phdr:sub(2))
        end
```
Then over in my VirtualService I have.. 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
  - "*"
  gateways:
  - hello-gateway
  http:
  - match:
    - headers:
        end-user:
          exact: userone
    route:
    - destination:
        host: hello.test1.svc.cluster.local
        port:
          number: 8080
  - route:
    - destination:
        host: hello.test3.svc.cluster.local
        port:
          number: 8080
```

Shout if you'd like any other info...
