### ISSUE TITLE
ServiceEntries in Kubernetes Cluster are shared between namespace.

### ISSUE THREAD

**Issue by seehait** [istio/istio#8462]
**Describe the bug**
My team is using Istio 1.0.1 inside of Kubernetes Cluster. Some application inside the cluster need to connect to services outside their cluster. So we defined ServiceEntries for all external services.

The following is the Kubernetes resource we defined, consist of 2 service entries of external db service. Despite both service entries point to the same db master host, but only the first one also point to the replica host.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db1
  namespace: namespace1
spec:
  hosts:
  - master.db1.xxx
  - replica.db1.xxx
  location: MESH_EXTERNAL
  ports:
  - name: mysql
    number: 3306
    protocol: TCP
  resolution: NONE
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db1
  namespace: namespace2
spec:
  hosts:
  - master.db1.xxx
  location: MESH_EXTERNAL
  ports:
  - name: mysql
    number: 3306
    protocol: TCP
  resolution: NONE
```

The problem is the connection to the external db is unstable. As we dig to the envoys config dump, we found that what service entry of type TCP do is just listen and forward the request of the specified port (0.0.0.0:3306 in this case) to the destination host.

We noticed that the defined service entries is not just bound to the namespace, but it is shared to the whole cluster. That's mean there are two listener on the 0.0.0.0:3306 inside the envoys. So the consequence is envoys may confused, and the connections will be unstable (keep-alive connection will be closed unexpectedly and randomly).

As my understanding, TCP Service Entries port must be unique within the Kubernetes namespace. But I can use the same port for any service entries inside difference namespace. But the strange thing is for now, service entries are shared to the whole cluster.

**Expected behavior**
Should the service entries bound to only defined Kubernetes namespace? (Since we may have applications connect to the same port but point to difference host.)

**Steps to reproduce the bug**
- Try adding the following Service Entries. Then try connect to those host with the keep-alive connection, Around 20 minutes, the connections will be unexpectedly closed.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db1
  namespace: namespace1
spec:
  hosts:
  - master.db1.xxx
  - replica.db1.xxx
  location: MESH_EXTERNAL
  ports:
  - name: mysql
    number: 3306
    protocol: TCP
  resolution: NONE
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db1
  namespace: namespace2
spec:
  hosts:
  - master.db1.xxx
  location: MESH_EXTERNAL
  ports:
  - name: mysql
    number: 3306
    protocol: TCP
  resolution: NONE
```

**Version**
- Istio version 1.0.1
- Kubernetes cluster version 1.10

**Is Istio Auth enabled or not?**
- enabled

**Environment**
- Kubernetes Cluster inside EC2 instance.
