### ISSUE TITLE
Enable different Auth Policy in the same Pod

### ISSUE THREAD

**Issue by tommyJimmy87** [istio/istio#8496]
**Describe the bug**
I'm trying to assign 2 Policy in the same pod for 2 different Service. What I need is to have one Service A for external access (Ingress) with mTLS and Auth (JWT/RBAC etc.) enabled and another Service B with mTLS enabled but without Auth stuff for internal communication. 

 ````
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-helloworld
  namespace: dev
  labels:
    release: beta
    component:  test-helloworld
    version: v1.1
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test-helloworld
        component:  test-helloworld
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: heroku/nodejs-hello-world
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 3000
          name: http
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: test-helloworld-svc
  namespace: dev
  labels:
    component:  test-helloworld
    app: test-helloworld
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: private-port
  selector:
    component: test-helloworld

Rendered file test-components/test-helloworld/2_service.yaml:
---
apiVersion: v1
kind: Service
metadata:
  name: test-helloworld-svc-ingress
  namespace: dev
  labels:
    component:  test-helloworld
    app: test-helloworld
spec:
  ports:
    - port: 3001
      targetPort: 3000
      name: http
  selector:
    component: test-helloworld

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  name:  test-helloworld-ingress
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress.host.com
spec:
  rules:
  - host: test-helloworld.dev.host

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-helloworld-vsvc
  namespace:  dev
spec:
  hosts:
  - "test-helloworld.dev.host"
  gateways:
  - istio-k8s-ingress.istio-system.svc.cluster.local
  http:
  - match:
    route:
    - destination:
        port:
          number: 3001
        host: test-helloworld-svc-ingress

---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: test-helloworld-rule
  namespace:  dev
spec:
  host: "test-helloworld-svc.dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: test-helloworld-rule-ingress
  namespace:  dev
spec:
  host: "test-helloworld-svc-ingress.dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: test-helloworld-no-jwt-policy
  namespace: dev
spec:
  targets:
  - name: test-helloworld-svc
  peers:
  - mtls:
      mode: STRICT

---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: test-helloworld-jwt-policy
  namespace: dev
spec:
  targets:
  - name: test-helloworld-svc-ingress
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: "issuer"
      jwksUri: "https://something"
      jwt_headers:
      - "x-jwt-assertion"
  principalBinding: USE_ORIGIN

---

````

Checking the tls-check command look like to work well : 

````
$ istioctl authn tls-check test-helloworld-svc-ingress.dev.svc.cluster.local
HOST:PORT                                                  STATUS     SERVER     CLIENT     AUTHN POLICY                       DESTINATION RULE
test-helloworld-svc-ingress.dev.svc.cluster.local:3001     OK         mTLS       mTLS       test-helloworld-jwt-policy/dev     test-helloworld-rule-ingress/dev


$ istioctl authn tls-check test-helloworld-svc.dev.svc.cluster.local
HOST:PORT                                          STATUS     SERVER     CLIENT     AUTHN POLICY                          DESTINATION RULE
test-helloworld-svc.dev.svc.cluster.local:3000     OK         mTLS       mTLS       test-helloworld-no-jwt-policy/dev     test-helloworld-rule/dev

````

**Expected behavior**

If i try to curl the endpoint from the DNS (Service A outside the mesh) it works well, I get the right error `Origin authentication failed. ` but if i try from the Service B with the private service inside another Pod for example (with istio proxy enabled as well) I got the same error. What i expect is that from the Service B i could call it without JWT.

Service A call : 
````
$ wget -q -S -O - test-helloworld-svc-ingress.dev.svc.cluster.local:3001
  HTTP/1.1 401 Unauthorized
  content-length: 29
  content-type: text/plain
  date: Wed, 05 Sep 2018 08:30:59 GMT
  server: envoy
  x-envoy-upstream-service-time: 6
````
This is the right behavior for the "ingress service". 

Service B call :
````
$ wget -q -S -O - test-helloworld-svc.dev.svc.cluster.local:3000
  HTTP/1.1 401 Unauthorized
  content-length: 29
  content-type: text/plain
  date: Wed, 05 Sep 2018 08:31:08 GMT
  server: envoy
  x-envoy-decorator-operation: test-helloworld-svc-ingress.dev.svc.cluster.local:3001/*
````

The problem is that the Service B  envoy proxy seems to redirect to the Service A with `x-envoy-decorator-operation`. Instead i would like to call it without the Auth Policy Enabled. 

**Version**
Istio Version : 1.0
Kubernetes : 1.9

**Is Istio Auth enabled or not?**
Yes
