### ISSUE TITLE
Helm Install Options

### ISSUE THREAD

**Issue by jaredeis** [istio/istio#8501]
**Describe the bug**
Trying to use the --set flag for helm install/template to add an annotation with the gateways.istio-ingressgateway.serviceAnnotations key and there doesn't seem to be a way to format the key value pair for the annotation to add the annotation for an aws internal ELB such as:

```
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
...
```

**Expected behavior**
We would expect that some format of this command:
`helm template install/kubernetes/helm/istio --name istio --set gateways.istio-ingressgateway.serviceAnnotations.service.beta.kubernetes.io/aws-load-balancer-internal="'0.0.0.0/0'" --namespace istio-system > istio.yaml`

to generate the above annotation to the istio-ingressgateway Service.

**Steps to reproduce the bug**
Run the command above against istio 1.0.0 helm chart and look in the annotations section of the istio-ingressgateway Service. The output will look like:

```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service: map[beta:map[kubernetes:map[io/aws-load-balancer-internal:'0.0.0.0/0']]]
...
```

Obviously, the dots in the annotation are breaking the output in the resulting yaml, and no amount of quoting or escaping the dots seems to prevent that issue when specifing an annotation such as `service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'`

**Version**
Tested on 1.0.0 and 1.0.1

**Is Istio Auth enabled or not?**
It will need to be, but this isn't an issue inside istio itself

**Environment**
AWS EKS

**Cluster state**
Going to say N/A unless someone requests it for some reason.

**Comment by sporokh** [comment]
Based on official golang and helm documentation, when using `--set` and passing map you need to specify this in this way:

```
helm template install/kubernetes/helm/istio --name istio --set gateways.istio-ingressgateway.serviceAnnotations.key=value --namespace istio-system > istio.yaml
```

That's probably a documentation issue.

**Comment by sporokh** [comment]
You probably just need to escape the dots:
```
helm template install/kubernetes/helm/istio --name istio --set gateways.istio-ingressgateway.serviceAnnotations.'service\.beta\.kubernetes\.io/aws-load-balancer-internal'=0.0.0.0/0 --namespace istio-system > istio.yaml
```

This works for me, resulting in:
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
