### ISSUE TITLE
err:rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#8509]
**Describe the bug**

gRPC server and client uisng WithInsecure. (no tls)

rpc client has resp err:
```
rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers
```

```
but i change demo.yaml port 1443 to 1234 same as targetPort, it work. but no loadbalance.
```

istio-proxy log:
```
[2018-09-06T01:52:33.283Z] "POST /test.PingService/Ping HTTP/2" 200 UF 18 0 1 - "-" "grpc-go/1.15.0-dev" "9ff26768-08c0-9e82-916c-c4badbacc358" "server.test.svc.cluster.local:1443" "172.20.50.36:1443"
[2018-09-06T01:52:35.286Z] "POST /test.PingService/Ping HTTP/2" 200 UF 18 0 1 - "-" "grpc-go/1.15.0-dev" "be968cd8-8038-9580-8026-c384bfc12083" "server.test.svc.cluster.local:1443" "172.20.50.36:1443"
[2018-09-06T01:52:37.288Z] "POST /test.PingService/Ping HTTP/2" 200 UF 18 0 1 - "-" "grpc-go/1.15.0-dev" "328ea1ab-f8a6-9b21-97f2-15fc63252f27" "server.test.svc.cluster.local:1443" "172.20.50.36:1443"
[2018-09-06T01:52:39.290Z] "POST /test.PingService/Ping HTTP/2" 200 UF 18 0 1 - "-" "grpc-go/1.15.0-dev" "f27b8ede-753c-9c94-a4e8-707ccc655ca5" "server.test.svc.cluster.local:1443" "172.20.50.36:1443"
[2018-09-06T01:52:41.292Z] "POST /test.PingService/Ping HTTP/2" 200 UF 18 0 1 - "-" "grpc-go/1.15.0-dev" "ddd69a10-a6de-9587-a202-9bd16ec304f2" "server.test.svc.cluster.local:1443" "172.20.50.36:1443"
[2018-09-06T01:52:43.295Z] "POST /test.PingService/Ping HTTP/2" 200 UF 18 0 1 - "-" "grpc-go/1.15.0-dev" "d6096d04-e4c8-9840-854a-d0ee2373f9bd" "server.test.svc.cluster.local:1443" "172.20.50.36:1443"
```

**Expected behavior**
RPC works.

**Steps to reproduce the bug**
gen isito.yaml
```
helm template install/kubernetes/helm/istio \
    --name istio \
    --namespace istio-system \
    --set global.tag="1.0.1" \
    --set global.proxy.includeIPRanges="172.16.0.10/20\,172.20.0.10/16" \
    --set gateways.istio-ingressgateway.type="NodePort" \
    --set servicegraph.enabled=true \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    --set certmanager.enabled=true \
    > $HOME/istio.yaml
```

then 
```
kubectl apply -f creds.yaml
kubectl apply -f istio.yaml
```

demo.yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: server
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 1443
      targetPort: 1234
  selector:
    app: server

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: test
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: server
        ver: v1
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: server
        image: "sdrzlyz/istio-demo-server:v5"
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc-port
          containerPort: 1234
        readinessProbe:
          tcpSocket:
            port: grpc-port
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: grpc-port
          initialDelaySeconds: 15
          periodSeconds: 20

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
  namespace: test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: client
        image: "sdrzlyz/istio-demo-client:v5"
        imagePullPolicy: Always
        env:
        - name: SADDR
          value: "server.test.svc.cluster.local:1443"
```

**Version**
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
```
helm template install/kubernetes/helm/istio \
    --name istio \
    --namespace istio-system \
    --set global.tag="1.0.1" \
    --set global.proxy.includeIPRanges="172.16.0.10/20\,172.20.0.10/16" \
    --set global.hyperkube.hub="hub.arctron.cn/coreos" \
    --set gateways.istio-ingressgateway.type="NodePort" \
    --set servicegraph.enabled=true \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    --set certmanager.enabled=true \
    --set certmanager.hub="hub.arctron.cn/istio-release" \
    > $HOME/istio.yaml
```

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
