### ISSUE TITLE
Quota Template with dimensions from request header

### ISSUE THREAD

**Issue by DaspawnW** [istio/istio#8526]
**Describe the bug**
I tried to deploy a redis request quota based on your example https://preliminary.istio.io/docs/tasks/policy-enforcement/rate-limiting.html.
The idea is here to use an authorization header to define as dimension for redisquota.

This doesn't seem to work. It seems that the authorization header is ignored.

**Expected behavior**
If I access the URL in two different requests with two different authorization headers I'll have access if for my authorization header the quota is not exceeded. For the other account with a maxAmount of 1 request in 20s the request should be denied.

**Steps to reproduce the bug**
Here is my configuration
```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: redisquota
metadata:
  name: handler
  namespace: istio-system
spec:
  connectionPoolSize: 10
  redisServerUrl: redis-master.redis:6379
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 1
    validDuration: 20s
    bucketDuration: 500ms
    rateLimitAlgorithm: ROLLING_WINDOW
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: request.headers["X-Test-Header"] | "unknown"
    destination: destination.labels["app"] | destination.workload.name | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  # quota only applies if you are not logged in.
  # match: match(request.headers["cookie"], "user=*") == false
  actions:
  - handler: handler.redisquota
    instances:
    - requestcount.quota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcount
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: ms-1
    namespace: microservices
    #  - service: '*'  # Uncomment this to bind *all* services to request-count
---
```

```bash
root@busybox:/# echo "$(date)" && curl https://ms-1.example.play/api/ms1  --insecure -H "X-Test-Header: 789" && echo ""
Thu Sep  6 14:27:35 UTC 2018
Hello World from ms1
root@busybox:/# echo "$(date)" && curl https://ms-1.example.play/api/ms1  --insecure -H "X-Test-Header: 789" && echo ""
Thu Sep  6 14:27:36 UTC 2018
Hello World from ms1
root@busybox:/# echo "$(date)" && curl https://ms-1.example.play/api/ms1  --insecure -H "X-Test-Header: 789" && echo ""
Thu Sep  6 14:27:37 UTC 2018
RESOURCE_EXHAUSTED:Quota is exhausted for: requestcount
root@busybox:/# echo "$(date)" && curl https://ms-1.example.play/api/ms1  --insecure -H "X-Test-Header: 123" && echo ""
Thu Sep  6 14:27:41 UTC 2018
RESOURCE_EXHAUSTED:Quota is exhausted for: requestcount

```
Here are the calls to access it via an external busybox container:

**Version**
```bash
istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

```
**Is Istio Auth enabled or not?**
```
~/Downloads/darwin-amd64/helm template install/kubernetes/helm/istio \
    --name istio \
    --namespace istio-system \
    --set global.mtls.enabled=true \
    --set global.proxy.includeIPRanges="10.32.0.0/24" \ # also include pod ip range to prevent direct access to port via port scan
    --set sidecarInjectorWebhook.enabled=false \
    --set ingress.enabled=false \
    --set gateways.istio-ingressgateway.enabled=true \
    --set gateways.istio-ingressgateway.type=NodePort \
    --set gateways.istio-egressgateway.enabled=true \
    --set gateways.istio-egressgateway.type=NodePort \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    --set security.enabled=true \
    > ../istio.yaml
```
**Environment**
Ubuntu 16.04

**Comment by mandarjog** [comment]
The rule in your configuration is applying quota unconditionally.
So all requests are going to be subject to the same quota `requestcount.quota.istio-system`, with source and destination dimensions.

If you wish you use the authorization header, you should 
1. dimension quota by `request.headers["authorization"]` and you can also reinstate `match` condition in the rule which is commented out in the config.

**Comment by DaspawnW** [comment]
Hi @mandarjog,

sorry I'm a bit confused.

How do I specify this, does I have to change this
```
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 1
    validDuration: 20s
    bucketDuration: 500ms
    rateLimitAlgorithm: ROLLING_WINDOW
```
to
```
  quotas:
  - name:request.headers["authorization"]
    maxAmount: 1
    validDuration: 20s
    bucketDuration: 500ms
    rateLimitAlgorithm: ROLLING_WINDOW
```
?

Why do I need the match condition in the quota, I thought the match in it is only if you will bypass the quota for special users?

**Comment by DaspawnW** [comment]
So to be more general, we are using in istio a JWT-Policy that connects to an keycloak server to validate JWTokens that are send as Authorization header.
Now I would be able to set Quotas per User. First I tried to use the JWToken as unique identifier, I know this was a stupid idea. Now I see that the jwt generates some values like: **request.auth.principal**.
I will do the quota dynamically per principal  because I don't know the users in the Keycloak.

As described in the tutorial https://preliminary.istio.io/docs/tasks/policy-enforcement/rate-limiting/ it can be per Client IP (In the above example we have effectively rate limited productpage at 2 rps per client IP). I copied the example above and adjusted it now to have as source of the dimensions in the quota-CRD the principal:
```
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: request.auth.principal
    destination: destination.labels["app"] | destination.workload.name | "unknown"
```

So I don't understand why this and also my old example with authorization header won't work, when you describe in the tutorial, that it's possible by client ip?

Here is also my auth policy:
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "ms-1"
  namespace: microservices
spec:
  targets:
  - name: ms-1
  peers:
  - mtls:
      mode: STRICT
  origins:
  - jwt:
      issuer: "https://<url>/auth/realms/default"
      jwksUri: "https://<url>/auth/realms/default/protocol/openid-connect/certs"
      audiences:
        - test-api
  principalBinding: USE_ORIGIN
```
