### ISSUE TITLE
More usable way for control egress traffice

### ISSUE THREAD

**Issue by x15zhang** [istio/istio#8572]
**Describe the feature request**
For control egress traffice,by default, Istio-enabled services are unable to access URLs outside of the cluster, we can enable access to external services by defining ServiceEntry configurations, or alternatively, to bypass the Istio proxy for a specific range of IPs.

But both of the two solution is not good.
1.Defining ServiceEntry is not convienent if there are too many services outside of the cluster.
2.Bypass the Istio proxy for a specific range of IPs let the specific range of IPs can not be managed or controlled by Istio.

The ideal way is that by default istio-enabled services are able to access all URLs,but can controll services outside of the cluster by defining other configs.

**Comment by x15zhang** [comment]
@rshriram @Kenny Bambridge

**Comment by rvandegrift** [comment]
I agree, the current developer/user experience for egress services is not pretty.  Especially in the case of HTTPS, I've found the config verbose and fragile.

I think the current experience could be improved just by providing higher-level resources that generate the ServiceEntry/VirtualService configuration:
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: SimpleEgressHTTPS
metadata:
  name: https-egress-services
spec:
  targets:
    - hostname: container.googleapis.com
    - hostname: pubsub.googleapis.com
    - hostname: secure.example.com
      port: 8443
```

This resource would do nothing but create the config in https://gist.github.com/rvandegrift/ca66734485fe052e70fe654642bb7add
