### ISSUE TITLE
SNI host is not a compatible subset of the virtual service hosts

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#8585]
**Istio**: 1.0.2

I seem to be running into this issue `Error: release apps failed: admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: SNI host is not a compatible subset of the virtual service hosts: *.sendgrid.com`

My virtual service configuration looks like below,
```
spec:
  hosts:
  - "api.sendgrid.com"
  tls:
  - match:
    - port: 443
      sniHosts:
      - "*.sendgrid.com"
    route:
    - destination:
        host: "api.sendgrid.com"
        port:
          number: 443
      weight: 100
```

Can someone please explain why this is not correct ? This is something that has been introduced in `1.0.2` (as part of https://github.com/istio/istio/pull/8342).

**Comment by nixgadget** [comment]
Bump. If someone could clarify whats required for this to work in the doc that would be awesome.

**Comment by berlwein-empiriecom** [comment]
I ran into a similar issue, maybe my solution works for you as well.
Istio >= 1.0.2 seems to require any hosts that you match on to also appear in the general "hosts" part, maybe try changing your config to the following (this changes line three):
```
spec:
  hosts:
  - "*.sendgrid.com"
  tls:
  - match:
    - port: 443
      sniHosts:
      - "*.sendgrid.com"
    route:
    - destination:
        host: "api.sendgrid.com"
        port:
          number: 443
      weight: 100
```
