### ISSUE TITLE
Grafana fails with persistence enabled

### ISSUE THREAD

**Issue by awdrius** [istio/istio#8594]
**Describe the bug**
Using istio 1.0.2 (chart reports 1.0.1) with grafana and grafana persistence enabled results in grafana pod failing with the error:
`GF_PATHS_DATA='/var/lib/grafana' is not writable.`

**Expected behavior**
Grafana to be running

**Steps to reproduce the bug**
Enable grafana and grafana persistence like this:
```
grafana:
  enabled: true
  persist: true
```

**Version**

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

istioctl version:
Not using istioctl

**Is Istio Auth enabled or not?**

I used helm chart with values.yaml file:
```
grafana:
  enabled: true
  persist: true
  storageClassName: standard
  security:
    enabled: true

tracing:
  enabled: true

kiali:
  enabled: true

certmanager:
  enabled: true
  tag: v0.4.1
```

**Environment**
GCP Kubernetes Engine

**Cluster state**
Fresh cluster with no additions, just what GKE supplies.

**Investigation**
Using https://github.com/grafana/grafana-docker/issues/167 as a base I edited `/install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml` and added securityContext to pod template spec:
```
      securityContext:
        runAsUser: 472
        fsGroup: 472
```
Attached is a diff file for it.

It works now, grafana is happily churning but I am not sure this is the correct way to solve the original issue.

[diff.txt](https://github.com/istio/istio/files/2366655/diff.txt)
