### ISSUE TITLE
Istio allows to break Kubernetes Namespace isolation when using `Ingress Gateway` and `VirtualService`

### ISSUE THREAD

**Issue by yskopets** [istio/istio#8615]
**Describe the bug**
In order to enforce Namespace isolation, `Kubernetes Ingress` resource only allows references to `Services` in the same `Namespace`.

In contrast, with `Istio` it's possible to create a `VirtualService` resource that references a `Service` from another Namespace and expose that `Service` to the outside world via `Ingress Gateway`.

**Expected behavior**
`Istio` should consistently enforce Kubernetes Namespace isolation.

**Steps to reproduce the bug**

Use 3 namespaces:
1. `namespace-a` - a namespace owned by "Istio Operator", where a cluster-wide `Istio Ingress Gateway` is defined
2. `namespace-b` - a namespace owned by "Team #1", where `httpbin` sample application is deployed 
3. `namespace-c` - a namespace owned by "Team #2", where `Istio VirtualService` resource is abused to expose to the outside world `httpbin` service owned by "Team #1"
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: shared-gateway
  namespace: namespace-a
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    # one Gateway for all services
    - "*"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: namespace-b
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: httpbin
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: namespace-c
spec:
  hosts:
  - "httbin-c.example.org"
  gateways:
  - shared-gateway.namespace-a.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        # Notice: here we intentionally expose a service from somebody's else namespace !!!
        host: httpbin.namespace-b.svc.cluster.local
```

**Version**
`istioctl version`:
```
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

`kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
Yes

**Environment**
GKE

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2372615/istio-dump.tar.gz)

**Comment by mabushey** [comment]
I have the exact opposite problem, as far as I can tell istio routes ONLY work on the default namespace. host: httpbin.namespace-b.svc.cluster.local will always result in "no healthy upstream" (with httpbin running in the namespace-b namespace) while httpbin.default.svc.cluster.local works, assuming a copy is running in the default namespace.

**Comment by mabushey** [comment]
Also I've read that gateways are not supposed to be namespaced, but possibly that's incorrect and why I'm having issues.

**Comment by yskopets** [comment]
@mabushey Hi!

I've posted the complete configuration at https://gist.github.com/yskopets/5d5242e7572ea782a8773789fcdb8560

**Comment by yskopets** [comment]
@mabushey The goal of this ticket is to point out a discrepancy between `Kubernetes` model and `Istio` model.

As an `Istio Operator`, I should be given a choice which model to enforce.

I think, it's not normal that behaviour which breaks Namespace isolation is a default and I have no knobs to prevent it.

**Comment by mabushey** [comment]
I have namespaces working now.

**Comment by sh777** [comment]
@mabushey
How did you make it work? I ran into the same issue today and couldn't make it work unless I put everything under default namespace.

**Comment by mabushey** [comment]
@sh777 Let's figure this out... Try adding this:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector: {}
  ingress:
  - {}
```

Make sure you list the namespace in the routing rule, for example here it's `istio-system`:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:           
  name: grafana                                        
spec:
  hosts:                                
  - "grafana.example.com"
  gateways:
  - elb-gateway      
  http:
  - match:
    - uri:     
        prefix: /  
    route:          
    - destination:
        port:  
          number: 3000
        host: grafana.istio-system.svc.cluster.local
```
