### ISSUE TITLE
service-graph installation should use specific version

### ISSUE THREAD

**Issue by effoeffi** [istio/istio#863]
Hello,

Istio version 0.1.6 installation, service-graph kubernetes deployment (servicegraph.yaml) uses `latest` as servicegraph docker image tag (`gcr.io/istio-testing/servicegraph:latest`), see:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicegraph
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicegraph
    spec:
      containers:
      - name: servicegraph
        image: gcr.io/istio-testing/servicegraph:latest
        ports:
          - containerPort: 8088
        args:
        - --prometheusAddr=http://prometheus:9090
```
https://github.com/istio/istio/releases/tag/0.1.6

Effi
