### ISSUE TITLE
Reaching out another pod with ClusterIP makes a failure connection

### ISSUE THREAD

**Issue by sneko** [istio/istio#8631]
Hi everyone!

I'm using Istio 0.7 with Auth enabled and I get an issue when my microservice with Envoy sidecar injected try to reach my Kafka Cluster.

To be more precise, my Kafka cluster has 2 kind of services:
- a basic one without any specific configuration
- another one with ClusterIP so that the connection is loadbalanced between each instance of my Kafka cluster

It appears that by using the basic one I can reach Kafka successfully, but when switching to the ClusterIP service, it sends something weird to the Kafka cluster and the microservice gets the error `connection reset by peer`.

I don't know if my description is understandable but I would like to know if it's a known issue ? I didn't find anything about that... What's weird is that's "outgoing" traffic of my microservice so I don't understand why Istio would change the data for internal cluster communication.

Thank you,

**Comment by mabushey** [comment]
I may be completely misunderstanding what you're stating, but with Istio you need to create an egress rule to allow outside communication. For example to allow https outbount to google.com, you need:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
```
