### ISSUE TITLE
Allow Istio Ingress to use ELB to do SSL termination

### ISSUE THREAD

**Issue by mabushey** [istio/istio#8638]
**Describe the feature request**
I would like to use a cert from AWS cert manager on an ELB to do the SSL Termination

**Describe alternatives you've considered**
Just use a Kubernetes LoadBalancer Service
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:754210483472:certificate/0c9ccc7b-27f2-43c6-a93f-4efb8a3e6a46"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

**Comment by ibelikov** [comment]
@mabushey this already works fine. Keep in mind that you need to change the protocol of https port in you gateway configuration to HTTP.

**Comment by mabushey** [comment]
@ibelikov Thanjk, awesome! Unfortunately I can;t make this work / have no idea how to do this.

This is what I have in my gateway.yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecample.com-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.example.com"
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "*.example.com"
```

**Comment by ibelikov** [comment]
@mabushey well, similar config actually works for me.

A couple of things that you could check:

1. If you applied annotations to Ingress Gateway service after the ELB was created, check that they actually are applied (e. g. ELB listeners in AWS are HTTP/HTTPS, not TCP and the right certificate is actually set to be served). Trying with freshly created ELB also works.
2. Change port names in Gateway to something unique (but keeping the protocol prefix), I stick to "http-gatewayname-namespace" and "https-gatewayname-namespace" style naming. It's not that obvious through Istio docs, but a lot of issues with multiple Gateways come from using the same port names.

**Comment by mabushey** [comment]
@ibelikov Thanks for the tip on the gateway name. I did not apply any annotations to the gateway, I'm doing everything in default as namespaces are not compatible with istio Ingress.

> the right certificate is actually set to be served
No, it's not. It does not appear that Istio can work with cert manager. Kubernetes supports this, but not Istio.

**Comment by mabushey** [comment]
I was able to manually hack the LB to get it to work. I deleted the listener for 443 HTTPS to 31390 HTTP and recreated it using the SSL cert in Cert Manager.

**Comment by cmcconnell1** [comment]
Hello All,

Curious if there's a way to configure/deploy Istio Ingress with L7 Term on the ELB using the ARN for a certificate (in AWS IAM)  similar to how it is done for kubernetes ingress-nginx?:

Ref: [Kubernetes ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/master/docs/deploy/index.md#aws)
Kubernetes ingress-nginx uses an Elastic Load Balancer (ELB) to expose the NGINX Ingress controller behind a Service of Type=LoadBalancer. Since Kubernetes v1.9.0 it is possible to use a classic load balancer (ELB) or network load balancer (NLB).

Which looks something like this for a legacy ELB:
```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::0123456789012:server-certificate/my-company-com-crt"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http
---
```

I've read the Istio docs noted below, but being new to Istio I could be missing something.
[configuring-ingress-using-an-istio-gateway](https://istio.io/docs/tasks/traffic-management/ingress/#configuring-ingress-using-an-istio-gateway)
[secure ingress](https://istio.io/docs/tasks/traffic-management/secure-ingress/)

On this note, seeing an open issue for [Istio Ingress TLS key management use ACM #6566](https://github.com/istio/istio/issues/6566)

Thanks
