### ISSUE TITLE
End user JWT authentication is not working as expected with a OAuth2 Server running within the k8s cluster

### ISSUE THREAD

**Issue by mefarazath** [istio/istio#8659]
**Describe the bug**

I am trying out the [JWT end-user authentication sample](https://istio.io/help/ops/security/end-user-auth/) with WSO2 Identity Server as the JWT Issuer. Below is the authentication policy I used

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: httpbin
  origins:
  - jwt:
      issuer: "https://localhost:9443/oauth2/token"
      jwksUri: "https://gist.githubusercontent.com/mefarazath/0757201b14de6f2a3c01b62d39648367/raw/1a37b704825f64f0763dfc02dfabc1af44fb344b/test-jwt.jwks"
  principalBinding: USE_ORIGIN
```

As you see in the above policy I had to use a public url (https://gist.githubusercontent.com/mefarazath/0757201b14de6f2a3c01b62d39648367/raw/1a37b704825f64f0763dfc02dfabc1af44fb344b/test-jwt.jwks) to simulate my jwks endpoint since I could not get the sample working with the WSO2 server deployed within the cluster

I deployed the OAuth2 Server using,
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cell-iam
    version: v1
  name: cell-iam-service
spec:
  clusterIP: 10.104.92.228
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30994
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: cell-iam
    version: v1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cell-iam
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cell-iam
        version: v1
    spec:
      containers:
      - name: cell-iam
        image: mefarazath/lightweight-wso2is
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9443
---
```

I confirmed that the JWKS endpoint is accessible within the k8s cluster using the cluster IP or NodePort by running an ubuntu image in a pod within the same namespace. I tried replacing the jwksUri with clusterIp and the sample stopped working. From the isito proxy logs I was able to see,

```
[2018-09-12 12:26:12.571][17][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 172.17.0.13_8000: Proto constraint validation failed (JwtAuthenticationValidationError.Rules[i]: ["embedded message failed validation"] | caused by JwtRuleValidationError.LocalJwks: ["embedded message failed validation"] | caused by DataSourceValidationError.InlineString: ["value length must be at least " '\x01' " bytes"]): rules {
  issuer: "https://localhost:9443/oauth2/token"
  local_jwks {
    inline_string: ""
  }
  forward: true
  forward_payload_header: "istio-sec-948f5aaa926a8a4d63e3ad5bf058ce381a69561e"
}
allow_missing_or_failed: true
```

For the working case (jwks url as a public url)
```
[2018-09-12 12:26:20.370][17][info][config] ./src/envoy/http/jwt_auth/auth_store.h:72] Loaded JwtAuthConfig: rules {
  issuer: "https://localhost:9443/oauth2/token"
  local_jwks {
    inline_string: "{\"keys\":[{\"kty\":\"RSA\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"NTAxZmMxNDMyZDg3MTU1ZGM0MzEzODJhZWI4NDNlZDU1OGFkNjFiMQ\",\"alg\":\"RS256\",\"n\":\"luZFdW1ynitztkWLC6xKegbRWxky-5P0p4ShYEOkHs30QI2VCuR6Qo4Bz5rTgLBrky03W1GAVrZxuvKRGj9V9-PmjdGtau4CTXu9pLLcqnruaczoSdvBYA3lS9a7zgFU0-s6kMl2EhB-rk7gXluEep7lIOenzfl2f6IoTKa2fVgVd3YKiSGsyL4tztS70vmmX121qm0sTJdKWP4HxXyqK9neolXI9fYyHOYILVNZ69z_73OOVhkh_mvTmWZLM7GM6sApmyLX6OXUp8z0pkY-vT_9-zRxxQs7GurC4_C1nK3rI_0ySUgGEafO1atNjYmlFN-M3tZX6nEcA6g94IavyQ\"}]}"
  }
  forward: true
  forward_payload_header: "istio-sec-948f5aaa926a8a4d63e3ad5bf058ce381a69561e"
}
allow_missing_or_failed: true
```

Appreciate some suggestions to debug this further to get this working.

**Version**
istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Followed https://istio.io/docs/setup/kubernetes/

**Environment**
Ubuntu 14.04
minikube version: v0.28.2
istion: Version: 1.0.2
