### ISSUE TITLE
Istio Pilot HPA (HorizontalPodAutoscaler) created in default namespace

### ISSUE THREAD

**Issue by sporokh** [istio/istio#8693]
**Describe the bug**
When installing istio-1.0.0 (or even 1.0.1) with Helm all HPA being deployed to istio-system namespace (or the namespace you provide to helm during install), but istio pilot always deployed to default namespace. From the chart (no namespace field at all, comparing to other HPA's):
```
{{- if .Values.autoscaleMin }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: istio-pilot
spec:
    maxReplicas: {{ .Values.autoscaleMax }}
    minReplicas: {{ .Values.autoscaleMin }}
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: istio-pilot
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.cpu.targetAverageUtilization }}
---
{{- end }}
```

**Expected behavior**
Istio HPA pilot should be in the istio-system namespace.

**Steps to reproduce the bug**
Install istio using helm with `--namespace istio-system` and execute
`kubectl get hpa --all-namespaces`

**Version**
Kubernetes 1.10.3
Istio-1.0.0 and Istio-1.0.1

**Installation**
With the Helm chart. Official from this page:
https://istio.io/docs/setup/kubernetes/helm-install/

**Environment**
AWS EKS

**Cluster state**
Not required.
