### ISSUE TITLE
Internal Kubernetes API Calls Blocked by Istio

### ISSUE THREAD

**Issue by rsnj** [istio/istio#8696]
**Describe the bug**
I'm installing a monitoring service in to my pod which is trying to make a call to the Kubernetes API server. This request is being blocked by the Istio sidecar. If I disable the `istio-injection` and redeploy everything works as planned. Do I need to enable anything to make this work?

**Expected behavior**
My pods can access the internal Kubernetes API

**Steps to reproduce the bug**
```
curl https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/default/pods
```
from inside my pod does not respond.

**Version**
Istio:
```
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```
helm install install/kubernetes/helm/istio \
    --name istio \
    --namespace istio-system \
    --set certmanager.enabled=true
```

**Environment**
Microsoft Azure AKS

**Comment by krancour** [comment]
I can confirm this issue exists and is also the root cause of Knative not working on AKS-- their autoscaler, which is a controller, is unable to sync with the Kubernetes apiserver. Disabling the `istio-proxy` sidecar on that pod fixes things, but my sense is that's not the right thing to do.

It's perplexing to me that this occurs in AKS but not elsewhere.

Can someone help me troubleshoot this? (I work for Azure.)

**Comment by adinunzio84** [comment]
We have this problem - we made a ServiceEntry and VirtualService to account for the fact that the apiserver is now accessed over a public URL. I made the following ServiceEntry and VirtualService:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: azmk8s-ext
spec:
  hosts:
  - "<my-cluster>.hcp.centralus.azmk8s.io"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tls-routing
spec:
  hosts:
  - <my-cluster>.hcp.centralus.azmk8s.io
  tls:
  - match:
    - port: 443
      sniHosts:
      - <my-cluster>.hcp.centralus.azmk8s.io
    route:
    - destination:
        host: <my-cluster>.hcp.centralus.azmk8s.io
    timeout: 0.5s
```

This gets it to the point where I can access the api-server, but after 5 minutes, it stops working, and calls to the api-server hang. Also, calls to Go's **net.LookupIP(host)** hang during this period, when providing the FQDN of the AKS apiserver.

I found that if I wait 10-15 minutes, the problem seems to resolve itself, but starts failing again after another 5 minutes. I also found that I can make a request to the apiserver when it's working, and that seems to delay the point where it stops. I made a request, then another 1 minute later - and it started failing 5 minutes after the 2nd request, not the first.

Hope this is helpful!

**Comment by adinunzio84** [comment]
@mkjoerg, does the plug-in use client-go? If so, there's a strange issue that seems to only happen when combining Istio, AKS, and client-go (but any 2 are fine): kubernetes/client-go#527

**Comment by mkjoerg** [comment]
@adinunzio84, no the rabbitmq plugin is erlang based. https://github.com/adinunzio84

**Comment by krancour** [comment]
While kubernetes/client-go#527 may technically still be an issue, I want to point out that there is now, at least, a workaround in place on the AKS end.

A mutating webhook is now overwriting environment variables such as `KUBERNETES_SERVICE_HOST` for all pods with the _external_ DNS name for your Kubernetes apiserver. The practical effect of this is that traffic bound for the apiserver exits and re-enters the cluster (which isn't ideal-- hence why I count this as a workaround rather than a solution). The load balancer(s) that are involved in this alternative route to the apiserver are not subject to the difficulties explained in kubernetes/client-go#527.

While this may be more of a workaround than a strategic solution, it's fair to say that this issue is effectively remediated. Should we consider closing it?

**Comment by adinunzio84** [comment]
@krancour are you sure about: "The load balancer(s) that are involved in this alternative route to the apiserver are not subject to the difficulties explained in kubernetes/client-go#527."?

I [commented here](https://github.com/Microsoft/ApplicationInsights-Kubernetes/issues/169#issuecomment-456872286) more info about the issue I describe in kubernetes/client-go#527, and it seems it's actually more related to the load balancers involved with AKS than client-go.

If applications with Istio sidecars are able to access the API server after the 5-minute window (where the LB closes the connection), then I'd say we can close this. Otherwise, in my opinion, this should remain open and depends on envoyproxy/envoy#3634

**Comment by krancour** [comment]
@adinunzio84, the cluster-internal load balancers and externally facing load balancers are different. The externally facing load balancers have had TCP reset as an opt-in "preview" feature since mid-September, while the cluster-internal load balancers, if I understand correctly, still lack this feature.

https://azure.microsoft.com/en-us/updates/load-balancer-outbound-rules/

Oddly, when I dig down into LB details, I cannot see any evidence that AKS actually enabled the feature in question when it deployed the cluster, _however_, I am currently observing correct/desired behavior.

I'll follow up with my colleagues on the AKS team to figure out what's going on here.

If you want to try this yourself, perhaps you can independently verify / refute that this works as I claim.

**Comment by krancour** [comment]
That is correct. The post I linked to does reference standard load balancers, whilst AKS is currently using basic load balancers only-- which deepens the mystery of why this is now working.

**Comment by vcanaa** [comment]
Internal Kubernetes API calls seem to fail for the first seconds. You might find the this repro useful: see update of #12187

**Comment by omerfsen** [comment]
I know it is an old issue but i solved this issue with:

K8S_INTERNAL_API_IP=$(kubectl get svc  kubernetes -o jsonpath='{.spec.clusterIP}')
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
....
.....
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        envoyStatsd:
          enabled: false
        excludeIPRanges: "${K8S_INTERNAL_API_IP}/32"
```

Path is: 

**.spec.values.global.proxy.excludeIPRanges**

**Comment by taitelman** [comment]
how about 
```
kind: IstioOperator
metadata:
  namespace: perators
  name: my-iop
spec:
  profile: empty
  values:
    global:
      proxy:
        excludeIPRanges: "172.21.0.0/32" # don't let istio egress rules block K8s API
```

**Comment by xlanor** [comment]
> I know it is an old issue but i solved this issue with:
> 
> K8S_INTERNAL_API_IP=$(kubectl get svc kubernetes -o jsonpath='{.spec.clusterIP}')
> 
> ```yaml
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec:
> ....
> .....
>       proxy:
>         autoInject: enabled
>         clusterDomain: cluster.local
>         componentLogLevel: misc:error
>         enableCoreDump: false
>         envoyStatsd:
>           enabled: false
>         excludeIPRanges: "${K8S_INTERNAL_API_IP}/32"
> ```
> 
> Path is:
> 
> **.spec.values.global.proxy.excludeIPRanges**

thank you so much. This worked perfectly.

I was running into an issue because I'm using kubectl in init containers to check job statuses before deploying a replicaset. couldnt connect to the api at all.

**Comment by jdelgadillo** [comment]
We just switched from Contour to Istio (1.9.4) on our dev environments and are running into this issue *alot*

We've modified our IstioOperator settings with the excludeIPRanges mentioned in this issue, but we're still seeing the issue.

It tends to happen regularly when our nightly builds get deployed to our dev clusters (~2AM PT).  After enough restart, the problem seems to go away, but we've yet to find the surefire workaround/remedy.

Any other things we should be looking at?

**Comment by jdelgadillo** [comment]
We managed to get around this issue with the following DestinationRul in our services' namespace:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: k8s-default-destrule
  namespace: my-service-namespace
spec:
  host: "kubernetes.default.svc" #Disabling it for Kube API Server communication
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Comment by jdelgadillo** [comment]
Even with the DestinationRule, we're still seeing intermittent issues talking to kubernetes.default.svc and ElasticSearch instances in different namespaces.  We've added retries in our code as well as a VirtualService to kubernetes.default.svc with retries, yet we still see intermittent issues.  The issues were present, but not nearly as common since the switch to istio.

**Comment by taitelman** [comment]
ok so I have another solution : try this master sidecar config:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-system  # or just place here your container NS
spec:
  egress:
    - hosts:
        - ./*
        - default/kubernetes.default.svc.cluster.local
        - default/etcd.default.svc.cluster.local
        - istio-system/*
 ```
 advice given by @WilliamNewshutz
