### ISSUE TITLE
virtualservices not working with no suffixed domains

### ISSUE THREAD

**Issue by AWKIF** [istio/istio#8720]
Hello

**Describe the bug**
virtualservices with for example:
apiVersion: networking.istio.io/v1alpha3
```
kind: VirtualService
metadata:
  name: go-vs
  namespace: default
spec:
  hosts:
  - "go"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: golink-server.ee.svc.dev.kubernetes
```
while if you put something like  go.xxx.yyy it is working

**Expected behavior**
redirect to the service when matching host header

**Steps to reproduce the bug**
Create a virtualservice with a no suffixed domain

**Version**
istio 1.0.0

**Installation**
helm templating

**Environment**
baremetal k8s 1.10.3

Thank you !

**Comment by UnwashedMeme** [comment]
The docs mention this, see the `hosts` field definition in https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService

> Note for Kubernetes users: When short names are used (e.g. “reviews” instead of “reviews.default.svc.cluster.local”), Istio will interpret the short name based on the namespace of the rule, not the service. A rule in the “default” namespace containing a host “reviews will be interpreted as “reviews.default.svc.cluster.local”, irrespective of the actual namespace associated with the reviews service. To avoid potential misconfigurations, it is recommended to always use fully qualified domain names over short names.

But I found this to be irritating when I encountered it the other day too.   It will never match a barehostname, it always rewrites it to be fully qualified in the envoy config. I wish it did both.

**Comment by AWKIF** [comment]
@UnwashedMeme Thanks, the issue is that it's not about my service name but my url host, i'd like to reach my apps through http://go/xxx
Is there a way to add this for the next release?

**Comment by UnwashedMeme** [comment]
@AWKIF, yes, that was my experience as well: when I tried to define a barehostname, e.g. 

```
metadata:
  namespace: foo
kind: VirtualService
spec:
   hosts:
     - go
```

The envoy config it generates is for `go.foo.svc.cluster.local` as such it will not match http://go/.  When I tried to do something similar I found in the logs from pilot:

> parseHostname(customer-webapi) => error missing service name and namespace from the service hostname "customer-webapi"

I believe this comes from https://github.com/istio/istio/blob/6fcedc7558486963fead83c65fd03ca69c09fd08/pilot/pkg/serviceregistry/kube/conversion.go#L161

So given that behavior it really looks like istio won't do what you and I are trying to do right now. I agree it would be nice, but we'll have to wait for a project maintainer to weigh in as to why. I don't know the larger context.
