### ISSUE TITLE
How to configure egress for different external TCP service with same port

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#8833]
**Describe the bug**
{{ Succinctly describe the bug }}

In our company, the database/mq resources which each service depends on are using different domain, but the ports are all same(mysql:3306, kafka:9093). every resource is different, so it cannot be shard. 

According to [8410](https://github.com/istio/istio/issues/8410) mentioned, when TCP service entry is set without an address field and the resolution is set to NONE, however I have made the following configuration but it still doesn't work.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-mysql-all
spec:
  hosts:
  - mysql-1.xxx.io
  - mysql-2.xxx.io
  - mysql-3.xxx.io
  ports:
  - name: tcp
    number: 3306
    protocol: TCP
  resolution: NONE
```

i'm also confusing that the tcp serviceentry need a address field, however some external host ip range is not public. And the 9093 port of mixer is conflict with kafka port...

**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}
istio 1.0.1

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
kubernetes

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
