### ISSUE TITLE
outlier detection destination rule not eliminating any upstream hosts

### ISSUE THREAD

**Issue by bijukunjummen** [istio/istio#8846]
**Describe the bug**
Envoy outlier detection not eliminating any upstream hosts which were programmed to return 5xx for every request, with the following Circuit breaker setting:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-destination-rule
spec:
  host: backend-app-service
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
```
I doubt if I hit the [panic threshold](https://www.envoyproxy.io/docs/envoy/latest/faq/lb_panic_threshold) as the stats dump did not show any numbers against panic threshold.

```
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.lb_healthy_panic: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_active: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_consecutive_5xx: 2
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_detected_consecutive_5xx: 2
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_detected_consecutive_gateway_failure: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_detected_success_rate: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_enforced_consecutive_5xx: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_enforced_consecutive_gateway_failure: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_enforced_success_rate: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_enforced_total: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_overflow: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_success_rate: 0
cluster.outbound|8080||backend-app-service.istio-test.svc.cluster.local.outlier_detection.ejections_total: 2
```
 
**Expected behavior**
All the hosts should be eliminated.

**Steps to reproduce the bug**

The following destination rule, with the pods in the service returning 5xx for every call.
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-destination-rule
spec:
  host: backend-app-service
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
```

When I exported envoy config using :
```
kubectl exec -it client-app-v3-75f95ccf5f-9d99s  -c istio-proxy  -- sh -c 'curl localhost:15000/config_dump'
```

The envoy config showed up as:
```
"outlier_detection": {
       "interval": "30s",
       "base_ejection_time": "180s",
       "max_ejection_percent": 100,
       "enforcing_consecutive_5xx": 0,
       "consecutive_gateway_failure": 1,
       "enforcing_consecutive_gateway_failure": 100
      }
```

See how the `enforcing_consecutive_5xx` is set as 0 and is not configurable from `destinationrule`. I think it needs be configurable also, per [this document](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/outlier_detection.proto#envoy-api-field-cluster-outlierdetection-consecutive-5xx), it is 

> The % chance that a host will be actually ejected

and so setting to 0 will not eject any hosts?

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
```
$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
On Minikube based on instructions here - https://istio.io/docs/setup/kubernetes/quick-start/

**Environment**
All on minikube

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by UnwashedMeme** [comment]
If you look at the stats from envoy 

> ... .outlier_detection.ejections_total: 2

So they are being ejected, they aren't staying ejected. This looks like the same behavior I saw in #8673. Try looking at `.membership_change`, does that increase every couple seconds and reset `.ejections_active` back to 0 when it does?

**Comment by UnwashedMeme** [comment]
In my case I spotted `ejections_active =1` it just got reset back to 0 after only a few seconds--the same time membership change increased on its regular schedule.

I also saw `ejections_detected_consecutive_gateway_failure` increasing; as far as I recall from my research envoy has both a consecutive 5xx and a consecutive gateway failures ([Detection Types](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/outlier#detection-types)) but I think istio is only using the consecutive gateway fails. I think I recall confirming that with looking at the envoy `/config_dump`.

**Comment by hemantseth0210** [comment]
I was able to manage it work in my case. Initially it wasn't tripping the circuit when I was returning 500 error from the service. Outlier detection was configured like below:
```
trafficPolicy:
      outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 10m
      maxEjectionPercent: 100
```

I pulled up the config using
`kubectl exec podname -i -t -c istio-proxy -- curl localhost:15000/config_dump` 

I found out that envoy config was set to 
```
"outlier_detection": {
       "interval": "1s",
       "base_ejection_time": "600s",
       "max_ejection_percent": 100,
       "enforcing_consecutive_5xx": 0,
       "consecutive_gateway_failure": 1,
       "enforcing_consecutive_gateway_failure": 100
      }
```
Basically consecutiveErrors was translating to consecutive_gateway_failure. When I looked up in this doc [https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/outlier#detection-types](url) I concluded that consecutive_gateway_failure only works 
> If an upstream host returns some number of consecutive “gateway errors” (502, 503 or 504 status code), it will be ejected

When I modified my service to return 503 I tripped the circuit for me. However, I agree with @bijukunjummen that there should be some way to set up the enforcing_consecutive_5xx value.

I hope someone can benefit from my answer.

**Comment by Dimss** [comment]
@hemantseth0210 you are 100% right! Thank you! :) 
I just spent view hours to understand why my broken pod wasn't ejected from the poll, and apparently it was an 500 issue. 
I've created a test SpringBoot app, with just throw 500 error, and until I changed it to return 502, my broken pod wasn't  ejected from the pool. 
Looks like there is a bug in Istio docs where clearly say, that `5xx return code qualifies as an error` -> 
`https://istio.io/docs/reference/config/istio.networking.v1alpha3/#OutlierDetection`
Anyhow here is my working configs: 

**Deployment**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubis-rest
spec:
  serviceName: "kubis-rest"
  replicas: 2
  selector:
    matchLabels:
      app: kubis-rest
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: kubis-rest
        version: v0-3
    spec:
      containers:
      - name: kubis-rest
        image: "docker-registry.default.svc:5000/kubis/kubis-rest:0.3.5"
        ports:
        - containerPort: 8080
```

**DestinationRule and VirtualService**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kubis-rest
spec:
  host: kubis-rest
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutiveErrors: 1
      interval: 10s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
  subsets:
  - name: v0-3
    labels:
      version: v0-3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubis-rest
spec:
  hosts:
    - kubis-rest
  http:
  - route:
    - destination:
        host: kubis-rest
        subset: v0-3
```
