### ISSUE TITLE
Inter pod communication using ${POD_IP//./-}.default.pod.cluster.local addresses

### ISSUE THREAD

**Issue by sebarys** [istio/istio#8871]
**Describe the bug**

Hi,
We are using Istio version: 0.8.0 with mTLS enabled. I have tried to configure akka cluster to work behind Istio sidecards. Setup described here https://github.com/akka/akka-management/issues/209 unfortunately is not working for me.

Example situation:
I have three nodes with IPs: 10.244.17.28, 10.244.35.45, 10.244.17.29
During initialisation single node is requesting endpoint that returns seed nodes on each node in the cluster. So node with IP 10.244.17.28 will request following requests:
- `curl http://10-244-35-45.mynamespace.pod.cluster.local:8558/bootstrap/seed-nodes` -> 200
- `curl http://10-244-17-29.mynamespace.pod.cluster.local:8558/bootstrap/seed-nodes` -> 200
- `curl http://10-244-17-28.mynamespace.pod.cluster.local:8558/bootstrap/seed-nodes` -> The connection closed with error: Connection reset by peer

I don't know why but node couldn't request itself using `${POD_IP//./-}.default.pod.cluster.local` address, but is able to call other nodes. When I tried to request it by curl http://localhost:8558/bootstrap/seed-nodes everything is working well. Below example manifests:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: efc-istio
  namespace: mynamespace
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: efc-istio
        tier: backend
        version: istio
        env: us
    spec:
      containers:
      - name: efc-istio
        image: efc:istio-test
        imagePullPolicy: Always
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2551
          protocol: TCP
        # external http
        - name: http-akka-mgmt
          containerPort: 8558
          protocol: TCP
        # akka-management bootstrap
        - name: bootstrap
          containerPort: 8558
          protocol: TCP
        # application endpoint
        - name: http-app
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 0.7Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        envFrom:
        - configMapRef:
            name: efc-istio
        - secretRef:
            name: efc-istio
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: APP_NAME
          value: "efc"
---
apiVersion: v1
kind: Service
metadata:
  name: efc-istio
  namespace: mynamespace
  labels:
    app: efc-istio
    version: istio
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  - port: 2551
    name: remoting 
    protocol: TCP
    targetPort: 2551
  - port: 8558
    name: akka-mgmt-http
    protocol: TCP
    targetPort: 8558
  selector:
    app: efc-istio
    version: istio
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: akka-internal-traffic
spec:
  hosts:
  - "*.mynamespace.pod.cluster.local"
  location: MESH_INTERNAL
  ports:
  - number: 2551
    name: "remoting"
    protocol: TCP
  - number: 8558
    name: "http-akka-mgmt"
    protocol: HTTP
  resolution: NONE

```

**Expected behavior**

Node should request successfully other nodes and itself using addresses like `*.mynamespace.pod.cluster.local` what allow it to form cluster properly.

**Steps to reproduce the bug**

Above I pasted manifest with example configuration

**Version**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-13T09:23:50Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Environment**

K8s cluster deployed in AWS.

Thanks in advance for your help and suggestions ;)
