### ISSUE TITLE
Services with named ports inaccessible in istio-1.0.2

### ISSUE THREAD

**Issue by cdmitri** [istio/istio#8919]
**Describe the bug**
HTTP services that are do not have an http- prefix can not be accessed.

**Expected behavior**
While the requirement for "http-" prefix is touched upon here: https://istio-releases.github.io/v0.1/docs/tasks/integrating-services-into-istio.html, this requirement is not obvious in other parts of documentation and examples.

Other projects stumbled upon this as well and took a while to pin-point.

Same service definitinios used were confirmed to work in previous versions. Since it was a new version migration problem for us (from 1.0.0), I'm opening it as issue so that others can find it quicker. 

Possibility of handling it as a separate setting instead of a "prefix" was discussed here: https://github.com/istio/old_issues_repo/issues/88. 

Similar settings and behaviour is explicitly different and described in documentation here: https://istio.io/docs/reference/config/istio.networking.v1alpha3/, including a separate "protocol" setting and a port name without a "http-" prefix.

**Question:** Should he have an effort to make these settings to be consistent across all definitions and not rely on the prefix in favor of a separate setting as in Gateway definition?

**Steps to reproduce the bug**
Remove "http-" prefix from a regular service definition. Example: 

```
# does not work
apiVersion: v1
kind: Service
metadata:
    name: squeak-devshell-svc
    labels:
      app: squeak-devshell-app
spec:
  ports:
  - port: 32323
    name: someportname
    targetPort: 54321
  selector:
    app: squeak-devshell-app
....
```
```
# works
apiVersion: v1
kind: Service
metadata:
    name: squeak-devshell-svc
    labels:
      app: squeak-devshell-app
spec:
  ports:
  - port: 32323
    name: http-someportname
    targetPort: 54321
  selector:
    app: squeak-devshell-app
...
```
more detailed description: https://gist.github.com/cdmitri/dce98692b05dbe6274e64d66999d3cc7

**Version**
* istio-1.0.2
* kubernetes v1.10

**Installation**
* kubectl create -f istio-demo.yaml

**Environment**
* GKE

**Comment by jaygorrell** [comment]
Isn't this covered well by this page?
https://istio.io/docs/setup/kubernetes/spec-requirements/

This is linked to from almost every installation page. It's also on the traffic management FAQ:
https://istio.io/help/faq/traffic-management/#naming-port-convention

**Comment by cdmitri** [comment]
Hi @jaygorrell - thanks for the references! Yes, I think there are some places in the docs that once you know or suspect that the issue has something to do with a "port name", you can find a confirmation that this is your problem. The tricky part is that if let's say you're starting from some point in the documentation without reading it whole (or updates), there are some places where this is not mentioned. Also in related docs like here: https://istio.io/docs/reference/config/istio.networking.v1alpha3/ the ServiceEntry is setup explicitly by using a different format for the port name and with a separate setting:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-wikipedia
spec:
  hosts:
  - wikipedia.org
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: example-http
    protocol: HTTP
  resolution: DNS
```

Since I've noticed that there has been continuing discussion it would be good to know if there are plans to change the prefix requirement completely and/or add additional references to this info in other parts of the docs that might make it even more obvious.

Cheers,
Dmitri
