### ISSUE TITLE
Readiness and Liveness probes failing frequently without mTLS 

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#8963]
**Describe the bug**
I have an environment with 100+ deplyoments, mostly consisting of 2 pods each. Somewhere around 1/3 of the pods seem to have regular restarts due to liveness probe failures.

Most other issues already filed seem to be related to one of two things:
1. mTLS is enabled and k8s cannot perform the health check
2. Race conditions with the service start-up and the sidecar not being ready

In this case, it's neither of those. The pods are failing after being up and running for a while. No mTLS is enabled in this environment. 

Perhaps one of the more interesting things is that the restarts seem to follow a pod... meaning I have lots of pods with 0 restarts and the ones with restarts have maybe 5-10 throughout the day. Deleting a pod with restarts usually replaces it with a new pod that starts to accumulate restarts as well.

I do not think this is actually specific to liveness probes because _some_ service calls are failing as well... I think there is just some inconsistency in the service availability. I have not implemented retries or anything yet because I'd like to resolve this issue before putting a band-aid in place.

**Expected behavior**
Running Istio does not significantly increase the failure rate of liveness probes.

**Steps to reproduce the bug**
Sorry, I'm not entirely sure what the cause is to trigger it here. I can say I have over 500 pods in the environment and they don't have issues without Istio.

**Version**
Istio: 1.0.2
Kubernetes: 1.9.3

**Installation**
`helm template` with the following vars file:
```
global:
  proxy:
    # Only send internal requests through the mesh
    includeIPRanges: "100.64.0.0/10"

prometheus:
  enabled: true

grafana:
  enabled: true
```

**Environment**
AWS Kops-built Cluster

**Comment by nmittler** [comment]
@andraxylia unassigning for now.  It doesn't seem to be related to the sidecar readiness probe.

**Comment by jaygorrell** [comment]
Correct @nmittler. In fact, I'm pretty certain this isn't really related to readiness probes on the services themselves either -- they are just a reliable way to discover the problem in the `describe pod` output.

I've had reports from many users getting things like `upstream connect error or disconnect/reset before headers`, which may be a little more helpful.

One more thing of note, almost all of our services run on 8080 and our `Service` resource looks like this in every case:
```
apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  selector:
    app: service-name
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
```

And I guess I should note that I haven't added VirtualService or DestinationRules yet.
