### ISSUE TITLE
Deploy individual jaeger components(agent/collector/query) instead of all-in-one

### ISSUE THREAD

**Issue by wentao-zh** [istio/istio#8965]
**Describe the feature request**
The deployment of Jaeger is all-in-one mode. That means all of the 3 components(jaeger agent/collector/query UI) are in one container and data is in memory. This deployment can not be used in production. A better way is to provide individual deployment for each jeager component.

**Describe alternatives you've considered**
I modified the jaeger deployment part of istio yaml like the snippet below. And specify an ELK as it's backend storage. It works for me.
```
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5778
              protocol: TCP
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "jaeger-collector.istio-system.svc.cluster.local:14267"         
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-tracing-query
  namespace: istio-system
  labels:
    app: istio-tracing-query
    chart: tracing-query-0.1.0
    release: istio
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: jaeger-query
          image: jaegertracing/jaeger-query
          imagePullPolicy: IfNotPresent
          args:
          - "--es.server-urls=http://$ELASTIC_SEARCH:9200"
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 16687
              protocol: TCP
          env:
          - name: SPAN_STORAGE_TYPE
            value: "elasticsearch"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-tracing-collector
  namespace: istio-system
  labels:
    app: istio-tracing-collector
    chart: tracing-collector-0.1.0
    release: istio
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: jaeger-collector
          image: jaegertracing/jaeger-collector
          imagePullPolicy: IfNotPresent
          args:
          - "--es.server-urls=http://$ELASTIC_SEARCH:9200"
          - "--es.num-shards=1"
          ports:
            - containerPort: 14269
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14267
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          env:
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
             value: "9411"
          - name: SPAN_STORAGE_TYPE
             value: "elasticsearch"
```

**Additional context**
I'd like to put the snippet into the Helm Chart template of istio and summit a PR
