### ISSUE TITLE
can't create virtualservice with tcp route in 0.8

### ISSUE THREAD

**Issue by huydinhle** [istio/istio#9012]
### pilot logs
{"level":"error","time":"2018-09-27T18:29:20.060578Z","msg":"Failed to convert virtual-service object, ignoring: default/laanc-routing YAML decoding error: gateways:\n- mesh\n- istio-egressgateway\nhosts:\n- laanc.prod.airmap.com\nhttp:\n- match:\n  - gateways:\n    - mesh\n    port: 3128\n  route:\n  - destination:\n      host: istio-egressgateway.istio-system.svc.cluster.local\n- match:\n  - gateway:\n    - istio-egressgateway\n    port: 3128\n  route:\n  - destination:\n      host: laanc.prod.airmap.com\n unknown field \"gateway\" in v1alpha3.HTTPMatchRequest map[gateways:[mesh istio-egressgateway] hosts:[laanc.prod.airmap.com] http:[map[match:[map[gateways:[mesh] port:3128]] route:[map[destination:map[host:istio-egressgateway.istio-system.svc.cluster.local]]]] map[match:[map[gateway:[istio-egressgateway] port:3128]] route:[map[destination:map[host:laanc.prod.airmap.com]]]]]]"}

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-laanc-through-egress-gateway
spec:
  hosts:
  - laanc.prod.airmap.com
  gateways:
  - istio-egressgateway
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-next.svc.cluster.local
        subset: laanc
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: laanc.prod.airmap.com
        port:
          number: 3128
      weight: 100
```

What have I done wrong here
