### ISSUE TITLE
Legacy ingress 404's with named servicePort 

### ISSUE THREAD

**Issue by markeijsermans** [istio/istio#9013]
**Describe the bug**
Legacy ingress fails when the backing service is defined with a named `servicePort`. A numeric port works. Named `servicePort` worked on a previous install of Istio 0.5.1

**Expected behavior**
`curl http://myservice.example.com` via legacy ingress and get http 200 OK.

**Steps to reproduce the bug**
The following service/ingress results in a http 404.
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice
  labels:
    app: myservice
spec:
  rules:
  - host: myservice.example.com
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: http-service  # <== THIS BREAKS
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myservice
spec:
  type: ClusterIP
  selector:
    app: myservice
  ports:
  - name: http-service
    port: 8080
    protocol: TCP
    targetPort: 8080
```
Log from the ingress worker:
```
[2018-09-27T19:15:41.810Z] "GET /foo HTTP/1.1" 404 NR 0 0 0 - "10.1.2.139" "curl/7.58.0" "b4e4b3bc-01f6-98b3-beef-877f79ad9c95" "myservice.example.com" "-"
```

Using a numeric `servicePort` for the Ingress fixes the issue and results in a http 200 OK:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice
  labels:
    app: myservice
spec:
  rules:
  - host: myservice.example.com
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 8080
```

**Version**
Istio
```
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
Kubernetes
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Istio 1.0.2 Helm chart with the following config:
```yaml
global:
  k8sIngressSelector: ingress
  k8sIngressHttps: false
  controlPlaneSecurityEnabled: false
  mtls:
    enabled: false
ingress:
  enabled: true
gateways:
  enabled: false
```

**Environment**
Minikube & AWS

**Cluster state**
will generate on request
