### ISSUE TITLE
In different namespace , TLS not working with multiple domain , just one can work

### ISSUE THREAD

**Issue by ethonchen** [istio/istio#9029]
**Describe the bug**
I have 2 host like : https://a.xyz.com (the backend in a namespace named anamespace ) ,  https://b.xyz.com (the backend in a namespace named bnamespace ) ,and i conf follow like this 
https://istio.io/docs/tasks/traffic-management/secure-ingress/
[Configure a TLS ingress gateway for multiple hosts]

and my yaml like this:
a.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: front-a
  namespace: anamespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http-a
      protocol: HTTP
    hosts:
    - "a.xyz.com"
  - port:
      number: 443
      name: https-a
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "a.xyz.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsvc-a
  namespace: anamespace
spec:
  hosts:
  - "a.xyz.com"
  gateways:
  - front-a
  http:
  - match:
    - uri:
        prefix: /gw
    route:
    - destination:
        host: abackend
        port:
           number: 8080
```
b.yaml

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: front-b
  namespace: bnamesapce
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http-b
      protocol: HTTP
    hosts:
    - "b.xyz.com"
  - port:
      number: 443
      name: https-b
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-b-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-b-certs/tls.key
    hosts:
    - "b.xyz.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsvc-b
  namespace: bnamespace
spec:
  hosts:
  - "b.xyz.com"
  gateways:
  - front-b
  http:
  - match:
    - uri:
        prefix: /gw
    route:
    - destination:
        host: bbackend
        port:
           number: 8080
```
It's just one https work , the other is not working .
when my command seq like this:
kubectl create -f a.yaml
kubectl create -f b.yaml
```
https://a.xyz.com  ---- work
http://a.xyz.com  ---- work
http://b.xyz.com  ---- work
https://b.xyz.com  ---- DO NOT WORK
```

and when  my command seq like this:
kubectl create -f b.yaml
kubectl create -f a.yaml
```
https://a.xyz.com  ---- DO NOT WORK
http://a.xyz.com  ---- work
http://b.xyz.com  ---- work
https://b.xyz.com  ---- work
```

**Version**
my Kubernetes version : 1.11.2
my Istio version : 1.0.2
