### ISSUE TITLE
Failed to add serviceAnnotations in values.yaml

### ISSUE THREAD

**Issue by marcusrios** [istio/istio#9037]
**Describe the bug**
I'm trying to add the annotation `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"` in the `gateways.istio-ingressgateway` section but when I'm apply/upgrade using helm the API throw the following error:

```
Error: UPGRADE FAILED: v1.Service: ObjectMeta: v1.ObjectMeta: Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|enabled":true,"servi|..., bigger context ...|load-balancer-cross-zone-load-balancing-enabled":true,"service.beta.kubernetes.io/aws-load-balancer-|...
```

**Expected behavior**
Be able to pass this property to the Load Balancer creation through helm

**Steps to reproduce the bug**
Download [istio](https://github.com/istio/istio/releases/tag/1.0.2) `1.0.2`
Edit the file `values.yaml` in`install/kubernetes/helm/istio` adding the following annotations in `gateways.istio-ingressgateway`

```yaml
...
serviceAnnotations:
  service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
...
```

Apply:

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
``` 

**Version**
Istio version: `1.0.2`
Kubernetes version: `v1.10.0`
Helm version: `v2.11.0`
Tiller version: `v2.11.0`

**Installation**
I'm using the recommended mode which is `helm install` : https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install

**Environment**
Provider: AWS
Client (istioctl and helm): MacOS

**Additional infos**
Works if a manually edit the ingress gateway service and add this options directly.

```bash
kubectl -n istio-system edit service istio-ingressgateway
```
