### ISSUE TITLE
Service cannot access external Hbase slaves.

### ISSUE THREAD

**Issue by magicalne** [istio/istio#9047]
**Describe the bug**
I have a hbase cluster out of k8s in aws. Sidecar injected service cannot access outside hbase. But service without sidecar can access outside hbase.

I can confirm that my request can reach my service. When my service is trying to access hbase, my service needs to talk to zookeeper first and read meta data from master. I can also confirm that my service can access zookeeper perfectly with given domain and port(2181). 

But my service fails to talk to hbase slaves.

Logs from service:
>10:37:23 {"log":"Sat Sep 29 02:28:52 GMT 2018, RpcRetryingCaller{globalStartTime=1538188132100, pause=100, retries=35}, org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Call to ip-172-31-6-45.ap-southeast-1.compute.internal/172.31.6.45:16020 failed on local exception: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Connection to ip-172-31-6-45.ap-southeast-1.compute.internal/17
10:37:23 {"log":"Sat Sep 29 02:28:52 GMT 2018, RpcRetryingCaller{globalStartTime=1538188132100, pause=100, retries=35}, org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Call to ip-172-31-6-45.ap-southeast-1.compute.internal/172.31.6.45:16020 failed on local exception: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Connection to ip-172-31-6-45.ap-southeast-1.compute.internal/17
10:37:23 {"log":"Sat Sep 29 02:28:52 GMT 2018, RpcRetryingCaller{globalStartTime=1538188132100, pause=100, retries=35}, org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Call to ip-172-31-6-45.ap-southeast-1.compute.internal/172.31.6.45:16020 failed on local exception: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Connection to ip-172-31-6-45.ap-southeast-1.compute.internal/17
10:37:23 {"log":"Sat Sep 29 02:28:52 GMT 2018, RpcRetryingCaller{globalStartTime=1538188132100, pause=100, retries=35}, org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Call to ip-172-31-6-45.ap-southeast-1.compute.internal/172.31.6.45:16020 failed on local exception: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Connection to ip-172-31-6-45.ap-southeast-1.compute.internal/17
10:37:23 {"log":"Sat Sep 29 02:28:53 GMT 2018, RpcRetryingCaller{globalStartTime=1538188132100, pause=100, retries=35}, java.io.IOException: Connection reset by peer\n","stream":"stdout","docker":{"container_id":"aeb270508a28cc72e18f8e5b5658112997297fb9c9a9c21d8c05d5a42daff05b"},"kubernetes":{"container_name":"moneyne-server","namespace_name":"default","pod_name":"moneyne-server-6b78755bdd-26cqs","pod_id":

Since hbase client uses grpc to talk to the region server(slave), I think the problem is in the external service entry of grpc.

Here is the log from hbase client:
>Sep 29, 2018 2:34:13 AM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Content-Type 'application/x-www-form-urlencoded' is not supported
io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
at io.grpc.netty.NettyServerHandler.verifyContentType(NettyServerHandler.java:594)
at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:345)

**Expected behavior**
I want my sidecar injected service to access hbase smoothly.

**Steps to reproduce the bug**
My service looks like:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: moneyne-server-gateway
  namespace: prod
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 9090
      name: grpc
      protocol: GRPC #or GRPC, which gives the same result
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: moneyne-server
spec:
  hosts:
  - "*"
  gateways:
  - moneyne-server-gateway
  http:
  - route:
    - destination:
        port:
          number: 9090
        host: moneyne-server
---
apiVersion: v1
kind: Service
metadata:
  name: moneyne-server
  labels:
    app: moneyne-server
spec:
  ports:
  - name: grpc
    port: 9090
  selector:
    app: moneyne-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moneyne-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: moneyne-server
        version: v1
    spec:
      containers:
      - image: xxx.dkr.ecr.ap-southeast-1.amazonaws.com/moneyne
        imagePullPolicy: Always
        name: moneyne-server
        ports:
        - containerPort: 9090
```
Then I follow the doc to define my service entries as below.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-hbase-master
spec:
  hosts:
  - ip-xxx-xxx-xx-xx.ap-southeast-1.compute.internal #hbase
  location: MESH_EXTERNAL
  ports:
  - number: 16000
    name: HMaster
    protocol: TCP
#  - number: 16010
#    name: HMaster UI
#    protocol: HTTP
#  - number: 16020
#    name: grpc-regionserver
#    protocol: GRPC
#  - number: 16030
#    name: region server info
#    protocol: HTTP
#  - number: 8070
#    name: REST server
#    protocol: HTTP
#  - number: 8085
#    name: REST UI
#    protocol: HTTP
  - number: 2181
    name: zookeeper
    protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-hbase-slave
spec:
  hosts:
  - "*.ap-southeast-1.compute.internal"
  location: MESH_EXTERNAL
  ports:
  - number: 16020
    name: grpc-regionserver
    protocol: GRPC
  resolution: NONE
```

**Version**
istio version:
>Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

k8s version:
>Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Installed istio with helm

**Environment**
AWS, kops, helm

I think the problem is in **external-svc-hbase-slave**. I tried all the configs from the doc with no luck. 

**little questions**
1. Since istio-proxy of every sidecar is just a proxy. Why can I just use tcp as the same protocol for every single request?
2. Where can I see the audit log or access log for the external service entry?
3. Or can we see the accessible service entries of a pod/service? Like the ip tables?
