### ISSUE TITLE
Rate limit cannot work for services in other namepaces except for default

### ISSUE THREAD

**Issue by x15zhang** [istio/istio#9051]
**Describe the bug**

I installed two applications: 
1. bookinfo in default namespace
2. tomcat in myapp namespace.

Then I run the Rate Limit task with following config:

```
apiVersion: "config.istio.io/v1alpha2"
kind: memquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 1
    validDuration: 3s
```
```
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: request.headers["x-forwarded-for"] | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"
```
```
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcount
```
```
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: productpage
    namespace: default
  - name: tomcat
    namespace: webapp
```
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: handler.memquota
    instances:
    - requestcount.quota
```

Bookinfo in  default namepsace can work well and it permits 1 requests every 3 seconds. But tomcat in other namepsace cannot get any RESOURCE_EXHAUSTED response. 
And after I change tomcat to default namespace, rate limit can work well for it.

**Expected behavior**
Rate limit can work for services in all namepaces.

**Version**
istio version v1.0.0
kubenetes version v1.9.3
