### ISSUE TITLE
Disabling mixer with Helm template causes ingress/egress pods to crash

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#9056]
**Describe the bug**
Using `helm template` to generate the istio install file using mixer `enabled: false` causes the ingress-system ingressgateway and egressgateway pods to crash. No other deployed pods are necessary -- including no sidecars.

The crash events match what is described in https://github.com/istio/istio/issues/6508.

**Expected behavior**
Disabling mixer has no negative side effects.

**Steps to reproduce the bug**
1. Generate istio installation using the following values (much of this is unrelated, but it's what I tested with):
```
global:
  enableTracing: false
  proxy:
    # Disable Mixer logging every request
    accessLogFile: ""

    # Only send internal requests through the mesh
    includeIPRanges: "100.64.0.0/10"

mixer:
  enabled: false
```
2. Install istio using the generated yaml
3. Observe the `istio-system` pods for 10-15 minutes and see that ingress/egress crash

**Version**
Istio: 1.0.2
Kubernetes: 1.9.3

**Installation**
Helm template (see steps above)

**Environment**
AWS Kops
