### ISSUE TITLE
Helm value to configure TLS for `istio-telemetry-gateway`

### ISSUE THREAD

**Issue by MrSaints** [istio/istio#9076]
**Describe the feature request**

When `istio-telemetry-gateway` is enabled in Helm, there is no way to define TLS configuration for the generated gateway, and its virtual services.
Is this desirable? If so, how is `istio-telemetry-gateway` supposed to be used in practice?

**Describe alternatives you've considered**

Manually creating a gateway, and virtual services for Prometheus, and Grafana. This feels like it defeats the purpose of the `istio-telemetry-gateway` value though.

**Additional context**

The following is generated from Helm:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-telemetry-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15031
      name: http2-grafana
      protocol: HTTP2
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
  namespace: istio-system
spec:
  host: grafana.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE      
```
