### ISSUE TITLE
Mixer metrics should instantaneous not historical

### ISSUE THREAD

**Issue by coreypobrien** [istio/istio#9077]
Mixer's `/metrics` endpoint includes metrics from all historical configs instead of just the current config. This makes it difficult/impossible to accurately monitor for errors  

Consider `mixer_config_rule_configs_total` and `mixer_config_rule_configs_total` as an example.
When mixer starts with well-formed rules, `/metrics` looks like this:

```
mixer_config_rule_configs_total{configID="1"} 6
```

If you then apply a malformed rule (e.g. one with `match: context.protocol =&&= "http"`), you see the metrics for both the old and new configurations even though configuration 1 isn't active anymore.

```
mixer_config_rule_config_match_error_total{configID="2"} 1
mixer_config_rule_configs_total{configID="1"} 6
mixer_config_rule_configs_total{configID="2"} 7
```

You can delete the broken rule and you get all 3 configurations:

```
mixer_config_rule_config_match_error_total{configID="2"} 1
mixer_config_rule_configs_total{configID="1"} 6
mixer_config_rule_configs_total{configID="2"} 7
mixer_config_rule_configs_total{configID="3"} 6
```

Any system attempting to monitor for bad rule configurations would only be able to detect problems if it can first determine which `configID` to focus on. When pods restart, that configID gets reset to 1 which makes `configID` pretty useless as well.

I would expect that any query of the `/metrics` endpoint should only return metrics that are _currently_ valid, and should not return any historical metrics.

I'm testing with `1.1.0.snapshot.1` and k8s `v1.10.6-gke.2` on GKE. Istio was installed via the helm chart from the `1.1.0.snapshot.1` tag using the `1.1.0.snapshot.1` docker images.

Here's the rule I was using to generate a rule failure:
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: test
  namespace: istio-system
spec:
  actions:
  - handler: handler.stdio
    instances:
    - accesslog.logentry
  match: context.protocol =&&= "http" || context.protocol == "grpc"
```
