### ISSUE TITLE
Configuring an HTTP external authz service for EnvoyFilter resource

### ISSUE THREAD

**Issue by mefarazath** [istio/istio#9097]
**Describe the bug**

I am trying to enforce authorization for inbound traffic to the istio proxy. I used the "envoy.ext_authz" EnvoyFilter resource and implemented a GRPC server to do the authorization. Here is my working config

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz-grpc
  namespace: istio-system
spec:          
  workloadLabels:
    app: httpbin
  filters:                          
  - insertPosition:
      index: FIRST
    listenerMatch: 
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:      
      grpc_service:
        google_grpc:          
          target_uri: external-auth-grpc-server:8080
          stat_prefix: "ext_authz"
  - insertPosition:
      index: FIRST
    listenerMatch:                  
      listenerType: SIDECAR_INBOUND
      listenerProtocol: TCP
    filterType: NETWORK
    filterName: "envoy.ext_authz"
    filterConfig:                        
      grpc_service:   
        google_grpc:                    
          target_uri: external-auth-grpc-server:8080
          stat_prefix: "ext_authz"
```

While going through the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2alpha/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2alpha-httpservice) I also noticed that there is an option to have an HTTP server to do the authorization which I think would be much convenient to me. I tried different combinations of the config as I couldn't find a proper example

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-authz-inbound-authz
  namespace: istio-system
spec:          
  workloadLabels:
    app: httpbin
  filters:                          
  - insertPosition:
      index: FIRST
    listenerMatch: 
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:      
      http_service:
          server_uri:
            uri: http://http-authz:8080/http-authz/inbound
            cluster: outbound|8080||http-authz.default.svc.cluster.local
            timeout: 10s
  - insertPosition:
      index: FIRST
    listenerMatch:                  
      listenerType: SIDECAR_INBOUND
      listenerProtocol: TCP
    filterType: NETWORK
    filterName: "envoy.ext_authz"
    filterConfig:                        
      http_service:
          server_uri:
            uri: http://http-authz:8080/http-authz/inbound
            cluster: outbound|8080||http-authz.default.svc.cluster.local
            timeout: 10s
```

Each one resulted in either the envoy crashing and restarting or request not sent to the http service. 
Is having an HTTP service as an external authorization service supported in istio?
Particularly, what would be the correct value for 'cluster' to be used? A sample configuration would be awesome.

```
  http_service:
          server_uri:
            uri: http://http-authz:8080/http-authz/inbound
            cluster: outbound|8080||http-authz.default.svc.cluster.local
            timeout: 10s
```

I found a similar issue related to http external authorization service in https://groups.google.com/forum/#!topic/istio-users/cmC5odtmItY as well.

Thanks in advance for the help!

**Expected behavior**
Configure an HTTP service as external authorization service

**Steps to reproduce the bug**
N/A

**Version**
```
istioctl version 
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
https://istio.io/docs/setup/kubernetes/helm-install/

**Environment**
minikube version: v0.28.2

**Comment by EyMaddis** [comment]
Did you have any luck implementing this in your setup?

**Comment by sapien99** [comment]
Looking exact for the same thing, +1

**Comment by sapien99** [comment]
Guys, here is what works on my setup with istio 1.0.4. Guess one needs to define the Virtualservice - which imhO makes sense because the service needs to be reachable from within the mesh. (Skipped registry and image name)

Hope this works at yours too, good luck

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
spec:
  workloadLabels:
    app: istio-ingressgateway-health
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:
      http_service:
        server_uri:
          uri: http://istio-ingressgateway-auth.demo.svc.cluster.local
          cluster: outbound|80||istio-ingressgateway-auth.demo.svc.cluster.local
          timeout: 0.25s
          failure_mode_allow: false
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway-auth
  name: istio-ingressgateway-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-ingressgateway-auth
  template:
    metadata:
      labels:
        app: istio-ingressgateway-auth
    spec:
      containers:
      - env:
        - name: PORT
          value: "3000"
        image: myregistry/authgw:0.4
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway-auth
  name: istio-ingressgateway-auth
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: istio-ingressgateway-auth
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ingressgateway-auth.demo.svc.cluster.local
spec:
  gateways:
  - mesh
  hosts:
  - istio-ingressgateway-auth.demo.svc.cluster.local
  http:
  - route:
    - destination:
        host: istio-ingressgateway-auth.demo.svc.cluster.local
```
