### ISSUE TITLE
Rule match doesn't work with OOT adapter

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#9125]
**Describe the bug**
After following the [TCP Metrics](https://istio.io/docs/tasks/telemetry/tcp-metrics/) guide, I generated the following `rule` for my OOT adapter.

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: wavefront-tcp-rule
  namespace: istio-system
spec:
  match: context.protocol == "tcp"
         && destination.service == "mongodb.default.svc.cluster.local"
  actions:
  - handler: wavefront-handler.istio-system
    instances:
    - tcpsentbytes
    - tcpreceivedbytes
```

It however didn't produce metrics in my OOT adapter due to an issue in the `match` parameter. Changing `destination.service` to `destination.service.host` fixed the issue. Is this known/expected behavior?

**Expected behavior**
I exptected to see `InstanceMsg`s for `tcpsentbytes` and `tcpreceivedbytes` in the adapter when the match parameter was `destination.service` as described in the guide.

**Steps to reproduce the bug**
Follow instructions from [Wavefront Adapter for Istio](https://github.com/vmware/wavefront-adapter-for-istio) and the [TCP Metrics](https://istio.io/docs/tasks/telemetry/tcp-metrics/) page and use the above `rule` configuration.

**Version**
Output from `istioctl version`:

```
version.BuildInfo{Version:"1.1.0.snapshot.1", GitRevision:"45692c579c6d755194421540149a99ac4cb59528", User:"root", Host:"ac7ff4b30ee4", GolangVersion:"go1.10.1", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}
```

Output from `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

/cc @mandarjog
