### ISSUE TITLE
Applying Route Rule not working

### ISSUE THREAD

**Issue by sachitaggarwal** [istio/istio#9155]
Hello

I am trying out Istio on Google Kubernetes engine , i was able to succesfully deploy and test basic bookinfo application as mentioned here 
https://istio.io/docs/setup/kubernetes/quick-start-gke-dm/

But now when i try to apply other routing policies my basic app stops working

I executed following command - 
kubectl apply -f samples/bookinfo/networking/virtual-service-reviews-v3.yaml

yaml content >
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v3

```
Once i apply this policy UI application stops working and gives error , not able to get reviews
Can you please help here

Regards
Sachit

**Comment by sachitaggarwal** [comment]
This works now after applying original rule 
- kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml

But now fault tolerance examples are not working
yaml content >
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 7s
    route:
    - destination:
        host: ratings
        subset: v1
  - route:
    - destination:
        host: ratings
        subset: v1
```

Looks like tag for percentage has changed to 'percent' and there is no more child element value
i tried modified yaml like
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    fault:
      delay:
        percent: 100
        fixedDelay: 11s
    route:
    - destination:
        host: ratings
        subset: v1
  - route:
    - destination:
        host: ratings
        subset: v1
```
