### ISSUE TITLE
Istio sidecar not allowing connection to database

### ISSUE THREAD

**Issue by pepjo** [istio/istio#9157]
**Describe the bug**
Trying to connect to a Postgres database running inside Istio and kubernetes from a service inside istio, both with sidecars. Instead of allowing the connection the sidecar logs show:

```
[15][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
```

**Expected behavior**
They should be able to stablish a connection.

**Steps to reproduce the bug**
- Deploy a postgres database + service
- Deploy a service that connects to the database

**Version**
ISTIO:
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

KUBERNETES: (v1.11)
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Using helm with gateways.enabled=false & tracing.enabled=true

**Environment**
Kubernetes deployed in DigitalOcean

**NOTES**
 - Only works as expected if I deactivate the sidecar using the `sidecar.istio.io/inject: "false"` annotation on BOTH deployments work
 - I know I have to store passwords as secrets for production

**Deployment files**
Postgres database:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: app
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: app
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: app
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: db
    # protocol: TCP
  selector:
    app: postgres
  # clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      # annotations:
      #   sidecar.istio.io/inject: "false"
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: db
          # protocol: TCP
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 3
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim
```

Service that connects to the databse:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgservice-config
  namespace: app
  labels:
    app: pgservice
data:
  POSTGRESQL_CONNECTION: jdbc:postgresql://postgres:5432/postgres
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: mysecretpassword
---
apiVersion: v1
kind: Service
metadata:
  name: pgservice
  namespace: app
  labels:
    app: pgservice
spec:
  type: ClusterIP
  selector:
    app: pgservice
  ports:
  - port: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgservice-deployment
  namespace: app
  labels:
    app: pgservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgservice
  template:
    metadata:
      # annotations:
      #   sidecar.istio.io/inject: "false"
      labels:
        app: pgservice
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:10.4
        command: ['sh', '-c',
                  'until pg_isready -h postgres -p 5432;
                do echo waiting for database; sleep 2; done;']
      - name: exec-db-migration
        image: registry.gitlab.com/registry/pgmigration:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: pgmigration-config
      containers:
      - name: pgservice
        image: registry.gitlab.com/registry/pgservice:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: pgservice-config
        ports:
        - containerPort: 8080
          name: http
      imagePullSecrets:
      - name: regcred
```
