### ISSUE TITLE
Gateway pods are crashing

### ISSUE THREAD

**Issue by tamizharasanr** [istio/istio#9219]
**Describe the bug**
istio-egressgateway and istio-ingressgateway are crashing because the following error 
`Error: unknown flag: --discoveryRefreshDelay`

**Expected behavior**
istio-egressgateway and istio-ingressgateway will crashLoopBackOff

**Steps to reproduce the bug**
Install in kubernetes using helm with following config file

```
global:
  proxy:
    includeIPRanges: 100.64.0.0/10
ingress:
  enabled: false
ingressgateway:
  enabled: true
egressgateway:
  enabled: true
grafana:
  enabled: false
prometheus:
  enabled: false
servicegraph:
  enabled: false
tracing:
  enabled: true
  jaeger:
    enabled: true
kiali:
  enabled: false
pilot:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
```

**Version**
`istio version: 1.1.0.snapshot.1`
`kube version: v1.9.6`

**Installation**
Using Helm

**Environment**
clound vendor: AWS
OS: ubuntu:14.04
