### ISSUE TITLE
Connect external mysql database by egress gateway does not work

### ISSUE THREAD

**Issue by zoupl** [istio/istio#9224]
**I deployed ServiceEntry like this:**

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - dbext.telcloud.svc.cluster.local
  ports:
  - number: 3306
    name: db
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 10.144.166.68
    ports:
      http: 3306

```
**In a pod which have mysql client in it , i tried to connect to mysql and it is ok.**

```
mysql -uroot -p  -h dbext.telcloud.svc.cluster.local -P 3306
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 45
Server version: 5.7.23 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

```
**Later I deployed egress gateway and virtual service,  then, i tried to connect to mysql,  and it failed.
Here is egress gateway and virtualservice:**

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 3306
      name: db
      protocol: TCP
    hosts:
    - "dbext.telcloud.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dbext
spec:
  hosts:
  - dbext.telcloud.svc.cluster.local
  gateways:
  - istio-egressgateway
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: dbext.telcloud.svc.cluster.local
        port:
          number: 3306
      weight: 100

```

**Here is my result:**
```
root@mysql-fb75876c6-dcbh8:/# mysql -uroot -p -h dbext.telcloud.svc.cluster.local -P 80
Enter password:
```

**It was stuck, and there was no messages in logs of egress gateway.**

**Expected behavior**
mysql -uroot -p -h dbext.telcloud.svc.cluster.local -P 80, this command should be ok.

**Version**
Istio 1.0.2 release  
kubernetes v1.11.3

**Installation**
Install istio by helm

**Environment**
centos 7.4

**Comment by zoupl** [comment]
I found egress gateway only support 80 and 443, which is http and https. Is TCP not supported by egress gateway?

**Comment by zoupl** [comment]
```
  istio-egressgateway:
    enabled: true
    labels:
      app: istio-egressgateway
      istio: egressgateway
    replicaCount: 1
    autoscaleMin: 1
    autoscaleMax: 5
    cpu:
      targetAverageUtilization: 80
    serviceAnnotations: {}
    type: ClusterIP #change to NodePort or LoadBalancer if need be
    ports:
      - port: 80
        name: http2
      - port: 443
        name: https
    secretVolumes:
      - name: egressgateway-certs
        secretName: istio-egressgateway-certs
        mountPath: /etc/istio/egressgateway-certs
      - name: egressgateway-ca-certs
        secretName: istio-egressgateway-ca-certs
        mountPath: /etc/istio/egressgateway-ca-certs
```
