### ISSUE TITLE
Galley ignores logging arguments from the command line

### ISSUE THREAD

**Issue by hatmatter** [istio/istio#9265]
**Describe the bug**
The Galley service doesn't properly handle logging options that are passed to it on the command line. If the deployment is modified to include `--log_output_level=default:debug` the option is not applied to the Server and Validation go routines when Galley starts. Instead these go routines are always passed the DefaultArgs struct.

[`galley/cmd/galley/cmd/root.go: 49-50`](https://github.com/istio/istio/blob/1.1.0.snapshot.1/galley/cmd/galley/cmd/root.go#L49-L50) is where the default arguments are retrieved
[`galley/cmd/galley/cmd/root.go: 91,94`](https://github.com/istio/istio/blob/1.1.0.snapshot.1/galley/cmd/galley/cmd/root.go#L91) is where they are passed to the go routines without applying the command line arguments

**Expected behavior**
The process should propagate the logging options to the go routines server.RunServer and validation.RunValidation

**Steps to reproduce the bug**
1. Deploy Istio with Galley
2. Edit the deployment to include `--log_output_level=default:debug` command line argument
3. Look at the logs from the Galley pod and see that the logging options being used are still the default values

**Version**
I am testing this on 1.1.0-snapshot.1

**Installation**
1. git checkout 1.1.0-snapshot.1
2. run install/updateVersion.sh
3. kubectl apply -f install/kubernetes/istio-auth.yaml

**Comment by hzxuzhonghu** [comment]
I tested and it works for me.

**Comment by hatmatter** [comment]
Interesting.. can you post the commands section of your deployment yaml and the log output showing the settings being used? You tested it on the 1.1.0 snapshot?
Begs the question of whether I am misinterpreting the code, which I thought showed why it was not being applied.

**Comment by hatmatter** [comment]
```
      containers:
      - command:
        - /usr/local/bin/galley
        - --caCertFile=/etc/istio/certs/root-cert.pem
        - --tlsCertFile=/etc/istio/certs/cert-chain.pem
        - --tlsKeyFile=/etc/istio/certs/key.pem
        - --livenessProbeInterval=1s
        - --livenessProbePath=/healthliveness
        - --readinessProbePath=/healthready
        - --readinessProbeInterval=1s
        - --insecure=false
        - --validation-webhook-config-file
        - /etc/istio/config/validatingwebhookconfiguration.yaml
```
```kubectl logs -n istio-system istio-galley-757cb44894-qmqwq
Galley started with
KubeConfig: 
ResyncPeriod: 0s
APIAddress: tcp://0.0.0.0:9901
EnableGrpcTracing: tcp://0.0.0.0:9901
MaxReceivedMessageSize: 1048576
MaxConcurrentStreams: 1024
LoggingOptions: log.Options{OutputPaths:[]string{"stdout"}, ErrorOutputPaths:[]string{"stderr"}, RotateOutputPath:"", RotationMaxSize:104857600, RotationMaxAge:30, RotationMaxBackups:1000, JSONEncoding:false, LogGrpc:true, outputLevels:"default:info", logCallers:"", stackTraceLevels:"default:none"}
```

**Comment by hzxuzhonghu** [comment]
```
  containers:
  - command:
    - /usr/local/bin/galley
    - --caCertFile=/etc/istio/certs/root-cert.pem
    - --tlsCertFile=/etc/istio/certs/cert-chain.pem
    - --tlsKeyFile=/etc/istio/certs/key.pem
    - --livenessProbeInterval=1s
    - --livenessProbePath=/healthliveness
    - --readinessProbePath=/healthready
    - --readinessProbeInterval=1s
    - --insecure=true
    - --log_output_level=default:debug
    - --validation-webhook-config-file
    - /etc/istio/config/validatingwebhookconfiguration.yaml
    image: gcr.io/istio-release/galley:1.1.0.snapshot.1

```
logs: 
```
root@szvp000201060:/mnt/go/src/istio.io/istio# kubectl logs istio-galley-78b4fb7867-mk22n  -n istio-system 
Galley started with
KubeConfig: 
ResyncPeriod: 0s
APIAddress: tcp://0.0.0.0:9901
EnableGrpcTracing: tcp://0.0.0.0:9901
MaxReceivedMessageSize: 1048576
MaxConcurrentStreams: 1024
LoggingOptions: log.Options{OutputPaths:[]string{"stdout"}, ErrorOutputPaths:[]string{"stderr"}, RotateOutputPath:"", RotationMaxSize:104857600, RotationMaxAge:30, RotationMaxBackups:1000, JSONEncoding:false, LogGrpc:true, outputLevels:"default:info", logCallers:"", stackTraceLevels:"default:none"}
IntrospectionOptions: ctrlz.Options{Port:0x2694, Address:"127.0.0.1"}
Insecure: true
AccessListFile: /etc/istio/config/accesslist.yaml
EnableServer: true
KeyFile: /etc/istio/certs/key.pem
CertificateFile: /etc/istio/certs/cert-chain.pem
CACertificateFile: /etc/istio/certs/root-cert.pem
ConfigFilePath: 

2018-10-11T01:55:42.966967Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2018-10-11T01:55:42.966852Z	debug	registering [0] (adapter.InfoFn)(0xfa33e0)

```
