### ISSUE TITLE
VirtualService weight not  work.

### ISSUE THREAD

**Issue by xiaoxi1989** [istio/istio#9268]
**Describe the bug**
i have 2 versions app

```
app: istio-test-server-b
version:v1

app: istio-test-server-b
version:v2
```

there is a server will request them,it return istio-test-server-b hostname

`service: istio-test-server-a
`

VirtualService

```
kind: VirtualService
metadata:
  name: istio-test-server-b
  namespace: cxx
spec:
  hosts:
  - istio-test-server-a
  http:
  - route:
    - destination:
        host: istio-test-server-b
        port:
          number: 80
        subset: v1
      weight: 90
    - destination:
        host: istio-test-server-b
        port:
          number: 80
        subset: v2
      weight: 10

```
DestinationRule

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-test-server-b
spec:
  host: istio-test-server-b
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
```
request 10 times,return
```
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b2-b49d96859-fb7d5
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b2-b49d96859-fb7d5
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b2-b49d96859-fb7d5
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b2-b49d96859-fb7d5
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b2-b49d96859-fb7d5
```

**Expected behavior**
request 10 times
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b-69bcbc5948-2gxwr
istio-test-server-b2-b49d96859-fb7d5

**Steps to reproduce the bug**

**Version**
istioctl version
```
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@cxx1
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
helm template install

**Environment**
centos 7.5
