### ISSUE TITLE
Pilot discover conflict logs and port conflicts

### ISSUE THREAD

**Issue by vijaykumark** [istio/istio#9273]
**Describe the bug**
Our application is running on Istio 1.0.2. There are two sets of keycloak and freeipa running outside the istio cluster but in the same k8s cluster. Cassandra is also running outside istio.  There are applications listening on same ports but over ClusterIP type services. Does it cause conflict in istio?

Below attached logs for istio pilot where there are several logs mentioning `pilot_conflict_inbound_listener, pilot_conflict_outbound_listener_http_over_current_tcp, pilot_conflict_outbound_listener_tcp_over_current_tcp,
pilot_duplicate_envoy_clusters, pilot_eds_no_instances?`

What does these status mean: `pilot_conflict_inbound_listener, pilot_conflict_outbound_listener_http_over_current_tcp, pilot_conflict_outbound_listener_tcp_over_current_tcp,
pilot_duplicate_envoy_clusters, pilot_eds_no_instances?`

Couldn't find any information about what those errors mean and how to resolve those errors.
I have followed https://istio.io/docs/setup/kubernetes/spec-requirements/ and tried to name port names uniquely.

Any guidance is deeply appreciated.

Here are the pilot discover logs

```
2018-09-02T08:42:56.588149Z     info    ads     Push finished: 188.068326ms {
    "ProxyStatus": {
        "pilot_conflict_inbound_listener": {
            "project-app1-6cdccdf54c-q7jqv.project": {
                "proxy": "project-app1-6cdccdf54c-q7jqv.project",
                "message": "Rejected project-app1.project.svc.cluster.local, used project-app2.project.svc.cluster.local for 10.2.0.38:8080"
            }
        },
        "pilot_conflict_outbound_listener_http_over_current_tcp": {
            "0.0.0.0:8080": {
                "proxy": "project-app3-97748c65b-cjb4w.project",
                "message": "Listener=0.0.0.0:8080 AcceptedHTTP=keycloak.project.svc.cluster.local,kube-state-metrics.kube-system.svc.cluster.local RejectedTCP=keycloak2.project.svc.cluster.local HTTPServices=2"
            }
        },
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:9042": {
                "proxy": "project-app3-97748c65b-cjb4w.project",
                "message": "Listener=0.0.0.0:9042 AcceptedTCP=cassandra.project.svc.cluster.local RejectedTCP=cassandra.project.svc.cluster.local TCPServices=1"
            },
            "10.3.0.1:443": {
                "proxy": "project-app3-97748c65b-cjb4w.project",
                "message": "Listener=10.3.0.1:443 AcceptedTCP=kubernetes.default.svc.cluster.local RejectedTCP=10.3.0.1 TCPServices=1"
            }
        },
        "pilot_duplicate_envoy_clusters": {
            "outbound|443||kubernetes.default.svc.cluster.local": {
                "proxy": "istio-ingress-6475b8d5c8-kns6f.istio-system",
                "message": "Duplicate cluster outbound|443||kubernetes.default.svc.cluster.local found while pushing CDS"
            },
            "outbound|8080||keycloak.project.svc.cluster.local": {
                "proxy": "istio-ingress-6475b8d5c8-kns6f.istio-system",
                "message": "Duplicate cluster outbound|8080||keycloak.project.svc.cluster.local found while pushing CDS"
            },
            "outbound|9042||cassandra.project.svc.cluster.local": {
                "proxy": "istio-ingress-6475b8d5c8-kns6f.istio-system",
                "message": "Duplicate cluster outbound|9042||cassandra.project.svc.cluster.local found while pushing CDS"
            }
        },
        "pilot_eds_no_instances": {
            "outbound|389||freeipa.project.svc.cluster.local": {},
            "outbound|443||freeipa.project.svc.cluster.local": {},
            "outbound|464||freeipa.project.svc.cluster.local": {},
            "outbound|5601||kibana-logging.kube-system.svc.cluster.local": {},
            "outbound|6790||rook-ceph-mon0.rook.svc.cluster.local": {},
            "outbound|88||freeipa.project.svc.cluster.local": {},
            "outbound|9200||elasticsearch-logging.kube-system.svc.cluster.local": {}
        }
    },
    "Start": "2018-09-02T08:42:56.400062777Z",
    "End": "2018-09-02T08:42:56.587934187Z"
}
```

**Expected behavior**
What are the rules for defining port numbers to the applications? Can port 8080 be served by different services if they have type ClusterIP? 
Need more documentation explaining this in https://istio.io/docs/setup/kubernetes/spec-requirements/
In the documentation they mention only about if a pod belongs to multiple k8s services. No mention if different pods with services have same ports.

**Steps to reproduce the bug**
Run several applications where different services are listening on port 8080 and port 80, 443. Service type is ClusterIP.

**Version**
```
# istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Istio is installed with mTLS disabled using helm.

**Environment**
Bare metal CoreOS Kubernetes

**Comment by deadc** [comment]
same problem here, using as example the Mirroring  https://istio.io/docs/tasks/traffic-management/mirroring

**Comment by liamawhite** [comment]
Ports on different services should be fine unless they are speaking different protocols. In your case, I'm not 100% sure what is happening here. Are you using ServiceEntries to define the external to mesh apps? Could you share them?

**Comment by deadc** [comment]
Adding more information to the issue, when I use the service on port 8080, as described in Istio's own manual, the rule set in VirtualService does not work.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: httpbin
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 100
---
```
In Kiali, the observability tool we use makes it clear that there is a problem

![istio-issue](https://user-images.githubusercontent.com/706271/49531227-f85b7800-f8a0-11e8-9f16-8bd7128f1b8e.png)

But when we change the service port to 8000 for example, the configuration starts to function normally.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: httpbin
``` 

And in Kiali

![istio-issue-normal](https://user-images.githubusercontent.com/706271/49531507-8d5e7100-f8a1-11e8-93c1-b0089b22455b.png)

When we use another istio-pilot port like the 9093, the same problem occurs.

**Comment by c-knowles** [comment]
Might be related - using Istio 1.0.4, we get `pilot_conflict_inbound_listener` using definitions like these:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: gapi
  labels:
    tier: backend
    app: gapi
spec:
  ports:
    - port: 80
      targetPort: app
  selector:
    app: gapi
---
kind: Service
apiVersion: v1
metadata:
  name: gapi-lb
  labels:
    tier: backend
    app: gapi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gapi
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:OBFUSCATED
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: app
  selector:
    app: gapi
```

(we define like this to avoid connecting to the load balancer service internally using http on port 443, I fully expect we'll get rid of all this as we migrate more into Istio native routing and mTLS)
