### ISSUE TITLE
Use the same hostIP and different Ingress Gateway ports to distinguish different Kubernetes services

### ISSUE THREAD

**Issue by xiajidexue** [istio/istio#9288]
**Describe the feature request**

{{ Succinctly describe your request }}
I use hostnetwork for the Ingress Gateway pods, i expect that i can access different services by the same hostIP and different Gateway ports, hostIP is the IP of the host an Ingress Gateway pod scheduled on.

**Describe alternatives you've considered**
{{ Describe alternative solutions or workarounds you've considered. }}
One Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 9999
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
Another gateway with different a different gateway name and port :
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway2
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 10000
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
then access different services via the same hostIP:9999/10000

**Additional context**
{{ Add any other context about the feature request here }}
