### ISSUE TITLE
Use different Ingress Gateway ports cannot distinguish different Kubernetes services

### ISSUE THREAD

**Issue by xiajidexue** [istio/istio#9289]
**Describe the bug**
Use the same hostIP with different Ingress Gateway ports cannot distinguish different Kubernetes services

**Expected behavior**
Use the same hostIP with different Ingress Gateway ports can distinguish different Kubernetes services.

**Steps to reproduce the bug**
1. Create Ingress Gateway pod with hostnetwork
2. Create two gateways with different port and gateway names.
Gateway one with the name hello-gateway and port 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 9999
      name: http
      protocol: HTTP
    hosts:
    - "*"

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: tobegit3hub/grpc-helloworld
        ports:
        - containerPort: 50051

kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 32666
      targetPort: 50051
      name: grpc
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
  - "*"
  gateways:
  - hello-gateway
  http:
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: helloworld
        port:
          number: 32666
```
Another gateway with the name hello-gateway3 and the port 10000.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway3
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 10000
      name: http
      protocol: HTTP
    hosts:
    - "*"

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: helloworld2
spec:
  selector:
    matchLabels:
      app: helloworld2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helloworld2
    spec:
      containers:
      - name: helloworld2
        image: tobegit3hub/grpc-helloworld
        ports:
        - containerPort: 50051

kind: Service
apiVersion: v1
metadata:
  name: helloworld2
spec:
  selector:
    app: helloworld2
  ports:
    - protocol: TCP
      port: 32666
      targetPort: 50051
      name: grpc
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello2
spec:
  hosts:
  - "*"
  gateways:
  - hello-gateway3
  http:
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: helloworld2
        port:
          number: 32666
```

```
# istioctl get all --all-namespaces
NAME                          KIND                                      NAMESPACE      AGE
grafana-ports-mtls-disabled   Policy.authentication.istio.io.v1alpha1   istio-system   63d

DESTINATION-RULE NAME   HOST                                             SUBSETS   NAMESPACE      AGE
istio-policy            istio-policy.istio-system.svc.cluster.local                istio-system   16h
istio-telemetry         istio-telemetry.istio-system.svc.cluster.local             istio-system   16h

VIRTUAL-SERVICE NAME   GATEWAYS         HOSTS     #HTTP     #TCP      NAMESPACE   AGE
hello                  hello-gateway    *             1        0      default     18h
hello2                 hello-gateway3   *             1        0      default     12h

GATEWAY NAME                                 HOSTS     NAMESPACE      AGE
hello-gateway                                 *         default        15h
hello-gateway3                                *         default        13h
hello-gateway4                                *         default        12h
istio-autogenerated-k8s-ingress               *         istio-system   16h
```
Then access the helloworld and helloworld2 services via the hostIP where the Ingress Gateway pod on and port.
Suppose hostIP is 1.2.3.4, then access 1.2.3.4:9999 and  1.2.3.4:10000

But all traffics are directed to the helloworld service, even when 1.2.3.4:10000 is accessed.

i access other gateway hello-gateway4 with the port 10001, but without creating related virtualservice and k8s service, the traffic is still directed to the helloworld service.

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
istioctl version
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
Kuberenetes version
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
