### ISSUE TITLE
DestinationRule *.local means every service? even dns domain is't cluster.local

### ISSUE THREAD

**Issue by xiaoxi1989** [istio/istio#9291]
**Describe the bug**
my dns domain is cxx.com:
```
/ # nslookup kubernetes.default
nslookup: can't resolve '(null)': Name does not resolve
Name:      kubernetes.default
Address 1: 10.68.0.1 kubernetes.default.svc.cxx.com
```

```
cat <<EOF | istioctl create -f -
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
EOF
```
```
cat <<EOF | istioctl create -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```
`for from in "foo" "bar" "legacy"; do for to in "foo" "bar" "legacy"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl http://httpbin.${to}:8000/ip -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done`

```
sleep.foo to httpbin.foo: 200
sleep.foo to httpbin.bar: 200
sleep.foo to httpbin.legacy: 503
sleep.bar to httpbin.foo: 200
sleep.bar to httpbin.bar: 200
sleep.bar to httpbin.legacy: 503
sleep.legacy to httpbin.foo: 000
command terminated with exit code 56
sleep.legacy to httpbin.bar: 000
command terminated with exit code 56
sleep.legacy to httpbin.legacy: 200
```

if change DestinationRule host like :
```
cat <<EOF | kubectl apply -f -                                                                             
apiVersion: "networking.istio.io/v1alpha3"                                                                                    
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  host: "*.cxx.com"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```
do test
`for from in "foo" "bar" "legacy"; do for to in "foo" "bar" "legacy"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl http://httpbin.${to}:8000/ip -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done`

```
sleep.foo to httpbin.foo: 503
sleep.foo to httpbin.bar: 503
sleep.foo to httpbin.legacy: 200
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 503
sleep.bar to httpbin.legacy: 200
sleep.legacy to httpbin.foo: 000
command terminated with exit code 56
sleep.legacy to httpbin.bar: 000
command terminated with exit code 56
sleep.legacy to httpbin.legacy: 200
```

even i change host to httpbin.foo.svc.cxx.com
```
cat <<EOF | kubectl apply -f -                                                                             
apiVersion: "networking.istio.io/v1alpha3"                                                                                    
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  host: "httpbin.foo.svc.cxx.com"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```
`for from in "foo" "bar"; do for to in "foo" "bar"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl http://httpbin.${to}:8000/ip -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done`

```
sleep.foo to httpbin.foo: 503
sleep.foo to httpbin.bar: 503
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 503
```
is it my understanding mistake?

```
kubectl get DestinationRule --all-namespaces
NAMESPACE      NAME                  AGE
cxx            istio-test-server-b   1d
default        default               20m
istio-system   istio-policy          24d
istio-system   istio-telemetry       24d
```
```
kubectl get meshpolicy --all-namespaces
NAME      AGE
default   1h
```
```
kubectl get policy --all-namespaces
No resources found.
```

**Version**
```
istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@cxx1
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
helm install

**Environment**
centos7.5
