### ISSUE TITLE
Enable all egress traffic on a specific deployment

### ISSUE THREAD

**Issue by victorboissiere** [istio/istio#9304]
**Describe the feature request**
I have a microservice which needs to fetch images from a list of URLs and download them to S3. However, I have no way to know the URLs in advance and for that reason I cannot use any egress rules on this service.

**Describe alternatives you've considered**
I tried to disable egress rules on the deployment itself using the following annotation:
```yaml
sidecar.istio.io/includeOutboundIpRanges: "0.0.0.0/0"
```

However even if it does work for plain http, I always get CONNRESET for all https requests which means that they are intercepted somehow.

Is there a way to make it work? Is it a good idea/hack to deploy a basic proxy as another service without istio sidecar on it ? Is there a better alternative ?

**Additional context**
I would like to keep istio ingress traffic for this microservice.

**Comment by victorboissiere** [comment]
I found the solution:

```yaml
traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0"
```

I've searched the repo for everything starting with `sidecar.istio.io` and found this.

**Comment by ahsannaseem** [comment]
@victorboissiere  did you add in deployment like this? 

`  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: "0.0.0.0"` apparently its not working for me.

**Comment by ahsannaseem** [comment]
@victorboissiere did you add in deployment like this?

annotations: traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0" apparently its not working for me.

**Comment by victorboissiere** [comment]
Yes, I added the annotations to my deployment yaml configuration. However wget is still not working (I always get ECONNRESET in my container). However curl is now working and my NodeJS application can now make requests to all URLs without restrictions.

```yaml
spec:
template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
```

**Comment by ahsannaseem** [comment]
Thanks @victorboissiere, so putting everything in detail here for better clarification. My service consist of following attributes in dedicated namespace (Not using ServiceEntry)

1. Deployment (1 deployment)
2. Configmaps (1 configmap)
3. Service
4. VirtualService
5. GW

Istio is enabled in namespace and when I create / run deployment it create 2 pods as it should. Now as stated in issues subject I want to allow all outgoing traffic for deployment because my serives needs to connect with 2 service discovery server: 

1. vault running on port 8200
2. spring config server running on http
3. download dependencies and communicate with other services (which are not part of vpc/ k8)

Using following deployment file will not open outgoing connections. Only thing works is simple `https request on port 443` like when i run `curl https://google.com` its success but no response on `curl http://google.com` Also logs showing connection with vault is not establishing as well.

I have used almost all combinations in deployment but non of them seems to work. Anything I am missing or doing this in wrong way? would really appreciate contributions in this :) 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: my-application-service
  name: my-application-service-deployment
  namespace: temp-nampesapce
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-application-service-deployment
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: my-application-service-env-variables
        image: image.from.dockerhub:latest
        name: my-application-service-pod
        ports:
        - containerPort: 8080
          name: myappsvc
        resources:
          limits:
            cpu: 700m
            memory: 1.8Gi
          requests:
            cpu: 500m
            memory: 1.7Gi

```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-application-service-ingress
  namespace: temp-namespace
spec:
  hosts:
  - my-application.mydomain.com
  gateways:
  - http-gateway
  http:
  - route:
    - destination:
        host: my-application-service
        port:
          number: 80
```
```
kind: Service
apiVersion: v1
metadata:
  name: my-application-service
  namespace: temp-namespace
spec:
  selector:
    app: api-my-application-service-deployment
  ports:
  - port: 80
    targetPort: myappsvc
    protocol: TCP
```
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
  namespace: temp-namespace
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.mydomain.com"
```
I didnt find any proper documentation on how to allow all traffic there are different methods working for different folks/cases wondering is there standard straight forward "how to?" on allowing all outgoing traffic.

**Comment by victorboissiere** [comment]
I haven't found any proper documentation on all the labels available so I had to search in the github repository for some.

I think I know where might be the issue. You are adding annotations on your deployment but not on your pods. I think Istio is just looking for annotations on pods.

Here's an example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "48"
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: my-app
    spec:
      containers:
        image: my-app:latest
```
