### ISSUE TITLE
Q: is it possible to apply 'fault policy' for a particular subset ?

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#9340]
'subset' is a server side construct - does it make sense to apply policy like fault injection using server side construct ?

The example here - https://istio.io/docs/tasks/traffic-management/fault-injection/ talks about how to inject fault based on client side construct such as headers.

However, I have tired bellow configuration to achieve the same for server side construct and failed:

```
# inject 40% failure on subset v2

spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 50
  - route:
    - destination:
        host: reviews
        subset: v2
      weight: 50
    fault:
      abort:
        httpStatus: 500
        percent: 40
```

Looks like all the traffic goes to subset v1 only. 

It is not possible to achieve this by design or am I missing something ?
