### ISSUE TITLE
Conflict between health probes and service

### ISSUE THREAD

**Issue by kuburoma** [istio/istio#9355]
**Actual behavior**
Deployment written in spring exposes endpoint actuator/health on port 9990. When i expose service port 9990 for same pod i see in pilot (discovery) logs following warning.

`(Omitting listener for management address 10.0.8.64_9990 ({%!s(*core.Address_SocketAddress=&{0xc420fae300})}) due to collision with service listener 10.0.8.64_9990 ({%!s&{0xc42308a280})}))`

**Expected behavior**
No warning.  :-D

**Steps to reproduce the bug**
Deploy given deployment.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testik-deployment
  namespace: payment
  labels:
    app: testik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testik
  template:
    metadata:
      labels:
        app: testik
    spec:
      containers:
      - name: testik
        command:
        - java
        - -Dfile.encoding=UTF-8
        - -jar
        - /app/app.jar
        image: kuburoman/istio-actuator-test
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9990
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9990
      dnsConfig:
        options:
        - name: single-request-reopen
---
kind: Service
apiVersion: v1
metadata:
  name: testik
  namespace: payment
  labels:
    app_name: "testik"
spec:
  ports:
  - name: http
    port: 8080
  - name: http-admin
    port: 9990
  selector:
    app: testik
```

**Version**
Istio: 1.0.2
Kubernetes: 1.11.2

**Installation**
kubectl apply istio-1.0.2/install/kubernetes/istio-demo.yaml

**Environment**
AKS 1.11.2
