### ISSUE TITLE
Routing doesn't work after applying retries

### ISSUE THREAD

**Issue by KevinKlinger** [istio/istio#9377]
**Description**
My deployment works fine when using the VirtualService without retires.
After adding the replies to the VirtualService and applying it to my K8s, the ingress traffic won't be routed to the services.

My understanding of the configuration below was, requests to /v1/configurations, /v1/metaData and /health are being routed to hostOne and if their requests are failing, they will be retried up to 3 times.
Is there anything I'm missing here?

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trial-routings
  namespace: test
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /v1/configurations
    - uri:
        prefix: /v1/metaData
    - uri:
        exact: /health
    route:
    - destination:
        host: hostOne
        port:
          number: 6005
    retries:
        attempts: 3
        perTryTimeout: 2s

  - match:
    - uri:
        exact: /v1/search
    - uri:
        exact: /version
    route:
    - destination:
        host: hostTwo
        port:
          number: 6004
---
```

**Version**
Istio-version: 1.0.2
K8s-version: 1.11.3
