### ISSUE TITLE
Configuring Egress to allow connections to external SMTP servers

### ISSUE THREAD

**Issue by Jul13nT** [istio/istio#9379]
**Describe the bug**
If I try to send an email from my Spring Boot application, I have the following error : 

Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: in-v3.mailjet.com, port: 587, response: -1.

Am I missing something in my configuration ? How to allow connections to external SMTP ?

**Expected behavior**
I should be able to send an email via the mailjet SMTP. If I run my application outside of the cluster, it works fine.

**Steps to reproduce the bug**

- Install Istio with sidecar injector.
- Add config to allow connections to mailjet SMTP:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: mailjet
spec:
    hosts:
    - "*.mailjet.com"
    ports:
    - number: 587
      name: tls
      protocol: TLS
    resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: mailjet
spec:
    hosts:
    - "*.mailjet.com"
    tls:
    - match:
      - port: 587
        sni_hosts:
        - "*.mailjet.com"
      route:
      - destination:
          host: "*.mailjet.com"
          port:
            number: 587
        weight: 100
```

- Try to send an email from a container.

**Version**
Istio version: 1.0.2
k8s version: 1.11.1

**Installation**
Helm & Tiller

**Environment**
Rancher 2.1.0 on Debian 9

**Comment by Jul13nT** [comment]
I also tried with TCP but it does not work either.

**Comment by ymesika** [comment]
Your `VirtualService` also has a whole `tls` block.

**Comment by Jul13nT** [comment]
Yes, I tried to use TCP in the VirtualService as well but no luck. 

I finally got it working by replacing "*.mailjet.com" with "in-v3.mailjet.com" in the `ServiceEntry`. But I don't know why I need to specify the exact host.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: mailjet
spec:
    hosts:
    - "in-v3.mailjet.com"
    ports:
    - number: 587
      name: tls
      protocol: TLS
    resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: mailjet
spec:
    hosts:
    - "*.mailjet.com"
    tls:
    - match:
      - port: 587
        sni_hosts:
        - "*.mailjet.com"
      route:
      - destination:
          host: "*.mailjet.com"
          port:
            number: 587
        weight: 100
```

Thanks for you help.
