### ISSUE TITLE
Trying to create allow all service entry for outgoing traffic but not succeeding 

### ISSUE THREAD

**Issue by ahsannaseem** [istio/istio#9425]
Tried different versions of config but none of them seems to work on my case

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allowall
  namespace: temp-env
spec:
  hosts:
  - "*"
```

Above template created assuming if no ports mention it will allow all. Then tried to create specifically with ports but still no success. 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allowall
  namespace: temp-env
spec:
  hosts:
  - "*"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  - number: 8200
    protocol: HTTPS

```

Wondering is there any way where we can allow all outing like it is in aws SGs by default.
