### ISSUE TITLE
Mixer should change headers to lowercase when processing adapter configs

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#9432]
**Describe the bug**
If I create an out of process adapter and set the config to:

```
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: requestcontext
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      user: request.headers["Authorization"]
```
and submit a request with the header set to Authorization, then Mixer will send a nil adapter config to my adapter. If I use mixc then this works fine, but if envoy is in the path, then it will change the header to lowercase meaning that there's no match. HTTP headers are case insensitive so this makes sense for envoy to do, but we should follow similar behaviors in mixs and mixer. 

**Expected behavior**
Passing a header of "Authorization" when the instance config is set to collect a header of "Authorization" should work. Since HTTP is  case insensitive, either Authorization or authorization should be acceptable in the config.

**Steps to reproduce the bug**
See *describe the bug*

**Version**
istio 1.0.2

**Installation**
No mutual TLS, followed instructions for minikube at istio.io. Auto-injection enabled on the namespace. 

**Environment**
minikube with Istio 1.0.2

**Cluster state**
