### ISSUE TITLE
pilot conflict for outbound_listener_tcp_over_current_tcp for some TLS SNI hosts on 443

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#9447]
The following configuration causes the conflict in Istio 1.0.2:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - '*.google.com'
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - '*.google.com'
  tls:
  - match:
    - port: 443
      sni_hosts:
      - '*.google.com'
    route:
    - destination:
        host: '*.google.com'
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: com
spec:
  hosts:
  - '*.com'
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: com
spec:
  hosts:
  - '*.com'
  tls:
  - match:
    - port: 443
      sni_hosts:
      - '*.com'
    route:
    - destination:
        host: '*.com'
        port:
          number: 443
      weight: 100    
EOF
```

Cleanup:
```
kubectl delete serviceentry google com
kubectl delete virtualservice google com
```

The conflict:

```
"pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:443": {
        "proxy": "reviews-v3-5465dc97bc-hw8wn.default",
                "message": "Listener=0.0.0.0:443 AcceptedTCP=*.google.com RejectedTCP=*.com TCPServices=1"
            }
        },
```

However, the following configuration does not cause the conflict:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - '*.google.com'
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - '*.google.com'
  tls:
  - match:
    - port: 443
      sni_hosts:
      - '*.google.com'
    route:
    - destination:
        host: '*.google.com'
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - '*.cnn.com'
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn
spec:
  hosts:
  - '*.cnn.com'
  tls:
  - match:
    - port: 443
      sni_hosts:
      - '*.cnn.com'
    route:
    - destination:
        host: '*.cnn.com'
        port:
          number: 443
      weight: 100
---
EOF
```

Cleanup:
```
kubectl delete serviceentry google cnn
kubectl delete virtualservice google cnn
```
