### ISSUE TITLE
A `ServiceEntry` for `*.cnn.com` opens access to any external service, such as `https://www.google.com` or `https://www.bing.com`

### ISSUE THREAD

**Issue by yskopets** [istio/istio#9457]
**Describe the bug**

A `ServiceEntry` for `*.cnn.com` opens access to any external service (over HTTPS), e.g.
- https://www.google.com
- https://www.bing.com

**Expected behavior**

A `ServiceEntry` for `*.cnn.com` should open access ONLY to `*.cnn.com`.

**Steps to reproduce the bug**

1. Follow `Configuring HTTP and HTTPS external services` example (https://istio.io/docs/examples/advanced-egress/egress-tls-origination/#configuring-http-and-https-external-services):

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - "*.cnn.com"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: NONE
EOF
```

2. Make a request to a URL other than `*.cnn.com`, e.g. `https://www.google.com/`

```
kubectl exec -it $SOURCE_POD -c sleep -- curl -v https://www.google.com/
```

3. Requests succeeds even though `www.google.com` is NOT registered in the Mesh

**Version**
`istioctl version`

```
version.BuildInfo{Version:"1.1.0.snapshot.1", GitRevision:"45692c579c6d755194421540149a99ac4cb59528", User:"root", Host:"ac7ff4b30ee4", GolangVersion:"go1.10.1", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}
```

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Installation**

1. Use Minikube (https://istio.io/docs/setup/kubernetes/platform-setup/minikube/)
2. Install Istio with default mutual TLS authentication (https://istio.io/docs/setup/kubernetes/quick-start/#option-2-install-istio-with-default-mutual-tls-authentication)

**Environment**

Minikube

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2503229/istio-dump.tar.gz)
