### ISSUE TITLE
Crash with Mixer Out of Process Adapter

### ISSUE THREAD

**Issue by repenno** [istio/istio#9459]
**Describe the bug**
Crash when adapting Mixer Out of Process Adapter to use logentry template

**Expected behavior**
I expected my handler to receive a message

**Steps to reproduce the bug**
Follow the steps in https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough

But use this operator config
```yaml
# handler for adapter mygrpcadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: h1
  namespace: istio-system
spec:
  adapter: mygrpcadapter
  connection:
    address: "[::]:9000" #replaces at runtime by the test
  params:
    file_path: "out.txt"
---

# instance for template logentry
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: i1logentry
  namespace: istio-system
spec:
  template: logentry
severity: '"Default"'
timestamp: request.time
variables:
  requestSize: request.size | 0
---

# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: r1
  namespace: istio-system
spec:
  actions:
  - handler: h1
    instances:
    - i1logentry
---
```

**Version**
$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Kubernetes version 1.10

**Installation**
I followed the steps here: https://istio.io/docs/setup/kubernetes/quick-start/

I chose option 1

**Environment**
MacOS 10.13.6
Also tested on Ubuntu 18.04, same problem

**Cluster state**
I am running minikube
