### ISSUE TITLE
An example of `ServiceEntry` for `*.cnn.com` is misleading (or incomplete)

### ISSUE THREAD

**Issue by yskopets** [istio/istio#9460]
**Describe the bug**
An example of `ServiceEntry` for `*.cnn.com` is misleading (or incomplete). 
When I try to add a similar `ServiceEntry` for `*.google.com`, `Istio Pilot` logs an error.

```
2018-10-22T19:27:44.811871Z	info	ads	Push finished: 50.966558ms {
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:443": {
                "proxy": "httpbin-69d95f94c6-fsvxb.namespace-b",
                "message": "Listener=0.0.0.0:443 AcceptedTCP=*.cnn.com RejectedTCP=*.google.com TCPServices=1"
            }
        }
    },
    "Start": "2018-10-22T19:27:44.760791845Z",
    "End": "2018-10-22T19:27:44.811711313Z",
    "AuthzPolicies": null
}
```

**Expected behavior**

* An example configuration should be complete
* If for some reason an example configuration can not be copied-and-pasted, it should be mentioned explicitly

**Steps to reproduce the bug**
1. Follow Configuring HTTP and HTTPS external services example (https://istio.io/docs/examples/advanced-egress/egress-tls-origination/#configuring-http-and-https-external-services):

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - "*.cnn.com"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: NONE
EOF
```

2. Create another `ServiceEntry` by example, e.g.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: default
spec:
  hosts:
  - "*.google.com"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: NONE
```

3. Check logs of `Istio Pilot`

```
2018-10-22T19:27:44.811871Z	info	ads	Push finished: 50.966558ms {
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:443": {
                "proxy": "httpbin-69d95f94c6-fsvxb.namespace-b",
                "message": "Listener=0.0.0.0:443 AcceptedTCP=*.cnn.com RejectedTCP=*.google.com TCPServices=1"
            }
        }
    },
    "Start": "2018-10-22T19:27:44.760791845Z",
    "End": "2018-10-22T19:27:44.811711313Z",
    "AuthzPolicies": null
}
```

**Version**
`istioctl version`

```
version.BuildInfo{Version:"1.1.0.snapshot.1", GitRevision:"45692c579c6d755194421540149a99ac4cb59528", User:"root", Host:"ac7ff4b30ee4", GolangVersion:"go1.10.1", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}
```

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
1. Use Minikube (https://istio.io/docs/setup/kubernetes/platform-setup/minikube/)
2. Install Istio with default mutual TLS authentication (https://istio.io/docs/setup/kubernetes/quick-start/#option-2-install-istio-with-default-mutual-tls-authentication)

**Environment**

Minikube

**Cluster state**

[istio-dump.tar.gz](https://github.com/istio/istio/files/2503188/istio-dump.tar.gz)
