### ISSUE TITLE
Match by `sourceLabels` doesn't work if a workload is not selected by any `Service`, e.g. `Job`, `CronJob`, etc

### ISSUE THREAD

**Issue by yskopets** [istio/istio#9464]
**Describe the bug**
* I have a workload that is not selected by any `Service`, e.g. `Job`, `CronJob`, etc
* I want to define routing rules for outgoing traffic based on labels of the source workload
* Apparently, match by `sourceLabels` doesn't work in such a case

**Expected behavior**
Routing rules should work consistently for all workload types, with or without a `Service`

**Steps to reproduce the bug**
1. Create a `ServiceEntry`

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: yahoo
  namespace: default
spec:
  hosts:
  - yahoo.com
  ports:
  - number: 443
    name: https-port
    protocol: HTTPS
  - number: 444
    name: https-port-green
    protocol: HTTPS
  - number: 445
    name: https-port-blue
    protocol: HTTPS
  resolution: NONE
```

2. Create routing rules based on labels of the source workload

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: conditional-yahoo
  namespace: default
spec:
  hosts:
  - yahoo.com
  gateways:
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - yahoo.com
      sourceLabels:
        color: blue
    route:
    - destination:
        host: yahoo.com
        port:
          number: 445
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - yahoo.com
      sourceLabels:
        color: green
    route:
    - destination:
        host: yahoo.com
        port:
          number: 444
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - yahoo.com
    route:
    - destination:
        host: yahoo.com
        port:
          number: 443
```

3. Create a `Job`

```
apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
  namespace: namespace-b
spec:
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - command:
        - /bin/sleep
        - infinity
        image: tutum/curl
        imagePullPolicy: IfNotPresent
        name: sleep
      restartPolicy: Never
  backoffLimit: 4
```

4. Inspect generated Envoy config of that Job

```
{
     "version_info": "2018-10-22T21:02:45Z",
     "listener": {
      "name": "0.0.0.0_443",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 443
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "server_names": [
          "yahoo.com"
         ]
        },
        "filters": [
         {
          "name": "mixer",
          "config": {
           "disable_check_calls": true,
           "mixer_attributes": {
            "attributes": {
             "context.reporter.kind": {
              "string_value": "outbound"
             },
             "context.reporter.uid": {
              "string_value": "kubernetes://sleep-k7pj8.namespace-b"
             },
             "source.uid": {
              "string_value": "kubernetes://sleep-k7pj8.namespace-b"
             },
             "source.namespace": {
              "string_value": "namespace-b"
             },
             "destination.service.host": {
              "string_value": "yahoo.com"
             },
             "destination.service.name": {
              "string_value": "yahoo.com"
             },
             "destination.service.namespace": {
              "string_value": "default"
             }
            }
           },
           "transport": {
            "check_cluster": "outbound|15004||istio-policy.istio-system.svc.cluster.local",
            "network_fail_policy": {
             "policy": "FAIL_CLOSE"
            },
            "report_cluster": "outbound|15004||istio-telemetry.istio-system.svc.cluster.local",
            "attributes_for_mixer_proxy": {
             "attributes": {
              "source.uid": {
               "string_value": "kubernetes://sleep-k7pj8.namespace-b"
              }
             }
            }
           }
          }
         },
         {
          "name": "envoy.tcp_proxy",
          "config": {
           "access_log": [
            {
             "name": "envoy.file_access_log",
             "config": {
              "path": "/dev/stdout",
              "format": "[%START_TIME%] %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME%\n"
             }
            }
           ],
           "stat_prefix": "outbound|443||yahoo.com",
           "cluster": "outbound|443||yahoo.com"
          }
         }
        ]
       }
```

5. Notice that traffic will be routed to `yahoo.com:443` while `yahoo.com:445` was expected (based on label `color: blue`)

**Version**
`istioctl version`
```
version.BuildInfo{Version:"1.1.0.snapshot.1", GitRevision:"45692c579c6d755194421540149a99ac4cb59528", User:"root", Host:"ac7ff4b30ee4", GolangVersion:"go1.10.1", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}
```

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
1. Use Minikube (https://istio.io/docs/setup/kubernetes/platform-setup/minikube/)
2. Install Istio with default mutual TLS authentication (https://istio.io/docs/setup/kubernetes/quick-start/#option-2-install-istio-with-default-mutual-tls-authentication)

**Environment**
Minikube

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2503446/istio-dump.tar.gz)
