### ISSUE TITLE
Http telemetry for service entries

### ISSUE THREAD

**Issue by victorboissiere** [istio/istio#9488]
Telemetry only reports tcp metrics for egress service entries. http/https metrics seems to be only available for internal services.

Does Istio supports http telemetry for egress service entries ?

Here's an example of one of my service entries:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: integration
spec:
  hosts:
  - "*.googleapis.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
  namespace: integration
spec:
  hosts:
  - "*.googleapis.com"
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*.googleapis.com"
    route:
    - destination:
        host: "*.googleapis.com"
        port:
          number: 443
      weight: 100
```

I am using the default Helm charts, I do have http metrics but not for egress traffic which is so important for us to be able to monitor external APIs.
