### ISSUE TITLE
Originating TLS from egressgateway with custom trust store makes CDS push to mesh pods fail

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#9500]
**Describe the bug**
I want to validate TLS connections against external services originated at the egressgateway with custom cacerts.
It looks like the DestinationRule that defines the truststore results in Clusters being pushed to mesh pods with the file name.
As the secret is not mounted in these pods they reject the CDS messages:

```
2018-10-24T07:08:12.227006Z     warn    ads     ADS:CDS: ACK ERROR 127.0.0.1:35160 sidecar~10.1.12.242~testcurl-f7dfd957-hsx9r.test~test.svc.cluster.local-1 version_info:"2018-10-24T06:57:38Z" node:<id:"sidecar~10.1.12.242~testcurl-f7dfd957-hsx9r.test~test.svc.cluster.local" cluster:"testcurl" metadata:<fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:99cfc3f74c414dd4fa4aa784a0f8b13e22b81893" > > fields:<key:"ISTIO_PROXY_VERSION" value:<string_value:"1.0.2" > > fields:<key:"ISTIO_VERSION" value:<string_value:"1.0.2" > > fields:<key:"POD_NAME" value:<string_value:"testcurl-f7dfd957-hsx9r" > > fields:<key:"istio" value:<string_value:"sidecar" > > >
build_version:"0/1.8.0-dev//RELEASE" > type_url:"type.googleapis.com/envoy.api.v2.Cluster" response_nonce:"2018-10-24 07:08:12.182012541 +0000 UTC m=+2349.750883664" error_detail:<code:13 message:"unable to read file: /etc/istio/root-certs/rootca.pem" >
```
Also `istioctl ps` shows that clusters are not fully pushed:
```
$ istioctl ps
PROXY                                                  CDS        LDS        EDS               RDS          PILOT                           VERSION
istio-egressgateway-7865848f66-ghxl9.istio-system      SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-6bf48dc56-kltbj     1.0.2
istio-ingressgateway-8695db5498-ntkvr.istio-system     STALE      SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6bf48dc56-kltbj     1.0.2
testcurl-f7dfd957-hsx9r.sr-test                        STALE      SYNCED     SYNCED (100%)     SYNCED       istio-pilot-6bf48dc56-kltbj     1.0.2

```

**Expected behavior**
As there are no VirtualServices referencing the Subset of the DestinationRule that uses the caCertificates file, all clusters should be to all pods.

**Steps to reproduce the bug**
1. Create custom caCertificates and store them as a Secret:
  `kubectl create secret generic -n istio-system rootca --from-file=rootca.pem=rootca.pem`
2. Install Istio with a configuration that mounts the certificates into the egressgateway:
```yaml
gateways:
  istio-egressgateway:
    enabled: true
    labels:
      app: istio-egressgateway
      istio: egressgateway
    replicaCount: 1
    autoscaleMin: 1
    autoscaleMax: 5
    cpu:
      targetAverageUtilization: 80
    serviceAnnotations: {}
    type: ClusterIP #change to NodePort or LoadBalancer if need be
    ports:
      - port: 80
        name: http2
      - port: 443
        name: https
    secretVolumes:
      - name: egressgateway-certs
        secretName: istio-egressgateway-certs
        mountPath: /etc/istio/egressgateway-certs
      - name: egressgateway-ca-certs
        secretName: istio-egressgateway-ca-certs
        mountPath: /etc/istio/egressgateway-ca-certs
      # This is added
      - name: root-certs
        secretName: rootca
        mountPath: /etc/istio/root-certs
```
3. Create a Gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: test
spec:
  selector:
    app: istio-egressgateway
    istio: egressgateway
  servers:
  - hosts:
    - testservice.test
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      caCertificates: /etc/certs/root-cert.pem
      mode: MUTUAL
      privateKey: /etc/certs/key.pem
      serverCertificate: /etc/certs/cert-chain.pem
```
4. Configure a VirtualService that redirects to the egress gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService 
metadata:                                      
  name: testservice
  namespace: test                                     
spec:                      
  gateways:    
  - mesh       
  - test-gateway    
  hosts:      
  - testservice.test
  http:                                              
  - match:         
    - gateways:     
      - mesh        
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: egress-test
      weight: 100
  - match:
    - gateways:
      - test-gateway
      port: 443
    route:
    - destination:
        host: virtual-testservice.test
        port:
          number: 80
        subset: test
      weight: 100
```
5. Configure the DestinationRule for forwarding traffic to the egressgateway with mTLS:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-test
  namespace: test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: egress-test
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: testservice.test
```
6. Configure the DestinationRule to validate TLS connections in the egressgateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test
  namespace: test
spec:
  host: virtual-testservice.test
  subsets:
  - name: test
    trafficPolicy:
      connectionPool:
        tcp:
          connectTimeout: 5.000s
      tls:
        caCertificates: /etc/istio/root-certs/rootca.pem
        mode: SIMPLE
```

Clearly there is nobody using the subset `test` in a "mesh gateway".
Pilot should not try to push it as a Cluster.
Funnily it even pushes the routes and clusters that are required to get the call through over the gateway including TLS validation, but other clusters are affected.

**Version**
istioctl version:
```
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
I installed istio with 
```
helm install ~/istio/istio-1.0.2/install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/istio/istio-1.0.2/install/kubernetes/helm/istio/values-istio-auth-tls.yaml  --set global.mtls.enabled=true
```

In comparison to the original values-istio-auth.yaml the config file only contains the configuration of the egress gateway.

**Environment**
Kubernetes on Docker for Mac.

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
