### ISSUE TITLE
AWS EKS Istio routing does not work

### ISSUE THREAD

**Issue by dshmatov** [istio/istio#9529]
Platform: EKS, Minikube
k8s: v1.10.4
Istio: v1.0.2

So I'm stuck and have no clue what to do I have two namespaces with automatic Istio injection: `demo` and `default`. I've created Deployment inside of each namespace:
```
---
kind: Service
apiVersion: v1
metadata:
  name: demo-app-svc-2
  namespace: demo
  labels:
    app: demo-app-2
spec:
  selector:
    app: demo-app-2
  ports:
  - name: web
    port: 80
    targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-2
  namespace: demo
  labels:
    app: demo-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-2
  template:
    metadata:
      labels:
        app: demo-app-2
    spec:
      containers:
      - name: demo-app
        image: shmatovd/demo-app:0.0.9
        ports:
        - name: web
          containerPort: 8080

```

```
---
kind: Service
apiVersion: v1
metadata:
  name: demo-app-svc
  labels:
    app: demo-app
    version: v1
spec:
  selector:
    app: demo-app
  ports:
  - name: web
    port: 80
    targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v1
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
      - name: demo-app
        image: shmatovd/demo-app:0.0.9
        ports:
        - name: web
          containerPort: 8080

```

And created some routing rules with rewrite from `/reviews` to `/metrics`
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-app-vs
spec:
  hosts:
  - demo-app-svc.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /reviews
    rewrite:
      uri: /metrics
    route:
    - destination:
        host: demo-app-svc.default.svc.cluster.local
        subset: v1
  - route:
    - destination:
        host: demo-app-svc.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo-app-dr
spec:
  host: demo-app-svc.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1

```

when I'm trying to `curl` from `demo` namespace:
```
curl demo-app-svc.default.svc.cluster.local/reviews

```

I got no rewrites, got no logs about this request in Envoy sidecars on both Pods. Do I do something wrong? But if I try to point this routing to some external resource like `wikipedia.org` it works perfectly!

`Istio-system` namespace
```
NAME                                        READY     STATUS    RESTARTS   AGE
istio-citadel-769b85bf84-762dd              1/1       Running   0          20h
istio-egressgateway-677c95648f-mz555        1/1       Running   0          20h
istio-galley-5c65774d47-c8nq9               1/1       Running   0          20h
istio-ingressgateway-6fd6575b8b-4p55z       1/1       Running   0          20h
istio-pilot-65f4cfb764-pl8xr                2/2       Running   0          20h
istio-policy-5b9945744b-zgjv8               2/2       Running   0          20h
istio-sidecar-injector-75bfd779c9-x9jm5     1/1       Running   0          20h
istio-statsd-prom-bridge-7f44bb5ddb-6fjcv   1/1       Running   0          20h
istio-telemetry-5fc7ccc5b7-dxxhp            2/2       Running   0          20h
prometheus-84bd4b9796-btgj2                 1/1       Running   0          20h
```
`demo` namespace
```
NAME                              READY     STATUS    RESTARTS   AGE
pod/demo-app-2-7b747bc88f-6tdnr   2/2       Running   0          24m
pod/demo-app-2-7b747bc88f-jpv2l   2/2       Running   0          24m

NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/demo-app-svc-2   ClusterIP   172.20.27.25   <none>        80/TCP    24m

NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-app-2   2         2         2            2           24m

NAME                                    DESIRED   CURRENT   READY     AGE
replicaset.apps/demo-app-2-7b747bc88f   2         2         2         24m

```
`default` namespace
```
NAME                           READY     STATUS    RESTARTS   AGE
pod/demo-app-69b6ddd94-ms52g   2/2       Running   0          19h

NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/demo-app-svc   ClusterIP   172.20.134.134   <none>        80/TCP    19h
service/kubernetes     ClusterIP   172.20.0.1       <none>        443/TCP   1d

NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-app   1         1         1            1           19h

NAME                                 DESIRED   CURRENT   READY     AGE
replicaset.apps/demo-app-69b6ddd94   1         1         1         19h
```

**Comment by eduardobaitello** [comment]
@dshmatov Istio has a [naming porting convention](https://istio.io/help/faq/traffic-management/#naming-port-convention).

> The port names must be of the form protocol-suffix with http, http2, grpc, mongo, or redis as the protocol in order to take advantage of Istio’s routing features.

Please, try to rename your service port to something like this:
```
kind: Service
apiVersion: v1
metadata:
  name: demo-app-svc-2
  namespace: demo
  labels:
    app: demo-app-2
spec:
  selector:
    app: demo-app-2
  ports:
  - name: http-web   # <------------------------------------
    port: 80
    targetPort: web
```

**Comment by dshmatov** [comment]
Thank you @eduardobaitello ! It helped me a lot, but I was able to find out the solution by pointing `Service` to 8081 (you may use whatever port you want, except 80 ) and route traffic in `VirtualService` destination rule to this port, like:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: demo-app-svc-2
  namespace: demo
  labels:
    app: demo-app-2
spec:
  selector:
    app: demo-app-2
  ports:
  - name: web
    port: 8081    # <---------------------------------------------------
    targetPort: web
```
