### ISSUE TITLE
Istio gateway logging a lot if no "https" port exists for any gateway

### ISSUE THREAD

**Issue by miv** [istio/istio#9531]
**Describe the bug**
When using multiple https gateways port names are identifiers (sic!). So in our setup all https ports are named like name: "https-my-service-staging". Because no port named "https" port exists, gateways and pilot constantly writting errors

```
[2018-10-25 11:18:37.047][63][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 2, RDS: Failed to generate route https.443.https for node &{Kubernetes router 10.199.20.5 istio-ingressgateway-7986798496-pr7ql.istio-system istio-system.svc.cluster.local map[ISTIO_PROXY_VERSION:1.0.2 ISTIO_PROXY_SHA:istio-proxy:99cfc3f74c414dd4fa4aa784a0f8b13e22b81893 ISTIO_VERSION:1.0.2 POD_NAME:istio-ingressgateway-7986798496-pr7ql istio:sidecar]}: buildGatewayRoutes: could not find server for routeName https.443.https, have map[http.80:[port:<number:80 protocol:"HTTP" name:"http-stage-service2-web" > hosts:"stage-service2-web.ourdomain.com"  port:<number:80 protocol:"HTTP" name:"http-stage-service1-web" > hosts:"stage-service1-web.ourdomain.com" ] https.443.https-stage-service2-web:[port:<number:443 protocol:"HTTPS" name:"https-stage-service2-web" > hosts:"stage-service2-web.ourdomain.com" tls:<mode:SIMPLE server_certificate:"/etc/istio/ingressgateway-ourdomain-com-certs/tls.crt" private_key:"/etc/istio/ingressgateway-ourdomain-com-certs/tls.key" > ] https.443.https-stage-service1-web:[port:<number:443 protocol:"HTTPS" name:"https-stage-service1-web" > hosts:"stage-service1-web.ourdomain.com" tls:<mode:SIMPLE server_certificate:"/etc/istio/ingressgateway-ourdomain-com-certs/tls.crt" private_key:"/etc/istio/ingressgateway-ourdomain-com-certs/tls.key" > ]]
```

**Expected behavior**
If it so happened that istio must have diffenent port names to differentiate https  gateways, it should not expect to have https port. It must work without any gateways having port named "https"

**Steps to reproduce the bug**
Create gateway like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: server-service1-stage-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - stage-service1-web.yourdomain.com
    port:
      name: http-stage-service1-web
      number: 80
      protocol: HTTP
  - hosts:
    - stage-service1-web.yourdomain.com
    port:
      name: https-stage-service1-web
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-yourdomain-com-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-yourdomain-com-certs/tls.crt
```

See erros. Create any other empty gateways with port named "https" and errors are gone!

**Version**
1.0.2

**Installation**
Helm

**Environment**
Kubernetes 1.11
