### ISSUE TITLE
TCP egress with dynamic IPs (DNS resolution)

### ISSUE THREAD

**Issue by sneko** [istio/istio#9536]
Hi everyone! 

For development purposes I use a remote SMTP servers that catch all emails to let me check if everything works even without having a specific email adress. To resolve this remote service I use a ServiceEntry resource that targets 3 IPs through a TCP connection. But I have just noticed they are using dynamic IPs so every 2-3 days they are changing 😢 .

I have to change it manually each time the SMTP IPs changed and it's really annoying.

My question is (feature request): do you plan to support DNS resolver for TCP external requests (since I'm reaching the SMTP servers through a subdomain)?

I guess there are some techninal limitations because you didn't release that earlier, but is it possible it works?

Thank you,

Here is my ServiceEntry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mailtrap
spec:
  hosts:
  - "smtp.mailtrap.io"
  addresses:
  - "34.194.188.188/32"
  - "52.203.151.210/32"
  - "34.199.205.108/32"
  location: MESH_EXTERNAL
  ports:
  - number: 2525
    name: tcp
    protocol: TCP
  resolution: DNS
```
_Note: according to the documentation the "resolution" property is useless due to TCP connection_
