### ISSUE TITLE
Order of gateway server creation causing egress-gateway to crash

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#9546]
**Describe the bug**
when creating`Gateway` resources for an egress-gateway, the order of server creation will cause the egress-gateway to crash and become unusable. The use-case is where an egress-gateway allows egress traffic both for the client-side HTTPS requests and also egress-gateway based TLS origination. So we must create gateway resources which listen on 443 and use both HTTPS + MUTUAL and TLS + MUTUAL in a mtls-enabled cluster.
**Expected behavior**
I should be able to create both the following types of servers on gateways (residing on the same egress-gateway pod):
* server.protocol: HTTPS, server.tls.mode: MUTUAL
* server.protocol: TLS, server.tls.mode: MUTUAL

**Steps to reproduce the bug**
If we create a gateway server as follows:
STEP 1
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "https-mutual-example"
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: "https-example"
      protocol: HTTPS
    tls:
      mode: MUTUAL
      caCertificates: /etc/certs/root-cert.pem
      privateKey: /etc/certs/key.pem
      serverCertificate: /etc/certs/cert-chain.pem
    hosts:
      - "www.example.com"
```
STEP 2
and then create a TLS based gateway such as that in the example found here:
https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/

eg:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-egressgateway
  spec:
    selector:
      istio: egressgateway
    servers:
    - port:
        number: 443
        name: tls-cnn
        protocol: TLS
      hosts:
      - edition.cnn.com
      tls:
        mode: MUTUAL
        serverCertificate: /etc/certs/cert-chain.pem
        privateKey: /etc/certs/key.pem
        caCertificates: /etc/certs/root-cert.pem
    - port:
        number: 443
        name: tls-google
        protocol: TLS
      hosts:
      - www.google.com
      tls:
        mode: MUTUAL
        serverCertificate: /etc/certs/cert-chain.pem
        privateKey: /etc/certs/key.pem
        caCertificates: /etc/certs/root-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn-to-egressgateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-to-egressgateway
spec:
  hosts:
  - www.google.com
  gateways:
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: google
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  gateways:
  -  istio-egressgateway
  tcp:
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
   name: set-sni-mtls-for-egressgateway
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
      - name: cnn
        trafficPolicy:
          loadBalancer:
            simple: ROUND_ROBIN
          portLevelSettings:
          - port:
              number: 443
            tls:
              mode: ISTIO_MUTUAL
              sni: edition.cnn.com
      - name: google
        trafficPolicy:
          loadBalancer:
            simple: ROUND_ROBIN
          portLevelSettings:
          - port:
              number: 443
            tls:
              mode: ISTIO_MUTUAL
              sni: www.google.com
```

the egress-gateway will then spit out the following logs:
```text
[2018-10-25 22:26:36.356][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:500] add/update cluster outbound|443||edition.cnn.com starting warming
[2018-10-25 22:26:36.365][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:500] add/update cluster outbound|443||www.google.com starting warming
[2018-10-25 22:26:36.370][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|443|google|istio-egressgateway.istio-system.svc.cluster.local complete
[2018-10-25 22:26:36.370][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|443|cnn|istio-egressgateway.istio-system.svc.cluster.local complete
[2018-10-25 22:26:36.371][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|443||istio-egressgateway.istio-system.svc.cluster.local complete
[2018-10-25 22:26:36.375][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|80|google|istio-egressgateway.istio-system.svc.cluster.local complete
[2018-10-25 22:26:36.375][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|80|cnn|istio-egressgateway.istio-system.svc.cluster.local complete
[2018-10-25 22:26:36.375][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|80||istio-egressgateway.istio-system.svc.cluster.local complete
[2018-10-25 22:26:36.388][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|443||www.google.com complete
[2018-10-25 22:26:36.390][22][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:512] warming cluster outbound|443||edition.cnn.com complete
[2018-10-25 22:26:36.430][22][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_443: Proto constraint validation failed (field: "route_specifier", reason: is required): stat_prefix: "0.0.0.0_443"
http_filters {
  name: "mixer"
  config {
    fields {
      key: "default_destination_service"
      value {
        string_value: "default"
      }
    }
    fields {
      key: "forward_attributes"
      value {
        struct_value {
          fields {
            key: "attributes"
            value {
              struct_value {
                fields {
                  key: "source.uid"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    fields {
      key: "mixer_attributes"
      value {
        struct_value {
          fields {
            key: "attributes"
            value {
              struct_value {
                fields {
                  key: "context.reporter.kind"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "outbound"
                        }
                      }
                    }
                  }
                }
                fields {
                  key: "context.reporter.uid"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                        }
                      }
                    }
                  }
                }
                fields {
                  key: "source.namespace"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "istio-system"
                        }
                      }
                    }
                  }
                }
                fields {
                  key: "source.uid"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    fields {
      key: "service_configs"
      value {
        struct_value {
          fields {
            key: "default"
            value {
              struct_value {
              }
            }
          }
        }
      }
    }
    fields {
      key: "transport"
      value {
        struct_value {
          fields {
            key: "attributes_for_mixer_proxy"
            value {
              struct_value {
                fields {
                  key: "attributes"
                  value {
                    struct_value {
                      fields {
                        key: "source.uid"
                        value {
                          struct_value {
                            fields {
                              key: "string_value"
                              value {
                                string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          fields {
            key: "check_cluster"
            value {
              string_value: "outbound|9091||istio-policy.istio-system.svc.cluster.local"
            }
          }
          fields {
            key: "network_fail_policy"
            value {
              struct_value {
                fields {
                  key: "policy"
                  value {
                    string_value: "FAIL_CLOSE"
                  }
                }
              }
            }
          }
          fields {
            key: "report_cluster"
            value {
              string_value: "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
            }
          }
        }
      }
    }
  }
}
http_filters {
  name: "envoy.cors"
}
http_filters {
  name: "envoy.fault"
}
http_filters {
  name: "envoy.router"
}
tracing {
  operation_name: EGRESS
  client_sampling {
    value: 100
  }
  random_sampling {
    value: 100
  }
  overall_sampling {
    value: 100
  }
}
access_log {
  name: "envoy.file_access_log"
  config {
    fields {
      key: "path"
      value {
        string_value: "/dev/stdout"
      }
    }
  }
}
use_remote_address {
  value: true
}
generate_request_id {
  value: true
}
upgrade_configs {
  upgrade_type: "websocket"
}
stream_idle_timeout {
}

[2018-10-25 22:26:36.430][22][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: Proto constraint validation failed (field: "route_specifier", reason: is required): stat_prefix: "0.0.0.0_443"
http_filters {
  name: "mixer"
  config {
    fields {
      key: "default_destination_service"
      value {
        string_value: "default"
      }
    }
    fields {
      key: "forward_attributes"
      value {
        struct_value {
          fields {
            key: "attributes"
            value {
              struct_value {
                fields {
                  key: "source.uid"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    fields {
      key: "mixer_attributes"
      value {
        struct_value {
          fields {
            key: "attributes"
            value {
              struct_value {
                fields {
                  key: "context.reporter.kind"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "outbound"
                        }
                      }
                    }
                  }
                }
                fields {
                  key: "context.reporter.uid"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                        }
                      }
                    }
                  }
                }
                fields {
                  key: "source.namespace"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "istio-system"
                        }
                      }
                    }
                  }
                }
                fields {
                  key: "source.uid"
                  value {
                    struct_value {
                      fields {
                        key: "string_value"
                        value {
                          string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    fields {
      key: "service_configs"
      value {
        struct_value {
          fields {
            key: "default"
            value {
              struct_value {
              }
            }
          }
        }
      }
    }
    fields {
      key: "transport"
      value {
        struct_value {
          fields {
            key: "attributes_for_mixer_proxy"
            value {
              struct_value {
                fields {
                  key: "attributes"
                  value {
                    struct_value {
                      fields {
                        key: "source.uid"
                        value {
                          struct_value {
                            fields {
                              key: "string_value"
                              value {
                                string_value: "kubernetes://istio-egressgateway-57469596c9-dq88j.istio-system"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          fields {
            key: "check_cluster"
            value {
              string_value: "outbound|9091||istio-policy.istio-system.svc.cluster.local"
            }
          }
          fields {
            key: "network_fail_policy"
            value {
              struct_value {
                fields {
                  key: "policy"
                  value {
                    string_value: "FAIL_CLOSE"
                  }
                }
              }
            }
          }
          fields {
            key: "report_cluster"
            value {
              string_value: "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
            }
          }
        }
      }
    }
  }
}
http_filters {
  name: "envoy.cors"
}
http_filters {
  name: "envoy.fault"
}
http_filters {
  name: "envoy.router"
}
tracing {
  operation_name: EGRESS
  client_sampling {
    value: 100
  }
  random_sampling {
    value: 100
  }
  overall_sampling {
    value: 100
  }
}
access_log {
  name: "envoy.file_access_log"
  config {
    fields {
      key: "path"
      value {
        string_value: "/dev/stdout"
      }
    }
  }
}
use_remote_address {
  value: true
}
generate_request_id {
  value: true
}
upgrade_configs {
  upgrade_type: "websocket"
}
stream_idle_timeout {
}

```

**Version**
istio-1.0.2/bin/istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
helm installer with MTLS enabled

**Environment**
docker-for-mac + tested on AWS + Kops

**Cluster state**
nothing special about cluster state other than the order of steps the config is applied in.

**Comment by vadimeisenbergibm** [comment]
@castlemilk  As a workaround, you can use the same gateway for all the three hosts, just specify protocol TLS for the port (HTTPS is treated the same as TLS).

**Comment by PiotrSikora** [comment]
From the logs:
```
[2018-10-25 22:26:36.430][22][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_443: Proto constraint validation failed (field: "route_specifier", reason: is required): stat_prefix: "0.0.0.0_443"
```
it looks that Pilot sends invalid configuration. Perhaps it's internally mixing/overriding `0.0.0.0_443` (HTTPS) and `0.0.0.0_443` (TCP) resources? cc @costinm @rshriram 

FWIW, I don't believe mixing HTTPS & TCP listeners on the same IP:port is currently supported. Adding support for it would require moving from non-binding listeners to a filter chain matching with SNI-based selection between HTTPS & TCP filter chains. cc @duderino @costinm

**Comment by duderino** [comment]
I think the priority is on fixing Pilot to send valid config, but does Envoy need to protect itself better too?

@castlemilk did Envoy actually crash here?  The crash isn't visible in the logs.  If it entered an unstable state, what did that look like?

**Comment by castlemilk** [comment]
The way this issue was reached was from trying to enable transparent HTTPS traffic with TLS origination from the client application and also TLS origination from the egressgateway. These two scenarios are covered in the documentation here:
* https://istio.io/docs/examples/advanced-egress/egress-gateway/#perform-tls-origination-with-the-egress-gateway
* https://istio.io/docs/examples/advanced-egress/egress-gateway/#direct-https-traffic-through-an-egress-gateway

Once envoy is in the state described above, it will not longer correctly handle any egress traffic from what I observed. Effectively breaking egress entirely.

Another approach to solving was to add another port (8443) to the service definition of the egress gateway and then to use one port for HTTPS and one for TLS based gateway servers/listeners.

**Comment by duderino** [comment]
@rshriram told me he could do this for 1.1

**Comment by vadimeisenbergibm** [comment]
The problem is with using 443 in the egress gateway for both HTTP/mTLS and HTTPS/mTLS traffic. I submitted a PR https://github.com/istio/istio.io/pull/3200 to the [Egress Gateway with TLS Origination(https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway-tls-origination/) example.

Follow the instructions in the PR for HTTP/mTLS with TLS origination for edition.cnn.com, and the following configuration for for HTTPS/mTLS for www.google.com and en.wikipedia.org:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia
spec:
  hosts:
  - en.wikipedia.org
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-egressgateway-tls
  spec:
    selector:
      istio: egressgateway
    servers:
    - port:
        number: 443
        name: tls-wikipedia
        protocol: TLS
      hosts:
      - en.wikipedia.org
      tls:
        mode: MUTUAL
        serverCertificate: /etc/certs/cert-chain.pem
        privateKey: /etc/certs/key.pem
        caCertificates: /etc/certs/root-cert.pem
    - port:
        number: 443
        name: tls-google
        protocol: TLS
      hosts:
      - www.google.com
      tls:
        mode: MUTUAL
        serverCertificate: /etc/certs/cert-chain.pem
        privateKey: /etc/certs/key.pem
        caCertificates: /etc/certs/root-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikipedia-to-egressgateway
spec:
  hosts:
  - en.wikipedia.org
  gateways:
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - en.wikipedia.org
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: wikipedia
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-to-egressgateway
spec:
  hosts:
  - www.google.com
  gateways:
  - mesh
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: google
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikipedia
spec:
  hosts:
  - en.wikipedia.org
  gateways:
  - istio-egressgateway-tls
  tcp:
  - match:
    - gateways:
      - istio-egressgateway-tls
      port: 443
    route:
    - destination:
        host: en.wikipedia.org
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  gateways:
  -  istio-egressgateway-tls
  tcp:
  - match:
    - gateways:
      - istio-egressgateway-tls
      port: 443
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
   name: set-sni-mtls-for-egressgateway
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
      - name: wikipedia
        trafficPolicy:
          loadBalancer:
            simple: ROUND_ROBIN
          portLevelSettings:
          - port:
              number: 443
            tls:
              mode: ISTIO_MUTUAL
              sni: en.wikipedia.org
      - name: google
        trafficPolicy:
          loadBalancer:
            simple: ROUND_ROBIN
          portLevelSettings:
          - port:
              number: 443
            tls:
              mode: ISTIO_MUTUAL
              sni: www.google.com
```

To test it:

```
kubectl exec -it $SOURCE_POD -c sleep -- curl -s http://edition.cnn.com/politics | grep -o "<title>.*</title>"; kubectl exec -it $SOURCE_POD -c sleep -- curl -s https://www.google.com | grep -o "<title>.*</title>"; kubectl exec -it $SOURCE_POD -c sleep -- curl -s https://en.wikipedia.org/wiki/Main_page | grep -o "<title>.*</title>"
```

The output:
```
<title>CNNPolitics - Political News, Analysis and Opinion</title>
<title>Google</title>
<title>Wikipedia, the free encyclopedia</title>
```

Check the logs of the egress gateway:
```
kubectl logs -l istio=egressgateway -c istio-proxy -n istio-system | tail
```

The output:
```
[2019-02-06T14:06:06.390Z] "GET /politics HTTP/2" 200 - 0 1880375 35 7 "172.30.230.23" "curl/7.60.0" "abd8a2df-e639-91d0-99c6-1e45822ab2da" "edition.cnn.com" "151.101.65.67:443" outbound|443||edition.cnn.com - 172.30.146.106:80 172.30.230.23:41802 edition.cnn.com
[2019-02-06T14:06:08.327Z] "- - -" 0 - 601 17777 1308 - "-" "-" "-" "-" "216.58.197.196:443" outbound|443||www.google.com 172.30.146.106:50376 172.30.146.106:443 172.30.230.23:59082 www.google.com
[2019-02-06T14:06:10.655Z] "- - -" 0 - 578 81220 87 - "-" "-" "-" "-" "91.198.174.192:443" outbound|443||en.wikipedia.org 172.30.146.106:35682 172.30.146.106:443 172.30.230.23:59106 en.wikipedia.org
```

Note HTTP log entry for edition.cnn.com and TCP log entry for www.google.com and en.wikipedia.org, as expected.

CC @rshriram @duderino
