### ISSUE TITLE
X-Forwarded headers behavior with remove and append request headers features

### ISSUE THREAD

**Issue by gunhu** [istio/istio#9595]
**Describe the bug**

When I declare a VirtualService with **removeRequestHeaders** and **appendRequestHeaders**

**removeRequestHeaders** parameter imply that we cannot specify a new value for this header on the same request.

It seems to be done after appendRequestHeaders, here is a tcpdump capture trace:

> GET / HTTP/1.1
host: append.unhu.re
user-agent: curl/7.61.1
accept: */*
x-forwarded-for: 10.233.20.0
x-envoy-internal: true
x-request-id: 92fe6694-db96-9bb2-a71e-b26e7bcec935
x-envoy-decorator-operation: application.namespace.svc.preprod.kubernetes:80/*
x-b3-traceid: fb8170dd3fc887f4
x-b3-spanid: fb8170dd3fc887f4
x-b3-sampled: 1
x-istio-attributes: CjEKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRIVEhNnaXRodWJyZXZpZXctc2VydmVyCi4KHWRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZXNwYWNlEg0SC2NvcmViYWNrZW5kCkQKCnNvdXJjZS51aWQSNhI0a3ViZXJuZXRlczovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LThmZ2t6LmlzdGlvLXN5c3RlbQpUChhkZXN0aW5hdGlvbi5zZXJ2aWNlLmhvc3QSOBI2Z2l0aHVicmV2aWV3LXNlcnZlci5jb3JlYmFja2VuZC5zdmMucHJlcHJvZC5rdWJlcm5ldGVzCk0KF2Rlc3RpbmF0aW9uLnNlcnZpY2UudWlkEjISMGlzdGlvOi8vY29yZWJhY2tlbmQvc2VydmljZXMvZ2l0aHVicmV2aWV3LXNlcnZlcg==
content-length: 0

**appendRequestHeaders** if specified alone can put multiple strings in an already existing header in some case like **X-Forwarded-Proto** header it's a single value so it's not compliant with the standard, here is a tcpdump capture trace:

> GET / HTTP/1.1
host: append.unhu.re
user-agent: curl/7.61.1
accept: */*
x-forwarded-proto: http,https
x-forwarded-for: 10.233.20.0
x-envoy-internal: true
x-request-id: 088489d0-1b83-9870-9d52-3fe57829c7b4
x-envoy-decorator-operation: application.namespace.svc.preprod.kubernetes:80/*
x-b3-traceid: f1a8d44c0f978c47
x-b3-spanid: f1a8d44c0f978c47
x-b3-sampled: 1
x-istio-attributes: CjEKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRIVEhNnaXRodWJyZXZpZXctc2VydmVyCi4KHWRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZXNwYWNlEg0SC2NvcmViYWNrZW5kCkQKCnNvdXJjZS51aWQSNhI0a3ViZXJuZXRlczovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LThmZ2t6LmlzdGlvLXN5c3RlbQpUChhkZXN0aW5hdGlvbi5zZXJ2aWNlLmhvc3QSOBI2Z2l0aHVicmV2aWV3LXNlcnZlci5jb3JlYmFja2VuZC5zdmMucHJlcHJvZC5rdWJlcm5ldGVzCk0KF2Rlc3RpbmF0aW9uLnNlcnZpY2UudWlkEjISMGlzdGlvOi8vY29yZWJhY2tlbmQvc2VydmljZXMvZ2l0aHVicmV2aWV3LXNlcnZlcg==
content-length: 0

**Expected behavior**

The x-forwarded-proto header should be:

``x-forwarded-proto: https``

**Steps to reproduce the bug**

First case (with removeRequestHeaders and appendRequestHeaders):

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: application-vs
  namespace: default
spec:
  hosts:
  - "append.unhu.re"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: application.namespace.svc.preprod.kubernetes
        port:
          number: 80
    removeRequestHeaders: [ "X-Forwarded-Proto" ]
    appendRequestHeaders:
       "X-Forwarded-Proto": "https"
```

Second case (with only appendRequestHeaders):

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: application-vs
  namespace: default
spec:
  hosts:
  - "append.unhu.re"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: application.namespace.svc.preprod.kubernetes
        port:
          number: 80
    appendRequestHeaders:
       "X-Forwarded-Proto": "https"
```

**Version**

**istioctl**:

1.1.0-snapshot.2

**kubectl**:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**

Using the helm chart of the upstream archive.

**Environment**

Bare-metal setup on GNU/Linux Debian Stretch.

**Cluster state**

I will provide it if it's relevant since it's an Istio ingress only setup and related to headers manipulation.
