### ISSUE TITLE
404 while accessing External services in istio 

### ISSUE THREAD

**Issue by PrajwalGurumurthy** [istio/istio#9607]
**404 while accessing External services in istio. I am trying to do tls origination at the envoy proxy through virtual services for external  services. I am using the following yamls.**

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-com
spec:
  hosts:
  - test.com
  ports:
  - number: 80
    name: http-test1
    protocol: HTTP
  - number: 443
    name: http-test2
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-edition-test-com
spec:
  host: test.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS when accessing test.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rewrite-port-for-test-com
spec:
  hosts:
  - test.com
  http:
  - match:
      - port: 80
    route:
    - destination:
        host: test.com
        port:
          number: 443
```

**Observed behavior**

I am trying to access https://test.com from an application within the istio mesh.

After creating the above resources. I am accessing test.com from the application container as http://test.com:80/ , I am able to access the https://test.com [external service] which is outside the istio servicemesh.
Tls termination/origination is working fine at the envoy proxy.

If I delete the pod ( with application and envoy proxy as containers in it) and create a new pod, I am no longer able to access http://test.com from with in the application container.

If I delete and recreate the above mentioned service entry with different port names, thing again start working as before.
Please note if I use the same port names as before It doesnt work.
I am able to reproduce this consistently

I am using Istio 1.0.2
I am using kubernetes 1.10.8
Istio was installed using helm 
K8s was installed using kops.
K8s is runnning on AWS.

**Logs from ENVOY proxy:**
This is when u get 404

[2018-10-29T13:12:18.332Z] "POST /test/v1 HTTP/1.1" 404 NR 0 0 0 - "-" "ReactorNetty/0.7.9.RELEASE" "5b7b6b25-7b3b-9574-a72d-c5e4feda2ca7" "test.com" "-"

This is when thing are fine.

[2018-10-29T14:01:37.440Z] "POST /test/v1 HTTP/1.1" 200 - 70 507 101 100 "-" "ReactorNetty/0.7.9.RELEASE" "d1092107-1c41-9b75-865c-1f42c9391c21" "test.com" "xx.xxx.xxx.xx:443"
