### ISSUE TITLE
excludeOutboundPorts to facilitate headless data stores

### ISSUE THREAD

**Issue by Stono** [istio/istio#9632]
Hey, 
So we are still trying to fight istio to manage to use headless services within our cluster, and I know this causes pain for many other people (see the numerous issues).

The latest example is kafka, in which clients need to be able to connect to:

  - kafka-0.headless-service.namespace.svc.cluster.local:9092
  - kafka-1.headless-service.namespace.svc.cluster.local:9092
  - kafka-2.headless-service.namespace.svc.cluster.local:9092

All of the options we've talk about in the past aren't great, and are largely cluster wide and quite clumsy.

I'm wondering if it would be able to add an `excludeOutboundPorts` option to proxy_init, this would just resolve the problems of talking to headless services on specific ports, eg redis, mongo, kafka, etc etc for specific clients.

It seems like a decent addition as we already have:

  - traffic.sidecar.istio.io/includeOutboundIPRanges
  - traffic.sidecar.istio.io/excludeOutboundIPRanges
  - traffic.sidecar.istio.io/includeInboundPorts
  - traffic.sidecar.istio.io/excludeInboundPorts

**Comment by Stono** [comment]
Hmm, 
I don't know if this is a side effect or not, but creating a destinationrule for the headless service

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-to-kafka-headless
spec:
  host: kafka-headless.kafka.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

Successfully allows me to connect to `kafka-0.kafka-headless.kafka.svc.cluster.local:9092`.  I swear, this used to throw 404s.
