### ISSUE TITLE
Q: Running Gateway on VM

### ISSUE THREAD

**Issue by ayush201** [istio/istio#9675]
I'm able to run gateway on VM but I noticed that it's not able to pull bookinfo-gateway configuration
e.g.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
Output from gateway running in the VM (I notice port 80 is missing):
```
$ curl 0:15000/listeners
["0.0.0.0:15090"]
```

Output from gateway running in K8S:
```
root@istio-ingressgateway-5f6ddfdc86-qkq7p:/# curl 0:15000/listeners
["0.0.0.0:15090","0.0.0.0:80"]
```

I believe it's because of selector/label stuff since VM doesn't have the right labels. How do I go about getting this to work? 

`root 26757 0.3 0.4 141984 37256 pts/0 Sl 19:44 0:34 /opt/istio/istio-ingress/bin/envoy -c /opt/istio/istio-ingress/confi g/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster rawvm --service-node router ~10.128.0.18~kokoro-mesh-1-vm-ayushshr.default~default.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warn --v2-config-only`
