### ISSUE TITLE
Calling external services using mTLS

### ISSUE THREAD

**Issue by awalmsley** [istio/istio#9684]
The Istio reference docs have an example of calling an external service with mTLS. The client certificate, key and CA certificate need to be mounted in the Istio proxy container.
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-mongocluster
spec:
  host: mymongodb.somedomain
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
```
Is there a way to mount the certificates, while still using automatic sidecar injection? It looks as if it is necessary to generate the sidecars with Istioctl and then edit the deployment YAML to add a volume mount for the certificates.
