### ISSUE TITLE
VirtualServices don't affect Istio Service to Service calls

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#9696]
**Describe the bug**
Using the VirtualService below, I want to delay all requests to HTTPBIN for 15 seconds:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 80
    fault:
      delay:
        percent: 100
        fixedDelay: 15s
```

**Expected behavior**
All requests should be delayed by 15 seconds.

**Steps to reproduce the bug** and [Repo for the files](https://github.com/rinormaloku/call)

### 1. Install Istio and enable auto injection.

$ helm template install/kubernetes/helm/istio --name istio --set global.mtls.enabled=false --set tracing.enabled=true --set kiali.enabled=true --set grafana.enabled=true --namespace istio-system > istio.yaml

$ kubectl label namespace default istio-injection=enabled

### 2. Create a sample app:

$ kubectl apply -f [https://raw.githubusercontent.com/rinormaloku/call/master/call-service.yaml](https://raw.githubusercontent.com/rinormaloku/call/master/call-service.yaml)
$ kubectl apply -f [https://raw.githubusercontent.com/rinormaloku/call/master/httpbin.yaml](https://raw.githubusercontent.com/rinormaloku/call/master/httpbin.yaml)

### 3. Add an HTTP Gateway and VirtualService to send requests to the **Call Service**

$ kubectl apply -f [https://raw.githubusercontent.com/rinormaloku/call/master/istio-resources/http-gateway.yaml](https://raw.githubusercontent.com/rinormaloku/call/master/istio-resources/http-gateway.yaml)
$ kubectl apply -f [https://raw.githubusercontent.com/rinormaloku/call/master/istio-resources/virtualservice-external-call.yaml](https://raw.githubusercontent.com/rinormaloku/call/master/istio-resources/virtualservice-external-call.yaml)

### 4. (**The issue**) Add VirtualService to delay all calls from the Call service to HTTPBIN

$ kubectl apply -f [https://raw.githubusercontent.com/rinormaloku/call/master/istio-resources/virtualservice-httpbin.yaml](https://raw.githubusercontent.com/rinormaloku/call/master/istio-resources/virtualservice-httpbin.yaml)

### 5. CURL to the Call Service:
`curl $INGRESSGATEWAY_IP/call`

RESULT: **No delay**

**Version**
Istio 1.0.3
Kubernetes 1.11.3

**Environment**
AKS, Linux nodes

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2539306/istio-dump.tar.gz)

**Comment by hzxuzhonghu** [comment]
I tested this using istio on master. And the delay works well.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
     - uri:
         prefix: "/reviews/0"
    fault:
      delay:
        percent: 100
        fixedDelay: 7s
    route:
    - destination:
        host: reviews
        port: 
          number: 9080
  - route:
    - destination:
        host: reviews
        port:
          number: 9080

```
