### ISSUE TITLE
Healthchecks not working with Nginx?

### ISSUE THREAD

**Issue by sneko** [istio/istio#9709]
**Describe the bug**
Impossible to make readiness and liveness probes working with an Nginx docker image. I tried with mine, then I also tried an official one used in the example below.

Here is the error returned by Kubernetes when killing the pod:
`Readiness probe failed: Get http://100.96.2.160:80/healthz/tea: read tcp 100.96.2.1:39690->100.96.2.160:80: read: connection reset by peer`

Note that it works well when disabling the sidecar injection (for my images and the official one).

That's really strange... maybe I missed something?

**Expected behavior**
That it works

**Steps to reproduce the bug**
Use this deployment with Istio injection:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: app
        image: nginxdemos/hello:plain-text
        imagePullPolicy: Always
        ports:
        - name: deployment-port
          containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz/tea
            httpHeaders:
            - name: header1
              value: "some value"
            - name: header2
              value: "123"
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
```

_Before using this deployment example found here: https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/health-checks#example , I was using what you described here: https://raw.githubusercontent.com/istio/istio/release-1.0/samples/health-check/liveness-http.yaml

**Version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Istio 1.0.2

**Installation**
Helm chart

**Environment**
Cloud

**Cluster state**
Everything is working except that
