### ISSUE TITLE
ServiceEntry update not regenerating config

### ISSUE THREAD

**Issue by frankbu** [istio/istio#9743]
**Describe the bug**
This may be a more general regen problem, but my particular example is that I've created a ServiceEntry that redirects port 80 and 443 to an egressgateway (config with ISTIO_META_REQUESTED_NETWORK_VIEW=external) using an external network endpoint. This works as expected, but when I later remove one of the ports from the ServiceEntry and apply, the generated proxy config does not change.

**Expected behavior**
I left it running for 2 days, and still the update never happened, so it seems this is not just a long propagation delay issue.

**Steps to reproduce the bug**
Apply the following configuration.
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - edition.cnn.com
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  resolution: DNS
  endpoints:
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      https: 443
      http: 80
  - address: edition.cnn.com
    network: external
    ports:
      https: 443
      http: 80
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
  http:
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 80
EOF
```
Using the sleep sample
```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - http://edition.cnn.com/politics
```
If you look at the egressgateway logs you will see both http and https calls go through it, as expected.

Now remove the one of the endpoint ports from the serviceentry, e.g.,
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  resolution: DNS
  endpoints:
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      #https: 443
      http: 80
  - address: edition.cnn.com
    network: external
    ports:
      #https: 443
      http: 80
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
```
Retry the curl and nothing has changed. 

Look at the generated config in the sidecar, and you will see that it has not changed.

**Version**
Latest from release-1.1 branch

**Installation**

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by hzxuzhonghu** [comment]
I create a ServiceEntry , and I can still access `edition.cnn.com` by http and https. I guess if undefined, it will use spec.ports to build cluster.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  resolution: DNS
  endpoints:
  - address: istio-egressgateway.istio-system.svc.cluster.local
    #ports:                         do not contain any port
    #  https: 443
    #  http: 80
  - address: edition.cnn.com
    network: external
    ports:
      https: 443
      http: 80
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
```

```
root@szvp000201060:~# istioctl pc cluster sleep-58b99f48dd-6phmj  --fqdn  "outbound|80||edition.cnn.com" -ojson 
[
    {
        "name": "outbound|80||edition.cnn.com",
        "type": "STRICT_DNS",
        "connectTimeout": "1s",
        "hosts": [
            {
                "socketAddress": {
                    "address": "istio-egressgateway.istio-system.svc.cluster.local",
                    "portValue": 80
                }
            }
        ],
        "circuitBreakers": {
            "thresholds": [
                {}
            ]
        },
        "dnsLookupFamily": "V4_ONLY"
    }
]

```
