### ISSUE TITLE
Incorrect SNI values for ISTIO_MUTUAL clusters

### ISSUE THREAD

**Issue by rshriram** [istio/istio#9744]
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L270
updates the TLS clusters in place when converting from ISTIO_MUTUAL to normal MUTUAL.
This results in config corruption where the sni value generated for the first service ends up in the subsequent service as well, causing all mTLS connections to the second service to fail.

Steps to reproduce:

```yaml
apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: global-destinationrule
    namespace: default
  spec:
    host: '*.global'
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
  kind: ServiceEntry
  metadata:
    name: mysql-default-serviceentry
    namespace: default
  spec:
    addresses:
    - 127.255.1.1
    endpoints:
    - address: istio-egressgateway.istio-system.svc.cluster.local
      ports:
        TCP-3306-mysql-default: 15443
    hosts:
    - mysql.default.global
    location: MESH_INTERNAL
    ports:
    - name: TCP-3306-mysql-default
      number: 3306
      protocol: TCP
    resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
  kind: ServiceEntry
  metadata:
    name: server-default-serviceentry
    namespace: default
  spec:
    addresses:
    - 127.255.1.1
    endpoints:
    - address: istio-egressgateway.istio-system.svc.cluster.local
      ports:
        HTTP-80-server-default: 15443
    hosts:
    - server.default.global
    location: MESH_INTERNAL
    ports:
    - name: HTTP-80-server-default
      number: 80
      protocol: HTTP
    resolution: DNS
```

results in a CDS output with the following cluster:

```
{
     "version_info": "2018-11-05T15:54:32Z/16",
     "cluster": {
      "name": "outbound|80||server.default.global",
      "type": "STRICT_DNS",
      "connect_timeout": "1s",
      "hosts": [
       {
        "socket_address": {
         "address": "istio-egressgateway.istio-system.svc.cluster.local",
         "port_value": 15443
        }
       }
      ],
      "circuit_breakers": {
       "thresholds": [
        {}
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "tls_certificates": [
         {
          "certificate_chain": {
           "filename": "/etc/certs/cert-chain.pem"
          },
          "private_key": {
           "filename": "/etc/certs/key.pem"
          }
         }
        ],
        "validation_context": {
         "trusted_ca": {
          "filename": "/etc/certs/root-cert.pem"
         }
        },
        "alpn_protocols": [
         "istio"
        ]
       },
       "sni": "outbound_.3306_._.mysql.default.global"
      },
      "dns_lookup_family": "V4_ONLY"
     },
     "last_updated": "2018-11-05T15:55:17.293Z"
    },
```

where you see `outbound_.3306_.mysql.default.global` as the sni value for `outbound|80||server.default.global`. It should instead be `outbound_.80_.server.default.global`
