### ISSUE TITLE
Session affinity doesn't seem to apply to weighted subsets - Envoy support required

### ISSUE THREAD

**Issue by hngo4619** [istio/istio#9764]
**Describe the bug**
When attempting to apply session affinity to weighted subsets, the session affinity doesn't seem to apply and the subsets will randomly get served based on their weights as normal. Session affinity works as expected when not applying custom weighted subsets. 

**Expected behavior**
Session affinity to apply on top of weighted subsets. So user will randomly be sent to a version based on the assigned weight, and once they get to that version, they will continue being served that version.

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-world
  namespace: hdngo
spec:
  host: hello-world.hdngo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 0s
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: istio-system
spec:
  gateways:
  - istio-autogenerated-k8s-ingress
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: hello-world.hdngo.svc.cluster.local
        subset: v1
      weight: 60
    - destination:
        host: hello-world.hdngo.svc.cluster.local
        subset: v2
      weight: 30
    - destination:
        host: hello-world.hdngo.svc.cluster.local
        subset: v3
      weight: 10
```

**Version**
```
istioctl version                                                     
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8+IKS", GitCommit:"6e1ad1c45c23e44d15090962f3e738735998687a", GitTreeState:"clean", BuildDate:"2018-09-27T13:44:25Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Using Helm according to the documentation [here](https://istio.io/docs/setup/kubernetes/helm-install/).

**Environment**
IBM Cloud Public

**Cluster state**
N/A.

**Comment by dshmatov** [comment]
@hngo4619 Yep, I can confirm the same issue for me, also I've tried to define session affinity in subsets - the same result. I can tell more, it produces the same cookie hash for each of subset. It is weird. I'm trying to implement Canary Deployments approach but got a mix of resources (prod and canary) on the same web page

**Comment by Gadigg** [comment]
Same issue here,
 I'm trying to use Istio for implementing sticky sessions between two versions of the same service for a canary build, the cookie is set on request header but it seems that the VirtualService doesn't know how to lock on to a single subset after it was set to it keeps changing between services according to the weights supplied.. 
Did anyone succeed on achieving something like that?

Here's my VirtualService and DestinationRule 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary
spec:
  gateways:
  - canary-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
      headers:
    route:
    - destination:
        host: canary
        port:
          number: 5000
        subset: v1
      weight: 50
    - destination:
        host: canary
        port:
          number: 5000
        subset: v3
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: canary
spec:
  host: canary
  trafficPolicy:
   loadBalancer:
     consistentHash:
       httpCookie:
         name: canary-user
         ttl: 0s
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v3
    name: v3
```

**Comment by Gadigg** [comment]
Hi @vadimeisenbergibm did you get a chance to look at this?

**Comment by vadimeisenbergibm** [comment]
According to https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/load_balancers#ring-hash:

> The ring hash load balancer does not currently support weighting.

I guess this is the reason. @rshriram Am I correct?

**Comment by markmssd** [comment]
Ran into the exact same issue. This is really a deal breaker for us. Is there any alternative?

**Comment by vadimeisenbergibm** [comment]
@rshriram @costinm @kyessenov Any ideas? ^

**Comment by chriskolenko** [comment]
+1

**Comment by markmssd** [comment]
I ended up using https://istio.io/blog/2017/0.1-canary/#focused-canary-testing instead

**Comment by FengLiqiong** [comment]
Same issue in istio-1.1.0-rc.5.
But it seems istio 1.1.0 is using envoy 1.10.0, and envoy 1.10.0 ring hash load balancer seems to support weighting.

Please check https://github.com/istio/proxy/blob/1.1.0-rc.5/istio.deps:

> "lastStableSHA": "925810d00b0d3095a8e67fd4e04e0f597ed188bb"

and https://github.com/envoyproxy/envoy/blob/925810d00b0d3095a8e67fd4e04e0f597ed188bb/VERSION:

> 1.10.0-dev

and envoy 1.10.0 docs https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/load_balancers#ring-hash:

> Each host is hashed and placed on the ring some number of times proportional to its weight. For example, if host A has a weight of 1 and host B has a weight of 2, then there might be three entries on the ring: one for host A and two for host B. ......

**Comment by FengLiqiong** [comment]
Same issue in istio-1.1.1.
Istio-1.1.1 is using envoy SHA 8912fa36acdf4367d37998d98cead376762d2b49 which contains commit(https://github.com/envoyproxy/envoy/pull/5846 - upstream: support host and locality weighting in ring hash lb).

**Comment by FengLiqiong** [comment]
When we specify weight under [HTTPRouteDestination](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRouteDestination) in istio virtualservice, in envoy the weight under [weightedcluster](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-weightedcluster-clusterweight) is configured, and this `weight` is used to choose an upstream cluster when a request matches the route.
Incoming HTTP requests are matched to an upstream cluster(subset) with this `weight` before they are distributed between multiple hosts within a the upstream cluster(subset) by the ring hash load balancer, so requests with the same hash code can not be sticky to the same upstream cluster(subset). 
I think that is why session affinity doesn't apply to weighted subsets in istio/envoy.

The `weight` mentioned in [envoy ring hash load balancer](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/load_balancers#ring-hash) is pointing to the  [endpoint weight](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/endpoint/endpoint.proto#envoy-api-field-endpoint-lbendpoint-load-balancing-weight) which is assigned to an endpoint.
I don't see the envoy endpoint weight is exposed by istio, and if it is exposed, I think session affinity can apply to weighted clusters, but still can not apply to weighted subsets.

**Comment by FengLiqiong** [comment]
The response set-cookie header seems weired because it produces the same cookie hash for each of subset. If we use the virtualservice and destinationrule provided by @hngo4619, for the first requests there will be 3 same set-cookie headers `user="<same-hash-code-for-example-0d773697c78c675d>"` generated.
if running `istioctl proxy-config routes` to check the envoy configuration, you can see 3 same `cookie` hash policies are defined under `route`:
```
[
    {
        ...
        "virtualHosts": [
            {
                ...
                "routes": [
                    {
                        ...
                        "route": {
                            "weightedClusters": {
                                ...
                            }
                            "hashPolicy": [
                                {
                                    "cookie": {
                                        "name": "user",
                                        "ttl": "0s"
                                    }
                                },
                                {
                                    "cookie": {
                                        "name": "user",
                                        "ttl": "0s"
                                    }
                                },
                                {
                                    "cookie": {
                                        "name": "user",
                                        "ttl": "0s"
                                    }
                                }
                            ],
```

**Comment by stockhausenj** [comment]
Has there been any progress regarding the ability to have weight-based routing + consistentHashLB to prevent traffic from being split up between multiple pods on a single page load?

**Comment by shotat** [comment]
Any updates?

**Comment by ja3per** [comment]
> Has there been any progress regarding the ability to have weight-based routing + consistentHashLB to prevent traffic from being split up between multiple pods on a single page load?

I'm looking for the solution too.

**Comment by altitdb** [comment]
I have the same problem in version 1.1.9. Anyone found a solution for this problem?

**Comment by conrallendale** [comment]
In [this file](https://github.com/istio/istio/blob/master/tests/testdata/config/destination-rule-all.yaml), the trafficPolicy is specified as a subset config, not as a global DestinationRule config. So I guess the behaviour described on this issue was not supposed to work.

According to this file, the sticky sessions works between pods inside a subset, not between subsets, which makes the sticky session useless for canary deployments.

Was this behaviour intentional, or is this a bug?

**Comment by ja3per** [comment]
> Has there been any progress regarding the ability to have weight-based routing + consistentHashLB to prevent traffic from being split up between multiple pods on a single page load?

this config works for me. You can refer to.
`---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
   name: dsd-api-sso
   namespace: delivery-dsd
spec:
   host: dsd-api-sso
   trafficPolicy:
      loadBalancer:
        consistentHash:
          httpCookie:
            name: router
            ttl: 0s
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS`

**Comment by altitdb** [comment]
@ja3per, can you share your VirtualService configuration with us?

**Comment by ja3per** [comment]
> @ja3per, can you share your VirtualService configuration with us?

@altitdb sure, following is the vs configuration.
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dsd-api-sso
  namespace: delivery-dsd
spec:
  hosts:
  - "*"
  gateways:
  - dsd-gateway
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*"
    route:
    - destination:
        host: dsd-api-sso
        port:
          number: 8443
```

**Comment by stockhausenj** [comment]
@ja3per 
I think this feature is really only useful when you have > 1 destination rule so that you can do canary releases. I don't see where you are doing that.

**Comment by stockhausenj** [comment]
e.g
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  ...
spec:
  ...
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: service1.mynamespace.svc.cluster.local
        subset: v1
        ...
      weight: 80
    - destination:
        host: servic2.mynamespace.svc.cluster.local
        subset: v2
        ...
      weight: 20
```

**Comment by vadimeisenbergibm** [comment]
Duplicate of https://github.com/istio/istio/issues/1703

**Comment by conrallendale** [comment]
This is not a duplicate of #1703, but a bug from it.

**Comment by vadimeisenbergibm** [comment]
Posted a question on Envoy's repo https://github.com/envoyproxy/envoy/issues/8167

**Comment by vadimeisenbergibm** [comment]
@hngo4619 @Gadigg @conrallendale @dshmatov @altitdb @FengLiqiong This feature is not supported by Envoy. See https://github.com/envoyproxy/envoy/issues/8167#issuecomment-528930341:

> This isn't currently possible. Weighted clusters are chosen based on a random value selected at request time. I'll go ahead and label this as an enhancement request.

Once it is implemented in Envoy, I hope it will be transparently used by Istio without any change.

**Comment by vadimeisenbergibm** [comment]
@FengLiqiong Thank you for your explanation in https://github.com/istio/istio/issues/9764#issuecomment-479748409. It helped me to understand the issue and to post it at Envoy's repo. Sorry I missed your comments before.

**Comment by temporafugiunt** [comment]
Is there a workaround for this?

I ask because a real life example shows how important this is:
I have two different versions of my web app which "compile" random names for JavaScript files using WebPack to kill caching between versions. If my route changes mid download of a JS file (which it appears it does as this is the behavior I am seeing) the file may or may not exist in the version I have just switched to because it might have a different name so it terminates downloading with only a partial file. The call succeeds with 200 but the contents are incomplete.

Even if it didn't the contents of the file could change between versions so if it can't choose a subset at first request and stick to that subset then I could essentially be downloading a file whose contents change mid stream maybe?

**Comment by vadimeisenbergibm** [comment]
@temporafugiunt I understand the urgency of the requirement. Can you write on the Envoy's issue https://github.com/envoyproxy/envoy/issues/8167 and provide them your input and ask what could be a possible workaround? Maybe Envoy's community will have more answers. And maybe they will give that issue a higher priority. Istio is based on Envoy, once Envoy adds this feature, it will be simple/trivial to add it to Istio.

**Comment by Jeskz0rd** [comment]
For the time being, are there any suggestions for a workaround? 
I'm also following Envoy's issue [envoyproxy/envoy#8167](https://github.com/envoyproxy/envoy/issues/8167)

**Comment by taisho6339** [comment]
In my use case, I solved that issue with the following configuration.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-service-gateway-vs
spec:
  hosts:
    - "*"
  gateways:
    - sample-service-gateway
  http:
    - match:
        - headers:
            Cookie:
              exact: sample-service-version=v1
      route:
        - destination:
            host: sample-service
            subset: v1
            port:
              number: 8080
    - match:
        - headers:
            Cookie:
              exact: sample-service-version=v2
      route:
        - destination:
            host: sample-service
            subset: v2
            port:
              number: 8080
    - route:
        - destination:
            host: sample-service
            subset: v1
            port:
              number: 8080
          weight: 50
          headers:
            response:
              add:
                "Set-Cookie": sample-service-version=v1; Max-Age=2592000
        - destination:
            host: sample-service
            subset: v2
            port:
              number: 8080
          weight: 50
          headers:
            response:
              add:
                "Set-Cookie": sample-service-version=v2; Max-Age=2592000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sample-service
spec:
  host: sample-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
```

**Comment by jmendesky** [comment]
It looks like the change in envoy has been merged fairly recently: https://github.com/envoyproxy/envoy/pull/14875
is there any plan for making this available in Istio?

**Comment by ldemailly** [comment]
is https://github.com/istio/istio/issues/9764#issuecomment-631994703 still the only way to achieve this or is the integration with envoy's consistent hashing doable across weights/subsets now? (and if not shouldn't this be open?)

**Comment by ldemailly** [comment]
Btw correction/gotcha: don't use
```yaml
         - headers:
           Cookie:
              exact: sample-service-version=v1
```
as this would only work if you have exactly 1 cookie (which is practically never the case for real browser requests)

it would be nice that istio supports understanding individual cookies as opposed to just raw headers but in the meantime you'd need something like
```yaml
         - headers:
           Cookie:
              regex: sample-service-version=v1
```
(with the caveat this isn't quite a regex and will match that string anywhere, you can add optional ; etc ... as needed)


Also I use no Max-Age to get session cookies

**Comment by jcometki** [comment]
I had this same issue, I solved that with the following configuration:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sample-virtual-service
spec:
  gateways:
    - default
  hosts:
    - sample-host
  http:
    - match:
        - headers:
            Cookie:
              regex: .*userAffinity=v1.*
      route:
        - destination:
            host: sample-host.svc.cluster.local
            port:
              number: 80
            subset: v1
    - match:
        - headers:
            Cookie:
              regex: .*userAffinity=v2.*
      route:
        - destination:
            host: sample-host.svc.cluster.local
            port:
              number: 80
            subset: v2
    - route:
        - destination:
            host: sample-host.svc.cluster.local
            port:
              number: 80
            subset: v1
          weight: 75
        - destination:
            host: sample-host.svc.cluster.local
            port:
              number: 80
            subset: v2
          headers:
            response:
              add:
                Set-Cookie: userAffinity=v2; Max-Age=3600000
          weight: 25
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: sample-destination-rule
spec:
  host: sample-host.svc.cluster.local
  subsets:
    - labels:
        app: sample-app-v1
      name: v1
      trafficPolicy:
        loadBalancer:
          consistentHash:
            httpCookie:
              name: userAffinity=v1
              ttl: 1h
    - labels:
        app: sample-app-v2
      name: v2
```
