### ISSUE TITLE
no cors header response after define cors policy in vs?

### ISSUE THREAD

**Issue by shenxg13** [istio/istio#9783]
**Describe the bug**
no cors header response after define cors policy in vs

**Expected behavior**
cors header should be responsed.

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "192.168.0.62"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-gateway-vs
spec:
  hosts:
  - "192.168.0.62"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - port: 80
      uri:
        exact: /headers
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port: 
          number: 8080
    corsPolicy:
      allowOrigin:
      - "foo.example"
      allowMethods:
      - POST
      - GET
      allowHeaders:
      - authorization
      - content-type
      - accept
      - origin
      - user-agent
      exposeHeaders:
      - x-custom-header
      maxAge: 300s
      allowCredentials: true
```
```
[~/K8s/istio/istio-1.0.2/samples/bookinfo/platform/kube]$ curl http://192.168.0.62/headers -I
HTTP/1.1 200 OK
server: envoy
date: Wed, 07 Nov 2018 09:00:10 GMT
content-type: application/json
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 335
x-envoy-upstream-service-time: 8
```

**Version**
```
[~/K8s/istio/istio-1.0.2/samples/bookinfo/platform/kube]$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

[~/K8s/istio/istio-1.0.2/samples/bookinfo/platform/kube]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
[~/K8s/istio/istio-1.0.2/samples/bookinfo/platform/kube]$
```

**Comment by jondinard** [comment]
I'm having this issue as well, using the following configuration:
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: whitehall
  namespace: whitehall-istio
spec:
  hosts:
  - "*"
  gateways:
  - whitehall-gateway
  http:
  - match:
    - uri:
        prefix: /case/healthz
    rewrite:
      uri: /healthz
    corsPolicy:
      allowOrigin:
      - example.com
      allowMethods:
      - POST
      - GET
      allowCredentials: false
      allowHeaders:
      - X-Foo-Bar
      maxAge: "1h"
    route:
    - destination:
        host: caseservice-service
        port:
          number: 8085
  - route:
    - destination:
        host: caseservice-service
    corsPolicy:
      allowOrigin:
      - example.com
      allowMethods:
      - POST
      - GET
      allowCredentials: false
      allowHeaders:
      - X-Foo-Bar
      maxAge: "1h"`

**Comment by mrolla** [comment]
For envoy to return the CORS related headers you need to send at least the `Origin` ([preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)).

Try with

```
curl -v -HOrigin:foo.example http://192.168.0.62/headers
```

If it still does not work, make sure envoy is actually configured as expected with

```
istioctl proxy-config -n istio-system route istio-ingressgateway-... -ojson
```

**Comment by nahidupa** [comment]
I'm having this issue as well, Anyone know any alternative bypass, This almost block me going forward with istio.

**Comment by Bessonov** [comment]
It's even worse for me. I get only two headers `access-control-allow-origin` and `access-control-allow-credentials`. The others headers for methods and custom headers are not returned at all.

**Comment by Paic** [comment]
Experiencing the same issue on a Kubernetes Cluster v1.13.0 with Istio v1.0.5.

**Comment by Bessonov** [comment]
unstale

**Comment by prabhu-mannu** [comment]
i am having the same issue. CorsPolicy is not working on 1.17 and 1.8 
is there any solution for this ?
I have posted the question here: https://stackoverflow.com/questions/56578464/unable-to-get-corspolicy-working-in-istio

**Comment by mrnonz** [comment]
I have same issue on a Kubernetes Cluster v1.14.3 with Istio v1.2.0.

**Comment by jnsvd** [comment]
I'm facing the same issue with Istio 1.1.0.

**Comment by alexanderbuhler** [comment]
From what I could observe you have to provide the protocol aswell:

```
- https://foo.example
- http://foo.example
...
```

Does it work for you this way? I also thought it would be generic for any protocol

**Comment by philnichol** [comment]
I'm facing the same issue with Istio 1.1.7, have tried both with and without the protocol

**Comment by alexanderbuhler** [comment]
Oh okay. It's working for us with istio 1.2, so can't verify for 1.1.X.

**Comment by philnichol** [comment]
Oddly I get the following:
```
curl -X POST -H "Origin: https://not-allowed.com" https://api.test.local --head
HTTP/2 200
x-powered-by: Express
access-control-allow-origin: *
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
content-type: application/json; charset=utf-8
content-length: 5
etag: W/"5-fLbvuYullyqbUJDcLlF/4U0SywQ"
date: Wed, 24 Jul 2019 13:43:35 GMT
x-envoy-upstream-service-time: 6
server: istio-envoy

curl -X POST -H "Origin: https://allowed.com" https://api.test.local --head
HTTP/2 200
x-powered-by: Express
access-control-allow-origin: https://allowed.com
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
content-type: application/json; charset=utf-8
content-length: 5
etag: W/"5-fLbvuYullyqbUJDcLlF/4U0SywQ"
date: Wed, 24 Jul 2019 13:44:19 GMT
x-envoy-upstream-service-time: 4
server: istio-envoy```

Seems it return "access-control-allow-origin: *" if the Origin header doesn't match the CorsPolicy, but returns "access-control-allow-origin: https://allowed.com" when it does
config:
```
...
 "cors": {
    "allowOrigin": [
        "https://allowed.com"
    ],
    "allowMethods": "POST,OPTIONS",
    "allowHeaders": "Content-Type",
    "filterEnabled": {
        "defaultValue": {
            "numerator": 100
         }
     }
},
...
```

**Comment by Bessonov** [comment]
activity occurs

**Comment by mrnonz** [comment]
Any update?

**Comment by Bessonov** [comment]
@howardjohn @liamawhite istio-policy-bot is the new way of disrespecting community.

**Comment by liamawhite** [comment]
bump

**Comment by thangbn** [comment]
still happening with 1.2.5 release

**Comment by fhopfensperger** [comment]
have the same problem with istio version: 1.3.3.
Tried to specifiy allowOrigins with procotol (https) and without.
kubeversion: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5+IKS", GitCommit:"46ea161061498e0ebd9b11d66b3b7dba16fa594d", GitTreeState:"clean", BuildDate:"2019-10-17T13:24:04Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alefcarlos** [comment]
I was struggling with this issue, but in my case it was the formaing file:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/name: {{ include "account-api.name"  . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "account-api.name"  . }}
spec:
  gateways:
  - {{ .Values.istio.gateway }}
  hosts:
  - {{ .Values.istio.host }}
  http:
  - match:
    {{- if .Values.ssl.enabled }}
    - port:
        number: {{ .Values.ssl.port }}
    {{- end }}
    - uri:
        prefix: {{ .Values.istio.prefix }}
    route:
    - destination:
        host: {{ include "account-api.name"  . }}
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
      allowOrigin:
      - "http://localhost:5510"
      allowMethods:
      - POST
      - GET
      allowHeaders:
      - authorization
      - content-type
      - accept
      - origin
      - user-agent
      allowCredentials: true
      maxAge: "24h"
```

Now, everything is ok ! Thanks !

**Comment by blockspacer** [comment]
What's the status of that issue?

**Comment by EyalZilberblum** [comment]
I have the same issue, on Istio 1.2.2, when i set the allowOrigin header in VirtualService the envoy server return the origin that made the request without validating/filtering. 
This has security impact on production systems -although Low, but still need to be addressed.

Alternatively it there a way to configure the VS to make envoy not respond the access-control-allow-origin header?

**Comment by angelovopsan** [comment]
> ```yaml
> - "http://localhost:5510"
> ```
Hi, could you please share on which version you managed to block request with cors?

**Comment by alefcarlos** [comment]
@angelovopsan, yap ! I'm using Istio 1.2.4 ;)

**Comment by ten-lac** [comment]
I'm using Istio 1.7 and I have an issue where not all of the CORS headers are returned.  I've documented it in the [Istio forums](https://discuss.istio.io/t/istio-1-7-cors-policy-not-fully-working/8487).

When I apply the CORS policy, not all of the CORS headers are serialized back.  I only get back the following headers.  I'm wondering if I'm doing anything wrong?  I do have a JWT policy using the `RequestAuthentication` definition also applied to the same gateway the virtual service below is applied to.

* `Access-Control-Allow-Origin`
* `Access-Control-Allow-Credentials`

I'm expecting as expected in this [CorsPolicy document](https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy)
* `Access-Control-Allow-Methods`
* `Access-Control-Allow-Headers`
* `Access-Control-Max-Age`
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ingestion
  name: http-bobber-2-public
spec:
  hosts:
    - '*'
  gateways:
    - alb-system/default-istio-gateway
  http:
    - name: http-bobber-2-default-public-route
      match:
        - uri:
            prefix: /ingestion/http-bobber-2/
      rewrite:
        uri: /
      route:
        - destination:
            host: http-bobber-2.ingestion.svc.cluster.local
      corsPolicy:
        allowOrigins:
          - exact: "*"
        allowMethods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS
        allowCredentials: false
        allowHeaders:
          - authorization
        maxAge: "24h"
```

**Comment by Kampe** [comment]
See the same issues with 1.8

**Comment by maxdebayser** [comment]
What is the rationale behind the corsPolicy setting? It appears to me that you can achieve the same thing without weird behaviors by using the headers setting like this:
```
    headers:
      response:
        set:
          access-control-allow-credentials: "true"
          access-control-allow-headers: Content-Type, Authorization
          access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
          access-control-allow-origin: foo.com
          access-control-max-age: "86400"
```
Am I missing something?

**Comment by maxdebayser** [comment]
Oh, I think I found the explanation in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
```
<origin>
Specifies an origin. Only a single origin can be specified. If the server supports clients from multiple origins, it must return the origin for the specific client making the request.
```
So perhaps the best way to deal with these missing headers issue is to combine the `corsPolicy` and the `headers` setting of the `VirtualService` crd.

**Comment by maxdebayser** [comment]
Like @ten-lac , I've found that istio only returns the Access-Control-Allow-Origin and Access-Control-Allow-Credentials headers. Furthermore, if the back-end response already contains these headers, they are not overwritten with the values specified in `corsPolicy`. So for me the solution is to add this to the endpoint configuration:

```
    headers:
      response:
        remove:
        - access-control-allow-origin
        - access-control-allow-credentials
        set:
          access-control-allow-headers: Content-Type, Authorization
          access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
          access-control-max-age: "86400"
```

**Comment by sohahm** [comment]
You could use wildcard to accept all headers. The following example is what working for me.
`allowHeaders` accepts `"*"` but for `allowOrigins`, I had to use `regex: ".*"`
`allowMethods` does not accept wildcard.


```
allowHeaders:
- "*"
allowOrigins:
- regex: ".*"
allowMethods:
- GET
- POST
- PUT
- OPTIONS
```

**Comment by artyom-p** [comment]
Still an issue on 1.18. Adding CORS headers manually in endpoint configurations seems more like a workaround, not a real solution. There is a dedicated CORS section in VS and it's not working as it should...

**Comment by clarkmcc** [comment]
Also having the same issue. I was only able to get the headers to appear by doing this. I read through 10+ issues and stack overflow posts. Most of the authoritative responses were "CORS is a browser feature so don't expect it to work with cURL", however, **I can't even get the headers to appear using the VS CORS policy configuration**, much less get the browser to work. This is frustratingly difficult to get right.
```yaml
headers:
  response:
    remove:
      - 'Access-Control-Allow-Origin'
      - 'Access-Control-Allow-Methods'
      - 'Access-Control-Allow-Headers'
      - 'Access-Control-Allow-Credentials'
    set:
      Access-Control-Allow-Origin: 'https://app.dev.printtrackerpro.com/'
      Access-Control-Allow-Methods: 'GET, POST, PUT, DELETE, PATCH, OPTIONS'
      Access-Control-Allow-Headers: 'Origin, X-Requested-With, Content-Type, Accept, Authorization, X-Auth-Token'
      Access-Control-Allow-Credentials: 'true'
```
