### ISSUE TITLE
Where is the rule log?

### ISSUE THREAD

**Issue by dotw** [istio/istio#9811]
How to view the rule log? e.g: I want to know the result of evaluating value of ```destination.labels["app"]```
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkversion
spec:
  match: destination.labels["app"] == "ratings"
  actions:
  - handler: whitelist.listchecker
    instances:
    - appversion.listentry
```
