### ISSUE TITLE
Pod cannot reach a service in another cluster through mcgateway, HTTP 503 error

### ISSUE THREAD

**Issue by offzale** [istio/istio#9823]
**Describe the bug**

I have a service in clusterB, a dummy http server, and when I try to access from a pod in clusterA I get the error `upstream connect error or disconnect/reset before headers`. When I look into the sidecar logs of the pod in clusterA I find this:
```
[2018-11-08T14:21:02.721Z] "GET /HTTP/1.1" 503 UC 0 57 2 - "-" "curl/7.61.0" "1d780586-03d5-9bdf-b2be-37a0d017f0e5" "liveness.testing.svc.cluster.local" "ELB-IP-assigned-to-mcgateway-service-clusterB:15443" outbound|80||liveness.testing.svc.cluster.local - service-ip-on-clusterA:80 192.168.54.102:37374 -
```

I got nothing on the mcgateway of the clusterB though. Where I am getting this error from?

**Expected behavior**
I get a response from the service in clusterB accessing through the mcgateway on that same cluster.

**Steps to reproduce the bug**
Install these resources in clusterA:
```
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: liveness
  namespace: testing
  labels:
    app: liveness
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: liveness
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: remote-endpoint-for-liveness
spec:
  hosts:
  - liveness.testing.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: <Amazon-ELB-IP>
    ports:
      http: 15443
---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    istio-injection: enabled
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curl
  namespace: development
  labels:
    app: curl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: byrnedo/alpine-curl
        command: ["tail", "-f", "/dev/null"]
```

Install these other resources on clusterB:
```
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: liveness
  namespace: testing
  labels:
    app: liveness
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: liveness
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: liveness
  namespace: testing
  labels:
    app: liveness
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
      - name: liveness
        image: jasonrm/dummy-server
        args:
        - -port=80
        ports:
        - containerPort: 80
          name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: liveness-gateway
  namespace: testing
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: liveness
  namespace: testing
spec:
  gateways:
  - liveness-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: liveness
        port:
          number: 80
```

Run on clusterA:
`kubectl exec -n development <CURL-deployment-POD> curl liveness.testing.svc.cluster.local`

**Version on both clusters**
Kubernetes 1.11
Istio 1.1.0-snapshot2

**Installation**
Using helm charts, adding the secret for Citadel with the intermediates CA issued by the same root CA, with the following values:
global.mtls.enabled: true
global.multiCluster.connectUsingGateway: true
gateways.istio-mcgateway.enabled: true
security.selfSigned: false

**Environment**
Amazon through GiantSwarm
