### ISSUE TITLE
Egress issue with SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by arief-hidayat** [istio/istio#9844]
**Describe the bug**
I have deployment which injected with istio-proxy (it works if there's no istio-proxy).
The container needs to talk to external URL (oath server). So, I added the following serviceEntry.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: spacy-service-entry
  namespace: spacy
spec:
  hosts:
  - a-uaa-instance.authentication.sap.hana.ondemand.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
```
However, it failed with the following error
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='a-uaa-instance.authentication.sap.hana.ondemand.com', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)'),))
```
I tried couple of variations such as using TCP protocol, setting the resolution, adding destinationRule, etc. But I got the same error.

**Expected behavior**
It should be able to call the the external URL

**Steps to reproduce the bug**
* create deployment which has logic to call external URL
* istio-proxy is injected automatically since we configure the annotation to auto inject
* add the above serviceEntry

**Version**
kubernetes 1.10.8
istio 1.0.1

**Installation**
Through helm.

**Environment**
Kubernetes on top of AWS

**Cluster state**
Might contains confidential information (so I skip this)
