### ISSUE TITLE
corsPolicy not working 

### ISSUE THREAD

**Issue by ethonchen** [istio/istio#9878]
**Describe the bug**
i send a cors request , but it's not working.

**Expected behavior**
cors request work fine.

**Steps to reproduce the bug**
1. add corsPolicy in VirtualService like https://istio.io/docs/reference/config/istio.networking.v1alpha3/ 
as fllowes 
```
    corsPolicy:
      allowOrigin:
      - http://localhost:63342
      allowMethods:
      - POST
      - GET
      - OPTIONS
      allowCredentials: false
      allowHeaders:
      - "*"
      exposeHeaders:
      - "*"
      maxAge: "3600s"

```
2、 from localhost call service 

2.1 、 I found the options work ok .
2.2、 but the real POST return 403.

**Version**
kubectl version = 1.11.2
istioctl version = 1.0.2
**Installation**
from helm
**Environment**
centos 7
