### ISSUE TITLE
unable to unmarshal: unknown field "validDuration" in config.Params_Override

### ISSUE THREAD

**Issue by dotw** [istio/istio#9894]
I can't define a specific validDuration for overrides in 1.0.3? any changes?
```
apiVersion: "config.istio.io/v1alpha2"
kind: redisquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 5000
    validDuration: 10s
    bucketDuration: 9s
    rateLimitAlgorithm: ROLLING_WINDOW
    # The first matching override is applied.
    # A requestcount instance is checked against override dimensions.
    overrides:
    # The following override applies to 'ratings' when
    # the source is 'reviews'.
    - dimensions:
        destination: ratings
        source: reviews
      validDuration: 60s
      maxAmount: 1
    # The following override applies to 'ratings' regardless
    # of the source.
    - dimensions:
        destination: ratings
      maxAmount: 10
      validDuration: 120s
  redisServerUrl: "redis-release-master.istio-system.svc.cluster.local:6379"
  connectionPoolSize: 10
```
