### ISSUE TITLE
Egress rule with two ssl connection does not work

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#9897]
**Describe the bug**
I have one guestbook application deployed which will connect to IBM waston tone service. Since we need to use our API key to get the access token first, and then use the token to request a tone for a given word, So we need two ssl connection here:

 - iam.bluemix.net  : to get access token for a given api key
  - gateway-syd.watsonplatform.net : to get tone back using the access token

I am using the latest guestbook image as in https://github.com/IBM/guestbook.git
And my service entry is like below:
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: watson-tone-analyzer
spec:
  hosts:
  - iam.bluemix.net
  - gateway-syd.watsonplatform.net
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: watson-tone-analyzer
spec:
  hosts:
  - iam.bluemix.net
  - gateway-syd.watsonplatform.net
  tls:
  - match:
    - port: 443
      sni_hosts:
      - iam.bluemix.net
    route:
    - destination:
        host: iam.bluemix.net
        port:
          number: 443
      weight: 100
  tls:
  - match:
    - port: 443
      sni_hosts:
      - gateway-syd.watsonplatform.net
    route:
    - destination:
        host: gateway-syd.watsonplatform.net
        port:
          number: 443
      weight: 100

**Expected behavior**
THe tone  should return back and the

**Steps to reproduce the bug**

**Version**
istio 1.0.3
**Installation**
depoy guest book, redius, tone analyzer according to istio101

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**

Error message:
[2018-11-11 03:19:46,350] [140324525283072] [app : 97] [INFO] api key is there.
[2018-11-11 03:19:46,351] [140324525283072] [app : 123] [DEBUG] calling identity token method : apikey=GIR0EVAgJZVJigCNOwGOZlZKLQNR2AH3ayfbsoufRFWr&grant_type=urn%3Aibm%3Aparams%3Aoauth%3Agrant-type%3Aapikey
[2018-11-11 03:19:46,367] [140324525283072] [app : 202] [DEBUG] SSL connection failed: HTTPSConnectionPool(host=‘iam.bluemix.net’, port=443): Max retries exceeded with url: /identity/token?apikey=GIR0EVAgJZVJigCNOwGOZlZKLQNR2AH3ayfbsoufRFWr&grant_type=urn%3Aibm%3Aparams%3Aoauth%3Agrant-type%3Aapikey (Caused by SSLError(SSLError(“bad handshake: SysCallError(104, ‘ECONNRESET’)“,),))
[2018-11-11 03:19:46,367] [140324525283072] [app : 205] [INFO] Starting analyzer tone_analyzer_ep: https://gateway-syd.watsonplatform.net/tone-analyzer/api/v3/tone?version=2017-09-21&sentences=false

**Comment by vadimeisenbergibm** [comment]
@irisdingbj Can you try to define two separate service entries?

**Comment by louiscryan** [comment]
@vadimeisenbergibm can you update the target milestone for this issue

**Comment by vadimeisenbergibm** [comment]
@louiscryan done.

**Comment by vadimeisenbergibm** [comment]
Testing for www.google.com and edition.cnn.com:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
EOF
```

Access the external services:
1.  `kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -sL -o /dev/null -D - https://edition.cnn.com`
2. `kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -sL -o /dev/null -D - https://www.google.com`
```

Cleanup: `kubectl delete serviceentries/cnn serviceentries/google  virtualservices/cnn virtualservices/google`

**Comment by vadimeisenbergibm** [comment]
Testing for www.google.com and edition.cnn.com, single ServiceEntry, works.

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-cnn
spec:
  hosts:
  - www.google.com
  - edition.cnn.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
EOF
```

Access the external services:
1.  `kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -sL -o /dev/null -D - https://edition.cnn.com`
2. `kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -sL -o /dev/null -D - https://www.google.com`

Cleanup: 
`kubectl delete serviceentries/google-cnn  virtualservices/cnn virtualservices/google`

**Comment by linsun** [comment]
I believe Belinda Vennam also got this working by creating the extra service entry required by IAM.  @irisdingbj can you pls confirm this works for you now?

**Comment by linsun** [comment]
@irisdingbj @beemarie perhaps you can simplify it based on what @vadimeisenbergibm put in?

**Comment by vadimeisenbergibm** [comment]
Testing for www.google.com and edition.cnn.com, single ServiceEntry and single VirtualService, does not work.

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-cnn
spec:
  hosts:
  - www.google.com
  - edition.cnn.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-cnn
spec:
  hosts:
  - www.google.com
  - edition.cnn.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
  tls:
  - match:
    - port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
EOF
```

Access the external services:
1.  `kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -sL -o /dev/null -D - https://edition.cnn.com`
2. `kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -sL -o /dev/null -D - https://www.google.com`

Cleanup: 
`kubectl delete serviceentries/google-cnn  virtualservices/google-cnn`

**Comment by vadimeisenbergibm** [comment]
@irisdingbj @beemarie (cc @linsun) the problem is with double `tls:` section in the VirtualService, it seems the first `tls` section is ignored. To fix it, just remove the second `tls:` line in your virtual service, so the first `tls` section will have two `match` sections, for the two external services.

**Comment by beemarie** [comment]
@vadimeisenbergibm Thanks, the simplified version works fine.  I'll update the guestbook app.

**Comment by beemarie** [comment]
@irisdingbj can you confirm this is working for you?  The simplified version that is working for me can be found in this PR, but this looks similar (same?) as what you posted is not working:
https://github.com/IBM/guestbook/pull/59/files

**Comment by irisdingbj** [comment]
@beemarie Thanks, it works with your version. Thanks!
@vadimeisenbergibm Does it mean we can not have two tls entries in virtualService? The problem is there is no error message when applying the virutal service, so it is hard for user to know what is the problem..

**Comment by vadimeisenbergibm** [comment]
@irisdingbj You can have a single tls entry with multiple `match` sections. Note that it is just a YAML syntax - you cannot have the same field with the same name, as far as I understand. What happens is that Kubernetes takes into account the last field value, you can see it for Kubernetes objects as well.

Try this:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: sleep
  name: sleep2
  name: sleep3
  labels:
    app: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
EOF
```

The output will be:
`service "sleep3" created`. Kubernetes ignores the two previous values of the `name` field, without any warning. So in the case of double `tls` entries, they are probably are not preserved by Kubernetes in the CRD, so Istio probably has no chance to detect this problem.
