### ISSUE TITLE
CoreDNS with multicluster using gateway approach not resolving

### ISSUE THREAD

**Issue by offzale** [istio/istio#9902]
I am using the multicluster approach from this [commit](https://github.com/istio/istio/commit/ce90c45dfe8aaf46315aca1b31ddbc2d12a4d090), already merged on master branch. (docs [here](https://github.com/istio/istio.io/blob/c177b2499027e1421890fa44417ac1eaf0974c56/content/docs/setup/kubernetes/multicluster-install/gateways/index.md)) I already have a CoreDNS as the dns for the cluster. So I tried to:
- proxy the resolution of global entries from cluster's CoreDNS to the Istio one, which includes the plugin (would be the equivalent to the example of the docs using kube-dns)
- proxy the resolution of global entries from cluster's CoreDNS to the plugin directly modifying the Istio's CoreDNS service 
- deploy the plugin in the same pod as cluster's CoreDNS and use the same configuration as Istio's CoreDNS, adding the necessary permissions for the plugin

None of these scenarios work. The plugin reads the service entries, but CoreDNS is not able to resolve by proxying the request to the proxy.

This is the cluster's CoreDNS config in the third scenario:

```
    .:53 {
        errors
        health
        kubernetes cluster.local 172.31.0.0/16 192.168.0.0/16 {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        proxy global 127.0.0.1:8053 {
          protocol grpc insecure
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
```

Am I missing anyting? Did anyone get this new multicluster approach working? :)

**Comment by offzale** [comment]
Thank you for the quick answate @rshriram :) This is the service entry I am using.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: remote-endpoint-for-liveness
  namespace: default
spec:
  endpoints:
  - address: <AWS ELB IP>
     ports:
       http: 15443
  hosts:
  - liveness.testing.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
```
