### ISSUE TITLE
istio grpc gateway is not working

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#9919]
**Describe the bug**
istio grpc gateway is not working

**Expected behavior**
istio gateway can handle grpc service, **or is there any working sample?**

**Steps to reproduce the bug**
1. use the following single file along with the proto file to build a node server image
    https://github.com/grpc/grpc/blob/master/examples/node/dynamic_codegen/greeter_server.js
2. deploy it in k8s with a ClusterIP service
3. create a GRPC gateway and virtual service
4. visit the service via the gateway address, it's not working

**Version**
```
➜  ~ istioctl version
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
one key installation from the menu of an alibaba cloud k8s cluster

**Environment**
alibaba cloud

**Comment by hzxuzhonghu** [comment]
You should provide more, like configs and deployment yaml...

**Comment by xiaozhongliu** [comment]
> You should provide more, like configs and deployment yaml...

Thanks for ur reply, plz check all the yamls as below:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-k8s-demo-grpc
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: grpc
      protocol: GRPC
    hosts:
    - k8s-demo-grpc.dev.unicareer.com

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-demo-grpc
spec:
  gateways:
  - gateway-k8s-demo-grpc
  hosts:
  - k8s-demo-grpc.dev.unicareer.com
  http:
  - route:
    - destination:
        host: k8s-demo-grpc.dev.svc.cluster.local
        port:
          number: 80
          name: grpc

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-grpc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    app: k8s-demo-grpc

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo-grpc
spec:
  selector:
    matchLabels:
      app: k8s-demo-grpc
  revisionHistoryLimit: 3
  minReadySeconds: 5
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: k8s-demo-grpc
        version: v181113053936
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: k8s-demo-grpc
        image: registry.cn-hangzhou.aliyuncs.com/project-ns/k8s-demo-grpc:v181113053936
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: NODE_ENV
          value: dev
        - name: SERVER_ENV
          value: dev
        - name: EGG_SERVER_ENV
          value: dev
        - name: ENTRY_FILE
          value: ./server.js
        - name: TYPE
          value: bare
        - name: TZ
          value: Asia/Shanghai
        - name: LANG
          value: C.UTF-8
        - name: ENV_CONFIG
          valueFrom:
            configMapKeyRef:
              name: k8s-demo-grpc-config
              key: config.dev.js
        volumeMounts:
        - mountPath: /root/logs/k8s-demo-grpc
          name: log-volume
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/app/k8s-demo-grpc
      nodeSelector:
        usage: app
```

**Comment by xiaozhongliu** [comment]
@hzxuzhonghu Hi, could you help to check the configs provided?

**Comment by osswangxining** [comment]
You should specify the port name of K8S Service  k8s-demo-grpc by following the format:
name: grpc-suffix

**Comment by xiaozhongliu** [comment]
> You should specify the port name of K8S Service k8s-demo-grpc by following the format:
> name: grpc-suffix

@osswangxining Thanks Xining for ur reply. I don't understand ur suggestion, is there any doc on this?

**Comment by osswangxining** [comment]
> > You should specify the port name of K8S Service k8s-demo-grpc by following the format:
> > name: grpc-suffix
> 
> @osswangxining Thanks Xining for ur reply. I don't understand ur suggestion, is there any doc on this?

https://istio.io/help/faq/traffic-management/#naming-port-convention

**Comment by xiaozhongliu** [comment]
@osswangxining Thanks I changed all port names of the supplied four k8s/istio entities to "grpc-test", then it started to work for a go grpc sample, but it's still not working for nodejs.
Do you have any practice on nodejs grpc proxy?

**Comment by xiaozhongliu** [comment]
@osswangxining Also, do you have Dingding, QQ, or is there any discussion group? Let's play together. 让我们愉快地玩耍. My Dingding account is 18702188069.

**Comment by noisyox** [comment]
I am unable to access grpc application (listen 3000) using loadbalncer and can be accessed using Nodeport. Although if I setup any http application using http config it works without a sweat. Please help.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: grpc-test
      protocol: GRPC
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: frontend
        port:
          number: 3000
          name: grpc-test

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    name: grpc-test

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: prod
    spec:
      containers:
      - name: frontend
        image: ****:grpc
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "frontend-prod"
      imagePullSecrets:
        - name: gitlab-registry
```
