### ISSUE TITLE
Unable to initialise Galera MariaDB pods with sidecar injection

### ISSUE THREAD

**Issue by chunheisiu** [istio/istio#9923]
**Describe the bug**
When sidecars are injected into two Galera MariaDB pods, deployed as StatefulSets, both pods would fail to initialise and result in a CrashLoop. It seems that sidecar injection is interfering with the `gcomm://` protocol that the Galera cluster uses for synchronisation between two database instances. The current workaround is to disable sidecar injection on both pods, but doing so would lose the ability to monitor those pods.

**Expected behavior**
Istio sidecars injected into both MariaDB instances. Both MariaDB instances are able to initialise and synchronise with each other.

**Steps to reproduce the bug**
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true --set global.proxy.includeIPRanges="10.0.0.1/8" -x templates/sidecar-injector-configmap.yaml | kubectl apply -f -
```

**Version**
Istio 1.0.2, Kubernetes 1.12.1

**Installation**
Istio was installed via `helm`.

**Environment**
Ubuntu Server 18.04

**Comment by mabushey** [comment]
Galera is awesome. :) It's good that using Istio 1.0.2 as 1.0.3 and newer is broken for Stateful sets (istio-release-1.1-20181115-09-15 finally fixes the statefulset problem but introduces numerous new bugs).

Have you tried bringing up MariaDB without the automatic sidecar injection, and then after it's up enabling it?

maria-ns-no-sidecar.yml:
```
kind: Namespace
apiVersion: v1
metadata:
  name: maria 
  labels:
    env: prd
```

maria-ns-sidecar.ns
```
kind: Namespace
apiVersion: v1
metadata:
  name: maria 
  labels:
    env: prd
    istio-injection: enabled
```
