### ISSUE TITLE
grpc service not working with sidecar

### ISSUE THREAD

**Issue by mukundha** [istio/istio#9926]
**Describe the bug**
I have a grpc [helloworld](https://github.com/grpc/grpc-go/tree/master/examples/helloworld/greeter_server) service, when i deploy this in k8s, it works fine [able to access from a [client](https://github.com/grpc/grpc-go/tree/master/examples/helloworld/greeter_client)], but when i enable istio sidecar injection, client starts receiving errors - `upstream connect error or disconnect/reset before headers`

**Expected behavior**
grpc client was able to connect to the service, with or without the sidecar proxy

**Steps to reproduce the bug**
Start with a fresh install of Istio [no mTLS, no auto sidecar injection], use the following service
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellonode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellonode-app
    spec:
      containers:
      - name: server
        image: gcr.io/hipster-apim-demo/nodegreeter
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice-node
spec:
  type: LoadBalancer
  selector:
    app: hellonode-app
  ports:
  - port: 80
    targetPort: 50051
    protocol: TCP
    name: http
  - port: 443
    targetPort: 50051
    protocol: TCP
    name: grpc
---
```
Once created, you can use this client [here](https://github.com/grpc/grpc/blob/master/examples/node/dynamic_codegen/greeter_client.js) or [here](https://github.com/grpc/grpc-go/tree/master/examples/helloworld/greeter_client) to connect to the LB IP:443

Now,
```
kubectl label ns default istio-injection=enabled

kubectl delete pod <hellonode-pod>
```
Wait for the pod to restart, (now with sidecar), try the client, to see the error 

**Version**
GKE Version: 1.11.2-gke.15
Istio Versio: 1.0.3

**Installation**
by following the steps here https://istio.io/docs/setup/kubernetes/quick-start/

**Environment**
GKE

**Cluster state**

[istio-dump.tar.gz](https://github.com/istio/istio/files/2576961/istio-dump.tar.gz)

**Comment by mukundha** [comment]
This is the case only for few services

FWIW - it works for a different service 
```
apiVersion: v1
kind: Service
metadata:
  name: bookstore
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP    
    name: http
  - port: 443
    targetPort: 8000
    protocol: TCP
    name: grpc    
  selector:
    app: bookstore-app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookstore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
      - name: bookstore
        image: gcr.io/endpointsv2/python-grpc-bookstore-server:1
        ports:
          - containerPort: 8000
```

I am able to consistently reproduce this behavior for the hello service described above in the bug
