### ISSUE TITLE
Incorrect handling of ExternalName k8s services

### ISSUE THREAD

**Issue by imikushin** [istio/istio#9950]
When a request is made to a VirtualService backed by a Kubernetes service of type `ExternalName` (in my case, pointing to a cluster local name), the request doesn't get through and the reply is `503 Service Unavailable`. 

```
$ kubectl -n test get svc
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP                                           PORT(S)   AGE
nginx            ExternalName   <none>          nginx-internal.test.svc.cluster.local                 <none>    16m
nginx-internal   ClusterIP      10.71.251.104   <none>                                                80/TCP    2h
www              ExternalName   <none>          istio-ingressgateway.istio-system.svc.cluster.local   <none>    1h
```

VirtualService for host `www.test.svc.cluster.local` is backed by `nginx.test.svc.cluster.local` (http.route.destination.host field of the VirtualService object).

Hitting `http://www.test.svc.cluster.local/` from within the cluster gives `503 Service Unavailable`.

### Expected behavior
If the VirtualService is backed by `nginx-internal.test.svc.cluster.local`, the request gets through. It should work the same for `nginx.test.svc.cluster.local`. 

### Steps to reproduce the bug
Create test namespace and services as shown above. `nginx-internal` is a normal service backed by pods in the same namespace (via a label selector):
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal
  namespace: test
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
```

Create Gateway and VirtualService:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
spec:
  gateways:
  - test-gateway.test.svc.cluster.local
  - mesh
  hosts:
  - www.test.svc.cluster.local
  http:
  - route:
    - destination:
        host: nginx.test.svc.cluster.local
      weight: 100
```

Create a pod with bash and curl in istio-system. Exec into the pod and hit `http://www.test.svc.cluster.local/`. You'll get `503 Service Unavailable`.

### Workaround
1. Delete the backing ExternalName k8s service (`nginx`)
2. Create an Istio ServiceEntry:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: nginx-se
  namespace: test
spec:
  hosts:
  - nginx.test.svc.cluster.local
  endpoints:
  - address: nginx-internal.test.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
```

With the ServiceEntry in place of the ExternalName service, requests will get through. 

### Version
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.15", GitCommit:"3567055982b92fc8ae6935ec8f304ab867a4fe00", GitTreeState:"clean", BuildDate:"2018-11-03T00:01:41Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.2", GitRevision:"bd24a62648c07e24ca655c39727aeb0e4761919a", User:"root", Host:"6408abaf1dac", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean"}
```

## Environment
GKE, Container-Optimized OS

## Cluster state
[istio-dump.tar.gz](https://github.com/istio/istio/files/2578887/istio-dump.tar.gz)
